### ISSUE TITLE
Chain of too many subtasks throws recursion error

### ISSUE THREAD

**Issue by dnathe4th** [celery/celery#1078]
The following is my test case:

```
def text_users(userinfo, message, number):
    user_text_subtasks = []
    for user in userinfo:
        user_text_subtasks.append(text_individual_user.s(user, message, number))

    results = {
        "success": [],
        "error": [],
        "invalid_number": []
    }

    if len(user_text_subtasks):
        user_text_subtasks[0] = text_individual_user.s(results, userinfo[0], message, number)

    user_text_subtasks.append(text_callback.s(message))

    chain(*user_text_subtasks).apply_async()

@celery.task
def text_individual_user(result, user, message, number):
    # text them
    # return updated result
```

If the `userinfo` object I pass in is 75 items long (resulting in 76 subtasks in the chain because of the collection function at the end) the process executes fine. However  if `userinfo` is 100 items long (101 in the subtask chain) I get a recursion error.

The following is the stack trace:

```
Traceback (most recent call last):

File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/celery-3.0.12-py2.7.egg/celery/task/trace.py", line 224, in trace_task
  R = retval = fun(*args, **kwargs)
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/celery-3.0.12-py2.7.egg/celery/task/trace.py", line 406, in __protected_call__
  return self.run(*args, **kwargs)
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/example-0.1-py2.7-linux-x86_64.egg/example/views/text.py", line 220, in text_users
  chain(*driver_text_subtasks).apply_async()
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/celery-3.0.12-py2.7.egg/celery/canvas.py", line 150, in apply_async
  return self.type.apply_async(args, kwargs, **options)
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/celery-3.0.12-py2.7.egg/celery/app/builtins.py", line 245, in apply_async
  tasks[0].apply_async()
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/celery-3.0.12-py2.7.egg/celery/canvas.py", line 150, in apply_async
  return self.type.apply_async(args, kwargs, **options)
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/celery-3.0.12-py2.7.egg/celery/app/task.py", line 478, in apply_async
  **options)
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/celery-3.0.12-py2.7.egg/celery/app/amqp.py", line 229, in publish_task
  **kwargs)
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/kombu-2.4.8-py2.7.egg/kombu/messaging.py", line 150, in publish
  compression, headers)
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/kombu-2.4.8-py2.7.egg/kombu/messaging.py", line 201, in _prepare
  body) = encode(body, serializer=serializer)
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/kombu-2.4.8-py2.7.egg/kombu/serialization.py", line 162, in encode
  payload = encoder(data)
File "/home/example/api/master/23/env/local/lib/python2.7/site-packages/kombu-2.4.8-py2.7.egg/kombu/serialization.py", line 341, in dumps
  return dumper(obj, protocol=pickle_protocol)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by van4oza** [comment]
same issue on 4.2.1, any workaround besides `sys.setrecursionlimit`?
