### ISSUE TITLE
IOError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by frol** [celery/celery#1115]
Any ideas?

```
[: ERROR/MainProcess] Unrecoverable error: IOError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 200, in start
    self.namespace.start(self)
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 118, in start
    step.start(parent)
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 351, in start
    return self.obj.start()
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 191, in start
    ns.start(self)
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 118, in start
    step.start(parent)
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 663, in start
    c.loop(*c.loop_args())
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/worker/loops.py", line 87, in asynloop
    update_readers(on_poll_start())
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/worker/hub.py", line 173, in update_readers
    [self.add_reader(*x) for x in items(map)]
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/worker/hub.py", line 167, in add_reader
    return self.add(fd, callback, READ | ERR)
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/celery/worker/hub.py", line 158, in add
    self.poller.register(fd, flags)
  File "/home/webspm/webspm/env/local/lib/python2.7/site-packages/kombu/utils/eventio.py", line 85, in register
    self._epoll.register(fd, events)
IOError: [Errno 9] Bad file descriptor
```

I use Debian/squeeze x86_64, Python 2.7.3rc2, kombu from git 2.5 branch (2.5.2), celery from git master (3.1.0rc1). Redis as broker and as results backend.

**Comment by Fernandoize** [comment]
i have same issue 

software -> celery:4.2.1 (windowlicker) kombu:4.6.6 py:3.6.6
            billiard:3.5.0.5 py-amqp:2.5.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader

**Comment by auvipy** [comment]
you should try celery==4.4.0rc5 and then report.
