### ISSUE TITLE
ConnectionForced: None: (320) Too many heartbeats missed

### ISSUE THREAD

**Issue by andrewschoen** [celery/celery#1194]
After upgrading to celery 3.0.15 from 2.4.2 we started to receive the following traceback in all of our queue logs.  This happened in 3.0.13 as well.

```
ConnectionForced: None: (320) Too many heartbeats missed
[2013-02-11 11:04:18,100: ERROR/MainProcess] Error in timer: ConnectionForced(None, 'Too many heartbeats missed', None, '')
Traceback (most recent call last):
  File "/services/django/fe24/storyville/2013-01-29-17-58-56/lib/python2.6/site-packages/celery/utils/timer2.py", line 97, in apply_entry
    entry()
  File "/services/django/fe24/storyville/2013-01-29-17-58-56/lib/python2.6/site-packages/celery/utils/timer2.py", line 51, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/services/django/fe24/storyville/2013-01-29-17-58-56/lib/python2.6/site-packages/celery/utils/timer2.py", line 153, in _reschedules
    return fun(*args, **kwargs)
  File "/services/django/fe24/storyville/2013-01-29-17-58-56/lib/python2.6/site-packages/kombu/connection.py", line 264, in heartbeat_check
    return self.transport.heartbeat_check(self.connection, rate=rate)
  File "/services/django/fe24/storyville/2013-01-29-17-58-56/lib/python2.6/site-packages/kombu/transport/pyamqp.py", line 132, in heartbeat_check
    return connection.heartbeat_tick(rate=rate)
  File "/services/django/fe24/storyville/2013-01-29-17-58-56/lib/python2.6/site-packages/amqp/connection.py", line 849, in heartbeat_tick
    raise ConnectionForced('Too many heartbeats missed')
```

The workers still seemed to work correctly and the error didn't seem to have a pattern on how often it showed up in the logs.  We did receive the errors at a fairly steady rate though, minutes apart up to an hour.

Here is our setup:

```
celery==3.0.15
django-celery==3.0.11
celerymon==1.0.3
kombu==2.5.4
kombu-sqlalchemy==1.1.0
amqp==1.2.0
```

Adding the setting `BROKER_HEARTBEAT = 0` stopped this error from happening.

**Comment by er-satish** [comment]
@ask i'm getting same error with amqp version 5.0.9 even thought i haven't enabled the hearbeats explicitly. Does this mean in latest version again heartbeats is enabled by default.

**Comment by thedrow** [comment]
@ask no longer works on Celery. @er-satish You should file a new issue about this as a lot has changed since this ticket was opened.
