### ISSUE TITLE
Task of kind <> is not registered

### ISSUE THREAD

**Issue by Thhhza** [celery/celery#1263]
I get the following error message with a 3.0.17 worker running on Windows XP: "Task of kind <> is not registered, please make sure it's imported." The issue doesn't occur if the worker is running on Linux and it doesn't occur on versions prior to 3.0.17.

Output from trying to run the task:
[2013-03-28 10:40:31,875: WARNING/MainProcess] celery@ATS-TEST-OW1 ready.
[2013-03-28 10:40:31,921: INFO/MainProcess] consumer: Connected to amqp://guest@192.168.191.41:5672//.
[2013-03-28 10:40:56,280: INFO/MainProcess] Got task from broker: ats.tasks.test[e5bcd36a-890a-4fc4-8ebf-af5fa0378178]
[2013-03-28 10:40:56,312: ERROR/MainProcess] Task ats.tasks.test[e5bcd36a-890a-4fc4-8ebf-af5fa0378178] raised exception: Task of kind 'ats.tasks.test' is not registered, please make sure it's imported.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\billiard-2.7.3.23-py2.7-win32.egg\billiard\pool.py", line 293, in worker
    result = (True, func(_args, *_kwds))
  File "C:\Python27\lib\site-packages\celery-3.0.17-py2.7.egg\celery\task\trace.py", line 320, in _fast_trace_task
    return _tasks[task].__trace__(uuid, args, kwargs, request)[0]
  File "C:\Python27\lib\site-packages\celery-3.0.17-py2.7.egg\celery\app\registry.py", line 20, in **missing**
    raise self.NotRegistered(key)
NotRegistered: 'ats.tasks.test'

**Comment by Abhisek-** [comment]
I'm using `celery 4.1.1`.

But I'm not able to use class based task.

`tasks.py`
```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-

from flask import Flask
from celery import Task, Celery

from create_celery import make_celery

flask_app = Flask(__name__)
#flask_app.config_from_object('celeryobject')
flask_app.config.update(
    CELERY_BROKER_URL='redis://localhost:6379',
    CELERY_RESULT_BACKEND='redis://localhost:6379'
)

celery = make_celery(flask_app)

@celery.task
def add(x, y):
	time.sleep(3)
	return x + y

class MyTask(Task):
	ignore_result = True
	name = 'tasks.MyTask'

	def run(self, source, *args, **kwargs):
		self.source = source

		print(self.source)

mytask = MyTask()
celery.tasks.register(mytask)
mytask.delay(3)
```

`create_celery.py`
```python
from celery import Celery

def make_celery(app):
    celery = Celery(
        app.import_name,
        backend=app.config['CELERY_RESULT_BACKEND'],
        broker=app.config['CELERY_BROKER_URL']
    )
    #celery.conf.update(app.config)

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    return celery
```

`main.py`
```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-

import time

from tasks import add, flask_app, MyTask
#print(MyTask.something)

@flask_app.route('/')
def hello():
	res = add.delay(3, 4)
	print(res.get())
	return "Hello World 7"

@flask_app.route('/<name>')
def hello_name(name):
	mytask = MyTask()
	mytask.delay(3)
	return "Hello {}!".format(name)

if __name__ == '__main__':
	flask_app.run()
```


I'm getting the following error.
```

 -------------- celery@BLRKEC149197L v4.1.1 (latentcall)
---- **** -----
--- * ***  * -- Windows-8.1-6.3.9600-SP0 2018-05-30 17:56:55
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x38bcd7aeb8
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . tasks.MyTask
  . tasks.add

[2018-05-30 17:56:56,643: INFO/MainProcess] Connected to redis://localhost:6379//
[2018-05-30 17:56:57,041: INFO/SpawnPoolWorker-4] child process 14120 calling self.run()
[2018-05-30 17:56:57,044: INFO/SpawnPoolWorker-1] child process 6612 calling self.run()
[2018-05-30 17:56:57,051: INFO/SpawnPoolWorker-2] child process 6980 calling self.run()
[2018-05-30 17:56:57,059: INFO/SpawnPoolWorker-3] child process 328 calling self.run()
[2018-05-30 17:56:57,682: INFO/MainProcess] mingle: searching for neighbors
[2018-05-30 17:56:59,713: INFO/MainProcess] mingle: all alone
[2018-05-30 17:57:04,767: INFO/MainProcess] celery@BLRKEC149197L ready.
[2018-05-30 17:57:04,776: INFO/MainProcess] Received task: tasks.MyTask[14494776-1ca0-4a67-94f9-40dde2685831]
[2018-05-30 17:57:04,788: ERROR/MainProcess] Task handler raised error: Task of kind 'tasks.MyTask' never registered, please make sure it's imported.
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\billiard\pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "c:\program files\anaconda3\lib\site-packages\celery\app\trace.py", line 539, in _fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "c:\program files\anaconda3\lib\site-packages\celery\app\registry.py", line 21, in __missing__
    raise self.NotRegistered(key)
celery.exceptions.NotRegistered: 'tasks.MyTask'
[2018-05-30 17:57:04,790: INFO/MainProcess] Received task: tasks.MyTask[f143fdc9-fd22-485d-b749-629fc1995ecb]
[2018-05-30 17:57:04,806: INFO/MainProcess] Received task: tasks.MyTask[24b82eea-4b86-449a-b1f6-3370d37711ed]
[2018-05-30 17:57:04,808: ERROR/MainProcess] Task handler raised error: Task of kind 'tasks.MyTask' never registered, please make sure it's imported.
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\billiard\pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "c:\program files\anaconda3\lib\site-packages\celery\app\trace.py", line 539, in _fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "c:\program files\anaconda3\lib\site-packages\celery\app\registry.py", line 21, in __missing__
    raise self.NotRegistered(key)
celery.exceptions.NotRegistered: 'tasks.MyTask'
[2018-05-30 17:57:04,820: ERROR/MainProcess] Task handler raised error: Task of kind 'tasks.MyTask' never registered, please make sure it's imported.
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\billiard\pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "c:\program files\anaconda3\lib\site-packages\celery\app\trace.py", line 539, in _fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "c:\program files\anaconda3\lib\site-packages\celery\app\registry.py", line 21, in __missing__
    raise self.NotRegistered(key)
celery.exceptions.NotRegistered: 'tasks.MyTask'
[2018-05-30 17:57:04,821: INFO/MainProcess] Received task: tasks.MyTask[8f4e99e1-5df5-4390-b1a1-e1f44decbbc0]
[2018-05-30 17:57:04,835: ERROR/MainProcess] Task handler raised error: Task of kind 'tasks.MyTask' never registered, please make sure it's imported.
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\billiard\pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "c:\program files\anaconda3\lib\site-packages\celery\app\trace.py", line 539, in _fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "c:\program files\anaconda3\lib\site-packages\celery\app\registry.py", line 21, in __missing__
    raise self.NotRegistered(key)
celery.exceptions.NotRegistered: 'tasks.MyTask'
[2018-05-30 17:57:04,839: INFO/MainProcess] Received task: tasks.MyTask[4900e82d-39a3-4ebf-9e91-1abc87075355]
[2018-05-30 17:57:04,844: ERROR/MainProcess] Task handler raised error: Task of kind 'tasks.MyTask' never registered, please make sure it's imported.
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\billiard\pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "c:\program files\anaconda3\lib\site-packages\celery\app\trace.py", line 539, in _fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "c:\program files\anaconda3\lib\site-packages\celery\app\registry.py", line 21, in __missing__
    raise self.NotRegistered(key)
celery.exceptions.NotRegistered: 'tasks.MyTask'
```

Please help. You can point me to any documentation also, but I couldn't find any which resolved my issue.
