### ISSUE TITLE
Warnings when running worker with --loglevel=info

### ISSUE THREAD

**Issue by Xaroth** [celery/celery#1269]
This might partially partain to django-celery, as I'm using that, however, the error code seems to originate from celery itself, so I'm posting it here.

When running a test task, I get the following error:

```
[2013-03-29 15:08:49,098: WARNING/MainProcess] Traceback (most recent call last):
[2013-03-29 15:08:49,099: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 846, in emit
[2013-03-29 15:08:49,101: WARNING/MainProcess] msg = self.format(record)
[2013-03-29 15:08:49,102: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
[2013-03-29 15:08:49,102: WARNING/MainProcess] return fmt.format(record)
[2013-03-29 15:08:49,103: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/utils/log.py", line 111, in format
[2013-03-29 15:08:49,104: WARNING/MainProcess] return safe_str(logging.Formatter.format(self, record))
[2013-03-29 15:08:49,105: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
[2013-03-29 15:08:49,106: WARNING/MainProcess] record.message = record.getMessage()
[2013-03-29 15:08:49,107: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
[2013-03-29 15:08:49,107: WARNING/MainProcess] msg = msg % self.args
[2013-03-29 15:08:49,108: WARNING/MainProcess] TypeError: format requires a mapping
[2013-03-29 15:08:49,109: WARNING/MainProcess] Logged from file job.py, line 349
```

Judging by the code it seems some bad formatting, but I don't see the issue directly.

using: django-celery (git checkout from today)
using: celery (git checkout from today)
backend: amqp
result: cache

**Comment by krzyszt-github** [comment]
In my case there was monkey patching by kaa-base

kaa/base/logger.py:
```python
class Logger(logging.Logger):
    ...
    def makeRecord(self, name, level, fn, lno, msg, args, *_args, **_kwargs):
        ...
        msg = logger_str_convert(msg)
        args = tuple(logger_str_convert(x) for x in args)
```

**Comment by paulocheque** [comment]
I am facing the same issue in Heroku. It shows info logs but not warnings.

celery==5.3.1
django-celery-results==2.4.0
Django==4.2.1
Python 3.11
