### ISSUE TITLE
[3.1] Django fixup imports get triggered even when not using django

### ISSUE THREAD

**Issue by dnene** [celery/celery#1311]
I had to comment out the entire class and bypass django fixup here https://github.com/dnene/celery/commit/d3965e9e8997da9eb40adbfd67afafd21b1a2858 because of two issues.

a) return DjangoFixup(app).install() gets triggered even if I have no django installed or have made no changes to the default settings

b) the "from django import ..." statements also fail, again because django package has not been installed.

**Comment by stevepeak** [comment]
@dnene how did you end up solving this?

#### Setup
- `Python 2.7.8`
- `celery==3.1.18`
- not using `django`
  - `DJANGO_SETTINGS_MODULE`  is empty
` **not working** during `cx_Freeze`
- **working** when no using `cx_Freeze`


#### Traceback
```python
print "DJANGO_SETTINGS_MODULE:", os.getenv("DJANGO_SETTINGS_MODULE")
>>> DJANGO_SETTINGS_MODULE: None
....
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/2.7.8/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "enterprise.py", line 279, in <module>
    main()
  >> internal imports removed
  File "app/tasks/task.py", line 11, in <module>
    celery = Celery('reports', broker=broker)
  File "/home/ubuntu/.pyenv/versions/2.7.8/lib/python2.7/site-packages/celery/app/base.py", line 171, in __init__
    self._fixups = [symbol_by_name(fixup)(self) for fixup in self.fixups]
  File "/home/ubuntu/.pyenv/versions/2.7.8/lib/python2.7/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/ubuntu/.pyenv/versions/2.7.8/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named fixups.django
```

I've tried including `django` in the project and the same issue is presented. Thank you for your help!

**Comment by stevepeak** [comment]
I **believe** I fixed this by explicitly telling Celery there are no `fixups`. I'm still monitoring this.

```python
# fix issue by adding `fixups=[]`
Celery('app', broker=broker, fixups=[])
```
