### ISSUE TITLE
Broker password restrictions?

### ISSUE THREAD

**Issue by kylegibson-rldatix** [celery/celery#1553]
I am using celery 3.0.23. My broker backend is redis. I setup redis so requireauth was set to an extremely long / complex password, for example: `Ro3x<16%3xHO54l]1;ilx$Ae6+lR@%+0TQ6c~19XDS/q1AZ7mM`

Redis accepts and handles a password like this no problem.

`BROKER_URL`, however does not: (e.g. `BROKER_URL = "redis://:Ro3x<16%3xHO54l]1;ilx$Ae6+lR@%+0TQ6c~19XDS/q1AZ7mM@localhost:6379/0`

```
Traceback (most recent call last):
  File "env/bin/django-admin.py", line 8, in <module>
    management.execute_from_command_line()
  File "env/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "env/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "env/lib/python2.7/site-packages/djcelery/management/commands/celery.py", line 22, in run_from_argv
    ['%s %s' % (argv[0], argv[1])] + argv[2:],
  File "env/lib/python2.7/site-packages/celery/bin/celery.py", line 901, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "env/lib/python2.7/site-packages/celery/bin/base.py", line 187, in execute_from_commandline
    return self.handle_argv(prog_name, argv[1:])
  File "env/lib/python2.7/site-packages/celery/bin/celery.py", line 893, in handle_argv
    return self.execute(command, argv)
  File "env/lib/python2.7/site-packages/celery/bin/celery.py", line 868, in execute
    return cls(app=self.app).run_from_argv(self.prog_name, argv)
  File "env/lib/python2.7/site-packages/celery/bin/celery.py", line 148, in run_from_argv
    return self(*args, **options)
  File "env/lib/python2.7/site-packages/celery/bin/celery.py", line 118, in __call__
    ret = self.run(*args, **kwargs)
  File "env/lib/python2.7/site-packages/celery/bin/celery.py", line 220, in run
    return self.target.run(*args, **kwargs)
  File "env/lib/python2.7/site-packages/celery/bin/celeryd.py", line 153, in run
    return self.app.Worker(**kwargs).run()
  File "env/lib/python2.7/site-packages/celery/apps/worker.py", line 178, in run
    print(str(self.colored.cyan(' \n', self.startup_info())) +
  File "env/lib/python2.7/site-packages/celery/apps/worker.py", line 252, in startup_info
    'conninfo': self.app.connection().as_uri(),
  File "env/lib/python2.7/site-packages/celery/app/base.py", line 273, in connection
    **transport_options or {}))
  File "env/lib/python2.7/site-packages/kombu/connection.py", line 180, in __init__
    params.update(parse_url(hostname))
  File "env/lib/python2.7/site-packages/kombu/utils/url.py", line 34, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "env/lib/python2.7/site-packages/kombu/utils/url.py", line 12, in _parse_url
    scheme = urlparse(url).scheme
  File "/usr/lib/python2.7/urlparse.py", line 135, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 206, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

I had though that maybe, I could use `BROKER_PASSWORD` instead. Unfortunately, it seems that when `BROKER_URL` is set to anything, `BROKER_PASSWORD` is ignored. Worse yet, `BROKER_PASSWORD` is deprecated. In celery 4.0, the `BROKER_PASSWORD` setting will be removed. That means the only option for specifying the password will be via `BROKER_URL`. That really limits the complexity of passwords that are possible.

**Comment by anilpai** [comment]
> ValueError: Invalid IPv6 URL

I had the same issue while connecting to rabbitmq via celery. I replaced the password with only alphanumeric characters and now it works. This is due to urllib3 package's parse functionality.
