### ISSUE TITLE
chord_unlock loops endlessly after interrupted chord creation

### ISSUE THREAD

**Issue by rhettg** [celery/celery#1700]
Hit this scenario this morning when our celery box was under a lot of load. The machine got so slow, that one of our tasks that creates a chord was interrupted with a `SoftTimeLimitExceeded`

```
Stacktrace (most recent call last):

  File "celery/task/trace.py", line 228, in trace_task
    R = retval = fun(*args, **kwargs)
  File "newrelic/api/object_wrapper.py", line 220, in __call__
    self._nr_instance, args, kwargs)
  File "newrelic/api/background_task.py", line 88, in wrapper
    return wrapped(*args, **kwargs)
  File "celery/task/trace.py", line 415, in __protected_call__
    return self.run(*args, **kwargs)
  File "main/core/tasks.py", line 910, in <my task name>
    chord(courier_payouts)(callback)
  File "celery/canvas.py", line 470, in __call__
    return _chord.AsyncResult(callback_id, parent=_chord(**kwargs))
  File "celery/task/trace.py", line 416, in __protected_call__
    return orig(self, *args, **kwargs)
  File "newrelic/api/object_wrapper.py", line 220, in __call__
    self._nr_instance, args, kwargs)
  File "newrelic/api/background_task.py", line 74, in wrapper
    return wrapped(*args, **kwargs)
  File "celery/app/task.py", line 330, in __call__
    return self.run(*args, **kwargs)
  File "celery/app/builtins.py", line 336, in run
    return header(*partial_args, **{'task_id': group_id})
  File "celery/canvas.py", line 407, in __call__
    return type(*type.prepare(options, tasks, partial_args))
  File "celery/task/trace.py", line 416, in __protected_call__
    return orig(self, *args, **kwargs)
  File "newrelic/api/object_wrapper.py", line 220, in __call__
    self._nr_instance, args, kwargs)
  File "newrelic/api/background_task.py", line 74, in wrapper
    return wrapped(*args, **kwargs)
  File "celery/app/task.py", line 330, in __call__
    return self.run(*args, **kwargs)
  File "celery/app/builtins.py", line 178, in run
    add_to_parent=False) for stask in taskit]
  File "celery/canvas.py", line 194, in apply_async
    return self._apply_async(args, kwargs, **options)
  File "celery/app/task.py", line 473, in apply_async
    **options)
  File "celery/app/amqp.py", line 249, in publish_task
    **kwargs
  File "kombu/messaging.py", line 157, in publish
    compression, headers)
  File "kombu/messaging.py", line 233, in _prepare
    body) = encode(body, serializer=serializer)
  File "kombu/serialization.py", line 170, in encode
    payload = encoder(data)
  File "kombu/serialization.py", line 356, in dumps
    return dumper(obj, protocol=pickle_protocol)
  File "billiard/pool.py", line 227, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
```

Since it was interrupted, the subtasks didn't finish queuing, but the chord_unlock task did since that is done first, as you can see here: https://github.com/celery/celery/blob/3.0/celery/app/builtins.py#L336

This left the chord_unlock task endlessly looping, looking for a chord that would never complete.

We're running 3.0.19, but this looks like it would be an issue for newer versions as well.

**Comment by TauPan** [comment]
Am I right in assuming that the looping unlocks will eventually (after a long time) cause the message queue to run out of memory?

Because of this and the monitoring + cleanup hassle I suggest that a link to this issue should be added as a caveat to the documentation on chords for the time being.

**Comment by TauPan** [comment]
Oh, it appears I overlooked that this is (should be) fixed in 3.1.17... can anyone confirm that it is indeed fixed?

**Comment by rmihael** [comment]
We haven't seen these endless loops after updating to 3.1.17 in our deployment.

**Comment by TauPan** [comment]
Thanks... upgrading to 3.1.17, sorry for the noise ;)

**Comment by TauPan** [comment]
I still see looping chord_unlock_tasks as the only active tasks in the system with celery 3.1.17, after a worker crashed.

**Comment by rbu** [comment]
Please report a new bug if this is not reopened.

**Comment by TauPan** [comment]
I even see a chord_unlock task after a long running chord is completely finished.

Considering the amount of bugs that a search for 'chord' turns up ( https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+chord ) I'm abandoning chords for our application altogether. I had other issues I had to workaround before and I'm not optimistic for the near future, given the current lack of maintainers.

**Comment by bluebirdlboro** [comment]
Hi, I think I have run into this issue. My Celery version is 3.1.19. The system is windows 7. And I use git bash to enter commands...
What I was trying to do is execute these commands in django shell,
>>> from celery import chord
>>> chord((add.s(i,i) for i in xrange(10)), xsum.s())().get()

Then I use Ctrl-C to interupt it...then I got this... any help to kill these message would be great..thanks..


[2015-12-24 21:32:17,578: INFO/MainProcess] Received task: celery.chord_unlock[f
138c25a-f3fc-417a-9128-c38800eee992] eta:[2015-12-24 13:32:18.575000+00:00]
[2015-12-24 21:32:17,578: INFO/MainProcess] Task celery.chord_unlock[f138c25a-f3
fc-417a-9128-c38800eee992] retry: Retry in 1s
[2015-12-24 21:32:18,582: INFO/MainProcess] Received task: celery.chord_unlock[f
138c25a-f3fc-417a-9128-c38800eee992] eta:[2015-12-24 13:32:19.580000+00:00]
[2015-12-24 21:32:18,589: INFO/MainProcess] Task celery.chord_unlock[f138c25a-f3
fc-417a-9128-c38800eee992] retry: Retry in 1s
[2015-12-24 21:32:19,588: INFO/MainProcess] Received task: celery.chord_unlock[f
138c25a-f3fc-417a-9128-c38800eee992] eta:[2015-12-24 13:32:20.584000+00:00]
[2015-12-24 21:32:19,588: INFO/MainProcess] Task celery.chord_unlock[f138c25a-f3
fc-417a-9128-c38800eee992] retry: Retry in 1s
[2015-12-24 21:32:20,592: INFO/MainProcess] Received task: celery.chord_unlock[f
138c25a-f3fc-417a-9128-c38800eee992] eta:[2015-12-24 13:32:21.589000+00:00]
[2015-12-24 21:32:20,598: INFO/MainProcess] Task celery.chord_unlock[f138c25a-f3
fc-417a-9128-c38800eee992] retry: Retry in 1s
[2015-12-24 21:32:21,596: INFO/MainProcess] Task celery.chord_unlock[f138c25a-f3
fc-417a-9128-c38800eee992] retry: Retry in 1s
[2015-12-24 21:32:21,598: INFO/MainProcess] Received task: celery.chord_unlock[f
138c25a-f3fc-417a-9128-c38800eee992] eta:[2015-12-24 13:32:22.594000+00:00]
[2015-12-24 21:32:22,601: INFO/MainProcess] Received task: celery.chord_unlock[f
138c25a-f3fc-417a-9128-c38800eee992] eta:[2015-12-24 13:32:23.599000+00:00]
[2015-12-24 21:32:22,605: INFO/MainProcess] Task celery.chord_unlock[f138c25a-f3
fc-417a-9128-c38800eee992] retry: Retry in 1s

**Comment by ask** [comment]
You can revoke the out of control chord unlock task, like this:

    app.AsyncResult('f138c25a-f3fc-417a-9128-c38800eee992').revoke()

At least if you use a broker transport supporting remote control commands

**Comment by ask** [comment]
You should probably also set a max_retries for the chord unlock task:

    chord(...).apply_async(max_retries=300, interval=1)

Since the interval is 1 in this example it will retry for at most 5 minutes, but you can change the interval which defines how often the unlock chord wakes up to check if the chord completed.

**Comment by yellowcap** [comment]
I had a similar problem with rabbitmq when the results backend is not specified.

I was first trying to run celery without a results backend configuration. I got the same problem until l I activated amqp as results backend. Without specifying a results backend I get the infinite chord_unlock problem as well.

Maybe this is obvious to you, but it was not clear to me that groups nested in chains require a results backend.

**Comment by ask** [comment]
@yellowcap, Yeah, chords require a result backend with chord support, and `group(..) | task.s()` is automatically promoted to a chord!

I was under the impression that using the "disabled" backend would actually raise an exception in this case, maybe you were using the RPC:// backend?

The amqp:// result backend performs horribly, and will create one queue per task.  It's highly recommended you combine rabbitmq with redis:// for result backend if you have many or large chords.

**Comment by yellowcap** [comment]
@ask ok thanks for the tips, I will change to redis for the results backend. I thought I did not have the `CELERY_RESULT_BACKEND` setting in my settings.py file when I had the infinite loops. I'll see if I can reproduce the problem and report back if I think its worth having a closer look.

**Comment by jeremyll** [comment]
@yellowcap I had the same issue the last month. Made the redis results backend change a couple days ago after seeing the suggestion and haven't seen the issue since.

**Comment by alukach** [comment]
Just dropping my kludge fix regarding looping `celery.chord_unlock` tasks when using a DB `CELERY_RESULT_BACKEND`. As mentioned in #2725, the problem's damage can be at-least minimized by adding `max_retries` value to the task:

```python
from celery.signals import worker_init
@worker_init.connect
def limit_chord_unlock_tasks(worker, **kwargs):
    """
    Set max_retries for chord.unlock tasks to avoid infinitely looping
    tasks. (see celery/celery#1700 or celery/celery#2725)
    """
    task = worker.app.tasks['celery.chord_unlock']
    if task.max_retries is None:
        retries = getattr(worker.app.conf, 'CHORD_UNLOCK_MAX_RETRIES', None)
        task.max_retries = retries
```

And then add a `CHORD_UNLOCK_MAX_RETRIES` variable to my Celery configuration.  Not the best solution, but works as a failsafe.

**Comment by rajadain** [comment]
@alukach Your kludge seems better than mine, which was to shim the entire `add_unlock_chord_task` method https://github.com/WikiWatershed/model-my-watershed/pull/1265/commits/14af08a244d89ea9c8b9e5504bd2bf48721636bf. But this has been working for us well for over a year now.

**Comment by CharlesJQuarra** [comment]
I'm seeing a regression with version 4.2.2 ubuntu of this bug. The error mentions something about not being able to pickle `_pickle.load` objects:

```
[2019-03-31 12:45:16,617: ERROR/MainProcess] Error on stopping Pool: TypeError("can't pickle _thread.lock objects",)
Traceback (most recent call last):
  File "/root/miniconda/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/root/miniconda/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/root/miniconda/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/root/miniconda/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/root/miniconda/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/root/miniconda/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/root/miniconda/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/root/miniconda/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 306, in create_loop
    events = poll(poll_timeout)
  File "/root/miniconda/lib/python3.6/site-packages/kombu/utils/eventio.py", line 84, in poll
    return self._epoll.poll(timeout if timeout is not None else -1)
  File "/root/miniconda/lib/python3.6/site-packages/celery/apps/worker.py", line 284, in _handle_request
    raise exc(exitcode)
celery.exceptions.WorkerShutdown: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda/lib/python3.6/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/root/miniconda/lib/python3.6/site-packages/celery/bootsteps.py", line 373, in stop
    return self.obj.stop()
  File "/root/miniconda/lib/python3.6/site-packages/celery/concurrency/base.py", line 122, in stop
    self.on_stop()
  File "/root/miniconda/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 140, in on_stop
    self._pool.join()
  File "/root/miniconda/lib/python3.6/site-packages/billiard/pool.py", line 1578, in join
    stop_if_not_current(self._result_handler)
  File "/root/miniconda/lib/python3.6/site-packages/billiard/pool.py", line 143, in stop_if_not_current
    thread.stop(timeout)
  File "/root/miniconda/lib/python3.6/site-packages/billiard/pool.py", line 500, in stop
    self.on_stop_not_started()
  File "/root/miniconda/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 332, in on_stop_not_started
    check_timeouts()
  File "/root/miniconda/lib/python3.6/site-packages/billiard/pool.py", line 744, in handle_event
    next(self._it)
  File "/root/miniconda/lib/python3.6/site-packages/billiard/pool.py", line 697, in handle_timeouts
    cache = copy.deepcopy(self.cache)
  File "/root/miniconda/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/miniconda/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/miniconda/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/miniconda/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/miniconda/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects
```

**Comment by AleksNeStu** [comment]
**Just a quick workaround:** temporarily rename parameter `celery.chord_unlock` and restart celery.

Path e.g.: .venv/lib/python3.10/site-packages/celery/app/builtins.py

```
    @app.task(name='celery.chord_unlock_any_temp_name', max_retries=None, ...)
    def unlock_chord(self, group_id, callback, interval=None, ....):
```

**Comment by snailmail123** [comment]
> IIRC, I was able to stop the looping by using flower to cancel the specific task. I'm sure there is a command line way as well once you have the task id.

A decade later...after many hours of debugging, this was the only answer I could find which stopped that infinite loop...thank you

**Comment by auvipy** [comment]
> Just dropping my kludge fix regarding looping `celery.chord_unlock` tasks when using a DB `CELERY_RESULT_BACKEND`. As mentioned in [#2725](https://github.com/celery/celery/issues/2725), the problem's damage can be at-least minimized by adding `max_retries` value to the task:
> 
> from celery.signals import worker_init
> @worker_init.connect
> def limit_chord_unlock_tasks(sender, **kwargs):
>     """
>     Set max_retries for chord.unlock tasks to avoid infinitely looping
>     tasks. (see celery/celery#1700 or celery/celery#2725)
>     """
>     task = sender.app.tasks['celery.chord_unlock']
>     if task.max_retries is None:
>         retries = getattr(worker.app.conf, 'CHORD_UNLOCK_MAX_RETRIES', None)
>         task.max_retries = retries
> 
> And then add a `CHORD_UNLOCK_MAX_RETRIES` variable to my Celery configuration. Not the best solution, but works as a failsafe.

did you already contributed this to celery?
