### ISSUE TITLE
WorkerLostError('Worker exited prematurely: exitcode 155.',) with CELERYD_MAX_TASKS_PER_CHILD = 1

### ISSUE THREAD

**Issue by ionelmc** [celery/celery#1703]
Test code here: https://gist.github.com/ionelmc/7685690

Sample output:

```
Traceback (most recent call last):
  File "./app.py", line 42, in <module>
    assert results == ['ok' for i in range(10)], "BAD RESULTS: %r" % results
AssertionError: BAD RESULTS: ['ok', 'ok', 'ok', 'ok', 'ok', 'ok', WorkerLostError('Worker exited prematurely: exitcode 155.',), WorkerLostError('Worker exited prematurely: exitcode 155.',), 'ok', WorkerLostError('Worker exited prematurely: exitcode 155.',)]
wait 2 secs ...
Traceback (most recent call last):
  File "./app.py", line 42, in <module>
    assert results == ['ok' for i in range(10)], "BAD RESULTS: %r" % results
AssertionError: BAD RESULTS: ['ok', 'ok', 'ok', 'ok', 'ok', 'ok', WorkerLostError('Worker exited prematurely: exitcode 155.',), 'ok', 'ok', 'ok']
wait 2 secs ...
Traceback (most recent call last):
  File "./app.py", line 42, in <module>
    assert results == ['ok' for i in range(10)], "BAD RESULTS: %r" % results
AssertionError: BAD RESULTS: ['ok', 'ok', 'ok', 'ok', 'ok', 'ok', WorkerLostError('Worker exited prematurely: exitcode 155.',), 'ok', 'ok', 'ok']
wait 2 secs ...
Traceback (most recent call last):
  File "./app.py", line 42, in <module>
    assert results == ['ok' for i in range(10)], "BAD RESULTS: %r" % results
AssertionError: BAD RESULTS: ['ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', WorkerLostError('Worker exited prematurely: exitcode 155.',), WorkerLostError('Worker exited prematurely: exitcode 155.',), 'ok']
wait 2 secs ...
Traceback (most recent call last):
  File "./app.py", line 42, in <module>
    assert results == ['ok' for i in range(10)], "BAD RESULTS: %r" % results
AssertionError: BAD RESULTS: ['ok', 'ok', 'ok', 'ok', 'ok', 'ok', WorkerLostError('Worker exited prematurely: exitcode 155.',), WorkerLostError('Worker exited prematurely: exitcode 155.',), 'ok', 'ok']
wait 2 secs ...

...
```

**Comment by haiya512** [comment]
celery              4.2.1
python             2.7.12
the problem still exist
