### ISSUE TITLE
add_consumer/cancel_consumer control command accepted at worker startup will not response OK but will prevent consuming by worker

### ISSUE THREAD

**Issue by code-of-kpp** [celery/celery#1741]
```
[2013-12-14 14:33:44,472: DEBUG/MainProcess] pidbox received method add_consumer(queue=u'parts-gtd', exchange=None, routing_key=None, exchange_type=u'direct') [reply_to:{u'routing_key': u'6df39565-3a7a-3680-9c03-27d83ca141c4', u'exchange': u'reply.celery.pidbox'} ticket:7c28adaf-a3ac-4d3d-a5ad-f36a9d246a70]
[2013-12-14 14:33:44,472: ERROR/MainProcess] pidbox command error: AttributeError("'NoneType' object has no attribute 'consuming_from'",)
Traceback (most recent call last):
  File "/home/administrator/project/venv/local/lib/python2.7/site-packages/kombu/pidbox.py", line 101, in dispatch
    reply = handle(method, kwdict(arguments))
  File "/home/administrator/project/venv/local/lib/python2.7/site-packages/kombu/pidbox.py", line 119, in handle_call
    return self.handle(method, arguments)
  File "/home/administrator/project/venv/local/lib/python2.7/site-packages/kombu/pidbox.py", line 116, in handle
    return self.handlers[method](self.state, **arguments)
  File "/home/administrator/project/venv/local/lib/python2.7/site-packages/celery/worker/control.py", line 345, in add_consumer
    routing_key, **options)
  File "/home/administrator/project/venv/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 389, in add_task_queue
    if not cset.consuming_from(queue):
AttributeError: 'NoneType' object has no attribute 'consuming_from'
```

**Comment by RootLUG** [comment]
I have the same issue when I use bootstep which is hooked to "consumer". When `start` function in bootstep is executed I use consumer.add_task_queue to dynamically subscribe to the queues. I observed that there is rase condition that sometimes this fails because of the same traceback as posted in this issue. (I'm using gevent pool) Should I re-open this issue or report is as new one?

I would expect that the when start for consumer bootstep is fired that those internal would be already initialized
