### ISSUE TITLE
Deadlock when stopping a worker

### ISSUE THREAD

**Issue by brodie** [celery/celery#1770]
Occasionally when issuing a restart to celeryd_multi (using the generic init script), it'll hang while trying to stop one of the worker master processes:

```
> Waiting for 1 node -> 27865............................................................................................................................................................................
```

That'll sit there printing dots forever.

If I do `ps aufxww`, I can see the master process only has one child left. If I `strace` the child process, I see it's stuck in the middle of a `read()`:

```
$ strace -p 22089
Process 22089 attached - interrupt to quit
read(282,
```

If I strace the master process, I see it's looping and calling `select()` over and over (with no results):

```
$ strace -p 27865
Process 27865 attached - interrupt to quit
select(0, NULL, NULL, NULL, {0, 5265})  = 0 (Timeout)
fcntl(284, F_GETFL)                     = 0 (flags O_RDONLY)
fcntl(284, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
fcntl(284, F_GETFL)                     = 0x800 (flags O_RDONLY|O_NONBLOCK)
fcntl(284, F_SETFL, O_RDONLY)           = 0
select(285, [284], NULL, NULL, {0, 0})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 500000}) = 0 (Timeout)
fcntl(284, F_GETFL)                     = 0 (flags O_RDONLY)
fcntl(284, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
fcntl(284, F_GETFL)                     = 0x800 (flags O_RDONLY|O_NONBLOCK)
fcntl(284, F_SETFL, O_RDONLY)           = 0
select(285, [284], NULL, NULL, {0, 0})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 500000}) = 0 (Timeout)
fcntl(284, F_GETFL)                     = 0 (flags O_RDONLY)
fcntl(284, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
wait4(22089, 0x7fff3c4502c4, WNOHANG, NULL) = 0
fcntl(284, F_GETFL)                     = 0x800 (flags O_RDONLY|O_NONBLOCK)
fcntl(284, F_SETFL, O_RDONLY)           = 0
select(285, [284], NULL, NULL, {0, 0})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 500000}) = 0 (Timeout)
```

If I use lsof on the child process to see what the file descriptor 282 is, it says it's a FIFO.  I see the same FIFO in the master process (it has the same "node" according to lsof).

If I Ctrl+C the init script and run restart or stop again, it successfully kills the deadlocked master/child.

I should also note that I've seen a very similar deadlock when sending SIGHUP, but I'm having a hard time reproducing it, so I can't say for sure it's the same issue. The symptoms are similar though (a stuck child process doing nothing).

**Comment by adampl** [comment]
The same happens to me. I'm using Python 3.3, AMQP broker, Redis backend, and latest Python packages from pip (including Celery). I'll let you know if the `-Ofair` option solves the issue.

**Comment by adampl** [comment]
FYI: the `-Ofair` option prevents the deadlock in my case.

**Comment by ask** [comment]
Seems the original issue was fixed when enabling -Ofair.

Please open a separate issue if you have similar issue (not fixed by -Ofair)

**Comment by domenkozar** [comment]
We're still seeing deadlocks with `-Ofair`. We have 4 workers.

Example traces from two threads on a worker:

frame `
```
#0  0x00007fa375fae25d in read () from /lib64/libpthread.so.0
#1  0x00007fa36357b566 in read (__nbytes=4, __buf=0x7fff1f0859b4, __fd=17) at /usr/include/bits/unistd.h:44
#2  _Billiard_conn_recvall (h=17, buffer=buffer@entry=0x7fff1f0859b4 "", length=length@entry=4) at Modules/_billiard/socket_connection.c:76
#3  0x00007fa36357b93d in Billiard_conn_recv_string (
    buffer=buffer@entry=0x53af110 "\200\002K\002(My\037Nccelery.app.trace\n_fast_trace_task\nq\001(U\036feeds.transformers.rss_atom.byq\002U$cfefb0bb-399c-423e-9032-add27dabd6dfq\003}cfeedparser\nFeedParserDict\nq\004)\201q\005(U\016summary_detailq\006h\004)\201q\a(U\004baseq\bX", buflength=buflength@entry=131072, newbuffer=newbuffer@entry=0x7fff1f085a10, maxlength=maxlength@entry=9223372036854775807, conn=0x53af0f0) at Modules/_billiard/socket_connection.c:149
#4  0x00007fa36357ba6c in Billiard_connection_recv_payload (self=0x53af0f0) at Modules/_billiard/connection.h:424
#5  0x00007fa37629c9b0 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#6  0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#7  0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#8  0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#9  0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#10 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#11 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#12 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#13 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#14 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#15 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#16 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#17 0x00007fa37622b088 in function_call () from /lib64/libpython2.7.so.1.0
#18 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#19 0x00007fa376215075 in instancemethod_call () from /lib64/libpython2.7.so.1.0
#20 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#21 0x00007fa37625d147 in slot_tp_init () from /lib64/libpython2.7.so.1.0
#22 0x00007fa37625be5f in type_call () from /lib64/libpython2.7.so.1.0
#23 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#24 0x00007fa37629a32c in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#25 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#26 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#27 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#28 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#29 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#30 0x00007fa37622b17d in function_call () from /lib64/libpython2.7.so.1.0
#31 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#32 0x00007fa3762993c7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#33 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#34 0x00007fa37622b17d in function_call () from /lib64/libpython2.7.so.1.0
#35 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#36 0x00007fa376215075 in instancemethod_call () from /lib64/libpython2.7.so.1.0
#37 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#38 0x00007fa37625d147 in slot_tp_init () from /lib64/libpython2.7.so.1.0
#39 0x00007fa37625be5f in type_call () from /lib64/libpython2.7.so.1.0
#40 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#41 0x00007fa3762993c7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#42 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#43 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#44 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#45 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#46 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#47 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#48 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#49 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#50 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#51 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#52 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#53 0x00007fa37622b17d in function_call () from /lib64/libpython2.7.so.1.0
#54 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#55 0x00007fa3762993c7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#56 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#57 0x00007fa37622b17d in function_call () from /lib64/libpython2.7.so.1.0
#58 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#59 0x00007fa376215075 in instancemethod_call () from /lib64/libpython2.7.so.1.0
#60 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#61 0x00007fa37625d4e7 in slot_tp_call () from /lib64/libpython2.7.so.1.0
#62 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#63 0x00007fa3762993c7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#64 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
```

frame 2

```
#0  0x00007fa375fae25d in read () from /lib64/libpthread.so.0
#1  0x00007fa36357b566 in read (__nbytes=4, __buf=0x7fff1f0859b4, __fd=17) at /usr/include/bits/unistd.h:44
#2  _Billiard_conn_recvall (h=17, buffer=buffer@entry=0x7fff1f0859b4 "", length=length@entry=4) at Modules/_billiard/socket_connection.c:76
#3  0x00007fa36357b93d in Billiard_conn_recv_string (
    buffer=buffer@entry=0x53af110 "\200\002K\002(My\037Nccelery.app.trace\n_fast_trace_task\nq\001(U\036feeds.transformers.rss_atom.byq\002U$cfefb0bb-399c-423e-9032-add27dabd6dfq\003}cfeedparser\nFeedParserDict\nq\004)\201q\005(U\016summary_detailq\006h\004)\201q\a(U\004baseq\bX", buflength=buflength@entry=131072, newbuffer=newbuffer@entry=0x7fff1f085a10, maxlength=maxlength@entry=9223372036854775807, conn=0x53af0f0) at Modules/_billiard/socket_connection.c:149
#4  0x00007fa36357ba6c in Billiard_connection_recv_payload (self=0x53af0f0) at Modules/_billiard/connection.h:424
#5  0x00007fa37629c9b0 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#6  0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#7  0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#8  0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#9  0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#10 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#11 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#12 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#13 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#14 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#15 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#16 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#17 0x00007fa37622b088 in function_call () from /lib64/libpython2.7.so.1.0
#18 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#19 0x00007fa376215075 in instancemethod_call () from /lib64/libpython2.7.so.1.0
#20 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#21 0x00007fa37625d147 in slot_tp_init () from /lib64/libpython2.7.so.1.0
#22 0x00007fa37625be5f in type_call () from /lib64/libpython2.7.so.1.0
#23 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#24 0x00007fa37629a32c in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#25 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#26 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#27 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#28 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#29 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#30 0x00007fa37622b17d in function_call () from /lib64/libpython2.7.so.1.0
#31 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#32 0x00007fa3762993c7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#33 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#34 0x00007fa37622b17d in function_call () from /lib64/libpython2.7.so.1.0
#35 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#36 0x00007fa376215075 in instancemethod_call () from /lib64/libpython2.7.so.1.0
#37 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#38 0x00007fa37625d147 in slot_tp_init () from /lib64/libpython2.7.so.1.0
#39 0x00007fa37625be5f in type_call () from /lib64/libpython2.7.so.1.0
#40 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#41 0x00007fa3762993c7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#42 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#43 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#44 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#45 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#46 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#47 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#48 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#49 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#50 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#51 0x00007fa37629c83f in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#52 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#53 0x00007fa37622b17d in function_call () from /lib64/libpython2.7.so.1.0
#54 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#55 0x00007fa3762993c7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#56 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#57 0x00007fa37622b17d in function_call () from /lib64/libpython2.7.so.1.0
#58 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#59 0x00007fa376215075 in instancemethod_call () from /lib64/libpython2.7.so.1.0
#60 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#61 0x00007fa37625d4e7 in slot_tp_call () from /lib64/libpython2.7.so.1.0
#62 0x00007fa376206073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#63 0x00007fa3762993c7 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#64 0x00007fa37629e18d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
```

**Comment by domenkozar** [comment]
All of the 4 workers hanged at the same time, this hints it's a problem in the protocol.

**Comment by domenkozar** [comment]
Looks similar to #2606
