### ISSUE TITLE
UnexpectedFrame exception after "Connection to broker lost"

### ISSUE THREAD

**Issue by fellowshipofone** [celery/celery#1779]
Hey, I am not sure if this is a duplicate or not, but I could not find this exact issue. I realize we are not running 3.1.7 so I will upgrade all machines to check

Running:
amqp==1.3.3
billiard==3.3.0.10
celery==3.1.6
eventlet==0.14.0
kombu==3.0.7

Getting the following issue:

``` bash
[2014-01-10 12:13:17,420: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 270, in start
    blueprint.start(self)
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 790, in start
    c.loop(*c.loop_args())
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/celery/worker/loops.py", line 99, in synloop
    connection.drain_events(timeout=2.0)
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/kombu/connection.py", line 279, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 90, in drain_events
    return connection.drain_events(**kwargs)
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/amqp/connection.py", line 282, in drain_events
    chanmap, None, timeout=timeout,
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/amqp/connection.py", line 345, in _wait_multiple
    channel, method_sig, args, content = read_timeout(timeout)
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/amqp/connection.py", line 316, in read_timeout
    return self.method_reader.read_method()
  File "/usr/local/virtualenvs/shapeup/local/lib/python2.7/site-packages/amqp/method_framing.py", line 195, in read_method
    raise m
UnexpectedFrame: Received 0x2d while expecting 0xce
```

**Comment by thedrow** [comment]
This could be related to #2066.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by HughWarrington** [comment]
Still an issue in Celery 4.3.0.

**Comment by HughWarrington** [comment]
Looking again, we have a very different stack trace. I think this is only related to Kombu, not Celery.

Sorry for the noise.

Here's the stack trace anyway, in case it's of interest:

```
UnexpectedFrame: Basic.publish: (505) UNEXPECTED_FRAME - expected content body, got non content body frame instead
  File "xxx.py", line 50, in send
    xxx
  File "xxx.py", line 98, in run
    xxx,
  File "xxx.py", line 106, in publish
    xxx,
  File "kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "kombu/connection.py", line 510, in _ensured
    return fun(*args, **kwargs)
  File "kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "amqp/channel.py", line 1789, in basic_publish_confirm
    self.wait([spec.Basic.Ack, spec.Basic.Nack], callback=confirm_handler)
  File "amqp/abstract_channel.py", line 80, in wait
    self.connection.drain_events(timeout=timeout)
  File "amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "amqp/connection.py", line 506, in blocking_read
    return self.on_inbound_frame(frame)
  File "amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "amqp/connection.py", line 510, in on_inbound_method
    method_sig, payload, content,
  File "amqp/abstract_channel.py", line 126, in dispatch_method
    listener(*args)
  File "amqp/connection.py", line 639, in _on_close
    (class_id, method_id), ConnectionError)
```

**Comment by auvipy** [comment]
can you also check celery master? with py-amqp master?

**Comment by auvipy** [comment]
can you test with celery==4.4.0

**Comment by auvipy** [comment]
> To my knowledge, we've only seen this error once or twice in about 2 million server hours, and I have no reliable repro steps. Also these are production servers so unfortunately I'm unable to test.

closing for now based on this scenario for now. but we will reopen it if this becomes more frequent. also https://github.com/celery/celery/pull/6416 might fix this, we will reopen it if it doesn;t.
