### ISSUE TITLE
StaleDataError: UPDATE statement on table 'celery_taskmeta' expected to update 1 row(s); 0 were matched.  

### ISSUE THREAD

**Issue by ionelmc** [celery/celery#1786]
I get this

```
Traceback (most recent call last):
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/celery/app/trace.py", line 262, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/celery/backends/base.py", line 223, in store_result
    request=request, **kwargs)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/celery/backends/database/__init__.py", line 47, in _inner
    return fun(*args, **kwargs)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/celery/backends/database/__init__.py", line 99, in _store_result
    task = session.query(Task).filter(Task.task_id == task_id).first()
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2321, in first
    ret = list(self[0:1])
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2188, in __getitem__
    return list(res)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 65, in instances
    fetch = cursor.fetchall()
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 773, in fetchall
    self.cursor, self.context)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1026, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 767, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 736, in _fetchall_impl
    self._non_result()
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 741, in _non_result
    "This result object does not return rows. "
ResourceClosedError: This result object does not return rows. It has been closed automatically.
```

And then this:

```
[2014-01-13 15:16:26,279] pid=35232/Worker-144  - WARNING  - py.warnings - /home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/celery/app/trace.py:343: RuntimeWarning: Exception raised outside body: StaleDataError("UPDATE statement on table 'celery_taskmeta' expected to update 1 row(s); 0 were matched.",):
Traceback (most recent call last):
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/celery/app/trace.py", line 262, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/celery/backends/base.py", line 223, in store_result
    request=request, **kwargs)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/celery/backends/database/__init__.py", line 47, in _inner
    return fun(*args, **kwargs)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/celery/backends/database/__init__.py", line 108, in _store_result
    session.commit()
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 370, in commit
    self._prepare_impl()
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 350, in _prepare_impl
    self.session.flush()
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1879, in flush
    self._flush(objects)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1997, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 57, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1961, in _flush
    flush_context.execute()
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 370, in execute
    rec.execute(self)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 523, in execute
    uow
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 59, in save_obj
    mapper, table, update)
  File "/home/ionel/projects/core/.ve/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 528, in _emit_update_statements
    (table.description, len(update), rows))
StaleDataError: UPDATE statement on table 'celery_taskmeta' expected to update 1 row(s); 0 were matched.
```

**Comment by Hellathor** [comment]
> 

我遇到这个问题是由于字段类型错误导致的，希望对您有帮助。
