### ISSUE TITLE
Error in timer: TypeError("unhashable type: 'list'",)

### ISSUE THREAD

**Issue by extesy** [celery/celery#1798]
After processing several thousand tasks, after about a day and a half in idle mode, celery dumped this exception:

```
[2014-01-15 19:34:07,386: ERROR/MainProcess] Error in timer: TypeError("unhashable type: 'list'",)
Traceback (most recent call last):
  File "D:\Projects\Web\stuff\backend\lib\site-packages\kombu\async\timer.py", line 166, in apply_entry
    entry()
  File "D:\Projects\Web\stuff\backend\lib\site-packages\kombu\async\timer.py", line 64, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "D:\Projects\Web\stuff\backend\lib\site-packages\kombu\async\timer.py", line 132, in _reschedules
    self.enter_after(next, tref, priority)
  File "D:\Projects\Web\stuff\backend\lib\site-packages\kombu\async\timer.py", line 158, in enter_after
    return self.enter_at(entry, time() + secs, priority)
  File "D:\Projects\Web\stuff\backend\lib\site-packages\kombu\async\timer.py", line 155, in enter_at
    return self._enter(eta, priority, entry)
  File "D:\Projects\Web\stuff\backend\lib\site-packages\kombu\async\timer.py", line 161, in _enter
    push(self._queue, scheduled(eta, priority, entry))
  File "D:\Projects\Web\stuff\backend\lib\site-packages\kombu\async\timer.py", line 88, in __eq__
    return hash(self) == hash(other)
  File "D:\Projects\Web\stuff\backend\lib\site-packages\kombu\async\timer.py", line 77, in __hash__
    return hash((self.fun, self.args))
TypeError: unhashable type: 'list'
```

I am on Windows 7, Python 3.3.3.

**Comment by rammanoj** [comment]
I got the same error on calling the delay function. May I know how to resolve this. Initially, it worked fine. But I am not sure why suddenly it started popping this error, whenever I call delay function !!
