### ISSUE TITLE
--autoreload doesn't work in Vagrant VM when modules live in a Shared Folder

### ISSUE THREAD

**Issue by donspaulding** [celery/celery#1880]
We run django/celery in Vagrant VMs for local development.  We see the following error repeatedly dumped into the log files on our Vagrant VMs, but not in production with the exact same codebase.  The message is repeated on the order of every 2-3 seconds.

    [2014-02-19 12:47:07,193: ERROR/MainProcess] Error in timer: TypeError("'NoneType' object has no attribute '__getitem__'",)
    Traceback (most recent call last):
      File "/var/projects/pcp/virtualenv/local/lib/python2.7/site-packages/kombu/async/hub.py", line 153, in fire_timers
        entry()
      File "/var/projects/pcp/virtualenv/local/lib/python2.7/site-packages/kombu/async/timer.py", line 64, in __call__
        return self.fun(*self.args, **self.kwargs)
      File "/var/projects/pcp/virtualenv/local/lib/python2.7/site-packages/kombu/async/timer.py", line 132, in _reschedules
        return fun(*args, **kwargs)
      File "/var/projects/pcp/virtualenv/local/lib/python2.7/site-packages/celery/worker/autoreload.py", line 113, in find_changes
        self.on_change(modified)
      File "/var/projects/pcp/virtualenv/local/lib/python2.7/site-packages/celery/worker/autoreload.py", line 90, in on_change
        return self._on_change(modified)
      File "/var/projects/pcp/virtualenv/local/lib/python2.7/site-packages/celery/worker/autoreload.py", line 291, in on_change
        modified = [f for f in files if self._maybe_modified(f)]
      File "/var/projects/pcp/virtualenv/local/lib/python2.7/site-packages/celery/worker/autoreload.py", line 285, in _maybe_modified
        if digest != self._hashes[f]:
    TypeError: 'NoneType' object has no attribute '__getitem__'

This is obviously deep within the celery codebase.  I'm not sure what circumstances would cause `self._hashes == None` perpetually.  The only thing I can think of is that we're sharing our project code via Vagrant/VirtualBox's Shared Folders functionality  (but none of the other python modules, they're installed in the VM's virtualenv).  We've seen this approach wreak havoc with os.stat() calls in other projects, so that's why I'm wondering if it's the culprit in this case as well.

I'm happy to answer any additional questions that would help narrow down the cause of this.

Thanks,
Don

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

--autoreload will be undocumented in 4.0
