### ISSUE TITLE
Celery worker crash

### ISSUE THREAD

**Issue by navinsylvester** [celery/celery#1901]
Celery worker on windows works fine for sometime and then it errors out. Currently running celery - 3.1.9, kombu - 3.0.12 and the backend is redis. here is the crash details:  

```
[2014-03-03 16:27:24,413: INFO/MainProcess] Connected to redis://@redis-master:6379/0
[2014-03-03 16:27:25,615: INFO/MainProcess] mingle: searching for neighbors
[2014-03-03 16:27:32,476: INFO/MainProcess] mingle: sync with 1 nodes
[2014-03-03 16:27:32,490: INFO/MainProcess] mingle: sync complete
[2014-03-03 16:27:37,038: ERROR/MainProcess] Unrecoverable error: KeyError(u"Message for queue '052a1a32-1985-32a2-909c-642cfcb5bfde.reply.celery.pidbox' without consumers: {u'body': u'eyJjZWxlcnlAZ20tczQtbWdtdC11cGxvYWQtMDEiOiB7InJldm9rZWQiOiB7InJlbmRlcmZhcm0tN2NhMTE3YzktYjRiMy00NjVjLWFlNWMtNWIyNTQ2YzBhNmY4LTAiOiAxMzkzODY0MDQ3LjU2MjU0LCAicmVuZGVyZmFybS03Y2ExMTdjOS1iNGIzLTQ2NWMtYWU1Yy01YjI1NDZjMGE2ZjgtMSI6IDEzOTM4NjQwNDcuNTYyNTQ2LCAicmVuZGVyZmFybS03Y2ExMTdjOS1iNGIzLTQ2NWMtYWU1Yy01YjI1NDZjMGE2ZjgtMiI6IDEzOTM4NjQwNDcuNTYyNTQ5LCAicmVuZGVyZmFybS03Y2ExMTdjOS1iNGIzLTQ2NWMtYWU1Yy01YjI1NDZjMGE2ZjgtMyI6IDEzOTM4NjQwNDcuNTYyNTUxLCAicmVuZGVyZmFybS03Y2ExMTdjOS1iNGIzLTQ2NWMtYWU1Yy01YjI1NDZjMGE2ZjgtNCI6IDEzOTM4NjQwNDcuNTYyNTU0LCAicmVuZGVyZmFybS02YTY3MTM1MC04Y2QxLTQ1ZTMtYmZlNi0yZTljN2QxZTg4MWQiOiAxMzkzODY0MDQ3LjU2MjU2MSwgInJlbmRlcmZhcm0tN2NhMTE3YzktYjRiMy00NjVjLWFlNWMtNWIyNTQ2YzBhNmY4IjogMTM5Mzg2NDA0Ny41NjI1NTgsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC0xIjogMTM5Mzg2NDA0Ny41NjI1NTYsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC0wIjogMTM5Mzg2NDA0Ny41NjI1NjMsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC0zIjogMTM5Mzg2NDA0Ny41NjI1NjUsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC0yIjogMTM5Mzg2NDA0Ny41NjI1NjgsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC00IjogMTM5Mzg2NDA0Ny41NjI1N30sICJjbG9jayI6IDM3Mzk2fX0=', u'headers': {u'ticket': u'c274da69-a784-46de-96ac-d878b09978b5', u'clock': 961}, u'content-type': u'application/json', u'properties': {u'body_encoding': u'base64', u'delivery_info': {u'priority': 0, u'routing_key': u'052a1a32-1985-32a2-909c-642cfcb5bfde', u'exchange': u'reply.celery.pidbox'}, u'delivery_mode': 1, u'delivery_tag': 6556}, u'content-encoding': u'utf-8'}",)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\celery\worker\__init__.py", line 206, in start
    self.blueprint.start(self)
  File "c:\python27\lib\site-packages\celery\bootsteps.py", line 123, in start
    step.start(parent)
  File "c:\python27\lib\site-packages\celery\bootsteps.py", line 373, in start
    return self.obj.start()
  File "c:\python27\lib\site-packages\celery\worker\consumer.py", line 278, in start
    blueprint.start(self)
  File "c:\python27\lib\site-packages\celery\bootsteps.py", line 123, in start
    step.start(parent)
  File "c:\python27\lib\site-packages\celery\worker\consumer.py", line 796, in start
    c.loop(*c.loop_args())
  File "c:\python27\lib\site-packages\celery\worker\loops.py", line 99, in synloop
    connection.drain_events(timeout=2.0)
  File "c:\python27\lib\site-packages\kombu\connection.py", line 279, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "c:\python27\lib\site-packages\kombu\transport\virtual\__init__.py", line 842, in drain_events
    queue, message))
KeyError: u"Message for queue '052a1a32-1985-32a2-909c-642cfcb5bfde.reply.celery.pidbox' without consumers: {u'body': u'eyJjZWxlcnlAZ20tczQtbWdtdC11cGxvYWQtMDEiOiB7InJldm9rZWQiOiB7InJlbmRlcmZhcm0tN2NhMTE3YzktYjRiMy00NjVjLWFlNWMtNWIyNTQ2YzBhNmY4LTAiOiAxMzkzODY0MDQ3LjU2MjU0LCAicmVuZGVyZmFybS03Y2ExMTdjOS1iNGIzLTQ2NWMtYWU1Yy01YjI1NDZjMGE2ZjgtMSI6IDEzOTM4NjQwNDcuNTYyNTQ2LCAicmVuZGVyZmFybS03Y2ExMTdjOS1iNGIzLTQ2NWMtYWU1Yy01YjI1NDZjMGE2ZjgtMiI6IDEzOTM4NjQwNDcuNTYyNTQ5LCAicmVuZGVyZmFybS03Y2ExMTdjOS1iNGIzLTQ2NWMtYWU1Yy01YjI1NDZjMGE2ZjgtMyI6IDEzOTM4NjQwNDcuNTYyNTUxLCAicmVuZGVyZmFybS03Y2ExMTdjOS1iNGIzLTQ2NWMtYWU1Yy01YjI1NDZjMGE2ZjgtNCI6IDEzOTM4NjQwNDcuNTYyNTU0LCAicmVuZGVyZmFybS02YTY3MTM1MC04Y2QxLTQ1ZTMtYmZlNi0yZTljN2QxZTg4MWQiOiAxMzkzODY0MDQ3LjU2MjU2MSwgInJlbmRlcmZhcm0tN2NhMTE3YzktYjRiMy00NjVjLWFlNWMtNWIyNTQ2YzBhNmY4IjogMTM5Mzg2NDA0Ny41NjI1NTgsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC0xIjogMTM5Mzg2NDA0Ny41NjI1NTYsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC0wIjogMTM5Mzg2NDA0Ny41NjI1NjMsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC0zIjogMTM5Mzg2NDA0Ny41NjI1NjUsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC0yIjogMTM5Mzg2NDA0Ny41NjI1NjgsICJyZW5kZXJmYXJtLTZhNjcxMzUwLThjZDEtNDVlMy1iZmU2LTJlOWM3ZDFlODgxZC00IjogMTM5Mzg2NDA0Ny41NjI1N30sICJjbG9jayI6IDM3Mzk2fX0=', u'headers': {u'ticket': u'c274da69-a784-46de-96ac-d878b09978b5', u'clock': 961}, u'content-type': u'application/json', u'properties': {u'body_encoding': u'base64', u'delivery_info': {u'priority': 0, u'routing_key': u'052a1a32-1985-32a2-909c-642cfcb5bfde', u'exchange': u'reply.celery.pidbox'}, u'delivery_mode': 1, u'delivery_tag': 6556}, u'content-encoding': u'utf-8'}"
```

**Comment by hardikjshah** [comment]
Which versions has this issue fixed ?

**Comment by obforfair** [comment]
I also has this problem
The celery version is 3.1.23
this is the detail:
KeyError: u"Message for queue 'ebd1d395-a198-3952-9a48-42aff304c430.reply.celery.pidbox' without consumers: {u'body': u'eyJjZWxlcnkyQGFsLWJqLXNlYXJjaC1sb2dhbmFseXNpczAxOnB5dGhvbiI6IFt7ImV4Y2x1c2l2ZSI6IGZhbHNlLCAibmFtZSI6ICJweXRob246YWwtYmotc2VhcmNoLWxvZ2FuYWx5c2lzMDEiLCAiZXhjaGFuZ2UiOiB7Im5hbWUiOiAicHl0aG9uOmFsLWJqLXNlYXJjaC1sb2dhbmFseXNpczAxIiwgImR1cmFibGUiOiB0cnVlLCAiZGVsaXZlcnlfbW9kZSI6IDIsICJwYXNzaXZlIjogZmFsc2UsICJhcmd1bWVudHMiOiBudWxsLCAidHlwZSI6ICJkaXJlY3QiLCAiYXV0b19kZWxldGUiOiBmYWxzZX0sICJkdXJhYmxlIjogdHJ1ZSwgInJvdXRpbmdfa2V5IjogInB5dGhvbjphbC1iai1zZWFyY2gtbG9nYW5hbHlzaXMwMSIsICJhbGlhcyI6IG51bGwsICJxdWV1ZV9hcmd1bWVudHMiOiBudWxsLCAiYXV0b19kZWxldGUiOiBmYWxzZSwgImJpbmRpbmdfYXJndW1lbnRzIjogbnVsbCwgImJpbmRpbmdzIjogW10sICJub19hY2siOiBmYWxzZX1dfQ==', u'headers': {u'ticket': u'2e1af1c3-d26b-4291-987b-9fe79822d8a6', u'clock': 3592}, u'content-type': u'application/json', u'properties': {u'body_encoding': u'base64', u'delivery_info': {u'priority': 0, u'routing_key': u'ebd1d395-a198-3952-9a48-42aff304c430', u'exchange': u'reply.celery.pidbox'}, u'delivery_mode': 1, u'delivery_tag': u'006d3a3b-cd15-4e6b-a263-b6b17dce17ed'}, u'content-encoding': u'utf-8'}"

**Comment by arpheno** [comment]
I'm also having this problem in 3.1.23
