### ISSUE TITLE
Workdir Argument is Ignored

### ISSUE THREAD

**Issue by abraithwaite** [celery/celery#2003]
I thought I was having the same issue as #1235 but I think I found the root of the issue.  For context, I'll copy my content here:

At first I thought that celery wasn't handling permissions according to some edge case in python's os library:

``` python
    Traceback (most recent call last):
      File "/var/www/manage.py", line 44, in <module>
        execute_from_command_line(sys.argv)
      File "/var/www/lib/django/core/management/__init__.py", line 399, in execute_from_command_line
        utility.execute()
      File "/var/www/lib/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/var/www/lib/djcelery/management/commands/celeryd_detach.py", line 26, in run_from_argv
        detached().execute_from_commandline(argv)
      File "/var/www/lib/celery/bin/celeryd_detach.py", line 160, in execute_from_commandline
        **vars(options)
      File "/var/www/lib/celery/bin/celeryd_detach.py", line 42, in detach
        with detached(logfile, pidfile, uid, gid, umask, working_directory, fake):
      File "/var/www/lib/celery/platforms.py", line 313, in open
        os.chdir(self.workdir)
    OSError: [Errno 13] Permission denied: '/root'
```

> Looking at the code, it appears that we're trying to chdir _after_ setuid and setgid is called.  I'm not sure why `os.chdir` would need to read the current working directory, but this is what appears to be happening.  Running the script from a different directory seems to work fine.
> 
> [drop privileges](https://github.com/celery/celery/blob/master/celery/platforms.py#L383)
> [Daemon context](https://github.com/celery/celery/blob/master/celery/platforms.py#L393) calls [chdir](https://github.com/celery/celery/blob/master/celery/platforms.py#L314)

But I then later found by looking at the code that workdir wasn't getting initialized in daemon mode:

> Scratch that.  self.workdir is not being set, despite it being set at the command line:
> 
> Where all the options for the worker are defined:
> https://github.com/celery/celery/blob/master/celery/bin/celeryd_detach.py#L112
> https://github.com/celery/celery/blob/master/celery/bin/celeryd_detach.py#L32
> https://github.com/celery/celery/blob/master/celery/bin/base.py#L646

**Comment by Sispheor** [comment]
Hello guys, I still have the issue with Celery 3.1.23.

`
celery multi v3.1.23 (Cipater)
> Starting nodes...
	> celery@ktm35: OK
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 54, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 178, in run_from_argv
    self.maybe_detach([command] + argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 185, in maybe_detach
    detached_celeryd(self.app).execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celeryd_detach.py", line 173, in execute_from_commandline
    **vars(options)
  File "/usr/lib/python2.7/site-packages/celery/bin/celeryd_detach.py", line 50, in detach
    after_forkers=False):
  File "/usr/lib/python2.7/site-packages/celery/platforms.py", line 357, in open
    os.chdir(self.workdir)
OSError: [Errno 13] Permission denied: '/root'
`

But the workdir, specified with **CELERYD_CHDIR **in my _/etc/default/celeryd_ file is not /root  at all.

I try to run Celery as daemon with the generic init.d script.

**Comment by Sispheor** [comment]
It's ok. The init script must be named celeryd and not celery.
