### ISSUE TITLE
Example (chain + group) doesn't work with json

### ISSUE THREAD

**Issue by theking-laptop** [celery/celery#2033]
I test the example from: http://docs.celeryproject.org/en/latest/userguide/canvas.html, but it doesn't work.

Source code is simple like that:
```
@app.task
def add(x, y):
	return x + y

res = (add.s(4, 4) | group(add.si(i, i) for i in xrange(10)))()
```

My config:
```
CELERY_TASK_SERIALIZER='json'
CELERY_ACCEPT_CONTENT=['json']
```
If I enable them, the program throw error:
```
Traceback (most recent call last):
  File "bin/celery", line 9, in <module>
    load_entry_point('celery==3.1.11', 'console_scripts', 'celery')()
  File "/home/theking/env/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/home/theking/env/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/home/theking/env/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/theking/env/lib/python2.7/site-packages/celery/bin/base.py", line 306, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/theking/env/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/home/theking/env/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/theking/env/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/home/theking/env/lib/python2.7/site-packages/celery/bin/base.py", line 269, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/theking/env/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/home/theking/env/lib/python2.7/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/home/theking/env/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/home/theking/env/lib/python2.7/site-packages/celery/loaders/base.py", line 121, in import_default_modules
    tuple(maybe_list(self.app.conf.CELERY_INCLUDE))
  File "/home/theking/env/lib/python2.7/site-packages/celery/loaders/base.py", line 103, in import_task_module
    return self.import_from_cwd(module)
  File "/home/theking/env/lib/python2.7/site-packages/celery/loaders/base.py", line 112, in import_from_cwd
    package=package,
  File "/home/theking/env/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/home/theking/env/lib/python2.7/site-packages/celery/loaders/base.py", line 106, in import_module
    return importlib.import_module(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/theking/Downloads/Aptana_Studio_3/www/MyCelery/ok/tasks.py", line 212, in <module>
    abc = (add.s(4, 4) | group(add.si(i, i) for i in xrange(10)))()
  File "/home/theking/env/lib/python2.7/site-packages/celery/canvas.py", line 349, in __call__
    return self.apply_async(args, kwargs)
  File "/home/theking/env/lib/python2.7/site-packages/celery/canvas.py", line 241, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/theking/env/lib/python2.7/site-packages/celery/app/builtins.py", line 286, in apply_async
    tasks[0].apply_async(**options)
  File "/home/theking/env/lib/python2.7/site-packages/celery/canvas.py", line 241, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/theking/env/lib/python2.7/site-packages/celery/app/task.py", line 555, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/theking/env/lib/python2.7/site-packages/celery/app/base.py", line 351, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/theking/env/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/home/theking/env/lib/python2.7/site-packages/kombu/messaging.py", line 161, in publish
    compression, headers)
  File "/home/theking/env/lib/python2.7/site-packages/kombu/messaging.py", line 237, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/home/theking/env/lib/python2.7/site-packages/kombu/serialization.py", line 164, in dumps
    payload = encoder(data)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/theking/env/lib/python2.7/site-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/theking/env/lib/python2.7/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/theking/env/lib/python2.7/site-packages/kombu/serialization.py", line 164, in dumps
    payload = encoder(data)
  File "/home/theking/env/lib/python2.7/site-packages/anyjson/__init__.py", line 141, in dumps
    return implementation.dumps(value)
  File "/home/theking/env/lib/python2.7/site-packages/anyjson/__init__.py", line 87, in dumps
    return self._encode(data)
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
kombu.exceptions.EncodeError: keys must be a string
```

**Comment by ask** [comment]
Horrible patch, but what can you do :(

I stil recommend installing simplejson instead.
