### ISSUE TITLE
celery 3.1.11 with jython 2.7/trunk

### ISSUE THREAD

**Issue by jowenn** [celery/celery#2067]
Hi!

I have to get some java code running within worker tasks. I've installed and patched the dependencies, but I'm in troubles with the billiard dependency now, since it unconditionally includes multiprocessing that does not exist in jython, and it also tries to access os.O_NONBLOCK, that is not available in my debian version of jython (2.5) or in my self compiled version.

Since celery mentions, it is possible to use with jython, which exact versions of the dependencies are needed? I wouldn't mind to downgrade things, I just need it working

If jython is really supported, I don't think multiprocessing should be included unconditionally.

I tried: celery worker -A background_workers
I get the error:
Traceback (most recent call last):
  File "/srv/prj1/jythonbin/dist/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/__main__.py", line 29, in main
    from celery.bin.celery import main
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/bin/__init__.py", line 3, in <module>
    from .base import Option
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/bin/base.py", line 81, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/five.py", line 307, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/utils/__init__.py", line 27, in <module>
    from celery.exceptions import CPendingDeprecationWarning, CDeprecationWarning
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/exceptions.py", line 15, in <module>
    from billiard.exceptions import (  # noqa
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/billiard/__init__.py", line 60, in <module>
    from .process import Process, current_process, active_children
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/billiard/process.py", line 25, in <module>
    from multiprocessing import process as _mproc
ImportError: No module named multiprocessing

I also tried: celery worker -P threads -A background_workers
The error I get:
Traceback (most recent call last):
  File "/srv/prj1/jythonbin/dist/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/__main__.py", line 28, in main
    maybe_patch_concurrency()
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/__init__.py", line 127, in maybe_patch_concurrency
    concurrency.get_implementation(pool)
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/concurrency/__init__.py", line 29, in get_implementation
    return symbol_by_name(cls, ALIASES)
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/srv/prj1/jythonbin/dist/Lib/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/concurrency/threads.py", line 13, in <module>
    from .base import apply_target, BasePool
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/celery/concurrency/base.py", line 15, in <module>
    from billiard.einfo import ExceptionInfo
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/billiard/__init__.py", line 60, in <module>
    from .process import Process, current_process, active_children
  File "/srv/prj1/jythonbin/dist/Lib/site-packages/billiard/process.py", line 25, in <module>
    from multiprocessing import process as _mproc
ImportError: No module named multiprocessing

The relevant installed packages are:
amqp==1.4.5
anyjson==0.3.3
billiard==3.3.0.17
celery==3.1.11
kombu==3.0.16
pytz==2014.3
six==1.6.1
wsgiref==0.1.2

**Comment by thedrow** [comment]
You can always try the threadpool.

**Comment by anirban1c** [comment]
How do you use threadpool with celery in jython ?

Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)


billiard fails in process.py

>>> from celery import Celery



tried various combinations but still fails to import 
>>> from celery import Celery
...
...
    from .process import Process, current_process, active_children
  File "/vagrant/jython/27/Lib/site-packages/billiard-3.3.0.22-py2.7.egg/billiard/process.py", line 23, in <module>
    from multiprocessing import process as _mproc
ImportError: No module named multiprocessing


packages installed:

amqp==1.4.6
amqplib==1.0.2
anyjson==0.3.3
armws==0.1
billiard==3.3.0.22
carrot==0.10.7
celery==3.1.18
clamp==0.4
clamped==0.1
decorator==4.0.5
five==0.4.0
importlib==1.0.3
Inject==3.3.1
kombu==3.0.26
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.5
pika==0.10.0
poster==0.8.1
ptyprocess==0.5
pyreadline==2.0
python-dateutil==1.5
pytz==2015.7
PyYAML==3.11
simplegeneric==0.8.1
simplejson==3.6.5
six==1.9.0
socketpool==0.5.3
threadpool==1.3.2
traitlets==4.1.0b1

**Comment by ask** [comment]
threadpool is the default when using Jython.  We use the billiard library, which is a fork of multiprocessing, but recently it has also started importing some things from multiprocessing itself.

Maybe you can do `pip install multiprocessing` for the backport? Not sure if that will work at all.

**Comment by anirban1c** [comment]
I did import multiprocessing but will try the backport, will let you know

**Comment by ask** [comment]
If it doesn't work, then please try celery, billiard, kombu and amqp; from git master, and give me tracebacks from there

**Comment by anirban1c** [comment]
nope same issue, 
have to create a new env to try again over the weekend,
have gone back to sending tasks using pika to a rabbitmq q from jython app at the moment

thanks,
-anirban

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Jython.
