### ISSUE TITLE
ImportError: cannot import name '__all__' (five.py)

### ISSUE THREAD

**Issue by davidfischer-ch** [celery/celery#2083]
I think this is related to #2060 and I guess you should add `https://github.com/celery/py-amqp/zipball/master` to `celery/requirements/default.txt`.

```
stderr: Traceback (most recent call last):
  File "/home/ubuntu/cloudncode_test/venv/src/django/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ubuntu/cloudncode_test/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2189, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ubuntu/cloudncode_test/server/CloudNcode/__init__.py", line 13, in <module>
    from .celery import app as celery_app  # do not remove
  File "/home/ubuntu/cloudncode_test/server/CloudNcode/celery.py", line 13, in <module>
    from celery import Celery
  File "/home/ubuntu/cloudncode_test/venv/src/celery/celery/__init__.py", line 130, in <module>
    from celery import five
  File "/home/ubuntu/cloudncode_test/venv/src/celery/celery/five.py", line 19, in <module>
    from amqp.five import __all__ as _all_five
ImportError: cannot import name '__all__'
```

**Comment by komuW** [comment]
I think the documentation should be updated: https://github.com/celery/celery/blob/master/CONTRIBUTING.rst#running-the-unit-test-suite 
to reflect that if you want to run tests, the commands to run are;
`pip install -U -r requirements/test.txt`
`pip install -U -r requirements/dev.txt`
`pip install -U -r requirements/default.txt`

atleast that's what worked for me.
