### ISSUE TITLE
Class-based Task is not well documented, +exception

### ISSUE THREAD

**Issue by davidfischer-ch** [celery/celery#2084]
First thing first: I am grateful you are taking care of my issues.

One question: How can I unit-test (think Django TestCase) a class-based Task (currently throws an exception)?
1. Map it into a function (and how, #1150 give a partial response).
2. Do something else.

Simplified tasks.py:

```
from celery import shared_task, Task

@shared_task()
class EncodingTask(Task):
    name = __name__ + '.EncodingTask'

    def run(self, task_pk):
        return task_pk
```

Unit-testing my Django application with:

```
@override_settings(CELERY_EAGER_PROPAGATES_EXCEPTIONS=True, CELERY_ALWAYS_EAGER=True, BROKER_BACKEND='memory')
```

Traceback:

```
Traceback (most recent call last):
  File "/home/ubuntu/cloudncode_test/venv/src/django/django/test/utils.py", line 281, in inner
    return test_func(*args, **kwargs)
  File "/home/ubuntu/cloudncode_test/server/cloudncode_base/tests/test_models.py", line 174, in test_delete_media_do_not_cascade
    task = EncodingTask.create_and_launch(self.user, self.profile, self.media, 'output.txt')
  File "/home/ubuntu/cloudncode_test/server/cloudncode_base/models/encoding.py", line 96, in create_and_launch
    task.launch()
  File "/home/ubuntu/cloudncode_test/server/cloudncode_base/models/encoding.py", line 89, in launch
    tasks.EncodingTask().apply_async(kwargs={'task_pk': self.pk}, task_id=self.meta_id)
  File "/home/ubuntu/cloudncode_test/venv/src/celery/celery/app/task.py", line 454, in apply_async
    link=link, link_error=link_error, **options)
  File "/home/ubuntu/cloudncode_test/venv/src/celery/celery/app/task.py", line 633, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/home/ubuntu/cloudncode_test/venv/src/celery/celery/app/trace.py", line 370, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/ubuntu/cloudncode_test/venv/src/celery/celery/app/trace.py", line 355, in trace_task
    R = retval = fun(*args, **kwargs)
TypeError: object() takes no parameters
```

Thanks.

**Comment by anuragjain67** [comment]
@ask, I want to create class based task for reusable app, but I didn't find the way to bind celery_app.

Is following way correct ?
```
from celery import current_app
class _AddTask(app.Task):

    def run(self, x, y):
        return x + y
add = current_app.tasks[_AddTask.name]
```
