### ISSUE TITLE
"MySQL Connection not available" error when MySQL connection is listening

### ISSUE THREAD

**Issue by synthead** [celery/celery#2097]
This error is occasionally displayed in Celery's output.  Using mysql.connector 1.2.2 with Percona Server 5.6.17_65.0, Python 3.4.1, and Celery 3.1.12.

```
[2014-06-14 21:37:42,659: ERROR/MainProcess] Task pidrator.hardware_controller.UpdateEnabledSensors[0f26df3b-cb80-42a5-906b-b974fc391f13] raised unexpected: OperationalError()
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/max/programming/pidrator/pidrator/hardware_controller.py", line 50, in UpdateEnabledSensors
    ).apply_async()
  File "/usr/lib/python3.4/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/usr/lib/python3.4/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python3.4/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/lib/python3.4/site-packages/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/usr/lib/python3.4/site-packages/mysql/connector/django/base.py", line 552, in _cursor
    return super(DatabaseWrapper, self)._cursor()
  File "/usr/lib/python3.4/site-packages/django/db/backends/__init__.py", line 134, in _cursor
    return self.create_cursor()
  File "/usr/lib/python3.4/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python3.4/site-packages/django/utils/six.py", line 549, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/django/db/backends/__init__.py", line 134, in _cursor
    return self.create_cursor()
  File "/usr/lib/python3.4/site-packages/mysql/connector/django/base.py", line 537, in create_cursor
    cursor = self.connection.cursor()
  File "/usr/lib/python3.4/site-packages/mysql/connector/connection.py", line 1328, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
django.db.utils.OperationalError
```

**Comment by eiva** [comment]
I suppose that celery ignore url specs, like even if i trying to use mysql+mysqlconnector:// it still using mysql, moreover: if i specify sqlite:/// it still trying to use mysql...

**Comment by thedrow** [comment]
@eiva How is that related to this issue? If you have a problem, please report a new issue.
