### ISSUE TITLE
Exceptions in tasks autodiscover are not handled when worker is detached

### ISSUE THREAD

**Issue by DXist** [celery/celery#2119]
Celery worker fails silently and with 0 retcode when exception is occured in `app.autodiscover_tasks`.

In my case the problem was in circular import when import starts from `tasks.py` module. Here is part of the traceback:
```
Traceback (most recent call last):
  File "/home/srk/envs/madmin/bin/celery", line 9, in <module>
    load_entry_point('celery==3.2.0a2', 'console_scripts', 'celery')()
  File "/home/srk/workspace/celery/celery/__main__.py", line 30, in main
    main()
  File "/home/srk/workspace/celery/celery/bin/celery.py", line 82, in main
    cmd.execute_from_commandline(argv)
  File "/home/srk/workspace/celery/celery/bin/celery.py", line 778, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/srk/workspace/celery/celery/bin/base.py", line 306, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/srk/workspace/celery/celery/bin/celery.py", line 770, in handle_argv
    return self.execute(command, argv)
  File "/home/srk/workspace/celery/celery/bin/celery.py", line 702, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/srk/workspace/celery/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/home/srk/workspace/celery/celery/bin/base.py", line 269, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/srk/workspace/celery/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/home/srk/workspace/celery/celery/worker/__init__.py", line 97, in __init__
    self.app.loader.init_worker()
  File "/home/srk/workspace/celery/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/home/srk/workspace/celery/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/home/srk/workspace/celery/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/srk/envs/madmin/lib/python2.7/site-packages/amqp/promise.py", line 221, in __call__
    return self.set_error_state()
  File "/home/srk/envs/madmin/lib/python2.7/site-packages/amqp/promise.py", line 217, in __call__
    **(dict(self.kwargs, **kwargs) if kwargs else self.kwargs)
  File "/home/srk/workspace/celery/celery/app/base.py", line 350, in _autodiscover_tasks
    self.loader.autodiscover_tasks(packages, related_name)
  File "/home/srk/workspace/celery/celery/loaders/base.py", line 251, in autodiscover_tasks
    related_name) if mod)
  File "/home/srk/workspace/celery/celery/loaders/base.py", line 272, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/home/srk/workspace/celery/celery/loaders/base.py", line 291, in find_related_module
    return importlib.import_module('{0}.{1}'.format(package, related_name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  ..... application related import cycle is omitted ...
```

It's possible to emulate this behaviour using following callback for `app.autodiscover_tasks`:
```
def autodiscoverer():
    raise RuntimeError('foo')
app.autodiscover_tasks(autodiscoverer)
```

**Comment by thedrow** [comment]
@DXist have you found a fix for this?

**Comment by DXist** [comment]
@thedrow, I added a test to the CI setup of my project reproducing the error. In my case the error during autodiscover was caused by circular import. The test is 
```
echo -n | celery --app=myproject.celery --python shell
```

This test makes the issue not actual for me.

**Comment by thedrow** [comment]
So it should be closed?

**Comment by DXist** [comment]
Yes, you are right. Thank you for reminding about this issue!
