### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 18: ordinal not in range(128)

### ISSUE THREAD

**Issue by dubanoze** [celery/celery#2127]
Hello!
I have it.
Please, help.

```
[2014-07-07 21:21:11,591: WARNING/MainProcess] Traceback (most recent call last):
[2014-07-07 21:21:11,592: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
[2014-07-07 21:21:11,593: WARNING/MainProcess] msg = self.format(record)
[2014-07-07 21:21:11,594: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
[2014-07-07 21:21:11,595: WARNING/MainProcess] return fmt.format(record)
[2014-07-07 21:21:11,596: WARNING/MainProcess] File "/usr/local/.service/my.service/env/local/lib/python2.7/site-packages/celery/utils/log.py", line 138, in format
[2014-07-07 21:21:11,597: WARNING/MainProcess] msg = logging.Formatter.format(self, record)
[2014-07-07 21:21:11,598: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
[2014-07-07 21:21:11,600: WARNING/MainProcess] record.message = record.getMessage()
[2014-07-07 21:21:11,601: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
[2014-07-07 21:21:11,602: WARNING/MainProcess] msg = msg % self.args
[2014-07-07 21:21:11,603: WARNING/MainProcess] UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 18: ordinal not in range(128)
[2014-07-07 21:21:11,604: WARNING/MainProcess] Logged from file job.py, line 401
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

It may be fixed in 4.0 so we'll see if it comes back.
