### ISSUE TITLE
Error after broker connection lost when using the Redis broker

### ISSUE THREAD

**Issue by jclark360** [celery/celery#2139]
We've been seeing some wierd issues where we run a bunch of tasks, call wait on the list of results and it will just hang and not come back. These tasks do not fan out or anything fancy.

The errors we are getting from celery are below, is this a bug somewhere?

```
2014-07-11 07:03:17,847: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 267, in create_loop
    tick_callback()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 940, in on_poll_start
    [add_reader(fd, on_readable, fd) for fd in cycle.fds]
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 201, in add_reader
    return self.add(fds, callback, READ | ERR, args)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 152, in add
    self.poller.register(fd, flags)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/eventio.py", line 78, in register
    self._epoll.register(fd, events)
IOError: [Errno 9] Bad file descriptor
[2014-07-11 07:03:17,848: WARNING/MainProcess] Restoring 26 unacknowledged message(s).
[2014-07-11 07:04:51,735: WARNING/MainProcess] Cannot process event on channel 'celeryev': {'pattern': 'celeryev', 'type': 'pmessage', 'channel': 'celeryev', 'data': '{'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 593, in _receive
    message = loads(bytes_to_str(payload['data']))
  File "/usr/local/lib/python2.7/dist-packages/anyjson/__init__.py", line 135, in loads
    return implementation.loads(value)
  File "/usr/local/lib/python2.7/dist-packages/anyjson/__init__.py", line 99, in loads
    return self._decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 413, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 402, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 418, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 0 (char 0)
```

**Comment by thomasquintana** [comment]
We are having the same issue. Any progress on this would be great.

celery 3.1.18
redis 3.0.3

**Comment by starplanet** [comment]
I encounter this problem too. If no actions in celery last a long time, when I first call a task.delay(), celery will throw ConnectionError exception following:
```
[2015-12-28 19:28:08,222: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 972, in on_readable
    self._callbacks[queue](message)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 534, in _callback
    self.qos.append(message, message.delivery_tag)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 148, in append
    dumps([message._raw, EX, RK])) \
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2628, in execute
    conn.disconnect()
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 819, in disconnect
    channel._on_connection_disconnect(self)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 476, in _on_connection_disconnect
    raise get_redis_ConnectionError()
ConnectionError
```
Then I try again. All work fine. Is redis as broker reliable? Should I change redis to RabbitMQ?

**Comment by lylepratt** [comment]
I am having this issue as well. I'm beginning to think that Redis can not be used reliably with Celery. If someone can please help provide some insight on this error it would be a big help.

**Comment by ask** [comment]
@starplanet Please upgrade to kombu 3.0.32

**Comment by lylepratt** [comment]
@ask I'm running 3.0.32 and still have this issue almost constantly.

**Comment by lylepratt** [comment]
It looks like Kombu 3.0.33 was just released and I think it fixes the issue.

**Comment by RafaAguilar** [comment]
Same issue here with:

kombu==3.0.35
celery==3.1.23
redis==2.10.5

```
 . . .
  File "path/venv/lib/python3.4/site-packages/kombu/transport/redis.py", line 498, in _on_connection_disconnect
    raise get_redis_ConnectionError()
redis.exceptions.ConnectionError
```

**Comment by JonPeel** [comment]
Same again:
kombu==3.0.33
celery==3.1.20
redis==2.7.2
redis-server 2.2.12

  File "/opt/apps/maplecroft/versions/current/virtualenv/lib/python2.7/site-packages/kombu/transport/redis.py", line 491, in _on_connection_disconnect
    raise get_redis_ConnectionError()
ConnectionError

**Comment by ask** [comment]
I'm not sure if this is the same issue, please read celery/kombu#550

**Comment by JonPeel** [comment]
Hmm.  I can't blame RedisToGo in my case - I'm hosting redis locally on an Ubuntu 14.04 machine.   The issue crops up when connecting to that broker from an (admittedly dated) Centos box running python 2.7.2.  Connecting to the same broken from my ubuntu 14.04/python2.7.6 environment, I have no issues.

Not knowing kombu at all, is there anything I can hack in locally to see if some lower level issue bubbles up instead of this ambiguous ConnectionError?
