### ISSUE TITLE
Celery child processes die; Unrecoverable error: EOFError() thrown

### ISSUE THREAD

**Issue by abarton** [celery/celery#2171]
I don't know how to reproduce. The problem feels intermittent. Tasks are being generated from celery and are all of similar type; nothing unusual. An EOFErrow() will be thrown and the child processes will die but the parent process will continue to spin. If the workers are restarted work resumes as expected. 

```
2014-07-28 20:02:53,065 - celery.worker - ERROR - Unrecoverable error: EOFError()
Traceback (most recent call last):
  File "/path/to/lib/python3.3/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/path/to/lib/python3.3/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/path/to/lib/python3.3/site-packages/celery/bootsteps.py", line 373, in start
    return self.obj.start()
  File "/path/to/lib/python3.3/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/path/to/lib/python3.3/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/path/to/lib/python3.3/site-packages/celery/worker/consumer.py", line 796, in start
    c.loop(*c.loop_args())
  File "/path/to/lib/python3.3/site-packages/celery/worker/loops.py", line 72, in asynloop
    next(loop)
  File "/path/to/lib/python3.3/site-packages/kombu/async/hub.py", line 308, in create_loop
    next(cb)
  File "/path/to/lib/python3.3/site-packages/celery/concurrency/asynpool.py", line 243, in _recv_message
    message = load(bufv)
```

**Comment by thedrow** [comment]
@abarton That's easier said than done.
Where exactly should we catch that exception?
Can you point it out on the code?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
