### ISSUE TITLE
Retrieving results using the Cassandra backend in detailed mode raises an error

### ISSUE THREAD

**Issue by ginoledesma** [celery/celery#2222]
When using the Cassandra backend in detailed mode, reconstructing results throws the following error:

```python

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print result.id, result.get()
  File "/Users/gledesma/git/celery/.ve/lib/python2.7/site-packages/celery/result.py", line 171, in get
    self._get_task_meta()  # update self._cache
  File "/Users/gledesma/git/celery/.ve/lib/python2.7/site-packages/celery/result.py", line 331, in _get_task_meta
    return self._set_cache(meta)
  File "/Users/gledesma/git/celery/.ve/lib/python2.7/site-packages/celery/result.py", line 341, in _set_cache
    result_from_tuple(child, self.app) for child in children
  File "/Users/gledesma/git/celery/.ve/lib/python2.7/site-packages/celery/result.py", line 905, in result_from_tuple
    res, nodes = r
ValueError: need more than 1 value to unpack
```

In detailed mode, the `traceback` and `children` metadata for the task results are encoded twice. However, during retrieval, they are only decoded once. This leads to the error above where `celery.results_from_tuple` is decoding an improperly decoded value.

The root of the error is in backends/cassandra.py:

```python
    def _store_result(self, task_id, result, status,
                      traceback=None, request=None, **kwargs):
        """Store return value and status of an executed task."""

        def _do_store():
            cf = self._get_column_family()
            date_done = self.app.now()
            meta = {'status': status,
                    'date_done': date_done.strftime('%Y-%m-%dT%H:%M:%SZ'),
                    'traceback': self.encode(traceback),
                    'result': self.encode(result),
                    'children': self.encode(
                        self.current_task_children(request),
                    )}
            ttl = self.expires and max(self.expires.total_seconds(), 0)
            if self.detailed_mode:
                cf.insert(task_id, {date_done: self.encode(meta)}, ttl=ttl)
            else:
                cf.insert(task_id, meta, ttl=ttl)

        return self._retry_on_error(_do_store)

    def _get_task_meta_for(self, task_id):
        """Get task metadata for a task by id."""

        def _do_get():
            cf = self._get_column_family()
            try:
                if self.detailed_mode:
                    row = cf.get(task_id, column_reversed=True, column_count=1)
                    obj = self.decode(list(row.values())[0])
                else:
                    obj = cf.get(task_id)

                meta = {
                    'task_id': task_id,
                    'status': obj['status'],
                    'result': self.decode(obj['result']),
                    'date_done': obj['date_done'],
                    'traceback': self.decode(obj['traceback']),
                    'children': self.decode(obj['children']),
                }
            except (KeyError, pycassa.NotFoundException):
                meta = {'status': states.PENDING, 'result': None}
            return meta

        return self._retry_on_error(_do_get)
```

What's happening is the inconsistency of encoding/decoding for the `children` property (introduced in 6d64d7a24f15311a0bd13baf7f6a9879176d2d08). In detailed mode, the `children`, `results`, and `traceback` properties are not decoded again — causing them to be treated as encoded unicode literals instead of their native types (in this case, `result_from_tuple` is passed a unicode literal instead of a list/tuple).

This problem occurs in both 3.1.x and master. I've submitted a pull request that addresses this: https://github.com/celery/celery/pull/2221

**Comment by thedrow** [comment]
Issue should be closed since the PR was merged a long time ago.

**Comment by esc** [comment]
we are seeing this too nowadays, but not using cassandra

**Comment by thedrow** [comment]
@esc Then please open a new issue about it.
