### ISSUE TITLE
ImportError with a class in INSTALLED_APPS in Django 1.7

### ISSUE THREAD

**Issue by danxshap** [celery/celery#2248]
Django 1.7 now allows class names in `INSTALLED_APPS` and there's an ImportError that gets raised by the task autodiscover if you use them.

See traceback below:

```
(designlab)Daniels-MacBook-Pro-2:designlab dshap$ celery -A designlab_celery worker -l info
Traceback (most recent call last):
  File "/Users/dshap/.virtualenvs/designlab/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/bin/base.py", line 307, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/bin/base.py", line 270, in __call__
    ret = self.run(*args, **kwargs)
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/amqp/utils.py", line 42, in __call__
    self.set_error_state(exc)
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/amqp/utils.py", line 39, in __call__
    **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/app/base.py", line 329, in _autodiscover_tasks
    self.loader.autodiscover_tasks(packages, related_name)
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/loaders/base.py", line 251, in autodiscover_tasks
    related_name) if mod)
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/loaders/base.py", line 272, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/Users/dshap/.virtualenvs/designlab/lib/python2.7/site-packages/celery/loaders/base.py", line 282, in find_related_module
    pkg_path = importlib.import_module(package).__path__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named SimpleAdminConfig
```

**Comment by ask** [comment]
You can use this:

    from django.apps import apps
    app.autodiscover_tasks(lambda: [n.name for n in apps.get_app_configs()]

The autodiscover_tasks function is generic and takes a list of module names, so changing that to read Django app configs would be bad design.  I guess the proper solution is to add a helper function like `celery.fixups.django.autodiscover_tasks`

Very sad that `django.apps.apps.get_apps` will be removed in 1.9 as using it is __way__ more convenient:

     app.autodiscover_task(apps.get_apps)
