### ISSUE TITLE
Import error in master branch

### ISSUE THREAD

**Issue by pashinin** [celery/celery#2258]
celery==3.2.0a2

```
File "/pyenvs/p3/lib/python3.4/site-packages/celery/__init__.py", line 130, in <module>
    from celery import five
  File "/pyenvs/p3/lib/python3.4/site-packages/celery/five.py", line 19, in <module>
    from amqp.five import __all__ as _all_five
ImportError: cannot import name '__all__'
```

**Comment by supergis** [comment]
It caused by AMQP2.0,but system is "/usr/local/lib/python3.4/dist-packages/amqp-1.4.6-py3.4.egg".
Then delete "amqp-1.4.6-py3.4.egg" and “python3 setup.py install”  for py-AMQP,got another error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 614, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 920, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 812, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (amqp 2.0.0a1 (/usr/local/lib/python3.4/dist-packages/amqp-2.0.0a1-py3.4.egg), Requirement.parse('amqp<2.0,>=1.4.5'), {'kombu'})
```
This caused by Kombu,now can't using amqp 2.0.
May seek more resolution...

**Comment by supergis** [comment]
into "/kombu/requirements",edit the default.txt,delete "<2.0",may help.

**Comment by supergis** [comment]
But now run celery,get another error:
```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 9, in <module>
    load_entry_point('celery==3.2.0a2', 'console_scripts', 'celery')()
  File "/usr/local/lib/python3.4/dist-packages/celery-3.2.0a2-py3.4.egg/celery/__main__.py", line 29, in main
    from celery.bin.celery import main
  File "/usr/local/lib/python3.4/dist-packages/celery-3.2.0a2-py3.4.egg/celery/bin/__init__.py", line 3, in <module>
    from .base import Option
  File "/usr/local/lib/python3.4/dist-packages/celery-3.2.0a2-py3.4.egg/celery/bin/base.py", line 86, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency
  File "/usr/local/lib/python3.4/dist-packages/celery-3.2.0a2-py3.4.egg/celery/five.py", line 149, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.4/dist-packages/celery-3.2.0a2-py3.4.egg/celery/app/__init__.py", line 21, in <module>
    from .base import Celery, AppPickler
  File "/usr/local/lib/python3.4/dist-packages/celery-3.2.0a2-py3.4.egg/celery/app/base.py", line 28, in <module>
    from celery import platforms
  File "/usr/local/lib/python3.4/dist-packages/celery-3.2.0a2-py3.4.egg/celery/platforms.py", line 28, in <module>
    from billiard.compat import get_fdmax, close_open_fds
ImportError: cannot import name 'get_fdmax'
```

**Comment by supergis** [comment]
into /usr/local/lib/python3.4/dist-pakages,remove kombi3.0 but reserve 3.1,all ok.

**Comment by rokonbd** [comment]
Also I have got following issue

Python 2.7.10 (default, May 27 2015, 12:08:27) [C] on hp-ux11
Type "help", "copyright", "credits" or "license" for more information.
>>> from celery import Celery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/__init__.py", line 131, in <module>
    from celery import five
  File "/usr/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/five.py", line 19, in <module>
    from amqp.five import __all__ as _all_five
ImportError: cannot import name __all__

already I have install those dependency 

https://github.com/celery/py-amqp/zipball/master
https://github.com/celery/billiard/zipball/master
https://github.com/celery/kombu/zipball/master

**Comment by codepython** [comment]
install dev.txt ,have resolved my issue.
google is helper.

**Comment by extremewaysback** [comment]
@ask After installing dev.txt, it works. But how to specify my requirement.txt file dependency when I want to deploy my project online?
