### ISSUE TITLE
Workers got error because of mingle 

### ISSUE THREAD

**Issue by pfreixes** [celery/celery#2259]
I came across with this bug when I've tried to run Celery getting it from git@master repository because of #2245.

When I run more than one worker and these receive mingle messages they show the next error

```bash
[2014-09-15 10:03:44,208: DEBUG/MainProcess] pidbox received method hello(revoked={}, from_node=u'celery@laptop-dell') [reply_to:{u'routing_key': u'a2eac8e8-374f-3643-95ea-337a5e3da9f8', u'exchange': u'reply.celery.pidbox'} ticket:d8fd14c3-07df-4bab-99b7-7085880ca13c]
[2014-09-15 10:03:44,208: INFO/MainProcess] sync with celery@laptop-dell
[2014-09-15 10:03:44,209: ERROR/MainProcess] Control command error: error(11, 'Resource temporarily unavailable')
Traceback (most recent call last):
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 38, in on_message
    self.node.handle_message(body, message)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/pidbox.py", line 133, in handle_message
    return self.dispatch(**body)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/pidbox.py", line 116, in dispatch
    ticket=ticket)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/pidbox.py", line 139, in reply
    serializer=self.mailbox.serializer)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/pidbox.py", line 247, in _publish_reply
    **opts
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/messaging.py", line 168, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/messaging.py", line 180, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/messaging.py", line 111, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/common.py", line 113, in maybe_declare
    return _maybe_declare(entity, declared, ident, channel)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/common.py", line 120, in _maybe_declare
    entity.declare()
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/entity.py", line 166, in declare
    nowait=nowait, passive=passive,
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/channel.py", line 626, in exchange_declare
    wait=None if nowait else spec.Exchange.DeclareOk,
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 65, in send_method
    return self.wait(wait)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 80, in wait
    self.connection.drain_events()
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 354, in drain_events
    return self.blocking_read(timeout)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 359, in blocking_read
    return self.on_inbound_frame(read_frame())
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/transport.py", line 154, in read_frame
    frame_header = read(7, True)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/transport.py", line 273, in _read
    s = recv(n - len(rbuf))
error: [Errno 11] Resource temporarily unavailable
[2014-09-15 10:03:44,211: CRITICAL/MainProcess] Unrecoverable error: ValueError('generator already executing',)
Traceback (most recent call last):
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 208, in start
    self.blueprint.start(self)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 851, in start
    c.loop(*c.loop_args())
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/loops.py", line 74, in asynloop
    next(loop)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/async/hub.py", line 276, in create_loop
    item()
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/promise.py", line 221, in __call__
    return self.set_error_state()
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/promise.py", line 217, in __call__
    **(dict(self.kwargs, **kwargs) if kwargs else self.kwargs)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/transport/base.py", line 159, in _read
    drain_events(timeout=0)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 354, in drain_events
    return self.blocking_read(timeout)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 378, in blocking_read
    self.on_inbound_frame(frame)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/method_framing.py", line 85, in frame_handler
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 385, in on_inbound_method
    method_sig, payload, content,
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 129, in dispatch_method
    listener(*args)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/channel.py", line 1616, in _on_basic_deliver
    fun(msg)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/messaging.py", line 592, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/messaging.py", line 559, in receive
    [callback(body, message) for callback in callbacks]
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 43, in on_message
    self.reset()
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 59, in reset
    self.stop(self.c)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 55, in stop
    self.consumer = self._close_channel(c)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 64, in _close_channel
    ignore_errors(c, self.node.channel.close)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/common.py", line 281, in ignore_errors
    return fun(*args, **kwargs)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/channel.py", line 226, in close
    wait=spec.Channel.CloseOk,
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 65, in send_method
    return self.wait(wait)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 80, in wait
    self.connection.drain_events()
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 354, in drain_events
    return self.blocking_read(timeout)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 359, in blocking_read
    return self.on_inbound_frame(read_frame())
ValueError: generator already executing
[2014-09-15 10:03:44,213: DEBUG/MainProcess] | Worker: Closing Hub...
[2014-09-15 10:03:44,213: DEBUG/MainProcess] | Worker: Closing Pool...
[2014-09-15 10:03:44,213: DEBUG/MainProcess] | Worker: Closing Consumer...
[2014-09-15 10:03:44,214: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2014-09-15 10:03:44,214: DEBUG/MainProcess] | Consumer: Closing Connection...
[2014-09-15 10:03:44,214: DEBUG/MainProcess] | Consumer: Closing Events...
[2014-09-15 10:03:44,214: DEBUG/MainProcess] | Consumer: Closing Heart...
[2014-09-15 10:03:44,214: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2014-09-15 10:03:44,214: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2014-09-15 10:03:44,215: DEBUG/MainProcess] | Consumer: Closing Control...
[2014-09-15 10:03:44,215: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2014-09-15 10:03:44,215: DEBUG/MainProcess] | Consumer: Closing event loop...
[2014-09-15 10:03:44,215: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2014-09-15 10:03:44,216: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2014-09-15 10:03:44,216: ERROR/MainProcess] Error on stopping Gossip: StopIteration()
Traceback (most recent call last):
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 155, in send_all
    fun(parent, *args)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 409, in stop
    self._close(c, True)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 418, in _close
    ignore_errors(c.connection, consumer.cancel)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/common.py", line 281, in ignore_errors
    return fun(*args, **kwargs)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/messaging.py", line 456, in cancel
    cancel(tag)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/channel.py", line 1459, in basic_cancel
    wait=None if nowait else spec.Basic.CancelOk,
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 65, in send_method
    return self.wait(wait)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 80, in wait
    self.connection.drain_events()
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 354, in drain_events
    return self.blocking_read(timeout)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 359, in blocking_read
    return self.on_inbound_frame(read_frame())
StopIteration
[2014-09-15 10:03:44,217: DEBUG/MainProcess] | Consumer: Stopping Control...
[2014-09-15 10:03:44,218: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2014-09-15 10:03:44,218: DEBUG/MainProcess] Cancelling task consumer...
[2014-09-15 10:03:44,219: ERROR/MainProcess] Error on stopping Tasks: StopIteration()
Traceback (most recent call last):
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 155, in send_all
    fun(parent, *args)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 648, in stop
    ignore_errors(c, c.task_consumer.cancel)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/common.py", line 281, in ignore_errors
    return fun(*args, **kwargs)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/messaging.py", line 456, in cancel
    cancel(tag)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/channel.py", line 1459, in basic_cancel
    wait=None if nowait else spec.Basic.CancelOk,
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 65, in send_method
    return self.wait(wait)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 80, in wait
    self.connection.drain_events()
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 354, in drain_events
    return self.blocking_read(timeout)
  File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 359, in blocking_read
    return self.on_inbound_frame(read_frame())
StopIteration
[2014-09-15 10:03:44,219: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2014-09-15 10:03:44,219: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2014-09-15 10:03:44,220: DEBUG/MainProcess] | Consumer: Stopping Events...
[2014-09-15 10:03:44,220: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2014-09-15 10:03:44,220: DEBUG/MainProcess] | Worker: Stopping Pool...
[2014-09-15 10:03:45,227: DEBUG/MainProcess] | Worker: Stopping Hub...
[2014-09-15 10:03:45,228: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2014-09-15 10:03:45,229: WARNING/MainProcess] Traceback (most recent call last):
[2014-09-15 10:03:45,230: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/bin/celery", line 9, in <module>
[2014-09-15 10:03:45,231: WARNING/MainProcess] load_entry_point('celery==3.2.0a2', 'console_scripts', 'celery')()
[2014-09-15 10:03:45,232: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
[2014-09-15 10:03:45,233: WARNING/MainProcess] main()
[2014-09-15 10:03:45,233: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bin/celery.py", line 82, in main
[2014-09-15 10:03:45,234: WARNING/MainProcess] cmd.execute_from_commandline(argv)
[2014-09-15 10:03:45,234: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bin/celery.py", line 778, in execute_from_commandline
[2014-09-15 10:03:45,235: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
[2014-09-15 10:03:45,235: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bin/base.py", line 307, in execute_from_commandline
[2014-09-15 10:03:45,235: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
[2014-09-15 10:03:45,235: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bin/celery.py", line 770, in handle_argv
[2014-09-15 10:03:45,236: WARNING/MainProcess] return self.execute(command, argv)
[2014-09-15 10:03:45,236: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bin/celery.py", line 702, in execute
[2014-09-15 10:03:45,236: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2014-09-15 10:03:45,236: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
[2014-09-15 10:03:45,236: WARNING/MainProcess] return self(*args, **options)
[2014-09-15 10:03:45,236: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bin/base.py", line 270, in __call__
[2014-09-15 10:03:45,236: WARNING/MainProcess] ret = self.run(*args, **kwargs)
[2014-09-15 10:03:45,237: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bin/worker.py", line 214, in run
[2014-09-15 10:03:45,237: WARNING/MainProcess] worker.start()
[2014-09-15 10:03:45,237: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 213, in start
[2014-09-15 10:03:45,237: WARNING/MainProcess] self.stop(exitcode=EX_FAILURE)
[2014-09-15 10:03:45,237: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 258, in stop
[2014-09-15 10:03:45,237: WARNING/MainProcess] self._shutdown(warm=True)
[2014-09-15 10:03:45,237: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 272, in _shutdown
[2014-09-15 10:03:45,238: WARNING/MainProcess] self.blueprint.stop(self, terminate=not warm)
[2014-09-15 10:03:45,238: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 183, in stop
[2014-09-15 10:03:45,238: WARNING/MainProcess] self.on_stopped()
[2014-09-15 10:03:45,238: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 166, in on_stopped
[2014-09-15 10:03:45,238: WARNING/MainProcess] self.consumer.shutdown()
[2014-09-15 10:03:45,238: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 305, in shutdown
[2014-09-15 10:03:45,239: WARNING/MainProcess] self.blueprint.shutdown(self)
[2014-09-15 10:03:45,239: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 163, in shutdown
[2014-09-15 10:03:45,239: WARNING/MainProcess] self.send_all(parent, 'shutdown')
[2014-09-15 10:03:45,239: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 155, in send_all
[2014-09-15 10:03:45,239: WARNING/MainProcess] fun(parent, *args)
[2014-09-15 10:03:45,239: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 412, in shutdown
[2014-09-15 10:03:45,240: WARNING/MainProcess] self._close(c, False)
[2014-09-15 10:03:45,240: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/celery/bootsteps.py", line 422, in _close
[2014-09-15 10:03:45,240: WARNING/MainProcess] ignore_errors(c.connection, channel.close)
[2014-09-15 10:03:45,240: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/kombu/common.py", line 281, in ignore_errors
[2014-09-15 10:03:45,240: WARNING/MainProcess] return fun(*args, **kwargs)
[2014-09-15 10:03:45,240: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/channel.py", line 226, in close
[2014-09-15 10:03:45,241: WARNING/MainProcess] wait=spec.Channel.CloseOk,
[2014-09-15 10:03:45,241: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 65, in send_method
[2014-09-15 10:03:45,241: WARNING/MainProcess] return self.wait(wait)
[2014-09-15 10:03:45,241: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 80, in wait
[2014-09-15 10:03:45,241: WARNING/MainProcess] self.connection.drain_events()
[2014-09-15 10:03:45,242: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 354, in drain_events
[2014-09-15 10:03:45,242: WARNING/MainProcess] return self.blocking_read(timeout)
[2014-09-15 10:03:45,242: WARNING/MainProcess] File "/home/pfreixes/envs/m2m-framework/local/lib/python2.7/site-packages/amqp/connection.py", line 359, in blocking_read
[2014-09-15 10:03:45,242: WARNING/MainProcess] return self.on_inbound_frame(read_frame())
[2014-09-15 10:03:45,243: WARNING/MainProcess] StopIteration
[2014-09-15 10:03:45,243: DEBUG/MainProcess] removing tasks from inqueue until task handler finished```

**Comment by ask** [comment]
We haven't received this in a while, I think it may be fixed so let's see if it comes back :/
