### ISSUE TITLE
Master branch, exception on start - amqp.exceptions.FrameSyntaxError: Unknown value in table

### ISSUE THREAD

**Issue by pashinin** [celery/celery#2261]
When using master branch after I start worker or call a task

```
celery -A proj worker --loglevel=info
celery call tasks.update
```

I see this:

```
[2014-09-15 19:21:42,876: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s',)
Traceback (most recent call last):
  File "/pyenvs/p3/lib/python3.4/site-packages/celery-3.2.0a2-py3.4.egg/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/pyenvs/p3/lib/python3.4/site-packages/celery-3.2.0a2-py3.4.egg/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/pyenvs/p3/lib/python3.4/site-packages/celery-3.2.0a2-py3.4.egg/celery/worker/consumer.py", line 503, in start
    c.connection = c.connect()
  File "/pyenvs/p3/lib/python3.4/site-packages/celery-3.2.0a2-py3.4.egg/celery/worker/consumer.py", line 375, in connect
    callback=maybe_shutdown,
  File "/pyenvs/p3/lib/python3.4/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/pyenvs/p3/lib/python3.4/site-packages/kombu/utils/__init__.py", line 223, in retry_over_time
    return fun(*args, **kwargs)
  File "/pyenvs/p3/lib/python3.4/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/pyenvs/p3/lib/python3.4/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/pyenvs/p3/lib/python3.4/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/pyenvs/p3/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 115, in establish_connection
    conn = self.Connection(**opts)
  File "/pyenvs/p3/lib/python3.4/site-packages/amqp/connection.py", line 217, in __init__
    self.connect()
  File "/pyenvs/p3/lib/python3.4/site-packages/amqp/connection.py", line 236, in connect
    self.drain_events()
  File "/pyenvs/p3/lib/python3.4/site-packages/amqp/connection.py", line 354, in drain_events
    return self.blocking_read(timeout)
  File "/pyenvs/p3/lib/python3.4/site-packages/amqp/connection.py", line 359, in blocking_read
    return self.on_inbound_frame(read_frame())
  File "/pyenvs/p3/lib/python3.4/site-packages/amqp/method_framing.py", line 65, in frame_handler
    callback(channel, method_sig, buf, None)
  File "/pyenvs/p3/lib/python3.4/site-packages/amqp/connection.py", line 385, in on_inbound_method
    method_sig, payload, content,
  File "/pyenvs/p3/lib/python3.4/site-packages/amqp/abstract_channel.py", line 124, in dispatch_method
    args, _ = loads(amqp_method.args, payload, 4)
  File "/pyenvs/p3/lib/python3.4/site-packages/amqp/serialization.py", line 229, in loads
    val[key], offset = _read_item(buf, offset)
  File "/pyenvs/p3/lib/python3.4/site-packages/amqp/serialization.py", line 154, in _read_item
    ftype, type(ftype)))
amqp.exceptions.FrameSyntaxError: Unknown value in table: 70 (<class 'int'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pyenvs/p3/lib/python3.4/site-packages/celery-3.2.0a2-py3.4.egg/celery/worker/consumer.py", line 284, in start
    self._restart_state.step()
  File "/pyenvs/p3/lib/python3.4/site-packages/billiard/common.py", line 130, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
```

**Comment by kharazi** [comment]
+1

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Maybe it's fixed already, we'll see if it comes back after 4.0 release.

**Comment by Strapchay** [comment]
Hi, i am currently experiencing an error similar to this. Have been trying to figure out the reason why, have had to uninstall and reinstall rabbitmq incase it might be the issue. Here is what my log looks like:
[2024-04-15 20:52:31,221: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-04-15 20:52:31,223: INFO/MainProcess] mingle: searching for neighbors
[2024-04-15 20:52:31,224: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/amqp/connection.py", line 515, in channel
    return self.channels[channel_id]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 37, in start
    self.sync(c)
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
    replies = self.send_hello(c)
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/celery/app/control.py", line 389, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/kombu/pidbox.py", line 330, in _broadcast
    chan = channel or self.connection.default_channel
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/kombu/connection.py", line 956, in default_channel
    self._default_channel = self.channel()
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/kombu/connection.py", line 303, in channel
    chan = self.transport.create_channel(self.connection)
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/kombu/transport/pyamqp.py", line 168, in create_channel
    return connection.channel()
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/amqp/connection.py", line 518, in channel
    channel.open()
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/amqp/channel.py", line 448, in open
    return self.send_method(
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/amqp/abstract_channel.py", line 79, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/amqp/abstract_channel.py", line 99, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/amqp/connection.py", line 526, in drain_events
    while not self.blocking_read(timeout):
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/amqp/connection.py", line 531, in blocking_read
    frame = self.transport.read_frame()
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/amqp/transport.py", line 294, in read_frame
    frame_header = read(7, True)
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/amqp/transport.py", line 629, in _read
    s = recv(n - len(rbuf))
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-04-15 20:52:31,224: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 330, in start
    self._restart_state.step()
  File "/home/strapchay/Documents/api_mng_wordp/venv/lib/python3.10/site-packages/billiard/common.py", line 153, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s`
`
And here is what my config looks like:
celery.py:
`
from __future__ import absolute_import
import os

from celery import Celery
from celery.schedules import crontab

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")

app = Celery("core")

app.config_from_object("django.conf:settings", namespace="CELERY")
# app.conf.task_acks_late = True

app.autodiscover_tasks()

# implement periodic tasks here
app.conf.beat_schedules = {}
`
init.py:
`
from .celery import app as celery_app

__all__ = ("celery_app",)

`
django's settings.py:
`
# CELERYD_HIJACK_ROOT_LOGGER = False
CELERY_BROKER_URL = "amqp://guest:guest@localhost:5672/"
CELERY_RESULT_BACKEND = "rpc://"
# CELERY_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_WORKER_CANCEL_LONG_RUNNING_TASKS_ON_CONNECTION_LOSS = True
`
