### ISSUE TITLE
apply_async with queue set to dedicated queue causes PreconditionFailed exception

### ISSUE THREAD

**Issue by rbarlow** [celery/celery#2269]
I made a very simple Celery app, example.py:

```
from celery import Celery, task


broker_url = 'amqp://user:password@host/vhost'
app = Celery('mimic', broker=broker_url)

app.conf.update(CELERY_WORKER_DIRECT=True)


@app.task
def add(x, y): 
   return x + y
```

Then I started a worker:

```
(pulp)[rbarlow@notepad]~/devel/pulp% celery worker -A example --loglevel=info
```

Then I opened a Python shell, and did this:

```
>>> import example
>>> example.add.apply_async((2,2), queue='celery@my.hostname.dq')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/celery/app/task.py", line 555, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/lib/python2.6/site-packages/celery/app/base.py", line 351, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/lib/python2.6/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/usr/lib/python2.6/site-packages/kombu/messaging.py", line 168, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/lib/python2.6/site-packages/kombu/connection.py", line 440, in _ensured
    return fun(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/kombu/messaging.py", line 180, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/usr/lib/python2.6/site-packages/kombu/messaging.py", line 111, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/usr/lib/python2.6/site-packages/kombu/common.py", line 99, in maybe_declare
    return _maybe_declare(entity)
  File "/usr/lib/python2.6/site-packages/kombu/common.py", line 110, in _maybe_declare
    entity.declare()
  File "/usr/lib/python2.6/site-packages/kombu/entity.py", line 505, in declare
    self.queue_declare(nowait, passive=False)
  File "/usr/lib/python2.6/site-packages/kombu/entity.py", line 531, in queue_declare
    nowait=nowait)
  File "/usr/lib/python2.6/site-packages/amqp/channel.py", line 1258, in queue_declare
    (50, 11),  # Channel.queue_declare_ok
  File "/usr/lib/python2.6/site-packages/amqp/abstract_channel.py", line 69, in wait
    return self.dispatch_method(method_sig, args, content)
  File "/usr/lib/python2.6/site-packages/amqp/abstract_channel.py", line 87, in dispatch_method
    return amqp_method(self, args)
  File "/usr/lib/python2.6/site-packages/amqp/channel.py", line 241, in _close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - parameters for queue 'celery@notepad.usersys.redhat.com.dq' in vhost 'pulp_notepad' not equivalent
```

My memory of my debugging session is a little vague, but I *think* the parameter that was different was the auto_delete parameter. It seems that the worker was declaring this queue differently than apply_async was declaring it when I used it in this manner. @bmbouter, do you remember if that was the parameter that was different?

I did note that I can leave the .dq off of the queue argument, and that seems to work. I also learned that I can set exchange to C.dq and then set routing_key to the worker's name, and that also works. I believe that I should have been able to set the queue like this as well, however.

Is this a bug, or was I not meant to use the .dq directly in this manner? If I wasn't meant to do that, could we clarify the documentation for the dedicated queue feature so that others don't experience this in the future?

**Comment by bersace** [comment]
@ask Thanks for the snippet ! Can you point a documentation on how te query a specific worker ? say for instance, I write a monitoring task that gather informations in each worker to validate plateform status.

Regards.

**Comment by ask** [comment]
Sounds like you would want to use broadcast for this, which the celery AsyncResult has no specific support for.

The workers already have a broadcast system to report status, see remote control commands in the worker/monitoring guide.  You can easily add your own remote control commands.

**Comment by bersace** [comment]
Ok. I got a way to query a specific worker with the following code:

```python
queue = worker_direct(worker)
my_task.apply_async(exchange=queue.exchange.name, routing_key=worker)
```

**Comment by bersace** [comment]
@ask I'll check this. Thanks !
