### ISSUE TITLE
CLI improvement - Celery should sanitize the inputs that represent module names by stripping whitespace

### ISSUE THREAD

**Issue by hangtwenty** [celery/celery#2281]
# Problem (Commandline UI)

This doesn't work:

```
celery worker --app foo --loglevel=INFO --pool processes
```

and will produce the following traceback:

```
Traceback (most recent call last):
  File "/Users/mfloering/.virtualenvs/supercircuit/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/mfloering/.virtualenvs/supercircuit/lib/python2.7/site-packages/celery/__main__.py", line 28, in main
    maybe_patch_concurrency()
  File "/Users/mfloering/.virtualenvs/supercircuit/lib/python2.7/site-packages/celery/__init__.py", line 127, in maybe_patch_concurrency
    concurrency.get_implementation(pool)
  File "/Users/mfloering/.virtualenvs/supercircuit/lib/python2.7/site-packages/celery/concurrency/__init__.py", line 29, in get_implementation
    return symbol_by_name(cls, ALIASES)
  File "/Users/mfloering/.virtualenvs/supercircuit/lib/python2.7/site-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    sys.exc_info()[2])
  File "/Users/mfloering/.virtualenvs/supercircuit/lib/python2.7/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ValueError: Couldn't import '': Empty module name
```

This is because the `=` is required after `--app` and `--processes`.

This **will** work:

```bash
celery worker --app=foo --loglevel INFO --pool=processes
```

I know this has more to do with argument parsing (and the library that does that) than something Celery-specific.

However, it is extremely confusing to see spaces being allowed in the following instances:

* `-A foo` (short argument for `--app`)
* `--loglevel INFO`

But not working in these instances:

* `--app foo`
* `--pool processes`

The [Workers documentation](http://celery.readthedocs.org/en/latest/userguide/workers.html) only demonstrates `-A`, so it really takes a while to get to the bottom of that traceback -- I thought the problem was much more complicated and I looked at many application-specific possibilities before I got to the bottom of it.

This is important, because I believe it's common for users to use short arguments (`-A`) when running manual commands, then long arguments (`--app`) when moving those commands to automation and configuration (for the sake of readability). And then when that happens, it's easy to think you've broken something more complex (because you're thinking about integration).

# Solution

This can be solved by sanitizing commandline inputs where the argument is a module name. There are no use-cases where module names would start or end with spaces, so the spaces can be stripped.

I can make a pull request for this, but I wanted to confirm what arguments need attention. Any besides these?

* `--app`
* `--pool`

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
