### ISSUE TITLE
CELERY_RESULT_BACKEND = 'amqp' timeouts and errors

### ISSUE THREAD

**Issue by rrauenza** [celery/celery#2316]
Using celery 3.1.11, using rabbit

I turned on amqp backend from redis last night and woke up with some error messages this morning.

BROKER_URL = 'amqp://user:user@%s//celery' % 'localhost'
CELERY_RESULT_BACKEND = 'amqp' #### 'redis://localhost/1'

Some are time limit exceeded for tasks that appear to be waiting in amqp:

Traceback (most recent call last):
[...]
File "...virtualenv/lib/python2.7/site-packages/celery/canvas.py", line 241, in apply_async
return _apply(args, kwargs, **options)
File "...virtualenv/lib/python2.7/site-packages/celery/app/task.py", line 555, in apply_async
**dict(self._get_exec_options(), **options)
File "...virtualenv/lib/python2.7/site-packages/celery/app/base.py", line 351, in send_task
reply_to=reply_to or self.oid, **options
File "...virtualenv/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
**kwargs
File "...virtualenv/lib/python2.7/site-packages/kombu/messaging.py", line 168, in publish
routing_key, mandatory, immediate, exchange, declare)
File "...virtualenv/lib/python2.7/site-packages/kombu/connection.py", line 440, in _ensured
return fun(*args, **kwargs)
File "...virtualenv/lib/python2.7/site-packages/kombu/messaging.py", line 180, in _publish
[maybe_declare(entity) for entity in declare]
File "...virtualenv/lib/python2.7/site-packages/kombu/messaging.py", line 111, in maybe_declare
return maybe_declare(entity, self.channel, retry, **retry_policy)
File "...virtualenv/lib/python2.7/site-packages/kombu/common.py", line 99, in maybe_declare
return _maybe_declare(entity)
File "...virtualenv/lib/python2.7/site-packages/kombu/common.py", line 110, in _maybe_declare
entity.declare()
File "...virtualenv/lib/python2.7/site-packages/kombu/entity.py", line 504, in declare
self.exchange.declare(nowait)
File "...virtualenv/lib/python2.7/site-packages/kombu/entity.py", line 166, in declare
nowait=nowait, passive=passive,
File "...virtualenv/lib/python2.7/site-packages/amqp/channel.py", line 620, in exchange_declare
(40, 11), # Channel.exchange_declare_ok
File "...virtualenv/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
self.channel_id, allowed_methods)
File "...virtualenv/lib/python2.7/site-packages/amqp/connection.py", line 237, in _wait_method
self.method_reader.read_method()
File "...virtualenv/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
raise m
SoftTimeLimitExceeded: SoftTimeLimitExceeded()

another error I got was

Traceback (most recent call last):
File "...virtualenv/lib/python2.7/site-packages/celery/app/trace.py", line 235, in trace_task
request=task_request,
File "...virtualenv/lib/python2.7/site-packages/celery/backends/amqp.py", line 136, in store_result
delivery_mode=self.delivery_mode,
File "...virtualenv/lib/python2.7/site-packages/kombu/messaging.py", line 168, in publish
routing_key, mandatory, immediate, exchange, declare)
File "...virtualenv/lib/python2.7/site-packages/kombu/connection.py", line 440, in _ensured
return fun(*args, **kwargs)
File "...virtualenv/lib/python2.7/site-packages/kombu/messaging.py", line 180, in _publish
[maybe_declare(entity) for entity in declare]
File "...virtualenv/lib/python2.7/site-packages/kombu/messaging.py", line 111, in maybe_declare
return maybe_declare(entity, self.channel, retry, **retry_policy)
File "...virtualenv/lib/python2.7/site-packages/kombu/common.py", line 99, in maybe_declare
return _maybe_declare(entity)
File "...virtualenv/lib/python2.7/site-packages/kombu/common.py", line 114, in _maybe_declare
entity.declare()
File "...virtualenv/lib/python2.7/site-packages/kombu/entity.py", line 508, in declare
self.queue_bind(nowait)
File "...virtualenv/lib/python2.7/site-packages/kombu/entity.py", line 541, in queue_bind
self.binding_arguments, nowait=nowait)
File "...virtualenv/lib/python2.7/site-packages/kombu/entity.py", line 551, in bind_to
nowait=nowait)
File "...virtualenv/lib/python2.7/site-packages/amqp/channel.py", line 1003, in queue_bind
(50, 21), # Channel.queue_bind_ok
File "...virtualenv/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
self.channel_id, allowed_methods)
File "...virtualenv/lib/python2.7/site-packages/amqp/connection.py", line 237, in _wait_method
self.method_reader.read_method()
File "...virtualenv/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
raise m
UnexpectedFrame: Received 0x04 while expecting 0xce

(Is this the one caused by sharing an amqp file handle between threads/processes?)

I'll probably just switch back to redis, but wanted to report these.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Please don't use the amqp result backend anymore, use the rpc backend for RPC, or a database backend for persistent results.

**Comment by rrauenza** [comment]
> Please don't use the amqp result backend anymore, use the rpc backend for RPC, or a database backend for persistent results.

For clarity, I assume you meant:

Please don't use the amqp result backend anymore.  *Instead* use the rpc backend for RPC, or a database backend for persistent results.
