### ISSUE TITLE
Celery 3.1.15 breaks Django (deadlock)

### ISSUE THREAD

**Issue by lerela** [celery/celery#2362]
Hi,

Very serious issue for me here. Upgrading to Celery 3.1.15 and above blocks the Django setup(), ie. anything using a Django application, at least in my situation.

I just have "djcelery" in my INSTALLED_APPS. Then any command called with `manage.py` (`shell, runserver`, ...) or for instance through gunicorn gets stuck into a deadlock. Symptoms are just that nothing happen until I hit Ctrl^C and get the following traceback:

```
^CTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/www/site1/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/www/site1/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/www/site1/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/www/site1/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/www/site1/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/www/site1/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 23, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/www/site1/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/www/site1/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/www/site1/lib/python3.4/site-packages/djcelery/admin.py", line 296, in <module>
    class PeriodicTaskAdmin(admin.ModelAdmin):
  File "/www/site1/lib/python3.4/site-packages/djcelery/admin.py", line 298, in PeriodicTaskAdmin
    form = periodic_task_form()
  File "/www/site1/lib/python3.4/site-packages/djcelery/admin.py", line 251, in periodic_task_form
    current_app.loader.import_default_modules()
  File "/www/site1/lib/python3.4/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/www/site1/lib/python3.4/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/www/site1/lib/python3.4/site-packages/celery/fixups/django.py", line 69, in on_import_modules
    self.worker_fixup.validate_models()
  File "/www/site1/lib/python3.4/site-packages/celery/fixups/django.py", line 154, in validate_models
    django_setup()
  File "/www/site1/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/www/site1/lib/python3.4/site-packages/django/apps/registry.py", line 71, in populate
    with self._lock:
KeyboardInterrupt
```

Therefore, a simple upgrade via pip and a server reboot/reset breaks the whole application.
I'm using Python 3 and Django 1.7.1. Downgrading to 3.1.14 solves the issue.

**Comment by shayneoneill** [comment]
Please note: I'm getting this with 3.1.17. Possibly a regression?

**Comment by dustinfarris** [comment]
Also getting this with 3.1.17 — i don't use django-celery.

**Comment by jordigh** [comment]
I have seen this problem without Celery too. The problem is that some app when being loaded itself requires loading another app. This results in two calls to apps.populate() within the same call stack. The docstring for this function indicates that it is intentionally not reentrant, so the two calls in the same call stack end up deadlocking on this function.

So I suppose it's a bug that some apps require loading other apps while being loaded. I don't understand why apps.populate() can't just be modified to be reentrant, though. A function shouldn't be able to deadlock itself just because of a recursive call.
