### ISSUE TITLE
Worker creation fails some times in Debian but no in Windows

### ISSUE THREAD

**Issue by minuscorp** [celery/celery#2363]
Hello.

I have a dynamic celery application where our consumers can rent workers for several high time consuming tasks, so I use the command worker(app=app).run(loglevel='info', queues="%i,celery"%pk, hostname=str(number)+"@"+"%i"%pk, purge=True, concurrency=2, detach=True) to create new workers which consumes the queue of the client. These workers are created from a general worker per machine which is consuming a 'default' queue who recieves the task that creates the new worker:
def start_workers(self, number, pk):
    print "STARTING WORKER"
    worker(app=app).run(loglevel='info', queues="%i,celery"%pk, hostname=str(number)+"@"+"%i"%pk, purge=True, concurrency=2, detach=True)
    return 1
Here's where I'm having troubles, my Django server is running in a Windows machine and all the workers created in that machine from the previous task are running without problems. But when i add a 'default' consumer worker in a debian machine (running the exactly same code than the windows' one) if y try to launch a child worker sometimes i'm recieving the next error traceback:

[2014-11-10 13:42:09,785: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 293, in create_loop
    self.remove_reader(fd)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 210, in remove_reader
    self._unregister(fd)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 230, in _unregister
    self.poller.unregister(fd)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/eventio.py", line 85, in unregister
    self._epoll.unregister(fd)
IOError: [Errno 1] Operation not permitted

And even Flower is detecting the worker as "running", there's no such worker and it'll block all the processes because he's not doing his tasks but his tasks are marked in Flower as "received", but never done.

I'm trying to know if I'm doing wrong the creation of child workers and there's some way to do it better, what surprises me is that in Windows i have no blocking and no worker creation problems at all.

Regards.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
