### ISSUE TITLE
No POLLIN and friends on OSX

### ISSUE THREAD

**Issue by tebeka** [celery/celery#2430]
Running celery from master (8d146d8c14fad744b62694359afe5f02e141ace3) on OSX I see the following error. The reason is that `select` module on OSX does not have `POLLIN` and friends, only kqueue related functions and attributes.

```
$ python -m celery -A t worker --loglevel INFO
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mikitebeka/src/celery/celery/__main__.py", line 54, in <module>
    main()
  File "/Users/mikitebeka/src/celery/celery/__main__.py", line 30, in main
    main()
  File "celery/bin/celery.py", line 83, in main
    cmd.execute_from_commandline(argv)
  File "celery/bin/celery.py", line 780, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "celery/bin/celery.py", line 772, in handle_argv
    return self.execute(command, argv)
  File "celery/bin/celery.py", line 704, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "celery/bin/worker.py", line 194, in run
    pool_cls = (concurrency.get_implementation(pool_cls) or
  File "celery/concurrency/__init__.py", line 29, in get_implementation
    return symbol_by_name(cls, ALIASES)
  File "/Users/mikitebeka/src/celery/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "celery/concurrency/prefork.py", line 25, in <module>
    from .asynpool import AsynPool
  File "celery/concurrency/asynpool.py", line 114, in <module>
    poll=select.poll, POLLIN=select.POLLIN,
AttributeError: 'module' object has no attribute 'poll'
```

**Comment by asergeant01** [comment]
I'm also experiencing this.

**Comment by aphillipo** [comment]
I too also get this error.

**Comment by ask** [comment]
I'm developing on OS X, Python 2.7.8 and have no such issues.  What python/OS version are you running?

**Comment by aphillipo** [comment]
>> python --version
Python 2.7.6

>> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.2
BuildVersion:	14C109

**Comment by aphillipo** [comment]
I installed as follows: 

pip install -U https://github.com/celery/celery/zipball/master\#egg\=celery

Maybe if I install from source it'll work?

**Comment by aphillipo** [comment]
I've just installed it as follows from source using pip.

    Traceback (most recent call last):
      File "/Users/aphillipo/Sites/work/dave/venv_dave/bin/celery", line 9, in <module>
        load_entry_point('celery==3.2.0a2', 'console_scripts', 'celery')()
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/__main__.py", line 30, in main
        main()
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/bin/celery.py", line 83, in main
        cmd.execute_from_commandline(argv)
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/bin/celery.py", line 780, in execute_from_commandline
        super(CeleryCommand, self).execute_from_commandline(argv)))
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/bin/base.py", line 311, in execute_from_commandline
        return self.handle_argv(self.prog_name, argv[1:])
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/bin/celery.py", line 772, in handle_argv
        return self.execute(command, argv)
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/bin/celery.py", line 704, in execute
        ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/bin/worker.py", line 179, in run_from_argv
        return self(*args, **options)
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/bin/base.py", line 274, in __call__
        ret = self.run(*args, **kwargs)
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/bin/worker.py", line 194, in run
        pool_cls = (concurrency.get_implementation(pool_cls) or
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/concurrency/__init__.py", line 29, in get_implementation
        return symbol_by_name(cls, ALIASES)
      File "/Users/aphillipo/Sites/work/dave/venv_dave/lib/python2.7/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
        module = imp(module_name, package=package, **kwargs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/concurrency/prefork.py", line 25, in <module>
        from .asynpool import AsynPool
      File "/Users/aphillipo/Sites/work/dave/venv_dave/src/celery/celery/concurrency/asynpool.py", line 114, in <module>
        poll=select.poll, POLLIN=select.POLLIN,
    AttributeError: 'module' object has no attribute 'poll'
    exited with code 1

**Comment by aphillipo** [comment]
I'm going to update OSX and XCode and see what happens.

**Comment by aphillipo** [comment]
Okay so after upgrading to python 2.7.9 it still fails.

**Comment by aphillipo** [comment]
http://stackoverflow.com/questions/21952175/homebrew-python-installation-options

I'm using homebrew python which by default does not have select.poll support.

Sigh.  You can close this probably.

**Comment by ask** [comment]
Seems harsh to disable poll just because it will not support devices :/

**Comment by ask** [comment]
Btw, we could use `getattr(select, 'poll') or select.select`, but using select means we are limited to FD_SETSIZE (typically 1024) file descriptors, and that is not just for what we are polling: it's a limit on the total number of file descriptors used by the process.

**Comment by ask** [comment]
Seems the python shipped with os x also does not have `poll`, so not really any choice other than to fallback to it I guess.

**Comment by aphillipo** [comment]
I think this is fine as is.  Just make sure people use --with-poll if using homebrew python.  Not sure how well poll works on osx though you probably know more about this than me.  

from celery.contrib.methods import task_method
ImportError: No module named methods

Any ideas about this?
