### ISSUE TITLE
pyOpenSSL not installed causes cryptic error

### ISSUE THREAD

**Issue by chorsley** [celery/celery#2450]
I'd like to spend more time to work out a proper solution to this, but I'll leave this note for others.
When installing my Celery-based app on a new host, I got the following when trying to run:

```
[2015-01-12 17:50:23,275: ERROR/Worker-1] Process Worker-1
Traceback (most recent call last):
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap
    self.run()
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 286, in run
    self.after_fork()
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 389, in after_fork
    self.initializer(*self.initargs)
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 81, in process_initializer
    app=app)
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 183, in build_tracer
    request_stack = task.request_stack
AttributeError: 'mytask' object has no attribute 'request_stack'
[2015-01-12 17:50:24,303: ERROR/MainProcess] Unrecoverable error: ValueError('dictionary update sequence element #0 has length 1; 2 is required',)
Traceback (most recent call last):
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 569, in start
    replies = I.hello(c.hostname, revoked._data) or {}
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/app/control.py", line 112, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/app/control.py", line 71, in _request
    timeout=self.timeout, reply=True,
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/app/control.py", line 57, in _prepare
    by_node = flatten_reply(reply)
  File "/tmp/agent/venv/local/lib/python2.7/site-packages/celery/app/control.py", line 32, in flatten_reply
    nodes.update(item)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

After some digging around and trapping another exception directly at celery/app/task.py in Task.bind(), specifically the call to ```conf = app.conf```, I could get the actual exception, which let me know pyOpenSSL was not installed. Installing it resolved this issue, and all was well.

I assume the actual exception is being swallowed up by something above it and discarded, and is not being displayed to the user. The net effect was that one of my tasks wasn't being bound, was not being registered to the app, and failed later on as ```request_stack``` never got set.

I'd suggest displaying a more specific error in  this section if pyOpenSSL is not installed.

**Comment by ask** [comment]
Are you using `setup_security`?

**Comment by chorsley** [comment]
Yes, and I'm now wondering if the the error I encountered above is actually a symptom of a config error I made? I ended up having some issues with serialization errors and found setting allowed_serializers  explicitly helped, so settled on: ```setup_security(allowed_serializers=CELERY_ACCEPT_CONTENT)```, with

```
CELERY_TASK_SERIALIZER = 'auth'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['application/json', 'json']
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
