### ISSUE TITLE
TypeError when executing chain.get() and group.get()  (exceptions must be old-style classes)

### ISSUE THREAD

**Issue by buckensl** [celery/celery#2458]
Using celery 3.1.17 with MongoDB as a broker and result backend

If a chain/group subtask raises an exception, following TypeErros is raised when exectuing result.get()
```
TypeError: exceptions must be old-style classes or derived from BaseException, not dict
```

```
In [7]: c = chain(tasks.app_raise.si(), tasks.ok.si())

In [8]: res = c.apply_async()

In [9]: res.get()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-8bb969b0b8af> in <module>()
----> 1 res.get()

/opt/ampli/apps/taskmgr/venv/lib/python2.7/site-packages/celery/result.py in get(self, timeout, propagate, interval, no_ack, follow_parents, EXCEPTION_STATES, PROPAGATE_STATES)
    156         if follow_parents and propagate and self.parent:
    157             on_interval = self._maybe_reraise_parent_error
--> 158             on_interval()
    159 
    160         if self._cache:

/opt/ampli/apps/taskmgr/venv/lib/python2.7/site-packages/celery/result.py in _maybe_reraise_parent_error(self)
    180     def _maybe_reraise_parent_error(self):
    181         for node in reversed(list(self._parents())):
--> 182             node.maybe_reraise()
    183 
    184     def _parents(self):

/opt/ampli/apps/taskmgr/venv/lib/python2.7/site-packages/celery/result.py in maybe_reraise(self)
    270     def maybe_reraise(self):
    271         if self.state in states.PROPAGATE_STATES:
--> 272             raise self.result
    273 
    274     def build_graph(self, intermediate=False, formatter=None):

TypeError: exceptions must be old-style classes or derived from BaseException, not dict
```
Probably introduced in https://github.com/celery/celery/commit/c998f50cc58809718d09780439fe94bb3fa0252b

**Comment by manneorama** [comment]
Seeing the same problem on celery 3.1.17.
Broker: redis
Result backend: MongoDB

Example code triggering the error:
```python
@app.task
def exceptional_add(x, y):
    if x == 15:
        raise Exception('sausages')
    return x + y

@app.task
def finalizer():
    pass

res = chord((exceptional_add.s(i, i) for i in xrange(20)), finalizer.si())
res.get()
```

**Comment by marians** [comment]
Also with Celery 3.1.17 on Python 2.7.3, I am seeing this issue.

Worker log:
```
INFO MainProcess: Received task: webapp.utils.get_random_success[728e3e74-8ceb-41f7-8f82-9641c2c5b07d] eta:[2015-02-15 12:38:37.027977+00:00]
INFO MainProcess: Task webapp.utils.get_random_success[728e3e74-8ceb-41f7-8f82-9641c2c5b07d] retry: Retry in 3s
ERROR MainProcess: Task webapp.utils.get_random_success[728e3e74-8ceb-41f7-8f82-9641c2c5b07d] raised unexpected: MaxRetriesExceededError("Can't retry webapp.utils.get_random_success[728e3e74-8ceb-41f7-8f82-9641c2c5b07d] args:() kwargs:{}",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/webapp/tasks.py", line 15, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/webapp/utils.py", line 282, in get_random_success
    raise self.retry()
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 665, in retry
    self.name, request.id, S.args, S.kwargs))
MaxRetriesExceededError: Can't retry webapp.utils.get_random_success[728e3e74-8ceb-41f7-8f82-9641c2c5b07d] args:() kwargs:{}
```

Log from the calling webapp:
```
192.168.59.3 - - [15/Feb/2015 12:38:37] "GET /api/random_retry HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/webapp/api.py", line 213, in random_retry
    result = the_task.wait(propagate=True)
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 175, in get
    raise meta['result']
TypeError: exceptions must be old-style classes or derived from BaseException, not dict
```

Function in the webapp calling the task:

```python
@flaskapp.route("/api/random_retry", methods=["GET"])
def random_retry():
    start = time.time()
    the_task = utils.get_random_success.delay()
    try:
        result = the_task.wait()
        return json.jsonify({
            "result": result,
            "duration": time.time() - start
        })
    except MaxRetriesExceededError, e:
        raise ApiException("Maximum retries exceeded", status_code=500)
```

The task itself (`webapp.utils.get_random_success`):

```python
@celery.task(bind=True, default_retry_delay=3, max_retries=1)
def get_random_success(self):
    """
    This task will fail in 50 percent of all attempts
    and then be retried.
    """
    succeed = random.choice((True, False))
    if succeed == False:
        raise self.retry()
    return succeed
```

The celery app is created exactly as described here: http://flask.pocoo.org/docs/0.10/patterns/celery/

**Comment by marians** [comment]
When I change the `the_task.wait()` call to `the_task.wait(propagate=False)` I can inspect the returned value from what corresponds to [celery/result.py L178](https://github.com/celery/celery/blob/master/celery/result.py#L178) in master. It is of type `dict` and looks like this:

```python
{
    "exc_message": "Can't retry webapp.utils.get_random_success[5fb1819a-1297-4e77-b0dd-37f4309df71e] args:() kwargs:{}",
    "exc_type": "MaxRetriesExceededError"
}
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
