### ISSUE TITLE
Unrecoverable ValueError on exception unpickle

### ISSUE THREAD

**Issue by j00bar** [celery/celery#2466]
Howdy --

I'm getting the following trace:

```
[2015-01-23 12:19:08,775: ERROR/MainProcess] Unrecoverable error: TypeError('__init__() takes at least 2 arguments (1 given)', <class 'django.core.exceptions.ValidationError'>, ())
Traceback (most recent call last):
  File "/virtualenv/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/virtualenv/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/virtualenv/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/virtualenv/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/virtualenv/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/virtualenv/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/virtualenv/local/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/virtualenv/local/lib/python2.7/site-packages/kombu/async/hub.py", line 324, in create_loop
    cb(*cbargs)
  File "/virtualenv/local/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 278, in on_result_readable
    next(it)
  File "/virtualenv/local/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 255, in _recv_message
    message = load(BytesIO(bufv))
TypeError: ('__init__() takes at least 2 arguments (1 given)', <class 'django.core.exceptions.ValidationError'>, ())
```

This is using celery 3.1.17 consuming messages published by celery 3.0.12

Interestingly, I was getting the same result with a different stack trace while using celery 3.0.24 on the consumer, with stack traces that matched celery/billiard#12 - which was allegedly fixed in celery 3.0.6

Any help would be appreciated - thanks!

-jag

**Comment by haritamar** [comment]
Hello, we just encountered this as well (same stack trace, different exception).
@j00bar did you understand this issue eventually?

**Comment by j00bar** [comment]
I can't say I ever did - and I don't remember what I ended up doing instead.

**Comment by ask** [comment]
Must be using Django 1.6 where ValidationError incorrectly missed calling Exception.__init__.
