### ISSUE TITLE
Worker tries to create 'celeryev' exchange even though events, gossip, and heartbeat are disabled

### ISSUE THREAD

**Issue by CakeOfPiece** [celery/celery#2483]
It results in error message:

```
[2015-02-03 15:22:48,754: ERROR/MainProcess] Unrecoverable error: AccessRefused(403, "ACCESS_REFUSED - access to exchange 'celeryev' in vhost '/' refused for user 'user1'", (40, 10), 'Exchange.declare')
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.3/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python3.3/dist-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/lib/python3.3/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.3/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python3.3/dist-packages/celery/worker/consumer.py", line 508, in start
    enabled=self.send_events, groups=self.groups,
  File "/usr/local/lib/python3.3/dist-packages/celery/events/__init__.py", line 150, in __init__
    self.enable()
  File "/usr/local/lib/python3.3/dist-packages/celery/events/__init__.py", line 169, in enable
    serializer=self.serializer)
  File "/usr/local/lib/python3.3/dist-packages/kombu/messaging.py", line 85, in __init__
    self.revive(self._channel)
  File "/usr/local/lib/python3.3/dist-packages/kombu/messaging.py", line 218, in revive
    self.declare()
  File "/usr/local/lib/python3.3/dist-packages/kombu/messaging.py", line 105, in declare
    self.exchange.declare()
  File "/usr/local/lib/python3.3/dist-packages/kombu/entity.py", line 166, in declare
    nowait=nowait, passive=passive,
  File "/usr/local/lib/python3.3/dist-packages/amqp/channel.py", line 620, in exchange_declare
    (40, 11),  # Channel.exchange_declare_ok
  File "/usr/local/lib/python3.3/dist-packages/amqp/abstract_channel.py", line 69, in wait
    return self.dispatch_method(method_sig, args, content)
  File "/usr/local/lib/python3.3/dist-packages/amqp/abstract_channel.py", line 87, in dispatch_method
    return amqp_method(self, args)
  File "/usr/local/lib/python3.3/dist-packages/amqp/channel.py", line 241, in _close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.AccessRefused: Exchange.declare: (403) ACCESS_REFUSED - access to exchange 'celeryev' in vhost '/' refused for user 'user1'
```

Event bootstep is always created and started, and it always create Dispatcher with enabled=True argument https://github.com/celery/celery/blob/master/celery/worker/consumer.py#L533

**Comment by CakeOfPiece** [comment]
Anybody?
