### ISSUE TITLE
`celery.http_dispatch` always fail due to celery trying to handle bytes as string

### ISSUE THREAD

**Issue by clarkorz** [celery/celery#2499]
Hi, I'm trying celery as tasks distributor for my nodejs project. I create a minimal celery project which only imports `celery.task.http` module. 

```js
// will be exposed to route /api/tasks/status
Task.status = function (callback) {
    callback(null, { status: 'success', retval: 'hello' });
  };

// call task using node-celery
var task = client.createTask('celery.http_dispatch');
var result = task.call([], { url: 'http://172.16.208.1:3000/api/tasks/status', method: 'GET' });
```
```
curl http://172.16.208.1:3000/api/tasks/status
{"status":"success","retval":"hello"}
curl -I http://172.16.208.1:3000/api/tasks/status
HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin, Accept-Encoding
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Content-Length: 37
ETag: W/"25-d3757658"
Date: Thu, 12 Feb 2015 03:45:48 GMT
Connection: keep-alive
```

The web hook is executed successfully but celery fail to parse the json response.

```
celery -A default worker -l DEBUG
...
[2015-02-07 12:05:42,004: INFO/MainProcess] Received task: celery.http_dispatch[329a1353-f2e8-40db-bd02-89d66dbe1386]
[2015-02-07 12:05:42,004: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f8e513e3400> (args:('celery.http_dispatch', '329a1353-f2e8-40db-bd02-89d66dbe1386', [], {'url': 'http://172.16.208.1:3000/api/tasks/status', 'method': 'GET'}, {'args': [], 'headers': {}, 'is_eager': False, 'kwargs': {'url': 'http://172.16.208.1:3000/api/tasks/status', 'method': 'GET'}, 'task': 'celery.http_dispatch', 'id': '329a1353-f2e8-40db-bd02-89d66dbe1386', 'delivery_info': {'redelivered': False, 'routing_key': 'celery', 'priority': None, 'exchange': ''}, 'hostname': 'celery@clarkorz', 'reply_to': None, 'group': None, 'correlation_id': None}) kwargs:{})
[2015-02-07 12:05:42,010: DEBUG/MainProcess] Task accepted: celery.http_dispatch[329a1353-f2e8-40db-bd02-89d66dbe1386] pid:48307
[2015-02-07 12:05:42,027: ERROR/MainProcess] Task celery.http_dispatch[329a1353-f2e8-40db-bd02-89d66dbe1386] raised unexpected: TypeError('initial_value must be str or None, not bytes',)
Traceback (most recent call last):
  File "/opt/celery/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/celery/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/celery/lib/python3.4/site-packages/celery/task/http.py", line 190, in dispatch
    ).dispatch()
  File "/opt/celery/lib/python3.4/site-packages/celery/task/http.py", line 157, in dispatch
    return extract_response(raw_response)
  File "/opt/celery/lib/python3.4/site-packages/celery/task/http.py", line 70, in extract_response
    payload = loads(raw_response)
  File "/opt/celery/lib/python3.4/site-packages/anyjson/__init__.py", line 135, in loads
    return implementation.loads(value)
  File "/opt/celery/lib/python3.4/site-packages/anyjson/__init__.py", line 98, in loads
    return self._filedecode(StringIO(s))
TypeError: initial_value must be str or None, not bytes
```

I'm not familiar with python or celery, but I think `StringIO` only accepts string, so `raw_response` is a bytes array and should be decoded to a string.

**Comment by clarkorz** [comment]
My  minimal celery project only contains two files:

### default/celeryconfig.py
```python
## Broker settings.
BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost/0'

CELERY_IMPORTS = ("celery.task.http",)

## A whitelist of content-types/serializers to allow.
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
```

### default/celery.py
```python
from celery import Celery

app = Celery('tasks')
app.config_from_object('default.celeryconfig')

if __name__ == '__main__':
    app.start()
```
