### ISSUE TITLE
WorkerLostError doesn't seem to be calling task_failure callback

### ISSUE THREAD

**Issue by alkarimlalani** [celery/celery#2510]
I'm running a celery worker and I've configured the tasks.py file to have a task_failure callback as such:

```python
@task_failure.connect
def log_failure(*args, **kwargs):
    print "FAILED TASK"
    # do other work like logging the error and alerting someone
```

When I have a regular python error it calls my log_failure method just fine as you can see from the console output below:
```
[2015-02-19 17:28:22,820: WARNING/Worker-1] FAILED TASK
[2015-02-19 17:28:22,829: ERROR/MainProcess] Task tasks.test[c8677814-b212-430a-b847-a4ce3beaeb43] raised unexpected: ZeroDivisionError('integer division or modulo by zero',)
Traceback (most recent call last):
  File "/Users/alkarim/Virtualenvs/work/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/alkarim/Virtualenvs/work/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
```

My task also spawns off processes (using billiard of course) and the processes do some computations in C code that is called via the C extension modules. Sometimes the C code will throw an error because of a segfault, and I would hope that the task_failure callback is called, but this doesn't seem to be the case. In fact, if you look at the callback below, celery knows an error was thrown since it logs it in the same format as all unexpected errors but doesn't call the task_failure callback and hence there isn't a "FAILED TASK" print statement:
```
[2015-02-19 17:39:32,054: WARNING/Worker-1] triangle area: 11.54
[2015-02-19 17:39:36,709: ERROR/MainProcess] Process 'Worker-1' pid:44276 exited with 'signal 11 (SIGSEGV)'
[2015-02-19 17:39:36,725: ERROR/MainProcess] Task tasks.test[ac5081fc-9dfd-4f50-8bf1-627798dd21f4] raised unexpected: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).',)
Traceback (most recent call last):
  File "/Users/alkarim/Virtualenvs/work/lib/python2.7/site-packages/billiard/pool.py", line 1169, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
```

Curiously enough, I set up sending error emails, and I expected that it wouldn't send me an email for the segfault since it doesn't call the task_failure callback, but I was surprised to find that it actually does send the error emails. I looked at the source code and the logic seems to be here:
https://github.com/celery/celery/blob/a6ff6c1d62d8747c60eb665e915b568755ab2f90/celery/app/trace.py

In the "handle_failure" function it should call the task_failure function on line 195, before it sends an email (which is encapsulated in the _log_error function on line 200).

Any idea why it doesn't call the task_failure callback?

**Comment by mpermana** [comment]
Because your child worker process crashes with SEGSEGV, there is no way the child can call on_failure after a segfault (imagine if its like your power has been shut off)
