### ISSUE TITLE
Celery worker error in high available context

### ISSUE THREAD

**Issue by faxioman** [celery/celery#2527]
Using:
- celery==3.1.17
- amqp==1.4.6
- billiard==3.3.0.19
- kombu==3.0.24
- Django==1.7.5

with these settings:
```python
BROKER_URL = 'amqp://demo:demo@rabbitcluster:5672/demo'
CELERY_TASK_RESULT_EXPIRES = 600
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'amqp'
CELERY_RESULT_EXCHANGE = 'tasks.result.direct'
CELERY_RESULT_PERSISTENT = True
CELERY_DEFAULT_EXCHANGE = 'tasks.direct'
CELERY_DEFAULT_ROUTING_KEY = 'tasks'
CELERY_RESULT_EXCHANGE_TYPE = 'direct'
```

The broker is a cluster of three rabbit server (v 3.4.4) with active/active queues (queue policy is ha-mode:	all, ha-sync-mode: automatic for '*') balanced using haproxy with this configuration:
```
backend rabbitmq_amqp
    mode tcp
    balance roundrobin
    timeout connect 5s
    timeout server 120s
    option redispatch
    retries 3
    option tcpka
    server server1 srvrabbit1:5672 check inter 5s rise 2 fall 3
    server server2 srvrabbit2:5672 check inter 5s rise 2 fall 3
    server server3 srvrabbit3:5672 check inter 5s rise 2 fall 3

frontend rabbitmq_amqp
    bind 172.16.110.10:5672
    mode tcp
    option tcpka
    option tcplog
    timeout client 120s
    default_backend rabbitmq_amqp
```

When I stop the rabbit node where my celery worker is connected to, I can see a connection retry:
```
Connection to broker lost. Trying to re-establish the connection...
```
and the worker correctly opens a new connection.
But, from that moment, some messages are no more correctly processed, and I can see this error in worker log:
```
[2015-03-03 08:06:36,171: CRITICAL/MainProcess] Task home.tasks.somma[d3b3981f-a8ed-4954-8703-e5d16cd2be78] INTERNAL ERROR: TypeError("'NoneType' object has no attribute '__getitem__'",)
Traceback (most recent call last):
  File "/Users/fabio/Desktop/prova_rabbit_env/lib/python2.7/site-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/Users/fabio/Desktop/prova_rabbit_env/lib/python2.7/site-packages/celery/backends/amqp.py", line 136, in store_result
    delivery_mode=self.delivery_mode,
  File "/Users/fabio/Desktop/prova_rabbit_env/lib/python2.7/site-packages/kombu/messaging.py", line 168, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/Users/fabio/Desktop/prova_rabbit_env/lib/python2.7/site-packages/kombu/connection.py", line 448, in _ensured
    self._do_close_self()
  File "/Users/fabio/Desktop/prova_rabbit_env/lib/python2.7/site-packages/kombu/connection.py", line 288, in _do_close_self
    self.maybe_close_channel(self._default_channel)
  File "/Users/fabio/Desktop/prova_rabbit_env/lib/python2.7/site-packages/kombu/connection.py", line 280, in maybe_close_channel
    channel.close()
  File "/Users/fabio/Desktop/prova_rabbit_env/lib/python2.7/site-packages/amqp/channel.py", line 179, in close
    (20, 41),  # Channel.close_ok
  File "/Users/fabio/Desktop/prova_rabbit_env/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods)
  File "/Users/fabio/Desktop/prova_rabbit_env/lib/python2.7/site-packages/amqp/connection.py", line 225, in _wait_method
    method_queue = self.channels[channel_id].method_queue
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Debugging amqp/connection.py I see that self.channels is None.
After restarting the worker, all messages are correctly processed. I know that I can put all my rabbit nodes as array in BROKER_URL settings, but this is an unwanted behavior: I want to automatically add and remove rabbit nodes in haproxy using traffic monitoring rules... so, my python/django apps must not know the real rabbit nodes url.

**Comment by thedrow** [comment]
Do you have a VM or a Vagrantfile that I can use to reproduce this setup?

**Comment by ask** [comment]
This code path does not even exist anymore in master after the big amqp client refactor.

I added another check, though I don't think it will reach that point.

Please open a new issue if it does not work with the development version
