### ISSUE TITLE
Celery imports dependencies from outside of virtual envs

### ISSUE THREAD

**Issue by wrycu** [celery/celery#2543]
Running celery within a venv results in it attempting to import modules from python paths are outside of the current virtual environment.

```python
(venv)[wrycu@host] ~/code
$ celery -A run.py worker
Traceback (most recent call last):
  File "/home/user/wrycu/.venv/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/base.py", line 465, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/base.py", line 485, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/app/utils.py", line 232, in find_app
    sym = imp(app)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/home/user/wrycu/custom/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named py
```
Py is installed in the venv:
```
(venv)[wrycu@host] ~/code
$ pip freeze | grep py
py==1.4.26
```
Leaving the venv and installing py corrects the error:
```python
(venv)[wrycu@host] ~/code
$ deactivate
[wrycu@host] ~/code                                                                                                                                             
$ pip install py
Downloading/unpacking py
  Downloading py-1.4.26.tar.gz (190kB): 190kB downloaded
  Running setup.py (path:/tmp/pip_build_wrycu/py/setup.py) egg_info for package py

Installing collected packages: py
  Running setup.py install for py

Successfully installed py
Cleaning up...
```

```
[wrycu@host] ~/code
$ source ~/.venv/venv/bin/activate
```

```python
(venv)[wrycu@host] ~/code
$ celery -A run.py worker
Traceback (most recent call last):
  File "/home/user/wrycu/.venv/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/base.py", line 465, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/base.py", line 485, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/app/utils.py", line 229, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/bin/base.py", line 488, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/user/wrycu/.venv/venv/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/home/user/wrycu/custom/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named run
```

Path variables are set properly, as far as I can tell:
> VIRTUAL_ENV=/home/user/wrycu/.venv/venv
> PATH=/home/user/wrycu/.venv/venv/bin:/home/user/wrycu/custom/bin:

**Comment by marioandresgonzalez** [comment]
I can think in two options now

1) By any change, have you got more than one version of python installed. The behaviour you show, maybe is because the virtualenv was created with a different python binary.
 
2) what's your tasks module name? if your filename is run.py, shouldn't it be just "celery -A run worker"? (notice I removed the ".py")

Hope that helps

**Comment by wrycu** [comment]
1) Yes - there's a system python (2.6.6), a locally installed python (2.7.8 -- this is in my path and exists before the system python), and my venv (created from the locally installed python).  Installing modules into the local python install removes the problem.

2) Yeah, I'm still working out the kinks of how to get it to work. 

Wait, are you saying that this weird behavior is happening because I was running it incorrectly? (e.g. run.py instead of simply run)

**Comment by marioandresgonzalez** [comment]
Yes, that might be why, the command "celery worker -A <module>" doesn't expects a source file but a module instead. Reading in your example try this:
(venv)[wrycu@host] $ celery -A run worker

And also, as you say you've got 2 different python installations, I'd check what the python version is inside the .venv directory and when you install the module, make sure you're using the same. I say that because I've seen those issues before with virtualenv.

**Comment by wrycu** [comment]
Celery is installed inside of the venv.  The venv is running 2.7.8.

I'll confirm that this is the issue tomorrow and if it is, close this out.

Thanks for explaining!

**Comment by malinoff** [comment]
@wrycu yes, as @marioandresgonzalez said, you should specify module name in `-A`, not file name.
