### ISSUE TITLE
Autoscale can't scale down

### ISSUE THREAD

**Issue by arnauorriols** [celery/celery#2559]
When using autoscale, after having scaled up successfully, this error appears:

```
[2015-04-01 11:31:12,431: ERROR/MainProcess] Autoscaler: scale_down: AttributeError("'ForkProcess' object has no attribute 'terminate_controlled'",)
Traceback (most recent call last):
  File "/opt/miimetiq/env/lib/python2.7/site-packages/celery/worker/autoscale.py", line 143, in _shrink
    self.pool.shrink(n)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/billiard/pool.py", line 1205, in shrink
    worker.terminate_controlled()
AttributeError: 'ForkProcess' object has no attribute 'terminate_controlled'
```

The worker is started with:

    celery worker -A my.worker -n my.worker.local --autoscale=4,2 --without-gossip --without-mingle --without-heartbeat

Celery report:

```bash
$ celery report
software -> celery:3.2.0a2 (DEV) kombu:3.1.0a1 py:2.7.9
                    billiard:3.4.0.0b1 py-amqp:2.0.0a1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

Thanks.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Autoscale will be undocumented in 4.0 release
