### ISSUE TITLE
TypeError decoding an exception when no exception is specified in retry()

### ISSUE THREAD

**Issue by k21** [celery/celery#2560]
If the `exc` parameter to Task.retry() is not specified, the task is retried but a `TypeError` is raised in the code waiting for the result.

Traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/k21/projects/Project/env/lib/python3.4/site-packages/celery/result.py", line 169, in get
    no_ack=no_ack,
  File "/home/k21/projects/Project/env/lib/python3.4/site-packages/celery/backends/base.py", line 216, in wait_for
    meta = self.get_task_meta(task_id)
  File "/home/k21/projects/Project/env/lib/python3.4/site-packages/celery/backends/base.py", line 292, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/home/k21/projects/Project/env/lib/python3.4/site-packages/celery/backends/base.py", line 502, in _get_task_meta_for
    return self.decode_result(meta)
  File "/home/k21/projects/Project/env/lib/python3.4/site-packages/celery/backends/base.py", line 191, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/home/k21/projects/Project/env/lib/python3.4/site-packages/celery/backends/base.py", line 187, in meta_from_decoded
    meta['result'] = self.exception_to_python(meta['result'])
  File "/home/k21/projects/Project/env/lib/python3.4/site-packages/celery/backends/base.py", line 172, in exception_to_python
    from_utf8(exc['exc_type']), __name__)(exc['exc_message'])
TypeError: 'NoneType' object is not subscriptable
```

Virtual environment packages:
```
Flask==0.10.1
Flask-Script==2.0.5
Jinja2==2.7.3
Mako==1.0.1
MarkupSafe==0.23
SQLAlchemy==0.9.9
Werkzeug==0.10.4
alembic==0.7.5.post2
amqp==1.4.6
anyjson==0.3.3
billiard==3.3.0.19
celery==3.1.17
itsdangerous==0.24
kombu==3.0.24
psycopg2==2.6
pytz==2015.2
redis==2.10.3
requests==2.6.0
```

Celery configuration:
```
BROKER_URL = 'redis+socket:///var/lib/redis/redis.sock'
BROKER_TRANSPORT_OPTIONS = {
    'fanout_prefix': True,
    'fanout_patterns': True,
}
CELERY_RESULT_BACKEND = 'redis+socket:///var/lib/redis/redis.sock'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
```

Task code:
```
from myproject.tasks import celery

@celery.task(bind = True)
def task_name(self):
    self.retry()
```

**Comment by rslinckx** [comment]
I have the same error. Did you find any workaround ?

**Comment by kevinharvey** [comment]
I also get this error.

**Comment by kevinharvey** [comment]
Looks like this is fixed, but hasn't made it to PyPI yet https://github.com/celery/celery/issues/2687

**Comment by ask** [comment]
I'm working on releasing a new version this Friday

**Comment by kevinharvey** [comment]
Thanks! Just to close the loop on this, and by way of confirmation, I didn't see the error anymore after installing Celery from the master branch.
