### ISSUE TITLE
RuntimeError: Set changed size during iteration: \worker\control.py

### ISSUE THREAD

**Issue by patrickwolf** [celery/celery#2567]
I often receive this error in my Celery log files. Afterwards the worker seems to stop responding (at least Flower can't communicate with it anymore)
Is it a bug or a configuration issue?
Thanks a lot,
Patrick

```
RuntimeError: Set changed size during iteration
"2015-04-07 14:35:08,868",sync_admin,DEV1,S599394,kombu.pidbox,ERROR,"pidbox command error: RuntimeError('Set changed size during iteration',)"
Traceback (most recent call last):
  File "\\work\app_config\release\system\software\python\2.7.1.86832\Windows_NT.i386_virtualenv\celery\lib\site-packages\kombu\pidbox.py", line 105, in dispatch
    reply = handle(method, kwdict(arguments))
  File "\\work\app_config\release\system\software\python\2.7.1.86832\Windows_NT.i386_virtualenv\celery\lib\site-packages\kombu\pidbox.py", line 123, in handle_call
    return self.handle(method, arguments)
  File "\\work\app_config\release\system\software\python\2.7.1.86832\Windows_NT.i386_virtualenv\celery\lib\site-packages\kombu\pidbox.py", line 120, in handle
    return self.handlers[method](self.state, **arguments)
  File "\\work\app_config\release\system\software\python\2.7.1.86832\Windows_NT.i386_virtualenv\celery\lib\site-packages\celery\worker\control.py", line 217, in dump_active
    for request in worker_state.active_requests]
```

```
Environment:
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.2
            billiard:3.3.0.19 redis:2.10.3
platform -> system:Windows arch:32bit, WindowsPE imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:redis results:redis://192.168.210.29:6379/0

BROKER_TRANSPORT_OPTIONS: {    'visibility_timeout': 3600}
CELERY_TASK_SERIALIZER: 'json'
CELERY_ENABLE_UTC: True
CELERY_ACCEPT_CONTENT: ['json', 'yaml']
CELERY_RESULT_SERIALIZER: 'json'
CELERYD_HIJACK_ROOT_LOGGER: False
BROKER_URL: 'redis://192.168.210.29:6379/0'
CELERY_RESULT_BACKEND: 'redis://192.168.210.29:6379/0'
CELERYD_POOL_RESTARTS: True
```

**Comment by thedrow** [comment]
Can you please provide a failing test case that I can work with?
