### ISSUE TITLE
crashes without exception when cannot find libraries required for cache backend

### ISSUE THREAD

**Issue by tbazadaykin** [celery/celery#2572]
Celere crashes without any exception when using memcached as result backend and pylibmc (or python-memcached) are not installed.

This happens even if the log level set to DEBUG.

I think it would be good to bring some kind of warning, and not just quietly closed.

Celery 3.1.17

**Comment by malinoff** [comment]
Could you please show your configs and how do you run celery with the output?

**Comment by ask** [comment]
Client:

<pre>
>>> add.delay(2, 2)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/devel/celery/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/opt/devel/celery/celery/app/task.py", line 560, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/opt/devel/celery/celery/app/base.py", line 348, in send_task
    self.backend.on_task_call(P, task_id)
  File "/opt/devel/kombu/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/devel/celery/celery/app/base.py", line 625, in backend
    return self._get_backend()
  File "/opt/devel/celery/celery/app/base.py", line 444, in _get_backend
    return backend(app=self, url=url)
  File "/opt/devel/celery/celery/backends/cache.py", line 113, in __init__
    self.Client, self.key_t = backends[self.backend]()
  File "/opt/devel/celery/celery/backends/cache.py", line 55, in get_best_memcache
    is_pylibmc, memcache, key_t = import_best_memcache()
  File "/opt/devel/celery/celery/backends/cache.py", line 47, in import_best_memcache
    raise ImproperlyConfigured(REQUIRES_BACKEND)
ImproperlyConfigured: The memcached backend requires either pylibmc or python-memcache
</pre>

Worker:
<pre>
[2015-05-06 16:14:31,965: ERROR/ForkPoolWorker-8] Process ForkPoolWorker-8
Traceback (most recent call last):
  File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/billiard-3.4.0.0b1-py2.7-macosx-10.6-intel.egg/billiard/process.py", line 298, in _bootstrap
    self.run()
  File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/billiard-3.4.0.0b1-py2.7-macosx-10.6-intel.egg/billiard/process.py", line 112, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/billiard-3.4.0.0b1-py2.7-macosx-10.6-intel.egg/billiard/pool.py", line 290, in __call__
    self.after_fork()
  File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/billiard-3.4.0.0b1-py2.7-macosx-10.6-intel.egg/billiard/pool.py", line 393, in after_fork
    self.initializer(*self.initargs)
  File "/opt/devel/celery/celery/concurrency/prefork.py", line 81, in process_initializer
    app=app)
  File "/opt/devel/celery/celery/app/trace.py", line 161, in build_tracer
    backend = task.backend
  File "/opt/devel/celery/celery/app/task.py", line 919, in backend
    return self.app.backend
  File "/opt/devel/kombu/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/devel/celery/celery/app/base.py", line 625, in backend
    return self._get_backend()
  File "/opt/devel/celery/celery/app/base.py", line 444, in _get_backend
    return backend(app=self, url=url)
  File "/opt/devel/celery/celery/backends/cache.py", line 113, in __init__
    self.Client, self.key_t = backends[self.backend]()
  File "/opt/devel/celery/celery/backends/cache.py", line 55, in get_best_memcache
    is_pylibmc, memcache, key_t = import_best_memcache()
  File "/opt/devel/celery/celery/backends/cache.py", line 47, in import_best_memcache
    raise ImproperlyConfigured(REQUIRES_BACKEND)
ImproperlyConfigured: The memcached backend requires either pylibmc or python-memcached.
</pre>

**Comment by thedrow** [comment]
@tbazadaykin Can you provide a failing test case for us?

**Comment by tbazadaykin** [comment]
My bad. It was improperly configured logger.

**Comment by thedrow** [comment]
@tbazadaykin Thanks for letting us know.
