### ISSUE TITLE
error with "import celery"!

### ISSUE THREAD

**Issue by lovemoon0314** [celery/celery#2585]
```
[zht@localhost ~]$ python
Python 2.7.9 (default, Jan  7 2015, 11:52:44) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import celery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/celery-3.1.17-py2.7.egg/celery/__init__.py", line 130, in <module>
    from celery import five
  File "/usr/local/lib/python2.7/site-packages/celery-3.1.17-py2.7.egg/celery/five.py", line 51, in <module>
    from kombu.five import monotonic
  File "/usr/local/lib/python2.7/site-packages/kombu-3.0.24-py2.7.egg/kombu/five.py", line 77, in <module>
    librt = ctypes.CDLL('librt.so.1', use_errno=True)
TypeError: __init__() got an unexpected keyword argument 'use_errno'
```

**Comment by malinoff** [comment]
Could you please include celery and kombu versions?

**Comment by lovemoon0314** [comment]
@malinoff 
celery-3.1.17-py2.7.egg
kombu-3.0.24-py2.7.egg
thank you !

**Comment by malinoff** [comment]
Thanks, and how did you install celery?

**Comment by lovemoon0314** [comment]
@malinoff 
first:easy_install
then:pip
finally:source code
all faild ...

**Comment by malinoff** [comment]
Sorry, I'm unable to reproduce this:
```
(fresh)$ pip install celery
Collecting celery
  Downloading celery-3.1.17-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 516kB 748kB/s 
Collecting kombu<3.1,>=3.0.24 (from celery)
  Downloading kombu-3.0.24-py2.py3-none-any.whl (238kB)
    100% |████████████████████████████████| 241kB 1.5MB/s 
Collecting billiard<3.4,>=3.3.0.19 (from celery)
  Downloading billiard-3.3.0.20.tar.gz (150kB)
    100% |████████████████████████████████| 151kB 188kB/s 
Collecting pytz>dev (from celery)
  Downloading pytz-2015.2-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 479kB 462kB/s 
Collecting anyjson>=0.3.3 (from kombu<3.1,>=3.0.24->celery)
  Downloading anyjson-0.3.3.tar.gz
Collecting amqp<2.0,>=1.4.5 (from kombu<3.1,>=3.0.24->celery)
  Downloading amqp-1.4.6.tar.gz (77kB)
    100% |████████████████████████████████| 81kB 28kB/s 
Installing collected packages: anyjson, amqp, kombu, billiard, pytz, celery
  Running setup.py install for anyjson
  Running setup.py install for amqp
  Running setup.py install for billiard
Successfully installed amqp-1.4.6 anyjson-0.3.3 billiard-3.3.0.20 celery-3.1.17 kombu-3.0.24 pytz-2015.2
```
```
(fresh)$ pip freeze
amqp==1.4.6
anyjson==0.3.3
billiard==3.3.0.20
celery==3.1.17
kombu==3.0.24
pytz==2015.2
six==1.9.0
virtualenv==12.1.1
wheel==0.24.0
```
```
python
Python 3.4.2 (default, Jan 24 2015, 18:28:49) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import celery
>>> 
```

**Comment by PMickael** [comment]
Hi, it's seem to be a ctype error, with the arg : use_errno, before python 2.5 you have to install this package maybe you have an outdate version of ctype who are used by python 2.7, and with a redhat 4.4 maybe a little upgrade would be great 

Try this : 
```python
import ctypes
ctypes.CDLL('librt.so.1', use_errno=True)
```

Should not raise any error (on linux system).
Maybe pip install ctype --upgrade will fix the issue, or easy_install

**Comment by lovemoon0314** [comment]
@malinoff 
anyway,thank you very much for your help !

**Comment by lovemoon0314** [comment]
@PMickael 
it works!!!
the error just because i easy_install a redundant "ctpyes" with mistake version.
there is already a "ctypes" with python2.79 
just easy_install -m ctypes to fix it!
thank you very much !

**Comment by PMickael** [comment]
@lovemoon0314 
You're welcome
