### ISSUE TITLE
2 tests failed with 3.1.18

### ISSUE THREAD

**Issue by felixonmars** [celery/celery#2589]
Tested with Python 2.7.9 and PyMongo 3.0.1. Could not reproduce these errors with Celery 3.1.17.

```
======================================================================
FAIL: test_get_connection_no_connection_host (celery.tests.backends.test_mongodb.test_MongoBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-celery/src/celery-3.1.18-py2/celery/tests/backends/test_mongodb.py", line 102, in test_get_connection_no_connection_host
    auto_start_request=False)
  File "/usr/lib/python2.7/site-packages/mock.py", line 846, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: MongoClient(auto_start_request=False, host='mongodb://localhost:27017', max_pool_size=10)
Actual call: MongoClient(host='mongodb://localhost:27017', maxPoolSize=10)

======================================================================
FAIL: test_get_connection_no_connection_mongodb_uri (celery.tests.backends.test_mongodb.test_MongoBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-celery/src/celery-3.1.18-py2/celery/tests/backends/test_mongodb.py", line 117, in test_get_connection_no_connection_mongodb_uri
    auto_start_request=False)
  File "/usr/lib/python2.7/site-packages/mock.py", line 846, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: MongoClient(auto_start_request=False, host='mongodb://localhost:27017', max_pool_size=10)
Actual call: MongoClient(host='mongodb://localhost:27017', maxPoolSize=10)

----------------------------------------------------------------------
```

**Comment by malinoff** [comment]
These tests are failing because ``pymongo.MongoClient``'s constructor has been changed.
I believe since ``auto_start_request`` was deprecated in pymongo 2.x series, we can simply remove this parameter from the constructor.

``max_pool_size`` is trickier. It has been renamed to ``maxPoolSize`` and I don't think that checking pymongo's version in tests is something we should really do.

@ask what do you think? How about supporting pymongo 3.x only in celery 3.2 series and pymongo < 3.x only in celery 3.1 series?
