### ISSUE TITLE
nameerror on using custom task

### ISSUE THREAD

**Issue by raghuramos1987** [celery/celery#2603]
I am trying to use a custom task like in the example here http://jsatt.com/blog/class-based-celery-tasks/

```
import celery
from celery import Celery
cur_app = Celery('data_processor',
broker='redis+socket:///tmp/redis.sock',
backend='redis+socket:///tmp/redis.sock',
include=['task'])
if __name__ == '__main__':
    cur_app.start()

class Custom(celery.Task):

    def run(self):
        return 'hi'
    def bind(self, app):
        return super(Custom, self).bind(cur_app)
```

But, when I start the app I get this 

```
    return super(Custom, self).bind(cur_app)
NameError: global name 'Custom' is not defined
```

**Comment by raghuramos1987** [comment]
I also changed bind to be decorated with classmethod (since it looks like its supposed to be). But, I still get the same error. Shouldnt this not be the case since celery.Task is a new-style class. 

```
return celery.Task.bind(cur_app)
```
works.

**Comment by jerryhebert** [comment]
You just need to move your custom class definition above the ```cur_app.start()```, it's not in scope.

```
(vpython)[12:40:16:~]% cat t.py
def foo():
    c = C()

if __name__ == '__main__':
    foo()

class C(object):
    def __init__(self):
        print 'made C'

(vpython)[12:40:18:~]% python t.py
Traceback (most recent call last):
  File "t.py", line 5, in <module>
    foo()
  File "t.py", line 2, in foo
    c = C()
NameError: global name 'C' is not defined
(vpython)[12:40:21:~]% 
```

Versus:

```
(vpython)[12:41:01:~]% cat t.py
def foo():
    c = C()

class C(object):
    def __init__(self):
        print 'made C'

if __name__ == '__main__':
    foo()
(vpython)[12:41:04:~]% python t.py
made C
(vpython)[12:41:05:~]%
```

**Comment by raghuramos1987** [comment]
Duh... That was stupid. But, it still doesnt work. 

```
import celery
from celery import Celery

cur_app = Celery('data_processor',
    include=['task'])
cur_app.conf.update(
     CELERY_RESULT_BACKEND='redis+socket:///tmp/redis.sock',
     BROKER_URL='redis+socket:///tmp/redis.sock')

class Custom(celery.Task):

    def run(self):
        return 'hi'

    @classmethod
    def bind(self, app):
        return super(Custom, self).bind(cur_app)

if __name__ == '__main__':
    cur_app.start()
```

**Comment by malinoff** [comment]
@raghuramos1987 could you please include the traceback?

**Comment by raghuramos1987** [comment]
Running this code
```
import celery
from celery import Celery


cur_app = Celery('data_processor',
include=['task'])
cur_app.conf.update(
CELERY_RESULT_BACKEND='redis+socket:///tmp/redis.sock',
BROKER_URL='redis+socket:///tmp/redis.sock')

class Custom(celery.Task):

    def run(self):
        return 'hi'

    @classmethod
    def bind(self, app):
        return super(Custom, self).bind(cur_app)

if __name__ == '__main__':
    cur_app.start()
```
This is the error
```
Traceback (most recent call last):
  File "task.py", line 11, in <module>
    class Custom(celery.Task):
  File "/home/raghu/git/env/lib/python2.7/site-packages/celery/app/task.py", line 201, in __new__
    instance.bind(app)
  File "task.py", line 18, in bind
    return super(Custom, self).bind(cur_app)
NameError: global name 'Custom' is not defined
```

This is the traceback. I looked into it a bit more. When I start the worker with --autoreload without bind overridden and then adding bind, the trace back is this 

```
  File "/home/raghu/git/env/lib/python2.7/site-packages/celery/utils/imports.py", line 108, in reload_from_cwd
    return reloader(module)
  File "/home/raghu/git/task.py", line 11, in <module>
    class Custom(celery.Task):
  File "/home/raghu/git/env/lib/python2.7/site-packages/celery/app/task.py", line 201, in __new__
    instance.bind(app)
  File "/home/raghu/git/task.py", line 18, in bind
    return super(Custom, self).bind(cur_app)
TypeError: Error when calling the metaclass bases
    super(type, obj): obj must be an instance or subtype of type
```

**Comment by raghuramos1987** [comment]
FWIW. I got around this by just calling it as follows.

```
custom = CustomTask
custom.bind(app)
```

And adding a wrapper around it for modularity.
Then you dont need to override bind at all. But, it would be cleaner to override bind correctly I'd say.

**Comment by ask** [comment]
Your task is not `abstract=True`, so it's bound immediately during class creation, that means in effect `Custom` is _really not defined at this point_.

If you want the task to be bound to a specific app you can do it like `app.Task` and set the `_app` attribute:

    class Custom(celery.Task):
        _app = cur_app

    def run(self):
        return 'hi'


or simply:


    class Custom(cur_app.Task):
        
        def run(self):
            return 'hi'

**Comment by raghuramos1987** [comment]
thanks @ask !
