### ISSUE TITLE
on_worker_process_init ORA-03113 or ORA-03135

### ISSUE THREAD

**Issue by ppiccolo** [celery/celery#2646]
Hi 

I'm using celery 3.1.18 with django 1.7.4 redis as result backend rabbitMQ as message queue and Oracle 12c as database, celery is used to perform various background task like elastic search sync, and intensive statistics computation, sometimes i got ORA-03113 & ORA-03135 exceptions in django fixup _close_database during on_worker_process_init proc and the worker process die,  these exception are very generic and don't tell me nothing, at first look indicate that there are some network issue and that the oracle server close the connection, but in this case no errors on server side.

I'm able to reproduce this systematically in this way : 
1) start a celery task (that do something on database) with 1 worker and concurrency of 5 for example
2) kill a worker process sending a SIGTERM (kill worker-pid)
3) grow the pool adding one or more process 

as result each new created process crash with the ORA-03135

thanks in advance

**Comment by ask** [comment]
Do you have the full traceback for these exceptions?

**Comment by ppiccolo** [comment]
Yes sure : 

[2015-06-09 06:36:39,074: ERROR/Worker-913451] Process Worker-913451
Traceback (most recent call last):
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap
    self.run()
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/billiard/pool.py", line 288, in run
    self.after_fork()
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/billiard/pool.py", line 391, in after_fork
    self.initializer(*self.initargs)
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 82, in process_initializer
    signals.worker_process_init.send(sender=None)
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/celery/fixups/django.py", line 214, in on_worker_process_init
    self._close_database()
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/celery/fixups/django.py", line 251, in _close_database
    close()
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 203, in close
    self._close()
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 155, in _close
    return self.connection.close()
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/jellyfish/virtualenv/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 155, in _close
    return self.connection.close()
OperationalError: ORA-03135: connection lost contact
Process ID: 11865
Session ID: 684 Serial number: 7122

**Comment by thedrow** [comment]
It sounds like a preforking issue. I have to think about it some more.

**Comment by ppiccolo** [comment]
if can help thi is the command that run the worker : 
exec celery worker -A $CELERY_APP -c 10 -E -l INFO -Ofair --maxtasksperchild=1 -Q twitter -n twitter.%h

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by 0x4e3** [comment]
And it comes back.

* celery `4.4.7`
* oracle `12.2`
* cx_oracle `8.0.1`

`Signal handler <bound method DjangoWorkerFixup.on_worker_process_init of <celery.fixups.django.DjangoWorkerFixup object at 0x7f3490508a00>> raised: OperationalError(<cx_Oracle._Error object at 0x7f3480e7f7f0>)`

full traceback:  

```python
[2020-11-19 13:32:43,386: ERROR/ForkPoolWorker-2] Signal handler <bound method DjangoWorkerFixup.on_worker_process_init of <celery.fixups.django.DjangoWorkerFixup object at 0x7f3490508a00>> raised: OperationalError(<cx_Oracle._Error object at 0x7f3480e7f7f0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 252, in _close
    return self.connection.close()
cx_Oracle.OperationalError: ORA-03113: end-of-file on communication channel
Process ID: 0
Session ID: 313 Serial number: 40939

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.8/site-packages/celery/fixups/django.py", line 154, in on_worker_process_init
    self._close_database(force=True)
  File "/usr/local/lib/python3.8/site-packages/celery/fixups/django.py", line 187, in _close_database
    conn.close()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 294, in close
    self._close()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 252, in _close
    return self.connection.close()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 252, in _close
    return self.connection.close()
django.db.utils.OperationalError: ORA-03113: end-of-file on communication channel
Process ID: 0
Session ID: 313 Serial number: 40939
[2020-11-19 13:32:43,469: ERROR/ForkPoolWorker-3] Signal handler <bound method DjangoWorkerFixup.on_worker_process_init of <celery.fixups.django.DjangoWorkerFixup object at 0x7f3490508a00>> raised: OperationalError(<cx_Oracle._Error object at 0x7f3480e80df0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 252, in _close
    return self.connection.close()
cx_Oracle.OperationalError: ORA-03135: connection lost contact
Process ID: 0
Session ID: 313 Serial number: 40939

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.8/site-packages/celery/fixups/django.py", line 154, in on_worker_process_init
    self._close_database(force=True)
  File "/usr/local/lib/python3.8/site-packages/celery/fixups/django.py", line 187, in _close_database
    conn.close()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 294, in close
    self._close()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 252, in _close
    return self.connection.close()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 252, in _close
    return self.connection.close()
django.db.utils.OperationalError: ORA-03135: connection lost contact
Process ID: 0
Session ID: 313 Serial number: 40939
[2020-11-19 13:32:43,548: ERROR/ForkPoolWorker-4] Signal handler <bound method DjangoWorkerFixup.on_worker_process_init of <celery.fixups.django.DjangoWorkerFixup object at 0x7f3490508a00>> raised: OperationalError(<cx_Oracle._Error object at 0x7f3480e84430>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 252, in _close
    return self.connection.close()
cx_Oracle.OperationalError: ORA-03135: connection lost contact
Process ID: 0
Session ID: 313 Serial number: 40939

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.8/site-packages/celery/fixups/django.py", line 154, in on_worker_process_init
    self._close_database(force=True)
  File "/usr/local/lib/python3.8/site-packages/celery/fixups/django.py", line 187, in _close_database
    conn.close()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 294, in close
    self._close()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 252, in _close
    return self.connection.close()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 252, in _close
    return self.connection.close()
django.db.utils.OperationalError: ORA-03135: connection lost contact
Process ID: 0
Session ID: 313 Serial number: 40939
```

**Comment by auvipy** [comment]
@felixm sorry to tag you as I don't know any other Django oracle expert!

**Comment by felixxm** [comment]
There is nothing specific in these exceptions, it seems that a network connection is unstable. It's not an issue in Django or celery. 

It can be also an issue with DNS servers. You can try to change your listener configurations (`HOST`) to use IPs instead of names, and check if it's more stable. Nevertheless, that's not sth that should be investigated in the celery's bugtracker.

**Comment by auvipy** [comment]
> There is nothing specific in these exceptions, it seems that a network connection is unstable. It's not an issue in Django or celery.
> 
> It can be also an issue with DNS servers. You can try to change your listener configurations (`HOST`) to use IPs instead of names, and check if it's more stable. Nevertheless, that's not sth that should be investigated in the celery's bugtracker.

thank you very much for sharing your experience!

**Comment by 0x4e3** [comment]
Yes, but No: it's not an issue in django or celery, but also it's not a network problem. I have the same errors on local machine.
For now, after some experiments, workaround is downgrade `cx_oracle` to version `6.4`. According to their release notes, there are some changes in session management in version 7, it looks like a reason. I made step-by-step downgrade from `8.0.1` to `6.4.1`.
May be celery team can make some kind of "compatibility" tests for cx_oracle and celery to improve the documentation....

**Comment by auvipy** [comment]
> Yes, but No: it's not an issue in django or celery, but also it's not a network problem. I have the same errors on local machine.
> For now, after some experiments, workaround is to downgrade `cx_oracle` to version `6.4`. According to their release notes, there are some changes in session management in version 7, it looks like a reason. I made step-by-step downgrade from `8.0.1` to `6.4.1`.
> May be celery team can make some kind of "compatibility" tests for cx_oracle and celery to improve the documentation....

contributions are welcome. as it's a huge & versatile project
