### ISSUE TITLE
Emails are not sent when a task raises an exception

### ISSUE THREAD

**Issue by dblado** [celery/celery#2664]
I was trying out the settings for sending email on failed tasks and couldn't get an error message or an email message to come through.

I do receive an email when I do this:
```
from vendop.celery_vendop import *
from celery import current_app
current_app.mail_admins('Subject', 'body', fail_silently=False)
```

But I don't get an error email when I force an error to happen in a task:
```
[2015-06-17 22:46:16,436: ERROR/MainProcess] Task feed.tasks.task_follow_vendor[e4e1256d-118c-41ac-be83-1bdb6c3b80df] raised unexpected: AttributeError("type object 'Vendor' has no attribute 'object'",)
Traceback (most recent call last):
  File "/Users/dblado/vendop/virtenv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/dblado/vendop/virtenv/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "feed/tasks.py", line 11, in task_follow_vendor
    vendor = Vendor.object.get(id=vendor_id)
AttributeError: type object 'Vendor' has no attribute 'object'

```

Here are my settings for Celery:
```
from __future__ import absolute_import
from celery import Celery
from django.conf import settings
import os

CELERY_MONGODB_BACKEND_SETTINGS = {
    'database': 'vendop_celery',
    'taskmeta_collection': 'my_taskmeta_collection',
}
CELERY_EVENT_QUEUE_TTL = 10
CELERY_RESULT_BACKEND = 'mongodb://{}:{}'.format(settings.DB_HOSTS[0]['host'], settings.DB_HOSTS[0]['port'])

CELERY_SEND_TASK_ERROR_EMAILS = True
ADMINS = settings.ADMINS
SERVER_EMAIL = 'celery@vendop.com'
EMAIL_HOST = settings.EMAIL_HOST
EMAIL_PORT = settings.EMAIL_PORT
EMAIL_HOST_USER = settings.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = settings.EMAIL_HOST_PASSWORD
EMAIL_USE_TLS = settings.EMAIL_USE_TLS

app = Celery('vendop', backend=CELERY_RESULT_BACKEND, broker=settings.AMQP_BROKER)

app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

I have added error emails to the list of features to remove for 4.0 since we don't have resources to maintain it.

**Comment by chrisspen** [comment]
This is hugely disappointing. Not being aware of Celery errors is a massive maintenance nightmare.

**Comment by chrisspen** [comment]
Is there any workaround for this, such as by setting up our own exception handler? It's critical that dev teams be aware when Celery tasks encounter errors.
