### ISSUE TITLE
AttributeError: 'module' object has no attribute 'GoogleMixin'

### ISSUE THREAD

**Issue by whatsdis** [celery/celery#2671]
When I run the following 

    /usr/local/bin/celery worker -A tasks --logfile=/logs/celery.log --loglevel=INFO --autoreload --
    include=drone,tasks --concurrency=1 -Q test

It returns

```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 9, in <module>
    load_entry_point('celery==3.1.13', 'console_scripts', 'celery')()
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 301, in execute_from_commandline
    self.on_concurrency_setup()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 809, in on_concurrency_setup
    self.load_extension_commands()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 813, in load_extension_commands
    self.register_command).load()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 151, in load
    cls = symbol_by_name(sym)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/flower/__init__.py", line 6, in <module>
    from .app import Flower  # noqa
  File "/usr/local/lib/python2.7/dist-packages/flower/app.py", line 12, in <module>
    from flower.urls import handlers
  File "/usr/local/lib/python2.7/dist-packages/flower/urls.py", line 19, in <module>
    from .views import auth
  File "/usr/local/lib/python2.7/dist-packages/flower/views/auth.py", line 17, in <module>
    class LoginHandler(BaseHandler, tornado.auth.GoogleMixin):
AttributeError: 'module' object has no attribute 'GoogleMixin'
```

So I don't know why this is suddenly happening. What could possibly trigger this error when my other celery worker is running fine.

**Comment by thedrow** [comment]
That's an issue for flower and not for celery probably.
