### ISSUE TITLE
Call to ResultSet.join() hangs even though jobs are completed

### ISSUE THREAD

**Issue by rbu** [celery/celery#2672]
We are seeing Celery executor processes hanging that wait for task results. This happens randomly, but about every 10 times or so.

Steps to reproduce:

We run a script that puts a lot of tasks into a Celery queue and waits for results. The executor looks like this:
```
@celery.task
def generate_data(...):
    pass

def generate_tasks():
    jobs = []
    for x in range(1000):
        signature = generate_data.si(...)
        jobs.append(signature.delay())
    return jobs

def main():
    jobs = ResultSet(generate_tasks())
    jobs.join()
```

The main() function hangs forever even though all tasks execute. We have checked, there are no tasks waiting in RabbitMQ. The join() function loops coming back to RabbitMQ.

Setup details:
* RabbitMQ 3.1.5
* Python 2.6.6
* amqp-1.4.6-py2.6
* billiard-3.3.0.20-py2.6-linux-x86_64
* celery-3.1.18-py2.
* kombu-3.0.26-py2.6
* 2 Workers with autoscale to 4 (which is what happened when this occured)

The scheduling (main) thread loops in this (strace):
```
fcntl(5, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(5, F_SETFL, O_RDWR)               = 0
fcntl(5, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(5, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
poll([{fd=5, events=POLLIN}], 1, 1000)  = 0 (Timeout)
fcntl(5, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(5, F_SETFL, O_RDWR)               = 0
fcntl(5, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(5, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
poll([{fd=5, events=POLLIN}], 1, 1000)  = 0 (Timeout)
```

The file descriptor in question is an active amqp:
```
# lsof -i -n | grep 35118
beam.smp   1457 rabbitmq   29u  IPv4 33003953      0t0  TCP 127.0.0.1:amqp->127.0.0.1:50835 (ESTABLISHED)
main 28247 user    5u  IPv4 33003952      0t0  TCP 127.0.0.1:50835->127.0.0.1:amqp (ESTABLISHED)
```

When force-closing the socket via RabbitMQ, it became obvious it was looping:
```
Traceback (most recent call last):
  File "main.py", line 73, in main
    result_set.join()
  File "virtualenv/lib/python2.6/site-packages/celery-3.1.18-py2.6.egg/celery/result.py", line 642, in join
    interval=interval, no_ack=no_ack,
  File "virtualenv/lib/python2.6/site-packages/celery-3.1.18-py2.6.egg/celery/result.py", line 169, in get
    no_ack=no_ack,
  File "virtualenv/lib/python2.6/site-packages/celery-3.1.18-py2.6.egg/celery/backends/amqp.py", line 155, in wait_for
    on_interval=on_interval)
  File "virtualenv/lib/python2.6/site-packages/celery-3.1.18-py2.6.egg/celery/backends/amqp.py", line 231, in consume
    conn, consumer, timeout, on_interval)[task_id]
  File "virtualenv/lib/python2.6/site-packages/celery-3.1.18-py2.6.egg/celery/backends/amqp.py", line 212, in drain_events
    wait(timeout=1)
  File "virtualenv/lib/python2.6/site-packages/kombu-3.0.26-py2.6.egg/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "virtualenv/lib/python2.6/site-packages/kombu-3.0.26-py2.6.egg/kombu/transport/pyamqp.py", line 95, in drain_events
    return connection.drain_events(**kwargs)
  File "virtualenv/lib/python2.6/site-packages/amqp-1.4.6-py2.6.egg/amqp/connection.py", line 323, in drain_events
    return amqp_method(channel, args)
  File "virtualenv/lib/python2.6/site-packages/amqp-1.4.6-py2.6.egg/amqp/connection.py", line 529, in _close
    (class_id, method_id), ConnectionError)
amqp.exceptions.ConnectionForced: (0, 0): (320) CONNECTION_FORCED - Closed via management plugin
```

Here's the log from the worker processes. No hanging threads, not exceptions:
```
[2015-06-18 09:29:40,118: INFO/MainProcess] Connected to amqp://app:**@127.0.0.1:5672/app
[2015-06-18 09:29:40,127: INFO/MainProcess] mingle: searching for neighbors
[2015-06-18 09:29:41,134: INFO/MainProcess] mingle: all alone
[2015-06-18 09:29:41,144: WARNING/MainProcess] celery@localhost ready.
[2015-06-18 09:29:46,199: INFO/MainProcess] Received task: app.task[62f70904-8e6d-4f10-b99f-4e1b01e589d6]
[2015-06-18 09:29:46,201: INFO/MainProcess] Received task: app.task[4cc56216-cef6-42f7-ad43-736ed1523479]
[2015-06-18 09:29:46,213: INFO/MainProcess] Received task: app.task[e97e6686-dc39-4613-901d-3f7f67e0207a]
[2015-06-18 09:29:46,214: INFO/MainProcess] Scaling up 1 processes.
[2015-06-18 09:29:46,223: INFO/MainProcess] Received task: app.task[70968cbf-a7a5-4737-8769-7f235aecebbd]
[2015-06-18 09:29:46,224: INFO/MainProcess] Scaling up 1 processes.
[2015-06-18 09:29:46,248: INFO/MainProcess] Received task: app.task[11a08f7a-fd27-47de-a5fd-231d0ab33a03]
[2015-06-18 09:29:46,251: INFO/MainProcess] Received task: app.task[ba6a0214-8633-4a3f-8e5c-bdc96499597d]
[2015-06-18 09:29:46,252: INFO/MainProcess] Received task: app.task[f02de5d3-a052-49fe-ace2-2e92d9484dd7]
...
[2015-06-18 09:30:58,782: INFO/MainProcess] Task app.task[602528a4-87c8-43b2-b604-56ddb251f18f] succeeded in 0.971982910996s: None
[2015-06-18 09:30:59,179: INFO/MainProcess] Task app.task[891d0f43-b326-4272-a1c7-2ebb7cbf5f06] succeeded in 0.795299627003s: None
[2015-06-18 09:30:59,248: INFO/MainProcess] Task app.task[a95ee52b-301f-4ad1-adc9-0a393d170e90] succeeded in 0.702663101023s: None
[2015-06-18 09:31:11,146: INFO/MainProcess] Scaling down 2 processes.
```

There has been no unusual log entries in RabbitMQ's log except maybe the connection aborts (I assume due to worker scale down):
```
=INFO REPORT==== 18-Jun-2015::09:29:40 ===
accepting AMQP connection <0.22707.2> (127.0.0.1:50829 -> 127.0.0.1:5672)

=INFO REPORT==== 18-Jun-2015::09:29:40 ===
accepting AMQP connection <0.22712.2> (127.0.0.1:50830 -> 127.0.0.1:5672)

=INFO REPORT==== 18-Jun-2015::09:29:46 ===
accepting AMQP connection <0.22736.2> (127.0.0.1:50835 -> 127.0.0.1:5672)

=INFO REPORT==== 18-Jun-2015::09:29:50 ===
accepting AMQP connection <0.22747.2> (127.0.0.1:50836 -> 127.0.0.1:5672)

=INFO REPORT==== 18-Jun-2015::09:29:50 ===
accepting AMQP connection <0.22757.2> (127.0.0.1:50837 -> 127.0.0.1:5672)

=INFO REPORT==== 18-Jun-2015::09:29:50 ===
accepting AMQP connection <0.22767.2> (127.0.0.1:50838 -> 127.0.0.1:5672)

=INFO REPORT==== 18-Jun-2015::09:29:54 ===
accepting AMQP connection <0.22793.2> (127.0.0.1:50839 -> 127.0.0.1:5672)

=WARNING REPORT==== 18-Jun-2015::09:31:11 ===
closing AMQP connection <0.22747.2> (127.0.0.1:50836 -> 127.0.0.1:5672):
connection_closed_abruptly

=WARNING REPORT==== 18-Jun-2015::09:31:11 ===
closing AMQP connection <0.22767.2> (127.0.0.1:50838 -> 127.0.0.1:5672):
connection_closed_abruptly
``` 

I understand that ```join()``` has a timeout, which is useful to detect this issue, but the issue here is that RabbitMQ and Celery should be reliable, and not lose tasks or results unless there are exceptions.

**Comment by thedrow** [comment]
What happens when you don't use autoscaling?

**Comment by rbu** [comment]
Do you think it may be related to that? The automatic scale down happened about 12 seconds after the last job completed, so it should not cause any disruption.
The reason I am asking is that it takes quite a while to run the jobs and I can only use up so many resources on our development infrastructure (and my time).

**Comment by thedrow** [comment]
@rbu We've seen a lot of issues with autoscaling lately. Check the label.
If it happens once out of 10 it makes some sense that it might be related. It's worth a shot. I can't be 100% sure though.
I'll try to reproduce this issue as soon as possible.

**Comment by rbu** [comment]
We are running an experiment now where some workers have autoscaling disabled. Hopefully I can say something about whether the problem persists there in about a week.

**Comment by rbu** [comment]
@thedrow, we have changed parts of our workers from --autoscale=4,2 to --concurrency 2 and we are not experiencing this issue any more. Does that help you narrow down the original problem?

**Comment by thedrow** [comment]
Yes. This is yet another issue with this feature.
Are you guys running Celery with -Ofair by any chance?
We also found multiple issues with the combination of -Ofair and autoscaling.

**Comment by rbu** [comment]
We haven't set the -Ofair option. So if it's not the default, then we are not using the option.

**Comment by thedrow** [comment]
Then it's a different bug.
Are you using librabbitmq or amqp?

**Comment by rbu** [comment]
We're using amqp-1.4.6-py2.6

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
