### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ' ' 

### ISSUE THREAD

**Issue by nairdaus** [celery/celery#2673]
I have an issue when I run a worker with the following command:

python manage.py celery -A callfiles worker -l info

This is the message returned:

```python
/var/www/callfiles/local/lib/python2.7/site-packages/django/core/management/base.py:259: RemovedInDjango19Warning: "requires_model_validation" is deprecated in favor of "requires_system_checks".
  RemovedInDjango19Warning)

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/callfiles/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/var/www/callfiles/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/callfiles/local/lib/python2.7/site-packages/djcelery/management/commands/celery.py", line 23, in run_from_argv
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 100, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 124, in setup_instance
    self._conninfo = self.app.connection()
  File "/var/www/callfiles/local/lib/python2.7/site-packages/celery/app/base.py", line 385, in connection
    'BROKER_CONNECTION_TIMEOUT', connect_timeout
  File "/var/www/callfiles/local/lib/python2.7/site-packages/kombu/connection.py", line 167, in __init__
    params.update(parse_url(hostname))
  File "/var/www/callfiles/local/lib/python2.7/site-packages/kombu/utils/url.py", line 32, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "/var/www/callfiles/local/lib/python2.7/site-packages/kombu/utils/url.py", line 24, in _parse_url
    return (scheme, unquote(parts.hostname or '') or None, parts.port,
  File "/usr/lib/python2.7/urlparse.py", line 107, in port
    return int(port, 10)
ValueError: invalid literal for int() with base 10: ''
```

This happens in an Ubuntu 12.04 server 32 bit edition with python 2.7.3 inside, however in my laptop with kubuntu 15.04 with python 2.7.9 this problem doesn't happen. In both cases runing with virtualenv and same versions of Django 1.8.2 , Celery and Rabbitmq.

This is my list of installs in my virtualenv:

```
Django==1.8.2
Naked==0.1.31
PyYAML==3.11
amqp==1.4.6
anyjson==0.3.3
argparse==1.2.1
billiard==3.3.0.20
celery==3.1.18
distribute==0.6.24
django-celery==3.1.16
ecdsa==0.13
gunicorn==19.3.0
kombu==3.0.26
paramiko==1.15.2
pycrypto==2.6.1
pysftp==0.2.8
pytz==2015.4
requests==2.7.0
shellescape==3.4.1
wsgiref==0.1.2
```

Thanks in advanced.

**Comment by thedrow** [comment]
Can you share your configuration please?

**Comment by nairdaus** [comment]
Could you please tell me which configuration? Thanks.

**Comment by thedrow** [comment]
The Celery/Django configuration.

**Comment by nairdaus** [comment]
Hi, this is my settings.py


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-BO'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

#Buscando todos las tareas/ Find the tasks

#Celery periodic task / Tareas periodicas Celery
from datetime import timedelta

CELERYBEAT_SCHEDULE = {
    'Creando archivos de llamadas':{
        'task':'mkfiles.tasks.makingCallFiles',
        'schedule': timedelta(seconds = 60)
    }    
}

This is my celery.py

from __future__ import absolute_import
import os

from celery import Celery
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'callfiles.settings')

app= Celery('callfiles')

app.config_from_object('django.conf:settings')

app.autodiscover_tasks(lambda:settings.INSTALLED_APPS)

@app.task(bind=True)
def debug_task(self):
	print ('Request:{0!r}'.format(self.request))

And finally this is my task.py

from __future__ import absolute_import
from celery import shared_task
from . mkcallfiles import mkcall

@shared_task
def makingCallFiles():
	mkcall().readDB()

Do you need to see my classes mkcall().readDB() now?

**Comment by thedrow** [comment]
I don't see you setting the BROKER_URL so I'm assuming you are using RabbitMQ at localhost but that seems unlikely since the problem is in parsing the hostname.

In any case, can't you simply upgrade your Python version to the latest minor version?

**Comment by nairdaus** [comment]
Ok, thanks I will try on and post here what happens.

**Comment by nairdaus** [comment]
It's works!!, just upgrade python version, Thanks a lot for your advice
