### ISSUE TITLE
.get() on chain's AsyncResult fails when a subtask retries

### ISSUE THREAD

**Issue by PhilipGarnero** [celery/celery#2677]
I get an error when getting the result of a chain using `.get()` if one of the subtask in the chain is retrying :

```
#test.py
from celery import Celery
from time import sleep

app = Celery('tasks', broker='redis://0', backend='redis://1')
app.conf.update(
    CELERY_RESULT_SERIALIZER='json',
)

@app.task
def task_a(x):
    return x

@app.task(bind=True, max_retries=None)
def task_b(self, x):
    sleep(5)
    if x == 1:
        raise self.retry()
    else:
        return x
```
```
>>> from celery import chain
>>> import test
>>> a = chain(test.task_a.s(1), test.task_b.s())
>>> a.delay().get()
```
When task_b retries I get this traceback : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/result.py", line 171, in get
    no_ack=no_ack,
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 218, in wait_for
    meta = self.get_task_meta(task_id)
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 294, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 517, in _get_task_meta_for
    return self.decode_result(meta)
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 193, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 189, in meta_from_decoded
    meta['result'] = self.exception_to_python(meta['result'])
  File "/home/pgarnero/projects/.venv/local/lib/python2.7/site-packages/celery-3.2.0a2-py2.7.egg/celery/backends/base.py", line 172, in exception_to_python
    from_utf8(exc['exc_type']), __name__)(exc['exc_message'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```
It seems that this is due to the CELERY_RESULT_SERIALIZER parameter. When I comment it, everything works fine.
Will investigate further.

Note: inverting task_a and task_b doesn't change anything

**Comment by PhilipGarnero** [comment]
Actually this has nothing to do with the chain.
`test.task_b.delay(1).get()` fails as well.
