### ISSUE TITLE
celery/backends/base.py BaseBackend does not support keyword argument on_message

### ISSUE THREAD

**Issue by aarcro** [celery/celery#2702]
```python
>>> wf = group(concat.s(1) | group(concat.s(2), concat.s(3)))
>>> res = wf.delay()
>>> res.get()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/amcmillin/virtual_envs/massimport/lib/python2.7/site-packages/celery/result.py", line 581, in get
    on_message=on_message,
  File "/Users/amcmillin/virtual_envs/massimport/lib/python2.7/site-packages/celery/result.py", line 699, in join_native
    on_message):
  File "/Users/amcmillin/virtual_envs/massimport/lib/python2.7/site-packages/celery/result.py", line 676, in iter_native
    on_message=on_message,
TypeError: get_many() got an unexpected keyword argument 'on_message'
```

In #2550 an on_message callback was added, but it doesn't exist in the BaseBackend and is causing trouble for me. I'm running redis for the backend and result store.

**Comment by domenkozar** [comment]
Fixed by https://github.com/celery/celery/commit/759842aab336c8696056b4daa6f6e029281f5b9e, right @ask?

**Comment by ask** [comment]
Yeah :)  Didn't see there was an issue for it, thanks!
