### ISSUE TITLE
Celery sporadically throws "No such file or directory"

### ISSUE THREAD

**Issue by flaugher** [celery/celery#2718]
I'm running Celery v3.1.17 on OS X v10.9.5 and also on Debian v7.8.  My Django v1.62 app contains a Celery task that that uploads photos via a Celery worker from the user's computer onto my server.  I start/stop my workers using Supervisord.  I have an intermittent problem in which Celery raises an error "OSError: [Errno 2] No such file or directory".  I'm unable to reproduce the error.  One way to stop it is to restart my Celery workers.  I can also stop the error by restarting the Django web server on my Mac or Gunicorn on my production server.  This error happens approximately 20% of the time and I haven't been able to reproduce it.  Neither my system, application, nor Celery worker logs show anything.  Can anyone on the Celery team tell what might be happening from the stacktrace?

``` python
File "/Users/me/venv/myproj/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
   return view_func(request, *args, **kwargs)

 File "/www/myproj/apps/photos/views.py", line 92, in upload_photos
   upload_photos_task.apply_async((photo_file_list, user, access_mode), serializer='pickle')

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/local.py", line 143, in __getattr__
   return getattr(self._get_current_object(), name)

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/local.py", line 221, in _get_current_object
   return self.__evaluate__()

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/local.py", line 251, in __evaluate__
   thing = Proxy._get_current_object(self)

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/local.py", line 101, in _get_current_object
   return loc(*self.__args, **self.__kwargs)

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/app/base.py", line 269, in _task_from_fun
   '__wrapped__': fun}, **options))()

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/app/task.py", line 201, in __new__
   instance.bind(app)

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/app/task.py", line 357, in bind
   conf = app.conf

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/kombu/utils/__init__.py", line 322, in __get__
   value = obj.__dict__[self.__name__] = self.__get(obj)

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/app/base.py", line 629, in conf
   return self._get_config()

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/app/base.py", line 453, in _get_config
   self.loader.config_from_object(self._config_source)

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/loaders/base.py", line 140, in config_from_object
   obj = self._smart_import(obj, imp=self.import_from_cwd)

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/loaders/base.py", line 158, in _smart_import
   return imp(path)

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/loaders/base.py", line 112, in import_from_cwd
   package=package,

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
   with cwd_in_path():

 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
   return self.gen.next()

 File "/Users/me/venv/myproj/lib/python2.7/site-packages/celery/utils/imports.py", line 58, in cwd_in_path
   cwd = os.getcwd()

OSError: [Errno 2] No such file or directory
```

``` python
##### CELERYCONFIG.PY

from kombu import Queue, Exchange
BROKER_URL = 'amqp://'
CELERY_RESULT_BACKEND = 'amqp://'
CELERY_ACCEPT_CONTENT = ['json', 'application/x-python-serialize']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_RESULT_EXPIRES = 3600
CELERY_DEFAULT_QUEUE = 'default'
CELERY_QUEUES = (
    Queue('default', Exchange('default'), routing_key='default'),
    Queue('photos', Exchange('photos'), routing_key='photos'),
    Queue('mail', Exchange('mail'), routing_key='mail'),
)
CELERY_ROUTES = (
    {'apps.photos.tasks.upload_photos_task': {'queue': 'photos', 'routing_key': 'photos'}},
    {'apps.photos.tasks.hello': {'queue': 'default', 'routing_key': 'default'}},
    {'apps.default.tasks.add': {'queue': 'default', 'routing_key': 'default'}},
    {'apps.photos.tasks.send_email': {'queue': 'mail', 'routing_key': 'mail'}},
    {'apps.photos.tasks.send_combo_email': {'queue': 'mail', 'routing_key': 'mail'}},
)
```

**Comment by malinoff** [comment]
@flaugher `OSError` on `os.getcwd()` means that there is no current directory - can you show us how you run celery, in which directory?

**Comment by flaugher** [comment]
Dmitry, thanks for your prompt response. This is how I start Celery on my Mac.  First I'll change to the top-level Django project directory "/www/myproj".  Then I'll run the following bash script:

##### /www/myproj/bin/start-celery-osx
#!/usr/bin/env bash
loglevel='info'

if [ ! -d "/var/run/celery" ]; then
    echo "We need to recreate the /var/run/celery directory..."
    sudo mkdir /var/run/celery
    sudo chmod 775 /var/run/celery
    sudo chown celery:celery /var/run/celery
fi
celery worker \
    -A conf.celeryapp:app \
    -n worker1 \
    -Q default \
    --events \
    --loglevel=$loglevel \
    --logfile=/var/log/celery/worker1.log \
    --pidfile=/var/run/celery/worker1.pid \
    --detach
celery worker \
    -A conf.celeryapp:app \
    -n worker2 \
    -Q photos \
    --events \
    --loglevel=$loglevel \
    --logfile=/var/log/celery/worker2.log \
    --pidfile=/var/run/celery/worker2.pid \
    --detach
celery worker \
    -A conf.celeryapp:app \
    -n worker3 \
    -Q mail \
    --events \
    --loglevel=$loglevel \
    --logfile=/var/log/celery/worker3.log \
    --pidfile=/var/run/celery/worker3.pid \
    --detach

Here is celeryapp.py:

##### celeryapp.py
from celery import Celery
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'conf.settings.prod')
app = Celery('celeryapp')
app.config_from_object('conf.celeryconfig')
app.autodiscover_tasks(['apps.photos'])

On my Debian server, I change to my project's directory and run the command "sudo service supervisor start".  This is my Supervisor config file:

##### /etc/supervisor/conf.d/supervisor.conf
; ==========================
;  celery worker1 supervisor
; ==========================
[program:celeryw1]
command=/home/myproj/venv/myproj/bin/celery worker --app=conf.celeryapp:app -n worker1 --config=celeryconfig -Q default --loglevel=info --pidfile=/var/run/celery/worker1.pid
directory=/www/myproj
user=myproj
numprocs=1
stdout_logfile=/var/log/celery/worker1.log
stderr_logfile=/var/log/celery/worker1.log
redirect_stderr=true
pervisord is started
autostart=true
autorestart=true
startsecs=1
stopwaitsecs=600
killasgroup=true
priority=997
environment=MEDIA_ROOT="/var/www/myproj/media",STATIC_ROOT="/var/www/myproj/static",SERVER_TIER="web-prod",EMAIL_HOST_USER="me",EMAIL_HOST_PASSWORD="someemailpassword",SITE_ROOT="/www/myproj/",SECRET_KEY="somesecretkey",ROOT_PASSWORD="somepassword"

; ==========================
;  celery worker2 supervisor
; ==========================
[program:celeryw2]
command=/home/myproj/venv/myproj/bin/celery worker --app=conf.celeryapp:app -n worker2 --config=celeryconfig -Q photos --loglevel=info --pidfile=/var/run/celery/worker2.pid
directory=/www/myproj
user=myproj
numprocs=1
stdout_logfile=/var/log/celery/worker2.log
stderr_logfile=/var/log/celery/worker2.log
redirect_stderr=true
autostart=true
autorestart=true
startsecs=1
stopwaitsecs=600
killasgroup=true
priority=997
environment=MEDIA_ROOT="/var/www/myproj/media",STATIC_ROOT="/var/www/myproj/static",SERVER_TIER="web-prod",EMAIL_HOST_USER="me",EMAIL_HOST_PASSWORD="someemailpassword",SITE_ROOT="/www/myproj/",SECRET_KEY="somesecretkey",ROOT_PASSWORD="somepassword"


; ==========================
;  celery worker3 supervisor
; ==========================
[program:celeryw3]
command=/home/myproj/venv/myproj/bin/celery worker --app=conf.celeryapp:app -n worker3 --config=celeryconfig -Q mail --loglevel=info --pidfile=/var/run/celery/worker3.pid
directory=/www/myproj
user=myproj
numprocs=1
stdout_logfile=/var/log/celery/worker3.log
stderr_logfile=/var/log/celery/worker3.log
redirect_stderr=true
autostart=true
autorestart=true
startsecs=1
stopwaitsecs=600
killasgroup=true
priority=997
environment=MEDIA_ROOT="/var/www/myproj/media",STATIC_ROOT="/var/www/myproj/static",SERVER_TIER="web-prod",EMAIL_HOST_USER="me",EMAIL_HOST_PASSWORD="someemailpassword",SITE_ROOT="/www/myproj/",SECRET_KEY="somesecretkey",ROOT_PASSWORD="somepassword"

; ==========================
;  celery workers supervisor
; ==========================
[group:celery-workers]
programs=celeryw1,celeryw2,celeryw3
priority=998

**Comment by malinoff** [comment]
@flaugher can `/www/proj` directory be updated when running celery in the background? Can something change its permissions?

**Comment by flaugher** [comment]
As /www/proj is the Django project's top-level directory, it shouldn't change when Celery is running.  It only contains the project's Python and Django packages, modules, and configuration files.  Any files that the project  creates or writes to would either be photos uploaded by my users and stored in the /var/www/media directory or log files and all of those are located in /var/log.

**Comment by flaugher** [comment]
What's peculiar to me is that this doesn't happen all of the time and so I wonder if it's some timing issue.  It feels like Celery is looking for some directory which sometimes doesn't get created in time for Celery to access it.  Here is the logic for the Celery worker task that is executing when the problem occurs:

create two directories where photos will be uploaded to
for each photo in a list of photos:
    create an instance of my Photo class to store photo-related information
    save the uploaded photo to an "originals" directory
    convert the photo just saved to a PIL image
    create large and small versions of PIL image and save them to the directories created at the start
update my review queue so I know I have photos to review
send me an email telling me I have photos in the queue that need to be reviewed

One tangential question I have is, should I put as few operations into a Celery worker task as is feasible or is it OK to put larger blocks of business logic such what I just described into a Celery task?

**Comment by syabro** [comment]
Same here
```
  File "/home/hosts/ir-305-flood-dec-page/sources/homeowners/quotes/models/policy.py", line 1405, in search_index_handler
    update_search_index_task.apply_async(args=[policy_id], countdown=10)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/local.py", line 143, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/local.py", line 311, in _get_current_object
    return self.__evaluate__()
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/local.py", line 341, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/local.py", line 101, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/app/base.py", line 270, in _task_from_fun
    '__wrapped__': fun}, **options))()
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/app/task.py", line 201, in __new__
    instance.bind(app)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/app/task.py", line 357, in bind
    conf = app.conf
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/app/base.py", line 630, in conf
    return self._get_config()
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/app/base.py", line 454, in _get_config
    self.loader.config_from_object(self._config_source)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/loaders/base.py", line 140, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/loaders/base.py", line 153, in _smart_import
    return symbol_by_name(path, imp=imp)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/loaders/base.py", line 112, in import_from_cwd
    package=package,
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
    with cwd_in_path():
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/hosts/ir-305-flood-dec-page/venv/local/lib/python2.7/site-packages/celery/utils/imports.py", line 58, in cwd_in_path
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
```
any luck with it @flaugher?

**Comment by ask** [comment]
As `chdir(2)` will return `ENOENT` in the first place if the directory does not exist, having `getcwd(3)` return `ENOENT` can only happen if the directory was removed after changing into it.

**Comment by syabro** [comment]
@ask we're investigating but I'm pretty sure directory haven't changed, because I stop server, run it with the same command and don't see the error anymore

**Comment by syabro** [comment]
@ask checked. Directory exists.
`os.getenv('PWD')` returned current user dir `/home/app`. It exists, and process have permissions to access it.

any ideas?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by mwaaas** [comment]
I had the same error, in my case I was synchronizing two folders, fixed by stopping synchronizing

**Comment by BeOleg** [comment]
I think that it is possible simple that the celery worker has no permissions to create new files in the working directory...

**Comment by jonahfang** [comment]
I sovled this problem by changing python to v2.7.12 and kombu v3.0.30.

**Comment by nathanbedford** [comment]
@ask would you consider reopening this? 

We upgraded from Celery v4 to v5 (5.0.1) to try and 'fix' this issue too.  Thought we were free from it but found that we're still seeing this error occasionally (only in production of course).

We can't reproduce this locally.  Anyone else running into this?

Our set up:
* We're using Python 3.6.8
* Running in EC2 instances (AWS Elastic Beanstalk) 

```
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 301, in _get_current_object
    return object.__getattribute__(self, '__thing')
AttributeError: 'PromiseProxy' object has no attribute '__thing'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 41, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 41, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'loader'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/trace.py", line 409, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/python/bundle/2/app/Server/__init__.py", line 61, in __call__
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/trace.py", line 701, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/opt/python/bundle/2/app/Server/tasks/courses.py", line 34, in delete_module_item
  File "/opt/python/bundle/2/app/Server/models/courses.py", line 618, in delete
  File "/opt/python/bundle/2/app/Server/models/courses.py", line 608, in revoke_autograde_task
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 143, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 303, in _get_current_object
    return self.__evaluate__()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 333, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 105, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 441, in _task_from_fun
    task.bind(self)  # connects task to this app
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/task.py", line 332, in bind
    setattr(cls, attr_name, conf[config_name])
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/utils/collections.py", line 420, in __getitem__
    return getitem(k)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/utils/collections.py", line 264, in __getitem__
    return mapping[_key]
  File "/opt/python/run/venv/lib64/python3.6/collections/__init__.py", line 987, in __getitem__
    if key in self.data:
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 43, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 136, in data
    return self.callback()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 897, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 907, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 43, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 1196, in loader
    return get_loader_cls(self.loader_cls)(app=self)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/loaders/__init__.py", line 18, in get_loader_cls
    return symbol_by_name(loader, LOADER_ALIASES, imp=import_from_cwd)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/utils/imports.py", line 106, in import_from_cwd
    with cwd_in_path():
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/utils/imports.py", line 57, in cwd_in_path
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by xxholyChalicexx** [comment]
yeap from time to time i keep getting this issue in my ec2 instance too...i am in python 3.7 .

**Comment by fadebowaley** [comment]
I will like to be updated when this error is fixed. I'm on python 3.8 and we have the same issue on dev and production

**Comment by auvipy** [comment]
any script to reproduce it?

**Comment by auvipy** [comment]
> we see this issue when the project package is reinstalled without restarting celeryd. Because after the package is installed, the **pycache** folder is recreated. But celery was started earlier and the modules are still referencing the old folder(even if the name is the same), os.getcwd() would throw such an error in this case. The solution is to restart celery worker whenever package is reinstalled, even if the version doesn't change.

can we put this to some related place of doc?

**Comment by yangyang5214** [comment]
```
@contextmanager
def cwd_in_path():
    """Context adding the current working directory to sys.path."""
  +os.system("pwd") // Add new line above "cwd = os.getcwd()"
    cwd = os.getcwd()
```


```
# by shell script
sed -i '49a  \  \  os.system("pwd")' /usr/local/lib/python3.6/site-packages/celery/utils/imports.py
```

It will appear every time， because our system is deployed every time the machine is reinstalled.  

I solved it, by 👆， Can anyone analyze it?

**Comment by hashqueue** [comment]
I use `supervisord` to manage the Celery worker in the production environment. I also encountered the `FileNotFoundError: [Errno 2] No such file or directory` error. When I added `--workdir=/home/tms` to the `celery -A tms --workdir=/home/tms worker xxx` command, the issue was resolved. Not sure if this information can be helpful to you.

* python:3.10.12
* celery==5.3.1
* Django==4.2.4
* django-celery-beat==2.5.0
* django-celery-results==2.5.1
