### ISSUE TITLE
raise Terminated(15, ) when terminating task

### ISSUE THREAD

**Issue by ghost** [celery/celery#2727]
[2015-07-27 12:52:38,386: ERROR/MainProcess] Task myapp.tasks.test [150a75dc-592e-4c0c-b686-1cc5aaf5a168] raised unexpected: Terminated(15,)
Traceback (most recent call last):
  File "/home/blake/projects/venv/myapp/lib/python2.7/site-packages/billiard/pool.py", line 1674, in _set_terminated
    raise Terminated(-(signum or 0))
Terminated: 15

packages installed:

amqp==1.4.6
anyjson==0.3.3
beautifulsoup4==4.4.0
billiard==3.3.0.20
celery==3.1.18
Django==1.7.7
django-celery==3.1.16
django-pipeline==1.5.2
futures==3.0.3
kombu==3.0.25
pytz==2015.4
redis==2.10.3
requests==2.7.0
wheel==0.24.0

I'm starting worker with:

celery -A myapp worker --loglevel=INFO --concurrency=10 

i'm revoking with:

from celery.task.control import revoke
revoke(task_id, terminate=True, signal='SIGKILL')

is this the wrong approach?

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by howtoprogram** [comment]
still happens in 4.0 release

**Comment by morphyno** [comment]
I'm seeing this on celery version 3.1.25, can someone shed some light on this issue?

`[2017-09-15 12:05:26,543: INFO/MainProcess] Terminating b6e9961f-244c-4cf3-a830-cc363caf5d73 (15)
[2017-09-15 12:05:30,963: ERROR/MainProcess] Task framework.traff_tasks.traffictask[b6e9961f-244c-4cf3-a830-cc363caf5d73] raised unexpected: Terminated(15,)
Traceback (most recent call last):
`

**Comment by guomaoqiu** [comment]
still happens in  v4.0.2 (latentcall):

[2017-11-22 16:16:01,199: ERROR/MainProcess] Task handler raised error: Terminated(15,)
Traceback (most recent call last):
  File "/Users/Green/zero/lib/python2.7/site-packages/billiard/pool.py", line 1726, in _set_terminated
    raise Terminated(-(signum or 0))
Terminated: 15

**Comment by lordi** [comment]
It also happens with

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.2
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis+socket:redis.sock
```

Error message:

```
[2017-12-09 16:51:42,381: ERROR/MainProcess] Task handler raised error: Terminated(15,)
Traceback (most recent call last):
  File "site-packages/billiard/pool.py", line 1725, in _set_terminated
    raise Terminated(-(signum or 0))
billiard.exceptions.Terminated: 15
```

After this, the worker goes quiet and refuses to take any more tasks at all.

**Comment by lordi** [comment]
@ask Could you reopen this issue?

**Comment by thedrow** [comment]
We should catch that exception and exit properly.

**Comment by byronrau** [comment]
Having same issue, is there a workaround?

**Comment by auvipy** [comment]
anyone up with any proposal to fix as PR?

**Comment by atline** [comment]
Django==2.0.7
django-celery==3.2.2

Linux same issue, windows is ok, anyone raise a solution?

**Comment by auvipy** [comment]
I want to know it's status with 4.2.1 or master

**Comment by Fel-o** [comment]
still happens on 4.2.1

**Comment by VladimirSpigiel** [comment]
Have same issue here, on 4.2.1. Hope the team will fix this old issue.

**Comment by divick** [comment]
still happens on 4.3.0

**Comment by thedrow** [comment]
PRs welcome :)

**Comment by auvipy** [comment]
anyone could try this with the latest master and send a fix with a test?

**Comment by blairg23** [comment]
**Relevant `pip freeze` items:**
```
amqp==2.3.2
billiard==3.5.0.4
celery==4.1.1
Django==1.11.20
django-celery-beat==1.4.0
django-celery-email==2.0.1
django-celery-results==1.0.4
future==0.17.1
kombu==4.2.0
pytz==2019.1
redis==2.10.6
requests==2.22.0
requests-oauthlib==1.2.0
requests-toolbelt==0.8.0
```

**Still getting**

```
Terminated: 15
  File "billiard/pool.py", line 1725, in _set_terminated
    raise Terminated(-(signum or 0))
```

We noticed if you do a `watch celery -A <app> inspect scheduled` in one of your monitors, you can see the ETA queue get DROPPED, which leads to the problem of:

> After this, the worker goes quiet and refuses to take any more tasks at all.

**Comment by blairg23** [comment]
This related at all? https://github.com/celery/celery/issues/1810

**Comment by auvipy** [comment]
could you try billiard 3.6

**Comment by PawelMorawian** [comment]
> could you try billiard 3.6

I have this issue with :

```
Django==2.2.7
billiard==3.6.1.0
celery==4.4.0rc4
```

**Comment by auvipy** [comment]
can you provide the failing testcase for this?

**Comment by sashank-shyam** [comment]
For me personally, It's whenever I order a SIGKILL to a task like so:
 celery.control.revoke(my_task_id,terminate=True,signal="SIGKILL")
Similar to the above users, the task does terminate, but the worker no longer accepts tasks after.

**Comment by bramverhelst** [comment]
I have been hitting this bug recently, finding no way arround it.
The only thing that works for me when terminating a task is send the SIGUSR1 signal in combination with terminate=True: `result.revoke(terminate=True, signal='SIGUSR1')`

This raises a `SoftTimeLimeExceeded` exception immediately and does NOT kill the parent worker.
I would love to see the `Terminated` exception to behave similarly :)

**Comment by auvipy** [comment]
you should be using the latest release of celery==4.4.0, though the issue exist in master I tink

**Comment by lithammer** [comment]
A question for those running into this, are you running inside a (Docker) container and possibly running into some signal oddities regarding Python and PID 1.

https://hackernoon.com/my-process-became-pid-1-and-now-signals-behave-strangely-b05c52cc551c

**Comment by sashank-shyam** [comment]
> A question for those running into this, are you running inside a (Docker) container and possibly running into some signal oddities regarding Python and PID 1?

I was personally not running on a VM nor a container. Celery ran on ubuntu directly. The PID for celery was mos certainly not 1 (as in an OS it is reserved for init)

**Comment by bramverhelst** [comment]
> you should be using the latest release of celery==4.4.0, though the issue exist in master I tink

yes, even with celery==4.4.0 the issue remains :)

**Comment by auvipy** [comment]
can you provide a test case?

**Comment by bramverhelst** [comment]
Sure.

```python
from tests.tasks import simple_task
"""
@task(bind=True)
def simple_task(self):
    print("Going to sleep")
    time.sleep(5)
"""

_task = simple_task.si()
result = _task.apply_async()

result.revoke(terminate=True)
```

results in:
```text
 -------------- celery@mycomputer v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Darwin-18.7.0-x86_64-i386-64bit 2020-01-09 10:54:56
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         localapp:0x1027e8ce0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     redis://localhost:6379/1
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery

[tasks]
  . tests.tasks.simple_task

[2020-01-09 10:54:56,975: INFO/Beat] beat: Starting...
[2020-01-09 10:54:58,509: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2020-01-09 10:54:58,523: INFO/MainProcess] mingle: searching for neighbors
[2020-01-09 10:54:59,551: INFO/MainProcess] mingle: all alone
[2020-01-09 10:54:59,575: INFO/MainProcess] celery@mycomputer ready.
[2020-01-09 10:55:29,865: INFO/MainProcess] Received task: tests.tasks.simple_task[d94c715e-57da-431c-a5a3-5f3dcdcab453]  
[2020-01-09 10:55:29,868: WARNING/ForkPoolWorker-14] Going to sleep
[2020-01-09 10:55:29,870: INFO/MainProcess] Terminating d94c715e-57da-431c-a5a3-5f3dcdcab453 (15)
[2020-01-09 10:55:29,892: ERROR/MainProcess] Task handler raised error: Terminated(15,)
Traceback (most recent call last):
  File "/Users/verhelst/.virtualenvs/leak/lib/python2.7/site-packages/billiard/pool.py", line 1769, in _set_terminated
    raise Terminated(-(signum or 0))
Terminated: 15
```

**Comment by auvipy** [comment]
same happen with python 3?

**Comment by sashank-shyam** [comment]
Yep even with python3

**Comment by blkrt** [comment]
still happens with celery 4.4.2 and python3

**Comment by ungarj** [comment]
still happens with celery 4.4.6, billiard 3.6.3.0 and python 3.6.11

**Comment by youguanxinqing** [comment]
still happens with celery 4.4.5 and python 3.6.8

**Comment by auvipy** [comment]
> still happens with celery 4.4.5 and python 3.6.8

Help us to debug & find out a fix

**Comment by youguanxinqing** [comment]
> > still happens with celery 4.4.5 and python 3.6.8
> 
> Help us to debug & find out a fix

Sorry. I am so busy that I have no time to do it in the recent future.I will reproduce and try to fix it when I am free.

**Comment by joekendal** [comment]
> The only thing that works for me when terminating a task is send the SIGUSR1 signal in combination with terminate=True: `result.revoke(terminate=True, signal='SIGUSR1')`
> 
> This raises a `SoftTimeLimeExceeded` exception immediately and does NOT kill the parent worker.

Thanks!

**Comment by fcmxmk** [comment]
still happens with celery 5.0.2 and python3.8

**Comment by pakallis** [comment]
I have included a potential fix for the issue in #6630.
Is the desired behavior to not throw the Terminated exception and acknowledge the message?

I managed to reproduce the issue where a `Terminated` exception is raised but I haven't reproduced the issue where the worker is unable to receive messages after the `Terminated` exception.

**Comment by pakallis** [comment]
I have tested this in master (948bb797d) with the following code:
```python
# tasks.py
import time
from celery import Celery

app = Celery(backend="redis://")

@app.task(bind=True)
def sleeping(self, delay):
    time.sleep(delay)
```

```python
from tasks import sleeping

_task = sleeping.si(10)
result = _task.apply_async()
result.revoke(terminate=True)
```

**Package versions**

```
python==3.8.2
amqp==5.0.5
kombu==5.0.2
billiard==3.6.3.0
```

The output is:

```
 -------------- celery@pakallis-Inspiron-5577 v5.0.5 (singularity)
--- ***** ----- 
-- ******* ---- Linux-5.4.0-65-generic-x86_64-with-glibc2.27 2021-02-11 22:25:10
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7f82d3a2a610
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     redis://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . cl.atask

[2021-02-11 22:25:10,580: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2021-02-11 22:25:10,588: INFO/MainProcess] mingle: searching for neighbors
[2021-02-11 22:25:11,608: INFO/MainProcess] mingle: all alone
[2021-02-11 22:25:11,631: INFO/MainProcess] celery@pakallis-Inspiron-5577 ready.


[2021-02-11 22:25:24,453: INFO/MainProcess] Received task: cl.atask[7b57b56e-b34b-4c24-8784-7364974bd246]  
[2021-02-11 22:25:24,487: INFO/MainProcess] Terminating 7b57b56e-b34b-4c24-8784-7364974bd246 (Signals.SIGTERM)
[2021-02-11 22:25:24,503: ERROR/MainProcess] Task handler raised error: Terminated(15)
Traceback (most recent call last):
  File "/home/pakallis/.pyenv/versions/3.8.2/envs/CFD-simulations/lib/python3.8/site-packages/billiard/pool.py", line 1774, in _set_terminated
    raise Terminated(-(signum or 0))
billiard.exceptions.Terminated: 15

```

Turns out the `billiard.exceptions.Terminated` is a log message and no exception is raised at all in the worker.

As no exception is raised in the worker, the worker is not killed and can accept new tasks so I can't reproduce the previously mentioned issues.

As a result, I wonder if the issue is just the `Task handler raised...` log message. Perhaps, we could not display
that message when a task is terminated.
