### ISSUE TITLE
 UnicodeDecodeError when starting beat.

### ISSUE THREAD

**Issue by dmsoft** [celery/celery#2740]
Hello, 

The exception raised after starting "celery -A project beat -l info"
```
[2015-08-03 07:18:54,449: CRITICAL/MainProcess] beat raised exception <class 'UnicodeDecodeError'>: UnicodeDecodeError('ascii', b'\x07\xde\x07\x15\x0b\x15\r\x07\xc6\x0c', 1, 2, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/Users/dm/341/lib/python3.4/site-packages/kombu/utils/__init__.py", line 320, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dm/341/lib/python3.4/site-packages/celery/apps/beat.py", line 112, in start_scheduler
    beat.start()
  File "/Users/dm/341/lib/python3.4/site-packages/celery/beat.py", line 454, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/Users/dm/341/lib/python3.4/site-packages/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/dm/341/lib/python3.4/site-packages/celery/beat.py", line 494, in scheduler
    return self.get_scheduler()
  File "/Users/dm/341/lib/python3.4/site-packages/celery/beat.py", line 489, in get_scheduler
    lazy=lazy)
  File "/Users/dm/341/lib/python3.4/site-packages/celery/utils/imports.py", line 53, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/Users/dm/341/lib/python3.4/site-packages/celery/beat.py", line 358, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/Users/dm/341/lib/python3.4/site-packages/celery/beat.py", line 185, in __init__
    self.setup_schedule()
  File "/Users/dm/341/lib/python3.4/site-packages/celery/beat.py", line 377, in setup_schedule
    self._store['entries']
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xde in position 1: ordinal not in range(128)
```

**Comment by dmsoft** [comment]
When I run "celery -A project beat -l info -s /home/celery/var/run/celerybeat-schedule" it goes with no errors but it seems it doesn't ran the task.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by eltonplima** [comment]
This problem back!

I'm using Celery 4.0.0rc4

celery -A proj worker -l info -B

traceback:

```
celery beat v4.0.0rc4 (0today8) is starting.
__    -    ... __   -        _
LocalTime -> 2016-09-12 15:07:24
Configuration ->
    . broker -> amqp://guest:**@localhost:5672//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> /tmp/celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
[2016-09-12 15:07:24,490: INFO/MainProcess] beat: Starting...
[2016-09-12 15:07:24,534: CRITICAL/MainProcess] beat raised exception <class 'AttributeError'>: AttributeError("'bytes' object has no attribute 'encode'",)
Traceback (most recent call last):
  File "/home/eltonplima/workspace/ativa/sigma/.venv/src/kombu/kombu/utils/objects.py", line 40, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: b'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/apps/beat.py", line 107, in start_scheduler
    service.start()
  File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 522, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/home/eltonplima/workspace/ativa/sigma/.venv/src/kombu/kombu/utils/objects.py", line 42, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 566, in scheduler
    return self.get_scheduler()
  File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 561, in get_scheduler
    lazy=lazy,
  File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 406, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 205, in __init__
    self.setup_schedule()
  File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 436, in setup_schedule
    self._store[b'entries']
  File "/usr/lib/python3.5/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
AttributeError: 'bytes' object has no attribute 'encode'
[2016-09-12 15:07:24,535: WARNING/MainProcess] Traceback (most recent call last):
[2016-09-12 15:07:24,536: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/src/kombu/kombu/utils/objects.py", line 40, in __get__
[2016-09-12 15:07:24,536: WARNING/MainProcess] return obj.__dict__[self.__name__]
[2016-09-12 15:07:24,536: WARNING/MainProcess] KeyError
[2016-09-12 15:07:24,536: WARNING/MainProcess] :
[2016-09-12 15:07:24,536: WARNING/MainProcess] 'scheduler'
[2016-09-12 15:07:24,536: WARNING/MainProcess] During handling of the above exception, another exception occurred:
[2016-09-12 15:07:24,536: WARNING/MainProcess] Traceback (most recent call last):
[2016-09-12 15:07:24,537: WARNING/MainProcess] File "/usr/lib/python3.5/shelve.py", line 111, in __getitem__
[2016-09-12 15:07:24,537: WARNING/MainProcess] value = self.cache[key]
[2016-09-12 15:07:24,537: WARNING/MainProcess] KeyError
[2016-09-12 15:07:24,537: WARNING/MainProcess] :
[2016-09-12 15:07:24,537: WARNING/MainProcess] b'entries'
[2016-09-12 15:07:24,537: WARNING/MainProcess] During handling of the above exception, another exception occurred:
[2016-09-12 15:07:24,537: WARNING/MainProcess] Traceback (most recent call last):
[2016-09-12 15:07:24,537: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/bin/celery", line 11, in <module>
[2016-09-12 15:07:24,538: WARNING/MainProcess] sys.exit(main())
[2016-09-12 15:07:24,538: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/__main__.py", line 15, in main
[2016-09-12 15:07:24,538: WARNING/MainProcess] main()
[2016-09-12 15:07:24,538: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/bin/celery.py", line 333, in main
[2016-09-12 15:07:24,538: WARNING/MainProcess] cmd.execute_from_commandline(argv)
[2016-09-12 15:07:24,539: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/bin/celery.py", line 1154, in execute_from_commandline
[2016-09-12 15:07:24,539: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
[2016-09-12 15:07:24,539: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/bin/base.py", line 239, in execute_from_commandline
[2016-09-12 15:07:24,539: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
[2016-09-12 15:07:24,540: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/bin/celery.py", line 1146, in handle_argv
[2016-09-12 15:07:24,540: WARNING/MainProcess] return self.execute(command, argv)
[2016-09-12 15:07:24,540: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/bin/celery.py", line 1078, in execute
[2016-09-12 15:07:24,541: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2016-09-12 15:07:24,541: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/bin/base.py", line 243, in run_from_argv
[2016-09-12 15:07:24,541: WARNING/MainProcess] sys.argv if argv is None else argv, command)
[2016-09-12 15:07:24,541: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/bin/base.py", line 309, in handle_argv
[2016-09-12 15:07:24,541: WARNING/MainProcess] return self(*args, **options)
[2016-09-12 15:07:24,542: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/bin/base.py", line 202, in __call__
[2016-09-12 15:07:24,542: WARNING/MainProcess] ret = self.run(*args, **kwargs)
[2016-09-12 15:07:24,542: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/bin/beat.py", line 107, in run
[2016-09-12 15:07:24,542: WARNING/MainProcess] return beat().run()
[2016-09-12 15:07:24,542: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/apps/beat.py", line 79, in run
[2016-09-12 15:07:24,542: WARNING/MainProcess] self.start_scheduler()
[2016-09-12 15:07:24,542: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/apps/beat.py", line 107, in start_scheduler
[2016-09-12 15:07:24,543: WARNING/MainProcess] service.start()
[2016-09-12 15:07:24,543: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 522, in start
[2016-09-12 15:07:24,543: WARNING/MainProcess] humanize_seconds(self.scheduler.max_interval))
[2016-09-12 15:07:24,543: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/src/kombu/kombu/utils/objects.py", line 42, in __get__
[2016-09-12 15:07:24,543: WARNING/MainProcess] value = obj.__dict__[self.__name__] = self.__get(obj)
[2016-09-12 15:07:24,543: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 566, in scheduler
[2016-09-12 15:07:24,544: WARNING/MainProcess] return self.get_scheduler()
[2016-09-12 15:07:24,544: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 561, in get_scheduler
[2016-09-12 15:07:24,544: WARNING/MainProcess] lazy=lazy,
[2016-09-12 15:07:24,544: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 406, in __init__
[2016-09-12 15:07:24,545: WARNING/MainProcess] Scheduler.__init__(self, *args, **kwargs)
[2016-09-12 15:07:24,545: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 205, in __init__
[2016-09-12 15:07:24,545: WARNING/MainProcess] self.setup_schedule()
[2016-09-12 15:07:24,545: WARNING/MainProcess] File "/home/eltonplima/workspace/ativa/sigma/.venv/lib/python3.5/site-packages/celery/beat.py", line 436, in setup_schedule
[2016-09-12 15:07:24,545: WARNING/MainProcess] self._store[b'entries']
[2016-09-12 15:07:24,545: WARNING/MainProcess] File "/usr/lib/python3.5/shelve.py", line 113, in __getitem__
[2016-09-12 15:07:24,546: WARNING/MainProcess] f = BytesIO(self.dict[key.encode(self.keyencoding)])
[2016-09-12 15:07:24,546: WARNING/MainProcess] AttributeError
[2016-09-12 15:07:24,546: WARNING/MainProcess] :
[2016-09-12 15:07:24,546: WARNING/MainProcess] 'bytes' object has no attribute 'encode'
```

**Comment by ask** [comment]
If you were using celery 4.0.0rc3 then I think you'd have to remove your schedule database at this time: `rm celerybeat-schedule` (note that this file may have a suffix like .db)

In Celery 3.1 the keys in this db were bytes, then in 4.0 we set them to unicode for a while, then reverting back to bytes.  So if your db was created in between this time it will not work after the change.

**Comment by eltonplima** [comment]
This happened in a fresh install.

**Comment by fergyfresh** [comment]
Happening on a fresh install of celery beat v4.2.1
