### ISSUE TITLE
Add_consumer with eventlet pool causes simultaneous read on socket

### ISSUE THREAD

**Issue by Artimi** [celery/celery#2755]
Hi,

We use RabbitMQ as a broker and backend now. We need to dynamically add new queues to our celery so we use `app.control.add_consumer()` function when need for the new queue arises. Hovewer at the moment I call `add_consumer()` this RuntimeError is thrown:
```
[2015-08-10 14:48:43,612: ERROR/MainProcess] pidbox command error: RuntimeError("Second simultaneous read on fileno 4 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of greenlet.greenlet object at 0x7f254c3c5768>; THAT THREAD=FdListener('read', 4, <built-in method switch of greenlet.greenlet object at 0x7f254fd6b178>, <built-in method throw of greenlet.greenlet object at 0x7f254fd6b178>)",)
Traceback (most recent call last):
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/kombu/pidbox.py", line 105, in dispatch
    reply = handle(method, kwdict(arguments))
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/kombu/pidbox.py", line 123, in handle_call
    return self.handle(method, arguments)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/kombu/pidbox.py", line 120, in handle
    return self.handlers[method](self.state, **arguments)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/celery/worker/control.py", line 350, in add_consumer
    routing_key, **options)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/celery/worker/consumer.py", line 399, in add_task_queue
    cset.add_queue(q)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/kombu/messaging.py", line 418, in add_queue
    queue.declare()
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/kombu/entity.py", line 514, in declare
    self.exchange.declare(nowait)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/kombu/entity.py", line 174, in declare
    nowait=nowait, passive=passive,
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/amqp/channel.py", line 620, in exchange_declare
    (40, 11),  # Channel.exchange_declare_ok
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/amqp/connection.py", line 240, in _wait_method
    self.method_reader.read_method()
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/amqp/method_framing.py", line 107, in _next_method
    frame_type, channel, payload = read_frame()
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/amqp/transport.py", line 154, in read_frame
    frame_header = read(7, True)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/amqp/transport.py", line 277, in _read
    s = recv(n - len(rbuf))
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/eventlet/greenio/base.py", line 326, in recv
    timeout_exc=socket.timeout("timed out"))
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/eventlet/greenio/base.py", line 201, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/eventlet/hubs/__init__.py", line 158, in trampoline
    listener = hub.add(hub.READ, fileno, current.switch, current.throw, mark_as_closed)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/eventlet/hubs/epolls.py", line 49, in add
    listener = BaseHub.add(self, evtype, fileno, cb, tb, mac)
  File "/home/psebek/.virtualenvs/project-x/lib/python3.4/site-packages/eventlet/hubs/hub.py", line 177, in add
    evtype, fileno, evtype, cb, bucket[fileno]))
RuntimeError: Second simultaneous read on fileno 4 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of greenlet.greenlet object at 0x7f254c3c5768>; THAT THREAD=FdListener('read', 4, <built-in method switch of greenlet.greenlet object at 0x7f254fd6b178>, <built-in method throw of greenlet.greenlet object at 0x7f254fd6b178>)
```
You can take a look at the minimal runnin example at https://gist.github.com/Artimi/97375451f298b9e8c745, If you run celery with eventlet pool it fails.

Version of celery and related packages:
```
amqp==1.4.6
celery==3.1.17
greenlet==0.4.7
eventlet==0.17.4
kombu==3.0.26
```

**Comment by amokrov** [comment]
We have same problem with gevent (for python3.4 and python2.7):
```
[2015-08-21 10:18:53,431: ERROR/MainProcess] pidbox command error: AssertionError('This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.hub.Waiter object at 0x7f943d8df3f0>>',)
Traceback (most recent call last):
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/kombu/pidbox.py", line 105, in dispatch
    reply = handle(method, kwdict(arguments))
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/kombu/pidbox.py", line 126, in handle_cast
    return self.handle(method, arguments)
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/kombu/pidbox.py", line 120, in handle
    return self.handlers[method](self.state, **arguments)
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/celery/worker/control.py", line 357, in add_consumer
    routing_key, **options)
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/celery/worker/consumer.py", line 399, in add_task_queue
    cset.add_queue(q)
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/kombu/messaging.py", line 418, in add_queue
    queue.declare()
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/kombu/entity.py", line 514, in declare
    self.exchange.declare(nowait)
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/kombu/entity.py", line 174, in declare
    nowait=nowait, passive=passive,
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/amqp/channel.py", line 620, in exchange_declare
    (40, 11),  # Channel.exchange_declare_ok
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods)
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/amqp/connection.py", line 240, in _wait_method
    self.method_reader.read_method()
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/amqp/method_framing.py", line 107, in _next_method
    frame_type, channel, payload = read_frame()
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/amqp/transport.py", line 154, in read_frame
    frame_header = read(7, True)
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/amqp/transport.py", line 277, in _read
    s = recv(n - len(rbuf))
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/gevent/_socket3.py", line 284, in recv
    self._wait(self._read_event)
  File "/home/amokrov/.virtualenvs/multiscanner/lib/python3.4/site-packages/gevent/_socket3.py", line 119, in _wait
    assert watcher.callback is None, 'This socket is already used by another greenlet: %r' % (watcher.callback, )
AssertionError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.hub.Waiter object at 0x7f943d8df3f0>>
```
Eventlet and gevent use greenlets. When greenlets is used instead class Pidbox used gPidbox:
[worker/consumer.py class Control](https://github.com/celery/celery/blob/72b16ac7c43c9cbd56d2cc9d87ba5552d159ef1e/celery/worker/consumer.py#L682):
```
self.box = (pidbox.gPidbox if self.is_green else pidbox.Pidbox)(c)
```

Because of this addition of the consumer is in dummy thread ('Dummy-2'). But because a socket already in use in main thread we have this problem (two greenlets try to use one socket). When we use class Pidbox (without grenlet or eventlet patching) addition of the consumer is in main thread.

**Comment by ask** [comment]
Guess we need something, where something is anything but a lock.

Best approach would probably be to add these operations to a list, and have the main thread do them.

**Comment by failedguidedog** [comment]
Without the fix in 4.0.0 it is not possible to use `app.control.add_consumer()` while using `eventlet` pool.

Is it possible to backport this fix to the latest 3.1.x version?

**Comment by dtheodor** [comment]
The error for this with a modern version of gevent (1.3.7) surfaces with `ConcurrentObjectUseError: This socket is already used by another greenlet`, traceback looking like this

```
ERROR [kombu.pidbox:109] [pid:9621:DummyThread-2] pidbox command error: ConcurrentObjectUseError('This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.__waiter.Waiter object at 0x7ff398b3c368>>',)
Traceback (most recent call last):
  File "/kombu-3.0.37-py2.7.egg/kombu/pidbox.py", line 105, in dispatch
    reply = handle(method, kwdict(arguments))
  File "/kombu-3.0.37-py2.7.egg/kombu/pidbox.py", line 123, in handle_call
    return self.handle(method, arguments)
  File "/kombu-3.0.37-py2.7.egg/kombu/pidbox.py", line 120, in handle
    return self.handlers[method](self.state, **arguments)
  File "/celery-3.1.25-py2.7.egg/celery/worker/control.py", line 350, in add_consumer
    routing_key, **options)
  File "/celery-3.1.25-py2.7.egg/celery/worker/consumer.py", line 401, in add_task_queue
    cset.add_queue(q)
  File "/kombu-3.0.37-py2.7.egg/kombu/messaging.py", line 419, in add_queue
    queue.declare()
  File "/kombu-3.0.37-py2.7.egg/kombu/entity.py", line 521, in declare
    self.exchange.declare(nowait)
  File "/kombu-3.0.37-py2.7.egg/kombu/entity.py", line 174, in declare
    nowait=nowait, passive=passive,
  File "/amqp-1.4.9-py2.7.egg/amqp/channel.py", line 622, in exchange_declare
    (40, 11),  # Channel.exchange_declare_ok
  File "/amqp-1.4.9-py2.7.egg/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods, timeout)
  File "/amqp-1.4.9-py2.7.egg/amqp/connection.py", line 241, in _wait_method
    channel, method_sig, args, content = read_timeout(timeout)
  File "/amqp-1.4.9-py2.7.egg/amqp/connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
  File "/amqp-1.4.9-py2.7.egg/amqp/method_framing.py", line 193, in read_method
    raise m
ConcurrentObjectUseError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.__waiter.Waiter object at 0x7ff398b3c368>>
```

Adding this in case someone is searching for the issue using the ConcurrentObjectUseError name, took me a while to discover this issue.

**Comment by auvipy** [comment]
@dtheodor could you send a pr for fixing this?
