### ISSUE TITLE
Celery Channel Error 406 with RabbitMQ

### ISSUE THREAD

**Issue by nguyenhoan1988** [celery/celery#2757]
I am using Celery workflow to generate a complex workflow with combination of chord, chain, group together.

Then I keep running to this problem below, if I run multiple workers, multiple threads, I will hit this problem faster and my workers keep being killed.

I use **Redis** as result backend, and **RabbitMQ** as broker.

```
[2015-08-11 10:49:11,613: ERROR/MainProcess] Unrecoverable error: ChannelError('channel error 406, message: PRECONDITION_FAILED - unknown delivery tag 2039',)
Traceback (most recent call last):
  File "/myUser/anaconda/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/myUser/anaconda/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/myUser/anaconda/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/myUser/anaconda/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/myUser/anaconda/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/myUser/anaconda/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/myUser/anaconda/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/myUser/anaconda/lib/python2.7/site-packages/kombu/async/hub.py", line 324, in create_loop
    cb(*cbargs)
  File "/myUser/anaconda/lib/python2.7/site-packages/kombu/transport/base.py", line 162, in on_readable
    reader(loop)
  File "/myUser/anaconda/lib/python2.7/site-packages/kombu/transport/base.py", line 144, in _read
    drain_events(timeout=0)
  File "/myUser/anaconda/lib/python2.7/site-packages/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
ChannelError: channel error 406, message: PRECONDITION_FAILED - unknown delivery tag 2039
```

**Comment by nguyenhoan1988** [comment]
I have tried with the default Python rabbitmq client and the **librabbitmq** library and still get the same issue.

**Comment by nguyenhoan1988** [comment]
It appears that there is some problems with *librabbitmq*, when i use the default client, this problem seems disappear.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
