### ISSUE TITLE
Localhost as a default value - ConnectionRefused

### ISSUE THREAD

**Issue by rakanalh** [celery/celery#2765]
Hello,

I am running a django application with rabbitmq. I have the following configs for celery:

```
BROKER_URL = 'amqp://guest:guest@rabbitmq:5672//'
```

rabbitmq is the hostname that i got defined for the host which runs rabbitmq. 

PS: This is supposed to be a docker container. But i also tried to run this on Vagrant (details to come).

**Vagrant**
Basically what was happening is that executing:
```
celery -A celery_app worker -l debug
```
Would read the correct configurations from my settings.py and do it's thing accordingly. Now on vagrant this fails because i don't define a host with that name.

Running the worker outputs the following:

```
Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno -2] Name or service not known.
```

Which is expected.  However, when i run a django command which triggers a task, no such errors occur. 

This is probably because celery is reading the default value for BROKER_URL which is defined as localhost. On localhost (vagrant), there's rabbitmq installed so there's no problem connecting. But the worker doesn't work because the correct config value was read.

**docker**:
The whole thing started for me because the worker was starting correctly on it's own docker container given that the hostname configuration is correct. However, running the command which triggers the task would output a ```socket.error: [Errno 111] Connection refused```

Stack trace:
```
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/pycms/content_scraper/management/commands/youtube_start.py", line 7, in handle
    youtuber_start.delay()
  File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 243, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/usr/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/usr/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
socket.error: [Errno 111] Connection refused
```

This basically made me debug this issue on vagrant to see what's going on. Here are my packages that i am using (pip freeze):

```
celery==3.1.18
Django==1.7.9
django-celery==3.1.16
flower==0.8.2
kombu==3.0.26
```

Although django-celery is not needed here but it's a legacy app, same behavior if i remove that package.

I am guessing it's a celery issue, according to above but am not sure. WOuld you be so kind to look into that?

Thanks,

**Comment by rakanalh** [comment]
I was looking at the source code, by searching for BROKER_URL and found the [utils.py](https://github.com/celery/celery/blob/master/celery/app/utils.py#L77) 

More observations:
On docker, i defined CELERY_BROKER_URL and both the worker and the command which triggered a task worked. I tried to change that env var to BROKER_URL but celery took the default localhost value again.
Same thing with vagrant, both the worker and the task invocation tried to use the localhost when defining BROKER_URL.

Not sure if the behavior for BROKER_URL vs CELERY_BROKER_URL is documented. Do i always use CELERY_BROKER_URL with environment variables while BROKER_URL in my settings file? If so, the BROKER_URL value being read from the settings file when starting the worker but not when invoking a task, at least for my django setup.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
