### ISSUE TITLE
multi stopwait: possible race: kill can return EPERM if pid gets recycled

### ISSUE THREAD

**Issue by jdufresne** [celery/celery#2785]
I run celery as a non-root user. Occasionally when running `multi stopwait` I'll get an unhandled exception: "OSError: [Errno 1] Operation not permitted". Full trace below.

I investigated this a bit.

In `celery/bin/multi.py`, `stopwait()` eventually ends up in a loop inside `shutdown_nodes()`. Inside, this loop, a signal is sent to the celery process until `ESRCH` is received (signal sent in `node_alive()`). However, inside this loop, while the multi process is sleeping, the celery process could go away and a new process could appear with the same pid; as the OS recycles pids. If this new process, with the same pid, was started by a different user, the kill system call will return `EPERM` (this gets translated to a Python exception).

It appears, Celery is not able to handle this case and so results in an unhandled exception like the one below.

See http://linux.die.net/man/3/kill section "Errors" for a full list of errors returned by the `kill` system call.

```
celery multi v3.1.18 (Cipater)
> Stopping nodes...
    > company@company.com: TERM -> 16451
> Waiting for 1 node -> 16451.....Traceback (most recent call last):
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 97, in run_from_argv
    [command] + argv, prog_name,
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 209, in execute_from_commandline
    self.commands[argv[0]](argv[1:], cmd)
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 394, in stopwait
    return self._stop_nodes(p, cmd, retry=2)
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 372, in _stop_nodes
    callback=callback)
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 320, in shutdown_nodes
    if not self.node_alive(pid):
  File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 277, in node_alive
    os.kill(pid, 0)
OSError: [Errno 1] Operation not permitted
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by vihanb** [comment]
Was this ever resolved. I am having the same issue?

**Comment by auvipy** [comment]
> I run celery as a non-root user. Occasionally when running `multi stopwait` I'll get an unhandled exception: "OSError: [Errno 1] Operation not permitted". Full trace below.
> 
> I investigated this a bit.
> 
> In `celery/bin/multi.py`, `stopwait()` eventually ends up in a loop inside `shutdown_nodes()`. Inside, this loop, a signal is sent to the celery process until `ESRCH` is received (signal sent in `node_alive()`). However, inside this loop, while the multi process is sleeping, the celery process could go away and a new process could appear with the same pid; as the OS recycles pids. If this new process, with the same pid, was started by a different user, the kill system call will return `EPERM` (this gets translated to a Python exception).
> 
> It appears, Celery is not able to handle this case and so results in an unhandled exception like the one below.
> 
> See http://linux.die.net/man/3/kill section "Errors" for a full list of errors returned by the `kill` system call.
> 
> ```
> celery multi v3.1.18 (Cipater)
> > Stopping nodes...
>     > company@company.com: TERM -> 16451
> > Waiting for 1 node -> 16451.....Traceback (most recent call last):
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/bin/celery", line 11, in <module>
>     sys.exit(main())
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/__main__.py", line 30, in main
>     main()
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 81, in main
>     cmd.execute_from_commandline(argv)
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
>     super(CeleryCommand, self).execute_from_commandline(argv)))
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
>     return self.handle_argv(self.prog_name, argv[1:])
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 761, in handle_argv
>     return self.execute(command, argv)
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 693, in execute
>     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/celery.py", line 97, in run_from_argv
>     [command] + argv, prog_name,
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 209, in execute_from_commandline
>     self.commands[argv[0]](argv[1:], cmd)
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 394, in stopwait
>     return self._stop_nodes(p, cmd, retry=2)
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 372, in _stop_nodes
>     callback=callback)
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 320, in shutdown_nodes
>     if not self.node_alive(pid):
>   File "/path/to/venv/a9ec6e728550daa597ef368dc7fa04887aa8577b/lib/python2.6/site-packages/celery/bin/multi.py", line 277, in node_alive
>     os.kill(pid, 0)
> OSError: [Errno 1] Operation not permitted
> ```

can you share any work around or update on this issue?
