### ISSUE TITLE
Worker fails to come up on startup : celery + redis

### ISSUE THREAD

**Issue by hardikjshah** [celery/celery#2830]
I am working with celery and redis as the broker.
2-3 out of every 10 workers that come up fail to start correctly. 
I am attaching the traceback i am getting. 
I also saw a similar issue but it seems like that issue is resolved in newer versions. 
[ https://github.com/celery/celery/issues/1773 ]
I am already on celery - 3.1.18 and kombu - 3.0.26 and on a Linux machine [CentOS]

```
[2015-09-27 15:47:38,717: INFO/MainProcess] Connected to redis://guest@XXXX:6379//
[2015-09-27 15:47:38,846: INFO/MainProcess] mingle: searching for neighbors
[2015-09-27 15:47:48,476: INFO/MainProcess] mingle: sync with 31 nodes
[2015-09-27 15:48:01,806: INFO/MainProcess] mingle: sync complete
[2015-09-27 15:48:02,424: WARNING/MainProcess] celery@celery-worker-XXXXX ready.
[2015-09-27 15:48:02,736: ERROR/MainProcess(11507)] Unrecoverable error: KeyError("Message for queue '7de875c9-f8e5-3d9e-82ec-42a3100e5e86.reply.celery.pidbox' without consumers: {'body': XXXX, 'headers': {'ticket': 'b7e4b012-f82a-48f5-b858-6c50d3475628', 'clock': 694752}, 'content-type': 'application/json', 'properties': {'body_encoding': 'base64', 'delivery_info': {'priority': 0, 'routing_key': '7de875c9-f8e5-3d9e-82ec-42a3100e5e86', 'exchange': 'reply.celery.pidbox'}, 'delivery_mode': 1, 'delivery_tag': '81053833-7c4f-4c7a-a82f-ec828fe78bd2'}, 'content-encoding': 'utf-8'}"
Traceback (most recent call last):
  File "/usr/local/affine/affine/env/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/local/affine/affine/env/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/affine/affine/env/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/affine/affine/env/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/affine/affine/env/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/affine/affine/env/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/affine/affine/env/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/affine/affine/env/lib/python2.7/site-packages/kombu/async/hub.py", line 324, in create_loop
    cb(*cbargs)
  File "/usr/local/affine/affine/env/lib/python2.7/site-packages/kombu/transport/redis.py", line 956, in on_readable
    queue, message))
KeyError: "Message for queue ..... 'content-encoding': 'utf-8'}"

```
Can someone help me on how to fix this. Not sure what i am doing wrong.
Restarting the celery app works without any issues.

**Comment by hardikjshah** [comment]
I am unable to provide a test case since i cant reproduce this issue. I see this very infrequently and unfortunately only in production. I have repeated the same several times in a more controlled dev environment and am unable to reproduce the issue. 
Also, this issue is seen mainly when we have 100s of celery workers started together.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
