### ISSUE TITLE
System entropy source does not have state

### ISSUE THREAD

**Issue by miira** [celery/celery#2853]
After running 'celery worker -A apprrr.tasks' 

this is what I get. I am not quite sure, what to do with this exception. Can anybody please help me? Thank you in advance.

```
-------------- celery@somehost v3.1.18 (Cipater)
---- **** -----
--- * ***  * -- Windows-7-6.1.7601-SP1
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         apprrr.tasks:0x3f22ef0
- ** ---------- .> transport:   sqla+postgresql://user:pass@localhost:5432/somedb
- ** ---------- .> results:     db+postgresql://user:pass@localhost:5432/somedb
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[2015-10-12 18:34:57,124: ERROR/MainProcess] Unrecoverable error: NotImplementedError('System entropy source does not have state.',)
Traceback (most recent call last):
  File "c:\prj\rrr\venv\lib\site-packages\celery\worker\__init__.py", line 206, in start
    self.blueprint.start(self)
  File "c:\prj\rrr\venv\lib\site-packages\celery\bootsteps.py", line 123, in start
    step.start(parent)
  File "c:\prj\rrr\venv\lib\site-packages\celery\bootsteps.py", line 374, in start
    return self.obj.start()
  File "c:\prj\rrr\venv\lib\site-packages\celery\concurrency\base.py", line 131, in start
    self.on_start()
  File "c:\prj\rrr\venv\lib\site-packages\celery\concurrency\prefork.py", line 117, in on_start
    **self.options)
  File "c:\prj\rrr\venv\lib\site-packages\billiard\pool.py", line 968, in __init__
    self._create_worker_process(i)
  File "c:\prj\rrr\venv\lib\site-packages\billiard\pool.py", line 1064, in _create_worker_process
    w.start()
  File "c:\prj\rrr\venv\lib\site-packages\billiard\process.py", line 137, in start
    self._popen = Popen(self)
  File "c:\prj\rrr\venv\lib\site-packages\billiard\forking.py", line 263, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "c:\prj\rrr\venv\lib\site-packages\billiard\py2\reduction.py", line 84, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\dev\python27\Lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\dev\python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\dev\python27\Lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\dev\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\dev\python27\Lib\pickle.py", line 562, in save_tuple
    save(element)
  File "C:\dev\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\dev\python27\Lib\pickle.py", line 548, in save_tuple
    save(element)
  File "C:\dev\python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\dev\python27\Lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\dev\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\dev\python27\Lib\pickle.py", line 548, in save_tuple
    save(element)
  File "C:\dev\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\dev\python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\dev\python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\dev\python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\dev\python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\dev\python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\dev\python27\Lib\pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "C:\dev\python27\Lib\random.py", line 171, in __reduce__
    return self.__class__, (), self.getstate()
  File "C:\dev\python27\Lib\random.py", line 834, in _notimplemented
    raise NotImplementedError('System entropy source does not have state.')
NotImplementedError: System entropy source does not have state.

(venv) C:\prj\rrr>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\prj\rrr\venv\lib\site-packages\billiard\forking.py", line 459, in main
    self = load(from_parent)
  File "C:\dev\python27\Lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\dev\python27\Lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\dev\python27\Lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError


(venv) C:\prj\rrr> python -c "import os; print os.urandom(8).encode('hex')"
1f0fbe592cce3828

(venv) C:\prj\rrr>```

**Comment by miira** [comment]
Hint: It happens only on Windows. I tried this to run on Linux server and it works ok. 
However, I still don't know, how to solve it. :/

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Windows.
