### ISSUE TITLE
Corruption of celerybeat-schedule.db causes beat to fail with incomprehensible PyPy error

### ISSUE THREAD

**Issue by paul-pearce** [celery/celery#2862]
Corruption of celerybeat-schedule.db results in celery.beat failing with:
```
[2015-10-15 16:18:26,921: CRITICAL/MainProcess] beat raised exception <type 'exceptions.KeyError'>: KeyError('clearerr',)
Traceback (most recent call last):
  File "/usr/local/lib/pypy2.7/dist-packages/celery/apps/beat.py", line 112, in start_scheduler
    beat.start()
  File "/usr/local/lib/pypy2.7/dist-packages/celery/beat.py", line 454, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/usr/local/lib/pypy2.7/dist-packages/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/pypy2.7/dist-packages/celery/beat.py", line 494, in scheduler
    return self.get_scheduler()
  File "/usr/local/lib/pypy2.7/dist-packages/celery/beat.py", line 489, in get_scheduler
    lazy=lazy)
  File "/usr/local/lib/pypy2.7/dist-packages/celery/utils/imports.py", line 53, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/celery/beat.py", line 358, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/celery/beat.py", line 185, in __init__
    self.setup_schedule()
  File "/usr/local/lib/pypy2.7/dist-packages/celery/beat.py", line 380, in setup_schedule
    self._store['entries'] = {}
  File "/usr/lib/pypy/lib-python/2.7/shelve.py", line 133, in __setitem__
    self.dict[key] = f.getvalue()
  File "/usr/lib/pypy/lib_pypy/dbm.py", line 75, in __setitem__
    getattr(lib, funcs['clearerr'])(self._aobj)
KeyError: 'clearerr'
```

This is an error condition that should clearly be fatal but the error raised makes it somewhat difficult to diagnose the problem without diving into the source.

**Comment by ask** [comment]
You should mention that you are using PyPy in the title, as this is an important distinction.

The error here is coming from PyPy, and when reading the source there seems to be an obvious bug in PyPy:
https://github.com/rfk/pypy/blob/master/lib_pypy/dbm.py#L143-L151

There's no `clearerr` defined anywhere.

Try defining it and maybe you get to the original error.

**Comment by paul-pearce** [comment]
Thank you. I will raise this on the pypy side as well.
