### ISSUE TITLE
new_cassandra fails with task chaining and threadpool

### ISSUE THREAD

**Issue by piotrmaslanka** [celery/celery#2869]
When running new_cassandra and chaining tasks AND using threadpool following errors are generated:
```
015-10-20 11:34:53,166: WARNING/MainProcess] /usr/lib/python2.7/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: AttributeError("'NoneType' object has no attribute 'execute'",):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/lib/python2.7/site-packages/celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/backends/new_cassandra.py", line 177, in _store_result
    self._session.execute(self._write_stmt, (
AttributeError: 'NoneType' object has no attribute 'execute'

  exc, exc_info.traceback)))
[2015-10-20 11:34:53,167: CRITICAL/MainProcess] Task s4jobs.tasks.read_all_sensors.read_all_sensors[c70808fb-1f16-4e48-86e4-dc9ad44d5852] INTERNAL ERROR: AttributeError("'NoneType' object has no attribute 'execute'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/lib/python2.7/site-packages/celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/backends/new_cassandra.py", line 177, in _store_result
    self._session.execute(self._write_stmt, (
AttributeError: 'NoneType' object has no attribute 'execute'
```

Current debugging indicates that in this case it is possible for self._connection to be None and self._session not none.

As author of this backend I feel obliged to fix this issue. I will post a pull request on ready. Users using process pool are not affected.

**Comment by piotrmaslanka** [comment]
Debug indicates that it is possible for cassandra.cluster.Cluster(...) to return None under some circumstances. This is being investigated.

**Comment by piotrmaslanka** [comment]
```
[2015-10-20 12:00:17,122: INFO/MainProcess] 140337255057152@140336902963280: creates backend
[2015-10-20 12:00:17,223: WARNING/MainProcess] celery@web.smok4 ready.
[2015-10-20 12:00:22,864: INFO/MainProcess] Received task: s4jobs.tasks.build_device.build_device[e2ededd4-8a90-4a3e-a41d-b969d0cfa6f3]
[2015-10-20 12:00:27,396: INFO/MainProcess] 140336919914240: _get_connection
[2015-10-20 12:00:27,397: INFO/MainProcess] 140336919914240@140336902963280: will create new because None None
[2015-10-20 12:00:27,402: INFO/MainProcess] Received task: s4jobs.tasks.read_all_sensors.read_all_sensors[7e2daab8-bbbd-4fa3-8c06-1e77b69112b1]
[2015-10-20 12:00:27,520: INFO/MainProcess] 140336911521536: _get_connection
[2015-10-20 12:00:27,521: INFO/MainProcess] 140336911521536@140336902963280: will create new because <cassandra.cluster.Cluster object at 0x7fa2bb158190> None
[2015-10-20 12:00:27,527: INFO/MainProcess] Received task: s4jobs.tasks.postconfigure_device.postconfigure_device[419391ec-b8e4-4d7c-a483-328ed674c299]
[2015-10-20 12:00:27,654: WARNING/MainProcess] 140336919914240@140336902963280: <cassandra.cluster.Cluster object at 0x7fa2b886a9d0> <cassandra.cluster.Session object at 0x7fa2b90d0d50>
[2015-10-20 12:00:27,673: ERROR/MainProcess] 140336919914240@140336902963280: cleanup?
[2015-10-20 12:00:27,674: INFO/MainProcess] Task s4jobs.tasks.build_device.build_device[e2ededd4-8a90-4a3e-a41d-b969d0cfa6f3] succeeded in 4.76371016214s: None
[2015-10-20 12:00:27,684: WARNING/MainProcess] 140336911521536@140336902963280: None <cassandra.cluster.Session object at 0x7fa2b90a7890>
[2015-10-20 12:00:27,685: ERROR/MainProcess] 140336911521536@140336902963280: cleanup?
[2015-10-20 12:00:27,687: WARNING/MainProcess] /usr/lib/python2.7/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: AssertionError():
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/lib/python2.7/site-packages/celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/backends/new_cassandra.py", line 183, in _store_result
    self._get_connection(write=True)
  File "/usr/lib/python2.7/site-packages/celery/backends/new_cassandra.py", line 145, in _get_connection
    assert self._connection is not None and self._session is not None
AssertionError

  exc, exc_info.traceback)))
[2015-10-20 12:00:27,688: CRITICAL/MainProcess] Task s4jobs.tasks.read_all_sensors.read_all_sensors[7e2daab8-bbbd-4fa3-8c06-1e77b69112b1] INTERNAL ERROR: AssertionError()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/lib/python2.7/site-packages/celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/backends/new_cassandra.py", line 183, in _store_result
    self._get_connection(write=True)
  File "/usr/lib/python2.7/site-packages/celery/backends/new_cassandra.py", line 145, in _get_connection
    assert self._connection is not None and self._session is not None
AssertionError
[2015-10-20 12:00:27,730: INFO/MainProcess] 140336919914240: _get_connection
[2015-10-20 12:00:27,730: INFO/MainProcess] 140336919914240@140336902963280: will create new because None None
[2015-10-20 12:00:27,835: WARNING/MainProcess] 140336919914240@140336902963280: <cassandra.cluster.Cluster object at 0x7fa2b90d0450> <cassandra.cluster.Session object at 0x7fa2b8895390>
[2015-10-20 12:00:27,841: ERROR/MainProcess] 140336919914240@140336902963280: cleanup?
```
(prefixes in logs are thread identifier@object identifier

This confirms an obvious race condition in backend access. Backend will need to be protected with locks against this kind of abuse.

**Comment by piotrmaslanka** [comment]
Running threadpool seems insane. Last night, my single-thread-celery-worker tanked 29 GB of VM space after executing only 1600 tasks.

Retrying the operation with process pool. I think using threadpool should be discouraged at least.

**Comment by thedrow** [comment]
The thread pool relies on an old library that is no longer maintained. Use gevent/eventlet if you need concurrency on I/O.

**Comment by piotrmaslanka** [comment]
reissued as #2895
