### ISSUE TITLE
Chord fails in mark_as_done

### ISSUE THREAD

**Issue by linar-jether** [celery/celery#2885]
Seems to be caused by cd48cd34ae764c6a7e22ead1d51e2e154dd0e194
```python
Traceback (most recent call last):
  File "/home/jether/anaconda/lib/python2.7/site-packages/celery/app/trace.py", line 397, in trace_task
    mark_as_done(uuid, retval, task_request, publish_result)
  File "/home/jether/anaconda/lib/python2.7/site-packages/celery/backends/base.py", line 121, in mark_as_done
    self.on_chord_part_return(request, state)
TypeError: on_chord_part_return() takes at least 4 arguments (3 given)
```

**Comment by linar-jether** [comment]
```diff
index 4b7ae24..e03432f 100644
--- a/tmp/base.py
+++ b/home/jether/anaconda/lib/python2.7/site-packages/celery/backends/base.py
@@ -118,7 +118,7 @@ class BaseBackend(object):
         if store_result:
             self.store_result(task_id, result, status=state, request=request)
         if request and request.chord:
-            self.on_chord_part_return(request, state)
+            self.on_chord_part_return(request, state, result)
 
     def mark_as_failure(self, task_id, exc,
                         traceback=None, request=None, store_result=True,

```
