### ISSUE TITLE
new_cassandra backends fails when Cassandra cluster is unreachable

### ISSUE THREAD

**Issue by piotrmaslanka** [celery/celery#2895]
I have ran some tests with Celery in follow-up with #2869, and here is what I discovered:

when Cluster.connect() fails, backend class is left in inconsistent state that process_cleanup() is unable to salvage. A fix is required that detects when this situation occurs, and sets _connection and _session to None, in order for process_cleanup to work properly.

This is the log that leads to the conclusion:
```
[2015-10-29 13:14:16,610: WARNING/Worker-14] [control connection] Error connecting to 192.168.12.2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cassandra/cluster.py", line 1894, in _reconnect_internal
    return self._try_connect(host)
  File "/usr/lib/python2.7/site-packages/cassandra/cluster.py", line 1935, in _try_connect
    self._refresh_schema(connection, preloaded_results=shared_results)
  File "/usr/lib/python2.7/site-packages/cassandra/cluster.py", line 2096, in _refresh_schema
    responses = connection.wait_for_responses(*queries, timeout=self._timeout, fail_on_error=False)
  File "/usr/lib/python2.7/site-packages/cassandra/connection.py", line 346, in wait_for_responses
    return waiter.deliver(timeout)
  File "/usr/lib/python2.7/site-packages/cassandra/connection.py", line 743, in deliver
    raise OperationTimedOut()
OperationTimedOut: errors=None, last_host=None
[2015-10-29 13:14:16,617: ERROR/Worker-14] Control connection failed to connect, shutting down Cluster:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cassandra/cluster.py", line 755, in connect
    self.control_connection.connect()
  File "/usr/lib/python2.7/site-packages/cassandra/cluster.py", line 1868, in connect
    self._set_new_connection(self._reconnect_internal())
  File "/usr/lib/python2.7/site-packages/cassandra/cluster.py", line 1903, in _reconnect_internal
    raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {'192.168.12.2': OperationTimedOut('errors=None, last_host=None',)})
[2015-10-29 13:14:16,620: ERROR/Worker-14] Process cleanup failed: AttributeError("'NoneType' object has no attribute 'shutdown'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 312, in trace_task
    backend_cleanup()
  File "/usr/lib/python2.7/site-packages/celery/backends/new_cassandra.py", line 90, in process_cleanup
    self._session.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
```

**Comment by piotrmaslanka** [comment]
Fix + unit tests in #2896

**Comment by piotrmaslanka** [comment]
This theory also explains memory leaks that I have experienced. They would stem from failed Cluster objects lying around.

**Comment by piotrmaslanka** [comment]
Memory leak is still there, and I checked that it's not the task to blame. I'll try to figure it out.
