### ISSUE TITLE
LRUCache.update broken on Python 3.5

### ISSUE THREAD

**Issue by brakhane** [celery/celery#2897]
In Python 3.5, OrderedDict does not allow mutating while it is iterated over. This breaks `LRUCache.update` when it is called with a map larger than the maximum size:

``` 
File "/home/dennis/src/celery_/celery/utils/functional.py", line 75, in update
    for item in islice(iter(data), len(data) - limit):
RuntimeError: OrderedDict mutated during iteration
```

PR with fix follows

**Comment by lfam** [comment]
Hi, I'm working on distro packaging for GNU Guix.

We just updated our Python interpreter from 3.4.3 to 3.5.2 and celery's test suite is failing due to this issue, as shown below.

Checking the Git repo, it seems that the bug-fix commit is in celery 3.1.24 as 0cc9a4fd142, but it's not having the intended effect.

What do you recommend we do?

Please let me know if you'd like more information regarding the dependency graph and build environment we are using.

```
======================================================================
ERROR: test_safe_to_remove_while_iteritems (celery.tests.utils.test_functional.test_LRUCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-celery-3.1.24.drv-0/celery-3.1.24/celery/tests/utils/test_functional.py", line 106, in test_safe_to_remove_while_iteritems
    self.assertSafeIter('iteritems')
  File "/tmp/guix-build-python-celery-3.1.24.drv-0/celery-3.1.24/celery/tests/utils/test_functional.py", line 100, in assertSafeIter
    for _ in getattr(x, method)():
  File "/tmp/guix-build-python-celery-3.1.24.drv-0/celery-3.1.24/celery/utils/functional.py", line 88, in _iterate_items
    for k in self:
RuntimeError: OrderedDict mutated during iteration

======================================================================
ERROR: test_safe_to_remove_while_itervalues (celery.tests.utils.test_functional.test_LRUCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-celery-3.1.24.drv-0/celery-3.1.24/celery/tests/utils/test_functional.py", line 112, in test_safe_to_remove_while_itervalues
    self.assertSafeIter('itervalues')
  File "/tmp/guix-build-python-celery-3.1.24.drv-0/celery-3.1.24/celery/tests/utils/test_functional.py", line 100, in assertSafeIter
    for _ in getattr(x, method)():
  File "/tmp/guix-build-python-celery-3.1.24.drv-0/celery-3.1.24/celery/utils/functional.py", line 97, in _iterate_values
    for k in self:
RuntimeError: OrderedDict mutated during iteration

======================================================================
ERROR: test_safe_to_remove_while_keys (celery.tests.utils.test_functional.test_LRUCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-celery-3.1.24.drv-0/celery-3.1.24/celery/tests/utils/test_functional.py", line 109, in test_safe_to_remove_while_keys
    self.assertSafeIter('keys')
  File "/tmp/guix-build-python-celery-3.1.24.drv-0/celery-3.1.24/celery/tests/utils/test_functional.py", line 100, in assertSafeIter
    for _ in getattr(x, method)():
RuntimeError: OrderedDict mutated during iteration

----------------------------------------------------------------------
Ran 1712 tests in 29.499s

FAILED (errors=3, skipped=92)
```

**Comment by ask** [comment]
Looking at the operations in LRUCache they are all protected by a mutex, so I think it's the test here that is simply useless.

The test modifies the underlying OrderedDict directly, but that doesn't actually happen in any code using LRUCache.

**Comment by lfam** [comment]
@ask Thanks for the clarification. I will disable those tests in our packaging.
