### ISSUE TITLE
celery autodiscover_tasks not working for ValueError: Empty module name

### ISSUE THREAD

**Issue by hsiao19** [celery/celery#2908]
When I use autodiscover_tasks without django, I got this error : 
```
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\Scr
ipts\celery.exe\__main__.py", line 9, in <module>
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\celery\__main__.py", line 30, in main
    main()
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\celery\bin\celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\celery\bin\celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\celery\bin\base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\celery\bin\base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\celery\bin\base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\celery\app\utils.py", line 229, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\celery\bin\base.py", line 492, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\kombu\utils\__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "D:\intern\code\Mercurius\email_testing\virtualenv\Django-Celery-Demo\lib
\site-packages\celery\utils\imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named worker
```

Here is my demo project:

```
CeleryDemo/
        /__init__.py
        /Celery.py
        /celeryconfig.py
        /demo/
                  /__init__.py
                  /tasks.py

```

Celery.py:
```
from __future__ import absolute_import
from celery import Celery

import sys

app = Celery()

app.config_from_object('celeryconfig')
app.autodiscover_tasks(['demo'])

```
celeryconfig.py:
```
BROKER_URL = 'amqp://username:password@mq.domain.com'
CELERY_RESULT_BACKEND = 'redis://:password@mq.domain.com'

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT=['json']
```

demo/tasks.py:
```
# from celery import Celery
from celery import shared_task

@shared_task
def add(x, y):
    return x + y

from urllib import urlopen

@shared_task
def getHtml():
    html = urlopen("http://tw.yahoo.com/").read()
    return html
```

**Comment by ask** [comment]
I fixed the confusing error message, but the source of the error is that since your layout is t/demo/tasks.py, you must have `app.autodiscover_tasks(['t.demo'])`.

You probably also want to add `from __future__ import absolute_import` to the top of your tasks module.
