### ISSUE TITLE
Celery Main Process Down on OperationalError: (2006, 'MySQL server has gone away')

### ISSUE THREAD

**Issue by scarchik** [celery/celery#2919]
Hi,

I am using celery mostly for async task. It work perfect on python2.7. 
After update project to newest python 3.5, i got a problem with mysql connections.
All work fine, but in arbitrary period of time (5-10 hours normal work) celeryd fail down with Unrecoverable error.
After raise this error, tasks continue working and save result to DB. And after tasks finished, celeryd die.

Please help find the solution.

### Project configurations
* System: Ubuntu 12.04
* Python 3.5
    * mysqlclient as connector
* Django 1.8.4
* Celery 3.1.18
* Kombu 3.0.29

**Try to tweak mysql and django configuration:**
Mysql:
```
wait_timeout = 3600
```
Django:
```
CONN_MAX_AGE = 3000
```

**Celery Configuration:**
```
BROKER_BACKEND = "kombu.transport.django.Transport"
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERY_IGNORE_RESULT = True
CELERY_RESULT_DB_SHORT_LIVED_SESSIONS = True
CELERY_ALWAYS_EAGER = False
CELERYD_CONCURRENCY = 4
CELERYD_MAX_TASKS_PER_CHILD = 200
CELERYD_TASK_SOFT_TIME_LIMIT = 400
CELERYD_TASK_TIME_LIMIT = 500
CELERY_DISABLE_RATE_LIMITS = True
CELERY_DEFAULT_QUEUE = "default"
CELERY_QUEUES = {
   # 4 queue
}
CELERYBEAT_SCHEDULE = {
   # 8 task with 1-2 min interval 
}
```

### Traceback
```
[2015-11-10 17:45:17,776: ERROR/MainProcess] Unrecoverable error: OperationalError(2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 220, in execute
    self.errorhandler(self, exc, value)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 209, in execute
    r = self._query(query)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 371, in _query
    rowcount = self._do_query(q)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 335, in _do_query
    db.query(q)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/helena/python3/lib/python3.5/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/opt/helena/python3/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/opt/helena/python3/lib/python3.5/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/opt/helena/python3/lib/python3.5/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/opt/helena/python3/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/opt/helena/python3/lib/python3.5/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/opt/helena/python3/lib/python3.5/site-packages/celery/worker/loops.py", line 97, in synloop
    connection.drain_events(timeout=2.0)
  File "/opt/helena/python3/lib/python3.5/site-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/opt/helena/python3/lib/python3.5/site-packages/kombu/transport/virtual/__init__.py", line 830, in drain_events
    item, channel = get(timeout=timeout)
  File "/opt/helena/python3/lib/python3.5/site-packages/kombu/transport/virtual/scheduling.py", line 39, in get
    return self.fun(resource, **kwargs), resource
  File "/opt/helena/python3/lib/python3.5/site-packages/kombu/transport/virtual/__init__.py", line 850, in _drain_channel
    return channel.drain_events(timeout=timeout)
  File "/opt/helena/python3/lib/python3.5/site-packages/kombu/transport/virtual/__init__.py", line 642, in drain_events
    return self._poll(self.cycle, timeout=timeout)
  File "/opt/helena/python3/lib/python3.5/site-packages/kombu/transport/virtual/__init__.py", line 328, in _poll
    return cycle.get()
  File "/opt/helena/python3/lib/python3.5/site-packages/kombu/transport/virtual/scheduling.py", line 39, in get
    return self.fun(resource, **kwargs), resource
  File "/opt/helena/python3/lib/python3.5/site-packages/kombu/transport/django/__init__.py", line 49, in _get
    m = Queue.objects.fetch(queue)
  File "/opt/helena/python3/lib/python3.5/site-packages/kombu/transport/django/managers.py", line 33, in fetch
    queue = self.get(name=queue_name)
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/helena/python3/lib/python3.5/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/helena/python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 220, in execute
    self.errorhandler(self, exc, value)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 209, in execute
    r = self._query(query)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 371, in _query
    rowcount = self._do_query(q)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 335, in _do_query
    db.query(q)
  File "/opt/helena/python3/lib/python3.5/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
```

**Comment by ask** [comment]
Django didn't expose these exceptions before, so it was impossible to catch it. But now that it does we can just add `OperationalError` to Transport.connection_errors

**Comment by scarchik** [comment]
Thank you for your answer.

Can i override Transport.connection_errors without change celery or kombu source?
For example:
```
from celery import Celery
from kombu.transport.memory import Transport
from amqp.exceptions import ConnectionError
from django.db.utils import OperationalError

from my_project import celery_config

environ.setdefault('DJANGO_SETTINGS_MODULE', 'my_project.settings')
from django.conf import settings

celery_app = Celery('my_project')
celery_app.config_from_object(celery_config)
celery_app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

Transport.connection_errors = (ConnectionError, OperationalError, )
```

**Comment by Bakirelived** [comment]
what was the solution for this?

**Comment by scarchik** [comment]
I'm not sure, but problem has gone, after I set BROKER_POOL_LIMIT = 0.
