### ISSUE TITLE
Redis result backend cannot start tasks

### ISSUE THREAD

**Issue by linar-jether** [celery/celery#2942]
On Ubuntu 14.10, updated to current development versions of celery, kombu and billiard, with the redis backend.
(previous version with everything working was just before the lowercase settings change),

and now cannot run tasks (pickle serialization enabled through config), 
```python
[2015-12-01 10:39:52,464: ERROR/MainProcess] Task handler raised error: ValueError('too many values to unpack',)
Traceback (most recent call last):
  File "/home/jether/anaconda2/lib/python2.7/site-packages/billiard/pool.py", line 373, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/home/jether/anaconda2/lib/python2.7/site-packages/celery/app/trace.py", line 511, in _fast_trace_task
    args, kwargs = body
ValueError: too many values to unpack

```

task args example:
```python
[{'chord_size': None, 'task': 'scrapers.fetch_url', 'subtask_type': None, 'kwargs': {'append_time': True, 'ignore_duplicates': True, 'localFileName': 'file.html.gz', 'output_directory': '/path/to/file'}, 'args': ('http://url/file.html',), 'options': {'queue': 'realtime', 'rate_limit': '10/m'}, 'immutable': False}]
```

**Comment by ask** [comment]
Works for me here using task protocol 1 and 2, what are your other settings?

**Comment by cmoiccool** [comment]
I have a similar error message when trying to run this project : https://github.com/kedz/newsblaster after a fresh install.

```
[2015-12-07 14:29:26,838: INFO/Beat] Scheduler: Sending due task every-30-minutes-nyc_times (scheduler.tasks.schedule_newyork_times_spider)
[2015-12-07 14:29:27,234: INFO/MainProcess] Received task: scheduler.tasks.schedule_newyork_times_spider[0f137923-3f82-412e-9a2e-013b5afa1282]  
[2015-12-07 14:29:27,245: ERROR/MainProcess] Task handler raised error: ValueError('too many values to unpack',)
Traceback (most recent call last):
  File "/Users/davidangst/newsblaster_home/venv/lib/python2.7/site-packages/billiard/pool.py", line 373, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/Users/davidangst/newsblaster_home/venv/lib/python2.7/site-packages/celery-4.0.0rc1-py2.7.egg/celery/app/trace.py", line 511, in _fast_trace_task
    args, kwargs = body
ValueError: too many values to unpack
```
