### ISSUE TITLE
Raising an exception initialized with an unpickle-unable exception kills the main process

### ISSUE THREAD

**Issue by TomasFlam** [celery/celery#2943]
In Python 2, raising an exception initialized with an exception, which can be
pickled but not unpickled, kills the main process.

Python: 2.6, 2.7
Celery: 3.1.19
Kombu: 3.0.29
Billiard: 3.3.0.21

Example:
```python
from celery import Celery

app = Celery('kill', broker='amqp://localhost')

class UnpickleUnableException(Exception):
    def __init__(self, x):
        self.x = x

@app.task
def kill():
    raise Exception(UnpickleUnableException(None))

if __name__ == '__main__':
    kill.apply_async()
```

The tracebacks:
```
[2015-12-01 15:44:05,716: ERROR/MainProcess] Unrecoverable error: TypeError('__init__() takes exactly 2 arguments (1 given)', <class 'kill.UnpickleUnableException'>, ())
Traceback (most recent call last):
  File "/home/tomas/src/celery/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/tomas/src/celery/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/tomas/src/celery/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/tomas/src/celery/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/home/tomas/src/celery/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/tomas/src/celery/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/home/tomas/src/celery/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/home/tomas/.virtualenvs/celery27/lib/python2.7/site-packages/kombu/async/hub.py", line 324, in create_loop
    cb(*cbargs)
  File "/home/tomas/src/celery/celery/concurrency/asynpool.py", line 278, in on_result_readable
    next(it)
  File "/home/tomas/src/celery/celery/concurrency/asynpool.py", line 255, in _recv_message
    message = load(BytesIO(bufv))
TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'kill.UnpickleUnableException'>, ())
[2015-12-01 15:44:06,771: ERROR/MainProcess] Task kill.kill[1d5e02e4-b6a1-4519-8773-bcdacecb0ae0] raised unexpected: WorkerLostError('Worker exited prematurely: exitcode 0.',)
Traceback (most recent call last):
  File "/home/tomas/.virtualenvs/celery27/lib/python2.7/site-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: exitcode 0.
```

**Comment by ask** [comment]
It no longer crashes the main process in master:

```pytraceback

2016-10-12 15:45:49,414: ERROR/PoolWorker-1] Task cyanide.tasks.unpick[3ed082dd-cdcd-4219-acdf-af2f0a4c82d5] raised unexpected: Exception(UnpickleUnableException(),)
Traceback (most recent call last):
  File "celery/app/trace.py", line 369, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 623, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/celery/cyanide/cyanide/tasks.py", line 219, in unpick
    raise Exception(UnpickleUnableException(None))
Exception
[2016-10-12 15:45:49,422: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: Exception(UnpickleUnableException(),)>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'exceptions.Exception\'>: it\'s not the same object as exceptions.Exception",)''.>
Traceback (most recent call last):
  File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/billiard-3.5.0.1-py2.7-macosx-10.11-intel.egg/billiard/pool.py", line 370, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/billiard-3.5.0.1-py2.7-macosx-10.11-intel.egg/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/billiard-3.5.0.1-py2.7-macosx-10.11-intel.egg/billiard/reduction.py", line 82, in dumps
    cls(buf, protocol).dump(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 400, in save_reduce
    save(func)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 753, in save_global
    (obj, module, name))
MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: Exception(UnpickleUnableException(),)>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'exceptions.Exception\'>: it\'s not the same object as exceptions.Exception",)''
