### ISSUE TITLE
Make error messages for invalid result backend connection urls less cryptic

### ISSUE THREAD

**Issue by turtlemonvh** [celery/celery#2945]
Currently invalid [connection strings](http://celery.readthedocs.org/en/latest/configuration.html#database-url-examples) can result in pretty hard to decipher stack traces.  Here's an example of what I saw today when using `psycopg2://username:password@postgres:5432/default` (wrong) instead of `db+postgresql+psycopg2://username:password@postgres:5432/default` (correct):

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/process.py", line 292, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 292, in run
    self.after_fork()
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 395, in after_fork
    self.initializer(*self.initargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/concurrency/prefork.py", line 81, in process_initializer
    app=app)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 161, in build_tracer
    backend = task.backend
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 924, in backend
    return self.app.backend
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 626, in backend
    return self._get_backend()
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 445, in _get_backend
    return backend(app=self, url=url)
TypeError: 'module' object is not callable
```

I think that passing the connection strings through a validation function and raising some type of configuration error could make feedback to users much more valuable.

Relevant links

* Related issue on a project that uses celery
    * https://github.com/airbnb/airflow/issues/708
* Related StackOverflow question
    * http://stackoverflow.com/questions/14635673/celery-postgresql-configure-backend

Thanks!

**Comment by mistercrunch** [comment]
:heavy_plus_sign: :heavy_plus_sign:

**Comment by turtlemonvh** [comment]
Awesome - thanks @ask!

**Comment by mistercrunch** [comment]
![img] (http://pixel.nymag.com/imgs/daily/vulture/2015/gifs/leo-toast-9.w529.h352.2x.gif)
