### ISSUE TITLE
graph does not work with chord 

### ISSUE THREAD

**Issue by hevy-CC4477** [celery/celery#2949]
I was trying the nice graph feature on this sample:

```python
@app.task
def mul(x, y):
    return x * y

@app.task
def xsum(numbers):
    return sum(numbers)
```

The task execution work but the graph doesn't work, is it normal ?

```python
>>> chord_tmp = chord([mul.s(2, 3), mul.s(3, 4)], xsum.s())
>>> chord_tmp()
<AsyncResult: 1503ee6f-0a86-49c9-a479-5fce3f4a8bb0>
>>> chord_tmp().get()
18
>>> chord_tmp().graph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/celery-hf/env/lib/python2.6/site-packages/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/celery-hf/env/lib/python2.6/site-packages/celery/result.py", line 320, in graph
    return self.build_graph()
  File "/celery-hf/env/lib/python2.6/site-packages/celery/result.py", line 277, in build_graph
    for parent, node in self.iterdeps(intermediate=intermediate):
  File "/celery-hf/env/lib/python2.6/site-packages/celery/result.py", line 250, in iterdeps
    raise IncompleteStream()
celery.exceptions.IncompleteStream
```

Note: Why does the graph not work with GroupResult? I don't see any reason to not have it.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.
