### ISSUE TITLE
Chord body callback is not called sometimes

### ISSUE THREAD

**Issue by f1nality** [celery/celery#2952]
Hello!

I'm trying to implement such scheme:
I need to make a lot of http requests and perform action when they all completed (no matter successfully or not). So I decided to use Chord for this case.
Http requests can timeout - so I added soft time limit and 1 retry to these tasks.

The problem is that sometimes (1:10) chord completion callback is not called and I don't understand why (look like it happens when Soft time limit exception in one or more tasks being thrown but it could not happen also).

celery==3.1.19

Settings:

```python
BROKER_URL = 'amqp://'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
CELERY_CHORD_PROPAGATES = False
CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1
CELERY_TIMEZONE = 'UTC'
```

Log during this problem (as I understand this is the problem ``[2015-12-06 11:19:22,904: ERROR/MainProcess] Process 'Worker-6' pid:6343 exited with 'exitcode 1'`` - completion is somehow missed because of worked exit):

```
[2015-12-06 11:19:21,482: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[d8ececbe-a021-4164-8e3d-1c072e47956b]
[2015-12-06 11:19:21,608: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[a68137d5-bd66-42f3-9105-0d30920dfec7]
[2015-12-06 11:19:21,609: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[f94382a3-80e2-4d2c-b857-3472a7074861]
[2015-12-06 11:19:21,610: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[a46312c3-866a-4f8f-9d3b-89f44481fb99]
[2015-12-06 11:19:21,610: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[f32d6774-4717-498a-a744-7ccfcd7e904a]
[2015-12-06 11:19:21,663: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[7a2964dd-ec29-4f84-8422-09637c697d0c]
[2015-12-06 11:19:21,666: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[a5f617d2-6e03-4ccc-89a8-28c56a37599b]
[2015-12-06 11:19:21,875: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[e4d6d409-417e-41ae-b8a1-c6ccd3dbd41c]
[2015-12-06 11:19:21,876: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[ca3629b0-be00-4e76-a551-74b2aead7df9]
[2015-12-06 11:19:21,877: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[a4eebb4f-0cb4-46d5-9759-667e45c855a7]
[2015-12-06 11:19:21,877: WARNING/MainProcess] Soft time limit (10s) exceeded for tasks.example_task[99ab892c-5ccc-4d69-b7df-718f45e3075d]
[2015-12-06 11:19:21,661: ERROR/Worker-15] Chord 'dfdf7d09-660a-4368-8866-ccd8679aaf51' raised: SoftTimeLimitExceeded()
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 537, in on_chord_part_return
    deps = GroupResult.restore(gid, backend=task.backend)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 806, in restore
    ).restore_group(id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 320, in restore_group
    meta = self.get_group_meta(group_id, cache=cache)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 313, in get_group_meta
    meta = self._restore_group(group_id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 518, in _restore_group
    meta['result'] = result_from_tuple(result, self.app)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 913, in result_from_tuple
    res, [result_from_tuple(child, app) for child in nodes],
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 913, in <listcomp>
    res, [result_from_tuple(child, app) for child in nodes],
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 919, in result_from_tuple
    return Result(id, parent=parent)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 85, in __init__
    self.app = app_or_default(app or self.app)
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()
[2015-12-06 11:19:22,039: WARNING/Worker-12] /home/www/example-project/env/lib/python3.4/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: SoftTimeLimitExceeded():
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 257, in store_result
    request=request, **kwargs)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 491, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/redis.py", line 160, in set
    return self.ensure(self._set, (key, value), **retry_policy)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/redis.py", line 149, in ensure
    **retry_policy
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/utils/__init__.py", line 211, in retry_over_time
    def retry_over_time(fun, catch, args=[], kwargs={}, errback=None,
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()

  exc, exc_info.traceback)))

[2015-12-06 11:19:21,787: ERROR/Worker-3] Chord 'dfdf7d09-660a-4368-8866-ccd8679aaf51' raised: SoftTimeLimitExceeded()
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 537, in on_chord_part_return
    deps = GroupResult.restore(gid, backend=task.backend)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 806, in restore
    ).restore_group(id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 320, in restore_group
    meta = self.get_group_meta(group_id, cache=cache)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 313, in get_group_meta
    meta = self._restore_group(group_id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 518, in _restore_group
    meta['result'] = result_from_tuple(result, self.app)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 913, in result_from_tuple
    res, [result_from_tuple(child, app) for child in nodes],
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 913, in <listcomp>
    res, [result_from_tuple(child, app) for child in nodes],
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 919, in result_from_tuple
    return Result(id, parent=parent)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 83, in __init__
    def __init__(self, id, backend=None, task_name=None,
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()
[2015-12-06 11:19:21,894: ERROR/Worker-6] Pool process <Worker(Worker-6, started daemon)> error: SoftTimeLimitExceeded()
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 295, in run
    sys.exit(self.workloop(pid=pid))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 356, in workloop
    req = wait_for_job()
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 447, in receive
    ready, req = _receive(1.0)
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 419, in _recv
    return True, loads(get_payload())
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/py3/connection.py", line 263, in recv_payload
    return self._recv_bytes().getbuffer()
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/py3/connection.py", line 437, in _recv_bytes
    buf = self._recv(4)
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/py3/connection.py", line 412, in _recv
    chunk = read(handle, remaining)
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()
[2015-12-06 11:19:22,025: ERROR/Worker-7] Chord 'dfdf7d09-660a-4368-8866-ccd8679aaf51' raised: DecodeError(SoftTimeLimitExceeded(),)
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 537, in on_chord_part_return
    deps = GroupResult.restore(gid, backend=task.backend)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 806, in restore
    ).restore_group(id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 320, in restore_group
    meta = self.get_group_meta(group_id, cache=cache)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 313, in get_group_meta
    meta = self._restore_group(group_id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 516, in _restore_group
    meta = self.decode(meta)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 199, in decode
    accept=self.accept)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/usr/local/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/five.py", line 132, in reraise
    raise value.with_traceback(tb)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
kombu.exceptions.DecodeError: SoftTimeLimitExceeded()
[2015-12-06 11:19:22,180: ERROR/Worker-5] Chord 'dfdf7d09-660a-4368-8866-ccd8679aaf51' raised: SoftTimeLimitExceeded()
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 537, in on_chord_part_return
    deps = GroupResult.restore(gid, backend=task.backend)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 806, in restore
    ).restore_group(id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 320, in restore_group
    meta = self.get_group_meta(group_id, cache=cache)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 313, in get_group_meta
    meta = self._restore_group(group_id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 518, in _restore_group
    meta['result'] = result_from_tuple(result, self.app)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 913, in result_from_tuple
    res, [result_from_tuple(child, app) for child in nodes],
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 913, in <listcomp>
    res, [result_from_tuple(child, app) for child in nodes],
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()
[2015-12-06 11:19:22,293: ERROR/Worker-16] Chord 'dfdf7d09-660a-4368-8866-ccd8679aaf51' raised: DecodeError(SoftTimeLimitExceeded(),)
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 537, in on_chord_part_return
    deps = GroupResult.restore(gid, backend=task.backend)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 806, in restore
    ).restore_group(id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 320, in restore_group
    meta = self.get_group_meta(group_id, cache=cache)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 313, in get_group_meta
    meta = self._restore_group(group_id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 516, in _restore_group
    meta = self.decode(meta)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 199, in decode
    accept=self.accept)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/usr/local/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/five.py", line 132, in reraise
    raise value.with_traceback(tb)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
kombu.exceptions.DecodeError: SoftTimeLimitExceeded()
[2015-12-06 11:19:22,495: ERROR/Worker-8] Chord 'dfdf7d09-660a-4368-8866-ccd8679aaf51' raised: DecodeError(SoftTimeLimitExceeded(),)
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 537, in on_chord_part_return
    deps = GroupResult.restore(gid, backend=task.backend)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 806, in restore
    ).restore_group(id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 320, in restore_group
    meta = self.get_group_meta(group_id, cache=cache)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 313, in get_group_meta
    meta = self._restore_group(group_id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 516, in _restore_group
    meta = self.decode(meta)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 199, in decode
    accept=self.accept)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/usr/local/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/five.py", line 132, in reraise
    raise value.with_traceback(tb)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
kombu.exceptions.DecodeError: SoftTimeLimitExceeded()
[2015-12-06 11:19:22,516: ERROR/Worker-11] Chord 'dfdf7d09-660a-4368-8866-ccd8679aaf51' raised: DecodeError(SoftTimeLimitExceeded(),)
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 537, in on_chord_part_return
    deps = GroupResult.restore(gid, backend=task.backend)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 806, in restore
    ).restore_group(id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 320, in restore_group
    meta = self.get_group_meta(group_id, cache=cache)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 313, in get_group_meta
    meta = self._restore_group(group_id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 516, in _restore_group
    meta = self.decode(meta)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 199, in decode
    accept=self.accept)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/usr/local/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/five.py", line 132, in reraise
    raise value.with_traceback(tb)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
kombu.exceptions.DecodeError: SoftTimeLimitExceeded()
[2015-12-06 11:19:22,514: CRITICAL/MainProcess] Task tasks.example_task[23fee793-2b8c-4c0f-97dd-54e4a967deef] INTERNAL ERROR: SoftTimeLimitExceeded()
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 257, in store_result
    request=request, **kwargs)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 491, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/redis.py", line 160, in set
    return self.ensure(self._set, (key, value), **retry_policy)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/redis.py", line 149, in ensure
    **retry_policy
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/utils/__init__.py", line 211, in retry_over_time
    def retry_over_time(fun, catch, args=[], kwargs={}, errback=None,
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()
[2015-12-06 11:19:22,575: ERROR/Worker-1] Chord 'dfdf7d09-660a-4368-8866-ccd8679aaf51' raised: DecodeError(SoftTimeLimitExceeded(),)
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 537, in on_chord_part_return
    deps = GroupResult.restore(gid, backend=task.backend)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/result.py", line 806, in restore
    ).restore_group(id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 320, in restore_group
    meta = self.get_group_meta(group_id, cache=cache)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 313, in get_group_meta
    meta = self._restore_group(group_id)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 516, in _restore_group
    meta = self.decode(meta)
  File "/home/www/example-project/env/lib/python3.4/site-packages/celery/backends/base.py", line 199, in decode
    accept=self.accept)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/usr/local/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/five.py", line 132, in reraise
    raise value.with_traceback(tb)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
kombu.exceptions.DecodeError: SoftTimeLimitExceeded()
[2015-12-06 11:19:22,904: ERROR/MainProcess] Process 'Worker-6' pid:6343 exited with 'exitcode 1'
```

**Comment by f1nality** [comment]
As I understand this part of log contains worker exit reason:

```
[2015-12-06 11:19:21,894: ERROR/Worker-6] Pool process <Worker(Worker-6, started daemon)> error: SoftTimeLimitExceeded()
Traceback (most recent call last):
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 295, in run
    sys.exit(self.workloop(pid=pid))
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 356, in workloop
    req = wait_for_job()
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 447, in receive
    ready, req = _receive(1.0)
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 419, in _recv
    return True, loads(get_payload())
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/py3/connection.py", line 263, in recv_payload
    return self._recv_bytes().getbuffer()
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/py3/connection.py", line 437, in _recv_bytes
    buf = self._recv(4)
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/py3/connection.py", line 412, in _recv
    chunk = read(handle, remaining)
  File "/home/www/example-project/env/lib/python3.4/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()
```

**Comment by ask** [comment]
It's not a good idea to use time limits for this, use timeouts at the application level (in the HTTP requests).

Time limits are good for detecting cases where you don't handle it manually, but it's a very crude way to time out.

The time limit probably stopped the process at the point when it was storing the results.
