### ISSUE TITLE
celery4 with django got AttributeError: 'NoneType' object has no attribute 'collect' in kombu

### ISSUE THREAD

**Issue by c0b** [celery/celery#2960]
I started a django project following this guide with celery worker using the `@shared_tasks` it runs fine with celery3.19; while now need celery4 for some of its features, but it failed with an exception in kombu

http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

I installed the master version of celery, it shows 4.0.0-rc1, automatically installed all master version of kombu, billiard, and amqp
```console
pip wheel -e 'git+git://github.com/celery/celery.git'
```

this exception raised in django `./manage.py runserver`; while if I ran in `./manage.py shell` and do `from tasks import my_task` and `my_task.async_call([...])` that can succeed, wonder if celery4 changed something that requires an initialization? this error in kombu looks like broker not connected

```
[12/Dec/2015 12:21:36] ERROR [django.request:256] Internal Server Error: /api/site
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 456, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 453, in dispatch
    response = handler(request, *args, **kwargs)
  File "/src/bidder2/bidder_api/viewsets/site_viewset.py", line 58, in create
    task_id = bidder_task.apply_async([site.id, job.id, 'create'])
  File "/usr/lib/python2.7/site-packages/celery/app/task.py", line 501, in apply_async
    **options
  File "/usr/lib/python2.7/site-packages/celery/app/base.py", line 660, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/lib/python2.7/site-packages/celery/app/amqp.py", line 520, in send_task_message
    **properties
  File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 180, in publish
    exchange_name, declare,
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 454, in _ensured
    self.collect()
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 329, in collect
    gc_transport(self._connection)
  File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 101, in _collect
    connection.collect()
AttributeError: 'NoneType' object has no attribute 'collect'
```

**Comment by c0b** [comment]
this may not be a bug, feel free to close it if so; I asked on stackoverflow instead; hopefully get some help

http://stackoverflow.com/questions/34244681/celery4-with-django-got-attributeerror-nonetype-object-has-no-attribute-coll

**Comment by ask** [comment]
Please try the above patch.  Probably there was an error connecting before `self.connection` was even set.

**Comment by ask** [comment]
Wups, wrong repository in commit comment.  The commit was: celery/kombu@91dd48d018c9a3e32a5262bab845c9f7f53ca864

**Comment by c0b** [comment]
no, that didn't fix the problem, but a socket error instead, I tried librabbitmq got the same socket error; I feel it's like the django runserver didn't connect celery at all? and in `./manage.py shell` and from the shell import the task and run `mytask.apply_async([...])` that works well; is there a way how to debug why in django runserver it didn't connect celery?

```console
[12/Dec/2015 21:00:48] ERROR [django.request:256] Internal Server Error: /api/site
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 456, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 453, in dispatch
    response = handler(request, *args, **kwargs)
  File "myproj/viewsets/site_viewset.py", line 58, in create
    task_id = mytask.apply_async([site.id, job.id, 'create'])
  File "myproj/env/lib/python2.7/site-packages/celery/app/task.py", line 501, in apply_async
    **options
  File "myproj/env/lib/python2.7/site-packages/celery/app/base.py", line 660, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "myproj/env/lib/python2.7/site-packages/celery/app/amqp.py", line 520, in send_task_message
    **properties
  File "myproj/env/lib/python2.7/site-packages/kombu/messaging.py", line 180, in publish
    exchange_name, declare,
  File "myproj/env/lib/python2.7/site-packages/kombu/connection.py", line 463, in _ensured
    interval_max)
  File "myproj/env/lib/python2.7/site-packages/kombu/connection.py", line 376, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "myproj/env/lib/python2.7/site-packages/kombu/utils/__init__.py", line 217, in retry_over_time
    return fun(*args, **kwargs)
  File "myproj/env/lib/python2.7/site-packages/kombu/connection.py", line 242, in connect
    return self.connection
  File "myproj/env/lib/python2.7/site-packages/kombu/connection.py", line 748, in connection
    self._connection = self._establish_connection()
  File "myproj/env/lib/python2.7/site-packages/kombu/connection.py", line 700, in _establish_connection
    conn = self.transport.establish_connection()
  File "myproj/env/lib/python2.7/site-packages/kombu/transport/librabbitmq.py", line 126, in establish_connection
    conn = self.Connection(**opts)
  File "myproj/env/lib/python2.7/site-packages/librabbitmq/__init__.py", line 199, in __init__
    self.connect()
ConnectionError: Error opening socket: a socket error occurred
```
