### ISSUE TITLE
RuntimeError: Second simultaneous read on fileno detected

### ISSUE THREAD

**Issue by Glueon** [celery/celery#2963]
I use Django and Celery with eventlet. Basically my task updates one field in postgresql DB.

```
class MyTask(Task):
    abstract = True
    def on_success(...):
          models.MyModel.objects.filter(pk=args[0]).update(somefiekd='Good')
```

Wen I run about 500 threads from time to time I get this error:

````
[CRITICAL/MainProcess] Task app.tasks.mytask[...] INTERNAL ERROR: RuntimeError("Second simultaneous read on fi
leno 2014 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Consider using a pools.Pool. If you do know wh
at you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of greenlet.greenlet object at 0x7fd0b
9c08b90>; THAT THREAD=FdListener('read', 2014, <built-in method switch of greenlet.greenlet object at 0x7fd0bbf2f9c8>, <built-in method throw of greenlet.greenlet object at 0x7fd
0bbf2f9c8>)",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 289, in trace_task
    task_on_success(retval, uuid, args, kwargs)
  File "/usr/src/app/tasks.py", line 10, in on_success
    models.MyModel.objects.filter(pk=args[0]).update(somefield='Good')
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 562, in update
    with transaction.atomic(using=self.db, savepoint=False):
  File "/usr/local/lib/python3.5/site-packages/django/db/transaction.py", line 150, in __enter__
    if not connection.get_autocommit():
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 286, in get_autocommit
    self.ensure_connection()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
  File "/usr/local/lib/python3.5/site-packages/eventlet/support/psycopg2_patcher.py", line 50, in eventlet_wait_callback
    trampoline(conn.fileno(), read=True)
  File "/usr/local/lib/python3.5/site-packages/eventlet/hubs/__init__.py", line 158, in trampoline
    listener = hub.add(hub.READ, fileno, current.switch, current.throw, mark_as_closed)
  File "/usr/local/lib/python3.5/site-packages/eventlet/hubs/epolls.py", line 49, in add
    listener = BaseHub.add(self, evtype, fileno, cb, tb, mac)
  File "/usr/local/lib/python3.5/site-packages/eventlet/hubs/hub.py", line 177, in add
    evtype, fileno, evtype, cb, bucket[fileno]))
RuntimeError: Second simultaneous read on fileno 2014 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Co
nsider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method s
witch of greenlet.greenlet object at 0x7fd0b9c08b90>; THAT THREAD=FdListener('read', 2014, <built-in method switch of greenlet.greenlet object at 0x7fd0bbf2f9c8>, <built-in metho
d throw of greenlet.greenlet object at 0x7fd0bbf2f9c8>)
```

That happens on eventlet==0.17.4 and celery==3.1.19
It does not update DB record, so I guess ignoring this message wouldn't help?

**Comment by Glueon** [comment]
The problem seems to appear if the concurrency level is less than the number of active tasks.

**Comment by ask** [comment]
It means multiple greenthreads are sharing the same socket, and the postgresql connections are not thread safe.

So you simply have to avoid doing this, not sure exactly how, maybe it's in
 the tuning of the postgresql  connection pools. I'm not sure exactly.

Also since you are using eventlet+psycopg2 you need to make sure eventlet is able to 
monkey patch it, which you can check by calling:

    from eventlet.support import psycopg2_patcher
    psycopg2_patcher.make_psycopg_green()

If that fails you probably need to upgrade your version of `psycopg2`.
