### ISSUE TITLE
Celery: worker connection timed out

### ISSUE THREAD

**Issue by shiraiyuki** [celery/celery#2991]
I'm using amqp (1.4.6) , celery (3.1.14) and kombu (3.0.22). Recently, I create a worker in the internet connecting with rabbitmq-server(broker). Sometimes, worker get a [errno110] connection timed out error. The following is the worker's log:

```
[2016-01-07 15:44:02,001: WARNING/MainProcess] Traceback (most recent call last):
[2016-01-07 15:44:02,001: WARNING/MainProcess] File "../lib/python2.7/site-packages/eventlet/hubs/poll.py", line 115, in wait
[2016-01-07 15:44:02,036: WARNING/MainProcess] listener.cb(fileno)
[2016-01-07 15:44:02,036: WARNING/MainProcess] File "../lib/python2.7/site-packages/celery/worker/pidbox.py", line 112, in loop
[2016-01-07 15:44:02,063: WARNING/MainProcess] connection.drain_events(timeout=1.0)
[2016-01-07 15:44:02,063: WARNING/MainProcess] File "../lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
[2016-01-07 15:44:02,074: WARNING/MainProcess] return self.transport.drain_events(self.connection, **kwargs)
[2016-01-07 15:44:02,075: WARNING/MainProcess] File "../lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 91, in drain_events
[2016-01-07 15:44:02,092: WARNING/MainProcess] return connection.drain_events(**kwargs)
[2016-01-07 15:44:02,093: WARNING/MainProcess] File "../lib/python2.7/site-packages/amqp/connection.py", line 302, in drain_events
[2016-01-07 15:44:02,107: WARNING/MainProcess] chanmap, None, timeout=timeout,
[2016-01-07 15:44:02,107: WARNING/MainProcess] File "../lib/python2.7/site-packages/amqp/connection.py", line 365, in _wait_multiple
[2016-01-07 15:44:02,107: WARNING/MainProcess] channel, method_sig, args, content = read_timeout(timeout)
[2016-01-07 15:44:02,107: WARNING/MainProcess] File "../lib/python2.7/site-packages/amqp/connection.py", line 336, in read_timeout
[2016-01-07 15:44:02,107: WARNING/MainProcess] return self.method_reader.read_method()
[2016-01-07 15:44:02,107: WARNING/MainProcess] File "../lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
[2016-01-07 15:44:02,108: WARNING/MainProcess] raise m
[2016-01-07 15:44:02,108: WARNING/MainProcess] error: [Errno 110] Connection timed out
[2016-01-07 15:44:02,108: WARNING/MainProcess] Removing descriptor: 6
[2016-01-07 15:44:17,609: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
app.conf.update(
    CELERY_IGNORE_RESULT=True,
    CELERY_RESULT_BACKEND='rpc://',
    CELERY_DISABLE_RATE_LIMITS=True,
    # CELERY_DEFAULT_DELIVERY_MODE = True,
    CELERY_TASK_SERIALIZER='json',
    CELERY_RESULT_SERIALIZER='json',
    CELERY_TIMEZONE='Asia/Taipei',
    # if the heartbeat is 10.0 and the rate is the default 2.0, the check will be performed every 5 seconds
    # BROKER_HEARTBEAT=10.0,
    # BROKER_HEARTBEAT_CHECKRATE=2.0,
    BROKER_CONNECTION_MAX_RETRIES=None,
)
```

After this error message, when worker reconnect to broker, we get another error message:
consumer: `Cannot connect to amqp://guest:**@***:5672//: [Errno 104] Connection reset by peer`.

Then after a long time, sometimes the worker can reconnect to broker. But when I assign some jobs to the worker, the worker can't run normally. The worker can get the jobs but doesn't return success to
broker.

There is my celery setting: 

```
app.conf.update(
    CELERY_IGNORE_RESULT=True,
    CELERY_RESULT_BACKEND='rpc://',
    CELERY_DISABLE_RATE_LIMITS=True,
    # CELERY_DEFAULT_DELIVERY_MODE = True,
    CELERY_TASK_SERIALIZER='json',
    CELERY_RESULT_SERIALIZER='json',
    CELERY_TIMEZONE='Asia/Taipei',
    # if the heartbeat is 10.0 and the rate is the default 2.0, the check will be performed every 5 seconds
    # BROKER_HEARTBEAT=10.0,
    # BROKER_HEARTBEAT_CHECKRATE=2.0,
    BROKER_CONNECTION_MAX_RETRIES=None,
)
```

Are there any setting that I need to change?
And if the timeout occur, there is a method that we can know the worker is abnormal and restart worker automaticly?

Thanks

**Comment by ask** [comment]
Are there no remote control related errors above in the log, before this happens?

socket.timeout should be ignored in this code, so is this exception different from `socket.timeout`?
https://github.com/celery/celery/blob/3.1/celery/worker/pidbox.py#L111-L114

**Comment by Glueon** [comment]
Are you getting this when you run more tasks than there is a concurrency level?

**Comment by shiraiyuki** [comment]
In my rabbitmq's log, if worker get the error, i got a log like:
=ERROR REPORT==== 20-Jan-2016::10:57:14 ===
closing AMQP connection <0.2631.0> (ip:59989 -> ip:5672):
{inet_error,etimedout}

After the log, the worker got  "[Errno 110] Connection timed out" error and when worker reconnect to broker, it got timeout and "[Errno 104] Connection reset by peer" error until restart the worker.


And sometimes, my rabbitmq's log show:
closing AMQP connection <0.201.11> (127.0.0.1:49464 -> 127.0.0.1:5672):
connection_closed_abruptly

**Comment by Djarnis** [comment]
I was having similar issues using rabbitmq cluster behind an Elastic Load Balancer. What solved the issue for me was setting `BROKER_POOL_LIMIT = None`, disabling connection pooling. Downside is all the opens/closes of connections. These are my other settings: https://gist.github.com/Djarnis/c0d0df15656810123f8a#file-settings-py

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by vivekanand1101** [comment]
I am using Celery version: ```➜  ~ celery --version
4.0.2 (latentcall)
```
I still get the error. Connection timed out. Here is rabbitmq log file for the same:
[https://paste.fedoraproject.org/paste/hf2lbqkyK5ZQ5bBpg0u-eQ](rabbitmq-log-file)

**Comment by vivekanand1101** [comment]
Makes me #wannacry:
 
`=INFO REPORT==== 20-Jul-2017::12:40:55 ===
accepting AMQP connection <0.773.0> (127.0.0.1:59154 -> 127.0.0.1:5672)

=ERROR REPORT==== 20-Jul-2017::12:41:05 ===
closing AMQP connection <0.773.0> (127.0.0.1:59154 -> 127.0.0.1:5672):
{handshake_timeout,frame_header}

=INFO REPORT==== 20-Jul-2017::12:41:07 ===
accepting AMQP connection <0.776.0> (127.0.0.1:59174 -> 127.0.0.1:5672)

=ERROR REPORT==== 20-Jul-2017::12:41:17 ===
closing AMQP connection <0.776.0> (127.0.0.1:59174 -> 127.0.0.1:5672):
{handshake_timeout,frame_header}`

**Comment by vivekanand1101** [comment]
So, i know exactly how to fix this. Removed my ethernet cable and it worked -_-

**Comment by aayushgoel92** [comment]
@vivekanand1101 You are a life saver. Any ideas why this is happening?

**Comment by vivekanand1101** [comment]
@aayushgoel92 nope :(

**Comment by auvipy** [comment]
could you check the master branch with latest versions of dependency?

**Comment by auvipy** [comment]
@alanjds is this still an issue on 4.2? should we close this?

**Comment by alanjds** [comment]
I do not remember to had saw this before, @auvipy.

Is waiting feedback for 8 months. What about pinging @aayushgoel92 and
@shiraiyuki and wait a couple of weeks more?

Then close it :/

**Comment by auvipy** [comment]
sure!

**Comment by vsag96** [comment]
Yes this is still an issue, I am using 4.2.0, I have a rabbitmq 3.6 docker image. If you need more information please let me know, which parts of the codebase should be read for fixing this,I'll be glad to help. This issue has popped up recently #4980 .

**Comment by auvipy** [comment]
@vsag96 could you please install all the package from github master and check?

**Comment by hp685** [comment]
@auvipy I have also observed this recently using master with rabbitmq 3.6:
Detail from rabbitmq log:
=ERROR REPORT==== 26-Nov-2018::09:36:49 ===
closing AMQP connection <0.5823.374> (127.0.0.1:41877 -> 127.0.0.1:5672):
{handshake_timeout,frame_header}

I also increased the handshake_timeout to 60s from 10 but that did not help.

**Comment by sudhishvnair** [comment]
I am also facing this issue with V4.3. Please find trace below.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 510, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/usr/local/lib/python3.6/dist-packages/amqp/channel.py", line 1771, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "/usr/local/lib/python3.6/dist-packages/amqp/abstract_channel.py", line 51, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.6/dist-packages/amqp/method_framing.py", line 144, in write_frame
    frame, 0xce))
  File "/usr/local/lib/python3.6/dist-packages/amqp/transport.py", line 288, in write
    self._write(s)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/nlp_engine/rcm_ai_service/job_man/tasks.py", line 15, in nlp_layered_task
    celery_task_function_pdf_to_json(dParams)
  File "/root/nlp_engine/rcm_ai_service/src/pdf/views.py", line 401, in celery_task_function_pdf_to_json
    dMappedJson=context, dFileInfo=dFileInfo, lDbJsonSet=None)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/usr/local/lib/python3.6/dist-packages/celery/app/base.py", line 756, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/usr/local/lib/python3.6/dist-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 543, in _ensured
    errback and errback(exc, 0)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 436, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 510, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/usr/local/lib/python3.6/dist-packages/amqp/channel.py", line 1771, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "/usr/local/lib/python3.6/dist-packages/amqp/abstract_channel.py", line 51, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.6/dist-packages/amqp/method_framing.py", line 144, in write_frame
    frame, 0xce))
  File "/usr/local/lib/python3.6/dist-packages/amqp/transport.py", line 288, in write
    self._write(s)
kombu.exceptions.OperationalError: [Errno 110] Connection timed out

**Comment by pymonger** [comment]
Setting `BROKER_POOL_LIMIT = None` fixed this issue for me in celery v4.4.0rc3.

**Comment by auvipy** [comment]
thanks for verifying!

**Comment by thedrow** [comment]
@auvipy That's a workaround, not a fix.
Celery should be working with eventlet and a `BROKER_POOL_LIMIT`.

**Comment by tahamr83** [comment]
This still persists for me. We run on kubernetes, and when this occurs our task revokes stop working, the revokes never reach that worker since I couldn't find the *.pidbox queue for that worker in our rabbitmq instance.

**Comment by tahamr83** [comment]
Could it be that for some reason it's a different exception than `socket.timeout` here https://github.com/celery/celery/blob/7dfc1fde3606d261d20eaf13447fdf128e7b9bed/celery/worker/pidbox.py#L119, that causes the consumer to simply shutdown, effectively disabling all Control commands

**Comment by auvipy** [comment]
> Could it be that for some reason it's a different exception than `socket.timeout` here
> 
> https://github.com/celery/celery/blob/7dfc1fde3606d261d20eaf13447fdf128e7b9bed/celery/worker/pidbox.py#L119
> , that causes the consumer to simply shutdown, effectively disabling all Control commands

can you open a PR  and investigate?
