### ISSUE TITLE
[Python3] INTERNAL ERROR: AttributeError("'str' object has no attribute 'decode'",)

### ISSUE THREAD

**Issue by Daenyth** [celery/celery#2997]
I'm getting this error being thrown when a task raises some exceptions. Here's an example

```
Traceback (most recent call last):
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/celery/app/trace.py", line 238, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/cmp/cmp/rate_limit.py", line 78, in __call__
    return super(RateLimitedTask, self).__call__(*args, **kwargs)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/celery/app/trace.py", line 416, in __protected_call__
    return self.run(*args, **kwargs)
[... my task ...]
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/googleapiclient/http.py", line 729, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 503 when requesting https://some.website returned "There was a temporary error. Please try again later.">

During handling of the above exception, another exception occurred:

INTERNAL ERROR: AttributeError("'str' object has no attribute 'decode'",)
Traceback (most recent call last):
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/celery/app/trace.py", line 251, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/celery/app/trace.py", line 125, in handle_failure
    einfo=einfo)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/celery/utils/dispatch/signal.py", line 150, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/raven/contrib/celery/__init__.py", line 49, in process_failure_signal
    'kwargs': kwargs,
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/raven/base.py", line 577, in captureException
    return self.capture('raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/raven/base.py", line 444, in capture
    extra, stack, tags=tags, **kwargs)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/raven/base.py", line 269, in build_msg
    result = handler.capture(**kwargs)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/raven/events.py", line 63, in capture
    transformer=self.transform)
  File "/home/ubuntu/environment3/lib/python3.5/site-packages/raven/utils/stacks.py", line 219, in get_stack_info
    pre_context, context_line, post_context = get_lines_
```

**Comment by ask** [comment]
Seems this traceback is coming from `raven`?  I'm not sure what celery can do to help resolve the issue

**Comment by Daenyth** [comment]
I'll cross-file it there. It's either going to be an internal bug, or celery not passing the right type to one of raven's methods.

**Comment by Daenyth** [comment]
I didn't realize raven wasn't something celery was using - looked into it some more and I'm on an outdated version.

**Comment by ask** [comment]
Sorry, I forget that may not be obvious to you I should have mentioned it's a library used by Sentry. Glad you got it resolved!~
