### ISSUE TITLE
Exception launching celery multi start

### ISSUE THREAD

**Issue by gipi** [celery/celery#3016]
I'm experiencing a real strange error when trying to launch the worker via a init script (the one provided by the project): long story short, I encounter the following situation

```
# C_FAKEFORK=1 /var/www/.virtualenv/bin/celery multi start kebab --workdir=/var/www/app --pidfile=/var/www/%%N.pid --logfile=/var/www/logs/celery/%%N.log --loglevel=DEBUG --app=whatever --time-limit=2000 --concurrency=1 --loglevel=DEBUG
celery multi v3.1.19 (Cipater)
> Starting nodes...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/www/realistico/.virtualenv/lib/python2.7/site-packages/celery/__main__.py", line 54, in <module>
    main()
  File "/var/www/.virtualenv/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 762, in handle_argv
    return self.execute(command, argv)
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 694, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/bin/worker.py", line 211, in run
    pidfile=self.node_format(pidfile, hostname),
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/bin/base.py", line 582, in node_format
    return node_format(s, nodename, **extra)
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 354, in node_format
    s, host, n=name or NODENAME_DEFAULT, **extra)
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 371, in host_format
    return simple_format(s, keys)
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 384, in simple_format
    return pattern.sub(resolve, s)
  File "/var/www/.virtualenv/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 379, in resolve
    resolver = keys[match.expand(expand)]
KeyError: 'k'
        > kebab@ip-10-0-0-5: * Child terminated with errorcode 1
FAILED
```

the strange thing is that the ``KeyError`` is about the first character of the worker name (I tested changing it). I don't know if I'm missing something obvious here.

The installed packages are

```
# /var/www/.virtualenv/bin/pip freeze 
CairoSVG==1.0.18
Collectfast==0.2.3
Django==1.8.8
Markdown==2.6.2
Pillow==2.9.0
TornadIO2==0.0.4
amqp==1.4.9
anyjson==0.3.3
argparse==1.2.1
backports.ssl-match-hostname==3.4.0.2
billiard==3.3.0.22
boto==2.38.0
cairocffi==0.7.2
celery==3.1.19
certifi==2015.9.6.2
cffi==1.3.0
click==6.2
django-admin-bootstrapped==2.5.4
django-bootstrap3==6.2.2
django-celery==3.1.16
django-cors-headers==1.1.0
django-crispy-forms==1.5.2
django-environ==0.4.0
django-extensions==1.6.1
django-filter==0.11.0
django-jquery==1.9.1
django-storages==1.1.8
djangorestframework==3.3.2
djoser==0.4.0
ecdsa==0.13
first==2.0.1
kombu==3.0.33
paramiko==1.15.3
pip-tools==1.4.2
pipcheck==0.0.4
psycopg2==2.6.1
pycparser==2.14
pycrypto==2.6.1
python-dateutil==2.4.2
pytz==2015.7
redis==2.10.5
simplejson==3.8.0
six==1.10.0
tornado==4.2.1
wheel==0.24.0
wsgiref==0.1.2
```

Instead if I launch manually with

```
$ /var/www/.virtualenv/bin/celery worker --app=whatever --workdir=/var/www/app
```

all works fine.

**Comment by ask** [comment]
Seems the problem is caused by using `--logfile=%%N.log` instead of `--logfile=%N.log`

**Comment by ask** [comment]
Difficult to fix as celery_multi converts %%n.log to `%kebab.log`, and sends it to the worker which then tries to expand `%k`

**Comment by gipi** [comment]
Thanks, seems that from my part the error came from a bad copy&paste from a fabric script with a format string used for generate the configuration file.

I'm not an expert of celery implementation, but my first educated guess would be to check if the character following the ``%`` is contained into a list of available format characters, otherwise throw an error like ``format string error`` or whatever.

Right now I have no time to propose a patch, maybe at the end of the week.

**Comment by gipi** [comment]
Thank you for this fix.
