### ISSUE TITLE
beat reports error Bad file descriptor when celery worker embedded beat whose logger use syslog handler start 

### ISSUE THREAD

**Issue by starplanet** [celery/celery#3029]
The problem is: when I start worker embedded beat which uses syslog handler in root logger, it will report the following warning messages. start command is like "celery -A app worker -B -l info".
[2016-01-29 21:02:53,108: WARNING/Beat] Traceback (most recent call last):
[2016-01-29 21:02:53,109: WARNING/Beat] File "/usr/lib/python2.7/logging/handlers.py", line 863, in emit
[2016-01-29 21:02:53,110: WARNING/Beat] self.socket.sendto(msg, self.address)
[2016-01-29 21:02:53,110: WARNING/Beat] error: [Errno 9] Bad file descriptor
[2016-01-29 21:02:53,110: WARNING/Beat] Logged from file beat.py, line 468
[2016-01-29 21:02:53,111: WARNING/Beat] Traceback (most recent call last):
[2016-01-29 21:02:53,111: WARNING/Beat] File "/usr/lib/python2.7/logging/handlers.py", line 863, in emit
[2016-01-29 21:02:53,111: WARNING/Beat] self.socket.sendto(msg, self.address)
[2016-01-29 21:02:53,112: WARNING/Beat] error: [Errno 9] Bad file descriptor
[2016-01-29 21:02:53,112: WARNING/Beat] Logged from file beat.py, line 468
[2016-01-29 21:02:53,112: WARNING/Beat] Traceback (most recent call last):
[2016-01-29 21:02:53,112: WARNING/Beat] File "/usr/lib/python2.7/logging/handlers.py", line 863, in emit
[2016-01-29 21:02:53,113: WARNING/Beat] self.socket.sendto(msg, self.address)
[2016-01-29 21:02:53,113: WARNING/Beat] error: [Errno 9] Bad file descriptor
[2016-01-29 21:02:53,113: WARNING/Beat] Logged from file beat.py, line 468

But when I only start beat using command "celery -A app beat -l info", it works fine and rsyslogd can normally receive beat info messages. I don't know why.

my celery version is 3.1.20, use python 2.7.11。

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

Please start `celery beat` separately for now.  It may also have been fixed in master, so let's see if it comes back.

**Comment by robertaistleitner** [comment]
Too bad this isn't fixed.. Just stumbled upon this when I tried to upgrade from 2.5 to 3.1 because of the high availability feature.. Funny thing is that it still works with 3.0..

**Comment by don1uppa** [comment]
is this still broken or have I stumbled onto something else?

**Comment by DanielArndt** [comment]
I still see this all the time. If you are using the embedded beat, then it's likely the issue you're experiencing.

**Comment by SupremeGit** [comment]
Ugly. I'm seeing this in AWX docker container logs, eg:

[2018-08-21 06:58:50,121: ERROR/Beat] Message Error: Couldn't apply scheduled task cluster_heartbeat: could not receive data from server: Bad file descriptor
['  File "/var/lib/awx/venv/awx/bin/celery", line 11, in <module>\n    sys.exit(main())\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/__main__.py", line 30, in main\n    main()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main\n    cmd.execute_from_commandline(argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv\n    return self.execute(command, argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv\n    return self(*args, **options)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run\n    state_db=self.node_format(state_db, hostname), **kwargs\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start\n    self.blueprint.start(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start\n    step.start(parent)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start\n    return self.obj.start()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/process.py", line 137, in start\n    self._popen = Popen(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/forking.py", line 105, in __init__\n    code = process_obj._bootstrap()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap\n    self.run()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 553, in run\n    self.service.start(embedded_process=True)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 479, in start\n    interval = self.scheduler.tick()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 221, in tick\n    next_time_to_run = self.maybe_due(entry, self.publisher)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 207, in maybe_due\n    exc, traceback.format_stack(), exc_info=True)\n']
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due
    result = self.apply_async(entry, publisher=publisher)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 260, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 252, in apply_async
    **entry.options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/base.py", line 345, in send_task
    options = router.route(options, name, args, kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 50, in route
    route = self.lookup_route(task, args, kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 78, in lookup_route
    return _first_route(self.routes, task, args, kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/utils/functional.py", line 233, in _matcher
    answer = getattr(maybe_evaluate(obj), method)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/utils/ha.py", line 58, in route_for_task
    (changed, instance) = Instance.objects.get_or_register()
  File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 106, in get_or_register
    return (False, self.me())
  File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 86, in me
    if node.exists():
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 670, in exists
    return self.query.has_results(using=self.db)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 517, in has_results
    return compiler.has_results()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 858, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
SchedulingError: Couldn't apply scheduled task cluster_heartbeat: could not receive data from server: Bad file descriptor
[2018-08-21 06:58:50,123: DEBUG/Beat] beat: Waking up in 17.67 seconds.

**Comment by SupremeGit** [comment]
400+ MB of this garbage, every week.
This really is ugly.

**Comment by thedrow** [comment]
You are welcome to provide a fix.
PRs are always welcome.

**Comment by thomasjohn1994** [comment]
Please reopen this

**Comment by auvipy** [comment]
can anyone check the PR in the local setup?

**Comment by auvipy** [comment]
plz ping if not fixed in 4.4
