### ISSUE TITLE
Celery fails to start with Django custom user model

### ISSUE THREAD

**Issue by kviktor** [celery/celery#3041]
I have a weird problem with to start celery with a Django project. It fails with this error, however If I uncomment the cmd.check() in celery's source it works just fine. If I manually call the same command from a Django shell (./manage.py shell) it doesn't raise an exception. The celery file looks like the one in  the tutorial.

```
$ celery worker -A project -l info

Traceback (most recent call last):
  File "celery/fixups/django.py", line 161, in validate_models
    from django.core.management.validation import get_validation_errors
ImportError: No module named 'django.core.management.validation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "django/apps/config.py", line 159, in get_model
    return self.models[model_name.lower()]
KeyError: 'projectuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "celery", line 11, in <module>
    sys.exit(main())
  File "celery/__main__.py", line 30, in main
    main()
  File "celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "celery/bin/celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "celery/bin/celery.py", line 762, in handle_argv
    return self.execute(command, argv)
  File "celery/bin/celery.py", line 694, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "celery/bin/worker.py", line 213, in run
    ).start()
  File "celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "celery/fixups/django.py", line 73, in on_import_modules
    self.worker_fixup.validate_models()
  File "celery/fixups/django.py", line 173, in validate_models
    cmd.check()
  File "django/core/management/base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "django/contrib/auth/checks.py", line 12, in check_user_model
    cls = apps.get_model(settings.AUTH_USER_MODEL)
  File "django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "django/apps/config.py", line 162, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'profile' doesn't have a 'projectuser' model.
```

```python
>>> from django.core.management.base import BaseCommand
>>> cmd =  BaseCommand()
>>> cmd.check()
>>> 
```

project/\_\_init\_\_.py
```python
from .celery import app as celery_app  # noqa
```
project/celery.py
```python
from celery import Celery
from kombu import Exchange, Queue
import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings.base')

from django.conf import settings  # noqa

app = Celery('project', broker=settings.AMQP_URI)

app.conf.update(
    CELERY_RESULT_BACKEND='amqp',
    CELERY_TASK_RESULT_EXPIRES=300,
    CELERY_QUEUES=(
       Queue('manager', Exchange('manager', type='direct'), routing_key="manager"),
       Queue('exec', Exchange('exec', type='direct'), routing_key="exec")
    )

)
```

Versions:
Django==1.8.9
celery==3.1.20
Python 3.4.0

```
$ celery report -A project

software -> celery:3.1.20 (Cipater) kombu:3.0.33 py:3.4.0
            billiard:3.3.0.22 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp

CELERY_TASK_RESULT_EXPIRES: 300
CELERY_QUEUES: 
    (<unbound Queue manager -> <unbound Exchange manager(direct)> -> manager>,
 <unbound Queue exec -> <unbound Exchange exec(direct)> -> exec>)
CELERY_RESULT_BACKEND: 'amqp'
```

**Comment by malinoff** [comment]
I believe this should be fixed in master.
@ask ?

**Comment by kviktor** [comment]
It works with master (celery==4.0.0rc1), thanks!

**Comment by kviktor** [comment]
It runs, but whenever I call a task on its queue I get this error. The WARNING/PoolWorker-1 message is `print(settings.INSTALLED_APPS)` (so the profile app is in INSTALLED apps, I don't know why celery can't find it)

```
 -------------- celery@hostname v4.0.0rc1 (0today8)
---- **** -----
--- * ***  * -- Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty 2016-02-10 14:52:07
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         manager:0x7fedb4977278
- ** ---------- .> transport:   amqp://user:**@127.0.0.1:5672/project
- ** ---------- .> results:     amqp
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> manager          exchange=manager(direct) key=manager
               
 
[tasks]
  . belam
  . execcelery.gcc_compile
  . execcelery.run_program
  . execcelery.run_script
 
[2016-02-10 14:52:08,026: INFO/MainProcess] Connected to amqp://user:**@127.0.0.1:5672/project
[2016-02-10 14:52:08,041: INFO/MainProcess] mingle: searching for neighbors
[2016-02-10 14:52:09,067: INFO/MainProcess] mingle: sync with 1 nodes
[2016-02-10 14:52:09,068: INFO/MainProcess] mingle: sync complete
celery/fixups/django.py:300: UserWarning: Using s
ettings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
 
[2016-02-10 14:52:09,082: WARNING/MainProcess] ce
lery/fixups/django.py:300: UserWarning: Using settings.DEBUG leads to a memory leak, never use this settin
g in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
 
[2016-02-10 14:52:09,084: WARNING/MainProcess] celery@hostname ready.
0[2016-02-10 14:52:53,147: INFO/MainProcess] Received task: belam[f230b09e-34c2-4d14-a365-16ff8cc3e591]  
[2016-02-10 14:52:53,753: WARNING/PoolWorker-1] ('django.contrib.auth', 'django.contrib.contenttypes', 'dj
ango.contrib.sessions', 'django.contrib.sites', 'django.contrib.messages', 'django.contrib.staticfiles', '
django.contrib.admin', 'django_tables2', 'crispy_forms', 'taggit', 'acl', 'widget_tweaks', 'sizefield', 'a
utocomplete_light', 'profile', 'course', 'lecture', 'grading', 'exercise', 'assignment', 'dashboard', 'man
agement', 'rosetta')
[2016-02-10 14:52:53,801: ERROR/PoolWorker-1] Task belam[f230b09e-34c2-4d14-a365-16ff8cc3e591] raised unex
pected: ValueError("Related model 'profile.ProjectUser' cannot be resolved",)
Traceback (most recent call last):
  File "celery/app/trace.py", line 358, in trace_
task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 609, in __prot
ected_call__
    return self.run(*args, **kwargs)
  File "project/project/exercise/tasks.py", line 9, in evaluate_submission
    Submission.objects.get(pk=submission_pk).evaluate()
  File "django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 328, in
get
    num = len(clone)
  File "django/db/models/query.py", line 144, in
__len__
    self._fetch_all()
  File "django/db/models/query.py", line 965, in
_fetch_all
    self._result_cache = list(self.iterator())
  File "django/db/models/query.py", line 238, in
iterator
    results = compiler.execute_sql()
  File "django/db/models/sql/compiler.py", line 8
29, in execute_sql
    sql, params = self.as_sql()
  File "django/db/models/sql/compiler.py", line 3
78, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "django/db/models/sql/compiler.py", line 4
8, in pre_sql_setup
    self.setup_query()
  File "django/db/models/sql/compiler.py", line 3
9, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "django/db/models/sql/compiler.py", line 1
87, in get_select
    for c in self.get_default_columns():
  File "django/db/models/sql/compiler.py", line 5
24, in get_default_columns
    column = field.get_col(alias)
  File "django/db/models/fields/related.py", line
 2027, in get_col
    return super(ForeignKey, self).get_col(alias, output_field or self.related_field)
  File "django/db/models/fields/related.py", line
 1907, in related_field
    return self.foreign_related_fields[0]
  File "django/db/models/fields/related.py", line
 1641, in foreign_related_fields
    return tuple(rhs_field for lhs_field, rhs_field in self.related_fields if rhs_field)
  File "django/db/models/fields/related.py", line
 1628, in related_fields
    self._related_fields = self.resolve_related_fields()
  File "django/db/models/fields/related.py", line
 1613, in resolve_related_fields
    raise ValueError('Related model %r cannot be resolved' % self.rel.to)
ValueError: Related model 'profile.ProjectUser' cannot be resolved
```
