### ISSUE TITLE
Redis TimeoutError will eventually crash the workers

### ISSUE THREAD

**Issue by yetanotherportfolio** [celery/celery#3046]
I have an App with a Redis backend that use:

```
kombu==3.0.33
celery==3.1.20
hiredis==0.2.0
redis==2.10.5
```

I had some issue with redis the other day and I found my worker stopped. The last logs were:

```
[2016-02-08 19:12:36,069: ERROR/MainProcess] Unrecoverable error: TimeoutError('Timeout reading from socket',)
Traceback (most recent call last):
  File "[ENV]lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "[ENV]lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "[ENV]lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "[ENV]lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "[ENV]lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "[ENV]lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "[ENV]lib/python2.7/site-packages/celery/worker/loops.py", line 103, in synloop
    connection.drain_events(timeout=2.0)
  File "[ENV]lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "[ENV]lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 830, in drain_events
    item, channel = get(timeout=timeout)
  File "[ENV]lib/python2.7/site-packages/kombu/transport/redis.py", line 358, in get
    self.maybe_restore_messages()
  File "[ENV]lib/python2.7/site-packages/kombu/transport/redis.py", line 322, in maybe_restore_messages
    num=channel.unacked_restore_limit,
  File "[ENV]lib/python2.7/site-packages/kombu/transport/redis.py", line 188, in restore_visible
    self.unacked_mutex_expire):
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "[ENV]lib/python2.7/site-packages/kombu/transport/redis.py", line 112, in Mutex
    i_won = client.setnx(name, lock_id)
  File "[ENV]lib/python2.7/site-packages/redis/client.py", line 1094, in setnx
    return self.execute_command('SETNX', name, value)
  File "[ENV]lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "[ENV]lib/python2.7/site-packages/redis/client.py", line 582, in parse_response
    response = connection.read_response()
  File "[ENV]lib/python2.7/site-packages/redis/connection.py", line 572, in read_response
    response = self._parser.read_response()
  File "[ENV]lib/python2.7/site-packages/redis/connection.py", line 340, in read_response
    raise TimeoutError("Timeout reading from socket")
TimeoutError: Timeout reading from socket
```

**Comment by yefremat** [comment]
Same thing happened with my app. Requirements:

```
celery==3.1.18
hiredis==0.2.0
kombu==3.0.28
redis==2.10.3
```

And pretty the same traceback

```
[2016-03-12 18:07:33,940] Unrecoverable error: TimeoutError('Timeout reading from socket',)
Traceback (most recent call last):
  File "/home/rchannel/venv/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/rchannel/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/rchannel/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/rchannel/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/home/rchannel/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/rchannel/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/home/rchannel/venv/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/home/rchannel/venv/lib/python2.7/site-packages/kombu/async/hub.py", line 324, in create_loop
    cb(*cbargs)
  File "/home/rchannel/venv/lib/python2.7/site-packages/kombu/transport/redis.py", line 953, in on_readable
    item = self.cycle.on_readable(fileno)
  File "/home/rchannel/venv/lib/python2.7/site-packages/kombu/transport/redis.py", line 325, in on_readable
    return chan.handlers[type]()
  File "/home/rchannel/venv/lib/python2.7/site-packages/kombu/transport/redis.py", line 587, in _receive
    response = c.parse_response()
  File "/home/rchannel/venv/lib/python2.7/site-packages/redis/client.py", line 2150, in parse_response
    return self._execute(connection, connection.read_response)
  File "/home/rchannel/venv/lib/python2.7/site-packages/redis/client.py", line 2132, in _execute
    return command(*args)
  File "/home/rchannel/venv/lib/python2.7/site-packages/redis/connection.py", line 569, in read_response
    response = self._parser.read_response()
  File "/home/rchannel/venv/lib/python2.7/site-packages/redis/connection.py", line 339, in read_response
    raise TimeoutError("Timeout reading from socket")
TimeoutError: Timeout reading from socket
```

**Comment by ask** [comment]
ummm, not sure what to blame this on, but one of my patches seem to be the culprit:
https://github.com/celery/kombu/commit/adf9e9d1

I must have pasted this in vim somehow, but what `south_south_` is doing in my buffer is a mystery :/
