### ISSUE TITLE
Celery workers crashing due to `self.blueprint.start(self)` error

### ISSUE THREAD

**Issue by mickydionisio** [celery/celery#3059]
After upgrading to 3.1.20 we've started to have celery workers die on us. We are using a REDIS backend which is hosted in ElastiCache.

Please advise.
```
[2016-02-16 01:13:01,913: ERROR/MainProcess] Unrecoverable error: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/home/mykola/Env/yoda/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/mykola/Env/yoda/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/mykola/Env/yoda/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/mykola/Env/yoda/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/home/mykola/Env/yoda/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/mykola/Env/yoda/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/home/mykola/Env/yoda/local/lib/python2.7/site-packages/celery/worker/loops.py", line 103, in synloop
    connection.drain_events(timeout=2.0)
  File "/home/mykola/Env/yoda/local/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/mykola/Env/yoda/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 840, in drain_events
    message, queue = item
TypeError: 'NoneType' object is not iterable
```

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in recent versions, or master, so let's see if comes back after 4.0 release.
