### ISSUE TITLE
send_task fails when called from a thread

### ISSUE THREAD

**Issue by dessant** [celery/celery#3071]
Using `delay` works as expected, tested on Windows 10.

```python
from subprocess import Popen
from argparse import ArgumentParser
from time import sleep
from threading import Thread

from celery import Celery
from celery.execute import send_task


app = Celery('worker', broker='redis://')
app.conf.update(
    CELERY_RESULT_BACKEND='redis://',
)


@app.task(bind=True, name='test_task')
def test_task(self, *args):
    return self.request.id


def send():
    task = send_task('test_task')
    # task = test_task.delay()
    result = task.get()
    print(result)


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('--start-celery')
    argv, _ = parser.parse_known_args()
    if argv.start_celery:
        argv = ['worker',
                '--loglevel=INFO',
                '--pool=processes',
                '--concurrency=1']
        app.worker_main(argv)
    else:
        Popen(['python', 'test.py', '--start-celery', 'True'])
        sleep(6)
        Thread(target=send).start()
```

```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kombu\utils\__init__.py", line 423, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kombu\connection.py", line 436, in _ensured
    return fun(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kombu\messaging.py", line 177, in _publish
    channel = self.channel
  File "C:\Python34\lib\site-packages\kombu\messaging.py", line 194, in _get_channel
    channel = self._channel = channel()
  File "C:\Python34\lib\site-packages\kombu\utils\__init__.py", line 425, in __call__
    value = self.__value__ = self.__contract__()
  File "C:\Python34\lib\site-packages\kombu\messaging.py", line 209, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "C:\Python34\lib\site-packages\kombu\connection.py", line 756, in default_channel
    self.connection
  File "C:\Python34\lib\site-packages\kombu\connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "C:\Python34\lib\site-packages\kombu\connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "C:\Python34\lib\site-packages\kombu\transport\pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "C:\Python34\lib\site-packages\amqp\connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "C:\Python34\lib\site-packages\amqp\connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "C:\Python34\lib\site-packages\amqp\transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "C:\Python34\lib\site-packages\amqp\transport.py", line 95, in __init__
    raise socket.error(last_err)
OSError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 911, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 22, in send
    task = send_task('test_task')
  File "C:\Python34\lib\site-packages\celery\local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "C:\Python34\lib\site-packages\celery\app\base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "C:\Python34\lib\site-packages\celery\app\amqp.py", line 305, in publish_task
    **kwargs
  File "C:\Python34\lib\site-packages\kombu\messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "C:\Python34\lib\site-packages\kombu\connection.py", line 457, in _ensured
    interval_max)
  File "C:\Python34\lib\site-packages\kombu\connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "C:\Python34\lib\site-packages\kombu\utils\__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kombu\connection.py", line 237, in connect
    return self.connection
  File "C:\Python34\lib\site-packages\kombu\connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "C:\Python34\lib\site-packages\kombu\connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "C:\Python34\lib\site-packages\kombu\transport\pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "C:\Python34\lib\site-packages\amqp\connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "C:\Python34\lib\site-packages\amqp\connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "C:\Python34\lib\site-packages\amqp\transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "C:\Python34\lib\site-packages\amqp\transport.py", line 95, in __init__
    raise socket.error(last_err)
OSError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by ask** [comment]
First of all, `celery.execute.send_task` is deprecated.   It depends on the current_app, and the current_app is a thread local so in your thread you will be falling back to the default unconfigured app.

Use `app.send_task()`, or set the current_app in the thread:

    def send():
        app.set_current()


Explicitly passing app instances is by far the recommended approach, but setting the current app for each thread is also useful in case you need to depickle a task, or result.

**Comment by dessant** [comment]
@ask, thanks a lot for explaining, it works nicely.

**Comment by ask** [comment]
I really need to remember adding a section about this in the application guide :(
