### ISSUE TITLE
Negative `countdown` accepted when posting tasks, but causes `MainProcess` failure

### ISSUE THREAD

**Issue by twall** [celery/celery#3078]
It's possible to pass a negative value for `countdown`, which then results in an unrecoverable error in `MainProcess` when the task is pulled from the queue for processing.  

This was discovered after a third-party change in date formatting resulted in a `datetime` with a year of 300, which, when converted to seconds and passed as a countdown is a very large negative number.  `Task.retry()` happily accepts the negative number, as does `Celery.send_task()` and the `Producer`.  However, when the task is pulled from the queue, the worker dies:
```
    [2016-02-24 01:08:06,458: ERROR/MainProcess] Unrecoverable error: ValueError('year out of range',)
Traceback (most recent call last):
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/bootsteps.py", line 373, in start
    return self.obj.start()
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/worker/loops.py", line 72, in asynloop
    next(loop)
  File "/opt/venvs/current/lib/python2.7/site-packages/kombu/async/hub.py", line 289, in create_loop
    for fd, event in events or ():
  File "/opt/venvs/current/lib/python2.7/site-packages/kombu/messaging.py", line 598, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/opt/venvs/current/lib/python2.7/site-packages/kombu/messaging.py", line 564, in receive
    [callback(body, message) for callback in callbacks]
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/worker/consumer.py", line 458, in on_task_received
    callbacks)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/worker/strategy.py", line 70, in task_message_handler
    eta = to_timestamp(to_system_tz(req.eta))
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/utils/timeutils.py", line 114, in to_system
    return localize(dt, self.local)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/utils/timeutils.py", line 267, in localize
    dt = dt.astimezone(tz)
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/utils/timeutils.py", line 78, in utcoffset
    if self._isdst(dt):
  File "/opt/venvs/current/lib/python2.7/site-packages/celery/utils/timeutils.py", line 96, in _isdst
    stamp = _time.mktime(tt)
ValueError: year out of range
```

Using version 3.1.11, but examination of github code shows that negative values are still accepted.

**Comment by ask** [comment]
Kind of weird that mktime accepts the year 10e8, but not anything before 1902.

I'm not quite sure what to do here, silently accept it and execute the task is probably acceptable,
but hard to determine the difference between a ValueError where the year is out of range, with another error.

**Comment by twall** [comment]
You seem to be indicating that a negative “countdown” is normal, and that it’s reasonable to have even fairly large negative countdown values.  Why is this the case?

I would think that especially for client-originated calls (where I’m explicitly scheduling a task — at the point of invoking “.apply_async()") asking for a date in the past or a negative countdown would make no sense.

In my case, an explicit `datetime` was passed in for the ETA (which date was incorrect); that date was converted to the seconds offset.

**Comment by ask** [comment]
@twall I don't know what people are doing, all I know is that it currently accepts negative numbers
and since it's a bugfix release we have to continue doing so to keep backwards compatibility
