### ISSUE TITLE
call back error

### ISSUE THREAD

**Issue by uname-yang** [celery/celery#3100]
i use celery in tornado ,when i get this handler,error comes.
```python
    def get(self):
        seed_tasks.add_task.delay(3,8)
        seed_tasks.add_task.apply_async(args=[3,3],callback=self.on_result)
        self.finish()

    def on_result(self, response):
        print response.result
        self.write(str(response.result))
        self.finish()
```
this is my config
```
BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT=['json']
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'UTC'
```
this the error output
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado\web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Users\U6036458\Documents\GitHub\Tornado-Seed\handlers\task.py", line 15, in get
    seed_tasks.add_task.apply_async(args=[3,3],callback=self.on_result)
  File "C:\Python27\lib\site-packages\celery\app\task.py", line 565, in apply_async
    **dict(self._get_exec_options(), **options)
  File "C:\Python27\lib\site-packages\celery\app\base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "C:\Python27\lib\site-packages\celery\app\amqp.py", line 305, in publish_task
    **kwargs
  File "C:\Python27\lib\site-packages\kombu\messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "C:\Python27\lib\site-packages\kombu\connection.py", line 436, in _ensured
    return fun(*args, **kwargs)
  File "C:\Python27\lib\site-packages\kombu\messaging.py", line 188, in _publish
    mandatory=mandatory, immediate=immediate,
  File "C:\Python27\lib\site-packages\kombu\transport\virtual\__init__.py", line 521, in basic_publish
    message, exchange, routing_key, **kwargs
  File "C:\Python27\lib\site-packages\kombu\transport\virtual\exchange.py", line 61, in deliver
    _put(queue, message, **kwargs)
  File "C:\Python27\lib\site-packages\kombu\transport\redis.py", line 703, in _put
    client.lpush(self._q_for_pri(queue, pri), dumps(message))
  File "C:\Python27\lib\site-packages\anyjson\__init__.py", line 141, in dumps
    return implementation.dumps(value)
  File "C:\Python27\lib\site-packages\anyjson\__init__.py", line 87, in dumps
    return self._encode(data)
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <bound method TaskHandler.on_result of <handlers.task.TaskHandler object at 0x0000000003F35400>> is not JSON serializable
```

**Comment by NiuXWolf** [comment]
he has same problem with me 
http://stackoverflow.com/questions/28804029/tornado-celery-cant-use-gen-task-or-callback

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Tornado.
