### ISSUE TITLE
WorkerLostError on numpy.dot operation

### ISSUE THREAD

**Issue by allwinpb** [celery/celery#3128]
As above. A numpy dot operation on a medium sized numpy 2d matrix seems to segfault when run on a worker but works correctly when run on the regular python interpreter. Very trivial cases execute without issues. For example,

```
import numpy as np
sample_a = [[0,0],[0,1]]
sample_b = [[1,1],[0,1]]
print np.dot(sample_a, sample_b)
```

will execute and print properly in both regular python and inside a Celery worker.

However, larger ndarrays will Segfault and throw the above mentioned WorkerLostError when run inside a worker. Works perfectly fine when run on the interpreter.

```
sample_a = np.load('sample_a.npy')
sample_b = np.load('sample_b.npy')
sample_c = np.dot(sample_a, sample_b)
```

The above mentioned `sample_a.npy` and `sample_b.npy` have shapes `(633,113)` and `(113, 633)` respectively. They can be downloaded here: https://www.dropbox.com/sh/caie9f07b34hzs3/AAC7g3Ns_ttNOUeLYYovDqMla?dl=0. I can't seem to attach it with this Issue because of Github restrictions. In any case the error should be reproducible with any numpy array of similar shape.

I'm using the Jobtastic wrapper on top of Celery for the extra features but I'm fairly certain the problem is not there. Please correct if this is a bad assumption.

Traceback with `faulthandler`:

```
Fatal Python error: Segmentation fault

Current thread 0x00007fff723f2000 (most recent call first):
  File "/Users/allwin/Projects/contrast/tweetsearch/analyzers.py", line 133 in calculate_result
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/jobtastic/task.py", line 362 in run
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/app/trace.py", line 438 in __protected_call__
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/app/trace.py", line 240 in trace_task
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/app/trace.py", line 349 in _fast_trace_task
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/billiard/pool.py", line 367 in workloop
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/billiard/pool.py", line 295 in run
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/billiard/process.py", line 292 in _bootstrap
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/billiard/forking.py", line 105 in __init__
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/billiard/process.py", line 137 in start
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/billiard/pool.py", line 1068 in _create_worker_process
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 415 in _create_worker_process
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/billiard/pool.py", line 972 in __init__
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 401 in __init__
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 119 in on_start
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/concurrency/base.py", line 131 in start
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bootsteps.py", line 374 in start
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bootsteps.py", line 123 in start
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/worker/__init__.py", line 206 in start
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bin/worker.py", line 212 in run
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bin/base.py", line 274 in __call__
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bin/worker.py", line 179 in run_from_argv
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bin/celery.py", line 717 in execute
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bin/celery.py", line 785 in handle_argv
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bin/base.py", line 311 in execute_from_commandline
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bin/celery.py", line 793 in execute_from_commandline
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/bin/celery.py", line 81 in main
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/celery/__main__.py", line 30 in main
  File "/Users/allwin/Envs/fyp/bin/celery", line 11 in <module>
[2016-03-22 06:16:53,326: ERROR/MainProcess] Process 'Worker-2' pid:32104 exited with 'signal 11 (SIGSEGV)'
[2016-03-22 06:16:53,350: ERROR/MainProcess] Task tweetsearch.analyzers.TweetDataAnalyzer[cdd5320d-f9eb-4392-af22-0c76037cad11] raised unexpected: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).',)
Traceback (most recent call last):
  File "/Users/allwin/Envs/fyp/lib/python2.7/site-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
```

Output of `celery -A tweetsearch.analyzers report`

```
software -> celery:3.1.23 (Cipater) kombu:3.0.34 py:2.7.8
            billiard:3.3.0.23 redis:2.10.3
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost/
```

Output of `pip freeze` (using virtualenv)

```
Django==1.8.4
amqp==1.4.9
anyjson==0.3.3
billiard==3.3.0.23
celery==3.1.23
cycler==0.9.0
django-websocket-redis==0.4.4
faulthandler==2.4
gevent==1.0.2
greenlet==0.4.9
jobtastic==0.3.1
kombu==3.0.34
matplotlib==1.5.0
mongoengine==0.10.0
mysqlclient==1.3.7
nltk==3.1
numpy==1.10.4
oauthlib==1.0.3
pandas==0.17.0
psutil==3.2.1
pymongo==3.0.3
pyparsing==2.0.6
python-dateutil==2.4.2
pytz==2016.1
redis==2.10.3
requests==2.8.0
requests-oauthlib==0.6.0
scikit-learn==0.17.1
scipy==0.16.0
six==1.10.0
twython==3.3.0
wsgiref==0.1.2
```

Thank you all!

**Comment by ask** [comment]
Closing this, as we don't have the resources to support Numpy :(

**Comment by allwinpb** [comment]
Ah that's alright. I did eventually manage to get it working using `--pool=threads` when starting the worker. I'm leaving this here in case someone shows up here with the same problem. Cheers!

**Comment by kwin-wang** [comment]
@allwinpb Thanks for your advice about the similar question, I encounter this question too, but I get it working using `--pool=eventlet`

**Comment by vin18** [comment]
@allwinpb @kwin-wang 
Facing a similar issue
Additionally, I also want to spawn multiple processes to handle this. Seems celery does not support it.

**Comment by vin18** [comment]
@auvipy @ask Does celery have a huge memory footprint? I was able to run the worker when the matrix size is very small. However, the matrix original size which works without celery crashes the worker. 

Mem stats just before failing step:

With Celery:::
svmem(total=17179869184, available=3193221120, percent=81.4, used=13426524160, free=1235218432, active=6288064512, inactive=1958002688, wired=5180456960)


Without Celery:::
svmem(total=17179869184, available=3080290304, percent=82.1, used=13533560832, free=1132785664, active=6662369280, inactive=1947504640, wired=4923686912)

**Comment by momonala** [comment]
I experience this issue using `np.matmul` (similar enough to `np.dot`) and I solved the issue by swapping that method out for using scipy's sparse matrices: 

```
def sparse_multiply(n, m):
    """ Multiply two sparse matrices. Input matrices should align along inner axis.
    Args:
        n (np.array): left matrix
        m (np.array): right matrix
    Returns:
          Multipled matrix of n and m, as a np.array.
    """
    from scipy.sparse import csr_matrix
    k = csr_matrix(n) @ csr_matrix(m)
    return k.todense()
```

**Comment by gtmtg** [comment]
`pool=threads` worked for us as well!

**Comment by auvipy** [comment]
what fix you think should be applied to celery?
