### ISSUE TITLE
OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by joetheone** [celery/celery#3160]
I'm running celery 3.1.18. One of my production workers completely stopped, and when I checked the logs I found this error

    [2016-04-11 10:31:40,967: ERROR/MainProcess] Unrecoverable error: OverflowError('signed integer is greater than maximum',)
    Traceback (most recent call last):
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/celery/worker/loops.py", line 95, in synloop
    qos.update()
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/kombu/common.py", line 400, in update
    return self.set(self.value)
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/kombu/common.py", line 393, in set
    self.callback(prefetch_count=new_value)
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 614, in set_prefetch_count
    apply_global=qos_global,
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/kombu/messaging.py", line 533, in qos
    apply_global)
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/amqp/channel.py", line 2205, in basic_qos
    (60, 11),  # Channel.basic_qos_ok
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods, timeout)
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/amqp/connection.py", line 241, in _wait_method
    channel, method_sig, args, content = read_timeout(timeout)
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
      File "/home/ubuntu/mozio/env/local/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
    OverflowError: signed integer is greater than maximum

**Comment by trifle** [comment]
I hit this as well when running a worker on Mac OS.
Celery is 3.1.23, Python 2.7.11, kombu 3.0.35, amqp 1.4.9, consuming from RabbitMQ.

One thing I noticed is that the heartbeat queue fills up with messages that are never consumed and/or expired.

**Comment by ask** [comment]
So apparently the length argument to `recv(2)` is an unsigned int, but Python's `socket.read` is a signed int :/

I think 611f6ac990692ef5a92b4ecf255f9d4132d29d68 should fix this for the current stable amqp version, so could you please try running from the py-amqp 1.4 branch?

**Comment by trifle** [comment]
Thanks! I installed the current 1.4 branch and this seems to fix the bug, at least in my short testing.
Before, C-c on the worker would trigger the Overflow.

    pip install -U git+https://github.com/celery/py-amqp.git@1.4

    Collecting git+https://github.com/celery/py-amqp.git@1.4
      Cloning https://github.com/celery/py-amqp.git (to 1.4) to /var/folders/xp/lzrxdbyd4bddhkj03s32ypgm0000gn/T/pip-Vnvw9J-build
    Installing collected packages: amqp
      Found existing installation: amqp 1.4.9
        Uninstalling amqp-1.4.9:
          Successfully uninstalled amqp-1.4.9
      Running setup.py install for amqp ... done
    Successfully installed amqp-1.4.9
