### ISSUE TITLE
Celery beat exits with code 0 when an exception occurs

### ISSUE THREAD

**Issue by SimonPe** [celery/celery#3169]
When while running celery looses connection with the rabitmq host, an exception is raised. This exception gets caught in celery/apps/beat.py but the program still exits, Since the exception was already caught, it will just return "0" meaning success, which is clearly incorrect.

If an exception causes celery-beat to go down, It should exit with a non 0 return code.

This is important for people running the celery process from systemd with options like "Restart=on-failure" as now systemd has no clue on whether the process exited with an error or not.

I made a quick patch for this in #3168, but that probably needs more work.

Stack trace in the log (not really the issue I want to discuss here, but for completeness sake:
```
[2016-04-14 11:30:23,370: CRITICAL/MainProcess] beat raised exception <class 'socket.error'>: error(104, 'Connection reset by peer')
Traceback (most recent call last):
  File "eggs/celery-3.1.18-py2.7.egg/celery/apps/beat.py", line 112, in start_scheduler
    beat.start()
  File "eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 463, in start
    interval = self.scheduler.tick()
  File "eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 221, in tick
    next_time_to_run = self.maybe_due(entry, self.publisher)
  File "eggs/kombu-3.0.26-py2.7.egg/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 343, in publisher
    return self.Publisher(self._ensure_connected())
  File "eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 327, in _ensure_connected
    _error_handler, self.app.conf.BROKER_CONNECTION_MAX_RETRIES
  File "eggs/kombu-3.0.26-py2.7.egg/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "eggs/kombu-3.0.26-py2.7.egg/kombu/utils/__init__.py", line 243, in retry_over_time
    return fun(*args, **kwargs)
  File "eggs/kombu-3.0.26-py2.7.egg/kombu/connection.py", line 237, in connect
    return self.connection
  File "eggs/kombu-3.0.26-py2.7.egg/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "eggs/kombu-3.0.26-py2.7.egg/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "eggs/kombu-3.0.26-py2.7.egg/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "eggs/amqp-1.4.6-py2.7.egg/amqp/connection.py", line 180, in __init__
    (10, 30),  # tune
  File "eggs/amqp-1.4.6-py2.7.egg/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods)
  File "eggs/amqp-1.4.6-py2.7.egg/amqp/connection.py", line 240, in _wait_method
    self.method_reader.read_method()
  File "eggs/amqp-1.4.6-py2.7.egg/amqp/method_framing.py", line 189, in read_method
    raise m
error: [Errno 104] Connection reset by peer
```

**Comment by SimonPe** [comment]
fixed in #3168 closing this one.
