### ISSUE TITLE
Documentation: Celery calling tasks error - OSError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by sumitgoelpw** [celery/celery#3176]
Hi there,

I have Django==1.9.5, celery==3.1.23, kombu==3.0.35 and amqp==1.4.9 with redis broker and redis==2.10.5 running on Python 3.5.1. I am running redis locally, installed using brew.

I followed the documentionation http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html but keep getting below error,

```
Python 3.5.1 (default, Mar  5 2016, 15:28:46)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from focuss.tasks import add
>>> add.delay(3,2)
Traceback (most recent call last):
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/utils/__init__.py", line 423, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/connection.py", line 436, in _ensured
    return fun(*args, **kwargs)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/messaging.py", line 177, in _publish
    channel = self.channel
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/messaging.py", line 194, in _get_channel
    channel = self._channel = channel()
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/utils/__init__.py", line 425, in __call__
    value = self.__value__ = self.__contract__()
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/messaging.py", line 209, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/connection.py", line 757, in default_channel
    self.connection
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
OSError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/celery/app/task.py", line 565, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/Users/sumit.goel/.virtualenvs/myfocus/lib/python3.5/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
OSError: [Errno 61] Connection refused
>>>
```

I have following config for celery in settings.py,

```
BROKER_URL = 'redis://127.0.0.1:6379/'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
```

Google search shows similar issue had been reported under https://github.com/celery/kombu/issues/369 but the issue is closed with a comment that Python 3 issue back in 2014. Please help to resolve the issue.

**Comment by xavierp** [comment]
Hello !

Got the same issue here :

Traceback (most recent call last):
  File "/Users/xp/.pyenv/versions/3.5.1/envs/venv-beepbeep/lib/python3.5/site-packages/kombu/utils/__init__.py", line 423, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

Causing another error :

  File "/Somepath/lib/python3.5/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
OSError: [Errno 61] Connection refused

Here are my pip packages : alembic (0.8.5), amqp (1.4.9), anyjson (0.3.3), apipkg (1.4), billiard (3.3.0.23), celery (3.1.23), coverage (4.0.3), croniter (0.3.12), docutils (0.12), execnet (1.4.1), kombu (3.0.35), lockfile (0.12.2), Mako (1.0.4), MarkupSafe (0.23), pep8 (1.7.0), pip (8.1.1), py (1.4.31), PyMySQL (0.7.2), pytest (2.9.1), pytest-cache (1.0), pytest-cov (2.2.1), pytest-pep8 (1.0.6), python-daemon (2.1.1), python-dateutil (2.5.2), python-editor (0.5), pytz (2016.4), PyYAML (3.11), redis (2.10.5), setuptools (20.3.1), six (1.10.0), SQLAlchemy (1.0.12), wheel (0.29.0).

I'm on Python 3.5.1 and i use Redis as Broker.
Here is my Celery config :
CELERY_ENABLE_UTC=True,
CELERY_TIMEZONE='Europe/London',
CELERY_ACCEPT_CONTENT=['json', 'pickle'],
BROKER_URL=redis:/some-server:6379/0,
CELERY_RESULT_ENGINE_OPTIONS={'module': pymysql, 'echo': True}).

By the way the workers have no probleme to connect to the broker :
-------------- celery@local v3.1.23 (Cipater)
---- **** -----
--- * ***  * -- Darwin-15.3.0-x86_64-i386-64bit
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         beepbeep-celery:0x1081cd048
- ** ---------- .> transport:   redis://some-server:6379/0
- ** ---------- .> results:     mysql://user@server.com/celery_backend_dev
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . beepbeep.celery.execute_command

[2016-04-29 16:03:11,852: INFO/MainProcess] Connected to redis://server.com:6379/0
[2016-04-29 16:03:11,897: INFO/MainProcess] mingle: searching for neighbors
[2016-04-29 16:03:12,963: INFO/MainProcess] mingle: sync with 1 nodes
[2016-04-29 16:03:12,964: INFO/MainProcess] mingle: sync complete
[2016-04-29 16:03:13,081: WARNING/MainProcess] celery@local ready.

Any help would be very appreciated.

**Comment by xavierp** [comment]
Hi there.
I found out the solution.

It was a sort of a configuration problem. I think that my task wasnt properly connected to the app, leading to connections problems.
I was using the @task decorator directly instead of @app.task.

Hope this will help.

**Comment by virusdefender** [comment]
@xavierp 

I met the same issue. 
Did you replace "@task" with "@app.task"？

My code is listed below
```python
from django_project_name import celery_app

@celery_app.task
def func(foo, bar):
    pass
```

```python
# settings.py

REDIS_LOCAL_QUEUE = {
    "host": os.environ["REDIS_PORT_6379_TCP_ADDR"],
    "port": 6379,
    "db": 3,
    "password": ":" + os.environ["REDIS_PASSWORD"] + "@"
}

BROKER_URL = "redis://{password}{host}:{port}/{db}".format(password=REDIS_LOCAL_QUEUE.get("password", ""),
                                                           host=REDIS_LOCAL_QUEUE["host"],
                                                           port=REDIS_LOCAL_QUEUE["port"],
                                                           db=REDIS_LOCAL_QUEUE["db"])
```

It seems my config in `django_project_name/settings.py` does not work. I do not know why celery attempts to connect to `127.0.0.1`

![qq20160503-0 2x](https://cloud.githubusercontent.com/assets/4939404/14973608/84f3511c-111c-11e6-8c9c-2b85783c1329.png)

The environment variables are correct.

**Comment by xavierp** [comment]
Hello !
I think when you define tasks , they have to be attached to a celery app.
Here is a sample code of how i do this. I dont use Django so maybe it will
not be the same for you.

```python
from celery import Celery


app = Celery('my-celery-app')
app.conf.update(
     CONFIG_OPTIONS....
)

@app.task
def execute_command(params):
    # Task code
```

Here the task is bind the the app i defined as @app refers to my app.

Hope this will help you.
Regards

**Comment by ask** [comment]
The ChannelPromise stuff is not really related to the real error and can be ignored, it's just how Python 3 reports exceptions now.

Probably it is like people say here, that the task is not properly connected to the app.

If you use `@shared_task` then make sure that the app is loaded before you load your task (like in the Django example where `proj/__init__.py` imports `proj/celery.py` to make sure the app is defined as soon as the project is imported).

**Comment by ask** [comment]
Actually we should maybe add something in the documentation about this.  I don't have time for it at the moment though.

**Comment by chairco** [comment]
if found the OSError: [Errno 61] Connection refused

also can check the settings below:

`proj/proj/__init__.py`

```python
from __future__ import absolute_import

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app  # noqa
```

**Comment by jpatel3** [comment]
Whats the recommended way to handle the connection error when calling async task.

e.g. `task_name.delay(data)`

If above fails with `ConnectionError` exception.

**Comment by vishal1129** [comment]
Configure celery properly to use a redis(or whatever) backend you are using. This issue occurred because of wrong configuration in app settings.

**Comment by Fakhrillo** [comment]
> if found the OSError: [Errno 61] Connection refused
> 
> also can check the settings below:
> 
> `proj/proj/__init__.py`
> 
> from __future__ import absolute_import
> 
> # This will make sure the app is always imported when
> # Django starts so that shared_task will use this app.
> from .celery import app as celery_app  # noqa

This worked for me on my Django project, as it seems it couldn't properly import the Celery
