### ISSUE TITLE
Workers goes offline after completing random number of tasks

### ISSUE THREAD

**Issue by wavenator** [celery/celery#3179]
``` shell
[2016-04-24 03:30:06,066: ERROR/Process-1] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'fileno'",)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/lib/python3.5/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/lib/python3.5/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/usr/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/lib/python3.5/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/usr/lib/python3.5/site-packages/celery/worker/loops.py", line 41, in asynloop
    obj.controller.register_with_event_loop(hub)
  File "/usr/lib/python3.5/site-packages/celery/worker/__init__.py", line 218, in register_with_event_loop
    description='hub.register',
  File "/usr/lib/python3.5/site-packages/celery/bootsteps.py", line 155, in send_all
    fun(parent, *args)
  File "/usr/lib/python3.5/site-packages/celery/worker/components.py", line 185, in register_with_event_loop
    w.pool.register_with_event_loop(hub)
  File "/usr/lib/python3.5/site-packages/celery/concurrency/prefork.py", line 141, in register_with_event_loop
    return reg(loop)
  File "/usr/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 448, in register_with_event_loop
    [self._track_child_process(w, hub) for w in self._pool]
  File "/usr/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 448, in <listcomp>
    [self._track_child_process(w, hub) for w in self._pool]
  File "/usr/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 431, in _track_child_process
    hub.add_reader(fd, self._event_process_exit, hub, proc)
  File "/usr/lib/python3.5/site-packages/kombu/async/hub.py", line 210, in add_reader
    return self.add(fds, callback, READ | ERR, args)
  File "/usr/lib/python3.5/site-packages/kombu/async/hub.py", line 160, in add
    fd = fileno(fd)
  File "/usr/lib/python3.5/site-packages/kombu/utils/__init__.py", line 445, in fileno
    return f.fileno()
AttributeError: 'NoneType' object has no attribute 'fileno'
```

We're using redis as a backend and broker.
The have hundreds of workers, some of them turned offline and the majority of them were not.
Those who turned offline has logged this error, and there are some that hasn't logged any kind of error.
We're using python 3.5, and the most recent stable versions of celery/kombu....

**Comment by VitoVan** [comment]
I have the same issue on  my server, and it is also running redis as backend and broker.
And before this happen, I have some WorkerLostError in this queue, like this:
`billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM).`

**Comment by ask** [comment]
Be sure to enable the options mentioned in Caveats for redis here:
http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#caveats

These will be enabled by default in Celery 4.0.

**Comment by ask** [comment]
@VitoVan Celery don't kill workers for no reason, so the SIGTERM must be coming from somewhere!

Marking as Unfunded for now, but maybe the efforts to fix Redis problems will also fix this problem.

**Comment by auvipy** [comment]
will reopen if this popup again or someone request for this again.
