### ISSUE TITLE
UnicodeDecodeError with return value contains pandas DataFrame

### ISSUE THREAD

**Issue by shahuwang** [celery/celery#3194]
OS:  Ubuntu 14.04 LTS
Python: 2.7.6
Celery: 3.1.18
Pandas: 0.14.0

Code example:

```
# -*- coding: utf-8 -*-

from celery import Celery
import pandas as pd

app = Celery('tasks', broker="amqp://guest@localhost//")


@app.task
def unicodetest():
    df = pd.DataFrame(
        [[123456]], columns=["序号"])
    return {"table": df}
```

Error message:

[2016-05-05 14:15:27,535: WARNING/MainProcess] Traceback (most recent call last):
[2016-05-05 14:15:27,535: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
[2016-05-05 14:15:27,535: WARNING/MainProcess] msg = self.format(record)
[2016-05-05 14:15:27,535: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
[2016-05-05 14:15:27,536: WARNING/MainProcess] return fmt.format(record)
[2016-05-05 14:15:27,536: WARNING/MainProcess] File "/usr/local/lib/python2.7/dist-packages/celery/utils/log.py", line 144, in format
[2016-05-05 14:15:27,536: WARNING/MainProcess] msg = logging.Formatter.format(self, record)
[2016-05-05 14:15:27,536: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
[2016-05-05 14:15:27,536: WARNING/MainProcess] record.message = record.getMessage()
[2016-05-05 14:15:27,536: WARNING/MainProcess] File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
[2016-05-05 14:15:27,536: WARNING/MainProcess] msg = msg % self.args
[2016-05-05 14:15:27,536: WARNING/MainProcess] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 17: ordinal not in range(128)
[2016-05-05 14:15:27,536: WARNING/MainProcess] Logged from file job.py, line 401

**Comment by luyun-aa** [comment]
Maybe you can try `u"序号"`

**Comment by ask** [comment]
This works in master:

```
[2016-06-28 16:33:02,808: INFO/PoolWorker-3] Task cyanide.tasks.unicodetest[441c436e-5dc9-485e-8193-0e88d94e57ae] succeeded in 0.0204187800045s: {'table': ['序号']}
```

We need to be focusing all our efforts into the 4.0 release at the moment, so no current plans of researching what it takes to backport into 3.1.
