### ISSUE TITLE
Celery4 beat+worker - ImportError: cannot import name 'LRUCache'

### ISSUE THREAD

**Issue by stuaxo** [celery/celery#3200]
Trying to start celery worker on python 3.5.1, in a virtualenv on Ubuntu 64 bit I get this error:

```
 $ celery worker
Traceback (most recent call last):
  File "/home/stu/.virtualenvs/ng/bin/celery", line 9, in <module>
    load_entry_point('celery==4.0.0rc2', 'console_scripts', 'celery')()
  File "/home/stu/.virtualenvs/ng/lib/python3.5/site-packages/celery-4.0.0rc2-py3.5.egg/celery/__main__.py", line 13, in main
    from celery.bin.celery import main
  File "/home/stu/.virtualenvs/ng/lib/python3.5/site-packages/celery-4.0.0rc2-py3.5.egg/celery/bin/__init__.py", line 3, in <module>
    from .base import Option
  File "/home/stu/.virtualenvs/ng/lib/python3.5/site-packages/celery-4.0.0rc2-py3.5.egg/celery/bin/base.py", line 18, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency
  File "/home/stu/.virtualenvs/ng/lib/python3.5/site-packages/celery-4.0.0rc2-py3.5.egg/celery/five.py", line 150, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/stu/.virtualenvs/ng/lib/python3.5/site-packages/celery-4.0.0rc2-py3.5.egg/celery/app/__init__.py", line 14, in <module>
    from celery import _state
  File "/home/stu/.virtualenvs/ng/lib/python3.5/site-packages/celery-4.0.0rc2-py3.5.egg/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/home/stu/.virtualenvs/ng/lib/python3.5/site-packages/celery-4.0.0rc2-py3.5.egg/celery/utils/__init__.py", line 30, in <module>
    from .functional import memoize
  File "/home/stu/.virtualenvs/ng/lib/python3.5/site-packages/celery-4.0.0rc2-py3.5.egg/celery/utils/functional.py", line 17, in <module>
    from kombu.utils.functional import (
ImportError: cannot import name 'LRUCache'
```

Here is the output of pip freeze:
```
amqp==1.4.9
anyjson==0.3.3
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
billiard==3.3.0.23
celery==4.0.0rc2
cffi==1.6.0
-e git+https://github.com/pallets/click.git@6f4d267a51a907a7751d6585541863641518c1a0#egg=click
colored==1.2.1
cookies==2.2.1
coverage==4.0.3
crcmod==1.7
cryptography==1.3.2
datadog==0.11.0
DateTime==4.1.1
decorator==4.0.9
dill==0.2.5
dogapi==1.11.1
ecdsa==0.13
flower==0.9.1
gitdb==0.6.4
GitPython==2.0.2
google-api-python-client==1.5.0
googleads==3.15.0
httplib2==0.9.2
humanize==0.5.1
hypothesis==3.1.3
idna==2.1
impy==1.0.8
ipython==4.2.0
ipython-genutils==0.1.0
kids.cache==0.0.4
kombu==3.0.35
multiprocess==0.70.4
neobunch==2.0.2
networkx==1.11
nose==1.3.7
numpy==1.11.0
oauth2client==2.0.2
paramiko==2.0.0
pexpect==4.0.1
pickleshare==0.7.2
progressbar2==3.6.2
ptyprocess==0.5.1
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pycrypto==2.6.1
PyMySQL==0.7.2
pyOpenSSL==16.0.0
PySocks==1.5.6
python-dateutil==2.5.3
pytimeparse==1.1.5
pytz==2016.4
PyYAML==3.11
redis==2.10.5
requests==2.10.0
requests-aws==0.1.8
requests-futures==0.9.7
responses==0.5.1
restapi-logging-handler==0.2.2
rsa==3.4.2
sh==1.11
simplegeneric==0.8.1
simplejson==3.8.2
six==1.10.0
smmap==0.9.0
sqlparse==0.1.19
suds-jurko==0.6
tabulate==0.7.5
testfixtures==4.9.1
tornado==4.2
traitlets==4.2.1
ujson==1.35
uritemplate==0.6
vine==1.1.0
xmltodict==0.10.1
zope.interface==4.1.3
```

**Comment by stuaxo** [comment]
I needed to install dev versions of kombu + billiard:

```sh
pip install -e git+https://github.com/celery/billiard.git#egg=billiard
pip install -e git+https://github.com/celery/kombu.git#egg=kombu

```

**Comment by Woolworths** [comment]
Thanks for this!

**Comment by heylucky** [comment]
thanks，
`pip install -e git+https://github.com/celery/billiard.git#egg=billiard
pip install -e git+https://github.com/celery/kombu.git#egg=kombu`

that solves my problem,but still know the reasons......

**Comment by stuaxo** [comment]
It could be worth trying version 4.1 of everything, I had a quick peek inside the egg from pypi for kombu and it seems to have the LRUCache.
