### ISSUE TITLE
Issue with celery losing connection to Rabbit and hanging

### ISSUE THREAD

**Issue by jclark360** [celery/celery#3201]
We have ran into an issue several times now where our celery workers will lose connection to rabbit (AWS network issues), and then after a few "consumer: Connection to broker lost. Trying to re-establish the connection" messages the worker hangs.  It's running, and apparently trying to talk on a socket that doesn't exist anymore.  At this point no tasks are being picked up and we have to restart celery to get things going again.  Any ideas? Is this a bug?  Our config looks something like below, we run on Ubuntu 12.04 LTS, using celery 3.1.19

'BROKER_TRANSPORT_OPTIONS': {'confirm_publish': True}, 
'CELERY_ACCEPT_CONTENT': ['json'],
 'CELERY_TASK_SERIALIZER': 'json',
 'CELERY_RESULT_SERIALIZER': 'json'
, 'CELERY_ENABLE_UTC': True,
 'CELERY_DEFAULT_QUEUE': ‘default’ 
'CELERY_ROUTES': router(),
 'SERVER_ENVIRONMENT': 'default',
 'CELERY_ACKS_LATE': True,
 'BROKER_HEARTBEAT': 10,
 'CELERY_EVENT_QUEUE_TTL': 60
, 'CELERYD_MAX_TASKS_PER_CHILD': 30000,
 'CELERY_ALWAYS_EAGER': constants.CELERY_RUN_IN_PROC, 

Exception from worker:

[2016-05-06 23:29:03,372: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 324, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/base.py", line 144, in _read
    raise RecoverableConnectionError('Socket was disconnected')
RecoverableConnectionError: Socket was disconnected

**Comment by ask** [comment]
I'm sorry, but I currently don't have the resources to investigate this.  I'm not sure what the issue is, and it's probably not very difficult to fix. But I have to focus on releasing 4.0, and it could be fixed there.

**Comment by jclark360** [comment]
We figured this one out... rabbit server was pinned at 100% cpu and told the clients to back off thus the disconnect...
