### ISSUE TITLE
Max tasks per child and inspect().active() causes queue NOT_FOUND

### ISSUE THREAD

**Issue by Artimi** [celery/celery#3220]
Hi,

in our use case we want to use `CELERYD_MAX_TASKS_PER_CHILD` to clear memory once in a while and we are calling `inspect().active()` to determine next work. However, after sometime I get following error:

```
[2016-05-24 17:24:46,065: ERROR/MainProcess] Task not_found.task[5c68c5db-4364-427b-b8cc-8def0fbbf993] raised unexpected: NotFound('Basic.consume', 404, "NOT_FOUND - no queue '4107c1c7-bb11-3455-8e29-2c2722284f8f.reply.celery.pidbox' in vhost '/'", (60, 20))
Traceback (most recent call last):
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/psebek/playground/celery_queue_not_found/not_found.py", line 11, in task
    print(inspect(["celery@test_worker"]).active())
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/celery/app/control.py", line 81, in active
    return self._request('dump_active', safe=safe)
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/celery/app/control.py", line 71, in _request
    timeout=self.timeout, reply=True,
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/celery/app/control.py", line 316, in broadcast
    limit, callback, channel=channel,
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/kombu/pidbox.py", line 300, in _broadcast
    channel=chan)
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/kombu/pidbox.py", line 336, in _collect
    with consumer:
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/kombu/messaging.py", line 401, in __enter__
    self.consume()
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/kombu/messaging.py", line 450, in consume
    self._basic_consume(T, no_ack=no_ack, nowait=False)
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/kombu/messaging.py", line 572, in _basic_consume
    no_ack=no_ack, nowait=nowait)
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/kombu/entity.py", line 628, in consume
    nowait=nowait)
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/amqp/channel.py", line 1788, in basic_consume
    (60, 21),  # Channel.basic_consume_ok
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/amqp/abstract_channel.py", line 69, in wait
    return self.dispatch_method(method_sig, args, content)
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/amqp/abstract_channel.py", line 87, in dispatch_method
    return amqp_method(self, args)
  File "/home/psebek/.virtualenvs/fish-parser/lib/python3.4/site-packages/amqp/channel.py", line 243, in _close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.NotFound: Basic.consume: (404) NOT_FOUND - no queue '4107c1c7-bb11-3455-8e29-2c2722284f8f.reply.celery.pidbox' in vhost '/'
```

I have prepared minimal working example:

``` python
from celery.task.control import inspect
import time

app = Celery('not_found', broker='amqp://guest@localhost//')


@app.task
def task():
    print(inspect(["celery@test_worker"]).active())
    time.sleep(0.1)
    task.delay()

if __name__ == "__main__":
    task.delay()
    task.delay()
    task.delay()
    task.delay()
```

After you start it with following command you will get `NotFound` exception mentioned earlier.

```
$ celery -A not_found worker -l INFO --maxtasksperchild 1 -n test_worker
```

We are using following versions:

```
$ celery -A not_found report                                            

software -> celery:3.1.23 (Cipater) kombu:3.0.35 py:3.4.3
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

```

**Comment by ask** [comment]
I'm not getting this error in master, and I really need to be focusing on getting the 4.0 release out the door

**Comment by GuerreiroLeonardo** [comment]
I'm getting the same exact error on version 4.4.2

**Comment by auvipy** [comment]
try 5.2.7 please
