### ISSUE TITLE
[4.0.0.rc2] bind=True, Extra 'None' parameter added when using bind=True

### ISSUE THREAD

**Issue by stuaxo** [celery/celery#3222]
Something strange seems to happening to the parameters when I use bind=True

```python
@task(bind=True)
def run_job(self, job):
    pass

def create_job_workflow(jobs):
    return group(run_job.s(job) for job in jobs)
```

```
[2016-05-25 11:24:14,543: WARNING/PoolWorker-2] /home/stu/.virtualenvs/ng/src/celery/celery/app/trace.py:531: RuntimeWarning: Exception raised outside body: TypeError('run_job() takes 2 positional arguments but 3 were given',):
Traceback (most recent call last):
  File "/home/stu/.virtualenvs/ng/src/celery/celery/app/trace.py", line 406, in trace_task
    (retval,), parent_id=uuid, root_id=root_id,
  File "/home/stu/.virtualenvs/ng/src/celery/celery/canvas.py", line 278, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/stu/.virtualenvs/ng/src/celery/celery/app/task.py", line 488, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: run_job() takes 2 positional arguments but 3 were given

  exc, exc_info.traceback)))
[2016-05-25 11:24:14,545: ERROR/PoolWorker-2] Task juggler_ng.tasks.check_can_run[256b3498-5da4-4032-9886-a4bfd86a4fab] raised unexpected: TypeError('run_job() takes 2 positional arguments but 3 were given',)
Traceback (most recent call last):
  File "/home/stu/.virtualenvs/ng/src/celery/celery/app/trace.py", line 406, in trace_task
    (retval,), parent_id=uuid, root_id=root_id,
  File "/home/stu/.virtualenvs/ng/src/celery/celery/canvas.py", line 278, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/stu/.virtualenvs/ng/src/celery/celery/app/task.py", line 488, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: run_job() takes 2 positional arguments but 3 were given
```

If I use *args and **kwargs to see whats going on, I can see an extra 'None' param added:

```python
@task(bind=True)
def run_job(self, *args, **kwargs):
    print("self: ", self)
    print("args: ", args)
    print("kwargs: ", kwargs)
```

```
[2016-05-25 11:28:24,309: WARNING/MainProcess] celery@stu-OptiPlex-790 ready.
[2016-05-25 11:28:25,164: WARNING/PoolWorker-1] amz.amz_deal_currency_update tasks: []
[2016-05-25 11:28:25,391: WARNING/PoolWorker-3] self:
[2016-05-25 11:28:25,391: WARNING/PoolWorker-3] <@task: juggler_ng.tasks.run_job of default:0x7f7b247ab908 (v2 compatible)>
[2016-05-25 11:28:25,391: WARNING/PoolWorker-3] args:
[2016-05-25 11:28:25,391: WARNING/PoolWorker-3] (None, amz.amz_deal_currency_update)
[2016-05-25 11:28:25,391: WARNING/PoolWorker-3] kwargs:
[2016-05-25 11:28:25,391: WARNING/PoolWorker-3] {}
```

celery config
```
# see http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#configuration
BROKER_URL = 'redis://localhost:6379/6'

CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['pickle', 'json']

CELERY_ENABLE_UTC = False
CELERY_RESULT_BACKEND = 'redis://localhost/7'

CELERY_IMPORTS = ("juggler_ng.tasks", )

# Not enabled by default, but useful
CELERYD_POOL_RESTARTS = True

CELERY_ACKS_LATE = True

CELERY_PREFETCH_MULTIPLIER = 1
```

**Comment by stuaxo** [comment]
OK, looks like I didn't understand chains + chords properly.

**Comment by stefs304** [comment]
Hi @stuaxo , can you please tell me how you fixed this problem? I'm getting the same error but I'm unable to locate the problem.

**Comment by stuaxo** [comment]
Sorry for the lack of detail.  I work short contracts and don't have access to old code if the code isnt open.

I was using chains and chords to run many things in order, might have replaced run_job in my example with a plain (non celery) function.

But it's hard to say 2 years later - if you are using chains of chords like I was I'd look at them further.   Sorry I can't help more.

**Comment by stefs304** [comment]
Thanks for the quick response. 

I looked into chaining, but the usage examples were too abstract for me. I'm just starting to learn about job queuing, and found that rq is more straightforward, so I switched to rq for now. 
I may need celery in the future so thanks for the info nonetheless.
