### ISSUE TITLE
Too many connections (redis) at worker with chords

### ISSUE THREAD

**Issue by ztsv** [celery/celery#3227]
Sometimes i have an issue. It happens only on workers that uses chords.

The contents of the full traceback was: 

Traceback (most recent call last): 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 283, in trace_task 
uuid, retval, SUCCESS, request=task_request, 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/backends/base.py", line 271, in store_result 
request=request, **kwargs) 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/backends/base.py", line 505, in _store_result 
self.set(self.get_key_for_task(task_id), self.encode(meta)) 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/backends/redis.py", line 161, in set 
return self.ensure(self._set, (key, value), **retry_policy) 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/backends/redis.py", line 150, in ensure 
**retry_policy 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time 
return fun(*args, **kwargs) 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/backends/redis.py", line 170, in _set 
pipe.execute() 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/client.py", line 2572, in execute 
self.shard_hint) 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/connection.py", line 874, in get_connection 
connection = self.make_connection() 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/connection.py", line 881, in make_connection 
raise ConnectionError("Too many connections") 
ConnectionError: Too many connections 

I set additional settings bit it doesn't help:

BROKER_TRANSPORT_OPTIONS = {
    'max_connections': 2000,
}
Other workers works fine.

**Comment by ask** [comment]
How many tasks do you have in the chord? Do you use eventlet/gevent or the default prefork pool?  How many processes/threads does the worker have max? (-c|--concurrency argument)

**Comment by ztsv** [comment]
@ask eventlet with concurrency 1000, up to 500000 tasks in chord.

**Comment by ask** [comment]
The only explanation would be if the Redis connection pool simply raises a connection when exceeding the connection count instead of waiting for an available connection.  Not sure how such a pool is useful for anything, maybe there is a setting that we are missing so that it will wait?

**Comment by zachmccormick** [comment]
Redis does exactly what you just described with the `ConnectionPool` default implementation.  I browsed back in the source and found that, if this is happening on the broker end, you'd need to change `_get_pool()` in `kombu/transport/redis.py` to allow for one to pass a custom ConnectionPool class at init to be used when getting/creating the connection pool.  If Kombu is already connection pooling & handling blocking (which I think it may be), then you're fine on the broker end.

On the Result Store end, you added in 0ed47324c4cdf183570541e7cdf3f36f10f31434 the ability to pass in a connection_pool argument to the Redis backend, but it's never used.  If you alternatively allow someone to set a config option for a classname string for the redis connection pool implementation to use, you could probably allow people to use BlockingConnectionPool.  The connparams needs to accept `timeout` as a parameter, thus probably requiring either a fixed conf param for it (or better yet, just make REDIS_BACKEND_CONN_POOL_PARAMS a dictionary, then that future proofs it for people using their own backend impl)

**Comment by zachmccormick** [comment]
It shouldn't be tough to add.  I'll do a PR sometime soon of this.

**Comment by auvipy** [comment]
please send a pr

**Comment by auvipy** [comment]
> It shouldn't be tough to add. I'll do a PR sometime soon of this.

still up for verifying the issue?

**Comment by zachmccormick** [comment]
Yeah I could try to. It's been a while and I totally forget the context of using this, but I could probably help out.

Do you want to verify the issue is still happening or verify a particular fix?

**Comment by auvipy** [comment]
> Yeah I could try to. It's been a while and I totally forget the context of using this, but I could probably help out.
> 
> Do you want to verify the issue is still happening or verify a particular fix?

both actually :D

**Comment by zachmccormick** [comment]
So it looks like in:
```
redis==2.10.3
celery==3.1.23
kombu==3.0.34
```

You can supply the `connection_pool` kwarg in the `RedisBackend` constructor, which will be set to `self._ConnectionPool`, which is used by `def ConnectionPool`, which is used by `def _new_redis_client`. `_new_redis_client` passes `**params` into the constructor for ConnectionPool. `def _create_client` passes `**params` into `_new_redis_client`, and `def client` passes `**self.connparams` into `_create_client`.

If you create `RedisBackend` with a `redis.BlockingConnectionPool`, you seem to be able to forward the `max_connections` kwarg from `RedisBackend` to `BlockingConnectionPool`, but you cannot forward the `timeout` value to the `BlockingConnectionPool` (or any other configuration options for the connection pool class chosen). This would need to be addressed somehow, and seems to be what I meant with the "connparams" part of my comment.

> On the Result Store end, you added in 0ed4732 the ability to pass in a connection_pool argument to the Redis backend, but it's never used

It looks like the only way the backend is instantiated is via `get_backend_by_url`, which yields a backend class (parsed out of the url) and just calls `backend(app=self, url=url)`, meaning you can never provide the constructor kwargs for the backend.

Some of the other backends seem to use logic such as:

```
conf = self.app.conf
...
exchange = exchange or conf.CELERY_RESULT_EXCHANGE
```

But there are a number of options that only seem usable via the constructor in these classes (e.g. AMQPBackend's "connection", "persistent", or "auto_delete" values, CacheBackend's "expires", and RedisBackend's connection_pool).

---

In the latest master (looking at 47af16889fb14e4aeda7b3dec74c521a7b5b1b40), `_get_backend` in `base.py` still has the same behavior of only passing in app/url. Moreover, now that `def backend` will first try to return a threadlocal via `self._local.backend`, you'll end up instantiating a new connection pool for every thread, which may not be desired behavior at all in concurrent deployments.

I'm going to try to create a few concurrency-oriented test cases (i.e. lower local Redis's max connections to 10 and try various celery/redis connection pool configurations to confirm what I can/can't control re: connection pool behavior on a per-process and per-thread level, including eventlet/gevent).

---

On the broker front, I think I was wrong in my initial comment. I think the configuration option `broker_pool_limit` should be limiting things via the `pool` in `base.py`, which is a kombu ConnectionPool where `broker_pool_limit` is used in the construction as the limit, and `_acquire_connection` uses `acquire(block=True)` to do a forever-block on the pool.

I think, therefore, the behavior seen in the original issue is driven by the backend, not the broker.

**Comment by auvipy** [comment]
thanks for investigating

**Comment by wbobeirne** [comment]
Just wanted to chime in here and say that I'd love to see support for `BlockingConnectionPool`. Found this issue by searching for if this was supported. Seems like a perfect use case for Celery since in many cases, a task getting done eventually is more important than it getting done fast / failing if it doesn't.

**Comment by thedrow** [comment]
@wbobeirne We'd very much appreciate it if you can contribute a fix.
