### ISSUE TITLE
Python 3.5 strange exception from std library only when starting as celery task

### ISSUE THREAD

**Issue by kajzur** [celery/celery#3230]
Hi, 
we have strange problem with Celery. On Python 3.5 we have a strange exception (probably from std library or because of monkey patching).

```
Traceback (most recent call last):
  File "/opt/virtualenvs/aaa/lib/python3.5/site-packages/tasks/sip.py", line 672, in run
    return self.mix(recording_params)
  File "/opt/virtualenvs/aaa/lib/python3.5/site-packages/tasks/sip.py", line 707, in mix
    recording_params['rec_filename'] + ".wav")
  File "/opt/virtualenvs/aaa/lib/python3.5/site-packages/tasks/audio.py", line 108, in mix_recordings
    execute_system_command(('sox', '-m', in1_file, in2_file, out_file))
  File "/opt/virtualenvs/aaa/lib/python3.5/site-packages/tasks/audio.py", line 76, in execute_system_command
    p = Popen(command_parts, stdout=PIPE, stderr=PIPE)
  File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1473, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
AttributeError: 'NoneType' object has no attribute 'fork_exec'
```

Can someone help us with this issue?

**Comment by ask** [comment]
I don't think anything in Celery is patching this.  We don't monkey-patch anything afaik.

This seems to imply that `_posixsubprocess` is None in this module, so I guess it could be related to daemonic threads at shutdown where to gc interpreter has collected the symbols before the thread wakes up again.  Is it happening during shutdown?

**Comment by miohtama** [comment]
Smells like gevent monkey patches messing up things.

**Comment by kajzur** [comment]
This issue was related with gevent. Subprocess module was patched indeed, but not by us explicitly. Grequests module did, so eventually we made a workaround by reloading subprocess module after importing grequests. Certainly this is not a Celery bug at all. Thank you @miohtama

**Comment by auvipy** [comment]
closing this as not a celery bug
