### ISSUE TITLE
RuntimeError: Second simultaneous read on fileno 23 detected

### ISSUE THREAD

**Issue by ztsv** [celery/celery#3237]
Sometimes i get this error:

The contents of the full traceback was: 

```
Traceback (most recent call last): 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task 
R = retval = fun(*args, **kwargs) 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__ 
return self.run(*args, **kwargs) 
File "imapp/tasks.py", line 163, in save_users_with_meta 
update_user_info.apply_async((user['id'], ), ) 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/app/task.py", line 565, in apply_async 
**dict(self._get_exec_options(), **options) 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task 
reply_to=reply_to or self.oid, **options 
File "/home/sm/env/local/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task 
**kwargs 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish 
routing_key, mandatory, immediate, exchange, declare) 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/connection.py", line 436, in _ensured 
return fun(*args, **kwargs) 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/messaging.py", line 184, in _publish 
[maybe_declare(entity) for entity in declare] 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/messaging.py", line 111, in maybe_declare 
return maybe_declare(entity, self.channel, retry, **retry_policy) 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/common.py", line 113, in maybe_declare 
return _maybe_declare(entity, declared, ident, channel) 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/common.py", line 120, in _maybe_declare 
entity.declare() 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/entity.py", line 522, in declare 
self.queue_declare(nowait, passive=False) 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/entity.py", line 548, in queue_declare 
nowait=nowait) 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 447, in queue_declare 
return queue_declare_ok_t(queue, self._size(queue), 0) 
File "/home/sm/env/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 690, in _size 
sizes = pipe.execute() 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/client.py", line 2578, in execute 
return execute(conn, stack, raise_on_error) 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/client.py", line 2447, in _execute_transaction 
connection.send_packed_command(all_cmds) 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/connection.py", line 532, in send_packed_command 
self.connect() 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/connection.py", line 440, in connect 
self.on_connect() 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/connection.py", line 508, in on_connect 
if nativestr(self.read_response()) != 'OK': 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/connection.py", line 569, in read_response 
response = self._parser.read_response() 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/connection.py", line 224, in read_response 
response = self._buffer.readline() 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/connection.py", line 162, in readline 
self._read_from_socket() 
File "/home/sm/env/local/lib/python2.7/site-packages/redis/connection.py", line 120, in _read_from_socket 
data = self._sock.recv(socket_read_size) 
File "/home/sm/env/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 326, in recv 
timeout_exc=socket.timeout("timed out")) 
File "/home/sm/env/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 201, in _trampoline 
mark_as_closed=self._mark_as_closed) 
File "/home/sm/env/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 158, in trampoline 
listener = hub.add(hub.READ, fileno, current.switch, current.throw, mark_as_closed) 
File "/home/sm/env/local/lib/python2.7/site-packages/eventlet/hubs/epolls.py", line 49, in add 
listener = BaseHub.add(self, evtype, fileno, cb, tb, mac) 
File "/home/sm/env/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 177, in add 
evtype, fileno, evtype, cb, bucket[fileno])) 
RuntimeError: Second simultaneous read on fileno 23 detected. Unless you really know what you're doing, make sure that only one greenthread can read any particular socket. Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of greenlet.greenlet object at 0x7f59b15ac870>; THAT THREAD=FdListener('read', 23, <function on_read at 0x7f59ae3e89b0>, <function on_error at 0x7f59ae32c140>)
```

Limits:

```
cat /proc/3491/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             25600000             25600000             bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             3950                 3950                 processes
Max open files            100000               100000               files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       3950                 3950                 signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

FD Usage:

```
ls -l /proc/3491/fd
total 0
lrwx------ 1 sm sm 64 Jun  5 12:34 0 -> /dev/null
lrwx------ 1 sm sm 64 Jun  5 12:34 1 -> /dev/null
l-wx------ 1 sm sm 64 Jun  5 12:34 10 -> /var/log/celery/celery.log
l-wx------ 1 sm sm 64 Jun  5 12:34 11 -> /var/log/celery/celery.log
lrwx------ 1 sm sm 64 Jun  5 12:34 12 -> socket:[93605326]
lrwx------ 1 sm sm 64 Jun  5 12:34 13 -> anon_inode:[eventpoll]
lrwx------ 1 sm sm 64 Jun  5 12:34 14 -> socket:[93605327]
lrwx------ 1 sm sm 64 Jun  5 12:34 15 -> socket:[93605328]
lrwx------ 1 sm sm 64 Jun  5 12:34 16 -> socket:[93605329]
lrwx------ 1 sm sm 64 Jun  5 12:34 17 -> socket:[93605474]
lrwx------ 1 sm sm 64 Jun  5 12:34 18 -> socket:[93605475]
lrwx------ 1 sm sm 64 Jun  5 12:34 19 -> socket:[93605476]
lrwx------ 1 sm sm 64 Jun  5 12:34 2 -> /dev/null
lrwx------ 1 sm sm 64 Jun  5 12:34 20 -> socket:[93605478]
lrwx------ 1 sm sm 64 Jun  5 12:34 21 -> socket:[93605479]
lrwx------ 1 sm sm 64 Jun  5 12:34 22 -> socket:[93605482]
lrwx------ 1 sm sm 64 Jun  5 12:34 23 -> socket:[93605483]
lrwx------ 1 sm sm 64 Jun  5 12:34 25 -> socket:[93614751]
lrwx------ 1 sm sm 64 Jun  5 12:34 26 -> socket:[93614580]
lrwx------ 1 sm sm 64 Jun  5 12:34 28 -> socket:[93614488]
lrwx------ 1 sm sm 64 Jun  5 12:34 3 -> /dev/null
lrwx------ 1 sm sm 64 Jun  5 12:34 30 -> socket:[93625627]
lrwx------ 1 sm sm 64 Jun  5 12:34 38 -> socket:[93610841]
lrwx------ 1 sm sm 64 Jun  5 12:34 4 -> /dev/null
lrwx------ 1 sm sm 64 Jun  5 12:34 5 -> /dev/null
l-wx------ 1 sm sm 64 Jun  5 12:34 6 -> /home/sm/log/accounts.log
l-wx------ 1 sm sm 64 Jun  5 12:34 7 -> /home/sm/log/sm.log
```

Packages:

```
celery==3.1.23
greenlet==0.4.9
kombu==3.0.35
redis==2.10.3
```

**Comment by ask** [comment]
Have you tried using the development version?

(remember to also install `requirements/dev.txt `in the celery git master branch)

**Comment by ztsv** [comment]
Nope, this is production env

**Comment by ask** [comment]
You don't have a development or staging environment?

**Comment by ztsv** [comment]
I can't reproduce count of tasks on staging. Do you have any ideas what is cause of problem?

**Comment by gugu** [comment]
@ask I tried master, does not help

**Comment by thedrow** [comment]
We need something to work with here.
Got a test case we can use to reproduce the problem?

**Comment by auvipy** [comment]
closing due to lack of feedback.
