### ISSUE TITLE
Debug steps for chord not running?

### ISSUE THREAD

**Issue by dparkeruk** [celery/celery#3242]
Hi All,

I am struggling to debug an issue I have all of a sudden been hitting and would value some advice.

I am using celery 3.1.18 with Django, with RabbitMQ as the broker and an Oracle database as the backend, ie.:

CELERY_RESULT_BACKEND='djcelery.backends.database.DatabaseBackend'

My code makes use of chords and has been working successfully for a year or so now.

All of a sudden chords are not firing the callback across both my Dev and Prod envs and I am at a loss as to how to debug further.  The code has not changed and last night, without changing the code *something I did made chords come back to life temporarily only to stop working again this morning .. suggesting this is some sort of resource issue rather than a code problem.

So far, I have:
1. restarted the host that rabbitmq-server and celery are running on.
2. purged all queues and repeated step 1.
3. Disabled the backend (commented it out from settings.py, got the error about disabled backend, then enabled the backend once again.
4. Tried to run the basic commands that show chords working in the docs.  The example hangs on the shell and when you CTRL-C out you get:

>>> from celery import chord
>>> from tasks import add, tsum
>>> callback = tsum.s()
>>> header = [add.s(i, i) for i in range(100)]
>>> result = chord(header)(callback)
>>> result.get()
<hang .. hang ... hang>
^CTraceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/celery/result.py", line 169, in get
    no_ack=no_ack,
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/celery/backends/base.py", line 220, in wait_for
    on_interval()
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/celery/result.py", line 181, in _maybe_reraise_parent_error
    node.maybe_reraise()
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/celery/result.py", line 485, in maybe_reraise
    result.maybe_reraise()
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/celery/result.py", line 270, in maybe_reraise
    if self.state in states.PROPAGATE_STATES:
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/celery/result.py", line 394, in state
    return self._get_task_meta()['status']
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/celery/result.py", line 339, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/celery/backends/base.py", line 292, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/djcelery/backends/database.py", line 40, in _get_task_meta_for
    return self.TaskModel._default_manager.get_task(task_id).to_dict()
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/djcelery/managers.py", line 144, in get_task
    return self.get(task_id=task_id)
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/django/db/models/query.py", line 211, in iterator
    if connections[self.db].features.supports_select_related:
  File "/opt/exaboard/eXaboard/lib/python2.7/site-packages/django/db/models/query.py", line 900, in db
    @property
KeyboardInterrupt

Any advice on how to DEBUG further would be much appreciated!

**Comment by dparkeruk** [comment]
Apologies .. This can not (yet) be classed as a Bug .. This is not the correct forum for such a question.

Issue Closed.
