### ISSUE TITLE
Connection to broker getting lost every ~90 seconds when idle

### ISSUE THREAD

**Issue by arjun27** [celery/celery#3248]
Hi, we've been running into connection issues with the prefork worker with RabbitMQ as broker. Every 90 seconds or so when the worker is ideal it throws up the following stack trace and reconnects the broker.

This is on Heroku, with the CloudAMQP add-on. There is a gevent worker in the same environment which does not have any connection issues.

Any help on this will be most welcome. Thanks!

```
Jun 12 06:16:56 app/celeryd_prod_prefork.1:  [2016-06-12 06:16:55,858: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection... 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:  Traceback (most recent call last): 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/celery/worker/consumer.py", line 279, in start 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      blueprint.start(self) 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      step.start(parent) 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/celery/worker/consumer.py", line 838, in start 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      c.loop(*c.loop_args()) 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/celery/worker/loops.py", line 76, in asynloop 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      next(loop) 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/kombu/async/hub.py", line 340, in create_loop 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      cb(*cbargs) 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/base.py", line 164, in on_readable 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      reader(loop) 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/base.py", line 146, in _read 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      drain_events(timeout=0) 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 303, in drain_events 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      chanmap, None, timeout=timeout, 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 366, in _wait_multiple 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      channel, method_sig, args, content = read_timeout(timeout) 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/amqp/connection.py", line 337, in read_timeout 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      return self.method_reader.read_method() 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:    File "/app/.heroku/python/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:      raise m 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:  IOError: Socket closed 
Jun 12 06:16:56 app/celeryd_prod_prefork.1:  [2016-06-12 06:16:55,879: INFO/MainProcess] Connected to amqp://vpetacbn:**@jaguar.rmq.cloudamqp.com:5672/vpetacbn 
```

The worker command from the procfile is given below.

```
celeryd_prod_prefork: bin/start-pgbouncer-stunnel celery worker --app=hypertrackapi --pool=prefork --concurrency=$CELERY_PREFORK_WORKER_CONCURRENCY --workdir=hypertrackapi --loglevel=INFO --queues=gpsfilters,celery --without-gossip --without-mingle --without-heartbeat
```

The relevant package versions are given below.

```
celery==3.1.23
Django==1.9.6
django-celery==3.1.17
kombu==3.0.35
amqp==1.4.9
```

**Comment by ask** [comment]
Sounds like this is an issue with CloudAMQP, as there's no reason for the worker to close the connection.  That is, unless the broker has negotiated a heartbeat interval but are not sending them in time.

**Comment by asyazwan** [comment]
@arjun27 Did you figure this out? I'm having the same problem, getting `Connection to broker lost` on idle exactly every 90 seconds.

**Comment by markine** [comment]
Have you tried setting BROKER_HEARTBEAT = None per https://www.cloudamqp.com/docs/celery.html?

**Comment by mineta** [comment]
That worked for me @markine 
thanks! :-)
