### ISSUE TITLE
celery events crashing

### ISSUE THREAD

**Issue by MacDschie** [celery/celery#3264]
Hi there,

I try to get a grasp of what's happening with my celery tasks, so I enabled the events. The command `celery events` is showing some information, but only tasks are displayed which are started after I start the `celery events` command. I don't see already running tasks. Is it supposed to work this way?

Also, when I try to get the results for a running task by pressing `r`, the tool crashes with the following stack trace:

```
Exception in thread Thread-1:  
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/local/lib/python2.7/dist-packages/celery/events/cursesmon.py", line 499, in run
self.display.draw()
File "/usr/local/lib/python2.7/dist-packages/celery/events/cursesmon.py", line 354, in draw
self.handle_keypress()
File "/usr/local/lib/python2.7/dist-packages/celery/events/cursesmon.py", line 162, in handle_keypress
handler()
File "/usr/local/lib/python2.7/dist-packages/celery/events/cursesmon.py", line 328, in selection_result
'Task Result for {0.selected_task}'.format(self),
File "/usr/local/lib/python2.7/dist-packages/celery/events/cursesmon.py", line 172, in alert
callback(my, mx, next(y))
File "/usr/local/lib/python2.7/dist-packages/celery/events/cursesmon.py", line 323, in alert_callback
for line in wrap(result, mx - 2):
File "/usr/lib/python2.7/textwrap.py", line 354, in wrap
return w.wrap(text)
File "/usr/lib/python2.7/textwrap.py", line 325, in wrap
text = self._munge_whitespace(text)
File "/usr/lib/python2.7/textwrap.py", line 154, in _munge_whitespace
text = text.expandtabs()
AttributeError: 'NoneType' object has no attribute 'expandtabs'
```

I use celery v3.1.23 on Ubuntu 14.10 LTS.

**Comment by ask** [comment]
Seems this was fixed in the 3.1 branch:
a9db3acd9020cf944b5e53ea45cffdf0389c9485

I don't currently have an eta on the next 3.1 release, I'm focusing my efforts on the 4.0 release at the moment
