### ISSUE TITLE
[4.0.0.rc2] json cannot encode bytes

### ISSUE THREAD

**Issue by honux** [celery/celery#3272]
Heya,
Sometimes, don't know if it is caused due to my configuration, the following exception happen:

```python
[2016-06-23 10:55:01,582: ERROR/MainProcess] Control command error: EncodeError(TypeError('b\'[["br",503625,false],{},{"errbacks":null,"callbacks":null,"chord":null,"chain":[{"chord_size":null,"task":"Store.summoner_summary","immutable":false,"args":["br"],"subtask_type":null,"kwargs":{},"options":{"parent_id":"f921231f-dd9d-431c-ae40-7b6682d34d5f","reply_to":"6fd546e0-f6e2-327d-907e-f70be46b1834","group_id":"ab142b4f-1093-4b53-846d-b80153ce948c","task_id":"aef2e57f-4767-4dc7-b12b-002936cf5adc","root_id":"f921231f-dd9d-431c-ae40-7b6682d34d5f"}}]}]\' is not JSON serializable',),)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/kombu/utils/json.py", line 28, in default
    reducer = obj.__json__
AttributeError: 'bytes' object has no attribute '__json__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/kombu/serialization.py", line 56, in _reraise_errors
    yield
  File "/usr/local/lib/python3.4/dist-packages/kombu/serialization.py", line 165, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.4/dist-packages/kombu/utils/json.py", line 36, in dumps
    return _dumps(s, cls=cls)
  File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.4/dist-packages/kombu/utils/json.py", line 30, in default
    return _super(self, obj)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'[["br",503625,false],{},{"errbacks":null,"callbacks":null,"chord":null,"chain":[{"chord_size":null,"task":"Store.summoner_summary","immutable":false,"args":["br"],"subtask_type":null,"kwargs":{},"options":{"parent_id":"f921231f-dd9d-431c-ae40-7b6682d34d5f","reply_to":"6fd546e0-f6e2-327d-907e-f70be46b1834","group_id":"ab142b4f-1093-4b53-846d-b80153ce948c","task_id":"aef2e57f-4767-4dc7-b12b-002936cf5adc","root_id":"f921231f-dd9d-431c-ae40-7b6682d34d5f"}}]}]' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/celery/worker/pidbox.py", line 43, in on_message
    self.node.handle_message(body, message)
  File "/usr/local/lib/python3.4/dist-packages/kombu/pidbox.py", line 135, in handle_message
    return self.dispatch(**body)
  File "/usr/local/lib/python3.4/dist-packages/kombu/pidbox.py", line 118, in dispatch
    ticket=ticket)
  File "/usr/local/lib/python3.4/dist-packages/kombu/pidbox.py", line 141, in reply
    serializer=self.mailbox.serializer)
  File "/usr/local/lib/python3.4/dist-packages/kombu/pidbox.py", line 260, in _publish_reply
    **opts
  File "/usr/local/lib/python3.4/dist-packages/kombu/messaging.py", line 174, in publish
    compression, headers)
  File "/usr/local/lib/python3.4/dist-packages/kombu/messaging.py", line 256, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python3.4/dist-packages/kombu/serialization.py", line 165, in dumps
    payload = encoder(data)
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/kombu/serialization.py", line 60, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/vine/five.py", line 172, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/kombu/serialization.py", line 56, in _reraise_errors
    yield
  File "/usr/local/lib/python3.4/dist-packages/kombu/serialization.py", line 165, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.4/dist-packages/kombu/utils/json.py", line 36, in dumps
    return _dumps(s, cls=cls)
  File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.4/dist-packages/kombu/utils/json.py", line 30, in default
    return _super(self, obj)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
kombu.exceptions.EncodeError: b'[["br",503625,false],{},{"errbacks":null,"callbacks":null,"chord":null,"chain":[{"chord_size":null,"task":"Store.summoner_summary","immutable":false,"args":["br"],"subtask_type":null,"kwargs":{},"options":{"parent_id":"f921231f-dd9d-431c-ae40-7b6682d34d5f","reply_to":"6fd546e0-f6e2-327d-907e-f70be46b1834","group_id":"ab142b4f-1093-4b53-846d-b80153ce948c","task_id":"aef2e57f-4767-4dc7-b12b-002936cf5adc","root_id":"f921231f-dd9d-431c-ae40-7b6682d34d5f"}}]}]' is not JSON serializable
```

using the following configuration:
```python
from __future__ import absolute_import, unicode_literals

from celery import Celery
from kombu.serialization import register
from ujson import dumps, loads


register('ujson', dumps, loads, content_type='application/json', content_encoding='utf-8')

celery = Celery('RiotAPI', broker='redis://127.0.0.1/1', backend='redis://127.0.0.1/2', include=['riot_api.tasks'])

celery.conf.update(
  task_protocol = 2,
  task_serializer = 'ujson',
  accept_content = ['application/json'],
  result_expires = 120,
  result_serializer = 'ujson',
  result_compression = 'gzip',
  task_routes = {
    'RiotAPI.*': 'riot_api',
    'Updater.*': 'updater',
    'Store.*': 'store',
    'Professional.*': 'professional',
  },
)

if __name__ == '__main__':
  celery.start()
```

running under the latest version, with Python3 and Ubuntu16.
Processing on average ~3k tasks / second, it happens randomly once every ~7k tasks.

Also, shouldn't kombu also use the ujson serializer? :p

**Comment by ask** [comment]
Bytes isn't actually supported by json, as all strings are forced to be unicode.

You can base64 encode the bytestring, but then you have manually decode it when receiving it in the task.

We don't use any of the json libraries marketed as fast, as they usually have one or more serious defects.  E.g. truncating floats or similar breaking our timestamps.  I don't know the status of usjon specifically at this point though.

**Comment by honux** [comment]
The following piece of code caused the error:

```
@app.task(bind=True, name='Updater.match_filter_participants')
def updater_match_filter_participants(self, match_data, region, partial_data):
    (...)
    tasks = []
    tasks.append(dict(signature('Updater.summoner_leagues', args=(region, chunk, False))))
    return tasks
```

Probably not caused to celery, my fault.
