### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CouchDBBackend'

### ISSUE THREAD

**Issue by astewart-twist** [celery/celery#3287]
Installed development version of celery with following:
```
pip install -e git+https://github.com/celery/billiard.git#egg=billiard
pip install -e git+https://github.com/celery/py-amqp.git#egg=amqp
pip install -e git+https://github.com/celery/kombu.git#egg=kombu
pip install -e git+https://github.com/celery/vine.git#egg=vine
pip install -e git+https://github.com/celery/celery.git#egg=celery
pip install pycouchdb
```

Running celery worker containing following config: 
`app = Celery('tasks', broker='amqp://guest@rmq//', backend='couchdb://localhost:5984/db')`

Keep getting the following error:
```
[2016-07-04 07:04:45,148: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'module' object has no attribute 'CouchDBBackend'",)                                                                                                                             
Traceback (most recent call last):                                                                                                 
  File "/opt/src/celery/celery/worker/__init__.py", line 201, in start                                                             
    self.blueprint.start(self)                                                                                                     
  File "/opt/src/celery/celery/bootsteps.py", line 121, in start                                                                   
    self.on_start()                                                                                                                
  File "/opt/src/celery/celery/apps/worker.py", line 146, in on_start                                                              
    string(self.colored.cyan(' \n', self.startup_info())),                                                                         
  File "/opt/src/celery/celery/apps/worker.py", line 206, in startup_info                                                          
    results=self.app.backend.as_uri(),                                                                                             
  File "/opt/src/kombu/kombu/utils/__init__.py", line 302, in __get__                                                              
    value = obj.__dict__[self.__name__] = self.__get(obj)                                                                          
  File "/opt/src/celery/celery/app/base.py", line 1092, in backend                                                                 
    return self._get_backend()                                                                                                     
  File "/opt/src/celery/celery/app/base.py", line 831, in _get_backend                                                             
    self.loader)                                                                                                                   
  File "/opt/src/celery/celery/backends/__init__.py", line 73, in get_backend_by_url                                               
    return get_backend_cls(backend, loader), url                                                                                   
  File "/opt/src/celery/celery/backends/__init__.py", line 54, in get_backend_cls                                                  
    cls = symbol_by_name(backend, aliases)                                                                                         
  File "/opt/src/kombu/kombu/utils/__init__.py", line 101, in symbol_by_name                                                       
    return getattr(module, cls_name) if cls_name else module                                                                       
AttributeError: 'module' object has no attribute 'CouchDBBackend'
```

Any ideas?

**Comment by malinoff** [comment]
It's `CouchBackend`, not `CouchDBBackend`, https://github.com/celery/celery/blob/master/celery/backends/couchdb.py#L29

**Comment by astewart-twist** [comment]
Thanks @malinoff.  Looks like the actual problem is at https://github.com/celery/celery/blob/master/celery/backends/__init__.py#L37

I changed s/CouchDBBcackend/CouchBackend/ on that line and it worked fine.  Should I send a PR?  (Can we keep this open until then?)

**Comment by malinoff** [comment]
Yes, please :)

**Comment by astewart-twist** [comment]
Also, this may be another topic, but I notice that the couchdb backend is storing a stringified json blob of the result value in the resulting couchdb document rather than the json blob itself.  In other words it looks like a case of double-deserialization.  I'm not sure if this is supposed to be the intended behavior for the celery backends, but if not then it's a pretty simple fix to the couchdb backend.  Example: https://github.com/Twistbioscience/celery/blob/master/celery/backends/couchdb.py#L95

I can do another PR but I want to first check whether the couchdb backend is already implemented as intended.

**Comment by malinoff** [comment]
Yes, create another PR. This issue seems fixed.
