### ISSUE TITLE
django example cannot run

### ISSUE THREAD

**Issue by gqdw** [celery/celery#3291]
```
gqdw@acas-MacBook-Air ~/github/celery/examples/django [master]
± % python manage.py runserver                                                                               !10105
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/gqdw/github/celery/examples/django/proj/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/Users/gqdw/github/celery/examples/django/proj/celery.py", line 16, in <module>
    app.config_from_object('django.conf:settings', namespace='CELERY')
TypeError: config_from_object() got an unexpected keyword argument 'namespace'
```

my django version is 1.8.6

**Comment by ask** [comment]
This means you're reading the development documentation but using the stable version!

The stable documentation is here: https://docs.celeryproject.org/en/latest/

If you want to try the development version you need to install celery and kombu from git.
