### ISSUE TITLE
Linked and canvas task raises EncodeError, with datetime expires option format

### ISSUE THREAD

**Issue by penoux** [celery/celery#3301]
When setting a `datetime` format for `expires` option of a task (starting from the 2nd one of a chain for example, on the 1st one, it works), Celery raises an `EncodeError` exception.

In debug mode I saw it analyses and serializes (`isoformat`) the `expires` option type only for the 1st task of the chain, then tries to serialize in `publish_task` the `datetime` for subsequent tasks.
A possible fix would be to recursively analyze and serialize (`isoformat`) all `datetime` options of subsequent tasks, and to accept datetimestrings (iso8601) type in input of `expires` option.

Sample code :

```
expires = datetime.utcnow() - timedelta(seconds=2)`
ch = chain(add.subtask((1,2)), add.subtask((3, ), expires=expires))
```

Exception:

```
Traceback (most recent call last):
  File "C:\Users\PIHE7364\git\venusMQ\venusMQ\venusMQ\tests\tests_tasks.py", line 685, in test_run_celery_task
    res = ch.apply_async()
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\celery\canvas.py", line 251, in apply_async
    return _apply(args, kwargs, **options)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\celery\app\builtins.py", line 293, in apply_async
    tasks[0].apply_async(**options)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\celery\canvas.py", line 251, in apply_async
    return _apply(args, kwargs, **options)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\celery\app\task.py", line 565, in apply_async
    **dict(self._get_exec_options(), **options)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\celery\app\base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\celery\app\amqp.py", line 310, in publish_task
    **kwargs
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\kombu\messaging.py", line 165, in publish
    compression, headers)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\kombu\messaging.py", line 241, in _prepare
    body) = dumps(body, serializer=serializer)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\kombu\serialization.py", line 164, in dumps
    payload = encoder(data)
  File "C:\Python35\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\kombu\serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\kombu\five.py", line 131, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\kombu\serialization.py", line 55, in _reraise_errors
    yield
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\kombu\serialization.py", line 164, in dumps
    payload = encoder(data)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\anyjson\__init__.py", line 141, in dumps
    return implementation.dumps(value)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\anyjson\__init__.py", line 89, in dumps
    raise TypeError(TypeError(*exc.args)).with_traceback(sys.exc_info()[2])
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\anyjson\__init__.py", line 87, in dumps
    return self._encode(data)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\simplejson\__init__.py", line 380, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\simplejson\encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\simplejson\encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\PIHE7364\virtualenvs\py35\venusMQ\lib\site-packages\simplejson\encoder.py", line 252, in default
    raise TypeError(repr(o) + " is not JSON serializable")
kombu.exceptions.EncodeError: datetime.datetime(2016, 7, 8, 19, 2, 40, 90903) is not JSON serializable
```

**Comment by ask** [comment]
Interesting.  Handling all of the cases where sig.options['expires'] can be set will be tricky, and we don't want to traverse the signatures to find them as that would be slow.   I guess we could do it at the json serializer level and simply convert all datetimes to isoformat.

**Comment by penoux** [comment]
Sure, that would be simpler. Just probably an impact when deserializing the option for tasks after the 1st one (manage datetimestring)...

**Comment by penoux** [comment]
Thanks for the quick fix!
I suppose it will be for 4.0.0 only? 
I have a workaround using seconds instead of date time btw :)

**Comment by ask** [comment]
Yeah, focusing all efforts on 4 right now.  There will be an rc tag today hopefully :tada:

You can definitely use seconds right now, but that means the expiry will be n seconds after a worker finally calls the task (not from you called the first task in the workflow).
