### ISSUE TITLE
Project crash when celery==4.0.0rc3

### ISSUE THREAD

**Issue by soulraven** [celery/celery#3303]
Hello,
When i have update the celery package the all project has crashed with this error: 
`Traceback (most recent call last):
  File "/root/.pycharm_helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/pyProjectsEnv/proGeekAPI/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django`

**Comment by ask** [comment]
Ah, it seems like the example Django project had `kombu.transport.django` in `INSTALLED_APPS` for some reason, even though it's configured to use RabbitMQ by default.

Since using Django ORM as a broker is no longer supported, you need to remove this line from there.
just like I did in the patch: 252f789

**Comment by soulraven** [comment]
It seems that ar still some dependencies problems, if i remove kombu i get error that is not loaded module, if i install kombu i get
`Traceback (most recent call last):
  File "/root/.pycharm_helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/pyProjectsEnv/proGeekAPI/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/djcelery/models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
ImportError: cannot import name timedelta_seconds`

**Comment by malinoff** [comment]
@soulraven did you remove `kombu` package or just that line from INSTALLED_APPS?

**Comment by soulraven** [comment]
Only from the INSTALLED_APPS

**Comment by soulraven** [comment]
`Failed to get real commands on module "proGeekAPI": python process died with code 1: 
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pycharm/_jb_manage_tasks_provider.py", line 25, in <module>
    django.setup()
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/djcelery/models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
ImportError: cannot import name timedelta_seconds`

**Comment by soulraven** [comment]
Now after last update, i get this error:
`  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/djcelery/models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
  File "/usr/local/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named timeutils
`

**Comment by ask** [comment]
Django-celery does not support 4.0 yet, I've replaced the functionality there with new extensions: django-celery-results and django-celery-beat.   These are not compatible with the old Django-celery models, so need to migrate over somehow (I guess results can usually just be deleted when moving).

For the periodic task we could make an import utility maybe.
