### ISSUE TITLE
Crontab task raises EncodeError when stats() method is called from Flower

### ISSUE THREAD

**Issue by sarfaoui** [celery/celery#3320]
Somewhat similar to https://github.com/celery/celery/issues/3301.

I have an app that schedules crontab tasks, and I use Flower to keep an eye on things.
The tasks seem to be scheduled properly, but they are never ran.

When using flower, I get the following when trying to access worker info:

```
[W 160718 13:40:55 web:1493] 404 GET /worker/celery@dev-1 (127.0.0.1): Unable to get stats for 'celery@dev-1' worker
```

and in the beat log output:

```
[2016-07-18 13:40:54,115: DEBUG/MainProcess] pidbox received method stats() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '8f657d1d-8395-39bb-97dd-0d6fd076c668'} ticket:4226b691-c6c3-430e-8320-0edd1c6d318d]
[2016-07-18 13:40:54,117: ERROR/MainProcess] Control command error: EncodeError(TypeError("<class 'itertools.cycle'> is not JSON serializable",),)
Traceback (most recent call last):
  File "/home/samir.arfaoui/virtualenvs/juggler-ng-venv/src/kombu/kombu/serialization.py", line 56, in _reraise_errors
    yield
  File "/home/samir.arfaoui/virtualenvs/juggler-ng-venv/src/kombu/kombu/serialization.py", line 165, in dumps
    payload = encoder(data)
  File "/home/samir.arfaoui/virtualenvs/juggler-ng-venv/src/kombu/kombu/utils/json.py", line 64, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
  File "/home/samir.arfaoui/virtualenvs/juggler-ng-venv/lib/python3.5/site-packages/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
  File "/home/samir.arfaoui/virtualenvs/juggler-ng-venv/lib/python3.5/site-packages/simplejson/encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/samir.arfaoui/virtualenvs/juggler-ng-venv/lib/python3.5/site-packages/simplejson/encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
  File "/home/samir.arfaoui/virtualenvs/juggler-ng-venv/src/kombu/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/home/samir.arfaoui/virtualenvs/juggler-ng-venv/lib/python3.5/site-packages/simplejson/encoder.py", line 252, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <class 'itertools.cycle'> is not JSON serializable
```

it looks like a recent change to json.py is not handling crontab-type tasks properly.

I am using python 3.5.0, celery master, and kombu master.

**Comment by ask** [comment]
Thanks! Fix by above commit, at least unless someone defines a custom failover cycle, which is pretty rare I guess.

**Comment by sarfaoui** [comment]
Thank you very much!

**Comment by rmoorman** [comment]
@ask is there a chance that this will be backported/merged into 3.x? Thank you very much in advance.

**Comment by VerdigrisReader** [comment]
@rmoorman 
Until that happens try: pip install kombu==3.0.35

Looks like the change to celery's dependencies caused the stable release to behave un-stable-ly:
https://github.com/celery/celery/commit/eb81426d3f83c3141a9c57d1c62a12cc64e29de4

**Comment by rmoorman** [comment]
Thank you @VerdigrisReader! That does indeed help to fix this temporarily :-)

**Comment by lslxdx** [comment]
If one must define a custom failover cycle, then it can be wrapped this way:
```
def my_failover_strategy(servers):
    it = list(servers)  # don't modify callers list
    shuffle = random.shuffle
    for _ in repeat(None):
        shuffle(it)
        yield it[0]


class MyCallableFailoverStrategy(object):
    def __call__(self, *param, **kwargs):
        return my_failover_strategy(*param, **kwargs)

    def __json__(self):
        return 'my_failover_strategy'


broker_failover_strategy = MyCallableFailoverStrategy()
```
