### ISSUE TITLE
"implicit" chords (chain of group + task) call the last task twice

### ISSUE THREAD

**Issue by bruno-rino** [celery/celery#3332]
Using the same "implicit" chord from #3331 (I just added a print statement for the task's input), the tasks complete successfully and return the correct value when the redis backend and pickle serialization, but the last task is called one more time. Since it expects a list and gets an integer, an exception is raised.

It works fine with CELERY_ALWAYS_EAGER. I could not replicate with other settings, because of the two other bugs I posted today (#3330 and #3331).

```python
from __future__ import absolute_import, division, print_function
from celery import Celery, chord, chain, group

app = Celery('chords')
app.config_from_object('celeryconfig_redis_pickle')

@app.task
def add(x, y):
    return x + y

@app.task
def tsum(numbers):
    print(numbers)
    return sum(numbers)

if __name__ == '__main__':
    result = chain([
        group([add.s(i, i) for i in xrange(100)]),
        tsum.s(),
    ]).apply_async()

    print(result.get())

```

The worker's output:
```
[2016-07-20 16:07:08,588: INFO/MainProcess] Received task: chords.tsum[8f3545d2-2c26-4acf-b2f0-9c3eaa18f6c5]
[2016-07-20 16:07:08,589: WARNING/PoolWorker-2] [2, 0, 6, 4, 8, 10, 14, 16, 22, 20, 12, 26, 24, 18, 28, 32, 30, 34, 36, 38, 42, 40, 46, 44, 48, 50, 54, 52, 56, 58, 60, 62, 66, 64, 70, 68, 72, 74, 78, 76, 80, 82, 86, 84, 90, 88, 92, 94, 96, 98, 102, 100, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 166, 164, 170, 168, 174, 172, 176, 178, 182, 180, 184, 186, 188, 190, 194, 192, 196, 198]
[2016-07-20 16:07:08,614: INFO/PoolWorker-2] Task chords.tsum[8f3545d2-2c26-4acf-b2f0-9c3eaa18f6c5] succeeded in 0.0247339670314s: 9900
[2016-07-20 16:07:08,614: INFO/MainProcess] Received task: chords.tsum[8f3545d2-2c26-4acf-b2f0-9c3eaa18f6c5]
[2016-07-20 16:07:08,615: WARNING/PoolWorker-2] 9900
[2016-07-20 16:07:08,617: ERROR/PoolWorker-2] Task chords.tsum[8f3545d2-2c26-4acf-b2f0-9c3eaa18f6c5] raised unexpected: TypeError("'int' object is not iterable",)
Traceback (most recent call last):
  File "/Users/rino/.virtualenvs/nors4/lib/python2.7/site-packages/celery/app/trace.py", line 357, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/rino/.virtualenvs/nors4/lib/python2.7/site-packages/celery/app/trace.py", line 608, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/rino/dev/celery4/chords_implicit_fail/chords.py", line 21, in tsum
    return sum(numbers)
TypeError: 'int' object is not iterable
```

**Comment by ask** [comment]
Is this Celery 4 or 3.1?

**Comment by honux** [comment]
Celery 4

**Comment by ask** [comment]
Do you have that config, because here it seems to work just fine using redis as a broker/result backend:

```
[2016-07-28 13:23:55,212: WARNING/PoolWorker-5] [2, 0, 6, 4, 12, 8, 10, 16, 14, 20, 22, 24, 26, 18, 30, 28, 34, 32, 36, 38, 40, 42, 44, 46, 48, 50, 54, 52, 58, 56, 60, 62, 64, 66, 68, 70, 72, 74, 78, 76, 80, 82, 84, 86, 88, 90, 92, 94, 98, 96, 102, 100, 104, 106, 110, 108, 114, 112, 118, 116, 122, 120, 124, 126, 128, 130, 134, 132, 138, 136, 142, 140, 144, 146, 148, 150, 154, 152, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 178, 176, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
[2016-07-28 13:23:55,213: INFO/PoolWorker-5] Task chords.tsum[65025b51-62f4-4ed4-a19c-9d2bb3c4e413] succeeded in 0.000844555004733s: 9900
```

**Comment by bruno-rino** [comment]
The config I used (celeryconfig_redis_pickle.py):

```python
BROKER_URL = 'redis://'
CELERY_RESULT_BACKEND = 'redis://'

CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ['pickle']
```

**Comment by bruno-rino** [comment]
It is fixed on the latest master. Thanks!
