### ISSUE TITLE
Beat error with redis

### ISSUE THREAD

**Issue by jamesob** [celery/celery#3346]
Hi, 

I'm hitting stacktraces when running my celery worker.

I have Celery configured like so:
```
In [1]: import celery

In [2]: celery.__version__
Out[2]: u'4.0.0rc3'

In [3]: from limsana import celery

In [4]: celery.app.__dict__
Out[4]:
{'_conf': Settings({'task_serializer': 'json', 'result_serializer': 'json', 'task_always_eager': False, 'accept_content': ['json'], 'timezone': 'US/Pacific', u'broker_url': u'redis://xx.usw2.cache.amazonaws.com/0', u'result_backend': u'redis://xx.usw2.cache.amazonaws.com/0'}),
 '_config_source': None,
 '_finalize_mutex': <thread.lock at 0x7f02128df650>,
 '_fixups': [None],
 '_pending': deque([]),
 '_pending_defaults': deque([]),
 '_pending_periodic_tasks': deque([]),
 '_preconf': {'accept_content': ['json'],
  u'broker_url': u'redis://xx.usw2.cache.amazonaws.com/0',
  u'result_backend': u'redis://xx.usw2.cache.amazonaws.com/0',
  'result_serializer': 'json',
  'task_always_eager': False,
  'task_serializer': 'json',
  'timezone': 'US/Pacific'},
 '_preconf_set_by_auto': {u'broker_url', u'result_backend'},
 '_tasks': {},
 '_using_v1_reduce': None,
 'amqp_cls': u'celery.app.amqp:AMQP',
 'autofinalize': True,
 'clock': <LamportClock: 0>,
 'configured': False,
 'control_cls': u'celery.app.control:Control',
 'events_cls': u'celery.events:Events',
 'finalized': False,
 'fixups': {u'celery.fixups.django:fixup'},
 'loader_cls': u'celery.loaders.app:AppLoader',
 'log_cls': u'celery.app.log:Logging',
 'main': 'celery',
 'namespace': None,
 'on_after_configure': <Signal: Signal>,
 'on_after_finalize': <Signal: Signal>,
 'on_after_fork': <Signal: Signal>,
 'on_configure': <Signal: Signal>,
 'registry_cls': celery.app.registry.TaskRegistry,
 'set_as_current': True,
 'steps': defaultdict(set, {}),
 'task_cls': u'celery.app.task:Task',
 'user_options': defaultdict(set, {})}

In [7]: celery.app.conf.beat_schedule
Out[7]:
{'limsana.core.tasks.consumable_etl()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 2 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.consumable_etl'},
 'limsana.core.tasks.consumablelock_etl()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 2 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.consumablelock_etl'},
 'limsana.core.tasks.consumablemovement_etl()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 2 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.consumablemovement_etl'},
 'limsana.core.tasks.equipment_etl()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 2 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.equipment_etl'},
 'limsana.core.tasks.inventoryitemlot_etl()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 2 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.inventoryitemlot_etl'},
 'limsana.core.tasks.job_etl()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 2 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.job_etl'},
 'limsana.core.tasks.jobstate_etl()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 2 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.jobstate_etl'},
 'limsana.core.tasks.op_etl()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 2 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.op_etl'},
 'limsana.core.tasks.opmaterial_etl()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 2 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.opmaterial_etl'},
 'limsana.core.tasks.vacuum_op()': {u'args': (),
  u'kwargs': {},
  u'options': {},
  u'schedule': <crontab: 0 * * * * (m/h/d/dM/MY)>,
  u'task': u'limsana.core.tasks.vacuum_op'}}
```

with `report` output:

```
deploy@limsana-stg-app-fd260:~$ limsana_run celery -A limsana.celery_worker report

software -> celery:4.0.0rc3 (0today8) kombu:4.0.0rc3 py:2.7.6
            billiard:3.5.0.0 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://xx.usw2.cache.amazonaws.com/0

task_serializer: 'json'
result_serializer: 'json'
task_always_eager: False
accept_content: ['json']
timezone: 'US/Pacific'
broker_url: u'redis://xx.usw2.cache.amazonaws.com:6379/0'
result_backend: u'redis://xx.usw2.cache.amazonaws.com/0'
```

When I start the worker with
```
celery worker -A limsana.celery_worker -B -Q celery,subscribers -l INFO -c 10
```

I get a few errors:

```
[2016-07-28 20:38:48,088: INFO/Beat] beat: Starting...
[2016-07-28 20:38:48,120: ERROR/Beat] Process Beat
Traceback (most recent call last):
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/billiard/process.py", line 301, in _bootstrap
    self.run()
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 602, in run
    self.service.start(embedded_process=True)
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 520, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 302, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 561, in scheduler
    return self.get_scheduler()
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 556, in get_scheduler
    lazy=lazy)
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/utils/imports.py", line 60, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 408, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 208, in __init__
    self.setup_schedule()
  File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 438, in setup_schedule
    self._store['entries']
  File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
TypeError: String or Integer object expected for key, unicode found
[2016-07-28 20:38:48,122: WARNING/Beat] Process Beat:
[2016-07-28 20:38:48,122: WARNING/Beat] Traceback (most recent call last):
[2016-07-28 20:38:48,123: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/billiard/process.py", line 301, in _bootstrap
[2016-07-28 20:38:48,123: WARNING/Beat] self.run()
[2016-07-28 20:38:48,123: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 602, in run
[2016-07-28 20:38:48,124: WARNING/Beat] self.service.start(embedded_process=True)
[2016-07-28 20:38:48,124: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 520, in start
[2016-07-28 20:38:48,124: WARNING/Beat] humanize_seconds(self.scheduler.max_interval))
[2016-07-28 20:38:48,124: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 302, in __get__
[2016-07-28 20:38:48,125: WARNING/Beat] value = obj.__dict__[self.__name__] = self.__get(obj)
[2016-07-28 20:38:48,125: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 561, in scheduler
[2016-07-28 20:38:48,125: WARNING/Beat] return self.get_scheduler()
[2016-07-28 20:38:48,125: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 556, in get_scheduler
[2016-07-28 20:38:48,126: WARNING/Beat] lazy=lazy)
[2016-07-28 20:38:48,126: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/utils/imports.py", line 60, in instantiate
[2016-07-28 20:38:48,126: WARNING/Beat] return symbol_by_name(name)(*args, **kwargs)
[2016-07-28 20:38:48,126: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 408, in __init__
[2016-07-28 20:38:48,127: WARNING/Beat] Scheduler.__init__(self, *args, **kwargs)
[2016-07-28 20:38:48,127: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 208, in __init__
[2016-07-28 20:38:48,127: WARNING/Beat] self.setup_schedule()
[2016-07-28 20:38:48,128: WARNING/Beat] File "/home/deploy/limsana/config/2016-07-29.033656_98cfe8/repo/venv/local/lib/python2.7/site-packages/celery/beat.py", line 438, in setup_schedule
[2016-07-28 20:38:48,128: WARNING/Beat] self._store['entries']
[2016-07-28 20:38:48,128: WARNING/Beat] File "/usr/lib/python2.7/shelve.py", line 121, in __getitem__
[2016-07-28 20:38:48,128: WARNING/Beat] f = StringIO(self.dict[key])
[2016-07-28 20:38:48,129: WARNING/Beat] File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in __getitem__
[2016-07-28 20:38:48,129: WARNING/Beat] return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
[2016-07-28 20:38:48,129: WARNING/Beat] File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
[2016-07-28 20:38:48,129: WARNING/Beat] return function(*_args, **_kwargs)
[2016-07-28 20:38:48,130: WARNING/Beat] File "/usr/lib/python2.7/bsddb/__init__.py", line 270, in <lambda>
[2016-07-28 20:38:48,130: WARNING/Beat] return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
[2016-07-28 20:38:48,130: WARNING/Beat] TypeError: String or Integer object expected for key, unicode found
[2016-07-28 20:38:48,647: INFO/MainProcess] Connected to redis://xx.usw2.cache.amazonaws.com:6379/0
[2016-07-28 20:38:48,663: INFO/MainProcess] mingle: searching for neighbors
[2016-07-28 20:38:49,685: INFO/MainProcess] mingle: all alone
[2016-07-28 20:38:49,708: WARNING/MainProcess] celery@limsana-stg-app-fd260 ready.
```

It looks as though perhaps we need to also be catching a `TypeError` when [setting up a new schedule store](https://github.com/celery/celery/blob/master/celery/beat.py#L437).

Thanks!

**Comment by auvipy** [comment]
thanks for report, were you able to find out some work around to fix the error?

**Comment by jamesob** [comment]
Nope; I just downgraded to Celery 3.x. 😢

**Comment by vpes** [comment]
Hi James,
I found the same problem with Django 1.10 and I'm fix it using explicits bytestring in celery/beat.py when accessing the _store items,

for example in line 426
self._store[b'entries'] 

or line 447
if b'__version__' not in self._store:
I hope this helps
Best regards
Victor
