### ISSUE TITLE
Chain tasks sent several times when using chain in nested chords

### ISSUE THREAD

**Issue by aauroy** [celery/celery#3347]
When using a `group` of `chain` as `header` in a two-level depth nested chords (construct is shown below), chain tasks seems to be sent `n` (`n`being the task's position in the chain) times to workers (issue may be related to #3323 and/or #3332). 

```
chord([
    chord([
        chain(task, task, task, ...)
    ], body=A)
], body=B)
```

##### celery report output
```
➜  celery -A tasks report

software -> celery:4.0.0rc3 (0today8) kombu:4.0.0rc3 py:3.5.2
            billiard:3.5.0.0 py-amqp:2.0.3
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://192.168.99.100:6379/0

broker_url: 'amqp://guest:********@192.168.99.100:5672//'
result_backend: 'redis://192.168.99.100:6379/0'
```

##### code sample

```python
@app.task(bind=True)
def simple_task(self):
    return 'simple_task %s' % self.request.id


@app.task
def lower_body(args):
    return 'lower_body'


@app.task
def higher_body(args):
    return 'higher_body'


def test_chords_with_chains(nb_tasks):
    c = chord([
            chord([
                chain(simple_task.si() for i in range(nb_tasks))
            ], body=lower_body.s())
    ], body=higher_body.s())

    c.delay()
```

##### code execution

* Calling `test_chords_with_chains` with `nb_tasks=2`

```
>>> import tasks
>>> tasks.test_chords_with_chains(nb_tasks=2)
```

* Worker output - task `4bb904c8-74d3-4420-9ff7-3f9ca8cfabf0` is received twice and `on_chord_part_return` raises a `TypeError`.

*NB: Chord `7114cfb4-1fe6-4638-9384-92064af989aa` seems to be the inner `chord` (the id never matched the outer chords in my tests)*

```
[2016-07-29 11:18:18,081: INFO/MainProcess] Received task: tasks.simple_task[c7da0c78-b09b-4bb3-b393-579621717463]
[2016-07-29 11:18:18,400: INFO/MainProcess] Received task: tasks.simple_task[4bb904c8-74d3-4420-9ff7-3f9ca8cfabf0]
[2016-07-29 11:18:18,404: INFO/MainProcess] Received task: tasks.simple_task[4bb904c8-74d3-4420-9ff7-3f9ca8cfabf0]
[2016-07-29 11:18:18,405: INFO/PoolWorker-4] Task tasks.simple_task[c7da0c78-b09b-4bb3-b393-579621717463] succeeded in 0.03469938899979752s: 'simple_task c7da0c78-b09b-4bb3-b393-579621717463'
[2016-07-29 11:18:18,413: ERROR/PoolWorker-8] Chord '7114cfb4-1fe6-4638-9384-92064af989aa' raised: TypeError("unsupported operand type(s) for +: 'NoneType' and 'int'",)
Traceback (most recent call last):
  File "/lib/python3.5/site-packages/celery/backends/redis.py", line 271, in on_chord_part_return
    total = callback['chord_size'] + totaldiff
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
[2016-07-29 11:18:18,417: INFO/PoolWorker-8] Task tasks.simple_task[4bb904c8-74d3-4420-9ff7-3f9ca8cfabf0] succeeded in 0.01200144700032979s: 'simple_task 4bb904c8-74d3-4420-9ff7-3f9ca8cfabf0'
[2016-07-29 11:18:18,434: INFO/PoolWorker-2] Task tasks.simple_task[4bb904c8-74d3-4420-9ff7-3f9ca8cfabf0] succeeded in 0.028082659999199677s: 'simple_task 4bb904c8-74d3-4420-9ff7-3f9ca8cfabf0'
[2016-07-29 11:18:18,434: INFO/MainProcess] Received task: tasks.lower_body[cd3a4209-518a-4213-9717-0adb0fb18461]
[2016-07-29 11:18:18,470: INFO/PoolWorker-5] Task tasks.lower_body[cd3a4209-518a-4213-9717-0adb0fb18461] succeeded in 0.03399557900047512s: 'lower_body'
[2016-07-29 11:18:18,470: INFO/MainProcess] Received task: tasks.higher_body[0fb00a3a-441e-4704-8b42-e5d7f6000e99]
[2016-07-29 11:18:18,482: INFO/PoolWorker-7] Task tasks.higher_body[0fb00a3a-441e-4704-8b42-e5d7f6000e99] succeeded in 0.009452047000195307s: 'higher_body'
```

* Calling `test_chords_with_chains` with `nb_tasks=4`

```
>>> import tasks
>>> tasks.test_chords_with_chains(nb_tasks=4)
```

* Worker output - task `b7fb056a-17ba-44c9-91a2-c301788349bf` is received twice, task `003da11f-a7b3-4a3e-8c69-d32427ea8cc2` three times and task `de957609-6aba-4760-b82b-b43c2d3f604f` four times (`on_chord_part_return` still raises a `TypeError`).

```
[2016-07-29 11:28:25,654: INFO/MainProcess] Received task: tasks.simple_task[3c287be6-cef4-48c9-a070-dd1aeb87cc24]
[2016-07-29 11:28:27,485: INFO/MainProcess] Received task: tasks.simple_task[b7fb056a-17ba-44c9-91a2-c301788349bf]
[2016-07-29 11:28:27,486: INFO/MainProcess] Received task: tasks.simple_task[b7fb056a-17ba-44c9-91a2-c301788349bf]
[2016-07-29 11:28:27,487: INFO/PoolWorker-7] Task tasks.simple_task[3c287be6-cef4-48c9-a070-dd1aeb87cc24] succeeded in 0.005497850999745424s: 'simple_task 3c287be6-cef4-48c9-a070-dd1aeb87cc24'
[2016-07-29 11:28:27,489: INFO/PoolWorker-4] Task tasks.simple_task[b7fb056a-17ba-44c9-91a2-c301788349bf] succeeded in 0.0017032369996741181s: 'simple_task b7fb056a-17ba-44c9-91a2-c301788349bf'
[2016-07-29 11:28:27,490: INFO/MainProcess] Received task: tasks.simple_task[003da11f-a7b3-4a3e-8c69-d32427ea8cc2]
[2016-07-29 11:28:27,490: INFO/MainProcess] Received task: tasks.simple_task[003da11f-a7b3-4a3e-8c69-d32427ea8cc2]
[2016-07-29 11:28:27,491: INFO/MainProcess] Received task: tasks.simple_task[003da11f-a7b3-4a3e-8c69-d32427ea8cc2]
[2016-07-29 11:28:27,491: INFO/PoolWorker-3] Task tasks.simple_task[b7fb056a-17ba-44c9-91a2-c301788349bf] succeeded in 0.0038708420006514643s: 'simple_task b7fb056a-17ba-44c9-91a2-c301788349bf'
[2016-07-29 11:28:27,493: INFO/PoolWorker-5] Task tasks.simple_task[003da11f-a7b3-4a3e-8c69-d32427ea8cc2] succeeded in 0.0015831269993213937s: 'simple_task 003da11f-a7b3-4a3e-8c69-d32427ea8cc2'
[2016-07-29 11:28:27,493: INFO/PoolWorker-8] Task tasks.simple_task[003da11f-a7b3-4a3e-8c69-d32427ea8cc2] succeeded in 0.0016433700002380647s: 'simple_task 003da11f-a7b3-4a3e-8c69-d32427ea8cc2'
[2016-07-29 11:28:27,494: INFO/PoolWorker-2] Task tasks.simple_task[003da11f-a7b3-4a3e-8c69-d32427ea8cc2] succeeded in 0.0026385999999547494s: 'simple_task 003da11f-a7b3-4a3e-8c69-d32427ea8cc2'
[2016-07-29 11:28:27,495: INFO/MainProcess] Received task: tasks.simple_task[de957609-6aba-4760-b82b-b43c2d3f604f]
[2016-07-29 11:28:27,495: INFO/MainProcess] Received task: tasks.simple_task[de957609-6aba-4760-b82b-b43c2d3f604f]
[2016-07-29 11:28:27,496: INFO/MainProcess] Received task: tasks.simple_task[de957609-6aba-4760-b82b-b43c2d3f604f]
[2016-07-29 11:28:27,496: INFO/MainProcess] Received task: tasks.simple_task[de957609-6aba-4760-b82b-b43c2d3f604f]
[2016-07-29 11:28:27,499: INFO/PoolWorker-6] Task tasks.simple_task[de957609-6aba-4760-b82b-b43c2d3f604f] succeeded in 0.0020060820006619906s: 'simple_task de957609-6aba-4760-b82b-b43c2d3f604f'
[2016-07-29 11:28:27,499: INFO/PoolWorker-4] Task tasks.simple_task[de957609-6aba-4760-b82b-b43c2d3f604f] succeeded in 0.0019897629999832134s: 'simple_task de957609-6aba-4760-b82b-b43c2d3f604f'
[2016-07-29 11:28:27,500: INFO/PoolWorker-1] Task tasks.simple_task[de957609-6aba-4760-b82b-b43c2d3f604f] succeeded in 0.0026390180000817054s: 'simple_task de957609-6aba-4760-b82b-b43c2d3f604f'
[2016-07-29 11:28:27,500: ERROR/PoolWorker-3] Chord 'ee5d1bb0-33b7-482c-97d7-28f6423fb5d5' raised: TypeError("unsupported operand type(s) for +: 'NoneType' and 'int'",)
Traceback (most recent call last):
  File "/lib/python3.5/site-packages/celery/backends/redis.py", line 271, in on_chord_part_return
    total = callback['chord_size'] + totaldiff
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
[2016-07-29 11:28:27,501: INFO/PoolWorker-3] Task tasks.simple_task[de957609-6aba-4760-b82b-b43c2d3f604f] succeeded in 0.0037148969995541847s: 'simple_task de957609-6aba-4760-b82b-b43c2d3f604f'
```

**Comment by bruno-rino** [comment]
This seems to be a rabbitmq specific bug. Your sample code works fine using redis. Related to #3330

**Comment by ask** [comment]
This works for me both using the amqp and the redis result backend now:

```
[2016-10-12 19:31:55,405: INFO/MainProcess] Received task: app.simple_task[5e962bf0-a1c2-43c9-8d6c-0d505165f4f4]
[2016-10-12 19:31:55,420: INFO/MainProcess] Received task: celery.chord_unlock[b834e805-e4fc-4a20-bbb1-b0e16e2e6bac]  ETA:[2016-10-13 02:31:56.406485+00:00]
[2016-10-12 19:31:55,423: INFO/MainProcess] Received task: app.simple_task[5ba8eb16-20f6-4cd5-a0e4-ab4d0f163e3b]
[2016-10-12 19:31:55,432: INFO/MainProcess] Received task: celery.chord_unlock[a0c1107f-c331-4893-8f29-5949ad8ce320]  ETA:[2016-10-13 02:31:56.420132+00:00]
[2016-10-12 19:31:55,433: INFO/PoolWorker-4] Task app.simple_task[5e962bf0-a1c2-43c9-8d6c-0d505165f4f4] succeeded in 0.012187632994s: 'simple_task 5e962bf0-a1c2-43c9-8d6c-0d505165f4f4'
[2016-10-12 19:31:55,437: INFO/MainProcess] Received task: app.simple_task[765e498d-5403-41b2-a8bc-a5785115106a]
[2016-10-12 19:31:55,446: INFO/PoolWorker-1] Task app.simple_task[5ba8eb16-20f6-4cd5-a0e4-ab4d0f163e3b] succeeded in 0.0135732660128s: 'simple_task 5ba8eb16-20f6-4cd5-a0e4-ab4d0f163e3b'
[2016-10-12 19:31:55,450: INFO/MainProcess] Received task: app.simple_task[4f288407-b38b-4bcb-a97e-05800ffb32ca]
[2016-10-12 19:31:55,459: INFO/PoolWorker-8] Task app.simple_task[765e498d-5403-41b2-a8bc-a5785115106a] succeeded in 0.011067370011s: 'simple_task 765e498d-5403-41b2-a8bc-a5785115106a'
[2016-10-12 19:31:55,470: INFO/PoolWorker-3] Task app.simple_task[4f288407-b38b-4bcb-a97e-05800ffb32ca] succeeded in 0.00998086298932s: 'simple_task 4f288407-b38b-4bcb-a97e-05800ffb32ca'
[2016-10-12 19:31:56,442: INFO/PoolWorker-6] Task celery.chord_unlock[a0c1107f-c331-4893-8f29-5949ad8ce320] retry: Retry in 1s
[2016-10-12 19:31:56,442: INFO/MainProcess] Received task: celery.chord_unlock[a0c1107f-c331-4893-8f29-5949ad8ce320]  ETA:[2016-10-13 02:31:57.439251+00:00]
[2016-10-12 19:31:56,443: INFO/PoolWorker-4] Task celery.chord_unlock[b834e805-e4fc-4a20-bbb1-b0e16e2e6bac] succeeded in 0.0208622349892s: None
[2016-10-12 19:31:56,444: INFO/MainProcess] Received task: app.lower_body[bcd35f54-15d5-4f9d-a4b5-401075394d18]
[2016-10-12 19:31:56,447: INFO/PoolWorker-2] Task app.lower_body[bcd35f54-15d5-4f9d-a4b5-401075394d18] succeeded in 0.00164075399516s: 'lower_body'
[2016-10-12 19:31:58,195: INFO/PoolWorker-7] Task celery.chord_unlock[a0c1107f-c331-4893-8f29-5949ad8ce320] succeeded in 0.0215668200108s: None
[2016-10-12 19:31:58,196: INFO/MainProcess] Received task: app.higher_body[728e7e83-7ca0-4ad9-94c5-3d290a7f5c6c]
[2016-10-12 19:31:58,208: INFO/PoolWorker-5] Task app.higher_body[728e7e83-7ca0-4ad9-94c5-3d290a7f5c6c] succeeded in 0.0112173439993s: 'higher_body'
```

I'm guessing it was due to #3330, and reverting the amqp result backend changes also fixed this issue.
