### ISSUE TITLE
Chain doesn't work between separately configured apps

### ISSUE THREAD

**Issue by larmoreg** [celery/celery#3350]
I am trying to chain two separate workers (app1.py and app2.py) together using celery.

app1.py

```
from celery import Celery
from kombu import Exchange, Queue

app1 = Celery('app1')
app1.conf.update(
    BROKER_URL='amqp://',
    CELERY_RESULT_BACKEND='db+sqlite:///results.db',
    CELERY_QUEUES=(
        Queue('app1', Exchange('default', type='direct'), routing_key='app1'),
        Queue('app2', Exchange('default', type='direct'), routing_key='app2'),
    ),
)


@app1.task(exchange='default', routing_key='app1')
def add(x, y):
    return x + y
```

app2.py

```
from celery import Celery
from kombu import Exchange, Queue

app2 = Celery('app2')
app2.conf.update(
    BROKER_URL='amqp://',
    CELERY_RESULT_BACKEND='db+sqlite:///results.db',
    CELERY_QUEUES=(
        Queue('app1', Exchange('default', type='direct'), routing_key='app1'),
        Queue('app2', Exchange('default', type='direct'), routing_key='app2'),
    ),
)


@app2.task(exchange='default', routing_key='app2')
def mul(x, y):
    return x * y
```

The two workers are run using celery multi with two separate queues as follows:

```
celery multi start app1 -A app1 -Q app1
celery multi start app2 -A app2 -Q app2
```

And below is the test I am running (called test.py). The first two lines work as expected but the third hangs.

test.py

```
#!/usr/bin/env python2

from app1 import add
from app2 import mul

if __name__ == '__main__':
    print(add.s(1, 2).apply_async().get())
    print(mul.s(1, 2).apply_async().get())
    print((add.s(1, 2) | mul.s(3)).apply_async().get())
```

Looking at rabbitmqadmin I see one message sitting in the celery queue with the payload:

`[[3, 3], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": []}]`

Is this a bug or a feature not yet implemented? It seems to me that having the ability to chain between multiple (potentially remote) workers would be an extremely useful feature.

**Comment by aaronwinter** [comment]
`    print((add.s(1, 2) | mul.s(3)).apply_async().get())`

Correct me if I am wrong: you wan the first call `add.s(1, 2)` to be applied as the second argument to `mul.s(3)` right? What are you using a bitwise OR (`|`) for?

**Comment by larmoreg** [comment]
The pipe is shorthand for chain in celery (see http://docs.celeryproject.org/en/latest/userguide/canvas.html). The result of the add task is passed as the first argument to the mul task.

**Comment by aaronwinter** [comment]
Got it, thanks

**Comment by larmoreg** [comment]
I found a workaround that might shed more light on this issue.

If you explicitly set the exchange and routing_key in the chain:

`print((add.s(1, 2) | mul.s(3).set(exchange='default', routing_key='app2')).apply_async().get())`

Then it works as expected. It seems that chain is ignoring the settings in the task decorator.

**Comment by larmoreg** [comment]
The workaround above works only for chains. Chords don't work at all with multiple workers. For example the following fails:

`print(chord((add.s(1, 2), add.s(3, 4)), mul.s().set(exchange='default', routing_key='app2')).delay().get())`

**Comment by ask** [comment]
For chords this depends on the result backend used, the apps would have to use the same result backend.

I've been planning on adding a `.apply_async(reply_to='redis://b.com/1') argument, that would solve this.

**Comment by larmoreg** [comment]
The redis backend works for chords (but only with the workaround mentioned above). I have not been able to get any of amqp, rpc, or db to work with chords.

**Comment by tino** [comment]
This works for chords on the redis backend, however, it does not work when a task in the header fails. Then a `NotRegistered` error is raised, and the task remains in 'PENDING' state.

Any workarounds for that?

**Comment by ask** [comment]
@tino, Do you have a traceback?

**Comment by tino** [comment]
@ask:

Setting the queue happens with a task router:
```python
class ServiceTaskRouter(object):
    def route_for_task(self, task, *args, **kwargs):
        if task.startswith('service'):
            return {
                'queue': processing_queue,
                'routing_key': processing_queue
            }
```

Calling:
```python
callback = signature(
    'systems.tasks.save_calculated_yields',
    kwargs={'system_id': self.id}
).set(queue=settings.CELERY_DEFAULT_QUEUE)  # Be explicit about the queue

header = [signature('service.tasks.calculate', kwargs=string)
          for string in self.serialize_stringconfig()]
async_result = chord(header)(callback)
```

Gives this traceback in the service worker, which is another code base than the one the task is called from:
```
[2016-12-09 13:02:04,093: DEBUG/MainProcess] Task accepted: service.tasks.calculate[e8dc81f4-d2de-4881-a1fe-fd7f333d294a] pid:53
[2016-12-09 13:02:04,119: ERROR/Worker-1] Chord u'f1207b34-e1ee-4f1d-a5f3-2d9f895f15df' raised: "Dependency e8dc81f4-d2de-4881-a1fe-fd7f333d294a raised ValueError(u'Demonstrate failure in header task',)"
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 580, in on_chord_part_return
     ret = j(timeout=3.0, propagate=propagate)
   File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 691, in join_native
     raise value
 ValueError: Demonstrate failure in header task
[2016-12-09 13:02:04,136: WARNING/Worker-1] /usr/local/lib/python2.7/dist-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: Task of kind u'systems.tasks.save_calculated_yields' is not registered, please make sure it's imported.:
 Traceback (most   recent call last):
   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 296, in trace_task
     on_chord_part_return(task, state, R)
   File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 591, in on_chord_part_return
     self.chord_error_from_stack(callback, ChordError(reason))
   File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 138, in chord_error_from_stack
     backend = app._tasks[callback.task].backend
   File "/usr/local/lib/python2.7/dist-packages/celery/app/registry.py", line 26, in __missing__
     raise self.NotRegistered(key)
 NotRegistered: u'systems.tasks.save_calculated_yields'

   exc, exc_info.traceback)))
 [2016-12-09 13:02:04,149: CRITICAL/MainProcess] Task service.tasks.calculate[e8dc81f4-d2de-4881-a1fe-fd7f333d294a] INTERNAL ERROR: Task of kind u'systems.tasks.save_calculated_yields' is not registered, please make sure it's imported.
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 296, in trace_task
     on_chord_part_return(task, state, R)
   File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 591, in on_chord_part_return
     self.chord_error_from_stack(callback, ChordError(reason))
   File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 138, in chord_error_from_stack
     backend = app._tasks[callback.task].backend
   File "/usr/local/lib/python2.7/dist-packages/celery/app/registry.py", line 26, in __missing__
     raise self.NotRegistered(key)
 NotRegistered: u'systems.tasks.save_calculated_yields'
```

This works (but is a single task which I would like to parallelise):
```python
# An error cleanup task is needed, as the returned and stored task id is
# that of the calculation task. If the calculation task fails, the save
# task is dropped, and the frontend doesn't know the status anymore.
error_cleanup = signature('systems.tasks.cleanup_after_error_in_calculation',
                          args=(self.id,))  # The result will be prepended
# The queue neest to be explicitly set back to the default queue on the
# callback, otherwise it is executed in the service queue.
error_cleanup.set(queue=settings.CELERY_DEFAULT_QUEUE)

calculation_task = signature(
    'service.tasks.calculate_strings',
    args=self.serialize_stringconfig(),
    link_error=error_cleanup
)

callback = signature(
    'systems.tasks.save_calculated_yields',
    kwargs={'system_id': self.id}
).set(queue=settings.CELERY_DEFAULT_QUEUE)  # Idem being explicit about the queue

async_result = (calculation_task | callback).apply_async()
```

**Comment by auvipy** [comment]
can anyone verify if the changes in master fix this issue?

**Comment by auvipy** [comment]
does this solve the issue https://github.com/celery/celery/issues/2778#issuecomment-306821174 ?

**Comment by auvipy** [comment]
closing for lack of feedback
