### ISSUE TITLE
celery chord task raise critical error while redis backend connection socket timeout

### ISSUE THREAD

**Issue by ricky1993** [celery/celery#3363]
Hi all, we found when the server read from redis backend socket timeout, part of the chord body would lost. Can anyone give some help? Following is the traceback:

```
807_Mainthread /opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: TimeoutError('Timeout reading from socket',
Traceback (most recent call last):
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/celery/app/trace.py", line 296, in trace_task
    on_chord_part_return(task, state, R)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/celery/backends/base.py", line 555, in on_chord_part_return
    val = self.incr(key)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/celery/backends/redis.py", line 175, in incr
    return self.client.incr(key)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/client.py", line 842, in incr
    return self.execute_command('INCRBY', name, amount)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/client.py", line 529, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/client.py", line 541, in parse_response
    response = connection.read_response()
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/connection.py", line 572, in read_response
    response = self._parser.read_response()
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/connection.py", line 321, in read_response
    raise TimeoutError("Timeout reading from socket")
TimeoutError: Timeout reading from socket

  exc, exc_info.traceback)))
 -- report_internal_error:365
n108-023-033:2016-07-13 10:31:19,821 CRITICAL 750_MainThread Task video.src.encode.tasks.encode_single_definition[a46c03c2-4167-4e23-92f6-dd443ec4d834] INTERNAL ERROR: TimeoutError('Timeout reading from socket',) - log:282
Traceback (most recent call last):
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/celery/app/trace.py", line 296, in trace_task
    on_chord_part_return(task, state, R)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/celery/backends/base.py", line 555, in on_chord_part_return
    val = self.incr(key)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/celery/backends/redis.py", line 175, in incr
    return self.client.incr(key)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/client.py", line 842, in incr
    return self.execute_command('INCRBY', name, amount)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/client.py", line 529, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/client.py", line 541, in parse_response
    response = connection.read_response()
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/connection.py", line 572, in read_response
    response = self._parser.read_response()
  File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/redis/connection.py", line 321, in read_response
    raise TimeoutError("Timeout reading from socket")
TimeoutError: Timeout reading from socket
```

**Comment by thedrow** [comment]
@dvirsky Would you mind taking a look?

**Comment by ask** [comment]
I guess we need to retry all redis operations here, assuming this timeout error can be recovered from.

**Comment by ricky1993** [comment]
File "/opt/tiger/ss_lib/python_package/lib/python2.7/site-packages/celery/backends/base.py", line 555, in on_chord_part_return
    val = self.incr(key)
We found celery use a increasing key to count the number of task in a group. It doesn't satisfy idempotency and we are not sure if retry "incr(key)" will cause other problems.

**Comment by ask** [comment]
In Celery 4 the default redis socket timeout is 5 seconds, that should be raised to 120 seconds probably.

In Celery 3.1 though, I cannot see that there's any default timeout at all, but you can set one.  Did you set a timeout?

**Comment by auvipy** [comment]
reopen if it's still on master
