### ISSUE TITLE
Celery worker connection with Rabittmq met broken pipe error IN Gevent Mode

### ISSUE THREAD

**Issue by jcyrss** [celery/celery#3377]
Celery version 3.1.22

Celery worker connection with Rabittmq met broken pipe error IN Gevent Mode,
while no problem when Celery worker work in Process pool mode. 
Is that due to Gevent Monkey Patch?

======  Celery log ======

[2016-08-08 13:52:06,913: CRITICAL/MainProcess] Couldn't ack 293, reason:error(32, 'Broken pipe')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/kombu/message.py", line 93, in ack_log_error
    self.ack()
  File "/usr/local/lib/python2.7/site-packages/kombu/message.py", line 88, in ack
    self.channel.basic_ack(self.delivery_tag)
  File "/usr/local/lib/python2.7/site-packages/amqp/channel.py", line 1584, in basic_ack
    self._send_method((60, 80), args)
  File "/usr/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/usr/local/lib/python2.7/site-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/usr/local/lib/python2.7/site-packages/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
  File "/usr/local/lib/python2.7/site-packages/gevent/_socket2.py", line 412, in sendall
    timeleft = self.__send_chunk(chunk, flags, timeleft, end)
  File "/usr/local/lib/python2.7/site-packages/gevent/_socket2.py", line 351, in __send_chunk
    data_sent += self.send(chunk, flags)
  File "/usr/local/lib/python2.7/site-packages/gevent/_socket2.py", line 320, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe

======= Rabbitmq log ==================

=ERROR REPORT==== 8-Aug-2016::14:28:33 ===
closing AMQP connection <0.15928.4> (10.26.39.183:60732 -> 10.26.39.183:5672):
{writer,send_failed,{error,enotconn}}

=ERROR REPORT==== 8-Aug-2016::14:29:03 ===
closing AMQP connection <0.15981.4> (10.26.39.183:60736 -> 10.26.39.183:5672):
{writer,send_failed,{error,enotconn}}

=ERROR REPORT==== 8-Aug-2016::14:29:03 ===
closing AMQP connection <0.15955.4> (10.26.39.183:60734 -> 10.26.39.183:5672):
{writer,send_failed,{error,enotconn}}

**Comment by ask** [comment]
This is probably fixed in master

**Comment by jcyrss** [comment]
How can I change to master code, and still use celery 3.x without upgrade to 4.x RC?
Because I tried with 4.x RC and met some issues like celery beat does not work, and other weird things.

**Comment by jcyrss** [comment]
Hi, maybe I found one clue to reproduce that. 
That issue alway happen when the speed of Celery workers consuming task messages slower than Django applications producing messages, and about 3 thounds of messages piled in Rabbitmq.

**Comment by qinshuang** [comment]
I met the same problem, Is it fixed?

**Comment by jamestrose** [comment]
I have been experiencing the same issue, and also think it might be related to Django and exception handling. Anyone have any updates for this issue? Anybody found a solution or workaround?

**Comment by jamestrose** [comment]
I am also seeing the same problem in the latest build, and think it has something to do with Django and exception handling. Has anyone developed a solution or workaround?

**Comment by jamestrose** [comment]
test

**Comment by jimmyjr3** [comment]
test

**Comment by robsonpeixoto** [comment]
The RabbitMQ show this error:
```
rabbitmq_1  | =ERROR REPORT==== 3-Dec-2016::19:28:52 ===
rabbitmq_1  | closing AMQP connection <0.2500.1> (172.19.0.4:42882 -> 172.19.0.3:5672):
rabbitmq_1  | missed heartbeats from client, timeout: 60s
```

And the celery Traceback:
```
celery_1    | [2016-12-03 17:28:52,147: WARNING/MainProcess] Traceback (most recent call last):
celery_1    | [2016-12-03 17:28:52,150: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/gevent/hub.py", line 846, in switch
celery_1    |     switch(value)
celery_1    | [2016-12-03 17:28:52,153: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/celery/worker/pidbox.py", line 116, in loop
celery_1    |     connection.drain_events(timeout=1.0)
celery_1    | [2016-12-03 17:28:52,154: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 301, in drain_events
celery_1    |     return self.transport.drain_events(self.connection, **kwargs)
celery_1    | [2016-12-03 17:28:52,156: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
celery_1    |     return connection.drain_events(**kwargs)
celery_1    | [2016-12-03 17:28:52,158: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 464, in drain_events
celery_1    |     return self.blocking_read(timeout)
celery_1    | [2016-12-03 17:28:52,158: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 468, in blocking_read
celery_1    |     frame = self.transport.read_frame()
celery_1    | [2016-12-03 17:28:52,159: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 223, in read_frame
celery_1    |     frame_header = read(7, True)
celery_1    | [2016-12-03 17:28:52,161: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 363, in _read
celery_1    |     s = recv(n - len(rbuf))
celery_1    | [2016-12-03 17:28:52,162: WARNING/MainProcess] File "/usr/local/lib/python3.5/site-packages/gevent/_socket3.py", line 313, in recv
celery_1    |     return _socket.socket.recv(self._sock, *args)
celery_1    | [2016-12-03 17:28:52,162: WARNING/MainProcess] ConnectionResetError: [Errno 104] Connection reset by peer
celery_1    | [2016-12-03 17:28:52,163: WARNING/MainProcess] <built-in method switch of greenlet.greenlet object at 0x7efedbf853d8> failed with ConnectionResetError
```

More info about the environment:
```
root@5631e10b158e:/usr/src/app# celery -A notification report

software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.2
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

include: ['notification.tasks']
broker_url: 'amqp://guest:********@rabbitmq:5672//'
task_default_queue: 'notification'
```

**Comment by robsonpeixoto** [comment]
I'm having a similar bug on celery 4.0.0  #3649

**Comment by alanhamlett** [comment]
Having the same issue with Celery 4.0.2.

**Comment by nhaas-twist** [comment]
Same. Was fine under Celery 3.x.

**Comment by leobuskin** [comment]
Can confirm @jcyrss - same, when Django produces messages faster than Celery workers consuming, not sure is it gevent monkey patch or not, but now trying to find a solution, first step - multiplying celery instances

**Comment by vesterbaek** [comment]
Also seeing this with 4.1.0 and rabbitmq

**Comment by hoozecn** [comment]
Having the same prob with celery 4.0.2 + gevent + python3

**Comment by listingmirror** [comment]
I see this in prefork under high load

**Comment by listingmirror** [comment]
@canassa what is starved for resources here?

I have my rabbitmq box in kubernetes on a very very very big machine. I limit it to 8GB of ram, and no CPU limit. Memory usage sits at maybe 2 GB.  Anything in specific I should be looking for?

**Comment by canassa** [comment]
@listingmirror Starving resources in my case was high CPU usage. My machine was a EC2 T something and it was being throttled by Amazon when I saw this happening, like I said upgrading the machine fixed the issue. If your machine has both CPU and RAM to spare then I don't think I know what's the problem in your case, but I would still try to play around with a different hardware just to see if it helps

**Comment by listingmirror** [comment]
@canassa Thinking maybe the cpu WAS maxed for a few seconds at one point.. think rabbit just gets in a bad state internally and needs a reboot when this happens?  Argh.

**Comment by canassa** [comment]
@listingmirror That's weird, I have never seem rabbit crashing, that thing is solid as a rock. My problems were always with the celery workers but never with rabbit itself.

**Comment by listingmirror** [comment]
@canassa it's not rabbit crashing, it is the broken pipes as mentioned above.  I was wondering if somehow rabbit got in an internally bad state, which makes it drop connections?

Or maybe I am just giving it too many connections.. humm

**Comment by bernardko** [comment]
I'm seeing this issue with kombu consumers + gevent monkey patching. 

I have both normal consumers and monkey patched consumers connecting to the same rabbitmq instance and the monkey patched ones consistently raises broken pipe errors when acking while the normal consumers run without issue.

**Comment by hoozecn** [comment]
I don't think it's wise to close this issue if the issue caused by cpu overload. In most cases, we can't guarantee that the cpu will not be overloaded, although it could be temporary. Maybe a logic that will re-establish the connection automatically could help?

**Comment by auvipy** [comment]
any one can report if this still on master?

**Comment by mihajenko** [comment]
I've been dealing with this bug for over a year now (on 3.xx and 4.xx). I've switched from Windows to Linux during this. My experiences when this can happen:

1. On gevent threads that are taking too long
2. Workers don't consume messages from RabbitMQ fast enough
3. There is resource starvation for one of the dependent processes (ex: database swaps because lack of free memory) or generally when CPU cannot keep up with task processing
4. When resources are already scarce and new worker instances are started, worker synchronization occurs, which can block workers (**this** needs code fixing)

How to deal with them:

1. lower your expectations what greenlets can do
2. add more workers
3. optimize your tasks, optimize your OS/system, and/or get more resources (scale). **However**, since that is not a guarantee that this won't happen, assess how much time your tasks take and set soft and hard time limits on them, and accept the fact that hard limits can happen
4. see 3., but also killing and restarting hung workers (without hard limits) might not work, since newly started workers need to synchronize as well, leading them to fail over and over again

Hope this helps anyone.

**Comment by auvipy** [comment]
@mihajenko thanks for you detail explanation

**Comment by bremac** [comment]
I'm not familiar enough with celery's design to suggest a proper fix for the issue, but I do have a hack to force celery to reconnect if the connection drops: https://github.com/celery/celery/commit/385a60df09201a17ad646c71eb1c00255d0a4431

**Comment by auvipy** [comment]
@bremac could you please send a PR to fix?

**Comment by jagguli** [comment]
I've created a PR for this, currently testing this, seems good so far

https://github.com/celery/celery/pull/5581

**Comment by jagguli** [comment]
rabbitmq is missing heartbeats 

```

=ERROR REPORT==== 12-Jun-2019::06:22:10 ===
closing AMQP connection <0.4890.1> (13.0.1.102:36774 -> 13.0.1.11:5672):
missed heartbeats from client, timeout: 60s

=ERROR REPORT==== 12-Jun-2019::06:22:12 ===
closing AMQP connection <0.5024.1> (13.0.1.102:36822 -> 13.0.1.11:5672):
missed heartbeats from client, timeout: 60s

=ERROR REPORT==== 12-Jun-2019::06:22:12 ===
closing AMQP connection <0.5021.1> (13.0.1.102:36820 -> 13.0.1.11:5672):
missed heartbeats from client, timeout: 60s

=ERROR REPORT==== 12-Jun-2019::06:22:12 ===
closing AMQP connection <0.5018.1> (13.0.1.102:36816 -> 13.0.1.11:5672):
missed heartbeats from client, timeout: 60s

=ERROR REPORT==== 12-Jun-2019::06:22:12 ===
closing AMQP connection <0.5015.1> (13.0.1.102:36812 -> 13.0.1.11:5672):
missed heartbeats from client, timeout: 60s

=ERROR REPORT==== 12-Jun-2019::06:22:18 ===
closing AMQP connection <0.5066.1> (13.0.1.102:36840 -> 13.0.1.11:5672):
missed heartbeats from client, timeout: 60s
```

**Comment by nevenag** [comment]
I have seen this error when time is not synchronized between workers and the queue (some of my servers were in a different time zone.) Setting the same timezone helped.

`sudo  export TZ="US/Pacific"`

**Comment by laruellef** [comment]
Having same issue, for us it seems to be consistently linked to a long running task...
the ack at the end is what's failing...
```
Couldn't ack 40, reason:BrokenPipeError(32, 'Broken pipe')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kombu/message.py", line 131, in ack_log_error
    self.ack(multiple=multiple)
  File "/usr/local/lib/python3.5/dist-packages/kombu/message.py", line 126, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/usr/local/lib/python3.5/dist-packages/amqp/channel.py", line 1399, in basic_ack
    spec.Basic.Ack, argsig, (delivery_tag, multiple),
  File "/usr/local/lib/python3.5/dist-packages/amqp/abstract_channel.py", line 51, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.5/dist-packages/amqp/method_framing.py", line 172, in write_frame
    write(view[:offset])
  File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 284, in write
    self._write(s)
  File "/usr/local/lib/python3.5/dist-packages/gevent/_socket3.py", line 418, in sendall
    data_sent += self.send(data_memory[data_sent:], flags)
  File "/usr/local/lib/python3.5/dist-packages/gevent/_socket3.py", line 390, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe
```
Is there some setting we can try to fix this?
Currently the worker's dead when this happens, even tho we use supervisord with autorestart, at a minimum we would expect the error to bubble all the way up and to see supervisord restart the thread, but that's not happening...
supervisord thinks the worker is still running but it's really dead...
in settings, we have:
```
CELERY_BROKER_POOL_LIMIT = None
CELERY_BROKER_CONNECTION_TIMEOUT = 20
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = None
CELERY_TASK_RESULT_EXPIRES = 60
```
we use memcached as result backend.
will try to increase CELERY_TASK_RESULT_EXPIRES and see if that fixes the problem...
Any insights welcome...

**Comment by auvipy** [comment]
may I know it's update with celery==4.4.0

**Comment by auvipy** [comment]
can you try this patch https://github.com/celery/celery/pull/5581/files ?

**Comment by auvipy** [comment]
can you try this patch https://github.com/celery/celery/pull/5581/files ?

**Comment by madchap** [comment]
Still happening in 4.4.2 apparently. I am hit by this.

**Comment by auvipy** [comment]
feel free to test and update the unit test for the linked patch

**Comment by Honst211** [comment]
This problem still exists in 4.4.7

**Comment by aLeX1443** [comment]
Getting this in 5.0.2. Seems to be failing outside my `@app.task` so can't use a `try` statement to catch it

```
[2020-12-21 02:51:47,706: CRITICAL/MainProcess] Couldn't ack 84, reason:BrokenPipeError(32, 'Broken pipe')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/kombu/message.py", line 128, in ack_log_error
    self.ack(multiple=multiple)
  File "/opt/conda/lib/python3.7/site-packages/kombu/message.py", line 123, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/opt/conda/lib/python3.7/site-packages/amqp/channel.py", line 1392, in basic_ack
    spec.Basic.Ack, argsig, (delivery_tag, multiple),
  File "/opt/conda/lib/python3.7/site-packages/amqp/abstract_channel.py", line 57, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/opt/conda/lib/python3.7/site-packages/amqp/method_framing.py", line 183, in write_frame
    write(view[:offset])
  File "/opt/conda/lib/python3.7/site-packages/amqp/transport.py", line 321, in write
    self._write(s)
  File "/opt/conda/lib/python3.7/site-packages/gevent/_socket3.py", line 534, in sendall
    return _socketcommon._sendall(self, data_memory, flags)
  File "/opt/conda/lib/python3.7/site-packages/gevent/_socketcommon.py", line 392, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/opt/conda/lib/python3.7/site-packages/gevent/_socketcommon.py", line 321, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/opt/conda/lib/python3.7/site-packages/gevent/_socket3.py", line 515, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by ozgurakcali** [comment]
I've also been getting these errors with celery / rabbitmq / gevent workers. I've increased the resources on the server, so that max cpu usage hits at most around 50%, but still got these errors. Tried different concurrency levels between 4 and 128 with no help.  

celery==5.1.2
gevent==21.1.2
amqp ==5.0.6
rabbitmq: AWS managed service

Also, this does not happen with our dev environment, tasks there run on a much smaller db, so issuing much less db queries and external requests, I imagine this issue might have something to do with task loads.

We decided not to use gevent workers, but switched to threads workers, still enabling us more concurrency at less resource usage when compared to prefork workers, at the expense of possible less efficiency of os task scheduler when compared to gevent event loop.

**Comment by rmaleki** [comment]
Having the same issue:

`BrokenPipeError: [Errno 32] Broken pipe`

```
celery==5.2.7
gevent==22.10.1
amqp==5.1.1
kombu==5.2.4
```
this does not happen with our dev environment, I imagine this issue might have something to do with task loads.

**Comment by vladjkeeee13** [comment]
Got the same error.
Try to increase memory for this worker. It helped in my case.
