### ISSUE TITLE
Nested chains/chords fail under celery4

### ISSUE THREAD

**Issue by bruno-rino** [celery/celery#3381]
The following code works fine under celery 3. Under celery 4, it fails both for ALWAYS_EAGER and redis, but in different ways. Not tested for rabbitmq, because then chords are not working at all (see #3330)

In the following code I define:
- `t1` is a "simple" chord: its head consists of two tasks
- `t2` is a "nested" chord: its head consists of two chains instead
- `t3` and `t4` just add a task before `t1` and `t2` respectively, using a chain

only `t4` fails.

```python
from __future__ import absolute_import, division, print_function
from celery import Celery, chord, chain, group
from celery.utils.log import get_task_logger


app = Celery('tasks', backend='redis', broker='redis://')
# app.conf.CELERY_ALWAYS_EAGER = True
logger = get_task_logger(__name__)


@app.task
def ident(x):
    print(x)
    return x


@app.task
def tsum(numbers):
    print(numbers)
    return sum(numbers)


if __name__ == '__main__':

    t1 = chord([
        ident.si(2),
        ident.si(3),
    ], tsum.s())

    t2 = chord([
        chain([
            ident.si(2),
            ident.si(4),
        ]),
        chain([
            ident.si(3),
            ident.si(5),
        ]),
    ], tsum.s())

    t3 = chain([
        ident.si(1),
        t1
    ])

    t4 = chain([
        ident.si(1),
        t2
    ])

    result = t1.apply_async()
    print(result.get())

    result = t2.apply_async()
    print(result.get())

    result = t3.apply_async()
    print(result.get())

    result = t4.apply_async()
    print(result.get())

```
### redis
with redis, t4 fails with the following error:
AttributeError: 'dict' object has no attribute 'clone'

traceback
```
Traceback (most recent call last):
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/app/trace.py", line 413, in trace_task
    parent_id=uuid, root_id=root_id,
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 1169, in apply_async
    return self.run(tasks, body, args, task_id=task_id, **options)
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 1204, in run
    group_id=group_id, chord=body, root_id=root_id).results
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 1040, in freeze
    new_tasks, group_id, chord, root_id, parent_id,
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 1014, in _freeze_unroll
    task = maybe_signature(stack.popleft(), app=self._app).clone()
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 572, in clone
    s.kwargs['tasks'] = [sig.clone() for sig in s.kwargs['tasks']]
AttributeError: 'dict' object has no attribute 'clone'
```

celery -A tasks report
```
software -> celery:4.0.0rc3 (0today8) kombu:4.0.0rc3 py:2.7.10
            billiard:3.5.0.0 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis

broker_url: u'redis://localhost:6379//'
result_backend: 'redis'
```

### CELERY_ALWAYS_EAGER
with CELERY_ALWAYS_EAGER, t4 fails with the following error:
TypeError: ident() takes exactly 1 argument (2 given)

traceback
```
Traceback (most recent call last):
  File "tasks.py", line 65, in <module>
    result = t4.apply_async()
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 579, in apply_async
    return self.apply(args, kwargs, **options)
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 719, in apply
    last and (last.get(),), **dict(self.options, **options))
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 1176, in apply
    args=(tasks.apply(args, kwargs).get(propagate=propagate),),
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 992, in apply
    sig.apply(**options) for sig, _ in tasks
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/canvas.py", line 719, in apply
    last and (last.get(),), **dict(self.options, **options))
  File "/Users/rino/.virtualenvs/celery4/lib/python2.7/site-packages/celery/result.py", line 902, in get
    raise self.result
TypeError: ident() takes exactly 1 argument (2 given)
```

**Comment by originell** [comment]
Seconding that. The following code works in celery3, but fails in celery4. Note that the traceback is slightly different from bruno-rino's one. The failcase here is using rabbitmq, redis and python 2.7

# Code

```python
# Simplified code, extracted from a more elaborate production code.
from __future__ import absolute_import, print_function
from copy import deepcopy
import json

from celery import Celery, group


app = Celery('tasks', backend='redis://localhost:6379/1', broker='amqp://guest:guest@localhost:5672//')
app.conf.CELERY_TASK_SERIALIZER = "json"
app.conf.CELERY_RESULT_SERIALIZER = 'json'
app.conf.CELERY_ACCEPT_CONTENT = ['json', ]


@app.task
def groupmap(args_iterable, task_signature):
    def _generate_funcs():
        sig_clone = deepcopy(task_signature)
        for arg in args_iterable:
            new_func = app.signature(sig_clone).clone(args=(arg,))
            yield new_func
    return group(_generate_funcs()).delay()


@app.task
def load_user_profiles():
    return [4, 5, 6, 7, 8]


@app.task
def load_links(user_id, **kwargs):
    return {'imgur': 'http://www.example.com/users/{}'.format(user_id),
            'facebook': 'http://www.example.com/users/{}'.format(user_id),
            'google': 'http://www.example.com/users/{}'.format(user_id), }


@app.task
def merge_links(links):
    d = links.copy()
    d['imgur'] = ''
    # Usually we'd write back into the DB now.
    return d


if __name__ == '__main__':
    result = (
        load_user_profiles.s() |
        groupmap.s(
            load_links.s() |
            merge_links.s()
        )
    ).delay()
```


# Celery 4

## Traceback

```
[2016-08-24 15:30:57,918: ERROR/PoolWorker-1] Task tasks.groupmap[7b80ccb4-204c-466e-9e95-9d4ec6b84fee] raised unexpected: AttributeError("'dict' object has no attribute 'clone'",)
Traceback (most recent call last):
  File "/Users/luis/.virtualenvs/celery_issue_3381/lib/python2.7/site-packages/celery/app/trace.py", line 358, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/luis/.virtualenvs/celery_issue_3381/lib/python2.7/site-packages/celery/app/trace.py", line 609, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/luis/Source/celery_issue_3381/tasks.py", line 22, in groupmap
    return group(_generate_funcs()).delay()
  File "/Users/luis/.virtualenvs/celery_issue_3381/lib/python2.7/site-packages/celery/canvas.py", line 194, in delay
    return self.apply_async(partial_args, partial_kwargs)
  File "/Users/luis/.virtualenvs/celery_issue_3381/lib/python2.7/site-packages/celery/canvas.py", line 796, in apply_async
    app = self.app
  File "/Users/luis/.virtualenvs/celery_issue_3381/lib/python2.7/site-packages/celery/canvas.py", line 904, in app
    app = self.tasks[0].app
  File "/Users/luis/.virtualenvs/celery_issue_3381/lib/python2.7/site-packages/celery/utils/functional.py", line 215, in __getitem__
    self.__consumed.append(next(self.__it))
  File "/Users/luis/Source/celery_issue_3381/tasks.py", line 20, in _generate_funcs
    new_func = app.signature(sig_clone).clone(args=(arg,))
  File "/Users/luis/.virtualenvs/celery_issue_3381/lib/python2.7/site-packages/celery/canvas.py", line 438, in clone
    s.kwargs['tasks'] = [sig.clone() for sig in s.kwargs['tasks']]
AttributeError: 'dict' object has no attribute 'clone'
```


## Report

```
$ celery -A tasks report

software -> celery:4.0.0rc3 (0today8) kombu:4.0.0rc3 py:2.7.10
            billiard:3.5.0.0 py-amqp:2.0.3
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/1

BROKER_URL: u'amqp://guest:********@localhost:5672//'
CELERY_ACCEPT_CONTENT: ['json']
CELERY_TASK_SERIALIZER: 'json'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_RESULT_BACKEND: u'redis://localhost:6379/1'
```


# Celery 3

## Result

As expected:

```
$ python tasks.py
```

` celery -A tasks worker -l info` output:

```
[2016-08-24 15:28:44,818: INFO/MainProcess] Task tasks.load_links[9d5a58c8-c5a7-4034-ba7e-4cd9b6ede6af] succeeded in 0.0374731990742s: {'imgur': 'http://www.example.com/users/4', 'google': 'http://www.example.com/users/4', 'facebook':...
[2016-08-24 15:28:44,819: INFO/MainProcess] Task tasks.load_links[bcbda51e-62d9-403e-86dc-058ec4fc04a1] succeeded in 0.0362445870414s: {'imgur': 'http://www.example.com/users/5', 'google': 'http://www.example.com/users/5', 'facebook':...
[2016-08-24 15:28:44,819: INFO/MainProcess] Task tasks.merge_links[06997a44-7a7b-4ce6-8dc9-5147f513420d] succeeded in 0.00241417996585s: {u'imgur': '', u'google': u'http://www.example.com/users/6', u'facebook': u'http://www.example.com/users/6'}
[2016-08-24 15:28:44,820: INFO/MainProcess] Task tasks.merge_links[05cca1b9-64da-4f9b-b3bd-fe353aa32b8a] succeeded in 0.000872449018061s: {u'imgur': '', u'google': u'http://www.example.com/users/5', u'facebook': u'http://www.example.com/users/5'}
[2016-08-24 15:28:44,820: INFO/MainProcess] Task tasks.merge_links[d527be5c-3d2d-42ee-b5fe-993270aac525] succeeded in 0.00266398803797s: {u'imgur': '', u'google': u'http://www.example.com/users/4', u'facebook': u'http://www.example.com/users/4'}
```


## Report

```
$ celery -A tasks report

software -> celery:3.1.23 (Cipater) kombu:3.0.35 py:2.7.10
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/1

CELERY_TASK_SERIALIZER: 'json'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_ACCEPT_CONTENT: ['json']
```

**Comment by mvaled** [comment]
I'm seeing a similar issue with 4.2.1:

```
Traceback (most recent call last):
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/app/trace.py", line 439, in trace_task
    parent_id=uuid, root_id=root_id,
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/canvas.py", line 1232, in apply_async
    return self.run(tasks, body, args, task_id=task_id, **options)
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/canvas.py", line 1277, in run
    header_result = header(*partial_args, task_id=group_id, **options)
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/canvas.py", line 953, in __call__
    return self.apply_async(partial_args, **options)
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/canvas.py", line 978, in apply_async
    args=args, kwargs=kwargs, **options))
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/canvas.py", line 1054, in _apply_tasks
    **options)
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/canvas.py", line 557, in apply_async
    dict(self.options, **options) if options else self.options))
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/canvas.py", line 573, in run
    task_id, group_id, chord,
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/canvas.py", line 683, in prepare_steps
    task.link_error(errback)
  File "/srv/mercurio/src/xhg/eggs/celery-4.2.1-py2.7.egg/celery/canvas.py", line 1016, in link_error
    sig = sig.clone().set(immutable=True)
AttributeError: 'dict' object has no attribute 'clone'
```

Should I open a new issue?

**Comment by mvaled** [comment]
I've just noticed this is a very old issue, so I'm opening a new one.
