### ISSUE TITLE
celery4 worker fails to start on Windows

### ISSUE THREAD

**Issue by AnkurDedania** [celery/celery#3383]
trying to execute https://github.com/celery/celery/blob/master/examples/app/myapp.py

λ python myapp.py worker

```
 -------------- celery@C001683697 v4.0.0rc3 (0today8)
---- **** -----
--- * ***  * -- Windows-7-6.1.7601-SP1 2016-08-10 16:12:28
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         myapp:0x26c8c88
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[2016-08-10 16:12:28,153: CRITICAL/MainProcess] Unrecoverable error: AttributeError("Can't pickle local object 'Pool.__init__.<locals>.Process'",)

Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\celery\worker\__init__.py", line 201, in start
    self.blueprint.start(self)
  File "C:\Miniconda3\lib\site-packages\celery\bootsteps.py", line 125, in start
    step.start(parent)
  File "C:\Miniconda3\lib\site-packages\celery\bootsteps.py", line 376, in start
    return self.obj.start()
  File "C:\Miniconda3\lib\site-packages\celery\concurrency\base.py", line 134, in start
    self.on_start()
  File "C:\Miniconda3\lib\site-packages\celery\concurrency\prefork.py", line 117, in on_start
    **self.options)
  File "C:\Miniconda3\lib\site-packages\billiard\pool.py", line 1015, in __init__
    self._create_worker_process(i)
  File "C:\Miniconda3\lib\site-packages\billiard\pool.py", line 1124, in _create_worker_process
    w.start()
  File "C:\Miniconda3\lib\site-packages\billiard\process.py", line 122, in start
    self._popen = self._Popen(self)
  File "C:\Miniconda3\lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
  File "C:\Miniconda3\lib\site-packages\billiard\popen_spawn_win32.py", line 72, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Miniconda3\lib\site-packages\billiard\reduction.py", line 97, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Pool.__init__.<locals>.Process'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Miniconda3\lib\site-packages\billiard\spawn.py", line 159, in spawn_main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "C:\Miniconda3\lib\site-packages\billiard\reduction.py", line 119, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```

**Comment by berkerpeksag** [comment]
Thanks for the report. According to http://docs.celeryproject.org/en/master/whatsnew-4.0.html#removed-features, Windows is no longer supported by Celery 4.0.

**Comment by zhangqunshi** [comment]
@berkerpeksag  why don't support the windows?

**Comment by katrinleinweber** [comment]
The above links is dead. http://docs.celeryproject.org/en/latest/history/whatsnew-4.0.html#removed-features is the new location.

**Comment by auvipy** [comment]
now support added. try 4.2.x

**Comment by sparrowt** [comment]
Although the pickling issue is fixed (presumably by https://github.com/celery/billiard/pull/225) I'm still seeing the 2nd error shown above:
```
WindowsError: [Error 87] The parameter is incorrect
```
on celery 4.2.1 when running celery worker with `--pool prefork` argument.

I know Windows is not technically supported but @auvipy your comment suggests that perhaps Windows support has returned in some form, is that correct? Does anyone know how to fix this issue with `_winapi.OpenProcess(_winapi.PROCESS_DUP_HANDLE, False, source_pid)` failing?

I've checked and just before failing `source_pid` is set to a valid non-zero `int` which appears to be the parent process ID, and `_winapi.PROCESS_DUP_HANDLE` = 64 as expected...
