### ISSUE TITLE
django + celery catch mysql  OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.171' (60)") error

### ISSUE THREAD

**Issue by mygoda** [celery/celery#3384]
hi all,  my project is use django + celery to do some tasks. one tasks is  always use so long time.  in this task they just do some db operation, some like db select; db save; db update. but some times i get this error

```
OperationalError(2003, "Can't connect to MySQL server on '172.16.0.171' (60)")
Traceback (most recent call last):
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/celery/app/trace.py", line 238, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/celery/app/trace.py", line 416, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/tao-xu/core_task/core/tasks.py", line 1139, in task_is_finish
    now_task = Task.objects.get(task_id=task_id)
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/models/query.py", line 301, in get
    num = len(clone)
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 710, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 780, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/backends/__init__.py", line 157, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/backends/__init__.py", line 129, in _cursor
    self.ensure_connection()
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/backends/__init__.py", line 124, in ensure_connection
    self.connect()
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/backends/__init__.py", line 124, in ensure_connection
    self.connect()
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/backends/__init__.py", line 112, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 435, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/Users/tao-xu/.virtualenvs/test_vcenter/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.171' (60)")`
```

  my question is can celery hold db connection pool, every worker only use active db connection; and how to solve this . thanks

**Comment by ask** [comment]
It's the same as in with any database using code: You have to retry in the event of connection failure.

Celery will attempt to close the connection after every task, but I'm not sure if you have enabled the new connection pooling features of Django.  If you reuse a database connection you will experience a connection error at some point.

**Comment by auvipy** [comment]
I thinks it's fixed on django-celery
