### ISSUE TITLE
Data truncated warning when submitting large no of commands through celery group

### ISSUE THREAD

**Issue by Rajlaxmi** [celery/celery#3387]
I am using celery group to submit commands through a file

```
grouped = group(tasks)
result = grouped.apply_async(retry=True, retry_policy={'max_retries' : 3}, link=callback)
```

I am using MySQL db as backend and rabbitmq as broker
Whenever I submit > ~1200 commands, I receive following error:

```
/apps/pythonenv/lib/python2.6/site-packages/sqlalchemy/engine/default.py:450: Warning: Data truncated for column 'result' at row 1
  cursor.execute(statement, parameters)
```

Through the commands are successfully submitted to rabbitmq server.
When I try to query results in DB, I get the error:

```
Traceback (most recent call last):
  File "./view_job_status.py", line 100, in <module>
    result = GroupResult.restore(group_id)
  File "/apps/pythonenv/lib/python2.6/site-packages/celery/result.py", line 806, in restore
    ).restore_group(id)
  File "/apps/pythonenv/lib/python2.6/site-packages/celery/backends/base.py", line 320, in restore_group
    meta = self.get_group_meta(group_id, cache=cache)
  File "/apps/pythonenv/lib/python2.6/site-packages/celery/backends/base.py", line 313, in get_group_meta
    meta = self._restore_group(group_id)
  File "/apps/pythonenv/lib/python2.6/site-packages/celery/backends/database/__init__.py", line 63, in _inner
    return fun(*args, **kwargs)
  File "/apps/pythonenv/lib/python2.6/site-packages/celery/backends/database/__init__.py", line 162, in _restore_group
    TaskSet.taskset_id == group_id).first()
  File "/apps/pythonenv/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/apps/pythonenv/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/apps/pythonenv/lib/python2.6/site-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File "/apps/pythonenv/lib/python2.6/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/apps/pythonenv/lib/python2.6/site-packages/sqlalchemy/orm/loading.py", line 71, in instances
    rows = [proc(row) for row in fetch]
  File "/apps/pythonenv/lib/python2.6/site-packages/sqlalchemy/orm/loading.py", line 428, in _instance
    loaded_instance, populate_existing, populators)
  File "/apps/pythonenv/lib/python2.6/site-packages/sqlalchemy/orm/loading.py", line 486, in _populate_full
    dict_[key] = getter(row)
  File "/apps/pythonenv/lib/python2.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1253, in process
    return loads(value)
EOFError

```

**Comment by auvipy** [comment]
which version of celery? adn you are using python 2.6?

**Comment by Rajlaxmi** [comment]
Celery version: 3.1.19 (Cipater)
Python version: 2.6.9

**Comment by Rajlaxmi** [comment]
Any updates on this?

**Comment by ask** [comment]
I'm not sure why this happening, but are you using chords?  A group chained to another task is also a chord.  If you're using chords I'd strongly suggest you use the Redis result backend as it performs much better.

**Comment by auvipy** [comment]
try latest releases and master branch and reopen if it still exist on master
