### ISSUE TITLE
test_retry_kwargs_can_be_empty fails on pypy3

### ISSUE THREAD

**Issue by berkerpeksag** [celery/celery#3391]
From https://travis-ci.org/celery/celery/jobs/151613800:

```
======================================================================
ERROR: test_retry_kwargs_can_be_empty (celery.tests.tasks.test_tasks.test_task_retries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/celery/celery/celery/tests/tasks/test_tasks.py", line 178, in test_retry_kwargs_can_be_empty
    self.retry_task_mockapply.retry(args=[4, 4], kwargs=None)
  File "/home/travis/build/celery/celery/celery/app/task.py", line 611, in retry
    raise_with_context(exc or Retry('Task can be retried', None))
  File "/home/travis/build/celery/celery/celery/utils/serialization.py", line 255, in raise_with_context
    _raise_with_context(exc, exc_info[1])
  File "<string>", line 1, in _raise_with_context
TypeError: exception causes must derive from BaseException, not NoneType
```

https://github.com/celery/celery/blob/5031d6f27862001d3e3bc5a2dacf1185c933f2c9/celery/tests/tasks/test_tasks.py#L169

**Comment by berkerpeksag** [comment]
It looks like the culprit is https://github.com/celery/celery/commit/32b52ca875509b84d786e33ce2d39f62ab7ea050. Since `raise Exception from None` is new in Python 3.3 and PyPy 3 supports Python 3.2, I think the `if PY3` clause needs to be updated to `if PY33`.
