### ISSUE TITLE
AttributeError: 'Process' object has no attribute 'dead'

### ISSUE THREAD

**Issue by codingjoe** [celery/celery#3395]
Celery seems to be accessing an attribute here, before it's been set. In other places `hasattr` is used to prevent this from happening, but not everywhere it seems.

e.g. https://github.com/celery/celery/blob/master/celery/concurrency/asynpool.py#L1103

```
ERROR    [2016-08-15 16:19:01,453] [none] celery.worker: Unrecoverable error: AttributeError("'Process' object has no attribute 'dead'",)
Traceback (most recent call last):
  File "python3.5/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "python3.5/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "python3.5/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "python3.5/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "python3.5/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "python3.5/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "python3.5/site-packages/celery/concurrency/asynpool.py", line 420, in _event_process_exit
    self.maintain_pool()
  File "python3.5/site-packages/billiard/pool.py", line 1315, in maintain_pool
    self._maintain_pool()
  File "python3.5/site-packages/billiard/pool.py", line 1306, in _maintain_pool
    joined = self._join_exited_workers()
  File "python3.5/site-packages/billiard/pool.py", line 1210, in _join_exited_workers
    self._process_cleanup_queues(worker)
  File "python3.5/site-packages/celery/concurrency/asynpool.py", line 1086, in _process_cleanup_queues
    if not proc.dead:
AttributeError: 'Process' object has no attribute 'dead'
```

**Comment by codingjoe** [comment]
So if anyone else has this issue, the problem is that I, and maybe you too, updated to an unsupported Billiard version.
https://github.com/celery/celery/blob/3.1/requirements/default.txt
