### ISSUE TITLE
Celery 3.1.23: Nested chord encountered INTERNAL ERROR when task in header raised exception

### ISSUE THREAD

**Issue by wshe1978** [celery/celery#3396]
Env:
- Python3.5
- Celery-3.1.23 (broker: RabbitMQ-3.6.1, result backend: Redis-3.2.0), ACK_LATE=True
- kombu-3.0.35

In the code below, task `ShortTask` (class-based implementation) simply raises an exception when the input argument `value` is 0. So in the following nested chord, the 2nd task in header of outer chord will raise an exception. In this case, the chord task will raise a RuntimeError. But when handling this exception, another exception (`TypeError: sequence item 1: expected a bytes-like object, NoneType found`) occurred, causing the chord task unable to send back acknowledgement. When I shut down the workers, the chord task gets requeued.

``` python
workflow = chord(
        header=[
            ShortTask().s(value=1),
            ShortTask().s(value=0)
        ],
        body=chord(
            header=[
                ShortTask().s(value=1),
                ShortTask().s(value=1)
            ],
            body=ShortTask().s(value=1)
        )
    )
workflow.apply_async()
```

The exception is as follows:

```
[2016-08-15 14:52:56,019: WARNING/Worker-16] short_task.tasks.short_task[81b37118-e284-4fa8-bdc8-dc3849fb8318]: Received task (sum: None, value: 1).
[2016-08-15 14:52:56,019: ERROR/MainProcess] Task short_task.tasks.short_task[dc5fd60f-b6c1-4051-9eec-33e93b19d095] raised unexpected: RuntimeError('Invalid value: 0',)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/weiapplatix/Documents/Work/projects/experiments/celery_experiments/short_task/tasks.py", line 19, in run
    raise RuntimeError('Invalid value: %s' % value)
RuntimeError: Invalid value: 0
[2016-08-15 14:52:59,020: WARNING/Worker-16] short_task.tasks.short_task[81b37118-e284-4fa8-bdc8-dc3849fb8318]: Result is 1
[2016-08-15 14:52:59,025: ERROR/Worker-16] Chord 'dd629dc4-afdd-4409-aeba-cea661ab8737' raised: "Dependency dc5fd60f-b6c1-4051-9eec-33e93b19d095 raised RuntimeError('Invalid value: 0',)"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 580, in on_chord_part_return
    ret = j(timeout=3.0, propagate=propagate)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/result.py", line 691, in join_native
    raise value
celery.backends.base.RuntimeError: Invalid value: 0
[2016-08-15 14:52:59,028: WARNING/Worker-16] /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: TypeError('sequence item 1: expected a bytes-like object, NoneType found',):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 580, in on_chord_part_return
    ret = j(timeout=3.0, propagate=propagate)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/result.py", line 691, in join_native
    raise value
celery.backends.base.RuntimeError: Invalid value: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/app/trace.py", line 296, in trace_task
    on_chord_part_return(task, state, R)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 591, in on_chord_part_return
    self.chord_error_from_stack(callback, ChordError(reason))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 148, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 155, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, ei.traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 133, in mark_as_failure
    traceback=traceback, request=request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 271, in store_result
    request=request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 505, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 425, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found

  exc, exc_info.traceback)))
[2016-08-15 14:52:59,029: CRITICAL/MainProcess] Task short_task.tasks.short_task[81b37118-e284-4fa8-bdc8-dc3849fb8318] INTERNAL ERROR: TypeError('sequence item 1: expected a bytes-like object, NoneType found',)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/app/trace.py", line 296, in trace_task
    on_chord_part_return(task, state, R)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 591, in on_chord_part_return
    self.chord_error_from_stack(callback, ChordError(reason))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 148, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 155, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, ei.traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 133, in mark_as_failure
    traceback=traceback, request=request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 271, in store_result
    request=request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 505, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/celery/backends/base.py", line 425, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found
```

**Comment by auvipy** [comment]
try master and report if it's still the issue

**Comment by fcornelius** [comment]
Did anyone find a solution for this? I have the exact same error on celery master.
If I raise an Exception inside a task of a chord, the following exceptions occur once this chord has finished. The next chord will not be executed.

`workflow = chain(
        chord(
            header=[
                task1.s(), # <- raises Exception
                task2.s()
            ],
            body=Task3().s(value=0)
        ),
        chord(
            header=[
                task4.s(),
                task5.s()
            ],
            body=task3.s()
        ),
    )
workflow.apply_async()`

Exceptions:

`[2018-03-13 00:52:08,902: ERROR/ForkPoolWorker-2] Chord callback for 'ca818991-2ea1-47d1-93d3-5ea69c1b2a67' raised: ChordError("Dependency 73acd925-a5cb-4667-a8c7-670f428c29c1 raised Exception('Sample Exception',)",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 296, in on_chord_part_return
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 296, in <listcomp>
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 251, in _unpack_chord_result
    raise ChordError('Dependency {0} raised {1!r}'.format(tid, retval))
celery.exceptions.ChordError: Dependency 73acd925-a5cb-4667-a8c7-670f428c29c1 raised Exception('Sample Exception',)
[2018-03-13 00:52:08,910: ERROR/ForkPoolWorker-2] Chord 'ca818991-2ea1-47d1-93d3-5ea69c1b2a67' raised: TypeError('sequence item 1: expected a bytes-like object, NoneType found',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 296, in on_chord_part_return
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 296, in <listcomp>
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 251, in _unpack_chord_result
    raise ChordError('Dependency {0} raised {1!r}'.format(tid, retval))
celery.exceptions.ChordError: Dependency 73acd925-a5cb-4667-a8c7-670f428c29c1 raised Exception('Sample Exception',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 302, in on_chord_part_return
    ChordError('Callback error: {0!r}'.format(exc)),
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 221, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 228, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, ei.traceback)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 156, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 317, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 661, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 567, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found
[2018-03-13 00:52:08,913: WARNING/ForkPoolWorker-2] /usr/local/lib/python3.6/site-packages/celery/app/trace.py:561: RuntimeWarning: Exception raised outside body: TypeError('sequence item 1: expected a bytes-like object, NoneType found',):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 296, in on_chord_part_return
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 296, in <listcomp>
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 251, in _unpack_chord_result
    raise ChordError('Dependency {0} raised {1!r}'.format(tid, retval))
celery.exceptions.ChordError: Dependency 73acd925-a5cb-4667-a8c7-670f428c29c1 raised Exception('Sample Exception',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 302, in on_chord_part_return
    ChordError('Callback error: {0!r}'.format(exc)),
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 221, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 228, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, ei.traceback)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 156, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 317, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 661, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 567, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 442, in trace_task
    uuid, retval, task_request, publish_result,
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 147, in mark_as_done
    self.on_chord_part_return(request, state, result)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 311, in on_chord_part_return
    ChordError('Join error: {0!r}'.format(exc)),
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 221, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 228, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, ei.traceback)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 156, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 317, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 661, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 567, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found

  exc, exc_info.traceback)))
[2018-03-13 00:52:08,914: ERROR/ForkPoolWorker-2] Task app.tasks.task7[d1d78e24-7232-4bfb-880e-e4e49ceddbbc] raised unexpected: TypeError('sequence item 1: expected a bytes-like object, NoneType found',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 296, in on_chord_part_return
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 296, in <listcomp>
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 251, in _unpack_chord_result
    raise ChordError('Dependency {0} raised {1!r}'.format(tid, retval))
celery.exceptions.ChordError: Dependency 73acd925-a5cb-4667-a8c7-670f428c29c1 raised Exception('Sample Exception',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 302, in on_chord_part_return
    ChordError('Callback error: {0!r}'.format(exc)),
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 221, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 228, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, ei.traceback)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 156, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 317, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 661, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 567, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 442, in trace_task
    uuid, retval, task_request, publish_result,
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 147, in mark_as_done
    self.on_chord_part_return(request, state, result)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 311, in on_chord_part_return
    ChordError('Join error: {0!r}'.format(exc)),
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 221, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 228, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, ei.traceback)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 156, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 317, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 661, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 567, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found`

**Comment by auvipy** [comment]
lets see after 4.2 release in next week

**Comment by alex-px** [comment]
Nothing changed after 4.2 release, exceptions are still here.
In @fcornelius 's example task2 will fail because of failure in task1

**Comment by auvipy** [comment]
thanks for reporting

**Comment by xirdneh** [comment]
Possibly related to #4834
