### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'on_soft_timeout' with celery 3.1.15

### ISSUE THREAD

**Issue by qlands** [celery/celery#3403]
Hi, 

Getting this error with Celery 3.1.15

[2016-08-19 08:29:51,896: ERROR/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'on_soft_timeout'",)
Traceback (most recent call last):
  File "/opt/formshare/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/opt/formshare/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/opt/formshare/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/opt/formshare/lib/python2.7/site-packages/celery/concurrency/base.py", line 131, in start
    self.on_start()
  File "/opt/formshare/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 117, in on_start
    **self.options)
  File "/opt/formshare/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 390, in __init__
    self.on_soft_timeout = self._timeout_handler.on_soft_timeout
AttributeError: 'NoneType' object has no attribute 'on_soft_timeout'

Might it be a conflict with RabbitMQ? I am using 3.6.2

**Comment by renjupaul** [comment]
I did have the same error. was using billard 3.5 that might have caused this error. changed to billiard==3.3.0.22. now it's working fine.

**Comment by qlands** [comment]
Yep. That was the problem. Thanks.

**Comment by Di-man-rnd** [comment]
Thanks.
