### ISSUE TITLE
4.0.x: Config not read if gevent.monkey.patch_all is enabled

### ISSUE THREAD

**Issue by miohtama** [celery/celery#3405]
Stack
- OSX
- Celery 4.0.0rc3
- Python 3.5

My application uses gevent for some async functionality. For this, I need to run in `gevent.monkey.patch_all()` in very early in the application startup. I need to do this also for Celery worker process, as tasks are using gevent-enabled functionlity.

However, now I run an interesting problem that Celery doesn't read any configuration if the monkey patch is enabled. I assume this has something to do with the boot order, though I am not sure what.

I also put a breakpoint in `read_configuration` in my custom loader. It is not called if monkey patch is enabled.

With `gevent.monkey.patch_all()`:

```
[2016-08-21 19:31:59,909: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2016-08-21 19:31:59,910: DEBUG/MainProcess] | Worker: Building graph...
[2016-08-21 19:31:59,911: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, StateDB, Beat, Consumer}
[2016-08-21 19:31:59,925: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2016-08-21 19:31:59,926: DEBUG/MainProcess] | Consumer: Building graph...
[2016-08-21 19:31:59,937: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Mingle, Gossip, Tasks, Control, Heart, event loop}

-------------- celery@Kohr-Ah.local v4.0.0rc3 (0today8)
---- **** ----- 
--- * ***  * -- Darwin-15.6.0-x86_64-i386-64bit 2016-08-21 19:31:59
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         default:0x1106e3390 (.default.Loader)
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
```

Without `gevent.monkey.patch_all()`:

```
19:34:08] [celery.bootsteps _debug] | Worker: Preparing bootsteps.
[19:34:08] [celery.bootsteps _debug] | Worker: Building graph...
[19:34:08] [celery.bootsteps _debug] | Worker: New boot order: {Beat, StateDB, Timer, Hub, Pool, Consumer}
[19:34:08] [celery.bootsteps _debug] | Consumer: Preparing bootsteps.
[19:34:08] [celery.bootsteps _debug] | Consumer: Building graph...
[19:34:08] [celery.bootsteps _debug] | Consumer: New boot order: {Connection, Agent, Events, Mingle, Tasks, Control, Heart, Gossip, event loop}

 -------------- celery@Kohr-Ah.local v4.0.0rc3 (0today8)
---- **** ----- 
--- * ***  * -- Darwin-15.6.0-x86_64-i386-64bit 2016-08-21 19:34:08
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         default:0x107d6c400 (websauna.system.task.celeryloader.WebsaunaLoader)
- ** ---------- .> transport:   redis://localhost:6379/3
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
```

**Comment by miohtama** [comment]
Further to clarify this happens with both `--pool=gevent` or manually calling `gevent.monkey.patch_all()`

**Comment by miohtama** [comment]
After poking around with command line switches it seems that `--loader` is ignored if `--pool` is given. 

In both cases settings from command line are still read.

**Comment by miohtama** [comment]
Looks like the issue is in `_state.py` and `_get_current_app` that only checks `CELERY_LOADER` environment variable, but not command line.

**Comment by miohtama** [comment]
However, to test the waters, looks like after all forcing of monkey patching and picking up the loader Celery won't run nicely with gevent:

    [20:09:07] [celery.worker start] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'push'",)
    Traceback (most recent call last):
      File "/Users/mikko/code/xxx/venv/lib/python3.5/site-packages/celery/worker/__init__.py", line 201, in start
        self.blueprint.start(self)
      File "/Users/mikko/code/xxx/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 125, in start
        step.start(parent)
      File "/Users/mikko/code/xxx/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 376, in start
        return self.obj.start()
      File "/Users/mikko/code/xxx/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 315, in start
        blueprint.start(self)
      File "/Users/mikko/code/xxx/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 125, in start
        step.start(parent)
      File "/Users/mikko/code/xxx/venv/lib/python3.5/site-packages/celery/worker/consumer/tasks.py", line 23, in start
        c.update_strategies()
      File "/Users/mikko/code/xxx/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 520, in update_strategies
        app=self.app)
      File "/Users/mikko/code/xxx/venv/lib/python3.5/site-packages/celery/app/trace.py", line 295, in build_tracer
        push_request = request_stack.push
    AttributeError: 'NoneType' object has no attribute 'push'

**Comment by ask** [comment]
Are you using the `--loader` argument?  It's kind of an outdated concept at this point since you can just subclass an app.  We only have the argument for compatibility with older apps, but afair once you use the `-A` argument it's ignored.

I'm using gevent and eventlet in testing here, and it reads my configuration fine, but not using a custom loader.

**Comment by miohtama** [comment]
@ask Yes that was the case. A custom loader + `--loader` doesn't work. A custom loader + environment variable works.

**Comment by miohtama** [comment]
I think the solution here would be document with an code example how to deploy custom applications and config loaders and deprecate old methods.

**Comment by ask** [comment]
Oh, the loaders are still used, it's just that applications are much more flexible and it seems rather
redundant to have to specify two paths on the command-line: `-A proj:app --loader=proj:Loader`.

So if you specify -A, the --loader argument is ignored, but I just changed it so it always respects both arguments.

You can specify the loader for an app:

```
class Celery(celery.Celery):
    loader_cls = MyLoader
```

MyLoader here can be a class, or the path to a class.

You can also specify it as an argument:

```py
app = Celery(loader=MyLoader)
```

**Comment by auvipy** [comment]
report again if it exist after new release
