### ISSUE TITLE
celery beat stops sending tasks after network failure

### ISSUE THREAD

**Issue by mbattifarano** [celery/celery#3409]
# Celery beat stops sending tasks after failed hostname lookup

We are running celery beat as a standalone processes with a scheduled "heartbeat" task every minute. After 24 to 30 hours of uptime celery will attempt to send a "heartbeat" but fail with `Message Error: Couldn't apply scheduled task ping: Error opening socket: hostname lookup failed` (traceback below). After this failure it will attempt to send one more task. That task never reaches the queue and no subsequent scheduled tasks are sent. The beat process itself remains alive indefinitely so this failure requires a manual restart of celery beat.
## Stack:

python 2.7.10
celery 3.1.19
kombu 3.0.35
librabbitmq 1.6.1

rabbitmq 3.6

containerized Ubuntu 16.04 running on AWS using ECS
### python logs and traceback:

```
[2016-08-24 09:44:32,420: INFO/MainProcess] Scheduler: Sending due task ping (ping_task)

Message Error: Couldn't apply scheduled task ping: Error opening socket: hostname lookup failed
File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
    main()
File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 762, in handle_argv
    return self.execute(command, argv)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 694, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 315, in run_from_argv
    sys.argv if argv is None else argv, command)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 377, in handle_argv
    return self(*args, **options)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/beat.py", line 79, in run
    return beat().run()
File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 83, in run
    self.start_scheduler()
File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 112, in start_scheduler
    beat.start()
File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 473, in start
File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 221, in tick

Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 204, in maybe_due
    result = self.apply_async(entry, publisher=publisher)
File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 260, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 252, in apply_async
    **entry.options)
File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 560, in apply_async
    **dict(self._get_exec_options(), **options)
File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
File "/usr/local/lib/python2.7/dist-packages/celery/app/amqp.py", line 305, in publish_task
File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 237, in connect
    return self.connection
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
File "/usr/local/lib/python2.7/dist-packages/kombu/transport/librabbitmq.py", line 123, in establish_connection
    conn = self.Connection(**opts)
File "/usr/local/lib/python2.7/dist-packages/librabbitmq/__init__.py", line 199, in __init__
    self.connect()
SchedulingError: Couldn't apply scheduled task ping: Error opening socket: hostname lookup failed

[2016-08-24 09:43:32,385: DEBUG/MainProcess] beat: Waking up in 59.99 seconds.
[2016-08-24 09:44:32,420: INFO/MainProcess] Scheduler: Sending due task ping (dynamic_dropoff.celery.tasks.ping_task)
```

The last line of this excerpt is the last thing celery beat logs. The task is trying to send never makes it to the queue. (see related [SO](http://stackoverflow.com/questions/38444382/celery-beat-process-crashes-after-nslookup-failure) post) The celery beat process itself does not exit. It continues to consume memory and if left for long enough it is eventually killed when it hits the container hard memory limit.
### `strace -p` (after failure):

```
...
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=108, ...}) = 0
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = -1 EMFILE (Too many open files)
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=108, ...}) = 0
socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = -1 EMFILE (Too many open files)
socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = -1 EMFILE (Too many open files)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 0})     = 0 (Timeout)
brk(0x702ef000)                         = 0x702ef000
...
```

These 9 lines continued to repeat for the several minutes we observed the output.
## Interventions:

At first glance, it looked somewhat similar to a bug reported with the uuid daemon in #1822. This seemed an unlikely cause as it was already a year or so old, on an older version of ubuntu, and failed much more quickly than ours, but we discovered that `uuidd` wasn't even installed on the system running celery so we implemented the fix as described in the [comments](https://github.com/celery/celery/pull/1822#issuecomment-33430437) but continued to experience the issue.

Let me know if there are other details or diagnostic information I can provide. 

Thanks,
Matt

**Comment by ask** [comment]
Setting `BROKER_POOL_LIMIT=0` in the beat process could make this much less likely to happen.  You can use the beat_init signal to set the configuration only for beat: http://docs.celeryproject.org/en/latest/userguide/signals.html#beat-init

Another solution would be to use RabbitMQ publisher acknowledgments, using `BROKER_TRANSPORT_OPTIONS={'confirm_publish': True}`

**Comment by ask** [comment]
Note: You would have to use pyamqp:// for publisher requirements

**Comment by mbattifarano** [comment]
Thanks for the reply. We'll implement your suggestions and update this thread with our results.

**Comment by mbattifarano** [comment]
Some updates. 

First, our initial broker configuration:

```
BROKER_URL = 'librabbitmq://[...]'
BROKER_TRANSPORT_OPTIONS = {'confirm_publish': True}
BROKER_POOL_LIMIT = None
```

From your reply it seems like the transport options would have had no effect since we were using the  librabbitmq transport. According to the docs, `BROKER_POOL_LIMIT = None` is equivalent to `BROKER_POOL_LIMIT = 0`.

I implemented your suggestions as four different configurations all using the `pyamqp` transport:

1. confirm publish = True, pool limit = 0
2. confirm publish = True, pool limit = 10
3. confirm publish = False, pool limit = 0
4. confirm publish = False, pool limit = 10

For each test I started celery beat with:
`celery beat --app=project.app:app --loglevel DEBUG --logfile ex_1.log `

The results were the same across all four experiments: exactly two "ping" tasks were sent according to schedule and then no further tasks were sent. 

log output:

```
[2016-08-31 14:20:07,460: DEBUG/MainProcess] Setting default socket timeout to 30
[2016-08-31 14:20:07,460: INFO/MainProcess] beat: Starting...
[2016-08-31 14:20:07,481: DEBUG/MainProcess] Current schedule:
<Entry: ping tasks.ping_task() <freq: 1.00 minute>
[2016-08-31 14:20:07,481: DEBUG/MainProcess] beat: Ticking with max interval->5.00 minutes
[2016-08-31 14:20:07,493: DEBUG/MainProcess] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2016 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@******.ec2.internal', u'platform': u'Erlang/OTP', u'version': u'3.6.3'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[2016-08-31 14:20:07,497: DEBUG/MainProcess] Open OK!
[2016-08-31 14:20:07,497: INFO/MainProcess] Scheduler: Sending due task ping (tasks.ping_task)
[2016-08-31 14:20:07,498: DEBUG/MainProcess] using channel_id: 1
[2016-08-31 14:20:07,500: DEBUG/MainProcess] Channel open
[2016-08-31 14:20:07,516: DEBUG/MainProcess] beat: Synchronizing schedule...
[2016-08-31 14:20:07,518: DEBUG/MainProcess] tasks.ping_task sent. id->55ec74c7-d0e9-4469-bf06-f5d3ff2743af
[2016-08-31 14:20:07,519: DEBUG/MainProcess] beat: Waking up in 59.99 seconds.
[2016-08-31 14:21:07,568: INFO/MainProcess] Scheduler: Sending due task ping (tasks.ping_task)
[2016-08-31 14:21:07,578: DEBUG/MainProcess] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2016 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@******.ec2.internal', u'platform': u'Erlang/OTP', u'version': u'3.6.3'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[2016-08-31 14:21:07,581: DEBUG/MainProcess] Open OK!
[2016-08-31 14:21:07,581: DEBUG/MainProcess] using channel_id: 1
[2016-08-31 14:21:07,583: DEBUG/MainProcess] Channel open
[2016-08-31 14:21:07,593: DEBUG/MainProcess] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2016 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@******.ec2.internal', u'platform': u'Erlang/OTP', u'version': u'3.6.3'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[2016-08-31 14:21:07,597: DEBUG/MainProcess] Open OK!
[2016-08-31 14:21:07,597: DEBUG/MainProcess] using channel_id: 1
[2016-08-31 14:21:07,599: DEBUG/MainProcess] Channel open
[2016-08-31 14:21:07,609: DEBUG/MainProcess] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2016 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@******.ec2.internal', u'platform': u'Erlang/OTP', u'version': u'3.6.3'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[2016-08-31 14:21:07,613: DEBUG/MainProcess] Open OK!
[2016-08-31 14:21:07,613: DEBUG/MainProcess] using channel_id: 1
[2016-08-31 14:21:07,615: DEBUG/MainProcess] Channel open
[same debug statements repeat ad infinitum]
```

The logs for each of the four experiments showed the same repeating debug statements. One thing I noticed is that despite changing the `BROKER_TRANSPORT_OPTIONS` dict, the `Start from server` log statement shows `'publisher_confirms': True` in its properties dict. Im not sure if these two concepts are related, but it looked suspicious to me.

Im in the process of running tests with the value of `BROKER_POOL_LIMIT` using the `librabbitmq` transport, and will update here with results.

**Comment by Phantazm** [comment]
I have the same problem. If connection to rabbit is lost the worker reconnects but the beat doesn't.

**Comment by ivanpricewaycom** [comment]
+1, we're seeing this too. difficult to understand how anyone is running beat in production if it is this fragile to a temporary disconnection from the broker ? we're gonna default back to cron or similar.

**Comment by MrJohnsson77** [comment]
@ivanpricewaycom i think it's related to the amqp library.
I could reproduce the problems by just restarting the RabbitMQ server and the Beat didn't reconnect.
It does however work as expected when using redis as backend.

I haven't had time to look into it so i solved my problem with using redis as a backend instead.

**Comment by ivanpricewaycom** [comment]
gday MrJohnsson77
yep it's highly possible, our problem was that we already have rabbit for other stuff, i don't love the idea of running both just for this reason, and a cron poll is an easy fix in our case so no worries.

-i

**Comment by FrankHitman** [comment]
+1
` BROKER_URL = 'amqp://guest:password@localhost:5672//'`
`CELERY_RESULT_BACKEND = 'rpc://' `
`CELERY_RESULT_PERSISTENT = False`
`CELERYBEAT_SCHEDULE = {
        'recycle':{
            'task': 'recycle.tasks.auto_release',
            'schedule': timedelta(seconds=5),
            'args': ()
        },
 `

when setting  like above  and restart rabbitmq-server,  beat will build many connection to rabbitmq, but workers don't receive task from beat. but my project cannot allowed to  change celery_result_backend to redis or memcached. anybody has some solutions?

**Comment by auvipy** [comment]
check the issue with latest release or master branch and report again

**Comment by korycins** [comment]
Does anyone have a solution for that? 
I am having the same issue with celery==4.1.0 and rabbitmq == 3.5.7

**Comment by renzop** [comment]
I ran into the same problem with celery==4.2 and rabbitmq==3.6
When I delete the clerybeat-schedule file, beat works fine again... So deleting that file in a cron job. could be a dirty fix
