### ISSUE TITLE
geventDrainer doesn't start() ResultConsumer

### ISSUE THREAD

**Issue by mojodna** [celery/celery#3452]
With `celery==4.0.0rc4` and `gunicorn` serving up a WSGI app using `gevent` workers, event draining emits the following exception (I'm treating it as a warning since it doesn't cause problems):

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/async.py", line 78, in run
    self.result_consumer.drain_events(timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 73, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get_message'
<Greenlet at 0x7f5e477da4b0: <bound method geventDrainer.run of <celery.backends.async.geventDrainer object at 0x7f5e47859ed0>>> failed with AttributeError
```

The root cause appears to be [`ResultConsumer.drain_events`](https://github.com/celery/celery/blob/master/celery/backends/redis.py#L72) either not checking for a valid `_pubsub` attribute or having not been started somewhere.

**Comment by ask** [comment]
Are you using the latest git master, or the dev version on PyPI?

**Comment by mojodna** [comment]
`4.0.0rc4` from PyPI, installed via `pip`.

**Comment by ask** [comment]
Try using 4.0rc5 on pip now, it should be fixed!

**Comment by mojodna** [comment]
Fantastic!

**Comment by mojodna** [comment]
It's baack. This is from rc5:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/async.py", line 83, in run
    self.result_consumer.drain_events(timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 69, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get_message'
<Greenlet at 0x7efd9d8ba550: <bound method geventDrainer.run of <celery.backends.async.geventDrainer object at 0x7efd9d99f550>>> failed with AttributeError
```

**Comment by khj809** [comment]
same problem occurred in 4.0.2

**Comment by psrok1** [comment]
Also have problems with 4.0.2:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/async.py", line 83, in run
    self.result_consumer.drain_events(timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 69, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get_message'
Thu Jun 22 19:46:28 2017 <Greenlet at 0x7f9f36b7b050: <bound method geventDrainer.run of <celery.backends.async.geventDrainer object at 0x7f9f36f32510>>> failed with AttributeError
```

**Comment by janaaronlee** [comment]
Issue is visible in 4.1.0:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/async.py", line 83, in run
    self.result_consumer.drain_events(timeout=1)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 69, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get_message'
Tue Sep 19 00:19:22 2017 <Greenlet at 0x7f771fffda60: <bound method greenletDrainer.run of <celery.backends.async.geventDrainer object at 0x7f771ffc8f28>>> failed with AttributeError
```

**Comment by StolerHua** [comment]
isuue also occurs 
window10 

Python 3.6.4
celery==4.1.0
gevent==1.2.2
kombu==4.1.0
redis==2.10.6

Traceback (most recent call last):
  File "c:\users\11876\anaconda3\envs\pythontools\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "c:\users\11876\anaconda3\envs\pythontools\lib\site-packages\celery\backends\async.py", line 83, in run
    self.result_consumer.drain_events(timeout=1)
  File "c:\users\11876\anaconda3\envs\pythontools\lib\site-packages\celery\backends\redis.py", line 69, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get_message'

**Comment by ipingtw** [comment]
same problem occurs with 4.2.1
