### ISSUE TITLE
ImportError: cannot import name maybe_sanitize_url

### ISSUE THREAD

**Issue by RuslanLomov** [celery/celery#3473]
What i installed on my cluster:
`airflow celery`, `python-kombu`, `python-billiard`, `python 2.7`
when I'm starting `celery help` command :
```
root@cluster1:~# celery help
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 29, in main
    from celery.bin.celery import main
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/__init__.py", line 3, in <module>
    from .base import Option
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 86, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency
  File "/usr/local/lib/python2.7/dist-packages/celery/five.py", line 306, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python2.7/dist-packages/celery/app/__init__.py", line 22, in <module>
    from .base import Celery, AppPickler
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 43, in <module>
    from .utils import (
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 18, in <module>
    from kombu.utils.url import maybe_sanitize_url
ImportError: cannot import name maybe_sanitize_url
```
What kind of problem is that?

**Comment by ask** [comment]
What versions of celery and kombu?

**Comment by RuslanLomov** [comment]
last versions

**Comment by auvipy** [comment]
python-kombu, python-billiard tells that you used os packages to install them. could you try to install them using pip? and then check if everything works fine.

**Comment by RuslanLomov** [comment]
```
root@cluster1:~# pip install kombu
Requirement already satisfied (use --upgrade to upgrade): kombu in /usr/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): anyjson>=0.3.3 in /usr/lib/python2.7/dist-packages (from kombu)
Requirement already satisfied (use --upgrade to upgrade): amqp<2.0,>=1.3.3 in /usr/local/lib/python2.7/dist-packages (from kombu)
Cleaning up...

```

**Comment by auvipy** [comment]
try pip install -U kombu

**Comment by RuslanLomov** [comment]
thnks,it works fine after update!

**Comment by auvipy** [comment]
offer me a big mac burger ;) @RuslanLomov
