### ISSUE TITLE
Unrecoverable Error on Beat Start

### ISSUE THREAD

**Issue by lawrencemq** [celery/celery#3476]
Using Python 3.5, Django 1.10, and Celery 3.1.23.

Can reproduce in multiple environments and locally on dev machine.  
From debug logs, it seems the Beat causes a fatal error and crashes Celery:

`
celery -B -A app worker -l DEBUG

[2016-09-27 02:42:31,055: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2016-09-27 02:42:31,064: DEBUG/MainProcess] | Worker: Building graph...
[2016-09-27 02:42:31,065: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Queues (intra), Pool, Autoscaler, StateDB, Beat, Autoreloader, Consumer}
[2016-09-27 02:42:31,096: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2016-09-27 02:42:31,096: DEBUG/MainProcess] | Consumer: Building graph...
[2016-09-27 02:42:31,128: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Tasks, Control, Agent, Gossip, Heart, event loop}

 -------------- celery@.... v3.1.23 (Cipater)
---- ***\* -----
--- \* **\*  \* -- Linux-3.13.0-95-generic-x86_64-with-debian-jessie-sid
-- \* - ***\* ---
- *\* ---------- [config]
- *\* ---------- .> app:         .....
- *\* ---------- .> transport:   redis://.....
- *\* ---------- .> results:     redis://.....
- **\* --- \* --- .> concurrency: 8 (prefork)
  -- ******\* ----
  --- ****\* ----- [queues]
  -------------- .> celery           exchange=celery(direct) key=celery

[tasks]
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
.......

[2016-09-27 02:42:31,148: DEBUG/MainProcess] | Worker: Starting Hub
[2016-09-27 02:42:31,149: DEBUG/MainProcess] ^-- substep ok
[2016-09-27 02:42:31,149: DEBUG/MainProcess] | Worker: Starting Pool
[2016-09-27 02:42:31,527: DEBUG/MainProcess] ^-- substep ok
[2016-09-27 02:42:31,527: DEBUG/MainProcess] | Worker: Starting Beat
[2016-09-27 02:42:31,528: ERROR/MainProcess] Unrecoverable error: TypeError('_Popen() takes 1 positional argument but 2 were given',)
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/app/.heroku/python/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/app/.heroku/python/lib/python3.5/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/app/.heroku/python/lib/python3.5/site-packages/billiard/process.py", line 122, in start
    self._popen = self._Popen(self)
TypeError: _Popen() takes 1 positional argument but 2 were given
[2016-09-27 02:42:31,531: DEBUG/MainProcess] removing tasks from inqueue until task handler finished`

**Comment by georgepsarakis** [comment]
@lawrencemq did you manage to find a solution to this?

**Comment by atkawa7** [comment]
@georgepsarakis @georgepsarakis  I am having the same problems

**Comment by auvipy** [comment]
we decided not to support 3.1 branch anymore. try the latest branch and reopen if it still exist.
