### ISSUE TITLE
Attempting to use AMQP when SQS is configured?

### ISSUE THREAD

**Issue by astronouth7303** [celery/celery#3486]
Using Celery 4.0.0rc4, I'm getting the following error in my logs:

```
2016-09-30 11:06:20,725 health_check_celery3.plugin_health_check    ERROR   Unknown Error
Traceback (most recent call last):
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/utils/functional.py", line 35, in __call__
return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 488, in _ensured
return fun(*args, **kwargs)
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/messaging.py", line 182, in _publish
channel = self.channel
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/messaging.py", line 204, in _get_channel
channel = self._channel = channel()
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/utils/functional.py", line 37, in __call__
value = self.__value__ = self.__contract__()
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/messaging.py", line 219, in <lambda>
channel = ChannelPromise(lambda: connection.default_channel)
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 814, in default_channel
self.connection
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 798, in connection
self._connection = self._establish_connection()
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 751, in _establish_connection
conn = self.transport.establish_connection()
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 119, in establish_connection
conn.connect()
File "/opt/python/run/venv/lib/python3.4/site-packages/amqp/connection.py", line 272, in connect
self.transport.connect()
File "/opt/python/run/venv/lib/python3.4/site-packages/amqp/transport.py", line 100, in connect
self._connect(self.host, self.port, self.connect_timeout)
File "/opt/python/run/venv/lib/python3.4/site-packages/amqp/transport.py", line 141, in _connect
self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 409, in _reraise_as_library_errors
yield
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 509, in _ensured
reraise_as_library_errors=False,
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 400, in ensure_connection
callback)
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/utils/functional.py", line 329, in retry_over_time
return fun(*args, **kwargs)
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 258, in connect
return self.connection
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 798, in connection
self._connection = self._establish_connection()
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 751, in _establish_connection
conn = self.transport.establish_connection()
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 119, in establish_connection
conn.connect()
File "/opt/python/run/venv/lib/python3.4/site-packages/amqp/connection.py", line 272, in connect
self.transport.connect()
File "/opt/python/run/venv/lib/python3.4/site-packages/amqp/transport.py", line 100, in connect
self._connect(self.host, self.port, self.connect_timeout)
File "/opt/python/run/venv/lib/python3.4/site-packages/amqp/transport.py", line 141, in _connect
self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/python/run/venv/src/django-health-check/health_check_celery3/plugin_health_check.py", line 24, in check_status
expires=datetime.now() + timedelta(seconds=timeout)
File "/opt/python/run/venv/lib/python3.4/site-packages/celery/app/task.py", line 510, in apply_async
**options
File "/opt/python/run/venv/lib/python3.4/site-packages/celery/app/base.py", line 665, in send_task
amqp.send_task_message(P, name, message, **options)
File "/opt/python/run/venv/lib/python3.4/site-packages/celery/app/amqp.py", line 547, in send_task_message
**properties
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/messaging.py", line 176, in publish
exchange_name, declare,
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 522, in _ensured
errback and errback(exc, 0)
File "/usr/lib64/python3.4/contextlib.py", line 77, in __exit__
self.gen.throw(type, value, traceback)
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
sys.exc_info()[2])
File "/opt/python/run/venv/lib/python3.4/site-packages/vine/five.py", line 172, in reraise
raise value.with_traceback(tb)
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 409, in _reraise_as_library_errors
yield
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 509, in _ensured
reraise_as_library_errors=False,
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 400, in ensure_connection
callback)
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/utils/functional.py", line 329, in retry_over_time
return fun(*args, **kwargs)
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 258, in connect
return self.connection
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 798, in connection
self._connection = self._establish_connection()
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/connection.py", line 751, in _establish_connection
conn = self.transport.establish_connection()
File "/opt/python/run/venv/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 119, in establish_connection
conn.connect()
File "/opt/python/run/venv/lib/python3.4/site-packages/amqp/connection.py", line 272, in connect
self.transport.connect()
File "/opt/python/run/venv/lib/python3.4/site-packages/amqp/transport.py", line 100, in connect
self._connect(self.host, self.port, self.connect_timeout)
File "/opt/python/run/venv/lib/python3.4/site-packages/amqp/transport.py", line 141, in _connect
self.sock.connect(sa)
kombu.exceptions.OperationalError: [Errno 111] Connection refused
```

But I'm configuring celery to use SQS:

``` python
CELERY_RESULT_BACKEND = 'django-cache'
CELERY_BROKER_URL = 'sqs://'
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'queue_name_prefix': os.environ.get('AWS_STACK_NAME', 'inno') + '-',
    'polling_interval': 20,
}
```

I'm using a relatively standard `celery.py` file:

``` python
import os
import logging
from celery import Celery

# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'innocence.settings')

# We do this to initialize Django (in theory...)
from django.conf import settings

logging.getLogger(__name__).info("broker", settings.CELERY_BROKER_URL)

app = Celery('innocence')

# Using a string here means the worker doesn't have to serialize
# the configuration object.
app.config_from_object('django.conf:settings', namespace='CELERY')

logging.getLogger(__name__).info("settings", app.conf)

# load task modules from all registered Django app configs.
app.autodiscover_tasks()

@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```

(This is on my webserver, so it's being started through django by `mod_wsgi`, not by the `celery` tool.)

However, I am _not_ seeing those logging statements.

I am importing the celery file in the `__init__.py`:

``` python
from .celery import app as celery_app

__all__ = 'celery_app',
```

It does sometimes decide to work, but only a minority of the time.

**Comment by astronouth7303** [comment]
Hm, I'm also getting this error:

```
celery.utils.dispatch.signal	ERROR	Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f7ae51bb7b8>> raised: ImportError("No module named 'django.core.management.validation'",)
Traceback (most recent call last):
File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/utils/dispatch/signal.py", line 170, in send
response = receiver(signal=self, sender=sender, **named)
File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/fixups/django.py", line 82, in on_import_modules
self.worker_fixup.validate_models()
File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/fixups/django.py", line 124, in validate_models
from django.core.management.validation import get_validation_errors
ImportError: No module named 'django.core.management.validation'
```

Not sure if it's related.

**Comment by astronouth7303** [comment]
It was my `celery.py`. You must not refer to django settings within it.

**Comment by astronouth7303** [comment]
So that was a little premature. The issue only appears intermittently now.
