### ISSUE TITLE
exception in task failure signal handler can leave tasks un-acked

### ISSUE THREAD

**Issue by chrono** [celery/celery#3488]
We're running `3.1.18` with `acks_late` and rabbit backend. When a custom `task_failure` signal handler (like the one by `raven-python`) throws an exception, the task will remain an un-acked zombie on that worker/rabbit-consumer forever.

This could perhaps lead to other issues, like maintenance of QoS for task prefetch being incorrect.

The specific bug below has probably been fixed in `raven==5.17.0` but this class of error should not get tasks stuck like this.

We noticed this since we run separate vhosts for each version deployed and shut down old workers several hours after they have been replaced with a newer deployment. That caused the unacked tasks go back into `ready` state. At this point no task should have been left in that vhost.

After inspecting logs of the celery events firehose we identified that all such tasks ran into `task-failed` with the exception shown below.

```
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/celery/app/trace.py", line 125, in handle_failure
    einfo=einfo)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/raven/contrib/celery/__init__.py", line 34, in process_failure_signal
    'kwargs': kwargs,
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/raven/base.py", line 766, in captureException
    'raven.events.Exception', exc_info=exc_info, **kwargs)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 271, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/raven/base.py", line 595, in capture
    **kwargs)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 212, in build_msg
    data = super(DjangoClient, self).build_msg(*args, **kwargs)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/raven/base.py", line 463, in build_msg
    crumbs = self.context.breadcrumbs.get_buffer()
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 42, in get_buffer
    processor(payload)
  File "/home/ubuntu/virtualenvs/app_foo/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 72, in processor
    formatted_msg = msg % args
TypeError: format requires a mapping
```

**Comment by ask** [comment]
This has been changed for 4.0, where errors occurring in signals no longer propagate and are logged instead.
