### ISSUE TITLE
Celery CLI is broken (version 4.0.0rc4)

### ISSUE THREAD

**Issue by galuszkak** [celery/celery#3495]
Now in RC4 version I can't inspect celery status/active_queues etc. actually all celery cli commands doesn't work at all.

```
celery status --app=app.celery.app
Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/__main__.py", line 15, in main
    main()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 333, in main
    cmd.execute_from_commandline(argv)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 1154, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/base.py", line 239, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 1146, in handle_argv
    return self.execute(command, argv)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 1078, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/base.py", line 243, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/base.py", line 309, in handle_argv
    return self(*args, **options)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/base.py", line 202, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 760, in run
    replies = I.run('ping', **kwargs)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 605, in run
    return self.do_call_method(args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 636, in do_call_method
    callback=None if json else self.say_remote_command_reply,
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 719, in call
    method, **arguments)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/app/control.py", line 71, in _request
    timeout=self.timeout, reply=True,
  File "/home/ubuntu/venv/lib/python3.5/site-packages/celery/app/control.py", line 330, in broadcast
    limit, callback, channel=channel,
  File "/home/ubuntu/venv/lib/python3.5/site-packages/kombu/pidbox.py", line 294, in _broadcast
    chan = channel or self.connection.default_channel
  File "/home/ubuntu/venv/lib/python3.5/site-packages/kombu/connection.py", line 814, in default_channel
    self.connection
  File "/home/ubuntu/venv/lib/python3.5/site-packages/kombu/connection.py", line 798, in connection
    self._connection = self._establish_connection()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/kombu/connection.py", line 751, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 119, in establish_connection
    conn.connect()
AttributeError: 'Connection' object has no attribute 'connect'
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
(venv) ubuntu@ip-172-31-0-132:~/release$ celery --version
4.0.0rc4 (0today8)```

**Comment by galuszkak** [comment]
Worth to note, we are using py-amqp from master branch as fix with messages wasn't released yet.

**Comment by ask** [comment]
It seems to me you are not using py-amqp from master, as Connection.connect() is new in py-amqp 2.0?

**Comment by galuszkak** [comment]
@ask this is what we have in requirements.txt on deploy:
```
-e git+https://github.com/celery/py-amqp#egg=amqp
```
I'm pretty sure, because we need version from master as some tasks were missing because short message bug.
I can do pip freeze if you want or check whatever you want else. 👍

**Comment by galuszkak** [comment]
Hm You were right. But I don't know why this is happening.

```
(venv) ubuntu@ip-172-31-0-132:~$ pip install -e git+https://github.com/celery/py-amqp#egg=amqp
Obtaining amqp from git+https://github.com/celery/py-amqp#egg=amqp
  Updating ./venv/src/amqp clone
Requirement already satisfied (use --upgrade to upgrade): vine>=1.1.2 in ./venv/lib/python3.5/site-packages (from amqp)
Installing collected packages: amqp
  Running setup.py develop for amqp
Successfully installed amqp-1.4.9
```

**Comment by galuszkak** [comment]
I'm installing straight from repository and it's installing 1.4.9 that's pretty weird.

**Comment by galuszkak** [comment]
OK This was on my side. Sorry for trouble. I think pip sometimes goes like crazy.
