### ISSUE TITLE
How to use pymysql for CELERY_RESULT_BACKEND

### ISSUE THREAD

**Issue by heramerom** [celery/celery#3503]
I config 
```
CELERY_RESULT_BACKEND = 'db+mysql://....'
```
but got error.
```
No module named 'MySQLdb'
```
I use Python3. The Google said that *MySQLdb* not support Python3. I want use *pymysql*,
but how can I config it?
Thanks!

**Comment by ask** [comment]
I don't know,  but how do you use pymysql with SQLAlchemy? The answer to that will probably be relevant.

**Comment by heramerom** [comment]
Thank you!
I just want to use mysql for CELERY_RESULT_BACKEND. but the official demo is `db+mysql://`. I Google it but found nothing.
and how to use SQLALchemy?
Sorry, I'm a newbie.

**Comment by ask** [comment]
Ah! I'm sorry for assuming you'd be familiar with sqlalchemy connection strings.  It may not be entirely clear, but the part after `db+` can be anything supported by SQLAlchemy:

http://docs.celeryproject.org/en/latest/configuration.html#database-url-examples

That document links to this page in the SQLAlchemy documentation, which also lists MySQL connection strings:
http://docs.sqlalchemy.org/en/rel_1_1/core/engines.html#mysql

So from that I'm guessing it should be:

```py
CELERY_RESULT_BACKEND = 'db+mysql+mysqldb://scott:tiger@localhost/foo'
```

But you would have to report back if using double plus doesn't work.

**Comment by ask** [comment]
Actually, mysqldb is the MySQLDB default one that didn't work for you, but db+mysql+pymysql works for me here (even if undocumented in the sqlalchemy docs):

```py
CELERY_RESULT_BACKEND = 'db+mysql+pymysql://scott:tiger@localhost/foo'
```

**Comment by heramerom** [comment]
Thank you very much!
but not work.
```
class CeleryConfig(object):
    CELERY_BROKER_URL = 'sqla+mysql://root:123@localhost:3306/celery'
    CELERY_RESULT_BACKEND = 'db+mysql+pymysql://root:123@localhost:3306/celery'

    CELERY_TASK_SERIALIZER = 'json'
```
Except:
```
[2016-10-11 15:21:20,748: ERROR/MainProcess] Unrecoverable error: ImportError("No module named 'MySQLdb'",)
Traceback (most recent call last):
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/worker/consumer.py", line 609, in start
    c.connection, on_decode_error=c.on_decode_error,
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/app/amqp.py", line 385, in __init__
    **kw
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/messaging.py", line 364, in __init__
    self.revive(self.channel)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/messaging.py", line 376, in revive
    self.declare()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/messaging.py", line 386, in declare
    queue.declare()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/entity.py", line 522, in declare
    self.queue_declare(nowait, passive=False)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/entity.py", line 548, in queue_declare
    nowait=nowait)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/virtual/__init__.py", line 446, in queue_declare
    self._new_queue(queue, **kwargs)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 80, in _new_queue
    self._get_or_create(queue)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 68, in _get_or_create
    obj = self.session.query(self.queue_cls) \
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 63, in session
    _, Session = self._open()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 54, in _open
    engine = self._engine_from_config()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 49, in _engine_from_config
    return create_engine(conninfo.hostname, **transport_options)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 92, in dbapi
    return __import__('MySQLdb')
ImportError: No module named 'MySQLdb'
```
and 
```
CELERY_RESULT_BACKEND = 'db+mysql+mysqldb://scott:tiger@localhost/foo'
```
Except:
```
[2016-10-11 15:21:03,904: ERROR/MainProcess] Unrecoverable error: ImportError("No module named 'MySQLdb'",)
Traceback (most recent call last):
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/worker/consumer.py", line 609, in start
    c.connection, on_decode_error=c.on_decode_error,
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/celery/app/amqp.py", line 385, in __init__
    **kw
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/messaging.py", line 364, in __init__
    self.revive(self.channel)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/messaging.py", line 376, in revive
    self.declare()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/messaging.py", line 386, in declare
    queue.declare()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/entity.py", line 522, in declare
    self.queue_declare(nowait, passive=False)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/entity.py", line 548, in queue_declare
    nowait=nowait)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/virtual/__init__.py", line 446, in queue_declare
    self._new_queue(queue, **kwargs)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 80, in _new_queue
    self._get_or_create(queue)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 68, in _get_or_create
    obj = self.session.query(self.queue_cls) \
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 63, in session
    _, Session = self._open()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 54, in _open
    engine = self._engine_from_config()
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/kombu/transport/sqlalchemy/__init__.py", line 49, in _engine_from_config
    return create_engine(conninfo.hostname, **transport_options)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/geeko/.pyenv/versions/3.5.2/lib/python3.5/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 92, in dbapi
    return __import__('MySQLdb')
ImportError: No module named 'MySQLdb'
```
It seems that the `db` in `db+mysql` means 'MySQLdb' model. [MySQLdb](https://pypi.python.org/pypi/MySQL-python/1.2.5) said that support 3.0 in the future. so I want to change the driver to `pymysql`, but I don't know how to do.

**Comment by ask** [comment]
You set the correct db URL for the result backend, but not for the broker!

```py
    CELERY_BROKER_URL = 'sqla+mysql://root:123@localhost:3306/celery'
                                              #  ^^^ missing pymysql 
    CELERY_RESULT_BACKEND = 'db+mysql+pymysql://root:123@localhost:3306/celery'
```

All of the tracebacks are from the broker, not the result backend.

**Comment by heramerom** [comment]
It works. Thank you very much!

**Comment by fantasyhh** [comment]
Get the same error  . wow ,Good job.....      :  )   Thanks

**Comment by michaelfresco** [comment]
@ask 
THANKS! I finally fixed the error with your line:

    CELERY_RESULT_BACKEND = 'db+mysql+pymysql://scott:tiger@localhost/foo'

**Comment by xiexinmofo** [comment]
是的 我也遇到了同样的问题,官方文档是不是可以补充下这个mysql的示例,这个场景应该是用的最多的!
