### ISSUE TITLE
[rc5] Bad Signature

### ISSUE THREAD

**Issue by astronouth7303** [celery/celery#3514]
```
Traceback (most recent call last):
  File "/opt/python/run/venv/src/kombu/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'control'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/run/venv/bin/celery", line 9, in <module>
    load_entry_point('celery==4.0.0rc5', 'console_scripts', 'celery')()
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bin/celery.py", line 334, in main
    cmd.execute_from_commandline(argv)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bin/celery.py", line 1216, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bin/base.py", line 274, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bin/celery.py", line 1208, in handle_argv
    return self.execute(command, argv)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bin/celery.py", line 1140, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bin/base.py", line 237, in __call__
    ret = self.run(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/__init__.py", line 101, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/__init__.py", line 142, in setup_instance
    self.blueprint.apply(self, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bootsteps.py", line 216, in apply
    step.include(parent)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bootsteps.py", line 389, in include
    inc, ret = self._should_include(parent)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bootsteps.py", line 344, in _should_include
    return True, self.create(parent)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/components.py", line 241, in create
    prefetch_multiplier=w.prefetch_multiplier,
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bootsteps.py", line 340, in instantiate
    return instantiate(name, *args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/utils/imports.py", line 57, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 215, in __init__
    self.blueprint.apply(self, **dict(worker_options or {}, **kwargs))
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bootsteps.py", line 210, in apply
    step = S(parent, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/consumer/control.py", line 28, in __init__
    self.box = (pidbox.gPidbox if self.is_green else pidbox.Pidbox)(c)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/pidbox.py", line 30, in __init__
    self.node = c.app.control.mailbox.Node(
  File "/opt/python/run/venv/src/kombu/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/app/base.py", line 1153, in control
    return instantiate(self.control_cls, app=self)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/utils/imports.py", line 57, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/app/control.py", line 156, in __init__
    reply_queue_expires=app.conf.control_queue_expires,
TypeError: __init__() got an unexpected keyword argument 'reply_queue_ttl'
```

I'm getting the error for the arguments `queue_expires`, `reply_queue_expires`, as well as `reply_queue_ttl`.

**Comment by astronouth7303** [comment]
Oops, this is from pip excepting a `-e` install of kombu as valid `>dev`.
