### ISSUE TITLE
KeyError 'scheduler'

### ISSUE THREAD

**Issue by ggstuart** [celery/celery#3521]
Hi,

I'm struggling to get celery beat going. I upgraded to the latest release candidate but the problem persists. 

Whenever I try to run celery beat I get this kind of thing.

```

[2016-10-24 17:39:00,898: ERROR/Beat] Process Beat
Traceback (most recent call last):
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/billiard/process.py", line 306, in _bootstrap
    self.run()
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 613, in run
    self.service.start(embedded_process=True)
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 528, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 572, in scheduler
    return self.get_scheduler()
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 567, in get_scheduler
    lazy=lazy,
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 407, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 204, in __init__
    self.setup_schedule()
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 459, in setup_schedule
    repr(entry) for entry in values(entries)))
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 459, in <genexpr>
    repr(entry) for entry in values(entries)))
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 142, in __repr__
    call=reprcall(self.task, self.args or (), self.kwargs or {}),
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/kombu/utils/functional.py", line 356, in reprcall
    name, sep.join(map(_safe_repr, args or ())),
TypeError: 'int' object is not iterable
[2016-10-24 17:39:00,900: WARNING/Beat] Process Beat:
[2016-10-24 17:39:00,900: WARNING/Beat] Traceback (most recent call last):
[2016-10-24 17:39:00,901: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
[2016-10-24 17:39:00,901: WARNING/Beat] KeyError: 'scheduler'
[2016-10-24 17:39:00,901: WARNING/Beat] During handling of the above exception, another exception occurred:
[2016-10-24 17:39:00,901: WARNING/Beat] Traceback (most recent call last):
[2016-10-24 17:39:00,901: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/billiard/process.py", line 306, in _bootstrap
    self.run()
[2016-10-24 17:39:00,901: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 613, in run
    self.service.start(embedded_process=True)
[2016-10-24 17:39:00,901: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 528, in start
    humanize_seconds(self.scheduler.max_interval))
[2016-10-24 17:39:00,901: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
[2016-10-24 17:39:00,902: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 572, in scheduler
    return self.get_scheduler()
[2016-10-24 17:39:00,902: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 567, in get_scheduler
    lazy=lazy,
[2016-10-24 17:39:00,902: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 407, in __init__
    Scheduler.__init__(self, *args, **kwargs)
[2016-10-24 17:39:00,902: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 204, in __init__
    self.setup_schedule()
[2016-10-24 17:39:00,902: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 459, in setup_schedule
    repr(entry) for entry in values(entries)))
[2016-10-24 17:39:00,902: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 459, in <genexpr>
    repr(entry) for entry in values(entries)))
[2016-10-24 17:39:00,902: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/beat.py", line 142, in __repr__
    call=reprcall(self.task, self.args or (), self.kwargs or {}),
[2016-10-24 17:39:00,902: WARNING/Beat] File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/kombu/utils/functional.py", line 356, in reprcall
    name, sep.join(map(_safe_repr, args or ())),
[2016-10-24 17:39:00,902: WARNING/Beat] TypeError: 'int' object is not iterable


```

**Comment by ask** [comment]
What version is this?

**Comment by ggstuart** [comment]
4.0.0rc6 (0today8)

**Comment by ggstuart** [comment]
I'm also getting this error in my worker without using beat.

```
[2016-10-25 11:13:01,477: ERROR/PoolWorker-3] Task data_file_tasks.process_file_by_id[6ff3cca6-75f1-41f8-89e9-c3495c0ba8aa] raised unexpected: IndexError(0,)
Traceback (most recent call last):
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/utils/functional.py", line 202, in __getitem__
    return self.__consumed[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/utils/functional.py", line 206, in __getitem__
    self.__consumed.append(next(self.__it))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/app/trace.py", line 369, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/app/trace.py", line 623, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/graeme/Projects/EDINet/edinet-server/edinet/daemon/data_file_tasks.py", line 84, in process_file_by_id
    return chord(prepare_devices)(process_results.s(file_record))
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/canvas.py", line 1273, in __call__
    return self.apply_async((), {'body': body} if body else {}, **options)
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/canvas.py", line 1309, in apply_async
    app = self._get_app(body)
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/canvas.py", line 1408, in _get_app
    app = tasks[0]._app
  File "/home/graeme/.virtualenvs/edinet/local/lib/python3.4/site-packages/celery/utils/functional.py", line 208, in __getitem__
    raise IndexError(index)
IndexError: 0

```

**Comment by ggstuart** [comment]
I think I may have resolved one issue which was that the 'args' value should be an iterable but I passed `(120)` which becomes an int.

Now Beat seems to work.

**Comment by gamelife1314** [comment]
I have also encountered the same problem，my settings as are follows:

`
"BROKER_URL": "amqp://'",
        "CELERY_RESULT_BACKEND ": "redis://",
        "CELERY_ACCEPT_CONTENT": ["json"],
        "CELERY_TASK_SERIALIZER": "json",
        "CELERY_RESULT_SERIALIZER ": "json",
        "CELERY_TIMEZONE ": "Asia/Shanghai",
        # "CELERYBEAT_SCHEDULE_FILENAME": "celerybeat-schedule.db",
        "CELERYBEAT_SCHEDULE": {
            "weixin-newrank-search": {
                'task': 'weixin.nr-get-account-info',
                'schedule': 300,
                "args": ({
                    "latest_post_time": 1479765634,
                    "account_id": "rmrbwx",
                    "exist_nr": 1
                },)
            },
        },
`
