### ISSUE TITLE
workers failing recover from connection failure to rabbitmq since using CELERYD_MAX_TASKS_PER_CHILD

### ISSUE THREAD

**Issue by AvihayTsayeg** [celery/celery#3522]
Hi,
Workers were shutdown (no pid file) after connection failure.
first error:

```
[2016-10-19 23:57:33,873: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
```

Then few failing retry

And this :

```
[2016-10-20 00:06:19,629: INFO/MainProcess] Connected to amqp://user:pwd@host:5672/virtual
[2016-10-20 00:06:19,721: INFO/MainProcess] mingle: searching for neighbors
[2016-10-20 00:06:21,443: INFO/MainProcess] mingle: sync with 4 nodes
[2016-10-20 00:06:21,445: INFO/MainProcess] mingle: sync complete
[2016-10-20 00:06:21,644: ERROR/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'drain_events'",)
Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "venv/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "venv/lib/python2.7/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "venv/lib/python2.7/site-packages/kombu/async/hub.py", line 279, in create_loop
    item()
  File "venv/lib/python2.7/site-packages/amqp/utils.py", line 42, in __call__
    self.set_error_state(exc)
  File "venv/lib/python2.7/site-packages/amqp/utils.py", line 39, in __call__
    **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
  File "venv/lib/python2.7/site-packages/kombu/connection.py", line 288, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events
    return connection.drain_events(**kwargs)
```

celery (3.1.23)
amqp (1.4.9)
kombu (3.0.37)

This happens since we used this parameter
CELERYD_MAX_TASKS_PER_CHILD

```
software -> celery:3.1.23 (Cipater) kombu:3.0.37 py:2.7.3  billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:amqp

BROKER_HEARTBEAT: 2
CELERYD_PREFETCH_MULTIPLIER: 1
CELERYD_MAX_TASKS_PER_CHILD: 1
CELERYD_HIJACK_ROOT_LOGGER: False
BROKER_CONNECTION_RETRY: True
BROKER_POOL_LIMIT: 36
CELERY_IGNORE_RESULT: True
CELERYD_TASK_SOFT_TIME_LIMIT: 604800
CELERYD_TASK_TIME_LIMIT: 604860
BROKER_URL: 'amqp://user:********@server:5672/virt'
CELERY_RESULT_BACKEND: 'amqp'
BROKER_HEARTBEAT_CHECKRATE: 1
```

I tried avoiding using connection pool and the same behavior happened.
Using CELERYD_MAX_TASKS_PER_CHILD=10 got the same behavior.

Regards, Avihay

**Comment by auvipy** [comment]
should be fixed on master
