### ISSUE TITLE
I cannot start celery v4.0.0rc6 on a RHEL 7 with python 2.7.5

### ISSUE THREAD

**Issue by tl-marino** [celery/celery#3533]
While starting celery v4.0.0rc6 on a RHEL 7, I get following error:

 _-------------- celery@.. v4.0.0rc6 (0today8)
---- **** -----
--- * ***  * -- Linux-3.10.0-327.36.2.el7.x86_64-x86_64-with-redhat-7.2-Maipo 2016-10-27 14:09:36
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         myApplication:0x294fe90
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> default          exchange=default(direct) key=default
 
 
[2016-10-27 14:09:37,479: CRITICAL/MainProcess] Unrecoverable error: TypeError('Struct() argument 1 must be string, not unicode',)
Traceback (most recent call last):
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/worker/worker.py", line 204, in start
    self.blueprint.start(self)
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 589, in start
    c.loop(*c.loop_args())
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/worker/loops.py", line 90, in asynloop
    next(loop)
  File "/home/xx/yy/venv/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 292, in on_result_readable
    next(it)
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 247, in _recv_message
    body_size, = unpack_from('>i', bufv)
  File "/home/xx/yy/venv/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 61, in unpack_from
    return _unpack_from(fmt, view.tobytes())  # <- memoryview
TypeError: Struct() argument 1 must be string, not unicode_ 

########################################################################
I can resolve this by replacing fmt with str(fmt) on line 61 of python2.7/site-packages/celery/concurrency/asynpool.py. 

The same happens with celery rc7

**Comment by ask** [comment]
Thanks!  rc7 will be on PyPI shortly

**Comment by devdlabs** [comment]
this issue still haunting in 4.0.1. It seems `b` missing in new version?
After editing `header = pack('>I', size)` to `header = pack(b'>I', size)` it worked!
