### ISSUE TITLE
Unrecoverable error: TypeError("__init__() got multiple values for keyword argument 'body'",)

### ISSUE THREAD

**Issue by gjedeer** [celery/celery#3543]
## Checklist

- [*] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [*] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I ran the most basic hello world example with `celery worker -A tasks` and it failed.

Celery master, kombu master, other dependencies as following. The same happened with 4.0.0rc7. CentOS 7, virtualenv with --no-site-packages.
<pre>
amqp==2.1.1
billiard==3.5.0.2
celery==4.0.0
kombu==4.0.0
librabbitmq==1.6.1
pytz==2016.7
vine==1.1.3
wsgiref==0.1.2
</pre>

<pre>
$ cat celeryconfig.py
broker_url = 'amqp://******:********@squirrel.rmq.cloudamqp.com/*****'
broker_pool_limit = 1
broker_heartbeat = None
broker_connection_timeout = 30
result_backend = 'rpc://'
worker_send_task_events = True
event_queue_expires = 60
task_serializer = 'json'
result_serializer = 'json'
accept_content = ['json']
timezone = 'Europe/Berlin'
enable_utc = True
</pre>

<pre>
$ cat tasks.py
from celery import Celery

app = Celery('tasks')

@app.task
def add(x, y):
    return x + y

app.config_from_object('celeryconfig')
</pre>

## Expected behavior
I'm able to run a Celery 4.0 worker, or atleast I get a meaningful error message

## Actual behavior
<pre>
$ celery worker -A tasks
 
 -------------- celery@devapi.dknow.eu v4.0.0 (0today8)
---- **** ----- 
--- * ***  * -- Linux-3.10.0-327.36.3.el7.x86_64-x86_64-with-centos-7.2.1511-Core 2016-11-04 13:27:45
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x1b73dd0
- ** ---------- .> transport:   amqp://******:**@squirrel.rmq.cloudamqp.com:5672/*****
- ** ---------- .> results:     rpc://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[2016-11-04 13:28:04,807: CRITICAL/MainProcess] Unrecoverable error: TypeError("__init__() got multiple values for keyword argument 'body'",)
Traceback (most recent call last):
  File "/home/knowledge/venv/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/knowledge/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/knowledge/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/home/knowledge/venv/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/knowledge/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/knowledge/venv/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 584, in start
    c.loop(*c.loop_args())
  File "/home/knowledge/venv/lib/python2.7/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/home/knowledge/venv/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/home/knowledge/venv/lib/python2.7/site-packages/kombu/transport/base.py", line 236, in on_readable
    reader(loop)
  File "/home/knowledge/venv/lib/python2.7/site-packages/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "/home/knowledge/venv/lib/python2.7/site-packages/librabbitmq/__init__.py", line 220, in drain_events
    self._basic_recv(timeout)
  File "/home/knowledge/venv/lib/python2.7/site-packages/kombu/transport/librabbitmq.py", line 45, in __init__
    headers=props.get('headers'))
TypeError: __init__() got multiple values for keyword argument 'body'
</pre>

## Report

<pre>
$ celery -A tasks report

software -> celery:4.0.0 (0today8) kombu:4.0.0 py:2.7.5
            billiard:3.5.0.2 librabbitmq:1.6.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:librabbitmq results:rpc:///

task_serializer: 'json'
broker_heartbeat: None
broker_connection_timeout: 30
accept_content: ['json']
broker_pool_limit: 1
enable_utc: True
event_queue_expires: 60
result_serializer: 'json'
worker_send_task_events: True
timezone: 'Europe/Berlin'
broker_url: u'amqp://*****:********@squirrel.rmq.cloudamqp.com:5672/*****'
result_backend: u'rpc:///'
</pre>

**Comment by ask** [comment]
I think you should not be using librabbitmq with 4.0, it's currently very broken for me.  Uninstall it and use pyamqp:// for now.

**Comment by gjedeer** [comment]
Thank you for your answer, I'll close this issue then.
