### ISSUE TITLE
WindowsError: [Error 87] The parameter is incorrect Error on Celery 4 

### ISSUE THREAD

**Issue by netcrime** [celery/celery#3551]
Cannot start Celery 4 worker.

OS: Windows 10 x64
Python: 2.7
Celery version: 4
VirtualEnv, Django 1.10

ERROR:
`[2016-11-05 20:23:25,759: CRITICAL/MainProcess] Unrecoverable error: TypeError('must be integer<k>, not _subprocess_handle',)
Traceback (most recent call last):
  File "c:\development\env\zillow2\lib\site-packages\celery\worker\worker.py", line 203, in start
    self.blueprint.start(self)
  File "c:\development\env\zillow2\lib\site-packages\celery\bootsteps.py", line 119, in start
    step.start(parent)
  File "c:\development\env\zillow2\lib\site-packages\celery\bootsteps.py", line 370, in start
    return self.obj.start()
  File "c:\development\env\zillow2\lib\site-packages\celery\concurrency\base.py", line 131, in start
    self.on_start()
  File "c:\development\env\zillow2\lib\site-packages\celery\concurrency\prefork.py", line 112, in on_start
    **self.options)
  File "c:\development\env\zillow2\lib\site-packages\billiard\pool.py", line 1008, in __init__
    self._create_worker_process(i)
  File "c:\development\env\zillow2\lib\site-packages\billiard\pool.py", line 1117, in _create_worker_process
    w.start()
  File "c:\development\env\zillow2\lib\site-packages\billiard\process.py", line 122, in start
    self._popen = self._Popen(self)
  File "c:\development\env\zillow2\lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
  File "c:\development\env\zillow2\lib\site-packages\billiard\popen_spawn_win32.py", line 64, in __init__
    _winapi.CloseHandle(ht)
TypeError: must be integer<k>, not _subprocess_handle

(zillow2) C:\DEVELOPMENT\zillow2\project>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\development\env\zillow2\lib\site-packages\billiard\spawn.py", line 159, in spawn_main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "c:\development\env\zillow2\lib\site-packages\billiard\reduction.py", line 121, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
WindowsError: [Error 87] The parameter is incorrect
`
I was able to run Celery worker only when degraded celery version to 3

**Comment by malinoff** [comment]
Sorry, windows is not officially supported by celery 4, http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#removed-features

**Comment by vladimir-poleh** [comment]
Problem is incorrect handle closing for the Python 2.7. I have fix for it, but there is another issue with nested class instance pickling.

**Comment by obskyr** [comment]
Nguhhhh. I have the same problem. I'm doing my main development on Windows, too, so this is a bit of a tough situation.

In addition, I can't get Celery 3.x.x working, but I suppose that's just because I'm doing something wrong.

**Comment by netcrime** [comment]
Well I just downgraded to 3.x.x

**Comment by NwawelAIroume** [comment]
same issue on my side! i think will use the downgraded too!

**Comment by monk8800** [comment]
When will this be likely fixed? Just ran into the same issue 
celery==4.0.2, will probably downgrade as well as no issue previously running 
celery==3.1.18

**Comment by netcrime** [comment]
> Microsoft Windows is no longer supported.
> 
> The test suite is passing, and Celery seems to be working with Windows, but we make no guarantees as we are unable to diagnose issues on this platform. If you are a company requiring support on this platform, please get in touch.

Probably not going to be fixed.

**Comment by JonnathanCalderon** [comment]
I'm on Windows 7 and I cant do a downgrade python3.6 because of some lib-errors with python.version<=3.5. So, I gotta to develop a hackish way cause Celery is anti-windows?

**Comment by netcrime** [comment]
JonnathanCalderon you have to "downgrade" celery not python. Just create new virtualenv and install proper versions.

**Comment by rsoumyassdi** [comment]
I had celery 4, 
celery==3.1.18 worked for me.. If anyone still has the issue, 
Just wanted to share.

**Comment by auvipy** [comment]
follow this to fix https://github.com/celery/celery/pull/4078
