### ISSUE TITLE
Elasticsearch storage does not work

### ISSUE THREAD

**Issue by mrfuxi** [celery/celery#3556]
Elasticsearch result backend implementation has bugs in it:
* `_index` method is ignoring both `id` and `body` and that is causing elasticsearch client to miss required arg `body`. Looks like it was cause by commit https://github.com/celery/celery/commit/9364a9ec8939c32b879fc4333dddd5cbaa192439

```
[2016-11-07 12:16:12,380: ERROR/MainProcess] Pool callback raised exception: TypeError("index() missing 1 required positional argument: 'body'",)
Traceback (most recent call last):
  File "project/lib/python3.5/site-packages/billiard/pool.py", line 1748, in safe_apply_callback
    fun(*args, **kwargs)
  File "project/lib/python3.5/site-packages/celery/worker/request.py", line 366, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "project/lib/python3.5/site-packages/celery/backends/base.py", line 163, in mark_as_failure
    traceback=traceback, request=request)
  File "project/lib/python3.5/site-packages/celery/backends/base.py", line 309, in store_result
    request=request, **kwargs)
  File "project/lib/python3.5/site-packages/celery/backends/base.py", line 652, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "project/lib/python3.5/site-packages/celery/backends/elasticsearch.py", line 80, in set
    datetime.utcnow().isoformat()[:-3]
  File "project/lib/python3.5/site-packages/celery/backends/elasticsearch.py", line 94, in _index
    **kwargs
  File "project/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: index() missing 1 required positional argument: 'body'
```

* When I made some local changes to pass bo values to elasticsearch client i got encoding error. In Py3.5 key is a bytestring type

```
[2016-11-07 12:20:17,399: ERROR/MainProcess] Pool callback raised exception: AttributeError("'bytes' object has no attribute 'encode'",)
Traceback (most recent call last):
  File "project/lib/python3.5/site-packages/billiard/pool.py", line 1748, in safe_apply_callback
    fun(*args, **kwargs)
  File "project/lib/python3.5/site-packages/celery/worker/request.py", line 366, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "project/lib/python3.5/site-packages/celery/backends/base.py", line 163, in mark_as_failure
    traceback=traceback, request=request)
  File "project/lib/python3.5/site-packages/celery/backends/base.py", line 309, in store_result
    request=request, **kwargs)
  File "project/lib/python3.5/site-packages/celery/backends/base.py", line 652, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "project/lib/python3.5/site-packages/celery/backends/elasticsearch.py", line 80, in set
    datetime.utcnow().isoformat()[:-3]
  File "project/lib/python3.5/site-packages/celery/backends/elasticsearch.py", line 94, in _index
    **kwargs
  File "project/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "project/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "project/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 47, in _make_path
    quote_plus(_escape(p), b',*') for p in parts if p not in SKIP_IN_PATH)
  File "project/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 47, in <genexpr>
    quote_plus(_escape(p), b',*') for p in parts if p not in SKIP_IN_PATH)
  File "project/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 32, in _escape
    return value.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by thedrow** [comment]
This was fixed by #3606.
