### ISSUE TITLE
Launching Celery worker with -c >169 crashes

### ISSUE THREAD

**Issue by MoorsTech** [celery/celery#3560]
This might be totally expected behavior, but I couldn't find any information about this.
Running `celery worker -A app -c 169` works just fine, but `celery worker -A app -c 170` does not - see output below. I get the same issue when growing the process-pool via the control-module.

``celery -A proj report``
```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:2.7.12
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

## Steps to reproduce
celery worker -A proj -c 170
## Error-Logs
```
[2016-11-07 22:28:30,551: CRITICAL/MainProcess] Unrecoverable error: OSError(24, 'Too many open files')
Traceback (most recent call last):
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 584, in start
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/worker/loops.py", line 49, in asynloop
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/worker/worker.py", line 217, in register_with_event_loop
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/bootsteps.py", line 151, in send_all
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/worker/components.py", line 178, in register_with_event_loop
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 134, in register_with_event_loop
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 472, in register_with_event_loop
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 454, in _track_child_process
OSError: [Errno 24] Too many open files
[2016-11-07 22:28:30,552: ERROR/MainProcess] Error on stopping Heart: OSError('Load averages are unobtainable',)
Traceback (most recent call last):
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/bootsteps.py", line 151, in send_all
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/worker/consumer/heart.py", line 35, in stop
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/worker/heartbeat.py", line 61, in stop
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/worker/heartbeat.py", line 46, in _send
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/utils/sysinfo.py", line 24, in load_average
  File "/home/moorstech/.virtualenvs/test/local/lib/python2.7/site-packages/celery/utils/sysinfo.py", line 14, in _load_average
OSError: Load averages are unobtainable
```

**Comment by ask** [comment]
It works fine for me here on macOS, so I'm guessing this is just as the error message says: you have run out of file descriptors.

You may need to increase the max number of open file descriptors allowed on your system:
http://stackoverflow.com/questions/21515463/how-to-increase-maximum-file-open-limit-ulimit-in-ubuntu

Every process will require at least 2 file descriptors: one pipe for incoming tasks, one pipe for results back to the parent, then comes any sockets or files your tasks may open.

**Comment by MoorsTech** [comment]
Thanks @ask, you are right of course, I was running out of file-descriptors. Increasing the hard&soft limits helped here.
I was a bit surprised though that each celery-process actually required ~6 file descriptors. Anyways, thanks! =)
