### ISSUE TITLE
How to customize the default logger info

### ISSUE THREAD

**Issue by xiazhibin** [celery/celery#3599]
I run my celery:`celery -A proj worker -l INFO`
When I start a task,I can get such log info:
`[2016-11-16 18:33:40,620: INFO/MainProcess] Received task: proj.tasks.task_add.add[7df34cf5-7175-4848-bd36-5f0c910f07dd]`
`[2016-11-16 18:33:40,625: INFO/MainProcess] Task proj.tasks.task_add.add[7df34cf5-7175-4848-bd36-5f0c910f07dd] succeeded in 0.00376014899666s: '{"r": 6}'`

I want to add the hostname(where the celery run at) to log info.
like that:
`[2016-11-16 18:33:40,625: INFO/MainProcess] hostname:celery@bin381-2.local Task proj.tasks.task_add.add[7df34cf5-7175-4848-bd36-5f0c910f07dd] succeeded in 0.00376014899666s: '{"r": 6}'`

How can I do that?

**Comment by ask** [comment]
You should be able to set this using the `worker_log_format` setting:
http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-worker_log_format

I think there's a key for the current hostname, but I don't think there's one for the worker nodename.

You generate this dynamically using the `celeryd_init` signal:

```py

from celery.signals

@signals.celeryd_init.connect
def setup_log_format(sender, conf, **kwargs):
    conf.worker_log_format = """
        [%(asctime)s: %(levelname)s/%(processName)s {0}] %(message)s
    """.strip().format(sender)
    conf.worker_task_log_format = (
        '[%(asctime)s: %(levelname)s/%(processName)s {0}] '
        '[%(task_name)s(%(task_id)s)] %(message)s'
    ).format(sender)
```

You can put this in the module that you define the `app = Celery(...)` for example.

**Comment by xiazhibin** [comment]
It does not work at all
```
@signals.celeryd_init.connect
def setup_log_format(sender, conf, **kwargs):
    conf.worker_log_format = """
        [%(asctime)s:  {0}] %(message)s
    """.strip().format(sender)
    conf.worker_task_log_format = (
        '[%(asctime)s: ] %(message)s'
    ).format(sender)
```

Here is the log 
`[2016-12-09 21:13:50,399: INFO/Worker-3] proj.tasks.task_add.add[bf3807da-2cdc-4154-909e-eee86b642299]: {"url": "https://www.tick.com/s?wd=quickse%2Biph8ZsTZUKgkx9rhIImt50PlwCYwt4D7J&rsv_sug2=1&prefixsug=quickse&rsp=3&inputT=6201&rsv_sug4=6200", "r": 6}`

**Comment by rtindru** [comment]
`%(hostname)s` does not work - raises a `KeyError`

```
Logged from file bootsteps.py, line 272
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/log.py", line 142, in format
    msg = logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 469, in format
    s = self._fmt % record.__dict__
KeyError: 'hostname'
```

**Comment by DylanYoung** [comment]
Running into this as well.  Can we reopen this as a ticket to document the available variables?

**Comment by xxholyChalicexx** [comment]
Is there any way one can include username in the log of celery ? I am trying to customize the text that is displayed in the celery log .
