### ISSUE TITLE
Bug in _saferepr causes UnicodeDecodeError

### ISSUE THREAD

**Issue by jas32096** [celery/celery#3600]
An issue in `_saferepr` is crashing my program. I think it's because `_saferepr` doesn't properly handle backslash replaced ascii.

I tried changing `saferepr` to just `return repr(o)` and that seemed to solve the issue.

## Report
```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:2.7.11
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:rpc:///

accept_content: set(['pickle'])
task_serializer: 'pickle'
broker_url: u'amqp://guest:********@localhost:5672//'
result_backend: u'rpc:///'
result_serializer: 'pickle'
```

## Traceback
```
Traceback (most recent call last):
  File "./commands.py", line 29, in <module>
    manager.run()
  File "/Users/jschechter/Desktop/21Shifts/.env/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/jschechter/Desktop/21Shifts/.env/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/jschechter/Desktop/21Shifts/.env/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "./commands.py", line 25, in broadcast
    rets = [positon.broadcast(charge=False, delay=True) for positon in Position.query]
  File "/Users/jschechter/Desktop/21Shifts/app/positions/position.py", line 88, in broadcast
    return broadcast.delay(self, charge) if delay else broadcast(self, charge)
  File "/Users/jschechter/Desktop/21Shifts/.env/lib/python2.7/site-packages/celery/app/task.py", line 413, in delay
    return self.apply_async(args, kwargs)
  File "/Users/jschechter/Desktop/21Shifts/.env/lib/python2.7/site-packages/celery/app/task.py", line 536, in apply_async
    **options
  File "/Users/jschechter/Desktop/21Shifts/.env/lib/python2.7/site-packages/celery/app/base.py", line 712, in send_task
    root_id, parent_id, shadow, chain,
  File "/Users/jschechter/Desktop/21Shifts/.env/lib/python2.7/site-packages/celery/app/amqp.py", line 333, in as_task_v2
    argsrepr = saferepr(args, self.argsrepr_maxsize)
  File "/Users/jschechter/Desktop/21Shifts/.env/lib/python2.7/site-packages/celery/utils/saferepr.py", line 74, in saferepr
    o, maxlen=maxlen, maxlevels=maxlevels, seen=seen
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 15: ordinal not in range(128)
```

## My repr
```python
def __unicode__(self): return ('<Position #%i : %s>' % (self.id, self.name))
def __repr__(self):    return unicode(self).encode('utf-8', errors='backslash replace')
```

The irony of this bug is not lost on me...

**Comment by jas32096** [comment]
Using this awful hack until this bug is fixed. It sorta works with my db Models SQLAlchemy.

```Python
def celerysafe(cls):
    return type(cls.__name__, (cls,),{
        '__reduce__':
            lambda x: cls.__reduce__(cls.query.get(x.id)),
        '__repr__':
            lambda x: "Eat shit",
        '__eq__':
            lambda x,y:
                (x.id == y.id
                 if x.__class__.__name__ == y.__class__.__name__
                 else cls.__eq__(y))})
```

Might be helpful to someone else; probably not, though.

**Comment by ask** [comment]
Hmm, but `__repr__` on Python 3 should return str, and not bytes, so shouldn't it convert it back to str after replacing the unrepresentable characters?

```
def __repr__(self):
    return unicode(self).encode('utf-8', errors='backslash replace').decode()
```

But I'm still now sure how this could possibly work if you're using Python 3.5: the `unicode()` function was removed in Python 3.

**Comment by jas32096** [comment]
@ask I'm using Python 2.7.11 with Flask 0.11

**Comment by ask** [comment]
Ok, that makes more sense,  the bugreport info said 3.5.0.2 :)

Try with the patch in 5a4d1ef please!

**Comment by jas32096** [comment]
Thanks @ask ; working well, now
