### ISSUE TITLE
List of Json Dicts unable to serialize (throws  EncodeError)

### ISSUE THREAD

**Issue by ssudake21** [celery/celery#3604]
## Checklist
Celery Report
```
(new_dev) chronin@chronin$ celery -A Mtt report
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:2.7.11+
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/0

enable_utc: True
timezone: 'UTC'
broker_url: u'amqp://uvv:********@localhost:5672/pc'
result_backend: u'redis://localhost:6379/0'
```

## Steps to reproduce
Please refer attached stacktrace.

## Expected behavior
Unable to confirm.

## Actual behavior
```
Task pc.services.api.get_problem_details[eb87fd0b-4d09-476b-b223-c5db1e2c3f8a] raised unexpected: EncodeError(TypeError("[{'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_1.txt', 'memory_limit': 256, 'points': 2, 'sr_no': 1, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_1.txt', u'id': 194}, {'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_2.txt', 'memory_limit': 256, 'points': 2, 'sr_no': 2, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_2.txt', u'id': 195}, {'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_3.txt', 'memory_limit': 256, 'points': 3, 'sr_no': 3, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_3.txt', u'id': 196}, {'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_4.txt', 'memory_limit': 256, 'points': 3, 'sr_no': 4, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_4.txt', u'id': 197}] is not JSON serializable",),)
Traceback (most recent call last):
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/celery/app/trace.py", line 428, in trace_task
    uuid, retval, task_request, publish_result,
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/celery/backends/base.py", line 152, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/celery/backends/base.py", line 309, in store_result
    request=request, **kwargs)
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/celery/backends/base.py", line 652, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/celery/backends/base.py", line 259, in encode
    _, _, payload = self._encode(data)
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/celery/backends/base.py", line 263, in _encode
    return dumps(data, serializer=self.serializer)
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/chronin/General/new_dev/local/lib/python2.7/site-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
EncodeError: [{'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_1.txt', 'memory_limit': 256, 'points': 2, 'sr_no': 1, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_1.txt', u'id': 194}, {'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_2.txt', 'memory_limit': 256, 'points': 2, 'sr_no': 2, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_2.txt', u'id': 195}, {'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_3.txt', 'memory_limit': 256, 'points': 3, 'sr_no': 3, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_3.txt', u'id': 196}, {'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_4.txt', 'memory_limit': 256, 'points': 3, 'sr_no': 4, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_4.txt', u'id': 197}] is not JSON serializable
```

**Comment by monsterxx03** [comment]
Come to the similar error when task parameter is a list, but my error is json decode error.

task result is stored as pickle, but client try to decode it via json. BTW I set `task_serializer` to  msgpack in config.

Another wired impact is when come to this error in a gunicorn worker (gevent),  the worker's cpu usage become very high, but still can reponse to web request(become slower). Even I stop all traffic, the worker cpu usage is still very high.

do 

    strace -p <gunicorn-worker-pid>

I can see the worker is looping in epoll_wait at a crazy speed:

    clock_gettime(CLOCK_MONOTONIC, {66261, 377855703}) = 0
    clock_gettime(CLOCK_MONOTONIC, {66261, 378249735}) = 0
    epoll_wait(19, [], 64, 999)
    ...... # repeating

It only happen after failed to insert task .

**Comment by ask** [comment]
I'm perfectly able to encode the list of dicts as represented in the text:

```py
>>> x
[{'sr_no': 1, 'std_input': '/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_1.txt', 'points': 2, 'id': 194, 'std_output': '/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_1.txt', 'memory_limit': 256, 'time_limit': 2}, {'sr_no': 2, 'std_input': '/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_2.txt', 'points': 2, 'id': 195, 'std_output': '/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_2.txt', 'memory_limit': 256, 'time_limit': 2}, {'sr_no': 3, 'std_input': '/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_3.txt', 'points': 3, 'id': 196, 'std_output': '/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_3.txt', 'memory_limit': 256, 'time_limit': 2}, {'sr_no': 4, 'std_input': '/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_4.txt', 'points': 3, 'id': 197, 'std_output': '/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_4.txt', 'memory_limit': 256, 'time_limit': 2}]
>>> from kombu.utils.json import dumps
>>> dumps(x)
'[{"sr_no": 1, "std_input": "/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_1.txt", "points": 2, "id": 194, "std_output": "/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_1.txt", "memory_limit": 256, "time_limit": 2}, {"sr_no": 2, "std_input": "/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_2.txt", "points": 2, "id": 195, "std_output": "/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_2.txt", "memory_limit": 256, "time_limit": 2}, {"sr_no": 3, "std_input": "/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_3.txt", "points": 3, "id": 196, "std_output": "/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_3.txt", "memory_limit": 256, "time_limit": 2}, {"sr_no": 4, "std_input": "/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_4.txt", "points": 3, "id": 197, "std_output": "/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_4.txt", "memory_limit": 256, "time_limit": 2}]'
```

but note that what is printed here is only the representation of the list of dicts, as in `repr(x)`, if these objects contained are special objects with a ``repr()`` that just looks like a string then it may still not encode properly.

One example would be if these paths are actually some kind of Path object, that returns the path in the repr.

I would need to know more about the actual types contained inside this list-of-dicts.

**Comment by ask** [comment]
Though it seems as if it was the types within the list-of-dicts then the error would be more concrete:

```py
>>> class Path(object):
...    def __init__(self, v):
...       self.v = v
...    def __repr__(self):
...       return self.v
...
>>> x = [{'std_input': Path("/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_1.txt")}]
>>> x
[{'std_input': /home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_1.txt}]
>>> dumps(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asksol/.virtualenvs/def3/lib/python3.5/site-packages/kombu-4.0.0-py3.5.egg/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/Users/asksol/.virtualenvs/def3/lib/python3.5/site-packages/kombu-4.0.0-py3.5.egg/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: /home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_1.txt is not JSON serializable
```

**Comment by ask** [comment]
What's happening is probably something more close to this:

```py
>>> class Data(object):
...   def __init__(self, data):
...       self.data = data
...   def __repr__(self):
...       return repr(self.data)
...
>>> x = Data([{'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_1.txt', 'memory_limit': 256, 'points': 2, 'sr_no': 1, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_1.txt', u'id': 194}, {'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet                                                                                 in/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_2.txt', u'id': 195}, {'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_3.txt', 'memory_limit': 256, 'points': 3, 'sr_no': 3, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_3.txt', u'id': 196}, {'time_limit': 2, 'std_output': u'/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_4.txt', 'memory_limit': 256, 'points': 3, 'sr_no': 4, 'std_input': u'/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_4.txt', u'id': 197}])
>>> dumps(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asksol/.virtualenvs/def3/lib/python3.5/site-packages/kombu-4.0.0-py3.5.egg/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/Users/asksol/.virtualenvs/def3/lib/python3.5/site-packages/kombu-4.0.0-py3.5.egg/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: [{'sr_no': 1, 'std_input': '/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_1.txt', 'points': 2, 'id': 194, 'std_output': '/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_1.txt', 'memory_limit': 256, 'time_limit': 2}, {'sr_no': 2, 'std_input': '/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_2.txt', 'points': 2, 'id': 195, 'std_output': '/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_2.txt', 'memory_limit': 256, 'time_limit': 2}, {'sr_no': 3, 'std_input': '/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_3.txt', 'points': 3, 'id': 196, 'std_output': '/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_3.txt', 'memory_limit': 256, 'time_limit': 2}, {'sr_no': 4, 'std_input': '/home/chronin/General/uvv1.1/media/qdb_stdin/ip_spreadsheet_4.txt', 'points': 3, 'id': 197, 'std_output': '/home/chronin/General/uvv1.1/media/qdb_stdout/op_spreadsheet_4.txt', 'memory_limit': 256, 'time_limit': 2}] is not JSON serializable
```


So what looks like a list-of-dicts is actually some other kind of object that you need to get the list-of-dicts from.

**Comment by ssudake21** [comment]
You suspicion seems to be correct (paths can be django File objects). I will verify more on this.
