### ISSUE TITLE
CELERYD_MAX_TASKS_PER_CHILD desn't works well

### ISSUE THREAD

**Issue by xiangmeng4geo** [celery/celery#3607]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
[report.txt](https://github.com/celery/celery/files/599322/report.txt)
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

In my celery project which uses some of C++ Libs,like opencv/numpy/GDAL and some cpp code writen by ourself. due to the long run of memory is growing, so I have to force the restart worker to release the memory.
But I set the CELERYD_MAX_TASKS_PER_CHILD = 4 ,after some tasks , it will block the execution of my task.

```
Pool callback raised exception: LoopExit('This operation would block forever', <Hub at 0x582a870 epoll pending=0 ref=0 fileno=57>)
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/billiard/pool.py", line 1700, in safe_apply_callback
    fun(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/celery/worker/job.py", line 373, in on_timeout
    self.task.backend.mark_as_failure(self.id, exc, request=self)
  File "/usr/local/python/lib/python2.7/site-packages/celery/backends/base.py", line 133, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/python/lib/python2.7/site-packages/celery/backends/base.py", line 271, in store_result
    request=request, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/celery/backends/base.py", line 505, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/python/lib/python2.7/site-packages/celery/backends/redis.py", line 161, in set
    return self.ensure(self._set, (key, value), **retry_policy)
  File "/usr/local/python/lib/python2.7/site-packages/celery/backends/redis.py", line 150, 03in ensure
    **retry_policy
  File "/usr/local/python/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/celery/backends/redis.py", line 170, in _set
    pipe.execute()
  File "/usr/local/python/lib/python2.7/site-packages/redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/python/lib/python2.7/site-packages/redis/client.py", line 2455, in _execute_transaction
    self.parse_response(connection, '_')
  File "/usr/local/python/lib/python2.7/site-packages/redis/client.py", line 2536, in parse_response
    self, connection, command_name, **options)
  File "/usr/local/python/lib/python2.7/site-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/usr/local/python/lib/python2.7/site-packages/redis/connection.py", line 569, in read_response
    response = self._parser.read_response()
  File "/usr/local/python/lib/python2.7/site-packages/redis/connection.py", line 224, in read_response
    response = self._buffer.readline()
  File "/usr/local/python/lib/python2.7/site-packages/redis/connection.py", line 162, in readline
    self._read_from_socket()
  File "/usr/local/python/lib/python2.7/site-packages/redis/connection.py", line 120, in _read_from_socket
    data = self._sock.recv(socket_read_size)
  File "/usr/local/python/lib/python2.7/site-packages/gevent/_socket2.py", line 280, in recv
    self._wait(self._read_event)
  File "/usr/local/python/lib/python2.7/site-packages/gevent/_socket2.py", line 179, in _wait
    self.hub.wait(watcher)
  File "/usr/local/python/lib/python2.7/site-packages/gevent/hub.py", line 627, in wait
    result = waiter.get()
  File "/usr/local/python/lib/python2.7/site-packages/gevent/hub.py", line 875, in get
    return self.hub.switch()
  File "/usr/local/python/lib/python2.7/site-packages/gevent/hub.py", line 606, in switch
    return greenlet.switch(self)
LoopExit: ('This operation would block forever', <Hub at 0x5dcae10 epoll pending=0 ref=0 fileno=41>)
```
My Task is something like :
```python
@app.task(soft_time_limit=360, max_retries=3)
def main_task():
    for info in info_list:
        task_group1.append(
            (
               subtask1.s(info) |
               subtask2.s()  
            )
        )
     result = group(task_group1).apply_async().get()
     ....
@app.task
def subtask1(info):
   ....
   return {'key1':value1,'key2':value2 ...}
@app.task
def subtask2(subtask1_result):
   ....
   return {'key1':value1,'key2':value2 ...}

```

**Comment by ask** [comment]
Why does the traceback include gevent?  The `--pool=gevent` pool doesn't support --maxtasksperchild, but here it seems you are combining the prefork pool with the gevent monkey patches?

**Comment by xiangmeng4geo** [comment]
Thanks , some one use  monkey.patch_socket() in our project.Now I remove all patch_socket.
But there is new problem,some task block .In the RabbitMQ console I can see some unacked messages.When I restart worker,the task will be start. 
I set CELERYD_PREFETCH_MULTIPLIER=0, but problem still there.

**Comment by xiangmeng4geo** [comment]
If I add monkey.patch_socket(),there is no message unacked,but when I remove patch_socket, some task will unacked.Is there some relationshap between gevent and rabbitmq?

**Comment by xiangmeng4geo** [comment]
Hello, I think I found the reason for the problem.
```
@app.task(soft_time_limit=360, max_retries=3)
def main_task():
     result = group([subtask1,subtask2,......]).apply_async().get() # block here
     # have to do some thing after group 
     result2 = do_something_else(result)
     return result2
@app.task
def subtask1(info):
   ....
   return {'key1':value1,'key2':value2 ...}
@app.task
def subtask2(subtask1_result):
   ....
   return {'key1':value1,'key2':value2 ...}
```
I called the ```apply_async().get() ``` method in my main task. This will cause the main task to block.The subtask called in main_task which subtask and main_task in same channel will block at the same time, other subtask is ok. It's looks like subtask waiting main_task and main_task wait subtask.
What is interesting is that gevent.monkey_patch.patch_socket () can avoid apply_async().get() blocking channel. But I don't know the inside of the principle. 
I'm going to put the main_task in a new queue. I do not know whether there is a better solution.
