### ISSUE TITLE
MongoDB backend can not handle mongodb urls with replica sets.

### ISSUE THREAD

**Issue by esc** [celery/celery#3611]
I'm trying to connect to a mongo deployment with replica sets, mostly using the documentation provided at:

http://docs.mlab.com/connecting/#replica-set-connections

The mongodb url is something along the lines of:

`mongodb://<dbuser>:<dbpassword>@ds012345-a0.mlab.com:56789,ds012345-a1.mlab.com:56790/<dbname>?replicaSet=rs-ds012345`

Note especially that the url contains a comma.

Now, when using such a url in celery as `CELERY_RESULT_BACKEND` I get something along the lines of:

```
Traceback (most recent call last):
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/virtualenvs/api/bin/tbn-api.py", line 59, in <module>
    logger.debug(app.celery.conf.humanize(with_defaults=True, censored=True))
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/celery/app/utils.py", line 179, in humanize
    for key, value in items(self.table(with_defaults, censored)))
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/celery/app/utils.py", line 171, in table
    self if with_defaults else self.without_defaults())
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/celery/app/utils.py", line 307, in filter_hidden_settings
    return {k: maybe_censor(k, v) for k, v in items(conf)}
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/celery/app/utils.py", line 307, in <dictcomp>
    return {k: maybe_censor(k, v) for k, v in items(conf)}
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/celery/app/utils.py", line 303, in maybe_censor
    return maybe_sanitize_url(value, mask=mask)
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/kombu/utils/url.py", line 92, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/kombu/utils/url.py", line 85, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "/opt/virtualenvs/api/local/lib/python2.7/site-packages/kombu/utils/url.py", line 52, in url_to_parts
    parts.port,
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '56789,ds012345-a1.mlab.com'

````

I presume that celery and kombu make assumptions about the url---namely that it doesn't contain a comma--which are not given for monogo urls with replica-sets.

Maybe there is also an alternative to configure this correctly, however I couldn't find anything in the celery documentation.

**Comment by imanhodjaev** [comment]
:+1: I have the same issue here.

**Comment by esc** [comment]
Oh, I actually found a solution to this issue, but forgot to report back. My solution is to include the URL at a later stage, like so:

```
CELERY_RESULT_BACKEND = "mongodb"
CELERY_MONGODB_BACKEND_SETTINGS = {"host": "MONGO_DB_URL_GOES_HERE",
                                   "database": "celery",
                                   "taskmeta_collection": "celery_taskmeta"}

```

I didn't read the code, but I assume that the only reason to parse the url is to obtain the protocol (in this case `mongodb`) and this bypasses that. I assume that the `host` entry will simply be passed down to `pymongo` without any interference.

@imanhodjaev can you try this and report back if it works for you too?

Might make sense to include a note in the documentation here, since we are probably not the only ones hitting this snag. Anyway, let me know.

**Comment by imanhodjaev** [comment]
@esc it works but it fail on parsing multiple nodes like

`mongodb-node1:30002,mongodb-node2:30002,mongodb-node3:30002/SOME_DB?replicaSet=rs-SOME_DB`

```
  File "/opt/metering/eggs/pymongo-2.7.2-py2.7-linux-x86_64.egg/pymongo/mongo_client.py", line 930, in _ensure_connected
    self.__ensure_member()
  File "/opt/metering/eggs/pymongo-2.7.2-py2.7-linux-x86_64.egg/pymongo/mongo_client.py", line 803, in __ensure_member
    member, nodes = self.__find_node()
  File "/opt/metering/eggs/pymongo-2.7.2-py2.7-linux-x86_64.egg/pymongo/mongo_client.py", line 863, in __find_node
    member, nodes = self.__try_node(candidate)
  File "/opt/metering/eggs/pymongo-2.7.2-py2.7-linux-x86_64.egg/pymongo/mongo_client.py", line 728, in __try_node
    % (node[0], node[1], self.__repl))
ConfigurationError: mongodb-node3:30002 is not a member of replica set rs-SOME_DB:27017
```

It can't parse the last node host with port properly.

**Comment by lein** [comment]
@imanhodjaev it works in such configuration

`CELERY_RESULT_BACKEND = "mongodb"

CELERY_MONGODB_BACKEND_SETTINGS = {
        'host': '<node1>:<port>,<node2>:<port>,<node3>:<port>/',
        'replicaSet': '<replica-set>',
        'database': 'celery',
        'taskmeta_collection': 'celery_taskmeta'
}`
