### ISSUE TITLE
Tasks with missing names cause problems downstream when iterating through them

### ISSUE THREAD

**Issue by rickwargo** [celery/celery#3615]
This will typically occur with class-based tasks, especially when converting to celery 4 and utilizing abstract_tasks. This is most likely an invalid task error and should be exposed during task registration.

## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Report
```
$ celery -A myapp report

software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.2
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```
## Steps to reproduce
file: myapp.py
```
from celery import Celery, Task

app = Celery('hello')

class MyTask(Task):
    pass

app.tasks.register(MyTask())
```
run:
```
$ celery -A myapp worker -l info
```
## Expected behavior
Should raise an error that the task is invalid

## Actual behavior
Causes a downstream error when iterating through tasks.
```
[2016-11-22 15:27:23,491: CRITICAL/MainProcess] Unrecoverable error: TypeError('unorderable types: NoneType() < str()',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/usr/local/lib/python3.5/site-packages/celery/apps/worker.py", line 143, in on_start
    self.emit_banner()
  File "/usr/local/lib/python3.5/site-packages/celery/apps/worker.py", line 159, in emit_banner
    string(self.colored.reset(self.extra_info() or '')),
  File "/usr/local/lib/python3.5/site-packages/celery/apps/worker.py", line 190, in extra_info
    tasklist = self.tasklist(include_builtins=include_builtins)
  File "/usr/local/lib/python3.5/site-packages/celery/apps/worker.py", line 183, in tasklist
    '  . {0}'.format(task) for task in sorted(self.app.tasks)
TypeError: unorderable types: NoneType() < str()
```

**Comment by ask** [comment]
I added a `app.register_task` function instead, which sets the name:

```py
from celery import Celery, Task

app = Celery('hello')

class MyTask(Task):
    pass

app.register_task(MyTask())
```
