### ISSUE TITLE
inspect stats reply KeyError

### ISSUE THREAD

**Issue by jiangrzh** [celery/celery#3621]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

        software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.2
                    billiard:3.5.0.2 py-amqp:2.1.1
        platform -> system:Linux arch:64bit, ELF imp:CPython
        loader   -> celery.loaders.app.AppLoader
        settings -> transport:amqp results:disabled

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Execute celery inspect stats reply KeyError when worker running...

## Expected behavior
Should return worker stats.

## Actual behavior
```bash
$ celery -A UTSC inspect stats
-> utsc@hostname: ERROR
         KeyError('5',)
```
--------------------------
logs report：
```bash
[2016-11-24 01:20:52,216: ERROR/MainProcess] pidbox command error: KeyError('5',)
Traceback (most recent call last):
  File "/home/workspace/UTSC/lib/python3.5/site-packages/kombu/pidbox.py", line 101, in dispatch
    reply = handle(method, arguments)
  File "/home/workspace/UTSC/lib/python3.5/site-packages/kombu/pidbox.py", line 119, in handle_call
    return self.handle(method, arguments)
  File "/home/workspace/UTSC/lib/python3.5/site-packages/kombu/pidbox.py", line 116, in handle
    return self.handlers[method](self.state, **arguments)
  File "/home/workspace/UTSC/lib/python3.5/site-packages/celery/worker/control.py", line 333, in stats
    return state.consumer.controller.stats()
  File "/home/workspace/UTSC/lib/python3.5/site-packages/celery/worker/worker.py", line 326, in stats
    info.update(self.blueprint.info(self))
  File "/home/workspace/UTSC/lib/python3.5/site-packages/celery/bootsteps.py", line 128, in info
    info.update(step.info(parent) or {})
  File "/home/workspace/UTSC/lib/python3.5/site-packages/celery/worker/components.py", line 175, in info
    return {'pool': w.pool.info if w.pool else 'N/A'}
  File "/home/workspace/UTSC/lib/python3.5/site-packages/celery/concurrency/base.py", line 164, in info
    return self._get_info()
  File "/home/workspace/UTSC/lib/python3.5/site-packages/celery/concurrency/prefork.py", line 162, in _get_info
    'writes': write_stats() if write_stats is not None else 'N/A',
  File "/home/workspace/UTSC/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 1099, in human_write_stats
    'strategy': SCHED_STRATEGY_TO_NAME[self.sched_strategy],
KeyError: '5'
```

**Comment by jiangrzh** [comment]
Sorry, I know what's the problem now，there was anther old version celery installed in the system path

**Comment by jiangrzh** [comment]
It's happen when celery worker start with Option "-O"
