### ISSUE TITLE
Retries are not sent to the same "custom" queue

### ISSUE THREAD

**Issue by mabouels** [celery/celery#3622]
## Checklist

- [x]  I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.4.0
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0

broker_url: 'redis://localhost:6379/0'
result_backend: 'redis://localhost:6379/0'
```
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
```
from celery import Celery
app = Celery('vanilla', broker='redis://localhost:6379/0', backend='redis://localhost:6379/0')

@app.task(bind=True, max_retries=3, default_retry_delay=1)
def Fail(self):
    try:
        raise AssertionError('Oh My!')
    except Exception as e:
        self.retry(exc=e)
```

Run Server1 processing the default "celery" queue:
`celery worker -A vanilla --loglevel=info 
`
Run Server2 processing the custom "worker" queue:
`celery worker -A vanilla --queues=worker --hostname=worker@%h --loglevel=info
`

Call the "Fail" task and queue it on the custom "worker" queue
`Fail.apply_async(queue='worker')
`

## Expected behavior
The retries should respect the same custom "worker" queue of the original task. This used to be the behaviour in Celery versions prior to 4.0.

## Actual behavior
While the task first ran on the server with the custom "worker" queue, the retries seem to be sent to the other server with the default "celery"!

Serve2 log (Processing the "worker" queue):
```
[2016-11-24 11:18:29,277: INFO/MainProcess] Connected to redis://localhost:6379/0
[2016-11-24 11:18:29,285: INFO/MainProcess] mingle: searching for neighbors
[2016-11-24 11:18:30,307: INFO/MainProcess] mingle: sync with 1 nodes
[2016-11-24 11:18:30,307: INFO/MainProcess] mingle: sync complete
[2016-11-24 11:18:30,315: INFO/MainProcess] worker@ott-ads-238 ready.
[2016-11-24 11:18:39,239: INFO/MainProcess] Received task: vanilla.Fail[b364f080-6aa1-4f31-808e-c5260b5ea63d]  
[2016-11-24 11:18:39,288: INFO/PoolWorker-3] Task vanilla.Fail[b364f080-6aa1-4f31-808e-c5260b5ea63d] retry: Retry in 1s: AssertionError('Oh My!',)
```

Server1 log (Processing the "celery" queue):
```
[2016-11-24 11:18:28,116: INFO/MainProcess] Connected to redis://localhost:6379/0
[2016-11-24 11:18:28,123: INFO/MainProcess] mingle: searching for neighbors
[2016-11-24 11:18:29,168: INFO/MainProcess] mingle: all alone
[2016-11-24 11:18:29,183: INFO/MainProcess] celery@ott-ads-238 ready.
[2016-11-24 11:18:29,301: INFO/MainProcess] sync with worker@ott-ads-238
[2016-11-24 11:18:39,279: INFO/MainProcess] Received task: vanilla.Fail[b364f080-6aa1-4f31-808e-c5260b5ea63d]  ETA:[2016-11-24 16:18:40.243377+00:00] 
[2016-11-24 11:18:40,395: INFO/MainProcess] Received task: vanilla.Fail[b364f080-6aa1-4f31-808e-c5260b5ea63d]  ETA:[2016-11-24 16:18:41.367465+00:00] 
[2016-11-24 11:18:40,404: INFO/PoolWorker-3] Task vanilla.Fail[b364f080-6aa1-4f31-808e-c5260b5ea63d] retry: Retry in 1s: AssertionError('Oh My!',)
[2016-11-24 11:18:41,644: INFO/MainProcess] Received task: vanilla.Fail[b364f080-6aa1-4f31-808e-c5260b5ea63d]  ETA:[2016-11-24 16:18:42.617218+00:00] 
[2016-11-24 11:18:41,647: INFO/PoolWorker-1] Task vanilla.Fail[b364f080-6aa1-4f31-808e-c5260b5ea63d] retry: Retry in 1s: AssertionError('Oh My!',)
[2016-11-24 11:18:42,733: ERROR/PoolWorker-4] Task vanilla.Fail[b364f080-6aa1-4f31-808e-c5260b5ea63d] raised unexpected: AssertionError('Oh My!',)
Traceback (most recent call last):
  File "/auto/firex-ott/celery4/lib/python3.4/site-packages/celery/app/trace.py", line 368, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/auto/firex-ott/celery4/lib/python3.4/site-packages/celery/app/trace.py", line 623, in __protected_call__
    return self.run(*args, **kwargs)
  File "/auto/firex-ott/celery4/vanilla.py", line 19, in Fail
    self.retry(exc=e)
  File "/auto/firex-ott/celery4/lib/python3.4/site-packages/celery/app/task.py", line 661, in retry
    raise_with_context(exc)
  File "/auto/firex-ott/celery4/vanilla.py", line 17, in Fail
    raise AssertionError('Oh My!')
AssertionError: Oh My!
```

While the example above uses Redis, I was able to reproduce it with pyamqp.
This only started happening in Celery 4.0

**Comment by Schweigi** [comment]
We have the same issue with Celery 4. As a workaround we pass the queue name when retrying.

`self.retry(exc=e)` => `self.retry(exc=e, queue="worker")`

**Comment by mabouels** [comment]
Thanks @ask !

**Comment by mabouels** [comment]
Thanks @Schweigi. That's what we've been doing as well as a temporary work-around, but,  it wouldn't solve the issue when the queue name itself was not known beforehand.
