### ISSUE TITLE
UnicodeEncodeError in celery logging (\xf6)

### ISSUE THREAD

**Issue by april** [celery/celery#3633]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.4.3
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

CELERY_REDIRECT_STDOUTS_LEVEL: 'WARNING'
BROKER_URL: 'redis://localhost:6379/0'
CELERY_RESULT_SERIALIZER: 'json'
CELERYD_TASK_SOFT_TIME_LIMIT: 751
CELERY_IGNORE_RESULTS: True
CELERYD_TASK_TIME_LIMIT: 1129
CELERY_ACCEPT_CONTENT: ['json']
CELERY_TASK_SERIALIZER: 'json'
```

- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I have celery running a task using requests, setup with loglevel `WARNING`.  If I requests.get('https://self-storage.virtualways.de') in my code, I get the following traceback:

```
[2016-11-30 15:37:45,932: WARNING/PoolWorker-312] --- Logging error ---
[2016-11-30 15:37:45,933: WARNING/PoolWorker-312] Traceback (most recent call last):
[2016-11-30 15:37:45,933: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 313, in _match_hostname
    match_hostname(cert, asserted_hostname)
[2016-11-30 15:37:45,934: WARNING/PoolWorker-312] File "/usr/lib/python3.4/ssl.py", line 285, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
[2016-11-30 15:37:45,934: WARNING/PoolWorker-312] ssl.CertificateError: hostname 'self-storage.virtualways.de' doesn't match either of 'www.handwerkstraum.de', 'handwerkstraum.de'
[2016-11-30 15:37:45,934: WARNING/PoolWorker-312] During handling of the above exception, another exception occurred:
[2016-11-30 15:37:45,934: WARNING/PoolWorker-312] Traceback (most recent call last):
[2016-11-30 15:37:45,934: WARNING/PoolWorker-312] File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
[2016-11-30 15:37:45,935: WARNING/PoolWorker-312] UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 516: ordinal not in range(128)
[2016-11-30 15:37:45,935: WARNING/PoolWorker-312] Call stack:
[2016-11-30 15:37:45,940: WARNING/PoolWorker-312] File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
[2016-11-30 15:37:45,941: WARNING/PoolWorker-312] File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
[2016-11-30 15:37:45,941: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/__main__.py", line 18, in <module>
    main()
[2016-11-30 15:37:45,941: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/__main__.py", line 14, in main
    _main()
[2016-11-30 15:37:45,941: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
[2016-11-30 15:37:45,941: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
[2016-11-30 15:37:45,941: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 278, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
[2016-11-30 15:37:45,941: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
[2016-11-30 15:37:45,942: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2016-11-30 15:37:45,942: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
[2016-11-30 15:37:45,942: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bin/base.py", line 241, in __call__
    ret = self.run(*args, **kwargs)
[2016-11-30 15:37:45,942: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bin/worker.py", line 256, in run
    worker.start()
[2016-11-30 15:37:45,942: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2016-11-30 15:37:45,942: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
[2016-11-30 15:37:45,942: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
[2016-11-30 15:37:45,942: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
[2016-11-30 15:37:45,943: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
[2016-11-30 15:37:45,943: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/worker/consumer/consumer.py", line 584, in start
    c.loop(*c.loop_args())
[2016-11-30 15:37:45,943: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
[2016-11-30 15:37:45,943: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
[2016-11-30 15:37:45,943: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/concurrency/asynpool.py", line 444, in _event_process_exit
    self.maintain_pool()
[2016-11-30 15:37:45,943: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/pool.py", line 1308, in maintain_pool
    self._maintain_pool()
[2016-11-30 15:37:45,943: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/pool.py", line 1300, in _maintain_pool
    self._repopulate_pool(joined)
[2016-11-30 15:37:45,943: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/pool.py", line 1285, in _repopulate_pool
    self._create_worker_process(self._avail_index())
[2016-11-30 15:37:45,944: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/concurrency/asynpool.py", line 439, in _create_worker_process
    return super(AsynPool, self)._create_worker_process(i)
[2016-11-30 15:37:45,944: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/pool.py", line 1117, in _create_worker_process
    w.start()
[2016-11-30 15:37:45,944: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/process.py", line 122, in start
    self._popen = self._Popen(self)
[2016-11-30 15:37:45,944: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2016-11-30 15:37:45,944: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2016-11-30 15:37:45,944: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2016-11-30 15:37:45,944: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/process.py", line 306, in _bootstrap
    self.run()
[2016-11-30 15:37:45,944: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/process.py", line 112, in run
    self._target(*self._args, **self._kwargs)
[2016-11-30 15:37:45,945: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/pool.py", line 290, in __call__
    sys.exit(self.workloop(pid=pid))
[2016-11-30 15:37:45,945: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/billiard/pool.py", line 359, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2016-11-30 15:37:45,945: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 531, in _fast_trace_task
    uuid, args, kwargs, request,
[2016-11-30 15:37:45,945: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 368, in trace_task
    R = retval = fun(*args, **kwargs)
[2016-11-30 15:37:45,945: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/celery/app/trace.py", line 623, in __protected_call__
    return self.run(*args, **kwargs)
[2016-11-30 15:37:45,945: WARNING/PoolWorker-312] File "/home/httpobs/httpobs/httpobs/scanner/tasks.py", line 31, in scan
    reqs = retrieve_all(hostname, cookies=headers['cookies'], headers=headers['headers'])
[2016-11-30 15:37:45,945: WARNING/PoolWorker-312] File "/home/httpobs/httpobs/httpobs/scanner/retriever/retriever.py", line 147, in retrieve_all
    https_session = __create_session('https://' + hostname + kwargs['https_port'] + kwargs['path'], **kwargs)
[2016-11-30 15:37:45,945: WARNING/PoolWorker-312] File "/home/httpobs/httpobs/httpobs/scanner/retriever/retriever.py", line 52, in __create_session
    r = s.get(url, timeout=TIMEOUT)
[2016-11-30 15:37:45,946: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
[2016-11-30 15:37:45,946: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
[2016-11-30 15:37:45,946: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
[2016-11-30 15:37:45,946: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
[2016-11-30 15:37:45,946: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
[2016-11-30 15:37:45,946: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
[2016-11-30 15:37:45,946: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
[2016-11-30 15:37:45,946: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 305, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
[2016-11-30 15:37:45,947: WARNING/PoolWorker-312] File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 317, in _match_hostname
    'Certificate: %s', asserted_hostname, cert
```

This seems to crash the master process, and thereafter celery inspect simply returns `Error: No nodes replied within time constraint.`

`sys.getdefaultencoding()` is utf-8.

## Expected behavior

Most certificate errors get handled properly by my code (and celery's logging), simply logging information about the certificate at `ERROR` level.

## Actual behavior

This particular certificate causes a stacktrace in celery's logging.  Note that a simple logger setup has no problem with this, just celery's handling of it:

```
>>> requests.get('https://self-storage.virtualways.de')
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): self-storage.virtualways.de
ERROR:requests.packages.urllib3.connection:Certificate did not match expected hostname: self-storage.virtualways.de. Certificate: {'caIssuers': ('http://crt.comodoca.com/COMODORSAOrganizationValidationSecureServerCA.crt',), 'subject': ((('countryName', 'DE'),), (('postalCode', '89077'),), (('stateOrProvinceName', 'BW'),), (('localityName', 'Ulm'),), (('streetAddress', 'Söflinger Straße 207'),), (('organizationName', 'EG-Shop GmbH'),), (('organizationalUnitName', 'Shop'),), (('organizationalUnitName', 'Authorized by United SSL'),), (('organizationalUnitName', 'InstantSSL'),), (('commonName', 'www.handwerkstraum.de'),)), 'serialNumber': '540A934851941CD6C2485635EA0BB93C', 'issuer': ((('countryName', 'GB'),), (('stateOrProvinceName', 'Greater Manchester'),), (('localityName', 'Salford'),), (('organizationName', 'COMODO CA Limited'),), (('commonName', 'COMODO RSA Organization Validation Secure Server CA'),)), 'notBefore': 'Sep  8 00:00:00 2016 GMT', 'OCSP': ('http://ocsp.comodoca.com',), 'subjectAltName': (('DNS', 'www.handwerkstraum.de'), ('DNS', 'handwerkstraum.de')), 'notAfter': 'Sep  8 23:59:59 2018 GMT', 'crlDistributionPoints': ('http://crl.comodoca.com/COMODORSAOrganizationValidationSecureServerCA.crl',), 'version': 3}
```

**Comment by marumari** [comment]
Also, requests is at the latest public version (2.12.2)

**Comment by marumari** [comment]
This is happening on an Ubuntu 14.04 (trusty) LTS system with Python 3.4.3.  On my Macbook (OS X 10.12.1, Python 3.5.2), it doesn't seem to happen.

**Comment by georgepsarakis** [comment]
@april perhaps this issue can now be closed?

**Comment by april** [comment]
Is it fixed?  I haven't seen any references to this bug in any commits.
I'd rather not have to turn down my logging so that celery doesn't crash.

On Apr 8, 2017, at 12:03 PM, George Psarakis <notifications@github.com>
wrote:

@april <https://github.com/april> perhaps this issue can now be closed?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/celery/celery/issues/3633#issuecomment-292731346>, or mute
the thread

**Comment by auvipy** [comment]
can you re-verify this on top of master?

**Comment by april** [comment]
Are we talking `HEAD` or simply the newest published version of celery?

**Comment by georgepsarakis** [comment]
The suggestion refers to installation from Github directly (latest commit on `master` branch), not PyPI.

**Comment by auvipy** [comment]
this might be a serialization issue
