### ISSUE TITLE
Running "celery multi" on windows conflicts with path

### ISSUE THREAD

**Issue by Nekorooni** [celery/celery#3639]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.2
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Windows arch:32bit, WindowsPE imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp:///

result_backend: 'amqp:///'
```
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
1. Open cmd in project folder
2. Run `celery multi start 4 -A xxx -l info -c4 --pidfile="C:\%n.pid"`

## Expected behavior
Celery starts 4 workers.

## Actual behavior
Celery fails starting a worker 4 times.

```CMD
C:\Users\xxx\xxx>celery multi start 4 -A xxx-c4 --pidfile="C:\%n.pid"
celery multi v4.0.0 (latentcall)
> Starting nodes...
usage: c:\program files (x86)\python35-32\lib\site-packages\celery\bin\celery.py worker [options]
c:\program files (x86)\python35-32\lib\site-packages\celery\bin\celery.py: error: unrecognized arguments: files (x86)\python35-32\python.exe
        > celery1@DESKTOP-2738VCR: * Child terminated with exit code 2
FAILED
usage: c:\program files (x86)\python35-32\lib\site-packages\celery\bin\celery.py worker [options]
c:\program files (x86)\python35-32\lib\site-packages\celery\bin\celery.py: error: unrecognized arguments: files (x86)\python35-32\python.exe
        > celery2@DESKTOP-2738VCR: * Child terminated with exit code 2
FAILED
usage: c:\program files (x86)\python35-32\lib\site-packages\celery\bin\celery.py worker [options]
c:\program files (x86)\python35-32\lib\site-packages\celery\bin\celery.py: error: unrecognized arguments: files (x86)\python35-32\python.exe
        > celery3@DESKTOP-2738VCR: * Child terminated with exit code 2
FAILED
usage: c:\program files (x86)\python35-32\lib\site-packages\celery\bin\celery.py worker [options]
c:\program files (x86)\python35-32\lib\site-packages\celery\bin\celery.py: error: unrecognized arguments: files (x86)\python35-32\python.exe
        > celery4@DESKTOP-2738VCR: * Child terminated with exit code 2
FAILED
```

**Comment by alimp5** [comment]
5.2.7 (dawn-chorus).
windows 10 - latest build.
python 3.8.10

`celery multi start 2 -c 6 -A ea_games worker -l info --pool=eventlet`:


```
> Starting nodes...
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "f:\ea_auto_snipe\lib\site-packages\celery\__main__.py", line 19, in <module>
    main()
  File "f:\ea_auto_snipe\lib\site-packages\celery\__main__.py", line 15, in main
    sys.exit(_main())
  File "f:\ea_auto_snipe\lib\site-packages\celery\bin\celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "f:\ea_auto_snipe\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "f:\ea_auto_snipe\lib\site-packages\celery\bin\base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
  File "f:\ea_auto_snipe\lib\site-packages\celery\bin\worker.py", line 331, in worker
    return detach(sys.executable,
  File "f:\ea_auto_snipe\lib\site-packages\celery\bin\worker.py", line 120, in detach
    with detached(logfile, pidfile, uid, gid, umask, workdir, fake,
  File "f:\ea_auto_snipe\lib\site-packages\celery\platforms.py", line 412, in detached
    raise RuntimeError('This platform does not support detach.')
RuntimeError: This platform does not support detach.
        > 2@linux11-pc: * Child terminated with exit code 1
FAILED
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "f:\ea_auto_snipe\lib\site-packages\celery\__main__.py", line 19, in <module>
    main()
  File "f:\ea_auto_snipe\lib\site-packages\celery\__main__.py", line 15, in main
    sys.exit(_main())
  File "f:\ea_auto_snipe\lib\site-packages\celery\bin\celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "f:\ea_auto_snipe\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "f:\ea_auto_snipe\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "f:\ea_auto_snipe\lib\site-packages\celery\bin\base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
  File "f:\ea_auto_snipe\lib\site-packages\celery\bin\worker.py", line 331, in worker
    return detach(sys.executable,
  File "f:\ea_auto_snipe\lib\site-packages\celery\bin\worker.py", line 120, in detach
    with detached(logfile, pidfile, uid, gid, umask, workdir, fake,
  File "f:\ea_auto_snipe\lib\site-packages\celery\platforms.py", line 412, in detached
    raise RuntimeError('This platform does not support detach.')
RuntimeError: This platform does not support detach.
        > worker@linux11-pc: * Child terminated with exit code 1
FAILED

```
