### ISSUE TITLE
None and int type comparison in apps/worker.py, Worker.extra_info

### ISSUE THREAD

**Issue by acushner-xaxis** [celery/celery#3641]
## Checklist

- [x] i can't do this because it happens when i spawn celery from airflow (`airflow worker`), but the celery version is 4.0.0, python version 3.5., airflow version 1.7.3, on mac os 10.11.5
- [x] it exists in master. the problem happens here in `apps/workers.py`:  
```
    def extra_info(self):
        # ERROR BELOW when self.loglevel is None
        if self.loglevel <= logging.INFO:
            include_builtins = self.loglevel <= logging.DEBUG
            tasklist = self.tasklist(include_builtins=include_builtins)
            return EXTRA_INFO_FMT.format(tasks=tasklist)
```

## Steps to reproduce
run `airflow worker`

## Expected behavior
run the actual celery workers

## Actual behavior

```[2016-12-01 12:24:08,468: CRITICAL/MainProcess] Unrecoverable error: TypeError('unorderable types: NoneType() <= int()',)
Traceback (most recent call last):
  File "/Users/xaxis/virtualenvs/spark/lib/python3.5/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/xaxis/virtualenvs/spark/lib/python3.5/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/Users/xaxis/virtualenvs/spark/lib/python3.5/site-packages/celery/apps/worker.py", line 143, in on_start
    self.emit_banner()
  File "/Users/xaxis/virtualenvs/spark/lib/python3.5/site-packages/celery/apps/worker.py", line 159, in emit_banner
    string(self.colored.reset(self.extra_info() or '')),
  File "/Users/xaxis/virtualenvs/spark/lib/python3.5/site-packages/celery/apps/worker.py", line 188, in extra_info
    if self.loglevel <= logging.INFO:
TypeError: unorderable types: NoneType() <= int()
```

## Steps to fix
just add a check to make sure `self.loglevel` is not None:
```
    def extra_info(self):
        if self.loglevel is None: 
            return
        if self.loglevel <= logging.INFO:
            include_builtins = self.loglevel <= logging.DEBUG
            tasklist = self.tasklist(include_builtins=include_builtins)
            return EXTRA_INFO_FMT.format(tasks=tasklist)
```

NOTE: i tested this and it works. even though python 2 allows `None` and `int` comparisons, it fails in python 3. additionally, i know that i can only reproduce this using airflow, but regardless, there shouldn't be `None` and `int` comparisons in the code.

**Comment by acushner-xaxis** [comment]
another solution that would be backwards-compatible (because, in python 2, `None` is less than everything except itself), would be:
```
    def extra_info(self):
        if self.loglevel is None or self.loglevel <= logging.INFO:
            include_builtins = self.loglevel <= logging.DEBUG
            tasklist = self.tasklist(include_builtins=include_builtins)
            return EXTRA_INFO_FMT.format(tasks=tasklist)
```
