### ISSUE TITLE
Can't pickle <class 'billiard.pool.Pool.__init__.<locals>.Process'>: attribute lookup Process on billiard.pool failed

### ISSUE THREAD

**Issue by pszawa** [celery/celery#3655]
```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.4.3
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Windows arch:32bit, WindowsPE imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

broker_url: 'amqp://qnoonhth:********@chicken.rmq.cloudamqp.com:5672/qnoonhth'
```
## Steps to reproduce

Fresh virtualenv with celery

```
from celery import Celery
app = Celery('tasks', broker='amqp://qnoonhth:xxxxxx@chicken.rmq.cloudamqp.com/qnoonhth')
@app.task
def add(x, y):
    return x + y
```
## Expected behavior

Run without errors

## Actual behavior

```
(mojenv) Q:\tmp\testowypython>celery -A tasks report

software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.4.3
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Windows arch:32bit, WindowsPE imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

broker_url: 'amqp://qnoonhth:********@chicken.rmq.cloudamqp.com:5672/qnoonhth'


(mojenv) Q:\tmp\testowypython>celery -A tasks worker -l info

 -------------- celery@duzy v4.0.0 (latentcall)
---- **** -----
--- * ***  * -- Windows-7-6.1.7601-SP1 2016-12-06 11:35:07
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x35282b0
- ** ---------- .> transport:   amqp://qnoonhth:**@chicken.rmq.cloudamqp.com:5672/qnoonhth
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . tasks.add

[2016-12-06 11:35:07,617: CRITICAL/MainProcess] Unrecoverable error: PicklingError("Can't pickle <class 'billiard.pool.Pool.__init__.<locals>.Process'>: attribute lookup Process on billiard.poold",)
Traceback (most recent call last):
  File "q:\tmp\testowypython\mojenv\lib\site-packages\celery\worker\worker.py", line 203, in start
    self.blueprint.start(self)
  File "q:\tmp\testowypython\mojenv\lib\site-packages\celery\bootsteps.py", line 119, in start
    step.start(parent)
  File "q:\tmp\testowypython\mojenv\lib\site-packages\celery\bootsteps.py", line 370, in start
    return self.obj.start()
  File "q:\tmp\testowypython\mojenv\lib\site-packages\celery\concurrency\base.py", line 131, in start
    self.on_start()
  File "q:\tmp\testowypython\mojenv\lib\site-packages\celery\concurrency\prefork.py", line 112, in on_start
    **self.options)
  File "q:\tmp\testowypython\mojenv\lib\site-packages\billiard\pool.py", line 1008, in __init__
    self._create_worker_process(i)
  File "q:\tmp\testowypython\mojenv\lib\site-packages\billiard\pool.py", line 1117, in _create_worker_process
    w.start()
  File "q:\tmp\testowypython\mojenv\lib\site-packages\billiard\process.py", line 122, in start
    self._popen = self._Popen(self)
  File "q:\tmp\testowypython\mojenv\lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
  File "q:\tmp\testowypython\mojenv\lib\site-packages\billiard\popen_spawn_win32.py", line 79, in __init__
    reduction.dump(process_obj, to_child)
  File "q:\tmp\testowypython\mojenv\lib\site-packages\billiard\reduction.py", line 99, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'billiard.pool.Pool.__init__.<locals>.Process'>: attribute lookup Process on billiard.pool failed

(mojenv) Q:\tmp\testowypython>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "q:\tmp\testowypython\mojenv\lib\site-packages\billiard\spawn.py", line 159, in spawn_main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "q:\tmp\testowypython\mojenv\lib\site-packages\billiard\reduction.py", line 121, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] Parametr jest niepoprawny
```

**Comment by bpe2004** [comment]
same issue here with python 3.5.1 on Windows 10 using the steps from the tutorial.

software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.1 billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Windows arch:64bit, WindowsPE imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
broker_url: 'amqp://guest:********@localhost:5672//'

**Comment by Rooon** [comment]
Also have this issue, also on windows 10. Celery 3.1 still works.

**Comment by jijoy** [comment]
I too have same issue. Is it fixed yet ?

**Comment by Rooon** [comment]
Celery 4.x stopped officially supporting windows, but is open for patches.
http://docs.celeryproject.org/en/latest/faq.html#does-celery-support-windows

**Comment by auvipy** [comment]
we re-added windows
