### ISSUE TITLE
python3 celery4 Control command error: EncodeError

### ISSUE THREAD

**Issue by HatBoy** [celery/celery#3667]
I use Python3, Celery 4.0.0, when I execte `:celery -A prok inspect  active`, I have this Error：

```
[2016-12-09 15:32:01,837: ERROR/MainProcess] Control command error: EncodeError(TypeError('b\'[[], {}, {"callbacks": null, "errbacks": null, "chord": null, "chain": null}]\' is not JSON serializable',),)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'[[], {}, {"callbacks": null, "errbacks": null, "chord": null, "chain": null}]' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/pidbox.py", line 42, in on_message
    self.node.handle_message(body, message)
  File "/usr/local/lib/python3.5/dist-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/usr/local/lib/python3.5/dist-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/usr/local/lib/python3.5/dist-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/usr/local/lib/python3.5/dist-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/usr/local/lib/python3.5/dist-packages/kombu/messaging.py", line 167, in publish
    compression, headers)
  File "/usr/local/lib/python3.5/dist-packages/kombu/messaging.py", line 249, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/vine/five.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
kombu.exceptions.EncodeError: b'[[], {}, {"callbacks": null, "errbacks": null, "chord": null, "chain": null}]' is not JSON serializable
[2016-12-09 15:32:01,845: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'can_read'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 584, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/dist-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 1038, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 670, in _receive
    while c.connection.can_read(timeout=0):
AttributeError: 'NoneType' object has no attribute 'can_read'
```
Why ? thank you

**Comment by ziXiong** [comment]
Something similar to you。
I‘m using python3.5, celery4.0.1， using settings 
```
CELERY_ACCEPT_CONTENT = ['pickle']
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_SERIALIZER = 'pickle'
```
when I  inspect scheduled in the shell。I got Error lile

```
[2016-12-10 14:24:02,052: ERROR/MainProcess] Control command error: EncodeError(TypeError("b'\\x80\\x02)}q\\x00(X\\x0e\\x00\\x00\\x00is_hello_firstq\\x01\\x89X\\n\\x00\\x00\\x00to_user_idq\\x02cutils.common.base\\nIdInt\\nq\\x03K>\\x85q\\x04\\x81q\\x05X\\x07\\x00\\x00\\x00contentq\\x06X$\\x00\\x00\\x00e196e478-111d-4002-9af7-f12b171dbdc0q\\x07X\\x0c\\x00\\x00\\x00from_user_idq\\x08K X\\r\\x00\\x00\\x00is_first_wordq\\t\\x88X\\x08\\x00\\x00\\x00msg_typeq\\nccore_im.constant\\nEMsgType\\nq\\x0bX\\x05\\x00\\x00\\x00audioq\\x0c\\x85q\\rRq\\x0eu}q\\x0f(X\\x05\\x00\\x00\\x00chordq\\x10NX\\x08\\x00\\x00\\x00errbacksq\\x11NX\\x05\\x00\\x00\\x00chainq\\x12NX\\t\\x00\\x00\\x00callbacksq\\x13Nu\\x87q\\x14.' is not JSON serializable",),)
Traceback (most recent call last):
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/utils/json.py", line 72, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'\x80\x02)}q\x00(X\x0e\x00\x00\x00is_hello_firstq\x01\x89X\n\x00\x00\x00to_user_idq\x02cutils.common.base\nIdInt\nq\x03K>\x85q\x04\x81q\x05X\x07\x00\x00\x00contentq\x06X$\x00\x00\x00e196e478-111d-4002-9af7-f12b171dbdc0q\x07X\x0c\x00\x00\x00from_user_idq\x08K X\r\x00\x00\x00is_first_wordq\t\x88X\x08\x00\x00\x00msg_typeq\nccore_im.constant\nEMsgType\nq\x0bX\x05\x00\x00\x00audioq\x0c\x85q\rRq\x0eu}q\x0f(X\x05\x00\x00\x00chordq\x10NX\x08\x00\x00\x00errbacksq\x11NX\x05\x00\x00\x00chainq\x12NX\t\x00\x00\x00callbacksq\x13Nu\x87q\x14.' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/celery/worker/pidbox.py", line 42, in on_message
    self.node.handle_message(body, message)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/vine/five.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/utils/json.py", line 72, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/harley/.yue-env/lib/python3.5/site-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
kombu.exceptions.EncodeError: b'\x80\x02)}q\x00(X\x0e\x00\x00\x00is_hello_firstq\x01\x89X\n\x00\x00\x00to_user_idq\x02cutils.common.base\nIdInt\nq\x03K>\x85q\x04\x81q\x05X\x07\x00\x00\x00contentq\x06X$\x00\x00\x00e196e478-111d-4002-9af7-f12b171dbdc0q\x07X\x0c\x00\x00\x00from_user_idq\x08K X\r\x00\x00\x00is_first_wordq\t\x88X\x08\x00\x00\x00msg_typeq\nccore_im.constant\nEMsgType\nq\x0bX\x05\x00\x00\x00audioq\x0c\x85q\rRq\x0eu}q\x0f(X\x05\x00\x00\x00chordq\x10NX\x08\x00\x00\x00errbacksq\x11NX\x05\x00\x00\x00chainq\x12NX\t\x00\x00\x00callbacksq\x13Nu\x87q\x14.' is not JSON serializable
```

first time to use celery, this confused me。

**Comment by HatBoy** [comment]
How did you solve this problem?

**Comment by syphar** [comment]
we're also stumbling into this error, message format is `pickle`, celery is `4.0.1`. 

For is it seems to be related to workflows (chain/chord), but not sure how
