### ISSUE TITLE
Generating argsrepr / kwargsrepr produces a UnicodeDecodeError

### ISSUE THREAD

**Issue by mihajenko** [celery/celery#3676]
## Checklist

* Ubuntu 14.04
* Python 2.7  (Python 3 probably not affected)
* Celery 4.0.1
* Default configuration option: task_protocol = 2

## Error traceback

```
[2016-12-12 03:31:40,834: ERROR/MainProcess] Task myproj.tasks.get_data[806a5db4-7757-432b-b248-29c7d0199d89] raised unexpected: UnicodeDecodeError('ascii', '<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"\n\txmlns:content="http://purl.org/rss/1.0/modules/content/"\n\txmlns:wfw="http://wellformedweb.org/CommentAPI/"\n\txmlns:dc="http://purl.org/dc/elements/1.1/"\n\txmlns:atom="http://www.w3.org/2005/Atom"\n\txmlns:sy="http://purl.org/rss/1.0/modules/syndication/"\n\txmlns:slash="http://purl.org/rss/1.0/modules/slash/"\n\txmlns:georss="http://www.georss.org/georss" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:media="http://search.yahoo.com/mrss/"\n\t>\n\n<channel>\n\t<title>La Cri\xc3\xa9e : p\xc3\xa9riodiques en ligne</title>\n\t<atom:link href="https://periodiques.wordpress.com/feed/" rel="self" type="application/rss+xml" />\n\t<link>https://periodiques.wordpress.com</link>\n\t<description>&#34;...et tout s&#039;enchev\xc3\xaatra dans un d\xc3\xa9sordre impeccable...&#34;</description>\n\t<lastBuildDate>Fri, 25 Nov 2016 09:08:44 +0000</lastBuildDate>\n\t<language>fr-FR</language>\n\t<sy:updatePeriod>hourly</sy:updatePeriod>\n\t<sy:updateFrequency>1</s', 533, 534, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/home/mihaj/venv/myproj/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mihaj/venv/myproj/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mihaj/git/myproj/myproj/tasks.py", line 586, in get_feed_data
    parse_feed_data.apply_async((url, headers_idx, content, chain_id,))
  File "/home/mihaj/venv/myproj/lib/python2.7/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/home/mihaj/venv/myproj/lib/python2.7/site-packages/celery/app/base.py", line 729, in send_task
    root_id, parent_id, shadow, chain,
  File "/home/mihaj/venv/myproj/lib/python2.7/site-packages/celery/app/amqp.py", line 337, in as_task_v2
    argsrepr = saferepr(args, self.argsrepr_maxsize)
  File "/home/mihaj/venv/myproj/lib/python2.7/site-packages/celery/utils/saferepr.py", line 94, in saferepr
    o, maxlen=maxlen, maxlevels=maxlevels, seen=seen
  File "/home/mihaj/venv/myproj/lib/python2.7/site-packages/celery/utils/saferepr.py", line 194, in _saferepr
    val = _format_chars(token.value, maxlen)
  File "/home/mihaj/venv/myproj/lib/python2.7/site-packages/celery/utils/saferepr.py", line 167, in _format_chars
    return "'{0}'".format(truncate(val, maxlen))
  File "/home/mihaj/venv/myproj/lib/python2.7/site-packages/celery/utils/text.py", line 100, in truncate
    return s[:maxlen].rsplit(' ', 1)[0] + suffix
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 533: ordinal not in range(128)
```

## Steps to reproduce

Send a task with an argument including a non-ASCII encoded byte string value (mine were UTF-8 encoded).

## Expected behavior

Task is sent, args / kwargs are traversed and decoded to argsrepr / kwargsrepr.

## Actual behavior

Task is sent, args / kwargs are traversed, decoding of non-ASCII encoded byte string argument values raises a UnicodeDecodeError.

## Workarounds

1. Use task_protocol = 1
2. Set Celery.amqp instance properties argsrepr_maxsize / kwargsrepr_maxsize to 0

**Comment by skob** [comment]
Same here on 4.2.1 celery

**Comment by thedrow** [comment]
@skob Please open a new issue about it.
