### ISSUE TITLE
Incorrect handling of tasks with keyword arguments

### ISSUE THREAD

**Issue by rsichny** [celery/celery#3678]
Probably the problem is this: https://github.com/celery/celery/pull/3658

## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

### celery report
```
software -> celery:4.0.1 (latentcall) kombu:4.0.1 py:3.5.2
            billiard:3.5.0.2 memory:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:memory results:cache+memory:///

result_backend: 'cache+memory:///'
broker_url: 'memory://localhost//'
```

### Python code

```
from celery import Celery

app = Celery(broker="memory://", backend="cache+memory://")

@app.task
def test_func(foo, *args, bar=''):
    return foo
```

### Reproduce with
```
res = test_func.delay("")
```

## Expected behavior

AsyncResult should be returned

## Actual behavior

```
>>> test_func.delay("")
Traceback (most recent call last):
  File "_confidential_.env/lib/python3.5/site-packages/celery/local.py", line 317, in _get_current_object
    return object.__getattribute__(self, '__thing')
AttributeError: 'PromiseProxy' object has no attribute '__thing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_confidential_.env/lib/python3.5/site-packages/celery/local.py", line 146, in __getattr__
    return getattr(self._get_current_object(), name)
  File "_confidential_.env/lib/python3.5/site-packages/celery/local.py", line 319, in _get_current_object
    return self.__evaluate__()
  File "_confidential_.env/lib/python3.5/site-packages/celery/local.py", line 349, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "_confidential_.env/lib/python3.5/site-packages/celery/local.py", line 109, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "_confidential_.env/lib/python3.5/site-packages/celery/app/base.py", line 453, in _task_from_fun
    '__header__': staticmethod(head_from_fun(fun, bound=bind)),
  File "_confidential_.env/lib/python3.5/site-packages/celery/utils/functional.py", line 281, in head_from_fun
    exec(definition, namespace)
  File "<string>", line 2
    def test_func(foo, *args, *, bar="0"):
                              ^
SyntaxError: invalid syntax
```

**Comment by rsichny** [comment]
probably the fix is to change https://github.com/celery/celery/blob/master/celery/utils/functional.py#L249 to the following:

```python
    return ', '.join(filter(None, [
        ', '.join(positional),
        ', '.join('{0}={1}'.format(k, v) for k, v in optional),
        '*{0}'.format(spec.varargs) if spec.varargs else None,
        '**{0}'.format(spec.varkw) if spec.varkw else None,
        '*' if (kwonlyargs or kwonlyargs_optional) and not spec.varargs else None, # this is the changed line
        ', '.join(kwonlyargs) if kwonlyargs else None,
        ', '.join('{0}="{1}"'.format(k, v) for k, v in kwonlyargs_optional),
    ]))
```

**Comment by nathanbedford** [comment]
We upgraded from Celery v4 to v5 (5.0.1) to try and 'fix' this issue too.  Thought we were free from it but found that we're still seeing this error occasionally (only in production of course).

We can't reproduce this locally.  Anyone else running into this?

Our set up:
* We're using Python 3.6.8
* Running in EC2 instances (AWS Elastic Beanstalk) 

```
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 301, in _get_current_object
    return object.__getattribute__(self, '__thing')
AttributeError: 'PromiseProxy' object has no attribute '__thing'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 41, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 41, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'loader'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/trace.py", line 409, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/python/bundle/2/app/Server/__init__.py", line 61, in __call__
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/trace.py", line 701, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/opt/python/bundle/2/app/Server/tasks/courses.py", line 34, in delete_module_item
  File "/opt/python/bundle/2/app/Server/models/courses.py", line 618, in delete
  File "/opt/python/bundle/2/app/Server/models/courses.py", line 608, in revoke_autograde_task
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 143, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 303, in _get_current_object
    return self.__evaluate__()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 333, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/local.py", line 105, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 441, in _task_from_fun
    task.bind(self)  # connects task to this app
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/task.py", line 332, in bind
    setattr(cls, attr_name, conf[config_name])
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/utils/collections.py", line 420, in __getitem__
    return getitem(k)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/utils/collections.py", line 264, in __getitem__
    return mapping[_key]
  File "/opt/python/run/venv/lib64/python3.6/collections/__init__.py", line 987, in __getitem__
    if key in self.data:
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 43, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 136, in data
    return self.callback()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 897, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 907, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/objects.py", line 43, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/app/base.py", line 1196, in loader
    return get_loader_cls(self.loader_cls)(app=self)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/loaders/__init__.py", line 18, in get_loader_cls
    return symbol_by_name(loader, LOADER_ALIASES, imp=import_from_cwd)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/utils/imports.py", line 106, in import_from_cwd
    with cwd_in_path():
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/celery/utils/imports.py", line 57, in cwd_in_path
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```
