### ISSUE TITLE
Celery cannot parse platform.release() "4.4.21+"

### ISSUE THREAD

**Issue by msimon** [celery/celery#3691]
When running celery on Google container VM image, with Linux kernel 4.4.21+ the code in /usr/local/lib/python3.5/site-packages/amqp/platform.py fails to parse '21+' as a int.

It can be fix by updating to code to:
`tuple(map(lambda x: int(x.replace("+", "")), platform.release().split('-')[0].split('.')))`

$> uname -r (same value that platform.release() returned).
4.4.21+

$> celery worker

> Traceback (most recent call last):
>   File "/usr/local/bin/celery", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.5/site-packages/celery/__main__.py", line 13, in main
>     from celery.bin.celery import main as _main
>   File "/usr/local/lib/python3.5/site-packages/celery/bin/__init__.py", line 2, in <module>
>     from .base import Option
>   File "/usr/local/lib/python3.5/site-packages/celery/bin/base.py", line 17, in <module>
>     from celery import VERSION_BANNER, Celery, maybe_patch_concurrency
>   File "<frozen importlib._bootstrap>", line 1013, in _handle_fromlist
>   File "/usr/local/lib/python3.5/site-packages/celery/local.py", line 509, in __getattr__
>     module = __import__(self._object_origins[name], None, None, [name])
>   File "/usr/local/lib/python3.5/site-packages/celery/app/__init__.py", line 5, in <module>
>     from celery import _state
>   File "/usr/local/lib/python3.5/site-packages/celery/_state.py", line 15, in <module>
>     from celery.utils.threads import LocalStack
>   File "/usr/local/lib/python3.5/site-packages/celery/utils/__init__.py", line 10, in <module>
>     from .nodenames import worker_direct, nodename, nodesplit
>   File "/usr/local/lib/python3.5/site-packages/celery/utils/nodenames.py", line 7, in <module>
>     from kombu.entity import Exchange, Queue
>   File "/usr/local/lib/python3.5/site-packages/kombu/entity.py", line 6, in <module>
>     from .abstract import MaybeChannelBound, Object
>   File "/usr/local/lib/python3.5/site-packages/kombu/abstract.py", line 6, in <module>
>     from .connection import maybe_channel
>   File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 15, in <module>
>     from kombu import exceptions
>   File "/usr/local/lib/python3.5/site-packages/kombu/exceptions.py", line 6, in <module>
>     from amqp import ChannelError, ConnectionError, ResourceError
>   File "/usr/local/lib/python3.5/site-packages/amqp/__init__.py", line 47, in <module>
>     from .connection import Connection  # noqa
>   File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 40, in <module>
>     from .transport import Transport
>   File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 31, in <module>
>     from .platform import SOL_TCP, TCP_USER_TIMEOUT, HAS_TCP_USER_TIMEOUT
>   File "/usr/local/lib/python3.5/site-packages/amqp/platform.py", line 16, in <module>
>     int, platform.release().split('-')[0].split('.')))
> ValueError: invalid literal for int() with base 10: '21+'
>

**Comment by msimon** [comment]
Wrong project, it's related to ampq and not celery. Sorry.
