### ISSUE TITLE
Django +Celery +SQS -> boto.exception.SQSError: SQSError: 599 gnutls_handshake()

### ISSUE THREAD

**Issue by tyapkov** [celery/celery#3701]
I have Django app in Production working together with Celery and Amazon SQS. Every day in my celery logs I can see that there was SSL error:

    [2016-12-14 16:06:28,917: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
    Traceback (most recent call last):
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 318, in start
        blueprint.start(self)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
        step.start(parent)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 584, in start
        c.loop(*c.loop_args())
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/celery/worker/loops.py", line 88, in asynloop
        next(loop)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/kombu/async/hub.py", line 284, in create_loop
        poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/kombu/async/hub.py", line 137, in fire_timers
        entry()
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/kombu/async/timer.py", line 68, in __call__
        return self.fun(*self.args, **self.kwargs)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/kombu/async/timer.py", line 127, in _reschedules
        return fun(*args, **kwargs)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/kombu/async/http/curl.py", line 108, in _timeout_check
        self._process_pending_requests()
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/kombu/async/http/curl.py", line 132, in _process_pending_requests
        self._process(curl, errno, reason)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/kombu/async/http/curl.py", line 178, in _process
        buffer=buffer, effective_url=effective_url, error=error,
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/vine/promises.py", line 146, in __call__
        svpending(*ca, **ck)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/vine/promises.py", line 139, in __call__
        return self.throw()
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/vine/promises.py", line 136, in __call__
        retval = fun(*final_args, **final_kwargs)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/vine/funtools.py", line 100, in _transback
        return callback(ret)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/vine/promises.py", line 139, in __call__
        return self.throw()
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/vine/promises.py", line 136, in __call__
        retval = fun(*final_args, **final_kwargs)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/vine/funtools.py", line 98, in _transback
        callback.throw()
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/vine/funtools.py", line 96, in _transback
        ret = filter_(*args + (ret,), **kwargs)
      File "/home/ubuntu/virtualenvs/env/lib/python3.5/site-packages/kombu/async/aws/connection.py", line 269, in _on_list_ready
        raise self._for_status(response, body)
    boto.exception.SQSError: SQSError: 599 gnutls_handshake() failed: An unexpected TLS packet was received.

Sometimes queues are crashing after this message and I have to restart my Celery workers. In general I am not sure if Celery tasks are running and executed correctly after I get this error.

Does anybody know how to solve it?

**Comment by adamn** [comment]
Are you using libcurl4-gnutls-dev as the underlying curl?  Maybe try libcurl4-openssl-dev?  It's unfortunate that kombu is using pycurl to interact with sqs (at least I think that's how it works) instead of boto3 but such is life.

**Comment by tyapkov** [comment]
@adamn thanks! you are actually right. I am testing right now reinstalled libcurl + openssl instead of gnutls. If I won't get any disconnections in next days then I assume it is a working solution.

**Comment by georgepsarakis** [comment]
@adamn just a clarification: the Kombu SQS transport **does** use [boto](https://github.com/celery/kombu/blob/master/kombu/transport/SQS.py#L95) in order to interact with the AWS service.

**Comment by adamn** [comment]
@georgepsarakis What function is using `async.http.curl` and why is it in the traceback showing an `SQSError`?

**Comment by georgepsarakis** [comment]
I think this [module](https://github.com/celery/kombu/blob/master/kombu/async/aws/connection.py#L9) extends `boto` request classes, to enable asynchronous operations using callbacks.

See also the parent classes for [AsyncAWSQueryConnection](https://github.com/celery/kombu/blob/master/kombu/async/aws/connection.py#L218).

**Comment by villasv** [comment]
So, was the suggested fix confirmed?

**Comment by georgepsarakis** [comment]
@adamn @villasv SQS transport uses `boto3` in latest version (v4.1.0) .

**Comment by villasv** [comment]
@georgepsarakis Yes, in fact installing `celery[sqs]` apparently won't install that as dependency. I've installed `boto3` manually and solved the dependency problem, but still I get the `599` thing happening.

**Comment by georgepsarakis** [comment]
@villasv very good observation! We certainly need to update the requirements file for SQS to use `boto3`: https://github.com/celery/celery/blob/fa6269f7f3e97985bb93ccbf57161373e4646ff3/requirements/extras/sqs.txt

**Comment by georgepsarakis** [comment]
@villasv I found some resources on the issue:
- https://bugs.launchpad.net/ubuntu/+source/pycurl/+bug/926548
- https://github.com/xmendez/wfuzz/wiki/PyCurlSSLBug
- https://askubuntu.com/questions/186847/error-gnutls-handshake-failed-when-connecting-to-https-servers
- https://stackoverflow.com/questions/1942719/pycurl-tls-handshake-error

This seems as an issue with your version of PyCurl and GnuTLS / OpenSSL linked libraries on your system. Can you please share the versions for these libraries and your exact OS?

**Comment by villasv** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

$ pip3 show pycurl
Name: pycurl
Version: 7.43.0
Summary: PycURL -- A Python Interface To The cURL library
Home-page: http://pycurl.io/
Author: Oleg Pudeyev
Author-email: oleg@bsdpower.com
License: LGPL/MIT
Location: /usr/lib/python3/dist-packages
Requires:

$ dpkg --list | grep ssl
ii  libgnutls-openssl27:amd64        3.4.10-4ubuntu1.2                          amd64        GNU TLS library - OpenSSL wrapper
ii  libssl1.0.0:amd64                1.0.2g-1ubuntu4.6                          amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                          1.0.2g-1ubuntu4.6                          amd64        Secure Sockets Layer toolkit - cryptographic utility

$ dpkg --list | grep tls
ii  libcurl3-gnutls:amd64            7.47.0-1ubuntu2.2                          amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libgnutls-openssl27:amd64        3.4.10-4ubuntu1.2                          amd64        GNU TLS library - OpenSSL wrapper
ii  libgnutls30:amd64                3.4.10-4ubuntu1.2                          amd64        GNU TLS library - main runtime library
```

**Comment by villasv** [comment]
Just remembered to reach back on this issue... a few months late only.

> @georgepsarakis This  seems as an issue with your version of PyCurl and GnuTLS / OpenSSL  linked libraries on your system.

Indeed, made it work using
```pip install --no-cache-dir --compile --ignore-installed --install-option="--with-nss" pycurl```

**Comment by georgepsarakis** [comment]
@villasv great, thanks for sharing the solution :smile: !
