### ISSUE TITLE
StopIteration() after a few minutes of workers job

### ISSUE THREAD

**Issue by Katharsis** [celery/celery#3729]
Hi,

~20 minutes from the start of 4 workers with 4 processes per worker I got StopIteration().

I'm using PyPy2 5.6 x64 on Debian 8. Workers are using venv:

* amqp (1.4.9)
* billiard (3.3.0.23)
* celery (3.1.25)
* greenlet (0.4.10)
* kombu (3.0.37)

How I run Celery workers:

> #!/bin/bash
> 
> celery worker -A project_name.celeryconf -Q default -n default@%h -Ofair --autoscale=4,4 --maxtasksperchild=8

Celery workers are working as a microservices (I am using Docker).
Moreover, I am using Rancher for scaling Celery workers.

Raised exception is below:

`ERROR:kombu.async.hub:Error in timer: StopIteration()
Traceback (most recent call last):
File "/usr/local/site-packages/kombu/async/hub.py", line 140, in fire_timers
entry()
File "/usr/local/site-packages/kombu/async/timer.py", line 64, in _call_
return self.fun(*self.args, **self.kwargs)
File "/usr/local/site-packages/kombu/async/timer.py", line 132, in _reschedules
return fun(*args, **kwargs)
File "/usr/local/site-packages/billiard/pool.py", line 1308, in maintain_pool
self._maintain_pool()
File "/usr/local/site-packages/billiard/pool.py", line 1300, in _maintain_pool
self._repopulate_pool(joined)
File "/usr/local/site-packages/billiard/pool.py", line 1285, in _repopulate_pool
self._create_worker_process(self._avail_index())
File "/usr/local/site-packages/celery/concurrency/asynpool.py", line 415, in _create_worker_process
return super(AsynPool, self)._create_worker_process
File "/usr/local/site-packages/billiard/pool.py", line 1102, in _create_worker_process
inq, outq, synq = self.get_process_queues()
File "/usr/local/site-packages/celery/concurrency/asynpool.py", line 997, in get_process_queues
return next(q for q, owner in items(self._queues)
StopIteration`

I don't know what's the matter.

**Comment by azhard4int** [comment]
@Katharsis did you manage to solve this problem?

**Comment by Katharsis** [comment]
@azhard4int 

I believe yes.
The problem did not occur any more.
To be honest, I do not know what exactly helps (venv upgrade, PyPy update to 5.7 or sth else).

**Comment by auvipy** [comment]
I hope upgrading to new versions should solve. report if thats not the case
