### ISSUE TITLE
Retrying tasks with an expiry fails with "'str' object has no attribute 'isoformat'"

### ISSUE THREAD

**Issue by bremac** [celery/celery#3734]
## Summary
Celery fails to retry tasks with `expires` set. The problem is that celery passes a ISO8601-formatted string to `celery.app.amqp.as_task_v2()` instead of a datetime.

## Steps to reproduce
1. Create a fresh virtualenv and install celery from master.
2. Create tasks.py with the following content:
```
from celery import Celery

app = Celery('tasks', broker='pyamqp://')

@app.task(bind=True, expires=60.0, max_retries=1)
def randint(self):
    if self.request.retries == 0:
        raise self.retry(countdown=0.1)
    return 42
```
3. Trigger the job:
```
$ python -c 'import tasks; tasks.randint.delay()'
$ celery -A tasks worker --loglevel=info
```

## Expected behavior
The task is retried once, then returns 42. Ex. it should log something like the following:
```
... startup message omitted ...

[2017-01-03 12:04:40,705: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-01-03 12:04:40,715: INFO/MainProcess] mingle: searching for neighbors
[2017-01-03 12:04:41,734: INFO/MainProcess] mingle: all alone
[2017-01-03 12:04:41,746: INFO/MainProcess] celery@mrslim ready.
[2017-01-03 12:04:41,747: INFO/MainProcess] Received task: tasks.randint[2eaa60ce-28d8-435d-8aec-2f0fed8afa28]  
[2017-01-03 12:04:41,872: INFO/PoolWorker-4] Task tasks.randint[2eaa60ce-28d8-435d-8aec-2f0fed8afa28] retry: Retry in 0.1s
[2017-01-03 12:04:41,872: INFO/MainProcess] Received task: tasks.randint[2eaa60ce-28d8-435d-8aec-2f0fed8afa28]  ETA:[2017-01-03 20:04:41.953403+00:00] 
[2017-01-03 12:04:42,717: INFO/PoolWorker-2] Task tasks.randint[2eaa60ce-28d8-435d-8aec-2f0fed8afa28] succeeded in 0.000306855999952s: 42
```

## Actual behavior

The retry call fails and the job is never completed. It logs the following instead:

```
... startup message omitted ...

[2017-01-03 12:05:40,585: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-01-03 12:05:40,594: INFO/MainProcess] mingle: searching for neighbors
[2017-01-03 12:05:41,615: INFO/MainProcess] mingle: all alone
[2017-01-03 12:05:41,631: INFO/MainProcess] celery@mrslim ready.
[2017-01-03 12:05:41,632: INFO/MainProcess] Received task: tasks.randint[95e4d770-19f7-44d3-a052-738f293036c5]   expires:[2017-01-03 20:06:40.130848+00:00]
[2017-01-03 12:05:41,735: WARNING/PoolWorker-4] Task tasks.randint[95e4d770-19f7-44d3-a052-738f293036c5] reject requeue=False: 'str' object has no attribute 'isoformat'
Traceback (most recent call last):
  File "/home/bremac/src/celery_test/venv/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/bremac/src/celery_test/venv/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/bremac/src/celery_test/tasks.py", line 9, in randint
    raise self.retry(countdown=0.1)
  File "/home/bremac/src/celery_test/venv/lib/python2.7/site-packages/celery/app/task.py", line 687, in retry
    raise Reject(exc, requeue=False)
Reject: (AttributeError("'str' object has no attribute 'isoformat'",), False)
```

Pdb gives me the following backtrace for the original exception. I've omitted everything above the call to `self.retry` for brevity:

```
  /home/bremac/src/celery_test/venv/lib/python2.7/site-packages/celery/app/task.py(685)retry()
-> S.apply_async()
  /home/bremac/src/celery_test/venv/lib/python2.7/site-packages/celery/canvas.py(221)apply_async()
-> return _apply(args, kwargs, **options)
  /home/bremac/src/celery_test/venv/lib/python2.7/site-packages/celery/app/task.py(535)apply_async()
-> **options
  /home/bremac/src/celery_test/venv/lib/python2.7/site-packages/celery/app/base.py(729)send_task()
-> root_id, parent_id, shadow, chain,
  /home/bremac/src/celery_test/venv/lib/python2.7/site-packages/celery/app/amqp.py(334)as_task_v2()
-> expires = expires and expires.isoformat()
```

## Other information

```
$ celery -A tasks report  # installed from a checkout on master

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.13
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:disabled

broker_url: u'amqp://guest:********@localhost:5672//'
```

**Comment by jfduque** [comment]
Bug is still present in 4.0.2, using this workaround in the meantime.

`raise self.retry(countdown=5, exc=exc, expires=None)`

**Comment by colinmcintosh** [comment]
We're seeing this issue too. Happens everytime we retry a task that has an expiration set (which is all of our tasks).

**Comment by colinmcintosh** [comment]
It looks like the Request class converts the serialized isoformat from the request to a datetime object but during a retry the `expires` time is taken from the Context class which stores this as an isoformat string. I assume this needs to be converted to a datetime before being passed to the Context class but I can't find where that happens.

@ask if you could point me to where this Context class is created I can create a PR to fix this.

**Comment by colinmcintosh** [comment]
Using the example above I put together a workaround to use in the meantime
```
#!/usr/bin/env python3
from celery import Celery
from celery.app.task import Task
from celery.utils.time import maybe_iso8601


CELERY_CONFIG = {
    "enable_utc": True,
    "broker_url": 'redis://127.0.0.1:6379/4',
    "task_serializer": "json",
    "event_serializer": "json",
    "result_serializer": "json"
}


class BaseTask(Task):

    def signature_from_request(self, request=None, args=None, kwargs=None, queue=None, **extra_options):
        """Workaround for https://github.com/celery/celery/issues/3734."""
        request.expires = maybe_iso8601(request.expires)
        return super(BaseTask, self).signature_from_request(request=request, args=args, kwargs=kwargs, queue=queue, **extra_options)



app = Celery("tasks")
app.conf.update(**CELERY_CONFIG)


@app.task(bind=True, expires=60.0, max_retries=1, base=BaseTask)
def randint(self):
    if self.request.retries == 0:
        raise self.retry(countdown=0.1)
    return 42

```

**Comment by bremac** [comment]
@colinmcintosh I spent some time trying to find a good place to handle the conversion, but I couldn't either. My existing workaround is https://github.com/celery/celery/pull/3790. :-\
