### ISSUE TITLE
ConnectionError with localhost redis.

### ISSUE THREAD

**Issue by Cediddi** [celery/celery#3738]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I run the project with celery multi, queue 50 long running (200secs max) jobs and wait it to finish first 40, after that all 20 concurrent threads die instanteniously and worker shuts down.
## Expected behavior
Not losing connection to redis broker on localhost.
## Actual behavior
    [2017-01-04 16:57:57,648: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
    Traceback (most recent call last):
      File "/home/staging/venv/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
        blueprint.start(self)
      File "/home/staging/venv/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
        step.start(parent)
      File "/home/staging/venv/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 594, in start
        c.loop(*c.loop_args())
      File "/home/staging/venv/local/lib/python2.7/site-packages/celery/worker/loops.py", line 88, in asynloop
        next(loop)
      File "/home/staging/venv/local/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
        cb(*cbargs)
      File "/home/staging/venv/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 1039, in on_readable
        self.cycle.on_readable(fileno)
      File "/home/staging/venv/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 337, in on_readable
        chan.handlers[type]()
      File "/home/staging/venv/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 714, in _brpop_read
        **options)
      File "/home/staging/venv/local/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
        response = connection.read_response()
      File "/home/staging/venv/local/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
        response = self._parser.read_response()
      File "/home/staging/venv/local/lib/python2.7/site-packages/redis/connection.py", line 357, in read_response
        (e.args,))
    ConnectionError: Error while reading from socket: ('Connection closed by server.',)

My report:
    software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.6
                billiard:3.5.0.2 redis:2.10.5
    platform -> system:Linux arch:64bit, ELF imp:CPython
    loader   -> celery.loaders.app.AppLoader
    settings -> transport:redis results:redis://:**@localhost:6379/3

    broker_transport_options: {
        'visibility_timeout': 432000}
    worker_max_tasks_per_child: 3
    worker_prefetch_multiplier: 1
    task_track_started: True
    result_expires: 259200
    enable_utc: True
    timezone: 'UTC'
    broker_url: u'redis://:********@localhost:6379/2'
    result_backend: u'redis://:********@localhost:6379/3'

I'm using ubuntu 14.04 and redis-server 2.8.4

I can't try the master branch as this is happening on our production server. Also we have 21 other workers, split to 7 servers, working on same redis server, but working on a  different database (broker:10/result:11) finishing tens of thousands of tasks every hour without a hitch.
Interesting part is, they should be more likely to lose connection, as they're connecting over network, yet the worker on localhost is the one getting disconnected.

**Comment by BuddhiAbeyratne** [comment]
im having the same issue did you find a solution

**Comment by Cediddi** [comment]
Yes, I switched to rabbitmq as my queue. My result backend is still redis and it's working okay. I guess the bug is only visible when you use redis as your broker. After all redis is not a queue manager.

**Comment by timo-piirmann** [comment]
Running into same issues so any insight would really appreciated :)

```
software -> 
    celery: 4.1.0 (latentcall) 
    kombu: 4.1.0 
    py:3.6.2
    billiard: 3.5.0.3 
    redis: 2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled
```

**Comment by auvipy** [comment]
check the latest commits to see if redis broaker related issues are fixed

**Comment by timo-piirmann** [comment]
Originally we were running redis-server 2.8.x without the latest bugfix versions. After updating to redis-server 3.2.x things seem to have stabled.

But can't yet be 100% sure

**Comment by toti1212** [comment]
Same issue. We use redis-server 3.2.x but...

 ```
    celery: 4.1.0 
    kombu: 4.1.0 
    billiard: 3.5.0.3 
    redis: 2.10.6
```

**Comment by auvipy** [comment]
celery 4.2.1 is the lalest
