### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'weak' on upgrade to celery 4.0.2

### ISSUE THREAD

**Issue by sritulasi** [celery/celery#3754]
I upgraded to celery==4.0.2 from 3.1.25 and getting this error since then. 

This is happening when I am trying to get the result using AsyncResult, given a task_id. 

**line causing the above error**:
```py
result = create_personalized_wb_for_branch.AsyncResult(
        pws_request_obj.task_id
    )
```

Did anything change in the way AsyncResult needs to be called? 

```
backend = redis
broker = rabbitmq 
```

```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 94, in tm_tween
    reraise(*exc_info)
  File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 75, in tm_tween
    response = handler(request)
  File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/opt/webapps/xamcheck-feedback/xamcheck_feedback/view_decorators.py", line 35, in wrapper
    return wrapped(request, *args, **kwargs)
  File "/opt/webapps/xamcheck-feedback/xamcheck_feedback/view_decorators.py", line 57, in wrapper
    return wrapped(request, *args, **kwargs)
  File "/opt/webapps/xamcheck-feedback/xamcheck_feedback/views/fulfillment_center.py", line 1594, in download_pwb_waiting_page_view
    pws_request_obj.task_id
  File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/celery/app/task.py", line 753, in AsyncResult
    task_name=self.name, **kwargs)
  **File "/home/ubuntu/.virtualenvs/xamcheck-feedback/lib/python2.7/site-packages/celery/result.py", line 95, in __init__
    self.on_ready = promise(self._on_fulfilled, weak=True)
TypeError: __init__() got an unexpected keyword argument 'weak'**
```

**Comment by ask** [comment]
Please try to upgrade vine.  It may seem like you have an older version installed, and that your dependencies weren't installed properly:

```
pip install -U vine
```

**Comment by sritulasi** [comment]
Thanks. That helped. I was using vine 1.1.1
