### ISSUE TITLE
Arisen exceptions from subtasks will be caught by supertask as non builtin, task handler raises PicklingError

### ISSUE THREAD

**Issue by sp-ricard-valverde** [celery/celery#3758]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Report

```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.5.0
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:rpc

imports:
    ('project.myapp.tasks',)
task_annotations: {
 'tasks.add': {'rate_limit': '10/s'}}
broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'rpc'
```

## Steps to reproduce

1. Start default `rabbitmq-server` and a default `worker`
2. Have two tasks, one called inside the other:
```
@celery_app.task
def super_task():
    async_res = sub_task.apply_async()
    while not async_res.ready():
        time.sleep(1)

    if async_res.failed():
        raise async_res.result
    else:
        return async_res.result


@celery_app.task
def sub_task():
    raise Exception('Controlled error')
```

3. Call for `super_task`
```
r = super_task.apply_async()

    try:
        r.get()
    except Exception as exc:
        if exc.__class__.__module__ != 'builtins':
            assert 0, 'Exception type is not builtin'
```

_optionally_: download the attached project, install celery and run the file `test_raising.py`
[celery_project.zip](https://github.com/celery/celery/files/702053/celery_project.zip)

## Expected behavior

The subtask exception of type `Exception` from python `builtins` module to be arisen up to the main process and the assert check successful

## Actual behavior

The arisen exception is not builtin is of class `celery.backends.base.Exception` instead, and if you check the `worker` log a `super_task` task handler raised an error:
```
<MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: Exception('Controlled error',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'celery.backends.base.Exception\'>: attribute lookup Exception on celery.backends.base failed",)''.>
```

**Comment by sp-ricard-valverde** [comment]
I think it's a consequence of patch added in https://github.com/celery/celery/issues/2518

**Comment by sp-ricard-valverde** [comment]
possible duplicate https://github.com/celery/celery/issues/3586

**Comment by takhs91** [comment]
Hello! I also face the same issue. you are right about #2518 it also clearly stated [here](https://github.com/celery/celery/issues/2518#issuecomment-98326120).

Is this happening only in the amqp/rpc backends or also in the other backends? Are there any plans in fixing this?

**Comment by bmbouter** [comment]
I am also experiencing this issue (I think). I am using the Qpid backend, so I don't think it's backend specific. I have a user-defined (by me) exception being raised inside of my tasks.

If you raise the following exception:

```
class SizeValidationError(Exception):
    def __init__(self, url):
        self.url = url
        super().__init__()
```

You will get a traceback like this:

```
Aug 22 17:01:47 pulp3 celery[22385]: [2017-08-22 17:01:47,491: ERROR/ForkPoolWorker-1] Task failed : [215dd3c4-753b-4daf-89d0-2678038f6094]
Aug 22 17:01:47 pulp3 celery[22385]: [2017-08-22 17:01:47,500: ERROR/ForkPoolWorker-1] Task pulpcore.app.tasks.importer.sync[215dd3c4-753b-4daf-89d0-2678038f6094] raised unexpected: SizeValidationError('PLP0004',)
Aug 22 17:01:47 pulp3 celery[22385]: Traceback (most recent call last):
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/.virtualenvs/pulp/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
Aug 22 17:01:47 pulp3 celery[22385]:     R = retval = fun(*args, **kwargs)
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/devel/pulp/platform/pulpcore/tasking/tasks.py", line 272, in __call__
Aug 22 17:01:47 pulp3 celery[22385]:     return super(UserFacingTask, self).__call__(*args, **kwargs)
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/.virtualenvs/pulp/lib/python3.5/site-packages/celery/app/trace.py", line 629, in __protected_call__
Aug 22 17:01:47 pulp3 celery[22385]:     return self.run(*args, **kwargs)
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/devel/pulp/platform/pulpcore/app/tasks/importer.py", line 75, in sync
Aug 22 17:01:47 pulp3 celery[22385]:     importer.sync()
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/devel/pulp_example/pulp_example/app/models.py", line 180, in sync
Aug 22 17:01:47 pulp3 celery[22385]:     delta = self._find_delta()
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/devel/pulp_example/pulp_example/app/models.py", line 161, in _find_delta
Aug 22 17:01:47 pulp3 celery[22385]:     download_result = task.result()
Aug 22 17:01:47 pulp3 celery[22385]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 293, in result
Aug 22 17:01:47 pulp3 celery[22385]:     raise self._exception
Aug 22 17:01:47 pulp3 celery[22385]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
Aug 22 17:01:47 pulp3 celery[22385]:     result = coro.send(None)
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/devel/pulp/platform/pulpcore/download/http.py", line 132, in run
Aug 22 17:01:47 pulp3 celery[22385]:     to_return = await self._handle_response(response)
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/devel/pulp/platform/pulpcore/download/http.py", line 116, in _handle_response
Aug 22 17:01:47 pulp3 celery[22385]:     self._validate_size()
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/devel/pulp/platform/pulpcore/download/http.py", line 97, in _validate_size
Aug 22 17:01:47 pulp3 celery[22385]:     actual_size=self._size)
Aug 22 17:01:47 pulp3 celery[22385]: pulpcore.exceptions.download.SizeValidationError: PLP0004
Aug 22 17:01:47 pulp3 celery[22385]: [2017-08-22 17:01:47,508: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: SizeValidationError('PLP0004',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'pulpcore.exceptions.download.SizeValidationError\'>: it\'s not the same object as pulpcore.exceptions.download.SizeValidationError",)''.>
Aug 22 17:01:47 pulp3 celery[22385]: Traceback (most recent call last):
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/.virtualenvs/pulp/lib/python3.5/site-packages/billiard/pool.py", line 362, in workloop
Aug 22 17:01:47 pulp3 celery[22385]:     put((READY, (job, i, result, inqW_fd)))
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/.virtualenvs/pulp/lib/python3.5/site-packages/billiard/queues.py", line 366, in put
Aug 22 17:01:47 pulp3 celery[22385]:     self.send_payload(ForkingPickler.dumps(obj))
Aug 22 17:01:47 pulp3 celery[22385]:   File "/home/vagrant/.virtualenvs/pulp/lib/python3.5/site-packages/billiard/reduction.py", line 56, in dumps
Aug 22 17:01:47 pulp3 celery[22385]:     cls(buf, protocol).dump(obj)
Aug 22 17:01:47 pulp3 celery[22385]: billiard.pool.MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: SizeValidationError('PLP0004',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'pulpcore.exceptions.download.SizeValidationError\'>: it\'s not the same object as pulpcore.exceptions.download.SizeValidationError",)''.
```

This exception raises as expected normally:

```
class SizeValidationError(Exception):
    def __init__(self):
        self.url = 'this does not matter'
        super().__init__()
```

**Comment by r-darwish** [comment]
I think I'm experiencing something similar. I use the following app as en example:

`main.py`:

``` python
from tasks import task

def main():
    task.delay()

if __name__ == "__main__":
    main()
```

`tasks/__init__.py`:

``` python
import os
from celery import Celery

task_queue = Celery('tasks',
                    backend=os.environ.get('CELERY_BACKEND_URL', 'rpc://'),
                    broker=os.environ.get('CELERY_BROKER_URL', 'amqp://guest@localhost//'))


class Custom(Exception):
    def __init__(self, a, b):
        super().__init__(a)


@task_queue.task
def task():
    raise Custom(2, 1)
```

The worker is launched via the command `celery worker -A tasks`

The following exception is printed at the worker window:

``` python-traceback
[2017-10-01 14:51:53,289: ERROR/ForkPoolWorker-8] Task tasks.task[38d5d635-f1f3-4d44-9c88-499b50a08c75] raised unexpected: Custom(2,)
Traceback (most recent call last):
  File "/home/roeyd/src/testapp/.env/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/roeyd/src/testapp/.env/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/roeyd/src/testapp/d74dd4cd70f6de3171c350cda05b93fc/tasks/__init__.py", line 16, in task
    raise Custom(2, 1)
tasks.Custom: 2
[2017-10-01 14:51:53,292: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: Custom(2,)>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'tasks.Custom\'>: it\'s not the same object as tasks.Custom",)''.>
Traceback (most recent call last):
  File "/home/roeyd/src/testapp/.env/lib/python3.6/site-packages/billiard/pool.py", line 362, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/home/roeyd/src/testapp/.env/lib/python3.6/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/home/roeyd/src/testapp/.env/lib/python3.6/site-packages/billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: Custom(2,)>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'tasks.Custom\'>: it\'s not the same object as tasks.Custom",)''.
```

Commenting out the call for `super` makes it work as expected. Also, changing `__init__` so that it receives a single parameter (but keeps calling super) also works as expected.

**Comment by auvipy** [comment]
have a look on this https://github.com/celery/celery/pull/3592 for tracking progress

**Comment by PATAPOsha** [comment]
I steel having same issue in celery 4.3.0. Why is it closed?

**Comment by thedrow** [comment]
@PATAPOsha #5074 should fix this issue.
Can you try master?

**Comment by sp-ricard-valverde** [comment]
> @PATAPOsha #5074 should fix this issue.
> Can you try master?

It got apparently reverted by https://github.com/celery/celery/commit/22d02981bf54a6d854576ff2392d686f20d3a9b3

**Comment by thedrow** [comment]
#3586 should track this...
