### ISSUE TITLE
consumer: Connection to broker lost when I restart the worker

### ISSUE THREAD

**Issue by jolovejo** [celery/celery#3760]
We use --max-tasks-per-child 1 in woker command. And when a task succeeded, it will automatically restart the work. And every time we will receive the warning like:
```
[2017-01-13 15:51:07,161: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/redis/connection.py", line 346, in read_response
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/kombu/transport/redis.py", line 1039, in on_readable
    self.cycle.on_readable(fileno)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/kombu/transport/redis.py", line 714, in _brpop_read
    **options)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/redis/connection.py", line 357, in read_response
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
```
The full log:
```
[2017-01-13 15:51:07,080: ERROR/MainProcess] Process 'PoolWorker-1' pid:30444 exited with 'exitcode 70'
[2017-01-13 15:51:07,161: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/redis/connection.py", line 346, in read_response
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/kombu/transport/redis.py", line 1039, in on_readable
    self.cycle.on_readable(fileno)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/kombu/transport/redis.py", line 714, in _brpop_read
    **options)
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/Users/Joanna/.virtualenvs/mdt-dev/lib/python3.6/site-packages/redis/connection.py", line 357, in read_response
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
[2017-01-13 15:51:07,173: DEBUG/MainProcess] | Consumer: Restarting event loop...
[2017-01-13 15:51:07,173: DEBUG/MainProcess] | Consumer: Restarting Control...
[2017-01-13 15:51:07,174: DEBUG/MainProcess] | Consumer: Restarting Tasks...
[2017-01-13 15:51:07,174: DEBUG/MainProcess] Canceling task consumer...
[2017-01-13 15:51:07,174: DEBUG/MainProcess] | Consumer: Restarting Heart...
[2017-01-13 15:51:07,176: DEBUG/MainProcess] | Consumer: Restarting Gossip...
[2017-01-13 15:51:07,176: DEBUG/MainProcess] | Consumer: Restarting Mingle...
[2017-01-13 15:51:07,176: DEBUG/MainProcess] | Consumer: Restarting Events...
[2017-01-13 15:51:07,177: DEBUG/MainProcess] | Consumer: Restarting Connection...
[2017-01-13 15:51:07,177: DEBUG/MainProcess] | Consumer: Starting Connection
[2017-01-13 15:51:07,185: INFO/MainProcess] Connected to redis://127.0.0.1:6379/3
[2017-01-13 15:51:07,185: DEBUG/MainProcess] ^-- substep ok
[2017-01-13 15:51:07,186: DEBUG/MainProcess] | Consumer: Starting Events
[2017-01-13 15:51:07,194: DEBUG/MainProcess] ^-- substep ok
[2017-01-13 15:51:07,194: DEBUG/MainProcess] | Consumer: Starting Mingle
[2017-01-13 15:51:07,194: INFO/MainProcess] mingle: searching for neighbors
[2017-01-13 15:51:08,204: INFO/MainProcess] mingle: all alone
[2017-01-13 15:51:08,204: DEBUG/MainProcess] ^-- substep ok
[2017-01-13 15:51:08,204: DEBUG/MainProcess] | Consumer: Starting Gossip
[2017-01-13 15:51:08,209: DEBUG/MainProcess] ^-- substep ok
[2017-01-13 15:51:08,209: DEBUG/MainProcess] | Consumer: Starting Heart
[2017-01-13 15:51:08,210: DEBUG/MainProcess] ^-- substep ok
[2017-01-13 15:51:08,210: DEBUG/MainProcess] | Consumer: Starting Tasks
[2017-01-13 15:51:08,213: DEBUG/MainProcess] ^-- substep ok
[2017-01-13 15:51:08,214: DEBUG/MainProcess] | Consumer: Starting Control
[2017-01-13 15:51:08,216: DEBUG/MainProcess] ^-- substep ok
[2017-01-13 15:51:08,216: DEBUG/MainProcess] | Consumer: Starting event loop
[2017-01-13 15:51:08,216: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2017-01-13 15:51:08,217: DEBUG/MainProcess] basic.qos: prefetch_count->4
```
## Steps to reproduce
$ kill -HUP $pid

**Comment by georgepsarakis** [comment]
Are you using Python 3.6? If you see in the bottom [here](https://pypi.python.org/pypi/celery/), 3.6 is not yet in the supported versions.

**Comment by auvipy** [comment]
@jolovejo could you verify the issue on recent master?

**Comment by TopcoderWuxie** [comment]
it also occured in python3.4.3 + celery4.2.0 + redis2.10.6  and redis tenv is 2.8.4, is the version not supported?
