### ISSUE TITLE
Redis pubsub timeout when waiting for multiple results in threads

### ISSUE THREAD

**Issue by sjagoe** [celery/celery#3761]
Submitting tasks and waiting for results in threads often (but not always) appears to hang, and finally terminate with a timeout on the Redis result PUBSUB socket.

This scenario appears in a project I have recently become involved in that uses grpc.io effectively as a "frontend" to celery, allowing a Java component to submit tasks to celery workers and wait for the results. gRPC appears to require a `concurrent.futures.ThreadPoolExecutor` in order to handle requests, hence the celery requests being submitted from threads.

- `celery report` output included at the bottom of the report.
- The issue is present at least in Celery 4.0.2 and `master`.
- The described scenario worked in Celery 3.1.x

## Steps to reproduce

In this example scenario, I have a single worker with prefetch multiplier of `1`, and I'm submitting two tasks (submitted from separate threads) that take up to 500ms each to complete, so it is certain that one of the tasks will have to wait in the queue until the worker is free.

Watcging the celery worker logs, it is clear that both tasks _have_ successfully executed.

In looking into the issue, it seems that the result for both submitted tasks _has_ been read from redis by the client (by inserting a `print` in `celery.backends.redis.ResultConsumer.drain_events`), but one thread seems to go back to `drain_events()` and block until a timeout from redis.

I named this snippet below `redis_pubsub_timeout.py` and just dumped it in a virtualenv `site-packages` (or otherwise on `sys.path`) for simplicity.

Run the worker with `celery worker --app redis_pubsub_timeout.app -l info` and the client with `python -m redis_pubsub_timeout`.

```python
from concurrent.futures import ThreadPoolExecutor
import random
import time

from celery import Celery

CONFIG = {
    'broker_url': 'redis://localhost:6379/4',
    'result_backend': 'redis://localhost:6379/4',
    'task_serializer': 'json',
    'result_serializer': 'json',
    'accept_content': ['json'],
    'worker_prefetch_multiplier': 1,
    'worker_concurrency': 1,
    'worker_pool': 'prefork',
}

app = Celery(__name__)
app.config_from_object(CONFIG)


@app.task(name='redis_pubsub_timeout.mytask')
def mytask():
    sleeptime = random.randint(10, 50) / float(100)
    time.sleep(sleeptime)
    return sleeptime


if __name__ == '__main__':
    def execute_task():
        result = mytask.delay()
        return result.get()

    WORKERS = 2
    with ThreadPoolExecutor(max_workers=WORKERS) as executor:
        futures = [executor.submit(execute_task) for i in range(WORKERS)]
    values = [future.result() for future in futures]
    print(values)
```

## Expected behavior

The tasks complete and return the result to the caller.

## Actual behavior

The following error is seen the the client when waiting for the results from the worker.

```
$ python -m redis_pubsub_timeout
Traceback (most recent call last):
  File "/nix/store/7zqg0icnd3ymbzpgwsh4qdv064ccgwc4-python-2.7.13/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/nix/store/7zqg0icnd3ymbzpgwsh4qdv064ccgwc4-python-2.7.13/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/redis_pubsub_timeout.py", line 37, in <module>
    values = [result.result() for result in results]
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/redis_pubsub_timeout.py", line 32, in execute_task
    return result.get()
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/celery/result.py", line 189, in get
    on_message=on_message,
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/celery/backends/async.py", line 190, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/celery/backends/async.py", line 259, in _wait_for_pending
    on_interval=on_interval):
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/celery/backends/async.py", line 57, in drain_events_until
    yield self.wait_for(p, wait, timeout=1)
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/celery/backends/async.py", line 67, in wait_for
    wait(timeout=timeout)
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/celery/backends/redis.py", line 69, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/redis/client.py", line 2260, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/redis/client.py", line 2183, in parse_response
    return self._execute(connection, connection.read_response)
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/redis/client.py", line 2165, in _execute
    return command(*args)
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/home/sjagoe/celery4/lib/python2.7/site-packages/redis/connection.py", line 139, in _read_from_socket
    raise TimeoutError("Timeout reading from socket")
redis.exceptions.TimeoutError: Timeout reading from socket
```

## Celery report

```
$ celery report --app redis_pubsub_timeout.app  

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.13
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/4

worker_pool: 'prefork'
task_serializer: 'json'
result_serializer: 'json'
worker_concurrency: 3
worker_prefetch_multiplier: 1
accept_content: ['json']
broker_url: u'redis://localhost:6379/4'
result_backend: u'redis://localhost:6379/4'
```

**Comment by hp685** [comment]
I'm encountering the same issue, intermittently. Looking through the logs, I see the task has completed, but client calling the Task doesn't receive a response, and blocks on a .get() until TimeoutError. 

I'm using prefork with concurrency of 20 
and my app.con settings are as follows:
    accept_content=['json', 'pickle'],
    task_serializer='pickle',
    result_serializer='pickle',

**Comment by ariwbolton** [comment]
I'm experiencing the same issue w/ same config as @hp685, Celery 4.0.2, and redis. (Tasks are queued from Flask thread, if it makes any difference).

**Comment by ray-is-in** [comment]
I'm experiencing the same issue with similar configs as @hp685. Task appears to finish as seen by flower, and spawned by django.
Django 1.11.5
Celery 4.1.0
python 3.6
redis 2.10.6

**Comment by auvipy** [comment]
thanks!
