### ISSUE TITLE
Celery worker stalls for unknown reason.

### ISSUE THREAD

**Issue by x00x70** [celery/celery#3819]
My celery worker's keep hanging for some reason - they dont error out, there's nothing in debug logs that suggest something has broken, they just stop after running a few tasks. I'm running multiple workers managed by supervisord - 
`celery worker -A proj -Q mysqsqueue --loglevel=info --autoscale=4,1`
The only way i can fix this is by setting --pool=solo - but then i lost the functionality to run multiple threads all at once and this completely slows my application down.
A lot of my tasks use the requests package which i have read can cause workers to hang, but i have set timeouts within all request commands. I also read that if i use gevent/eventlet pools this might handle this better, however when setting --pool=gevent, my worker wont even start. Please see the error message below.

Until now everything has been working, its just that my application has scaled up to the 1000's of tasks and the worker's now stall with no errors. I can provide more details if necessary, but not sure where else to turn now.

## Checklist (
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.5
            billiard:3.5.0.2 sqs:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqs results:db+postgresql+psycopg2://aws****:**@aws*****eu-west-2.rds.amazonaws.com/t*****8

task_serializer: 'json'
broker_transport_options: {
    'region': 'eu-west-2'}
result_serializer: 'json'

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
celery worker -A proj -Q myQueue  --pool=gevent
## Expected behavior
Celery should be working.
## Actual behavior
Setting pool -P gevent or evenlet produces the following error:
```
[2017-02-08 14:19:10,955: CRITICAL/MainProcess] Unrecoverable error: TypeError("drain_events() got an unexpected keyword argument 'callback'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/usr/lib/python2.7/site-packages/celery/worker/loops.py", line 118, in synloop
    connection.drain_events(timeout=2.0)
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 961, in drain_events
    get(self._deliver, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/usr/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 999, in _drain_channel
    return channel.drain_events(callback=callback, timeout=timeout)
TypeError: drain_events() got an unexpected keyword argument 'callback'
```
Any help would be appreciated.
Thanks.

**Comment by nigma** [comment]
When you run the default preform pool, do you have the `CELERY_WORKER_MAX_TASKS_PER_CHILD` setting value set?

**Comment by Sheepzez** [comment]
I'm receiving this error in a very similar situation.

```
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/worker/loops.py", line 118, in synloop
    connection.drain_events(timeout=2.0)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/kombu/transport/virtual/base.py", line 961, in drain_events
    get(self._deliver, timeout=timeout)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/kombu/transport/virtual/base.py", line 999, in _drain_channel
    return channel.drain_events(callback=callback, timeout=timeout)
TypeError: drain_events() got an unexpected keyword argument 'callback'
```

@nigma You mentioned `CELERY_WORKER_MAX_TASKS_PER_CHILD`? Should this be set, or not set? If set, what's a reasonable default?

**Comment by thedrow** [comment]
Can anyone provide a testcase for us to reproduce?

**Comment by grvhi** [comment]
We will try to put together a reproducible test case, but in the meantime, we're coming across exactly the same issue with celery 4.0.2 but only when using gevent. This issue in kombu (fixed) seems related: https://github.com/celery/kombu/issues/694

**Comment by auvipy** [comment]
is this issue still exist in master?
