### ISSUE TITLE
Error !

### ISSUE THREAD

**Issue by commiaI** [celery/celery#3820]
Hello, here is the result of the command `$ celery -A fir_celery.celeryconf worker -l info` : 

```
celery -A fir_celery.celeryconf worker -l info
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 489, in setup_app_from_commandline
    self._handle_user_preload_options(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 494, in _handle_user_preload_options
    user_preload = tuple(self.app.user_options['preload'] or ())
AttributeError: 'str' object has no attribute 'user_options'
```

Do you know the problem ?

**Comment by georgepsarakis** [comment]
Can you please give more details on your configuration and tasks?

**Comment by thedrow** [comment]
This issue has gone stale. @commiaI Please comment to reopen.
