### ISSUE TITLE
Tasks created from classmethods no longer work

### ISSUE THREAD

**Issue by dralley** [celery/celery#3863]
## Checklist

**Version info:**

* celery 4.0.2 (latentcall)
* kombu 4.0.2 
* py 2.7.13
* billiard 3.5.0.2

**Verified against celery/master:**  Yes

## Steps to reproduce

Save as reproducer.py and then run with ```celery -A reproducer worker```

```
from celery import Celery, task, Task

app = Celery('hello', broker='qpid://localhost/')


class ReproducerClass:

    @classmethod
    def task_classmethod(cls):
        return 'hello world'

    @staticmethod
    def task_staticmethod():
        return 'hello world'


# this works
statictask = task(ReproducerClass.task_staticmethod, base=Task)
# this blows up
classtask = task(ReproducerClass.task_classmethod, base=Task)

```

## Expected behavior

class method task will function as a normal task, as it did in Celery 3.1.x

## Actual behavior

```
Traceback (most recent call last):
  File "/usr/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 95, in __init__
    self.on_before_init(**kwargs)
  File "/usr/lib/python2.7/site-packages/celery/apps/worker.py", line 97, in on_before_init
    trace.setup_worker_optimizations(self.app, self.hostname)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 568, in setup_worker_optimizations
    app.finalize()
  File "/usr/lib/python2.7/site-packages/celery/app/base.py", line 512, in finalize
    _announce_app_finalized(self)
  File "/usr/lib/python2.7/site-packages/celery/_state.py", line 52, in _announce_app_finalized
    callback(app)
  File "/usr/lib/python2.7/site-packages/celery/app/base.py", line 412, in cons
    return app._task_from_fun(fun, **opts)
  File "/usr/lib/python2.7/site-packages/celery/app/base.py", line 453, in _task_from_fun
    '__header__': staticmethod(head_from_fun(fun, bound=bind)),
  File "/usr/lib/python2.7/site-packages/celery/utils/functional.py", line 275, in head_from_fun
    fun_args=_argsfromspec(getfullargspec(fun)),
  File "/usr/lib/python2.7/site-packages/vine/five.py", line 350, in getfullargspec
    s = _getargspec(fun)
  File "/usr/lib64/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <method-wrapper '__call__' of instancemethod object at 0x7f6ba1d7b410> is not a Python function
```

As you can see, the entire traceback is within Celery, leaving no indication of where the problem might be.  After debugging, we found that the deficiency is [here](https://github.com/celery/celery/blob/1992cb07f1d4de44ab80ff7ee8ab93614517d7ae/celery/utils/functional.py#L269):

Here is the exerpt:

```
    if not inspect.isfunction(fun) and hasattr(fun, '__call__'):
        name, fun = fun.__class__.__name__, fun.__call__
    else:
        name = fun.__name__
````

If you mess around with the following code in REPL or ipython, we can figure out what's going on.

```
In [1]: class Test:
    @classmethod
    def cmtest(cls):
        print "cmtest"
    @staticmethod
    def smtest():
        print "smtest"
   ...:         

In [2]: import inspect

In [3]: inspect.isfunction(Test.cmtest)
Out[3]: False

In [4]: inspect.isfunction(Test.smtest)
Out[4]: True

In [5]: Test.cmtest.__call__
Out[5]: <method-wrapper '__call__' of instancemethod object at 0x7fce55138730>

In [6]: Test.smtest.__call__
Out[6]: <method-wrapper '__call__' of function object at 0x7fce5393f758>
```

The staticmethod is taking the "else" branch, while the classmethod is taking the "if" branch.  That's about as far down the rabbit hole as I wanted to go.  Nevertheless, it's a regression from Celery 3.1.x behavior.

**Comment by dralley** [comment]
Just realized that an issue for this already exists: #3609

**Comment by TaskDead** [comment]
I get similar errors when I use a function(static) complied using cython

print statements added in /celery/utils/functional.py - head_from_fun
<cyfunction text_search at 0x7f0002caa4d0>
which leads to the error messages provided by @dralley

**Comment by TaskDead** [comment]
Complete error message:


Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/worker.py", line 95, in __init__
    self.on_before_init(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/apps/worker.py", line 97, in on_before_init
    trace.setup_worker_optimizations(self.app, self.hostname)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 568, in setup_worker_optimizations
    app.finalize()
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 512, in finalize
    _announce_app_finalized(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/_state.py", line 52, in _announce_app_finalized
    callback(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 412, in cons
    return app._task_from_fun(fun, **opts)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 453, in _task_from_fun
    '__header__': staticmethod(head_from_fun(fun, bound=bind)),
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/functional.py", line 280, in head_from_fun
    fun_args=_argsfromspec(getfullargspec(fun)),
  File "/usr/local/lib/python2.7/dist-packages/vine/five.py", line 350, in getfullargspec
    s = _getargspec(fun)
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <method-wrapper '__call__' of cython_function_or_method object at 0x7f17349204d0> is not a Python function

**Comment by georgepsarakis** [comment]
This is actually one of the [limitations](http://cython.readthedocs.io/en/latest/src/userguide/limitations.html#inspect-support) of Cython. In this particular case, the function signature cannot be read using `inspect.getargspec`.

**Comment by TaskDead** [comment]
@georgepsarakis  Then I wont be able to upgrade celery, thanks for the clarification
