### ISSUE TITLE
`Task handler raised error: TypeError("'NoneType' object is not callable",)` from MainProcess when a Task call asynchronously another Task

### ISSUE THREAD

**Issue by zentrung** [celery/celery#3866]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
$ celery -A celery4:app report

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.5.2
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

task_default_routing_key: '********'
imports: ['celery4.multiply', 'celery4.sum']
task_default_exchange_type: 'direct'
timezone: 'UTC'
enable_utc: True
task_acks_late: True
result_serializer: 'json'
task_ignore_result: True
task_default_exchange: 'xm.tasks'
multiprocessing: <module 'multiprocessing' from '/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/__init__.py'>
Queue: <class 'kombu.entity.Queue'>
worker_concurrency: 13
worker_disable_rate_limits: True
accept_content: {'json'}
task_serializer: 'json'
task_routes: {
    'celery4.multiply.Multiply': {   'queue': 'xm.tasks',
                                     'routing_key': '********'},
    'celery4.multiply.Sum': {'queue': 'xm.tasks', 'routing_key': '********'}}
Exchange: <class 'kombu.entity.Exchange'>
worker_hijack_root_logger: False
broker_pool_limit: 13
broker_url: 'amqp://trau:********@dev-1.c.xomad-1084.internal:5672//'
task_protocol: 1
concurrency_processes: 13
os: <module 'os' from '/Users/trung/virtualenvs/celery4/bin/../lib/python3.5/os.py'>
task_default_queue: 'xm.tasks'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

`celery4.py`

```python
from celery import Celery, Task


def create_app():
    celery = Celery(__name__, strict_typing=False)
    celery.config_from_object('celeryconfig')
    celery.conf.task_protocol = 1
    return celery


app = create_app()


class Sum(Task):
    _multiply_task = None

    @property
    def multiply_task(self):
        if not self._multiply_task:
            self._multiply_task = Multiply()
            app.register_task(self._multiply_task)
        return self._multiply_task

    def run(self, x, y):
        self.multiply_task.delay(x, y)
        return x + y


app.register_task(Sum())


class Multiply(Task):
    _sum_task = None

    @property
    def sum_task(self):
        if not self._sum_task:
            self._sum_task = Sum()
            app.register_task(self._sum_task)
        return self._sum_task

    def run(self, x, y):
        self.sum_task.delay(x, y)
        return x * y


app.register_task(Multiply())
```

`test.py`

```python
from celery4 import app, Sum

if __name__ == '__main__':
    t = Sum()
    app.register_task(t)
    print(t.delay(3, 5))
```

## Expected behavior
Before finishing, task `Sum` invokes task `Multiply` which in turn invokes task `Sum` which in turn invokes `Multiply` and so on...

## Actual behavior

```
$ celery worker -A celery4:app -l INFO --concurrency=1
 
 -------------- celery@lap2.local v4.0.2 (latentcall)
---- **** ----- 
--- * ***  * -- Darwin-16.4.0-x86_64-i386-64bit 2017-02-24 22:11:03
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         celery4:0x10d31f358
- ** ---------- .> transport:   amqp://trau:**@dev-1.c.xomad-1084.internal:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> xm.tasks         exchange=xm.tasks(direct) key=xm.tasks
                

[tasks]
  . celery4.Multiply
  . celery4.Sum

[2017-02-24 22:11:25,627: INFO/MainProcess] Connected to amqp://trau:**@dev-1.c.xomad-1084.internal:5672//
[2017-02-24 22:11:27,340: INFO/MainProcess] mingle: searching for neighbors
[2017-02-24 22:11:34,564: INFO/MainProcess] mingle: all alone
[2017-02-24 22:11:38,660: INFO/MainProcess] celery@lap2.local ready.
[2017-02-24 22:12:24,924: INFO/MainProcess] Received task: celery4.Sum[9d4a2a0b-890c-4752-a2ae-2231ed35ea7f]  
[2017-02-24 22:12:30,079: INFO/PoolWorker-1] Task celery4.Sum[9d4a2a0b-890c-4752-a2ae-2231ed35ea7f] succeeded in 3.6204605321399868s: 8
[2017-02-24 22:12:30,312: INFO/MainProcess] Received task: celery4.Multiply[48b76369-20d3-4de0-bf63-5a6cecd13bd4]  
[2017-02-24 22:12:30,478: ERROR/MainProcess] Task handler raised error: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "/Users/trung/virtualenvs/celery4/lib/python3.5/site-packages/billiard/pool.py", line 359, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/Users/trung/virtualenvs/celery4/lib/python3.5/site-packages/celery/app/trace.py", line 530, in _fast_trace_task
    uuid, args, kwargs, request,
TypeError: 'NoneType' object is not callable
```

This issue happens with both Python3.5 and Python2.7, on Ubuntu16.04 and Mac. I think somehow `fun` is set to `None` in
```
  File "/Users/trung/virtualenvs/celery4/lib/python3.5/site-packages/billiard/pool.py", line 359, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
```

**Comment by arjunchatterjee196** [comment]
I think this problem is caused due to Python Version Compatibility. 

On **Python2.7.10 I have not faced any problems**. 

But when I deployed using docker where I had Python2.7.12 installed, 80% of my tasks are failing with exactly the same traceback


	[2017-02-24 22:12:30,478: ERROR/MainProcess] Task handler raised error: TypeError("'NoneType' object is not callable",)
	Traceback (most recent call last):
	  File "/Users/trung/virtualenvs/celery4/lib/python3.5/site-packages/billiard/pool.py", line 359, in workloop
	    result = (True, prepare_result(fun(*args, **kwargs)))
	  File "/Users/trung/virtualenvs/celery4/lib/python3.5/site-packages/celery/app/trace.py", line 530, in _fast_trace_task
	    uuid, args, kwargs, request,
	TypeError: 'NoneType' object is not callable

**Comment by auvipy** [comment]
probably fixed. try new version

**Comment by renierdbruyn** [comment]
I am experiencing the same issue using celery 4 and Python 3.6
