### ISSUE TITLE
Can't start celery worker: PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED

### ISSUE THREAD

**Issue by mennanov** [celery/celery#3868]
I can't start a Celery worker, after running the command:

`celery worker -A project_name`

i get an exception:

```
[2017-02-28 01:39:55,452: CRITICAL/MainProcess] Unrecoverable error: PreconditionFailed(406, u"PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'celery@Ubuntu-1404-trusty-64-minimal.celery.pidbox' in vhost 'bunnylove': received the value '10000' of type 'signedint' but current is none", (50, 10), u'Queue.declare')
Traceback (most recent call last):
  File "/home/bunnylove/local/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/bunnylove/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/bunnylove/local/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/home/bunnylove/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/bunnylove/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/bunnylove/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 51, in start
    self.consumer = self.node.listen(callback=self.on_message)
  File "/home/bunnylove/local/lib/python2.7/site-packages/kombu/pidbox.py", line 90, in listen
    on_decode_error=self.on_decode_error)
  File "/home/bunnylove/local/lib/python2.7/site-packages/kombu/pidbox.py", line 77, in Consumer
    **options
  File "/home/bunnylove/local/lib/python2.7/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/home/bunnylove/local/lib/python2.7/site-packages/kombu/messaging.py", line 407, in revive
    self.declare()
  File "/home/bunnylove/local/lib/python2.7/site-packages/kombu/messaging.py", line 420, in declare
    queue.declare()
  File "/home/bunnylove/local/lib/python2.7/site-packages/kombu/entity.py", line 605, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/home/bunnylove/local/lib/python2.7/site-packages/kombu/entity.py", line 614, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/home/bunnylove/local/lib/python2.7/site-packages/kombu/entity.py", line 649, in queue_declare
    nowait=nowait,
  File "/home/bunnylove/local/lib/python2.7/site-packages/amqp/channel.py", line 1165, in queue_declare
    spec.Queue.DeclareOk, returns_tuple=True,
  File "/home/bunnylove/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 93, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/bunnylove/local/lib/python2.7/site-packages/amqp/connection.py", line 464, in drain_events
    return self.blocking_read(timeout)
  File "/home/bunnylove/local/lib/python2.7/site-packages/amqp/connection.py", line 469, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/bunnylove/local/lib/python2.7/site-packages/amqp/method_framing.py", line 68, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/bunnylove/local/lib/python2.7/site-packages/amqp/connection.py", line 473, in on_inbound_method
    method_sig, payload, content,
  File "/home/bunnylove/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 142, in dispatch_method
    listener(*args)
  File "/home/bunnylove/local/lib/python2.7/site-packages/amqp/channel.py", line 293, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'celery@Ubuntu-1404-trusty-64-minimal.celery.pidbox' in vhost 'bunnylove': received the value '10000' of type 'signedint' but current is none
```

I tried to reset RabbitMQ (remove all queues and users, vhosts), but it did not help.
Setting `task_ignore_result = True` did not help, `CELERY_TASK_RESULT_EXPIRES = 3600` did not help either.

[report.txt](https://github.com/celery/celery/files/805096/report.txt)

**Comment by mennanov** [comment]
[report.txt](https://github.com/celery/celery/files/805096/report.txt)

**Comment by mennanov** [comment]
Changing the broker URL from "pyamqp://" to "amqp://" resolved the issue.

**Comment by gitaarik** [comment]
I get the same error but I've never used `pyamqp://`, always `amqp://`. Tried to play with the settings you suggested but no success. Anyone has an idea?

**Comment by gitaarik** [comment]
Ok, I figured it out... It was because there was still a 3.1 worker running in another virtualenv. Once I stopped that one the worker in the virtualenv with Celery 4.0 didn't get this error anymore.

I'm wondering now if I need two worker processes anyway, probably not. It's for 2 different projects, which both have their own virtualenv, but maybe I should run celery workers in another separate virtualenv?

**Comment by mhnagaoka** [comment]
We faced a similar problem and managed to solve it by specifying different names for each worker using the `-n` / `--hostname` argument.

Link to the documentation:
http://docs.celeryproject.org/en/v4.1.0/userguide/workers.html#starting-the-worker

**Comment by yuanke7** [comment]
> Changing the broker URL from "pyamqp://" to "amqp://" resolved the issue.

No effect.

**Comment by soderluk** [comment]
I ran to this exact same issue after upgrading from Celery 3.X to 4.X. Setting the configuration values made no difference. Restarting rabbitmq-server did the job. After RabbitMQ restarted, no more Unrecoverable errors in the Celery logs.
