### ISSUE TITLE
After connection lost to broker (SQS), celery is unable to reestablish a connection

### ISSUE THREAD

**Issue by alilucioboz** [celery/celery#3877]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
            billiard:3.5.0.2 sqs:N/A
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqs results:disabled

broker_url: u'sqs://localhost//'
```
- [x] I have verified that the issue exists against the `master` branch of Celery.
```
> pip freeze
amqp==2.1.4
anyjson==0.3.3
appdirs==1.4.2
billiard==3.5.0.2
boto==2.46.1
celery==4.0.2
kombu==4.0.2
packaging==16.8
pycurl==7.43.0
pyparsing==2.1.10
pytz==2016.10
six==1.10.0
vine==1.1.3
```

## Steps to reproduce

Add the following to `tasks.py`:

```
from celery import Celery

app = Celery('tasks', broker='sqs://')

@app.task()
def do_something():
    print "Processing..."
```

1. Start celery: `celery -A tasks worker --loglevel=info`
2. In another window, start the python console: `python -i tasks.py`
3. Verify that it's working: `do_something.delay()`
4. Disconnect from the internet
5. Reconnect to internet after 2 minutes
6. `do_something.delay()` now doesn't get picked up by workers

Nothing is logged by the worker

## Expected behavior

The workers should establish a connection again. This works when I use celery==3.1.25, it will reestablish the connection and continue to work. So either this was introduced in celery==4.0.0 or one of the other dependencies.

## Actual behavior

The worker never reestablishes a connection, and the queue just builds up with tasks.

On other systems, I have seen the following where it's not able to reconnect:
```
HTTP Error: SQSError: 500 Internal Server Error
consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/var/www/celery/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/var/www/celery/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/var/www/celery/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 584, in start
    c.loop(*c.loop_args())
  File "/var/www/celery/local/lib/python2.7/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/http/curl.py", line 111, in on_readable
    return self._on_event(fd, _pycurl.CSELECT_IN)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/http/curl.py", line 124, in _on_event
    self._process_pending_requests()
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/http/curl.py", line 130, in _process_pending_requests
    self._process(curl)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/http/curl.py", line 178, in _process
    buffer=buffer, effective_url=effective_url, error=error,
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 146, in __call__
    svpending(*ca, **ck)
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 139, in __call__
    return self.throw()
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 136, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/funtools.py", line 100, in _transback
    return callback(ret)
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 139, in __call__
    return self.throw()
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 136, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/funtools.py", line 98, in _transback
    callback.throw()
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/funtools.py", line 96, in _transback
    ret = filter_(*args + (ret,), **kwargs)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/aws/connection.py", line 269, in _on_list_ready
    raise self._for_status(response, body)
SQSError: SQSError: 500 Internal Server Error
```

As well as:
```
Empty body: SQSError: 599 TCP connection reset by peer
consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/var/www/celery/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/var/www/celery/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/var/www/celery/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 584, in start
    c.loop(*c.loop_args())
  File "/var/www/celery/local/lib/python2.7/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/http/curl.py", line 111, in on_readable
    return self._on_event(fd, _pycurl.CSELECT_IN)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/http/curl.py", line 124, in _on_event
    self._process_pending_requests()
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/http/curl.py", line 132, in _process_pending_requests
    self._process(curl, errno, reason)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/http/curl.py", line 178, in _process
    buffer=buffer, effective_url=effective_url, error=error,
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 146, in __call__
    svpending(*ca, **ck)
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 139, in __call__
    return self.throw()
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 136, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/funtools.py", line 100, in _transback
    return callback(ret)
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 139, in __call__
    return self.throw()
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/promises.py", line 136, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/funtools.py", line 98, in _transback
    callback.throw()
  File "/var/www/celery/local/lib/python2.7/site-packages/vine/funtools.py", line 96, in _transback
    ret = filter_(*args + (ret,), **kwargs)
  File "/var/www/celery/local/lib/python2.7/site-packages/kombu/async/aws/connection.py", line 269, in _on_list_ready
    raise self._for_status(response, body)
SQSError: SQSError: 599 TCP connection reset by peer
Connected to sqs://localhost//
```
It logged that it connected, but it wasn't picking up any tasks and the queue continued to grow.

**Comment by ghoranyi** [comment]
I think we have the same problem. Our celery workers are dying one by one due to this error (since SQS does fail in responding in some cases). We are using a very similar setup:
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12 billiard:3.5.0.2 sqs:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqs results:disabled
```
```
[2017-03-14 08:00:43,237: ERROR/MainProcess] Callback <promise@0x7f6c8afe86d8> raised exception: SQSError: 599 SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
Traceback (most recent call last):
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/kombu/async/http/curl.py", line 178, in _process
    buffer=buffer, effective_url=effective_url, error=error,
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/vine/promises.py", line 146, in __call__
    svpending(*ca, **ck)
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/vine/promises.py", line 139, in __call__
    return self.throw()
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/vine/promises.py", line 136, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/vine/funtools.py", line 100, in _transback
    return callback(ret)
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/vine/promises.py", line 139, in __call__
    return self.throw()
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/vine/promises.py", line 136, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/vine/funtools.py", line 98, in _transback
    callback.throw()
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/vine/funtools.py", line 96, in _transback
    ret = filter_(*args + (ret,), **kwargs)
  File "/opt/prezi/virtualenv/local/lib/python2.7/site-packages/kombu/async/aws/connection.py", line 269, in _on_list_ready
    raise self._for_status(response, body)
SQSError: SQSError: 599 SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
```

**Comment by kaushalmishra** [comment]
Is there any update on this issue. I am facing the same issue.

**Comment by ghoranyi** [comment]
I started to debug a bit, but nothing yet.
Here are some more details on the symptom:
I've started celery with debug logging. At 18:06:55 I've disconnected my internet. Then at 18:10:00 I've reconnected.
You can find the logs here: https://gist.github.com/ghoranyi/ebc96411b92baf0eb7b00223e3717453
Even after reconnecting my internet and waiting a couple of mins, the worker could not recover.

**Comment by ghoranyi** [comment]
Also, this is pretty obviously not a celery issue but a kombu, right? Should we move the issue over there?

**Comment by msrb** [comment]
Possibly related to https://github.com/celery/kombu/pull/733 (?)

Note I think I have a workaround for this issue [here]. I've been successfully testing it for a week now. It's not a real fix though. 

It's possible that the real fix is already in (kombu's) master branch.

[here]: https://github.com/msrb/kombu/commit/cebbcd22c3ca779a5450903b3eba39a79fbba52d

**Comment by georgepsarakis** [comment]
@msrb could you please explain the logic of the fix? It may be valid. The master branch of `kombu` indeed contains some fixes on re-connection logic.

**Comment by auvipy** [comment]
should be fixed by https://github.com/celery/kombu/pull/733
