### ISSUE TITLE
Die of RABBITMQ address would cause error to celery, celerybeat and CPU 100% usage

### ISSUE THREAD

**Issue by cryptogun** [celery/celery#3893]
I found that my laptop fan is loud and CPU reached 100% at 2017-03-06 04:09. And there are 2 errors in my celery/celerybeat logs: `ERROR: Pidfile (celerybeat.pid) already exists.` and `ERROR/MainProcess] consumer: Cannot connect to amqp:`.
I think `supervisor` starting `celerybeat` repeatedly is the cause of high CPU usage.
Okay, now I know what happened:
- Broker: amqp:// 192.168.1.2 (is localhost)
- Power cut off, router's shutdown. So no 192.168.1.x assigned.
- Laptop has battery.
- Next task scheduling.

Then celery `cannot connect to amqp:`. But why celerybeat keeps `celerybeat.pid` file after unable to connect to broker and exited?
Here's the detail:

```log
[2017-03-05 17:17:01 +0800] [977] [INFO] Starting gunicorn 19.6.0
[2017-03-05 17:17:22,607: INFO/MainProcess] beat: Starting...
[2017-03-05 17:17:22,841: INFO/MainProcess] Connected to amqp://site:**@192.168.1.2:5672/site_vhost
[2017-03-05 17:17:22,934: INFO/MainProcess] mingle: searching for neighbors

# 3 crontab tasks (one 0,10,20,30,40,50 * * * *, two 1,11,21,31,41,51 * * * *)
[2017-03-05 17:30:00,002: INFO/MainProcess] Scheduler: Sending due task TASK_A (homepage.tasks.task_a)
[2017-03-05 17:30:00,006: INFO/MainProcess] Received task: homepage.tasks.task_a[86a4f8fe-7e8d-4526-9ae8-0016bd7a2348]  
[2017-03-05 17:30:00,178: INFO/PoolWorker-4] Task homepage.tasks.task_a[86a4f8fe-7e8d-4526-9ae8-0016bd7a2348] succeeded in 0.0022326859999566295s: 'Already done pickday.'
[2017-03-05 17:31:00,002: INFO/MainProcess] Scheduler: Sending due task TASK_B (homepage.tasks.task_b)
[2017-03-05 17:31:00,005: INFO/MainProcess] Received task: homepage.tasks.task_b[fd3f72c4-8c49-46ec-949a-9b0a39aa4c95]  
[2017-03-05 17:31:00,008: INFO/MainProcess] Scheduler: Sending due task TASK_C (homepage.tasks.task_c)
[2017-03-05 17:31:00,012: INFO/MainProcess] Received task: homepage.tasks.task_c[4dcce5bd-40b2-466e-a1df-983f2d3e672f]  

[2017-03-05 17:31:00,119: INFO/PoolWorker-4] Task homepage.tasks.task_b[fd3f72c4-8c49-46ec-949a-9b0a39aa4c95] succeeded in 0.001223967999976594s: 'Already done cart.'
[2017-03-05 17:31:00,122: INFO/PoolWorker-4] Task homepage.tasks.task_c[4dcce5bd-40b2-466e-a1df-983f2d3e672f] succeeded in 0.0005572640000082174s: 'Already done goodtopic (create threads).'

--------------------------------------------------------------
[2017-03-05 17:40:00,004: INFO/MainProcess] Scheduler: Sending due task TASK_A (homepage.tasks.task_a)
ERROR: Pidfile (celerybeat.pid) already exists.
Seems we're already running? (pid: 1376)
celery beat v4.0.2 (latentcall) is starting.

# Above three outputs loop forever... and no other outputs.
--------------------------------------------------------------
[2017-03-05 17:40:00,010: INFO/MainProcess] Received task: homepage.tasks.task_a[70f1e3bb-3975-4c04-a523-817cafde5718]  
[2017-03-05 17:40:00,473: INFO/PoolWorker-5] Task homepage.tasks.task_a[70f1e3bb-3975-4c04-a523-817cafde5718] succeeded in 0.003183575000093697s: 'Already done pickday.'
[2017-03-05 17:40:09,530: INFO/MainProcess] missed heartbeat from celery_default@laptop
[2017-03-05 17:40:09,614: INFO/MainProcess] missed heartbeat from celery_pdf@laptop
=============================
[2017-03-05 17:41:07,421: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/kombu/transport/base.py", line 236, in on_readable
    reader(loop)
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/amqp/connection.py", line 464, in drain_events
    return self.blocking_read(timeout)
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/amqp/connection.py", line 468, in blocking_read
    frame = self.transport.read_frame()
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/amqp/transport.py", line 237, in read_frame
    frame_header = read(7, True)
  File "/home/a/Desktop/sitesite/siteenv/lib/python3.5/site-packages/amqp/transport.py", line 377, in _read
    s = recv(n - len(rbuf))
TimeoutError: [Errno 110] Connection timed out
[2017-03-05 17:41:07,448: ERROR/MainProcess] consumer: Cannot connect to amqp://site:**@192.168.1.2:5672/site_vhost: [Errno 101] Network is unreachable.
Trying again in 2.00 seconds...
=============================
[2017-03-05 17:41:14,640: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
TimeoutError: [Errno 110] Connection timed out
Trying again in 32.00 seconds...



[2017-03-05 17:45:15,297: ERROR/MainProcess] consumer: Cannot connect to amqp://site:**@192.168.1.2:5672/site_vhost: [Errno 101] Network is unreachable.
[2017-03-05 17:45:15 +0800] [977] [INFO] Handling signal: term
worker: Warm shutdown (MainProcess)
worker: Warm shutdown (MainProcess)


[2017-03-05 18:32:26 +0800] [868] [INFO] Starting gunicorn 19.6.0
[2017-03-05 18:32:38,359: ERROR/MainProcess] consumer: Cannot connect to amqp://site:**@192.168.1.2:5672/site_vhost: [Errno 101] Network is unreachable.
Trying again in 2.00 seconds...
...
[2017-03-05 18:32:58,462: INFO/MainProcess] Connected to amqp://site:**@192.168.1.2:5672/site_vhost
[2017-03-05 18:32:58,488: INFO/MainProcess] mingle: searching for neighbors
```

**Comment by thedrow** [comment]
Can you please provide a minimal test case for us to reproduce the problem?

**Comment by cryptogun** [comment]
Well I don't have time now. Sorry... Should I provide a virtual machine disk? And how to simulate the time ticking? Cause waiting a day takes too long and changing the system time requires many clicks...

**Comment by thedrow** [comment]
We need a *minimal* test case that has the fewest conditions possible to reproduce the problems you are having.
We recommend that you'll try the next celery release which is coming soon. A fix to a bug causing 100% CPU usage has been committed there.

**Comment by nicbou** [comment]
@thedrow, I can add more information to this issue.

The minimal test case is simple: create a RabbitMQ-based celery queue, restart RabbitMQ and send a task to it while celery is restarting.

Our reproduction steps are the following:

1. Have a Docker image (Ubuntu 16.04, Python 2.7.12) with the following package versions:
   ```
   amqp==2.2.2
   billiard==3.5.0.3
   celery==4.0.2
   gunicorn==19.7.1
   kombu==4.1.0
   (plus some other unrelated packages)
   ```
   This image is an API that queues Celery tasks for a separate docker image.
2. Have a separate `rabbitmq:3.6-management` Docker image
3. In one terminal, look at the API CPU usage, and in another, look at the API logs.
4. Restart the RabbitMQ Docker image
5. Queue a task as RabbitMQ is restarting

The CPU usage immediately skyrockets and will never return to normal. The code hangs at the `celery.chain` call and the task is never processed. If I run the exact same code and call `celery.chain` again a few seconds later, it works. However, the first task is never cleared and the CPU usage does not return to normal.

**Comment by nicbou** [comment]
This StackOverflow question looks oddly like the same issue: https://stackoverflow.com/questions/16478048/celery-connection-broker-lost-makes-cpu-usage-go-to-100

**Comment by nicbou** [comment]
It seems like the issue only happens if we make the `celery.chain` call before the connection to RabbitMQ is restored (see `Connected to amqp://i2r:**@jobqueue:5672//` in the logs). Subsequent requests are handled properly.

**Comment by auvipy** [comment]
Nicolas, do you have any fix in practice?

**Comment by nicbou** [comment]
We simply moved to another library as this prevented us from going to production. We now use pika.

**Comment by auvipy** [comment]
what is it's update with celery 4.4rc?
