### ISSUE TITLE
Preventing Celery from creating Exchanges celery, celeryev, celeryev.pidbox, reply.celery.pidbox

### ISSUE THREAD

**Issue by gangofmumbai** [celery/celery#3895]
Hitting Access refused while launching celery worker because Celery tries to create the new exchange while using RabbitMQ. I am using RabbitMQ server hosted by devOps and rules for creating new exchanges and queues are very strict. Is there a way around it?
Celery Version used : 3.1.25

      celery -A MyApp worker -l INFO
      [2017-03-07 11:43:55,165: INFO/MainProcess] Connected to amqp://user:**@rmqdev.com:5671/vhost
      [2017-03-07 11:43:55,486: ERROR/MainProcess] Unrecoverable error: AccessRefused(403, u"ACCESS_REFUSED - access to exchange 'celeryev' in vhost 'vhost' refused for user 'user'", (40, 10), 'Exchange.declare')
      Traceback (most recent call last):
        File "c:\dropbox\plan\lib\site-packages\celery\worker\__init__.py", line 206, in start
          self.blueprint.start(self)
        File "c:\dropbox\plan\lib\site-packages\celery\bootsteps.py", line 123, in start
          step.start(parent)
        File "c:\dropbox\plan\lib\site-packages\celery\bootsteps.py", line 374, in start
          return self.obj.start()
        File "c:\dropbox\plan\lib\site-packages\celery\worker\consumer.py", line 280, in start
          blueprint.start(self)
        File "c:\dropbox\plan\lib\site-packages\celery\bootsteps.py", line 123, in start
          step.start(parent)
        File "c:\dropbox\plan\lib\site-packages\celery\worker\consumer.py", line 555, in start
          enabled=self.send_events, groups=self.groups,
        File "c:\dropbox\plan\lib\site-packages\celery\events\__init__.py", line 150, in __init__
          self.enable()
        File "c:\dropbox\plan\lib\site-packages\celery\events\__init__.py", line 169, in enable
          serializer=self.serializer)
        File "c:\dropbox\plan\lib\site-packages\kombu\messaging.py", line 85, in __init__
          self.revive(self._channel)
        File "c:\dropbox\plan\lib\site-packages\kombu\messaging.py", line 222, in revive
          self.declare()
        File "c:\dropbox\plan\lib\site-packages\kombu\messaging.py", line 105, in declare
          self.exchange.declare()
        File "c:\dropbox\plan\lib\site-packages\kombu\entity.py", line 174, in declare
          nowait=nowait, passive=passive,
        File "c:\dropbox\plan\lib\site-packages\amqp\channel.py", line 622, in exchange_declare
          (40, 11),  # Channel.exchange_declare_ok
        File "c:\dropbox\plan\lib\site-packages\amqp\abstract_channel.py", line 69, in wait
          return self.dispatch_method(method_sig, args, content)
        File "c:\dropbox\plan\lib\site-packages\amqp\abstract_channel.py", line 87, in dispatch_method
          return amqp_method(self, args)
        File "c:\dropbox\plan\lib\site-packages\amqp\channel.py", line 243, in _close
          reply_code, reply_text, (class_id, method_id), ChannelError,
      AccessRefused: Exchange.declare: (403) ACCESS_REFUSED - access to exchange 'celeryev' in vhost 'vhost' refused for user 'user'

I tried on master branch but it failed with different reason since my project has windows dependency. So I had to stick to `3.1.25`.

## Steps to reproduce
Need a Rabbitmq server which does not allow to create new exchanges.
## Expected behavior
Expecting a way to override or specify the exchanges celery
## Actual behavior
Get Access refused error.

**Comment by rsichny** [comment]
probably you can extend Exchange class, [override `declare()` method](http://docs.celeryproject.org/projects/kombu/en/latest/reference/kombu.html#kombu.Exchange.declare) to do nothing and then use [explicit queues declaration](http://docs.celeryproject.org/en/latest/userguide/routing.html#defining-queues)

**Comment by aaronroe** [comment]
You might already know this, but just to put it out there -
If you can get around the dependency issues and use a newer version of celery, the following shouldn't declare any exchanges or queues:
- explicitly define your queues, exchanges, and routing keys, and use queues that are created using the no_declare=True optional parameter.
- set worker_enable_remote_control to False
- Set task_create_missing_queues to False
- Run the worker with the --without-gossip, --without-heartbeat, and --without-mingle arguments
