### ISSUE TITLE
Celery4 + Rabbit + Redis, workers stop executing tasks while RabbitMQ disk usage skyrockets

### ISSUE THREAD

**Issue by manneorama** [celery/celery#3916]
## Checklist
- [x] I have included the output of ``celery -A proj report`` in the issue.
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://******:6379/0

task_serializer: 'json'
theoracle: <module 'theoracle' from '/******/minion/local/lib/python2.7/site-packages/theoracle/__init__.pyc'>
event_queue_ttl: 60
worker_send_task_events: False
enable_utc: True
timezone: 'UTC'
task_default_queue: 'default-20170313-0'
resource_intensive_task: <@task: minion_worker.celery_tasks.exception_handling_task.resource_intensive_task of minion:0x7f6706dd8ed0>
worker_max_tasks_per_child: 1
standard_task: <@task: minion_worker.celery_tasks.exception_handling_task.standard_task of minion:0x7f6706dd8ed0>
accept_content: ['json']
include: ['minion_worker.celery_tasks.bootstrap',
 'minion_worker.celery_tasks.exception_handling_task',
 'minion_worker.celery_tasks.notify_task']
result_backend: u'redis://******:6379/0'
result_serializer: 'json'
timedelta: <type 'datetime.timedelta'>
task_acks_late: True
task_routes: {
    u'minion_worker.celery_tasks.bootstrap.celery_bootstrap': {   'queue': 'bootstrap.linux-20170313-0',
                                                                  'routing_key': u'********'},
    u'minion_worker.celery_tasks.exception_handling_task.resource_intensive_task': {   'queue': 'heavy.linux-20170313-0',
                                                                                       'routing_key': u'********'},
    u'minion_worker.celery_tasks.exception_handling_task.standard_task': {   'queue': 'main.linux-20170313-0',
                                                                             'routing_key': u'********'},
    u'minion_worker.celery_tasks.notify_task.dummy_task': {   'queue': 'bootstrap.linux-20170313-0',
                                                              'routing_key': u'********'},
    u'minion_worker.celery_tasks.notify_task.notify_task': {   'queue': 'bootstrap.linux-20170313-0',
                                                               'routing_key': u'********'}}
Queue: <class 'kombu.entity.Queue'>
result_expires: datetime.timedelta(2)
notify_task: <@task: minion_worker.celery_tasks.notify_task.notify_task of minion:0x7f6706dd8ed0>
task_queues: 
    (<unbound Queue default-20170313-0 -> <unbound Exchange u''(direct)> -> default-20170313-0>,
 <unbound Queue bootstrap.linux-20170313-0 -> <unbound Exchange minion(topic)> -> bootstrap.linux-20170313-0.#>,
 <unbound Queue heavy.linux-20170313-0 -> <unbound Exchange minion(topic)> -> heavy.linux-20170313-0>,
 <unbound Queue main.linux-20170313-0 -> <unbound Exchange minion(topic)> -> main.linux-20170313-0>)
dummy_task: <@task: minion_worker.celery_tasks.notify_task.dummy_task of minion:0x7f6706dd8ed0>
task_create_missing_queues: False
celery_bootstrap: <@task: minion_worker.celery_tasks.bootstrap.celery_bootstrap of minion:0x7f6706dd8ed0>
worker_prefetch_multiplier: 1
worker_disable_rate_limits: True
broker_url: u'amqp://minion:********@*******:5672/minion_host'
os: <module 'os' from '/******/minion/lib/python2.7/os.pyc'>
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
We're not quite sure how to reproduce this outside our own environment, since we don't know if the combination Celery4 + our canvas is the thing causing the troubles to begin with. Anyway, we're using a canvas that looks something like this:
```
chain(
    chain(
        group(chain(a11, b11, c11), chain(a12, b12, c12), ...) | callback1.
        group(chain(a21, b21, c21), chain(a22, b22, c22), ...) | callback2
    ),
    notify_slack
)
```
Together with custom error handling since we've noticed that everything just halts completely if anything raises an exception that isn't caught before reaching Celery (something to do with the chords, it seems).

Anyway, we've recently upgraded to Celery 4.0.2 from 3.1.25, and that's where the problems started. 
    
## Expected behavior
RabbitMQ and Celery play nice for extended periods of time (as was the case with Celery 3.1.25)

## Actual behavior
Upon a restart of the rabbit instance and all of the workers, everything works fine. But after a while, Rabbit's disk usage starts climbing (specifically the folder mnesia/minion_broker/msg_store_persistent), reaching 400 GB in just a couple of hours), while the chains stop functioning after the first group has been successfully executed.

Seeing this in worker logs:
`[2017-03-16 09:38:24,533: ERROR/MainProcess] Control command error: error(104, 'Connection reset by peer')`

Traceback (timestamp omitted for brevity):
```
error: [Errno 104] Connection reset by peer
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    self._write(s)
  File "/env/local/lib/python2.7/site-packages/amqp/transport.py", line 269, in write
    write(view[:offset])
  File "/env/local/lib/python2.7/site-packages/amqp/method_framing.py", line 174, in write_frame
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/env/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 64, in send_method
    (0, exchange, routing_key, mandatory, immediate), msg
  File "/env/local/lib/python2.7/site-packages/amqp/channel.py", line 1748, in _basic_publish
    mandatory=mandatory, immediate=immediate,
  File "/env/local/lib/python2.7/site-packages/kombu/messaging.py", line 203, in _publish
    exchange_name, declare,
  File "/env/local/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
    **opts
  File "/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 265, in _publish_reply
    serializer=self.mailbox.serializer)
  File "/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 135, in reply
    ticket=ticket)
  File "/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 112, in dispatch
    return self.dispatch(**body)
  File "/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 129, in handle_message
    self.node.handle_message(body, message)
  File "/env/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 42, in on_message
Traceback (most recent call last):
[2017-03-16 09:38:24,533: ERROR/MainProcess] Control command error: error(104, 'Connection reset by peer')
```

**Comment by raphael0202** [comment]
Having exactly the same problem, since an upgrade from Celery 3.1.24 to 4.0.2.
The rabbitmq log is quickly filled with the following (repeatedly):
```
=INFO REPORT==== 11-Apr-2017::14:00:26 ===
accepting AMQP connection <0.30406.2966> (172.31.44.163:59852 -> 172.31.10.34:5672)

=WARNING REPORT==== 11-Apr-2017::14:00:26 ===
closing AMQP connection <0.30406.2966> (172.31.44.163:59852 -> 172.31.10.34:5672):
connection_closed_abruptly
```
My celery report:
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:rpc

CELERY_ACKS_LATE: True
CELERY_TASK_SERIALIZER: 'pickle'
CELERY_RESULT_SERIALIZER: 'pickle'
CELERY_ACCEPT_CONTENT: ['pickle']
CELERYD_LOG_FORMAT: '%(asctime)s - Celery-%(processName)s - %(levelname)s - %(message)s'
CELERYD_CONCURRENCY: 4
CELERYBEAT_SCHEDULE: {
    }
CELERYD_PREFETCH_MULTIPLIER: 1
CELERYBEAT_MAX_LOOP_INTERVAL: 15
CELERY_EVENT_QUEUE_EXPIRES: 60
CELERY_RESULT_BACKEND: 'rpc'```

**Comment by auvipy** [comment]
any change after using latest release or fixes from master? would be helpful if you could try 4.2 when its released and let us know

**Comment by auvipy** [comment]
let us know its status with celery 4.2 rc4

**Comment by llybin** [comment]
![image](https://user-images.githubusercontent.com/5445357/45415173-3af92400-b6a7-11e8-9d92-6ec595b672a3.png)

celery==4.2.1
kombu==4.2.1

**Comment by auvipy** [comment]
do you have any fix in mind?

**Comment by llybin** [comment]
I [increased](https://phpsolved.com/ubuntu-16-increase-maximum-file-open-limit-ulimit-n/) ulimit on celery nodes, the problem began to be reproduced much less often. On one celery node I switched on redis broker and on this machine the problem gone away fully. Maybe kombu does not close some descriptors.. Redis and RabbitMQ host on one machine.

**Comment by llybin** [comment]
Perhaps the problem is related to https://github.com/celery/celery/issues/5047

**Comment by auvipy** [comment]
thanks for reporting. there is two pr open in celery and kombu to fix retry issue. so please check https://github.com/celery/kombu/pull/920 too

**Comment by auvipy** [comment]
Haven't closed the issue for further verification. do you have any fix in practice?

**Comment by sposs** [comment]
Hi,
Any news after DCUS? I'm facing this issue too and it's quite irritating...

**Comment by rgeens** [comment]
In case anybody is interested in digging further, for https://github.com/celery/celery/issues/5047 I added a retry, which while I think a good thing in itself, doesn't fix the underlying rabbitmq connection loss. I suspect that connection loss is causing a bunch of different issues, including this one, it's the same sort of connection reset / command control error behavior.

I was able to reproduce the connection loss, but I haven't had time to dig deeper to find the cause: https://github.com/celery/celery/issues/5047#issuecomment-420665195 . Somebody getting to the bottom of that might help with this issue.

**Comment by sposs** [comment]
Why closed? Have you found the problem?

**Comment by auvipy** [comment]
please check the issue https://github.com/celery/celery/pull/5066 report if it doesn't fix

**Comment by joekohlsdorf** [comment]
It doesn't fix it, it is a band-aid fix.

**Comment by rgeens** [comment]
I think the underlying problem is https://github.com/celery/celery/issues/5047#issuecomment-420665195 . I dug a bit further into it and noted my findings at https://github.com/celery/celery/issues/5047#issuecomment-433733601 . It appears Celery isn't sending rabbitmq heartbeats on one of two connections when using pyamq. This then causes rabbitmq to kill the connection after a while. I also found that when using librabbitmq instead of pyamq, it didn't reproduce anymore. I haven't had time to look further into what's going wrong with pyamq.

**Comment by auvipy** [comment]
can you try celery==4.4.0 and share the trackback?

**Comment by auvipy** [comment]
hi this still occuring in master?
