### ISSUE TITLE
"DecodeError: No JSON object could be decoded" when running Django example

### ISSUE THREAD

**Issue by eoconnor** [celery/celery#3922]
## Checklist

- [ X ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ X ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I cloned the Celery repo from the master branch. The only thing I changed were the CELERY_BROKER_URL and CELERY_RESULT_BACKEND parameters in examples/django/proj/settings.py, to reference my local Redis installation. I then ran through the Django example as documented in the README.

## Expected behavior
Was expecting the same output as documented in the Django example README.

## Actual behavior
I got this instead:
```
$ python manage.py shell
Python 2.7.9 (default, Feb 10 2015, 03:28:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from demoapp.tasks import add, mul, xsum
>>> res = add.delay(2,3)
>>> res
<AsyncResult: 17e43b39-b05b-47cf-8b4b-acc40cefb197>
>>> res.get()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 189, in get
    on_message=on_message,
  File "/usr/local/lib/python2.7/site-packages/celery/backends/async.py", line 189, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/celery/backends/async.py", line 251, in _wait_for_pending
    self.on_wait_for_pending(result, timeout=timeout, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/backends/redis.py", line 60, in on_wait_for_pending
    for meta in result._iter_meta():
  File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 374, in _iter_meta
    return iter([self._get_task_meta()])
  File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 370, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 352, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 668, in _get_task_meta_for
    return self.decode_result(meta)
  File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 271, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 278, in decode
    accept=self.accept)
  File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/json.py", line 93, in loads
    return _loads(s)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
DecodeError: No JSON object could be decoded
```

## Celery report output
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.9
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost/

SECURE_SSL_REDIRECT: False
SECURE_HSTS_SECONDS: 0
USE_X_FORWARDED_PORT: False
CSRF_COOKIE_SECURE: False
LANGUAGE_CODE: u'en-us'
ROOT_URLCONF: u'proj.urls'
LOGIN_URL: '/accounts/login/'
EMAIL_HOST_PASSWORD: u'********'
TEST_NON_SERIALIZED_APPS: []
DEFAULT_CHARSET: 'utf-8'
SESSION_SERIALIZER: 'django.contrib.sessions.serializers.JSONSerializer'
STATIC_ROOT: u''
ALLOWED_HOSTS: []
EMAIL_HOST: 'localhost'
MESSAGE_STORAGE: 'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX: '[Django] '
FILE_UPLOAD_PERMISSIONS: None
STATICFILES_FINDERS: 
    (u'django.contrib.staticfiles.finders.FileSystemFinder',
 u'django.contrib.staticfiles.finders.AppDirectoriesFinder')
SESSION_CACHE_ALIAS: 'default'
SESSION_COOKIE_DOMAIN: None
SESSION_COOKIE_NAME: 'sessionid'
CELERY_BROKER_URL: u'redis://localhost:6379/0'
TIME_INPUT_FORMATS: ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
SECURE_REDIRECT_EXEMPT: []
DATABASES: {
    u'default': {   u'ENGINE': u'django.db.backends.sqlite3',
                    u'HOST': u'',
                    u'NAME': u'test.db',
                    u'PASSWORD': u'********',
                    u'PORT': u'',
                    u'USER': u''}}
EMAIL_SSL_KEYFILE: u'********'
FILE_UPLOAD_DIRECTORY_PERMISSIONS: None
THOUSAND_SEPARATOR: ','
FILE_UPLOAD_HANDLERS: ['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
DEFAULT_CONTENT_TYPE: 'text/html'
APPEND_SLASH: True
FIRST_DAY_OF_WEEK: 0
DATABASE_ROUTERS: u'********'
EMAIL_USE_SSL: False
YEAR_MONTH_FORMAT: 'F Y'
STATICFILES_STORAGE: 'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES: {
    'default': {   'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
SERVER_EMAIL: 'root@localhost'
SESSION_COOKIE_PATH: '/'
SILENCED_SYSTEM_CHECKS: []
MIDDLEWARE_CLASSES: 
    (u'django.middleware.common.CommonMiddleware',
 u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware')
USE_I18N: True
SECRET_KEY: u'********'
LANGUAGE_COOKIE_NAME: 'django_language'
DEFAULT_INDEX_TABLESPACE: ''
LOGGING_CONFIG: 'logging.config.dictConfig'
TEMPLATE_LOADERS: 
    (u'django.template.loaders.filesystem.Loader',
 u'django.template.loaders.app_directories.Loader')
WSGI_APPLICATION: u'proj.wsgi.application'
FORMAT_MODULE_PATH: None
X_FRAME_OPTIONS: 'SAMEORIGIN'
CSRF_COOKIE_NAME: 'csrftoken'
AUTH_PASSWORD_VALIDATORS: u'********'
USE_X_FORWARDED_HOST: False
CSRF_HEADER_NAME: 'HTTP_X_CSRFTOKEN'
EMAIL_TIMEOUT: None
SECURE_SSL_HOST: None
SIGNING_BACKEND: 'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE: False
SECURE_BROWSER_XSS_FILTER: False
CSRF_COOKIE_DOMAIN: None
FILE_CHARSET: 'utf-8'
DEBUG: True
CSRF_TRUSTED_ORIGINS: []
LANGUAGE_COOKIE_DOMAIN: None
DEFAULT_FILE_STORAGE: 'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS: 
    (u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.messages',
 u'django.contrib.staticfiles',
 u'django.contrib.admin',
 u'demoapp')
LANGUAGES_BIDI: ['he', 'ar', 'fa', 'ur']
SECURE_HSTS_INCLUDE_SUBDOMAINS: False
STATICFILES_DIRS: 
    ()
is_overridden: <bound method Settings.is_overridden of <Settings "proj.settings">>
PREPEND_WWW: False
SECURE_PROXY_SSL_HEADER: None
LANGUAGE_COOKIE_AGE: None
SESSION_COOKIE_HTTPONLY: True
DEBUG_PROPAGATE_EXCEPTIONS: False
INTERNAL_IPS: []
MEDIA_URL: u''
MONTH_DAY_FORMAT: 'F j'
MANAGERS: 
    ()
SESSION_EXPIRE_AT_BROWSER_CLOSE: False
TIME_FORMAT: 'P'
AUTH_USER_MODEL: 'auth.User'
DATE_INPUT_FORMATS: ['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']
AUTHENTICATION_BACKENDS: ['django.contrib.auth.backends.ModelBackend']
USE_THOUSAND_SEPARATOR: False
PASSWORD_RESET_TIMEOUT_DAYS: u'********'
SESSION_FILE_PATH: None
CACHE_MIDDLEWARE_ALIAS: 'default'
SESSION_SAVE_EVERY_REQUEST: False
NUMBER_GROUPING: 0
SESSION_ENGINE: 'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW: 'django.views.csrf.csrf_failure'
LOCALE_PATHS: []
LOGIN_REDIRECT_URL: '/accounts/profile/'
CELERY_TASK_SERIALIZER: u'json'
DECIMAL_SEPARATOR: '.'
IGNORABLE_404_URLS: []
CSRF_COOKIE_PATH: '/'
TEMPLATE_STRING_IF_INVALID: ''
ALLOWED_INCLUDE_ROOTS: []
USE_L10N: True
FIXTURE_DIRS: []
FORCE_SCRIPT_NAME: None
DATE_FORMAT: 'N j, Y'
MEDIA_ROOT: u''
DEFAULT_EXCEPTION_REPORTER_FILTER: 'django.views.debug.SafeExceptionReporterFilter'
ADMINS: 
    ()
TEMPLATE_DEBUG: True
DEFAULT_FROM_EMAIL: 'webmaster@localhost'
SECURE_CONTENT_TYPE_NOSNIFF: False
DATETIME_FORMAT: 'N j, Y, P'
TEMPLATE_DIRS: 
    ()
CELERY_ACCEPT_CONTENT: [u'json']
SITE_ID: 1
DISALLOWED_USER_AGENTS: []
LOGOUT_URL: '/accounts/logout/'
LOGGING: {
    u'disable_existing_loggers': False,
    u'filters': {   u'require_debug_false': {   u'()': u'django.utils.log.RequireDebugFalse'}},
    u'handlers': {   u'mail_admins': {   u'class': u'django.utils.log.AdminEmailHandler',
                                         u'filters': [   u'require_debug_false'],
                                         u'level': u'ERROR'}},
    u'loggers': {   u'django.request': {   u'handlers': [u'mail_admins'],
                                           u'level': u'ERROR',
                                           u'propagate': True}},
    u'version': 1}
SHORT_DATE_FORMAT: 'm/d/Y'
TEMPLATES: []
TEST_RUNNER: 'django.test.runner.DiscoverRunner'
CACHE_MIDDLEWARE_KEY_PREFIX: u'********'
EMAIL_USE_TLS: False
TIME_ZONE: u'America/Chicago'
FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_TABLESPACE: ''
TEMPLATE_CONTEXT_PROCESSORS: ['django.contrib.auth.context_processors.auth',
 'django.template.context_processors.debug',
 'django.template.context_processors.i18n',
 'django.template.context_processors.media',
 'django.template.context_processors.static',
 'django.template.context_processors.tz',
 'django.contrib.messages.context_processors.messages']
MIGRATION_MODULES: {
    }
SESSION_COOKIE_AGE: 1209600
SETTINGS_MODULE: u'proj.settings'
USE_ETAGS: False
LANGUAGES: [('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]
FILE_UPLOAD_TEMP_DIR: None
CSRF_COOKIE_AGE: 31449600
STATIC_URL: u'/static/'
EMAIL_PORT: 25
USE_TZ: True
SHORT_DATETIME_FORMAT: 'm/d/Y P'
CELERY_RESULT_BACKEND: u'redis://localhost/'
PASSWORD_HASHERS: u'********'
ABSOLUTE_URL_OVERRIDES: {
    }
LANGUAGE_COOKIE_PATH: '/'
CACHE_MIDDLEWARE_SECONDS: 600
EMAIL_SSL_CERTFILE: None
CSRF_COOKIE_HTTPONLY: False
DATETIME_INPUT_FORMATS: ['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y']
EMAIL_HOST_USER: ''
```

**Comment by georgepsarakis** [comment]
Can you try adding an extra setting [here](https://github.com/celery/celery/blob/master/examples/django/proj/settings.py#L16):

```
CELERY_RESULT_SERIALIZER = 'json'
```

**Comment by eoconnor** [comment]
That seems to work. I ran a bunch of examples after adding that line and did not see a recurrence of the exception.

**Comment by georgepsarakis** [comment]
I see, it shouldn't be caused in the first place though.

I just tried with current master and the following settings:
```
CELERY_BROKER_URL = 'redis://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_BACKEND = 'redis://'
CELERY_TASK_SERIALIZER = 'json'
```

and everything works.

Can you do the following please:
- Remove the `CELERY_RESULT_SERIALIZER` setting.
- Use `FLUSHALL` to truncate all Redis databases (**Note that this is a destructive command!**).
- Run again the example.

**Comment by georgepsarakis** [comment]
@eoconnor any update on this?

**Comment by eoconnor** [comment]
Sorry for the delayed response. Following those steps, the example worked just fine. Thanks!

**Comment by georgepsarakis** [comment]
@eoconnor thanks for the feedback. I will close this for now, but if you still have problems feel free to re-open.
