### ISSUE TITLE
Connection to broker lost. Trying to re-establish the connection...

### ISSUE THREAD

**Issue by dharanpdarsana** [celery/celery#3932]
We are using Django Rest Framework with MongoEngine, Redis, Celery and Kombu, and we are getting the following error in our logs:

`[2017-03-22 06:26:01,702: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 1039, in on_readable
    self.cycle.on_readable(fileno)
File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 667, in _receive
    ret.append(self._receive_one(c))
File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 678, in _receive_one
    response = c.parse_response()
File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2183, in parse_response
    return self._execute(connection, connection.read_response)
File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2176, in _execute
    return command(*args)
File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
ConnectionError: Error while reading from socket: ('Connection closed by server.',)

[2017-03-22 06:26:01,868: INFO/MainProcess] Connected to redis://:******************************/1

### Versions used
python==2.7.12
redis==3.2.3
kombu==4.0.2
Django==1.10.3
celery==4.0.2
amqp==2.1.1
billiard==3.5.0.2
pytz==2016.7
Django==1.10.3o

We have HaProxy infront of Redis cluster and connections, everything else work without any issues. Could you please help us trouble shoot this error ?
Or guide on what to look for and where to look for , etc ?

We really appreciate your help,

Thanks,
Darsana

**Comment by jpatel3** [comment]
@dharanpdarsana Do you have redis running?  Here is how you can validate -

```
$ redis-cli                                                                
redis 127.0.0.1:6379> ping
PONG
redis 127.0.0.1:6379> set mykey somevalue
OK
redis 127.0.0.1:6379> get mykey
"somevalue"
```

**Comment by dharanpdarsana** [comment]
@jpatel3 The connection is working and 90% of the connections are going through without any issue

**Comment by richmondwang** [comment]
I am also (suddenly) experiencing a broken pipe error.

```log
[2017-05-22 17:18:10,939: INFO/MainProcess] Connected to amqp://user123:**@192.168.99.100:5672//
[2017-05-22 17:18:10,955: INFO/MainProcess] mingle: searching for neighbors
[2017-05-22 17:18:10,965: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 38, in start
    self.sync(c)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 42, in sync
    replies = self.send_hello(c)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 55, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/celery/app/control.py", line 129, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/celery/app/control.py", line 81, in _request
    timeout=self.timeout, reply=True,
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/kombu/pidbox.py", line 315, in _broadcast
    serializer=serializer)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/kombu/pidbox.py", line 290, in _publish
    serializer=serializer,
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/kombu/messaging.py", line 194, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/kombu/messaging.py", line 194, in <listcomp>
    [maybe_declare(entity) for entity in declare]
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/kombu/messaging.py", line 102, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/kombu/common.py", line 125, in maybe_declare
    return _maybe_declare(entity, declared, ident, channel, orig)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/kombu/common.py", line 131, in _maybe_declare
    entity.declare(channel=channel)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/kombu/entity.py", line 185, in declare
    nowait=nowait, passive=passive,
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/amqp/channel.py", line 630, in exchange_declare
    wait=None if nowait else spec.Exchange.DeclareOk,
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 64, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/amqp/method_framing.py", line 174, in write_frame
    write(view[:offset])
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/amqp/transport.py", line 269, in write
    self._write(s)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/eventlet/greenio/base.py", line 397, in sendall
    tail = self.send(data, flags)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/eventlet/greenio/base.py", line 391, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/Users/richmond/Projects/backend/env/lib/python3.6/site-packages/eventlet/greenio/base.py", line 378, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [Errno 32] Broken pipe
[2017-05-22 17:18:11,032: INFO/MainProcess] Connected to amqp://user123:**@192.168.99.100:5672//
[2017-05-22 17:18:11,046: INFO/MainProcess] mingle: searching for neighbors
[2017-05-22 17:18:12,075: INFO/MainProcess] mingle: all alone
[2017-05-22 17:18:12,104: INFO/MainProcess] celery@Richmonds-Mac-mini.local ready.
```

**Comment by Kurara** [comment]
I have the same problem and I'm using the same versions and I can't find a solution :(

**Comment by pengye91** [comment]
I am using kombu and running into the same situation, I'm not sure but I think maybe it's an issue working with haproxy.

When connected to haproxy which routes connections to several rabbitmq nodes, both producers and consumers have the same "connection to broker lost" issue, but when directly connected to a rabbitmq node, the issue never occurs.

**Comment by mistercrunch** [comment]
Also seeing this, and also behind haproxy

**Comment by Surgo** [comment]
Maybe it's happened SQS brokers too:

```
boto==2.47.0
celery==4.0.2
kombu==4.0.2
```

**Comment by miljevic** [comment]
The same problem here, Celery with RabbitMQ.

amqp==2.2.1
billiard==3.5.0.3
celery==4.1.0
kombu==4.1.0
pytz==2017.2
vine==1.1.4

**Comment by chrisspen** [comment]
I'm having this same problem with RabbitMQ running on localhost. It's odd that local connections would time-out or lose connection. I do have some pretty intensive tasks, and my CPU is at 100%, but my memory usage is low. Would that cause dropped connections?

    celery==4.0.2
    kombu==4.0.2
    Django==1.8.6
    RabbitMQ==3.2.4

**Comment by Shuklapreetika** [comment]
@chrisspen, were you able to resolve the issue? I am having a similar scenario, where while performing an CPU intensive task, the connection to redis gets dropped: the following is one of the many manifestation of exceptions which I receive:
```
[2017-10-11 13:34:57,244: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/python/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/python/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/usr/local/python/lib/python2.7/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/usr/local/python/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/usr/local/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 1039, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/usr/local/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 714, in _brpop_read
    **options)
  File "/usr/local/python/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/python/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/usr/local/python/lib/python2.7/site-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/usr/local/python/lib/python2.7/site-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/usr/local/python/lib/python2.7/site-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
ConnectionError: Error while reading from socket: ('Connection closed by server.',)

```

**Comment by imaia** [comment]
I also had a " Connection to broker lost" using rabbit + celery under high CPU usage; not sure is related.

**Comment by Daynity** [comment]
I add this to my celery config and it works. 
``` python 
BROKER_HEARTBEAT = int(cp.getenv('BROKER_HEARTBEAT', 100))
BROKER_POOL_LIMIT = int(cp.getenv('BROKER_POOL_LIMIT', 10))
BROKER_CONNECTION_TIMEOUT = int(cp.getenv('BROKER_CONNECTION_TIMEOUT', 30))
BROKER_CONNECTION_MAX_RETRIES = int(cp.getenv('BROKER_CONNECTION_MAX_RETRIES', 200))
CELERYD_WORKER_LOST_WAIT = int(cp.getenv('CELERYD_WORKER_LOST_WAIT', 10))
```

**Comment by auvipy** [comment]
this might be an issue with HAProxy

**Comment by benjolitz** [comment]
@auvipy I doubt it. I do not use HAProxy and have been trying to use Celery 4.0.3 to migrate from 3.1.25.

I still get this error.

**Comment by auvipy** [comment]
Let wait for 4.2 release

**Comment by bingqiangzhang** [comment]
I'm having this same problem with  Redis running on localhost. My redis config **timeout** value is **5**.  When too many tasks executed  beyond 5 seconds, it would result in this exception:

```
[2018-03-28 10:13:09,557: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/python2.7/lib/python2.7/site-packages/celery-4.2.0rc1-py2.7.egg/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "/usr/local/python2.7/lib/python2.7/site-packages/celery-4.2.0rc1-py2.7.egg/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/python2.7/lib/python2.7/site-packages/celery-4.2.0rc1-py2.7.egg/celery/worker/consumer/consumer.py", line 598, in start
    c.loop(*c.loop_args())
  File "/usr/local/python2.7/lib/python2.7/site-packages/celery-4.2.0rc1-py2.7.egg/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/python2.7/lib/python2.7/site-packages/kombu/async/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/local/python2.7/lib/python2.7/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/python2.7/lib/python2.7/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/usr/local/python2.7/lib/python2.7/site-packages/kombu/transport/redis.py", line 714, in _brpop_read
    **options)
  File "/usr/local/python2.7/lib/python2.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/python2.7/lib/python2.7/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/usr/local/python2.7/lib/python2.7/site-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/usr/local/python2.7/lib/python2.7/site-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/usr/local/python2.7/lib/python2.7/site-packages/redis/connection.py", line 191, in _read_from_socket
    (e.args,))
ConnectionError: Error while reading from socket: ('Connection closed by server.',)
[2018-03-28 10:13:09,558: WARNING/MainProcess] Restoring 7 unacknowledged message(s)
```
And  i found that if  argument for celery application is too long, such as a string of  length 65000 ,and  the connection between celery and redis with closed and can't reconnect.
Here is the example:

```python
# filename: task.py
# test for celery task
import time
from celery import Celery
app = Celery('tasks', broker='redis://:@127.0.0.1:6379/2')

@app.task
def test(data):
    time.sleep(20)
```
start  2 celery worker
```bash
celery -A task worker -c 2 -l info 
```

```python
# filename: test.py
# produce celery task 
from mytask import test
for i in range(40):
    test.delay('1'*65000)
 ```
run  test 
```bash
python test.py
```
Wait for about 2mins, then run this command and you will find no connection between celery and redis is  ESTABLISHED.
```bash
netstat -natp | grep 6379 | grep ESTABLISHED
``` 
It indicated that connections between celery and redis   were  closed and reconnected failed.So what cause dropped connections and reconnected failed?

``` bash
celery-4.1.0 or celery-4.2.0rc1
kombu==4.1.0
billiard==3.5.0.3
pytz==2018.3
amqp==2.2.2
vine==1.1.4

redis 4.0.2
```
I don't know why this happened, but if timeout of redis.conf is set to 0, problems will disappeared.
Thank you.

**Comment by nfrik** [comment]
I have the same problem with amqp broker and:
kombu==4.2.1
celery==4.2.0

**Comment by bastova** [comment]
Same issue with celery==4.2.0 and kombu==4.2.1

**Comment by auvipy** [comment]
anyone had any fix in practice?

**Comment by wona-git** [comment]
Same issue with celery == 4.2.1 
how do I resolve this ?

**Comment by sunilx64** [comment]
same issue, I am using celery==4.2.0, kombu==4.2.0, and Rabbitmq cluster as broker 
any solution ?

**Comment by SuperMasterBlasterLaser** [comment]
I also have this problem. My logs are constantly spammed by this exceptions

**Comment by matteomartinelli** [comment]
Same here with latest celery, any fix available?

**Comment by Surgo** [comment]
I try following to suppress logs. It's works fine for me.

- SQS with botocore
- Retry when connection errror

```
from billiard.exceptions import (
    SoftTimeLimitExceeded as CelerySoftTimeLimitExceeded,
)
from botocore.exceptions import (
    ClientError as BotocoreClientError,
    HTTPClientError as BotocoreHTTPClientError,
)

@app.task(
    autoretry_for=(
        BotocoreClientError,
        BotocoreHTTPClientError,
        CelerySoftTimeLimitExceeded,
    ),
)
def my_task(user):
    pass
```

**Comment by shaoeChen** [comment]
hi.
i have the same problem when i use package version celery 4.2.1 and amqp 2.4.0.
now i try celery 4.2.1 and amqp 2.3.2, it seems good.
work well.
hope can help somebody who have the problem.

**Comment by ovidiu-munteanu** [comment]
@auvipy, I can see that this issue was closed but I am not sure if there is a fix for it yet or if one is planned... It would be great if you could confirm what the current status is, thanks.

**Comment by auvipy** [comment]
could you please try celery and kombu from the master and report again?

**Comment by ansonurpants** [comment]
I'm also having this issue. I tried the solution from @shaoeChen above using 2.3.2 amqp and 4.2.1 celery but still having this problem

**Comment by chidg** [comment]
Same issue, 
celery 4.2.1
kombu 4.3.0
amqp 2.4.1
redis 2.10.5

**Comment by AvnerCohen** [comment]
In the special case of AWS + cluster of Rabbit MQ, this configuration seems to solve it:
![image](https://user-images.githubusercontent.com/1297254/56468282-e71b9e00-6432-11e9-993a-f4d6c1f5d73e.png)

Default idle timeout is 60.

**Comment by zhumingu** [comment]
Same issue

redis==3.2.1  
celery[redis]==4.3.0

Restart celery will be ok

**Comment by auvipy** [comment]
try celery==4.4.0rc5

**Comment by neoword** [comment]
@auvipy would be good if you reference the change in `celery==4.4.0rc5` that fixes this issue for posterity.

FWIW, bumping to 4.4.0rc5 seems to have stabilized my issue.

**Comment by auvipy** [comment]
celery==4.4.0 is the current stable release. try that & report back.

**Comment by neoword** [comment]
`celery==4.4.0`
`kombu==4.6.7`
works!

**Comment by sidnaik03** [comment]
I am facing the same issue
`[2020-04-22 05:31:09,243: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "c:\users\administrator\code\user\cel_env\lib\site-packages\redis\connection.py", line 700, in send_packed_command
    sendall(self._sock, item)
  File "c:\users\administrator\code\user\cel_env\lib\site-packages\redis\_compat.py", line 8, in sendall
    return sock.sendall(*args, **kwargs)
  File "c:\users\administrator\code\user\cel_env\lib\site-packages\eventlet\greenio\base.py", line 403, in sendall
    tail = self.send(data, flags)
  File "c:\users\administrator\code\user\cel_env\lib\site-packages\eventlet\greenio\base.py", line 397, in send
    return self._send_loop(self.fd.send, data, flags)
  File "c:\users\administrator\code\user\cel_env\lib\site-packages\eventlet\greenio\base.py", line 384, in _send_loop
    return send_method(data, *args)
ConnectionResetError: An existing connection was forcibly closed by the remote host`

my pip list
`billiard==3.6.3.0
BTrees==4.4.1
celery==4.4.2
kombu==4.6.8`

**Comment by turbaszek** [comment]
I'm facing the same issue as reported in https://github.com/apache/airflow/issues/11622

The interesting thing is that it happens only when we try to run Celery worker in daemonized way.
```
celery==4.4.7
kombu==4.6.11
billiard==3.6.3.0
redis==3.5.3
```

**Comment by japsu** [comment]
I had a similar issue using the HAproxy provided by [redis-ha Helm chart](https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha). Turns out its default `timeout client` was `30s`, and Redis' default TCP keepalive interval is "[about 5 minutes](https://redis.io/topics/clients#tcp-keepalive)". Raising the `timeout client` and `timeout server` both to `330s`, the problem seems to have been fixed.

**Comment by auvipy** [comment]
> I had a similar issue using the HAproxy provided by [redis-ha Helm chart](https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha). Turns out its default `timeout client` was `30s`, and Redis' default TCP keepalive interval is "[about 5 minutes](https://redis.io/topics/clients#tcp-keepalive)". Raising the `timeout client` and `timeout server` both to `330s`, the problem seems to have been fixed.

should we provide this on the docs?

**Comment by IAmBotmaker** [comment]
Well, I'm not sure whether it's the right solution, but I changed my EC2 instance on Amazon on which I use celery+rabbitmq+gunicorn+supervisor as part of my infrastructure. 

- from 1Gb to that which has 2Gb (maybe you have different needs, so adjust accordingly)

As syslog file in Ubuntu showed - oom error was killing brokers and other things, and increasing server memory size helped to solve this.

Now my logs are clear from errors. 
And no need to adjust my code.

**Comment by auvipy** [comment]
> Well, I'm not sure whether it's the right solution, but I changed my EC2 instance on Amazon on which I use celery+rabbitmq+gunicorn+supervisor as part of my infrastructure of long (up to several hours long) tasks with thousands of messages managed by this 24/7 ...
> 
> ... - from 1Gb memory-sized to that which has 2Gb (maybe you have different needs, so adjust accordingly)
> 
> As syslog file in Ubuntu showed - oom error was killing brokers and other things, and increasing server memory size helped to solve this.
> 
> Now my logs are clear from errors.
> And no need to adjust my code.

very practical!

**Comment by atodniAr** [comment]
I had an application using celery with redis backend (haproxy) over k8s.

**Facts**:

- My haproxy deployment has a 37s timeout setting.
- Celery prompt similar error message every 37s, then reconnect to redis.

Thus, I think celery consumer lack a proper heartbeat with haproxy, which caused haproxy to break the connection on idle.

**Comment by thedrow** [comment]
> 
> 
> I had a similar issue using the HAproxy provided by [redis-ha Helm chart](https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha). Turns out its default `timeout client` was `30s`, and Redis' default TCP keepalive interval is "[about 5 minutes](https://redis.io/topics/clients#tcp-keepalive)". Raising the `timeout client` and `timeout server` both to `330s`, the problem seems to have been fixed.

Didn't this help?
We just need to document this.

**Comment by laczar** [comment]
is this solution applied or being planned on celery?

**Comment by hamid914** [comment]
I had this error with `amqp==5.0.8` and it is fixed by upgrading to `amqp==5.0.9`

**Comment by cathhuo** [comment]
i have the same issue in 5.2.7

**Comment by vlad-stack** [comment]
I have the same issue in 5.2.7, and 5.3.0b1

**Comment by DAAworld** [comment]
kombu==5.3.2
celery==5.3.4
redis==5.0.0

my config 
    BROKER_CONNECTION_MAX_RETRIES = 0
    CELERY_REDIS_RETRY_ON_TIMEOUT = True
    CELERY_REDIS_SOCKET_CONNECT_TIMEOUT = 5
    REDIS_BACKEND_HEALTH_CHECK_INTERVAL = 5

I closed my internet about 1 minutes, and celery beat was retried successed, but worker raise error : 
[2023-10-25 17:22:12,954: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/connection.py", line 435, in send_packed_command
    self._sock.sendall(item)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 742, in start
    c.loop(*c.loop_args())
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/transport/redis.py", line 1341, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/transport/redis.py", line 566, in on_readable
    chan.handlers[type]()
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/transport/redis.py", line 910, in _receive
    ret.append(self._receive_one(c))
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/transport/redis.py", line 920, in _receive_one
    response = c.parse_response()
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/client.py", line 786, in parse_response
    self.check_health()
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/client.py", line 824, in check_health
    conn.send_command("PING", self.HEALTH_CHECK_MESSAGE, check_health=False)
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/connection.py", line 457, in send_command
    self.send_packed_command(
  File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/connection.py", line 446, in send_packed_command
    raise ConnectionError(f"Error {errno} while writing to socket. {errmsg}.")
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
