### ISSUE TITLE
Unrecoverable error: UnicodeDecodeError

### ISSUE THREAD

**Issue by sieben** [celery/celery#3938]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

$ python3 -m celery -A tasks report

software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.5.2
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:redis:///

result_backend: 'redis:///'
broker_url: 'amqp://guest:********@localhost:5672//'
accept_content: ['json']
task_serializer: 'json'
enable_utc: True
timezone: 'Europe/Paris'
result_serializer: 'json'

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Launching with:

    python3 -m celery -A tasks  worker --loglevel=debug

## Expected behavior

Worker starting to run and perform tasks smoothly

## Actual behavior

After some seconds it fails and gives the following output:

```
[2017-03-27 10:42:51,530: CRITICAL/MainProcess] Unrecoverable error: UnicodeDecodeError('utf-8', b'N\xfd\x17=\x00\x00', 1, 2, 'invalid start byte')
Traceback (most recent call last):
  File "/home/sieben/.local/lib/python3.5/site-packages/celery-4.0.2-py3.5.egg/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/sieben/.local/lib/python3.5/site-packages/celery-4.0.2-py3.5.egg/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/sieben/.local/lib/python3.5/site-packages/celery-4.0.2-py3.5.egg/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/home/sieben/.local/lib/python3.5/site-packages/celery-4.0.2-py3.5.egg/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/home/sieben/.local/lib/python3.5/site-packages/celery-4.0.2-py3.5.egg/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/sieben/.local/lib/python3.5/site-packages/celery-4.0.2-py3.5.egg/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/home/sieben/.local/lib/python3.5/site-packages/celery-4.0.2-py3.5.egg/celery/worker/loops.py", line 85, in asynloop
    update_qos()
  File "/home/sieben/.local/lib/python3.5/site-packages/kombu/common.py", line 413, in update
    return self.set(self.value)
  File "/home/sieben/.local/lib/python3.5/site-packages/kombu/common.py", line 406, in set
    self.callback(prefetch_count=new_value)
  File "/home/sieben/.local/lib/python3.5/site-packages/celery-4.0.2-py3.5.egg/celery/worker/consumer/tasks.py", line 43, in set_prefetch_count
    apply_global=qos_global,
  File "/home/sieben/.local/lib/python3.5/site-packages/kombu/messaging.py", line 557, in qos
    apply_global)
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/channel.py", line 1828, in basic_qos
    wait=spec.Basic.QosOk,
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/abstract_channel.py", line 73, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/abstract_channel.py", line 93, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/connection.py", line 464, in drain_events
    return self.blocking_read(timeout)
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/connection.py", line 469, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/method_framing.py", line 72, in on_frame
    msg.inbound_header(buf)
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/serialization.py", line 564, in inbound_header
    self._load_properties(class_id, buf, offset)
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/serialization.py", line 521, in _load_properties
    props, offset = classes[class_id](buf, offset)
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/serialization.py", line 423, in decode_properties_basic
    _f, offset = loads('F', buf, offset)
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/serialization.py", line 228, in loads
    key = pstr_t(buf[offset:offset + keylen])
  File "/home/sieben/.local/lib/python3.5/site-packages/amqp/utils.py", line 82, in bytes_to_str
    return s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
```

If I run the same code but with python2.7 I get the following messages in the log: 

````
[2017-03-27 10:44:16,219: WARNING/MainProcess] Received and deleted unknown message.  Wrong destination?!?

The full contents of the message body was: body: [[], {}, {u'errbacks': None, u'callbacks': None, u'chord': None, u'chain': None}] (77b)
{content_type:'application/json' content_encoding:'utf-8'
  delivery_info:{u'consumer_tag': u'None4', u'redelivered': True, u'routing_key': u'celery', u'delivery_tag': 1, u'exchange': u''} headers={'\xe5\xca.\xdb\x00\x00\x00\x00\x00': None, 'P&5\x07\x00': None, 'T\nKB\x00\x00\x00': '10daae72-fea9-494a-a6f7-741b3d81c31c', 'N\xfd\x17=\x00\x00': 'gen27770@sieben-inria', '\xcfb\xddR': 'py', '9*\xa8': None, '\xb7/b\x84\x00\x00\x00': 0, '\xe0\x0b\xfa\x89\x00\x00\x00': None, '\xdfR\xc4x\x00\x00\x00\x00\x00': [None, None], 'T3\x1d ': '6tisch/sf0/01', '\xae\xbf': '10daae72-fea9-494a-a6f7-741b3d81c31c', '\x11s\x1f\xd8\x00\x00\x00\x00': '()', 'UL\xa1\xfc\x00\x00\x00\x00\x00\x00': '{}'}}
```

**Comment by thedrow** [comment]
It's impossible for us to recreate this without more information. Can you please provide the task you are using to reproduce this?

**Comment by rambhairao** [comment]
I  have the same issue for last 2 days. 
I am using Celery: 4.1.0
with Django as a backend, i am running a simple task [](http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#tut-celery) First step with celery 
Also using: 'django_celery_results'
and 'django_celery_beat'

**Comment by thedrow** [comment]
@rambhairao Can you provide more details?

**Comment by rambhairao** [comment]
thanks for the response
making a simple backend task using celery with Django  with # First step with Celery
Django version: 1.11.3
Celery: Lastest release
rabbitmq as a default message broker
and Django as  a backend_url
in Django settings.py Installed app I have
'django_celery_results',
 'django_celery_beat',
Getting Error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
when executing # Command 
celery -A app_name worker --app=app_name.celery:app --loglevel=INFO

**Comment by thedrow** [comment]
Can you reproduce the same problem on another computer? Preferably a server somewhere without your locale settings.

**Comment by rambhairao** [comment]
this is the error i'm getting on executing command
`(env) Macs-MacBook-Pro-2:google_outh3 mac$ celery -A google_outh3 worker --app=google_outh3.celery:app --loglevel=INFO
 
 -------------- celery@Macs-MacBook-Pro-2.local v4.1.0 (latentcall)
---- **** ----- 
--- * ***  * -- Darwin-14.5.0-x86_64-i386-64bit 2017-11-29 05:40:14
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         google_outh3:0x103aa4fd0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . google_outh3.celery.debug_task
  . outh_app3.tasks.add
  . outh_app3.tasks.mul
  . outh_app3.tasks.xsum

[2017-11-29 05:40:14,437: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-29 05:40:14,455: INFO/MainProcess] mingle: searching for neighbors
[2017-11-29 05:40:15,501: INFO/MainProcess] mingle: all alone
[2017-11-29 05:40:15,596: WARNING/MainProcess] /Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2017-11-29 05:40:15,596: INFO/MainProcess] celery@Macs-MacBook-Pro-2.local ready.
[2017-11-29 05:40:15,597: CRITICAL/MainProcess] Unrecoverable error: UnicodeDecodeError('utf-8', b'N\xfd\x17=\x00\x00', 1, 2, 'invalid start byte')
Traceback (most recent call last):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/loops.py", line 85, in asynloop
    update_qos()
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 417, in update
    return self.set(self.value)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 410, in set
    self.callback(prefetch_count=new_value)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/tasks.py", line 43, in set_prefetch_count
    apply_global=qos_global,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/messaging.py", line 558, in qos
    apply_global)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/channel.py", line 1814, in basic_qos
    wait=spec.Basic.QosOk,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 477, in blocking_read
    return self.on_inbound_frame(frame)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/method_framing.py", line 59, in on_frame
    msg.inbound_header(buf)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 550, in inbound_header
    self._load_properties(class_id, buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 507, in _load_properties
    props, offset = classes[class_id](buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 409, in decode_properties_basic
    _f, offset = loads('F', buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 214, in loads
    key = pstr_t(buf[offset:offset + keylen])
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/utils.py", line 82, in bytes_to_str
    return s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
[2017-11-29 05:40:15,701: ERROR/MainProcess] Error on stopping Gossip: UnicodeDecodeError('utf-8', b'N\xfd\x17=\x00\x00', 1, 2, 'invalid start byte')
Traceback (most recent call last):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/loops.py", line 85, in asynloop
    update_qos()
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 417, in update
    return self.set(self.value)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 410, in set
    self.callback(prefetch_count=new_value)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/tasks.py", line 43, in set_prefetch_count
    apply_global=qos_global,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/messaging.py", line 558, in qos
    apply_global)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/channel.py", line 1814, in basic_qos
    wait=spec.Basic.QosOk,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 477, in blocking_read
    return self.on_inbound_frame(frame)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/method_framing.py", line 59, in on_frame
    msg.inbound_header(buf)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 550, in inbound_header
    self._load_properties(class_id, buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 507, in _load_properties
    props, offset = classes[class_id](buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 409, in decode_properties_basic
    _f, offset = loads('F', buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 214, in loads
    key = pstr_t(buf[offset:offset + keylen])
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/utils.py", line 82, in bytes_to_str
    return s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 407, in stop
    self._close(c, True)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 416, in _close
    ignore_errors(c.connection, consumer.cancel)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 298, in ignore_errors
    return fun(*args, **kwargs)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/messaging.py", line 488, in cancel
    cancel(tag)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/channel.py", line 1440, in basic_cancel
    wait=None if nowait else spec.Basic.CancelOk,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 477, in blocking_read
    return self.on_inbound_frame(frame)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/method_framing.py", line 59, in on_frame
    msg.inbound_header(buf)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 550, in inbound_header
    self._load_properties(class_id, buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 507, in _load_properties
    props, offset = classes[class_id](buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 409, in decode_properties_basic
    _f, offset = loads('F', buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 214, in loads
    key = pstr_t(buf[offset:offset + keylen])
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/utils.py", line 82, in bytes_to_str
    return s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
(env) Macs-MacBook-Pro-2:google_outh3 mac$ LANG=en_US.UTF-8  celery -A google_outh3 worker --app=google_outh3.celery:app --loglevel=INFO
 
 -------------- celery@Macs-MacBook-Pro-2.local v4.1.0 (latentcall)
---- **** ----- 
--- * ***  * -- Darwin-14.5.0-x86_64-i386-64bit 2017-11-29 05:43:54
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         google_outh3:0x103aabfd0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . google_outh3.celery.debug_task
  . outh_app3.tasks.add
  . outh_app3.tasks.mul
  . outh_app3.tasks.xsum

[2017-11-29 05:43:54,792: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-29 05:43:54,811: INFO/MainProcess] mingle: searching for neighbors
[2017-11-29 05:43:55,840: INFO/MainProcess] mingle: all alone
[2017-11-29 05:43:55,928: WARNING/MainProcess] /Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2017-11-29 05:43:55,928: INFO/MainProcess] celery@Macs-MacBook-Pro-2.local ready.
[2017-11-29 05:43:55,929: CRITICAL/MainProcess] Unrecoverable error: UnicodeDecodeError('utf-8', b'N\xfd\x17=\x00\x00', 1, 2, 'invalid start byte')
Traceback (most recent call last):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/loops.py", line 85, in asynloop
    update_qos()
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 417, in update
    return self.set(self.value)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 410, in set
    self.callback(prefetch_count=new_value)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/tasks.py", line 43, in set_prefetch_count
    apply_global=qos_global,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/messaging.py", line 558, in qos
    apply_global)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/channel.py", line 1814, in basic_qos
    wait=spec.Basic.QosOk,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 477, in blocking_read
    return self.on_inbound_frame(frame)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/method_framing.py", line 59, in on_frame
    msg.inbound_header(buf)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 550, in inbound_header
    self._load_properties(class_id, buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 507, in _load_properties
    props, offset = classes[class_id](buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 409, in decode_properties_basic
    _f, offset = loads('F', buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 214, in loads
    key = pstr_t(buf[offset:offset + keylen])
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/utils.py", line 82, in bytes_to_str
    return s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
[2017-11-29 05:43:56,187: ERROR/MainProcess] Error on stopping Gossip: UnicodeDecodeError('utf-8', b'N\xfd\x17=\x00\x00', 1, 2, 'invalid start byte')
Traceback (most recent call last):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/loops.py", line 85, in asynloop
    update_qos()
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 417, in update
    return self.set(self.value)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 410, in set
    self.callback(prefetch_count=new_value)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/worker/consumer/tasks.py", line 43, in set_prefetch_count
    apply_global=qos_global,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/messaging.py", line 558, in qos
    apply_global)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/channel.py", line 1814, in basic_qos
    wait=spec.Basic.QosOk,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 477, in blocking_read
    return self.on_inbound_frame(frame)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/method_framing.py", line 59, in on_frame
    msg.inbound_header(buf)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 550, in inbound_header
    self._load_properties(class_id, buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 507, in _load_properties
    props, offset = classes[class_id](buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 409, in decode_properties_basic
    _f, offset = loads('F', buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 214, in loads
    key = pstr_t(buf[offset:offset + keylen])
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/utils.py", line 82, in bytes_to_str
    return s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 407, in stop
    self._close(c, True)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/celery/bootsteps.py", line 416, in _close
    ignore_errors(c.connection, consumer.cancel)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/common.py", line 298, in ignore_errors
    return fun(*args, **kwargs)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/kombu/messaging.py", line 488, in cancel
    cancel(tag)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/channel.py", line 1440, in basic_cancel
    wait=None if nowait else spec.Basic.CancelOk,
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/connection.py", line 477, in blocking_read
    return self.on_inbound_frame(frame)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/method_framing.py", line 59, in on_frame
    msg.inbound_header(buf)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 550, in inbound_header
    self._load_properties(class_id, buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 507, in _load_properties
    props, offset = classes[class_id](buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 409, in decode_properties_basic
    _f, offset = loads('F', buf, offset)
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/serialization.py", line 214, in loads
    key = pstr_t(buf[offset:offset + keylen])
  File "/Users/mac/Desktop/project_django/project3/env/lib/python3.6/site-packages/amqp/utils.py", line 82, in bytes_to_str
    return s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte`

**Comment by rambhairao** [comment]
No, i am not able to do this now to checking this on another server

**Comment by rambhairao** [comment]
I uninstall rabbitmq and celery from my mac, then install it and start a simple celery task 
But  giving same error

**Comment by rambhairao** [comment]
repeat the rabbitmq log file

**Comment by danhenriquesc** [comment]
@rambhairao Hi! Did you found the fix for this issue?

**Comment by auvipy** [comment]
could anyone try the master branch with all updated dependencies?

**Comment by auvipy** [comment]
could canyone try the patch pointed here https://github.com/celery/py-amqp/issues/181

**Comment by auvipy** [comment]
closing for lack of feedback
