### ISSUE TITLE
Consumer bootsteps fail to work if they require the Timer component 

### ISSUE THREAD

**Issue by dralley** [celery/celery#3955]
## Checklist

- [x] Affected Celery versions:  3.1.z, 4.0.z
- [x] Issue exists against the `master` branch of Celery.

## Steps to reproduce

```
from celery import Celery
from celery import bootsteps

class Reproducer(bootsteps.StartStopStep):
    requires = ('celery.worker.components:Timer', )

    def __init__(self, parent, **kwargs):
        print('{0!r} is in init'.format(parent))

    def start(self, worker):
        print('{0!r} is starting up'.format(worker))

        self.timer_ref = worker.timer.call_repeatedly(
            5,
            self.do_work,
            (worker, ),
            priority=10,
        )

    def do_work(self, worker):
        print('{0!r} heartbeat'.format(worker))

    def stop(self, parent):
        print('{0!r} is stopping'.format(parent))

    def shutdown(self, parent):
        print('{0!r} is shutting down'.format(parent))

app = Celery(broker='amqp://')
app.steps['consumer'].add(Reproducer)
```

1. Start the worker "celery worker -A reproducer.app"
2. Stop the broker "sudo systemctl stop rabbitmq-server"
3.  Wait a few seconds
4.  Restart the broker "sudo systemctl start rabbitmq-server"

## Expected behavior

Celery worker starts properly

## Actual behavior

```
[dalley@dhcp129-27 devel]$ celery worker -A reproducer
<Consumer: celery@dhcp129-27.rdu.redhat.com (initializing)> is in init
Traceback (most recent call last):
  File "/usr/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 139, in setup_instance
    self.blueprint.apply(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 214, in apply
    step.include(parent)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 384, in include
    inc, ret = self._should_include(parent)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 339, in _should_include
    return True, self.create(parent)
  File "/usr/lib/python2.7/site-packages/celery/worker/components.py", line 241, in create
    prefetch_multiplier=w.prefetch_multiplier,
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 335, in instantiate
    return instantiate(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/utils/imports.py", line 53, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 220, in __init__
    self.blueprint.apply(self, **dict(worker_options or {}, **kwargs))
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 214, in apply
    step.include(parent)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 343, in include
    return self._should_include(parent)[0]
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 339, in _should_include
    return True, self.create(parent)
  File "/usr/lib/python2.7/site-packages/celery/worker/components.py", line 39, in create
    if w.use_eventloop:
AttributeError: 'Consumer' object has no attribute 'use_eventloop'
```

**Comment by auvipy** [comment]
were you able to find any fix? if so feel free to send a pr

**Comment by cjh1** [comment]
I am seeing the same issue.

**Comment by almcc** [comment]
I'm not quite seeing the same thing, after starting the worker, stopping the broker and then restart broker is started (rabbitmq in docker for me), the worker reconnects ok, and accepts tasks, however the timer is no longer running. My code is very similar to above. 

```python
from celery import Celery
from celery import bootsteps

app = Celery('tasks', broker='pyamqp://guest@localhost//')


class PeriodicBackground(bootsteps.StartStopStep):
    requires = {'celery.worker.components:Timer'}

    def __init__(self, worker, background_interval=5.0, **kwargs):
        self.background_interval = background_interval
        self.background_timer = None

    def start(self, worker):
        print('START')
        self.background_timer = worker.timer.call_repeatedly(
            self.background_interval, self.trigger_background, (worker,), priority=10,
        )

    def stop(self, worker):
        print('STOP')
        if self.background_timer:
            self.background_timer.cancel()
            self.background_timer = None

    def terminate(self, worker):
        print('TERMINATE')

    def trigger_background(self, worker):
        print('BACKGROUND')


app.steps['worker'].add(PeriodicBackground)


@app.task
def example():
    print('EXAMPLE')
```

**Comment by dralley** [comment]
Attach it to the consumer instead of the worker

**Comment by dralley** [comment]
@auvipy no idea, it works fine without the "requires" so I've just ignored it since then.

**Comment by almcc** [comment]
@dralley Ah yes, when I attach it to the consumer I get the same error as you. And when I remove the requires timer, it works ok, so looks not to be fixed in 4.2. Looks like my issue is a separate one .
