### ISSUE TITLE
Tasks hang when using Rabbitmq cluster through HAProxy as result backend

### ISSUE THREAD

**Issue by bavaria95** [celery/celery#3956]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I have a cluster of 2 rabbitmq nodes (with mirrored queues) which I set up behind haproxy (IP of haproxy - `188.184.29.122`):
```
global
        daemon
listen rabbitmq 0.0.0.0:5672
        mode            tcp
        retries         3
        timeout client  3h
        timeout server  3h
        option          clitcpka
        option          tcplog
        default_backend rmqbackend

backend rmqbackend
        mode	   tcp
        server     x 188.184.82.60:5672 check
        server     y 188.184.81.248:5672 check backup
```

`188.184.82.60:5672` and `188.184.81.248:5672` pointing to rabbitmq instances.

And the following celery config:
```
BROKER_URL = 'pyamqp://guest:guest@188.184.29.122:5672//'
CELERY_RESULT_BACKEND = 'rpc://:@188.184.29.122:5672//'
```

For the completeness of the question adding definition of the task and example flask app:
```
from celery import Celery

app = Celery('tasks')
app.config_from_object('celeryconfig')

@app.task
def add(x, y):
    return x + y
```

```
from flask import Flask
from tasks import *

app = Flask(__name__)

@app.route("/task")
def task():
    r = add.delay(1, 1)
    return str(r.get())
```

Output of `celery -A proj report`:
```
software -> celery:3.1.25 (Cipater) kombu:3.0.37 py:2.7.5
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:rpc://188.184.29.122:5672//

BROKER_URL: 'amqp://guest:********@188.184.29.122:5672//'
CELERY_RESULT_BACKEND: 'rpc://188.184.29.122:5672//'
```

## Expected behavior
I start Celery with `celery -A tasks worker --loglevel=info --purge`, then app server with `gunicorn app:app -b 0.0.0.0:5000 -w 4 -p pid --log-level debug`. Request to the app_server:5000 work good, but I expect to be able to stop one rabbitmq node (on `188.184.82.60`) and the app is available to respond in the same way.

## Actual behavior
When I kill the rabbitmq node I get that in celery logs (which is ok):
```
[2017-04-04 11:09:06,267: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/worker/consumer.py", line 280, in start
    blueprint.start(self)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/lib/python2.7/site-packages/celery/worker/consumer.py", line 884, in start
    c.loop(*c.loop_args())
  File "/usr/lib/python2.7/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/usr/lib/python2.7/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/usr/lib/python2.7/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/usr/lib/python2.7/site-packages/kombu/transport/base.py", line 146, in _read
    drain_events(timeout=0)
  File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 324, in drain_events
    return amqp_method(channel, args)
  File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 530, in _close
    (class_id, method_id), ConnectionError)
ConnectionForced: (0, 0): (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
[2017-04-04 11:09:09,292: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@188.184.29.122:5672//: Socket closed.
Trying again in 2.00 seconds...

[2017-04-04 11:09:14,309: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@188.184.29.122:5672//: Socket closed.
Trying again in 4.00 seconds...
[2017-04-04 11:09:18,327: INFO/MainProcess] Connected to amqp://guest:**@188.184.29.122:5672//
```

But for some time all my request to the app server hang and in rabbitmq logs (on the backup node, `188.184.81.248`) I am getting a long stream of such messages (and in celery logs it does not display that task was received)
```
=WARNING REPORT==== 4-Apr-2017::11:11:04 ===
closing AMQP connection <0.15366.16> (188.184.29.122:43780 -> 188.184.81.248:5672):
client unexpectedly closed TCP connection
```

In a few minutes I am able again to make requests to the server.

**Comment by auvipy** [comment]
try latest release and report issues
