### ISSUE TITLE
-B, --beat options require djcelery

### ISSUE THREAD

**Issue by tgehrs** [celery/celery#3985]
I am attempting to start a worker on celery 4.0.2 with an embedded beat. According to docs this can be done with 
`$ celery -A proj worker -B`
However that then throws an import error:
`ImportError: No module named 'djcelery'`

## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
My installed versions:
```
celery==4.0.2
django-celery-beat==1.0.1
Django==1.10.3
```
django-celery is not installed
- [x] I have verified that the issue exists against the `master` branch of Celery.
did my best but having trouble tracking this down

## Steps to reproduce
include -B without django-celery installed
## Expected behavior
beat is embedded in the worker
## Actual behavior
beat fails to start, output below 

```[2017-04-18 21:09:17,428: WARNING/Beat] Process Beat:
[2017-04-18 21:09:17,428: WARNING/Beat] Traceback (most recent call last):
[2017-04-18 21:09:17,429: WARNING/Beat] File "/Users/Tyler/GitHub/merchantmanager/src/mmenv/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
[2017-04-18 21:09:17,429: WARNING/Beat] KeyError: 'scheduler'
[2017-04-18 21:09:17,429: WARNING/Beat] During handling of the above exception, another exception occurred:
[2017-04-18 21:09:17,429: WARNING/Beat] Traceback (most recent call last):
[2017-04-18 21:09:17,429: WARNING/Beat] File "/Users/Tyler/GitHub/merchantmanager/src/mmenv/lib/python3.5/site-packages/billiard/process.py", line 306, in _bootstrap
    self.run()
[2017-04-18 21:09:17,429: WARNING/Beat] File "/Users/Tyler/GitHub/merchantmanager/src/mmenv/lib/python3.5/site-packages/celery/beat.py", line 613, in run
    self.service.start(embedded_process=True)
[2017-04-18 21:09:17,430: WARNING/Beat] File "/Users/Tyler/GitHub/merchantmanager/src/mmenv/lib/python3.5/site-packages/celery/beat.py", line 528, in start
    humanize_seconds(self.scheduler.max_interval))
[2017-04-18 21:09:17,430: WARNING/Beat] File "/Users/Tyler/GitHub/merchantmanager/src/mmenv/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
[2017-04-18 21:09:17,430: WARNING/Beat] File "/Users/Tyler/GitHub/merchantmanager/src/mmenv/lib/python3.5/site-packages/celery/beat.py", line 572, in scheduler
    return self.get_scheduler()
[2017-04-18 21:09:17,430: WARNING/Beat] File "/Users/Tyler/GitHub/merchantmanager/src/mmenv/lib/python3.5/site-packages/celery/beat.py", line 563, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
[2017-04-18 21:09:17,430: WARNING/Beat] File "/Users/Tyler/GitHub/merchantmanager/src/mmenv/lib/python3.5/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
[2017-04-18 21:09:17,430: WARNING/Beat] File "/Users/Tyler/GitHub/merchantmanager/src/mmenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
[2017-04-18 21:09:17,430: WARNING/Beat] File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[2017-04-18 21:09:17,431: WARNING/Beat] File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[2017-04-18 21:09:17,431: WARNING/Beat] File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
[2017-04-18 21:09:17,431: WARNING/Beat] File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[2017-04-18 21:09:17,431: WARNING/Beat] File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[2017-04-18 21:09:17,431: WARNING/Beat] File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[2017-04-18 21:09:17,431: WARNING/Beat] File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
[2017-04-18 21:09:17,431: WARNING/Beat] ImportError: No module named 'djcelery'
```

**Comment by auvipy** [comment]
this should have already been fixed with newer release. Report if not
