### ISSUE TITLE
exception in chain upstream doesn't signal downstream GroupResult

### ISSUE THREAD

**Issue by yoichi** [celery/celery#4004]
Suppose that we have a chain with the last element is a group:

```
chain(task_a.si(), group(task_b.si(), task_c.si(),...))
```

When exception occur in task_a, chain(...).delay().get() hangs while the error is detected in the worker side.

## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.

```
software -> celery:3.1.25 (Cipater) kombu:3.0.37 py:3.5.2
            billiard:3.3.0.23 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/

CELERY_RESULT_BACKEND: 'redis://localhost:6379/'
BROKER_URL: 'redis://localhost:6379//'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.5.2
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/

broker_url: 'redis://localhost:6379//'
result_backend: 'redis://localhost:6379/'
```
( e812c5780b4006516116f059ab498e1f043bdd50 in master)

## Steps to reproduce

run worker by "celery -A tasks worker -i info" with following code (tasks.py)

```
from celery import Celery

app = Celery('tasks', backend='redis://localhost:6379', broker='redis://localhost:6379')

@app.task
def work():
    pass

@app.task
def nop():
    pass

@app.task
def error():
    raise Exception("error!!!")
```

run chain by following code (tasks_run.py)

```
import celery
import tasks

c = celery.chain(tasks.error.si(), 
                 celery.group(tasks.work.si(), tasks.work.si()))
r = c.delay()
r.get()
```

## Expected behavior

When the worker detects the error as:
```
[2017-05-01 15:17:06,725: INFO/MainProcess] Received task: tasks.error[b74e2759-4caf-41c1-9694-37b8a58ce6c6]
[2017-05-01 15:17:06,727: ERROR/MainProcess] Task tasks.error[b74e2759-4caf-41c1-9694-37b8a58ce6c6] raised unexpected: Exception('error!!!',)
Traceback (most recent call last):
  File "/home/developer/python3-dev/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/developer/python3-dev/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/developer/TECH-51/tasks.py", line 15, in error
    raise Exception("error!!!")
Exception: error!!!
```

"r.get()" reraises the Exception on the client side.

## Actual behavior

"r.get()" hangs. Ctrl+c shows following stacktraces:

with Celery v3.1.25

```
$ python tasks_run.py 
^CTraceback (most recent call last):
  File "tasks_run.py", line 7, in <module>
    r.get()
  File "/home/developer/python3-dev/lib/python3.5/site-packages/celery/result.py", line 578, in get
    interval=interval, callback=callback, no_ack=no_ack)
  File "/home/developer/python3-dev/lib/python3.5/site-packages/celery/result.py", line 688, in join_native
    for task_id, meta in self.iter_native(timeout, interval, no_ack):
  File "/home/developer/python3-dev/lib/python3.5/site-packages/celery/backends/base.py", line 495, in get_many
    time.sleep(interval)  # don't busy loop.
KeyboardInterrupt
```

with Celery (master)

```
$ python tasks_run.py 
^CTraceback (most recent call last):
  File "tasks_run.py", line 7, in <module>
    r.get()
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/celery/result.py", line 635, in get
    on_message=on_message,
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/celery/result.py", line 746, in join_native
    on_message, on_interval):
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/celery/backends/async.py", line 143, in iter_native
    for _ in self._wait_for_pending(result, no_ack=no_ack, **kwargs):
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/celery/backends/async.py", line 256, in _wait_for_pending
    on_interval=on_interval):
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/celery/backends/async.py", line 57, in drain_events_until
    yield self.wait_for(p, wait, timeout=1)
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/celery/backends/async.py", line 66, in wait_for
    wait(timeout=timeout)
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/celery/backends/redis.py", line 69, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/redis/client.py", line 2260, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/redis/client.py", line 2181, in parse_response
    if not block and not connection.can_read(timeout=timeout):
  File "/home/developer/python3-dev-celery-master/lib/python3.5/site-packages/redis/connection.py", line 572, in can_read
    bool(select([sock], [], [], timeout)[0])
KeyboardInterrupt
```

## Workaround?

With celery v3.1.25, put single task at the end of the chain seems to resolve the issue (exception will be reraised).

```
import celery
import tasks

c = celery.chain(tasks.error.si(),
                 celery.group(tasks.work.si(), tasks.work.si()),
                 tasks.nop.si())
r = c.delay()
r.get()
```

On the other hand, with celery v4.0.2, the modified code sometime reraise the exception, and sometime hangs. An interesting thing is that if we insert time.sleep(0.5) just before r.get() in addition to add the single task at the end of the chain resolve the problem in v4.0.2.

Since we're going to use celery 3.1.25 with our code, I want to know if the workaround in v3.1.25 is correct.

**Comment by vadim-pavlov** [comment]
I might be wrong, but [this line](https://github.com/celery/celery/blob/e812c5780b4006516116f059ab498e1f043bdd50/celery/backends/base.py#L489) seems to be the root cause of the issue for the base backend, as it polls the same result from the **cache** over and over again.

**Comment by georgepsarakis** [comment]
Your workaround may also show that chords do not have the same behavior (see [Canvas](http://docs.celeryproject.org/en/latest/userguide/canvas.html#chains)):

> Chaining a group together with another task will automatically upgrade it to be a chord:

**Comment by yoichi** [comment]
> An interesting thing is that if we insert time.sleep(0.5) just before r.get() in addition to add the single task at the end of the chain resolve the problem in v4.0.2.

I found the difference comes from AsyncResult.get() can reraise exception by self._maybe_reraise_parent_error() only if the parent task finished before we call r.get().
