### ISSUE TITLE
Clarify support for task priority with redis backend

### ISSUE THREAD

**Issue by neutralino1** [celery/celery#4028]
The official documentation is not clear as to how to get task priorities to work with a redis backend.

I have tried the following and it does not work:
```python
@app.task(queue = 'priority_test', priority = 9)
def high_pri():
  print("HIGH")

@app.task(queue = 'priority_test', priority = 0)
def low_pri():
  sleep(1)
  print("LOW")
```

I started a worker with single concurrency, queued 100 low priority tasks, and then one high priority task and it got run last. I tried inverting the priorities, same result.

Searching through the code for `priority` doesn't show anything obvious.

Are tasks priorities supported with a redis back-end, and if so, what is the right way to set it up?

Thank you

**Comment by MrYoda** [comment]
As I know there is no priorities support in celery. You could emulate it on queue level:
```
CELERY_QUEUES = (
    Queue('high', Exchange('high'), routing_key='high'),
    Queue('normal', Exchange('normal'), routing_key='normal'),
    Queue('low', Exchange('low'), routing_key='low'),
)
CELERY_DEFAULT_QUEUE = 'normal'
CELERY_DEFAULT_EXCHANGE = 'normal'
CELERY_DEFAULT_ROUTING_KEY = 'normal'
CELERY_ROUTES = {
    # -- HIGH PRIORITY QUEUE -- #
    'myapp.tasks.check_payment_status': {'queue': 'high'},
    # -- LOW PRIORITY QUEUE -- #
    'myapp.tasks.close_session': {'queue': 'low'},
}
```

**Comment by muelli** [comment]
> As I know there is no priorities support in celery.

http://docs.celeryproject.org/en/latest/faq.html#does-celery-support-task-priorities states:

> 
> Does Celery support task priorities?
> 
> Answer: Yes, RabbitMQ supports priorities since version 3.5.0, and the Redis transport emulates priority support.

So Celery does support priority queues, right?

**Comment by muelli** [comment]
I'd appreciate an example of how to make proper use of priority queues with Celery without resorting to separate queues.

**Comment by Giaco9** [comment]
Hi, I'm trying to run a single worker with 2 different queues. One is with higher priority than the other one. I'm using celery v4.1.0 and as transport redis v3.2.6. This is my configuration. 

```
CELERY_QUEUES = (
    Queue('slow', Exchange('slow'), routing_key='slow'),
    Queue('fast', Exchange('fast'), routing_key='fast'),
)
CELERY_DEFAULT_QUEUE = 'fast'
CELERY_DEFAULT_EXCHANGE = 'fast'
CELERY_DEFAULT_ROUTING_KEY = 'fast'
CELERY_ROUTES = {
    'slow_task': {'queue': 'slow'},
    '*': {'queue': 'fast'},
}
```

In this way all my tasks are run randomly. Instead I need that all the "slow_task"s are run after all the other one. How can I do it?

The worker starts with this command

```
celery -A app worker -c 1 -n log@%h --loglevel=INFO -Q fast,slow
```

Thanks for your help

**Comment by typistX** [comment]
What does “and the Redis transport emulates priority support" mean? I’m yet to see a working example of this.

**Comment by phillbaker** [comment]
@typistX this works for us:

```
REDIS_HIGH_PRIORITY = 0
REDIS_LOW_PRIORITY = 9
...

a_task.apply_async(
    args=[bar_id],
    kwargs={'foo': 1},
    priority=REDIS_LOW_PRIORITY)
```

Two things that may help is using `-Ofair` for your worker, without it, task allocation may not follow these rules, see: https://medium.com/@taylorhughes/three-quick-tips-from-two-years-with-celery-c05ff9d7f9eb#d7ec. As well, you may need to reduce the `CELERYD_PREFETCH_MULTIPLIER` setting to `1` [(it can't be set to 0)](https://stackoverflow.com/a/16061666/2284646) (I also had to set this at the command line, e.g. `--prefetch-multiplier=1` instead of the settings variable).

**Comment by typistX** [comment]
@phillbaker - thanks a bunch Phill. Been trying a lot of things without much success so far. One thing I’ve noticed though, even with using all the settings above - if I omit the priority argument from a certain call, then priority is ignored altogether. 

That means that two tasks will perform in the order they were called, if one of them is missing the “priority” argument. Only if both functions are called with priority (say one with “0” and one with “9”) then priority is honored.

**Comment by phillbaker** [comment]
@typistX I actually did try without sending a priority and (in redis), and I think it does "work": 
* redis priority is "emulated" by splitting jobs into separate queues (ie if the queue is `celery`, jobs end up in (roughly) `celery`, `celery0`, `celery1`, `celery2`)
* so, jobs without a priority end up in the default queue (`celery`) which is the highest priority
* for tasks at the same priority, they (depending on the number of workers) will be executed in the order they were called


Note: a lot of the code for this is actually in kombu.

**Comment by typistX** [comment]
@phillbaker thanks for sticking with me on this Phill. 

> so, jobs without a priority end up in the default queue (celery) which is the highest priority

This the part that confuses me. What you’re basically saying is that a task with priority=0, is the same as a task without a priority arg. Which contradicts with the following?:

> actually did try without sending a priority and (in redis), and I think it does "work"

In any case, unless I’m misunderstanding something I think I will have to use separate workers for the tasks. Celery isn’t really good at priorities: If I send 15 priority=9 tasks and 1 priority=0 task it will get to the important one after like 10 tasks :/

**Comment by dejlek** [comment]
That is because after 4.0.1 priority=9 is HIGHER than priority=0 (thanks to @phillbaker for clarifying that in #4599) ...

**Comment by typistX** [comment]
@dejlek I think it was changed but then reverted back to 0 = high, 9 = low. So I think this unrelated...

**Comment by dejlek** [comment]
Read this: https://github.com/celery/celery/issues/4599#issuecomment-410916217

**Comment by manhtai** [comment]
@dejlek @SHxKM I see the Celery docs mentions about priority number like this:

> A number between 0 and 255, where 255 is the highest priority.
> Supported by: RabbitMQ, Redis (priority reversed, 0 is highest).

So it depends on brokers also.

**Comment by dejlek** [comment]
The point is not that it not documented. Problem is that different sources of information (Celery documentation AND code) give conflicting information!

**Comment by dejlek** [comment]
I have even asked about this on StackOverflow - https://stackoverflow.com/questions/49319834/could-someone-please-clarify-the-task-priority-usage-in-celery-tasks

**Comment by Tendrid** [comment]
I've read this whole thread, and every link therein, however, i still don't clearly understand how to use priority with a redis backend in celery, so i'll ask clear questions, in hopes of getting a clear answer for the sake of generations to come:

When using redis backend in celery 4.3.9:

1. when "priority=9" is fed into an apply_async, is that task handled _before_ one with "priority=0"
2. if i have a queue "a-foo", and i utilize "priority=9", does that simply make a queue called "a-foo9"
3. if i do not apply a priority at all, does that task go in to whatever queue it was routed, without a default priority (ie "a-foo" instead of "a-foo2"
4. if i set a task_default_priority of "9", and #2 is correct, does that mean all tasks without a priority, are put in to the queue "a-foo9"?
5. is Celery("myapp").conf.worker_prefetch_multiplier = 1 (shortened to one line for clarity) good enough to set the prefetch multiplier, or must i instead/in addition set it in a cli argument (if so, what is the argument)
6: if all of this is true, and redis priority is determined by alphabetical ordering of queue names, must i set the queue strategy for all of this to work as predicted? eg: Celery("myapp").conf.broker_transport_options = {"queue_order_strategy": "sorted"}

**Comment by Tendrid** [comment]
To end the confusion, i've started building a test repo that i can use to build simple and complex strategies as tests, to test prioritization: https://github.com/Tendrid/celery-redis-priority-test

With my first test, i've already learned that numeric prioritization is indeed backwards. (as to be expected, because b-medium0 comes _before_ b-medium9 alphanumerically sorted.)

Feel free to help expand on these tests, or give feedback on the structure of the repo in general.

**Comment by Tendrid** [comment]
We just discovered another oddity, and documented it as the 5 point in the readme in the test repo above.  Here is what we found:

If you override task priority by setting broker_transport_options to {"priority_steps":[0, 2, 4, 6, 8]}, 0 will be the highest priority. If you invert that to {"priority_steps":[8, 6, 4, 2, 0]}, 8 will be the highest. The order of priority_steps dictates priority order.

**Comment by dejlek** [comment]
@Tendrid , that is precisely why I created this issue - https://github.com/celery/celery/issues/4599 !! It *is* confusing, and should be well-documented...

**Comment by ericholscher** [comment]
Thanks for all the work here. I've just been implementing priority ordering, and it was indeed confusing. I think we've got it working 🤞

**Comment by Tendrid** [comment]
@ericholscher for default routing, take a look at https://github.com/Tendrid/celery-redis-priority-test/blob/master/app.py#L17

This line tells celery, with redis, to specifically use queues by sorted value (in alpha order).  If memory serves, without this line, the default configuration will utilize the queues with a round-robin strategy.

Hope that helps!

**Comment by auvipy** [comment]
anyone up for a PR?

**Comment by IamAbhiKaushik** [comment]
So can we set priority in tasks using just one queue or not?

**Comment by auvipy** [comment]
> Coming from [huey](https://github.com/coleifer/huey) I was expecting that Celery as the more mature project supports priority queues. The documentation says that priority queues are supported however [it also says this](https://docs.celeryproject.org/en/stable/userguide/routing.html?highlight=priority#redis-message-priorities):
> 
> > Redis itself has no notion of priorities.
> 
> This is not quite correct. By using sorted sets popping ([ZPOPMAX](https://redis.io/commands/ZPOPMAX) available since Redis 5) you can implement priorities with a single queue. There seems to be a lot already written (e.g. ericholscher mentions some implementation?) but I was hoping to find some clear summary of the status quo in the celery docs. And since that statement in the documentation is not quite right I am not sure if this is up to date.

Yes docs need some modifications, as they were written in pre redis 5 era :) . would you mind checking the codes & docs and come up with a PR or improving docs or may be some code?

**Comment by azin634** [comment]
according to the docs:

```
app.conf.broker_transport_options = {
    'queue_order_strategy': 'priority',
}
```
The config above will give you these queue names:
```
['celery', 'celery\x06\x163', 'celery\x06\x166', 'celery\x06\x169']
```

My question is, do we need to start the worker like this?
```
celery worker -A tasks -Q celery,celery\x06\x163,celery\x06\x166,celery\x06\x169
```

**Comment by der-joel** [comment]
Using the example configuration from the [docs](https://docs.celeryq.dev/en/latest/userguide/routing.html#redis-message-priorities) also seems to break worker inspection. 
Can anyone provide a working example for priority-based task queues using redis?

Code:
```python3
# init celery app
app = Celery(__name__,
             backend=REDIS_URL,
             broker=REDIS_URL)
# set broker transport options
app.conf.broker_transport_options = {
    'priority_steps': list(range(10)),
    'sep': ':',
    'queue_order_strategy': 'priority',
}
# inspect worker
print(f"worker config: {celery_app.control.inspect().conf()}")
```
Error-Traceback:
```
[2022-05-09 18:05:12,386: ERROR/celery-prefork-worker] Control command error: ValueError('not enough values to unpack (expected 3, got 1)')
Traceback (most recent call last):
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/celery/worker/pidbox.py", line 44, in on_message
    self.node.handle_message(body, message)
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/pidbox.py", line 141, in handle_message
    return self.dispatch(**body)
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/pidbox.py", line 108, in dispatch
    self.reply({self.hostname: reply},
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/pidbox.py", line 145, in reply
    self.mailbox._publish_reply(data, exchange, routing_key, ticket,
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/pidbox.py", line 275, in _publish_reply
    producer.publish(
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/messaging.py", line 177, in publish
    return _publish(
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/connection.py", line 524, in _ensured
    return fun(*args, **kwargs)
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/messaging.py", line 199, in _publish
    return channel.basic_publish(
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 593, in basic_publish
    return self.typeof(exchange).deliver(
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/transport/virtual/exchange.py", line 69, in deliver
    for queue in _lookup(exchange, routing_key):
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 702, in _lookup
    R = self.typeof(exchange).lookup(
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/transport/virtual/exchange.py", line 61, in lookup
    return {
  File "/home/work/PycharmProjects/mestiny/venv/project2Env/lib/python3.8/site-packages/kombu/transport/virtual/exchange.py", line 62, in <setcomp>
    queue for rkey, _, queue in table
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by ad-m-ss** [comment]
@der-joel in Django to have it workings it's enough in configuration to have:

```
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "queue_order_strategy": "priority",
    "priority_steps": list(range(10)),
}
CELERY_TASK_INHERIT_PARENT_PRIORITY = True
```

The exception you have is related to changing the `sep` while there are messages in the queue in Redis. Especially those message for direct configuration with the worker (ping etc.) is problematic. As a result, Celery is unable to parse the key name in Redis and crashes. If you want to change `sep` no messages can be in-fly at that moment.

**Comment by felixriese** [comment]
Thanks for the explanations!

Is there an easy way to test if the prioritization works? Two first steps would be:
* Can I somewhere list the queue names (`celery`, `celery1`, ...)?
* Can I read out the priority of a task in retrospective? (I was not able to do so via redis so far)

[I saw the tests in this repo https://github.com/Tendrid/celery-redis-priority-test and I like them! It is quite some overhead, though, to create automated tests with it]

**Comment by pappacena** [comment]
> The exception you have is related to changing the `sep` while there are messages in the queue in Redis. Especially those message for direct configuration with the worker (ping etc.) is problematic. As a result, Celery is unable to parse the key name in Redis and crashes. If you want to change `sep` no messages can be in-fly at that moment.

Just replying here for future references: I had the exact same exception as @der-joel . And even if I run `FLUSHALL` on redis and restart the workers, the problem continues. 

It seems that the problem is in kombu. The [virtual transport exchange](https://github.com/celery/kombu/tree/9abe689cd41362db27a6d1431bcb4c413fd7617e/kombu/transport/virtual) (which seems to be the responsible for broadcast messages communication) has no knowledge about the `sep` we use in celery at all.

I removed the custom `sep`, as suggested by @ad-m-ss and it seems to work fine.

**Comment by ShaleenAg** [comment]
is there any changes for the 5.XX version? I tried the methods above, but none seem to work for implementing priority.
