### ISSUE TITLE
A task defined as some_task(*args, param="default", **kwargs) fails

### ISSUE THREAD

**Issue by alexpirine** [celery/celery#4034]
## Steps to reproduce

Define your Celery task:

```python
from celery import shared_task

@shared_task()
def some_task(*args, param="default", **kwargs):
    return
```

Run `celery -A proj worker`

## Expected behavior

Celery loads.

## Actual behavior

Celery fails to load.

```console
Traceback (most recent call last):
  […]
  File "…/celery/__main__.py", line 14, in main
    _main()
  File "…/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "…/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "…/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "…/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "…/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "…/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "…/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "…/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "…/celery/worker/worker.py", line 95, in __init__
    self.on_before_init(**kwargs)
  File "…/celery/apps/worker.py", line 97, in on_before_init
    trace.setup_worker_optimizations(self.app, self.hostname)
  File "…/celery/app/trace.py", line 568, in setup_worker_optimizations
    app.finalize()
  File "…/celery/app/base.py", line 512, in finalize
    _announce_app_finalized(self)
  File "…/celery/_state.py", line 52, in _announce_app_finalized
    callback(app)
  File "…/celery/app/__init__.py", line 59, in <lambda>
    lambda app: app._task_from_fun(fun, **options)
  File "…/celery/app/base.py", line 453, in _task_from_fun
    '__header__': staticmethod(head_from_fun(fun, bound=bind)),
  File "…/celery/utils/functional.py", line 283, in head_from_fun
    exec(definition, namespace)
  File "<string>", line 2
    def some_task(*args, **kwargs, param="default"):
                                          ^
SyntaxError: invalid syntax
```

**Comment by alexpirine** [comment]
The actual problem seems to reside in the `_argsfromspec` function:

https://github.com/celery/celery/blob/master/celery/utils/functional.py#L228

**Comment by alexpirine** [comment]
OK, I am sorry. The issue seems to be solved on the master.

However… How do I fix it in my project? Could we expect a minor release soon?
