### ISSUE TITLE
Reporting with multiple memcached servers raises ValueError

### ISSUE THREAD

**Issue by JeffreyDevloo** [celery/celery#4059]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
```
oot@e187-2:~# celery -A ovs.celery_run report
Traceback (most recent call last):
  File "/usr/bin/celery", line 26, in <module>
    load_entry_point("celery", "console_scripts", "celery")()
  File "/usr/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 315, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 377, in handle_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 671, in run
    self.out(self.app.bugreport())
  File "/usr/lib/python2.7/dist-packages/celery/app/base.py", line 438, in bugreport
    return bugreport(self)
  File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 225, in bugreport
    app.conf.CELERY_RESULT_BACKEND or 'disabled'),
  File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 63, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 58, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 24, in _parse_url
    return (scheme, unquote(parts.hostname or '') or None, parts.port,
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '11211;10.100.187.32'
root@e187-2:~# celery --version
3.1.23 (Cipater)

```

- [x] I have verified that the issue exists against the `master` branch of Celery.
```
root@ovs01-201:~# celery --version
4.0.2 (latentcall)
root@ovs01-201:~# celery -A ovs.celery_run report
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 285, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 368, in handle_argv
    return self(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 363, in run
    self.out(self.app.bugreport())
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 895, in bugreport
    return bugreport(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 344, in bugreport
    results=maybe_sanitize_url(app.conf.result_backend or 'disabled'),
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/url.py", line 92, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/url.py", line 85, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/url.py", line 52, in url_to_parts
    parts.port,
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '11211;10.100.199.202'

```

## Steps to reproduce
- Install celery
- Setup Celery with multiple memcached server as result backend
- Run celery -A projectname report

Example configuration (fetched using celery shell -A projectname -> app.conf:
```
In [2]: app.conf['CELERY_RESULT_BACKEND']
Out[2]: 'cache+memcached://10.100.199.201:11211;10.100.199.202:11211;10.100.199.203:11211/'
```
This config is identical to the one in the examples: http://docs.celeryproject.org/en/latest/userguide/configuration.html#cache-backend-settings
**Celery does not crash. It is able to process tasks (offloaded to rabbitmq in our case) and able to push the results to memcached.**
## Expected behavior
Receive an overview of the celery project.
## Actual behavior
A stacktrace is presented with the user being completely clueless as to what has been potentially wrongly configured.
## Platform
Ubuntu 16.04.1 LTS

**Comment by auvipy** [comment]
ValueError: invalid literal for int() with base 10: '11211;10.100.199.202'

changing the value should work

**Comment by JeffreyDevloo** [comment]
Could you elaborate on what value would be correct? I have nothing to work with at the moment

**Comment by lskillen** [comment]
@auvipy @JeffreyDevloo Did you figure out a workaround for this? We encountered the same scenario.

**Comment by JeffreyDevloo** [comment]
@lskillen I have not found a solution so I am currently using a different result backend. My apologies that I can't help you any further (did not receive any additional input myself)

**Comment by lskillen** [comment]
@JeffreyDevloo Not a problem - Let's see what @auvipy has to say. :-)

I was able to "partially" workaround the issue by specifying the memcached servers in the (admittedly deprecated) `cache_backend` setting - For example:

```
CELERY_RESULT_BACKEND = "cache"
CELERY_CACHE_BACKEND = "memcached://cache1:11211;cache2:11211/"
```

But we still get the same `maybe_sanitize_url` when kombu is creating pid boxes. As in your situation celery continues to run, but I suspect whatever functionality relies on the pid boxes won't be working correctly (I assume it's for worker control commands).

It's strange that the official documentation lists multiple servers as an example, but perhaps it was never checked. I'm tempted to fork and fix it but I've got a lot on my plate right now. It seems like the code in `maybe_sanitize_url` should detect that splitting is in the string, and process the URls as `memcached://cache1:11211` and `memcached://cache:11211` separately, perhaps.

**Comment by thedrow** [comment]
@auvipy Why was this issue closed? What's the fix?

**Comment by auvipy** [comment]
Seems I miss judged the issue

**Comment by auvipy** [comment]
i request to try celery==4.4.0 and share the trackback

**Comment by auvipy** [comment]
closing for lack of feedback for now
