### ISSUE TITLE
Hanging celery_worker pytest fixture

### ISSUE THREAD

**Issue by pumazi** [celery/celery#4088]
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:db+postgresql://*******@localhost/*************

result_backend: u'db+postgresql://**********@localhost/****************'
broker_url: u'amqp://guest:********@localhost:5672//'
result_persistent: True
```
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

There are two tests in a class that use the pytest `celery.contrib.pytest.celery_worker` fixture. Individually the tests run and pass without issue. Together the first test passes and the second hangs with the following log output:

```pytb
[2017-06-14 16:10:45,617: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'register'",)
Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File ".../lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File ".../lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File ".../lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File ".../lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File ".../lib/python2.7/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File ".../lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 407, in connect
    conn.transport.register_with_event_loop(conn.connection, self.hub)
  File ".../lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 146, in register_with_event_loop
    loop.add_reader(connection.sock, self.on_readable, connection, loop)
  File ".../lib/python2.7/site-packages/kombu/async/hub.py", line 208, in add_reader
    return self.add(fds, callback, READ | ERR, args)
  File ".../lib/python2.7/site-packages/kombu/async/hub.py", line 159, in add
    self.poller.register(fd, flags)
AttributeError: 'NoneType' object has no attribute 'register'
```

## Expected behavior

I'd expect both tests to pass in sequence.

## Actual behavior

The pytest runner hangs.

**Comment by auvipy** [comment]
@blueyed could you share some insight?

**Comment by sadiqsahib** [comment]
Same issue.

**Comment by karenc** [comment]
The error seems to be related to a shared event loop.  I ran the tests and compared the objects used by the different tests.  It turns out that `Consumer.hub` is shared between all the `Consumer` objects, see  [consumer.py](https://github.com/celery/celery/blob/master/celery/worker/consumer/consumer.py#L409):

```python
conn.transport.register_with_event_loop(conn.connection, self.hub)
```

This is where `hub` is created, in [components.py](https://github.com/celery/celery/blob/master/celery/worker/components.py#L72):

```python
w.hub = get_event_loop()
```

This event loop is shared between the tests.  At the end of the first test, the event loop is terminated:

```python
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/worker/worker.py", line 205, in start
    self.terminate()                                                
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/worker/worker.py", line 259, in terminate
    self._shutdown(warm=False)                                      
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/worker/worker.py", line 266, in _shutdown
    self.blueprint.stop(self, terminate=not warm)                   
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/bootsteps.py", line 173, in stop
    description=what, propagate=False,                              
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/bootsteps.py", line 138, in restart
    self.send_all(parent, method, description, propagate=propagate) 
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)                                              
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/worker/components.py", line 87, in terminate
    w.hub.close()                                                   
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/kombu/async/hub.py", line 249, in close
    self._close_poller()         
```

The next test uses the same event loop without resetting it, which causes `poller` to be `None`, as shown in the traceback in the issue description.

I think if we ever get into a situation where we have more than one work controller, and one of them calls [shutdown](
https://github.com/celery/celery/blob/master/celery/worker/worker.py#L261), it is going to screw up the event loop for everyone else.

**Comment by alanjds** [comment]
I am hitting this problem outside of the tests :/

**Comment by alanjds** [comment]
Can this be fixed by checking if the hub is None and `get_event_loop()` again if so? This seems reasonable?

**Comment by alanjds** [comment]
Got able to re-run a worker after this changes on Kombu: https://github.com/alanjds/kombu/commit/1b4cd42dc749a052e026be538845e288d614c99c

Needed to manually reset `should_shutdown` and `shoud_terminate` on `celery.worker.state` too.

**Comment by auvipy** [comment]
feel free to send a pr

**Comment by alanjds** [comment]
@auvipy May the PR https://github.com/celery/kombu/pull/866 fix this issue.

I still need to figure out where/when `celery.worker.state.should_{shutdown,terminate}` should be reset, but Kombu' PR is needed anyway.

**Comment by auvipy** [comment]
thanks

**Comment by alanjds** [comment]
To the record, this was closed via this fix on Kombu: https://github.com/celery/kombu/pull/866

**Comment by auvipy** [comment]
thanks, I should have mentioned that while closing.
