### ISSUE TITLE
Consul Backend decodes key incorrectly

### ISSUE THREAD

**Issue by nuwang** [celery/celery#4096]
## Checklist
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.6.0
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:consul://localhost:8500/

broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'consul://localhost:8500/'
result_serializer: 'json'

## Steps to reproduce

Using Consul as a result backend for Celery with Python 3 will raise an exception.

## Expected behavior

Should store values successfully.

## Actual behavior

The following exception is raised in Python 3:
```
[2017-06-18 14:16:47,346: ERROR/MainProcess] Pool callback raised exception: AttributeError("'bytes' object has no attribute 'encode'",)
Traceback (most recent call last):
  File "/Users/Nuwan/work/cloudmanv2/venv/lib/python3.6/site-packages/billiard/pool.py", line 1748, in safe_apply_callback
    fun(*args, **kwargs)
  File "/Users/Nuwan/work/cloudmanv2/venv/lib/python3.6/site-packages/celery/worker/request.py", line 366, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "/Users/Nuwan/work/cloudmanv2/venv/lib/python3.6/site-packages/celery/backends/base.py", line 163, in mark_as_failure
    traceback=traceback, request=request)
  File "/Users/Nuwan/work/cloudmanv2/venv/lib/python3.6/site-packages/celery/backends/base.py", line 309, in store_result
    request=request, **kwargs)
  File "/Users/Nuwan/work/cloudmanv2/venv/lib/python3.6/site-packages/celery/backends/base.py", line 652, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/Users/Nuwan/work/cloudmanv2/venv/lib/python3.6/site-packages/celery/backends/consul.py", line 84, in set
    key = self._key_to_consul_key(key)
  File "/Users/Nuwan/work/cloudmanv2/venv/lib/python3.6/site-packages/celery/backends/consul.py", line 54, in _key_to_consul_key
    key = key.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
```
## Reason

The consul backend uses _key_to_consul_key to convert the key generated by the BaseKeyValueStore to a consul key path. However, when _key_to_consul_key receives the key on PY3, it's already a byte array, and therefore should be decoded to construct the path, instead of encoded as the code stands now.

## Fix
```
    def _key_to_consul_key(self, key):
        if PY3:
            key = key.decode('utf-8')
        return key if self.path is None else '{0}/{1}'.format(self.path, key)
```
Pull request follows.

**Comment by nuwang** [comment]
I can't recreate this with the latest version of Celery, and the fix I propose seems unnecessary, so closing this.
