### ISSUE TITLE
ResultConsumer greenlet race condition

### ISSUE THREAD

**Issue by psrok1** [celery/celery#4105]
When I tried to get result from task inside greenlet, I've got an exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/async.py", line 83, in run
    self.result_consumer.drain_events(timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 69, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get_message'
<Greenlet at 0x7efd9d8ba550: <bound method geventDrainer.run of <celery.backends.async.geventDrainer object at 0x7efd9d99f550>>> failed with AttributeError
```

Celery version:

```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
                   billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis
```

After some recon, I've found that error occurs, when `threading` module is monkey-patched by `gevent.monkey`. It seems that attribute `_pubsub` from `celery.backends.async.ResultConsumer` is initialized a bit too late. Bug is triggered by racing `greenletDrainer.start()` and `ResultConsumer.start()` initializers.

```python
    def add_pending_result(self, result, weak=False, start_drainer=True):
        if start_drainer:
            # Spawns greenlet and starts to drain events
            self.result_consumer.drainer.start()
        try:
            self._maybe_resolve_from_buffer(result)
        except Empty:
            # Initializes pubsub needed by drainer
            self._add_pending_result(result.id, result, weak=weak)
        return result
```

```python
class greenletDrainer(Drainer):
    #...

    def run(self):
        self._started.set()
        while not self._stopped.is_set():
            try:
                self.result_consumer.drain_events(timeout=1)
            except socket.timeout:
                pass
        self._shutdown.set()

    # self.result_consumer.drainer.start()
    def start(self):
        if not self._started.is_set():
            self._g = self.spawn(self.run)
            # Switches immediately to self.run
            self._started.wait()
```

Issue related with #3452.

Filtered Python trace and way to reproduce a bug can be found [in this Gist](https://gist.github.com/psrok1/8dc27d3cdf367573183fc3f1e5524293)

**Comment by psrok1** [comment]
Bypass:
```python
# Manually initialize consumer
celery_app.backend.result_consumer.start("")

def fetch(uuid):
    res = AsyncResult(uuid, app=celery_app).get()
    print res
```

**Comment by auvipy** [comment]
can you send a patch with test to fix the issue?
