### ISSUE TITLE
My task runs standalone successfully, but as a Celery task it fails.

### ISSUE THREAD

**Issue by bwest-at-xometry** [celery/celery#4113]
## Checklist

- [*] I have included the output of ``celery -A proj report`` in the issue.
- [ ] I have verified that the issue exists against the `master` branch of Celery.

Report:
```
        software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.13
                    billiard:3.5.0.2 py-amqp:2.1.4
        platform -> system:Darwin arch:64bit imp:CPython
        loader   -> celery.loaders.app.AppLoader
        settings -> transport:amqp results:amqp://guest:**@127.0.0.1:5672/
```

## Steps to reproduce
My task is compute and memory intensive and can run between 5 seconds and 10+ minutes, depending on the input.  As the size of the input increases, I reach a threshold where the task starts to fail.

The failure is consistent.  In particular, the task can be the first task after the Celery worker has started.

## Expected behavior
Task run stand alone completes successfully.

## Actual behavior
Task run as a Celery task fails:

```
libc++abi.dylib: terminating with uncaught exception of type char const*
[2017-06-27 14:24:57,119: ERROR/MainProcess] Process 'PoolWorker-2' pid:81830 exited with 'signal 6 (SIGABRT)'
[2017-06-27 14:24:57,135: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 6 (SIGABRT).',)
Traceback (most recent call last):
  File "/Users/bnwest/anaconda2/envs/celeryfour/lib/python2.7/site-packages/billiard/pool.py", line 1224, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT).
```

The unhandled exception appears to bubble from some C/C++ NumPy code.

There must be something with running my task in a Celery worker context that is giving me problems.  Any suggestion to help debug/fix this or configuration settings to try would be greatly appreciated.

**Comment by georgepsarakis** [comment]
@bwest-at-xometry can you try starting the worker with the `solo` pool?

**Comment by bwest-at-xometry** [comment]
--pool=solo fixed my problems.  Is there documentation on what now can and can not do with --pool=solo?

Thanks!

**Comment by georgepsarakis** [comment]
You can find some references on the `solo` pool in the [Worker documentation](http://docs.celeryproject.org/en/latest/userguide/workers.html).

Your problem seems to be with process forking and solo is a [single-threaded pool](http://docs.celeryproject.org/en/latest/internals/reference/celery.concurrency.solo.html). As you might have guessed, you will not gain any concurrency for your task, instead you must start more workers to increase processed task rate.

**Comment by georgepsarakis** [comment]
If you can consider the issue resolved, please close :smile: !

**Comment by bwest-at-xometry** [comment]
Thank you, again.

**Comment by georgepsarakis** [comment]
@bwest-at-xometry you are most welcome!

**Comment by samizdis** [comment]
"Is there documentation on what one can and can not do with --pool=solo?"

Not really, see https://github.com/celery/celery/issues/3061

Essentially --pool=solo just stops the worker threading, so only one task is run (per worker) at once.

One additional thing that's worth knowing is that broadcast is also affected, so any remote-control stuff (e.g. inspect().active() ) gets blocked, see http://docs.celeryproject.org/en/latest/userguide/workers.html#remote-control and also https://github.com/celery/celery/issues/3768

**Comment by drdataflow** [comment]
using -P eventlet and setting the concurrency fixed this for me

**Comment by ohoroyoi** [comment]
you guys my life saver! thank you very much! @bwest-at-xometry @georgepsarakis

**Comment by ohoroyoi** [comment]
@sami
hello, I have a question. Before you know this command '--pool solo', my command was `celery -A app.jobs.task worker --loglevel=DEBUG --concurrency=1 `. it means I use just one worker. Am I wrong? then why command put `solo` again?

**Comment by Abhaya1998** [comment]
@ohoroyoi 
The difference is when you start worker without solo, the worker itself will be the main process and it will spawn child with -c=1.
While with solo the worker itself will run the task inline.
Ref: https://www.distributedpython.com/2018/10/26/celery-execution-pool/

**Comment by pharapeti** [comment]
> objc[39430]: +[NSString initialize] may have been in progress in another thread when fork() was called.
objc[39430]: +[NSString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[2020-09-21 21:42:39,547: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2020-09-21 21:42:40,899: ERROR/MainProcess] Process 'ForkPoolWorker-7' pid:39430 exited with 'signal 6 (SIGABRT)'
[2020-09-21 21:42:40,924: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 6 (SIGABRT).')
Traceback (most recent call last):
  File "/Users/pharapeti/Documents/web_dashboard/env/lib/python3.8/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT).

Above is the log output of the bug caught when running with multiple concurrent workers. I'm currently on OSX 10.15.6 and after reading through a related [issue](https://github.com/darkskyapp/forecast-ruby/issues/13), I solved the issue by running command in console:

`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`

Output afterwards:

> [2020-09-21 21:43:11,768: INFO/MainProcess] Received task: dashboard.tasks.startSerialConnection[eca6ce3b-d91d-4688-9adb-1dd656af17f5]
[2020-09-21 21:43:11,769: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x11133d5e0> (args:('dashboard.tasks.startSerialConnection', 'eca6ce3b-d91d-4688-9adb-1dd656af17f5', {'lang': 'py', 'task': 'dashboard.tasks.startSerialConnection', 'id': 'eca6ce3b-d91d-4688-9adb-1dd656af17f5', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'eca6ce3b-d91d-4688-9adb-1dd656af17f5', 'parent_id': None, 'argsrepr': "('/dev/cu.usbserial-14140',)", 'kwargsrepr': '{}', 'origin': 'gen39332@Patrices-MBP', 'reply_to': '0e7c5793-17d7-3056-b53a-1ebdf0b0570e', 'correlation_id': 'eca6ce3b-d91d-4688-9adb-1dd656af17f5', 'hostname': 'celery@Patrices-MBP', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': False}, 'args': ['/dev/cu.usbserial-14140'], 'kwargs': {}}, '[["/dev/cu.usbserial-14140"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2020-09-21 21:43:11,769: DEBUG/MainProcess] Task accepted: dashboard.tasks.startSerialConnection[eca6ce3b-d91d-4688-9adb-1dd656af17f5] pid:39564
[2020-09-21 21:43:14,547: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2020-09-21 21:43:17,476: WARNING/ForkPoolWorker-4] SPOT 0
[2020-09-21 21:43:17,477: WARNING/ForkPoolWorker-4] SPOT 0.5
[2020-09-21 21:43:17,489: INFO/ForkPoolWorker-4] Task dashboard.tasks.startSerialConnection[eca6ce3b-d91d-4688-9adb-1dd656af17f5] succeeded in 5.719109770000001s: 'Could not connect to device. Either Arduino is open, device is not
					connected or you are using the incorrect port.'

Therefore, it looks like changes to the MacOSX Mojave and Catalina kernel are killing the concurrent Celery forks in an effort to ensure fork safety.

**Comment by prmammoth** [comment]
@georgepsarakis  This issue is hitting us badly. Though putting pool=solo solves it but then we are not able to take benefit of the execution pool provided by celery. I don't consider this a fix but a workaround. There should be some more guidance on what is happening and how can one avoid, the situation. May be a proper exception than doing an abort so the application can make required correction based upon understanding the nature of exception.

**Comment by haviduck** [comment]
wow, i never thought id be stuck on what i thought was the trivial part of my flow. spin up workers, catch their signals or events to ensure proper management. i hate that solo is blocking so im near to just hammer in zmq and make a hub.

i love celery, but damn this is rough

**Comment by thedrow** [comment]
We'd welcome any documentation changes and improvements as PRs.

**Comment by haviduck** [comment]
try prefork and ensure you are not on windows

**Comment by floschne** [comment]
Another way that "fixed" the problem for me was setting the number of torch threads to 1: `torch.set_num_threads(1)` BEFORE loading the model in the worker.

**Comment by argonaut76** [comment]
Bumping this again as I've just run into the same problem running an API that uses Python's sentence-transformers library. The --pool=solo workaround is not viable as the API requires concurrency. Any word on a real fix?

**Comment by Uzzije** [comment]
Having a similar issue as @argonaut76 regarding the use of celery and sentence-transformers.

**Comment by mowsen** [comment]
Same problem as @argonaut76 trying to do some NLP with flair. Worker just hangs and stops working. --pool=solo fixes this but no concurrency possible

**Comment by argonaut76** [comment]
> Same problem as @argonaut76 trying to do some NLP with flair. Worker just hangs and stops working. --pool=solo fixes this but no concurrency possible

I ended up implementing a second API (without celery) just for the transformer model and ran it in a separate container. The celery app calls it as needed. Orchestrated everything with docker compose. This solved the problem, but is obviously more complex.

**Comment by suhjohn** [comment]
<img width="897" alt="Screenshot 2023-05-17 at 12 36 23 PM" src="https://github.com/celery/celery/assets/31156679/b3e9547e-03c2-4265-942e-f7a9b816308e">

For those who are also struggling with Celery and Sentence-Transformers or Pytorch related

**Comment by qx** [comment]
This bug is still alive!
