### ISSUE TITLE
Inspect active task: get acquire error

### ISSUE THREAD

**Issue by TreHack** [celery/celery#4155]
When I call insepect.active() to see the active task, I get the below error:
My code is:
```
import celery
def revoke_celery_task(group, parent_job):
    inspect = Inspect(app=celery.current_app)
    active_node_dict = inspect.active()
    .....
    the rest code is to revoke the active task.
    .....
```
the error is:
```
Traceback (most recent call last):
  File "/home/test/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/test/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/test/git-lab/apps/jenkinsjobs/tasks.py", line 128, in save_jenkinsjob_runinfo
    channel.start_consuming()
  File "/home/test/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/home/test/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/home/test/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/home/test/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/home/test/git-lab/apps/jenkinsjobs/tasks.py", line 105, in callback
    revoke_celery_task(group, parent_job)
  File "/home/test/git-lab/apps/jenkinsjobs/tasks.py", line 702, in revoke_celery_task
    active_node_dict = inspect.active()
  File "/home/test/env/local/lib/python2.7/site-packages/celery/app/control.py", line 94, in active
    return self._request('active')
  File "/home/test/env/local/lib/python2.7/site-packages/celery/app/control.py", line 81, in _request
    timeout=self.timeout, reply=True,
  File "/home/test/env/local/lib/python2.7/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/home/test/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 315, in _broadcast
    serializer=serializer)
  File "/home/test/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 285, in _publish
    with self.producer_or_acquire(producer, chan) as producer:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/yzxn1709/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 247, in producer_or_acquire
    with self.producer_pool.acquire() as producer:
  File "/home/yzxn1709/env/local/lib/python2.7/site-packages/kombu/resource.py", line 74, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: Acquire on closed pool
```

**Comment by auvipy** [comment]
please check the master branch and report again
