### ISSUE TITLE
Redis connection refused error but redis-cli connects and shows values which I am expecting in db

### ISSUE THREAD

**Issue by meets7** [celery/celery#4162]
## Checklist

- [x] Celery : 4.0.2
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
-
## Expected behavior
-
## Actual behavior
I am not able to figure this out. I have flask app with celery and using Redis as a broker on Ubuntu 16.04. It was working fine for the last many days and today all of a sudden it is giving the following exception.

```
[2017-07-26 20:12:25,512: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 129, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 2165, in _execute
    return command(*args)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/kombu/transport/redis.py", line 1039, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/kombu/transport/redis.py", line 667, in _receive
    ret.append(self._receive_one(c))
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/kombu/transport/redis.py", line 678, in _receive_one
    response = c.parse_response()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 2183, in parse_response
    return self._execute(connection, connection.read_response)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 2172, in _execute
    connection.connect()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
[2017-07-26 20:12:25,804: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds...

[2017-07-26 20:12:26,725: ERROR/PoolWorker-3] Something went wrong in async processes.
Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/tasks.py", line 66, in send_event_notification_async
    sleep(nextEventDelayInSeconds)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/billiard/common.py", line 125, in _shutdown_cleanup
    sys.exit(-(256 - signum))
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/billiard/pool.py", line 281, in exit
    return _exit()
SystemExit
[2017-07-26 20:12:26,726: ERROR/PoolWorker-4] Something went wrong in async processes.
Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/tasks.py", line 66, in send_event_notification_async
    sleep(nextEventDelayInSeconds)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/billiard/common.py", line 125, in _shutdown_cleanup
    sys.exit(-(256 - signum))
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/billiard/pool.py", line 281, in exit
    return _exit()
SystemExit
[2017-07-26 20:12:26,734: ERROR/PoolWorker-8] Something went wrong in async processes.
Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/tasks.py", line 66, in send_event_notification_async
    sleep(nextEventDelayInSeconds)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/billiard/common.py", line 125, in _shutdown_cleanup
    sys.exit(-(256 - signum))
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/billiard/pool.py", line 281, in exit
    return _exit()
SystemExit
[2017-07-26 20:12:27,729: ERROR/MainProcess] Process 'PoolWorker-6' pid:2057 exited with 'signal 15 (SIGTERM)'
[2017-07-26 20:12:27,740: ERROR/MainProcess] Process 'PoolWorker-5' pid:2055 exited with 'exitcode 15'
[2017-07-26 20:12:27,750: ERROR/MainProcess] Process 'PoolWorker-2' pid:2052 exited with 'exitcode 15'
[2017-07-26 20:12:27,761: ERROR/MainProcess] Process 'PoolWorker-1' pid:2051 exited with 'exitcode 15'
[2017-07-26 20:12:27,812: ERROR/MainProcess] Process 'PoolWorker-7' pid:2059 exited with 'exitcode 15'
[2017-07-26 20:13:27,799: ERROR/PoolWorker-3] Something went wrong in async processes.
Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 129, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/tasks.py", line 45, in send_event_notification_async
    r.set(priority, True)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 1072, in set
    return self.execute_command('SET', *pieces)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
[2017-07-26 20:13:27,800: ERROR/PoolWorker-4] Something went wrong in async processes.
Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 129, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/tasks.py", line 45, in send_event_notification_async
    r.set(priority, True)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 1072, in set
    return self.execute_command('SET', *pieces)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
[2017-07-26 20:13:27,802: ERROR/PoolWorker-8] Something went wrong in async processes.
Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 129, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsangvikar/apps/msbot/tasks.py", line 45, in send_event_notification_async
    r.set(priority, True)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 1072, in set
    return self.execute_command('SET', *pieces)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/dsangvikar/apps/msbot/msbotenv/lib/python3.5/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

```
I guess it retries after 2 seconds and again fails and the same exceptions. What is more confusing is redis-server is up and running properly. redis-cli ping works. Further more, I opened up redis-cli and tried to get the values which the celery worker is supposed to add. Those are also gettable. Btw, I flush all the values on server restart. So when I restarted the server, it updated the values accordingly. How do I figure out what's wrong?

I didn't make any changes on the redis-server configuration files. All ways working well till yesterday. Kindly let me know what more details are required. Thanks.

**Comment by davidt99** [comment]
Try to connect to redis using the redis driver and see if you still have the issue:
```python
redis.StrictRedis(host=redis_address, port=redis_port).keys()
```

**Comment by meets7** [comment]
Yes, using the same.

**Comment by georgepsarakis** [comment]
So this happens once connection is lost and the worker attempts to reconnect? Is Redis server listening on localhost and port 6379?

**Comment by meets7** [comment]
Yes, Redis is up and running. I am not sure why this happens. Basically, if I reboot the server, on startup the exceptions are thrown. But, if I kill the celery workers first using `pkill -9 -f 'celery worker'` , it boots up properly without exceptions and runs. How do I make sure that celery workers close when I issue a `sudo reboot` on the ubuntu server?

**Comment by bingqiangzhang** [comment]
You can try to set redis config like this 
127.0.0.1:6379> CONFIG SET timeout 0
OK

If it works, write it in your redis.conf.

**Comment by hmarcelodn** [comment]
How did you solve this issue ?

**Comment by hmarcelodn** [comment]
@meets7

**Comment by rocksyne** [comment]
Had a similar problem.I can't explain why this worked, but doing

> sudo apt install redis-server

and then retrying just resolved everything for me.

**Comment by jos3fc0** [comment]
la solucion es: sudo service redis-server start

**Comment by kmrabhay** [comment]
Correct solution  `sudo apt install redis-server `

**Comment by nate-benton90** [comment]
I am running the Redis server in a Docker container and getting the same type of errors. Using redis-cli works just fine. I've read and tried what's been presented above but errors manifest when trying to perform any kind of communication via Python, the following errors are thrown:

`Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mars_photo.py", line 10, in <module>
    q.enqueue(get_mars_photo, 990 + i)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rq/queue.py", line 396, in enqueue
    return self.enqueue_call(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rq/queue.py", line 344, in enqueue_call
    job = self.enqueue_job(job, at_front=at_front)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rq/queue.py", line 452, in enqueue_job
    pipe.execute()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 3.22.222.83:6379. Connection refused.`

**Comment by namanUIUC** [comment]
@nate-benton90 did you solve this issue ?

**Comment by sergioherrera7** [comment]
This works in my setup:

> from .celery import app as celery_app
>__all__ = ('celery_app',)
>
>(...)adding it to __init__.py file of project root folder

https://stackoverflow.com/a/71394216/2901641

**Comment by sugandhsec** [comment]
I was facing same issue , and tried almost every solution from opensource , at the end i got solution which works 100% efficiently. 

all you need to do is 

inside  file 

> projects--->>__ init __.py


you have to add this two lines of code 

> code:

    from __future__ import absolute_import
    
    # This will make sure the app is always imported when
    # Django starts so that shared_task will use this app.
    from .celery import app as celery_app

#Django #celery #redis #celeryconnectionerror #connectionrefused
