### ISSUE TITLE
Celery on Linux with SQS Broker fails with 'TypeError: list items must be string objects'

### ISSUE THREAD

**Issue by panchuparayil** [celery/celery#4181]
Installing celery 4.1 with SQS Broker and fails with the following stack trace. I see it creating a queue so I know AWS credentials are valid.

Any pointers? I am using Python 2.7 on linux.

```
[2017-08-04 18:22:16,250: CRITICAL/MainProcess] Unrecoverable error: TypeError('list items must be string objects',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/lib/python2.7/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/usr/lib/python2.7/site-packages/kombu/async/hub.py", line 291, in create_loop
    item()
  File "/usr/lib/python2.7/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/usr/lib/python2.7/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/lib/python2.7/site-packages/kombu/transport/SQS.py", line 316, in _schedule_queue
    queue, callback=promise(self._loop1, (queue,)),
  File "/usr/lib/python2.7/site-packages/kombu/transport/SQS.py", line 332, in _get_bulk_async
    return self._get_async(queue, maxcount, callback=callback)
  File "/usr/lib/python2.7/site-packages/kombu/transport/SQS.py", line 343, in _get_async
    callback=transform(self._on_messages_ready, callback, q, queue),
  File "/usr/lib/python2.7/site-packages/kombu/transport/SQS.py", line 363, in _get_from_sqs
    callback=callback,
  File "/usr/lib/python2.7/site-packages/kombu/async/aws/sqs/connection.py", line 78, in receive_message
    queue_url, callback=callback, parent=queue,
  File "/usr/lib/python2.7/site-packages/kombu/async/aws/connection.py", line 205, in get_list
    operation
  File "/usr/lib/python2.7/site-packages/kombu/async/aws/connection.py", line 198, in make_request
    return self._mexe(prepared_request, callback=callback)
  File "/usr/lib/python2.7/site-packages/kombu/async/aws/connection.py", line 166, in _mexe
    conn.getresponse(callback=callback)
  File "/usr/lib/python2.7/site-packages/kombu/async/aws/connection.py", line 115, in getresponse
    return self.http_client.add_request(request)
  File "/usr/lib/python2.7/site-packages/kombu/async/http/curl.py", line 74, in add_request
    self._process_queue()
  File "/usr/lib/python2.7/site-packages/kombu/async/http/curl.py", line 152, in _process_queue
    self._setup_request(curl, request, buf, headers)
  File "/usr/lib/python2.7/site-packages/kombu/async/http/curl.py", line 191, in _setup_request
    ['{0}: {1}'.format(*h) for h in items(request.headers)],
TypeError: list items must be string objects
```

**Comment by alukach** [comment]
For the record, I'm using Celery 4.1.0 with SQS and Python3 and can report that all is working as expected. @panchuparayil Can you report the contents of `request.headers`? (_hint_: Set a breakpoint with `celery.contrib.rdb`)

**Comment by boveylisi2013** [comment]
Got the same error as panchuparayil with the same environment. Seems that the latest version of celery and kombu are broken for SQS broker and python 2.7. Any updates for this?

**Comment by georgepsarakis** [comment]
I this this is [related](https://github.com/pycurl/pycurl/issues/124). @boveylisi2013 what version of `pycurl` are you using?

**Comment by jkoehl** [comment]
@boveylisi2013 

I ended up upgrading my pycurl to 7.43.0 and that fixed the issue. I did have to [battle through the SSL config](https://stackoverflow.com/questions/21096436/ssl-backend-error-when-using-openssl) of pycurl but after that it seems to work.
