### ISSUE TITLE
Group of chains: arguments not passed to chains

### ISSUE THREAD

**Issue by samfrances** [celery/celery#4244]
## Checklist

This issue effects the celery 3.1.19 and celery 4.1.0, but somewhat differently.

The problem arises with a group of chains, of the following form:

```
workflow = group(
    chain(task1.s(), task2.s()),
    chain(task3.s(), task4.s())
)
```
Where all tasks take one positional argument.

In 4.1.0, calling `workflow.apply_async((n,))` for any value `n` will result in:

```
TypeError: task1() takes exactly 1 argument (0 given)
```

In 3.1.19, calling `workflow.apply_async((n,))` for any value `n` will work initially. However, if you trigger the task repeatedly in the same process, `task1` and `task2` start getting more than one arguments. The additional arguments are always arguments that have been passed in previous invocations.

More details, including scripts that can be used to reproduce this behaviour, are included in the **steps to reproduce** section below.

Output of ``celery -A proj report`` for 4.1.0:

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.12
            billiard:3.5.0.3 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/

CELERY_TASK_SERIALIZER: 'json'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_ACCEPT_CONTENT: ['json']
CELERY_SEND_EVENTS: True
CELERY_EVENT_SERIALIZER: 'json'
BROKER_URL: u'redis://localhost:6379//'
CELERY_RESULT_BACKEND: u'redis://localhost:6379/'
```

Output of ``celery -A proj report`` for 3.1.19:

```
software -> celery:3.1.19 (Cipater) kombu:3.0.37 py:2.7.12
            billiard:3.3.0.23 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/

CELERY_EVENT_SERIALIZER: 'json'
CELERY_TASK_SERIALIZER: 'json'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_ACCEPT_CONTENT: ['json']
CELERY_SEND_EVENTS: True
```

## Steps to reproduce

For 4.1.0, the following script will reproduce the problem:

```
from celery import Celery, group, chain, signature

broker = 'redis://localhost:6379/'
app = Celery('experiments2', backend=broker, broker=broker)
app.conf.update(
    CELERY_SEND_EVENTS=True,
    CELERY_TASK_SERIALIZER='json',
    CELERY_RESULT_SERIALIZER='json',
    CELERY_EVENT_SERIALIZER='json',
    CELERY_ACCEPT_CONTENT=['json'],
)


@app.task
def times2(a):
    print "run times2({})".format(a)
    return a * 2


@app.task
def times3(a):
    print "run times3({})".format(a)
    return a * 3


@app.task
def times5(a):
    print "run times5({})".format(a)
    return a * 5


@app.task
def negative(a):
    print "run negative({})".format(a)
    return -a


workflow = group(
    chain(times2.s(), negative.s()),
    chain(times3.s(), times5.s())
)

if __name__ == "__main__":

    workflow.apply_async((1,))

```

For 3.1.19, change the `if __name_ == "__main__"` part as follows:

```
if __name__ == "__main__":

    for n in range(20):

        res1 = workflow.apply_async(args=(n,))
        print res1.get()
```

## Expected behavior

I repeat the workflow for reference:
```
workflow = group(
    chain(times2.s(), negative.s()),
    chain(times3.s(), times5.s())
)
```
The expected behaviour (as far as I understand) is that when calling `workflow.apply_async((n,))`, each of the chains in the group will be passed `n`. So, the final result will be equivalent to:
```
[
    negative(times2(n)),
    times5(times3(n))
]
```

## Actual behavior

Celery 4.1.0 gives the following error (this is from the Python script, not in the celery worker output):

```
TypeError                                 Traceback (most recent call last)
/home/sam/Documents/learning_projects/celery_canvas/experiments2.py in <module>()
     58     for n in range(10):
     59 
---> 60         res1 = workflow.apply_async(args=(n,))
     61         print res1.get()

/home/sam/Documents/learning_projects/celery_canvas/venv/lib/python2.7/site-packages/celery/canvas.pyc in apply_async(self, args, kwargs, add_to_parent, producer, link, link_error, **options)
    984         p = barrier()
    985         results = list(self._apply_tasks(tasks, producer, app, p,
--> 986                                          args=args, kwargs=kwargs, **options))
    987         result = self.app.GroupResult(group_id, results, ready_barrier=p)
    988         p.finalize()

/home/sam/Documents/learning_projects/celery_canvas/venv/lib/python2.7/site-packages/celery/canvas.pyc in _apply_tasks(self, tasks, producer, app, p, add_to_parent, chord, args, kwargs, **options)
   1060                                 chord=sig.options.get('chord') or chord,
   1061                                 args=args, kwargs=kwargs,
-> 1062                                 **options)
   1063 
   1064                 # adding callback to result, such that it will gradually

/home/sam/Documents/learning_projects/celery_canvas/venv/lib/python2.7/site-packages/celery/canvas.pyc in apply_async(self, args, kwargs, **options)
    564             return self.apply(args, kwargs, **options)
    565         return self.run(args, kwargs, app=app, **(
--> 566             dict(self.options, **options) if options else self.options))
    567 
    568     def run(self, args=(), kwargs={}, group_id=None, chord=None,

/home/sam/Documents/learning_projects/celery_canvas/venv/lib/python2.7/site-packages/celery/canvas.pyc in run(self, args, kwargs, group_id, chord, task_id, link, link_error, publisher, producer, root_id, parent_id, app, **options)
    594             # Issue #3379.
    595             options['chain'] = tasks if not use_link else None
--> 596             first_task.apply_async(**options)
    597             return results[0]
    598 

/home/sam/Documents/learning_projects/celery_canvas/venv/lib/python2.7/site-packages/celery/canvas.pyc in apply_async(self, args, kwargs, route_name, **options)
    219         # pylint: disable=too-many-function-args
    220         #   Borks on this, as it's a property
--> 221         return _apply(args, kwargs, **options)
    222 
    223     def _merge(self, args=(), kwargs={}, options={}, force=False):

/home/sam/Documents/learning_projects/celery_canvas/venv/lib/python2.7/site-packages/celery/app/task.pyc in apply_async(self, args, kwargs, task_id, producer, link, link_error, shadow, **options)
    516                 pass
    517             else:
--> 518                 check_arguments(*(args or ()), **(kwargs or {}))
    519 
    520         app = self._get_app()

TypeError: times2() takes exactly 1 argument (0 given)
```

On the other hand, running 3.1.19 with the appropriately altered script (see above), gives the error, this time in the output of the celery worker:

```
$ celery -A experiments2 worker --loglevel=INFO --concurrency=4                              
 
 -------------- celery@sam-VirtualBox v3.1.19 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-4.10.0-33-generic-x86_64-with-Ubuntu-16.04-xenial
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         experiments2:0x7f2a9dfa2a90
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . experiments2.negative
  . experiments2.times2
  . experiments2.times3
  . experiments2.times5

[2017-08-31 17:27:04,097: INFO/MainProcess] Connected to redis://localhost:6379//
[2017-08-31 17:27:04,106: INFO/MainProcess] mingle: searching for neighbors
[2017-08-31 17:27:05,111: INFO/MainProcess] mingle: all alone
[2017-08-31 17:27:05,124: WARNING/MainProcess] celery@sam-VirtualBox ready.
[2017-08-31 17:27:11,152: INFO/MainProcess] Received task: experiments2.times2[3c33edfb-2390-4b2a-bce7-947139ef5bec]
[2017-08-31 17:27:11,155: WARNING/Worker-1] run times2(0)
[2017-08-31 17:27:11,163: INFO/MainProcess] Received task: experiments2.times3[60d62e08-3e36-46f2-a96b-d0b81f1de194]
[2017-08-31 17:27:11,169: WARNING/Worker-3] run times3(0)
[2017-08-31 17:27:11,198: INFO/MainProcess] Received task: experiments2.negative[3249987f-ce58-42f0-8bc0-374c74e083b1]
[2017-08-31 17:27:11,201: WARNING/Worker-2] run negative(0)
[2017-08-31 17:27:11,205: INFO/MainProcess] Task experiments2.negative[3249987f-ce58-42f0-8bc0-374c74e083b1] succeeded in 0.00359962000221s: 0
[2017-08-31 17:27:11,210: INFO/MainProcess] Task experiments2.times2[3c33edfb-2390-4b2a-bce7-947139ef5bec] succeeded in 0.0542540519964s: 0
[2017-08-31 17:27:11,212: INFO/MainProcess] Received task: experiments2.times5[08a46c29-689e-4960-97b6-28cd2ea4fddc]
[2017-08-31 17:27:11,215: INFO/MainProcess] Task experiments2.times3[60d62e08-3e36-46f2-a96b-d0b81f1de194] succeeded in 0.0460929540131s: 0
[2017-08-31 17:27:11,216: WARNING/Worker-4] run times5(0)
[2017-08-31 17:27:11,220: INFO/MainProcess] Task experiments2.times5[08a46c29-689e-4960-97b6-28cd2ea4fddc] succeeded in 0.00382349599386s: 0
[2017-08-31 17:27:12,184: INFO/MainProcess] Received task: experiments2.times2[602070e6-ec3d-41f3-a46c-b97341039d32]
[2017-08-31 17:27:12,197: INFO/MainProcess] Received task: experiments2.times3[f723051a-44e4-429f-9d53-9880c7566aeb]
[2017-08-31 17:27:12,202: ERROR/MainProcess] Task experiments2.times2[602070e6-ec3d-41f3-a46c-b97341039d32] raised unexpected: TypeError('times2() takes exactly 1 argument (2 given)',)
Traceback (most recent call last):
  File "/home/sam/Documents/learning_projects/celery_canvas/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/sam/Documents/learning_projects/celery_canvas/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: times2() takes exactly 1 argument (2 given)
[2017-08-31 17:27:12,207: ERROR/MainProcess] Task experiments2.times3[f723051a-44e4-429f-9d53-9880c7566aeb] raised unexpected: TypeError('times3() takes exactly 1 argument (2 given)',)
Traceback (most recent call last):
  File "/home/sam/Documents/learning_projects/celery_canvas/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/sam/Documents/learning_projects/celery_canvas/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: times3() takes exactly 1 argument (2 given)
```

**Comment by samfrances** [comment]
This issue can be solved using the following workaround:

```
workflow = group(
    chain(task1.s(), task2.s()),
    chain(task3.s(), task4.s())
)

# Later
workflow.apply_async((n,))
```
...with:
```
workflow = function(n):
    return group(
        chain(task1.s(n), task2.s()),
        chain(task3.s(n), task4.s())
    )

# Later
workflow(n).apply_async()
```

However, I still think that the behaviour reported above may represent a departure from expected behaviour.

**Comment by ashoaib1** [comment]
I have also faced this problem. And this is certainly unexpected. Also v3.1.18 is not affected by this problem.

**Comment by quantoid** [comment]
This is a problem if you are chaining a task into a group, and the group contains chains. In that case I don't think the workaround from @samfrances can be used.

**Comment by rajadain** [comment]
I also just ran into this and would like to see it fixed. When chaining a task and a group of chains, the first task in each chain in the group does not receive the result of the previous task.

**Comment by AmagicalFishy** [comment]
Is this the same issue? 

```
from celery import chord, chain
from celery.decorators import task

@task()
def task1():
    return 5

@task()
def task2(first_arg, second_arg):
    return first_arg + second_arg

@task()
def task3(arg_list):
    return [1 + num for num in arg_list]

chain(
        task1.s(),
        chord(
            task2.s(x) for x in range(0, 3)
        )
        (task3.s())
)

```

... results in: 

```
  File "testing.py", line 21, in <module>
    (task3.s())
  File "/usr/local/lib/python3.5/dist-packages/celery/canvas.py", line 1189, in __call__
    return self.apply_async((), {'body': body} if body else {}, **options)
  File "/usr/local/lib/python3.5/dist-packages/celery/canvas.py", line 1232, in apply_async
    return self.run(tasks, body, args, task_id=task_id, **options)
  File "/usr/local/lib/python3.5/dist-packages/celery/canvas.py", line 1277, in run
    header_result = header(*partial_args, task_id=group_id, **options)
  File "/usr/local/lib/python3.5/dist-packages/celery/canvas.py", line 953, in __call__
    return self.apply_async(partial_args, **options)
  File "/usr/local/lib/python3.5/dist-packages/celery/canvas.py", line 978, in apply_async
    args=args, kwargs=kwargs, **options))
  File "/usr/local/lib/python3.5/dist-packages/celery/canvas.py", line 1054, in _apply_tasks
    **options)
  File "/usr/local/lib/python3.5/dist-packages/celery/canvas.py", line 218, in apply_async
    return _apply(args, kwargs, **options)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/task.py", line 513, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: task2() missing 1 required positional argument: 'second_arg'
```

**Comment by thedrow** [comment]
If anyone is running into this bug, you're welcome to investigate.
Furthermore, a submitting a failing test case to our integration test suite is a good idea.

**Comment by auvipy** [comment]
I request to try celery==4.4.0 and share the trackback again

**Comment by eugene-s** [comment]
+

**Comment by eugene-s** [comment]
The same problem in 4.4.2
