### ISSUE TITLE
mongodb result backend:  DuplicateKeyError 

### ISSUE THREAD

**Issue by qingyunha** [celery/celery#4267]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.10
            billiard:3.5.0.3 librabbitmq:1.6.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:librabbitmq results:mongodb://cyberivy:**@127.0.0.1/
```
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
It rarely happened. I can't reproduce

## Actual behavior
```
Traceback (most recent call last):
  File "/opt/python2.7.10-customized/lib/python2.7/site-packages/celery/app/trace.py", line 362, in trace_task
    request=task_request,
  File "/opt/python2.7.10-customized/lib/python2.7/site-packages/celery/backends/base.py", line 309, in store_result
    request=request, **kwargs)
  File "/opt/python2.7.10-customized/lib/python2.7/site-packages/celery/backends/mongodb.py", line 175, in _store_result
    self.collection.save(meta)
  File "/opt/python2.7.10-customized/lib/python2.7/site-packages/pymongo/collection.py", line 2185, in save
    check_keys, False, manipulate, write_concern)
  File "/opt/python2.7.10-customized/lib/python2.7/site-packages/pymongo/collection.py", line 710, in _update
    _check_write_command_response([(0, result)])
  File "/opt/python2.7.10-customized/lib/python2.7/site-packages/pymongo/helpers.py", line 300, in _check_write_command_response
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
DuplicateKeyError: E11000 duplicate key error collection: celery.celery_taskmeta index: _id_ dup key: { : "671ea5ba-9eff-447e-b6c5-329477da3cb1" }
```

Thanks

**Comment by auvipy** [comment]
try latest releases and check the baster branch.
