### ISSUE TITLE
UnicodeEncodeErrors with celery built-in console logging

### ISSUE THREAD

**Issue by kmike** [celery/celery#427]
Colored celery console logger fails to display unicode strings containing non-ascii letters (e.g. django's sql query log with non-ascii data): 

```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 91-95: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/logging/__init__.py", line 776, in emit
    msg = self.format(record)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/logging/__init__.py", line 654, in format
    return fmt.format(record)
  File "/Users/kmike/envs/zina/lib/python2.6/site-packages/celery/log.py", line 56, in format
    t = logging.Formatter.format(self, record)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/logging/__init__.py", line 439, in format
    s = self._fmt % record.__dict__
  File "/Users/kmike/envs/zina/lib/python2.6/site-packages/celery/utils/term.py", line 62, in __str__
    return prefix + str(reduce(self._add, self.s)) + suffix
```

As a workaround I set `CELERYD_HIJACK_ROOT_LOGGER = False` and then add 'logging.StreamHandler' to 'celery' logger (it handles non-ascii data).

**Comment by lukeaus** [comment]
I have this set in my /etc/default/celeryd
export LANG=en_US.UTF-8

I have celery==3.1.18 and django-celery==3.1.17 installed.

As a side note, nginx handles unicode fine
However celery throwing a UnicodeDecodeError on this print statement
print '%s - Assessing %s-%s' % (user_name, foo.id, foo.name)

'<Worker: blah blah blah don\xe7a>'

Do I need to set:
export LANG=en_US.UTF-8
anywhere else?

**Comment by ask** [comment]
@lukeaus do you have a traceback?

nginx is not written in Python 2 ;)

**Comment by lukeaus** [comment]
@ask 
Yeah - I had another issue a while back with unicode and nginx - thats all working now.

This issue just relates to celery.

Here is a stacktrace as requested.

Traceback (most recent call last):

  File "/home/webapps/.virtualenvs/crowdstaff/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/webapps/.virtualenvs/crowdstaff/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/webapps/apps/crowdstaff/lib/smsverify/views.py", line 57, in verify_form
    return profile_complete_redir(request)

  File "/home/webapps/apps/crowdstaff/project/users/decorators.py", line 26, in func
    return view_func(request, *args, **kwargs)

  File "/home/webapps/apps/crowdstaff/project/workers/views/profile.py", line 445, in profile_complete_redir
    if request.user.signup_complete and profile_complete_and_user_verified(request):

  File "/home/webapps/apps/crowdstaff/project/users/decorators.py", line 26, in func
    return view_func(request, *args, **kwargs)

  File "/home/webapps/apps/crowdstaff/project/workers/views/profile.py", line 499, in profile_complete_and_user_verified
    return create_matches_for_signup_applications(request)

  File "/home/webapps/apps/crowdstaff/project/users/decorators.py", line 26, in func
    return view_func(request, *args, **kwargs)

  File "/home/webapps/apps/crowdstaff/project/workers/views/profile.py", line 523, in create_matches_for_signup_applications
    score = score_worker_for_job(worker, job, external_applicant=True)

  File "/home/webapps/apps/crowdstaff/project/jobs/process.py", line 490, in score_worker_for_job
    print '%s - Assessing %s-%s' % (worker, job.id, job.name)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

Any assistance would be greatly appreciated.
Thanks

**Comment by ask** [comment]
But this traceback seems to be from a Django view?   What are you running exactly when this error occurs?

**Comment by lukeaus** [comment]
@ask  so it is... wrong stacktrace. Sorry about that

I have uploaded the stacktrace as an image as Opbeat won't let me copy and paste the stacktrace as one might expect.

Opbeat also gives me these extra details:
args []
task <@task: jobs.process.process_jobs of default:0x7f2dd278d0d0 (v2 compatible)>
task_id 4b84ff8f-3ecc-4708-92b8-fa67e4a62390
kwargs {}

![stacktrace](https://cloud.githubusercontent.com/assets/5635204/10803043/6400a4b4-7e14-11e5-8da6-b3558ea559fb.jpg)

**Comment by ask** [comment]
The worker redirects output to stdout to the logger, but having unicode in there works for me.
In that case the traceback would also be different (occurring somewhere in celery.log)

Your problem is in your code, and could beseveral things, job.id or job.name could be objects that are stringified with __str__ instead of __unicode__ on Python2, or you have disabled the redirection.

May be fixed by using `safe_str`:

    from kombu.utils.encoding import safe_str
    print '%s - Assessing %s-%s' % (safe_str(worker), safe_str(job.id), safe_str(job.name))

Or you will get a better traceback

**Comment by lukeaus** [comment]
@ask 
Uou were right - good thinking.
I had a __unicode__ method  on the Worker model returning a string, rather than a unicode object.
Fixed. Thanks for your help
