### ISSUE TITLE
ETA string is not parsed into datetime when chaining tasks

### ISSUE THREAD

**Issue by jenstroeger** [celery/celery#4295]
I’m setting up two tasks in a [Chain](http://docs.celeryproject.org/en/latest/userguide/canvas.html#chains) like so:
```python
    @app.task(bind=True)
    def _do_something(self, arg):
        pass # First task to run.

    @app.task(bind=True)
    def _do_otherthing(self, arg):
        pass # Second task to run.

    def schedule_tasks():
        …
        task_args = ("Grumble",)
        something_eta = datetime.utcnow() + datetime.get_timedelta(seconds=20)
        something_sig = _do_something.signature(task_args, eta=something_eta, immutable=True)
        otherthing_eta = datetime.utcnow() + datetime.get_timedelta(seconds=40)
        otherthing_sig = _do_otherthing.signature(task_args, eta=otherthing_eta, immutable=True)

        task_chain = celery.chain(something_sig, otherthing_sig)                                    
        result = task_chain.delay()                                                                     
```
The first task `do_something()` schedules and executes fine, and then while scheduling the second task an exception raises:
```bash
[2017-09-28 10:56:50,048: WARNING/ForkPoolWorker-4] /…/lib/python3.5/site-packages/celery/app/trace.py:549: RuntimeWarning: Exception raised outside body: AttributeError("'str' object has no attribute 'isoformat'",):
Traceback (most recent call last):
  File "/…/lib/python3.5/site-packages/celery/app/trace.py", line 431, in trace_task
    parent_id=uuid, root_id=root_id,
  File "/…/lib/python3.5/site-packages/celery/canvas.py", line 222, in apply_async
    return _apply(args, kwargs, **options)
  File "/…/lib/python3.5/site-packages/celery/app/task.py", line 536, in apply_async
    **options
  File "/…/lib/python3.5/site-packages/celery/app/base.py", line 729, in send_task
    root_id, parent_id, shadow, chain,
  File "/…/lib/python3.5/site-packages/celery/app/amqp.py", line 333, in as_task_v2
    eta = eta and eta.isoformat()
AttributeError: 'str' object has no attribute 'isoformat'
```
My suspicion is that the second task’s `eta` is stored as a string, but when actually scheduled (see [`Signature.apply_async()`](https://github.com/celery/celery/blob/master/celery/canvas.py#L221) code) that string is _not_ parsed back into a [datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime) object again, thus causing the exception further downstream.

The following hack works for [amqp.py:333](https://github.com/celery/celery/blob/master/celery/app/amqp.py#L333), but is likely not the proper fix:
```python
eta = eta and (eta if isinstance(eta, str) else eta.isoformat())
```

Current Celery environment:
```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.4
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0

accept_content: ['json']
task_serializer: 'json'
result_serializer: 'json'
enable_utc: True
result_backend: 'redis://localhost:6379/0'
broker_url: 'redis://localhost:6379/0'
timezone: 'Europe/Berlin'
imports: 'srv.celery.tasks'
```

**Comment by auvipy** [comment]
I have added this to next release milestone with the hope to be tracked before the release
