### ISSUE TITLE
`task.retry()` is completely broken when using a timezone in 4.1

### ISSUE THREAD

**Issue by ThiefMaster** [celery/celery#4314]
This seems to be fixed in `master`, but broken in 4.1.0. It would be great if a 4.1.1 containing a fix for this was released soon.

```python
from celery import Celery


app = Celery(__name__)
app.conf.broker_url = 'redis://127.0.0.1:6379/4'
app.conf.timezone = 'Europe/Zurich'


@app.task(bind=True, max_retries=None)
def test(task):
    print 'retry #%d' % task.request.retries
    task.retry(countdown=5, max_retries=5)
```

When calling this task the retries happen immediately:

```
[2017-10-06 14:40:20,024: INFO/MainProcess] Received task: celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5]
[2017-10-06 14:40:20,025: WARNING/ForkPoolWorker-5] retry #0
[2017-10-06 14:40:20,042: INFO/ForkPoolWorker-5] Task celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5] retry: Retry in 5s
[2017-10-06 14:40:20,043: INFO/MainProcess] Received task: celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5]  ETA:[2017-10-06 12:40:25.026091+00:30]
[2017-10-06 14:40:20,049: WARNING/ForkPoolWorker-2] retry #1
[2017-10-06 14:40:20,069: INFO/MainProcess] Received task: celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5]  ETA:[2017-10-06 12:40:25.049778+00:30]
[2017-10-06 14:40:20,069: INFO/ForkPoolWorker-2] Task celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5] retry: Retry in 5s
[2017-10-06 14:40:20,072: WARNING/ForkPoolWorker-7] retry #2
[2017-10-06 14:40:20,089: INFO/ForkPoolWorker-7] Task celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5] retry: Retry in 5s
[2017-10-06 14:40:20,089: INFO/MainProcess] Received task: celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5]  ETA:[2017-10-06 12:40:25.072752+00:30]
[2017-10-06 14:40:20,090: WARNING/ForkPoolWorker-3] retry #3
[2017-10-06 14:40:20,107: INFO/ForkPoolWorker-3] Task celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5] retry: Retry in 5s
[2017-10-06 14:40:20,107: INFO/MainProcess] Received task: celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5]  ETA:[2017-10-06 12:40:25.091585+00:30]
[2017-10-06 14:40:20,109: WARNING/ForkPoolWorker-5] retry #4
[2017-10-06 14:40:20,110: INFO/ForkPoolWorker-5] Task celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5] retry: Retry in 5s
[2017-10-06 14:40:20,110: INFO/MainProcess] Received task: celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5]  ETA:[2017-10-06 12:40:25.109445+00:30]
[2017-10-06 14:40:20,111: WARNING/ForkPoolWorker-2] retry #5
[2017-10-06 14:40:20,111: ERROR/ForkPoolWorker-2] Task celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5] raised unexpected: MaxRetriesExceededError(u"Can't retry celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5] args:() kwargs:{}",)
Traceback (most recent call last):
  File "/tmp/celerytest/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/tmp/celerytest/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/tmp/celerytest/celerytest.py", line 12, in test
    task.retry(countdown=5, max_retries=5)
  File "/tmp/celerytest/lib/python2.7/site-packages/celery/app/task.py", line 672, in retry
    self.name, request.id, S.args, S.kwargs))
MaxRetriesExceededError: Can't retry celerytest.test[677f80ea-6c2c-49de-a9c8-ceac7e29eda5] args:() kwargs:{}
```

**Comment by auvipy** [comment]
probably a fix is work in progress, plz have a look on the recent pr/commits

**Comment by thedrow** [comment]
This is fixed in master so there's no actionable item other than #4387
