### ISSUE TITLE
celery tasks cannot run after cythonizing

### ISSUE THREAD

**Issue by zhangzhen** [celery/celery#4342]
Python: 3.5
Celery: 4.1.0

The code for celery tasks has been cythonized.
I started a worker as follows:
`celery worker -l info -A chrombackend.app.celery --concurrency=1`
I got the following error:
```
...
  File "/home/zhangz/Envs/chromgo2/lib/python3.5/site-packages/celery/app/base.py", line 453, in _task_from_fun
    '__header__': staticmethod(head_from_fun(fun, bound=bind)),
  File "/home/zhangz/Envs/chromgo2/lib/python3.5/site-packages/celery/utils/functional.py", line 284, in head_from_fun
    namespace = {'__name__': fun.__module__}
AttributeError: 'method-wrapper' object has no attribute '__module__'
```
Can someone help me to solve this problem?

Cheers,
Zhen Zhang

**Comment by thedrow** [comment]
It seems like your cython code may be wrong.
See https://stackoverflow.com/questions/30228821/importing-cython-function-attributeerror-module-object-has-no-attribute-fun
If I'm wrong, please comment and we'll reopen the issue.

**Comment by danigosa** [comment]
Same error here, it looks like if you build the tasks as cython modules it does not work, nothign to do with Cython syntax, my tasks have no cython at all (they are only compiled to c) and it breaks:

```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)

  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 95, in __init__
    self.on_before_init(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/apps/worker.py", line 97, in on_before_init
    trace.setup_worker_optimizations(self.app, self.hostname)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 575, in setup_worker_optimizations
    app.finalize()
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 512, in finalize
    _announce_app_finalized(self)
  File "/usr/local/lib/python3.6/site-packages/celery/_state.py", line 52, in _announce_app_finalized
    callback(app)
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 412, in cons
    return app._task_from_fun(fun, **opts)
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 453, in _task_from_fun
    '__header__': staticmethod(head_from_fun(fun, bound=bind)),
  File "/usr/local/lib/python3.6/site-packages/celery/utils/functional.py", line 284, in head_from_fun
    namespace = {'__name__': fun.__module__}
AttributeError: 'method-wrapper' object has no attribute '__module__'
```

**Comment by danigosa** [comment]
@thedrow hi man, I do really think this is a bug, accessing this attribute unconditionally is dangerous as its implementation in Cython breaks, it depends on the fact that the celery maintainers care about Cython support, which you would probably should but I'm not the one to say this :P

**Comment by auvipy** [comment]
should cythonizing break python attribute look up? what is the reason for the failure?

**Comment by georgepsarakis** [comment]
Cython functions do not have the same attributes as Python functions, as also mentioned [here](https://github.com/cython/cython/blob/master/docs/src/userguide/limitations.rst#inspect-support). Celery generates the task from a function which requires inspecting certain function attributes.

@danigosa if you want to give it a try, I would suggest updating the error-generating [line](https://github.com/celery/celery/blob/master/celery/utils/functional.py#L281) with a constant value and report what occurs in this case:

```
namespace = {'__name__': 'cython_test'}
```

We would appreciate the feedback :smile: !

**Comment by danigosa** [comment]
@georgepsarakis you got it:

**Override patch in the worker app file directly at `vim /usr/local/lib/python3.6/site-packages/celery/utils/functional.py`**
![image](https://user-images.githubusercontent.com/1827475/34075257-bab6b672-e2c1-11e7-9378-37856ab61962.png)

Then: 
`rm -rf /usr/local/lib/python3.6/site-packages/celery/utils/__pycache__ `

Then include them in cython compilation:

![image](https://user-images.githubusercontent.com/1827475/34075281-18075d40-e2c2-11e7-89b2-7752717e9017.png)

Finally:
```
[2017-12-16 23:35:23,041: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f56329539d8> (args:('robbie_ml_services.worker.v1.tasks.__predictors_tasks.get_gender_task', '60fe34a8-6460-4095-9599-625defa1ae96', {'lang': 'py', 'task': 'robbie_ml_services.worker.v1.tasks.__predictors_tasks.get_gender_task', 'id': '60fe34a8-6460-4095-9599-625defa1ae96', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '60fe34a8-6460-4095-9599-625defa1ae96', 'parent_id': None, 'argsrepr':... kwargs:{})
[2017-12-16 23:35:23,042: DEBUG/MainProcess] Task accepted: robbie_ml_services.worker.v1.tasks.__predictors_tasks.get_gender_task[60fe34a8-6460-4095-9599-625defa1ae96] pid:4001
.[2017-12-16 23:35:23,575: INFO/ForkPoolWorker-1] Task robbie_ml_services.worker.v1.tasks.__predictors_tasks.get_gender_task[60fe34a8-6460-4095-9599-625defa1ae96] succeeded in 0.5318677059995025s
```

**Comment by georgepsarakis** [comment]
@danigosa if that is not too much to ask, could you please try:

```
namespace = {'__name__': inspect.getmodule(fun).__name__}
```

If you can't get it to work, I will try and recreate the Cython conditions for a possible fix.

**Comment by danigosa** [comment]
There we go, bad luck:

![image](https://user-images.githubusercontent.com/1827475/34248802-9cf667ee-e637-11e7-80f9-3be01b2aabb0.png)

```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 95, in __init__
    self.on_before_init(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/apps/worker.py", line 97, in on_before_init
    trace.setup_worker_optimizations(self.app, self.hostname)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 575, in setup_worker_optimizations
    app.finalize()
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 512, in finalize
    _announce_app_finalized(self)
  File "/usr/local/lib/python3.6/site-packages/celery/_state.py", line 52, in _announce_app_finalized
    callback(app)
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 412, in cons
    return app._task_from_fun(fun, **opts)
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 453, in _task_from_fun
    '__header__': staticmethod(head_from_fun(fun, bound=bind)),
  File "/usr/local/lib/python3.6/site-packages/celery/utils/functional.py", line 284, in head_from_fun
    namespace = {'__name__': inspect.getmodule(fun).__name__}
AttributeError: 'NoneType' object has no attribute '__name__'
``` 

But nothing we cannot expect using `inspect` : https://github.com/cython/cython/wiki/Unsupported#inspect-support

**Comment by danigosa** [comment]
@georgepsarakis according to this: https://github.com/cython/cython/blob/master/tests/run/cyfunction.pyx

the cyfunction object has a direct `__name__` attribute on the `func_globals` attribute, that is something like this should work:

```python
➜  lib.linux-x86_64-3.6 git:(dev) ✗ ipython
Python 3.6.4 (default, Dec 21 2017, 01:45:11)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from robbie_visio_http_services.worker.v1.helpers import predict_frame_task_helper

In [2]: predict_frame_task_helper
Out[2]: <cyfunction predict_frame_task_helper at 0x7feb1bd20270>
In [5]: predict_frame_task_helper.func_globals
Out[5]:
{'ROBBIE_VISIO_STORAGE_URL_PREFIX': 'http://dummy/',
 '__builtins__': <module 'builtins' (built-in)>,
 '__doc__': None,
 '__file__': '/app/build/lib.linux-x86_64-3.6/robbie_visio_http_services/worker/v1/helpers.cpython-36m-x86_64-linux-gnu.so',
 '__loader__': <_frozen_importlib_external.ExtensionFileLoader at 0x7feb1bfae278>,
 '__name__': 'robbie_visio_http_services.worker.v1.helpers',
 '__package__': 'robbie_visio_http_services.worker.v1',
 '__spec__': ModuleSpec(name='robbie_visio_http_services.worker.v1.helpers', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x7feb1bfae278>, origin='/app/build/lib.linux-x86_64-3.6/robbie_visio_http_services/worker/v1/helpers.cpython-36m-x86_64-linux-gnu.so'),
 '__test__': {},
 '_compute_predictions': <cyfunction _compute_predictions at 0x7feb1bd20048>,
 'chain': celery.canvas.chain,
 'compute_device_dimensions': <cyfunction compute_device_dimensions at 0x7feb1c8c6f60>,
 'compute_time_dimensions': <cyfunction compute_time_dimensions at 0x7feb1c8c6ea8>,
 'datetime': <module 'datetime' from '/usr/local/lib/python3.6/datetime.py'>,
 'decode_b64_string': <cyfunction decode_b64_string at 0x7feb1c8c6df0>,
 'hashlib': <module 'hashlib' from '/usr/local/lib/python3.6/hashlib.py'>,
 'ingest_frame': <cyfunction ingest_frame at 0x7feb1c8c6bc8>,
 'ingest_frame_canvas': <cyfunction ingest_frame_canvas at 0x7feb1bd20328>,
 'ingest_frame_task_helper': <cyfunction ingest_frame_task_helper at 0x7feb1bd20100>,
 'parse': <function dateutil.parser.parse>,
 'predict_frame_task_helper': <cyfunction predict_frame_task_helper at 0x7feb1bd20270>,
 'predict_multi': <cyfunction predict_multi at 0x7feb1c8c6c80>,
 'sys': <module 'sys' (built-in)>,
 'upload_frame_task_helper': <cyfunction upload_frame_task_helper at 0x7feb1bd201b8>}
In [9]: predict_frame_task_helper.func_globals['__package__']
Out[9]: 'robbie_visio_http_services.worker.v1'
In [7]: predict_frame_task_helper.func_globals['__name__']
Out[7]: 'robbie_visio_http_services.worker.v1.helpers'
```
So an ugly but working solution would be:

```python
if hasattr(fun, '__module__'):
     # Is Python
     namespace = {'__name__': fun.__module__}  
elif hasattr(fun, 'func_globals'):
     # Is Cython
     namespace = {'__name__': fun.__module__}
else:
     # Is Stranger Things VIII
```

**Comment by georgepsarakis** [comment]
@danigosa can you please try with:

```
namespace = {'__name__': fun.__globals__['__name__']
```
I think this covers all cases.

**Comment by danigosa** [comment]
@georgepsarakis it works for cythonized functions but it doesn't seem to work for plain python ones:

```python
Python 3.6.4 (default, Dec 21 2017, 01:45:11)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from robbie_visio_http_services.worker.v1.helpers import ingest_frame_task_helper

In [2]: ingest_frame_task_helper
Out[2]: <cyfunction ingest_frame_task_helper at 0x7fc9d3976100>

In [3]: ingest_frame_task_helper.__globals__['__name__']
Out[3]: 'robbie_visio_http_services.worker.v1.helpers'

In [4]: from robbie_visio_http_services.worker.v1.__tasks import debug_task

In [5]: debug_task
Out[5]: <@task: robbie_visio_http_services.worker.v1.__tasks.debug_task of visio_http_worker at 0x7fc9d85fb8d0>

In [6]: debug_task.__globals__['__name__']
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-6423e2f8883b> in <module>()
----> 1 debug_task.__globals__['__name__']

/usr/local/lib/python3.6/site-packages/celery/local.py in __getattr__(self, name)
    144         if name == '__members__':
    145             return dir(self._get_current_object())
--> 146         return getattr(self._get_current_object(), name)
    147
    148     def __setitem__(self, key, value):

AttributeError: 'debug_task' object has no attribute '__globals__'
In [7]: debug_task.__module__
Out[7]: 'celery.local'
```

**Comment by georgepsarakis** [comment]
In this case `debug_task` is a `Task` object (notice that is decorated), not a function.

**Comment by danigosa** [comment]
@georgepsarakis yup it's true my bad, then if you are sure it works for a python function I can assure it works for a cython cyfunction too, I think we made it :)

**Comment by thedrow** [comment]
Did we resolve this in master?

**Comment by auvipy** [comment]
it has nothing to change in celery itself. so no code changes in celery needed actually.

**Comment by thedrow** [comment]
I disagree. This issue has demonstrated that it might be possible to allow Celery to run Cythonized tasks.

**Comment by auvipy** [comment]
theoretically you should be able to cythonize any python code. but the issue has some very good example of how to cythonize celery tasks. so we could at least extract those examples to a cython section of celery docs.

**Comment by pizzapanther** [comment]
I was able to get around the problem by excluding my tasks and celery app from cython. The rest of my code could be cythonized though. Just make sure to delete your `celerybeat-schedule` file when you switch. It caches some of the cython code so if it loads it will continue to kill your app until you remove the file and exclude your celery code from cython.

**Comment by banjin** [comment]
> @georgepsarakis you got it, **it works with the "patch"**:
> 
> **Override patch in the worker app file directly at `vim /usr/local/lib/python3.6/site-packages/celery/utils/functional.py`**
> ![image](https://user-images.githubusercontent.com/1827475/34075257-bab6b672-e2c1-11e7-9378-37856ab61962.png)
> 
> Then:
> `rm -rf /usr/local/lib/python3.6/site-packages/celery/utils/__pycache__ `
> 
> Then include them in cython compilation:
> 
> ![image](https://user-images.githubusercontent.com/1827475/34075281-18075d40-e2c2-11e7-89b2-7752717e9017.png)
> 
> Finally:
> 
> ```
> [2017-12-16 23:35:23,041: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f56329539d8> (args:('robbie_ml_services.worker.v1.tasks.__predictors_tasks.get_gender_task', '60fe34a8-6460-4095-9599-625defa1ae96', {'lang': 'py', 'task': 'robbie_ml_services.worker.v1.tasks.__predictors_tasks.get_gender_task', 'id': '60fe34a8-6460-4095-9599-625defa1ae96', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '60fe34a8-6460-4095-9599-625defa1ae96', 'parent_id': None, 'argsrepr':... kwargs:{})
> [2017-12-16 23:35:23,042: DEBUG/MainProcess] Task accepted: robbie_ml_services.worker.v1.tasks.__predictors_tasks.get_gender_task[60fe34a8-6460-4095-9599-625defa1ae96] pid:4001
> .[2017-12-16 23:35:23,575: INFO/ForkPoolWorker-1] Task robbie_ml_services.worker.v1.tasks.__predictors_tasks.get_gender_task[60fe34a8-6460-4095-9599-625defa1ae96] succeeded in 0.5318677059995025s
> ```
> You wanted proof, you got proof 😎

And `export PYTHONDONTWRITEBYTECODE=1`

**Comment by kunz07** [comment]
I've been experiencing the same issue while trying to run cythonized tasks.
Celery - 4.3
Python - 3.6
Run command - `celery -A appName worker -l debug -B`

```
Traceback (most recent call last):
  File "/home/ch/.local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/ch/.local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/ch/.local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/ch/.local/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/ch/.local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/ch/.local/lib/python3.6/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/worker/worker.py", line 97, in __init__
    self.on_before_init(**kwargs)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/apps/worker.py", line 93, in on_before_init
    trace.setup_worker_optimizations(self.app, self.hostname)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/app/trace.py", line 594, in setup_worker_optimizations
    app.finalize()
  File "/home/ch/.local/lib/python3.6/site-packages/celery/app/base.py", line 519, in finalize
    _announce_app_finalized(self)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/_state.py", line 54, in _announce_app_finalized
    callback(app)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/app/__init__.py", line 59, in <lambda>
    lambda app: app._task_from_fun(fun, **options)
  File "/home/ch/.local/lib/python3.6/site-packages/celery/app/base.py", line 450, in _task_from_fun
    '__header__': staticmethod(head_from_fun(fun, bound=bind)),
  File "/home/ch/.local/lib/python3.6/site-packages/celery/utils/functional.py", line 279, in head_from_fun
    namespace = {'__name__': fun.__module__}
AttributeError: 'method-wrapper' object has no attribute '__module__'
```

According to the 4.3 changelog, support for cython tasks has been added 
[https://docs.celeryproject.org/en/latest/changelog.html#rc1](url)

Any help would be appreciated :)

Regards,
Kunal
