### ISSUE TITLE
Celery hangs on startup

### ISSUE THREAD

**Issue by iofedurin** [celery/celery#4367]
I'm trying to use [real-time processing](http://docs.celeryproject.org/en/latest/userguide/monitoring.html#real-time-processing) with a Django app that is configured as specified in the [documentation](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#using-celery-with-django).

Without my_monitor() functions from the example, celery works fine, but as soon as I add this function it doesn't run.

Project struct: 

```
    - proj/
      - firstapp/  
      - manage.py  
      - proj/  
        - __init__.py
        - celery_config/
          - __init__.py
          - main.py
          - ...
        - celery.py 
        - settings.py  
        - urls.py  
        - ...
      - ...
```

In celery.py file I have the following code that works:

```
    from __future__ import absolute_import
    
    import os
    
    from celery import Celery
    from . import celery_config as config
    
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'proj.settings')
    
    celery_app = Celery('proj')
    
    celery_app.config_from_object(config)
```

celery_config stored broker_url, queues, routers, shedule and etc.

Run celery: 

   

>  $ celery -A proj ...

and in this form it works fine

then I add the function in celery.py:

```
    def celery_logger(app):
        state = app.events.State()
    
        def logging_task_received(event):
            state.event(event)
            task = state.tasks.get(event['uuid'])
             
            # here I want to add your own log entry in db
    
        with app.connection() as connection:
            recv = app.events.Receiver(channel=connection, handlers={
                'task-received': logging_task_received,
            })
            recv.capture(limit=None, timeout=None, wakeup=True)
    
    
    celery_logger(celery_app)
```

and now, it hangs when you call `celery -A proj ...`

**UPD:** If I add a timeout="Х" to recv.capture() then after "X" seconds i get error: 

    $ celery -A proj.celery_app worker
    Traceback (most recent call last):
      File "/usr/local/bin/celery", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 30, in main
        main()
      File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 81, in main
        cmd.execute_from_commandline(argv)
      File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
        super(CeleryCommand, self).execute_from_commandline(argv)))
      File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
        argv = self.setup_app_from_commandline(argv)
      File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
        self.app = self.find_app(app)
      File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 489, in find_app
        return find_app(app, symbol_by_name=self.symbol_by_name)
      File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 238, in find_app
        sym = imp(app)
      File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
        return imp(module, package=package)
      File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
      File "/home/john/workdir/proj/proj/celery_app.py", line 5, in <module>
        from .celery import celery_app
      File "/home/john/workdir/proj/proj/celery.py", line 32, in <module>
        celery_logger(celery_app)
      File "/home/john/workdir/proj/proj/celery.py", line 29, in celery_logger
        recv.capture(limit=None, timeout=15, wakeup=False)
      File "/usr/local/lib/python3.6/site-packages/celery/events/__init__.py", line 340, in capture
        return list(self.consume(limit=limit, timeout=timeout, wakeup=wakeup))
      File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 199, in consume
        conn.drain_events(timeout=safety_interval)
      File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 288, in drain_events
        return self.transport.drain_events(self.connection, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events
        return connection.drain_events(**kwargs)
      File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 303, in drain_events
        chanmap, None, timeout=timeout,
      File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 366, in _wait_multiple
        channel, method_sig, args, content = read_timeout(timeout)
      File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 337, in read_timeout
        return self.method_reader.read_method()
      File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 189, in read_method
        raise m
      File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 107, in _next_method
        frame_type, channel, payload = read_frame()
      File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 154, in read_frame
        frame_header = read(7, True)
      File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 277, in _read
        s = recv(n - len(rbuf))
    socket.timeout: timed out

**Comment by abhrj** [comment]
@iofedurin How did you solve this? I am hitting the exact same problem.

**Comment by behm** [comment]
@iofedurin @abhrj were you able to solve this issue?  I have just encountered the same thing running Celery 5.2.7
