### ISSUE TITLE
Error utf8' codec can't decode byte 0xb5 in position 10: invalid start byte when i wan generate pdf with weasyprint  

### ISSUE THREAD

**Issue by kellermatta** [celery/celery#4395]
nternal Server Error: /apicatalogos/pdfgeneration/
Traceback (most recent call last):
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/kellermaca/PuntoVenta/catalogos/views.py", line 116, in get
    result = result.get()
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/celery/result.py", line 194, in get
    on_message=on_message,
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/celery/backends/async.py", line 191, in wait_for_pending
    return result.maybe_throw(callback=callback, propagate=propagate)
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/celery/result.py", line 299, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/celery/result.py", line 292, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/Users/kellermaca/PuntoVenta/env/lib/python2.7/site-packages/vine/promises.py", line 217, in throw
    reraise(type(exc), exc, tb)
  File "<string>", line 1, in reraise
EncodeError: 'utf8' codec can't decode byte 0xb5 in position 10: invalid start byte

**Comment by georgepsarakis** [comment]
This does not seem like a Celery issue. In case you can provide more accurate details on how this is caused by Celery and not the task code itself, please re-open.
