### ISSUE TITLE
Main process crashes with maximum recursion depth exceeded and workers stop processing tasks 

### ISSUE THREAD

**Issue by alexkiro** [celery/celery#4411]
## Checklist

```
software -> celery:3.1.25 (Cipater) kombu:3.0.34 py:2.7.12
            billiard:3.3.0.23 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

CELERY_IGNORE_RESULT: True
CELERY_REDIRECT_STDOUTS_LEVEL: 'INFO'
BROKER_URL: 'redis+socket:///var/run/redis/redis.sock?virtual_host=4'
CELERY_ACCEPT_CONTENT: ['pickle', 'json', 'msgpack', 'yaml']
CELERYBEAT_SCHEDULE: {
    }
```

## Steps to reproduce

I can't reproduce this on any version, but it seems to randomly happen and cannot pinpoint reproduction steps.

## Crash Logs

```
[2017-10-24 16:04:36,012: CRITICAL/MainProcess] Internal error: RuntimeError('maximum recursion depth exceeded in cmp',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 227, in _process_task
    req.execute_using_pool(self.pool)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/job.py", line 264, in execute_using_pool
    correlation_id=uuid,
  File "/usr/local/lib/python2.7/site-packages/celery/concurrency/base.py", line 156, in apply_async
    **options)
  File "/usr/local/lib/python2.7/site-packages/billiard/pool.py", line 1440, in apply_async
    self._quick_put((TASK, (result._job, None, func, args, kwds)))
  File "/usr/local/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 793, in send_job
    body = dumps(tup, protocol=protocol)
RuntimeError: maximum recursion depth exceeded in cmp
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 227, in _process_task
    req.execute_using_pool(self.pool)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/job.py", line 264, in execute_using_pool
    correlation_id=uuid,
  File "/usr/local/lib/python2.7/site-packages/celery/concurrency/base.py", line 156, in apply_async
    **options)
  File "/usr/local/lib/python2.7/site-packages/billiard/pool.py", line 1440, in apply_async
    self._quick_put((TASK, (result._job, None, func, args, kwds)))
  File "/usr/local/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 793, in send_job
    body = dumps(tup, protocol=protocol)
RuntimeError: maximum recursion depth exceeded in cmp
```

## Expected behavior

Main process should continue, and not crash? 

## Actual behavior

Main process crashes and the workers stop processing new tasks. 

## Notes

Not sure if this is a bug or something I can fix on my end, hoping somebody can provide some more insight here.

**Comment by auvipy** [comment]
use the new releases and follow the docs and check again

**Comment by alexkiro** [comment]
> use the new releases and follow the docs and check again

FWIW, I cannot easily do an upgrade due to various complexities involved. I'll keep trying to find a workaround until I can do a safe upgrade.

**Comment by auvipy** [comment]
unfortunately we don't have enough resource to support older releases... you could post on mailing list for discussion and help
