### ISSUE TITLE
Backend result not writing to mysql / postgres. 

### ISSUE THREAD

**Issue by ilansr** [celery/celery#4440]
## celery report

>software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.10
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:db+postgresql://postgres:**@127.0.0.1:32775/postgres
>
>result_expires: 3600
broker_url: u'redis://localhost:6379/0'
include: [u'app.extensions.celery_tasks.tasks']
result_backend: u'db+postgresql://postgres:********@127.0.0.1:32775/postgres'

## Steps to reproduce
- Start celery with postgres or mysql backend
- Run a task asynchronously 
## Expected behavior
- write status of task to backend (Add new rows with status and result)
## Actual behavior
- Task runs successfully, however tasks status does not add to DB. (Tables remain empty)
Please note that celery_taskmeta and celery_tasksetmeta tables auto-create successfully.
The same issue happens both for postgres AND mysql.
It's when celery attempts to write task to db, the error occurs. log:

>2017-12-11 21:27:21,023: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,023 INFO sqlalchemy.engine.base.Engine select version()
[2017-12-11 21:27:21,023: INFO/ForkPoolWorker-4] select version()
[2017-12-11 21:27:21,024: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,024 INFO sqlalchemy.engine.base.Engine {}
[2017-12-11 21:27:21,024: INFO/ForkPoolWorker-4] {}
[2017-12-11 21:27:21,029: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,029 INFO sqlalchemy.engine.base.Engine select current_schema()
[2017-12-11 21:27:21,029: INFO/ForkPoolWorker-4] select current_schema()
[2017-12-11 21:27:21,029: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,029 INFO sqlalchemy.engine.base.Engine {}
[2017-12-11 21:27:21,029: INFO/ForkPoolWorker-4] {}
[2017-12-11 21:27:21,031: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,031 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
[2017-12-11 21:27:21,031: INFO/ForkPoolWorker-4] SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
[2017-12-11 21:27:21,032: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,032 INFO sqlalchemy.engine.base.Engine {}
[2017-12-11 21:27:21,032: INFO/ForkPoolWorker-4] {}
[2017-12-11 21:27:21,033: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,033 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
[2017-12-11 21:27:21,033: INFO/ForkPoolWorker-4] SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
[2017-12-11 21:27:21,034: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,033 INFO sqlalchemy.engine.base.Engine {}
[2017-12-11 21:27:21,033: INFO/ForkPoolWorker-4] {}
[2017-12-11 21:27:21,035: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,035 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
[2017-12-11 21:27:21,035: INFO/ForkPoolWorker-4] show standard_conforming_strings
[2017-12-11 21:27:21,036: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,036 INFO sqlalchemy.engine.base.Engine {}
[2017-12-11 21:27:21,036: INFO/ForkPoolWorker-4] {}
[2017-12-11 21:27:21,038: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,038 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
[2017-12-11 21:27:21,038: INFO/ForkPoolWorker-4] select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
[2017-12-11 21:27:21,039: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,038 INFO sqlalchemy.engine.base.Engine {'name': u'celery_tasksetmeta'}
[2017-12-11 21:27:21,038: INFO/ForkPoolWorker-4] {'name': u'celery_tasksetmeta'}
[2017-12-11 21:27:21,042: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,042 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
[2017-12-11 21:27:21,042: INFO/ForkPoolWorker-4] select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
[2017-12-11 21:27:21,043: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,043 INFO sqlalchemy.engine.base.Engine {'name': u'celery_taskmeta'}
[2017-12-11 21:27:21,043: INFO/ForkPoolWorker-4] {'name': u'celery_taskmeta'}
[2017-12-11 21:27:21,046: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,046 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
[2017-12-11 21:27:21,046: INFO/ForkPoolWorker-4] BEGIN (implicit)
[2017-12-11 21:27:21,047: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,047 INFO sqlalchemy.engine.base.Engine SELECT celery_taskmeta.id AS celery_taskmeta_id, celery_taskmeta.task_id AS celery_taskmeta_task_id, celery_taskmeta.status AS celery_taskmeta_status, celery_taskmeta.result AS celery_taskmeta_result, celery_taskmeta.date_done AS celery_taskmeta_date_done, celery_taskmeta.traceback AS celery_taskmeta_traceback
FROM celery_taskmeta
WHERE celery_taskmeta.task_id = %(task_id_1)s
[2017-12-11 21:27:21,047: INFO/ForkPoolWorker-4] SELECT celery_taskmeta.id AS celery_taskmeta_id, celery_taskmeta.task_id AS celery_taskmeta_task_id, celery_taskmeta.status AS celery_taskmeta_status, celery_taskmeta.result AS celery_taskmeta_result, celery_taskmeta.date_done AS celery_taskmeta_date_done, celery_taskmeta.traceback AS celery_taskmeta_traceback
FROM celery_taskmeta
WHERE celery_taskmeta.task_id = %(task_id_1)s
[2017-12-11 21:27:21,048: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,048 INFO sqlalchemy.engine.base.Engine {'task_id_1': '01688d43-4bab-44a4-9a74-0028f1e027f8'}
[2017-12-11 21:27:21,048: INFO/ForkPoolWorker-4] {'task_id_1': '01688d43-4bab-44a4-9a74-0028f1e027f8'}
[2017-12-11 21:27:21,053: WARNING/ForkPoolWorker-4] 2017-12-11 21:27:21,052 INFO sqlalchemy.engine.base.Engine ROLLBACK
[2017-12-11 21:27:21,052: INFO/ForkPoolWorker-4] ROLLBACK
[2017-12-11 21:27:21,057: WARNING/ForkPoolWorker-4] /Library/Python/2.7/site-packages/celery/app/trace.py:549: RuntimeWarning: Exception raised outside body: AttributeError("'Sequence' object has no attribute 'arg'",):
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/celery/app/trace.py", line 434, in trace_task
    uuid, retval, task_request, publish_result,
  File "/Library/Python/2.7/site-packages/celery/backends/base.py", line 152, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/Library/Python/2.7/site-packages/celery/backends/base.py", line 309, in store_result
    request=request, **kwargs)
  File "/Library/Python/2.7/site-packages/celery/backends/database/__init__.py", line 53, in _inner
    return fun(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/celery/backends/database/__init__.py", line 110, in _store_result
    task = Task(task_id)
  File "<string>", line 4, in __init__
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/state.py", line 408, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/event/attr.py", line 254, in __call__
    fn(*args, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/events.py", line 202, in wrap
    return fn(state.obj(), *arg, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy_utils/listeners.py", line 27, in instant_defaults_listener
    if callable(column.default.arg):
AttributeError: 'Sequence' object has no attribute 'arg'

**Comment by auvipy** [comment]
what result backend you are using? django/sqlalchemy?

**Comment by ilansr** [comment]
Thanks for replying!

I am not using django at all.
sqlalchemy package is installed however, nowhere do i specify in celery config to use sqlalchemy.
I just double-checked the documentaion -  I did not find a way to set this explicitly [http://docs.celeryproject.org/en/latest/userguide/configuration.html#database-backend-settings](url)

**Comment by ilansr** [comment]
FYI:

$ pip list | grep SQL
Flask-SQLAlchemy (2.2)
MySQL-python (1.2.5)
SQLAlchemy (1.1.5)
SQLAlchemy-Utils (0.32.12)

**Comment by auvipy** [comment]
http://docs.celeryproject.org/en/latest/userguide/configuration.html#conf-database-result-backend

**Comment by ilansr** [comment]
Hi,
If not clear, Please note that I have configured the db as told to in documentation.
This is the reason for this ticket.

**Comment by auvipy** [comment]
post your question to mailing list/irc after that report here again.
