### ISSUE TITLE
Maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Kimice** [celery/celery#4464]
Hi, when I call celery apply_async function, sometimes it raise Exception like this. It seems like getting config failed. This bug can't always reappear. I guess celery may be not init correctly. I'm so confused with this bug.

celery==4.1.0

I init celery with flask like this.

```
def make_celery(app):
    celery = Celery(app.import_name, backend=app.config['CELERY_RESULT_BACKEND'],
                    broker=app.config['CELERY_BROKER_URL'])
    celery.conf.update(app.config)
    celery.config_from_object('App.celery_custom.celery_config')
    TaskBase = celery.Task
    class ContextTask(TaskBase):
        abstract = True
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)
    celery.Task = ContextTask
    return celery

celery_app = make_celery(flask_app)

@celery_app.task(bind=True)
def checkInstance(self, a, b):
    pass

check_task = checkInstance.apply_async(args=['123', '123'], queue='123')
```

```
LOG:
[2017-12-26 08:42:58,659]: logs_util.py[line:64] [pid:25680] ERROR Traceback (most recent call last):
  File "./App/views/experiment_views.py", line 377, in create_experiment_and_run
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 521, in apply_async
    if app.conf.task_always_eager:
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/collections.py", line 431, in __getitem__
    return getitem(k)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/collections.py", line 280, in __getitem__
    return mapping[_key]
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 148, in data
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 911, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 921, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 128, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 146, in _smart_import
    return imp(path)
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 106, in import_from_cwd
    package=package,
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 100, in import_from_cwd
    with cwd_in_path():
  File "/usr/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(*args, **kwds))
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by georgepsarakis** [comment]
Can I ask the following:
- What is the purpose of using a custom base task class?
- Why override `__call__` instead of `run`? I think you should not override the `__call__` method and not use the `app_context` context manager, as I assume this is possibly causing the recursion.

**Comment by Kimice** [comment]
@georgepsarakis I have init celery following the guide.But bug still exist sometimes.
Is it possible to be associated with concurrency？

**Comment by Kimice** [comment]
This seems to be related to [laziness](http://docs.celeryproject.org/en/latest/userguide/application.html#laziness).
This bug haven't appear since I manually finalized app like this.

```
def make_celery(app):
    celery = Celery(app.import_name, backend=app.config['CELERY_RESULT_BACKEND'],
                    broker=app.config['CELERY_BROKER_URL'])
    celery.conf.update(app.config)
    celery.config_from_object('App.celery_custom.celery_config')

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    celery.finalize()  # manual finalize
    return celery
```

**Comment by Whpitot** [comment]
@Kimice I can't run the code you given, there is a error like this:
  File "D:\PigBrother\server\celery_app.py", line 36, in __call__
    return self.run(*args, **kwargs)
  File "d:\myself\venv\lib\site-packages\celery\app\task.py", line 392, in run
    raise NotImplementedError('Tasks must define the run method.')
NotImplementedError: Tasks must define the run method.

The function self.run(*args, **kwargs) is not implement

**Comment by knightdf** [comment]
Any update on this issue?
It shows again when im using flask 1.0.3 with celery 4.4.0
