### ISSUE TITLE
Application is not thread-safe

### ISSUE THREAD

**Issue by PromyLOPh** [celery/celery#4480]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.4
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:rpc:///

result_backend: 'rpc:///'
broker_url: 'amqp://guest:********@localhost:5672//'
```

## Steps to reproduce

Using code from the user manual, but two threads running concurrently:

```python
from celery import Celery
import time
from threading import Thread

app = Celery('test', broker='amqp://guest@localhost//', backend='rpc://')

@app.task(bind=True)
def hello(self, a, b):
    time.sleep(1)
    self.update_state(state="PROGRESS", meta={'progress': 50})
    time.sleep(1)
    self.update_state(state="PROGRESS", meta={'progress': 90})
    time.sleep(1)
    return 'hello world: %i' % (a+b)

if __name__ == '__main__':
    def run ():
        handle = hello.delay (1, 2)
        print (handle.get ())
    t1 = Thread (target=run)
    t2 = Thread (target=run)
    t1.start ()
    t2.start ()
    t1.join ()
    t2.join ()
```

## Expected behavior

```
hello world: 3
hello world: 3
```

## Actual behavior

Different exceptions, depending on timing. For instance:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/async.py", line 154, in add_pending_result
    self._maybe_resolve_from_buffer(result)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/async.py", line 160, in _maybe_resolve_from_buffer
    result._maybe_set_cache(self._pending_messages.take(result.id))
  File "/…/sandbox/lib/python3.5/site-packages/celery/utils/collections.py", line 871, in take
    raise self.Empty()
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/…/sandbox/lib/python3.5/site-packages/amqp/connection.py", line 456, in channel
    return self.channels[channel_id]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 19, in run
    print (handle.get ())
  File "/…/sandbox/lib/python3.5/site-packages/celery/result.py", line 193, in get
    self.backend.add_pending_result(self)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/async.py", line 156, in add_pending_result
    self._add_pending_result(result.id, result, weak=weak)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/async.py", line 166, in _add_pending_result
    self.result_consumer.consume_from(task_id)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/rpc.py", line 81, in consume_from
    return self.start(task_id)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/rpc.py", line 56, in start
    self._connection.default_channel, [initial_queue],
  File "/…/sandbox/lib/python3.5/site-packages/kombu/connection.py", line 821, in default_channel
    self._default_channel = self.channel()
  File "/…/sandbox/lib/python3.5/site-packages/kombu/connection.py", line 266, in channel
    chan = self.transport.create_channel(self.connection)
  File "/…/sandbox/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 100, in create_channel
    return connection.channel()
  File "/…/sandbox/lib/python3.5/site-packages/amqp/connection.py", line 459, in channel
    channel.open()
  File "/…/sandbox/lib/python3.5/site-packages/amqp/channel.py", line 432, in open
    spec.Channel.Open, 's', ('',), wait=spec.Channel.OpenOk,
  File "/…/sandbox/lib/python3.5/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/…/sandbox/lib/python3.5/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/…/sandbox/lib/python3.5/site-packages/amqp/connection.py", line 468, in drain_events
    while not self.blocking_read(timeout):
  File "/…/sandbox/lib/python3.5/site-packages/amqp/connection.py", line 473, in blocking_read
    frame = self.transport.read_frame()
  File "/…/sandbox/lib/python3.5/site-packages/amqp/transport.py", line 252, in read_frame
    payload = read(size)
  File "/…/sandbox/lib/python3.5/site-packages/amqp/transport.py", line 417, in _read
    s = recv(n - len(rbuf))
socket.timeout: timed out
```
or

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/async.py", line 154, in add_pending_result
    self._maybe_resolve_from_buffer(result)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/async.py", line 160, in _maybe_resolve_from_buffer
    result._maybe_set_cache(self._pending_messages.take(result.id))
  File "/…/sandbox/lib/python3.5/site-packages/celery/utils/collections.py", line 871, in take
    raise self.Empty()
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 19, in run
    print (handle.get ())
  File "/…/sandbox/lib/python3.5/site-packages/celery/result.py", line 193, in get
    self.backend.add_pending_result(self)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/async.py", line 156, in add_pending_result
    self._add_pending_result(result.id, result, weak=weak)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/async.py", line 166, in _add_pending_result
    self.result_consumer.consume_from(task_id)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/rpc.py", line 81, in consume_from
    return self.start(task_id)
  File "/…/sandbox/lib/python3.5/site-packages/celery/backends/rpc.py", line 59, in start
    self._consumer.consume()
  File "/…/sandbox/lib/python3.5/site-packages/kombu/messaging.py", line 477, in consume
    self._basic_consume(T, no_ack=no_ack, nowait=False)
  File "/…/sandbox/lib/python3.5/site-packages/kombu/messaging.py", line 598, in _basic_consume
    no_ack=no_ack, nowait=nowait)
  File "/…/sandbox/lib/python3.5/site-packages/kombu/entity.py", line 737, in consume
    arguments=self.consumer_arguments)
  File "/…/sandbox/lib/python3.5/site-packages/amqp/channel.py", line 1564, in basic_consume
    wait=None if nowait else spec.Basic.ConsumeOk,
  File "/…/sandbox/lib/python3.5/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/…/sandbox/lib/python3.5/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/…/sandbox/lib/python3.5/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/…/sandbox/lib/python3.5/site-packages/amqp/connection.py", line 476, in blocking_read
    frame = self.transport.read_frame()
  File "/…/sandbox/lib/python3.5/site-packages/amqp/transport.py", line 254, in read_frame
    'Received {0:#04x} while expecting 0xce'.format(ch))
amqp.exceptions.UnexpectedFrame: Received 0x3c while expecting 0xce
```

**Comment by auvipy** [comment]
did you check workers guide? celery doesn't follow this type of threading AFAIK

**Comment by PromyLOPh** [comment]
Yes, I did. Since the exceptions occur within the *calling* application
(inside .get(), to be precise) I don’t think this is an issue with the
worker.

I’m speculating here, but it looks like the ampq transport (or one of
the layers above) is lacking proper serialization, thus the two
concurrent .get() calls interfere with each other.

**Comment by auvipy** [comment]
lets wait for 4.2 release and see if it's already resolved

**Comment by PromyLOPh** [comment]
Is there a workaround I could use in the meantime?

**Comment by gehaxelt** [comment]
A solutions to this would be great. I'm also trying to run `task.delay()` and `task.get()` within a  thread and so far, it always gloriously blew up with a bunch of exceptions. (The issue here seems to be the `task.get()` part. 

Is there a work-around and/or fix for that?

**Comment by and3rson** [comment]
I can also reproduce this. Running `celery[redis]==4.2.1`. Simple test case:

```
for i in range(10): Thread(target=lambda: celery.send_task('foo', queue='bar').get()).start()
```

Sometimes it works, sometimes it yields `InvalidResponse: Protocol Error` and sometimes `AttributeError: 'list' object has no attribute 'decode'`.

**Comment by thedrow** [comment]
@auvipy Why have you closed this issue?

**Comment by zbentley** [comment]
This is affecting several of our Celery deployments as well (Celery 4.2.1, RabbitMQ 3.6, Python 2.7.6)

**Comment by ShaheedHaque** [comment]
I'm using Celery from Django. Am I right in thinking this issue means that usage is not reliable?

**Comment by thedrow** [comment]
No, there's no problem using Celery with Django.
Django does not inherently use threads.

If your WSGI server does, you may see issues.

**Comment by thedrow** [comment]
py-amqp is not thread safe unfortunately.
See celery/py-amqp#267.

We need to create a connection for each thread.

There is also a probable race condition in https://github.com/celery/celery/blob/master/celery/backends/asynchronous.py somewhere which causes this problem on Redis as well.

I don't have the time to dig into this right now. I hope I pointed you to the right direction.

**Comment by ShaheedHaque** [comment]
Thanks for confirming about Django any WSGI. As an aside, note that I'm chasing a similar issue to this with the Consul result backend in #5605.

**Comment by lfyzjck** [comment]
+1 
Environment： Celery 4.1 + Python 3.6.5 + redis-py 2.10.5
Exception：
```
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/celery/app/task.py", line 413, in delay
    return self.apply_async(args, kwargs)
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/celery/app/task.py", line 536, in apply_async
    **options
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/celery/app/base.py", line 736, in send_task
    self.backend.on_task_call(P, task_id)
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/celery/backends/redis.py", line 189, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/celery/backends/redis.py", line 76, in consume_from
    self._consume_from(task_id)
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/celery/backends/redis.py", line 82, in _consume_from
    self._pubsub.subscribe(key)
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/redis/client.py", line 2229, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/redis/client.py", line 2161, in execute_command
    self._execute(connection, connection.send_command, *args)
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/redis/client.py", line 2172, in _execute
    connection.connect()
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/redis/connection.py", line 455, in connect
    callback(self)
  File "/data/apps/datasync-api/.venv/lib/python3.6/site-packages/redis/client.py", line 2116, in on_connect
    for k, v in iteritems(self.channels):
RuntimeError: dictionary changed size during iteration
```

**Comment by machineslearnoliver** [comment]
Any updates on this issue? Facing the same `concurrent poll() invocation` when calling `result.get` from multiple websocket threads

**Comment by auvipy** [comment]
in celery 4.5 hopefully

**Comment by machineslearnoliver** [comment]
Are there any suggested workarounds I could try for now?

**Comment by auvipy** [comment]
https://github.com/celery/py-amqp/issues/267#issuecomment-525859382 can you check the comment?

**Comment by nicklyra** [comment]
Is this a potentially a duplicate of https://github.com/celery/celery/issues/4363 ?

**Comment by auvipy** [comment]
did https://github.com/celery/celery/pull/6416 solve this somehow?

**Comment by ShaheedHaque** [comment]
No. This bug is below the generic layer.

**Comment by Eieyron** [comment]
are there any updates regarding this? :)

**Comment by auvipy** [comment]
> are there any updates regarding this? :)

we are looking for investigators, you are most welcome to do so
