### ISSUE TITLE
django.db.utils.DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread

### ISSUE THREAD

**Issue by nitinmeharia** [celery/celery#4489]
### Application details:
```
    software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.4
            billiard:3.5.0.3 redis:2.10.6
    platform -> system:Darwin arch:64bit imp:CPython
    loader   -> celery.loaders.app.AppLoader
    settings -> transport:redis results:redis://localhost:6379/2
```

### Error log
```
    Signal handler <bound method DjangoWorkerFixup.on_worker_process_init of <celery.fixups.django.DjangoWorkerFixup object at 0x108e46fd0>> raised: DatabaseError("DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140736440837056 and this is thread id 4441538184.",)
    Traceback (most recent call last):
      File "/code/tmp/reignite/venv/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 227, in send
        response = receiver(signal=self, sender=sender, **named)
      File "/code/tmp/reignite/venv/lib/python3.6/site-packages/celery/fixups/django.py", line 154, in on_worker_process_init
        self._close_database()
      File "/code/tmp/reignite/venv/lib/python3.6/site-packages/celery/fixups/django.py", line 186, in _close_database
        conn.close()
      File "/code/tmp/reignite/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 283, in close
        self.validate_thread_sharing()
      File "/code/tmp/reignite/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 542, in validate_thread_sharing
        % (self.alias, self._thread_ident, thread.get_ident())
    django.db.utils.DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140736440837056 and this is thread id 4441538184.
```

## Steps to reproduce
```
celery multi restart w1 -A proj -l info
```
Its a django 1.11 application where we are getting this error.

**Comment by Simmias** [comment]
I encountered with this same problem when connectting to the mysql, 
environment: mac10.13, python3, mysqlclient1.3.13, mysql8.0, django2.1.3
Could anyone share me you experiments ?

**Comment by auvipy** [comment]
which version of celery you are using?
