### ISSUE TITLE
Celery not usefull for long term future tasks (far future)

### ISSUE THREAD

**Issue by tjerkw** [celery/celery#4522]
Celery has an option todo async tasks or scheduled/future tasks.
One use case it to create async tasks for a lot of business rules. Causing lots of async tasks to be created.

For example:
- Schedule an notification to be sent in 5 months in a userbase of millions: Millions on async tasks

I discussed this with a Co-worker, and our conclusion is that Celery's design for async tasks is not really suitable for this usecase. He suggested building a deamon, and my own Task db, and execute tasks that are ready to be executed.

But this defeats the whole purpose of having celery.

## Expected behavior

Celery should have a better design with executing thousands to 100thousands of async tasks in the far future.

Some people already build projects to solve this:
https://pypi.python.org/pypi/celery-longterm-scheduler
However it should be part of celery's core implementation. 

The rationale there explains it:

> Why not use the celery built-in apply_async(eta=)? Because you cannot ever really delete a pending job. AsyncResult('mytaskid').revoke() can only add the task ID to the statedb, where it has to stay _forever_ so the job is recognized as revoked. For jobs that are scheduled to run in 6 months time or later, this would create an unmanageable, ever-growing statedb.

**Comment by ShaheedHaque** [comment]
I have a similar problem in nature, though not in scale, and like you, I considered:

>building a daemon, and my own Task db, and execute tasks that are ready to be executed.

before concluding

>But this defeats the whole purpose of having celery.

In my case, I have jobs scheduled in the future, which I needed to (a) maintain visibility of and (b) be able to cancel. In the end, I concluded that using eta schedules made (b) hard for the reason you described, and (a) hard because there does not seem to be a race-free way to see what is/is not in the system (i.e. multiple invocations of celery inspect). I opted to use the Django support for Beat's Interval schedules, which I delete as the task runs to get the one-time effect.

**Comment by tjerkw** [comment]
Hmm this seem to be a solution: https://github.com/ZeitOnline/celery_longterm_scheduler

**Comment by KamaleshTangudu-Innovaccer** [comment]
But how to manage if the task db is being overloaded??

**Comment by shashank-iitj** [comment]
Facing the same issue. We need to schedule hundreds of thousands of small tasks for the future. Tasks scheduled in future are in unacked state in RabbitMQ. So when we schedule tasks, it ends up consuming memory which slows down our entire system.

**Comment by KamaleshTangudu-Innovaccer** [comment]
> Facing the same issue. We need to schedule hundreds of thousands of small tasks for the future. Tasks scheduled in future are in unacked state in RabbitMQ. So when we schedule tasks, it ends up consuming memory which slows down our entire system.

Follow the celery_longterm_scheduler suggestions mentioned in the above comments, it helped me.

**Comment by imdadahad** [comment]
I had a similar issue. I wanted to create several tasks that execute at different points in the future (day after, 7 days etc.)

In the end I built my own wrapper around AWS Step Functions, would be nice however if celery had this out of the box!

**Comment by adampl** [comment]
Why not just use Django Celery Beat for that?

**Comment by pythoneast** [comment]
> > Facing the same issue. We need to schedule hundreds of thousands of small tasks for the future. Tasks scheduled in future are in unacked state in RabbitMQ. So when we schedule tasks, it ends up consuming memory which slows down our entire system.
> 
> Follow the celery_longterm_scheduler suggestions mentioned in the above comments, it helped me.

I have a trouble with implementing this approach. I added config for celery as mentioned in documentation:
```app.conf.longterm_scheduler_backend = 'redis://redis:6739/1'```
But got an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 308, in run_from_argv
    return self.handle_argv(prog_name,
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 393, in handle_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery_longterm_scheduler/scheduler.py", line 113, in run
    get_scheduler(self.app).execute_pending(timestamp)
  File "/usr/local/lib/python3.8/site-packages/celery_longterm_scheduler/scheduler.py", line 36, in from_app
    return cls(app)
  File "/usr/local/lib/python3.8/site-packages/celery_longterm_scheduler/scheduler.py", line 31, in __init__
    app.conf['longterm_scheduler_backend'], app)
  File "/usr/local/lib/python3.8/site-packages/celery/utils/collections.py", line 449, in __getitem__
    return self.__missing__(key)
  File "/usr/local/lib/python3.8/site-packages/celery/utils/collections.py", line 276, in __missing__
    raise KeyError(key)
KeyError: 'longterm_scheduler_backend'
```
What am I doing wrong?

**Comment by jheld** [comment]
Redis streams potentially could allow a more native solution to this, but I'm not sure.

Still, it's great to see that project -- I had no idea it existed. We may want to add it to the docs somewhere.

**Comment by aakash2610** [comment]
I am facing the same issue. Is there any timeline on this issue of when it is going to be fixed? Or if there is any ideal workaround that celery team recommends?
