### ISSUE TITLE
high concurrency results in OSError

### ISSUE THREAD

**Issue by fechnert** [celery/celery#4541]
Working with a high amount on concurrency (> ~128), the worker raises an OSError:

```bash
celery worker -A my_project.conf:app -c 256 -O fair -l INFO
```

```bash
 -------------- celery@host v4.1.0 (latentcall)
---- **** -----
--- * ***  * -- Linux-4.4.36-8-default-x86_64-with-SuSE-42.2-x86_64 2018-02-15 12:44:20
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7fdba1e99f28
- ** ---------- .> transport:   redis://x.x.x.x:6379/0
- ** ---------- .> results:     redis://x.x.x.x:6379/0
- *** --- * --- .> concurrency: 256 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> much_stuff     exchange=much_stuff(direct) key=much_stuff

[tasks]
  . [...]

[2018-02-15 12:44:20,297: CRITICAL/MainProcess] Unrecoverable error: OSError(24, 'Too many open files')
Traceback (most recent call last):
  File "/usr/lib/foo/lib/python3.4/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/lib/foo/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/lib/foo/lib/python3.4/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/lib/foo/lib/python3.4/site-packages/celery/concurrency/base.py", line 131, in start
    self.on_start()
  File "/usr/lib/foo/lib/python3.4/site-packages/celery/concurrency/prefork.py", line 112, in on_start
    **self.options)
  File "/usr/lib/foo/lib/python3.4/site-packages/celery/concurrency/asynpool.py", line 387, in __init__
    self.create_process_queues(): None for _ in range(processes)
  File "/usr/lib/foo/lib/python3.4/site-packages/celery/concurrency/asynpool.py", line 387, in <dictcomp>
    self.create_process_queues(): None for _ in range(processes)
  File "/usr/lib/foo/lib/python3.4/site-packages/celery/concurrency/asynpool.py", line 1037, in create_process_queues
    inq = _SimpleQueue(wnonblock=True)
  File "/usr/lib/foo/lib/python3.4/site-packages/billiard/queues.py", line 339, in __init__
    duplex=False, rnonblock=rnonblock, wnonblock=wnonblock,
  File "/usr/lib/foo/lib/python3.4/site-packages/billiard/connection.py", line 571, in Pipe
    fd1, fd2 = os.pipe()
OSError: [Errno 24] Too many open files
```

`ulimit -a` gives the following output:

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 257140
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1850
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

I already checkes the issues

- #887 OSError: Too many open files
- #217 OSError: [Errno 24] Too many open files

And like suggested [here](https://github.com/ansible/ansible/issues/12259#issuecomment-137962724), i'm scared of changing the limit via `ulimit` because i can't hold the risk to reboot the whole server.

What can i do?

**Comment by thedrow** [comment]
You can change the limit of a running process using https://serverfault.com/questions/201207/set-max-file-limit-on-a-running-process or use `sysctl -p` (see https://www.cyberciti.biz/faq/reload-sysctl-conf-on-linux-using-sysctl/).
You don't have to reboot.

**Comment by fechnert** [comment]
Thanks @thedrow, will check this asap.

I thought the Exception `OSError: [Errno 24] Too many open files` means there are not enough available file handles. I think celery should raise another Exception to clarify that the running processes limit is the bottleneck and not the open file limit.

**Comment by thedrow** [comment]
This is the error Python provides when too many file descriptors are open. These include files, sockets, pipes etc.
