### ISSUE TITLE
ImproperlyConfigured when using allow_join_result

### ISSUE THREAD

**Issue by keaneokelley** [celery/celery#4553]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.4+
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis:///

broker_url: 'redis://localhost:6379//'
result_backend: 'redis:///'
```
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
```python
g = group(mytask.s(t) for t in things).delay()
with allow_join_result():
    g.get(on_message=callback, propagate=False)
```
## Expected behavior
Should work as expected, as seen on: https://stackoverflow.com/a/45491380
## Actual behavior
```python
[2018-02-21 13:31:29,930: ERROR/ForkPoolWorker-2] Task project.modules.discovery.scheduled_scan[47449b63-053e-4a56-9b30-91b2cfa88577] raised unexpected: ImproperlyConfigured('Backend does not support on_message c
allback',)
Traceback (most recent call last):
  File "/home/user/.envs/project/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/.envs/project/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/dev/project/project/modules/discovery.py", line 149, in scheduled_scan
    NmapScan.run_scans()
  File "/home/user/dev/project/project/modules/discovery.py", line 89, in run_scans
    g.get(on_message=cls.push_update, propagate=False)
  File "/home/user/.envs/project/lib/python3.6/site-packages/celery/result.py", line 635, in get
    on_message=on_message,
  File "/home/user/.envs/project/lib/python3.6/site-packages/celery/result.py", line 687, in join
    'Backend does not support on_message callback')
celery.exceptions.ImproperlyConfigured: Backend does not support on_message callback
```
This is caused because the call to `ResultSet.supports_native_join` returns None after the `IndexError`, as `result[0]` doesn't exist (yet?):
https://github.com/celery/celery/blob/bc366c887f194a3ff1f99671d9742a525a066339/celery/result.py#L801
This seems like un-intended behavior? Note that it works fine without the `allow_join_result`, although that is needed in my case.

**Comment by keaneokelley** [comment]
Did some further testing. This issue only occurs if the call to group contains an iterable of length 0. So it's failing because `results[0]` doesn't exist since there are no tasks to begin with.

I guess the only issue here is that this is a poor error message and the situation (no tasks) has nothing to do with the backend's configuration.

**Comment by auvipy** [comment]
can you suggest the improve error message?

**Comment by keaneokelley** [comment]
I'm not sure, perhaps something about a group being created with no tasks.
