### ISSUE TITLE
AttributeError: 'str' object has no attribute 'isoformat' with ETA

### ISSUE THREAD

**Issue by scobb** [celery/celery#4560]
## Checklist
```
$ pip freeze | grep celery
celery==4.1.0
django-celery-results==1.0.1
```

## Steps to reproduce
Create chord, add eta.

```
from datetime import datetime, timedelta
from celery import chain, group
@shared_task
def add(a, b):
    return a + b

@shared_task
def sum(inputs):
    return sum(inputs)

@shared_task
def err_handler(*args, **kwargs):
    print 'an error occurred'

def stuff():
    eta = datetime.utcnow() + timedelta(seconds=10)
    return chain(
        group(
            add.s(1, 2),
            add.s(3, 4),
        ),
        sum.s()
    ).on_error(err_handler.s()).apply_async(eta=eta)
``` 
## Expected behavior
after ETA, chain begins execution and executes to completion

## Actual behavior
Group begins execution after ETA, but callback throws exception:
```
[2018-02-26 16:29:44,350: INFO/ForkPoolWorker-5] Task tasks.add[4ecc6d45-40cc-40bc-ba79-b7efad956383] succeeded in 0.00307657103986s: 3
[2018-02-26 16:29:44,351: INFO/ForkPoolWorker-7] Task celery.chord_unlock[d17aa171-1b48-49b0-bcfa-bf961c65d0ea] retry: Retry in 1s
[2018-02-26 16:29:44,352: INFO/MainProcess] Received task: celery.chord_unlock[d17aa171-1b48-49b0-bcfa-bf961c65d0ea]  ETA:[2018-02-27 00:29:45.350604+00:00] 
[2018-02-26 16:29:44,353: INFO/ForkPoolWorker-4] Task tasks.add[62706ef5-97e3-444b-9037-33b64dac866d] succeeded in 0.00494244601578s: 7
[2018-02-26 16:29:45,795: ERROR/ForkPoolWorker-2] Chord 'a5329bed-f970-4969-9177-fd0c79af0be9' raised: AttributeError("'str' object has no attribute 'isoformat'",)
Traceback (most recent call last):
  File "/home/steve/env/local/lib/python2.7/site-packages/celery/app/builtins.py", line 91, in unlock_chord
    callback.delay(ret)
  File "/home/steve/env/local/lib/python2.7/site-packages/celery/canvas.py", line 182, in delay
    return self.apply_async(partial_args, partial_kwargs)
  File "/home/steve/env/local/lib/python2.7/site-packages/celery/canvas.py", line 221, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/steve/env/local/lib/python2.7/site-packages/celery/app/task.py", line 536, in apply_async
    **options
  File "/home/steve/env/local/lib/python2.7/site-packages/celery/app/base.py", line 729, in send_task
    root_id, parent_id, shadow, chain,
  File "/home/steve/env/local/lib/python2.7/site-packages/celery/app/amqp.py", line 333, in as_task_v2
    eta = eta and eta.isoformat()
AttributeError: 'str' object has no attribute 'isoformat'
```
Interesting to note, I am using redis as backend, but the exception is thrown in amqp code.

**Comment by thedrow** [comment]
@scobb Can you please check and see if the code in the PR fixes your issue?

**Comment by scobb** [comment]
Thanks for such a quick turnaround, @thedrow. This branch resolves my issue.
Setup:
```
(env) steve@steve:~$ pip freeze | grep celery
-e git+git@github.com:celery/celery.git@12a796fbc1a1e3489861893a855cd08b686a79e9#egg=celery
django-celery-beat==1.1.1
django-celery-results==1.0.1
```
Invocation:
```
In [1]: from tasks import stuff

In [2]: a = stuff()

In [3]: a.status
Out[3]: u'SUCCESS'

In [4]: a.result
Out[4]: 10
```
Worker:
```
[2018-02-28 10:02:33,817: INFO/MainProcess] Received task: tasks.add[4d53e44a-2062-4cb8-9a15-cabdfbd31031]  ETA:[2018-02-28 18:02:43.797295+00:00] 
[2018-02-28 10:02:33,818: INFO/MainProcess] Received task: tasks.add[2e0be238-4fdb-4484-819e-36d435863404]  ETA:[2018-02-28 18:02:43.797295+00:00] 
[2018-02-28 10:02:33,819: INFO/MainProcess] Received task: celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405]  ETA:[2018-02-28 18:02:34.817394+00:00] 
[2018-02-28 10:02:35,022: INFO/ForkPoolWorker-8] Task celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405] retry: Retry in 1s
[2018-02-28 10:02:35,022: INFO/MainProcess] Received task: celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405]  ETA:[2018-02-28 18:02:36.010828+00:00] 
[2018-02-28 10:02:36,101: INFO/ForkPoolWorker-1] Task celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405] retry: Retry in 1s
[2018-02-28 10:02:36,102: INFO/MainProcess] Received task: celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405]  ETA:[2018-02-28 18:02:37.090402+00:00] 
[2018-02-28 10:02:37,115: INFO/ForkPoolWorker-6] Task celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405] retry: Retry in 1s
[2018-02-28 10:02:37,115: INFO/MainProcess] Received task: celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405]  ETA:[2018-02-28 18:02:38.103988+00:00] 
[2018-02-28 10:02:39,026: INFO/ForkPoolWorker-2] Task celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405] retry: Retry in 1s
[2018-02-28 10:02:39,026: INFO/MainProcess] Received task: celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405]  ETA:[2018-02-28 18:02:40.015273+00:00] 
/home/steve/env/local/lib/python2.7/site-packages/django_celery_results/managers.py:132: TxIsolationWarning: Polling results with transaction isolation level 'repeatable-read'
within the same transaction may give outdated results.

Be sure to commit the transaction for each poll iteration.
  warnings.warn(TxIsolationWarning(W_ISOLATION_REP.strip()))

[2018-02-28 10:02:41,014: WARNING/ForkPoolWorker-8] /home/steve/env/local/lib/python2.7/site-packages/django_celery_results/managers.py:132: TxIsolationWarning: Polling results with transaction isolation level 'repeatable-read'
within the same transaction may give outdated results.

Be sure to commit the transaction for each poll iteration.
  warnings.warn(TxIsolationWarning(W_ISOLATION_REP.strip()))

[2018-02-28 10:02:41,016: INFO/ForkPoolWorker-8] Task celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405] retry: Retry in 1s
[2018-02-28 10:02:41,016: INFO/MainProcess] Received task: celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405]  ETA:[2018-02-28 18:02:42.014940+00:00] 
/home/steve/env/local/lib/python2.7/site-packages/django_celery_results/managers.py:132: TxIsolationWarning: Polling results with transaction isolation level 'repeatable-read'
within the same transaction may give outdated results.

Be sure to commit the transaction for each poll iteration.
  warnings.warn(TxIsolationWarning(W_ISOLATION_REP.strip()))

[2018-02-28 10:02:42,100: WARNING/ForkPoolWorker-1] /home/steve/env/local/lib/python2.7/site-packages/django_celery_results/managers.py:132: TxIsolationWarning: Polling results with transaction isolation level 'repeatable-read'
within the same transaction may give outdated results.

Be sure to commit the transaction for each poll iteration.
  warnings.warn(TxIsolationWarning(W_ISOLATION_REP.strip()))

[2018-02-28 10:02:42,102: INFO/ForkPoolWorker-1] Task celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405] retry: Retry in 1s
[2018-02-28 10:02:42,102: INFO/MainProcess] Received task: celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405]  ETA:[2018-02-28 18:02:43.100789+00:00] 
/home/steve/env/local/lib/python2.7/site-packages/django_celery_results/managers.py:132: TxIsolationWarning: Polling results with transaction isolation level 'repeatable-read'
within the same transaction may give outdated results.

Be sure to commit the transaction for each poll iteration.
  warnings.warn(TxIsolationWarning(W_ISOLATION_REP.strip()))

[2018-02-28 10:02:43,106: WARNING/ForkPoolWorker-6] /home/steve/env/local/lib/python2.7/site-packages/django_celery_results/managers.py:132: TxIsolationWarning: Polling results with transaction isolation level 'repeatable-read'
within the same transaction may give outdated results.

Be sure to commit the transaction for each poll iteration.
  warnings.warn(TxIsolationWarning(W_ISOLATION_REP.strip()))

[2018-02-28 10:02:43,107: INFO/ForkPoolWorker-6] Task celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405] retry: Retry in 1s
[2018-02-28 10:02:43,107: INFO/MainProcess] Received task: celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405]  ETA:[2018-02-28 18:02:44.106500+00:00] 
[2018-02-28 10:02:44,109: INFO/ForkPoolWorker-2] Task tasks.add[2e0be238-4fdb-4484-819e-36d435863404] succeeded in 0.00283794989809s: 7
[2018-02-28 10:02:44,112: INFO/ForkPoolWorker-3] Task tasks.add[4d53e44a-2062-4cb8-9a15-cabdfbd31031] succeeded in 0.00558405928314s: 3
[2018-02-28 10:02:44,125: INFO/ForkPoolWorker-4] Task celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405] retry: Retry in 1s
[2018-02-28 10:02:44,125: INFO/MainProcess] Received task: celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405]  ETA:[2018-02-28 18:02:45.113348+00:00] 
[2018-02-28 10:02:46,036: INFO/ForkPoolWorker-7] Task celery.chord_unlock[2980b301-9108-4104-9831-9c8192cb6405] succeeded in 0.0160546428524s: None
[2018-02-28 10:02:46,037: INFO/MainProcess] Received task: tasks.sum_task[b920bc4c-7093-4171-b4ba-d8b440bab061]  ETA:[2018-02-28 18:02:43.797295+00:00] 
[2018-02-28 10:02:46,043: INFO/ForkPoolWorker-5] Task tasks.sum_task[b920bc4c-7093-4171-b4ba-d8b440bab061] succeeded in 0.0046961279586s: 10
```

Thanks again!

**Comment by thedrow** [comment]
See https://github.com/celery/celery/issues/4387
