### ISSUE TITLE
`silent=True` option in `Celery.config_from_object` does not ignore `ModuleNotFoundError`

### ISSUE THREAD

**Issue by qria** [celery/celery#4603]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Save the following as `proj.py`

```py
from celery import Celery

app = Celery(__name__)

app.config_from_object('nonexistent.module', silent=True)
print(app.conf.get('SOME_CONFIG'))
```

And start the worker with `celery -A proj worker`

## Expected behavior

Since the documentation for [`silent=True` option for `config_from_object`](http://docs.celeryproject.org/en/latest/reference/celery.html#celery.Celery.config_from_object) says it ignores all import errors, nonexistent configuration module should be ignored. Specifically in this case, it should print `None` and exit.

## Actual behavior

Uncaught `ModuleNotFoundError` is raised, resulting in a halt.

## Result of ``celery -A proj report ``

```
Traceback (most recent call last):
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/loaders/base.py", line 149, in _smart_import
    return imp(path)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/loaders/base.py", line 103, in import_from_cwd
    package=package,
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/loaders/base.py", line 97, in import_module
    return importlib.import_module(module, package=package)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonexistent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/qria/.venvs/celery-bugreport/bin/celery", line 11, in <module>
    load_entry_point('celery==4.2.0', 'console_scripts', 'celery')()
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/qria/etc/celery-bugreport/tasks.py", line 6, in <module>
    print(app.conf.get('SOME_CONFIG'))
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/utils/collections.py", line 454, in get
    return self[key]
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/utils/collections.py", line 431, in __getitem__
    return getitem(k)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/utils/collections.py", line 280, in __getitem__
    return mapping[_key]
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/collections/__init__.py", line 989, in __getitem__
    if key in self.data:
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/app/base.py", line 141, in data
    return self.callback()
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/app/base.py", line 916, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/app/base.py", line 926, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/loaders/base.py", line 131, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/loaders/base.py", line 152, in _smart_import
    return symbol_by_name(path, imp=imp)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/loaders/base.py", line 103, in import_from_cwd
    package=package,
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/site-packages/celery/loaders/base.py", line 97, in import_module
    return importlib.import_module(module, package=package)
  File "/Users/qria/.venvs/celery-bugreport/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonexistent'
```

**Comment by qria** [comment]
I am guessing this got closed because of lack of activity and resources...

Or was there an external discussion on this issue that I missed?

**Comment by auvipy** [comment]
the error seems an error on your code not in celery.

**Comment by qria** [comment]
@auvipy Reading what I wrote again, it seems like I have failed to point out that the [documentation for `silent` option](http://docs.celeryproject.org/en/latest/reference/celery.html#celery.Celery.config_from_object) explicitly says the import errors are going to be ignored. I have edited the issue to clarify where I am having issue with.

However, I still believe that this is an issue of celery itself, because I have shown with my code that there are cases where import errors are not ignored as opposed to the documentation.

I may be misunderstanding the purpose of the `silent` option, please tell me if so.

As an aside, my usecase for this option was to have an git-ignored local configuration that I can import without checking if the file really exists or not.

**Comment by atom32k** [comment]
@auvipy how is investigation going?

**Comment by auvipy** [comment]
apparently not that great....
