### ISSUE TITLE
Cannot recover from task timeout

### ISSUE THREAD

**Issue by misssprite** [celery/celery#4604]
When the task hangs and reaches the hard timeout, the worker process is killed, but the following request all failed.

I tested the task `foo` by call time.sleep() at the first invocation of the first request, and the `sleep` param of the rest requests are `0`.
I assume that the first invocation of the first request triggers timeout, the process is killed and restarted, and all the request get run normally, right?

Snippet in `foo(param)`:
```
@app.task(base=MyTask, ack_late=True, bind=True, max_retries=3, default_retry_delay=6)
def foo(param):
    tsleep = param.get('sleep') or 0 
    tsleep = int(tsleep)  
    rkey = 'sleep_tag_{}'.format(param['id']) 
    if not rget(rkey, deploy_flag='debug'): 
        print('first time processing, sleeping {}s for debug'.format(tsleep))  
        time.sleep(tsleep) 
        rset(rkey, '1', deploy_flag='debug') 
        rexpire(rkey, 3600)  
    else:  
        print('second pass, not sleeping') 
```
Task is started with:
```
celery --time-limit=20 -A task  worker -l info -Q foo
```
Version info:
```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.6
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp:///
```

Settings:
```
CELERY_TASK_SERIALIZER='json'   
CELERY_ACCEPT_CONTENT=['json']
CELERY_RESULT_SERIALIZER='json'
CELERY_IGNORE_RESULT = True
CELERY_DEFAULT_EXCHANGE = 'error'
CELERY_DEFAULT_EXCHANGE_TYPE = 'direct'
CELERYD_CONCURRENCY = 1
CELERYD_TASK_TIME_LIMIT = 300
CELERYD_PREFETCH_MULTIPLIER = 1
```

Log:
```
[2018-03-19 08:44:08,154: INFO/MainProcess] celery@fd9bf296a02e ready.
[2018-03-19 08:44:21,995: INFO/MainProcess] Received task: task.foo[5d24b460-e1d4-443f-9f5b-f956191fcb43]  
[2018-03-19 08:44:21,997: INFO/ForkPoolWorker-1] run task, request 1
[2018-03-19 08:44:22,014: WARNING/ForkPoolWorker-1] first time processing, sleeping 30s for debug
[2018-03-19 08:44:23,065: INFO/MainProcess] Received task: task.foo[ee48e129-cca4-4a58-a0a9-698f7c308271]  
[2018-03-19 08:44:28,133: INFO/MainProcess] missed heartbeat from celery@78fcf97a241d
[2018-03-19 08:44:28,134: INFO/MainProcess] missed heartbeat from celery@000d961cafc3
[2018-03-19 08:44:28,134: INFO/MainProcess] missed heartbeat from celery@9f527918381d
[2018-03-19 08:44:28,134: INFO/MainProcess] missed heartbeat from celery@deb2970511ea
[2018-03-19 08:44:42,089: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(20.0,)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(20.0,)
[2018-03-19 08:44:42,089: ERROR/MainProcess] Hard time limit (20.0s) exceeded for task.foo[5d24b460-e1d4-443f-9f5b-f956191fcb43]
[2018-03-19 08:44:42,502: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:52 exited with 'signal 15 (SIGTERM)'
[2018-03-19 08:44:42,514: WARNING/MainProcess] Substantial drift from celery@deb2970511ea may mean clocks are out of sync.  Current drift is
18 seconds.  [orig: 2018-03-19 08:44:42.513316 recv: 2018-03-19 08:44:24.004516]

[2018-03-19 08:44:42,515: WARNING/MainProcess] Substantial drift from celery@78fcf97a241d may mean clocks are out of sync.  Current drift is
18 seconds.  [orig: 2018-03-19 08:44:42.515529 recv: 2018-03-19 08:44:24.226935]

[2018-03-19 08:44:42,516: WARNING/MainProcess] Substantial drift from celery@000d961cafc3 may mean clocks are out of sync.  Current drift is
18 seconds.  [orig: 2018-03-19 08:44:42.516422 recv: 2018-03-19 08:44:24.688588]

[2018-03-19 08:44:42,517: WARNING/MainProcess] Substantial drift from celery@9f527918381d may mean clocks are out of sync.  Current drift is
18 seconds.  [orig: 2018-03-19 08:44:42.517241 recv: 2018-03-19 08:44:24.690976]

[2018-03-19 08:44:42,535: INFO/ForkPoolWorker-2] run task, request 2
[2018-03-19 08:44:42,575: ERROR/ForkPoolWorker-2] Thread 'ResultHandler' crashed: OSError('handle is closed',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 478, in run
    return self.body()
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 866, in body
    self.finish_at_shutdown()
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 915, in finish_at_shutdown
    if not outqueue._reader.poll():
  File "/usr/local/lib/python2.7/dist-packages/billiard/connection.py", line 285, in poll
    self._check_closed()
  File "/usr/local/lib/python2.7/dist-packages/billiard/connection.py", line 165, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
[2018-03-19 08:44:42,702: INFO/MainProcess] Received task: task.foo[9fce7de2-4bba-4776-88fe-4bb87bc64f7c]  
[2018-03-19 08:44:43,311: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:55 exited with 'exitcode 1'
[2018-03-19 08:44:43,327: INFO/ForkPoolWorker-3] run task, request 3
```

**Comment by bohea** [comment]
same exception

**Comment by misssprite** [comment]
@bohea , I found the cause is the unnecessarily importing of `gevent` in my case.

**Comment by Sdot-Python** [comment]
If you encounter the same problem,Can **devoid gevent** modul ......Then use **ThreadPoolExecutor** Implement multithreading
