### ISSUE TITLE
MySQL result backend defaults to BLOB which may be too short for some results (LONGBLOB)

### ISSUE THREAD

**Issue by ackdesha** [celery/celery#461]
I was running into errors caused by loading truncated pickled results. Specifically, I would get an EOFError (see below). I eventually figured out that the `result` column of the celery_taskmeta MySQL table was not able to hold all of the pickled result data. By altering the table to use LONGBLOB instead of BLOB, I was able to deal with the large results (`alter table celery_taskmeta modify result LONGBLOB`). Is there a way to make this the default type in the future?

```
[2011-08-31 13:34:13,605: ERROR/PoolWorker-1] 
Traceback (most recent call last):
  File "/home/ubuntu/w/apis/trunk/apis/celerytasks/tasks/file_task_base.py", line 293, in process
    self.process_records()
  File "/home/ubuntu/w/apis/trunk/apis/celerytasks/tasks/proxmatch_file.py", line 381, in process_records
    self.wait_results(async_result_buffer)
  File "/home/ubuntu/w/apis/trunk/apis/celerytasks/tasks/proxmatch_file.py", line 435, in wait_results
    async_result.wait()
  File "/usr/local/lib/python2.6/dist-packages/celery/result.py", line 87, in wait
    return self.get(*args, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/celery/result.py", line 83, in get
    interval=interval)
  File "/usr/local/lib/python2.6/dist-packages/celery/backends/base.py", line 110, in wait_for
    status = self.get_status(task_id)
  File "/usr/local/lib/python2.6/dist-packages/celery/backends/base.py", line 206, in get_status
    return self.get_task_meta(task_id)["status"]
  File "/usr/local/lib/python2.6/dist-packages/celery/backends/base.py", line 227, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/usr/local/lib/python2.6/dist-packages/celery/backends/database.py", line 61, in _get_task_meta_for
    task = session.query(Task).filter(Task.task_id == task_id).first()
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 1770, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 1667, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 1960, in instances
    rows = [process[0](row, None) for row in fetch]
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/mapper.py", line 2600, in _instance
    populate_state(state, dict_, row, isnew, only_load_props)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/mapper.py", line 2454, in populate_state
    populator(state, dict_, row)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/strategies.py", line 150, in new_execute
    dict_[key] = row[col]
  File "/usr/local/lib/python2.6/dist-packages/celery/db/a805d4bd.py", line 55, in process
    return loads(value)
EOFError
```

**Comment by ericraymond** [comment]
Is there a resolution on this before it was closed?

**Comment by georgepsarakis** [comment]
@ericraymond the database result backend still uses [PickleType](https://github.com/celery/celery/blob/master/celery/backends/database/models.py#L29), which maps to a `LargeBinary` field in SQLAlchemy as far as I can tell. I suggest that you review the previous comments and if you can provide or propose a solution please feel free to open a new issue.

**Comment by ericraymond** [comment]
@georgepsarakis  How about something like:

**Comment by ericraymond** [comment]
@georgepsarakis   I see your point.

Celery could directly use the MySQL longblob type but that would break the abstraction that Celery uses sqlalchemy for multiple database dialects.  The other alternatives are for SQLAlchemy to change the MySQL dialect mapping or create a new (largeblob) MySQL Dialect.

**Comment by georgepsarakis** [comment]
@ericraymond I think I came up with a possible solution. We can redefine the field as [LargeBinary](https://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.LargeBinary) and handle the pickling part separately (before storing the result). From the documentation, you can pass a length parameter to the field definition, which MySQL will then map to the corresponding type (`MEDIUMBLOB`, `LONGBLOB`) that can contain binary strings of this length:

```
-- Set the maximum length to 4GB
mysql> CREATE TABLE results(serialized_result BLOB(4294967295));
Query OK, 0 rows affected (0.02 sec)

mysql> SHOW CREATE TABLE results\G
*************************** 1. row ***************************
       Table: results
Create Table: CREATE TABLE `results` (
  `serialized_result` longblob
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.00 sec)
```

What do you think?

**Comment by ericraymond** [comment]
Looks promising! Nice.

**Comment by remeika** [comment]
@auvipy Still working on this? If not I'd be happy to take a look.

**Comment by auvipy** [comment]
please feel free

**Comment by remeika** [comment]
I am making progress here, but just wanted to let folks know that moving from `BLOB` to `LARGEBLOB` storage in MySQL will increase the storage overhead per row from from [2 to 4 bytes](https://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html#data-types-storage-reqs-strings).

**Comment by georgepsarakis** [comment]
@remeika I can't imagine this being an issue. If you would like some guidance, you can open a draft Pull Request and we can discuss the implementation there.

**Comment by ericraymond** [comment]
Any progress on this.  Can this be planned for a future release?

**Comment by ericraymond** [comment]
Hoping this is part of 5.1 release....!

**Comment by thedrow** [comment]
I'm hoping so too.
#5771 just needs some finishing touches and we'd love some help with it.

**Comment by ericraymond** [comment]
Is this part of 5.2?

**Comment by thedrow** [comment]
I'm sorry I couldn't get to this in 5.1.
I'm hoping I'll have time to finish this by 5.2.

**Comment by alexpotv** [comment]
Commenting to show interest! For now, I've bypassed this feature by manually adjusting the column type in my migration files, but would really love to see it implemented!

**Comment by mvhconsult** [comment]
Any progress? I am trying out a sql backend (MariaDB) but most tasks now fail due to this storage size.

**Comment by auvipy** [comment]
I will revisit this after celery 5.5 release
