### ISSUE TITLE
pidbox reply queue not found when starting large numbers of workers

### ISSUE THREAD

**Issue by dwiest** [celery/celery#4618]
We are doing performance testing of our grid compute application using celery version 4.1.0 and have noticed that some of the workers fail when a large number are started at once.

We are running 24 r4.16xlarge EC2 instances with 64 workers each (equal to the number of CPUs) and a concurrency setting of 8.  We didn't have any problems with the same number of r4.8xlarge instances (with 32 workers each), but we now get the following stacktrace in the logs for some of the workers.

```
2018-03-22 13:48:00,182 [INFO] 22075 <celery.worker.consumer.mingle> "mingle: searching for neighbors"
2018-03-22 13:50:29,659 [CRITICAL] 22075 <celery.worker> "Unrecoverable error: NotFound(404, u"NOT_FOUND - no queue '8f952693-0f71-39f7-af0b-d0039865e642.reply.celery.pidbox' in vhost '/'", (60, 20), u'Basic.consume')"
Traceback (most recent call last):
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/worker/consumer/mingle.py", line 38, in start
    self.sync(c)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/worker/consumer/mingle.py", line 42, in sync
    replies = self.send_hello(c)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/worker/consumer/mingle.py", line 55, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/app/control.py", line 129, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/app/control.py", line 81, in _request
    timeout=self.timeout, reply=True,
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/kombu/pidbox.py", line 321, in _broadcast
    channel=chan)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/kombu/pidbox.py", line 357, in _collect
    with consumer:
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/kombu/messaging.py", line 434, in __enter__
    self.consume()
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/kombu/messaging.py", line 477, in consume
    self._basic_consume(T, no_ack=no_ack, nowait=False)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/kombu/messaging.py", line 598, in _basic_consume
    no_ack=no_ack, nowait=nowait)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/kombu/entity.py", line 737, in consume
    arguments=self.consumer_arguments)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/amqp/channel.py", line 1564, in basic_consume
    wait=None if nowait else spec.Basic.ConsumeOk,
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/amqp/connection.py", line 477, in blocking_read
    return self.on_inbound_frame(frame)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/amqp/connection.py", line 481, in on_inbound_method
    method_sig, payload, content,
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/data/foo/.virtualenvs/foo/local/lib/python2.7/site-packages/amqp/channel.py", line 279, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
NotFound: Basic.consume: (404) NOT_FOUND - no queue '8f952693-0f71-39f7-af0b-d0039865e642.reply.celery.pidbox' in vhost '/'
```

We are using billiard, kombu and py-amqp with RabbitMQ version 3.7.2  and Erlang 20.2.  Output of celery report is listed below.

If we try to start the celery service a second time the failed workers all appear to connect to RabbitMQ properly, but celery status is behaving inconsistently.  It is showing 2 different values for the number of nodes online when run repeatedly.  Sometimes we get "200 nodes online" and sometimes we get a value like "1305 nodes online".  When I check the log for a worker that is missing from the output of celery status I can see it is taking work.

Has anyone seen problems like this?  I'm not certain celery is the culprit, since there are a few other libraries involved.

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.12
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:disabled

task_default_delivery_mode: 'transient'
task_serializer: 'pickle'
task_default_exchange_type: 'direct'
imports: [REDACTED]
worker_pool_restarts: True
random: <module 'random' from '/usr/lib64/python2.7/random.pyc'>
cobalt: <module 'cobalt' from 'REDACTED/__init__.pyc'>
worker_send_task_events: False
EMAIL_PORT: 587
enable_utc: True
mongodb_backend_settings: {
    'options': {   'connect': False}}
task_default_queue: 'ha.transient'
worker_log_format: '%(asctime)s [%(levelname)s] %(process)d <%(name)s> "%(message)s"'
EMAIL_HOST_PASSWORD: u'********'
Exchange: <class 'kombu.entity.Exchange'>
task_ignore_result: True
accept_content: ['pickle', 'json']
logger: <logging.Logger object at 0x7f33e48cae10>
CELERY_MONGODB_SCHEDULER_DB_NAME: u'aws-perftest'
CELERY_SEND_TASK_ERROR_EMAILS: True
SERVER_EMAIL: 'celery@REDACTED'
result_serializer: 'pickle'
CELERY_MONGODB_SCHEDULER_URL: u'mongodb+srv://REDACTED'
task_store_errors_even_if_ignored: False
task_default_routing_key: u'********'
task_routes: 
    (<REDACTED object at 0x7f33e35982d0>,)
Queue: <class 'kombu.entity.Queue'>
ssl: <module 'ssl' from '/usr/lib64/python2.7/ssl.pyc'>
EMAIL_USE_TLS: True
result_expires: 3600
CELERY_MONGODB_SCHEDULER_COLLECTION_NAME: 'scheduledtasks'
result_cache_max: -1
EMAIL_HOST: 'smtp.gmail.com'
target_asset_type: <function target_asset_type at 0x7f33e48daed8>
task_queues: 
    (REDACTED)
logging: <module 'logging' from '/usr/lib64/python2.7/logging/__init__.pyc'>
task_create_missing_queues: False
CobaltTaskRouter: <class 'REDACTED'>
TASK_QUEUE_MAP: {
    'cobalt.grid.tasks_facts.task_create_facts_from_inflight_data': u'inflight_facts'}
get_celery_imports: <function get_celery_imports at 0x7f33e35885f0>
retry_count: <function retry_count at 0x7f33e48dae60>
ADMINS: [[u'DevOps', u'REDACTED']]
CELERY_MONGODB_SCHEDULER_INCLUDE_SCHEDULEDTASK_ID: True
broker_url: u'amqp://celery:********@rabbit1.us-east-1a:5672//'
EMAIL_HOST_USER: 'accounts@REDACTED'
```

**Comment by dwiest** [comment]
Closing issue.  Testing environment is no longer available to reproduce issue.

**Comment by TauPan** [comment]
I've just got hit by lots of erro mails from my code after I've manually increased the number of workers to "a lot" (I think I've increased the pool by 5 and then by 10 a couple of times, but didn't really count.)

```
Environment:


Django Version: 1.11.21
Python Version: 3.4.8
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'guardian',
 'rest_framework',
 'django_filters',
 'rest_framework_filters',
 'drf_link_header_pagination',
 'airshield.common',
 'airshield.vulnerabilities',
 'airshield.cve',
 'airshield.cpes',
 'airshield.cpe_inventories',
 'airshield.cvss',
 'airshield.inventories',
 'airshield.findings',
 'airshield.aggregators')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')



Traceback:

File "/usr/lib/python3.4/site-packages/celery/app/trace.py" in trace_task
  240.                     R = retval = fun(*args, **kwargs)

File "/usr/lib/python3.4/site-packages/celery/app/trace.py" in __protected_call__
  438.                 return self.run(*args, **kwargs)

File "/usr/lib/python3.4/site-packages/airshield/common/tasks.py" in run_todos
  132.     task_queues = _get_task_queues()

File "/usr/lib/python3.4/site-packages/airshield/tasklib.py" in _get_task_queues
  148.         queue_tasks = getattr(inspect, queue)(safe=True)

File "/usr/lib/python3.4/site-packages/celery/app/control.py" in scheduled
  84.         return self._request('dump_schedule', safe=safe)

File "/usr/lib/python3.4/site-packages/celery/app/control.py" in _request
  71.             timeout=self.timeout, reply=True,

File "/usr/lib/python3.4/site-packages/celery/app/control.py" in broadcast
  307.                 limit, callback, channel=channel,

File "/usr/lib/python3.4/site-packages/kombu/pidbox.py" in _broadcast
  294.                       serializer=serializer)

File "/usr/lib/python3.4/site-packages/kombu/pidbox.py" in _publish
  259.             maybe_declare(self.reply_queue(channel))

File "/usr/lib/python3.4/site-packages/kombu/common.py" in maybe_declare
  113.     return _maybe_declare(entity, declared, ident, channel)

File "/usr/lib/python3.4/site-packages/kombu/common.py" in _maybe_declare
  120.     entity.declare()

File "/usr/lib/python3.4/site-packages/kombu/entity.py" in declare
  508.             self.queue_bind(nowait)

File "/usr/lib/python3.4/site-packages/kombu/entity.py" in queue_bind
  541.                             self.binding_arguments, nowait=nowait)

File "/usr/lib/python3.4/site-packages/kombu/entity.py" in bind_to
  551.                                        nowait=nowait)

File "/usr/lib/python3.4/site-packages/amqp/channel.py" in queue_bind
  1003.                 (50, 21),  # Channel.queue_bind_ok

File "/usr/lib/python3.4/site-packages/amqp/abstract_channel.py" in wait
  69.         return self.dispatch_method(method_sig, args, content)

File "/usr/lib/python3.4/site-packages/amqp/abstract_channel.py" in dispatch_method
  87.             return amqp_method(self, args)

File "/usr/lib/python3.4/site-packages/amqp/channel.py" in _close
  241.             reply_code, reply_text, (class_id, method_id), ChannelError,

Exception Type: NotFound
Exception Value: Queue.bind: (404) NOT_FOUND - no queue 'e2b0c9f3-db67-32f8-8bb9-f7e78c311cec.reply.celery.pidbox' in vhost '/'

```

Some of my tasks try to check if they're running already by using `celery_app.control.inspect()`. (Yes, I've been warned that the latency is very high, and I'm looking to replace this code by a more robust solution.)

It's just a development machine so it's no issue, but I wanted to share that the number of workers seems relevant here. (I've never seen an error like this in production or on more well behaved development machines.)

**Comment by auvipy** [comment]
celery 4.3 / 4.4.0rc3 is what you should try
