### ISSUE TITLE
3.1.25 >3.1.26 Regression: `ImportError: cannot import name '_detect_environment'`

### ISSUE THREAD

**Issue by ciarancourtney** [celery/celery#4619]
I think this is due to 3.1.26 expecting Kombu 4.x, which AFAIK is not compatible with celery 3.x

```
ubuntu@ciaran:/opt/master$ venv/bin/pip install celery==3.1.26
Collecting celery==3.1.26
  Using cached celery-3.1.26-py2.py3-none-any.whl
Requirement already satisfied: billiard<3.4,>=3.3.0.23 in ./venv/lib/python3.6/site-packages (from celery==3.1.26)
Requirement already satisfied: pytz>dev in ./venv/lib/python3.6/site-packages (from celery==3.1.26)
Requirement already satisfied: kombu<3.1,>=3.0.37 in ./venv/lib/python3.6/site-packages (from celery==3.1.26)
Requirement already satisfied: amqp<2.0,>=1.4.9 in ./venv/lib/python3.6/site-packages (from kombu<3.1,>=3.0.37->celery==3.1.26)
Requirement already satisfied: anyjson>=0.3.3 in ./venv/lib/python3.6/site-packages (from kombu<3.1,>=3.0.37->celery==3.1.26)
Installing collected packages: celery
  Found existing installation: celery 3.1.25
    Uninstalling celery-3.1.25:
      Successfully uninstalled celery-3.1.25
Successfully installed celery-3.1.26
```

Stacktrace

```
/opt/master/venv/bin/python /opt/master/src/manage.py celeryd -lINFO
Traceback (most recent call last):
  File "/opt/master/src/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/master/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/master/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/master/venv/lib/python3.6/site-packages/djcelery/management/base.py", line 107, in run_from_argv
    return super(CeleryCommand, self).run_from_argv(argv)
  File "/opt/master/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/master/venv/lib/python3.6/site-packages/djcelery/management/base.py", line 100, in execute
    super(CeleryCommand, self).execute(*args, **options)
  File "/opt/master/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/master/venv/lib/python3.6/site-packages/djcelery/management/commands/celeryd.py", line 25, in handle
    worker.run(**options)
  File "/opt/master/venv/lib/python3.6/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/opt/master/venv/lib/python3.6/site-packages/celery/worker/__init__.py", line 100, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/opt/master/venv/lib/python3.6/site-packages/celery/worker/__init__.py", line 141, in setup_instance
    self.blueprint.apply(self, **kwargs)
  File "/opt/master/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 221, in apply
    step.include(parent)
  File "/opt/master/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 388, in include
    inc, ret = self._should_include(parent)
  File "/opt/master/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 344, in _should_include
    return True, self.create(parent)
  File "/opt/master/venv/lib/python3.6/site-packages/celery/worker/components.py", line 245, in create
    prefetch_multiplier=w.prefetch_multiplier,
  File "/opt/master/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 340, in instantiate
    return instantiate(name, *args, **kwargs)
  File "/opt/master/venv/lib/python3.6/site-packages/celery/utils/imports.py", line 53, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/opt/master/venv/lib/python3.6/site-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/master/venv/lib/python3.6/site-packages/celery/worker/consumer/__init__.py", line 3, in <module>
    from .consumer import Consumer
  File "/opt/master/venv/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 19, in <module>
    from kombu.utils.compat import _detect_environment
ImportError: cannot import name '_detect_environment'

Process finished with exit code 1
```

Can't find what could cause this in the [diff](https://github.com/celery/celery/compare/v3.1.25...v3.1.26)

**Comment by auvipy** [comment]
@thedrow

**Comment by spjwebster** [comment]
Can confirm we're seeing this too in our environment.

**Comment by vandorjw** [comment]
It is either pypi, or the build system pushing to pypi that is broken. The wheel and the gzip do not contain the same code. See

https://pypi.python.org/packages/c3/e3/d19b6c775f15bce93befebd5f32358a3ee897578732c9e13400b8f43fae7/celery-3.1.26-py2.py3-none-any.whl#md5=3dcb20b875fe0348390127d04f901896

and 

https://pypi.python.org/packages/89/86/00f257023b3919d458b6b1df0a29c0559284f55bf885d7593ec363a413ad/celery-3.1.26.tar.gz#md5=71b31213e981797a895135baae66c61f

The 'wheel' version contains code belonging to celery 4.

**Comment by thedrow** [comment]
I'll fix it today. Sorry for the trouble.

**Comment by thedrow** [comment]
Please try again. I released Celery 3.1.26-1.

**Comment by vandorjw** [comment]
@thedrow The new release didn't work. When I extract the contents of the **wheel package**, I still find the following files:

```
./celery
./celery-3.1.26.post1.dist-info
...
<SNIP>
...
./celery/worker/autoreload.py
./celery/worker/autoscale.py
./celery/worker/components.py
./celery/worker/consumer
./celery/worker/consumer.py
./celery/worker/control.py
./celery/worker/heartbeat.py
./celery/worker/__init__.py
./celery/worker/job.py
./celery/worker/loops.py
./celery/worker/pidbox.py
./celery/worker/request.py
./celery/worker/state.py
./celery/worker/strategy.py
./celery/worker/worker.py
./celery/worker/consumer/agent.py
./celery/worker/consumer/connection.py
./celery/worker/consumer/consumer.py
./celery/worker/consumer/control.py
./celery/worker/consumer/events.py
./celery/worker/consumer/gossip.py
./celery/worker/consumer/heart.py
./celery/worker/consumer/__init__.py
./celery/worker/consumer/mingle.py
./celery/worker/consumer/tasks.py
./celery-3.1.26.post1.dist-info/DESCRIPTION.rst
./celery-3.1.26.post1.dist-info/entry_points.txt
./celery-3.1.26.post1.dist-info/METADATA
./celery-3.1.26.post1.dist-info/metadata.json
./celery-3.1.26.post1.dist-info/RECORD
./celery-3.1.26.post1.dist-info/top_level.txt
./celery-3.1.26.post1.dist-info/WHEEL
```

`./celery/worker/consumer.py` and `./celery/worker/consumer/consumer.py` **both** exist

https://pypi.python.org/pypi/celery/3.1.26-1

**Comment by thedrow** [comment]
Something went horribly wrong here :(
I'm going to re-release again now.

**Comment by thedrow** [comment]
This is the entire diff between post1 and post2: https://try.diffoscope.org/geycppcfydbe.html
It doesn't look like there are any code changes.
The diff between the 3.1 branch and the v3.1.25 tag is:
```diff
diff --git a/Changelog b/Changelog
index d3eaab04e..a4b9b0d45 100644
--- a/Changelog
+++ b/Changelog
@@ -8,6 +8,14 @@ This document contains change notes for bugfix releases in the 3.1.x series
 (Cipater), please see :ref:`whatsnew-3.1` for an overview of what's
 new in Celery 3.1.
 
+.. _version-3.1.26:
+3.1.26
+======
+:release-date: 2018-23-03 16:00 PM IST
+:release-by: Omer Katz
+
+- Fixed a crash caused by tasks cycling between Celery 3 and Celery 4 workers.
+
 .. _version-3.1.25:
 
 3.1.25
diff --git a/README.rst b/README.rst
index f5595a16c..66e0aa10c 100644
--- a/README.rst
+++ b/README.rst
@@ -4,7 +4,7 @@
 
 .. image:: http://cloud.github.com/downloads/celery/celery/celery_128.png
 
-:Version: 3.1.25 (Cipater)
+:Version: 3.1.26 (Cipater)
 :Web: http://celeryproject.org/
 :Download: http://pypi.python.org/pypi/celery/
 :Source: http://github.com/celery/celery/
@@ -424,4 +424,3 @@ file in the top distribution directory for the full license text.
 .. image:: https://d2weczhvl823v0.cloudfront.net/celery/celery/trend.png
     :alt: Bitdeli badge
     :target: https://bitdeli.com/free
-
diff --git a/celery/__init__.py b/celery/__init__.py
index 497d1cdc4..ba5f057dc 100644
--- a/celery/__init__.py
+++ b/celery/__init__.py
@@ -19,7 +19,7 @@ version_info_t = namedtuple(
 )
 
 SERIES = 'Cipater'
-VERSION = version_info_t(3, 1, 25, '', '')
+VERSION = version_info_t(3, 1, 26, '.post2', '')
 __version__ = '{0.major}.{0.minor}.{0.micro}{0.releaselevel}'.format(VERSION)
 __author__ = 'Ask Solem'
 __contact__ = 'ask@celeryproject.org'
diff --git a/celery/worker/consumer.py b/celery/worker/consumer.py
index 45e6554c0..cc93d6c86 100644
--- a/celery/worker/consumer.py
+++ b/celery/worker/consumer.py
@@ -450,10 +450,10 @@ class Consumer(object):
         def on_task_received(body, message):
             headers = message.headers
             try:
-                type_, is_proto2 = headers['task'], 1
+                type_, is_proto2 = body['task'], 0
             except (KeyError, TypeError):
                 try:
-                    type_, is_proto2 = body['task'], 0
+                    type_, is_proto2 = headers['task'], 1
                 except (KeyError, TypeError):
                     return on_unknown_message(body, message)
 
diff --git a/docs/includes/introduction.txt b/docs/includes/introduction.txt
index fab8f092a..68d2219b0 100644
--- a/docs/includes/introduction.txt
+++ b/docs/includes/introduction.txt
@@ -1,4 +1,4 @@
-:Version: 3.1.25 (Cipater)
+:Version: 3.1.26 (Cipater)
 :Web: http://celeryproject.org/
 :Download: http://pypi.python.org/pypi/celery/
 :Source: http://github.com/celery/celery/
```

I'm not sure I understand what's wrong. In any case, I released 3.1.26 again from a **fresh clone**.
I'm gonna do the same for 4.2.0.

**Comment by thedrow** [comment]
This is the diff between the original release and post2: https://try.diffoscope.org/pgthrccfhdux.html
Again, there's not much of a difference.

Are you sure the problem you are describing is the issue here?

**Comment by thedrow** [comment]
@auvipy @georgepsarakis Please help me figure this out.

**Comment by thedrow** [comment]
This is the diff between 3.1.25 and 3.1.26: https://try.diffoscope.org/bhvdqbhszhyh.html
I don't see the problem you are describing.

**Comment by ch0k0bn** [comment]
`.post2` version seems to fix the problem. Thx for your quick fix.

**Comment by vandorjw** [comment]
I can also confirm that post2 fixed the issue.
Thanks for looking into this!

**Comment by thedrow** [comment]
The question is what went wrong. I still don't understand.

**Comment by georgepsarakis** [comment]
@thedrow if you can share the commands you are using for the release process, perhaps I can check if I can reproduce it.

**Comment by thedrow** [comment]
I just `python setup.py clean build sdist bdist_wheel`.
I upload using twine with the following command: `twine upload --sign -i 12A53B890119D176 dist/celery-3.1.26.post2*`.
In Celery 3, the version is bumped manually.

**Comment by vandorjw** [comment]
If you visit [this page](https://pypi.python.org/pypi/celery/4.2.0rc1#downloads), download the Python Wheel and check what is inside this wheel, you'll find under `celery/worker/` a file called: `consumer.py`. That file does not belong in Celery 4.2

https://github.com/celery/celery/tree/v4.2.0rc1/celery/worker

The MD5 digest of the wheel is: `f57dc80bf33a1150f6672cf9a73ecede`
