### ISSUE TITLE
Unable to group the tasks for parallel excecution

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [celery/celery#4659]
I have created a tensorflow keras model as a task in celery which takes two arguments(python list,integer)  and returns error value which is a integer.
whenever i call this task, its executing successfully. But when i group the same task with multiple parameters it showing error as follows

[2018-04-12 09:27:20,405: ERROR/MainProcess] Process 'ForkPoolWorker-7' pid:11648 exited with 'signal 11 (SIGSEGV)'
[2018-04-12 09:27:20,441: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
[2018-04-12 09:27:20,701: ERROR/MainProcess] Process 'ForkPoolWorker-8' pid:11651 exited with 'signal 11 (SIGSEGV)'
[2018-04-12 09:27:20,760: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV)

Can somebody help me to solve the error (signal 11).

Example code:
   
      Task:

           def do_neuralnet(list,integer)
           "
           "

           return interger

Calling:
             res = group(do_neuralnet(list,3),do_neuralnet(list,5))()
             result = res.get()

Here list in both of the  functions is same but integer is separate.

**Comment by russoz** [comment]
Apparently you are passing the calls to the functions directly into group().

Take a look at:
 http://docs.celeryproject.org/en/latest/userguide/canvas.html#signatures

You should probably be doing something like:
```
res = group(do_neuralnet.s(list,3),do_neuralnet.s(list,5))()
result = res.get()
```
Note the `.s`. It is weird that the error you get is a SEGV. Error handling should probably be better in there.

**Comment by ramesh-chowdeshetty** [comment]
thank for your reply, even tried with signatures. but same error

**Comment by russoz** [comment]
Does it work if you create a group with just one element?

**Comment by ramesh-chowdeshetty** [comment]
no , it's not working even for one element grouping

**Comment by russoz** [comment]
> whenever i call this task, its executing successfully
are you calling this with `.delay()` or `.apply_async()` ?

**Comment by kofwang** [comment]
I am facing same issue, any updates?

**Comment by auvipy** [comment]
is it having an error with celery 4.3 or master? could you share your code snippet and error traceback ?
