### ISSUE TITLE
When app.config_form_object parse the module string that partial exist, accessing app.config will cause RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by shidenggui** [celery/celery#4673]
## Checklist

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.14
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

## Steps to reproduce

1. Create empty `test_module.py`

2. Create `app.py`, add content below:

```python
# coding=utf-8

from celery import Celery

app = Celery()
app.config_from_object('test_module.notexist')

_ = app.conf['key']
```

3. `python app.py` or   `To do anything access app.conf` will cause `RuntimeError: maximum recursion depth exceeded`

## Expected behavior

Raise

`ImportError: No module named test_module.notexists`

or 

`
AttributeError: 'test_module object has no attribute 'notexists'
`

## Actual behavior

Cause `RuntimeError: maximum recursion depth exceeded`

```
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    _ = app.conf['key']
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/utils/collections.py", line 431, in __getitem__
    return getitem(k)
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/utils/collections.py", line 280, in __getitem__
    return mapping[_key]
  File "/xxx/anaconda2/lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/xxx/anaconda2/lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/xxx/anaconda2/lib/python2.7/UserDict.py", line 36, in __getitem__
......
  File "/xxx/anaconda2/lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/xxx/anaconda2/lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/xxx/anaconda2/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/app/base.py", line 148, in data
    return self.callback()
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/app/base.py", line 911, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/app/base.py", line 921, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/loaders/base.py", line 146, in _smart_import
    return imp(path)
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/loaders/base.py", line 106, in import_from_cwd
    package=package,
  File "/xxx/anaconda2/lib/python2.7/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
    with cwd_in_path():
  File "/xxx/anaconda2/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(*args, **kwds))
RuntimeError: maximum recursion depth exceeded
```

**Comment by auvipy** [comment]
is this still the case with celery 4.2.1?

**Comment by shidenggui** [comment]
@auvipy Yes, still happen.

**Comment by auvipy** [comment]
do you have any fix in mind with an appropriate test?

**Comment by shidenggui** [comment]
@auvipy I try but failed. If I have time I will try again.
