### ISSUE TITLE
announced error with worker_state_db &&  beat_schedule_filename runinng at pypy-5.10.0

### ISSUE THREAD

**Issue by cutso** [celery/celery#4676]
OS alpine-3.7
PYPY: pypy2-5.10.0

Today, i tried to run celery with pypy in docker container, but with an error.
If i defined "worker_state_db" or "beat_schedule_filename" in config file (celeryconfig.py), celery worker will be exited with below error.

Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/local/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/local/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/site-packages/celery/worker/worker.py", line 139, in setup_instance
    self.blueprint.apply(self, **kwargs)
  File "/usr/local/site-packages/celery/bootsteps.py", line 214, in apply
    step.include(parent)
  File "/usr/local/site-packages/celery/bootsteps.py", line 343, in include
    return self._should_include(parent)[0]
  File "/usr/local/site-packages/celery/bootsteps.py", line 339, in _should_include
    return True, self.create(parent)
  File "/usr/local/site-packages/celery/worker/components.py", line 214, in create
    w._persistence = w.state.Persistent(w.state, w.statedb, w.app.clock)
  File "/usr/local/site-packages/celery/worker/state.py", line 189, in __init__
    self.merge()
  File "/usr/local/site-packages/celery/worker/state.py", line 197, in merge
    self._merge_with(self.db)
  File "/usr/local/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/site-packages/celery/worker/state.py", line 266, in db
    return self.open()
  File "/usr/local/site-packages/celery/worker/state.py", line 193, in open
    self.filename, protocol=self.protocol, writeback=True,
  File "/usr/local/lib-python/2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib-python/2.7/shelve.py", line 226, in __init__
    import anydbm
  File "/usr/local/lib-python/2.7/anydbm.py", line 45, in <module>
    _mod = __import__(_name)
  File "/usr/local/lib_pypy/dbm.py", line 144, in <module>
    _init_func('open', (c_char_p, c_int, c_int), restype=c_void_p)
  File "/usr/local/lib_pypy/dbm.py", line 118, in _init_func
    func = getattr(lib, 'dbm_' + name)
  File "/usr/local/lib-python/2.7/ctypes/__init__.py", line 383, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/lib-python/2.7/ctypes/__init__.py", line 388, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "/usr/local/lib_pypy/_ctypes/function.py", line 252, in __init__
    ptr = self._getfuncptr([], ctypes.c_int)
  File "/usr/local/lib_pypy/_ctypes/function.py", line 437, in _getfuncptr
    self._ptr = cdll.getfunc(self.name, ffi_argtypes, ffi_restype)
AttributeError: No symbol dbm_open found in library libdb-5.3.so

# =====
here is the dockerfile
# =====
FROM jamiehewland/alpine-pypy:2-5.10.0-alpine3.7

MAINTAINER mofes mofes.hk@post.com

ENV TZ Asia/Shanghai

RUN apk add --update --no-cache \
        libc-dev \
        gcc \
        tzdata \
        curl \
        curl-dev \
        postgresql-dev

RUN pip install --no-cache-dir --disable-pip-version-check \
    tornado \
    futures \
    pycares \
    pycurl \
    redis \
    psycopg2cffi \
    passlib \
    pyjwt \
    ujson \
    requests \
    wtforms \
    celery \
    flower \
    && mkdir /var/lib/celery

RUN rm -rf /var/cache/apk/*

CMD ["pypy"]

#==== end dockerfile====

# Command 
celery worker --statedb=/var/lib/celery/worker-state.db

Can anybody helps?  Thx++++

**Comment by auvipy** [comment]
this doesn't seem to be a celery issue.
