### ISSUE TITLE
WorkerShutdown and WorkerLostError in long-running task execution

### ISSUE THREAD

**Issue by YLRong** [celery/celery#4680]
I'm using celery to run tasks which are listening to some web connections and recording the messages. The environment information is as following:

> **software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.3
>             billiard:3.5.0.3 py-amqp:2.2.2
> platform -> system:Linux arch:64bit imp:CPython
> loader   -> celery.loaders.app.AppLoader
> settings -> transport:amqp results:disabled**

These tasks should always be running as I used while true loop in async function to keep recording messages sent by web server. However, after several hours, all celery tasks stopped. And I found the main process and the child processes of my celery worker were still running but  the start time of child processes' was much newer than the main process.

> **PID                  STARTED     ELAPSED COMMAND
> 15785 Mon Apr 23 03:20:01 2018  2-04:53:38 /home/ubuntu/anaconda3/bin/python /home/ubuntu/anaconda3/bin/celery worker -A data_fetcher --loglevel=info --logfile=log.txt --concurrency=10
> 18587 Tue Apr 24 08:04:20 2018  1-00:09:19 /home/ubuntu/anaconda3/bin/python /home/ubuntu/anaconda3/bin/celery worker -A data_fetcher --loglevel=info --logfile=log.txt --concurrency=10
> 18588 Tue Apr 24 08:04:20 2018  1-00:09:19 /home/ubuntu/anaconda3/bin/python /home/ubuntu/anaconda3/bin/celery worker -A data_fetcher --loglevel=info --logfile=log.txt --concurrency=10**
> 

More related information in celery log file(all child processes):

> [2018-04-24 08:04:14,623: ERROR/MainProcess] Process 'ForkPoolWorker-6' pid:15794 exited with 'exitcode 70'
> [2018-04-24 08:04:14,633: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 70.',)
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
>     self.blueprint.start(self)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
>     step.start(parent)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
>     return self.obj.start()
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 320, in start
>     blueprint.start(self)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
>     step.start(parent)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
>     c.loop(*c.loop_args())
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/celery/worker/loops.py", line 77, in asynloop
>     raise WorkerShutdown(should_stop)
> celery.exceptions.WorkerShutdown: 0
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
>     human_status(exitcode)),
> billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 70.

Why were the child processes shut down and restarted? (and the celery tasks were never queued again.)
What's the best practice to keep such long-running tasks running forever?
Any help would be appreciated!

**Comment by davidmir** [comment]
I've exactly the same problem...

**Comment by UrbanSwati** [comment]
Check #3085
