### ISSUE TITLE
Error: No nodes replied within time constraint.

### ISSUE THREAD

**Issue by surinkim** [celery/celery#4688]
I've run below command.
`celery status --app 06_celery-task-queue`

The output message
`Error: No nodes replied within time constraint.`

The result of `celery -A 06_celery-task-queue report`

    $ celery -A 06_celery-task-queue report
    
    software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.2
                billiard:3.5.0.3 redis:2.10.6
    platform -> system:Linux arch:64bit, ELF imp:CPython
    loader   -> celery.loaders.app.AppLoader
    settings -> transport:redis results:redis://localhost/
    
    broker_url: 'redis://localhost:6379//'
    result_backend: 'redis://localhost/'

I've know that already some issues mentions this error and all of them closed.

1. https://github.com/celery/celery/issues/1456
2. https://github.com/celery/celery/issues/3453

However, an error still appears. How can I solve this?
If I'm wrong, please correct me.

**Comment by surinkim** [comment]
I am really sorry to have wasted your time.

I noticed that I did not run `celery worker` until I registered the issue. Moreover, after I realized that I made a mistake, I had forgotten that I had to close the issue posted here.

I am using version 4.1.0 and celery works normally without any problems.
```bash
$ celery status --app 03_celery-task
celery@hyun-VirtualBox: OK

1 node online.
```
I apologize once again for taking care of your precious time due to my carelessness.

**Comment by japrogramer** [comment]
I have the same issue after upgrading to python 3 and the latest celery[redis]
this is how im running the app
```
#/bin/bash
# sudo systemctl restart redis-server.service &
pkill -9 -f 'celery' &&
sleep 2 &&
celery -A medicalboard.taskapp.setup:app worker --logfile=$HOME/celerylog &
sleep 2 &&
celery -A medicalboard.taskapp.setup:app beat --logfile=$HOME/celerybeatlog --loglevel=debug &
```

when i inspect
```
celery -A medicalboard.taskapp.setup:app inspect active --timeout=5
Error: No nodes replied within time constraint.
```

**Comment by japrogramer** [comment]
I found this traceback

```
[2018-11-27 01:50:22,949: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'float' object has no attribute 'items'",)
Traceback (most recent call last):
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/kombu/transport/virtual/base.py", line 632, in _callback
    self.qos.append(message, message.delivery_tag)
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/kombu/transport/redis.py", line 149, in append
    pipe.zadd(self.unacked_index_key, time(), delivery_tag) \
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/home/ubuntu/sixnexus/.env/lib/python3.5/site-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'float' object has no attribute 'items'


```

**Comment by japrogramer** [comment]
oh, just noticed this https://github.com/celery/celery/issues/5175
