### ISSUE TITLE
RC3: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by chrisgrande** [celery/celery#4699]
## Steps to reproduce
Django: 1.8.19
django-celery-beat: 1.1.1
django-celery-results: 1.0.1

While attempting to see if 4.2 fixes: https://github.com/celery/django-celery-beat/issues/7 (doesn't seem to)
I installed 4.2, RC1, 2 and then 3. When attempting to start RC3 in my test env, 
`celery -A proj worker -B -E -l info`
it fails to start with the `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.` error.

## Expected behavior
RC2 starts.

## Actual behavior

`Traceback (most recent call last):
  File "/proj.env/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/proj.env/lib/python2.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/proj.env/lib/python2.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/proj.env/lib/python2.7/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/proj.env/lib/python2.7/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/proj.env/lib/python2.7/site-packages/celery/bin/celery.py", line 476, in handle_argv
    return self.execute(command, argv)
  File "/proj.env/lib/python2.7/site-packages/celery/bin/celery.py", line 408, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/proj.env/lib/python2.7/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/proj.env/lib/python2.7/site-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/proj.env/lib/python2.7/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/proj.env/lib/python2.7/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/proj.env/lib/python2.7/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/proj.env/lib/python2.7/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

**Comment by friendka** [comment]
Same exception for env:

Python: 3.6.5
Django: 2.0.5

Without any celery-beat | celery-results.

RC2 works fine.

**Comment by headdab** [comment]
Same problem.  Config is similar to friendka.

**Comment by jonashaag** [comment]
Could you all please try this patch: https://github.com/celery/celery/pull/4719

Does this make the worker start again for you?

**Comment by friendka** [comment]
RC3 + patch https://github.com/celery/celery/pull/4719 works for me (celery worker also celery beat)

**Comment by edersonbadeca** [comment]
I have fixed the problem by import the models only in the tasks and allow the auto discover task to find in the whole application instead of installed apps section.

Thank you

**Comment by JasirMJ** [comment]
> I have fixed the problem by import the models only in the tasks and allow the auto discover task to find in the whole application instead of installed apps section.
> 
> Thank you

Please attach the code or provide reference because I'm facing  the  same issue

**Comment by truongvan** [comment]
> > I have fixed the problem by import the models only in the tasks and allow the auto discover task to find in the whole application instead of installed apps section.
> > Thank you
> 
> Please attach the code or provide reference because I'm facing the same issue

Don't use:
```python
from tasks import add
def setup_periodic_tasks(sender, **kwargs):
    # Calls test('hello') every 10 seconds.
    sender.add_periodic_task(10.0, add.s(16,16), name='add every 10')
```

let use:
```python
app.conf.beat_schedule = {
   # Calls test('hello') every 10 seconds.
    'add every 10': {
        'task': 'tasks.add',
        'schedule': 10.0,
        'args': (16, 16)
    },
}
```
You will not need `from tasks import add` which makes error `AppRegistryNotReady`
