### ISSUE TITLE
Regression: Apps aren't loaded yet

### ISSUE THREAD

**Issue by jonashaag** [celery/celery#4713]
Worker is broken in rc3 whereas it worked in rc2.

Report is broken in celery >= 4.1 (other versions untested).

The problem seems to be that Django urlconf is loaded too early, which causes some Django import that is too early in the app loading process.

### rc2

Works fine.

### rc3

```
Traceback (most recent call last):
  File "/tmp/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 476, in handle_argv
    return self.execute(command, argv)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 408, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/tmp/venv/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/tmp/venv/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/tmp/venv/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 265, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/tmp/venv/lib/python3.6/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/tmp/venv/lib/python3.6/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/base.py", line 673, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/base.py", line 683, in _autodiscover_tasks_from_fixups
    pkg for fixup in self._fixups
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/base.py", line 684, in <listcomp>
    for pkg in fixup.autodiscover_tasks()
  File "/tmp/venv/lib/python3.6/site-packages/celery/fixups/django.py", line 92, in autodiscover_tasks
    return [config.name for config in apps.get_app_configs()]
  File "/tmp/venv/lib/python3.6/site-packages/django/apps/registry.py", line 138, in get_app_configs
    self.check_apps_ready()
  File "/tmp/venv/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

### rc2
```
Traceback (most recent call last):
  File "/tmp/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 476, in handle_argv
    return self.execute(command, argv)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 408, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 279, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 363, in handle_argv
    return self(*args, **options)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 359, in run
    self.out(self.app.bugreport())
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/base.py", line 901, in bugreport
    return bugreport(self)
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/utils.py", line 349, in bugreport
    human_settings=app.conf.humanize(),
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/utils.py", line 193, in humanize
    for key, value in items(self.table(with_defaults, censored)))
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/utils.py", line 193, in <genexpr>
    for key, value in items(self.table(with_defaults, censored)))
  File "/tmp/venv/lib/python3.6/site-packages/celery/utils/text.py", line 124, in pretty
    return pformat(value, width=width, **kw)
  File "/usr/lib/python3.6/pprint.py", line 58, in pformat
    compact=compact).pformat(object)
  File "/usr/lib/python3.6/pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/usr/lib/python3.6/pprint.py", line 161, in _format
    rep = self._repr(object, context, level)
  File "/usr/lib/python3.6/pprint.py", line 393, in _repr
    self._depth, level)
  File "/usr/lib/python3.6/pprint.py", line 405, in format
    return _safe_repr(object, context, maxlevels, level)
  File "/usr/lib/python3.6/pprint.py", line 555, in _safe_repr
    rep = repr(object)
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 79, in __repr__
    return repr(self.__cast())
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 131, in __cast
    return self.__text_cast()
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 436, in _reverse_with_prefix
    self._populate()
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 288, in _populate
    for pattern in reversed(self.url_patterns):
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/XXX/urls.py", line 16, in <module>
    import allauth.account.views
  File "/tmp/venv/lib/python3.6/site-packages/allauth/account/views.py", line 19, in <module>
    from .adapter import get_adapter
  File "/tmp/venv/lib/python3.6/site-packages/allauth/account/adapter.py", line 16, in <module>
    from django.contrib.auth.models import AbstractUser
  File "/tmp/venv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/tmp/venv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/tmp/venv/lib/python3.6/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/tmp/venv/lib/python3.6/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/tmp/venv/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

### rc3
```
Traceback (most recent call last):
  File "/tmp/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 476, in handle_argv
    return self.execute(command, argv)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 408, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 279, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 363, in handle_argv
    return self(*args, **options)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 359, in run
    self.out(self.app.bugreport())
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/base.py", line 900, in bugreport
    return bugreport(self)
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/utils.py", line 349, in bugreport
    human_settings=app.conf.humanize(),
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/utils.py", line 193, in humanize
    for key, value in items(self.table(with_defaults, censored)))
  File "/tmp/venv/lib/python3.6/site-packages/celery/app/utils.py", line 193, in <genexpr>
    for key, value in items(self.table(with_defaults, censored)))
  File "/tmp/venv/lib/python3.6/site-packages/celery/utils/text.py", line 124, in pretty
    return pformat(value, width=width, **kw)
  File "/usr/lib/python3.6/pprint.py", line 58, in pformat
    compact=compact).pformat(object)
  File "/usr/lib/python3.6/pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/usr/lib/python3.6/pprint.py", line 161, in _format
    rep = self._repr(object, context, level)
  File "/usr/lib/python3.6/pprint.py", line 393, in _repr
    self._depth, level)
  File "/usr/lib/python3.6/pprint.py", line 405, in format
    return _safe_repr(object, context, maxlevels, level)
  File "/usr/lib/python3.6/pprint.py", line 555, in _safe_repr
    rep = repr(object)
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 79, in __repr__
    return repr(self.__cast())
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 131, in __cast
    return self.__text_cast()
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 436, in _reverse_with_prefix
    self._populate()
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 288, in _populate
    for pattern in reversed(self.url_patterns):
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tmp/venv/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/XXX/urls.py", line 16, in <module>
    import allauth.account.views
  File "/tmp/venv/lib/python3.6/site-packages/allauth/account/views.py", line 19, in <module>
    from .adapter import get_adapter
  File "/tmp/venv/lib/python3.6/site-packages/allauth/account/adapter.py", line 16, in <module>
    from django.contrib.auth.models import AbstractUser
  File "/tmp/venv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/tmp/venv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/tmp/venv/lib/python3.6/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/tmp/venv/lib/python3.6/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/tmp/venv/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by jonashaag** [comment]
OK, reopening.

**Comment by jonashaag** [comment]
For `celery worker`, the culprit is this change: https://github.com/celery/celery/commit/c96287fde7429ce14477b0e3caec8d0e811b990d#diff-ce735a0a5a013896225943d54d73acc8L185 (until L193)

**Comment by jonashaag** [comment]
[testproj.tar.gz](https://github.com/celery/celery/files/1979250/testproj.tar.gz)

Minimal reproducing example project. You'll have to have `django-allauth` installed.

**Comment by auvipy** [comment]
which version of django? and any django integration packages used?

**Comment by auvipy** [comment]
interesting! @jonashaag could you apply the patch as pr and see?

**Comment by jonashaag** [comment]
@auvipy sorry which patch?

**Comment by auvipy** [comment]
the problem you tracked for the regression

**Comment by jonashaag** [comment]
So with #4699 fixed, the other problem is that `celery report` crashes. Shall I move that into a new issue?

**Comment by auvipy** [comment]
yes

**Comment by thedrow** [comment]
I'm going to close this issue.
Let's fix the other crash before GA.
@jonashaag What's the new issue number for that?
