### ISSUE TITLE
opened file descriptors after restoring unacknowledged messages?

### ISSUE THREAD

**Issue by kfrendrich** [celery/celery#4726]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
software -> celery:4.0.2 (latentcall) kombu:4.1.0 py:3.5.2
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:rpc:///

- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Background
I got this error message in every 6 minutes:
```

May 11 08:49:38: [2018-05-11 06:49:38,206: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
May 11 08:49:38: Traceback (most recent call last):
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/redis/connection.py", line 392, in read_response
May 11 08:49:38:     raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
May 11 08:49:38: OSError: Connection closed by server.
May 11 08:49:38: During handling of the above exception, another exception occurred:
May 11 08:49:38: Traceback (most recent call last):
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 318, in start
May 11 08:49:38:     blueprint.start(self)
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
May 11 08:49:38:     step.start(parent)
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 594, in start
May 11 08:49:38:     c.loop(*c.loop_args())
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/celery/worker/loops.py", line 88, in asynloop
May 11 08:49:38:     next(loop)
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/kombu/async/hub.py", line 354, in create_loop
May 11 08:49:38:     cb(*cbargs)
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/kombu/transport/redis.py", line 1040, in on_readable
May 11 08:49:38:     self.cycle.on_readable(fileno)
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/kombu/transport/redis.py", line 337, in on_readable
May 11 08:49:38:     chan.handlers[type]()
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/kombu/transport/redis.py", line 714, in _brpop_read
May 11 08:49:38:     **options)
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
May 11 08:49:38:     response = connection.read_response()
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/redis/connection.py", line 624, in read_response
May 11 08:49:38:     response = self._parser.read_response()
May 11 08:49:38:   File "/home/xxx/server/venv/lib/python3.5/site-packages/redis/connection.py", line 403, in read_response
May 11 08:49:38:     (e.args,))
May 11 08:49:38: redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
```

Sometimes after this traceback Iog I see this log line:
`Restoring 2 unacknowledged message(s)`
When I see this, the number of opened file descriptors of the celery process increasing with one.

When the Celery got a higher load, it tend to reach more than 1000 file descriptors.
And finally ends with this (which is as I know a select/poll related thing in redis-py):
```
[CRITICAL/MainProcess] Unrecoverable error: ValueError('filedescriptor out of range in select()',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/dist-packages/kombu/async/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 671, in _receive
    while c.connection.can_read(timeout=0):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 619, in can_read
    bool(select([sock], [], [], timeout)[0])
ValueError: filedescriptor out of range in select()
```
And the Celery crashes.

## My question
Does anyone have any idea where this 6 minutes timeout comes from and why is this "restore" leaves a file descriptor open?

**Comment by kfrendrich** [comment]
I've already realized that's not a timeout. If I increase the frequency of the background tasks then the it crashes in 1 minute.

**Comment by kfrendrich** [comment]
I've realized that the "socket_timeout" configuration parameter was the problem.
Sorry.

**Comment by georgepsarakis** [comment]
@kfrendrich thanks for sharing the explanations and solution to the issue, as other users may benefit from that.
