### ISSUE TITLE
self._conninfo.transport.implements.async throws AttributeError: async

### ISSUE THREAD

**Issue by rodrigc** [celery/celery#4747]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

1.  Create a Python 2.7 virtualenv
2.  Using the following requirements.txt file:

```
git+https://github.com/apache/incubator-airflow@v1-10-test#egg=apache-airflow[celery,crypto,emr,hive,hdfs,ldap,mysql,postgres,redis,slack,s3]
bson==0.4.3
celery>=4.2.0rc3
kombu>=4.2.0
```

4.  Do a `pip install -r requirements.txt`
5.  Do `airflow worker`

## Expected behavior

Airflow worker should start.

## Actual behavior

Airflow worker crashes

```
[2018-05-21 06:39:23,980] {__init__.py:48} INFO - Using executor CeleryExecutor
Traceback (most recent call last):
  File "/bin/airflow", line 32, in <module>
    args.func(args)
  File "/usr/lib/python2.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/airflow/bin/cli.py", line 959, in worker
    worker.run(**options)
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 101, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 124, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 243, in should_use_eventloop
    self._conninfo.transport.implements.async and
  File "/usr/lib/python2.7/site-packages/kombu/transport/base.py", line 125, in __getattr__
    raise AttributeError(key)
AttributeError: async
```

## celery report

```
celery -A airflow.executors.celery_executor:app report
```

```
[2018-05-21 07:01:14,013] {configuration.py:212} WARNING - section/key [celery/ssl_active] not found in config
[2018-05-21 07:01:14,014] {default_celery.py:51} WARNING - Celery Executor will run without SSL

software -> celery:4.2.0rc3 (windowlicker) kombu:4.2.0 py:2.7.5
            billiard:3.5.0.2 sqlalchemy:1.1.18
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqla results:db+mysql://airflow:**@localhost:3306/airflow

broker_transport_options: {
    u'ssl_active': False,
    u'ssl_cacert': u'',
    u'ssl_cert': u'',
    u'ssl_key': u'********',
    u'visibility_timeout': 21600}
broker_url: u'sqla+mysql://airflow:blah@localhost:3306/mydata'
worker_concurrency: 16
worker_prefetch_multiplier: 1
task_acks_late: True
event_serializer: 'json'
accept_content: ['json', 'pickle']
task_default_queue: 'airflow_celery'
result_backend: u'db+mysql://airflow:********@localhost:3306/airflow'
task_default_exchange: 'airflow_celery'
```

**Comment by rodrigc** [comment]
@thedrow can you confirm, it looks like you *just fixed* this in: https://github.com/celery/celery/commit/c8ef7ad60b72a194654c58beb04a1d65cd0435ad

**Comment by thedrow** [comment]
Yup this is the last stage before GA.
I'm gonna release Celery 4.1.1 soon. In the meanwhile, either install from master or use Celery 4.1.1.

**Comment by rodrigc** [comment]
@thedrow Cool, thanks.

I changed my requirements.txt to:

```
git+https://github.com/celery/celery@master#egg=celery
git+https://github.com/apache/incubator-airflow@v1-10-test#egg=apache-airflow[celery,crypto,emr,hive,hdfs,ldap,mysql,postgres,redis,slack,s3]
kombu>=4.1.0
```

And re-ran my test with airflow and confirmed the problem is gone.

**Comment by rodrigc** [comment]
@thedrow just to confirm, are you merging all this async rename stuff to celery 4.1.1?

**Comment by mouradmourafiq** [comment]
I pinned `kombu==4.1.0`

**Comment by rodrigc** [comment]
@thedrow thanks for releasing celery 4.1.1.  Can you also release a new 4.2.0rc which has this async stuff fixed?

**Comment by thedrow** [comment]
@rodrigc I will.

**Comment by thedrow** [comment]
Done.

**Comment by rodrigc** [comment]
@thedrow Thanks for fixing this so quickly!
