### ISSUE TITLE
Celery worker state changes to offline after a while

### ISSUE THREAD

**Issue by maxdebayser** [celery/celery#4758]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.

```#>celery -A tasks report

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.5.2
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://redis-prod/0

result_backend: 'redis://redis-prod/0'
task_track_started: True
task_acks_late: True
task_routes: {
 '*': {'queue': 'queue1'}}
worker_send_task_events: True
result_serializer: 'json'
broker_connection_max_retries: 0
broker_heartbeat: 20
worker_pool_restarts: True
task_serializer: 'json'
worker_redirect_stdouts_level: 'INFO'
accept_content: ['json', 'pickle']
task_queue_max_priority: 10
broker_url: 'amqp://guest:********@rabbitmq-prod:5672//'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

No, this issue is happening in release 4.1.0

## Steps to reproduce

Not sure, it happens randomly.

## Expected behavior

Workers should stay online in flower unless there is a problem. If there really was a persistent problem I would expect commands like 
```
celery -A tasks control heartbeat
celery -A tasks status
```

to show the workers as offline as well.

## Actual behavior

After several hours running, some workers appear as offline in flower and `celery -A proj events --dump` records no heartbeats coming from these workers. At the same time 
```
celery -A tasks control heartbeat
celery -A tasks status
```
show all workers as online. 

When I restart RabbitMQ with 
```
rabbitmqctl stop_app && rabbitmqctl start_app
```
the workers return to the online state and at the same time, the other worker nodes log messages complaining about a "Substantial drift" of several hours in relation to the clocks of the nodes that were offline. So it seems that somewhere the missing heartbeats were bottled up.

Another way to make them online again is to delete the celeryev.* queues in RabbitMQ.

This problem affect both workers with the fork pool and the gevent pool.

## Discussion

Ok, I know the described behavior above is pretty vague. Basically there are a zillion thing that could go wrong with the connection of the worker nodes to RabbitMQ. These worker nodes are deployed in Kubernetes pods in VMWare nodes, so there is a SNAT and DNAT going on. The VMs could be missing clock interrupts, or there could be problems with the conntrack tables, or the memory of the nodes could be exhausted. Put simply, it's expected that from time to time a worker node will loose connection to the broker. However, with worker heartbeats and socket KEEPALIVE (https://github.com/celery/py-amqp/blob/2304654c00e7fde13f32226a097a73eab7f7275f/amqp/transport.py#L165) it should be possible to detect connection problems and start recovery procedures.

I don't know exactly where in the celery/kombu/pq-amqp stack to look to debug this. I would appreciate any advice on that. In the meantime I'm going to activate CELERY_RDBSIG=1 and wait for workers to go offline again and try to get a stacktrace.

Maybe setting py-amqp socket read_timeout or write_timeout could be helpful in detecting stale TCP connections. Any thoughts on that? Another question that I have is how can I know which celeryev*. queue is owned by which worker? The connection descriptors in RabbitMQ are not helpful because of the SNAT.

**Comment by zwg-zero** [comment]
I have offline problem also, though I'm monitoring celery by flower.
I found:
when the link to broker blocked for a little period of time (less than keepalive time interval), The link which used for send events to broker will loss, and would not reconnect.
The flower will show the celery work is offline, but actually the celery work can be sent tasks.  
if block time of link larger than keepalive time interval, the connections(including task consuming and even pushing) to broker will be reconnected, so the flower will show the celery online.

**Comment by maxdebayser** [comment]
That's an interesting theory, @zwg-zero, how did you come to this conclusion? In the datacenter where our celery nodes are running sometimes there are small connection delays due to high traffic. And flower then shows the workers as offline exactly as you described.

**Comment by zwg-zero** [comment]
@maxdebayser I emulated the network block  using iptables(linux machine) rule to block traffic between celery worker and rabbitmq server(broker). 
1. start celery worker, and flower, use `ss -antp | grep amqp_port ` you will find three links connecting to broker, one for tasks consumer, one for even pushing (flower will enable celery worker event sending) and another one which I'm have no idea what does it for.
2. use iptables rule like : `iptables -I INPUT -tcp --dport amqp_port -j DROP` to block traffic (by enable celery worker debug, we can know when it sends keepalive message, enable the iptables rule just after a keepalive message sent )
3. wait a short time but before the next keepalive messge sending, remove the above iptables rule, like `iptables -D INPUT 1`
4.  use `ss -antp | grep amqp_port ` again, you will find one of link to broker disappeared
5. the flower will show the celery worker offline
6. I've ever  read a similar issue in celery(I can't find it now), one guy mentioned it's because celery event link to broker not use keepalive, only tasks consumer link use keepalive.
if you need more details to reproduce the above issue, I can provide.

**Comment by maxdebayser** [comment]
@zwg-zero That's awesome, with a reliable way to reproduce this issue it will be much easier to find a solution. I previously thought that the three connections, task queue, event queue and remote control queue were actually three amqp channels multiplexed over the same tcp connection. But `ss -antp` really shows three distinct connections, as you said.
I'll try to setup a minimal test case and share any results here.

**Comment by leveryd** [comment]
maybe i meet the same problem.
https://github.com/mher/flower/issues/806

**Comment by maxdebayser** [comment]
@zwg-zero , I've managed to reproduce your findings. I have a worker with 10s heartbeat. When I drop the packets for a 5s, many times the worker does not recover that third tcp connection.

`iptables -I INPUT -p tcp --dport 5672 -j DROP && sleep 5s && iptables -D INPUT 1`

However, when I drop the packets for a longer period, celery throws an exception and reconnects.

`iptables -I INPUT -p tcp --dport 5672 -j DROP && sleep 15s && iptables -D INPUT 1`

```
[2018-06-08 13:37:05,946: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/async/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/transport/base.py", line 236, in on_readable
    reader(loop)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/connection.py", line 476, in blocking_read
    frame = self.transport.read_frame()
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/transport.py", line 226, in read_frame
    frame_header = read(7, True)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/transport.py", line 401, in _read
    s = recv(n - len(rbuf))
TimeoutError: [Errno 110] Connection timed out

```

**Comment by maxdebayser** [comment]
Ok, I've found _a_ solution. But I don't know if it is a _good_ solution. Basically there some low level exception get swallowed. This patch lets them through:
```
diff --git a/celery/events/dispatcher.py b/celery/events/dispatcher.py
index 6e77e4121..29b285138 100644
--- a/celery/events/dispatcher.py
+++ b/celery/events/dispatcher.py
@@ -156,6 +156,8 @@ class EventDispatcher(object):
                 headers=self.headers,
                 delivery_mode=self.delivery_mode,
             )
+        except ConnectionError:
+            raise
         except Exception as exc:  # pylint: disable=broad-except
             if not self.buffer_while_offline:
                 raise
```

Now eveytime I drop packtes, I get this exception and then celery recovers:

```
[2018-06-08 15:44:16,822: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/async/hub.py", line 293, in create_loop
    poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/async/hub.py", line 136, in fire_timers
    entry()
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/async/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/async/timer.py", line 127, in _reschedules
    return fun(*args, **kwargs)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/heartbeat.py", line 47, in _send
    **SOFTWARE_INFO)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/events/dispatcher.py", line 201, in send
    retry_policy=retry_policy)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/events/dispatcher.py", line 142, in publish
    routing_key=type.replace('-', '.'), **kwargs)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/events/dispatcher.py", line 157, in _publish
    delivery_mode=self.delivery_mode,
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/channel.py", line 1734, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/transport.py", line 258, in write
    self._write(s)
BrokenPipeError: [Errno 32] Broken pipe
[2018-06-08 15:44:16,829: ERROR/MainProcess] Error on restarting Heart: BrokenPipeError(32, 'Broken pipe')
Traceback (most recent call last):
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/async/hub.py", line 293, in create_loop
    poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/async/hub.py", line 136, in fire_timers
    entry()
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/async/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/async/timer.py", line 127, in _reschedules
    return fun(*args, **kwargs)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/heartbeat.py", line 47, in _send
    **SOFTWARE_INFO)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/events/dispatcher.py", line 201, in send
    retry_policy=retry_policy)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/events/dispatcher.py", line 142, in publish
    routing_key=type.replace('-', '.'), **kwargs)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/events/dispatcher.py", line 157, in _publish
    delivery_mode=self.delivery_mode,
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/channel.py", line 1734, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/transport.py", line 258, in write
    self._write(s)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/consumer/heart.py", line 35, in stop
    c.heart = c.heart and c.heart.stop()
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/heartbeat.py", line 61, in stop
    self._send('worker-offline')
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/worker/heartbeat.py", line 47, in _send
    **SOFTWARE_INFO)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/events/dispatcher.py", line 201, in send
    retry_policy=retry_policy)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/events/dispatcher.py", line 142, in publish
    routing_key=type.replace('-', '.'), **kwargs)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/celery-4.1.0-py3.5.egg/celery/events/dispatcher.py", line 157, in _publish
    delivery_mode=self.delivery_mode,
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/kombu-4.1.0-py3.5.egg/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/channel.py", line 1734, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "/home/mbayser/.pyenv/versions/celery-env/lib/python3.5/site-packages/amqp-2.2.2-py3.5.egg/amqp/transport.py", line 258, in write
    self._write(s)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by maxdebayser** [comment]
No, this is not a complete solution yet because it restart the entire worker. The exception has to be handled somwhere, it can't just go all the way up.

**Comment by maxdebayser** [comment]
Ok, I think this is the correct path. I'm going to open a PR:

```
diff --git a/celery/worker/heartbeat.py b/celery/worker/heartbeat.py
index 8bd0dcc5f..e82d5ef7f 100644
--- a/celery/worker/heartbeat.py
+++ b/celery/worker/heartbeat.py
@@ -44,6 +44,7 @@ class Heart(object):
                                  active=len(active_requests),
                                  processed=all_total_count[0],
                                  loadavg=load_average(),
+                                 retry=True,
                                  **SOFTWARE_INFO)
 
     def start(self):
```

**Comment by maxdebayser** [comment]
Pull request https://github.com/celery/celery/pull/4804

**Comment by SHxKM** [comment]
I'm also experiencing this now (seemingly) out of the blue after never having seen it for over 1.5 years of running Celery. Only dependency that I see could contribute to this is `redis-py`, which I've removed, and will report back.

**Comment by thedrow** [comment]
Yes because it triggers another problem.

**Comment by echoocking** [comment]
same behavior with celery: 4.0.2, redis: 2.10.5, 
solve it by update kombu and redis

pip install kombu --upgrade
pip install redis --upgrade

**Comment by echoocking** [comment]
but another problem is redis connection always broken

[E 190413 10:36:00 events:125] Failed to capture events: 'Error while reading from socket: (u'Connection closed by server.',)', trying again in 1 seconds.

**Comment by alexandernst** [comment]
Any news on this?

**Comment by aliniribeiroo** [comment]
Im having the same problem!

**Comment by AleeRajpoot** [comment]
Still no solution to this? 👎

**Comment by sajjadalee** [comment]
Should we migrate to Apache Airflow?

**Comment by tatitati** [comment]
I'm also having this issue:
https://github.com/mher/flower/issues/1007

**Comment by thedrow** [comment]
> Should we migrate to Apache Airflow?

No, you should try to debug the problem and provide a PR that doesn't break functionality for other users.
We don't have the manpower to solve every bug we have.

**Comment by auvipy** [comment]
> Should we migrate to Apache Airflow?

Apache Airflow also use celery and the airflow core contributors help us debug and fix celery bugs and improve it for last few months.

**Comment by turbaszek** [comment]
> > Should we migrate to Apache Airflow?
> 
> Apache Airflow also use celery and the airflow core contributors help us debug and fix celery bugs and improve it for last few months.

@auvipy that's funny how I landed here because of https://github.com/apache/airflow/issues/11622 😄

**Comment by hmilkovi** [comment]
Any news?

I have use case where I need specific worker per machine to schedule tasks and this is an game breaker for me.

**Comment by hmilkovi** [comment]
Also have observed same behavior with Redis as broker.

also notice i was on Celery v4.4.7 then upgraded to v5.0.5 which also didn't help.

Also what I have noticed is that all workers that are near broker seem to have more stable online status then other in
other datacenters (Network is fine we have monitoring for packet loss and open ports).

I'm not sure if it has to do with latency or other as I don't see failed connections on Brokers or timeoutes.

**Comment by hmilkovi** [comment]
Hi @auvipy , I have noticed that after tuning TCP keepalive (VM and in Docker) I was able to get
all workers stable online.

It would be nice to see latency and TCP keepalive settings from other Celery users that have the same issue as I suspect this is an issue of dead connections.

**Comment by hmilkovi** [comment]
After more investigation it's definitely issue in Celery as I have put Haproxy in between broker and workers in other datacenter after this it stopped to happen.

**Comment by thedrow** [comment]
@hmilkovi Is there a fix you'd like to propose that doesn't hurt other users?

**Comment by hmilkovi** [comment]
@thedrow I will need some time do check or debug this as I tested following that didn't work:
1. Broker send tcp keepalive every second + timeout 120
2. Disable connection pulling to broker
3. More frequent heartbeats from wokers to broker

Only adding broker tcp reverse proxy near worker helped.  I would also like more Celery users to try this to double confirm.
Also notice connections to brokers stay up so I suspect issue is in kombu how it handles hearthbeats.

**Comment by maxdebayser** [comment]
My PR that fixed this problem was reverted with the claim that it broke other things. @zwg-zero had found a simple set of steps to reproduce the problem that I successfully reproduced on my machine. With my PR, that set of steps was no longer able to reproduce the problem. Similar evidence was never given for the claim that this PR broke something else.

I've been using a fork of celery 4 with my patch for 2 years now and have never had the problem again. Why can't there be a another configuration flag that configures the retry parameter?

**Comment by thedrow** [comment]
This is where the problem lies.
https://github.com/celery/celery/issues/4876#issuecomment-417303468

We need to be able to send a heartbeat from the producer as well.

**Comment by hmilkovi** [comment]
@thedrow I'm not sure about it as connections are alive at TCP layer and also happens not only with RabbitMQ but also Redis.
Notice I even tried on Redis SO_KEEPALIVE to send TCP ACKs to clients in absence of communication and didn't help just some time it got Workers online but not for to long.

@maxdebayser I tried with our patch didn't help

**Comment by salitaba** [comment]
I encountered a similar issue where my worker would intermittently go offline, especially during extended periods of high CPU usage. After some investigation, I suspected that the problem lay in the heartbeat checking mechanism and the connection with RabbitMQ, which seemed to slow down, causing the worker to erroneously believe it couldn't connect to RabbitMQ.

To address this, I made several adjustments to my Django configuration, which effectively resolved the issue:

CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_SEND_EVENTS = True
CELERY_SEND_SENT_EVENT = True
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_PERSISTENT = True
CELERY_REDIS_SOCKET_KEEPALIVE = True
CELERY_BROKER_POOL_LIMIT = None
CELERY_BROKER_CONNECTION_TIMEOUT = 300
CELERY_BROKER_MAX_RETRIES = None
CELERY_WORKER_LOST_WAIT = 300
CELERY_WORKER_STATE_DB = "worker.db"
CELERY_WORKER_CANCEL_LONG_RUNNING_TASKS_ON_CONNECTION_LOSS = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CHANNEL_ERROR_RETRY = True

These changes included increasing the worker lost wait to 300 seconds, removing the Celery broker pool limit, increasing the broker connection timeout, removing the broker max retries limit, enabling the worker to cancel long-running tasks on connection loss, and enabling broker channel error retry.

It's worth noting that my Celery version is 5.3.6.

This configuration adjustment significantly stabilized my worker performance, and I haven't experienced any further downtime since implementing these changes.

**Comment by max-wittig** [comment]
Noticed the same issue here without any logs, it just stops 😦 

![image](https://github.com/user-attachments/assets/51e7eb22-ca3e-4a61-bc34-aae0f3ceee0a)

**Comment by max-wittig** [comment]
The last log I see is: `{"task": "bom.tasks.my-short-task", "event": "task_started", "timestamp": "2024-09-04T03:37:09.645489Z", "logger": "django_structlog.celery.receivers", "level": "info"}`

So it never emitted `task_succeeded` on this very short running task

**Comment by hnykda** [comment]
I am seeing something similar, unfortunately. Really hard to debug and understand what's going on. Workers just go offline after some time, even though they seem to be perfectly healthy and doing useful work. It's especially weird when I see them literally crunching a task while being seemingly offline when using `celery inspect ping` or are offline in `flower`. They then go online for a second, only to go offline again, and seemingly when all work is done, they go back to alive 😢 . And it's not that they would be even using that much of CPU...

I will probably try @salitaba 's options and see if it helps. But came here to say that this is an issue at least on 5.5.1 with Redis, hosted on kubernetes.

**Comment by WorkHardes** [comment]
+1 on this, but I see stopping only of my default celery worker
