### ISSUE TITLE
Kombu Import Error when running celery 4.1.1 and python 3.6.5 with supervisor on Ubuntu 16

### ISSUE THREAD

**Issue by longd3** [celery/celery#4760]
Everything is fine when i run manually but whenever I run with supervisor, this error pops up

```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/bin/celery.py", line 476, in handle_argv
    return self.execute(command, argv)
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/bin/celery.py", line 408, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/worker/worker.py", line 101, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/worker/worker.py", line 132, in setup_instance
    self.pool_cls = _concurrency.get_implementation(self.pool_cls)
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/concurrency/__init__.py", line 23, in get_implementation
    return symbol_by_name(cls, ALIASES)
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 18, in <module>
    from celery.concurrency.base import BasePool
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/concurrency/base.py", line 15, in <module>
    from celery.utils import timer2
  File "/var/lib/jenkins/workspace/Staging/nike/ENV/lib/python3.6/site-packages/celery/utils/timer2.py", line 16, in <module>
    from kombu.asynchronous.timer import Entry
ModuleNotFoundError: No module named 'kombu.asynchronous.timer
```

**Comment by clokep** [comment]
You need to be using kombu 4.2.0 with Celery 4.1.1. Trying pinning both of those or reinstalling Celery with the upgrade flag (`pip install -U celery==4.1.1`).

**Comment by longd3** [comment]
Actually i was able to over come by deleting kombu at ENV level, i am not sure why there is one there besides the one in sites-package. Hope it helps if anyone runs to the same madness
