### ISSUE TITLE
In 4.2.0rc4, executing a group within a chain results in a TypeError

### ISSUE THREAD

**Issue by badloop** [celery/celery#4768]
### Celery Report Output
```sh
software -> celery:4.2.0rc4 (windowlicker) kombu:4.2.0 py:3.6.5
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://127.0.0.1:6379/0

broker_url: 'amqp://guest:********@127.0.0.1:5672//'
result_backend: 'redis://127.0.0.1:6379/0'
```
## Redis Server version
`Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=22c6ee099916a58b`

## RabbitMQ Version
`RABBITMQ_DEBIAN_VERSION=3.7.4-1`

## Steps to reproduce
Create two tasks, execute task 1 in a chain and then execute task 2 twice in a group in the chain, i.e. - 
```
( task1 | group( task2, task2) )
## Expected behavior
All tasks execute successfully
## Actual behavior
```

```sh
Exception raised outside body: EncodeError(TypeError("Object of type 'TypeError' is not JSON serializable",),):
Traceback (most recent call last):
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'AsyncResult' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/app/trace.py", line 442, in trace_task
    uuid, retval, task_request, publish_result,
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 144, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 316, in store_result
    request=request, **kwargs)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 658, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 266, in encode
    _, _, payload = self._encode(data)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 270, in _encode
    return dumps(data, serializer=self.serializer)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
kombu.exceptions.EncodeError: Object of type 'AsyncResult' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'TypeError' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/app/trace.py", line 445, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/app/trace.py", line 338, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/app/trace.py", line 172, in handle_error_state
    call_errbacks=call_errbacks)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/app/trace.py", line 217, in handle_failure
    call_errbacks=call_errbacks,
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 155, in mark_as_failure
    traceback=traceback, request=request)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 316, in store_result
    request=request, **kwargs)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 658, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 266, in encode
    _, _, payload = self._encode(data)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 270, in _encode
    return dumps(data, serializer=self.serializer)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
kombu.exceptions.EncodeError: Object of type 'TypeError' is not JSON serializable

  exc, exc_info.traceback)))
[2018-05-26 17:01:43,698: ERROR/MainProcess] Pool callback raised exception: EncodeError(TypeError("Object of type 'TypeError' is not JSON serializable",),)
Traceback (most recent call last):
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'TypeError' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/billiard/pool.py", line 1747, in safe_apply_callback
    fun(*args, **kwargs)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/worker/request.py", line 366, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 155, in mark_as_failure
    traceback=traceback, request=request)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 316, in store_result
    request=request, **kwargs)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 658, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 266, in encode
    _, _, payload = self._encode(data)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/backends/base.py", line 270, in _encode
    return dumps(data, serializer=self.serializer)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
```

**Comment by xirdneh** [comment]
Seems like there's an error raised and it can't be serialized.
Can you try to run the function manually with the arguments that would be passed as if they were in a chain and heck if there's any Exception raised?

**Comment by thedrow** [comment]
I don't think this is a severe bug. If it's a regression we'll have to block the release to fix it though.
@badloop Does your issue reproduce with Celery 4.1.1?

**Comment by auvipy** [comment]
@thedrow can we release pyamqp 2.3 in the mean time?

**Comment by thedrow** [comment]
I will do so.

**Comment by badloop** [comment]
@thedrow Confirming this works fine in 4.1.1

**Comment by thedrow** [comment]
@badloop Care to contribute the test case to our integration test suite?
Mark it as xfail so we can try to debug it.

**Comment by georgepsarakis** [comment]
@thedrow @badloop I think I may have located the root cause.

This [commit](https://github.com/celery/celery/commit/48de89df0c76e2961c3c27341b650dcd3a074be9#diff-58b5816dbb95159ae9810e56eac54312R874) introduced changes in the `as_typle` method.

I believe this [line](https://github.com/celery/celery/commit/48de89df0c76e2961c3c27341b650dcd3a074be9#diff-58b5816dbb95159ae9810e56eac54312R874) should actually be:

```python
return (self.id, self.parent.as_tuple()), [r.as_tuple() for r in self.results]
```

See also the `AsyncResult.as_tuple()` implementation [here](https://github.com/celery/celery/blob/2636251a1249634258c1910c6400bf2ccf28b8ed/celery/result.py#L128).

**Comment by thedrow** [comment]
Ok so we need an integration test proving that this fails without your change and that everything else is fine without it.
We can postpone unit tests if needed/possible because we really do need to hit GA.

**Comment by badloop** [comment]
So is this being handled, or do you still need a test from me?

**Comment by georgepsarakis** [comment]
@badloop contributions are always welcome :smile:

**Comment by georgepsarakis** [comment]
@xirdneh let me know if you need any help.

**Comment by badloop** [comment]
@georgepsarakis I will put together a unit test for this specifically. I would need some guidance on a integration test.

**Comment by thedrow** [comment]
@badloop Hi, do you need help with the test case?

**Comment by tothegump** [comment]
@badloop

**Comment by tothegump** [comment]
@badloop 
Hi, how to reproduce? I did this
## first define two tasks
```Python
@app.task
def task1():
    return 1

@app.task
def task2():
    return 2
```
## then, send task
```Python
chain(task1.si(), group(task2.si(), task2.si())).delay()
```
and there is no error.
Did I have some thing wrong?
## celery report
```
software -> celery:4.2.0rc4 (windowlicker) kombu:4.2.0 py:3.5.2
            billiard:3.5.0.3 py-amqp:2.3.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost/3

broker_url: 'amqp://uuu:********@localhost:5672/vh'
result_backend: 'redis://localhost/3'
```

**Comment by xirdneh** [comment]
@tothegump I was talking to him on IRC and I believe he has the unit test for this.
I also asked him to post some sample code to see if the issue is still in the chain serialization or in the tasks.
Hopefully he'll have some time to post them.

**Comment by badloop** [comment]
https://gist.github.com/badloop/d718f8c5919d8742797881d04a5c7352

Did what I could to set up the situation I was running into on this gist.  I'm putting the unit test together right now

**Comment by xirdneh** [comment]
I believe the problem is when trying to serialize an AsyncResult.
In the example there is a task called `workflow` which is the one that @badloop  is execution to kickstart the workflow.
This task creates a chain which result is then returned.
Kombu is trying to serialize the AsyncResult returned by the chain.
If the `workflow` function is called as a function (i.e. `workflow()`) instead as a task (i.e. `workflow.delay()`) then everything is ok.

I'm not sure this is a bug anymore, although it might make senes to make AsyncResult et. al (e.g. GropuResult) JSON serializable.
Thoughts @thedrow @auvipy ?

**Comment by xirdneh** [comment]
Also, @georgepsarakis's solution does work.
Since right now when an async result is serialized the format is to print return the id then the parent result. This is where the serialization breaks.
We can fix it by returning `self.parent.as_tuple()` instead of `self.parent`.
And now that I think about it it is an update that we need since is the correct way to return async results as tuples.
I'll write the integration test for this.
