### ISSUE TITLE
Scheduler's closed the connection when PeriodicTask update and heart-beat both do in the same time

### ISSUE THREAD

**Issue by PoloPing** [celery/celery#4771]
## Checklist
 I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

run celery beat and update PeriodicTask at tasks

## Expected behavior

Reliable operation with no exceptions being thrown.

## Actual behavior

the error message always showed up when tasks update PeriodicTask, 

tasks off-time and on-time both update PeriodicTask.enabled

it's off-time task
```
p_task = PeriodicTask.filter(name=task_name).first()
p_task.enabled = False
p_task.save()
```

it's on-time task
```
p_task = PeriodicTask.filter(name=task_name).first()
p_task.enabled = True
p_task.save()
```

always happened in the situation
```
[2018-05-27 07:24:00,019: INFO/MainProcess] Scheduler: Sending due task on-time-acff3875-c593-4e3b-a0ea-3ad274b73944 (robot.tasks.robot_join_chat_room)
[2018-05-27 07:24:00,040: INFO/MainProcess] Scheduler: Sending due task off-time-8f8170b2-401f-447a-a86b-0c531c44c33e (robot.tasks.robot_leave_chat_room)
[2018-05-27 07:24:30,093: INFO/MainProcess] Writing entries...
[2018-05-27 07:24:30,115: INFO/MainProcess] DatabaseScheduler: Schedule changed.
[2018-05-27 07:24:30,116: INFO/MainProcess] Writing entries...
[2018-05-27 07:24:30,117: INFO/MainProcess] Writing entries...
[2018-05-27 07:24:30,131: CRITICAL/MainProcess] beat raised exception <class 'django.db.utils.InterfaceError'>: InterfaceError('connection already closed',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 109, in start_scheduler
    service.start()
  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 594, in start
    self.scheduler._do_sync()
  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 373, in _do_sync
    self.sync()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 243, in sync
    self.schedule[name].save()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 289, in schedule
    self.sync()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 243, in sync
    self.schedule[name].save()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 284, in schedule
    elif self.schedule_changed():
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 215, in schedule_changed
    last, ts = self._last_timestamp, self.Changes.last_change()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/models.py", line 226, in last_change
    return cls.objects.get(ident=1).last_update
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 882, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
[2018-05-27 07:24:30,139: WARNING/MainProcess] Traceback (most recent call last):
[2018-05-27 07:24:30,139: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in _cursor
[2018-05-27 07:24:30,140: WARNING/MainProcess] return self._prepare_cursor(self.create_cursor(name))
[2018-05-27 07:24:30,140: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
[2018-05-27 07:24:30,141: WARNING/MainProcess] cursor = self.connection.cursor()
[2018-05-27 07:24:30,141: WARNING/MainProcess] psycopg2
[2018-05-27 07:24:30,141: WARNING/MainProcess] .
[2018-05-27 07:24:30,141: WARNING/MainProcess] InterfaceError
[2018-05-27 07:24:30,142: WARNING/MainProcess] :
[2018-05-27 07:24:30,142: WARNING/MainProcess] connection already closed
[2018-05-27 07:24:30,142: WARNING/MainProcess] The above exception was the direct cause of the following exception:
[2018-05-27 07:24:30,142: WARNING/MainProcess] Traceback (most recent call last):
[2018-05-27 07:24:30,142: WARNING/MainProcess] File "/usr/local/bin/celery", line 11, in <module>
[2018-05-27 07:24:30,143: WARNING/MainProcess] sys.exit(main())
[2018-05-27 07:24:30,149: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
[2018-05-27 07:24:30,149: WARNING/MainProcess] _main()
[2018-05-27 07:24:30,149: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
[2018-05-27 07:24:30,150: WARNING/MainProcess] cmd.execute_from_commandline(argv)
[2018-05-27 07:24:30,150: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline
[2018-05-27 07:24:30,151: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
[2018-05-27 07:24:30,151: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
[2018-05-27 07:24:30,151: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
[2018-05-27 07:24:30,151: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 476, in handle_argv
[2018-05-27 07:24:30,152: WARNING/MainProcess] return self.execute(command, argv)
[2018-05-27 07:24:30,152: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 408, in execute
[2018-05-27 07:24:30,158: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2018-05-27 07:24:30,159: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 279, in run_from_argv
[2018-05-27 07:24:30,159: WARNING/MainProcess] sys.argv if argv is None else argv, command)
[2018-05-27 07:24:30,159: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 363, in handle_argv
[2018-05-27 07:24:30,160: WARNING/MainProcess] return self(*args, **options)
[2018-05-27 07:24:30,160: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
[2018-05-27 07:24:30,161: WARNING/MainProcess] ret = self.run(*args, **kwargs)
[2018-05-27 07:24:30,161: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
[2018-05-27 07:24:30,161: WARNING/MainProcess] return beat().run()
[2018-05-27 07:24:30,161: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 81, in run
[2018-05-27 07:24:30,162: WARNING/MainProcess] self.start_scheduler()
[2018-05-27 07:24:30,162: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 109, in start_scheduler
[2018-05-27 07:24:30,162: WARNING/MainProcess] service.start()
[2018-05-27 07:24:30,168: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 594, in start
[2018-05-27 07:24:30,169: WARNING/MainProcess] self.scheduler._do_sync()
[2018-05-27 07:24:30,169: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 373, in _do_sync
[2018-05-27 07:24:30,170: WARNING/MainProcess] self.sync()
[2018-05-27 07:24:30,170: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 243, in sync
[2018-05-27 07:24:30,170: WARNING/MainProcess] self.schedule[name].save()
[2018-05-27 07:24:30,170: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 289, in schedule
[2018-05-27 07:24:30,171: WARNING/MainProcess] self.sync()
[2018-05-27 07:24:30,171: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 243, in sync
[2018-05-27 07:24:30,171: WARNING/MainProcess] self.schedule[name].save()
[2018-05-27 07:24:30,172: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 284, in schedule
[2018-05-27 07:24:30,172: WARNING/MainProcess] elif self.schedule_changed():
[2018-05-27 07:24:30,178: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 215, in schedule_changed
[2018-05-27 07:24:30,179: WARNING/MainProcess] last, ts = self._last_timestamp, self.Changes.last_change()
[2018-05-27 07:24:30,179: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django_celery_beat/models.py", line 226, in last_change
[2018-05-27 07:24:30,179: WARNING/MainProcess] return cls.objects.get(ident=1).last_update
[2018-05-27 07:24:30,179: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
[2018-05-27 07:24:30,180: WARNING/MainProcess] return getattr(self.get_queryset(), name)(*args, **kwargs)
[2018-05-27 07:24:30,180: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 374, in get
[2018-05-27 07:24:30,180: WARNING/MainProcess] num = len(clone)
[2018-05-27 07:24:30,181: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
[2018-05-27 07:24:30,181: WARNING/MainProcess] self._fetch_all()
[2018-05-27 07:24:30,181: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all
[2018-05-27 07:24:30,182: WARNING/MainProcess] self._result_cache = list(self._iterable_class(self))
[2018-05-27 07:24:30,188: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
[2018-05-27 07:24:30,188: WARNING/MainProcess] results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
[2018-05-27 07:24:30,188: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 882, in execute_sql
[2018-05-27 07:24:30,189: WARNING/MainProcess] cursor = self.connection.cursor()
[2018-05-27 07:24:30,189: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
[2018-05-27 07:24:30,190: WARNING/MainProcess] return self._cursor()
[2018-05-27 07:24:30,190: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in _cursor
[2018-05-27 07:24:30,190: WARNING/MainProcess] return self._prepare_cursor(self.create_cursor(name))
[2018-05-27 07:24:30,191: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
[2018-05-27 07:24:30,191: WARNING/MainProcess] six.reraise(dj_exc_type, dj_exc_value, traceback)
[2018-05-27 07:24:30,191: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
[2018-05-27 07:24:30,192: WARNING/MainProcess] raise value.with_traceback(tb)
[2018-05-27 07:24:30,198: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in _cursor
[2018-05-27 07:24:30,198: WARNING/MainProcess] return self._prepare_cursor(self.create_cursor(name))
[2018-05-27 07:24:30,199: WARNING/MainProcess] File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
[2018-05-27 07:24:30,199: WARNING/MainProcess] cursor = self.connection.cursor()
[2018-05-27 07:24:30,199: WARNING/MainProcess] django.db.utils
[2018-05-27 07:24:30,199: WARNING/MainProcess] .
[2018-05-27 07:24:30,199: WARNING/MainProcess] InterfaceError
[2018-05-27 07:24:30,200: WARNING/MainProcess] :
[2018-05-27 07:24:30,200: WARNING/MainProcess] connection already closed
```

speak-task dosen't operate model PeriodicTask
```
[2018-05-26 23:10:00,020: INFO/MainProcess] Scheduler: Sending due task off-time-c4bb3174-92cf-4af6-a1e4-b015dea3f025 (robot.tasks.robot_leave_chat_room)
[2018-05-26 23:10:00,042: INFO/MainProcess] Scheduler: Sending due task speak-4bbd8c22-6f13-4a55-b09b-c02b8dc2ed7b (robot.tasks.robot_predict)
[2018-05-26 23:10:00,073: INFO/MainProcess] Scheduler: Sending due task speak-acff3875-c593-4e3b-a0ea-3ad274b73944 (robot.tasks.robot_predict)
[2018-05-26 23:10:00,119: INFO/MainProcess] Scheduler: Sending due task speak-c4bb3174-92cf-4af6-a1e4-b015dea3f025 (robot.tasks.robot_predict)
[2018-05-26 23:10:00,129: INFO/MainProcess] Writing entries...
[2018-05-26 23:10:00,160: INFO/MainProcess] DatabaseScheduler: Schedule changed.
[2018-05-26 23:10:00,160: INFO/MainProcess] Writing entries...
[2018-05-26 23:10:00,178: ERROR/MainProcess] Message Error: connection already closed
['  File "/usr/local/bin/celery", line 11, in <module>\n    sys.exit(main())\n', '  File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main\n    _main()\n', '  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main\n    cmd.execute_from_commandline(argv)\n', '  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 476, in handle_argv\n    return self.execute(command, argv)\n', '  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 408, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 279, in run_from_argv\n    sys.argv if argv is None else argv, command)\n', '  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 363, in handle_argv\n    return self(*args, **options)\n', '  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/usr/local/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run\n    return beat().run()\n', '  File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 81, in run\n    self.start_scheduler()\n', '  File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 109, in start_scheduler\n    service.start()\n', '  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 588, in start\n    interval = self.scheduler.tick()\n', '  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 307, in tick\n    self.apply_entry(entry, producer=self.producer)\n', '  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 244, in apply_entry\n    exc, traceback.format_stack(), exc_info=True)\n']
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 241, in apply_entry
    result = self.apply_async(entry, producer=producer, advance=False)
  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 362, in apply_async
    self._do_sync()
  File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 373, in _do_sync
    self.sync()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 243, in sync
    self.schedule[name].save()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 289, in schedule
    self.sync()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 243, in sync
    self.schedule[name].save()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 284, in schedule
    elif self.schedule_changed():
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/schedulers.py", line 215, in schedule_changed
    last, ts = self._last_timestamp, self.Changes.last_change()
  File "/usr/local/lib/python3.6/site-packages/django_celery_beat/models.py", line 226, in last_change
    return cls.objects.get(ident=1).last_update
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 882, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

Output from "celery report":
```
software -> celery:4.2.0rc4 (windowlicker) kombu:4.2.0 py:3.6.2
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

also I found out the similar situation at issue #4542 

I consider the error happened due to the  race condition of DatabaseScheduler of sync function:
when the hear-beat and PeriodicTask update both do in the same time
```
    def sync(self):
        info('Writing entries...')
        _tried = set()
        try:
            close_old_connections()
            with transaction.atomic():
                while self._dirty:
                    try:
                        name = self._dirty.pop()
                        _tried.add(name)
                        self.schedule[name].save()
                    except (KeyError, ObjectDoesNotExist):
                        pass
        except DatabaseError as exc:
            # retry later
            self._dirty |= _tried
            logger.exception('Database error while sync: %r', exc)
```

close_old_connections()  ← that's why closed connection?

**Comment by juannyG** [comment]
Both this issue and https://github.com/celery/celery/issues/4542 seem to be rooted with `django-celery-beat` calling `close_old_connections` and not `celery` itself - that code doesn't exist in this repository. It might be more appropriate to close this issue and re-open it in https://github.com/celery/django-celery-beat/issues

Have you tried using the `master` branch of `django-celery-beat`? What version of it are you running?

**Comment by alon-unifi** [comment]
@PoloPing I'm having the exact same issue. Curious to know what you ended up doing to get around this. Thanks.
