### ISSUE TITLE
Upgrade to ampq 2.3.0, Kombu 4.2.0 and Celery 4.1.1 getting UnicodeDecodeError on task executions

### ISSUE THREAD

**Issue by marcinkuzminski** [celery/celery#4774]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Executing a task with 4.1.0 worked ok, now getting constant errors

## Actual behavior

Traceback:

CRITI [celery.worker] Unrecoverable error: UnicodeDecodeError('ascii', '\x00\x00\x00\x8d\x0fproduct_versionS\x00\x00\x00\x052.3.0\x07productS\x00\x00\x00\x07py-amqp\x0ccapabilitiesF\x00\x00\x00M\x1cauthentication_failure_closet\x01\x16consumer_cancel_notifyt\x01\x12connection.blockedt\x01\x08AMQPLAIN\x00\x00\x00%\x05LOGINS\x00\x00\x00\x06rcuser\x08PASSWORDS\x00\x00\x00\x06qweqwe\x05en_US', 3, 4, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/nix/store/ipwln1pkqkbfyl1d0x647n6nhvig3r6w-python2.7-celery-4.1.1/lib/python2.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/nix/store/ipwln1pkqkbfyl1d0x647n6nhvig3r6w-python2.7-celery-4.1.1/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/nix/store/ipwln1pkqkbfyl1d0x647n6nhvig3r6w-python2.7-celery-4.1.1/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/nix/store/ipwln1pkqkbfyl1d0x647n6nhvig3r6w-python2.7-celery-4.1.1/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 316, in start
    blueprint.start(self)
  File "/nix/store/ipwln1pkqkbfyl1d0x647n6nhvig3r6w-python2.7-celery-4.1.1/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/nix/store/ipwln1pkqkbfyl1d0x647n6nhvig3r6w-python2.7-celery-4.1.1/lib/python2.7/site-packages/celery/worker/consumer/connection.py", line 23, in start
    c.connection = c.connect()
  File "/nix/store/ipwln1pkqkbfyl1d0x647n6nhvig3r6w-python2.7-celery-4.1.1/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 403, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/nix/store/ipwln1pkqkbfyl1d0x647n6nhvig3r6w-python2.7-celery-4.1.1/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 410, in connection_for_read
    self.app.connection_for_read(heartbeat=heartbeat))
  File "/nix/store/ipwln1pkqkbfyl1d0x647n6nhvig3r6w-python2.7-celery-4.1.1/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 434, in ensure_connected
    callback=maybe_shutdown,
  File "/nix/store/9szv88csfmg1shwb8kh46sz5bmnmwv89-python2.7-kombu-4.2.0/lib/python2.7/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/nix/store/9szv88csfmg1shwb8kh46sz5bmnmwv89-python2.7-kombu-4.2.0/lib/python2.7/site-packages/kombu/utils/functional.py", line 332, in retry_over_time
    return fun(*args, **kwargs)
  File "/nix/store/9szv88csfmg1shwb8kh46sz5bmnmwv89-python2.7-kombu-4.2.0/lib/python2.7/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/nix/store/9szv88csfmg1shwb8kh46sz5bmnmwv89-python2.7-kombu-4.2.0/lib/python2.7/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/nix/store/9szv88csfmg1shwb8kh46sz5bmnmwv89-python2.7-kombu-4.2.0/lib/python2.7/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/nix/store/9szv88csfmg1shwb8kh46sz5bmnmwv89-python2.7-kombu-4.2.0/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/connection.py", line 308, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/connection.py", line 393, in _on_start
    login_response, self.locale),
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/method_framing.py", line 102, in write_frame
    args = str_to_bytes(args)
  File "/nix/store/02syii140x223czy9indssri6qs0s4yl-python2.7-amqp-2.3.0/lib/python2.7/site-packages/amqp/utils.py", line 91, in str_to_bytes
    return s.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 3: ordinal not in range(128

Can i help to debug this ?

**Comment by jacquerie** [comment]
Check out https://github.com/celery/py-amqp/issues/191, apparently they just released a 2.3.1 that should have fixed this issue.

**Comment by marcinkuzminski** [comment]
Confirmed that upgrading amqp to 2.3.1 fixes the problem
