### ISSUE TITLE
Connection reset when adding consumer in gevent worker pool

### ISSUE THREAD

**Issue by kyrelos** [celery/celery#4775]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

Celery versions affected: 4.2.0rc4, 4.2.0rc2
Last working version: 4.1.1

## Steps to reproduce
1. Start up a worker with gevent pool
2. send celery control cancel_consumer remote comand
3. Send celery control add_consumer remote command
## Expected behavior
Cancel consumer should remove all the workers consuming from the given queue
Add consumer should add a specified consumer to the given queue

## Actual behavior
Cancel consumer removes the workers from the queue as expected
Add consumer throws the following exception and the worker dies
```
Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 866, in switch
worker_1                                    |     switch(value)
worker_1                                    |   File "/usr/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 120, in loop
worker_1                                    |     connection.drain_events(timeout=1.0)
worker_1                                    |   File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 301, in drain_events
worker_1                                    |     return self.transport.drain_events(self.connection, **kwargs)
worker_1                                    |   File "/usr/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
worker_1                                    |     return connection.drain_events(**kwargs)
worker_1                                    |   File "/usr/local/lib/python2.7/site-packages/amqp/connection.py", line 491, in drain_events
worker_1                                    |     while not self.blocking_read(timeout):
worker_1                                    |   File "/usr/local/lib/python2.7/site-packages/amqp/connection.py", line 496, in blocking_read
worker_1                                    |     frame = self.transport.read_frame()
worker_1                                    |   File "/usr/local/lib/python2.7/site-packages/amqp/transport.py", line 243, in read_frame
worker_1                                    |     frame_header = read(7, True)
worker_1                                    |   File "/usr/local/lib/python2.7/site-packages/amqp/transport.py", line 418, in _read
worker_1                                    |     s = recv(n - len(rbuf))
worker_1                                    |   File "/usr/local/lib/python2.7/site-packages/gevent/_socket2.py", line 277, in recv
worker_1                                    |     return sock.recv(*args)
worker_1                                    | error: [Errno 104] Connection reset by peer
worker_1                                    | Mon May 28 19:40:01 2018 <built-in method switch of greenlet.greenlet object at 0x7f5b24653c30> failed with error
```

**Comment by auvipy** [comment]
whats the status with new versions?

**Comment by djlambert** [comment]
This looks like it might be a duplicate of #4817.

**Comment by frost-nzcr4** [comment]
FYI 4.3.0 still has it, but 4.4.0rc4 works fine

**Comment by auvipy** [comment]
thanks
