### ISSUE TITLE
ImportError: cannot import name 'GreenletExit'

### ISSUE THREAD

**Issue by bmjjr** [celery/celery#4780]
## Checklist

- [x ] I have included the output of ``celery -A proj report`` in the issue.
      
    ```
    software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.5
            billiard:3.5.0.3 redis:2.10.6
    platform -> system:Windows arch:64bit, WindowsPE imp:CPython
    loader   -> celery.loaders.app.AppLoader
    settings -> transport:redis results:redis://localhost:6379/0
    broker_url: 'redis://127.0.0.1:6379//'
    result_backend: 'redis://localhost:6379/0'
    include: ['base.tasks']
    ```
- [ x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
`celery -A base.celery worker -P gevent`
## Expected behavior
runs
## Actual behavior
```
 File "c:\programdata\miniconda3\envs\myenv\lib\site-packages\celery\concurrency\gevent.py", line 34, in __init__
    from gevent.greenlet import Greenlet, GreenletExit
ImportError: cannot import name 'GreenletExit'
```
Changing Timer.__init__ from this:

```
class Timer(_timer.Timer):
    def __init__(self, *args, **kwargs):
        from gevent.greenlet import Greenlet, GreenletExit
```
...to this:

```
class Timer(_timer.Timer):
    def __init__(self, *args, **kwargs):
        from gevent.greenlet import Greenlet
        from greenlet import GreenletExit
```

...resolves the problem.  After changing the import then `celery -A base.celery worker -P gevent` runs like it should.

```
 -------------- celery@DESKTOP-7QUDBA4 v4.1.0 (latentcall)
---- **** -----
--- * ***  * -- Windows-10-10.0.17134-SP0 2018-05-29 22:02:10
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         base:0x205ee24df60
- ** ---------- .> transport:   redis://127.0.0.1:6379//
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 4 (gevent)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
```
I'm running gevent==1.3.2 and greenlet==0.4.13

**Comment by bmjjr** [comment]
Just test it against master and received a different import error `ImportError: cannot import name 'timer'`
Here is the full traceback:
```
Traceback (most recent call last):
  File "c:\programdata\miniconda3\envs\py\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\envs\py\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\envs\py\Scripts\celery.exe\__main__.py", line 9, in <module>
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\__main__.py", line 14, in main
    maybe_patch_concurrency()
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\__init__.py", line 146, in maybe_patch_concurrency
    concurrency.get_implementation(pool)
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\concurrency\__init__.py", line 23, in get_implementation
    return symbol_by_name(cls, ALIASES)
  File "c:\programdata\miniconda3\envs\py\kombu\utils\imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "c:\programdata\miniconda3\envs\py\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\concurrency\gevent.py", line 5, in <module>
    from kombu.asynchronous import timer as _timer
ImportError: cannot import name 'timer'
```

**Comment by bmjjr** [comment]
And  `celery -A base.celery worker` throws `ModuleNotFoundError: No module named 'kombu.asynchronous.timer'`.
```
Traceback (most recent call last):
  File "c:\programdata\miniconda3\envs\py\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\envs\py\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\envs\py\Scripts\celery.exe\__main__.py", line 9, in <module>
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\__main__.py", line 16, in main
    _main()
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\bin\celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\bin\celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\bin\base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\bin\celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\bin\celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\bin\worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\bin\base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\bin\worker.py", line 257, in run
    **kwargs)
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\worker\worker.py", line 101, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\worker\worker.py", line 132, in setup_instance
    self.pool_cls = _concurrency.get_implementation(self.pool_cls)
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\concurrency\__init__.py", line 23, in get_implementation
    return symbol_by_name(cls, ALIASES)
  File "c:\programdata\miniconda3\envs\py\kombu\utils\imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "c:\programdata\miniconda3\envs\py\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\concurrency\prefork.py", line 18, in <module>
    from celery.concurrency.base import BasePool
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\concurrency\base.py", line 15, in <module>
    from celery.utils import timer2
  File "c:\programdata\miniconda3\envs\py\lib\site-packages\celery\utils\timer2.py", line 16, in <module>
    from kombu.asynchronous.timer import Entry
ModuleNotFoundError: No module named 'kombu.asynchronous.timer'
```

**Comment by bmjjr** [comment]
And the second issue is a dupe of #4772.  I'll look at it a bit and see if I can get any clue what is going on.

**Comment by clokep** [comment]
Celery 4.1.0 is only compatible with kombu 4.1.0. Celery master (which will be 4.2.0) is only compatible with kombu 4.2.0, so you should just be able to update kombu.

**Comment by kedare** [comment]
Do you know in which version this should be pushed to PIP ?
