### ISSUE TITLE
In  4.1.1, using Redis Sentinel backend results in a ModuleNotFoundError

### ISSUE THREAD

**Issue by badloop** [celery/celery#4782]
## Celery Report
```
software -> celery:4.1.1 (latentcall) kombu:4.2.0 py:3.6.5
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:sentinel://127.0.0.1:26379/0

broker_url: 'amqp://guest:********@127.0.0.1:5672//'
result_backend: 'sentinel://127.0.0.1:26379/0'
```

` Redis version: redis==2.10.6`

## Steps to reproduce
Instantiate celery using a redis sentinel backend

## Expected behavior
Celery object is created

## Actual behavior
```
[2018-05-29 20:18:22,315: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'sentinel'",)
Traceback (most recent call last):
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/apps/worker.py", line 139, in on_start
    self.emit_banner()
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/apps/worker.py", line 154, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/apps/worker.py", line 217, in startup_info
    results=self.app.backend.as_uri(),
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/app/base.py", line 1174, in backend
    return self._get_backend()
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/app/base.py", line 892, in _get_backend
    self.loader)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/app/backends.py", line 68, in by_url
    return by_name(backend, loader), url
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/celery/app/backends.py", line 48, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/Users/aaron/IdeaProjects/sdn-conductor-worker/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sentinel'
```

**Comment by thedrow** [comment]
Can you provide a sample project for me?
I'll try to reproduce this.

**Comment by badloop** [comment]
The error is thrown on the instantiation of the Celery object.  You can use the below code to reproduce.  

```python
"""
Kailash Flow Intent Workflow
"""
from celery import Celery
from celery import group
import os
import logging

logging.basicConfig(level=logging.DEBUG)

# RabbitMQ Configuration
rabbitMQUser = os.environ.get('RABBIT_MQ_USER')
rabbitMQPass = os.environ.get('RABBIT_MQ_PASS')
rabbitMQBroker = os.environ.get('RABBIT_MQ_BROKER')
rabbitMQUrl = "amqp://" + rabbitMQUser + ":" + rabbitMQPass + "@" + rabbitMQBroker +"//"

# Redis Configuration
redisHost = os.environ.get('REDIS_HOST')
redisPass = os.environ.get('REDIS_PASS')
redisPort = os.environ.get('REDIS_PORT')
redisUrl = "sentinel://" + redisHost + ":" + redisPort + "/0"

app = Celery(broker=rabbitMQUrl, backend=redisUrl)
```

**Comment by auvipy** [comment]
as per https://github.com/celery/celery/pull/4144 sentinel support was added in celery 4.2, and this wasn't back ported, so this is likely not to work. closing as invalid

**Comment by thedrow** [comment]
The sentinel backend does not exist in 4.1.x.
Use the 4.2 RC or wait for GA.

**Comment by badloop** [comment]
Thanks for the clarification!
