### ISSUE TITLE
The worker hangs after one task reached the timelimit

### ISSUE THREAD

**Issue by kfrendrich** [celery/celery#4789]
## Versions
celery==4.1.1
billiard==3.5.0.3
kombu==4.2.1
redis==2.10.6

## Steps to reproduce
```
import time
from datetime import timedelta

from celery import Celery


class CeleryConfig():
    CELERY_BROKER_URL = "redis://localhost:6379/12"
    # CELERY_TASK_SERIALIZER = "json"
    # CELERY_RESULT_SERIALIZER = "json"
    # CELERY_ACCEPT_CONTENT = ["json"]
    # CELERY_ENABLE_UTC = True
    # CELERY_TIMEZONE = "UTC"
    CELERY_BEAT_SCHEDULE = {
        'run-first': {
            'task': 'test.first',
            'schedule': timedelta(seconds=10),
        },
        'run-second': {
            'task': 'test.second',
            'schedule': timedelta(seconds=3),
        },

    }


app = Celery('test')
app.config_from_object(CeleryConfig(), namespace='CELERY')


@app.task
def first():
    print("START: FIRST")
    time.sleep(20)
    print("END: FIRST")


@app.task
def second():
    print("START: SECOND")
    time.sleep(1)
    print("END: SECOND")


if __name__ == '__main__':
    app.start(argv=[
        'celery', 'worker',
        '-B',
        # '-E',
        # '-Ofair',
        '--concurrency', '1',
        # '--max-tasks-per-child', '20',
        '--time-limit', '10',
        '-l', 'DEBUG',
    ])
```
## Expected behavior
A new worker should start and continue the execution of tasks (?)

## Actual behavior
After the first task killed due to a reached TimeLimit, the worker stops working.

```
[2018-06-01 11:00:55,903: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2018-06-01 11:00:55,904: DEBUG/MainProcess] | Worker: Building graph...
[2018-06-01 11:00:55,904: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Timer, Hub, Pool, Autoscaler, Beat, Consumer}
[2018-06-01 11:00:55,916: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2018-06-01 11:00:55,917: DEBUG/MainProcess] | Consumer: Building graph...
[2018-06-01 11:00:55,928: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Mingle, Gossip, Tasks, Control, Heart, event loop}
 
 -------------- celery@EX-VIE-LT013 v4.1.1 (latentcall)
---- **** ----- 
--- * ***  * -- Linux-4.4.126-48-default-x86_64-with-SuSE-42.3-x86_64 2018-06-01 11:00:55
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         test:0x7faa78741080
- ** ---------- .> transport:   redis://localhost:6379/12
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . test.first
  . test.second

[2018-06-01 11:00:55,938: DEBUG/MainProcess] | Worker: Starting Hub
[2018-06-01 11:00:55,938: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:55,938: DEBUG/MainProcess] | Worker: Starting Pool
[2018-06-01 11:00:55,955: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:55,955: DEBUG/MainProcess] | Worker: Starting Beat
[2018-06-01 11:00:55,957: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:55,957: DEBUG/MainProcess] | Worker: Starting Consumer
[2018-06-01 11:00:55,957: DEBUG/MainProcess] | Consumer: Starting Connection
[2018-06-01 11:00:55,962: INFO/Beat] beat: Starting...
[2018-06-01 11:00:55,972: DEBUG/Beat] Current schedule:
<ScheduleEntry: run-first test.first() <freq: 10.00 seconds>
<ScheduleEntry: celery.backend_cleanup celery.backend_cleanup() <crontab: 0 4 * * * (m/h/d/dM/MY)>
<ScheduleEntry: run-second test.second() <freq: 3.00 seconds>
[2018-06-01 11:00:55,972: DEBUG/Beat] beat: Ticking with max interval->5.00 minutes
[2018-06-01 11:00:55,976: INFO/MainProcess] Connected to redis://localhost:6379/12
[2018-06-01 11:00:55,976: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:55,976: DEBUG/MainProcess] | Consumer: Starting Events
[2018-06-01 11:00:55,987: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:55,987: DEBUG/MainProcess] | Consumer: Starting Mingle
[2018-06-01 11:00:55,987: INFO/MainProcess] mingle: searching for neighbors
[2018-06-01 11:00:55,987: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:00:56,003: DEBUG/Beat] beat: Synchronizing schedule...
[2018-06-01 11:00:56,004: DEBUG/Beat] test.second sent. id->9cb5024d-51ec-49f3-a5a1-69bf45e7cba5
[2018-06-01 11:00:56,005: DEBUG/Beat] beat: Waking up in 2.96 seconds.
[2018-06-01 11:00:57,011: INFO/MainProcess] mingle: all alone
[2018-06-01 11:00:57,011: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:57,011: DEBUG/MainProcess] | Consumer: Starting Gossip
[2018-06-01 11:00:57,012: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:57,013: DEBUG/MainProcess] | Consumer: Starting Tasks
[2018-06-01 11:00:57,014: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:57,015: DEBUG/MainProcess] | Consumer: Starting Control
[2018-06-01 11:00:57,016: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:57,016: DEBUG/MainProcess] | Consumer: Starting Heart
[2018-06-01 11:00:57,016: DEBUG/MainProcess] ^-- substep ok
[2018-06-01 11:00:57,016: DEBUG/MainProcess] | Consumer: Starting event loop
[2018-06-01 11:00:57,017: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2018-06-01 11:00:57,017: INFO/MainProcess] celery@EX-VIE-LT013 ready.
[2018-06-01 11:00:57,017: DEBUG/MainProcess] basic.qos: prefetch_count->4
[2018-06-01 11:00:57,267: INFO/MainProcess] Received task: test.second[9cb5024d-51ec-49f3-a5a1-69bf45e7cba5]  
[2018-06-01 11:00:57,267: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7faa74000a60> (args:('test.second', '9cb5024d-51ec-49f3-a5a1-69bf45e7cba5', {'group': None, 'expires': None, 'origin': 'gen17271@EX-VIE-LT013', 'task': 'test.second', 'retries': 0, 'kwargsrepr': '{}', 'lang': 'py', 'timelimit': [None, None], 'correlation_id': '9cb5024d-51ec-49f3-a5a1-69bf45e7cba5', 'parent_id': None, 'delivery_info': {'exchange': '', 'priority': 0, 'routing_key': 'celery', 'redelivered': None}, 'id': '9cb5024d-51ec-49f3-a5a1-69bf45e7cba5', 'argsrepr': '()', 'eta': None, 'reply_to': '2ac933c3-99da-30fc-be34-9bb4e834b501', 'root_id': '9cb5024d-51ec-49f3-a5a1-69bf45e7cba5'}, b'[[], {}, {"errbacks": null, "chain": null, "chord": null, "callbacks": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-06-01 11:00:57,268: DEBUG/MainProcess] Task accepted: test.second[9cb5024d-51ec-49f3-a5a1-69bf45e7cba5] pid:17270
[2018-06-01 11:00:57,268: WARNING/ForkPoolWorker-2] START: SECOND
[2018-06-01 11:00:58,269: WARNING/ForkPoolWorker-2] END: SECOND
[2018-06-01 11:00:58,270: INFO/ForkPoolWorker-2] Task test.second[9cb5024d-51ec-49f3-a5a1-69bf45e7cba5] succeeded in 1.0018056349999824s: None
[2018-06-01 11:00:58,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:00:58,974: DEBUG/Beat] test.second sent. id->0a37ce47-7dec-4429-97f2-fd5f5e18d705
[2018-06-01 11:00:58,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:00:58,974: INFO/MainProcess] Received task: test.second[0a37ce47-7dec-4429-97f2-fd5f5e18d705]  
[2018-06-01 11:00:58,974: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7faa74000a60> (args:('test.second', '0a37ce47-7dec-4429-97f2-fd5f5e18d705', {'group': None, 'expires': None, 'origin': 'gen17271@EX-VIE-LT013', 'task': 'test.second', 'retries': 0, 'kwargsrepr': '{}', 'lang': 'py', 'timelimit': [None, None], 'correlation_id': '0a37ce47-7dec-4429-97f2-fd5f5e18d705', 'parent_id': None, 'delivery_info': {'exchange': '', 'priority': 0, 'routing_key': 'celery', 'redelivered': None}, 'id': '0a37ce47-7dec-4429-97f2-fd5f5e18d705', 'argsrepr': '()', 'eta': None, 'reply_to': '2ac933c3-99da-30fc-be34-9bb4e834b501', 'root_id': '0a37ce47-7dec-4429-97f2-fd5f5e18d705'}, b'[[], {}, {"errbacks": null, "chain": null, "chord": null, "callbacks": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-06-01 11:00:58,975: DEBUG/MainProcess] Task accepted: test.second[0a37ce47-7dec-4429-97f2-fd5f5e18d705] pid:17270
[2018-06-01 11:00:58,975: WARNING/ForkPoolWorker-2] START: SECOND
[2018-06-01 11:00:59,976: WARNING/ForkPoolWorker-2] END: SECOND
[2018-06-01 11:00:59,976: INFO/ForkPoolWorker-2] Task test.second[0a37ce47-7dec-4429-97f2-fd5f5e18d705] succeeded in 1.0014440340000874s: None
[2018-06-01 11:01:01,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:01,974: DEBUG/Beat] test.second sent. id->6f54b929-fc29-4444-9744-9662dd0db761
[2018-06-01 11:01:01,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:01,974: INFO/MainProcess] Received task: test.second[6f54b929-fc29-4444-9744-9662dd0db761]  
[2018-06-01 11:01:01,974: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7faa74000a60> (args:('test.second', '6f54b929-fc29-4444-9744-9662dd0db761', {'group': None, 'expires': None, 'origin': 'gen17271@EX-VIE-LT013', 'task': 'test.second', 'retries': 0, 'kwargsrepr': '{}', 'lang': 'py', 'timelimit': [None, None], 'correlation_id': '6f54b929-fc29-4444-9744-9662dd0db761', 'parent_id': None, 'delivery_info': {'exchange': '', 'priority': 0, 'routing_key': 'celery', 'redelivered': None}, 'id': '6f54b929-fc29-4444-9744-9662dd0db761', 'argsrepr': '()', 'eta': None, 'reply_to': '2ac933c3-99da-30fc-be34-9bb4e834b501', 'root_id': '6f54b929-fc29-4444-9744-9662dd0db761'}, b'[[], {}, {"errbacks": null, "chain": null, "chord": null, "callbacks": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-06-01 11:01:01,975: DEBUG/MainProcess] Task accepted: test.second[6f54b929-fc29-4444-9744-9662dd0db761] pid:17270
[2018-06-01 11:01:01,975: WARNING/ForkPoolWorker-2] START: SECOND
[2018-06-01 11:01:02,976: WARNING/ForkPoolWorker-2] END: SECOND
[2018-06-01 11:01:02,976: INFO/ForkPoolWorker-2] Task test.second[6f54b929-fc29-4444-9744-9662dd0db761] succeeded in 1.0015182059996732s: None
[2018-06-01 11:01:04,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:04,974: DEBUG/Beat] test.second sent. id->49a3368a-d950-4e7e-9ccf-63c83d68b063
[2018-06-01 11:01:04,974: INFO/Beat] Scheduler: Sending due task run-first (test.first)
[2018-06-01 11:01:04,974: INFO/MainProcess] Received task: test.second[49a3368a-d950-4e7e-9ccf-63c83d68b063]  
[2018-06-01 11:01:04,975: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7faa74000a60> (args:('test.second', '49a3368a-d950-4e7e-9ccf-63c83d68b063', {'group': None, 'expires': None, 'origin': 'gen17271@EX-VIE-LT013', 'task': 'test.second', 'retries': 0, 'kwargsrepr': '{}', 'lang': 'py', 'timelimit': [None, None], 'correlation_id': '49a3368a-d950-4e7e-9ccf-63c83d68b063', 'parent_id': None, 'delivery_info': {'exchange': '', 'priority': 0, 'routing_key': 'celery', 'redelivered': None}, 'id': '49a3368a-d950-4e7e-9ccf-63c83d68b063', 'argsrepr': '()', 'eta': None, 'reply_to': '2ac933c3-99da-30fc-be34-9bb4e834b501', 'root_id': '49a3368a-d950-4e7e-9ccf-63c83d68b063'}, b'[[], {}, {"errbacks": null, "chain": null, "chord": null, "callbacks": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-06-01 11:01:04,975: DEBUG/Beat] test.first sent. id->f0552b89-3232-448d-87a6-72fb359aeb22
[2018-06-01 11:01:04,975: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:04,975: INFO/MainProcess] Received task: test.first[f0552b89-3232-448d-87a6-72fb359aeb22]  
[2018-06-01 11:01:04,976: WARNING/ForkPoolWorker-2] START: SECOND
[2018-06-01 11:01:04,976: DEBUG/MainProcess] Task accepted: test.second[49a3368a-d950-4e7e-9ccf-63c83d68b063] pid:17270
[2018-06-01 11:01:05,977: WARNING/ForkPoolWorker-2] END: SECOND
[2018-06-01 11:01:05,977: INFO/ForkPoolWorker-2] Task test.second[49a3368a-d950-4e7e-9ccf-63c83d68b063] succeeded in 1.001497768000263s: None
[2018-06-01 11:01:05,978: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7faa74000a60> (args:('test.first', 'f0552b89-3232-448d-87a6-72fb359aeb22', {'group': None, 'expires': None, 'origin': 'gen17271@EX-VIE-LT013', 'task': 'test.first', 'retries': 0, 'kwargsrepr': '{}', 'lang': 'py', 'timelimit': [None, None], 'correlation_id': 'f0552b89-3232-448d-87a6-72fb359aeb22', 'parent_id': None, 'delivery_info': {'exchange': '', 'priority': 0, 'routing_key': 'celery', 'redelivered': None}, 'id': 'f0552b89-3232-448d-87a6-72fb359aeb22', 'argsrepr': '()', 'eta': None, 'reply_to': '2ac933c3-99da-30fc-be34-9bb4e834b501', 'root_id': 'f0552b89-3232-448d-87a6-72fb359aeb22'}, b'[[], {}, {"errbacks": null, "chain": null, "chord": null, "callbacks": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-06-01 11:01:05,978: DEBUG/MainProcess] Task accepted: test.first[f0552b89-3232-448d-87a6-72fb359aeb22] pid:17270
[2018-06-01 11:01:05,978: WARNING/ForkPoolWorker-2] START: FIRST
[2018-06-01 11:01:07,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:07,974: DEBUG/Beat] test.second sent. id->94730619-ee95-40ec-81de-90eaf4f6ef72
[2018-06-01 11:01:07,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:07,974: INFO/MainProcess] Received task: test.second[94730619-ee95-40ec-81de-90eaf4f6ef72]  
[2018-06-01 11:01:10,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:10,974: DEBUG/Beat] test.second sent. id->76fd4d8e-a29e-4be8-8bb4-3361d2c2f4f2
[2018-06-01 11:01:10,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:10,974: INFO/MainProcess] Received task: test.second[76fd4d8e-a29e-4be8-8bb4-3361d2c2f4f2]  
[2018-06-01 11:01:13,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:13,974: DEBUG/Beat] test.second sent. id->81ae8c61-ffc2-4c1e-bfe9-a62374df7ba9
[2018-06-01 11:01:13,974: DEBUG/Beat] beat: Waking up now.
[2018-06-01 11:01:13,974: INFO/MainProcess] Received task: test.second[81ae8c61-ffc2-4c1e-bfe9-a62374df7ba9]  
[2018-06-01 11:01:14,974: INFO/Beat] Scheduler: Sending due task run-first (test.first)
[2018-06-01 11:01:14,975: DEBUG/Beat] test.first sent. id->75a55889-dee0-4639-b314-703fda4551b6
[2018-06-01 11:01:14,975: DEBUG/Beat] beat: Waking up in 1.99 seconds.
[2018-06-01 11:01:14,976: INFO/MainProcess] Received task: test.first[75a55889-dee0-4639-b314-703fda4551b6]  
[2018-06-01 11:01:15,980: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(10.0,)
Traceback (most recent call last):
  File "/home/kfrendrich/codes/virtualenv/python3.5/lib/python3.5/site-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(10.0,)
[2018-06-01 11:01:15,980: ERROR/MainProcess] Hard time limit (10.0s) exceeded for test.first[f0552b89-3232-448d-87a6-72fb359aeb22]
[2018-06-01 11:01:16,082: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:17270 exited with 'signal 9 (SIGKILL)'
[2018-06-01 11:01:16,123: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7faa74000a60> (args:('test.second', '94730619-ee95-40ec-81de-90eaf4f6ef72', {'group': None, 'expires': None, 'origin': 'gen17271@EX-VIE-LT013', 'task': 'test.second', 'retries': 0, 'kwargsrepr': '{}', 'lang': 'py', 'timelimit': [None, None], 'correlation_id': '94730619-ee95-40ec-81de-90eaf4f6ef72', 'parent_id': None, 'delivery_info': {'exchange': '', 'priority': 0, 'routing_key': 'celery', 'redelivered': None}, 'id': '94730619-ee95-40ec-81de-90eaf4f6ef72', 'argsrepr': '()', 'eta': None, 'reply_to': '2ac933c3-99da-30fc-be34-9bb4e834b501', 'root_id': '94730619-ee95-40ec-81de-90eaf4f6ef72'}, b'[[], {}, {"errbacks": null, "chain": null, "chord": null, "callbacks": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-06-01 11:01:16,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:16,974: DEBUG/Beat] test.second sent. id->71ce3e6a-0bde-4e3f-a3a6-6ffe8a196bda
[2018-06-01 11:01:16,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:19,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:19,974: DEBUG/Beat] test.second sent. id->c178b3de-0f39-452f-a6c9-8a2013147189
[2018-06-01 11:01:19,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:22,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:22,974: DEBUG/Beat] test.second sent. id->d742e931-3521-45d9-80bb-9f5d635d10a0
[2018-06-01 11:01:22,974: DEBUG/Beat] beat: Waking up in 1.99 seconds.
[2018-06-01 11:01:24,974: INFO/Beat] Scheduler: Sending due task run-first (test.first)
[2018-06-01 11:01:24,975: DEBUG/Beat] test.first sent. id->c9b56782-ec2e-486a-b0c9-7b25d372b4da
[2018-06-01 11:01:24,975: DEBUG/Beat] beat: Waking up now.
[2018-06-01 11:01:25,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:25,974: DEBUG/Beat] test.second sent. id->b2544426-4aa6-4feb-a789-09facc6e568b
[2018-06-01 11:01:25,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:28,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:28,974: DEBUG/Beat] test.second sent. id->84a632d4-febe-4901-b24a-39caf710fe37
[2018-06-01 11:01:28,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:31,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:31,974: DEBUG/Beat] test.second sent. id->6ffbec38-e7cc-4955-b37a-f2d6371a76c2
[2018-06-01 11:01:31,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:34,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:34,974: DEBUG/Beat] test.second sent. id->0bede6dc-9579-4fa0-a2a2-56fff54f3cfe
[2018-06-01 11:01:34,974: INFO/Beat] Scheduler: Sending due task run-first (test.first)
[2018-06-01 11:01:34,975: DEBUG/Beat] test.first sent. id->d6d0b51e-ba9b-4247-981f-2358911ee09a
[2018-06-01 11:01:34,975: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:37,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:37,974: DEBUG/Beat] test.second sent. id->d5cbaa56-c2c4-4b61-8141-30427c343f62
[2018-06-01 11:01:37,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:40,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:40,974: DEBUG/Beat] test.second sent. id->4b8e8b81-513e-4710-9811-e428c341f90d
[2018-06-01 11:01:40,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:43,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:43,974: DEBUG/Beat] test.second sent. id->7fb6658d-dab3-4e8e-a826-0deee0f955f2
[2018-06-01 11:01:43,974: DEBUG/Beat] beat: Waking up now.
[2018-06-01 11:01:44,974: INFO/Beat] Scheduler: Sending due task run-first (test.first)
[2018-06-01 11:01:44,975: DEBUG/Beat] test.first sent. id->a0ae6d18-03d9-4f18-a3c0-a09b59985062
[2018-06-01 11:01:44,975: DEBUG/Beat] beat: Waking up in 1.99 seconds.
[2018-06-01 11:01:46,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:46,974: DEBUG/Beat] test.second sent. id->6754311c-be12-4ab6-bce1-ff24500986aa
[2018-06-01 11:01:46,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:49,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:49,974: DEBUG/Beat] test.second sent. id->f44035fe-bebf-4033-a11a-0578e53531bc
[2018-06-01 11:01:49,974: DEBUG/Beat] beat: Waking up in 2.99 seconds.
[2018-06-01 11:01:52,973: INFO/Beat] Scheduler: Sending due task run-second (test.second)
[2018-06-01 11:01:52,974: DEBUG/Beat] test.second sent. id->05ad94a6-cd22-46c9-b8d6-3b2ab085aa1b
[2018-06-01 11:01:52,974: DEBUG/Beat] beat: Waking up in 1.99 seconds.
[2018-06-01 11:01:54,974: INFO/Beat] Scheduler: Sending due task run-first (test.first)
[2018-06-01 11:01:54,975: DEBUG/Beat] test.first sent. id->a57d895b-1641-4bee-9dc3-e3a3e19b168b
[2018-06-01 11:01:54,975: DEBUG/Beat] beat: Waking up now.
```

**Comment by kfrendrich** [comment]
The same thing happens if I send a sigkill for one of the workers.

I checked it with strace and it is hanging with a read operation:
```
Process 20770 attached
read(6, 
```

```
/proc/20770/fd/6 -> pipe:[1772812]
```

**Comment by kfrendrich** [comment]
I debugged the problem and here is some information:
In the `kombu/asynchronous/hub.py`:
```
    def create_loop(self,
        ....
                    else:
                        try:
                            cb(*cbargs)      <=  it start the hanging here
                        except Empty:
                            pass
```

and in the `redis-py/redis/_compat.py` file there is the:
```
    def recv_into(sock, *args, **kwargs):
        return sock.recv_into(*args, **kwargs)
```
Somehow it tries to read a closed socket and hangs forever.

If I write this **hack** manually:
```
    def recv_into(sock, *args, **kwargs):
        sock.settimeout(10)
        return sock.recv_into(*args, **kwargs)
```
it raises a timeout exception and creates a new socket and works.

**Comment by SharUpOff** [comment]
I've gotten the similar behaviour. When any task exceeds the hard time limit, the worker is being killed (SIGKILL). And no more tasks are processed after that. Also flower shows that worker is offline. Have no idea for now how to fix that. I temporarily use `task_soft_time_limit` that works fine because it does not kill worker.

# Log
```python
2018-11-21 13:56:54,683 ERROR Task handler raised error: TimeLimitExceeded(60,)
Traceback (most recent call last):
  File "/home/sharupoff/projects/mobile/api/env/lib/python2.7/site-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(60,)
2018-11-21 13:56:54,683 ERROR Hard time limit (60s) exceeded for core.tasks.write_log[d62435e0-0286-41b9-86d1-6749222c814c]
2018-11-21 13:56:54,784 ERROR Process 'ForkPoolWorker-13' pid:19336 exited with 'signal 9 (SIGKILL)'
```
# Code
```python
@shared_task
def write_log(name, level, msg, *args, **kwargs):
    logging.getLogger(name).log(level, msg, *args, **kwargs)
    from time import sleep
    sleep(300)
```
# Config
```python
CELERY_BROKER_URL = 'redis://localhost:6379/3'
CELERY_WORKER_CONCURRENCY = 20
CELERY_TASK_TIME_LIMIT = 60
CELERY_TASK_IGNORE_RESULT = True
CELERY_ACCEPT_CONTENT = ['msgpack']
CELERY_TASK_SERIALIZER = 'msgpack'
CELERY_RESULT_SERIALIZER = 'msgpack'
CELERY_EVENT_SERIALIZER = 'msgpack'
```
# Versions
```ini
celery==4.2.1
kombu==4.2.1
billiard==3.5.0.4
Django==1.11
redis==2.10.6
hiredis==0.2.0
```

**Comment by auvipy** [comment]
another this is install all the dependencies of celery from github master branch along with celery itself and check

**Comment by SharUpOff** [comment]
> could you drop hiredis and see? there is bug in celery using hiredis

I've checked. It really works without hiredis installed in my virtualenv. A worker is killed after the hard time limit, but a new instance accepts new tasks. Also flower shows that worker is still online.

```bash
(env) $ pip freeze | grep -c hiredis
1
(env) $ pip uninstall hiredis
Uninstalling hiredis-0.2.0:
  Would remove:
    /home/sharupoff/projects/mobile/api/env/lib/python2.7/site-packages/hiredis-0.2.0.dist-info/*
    /home/sharupoff/projects/mobile/api/env/lib/python2.7/site-packages/hiredis/*
Proceed (y/n)? Y
  Successfully uninstalled hiredis-0.2.0
(env) $ pip freeze | grep -c hiredis
0
```

```python
2018-11-23 14:12:30,029 ERROR Task handler raised error: TimeLimitExceeded(60,)
Traceback (most recent call last):
  File "/home/sharupoff/projects/mobile/api/env/lib/python2.7/site-packages/billiard/pool.py", line 658, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(60,)
2018-11-23 14:12:30,029 ERROR Hard time limit (60s) exceeded for core.tasks.write_log[e174d820-77ca-4d0b-870b-9979eca7ff43]
2018-11-23 14:12:30,135 ERROR Process 'ForkPoolWorker-16' pid:6478 exited with 'signal 9 (SIGKILL)'
```

> another this is install all the dependencies of celery from github master branch along with celery itself and check

I'll check this case too.
