### ISSUE TITLE
Unable to Connect to Azure Hosted Redis Broker via SSL/TLS Port 6380

### ISSUE THREAD

**Issue by ddavtian** [celery/celery#4792]
**Summary**

Maybe someone can shine some light on this. I am having a hard time connecting to an `Azure hosted Redis Cache on SSL/TLS port 6380`

`celery  4.1.1`

When trying to use a local version of Redis as a broker things are working fine. Locally we are not using an SSL connection. When trying to use an Azure hosted Redis cache on the default none TLS port `6379` things are working ok, but when trying to connect to the `SSL/TLS `enabled port which is `6380` on Azure, celery hangs and doesn't connect and eventually throws a socket error connection.

I am able to connect locally using `stunnel` and `redis-cli ` to the remote Azure hosted Redis server just fine on SSL/TLS and also using redis-py works fine without the need for the stunnel.

**Celery Config**

```
host='xxx-int-va7-xxxxxxx.redis.cache.windows.net'
passwword='xxxxxxxxxxxxxxxxxxxxxxxpkOOdeFdSRWOBeVU='
port='6380'

broker_use_ssl=True

broker_url = 'redis://:{pw}@{h}:{p}/0'.format(pw=passwword, h=host, p=port)
```

**Output**

```
-------------- celery@daxxxx-mac v4.1.1 (latentcall)
---- **** ----- 
--- * ***  * -- Darwin-17.5.0-x86_64-i386-64bit 2018-06-02 12:14:59
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         octo-engine-worker:0x10910f518
- ** ---------- .> transport:   redis://:**@xxx-int-va7-xxxxxxx.redis.cache.windows.net:6380/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . octo.tasks.monitor.job_status.JobStatus
  . octo.tasks.processor.arm_deployer.ArmProcessor
  . octo.tasks.processor.scale_sets.SsProcessor
  . octo.tasks.processor.service_principals.SpProcessor
  . octo.tasks.recurring.check_sub_quota.CheckSubscriptionQuota
  . octo.tasks.scheduler.job_scheduler.JobScheduler

[2018-06-02 12:14:59,277: DEBUG/MainProcess] | Worker: Starting Hub
[2018-06-02 12:14:59,277: DEBUG/MainProcess] ^-- substep ok
[2018-06-02 12:14:59,277: DEBUG/MainProcess] | Worker: Starting Pool
[2018-06-02 12:14:59,717: DEBUG/MainProcess] ^-- substep ok
[2018-06-02 12:14:59,718: DEBUG/MainProcess] | Worker: Starting Consumer
[2018-06-02 12:14:59,719: DEBUG/MainProcess] | Consumer: Starting Connection
```

**Error**

```
[2018-06-02 12:18:15,223: ERROR/MainProcess] consumer: Cannot connect to rredis://:**@xxx-int-va7-xxxxxxx.redis.cache.windows.net:6380/0: Error while reading from socket: (54, 'Connection reset by peer').
Trying again in 2.00 seconds...
```

**Comment by georgepsarakis** [comment]
I think there is an open issue in Kombu https://github.com/celery/kombu/issues/862 for SSL connection to Redis. Did you try enabling the [broker_use_ssl](http://docs.celeryproject.org/en/latest/userguide/configuration.html?highlight=ssl#std:setting-broker_use_ssl) option?

**Comment by ddavtian** [comment]
@georgepsarakis Yes, I did enable `broker_use_ssl=True` in the config. I updated my post to include that. The referenced ticket talks about `rediss://`. It's a schema difference as far as I understand it.

**Comment by ddavtian** [comment]
Just adding a bit more to this for reference. If I also enable `redis_backend_use_ssl=True` with the following config I get an exception thrown.

`result_backend = 'redis://:{pw}@{h}:{p}/0'.format(pw=passwword, h=host, p=port)`

**Packages**

```
redis  2.10.6
kombu  4.2.1
```

**Traceback**

```
Traceback (most recent call last):
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/celery/apps/worker.py", line 139, in on_start
    self.emit_banner()
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/celery/apps/worker.py", line 154, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/celery/apps/worker.py", line 217, in startup_info
    results=self.app.backend.as_uri(),
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/celery/app/base.py", line 1174, in backend
    return self._get_backend()
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/celery/app/base.py", line 893, in _get_backend
    return backend(app=self, url=url)
  File "/Users/davtian/Code/.virtualenvs/octo-engine-BidugOwt/lib/python3.6/site-packages/celery/backends/redis.py", line 140, in __init__
    self.connparams.update(ssl)
TypeError: 'bool' object is not iterable
[2018-06-02 13:43:35,673: INFO/MainProcess] Octo Engine shut down

Process finished with exit code 1
```

**Comment by georgepsarakis** [comment]
Perhaps it is not clear from the documentation, but the configuration parameter should actually be a [dictionary](https://github.com/celery/celery/blob/master/celery/backends/redis.py#L191). Could you try passing an empty dictionary: `redis_backend_use_ssl={}`? I think that this will work.

**Comment by ddavtian** [comment]
Hello @georgepsarakis, thank you for your reply.

I tried using an empty dictionary instead but it didn't connect either `redis_backend_use_ssl={}` 

```
redis_backend_use_ssl={}

## Broker settings.
broker_url = 'redis://:{password}@{host}:{port}/0'.format(
    password=quote(EnvironmentConfig.REDIS_PASSWORD, safe=''),
    host=EnvironmentConfig.REDIS_URL,
    port=EnvironmentConfig.REDIS_PORT)
```

```
[2018-06-08 12:29:09,834: DEBUG/MainProcess] | Worker: Starting Hub
[2018-06-08 12:29:09,834: DEBUG/MainProcess] ^-- substep ok
[2018-06-08 12:29:09,834: DEBUG/MainProcess] | Worker: Starting Pool
[2018-06-08 12:29:10,234: DEBUG/MainProcess] ^-- substep ok
[2018-06-08 12:29:10,235: DEBUG/MainProcess] | Worker: Starting Consumer
[2018-06-08 12:29:10,235: DEBUG/MainProcess] | Consumer: Starting Connection
[2018-06-08 12:30:37,080: ERROR/MainProcess] consumer: Cannot connect to redis://:**@xxxx-int-va7-xxxxxgea2xky.redis.cache.windows.net:6380/0: Error while reading from socket: (54, 'Connection reset by peer').
Trying again in 2.00 seconds...
```

**Comment by ddavtian** [comment]
@georgepsarakis a friend on the team mentioned that it needs to be set as follow and it works.

`broker_use_ssl={'ssl_cert_reqs': ssl.CERT_NONE}`

```
redis

The setting must be a dict the keys:

    ssl_cert_reqs (required): one of the SSLContext.verify_mode values:
            ssl.CERT_NONE
            ssl.CERT_OPTIONAL
            ssl.CERT_REQUIRED
```

**Comment by georgepsarakis** [comment]
@ddavtian great, thanks for sharing the solution! Do you think we should update the documentation perhaps?

**Comment by ddavtian** [comment]
@gabrielpjordao 👍 , it's extremely confusing :-)

**Comment by georgepsarakis** [comment]
@ddavtian I opened a separate issue to track this. In case you would like to contribute the documentation update, please feel free to do so. Thanks again!

**Comment by ddavtian** [comment]
@georgepsarakis for sure I will contribute. thank you!

**Comment by nmakarun** [comment]
Hello ddavtian, georgepsarakis,

Could you please help me with this issue,  consumer: Cannot connect to redis: Error while reading from socket: (104, 'Connection reset by peer'),

My redis connection string looks as below,

broker_url = redis://:password@hostname:port/0 

broker_use_ssl={'ssl_cert_reqs': ssl.CERT_NONE}.

I have no issues when I am using a rabbitmq backend.
