### ISSUE TITLE
ensure_bytes  causing "TypeError: Object of type 'bytes' is not JSON serializable" with Couchdb results backend

### ISSUE THREAD

**Issue by ghedb** [celery/celery#4798]
celery 4.1.0
pycouchdb 1.14

## Steps to Reproduce

Using couchdb as results_backend, run any task.

## 

celery converts the task_id to bytes, which breaks the json encoder in pychouchdb.

```python
ERROR/MainProcess] Pool callback raised exception: TypeError("Object of type 'bytes' is not JSON serializable",)
Traceback (most recent call last):
  File "python3.6/site-packages/billiard/pool.py", line 1747, in safe_apply_callback
    fun(*args, **kwargs)
  File "python3.6/site-packages/celery/worker/request.py", line 366, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "python3.6/site-packages/celery/backends/base.py", line 163, in mark_as_failure
    traceback=traceback, request=request)
  File "python3.6/site-packages/celery/backends/base.py", line 309, in store_result
    request=request, **kwargs)
  File "python3.6/site-packages/celery/backends/base.py", line 652, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "python3.6/site-packages/celery/backends/couchdb.py", line 87, in set
    self.connection.save(data)
  File "python3.6/site-packages/pycouchdb/client.py", line 378, in save
    data = utils.force_bytes(utils.to_json(_doc))
  File "python3.6/site-packages/pycouchdb/utils.py", line 101, in to_json
    return json.dumps(doc)
  File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

```python
    def _store_result(self, task_id, result, state,
                      traceback=None, request=None, **kwargs):
        meta = {
            'status': state, 'result': result, 'traceback': traceback,
            'children': self.current_task_children(request),
            'task_id': bytes_to_str(task_id),
        }
        self.set(self.get_key_for_task(task_id), self.encode(meta))
        return result
```
in base.py in meta the task_id is converted to string with bytes_to_Str, but not the key that is used in self.set by calling get_key_for_task

```python    
    def get_key_for_task(self, task_id, key=''):
        """Get the cache key for a task by id."""
        key_t = self.key_t
        return key_t('').join([
            self.task_keyprefix, key_t(task_id), key_t(key),
        ])
```
and self.key_t is set to ensure_bytes

**Comment by ghedb** [comment]
Overriding the task_id to be a str in self.set() works to store the results in couchdb, but it causes another problem for the unlock task in a celery chord.

```python
Task celery.chord_unlock[<UUID>] retry: Retry in 1s: TypeError("a bytes-like object is required, not 'str'",)
```

**Comment by ghedb** [comment]
Looks like this was actually fixed in https://github.com/celery/celery/pull/4166

**Comment by ghedb** [comment]
works in 4.2.0

**Comment by ghedb** [comment]
I just realized that now its not possible to get the results of any task once stored. Looks to be a similar issue but instead of set() its now get()


```python File "<console>", line 1, in <module>
  File "/lib/python3.6/site-packages/celery/result.py", line 224, in get
    on_message=on_message,
  File "/lib/python3.6/site-packages/celery/backends/base.py", line 470, in wait_for_pending
    no_ack=no_ack,
  File "/lib/python3.6/site-packages/celery/backends/base.py", line 493, in wait_for
    meta = self.get_task_meta(task_id)
  File "/lib/python3.6/site-packages/celery/backends/base.py", line 359, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/lib/python3.6/site-packages/celery/backends/base.py", line 671, in _get_task_meta_for
    meta = self.get(self.get_key_for_task(task_id))
  File "/lib/python3.6/site-packages/celery/backends/couchdb.py", line 85, in get
    return self.connection.get(key)['value']
  File "/lib/python3.6/site-packages/pycouchdb/client.py", line 352, in get
    (resp, result) = self.resource(*_id_to_path(doc_id)).get(params=params)
  File "/lib/python3.6/site-packages/pycouchdb/resource.py", line 51, in __call__
    base_url = utils.urljoin(self.base_url, *path)
  File "/lib/python3.6/site-packages/pycouchdb/utils.py", line 89, in urljoin
    return reduce(_join, path, base)
  File "/lib/python3.6/site-packages/pycouchdb/utils.py", line 56, in _join
    parts = [head.rstrip(URLSPLITTER), tail.lstrip(URLSPLITTER)]
```

**Comment by ghedb** [comment]
Opening a new issue for the get issue
