### ISSUE TITLE
chain fails on link_error fork

### ISSUE THREAD

**Issue by doka-ua** [celery/celery#4800]
Hi colleagues,

I'm newbie to Celery and described below can be either bug or my misunderstanding. Please, clarify.

celery -A tasks report

software -> celery:4.1.1 (latentcall) kombu:4.2.1 py:3.6.4
            billiard:3.5.0.3 py-amqp:2.3.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:rpc:///

broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'rpc:///'

## Steps to reproduce

```
# --- tasks.py ---
@app.task
def mydiv(x, y):
    return int(x/y)

@app.task
def p0_fail(tsk, exc, trcb):
    result = app.AsyncResult(tsk)
    print("Task {0} raised exception: {1!r}/{4!r}\n{2!r} and is in '{3}' state".format(
        tsk.id, result.info, result.traceback, result.state, result.result))
```
    >>> from tasks import *
    >>> res = (myadd.s(3,3) | mydiv.s(0).set(link_error = p0_fail.s()) | mysub.s(2)).apply_async()

This, as expected, leads to "Division by Zero" exception (snippet from celery's worker console):
```
[2018-06-07 18:14:12,676: WARNING/ForkPoolWorker-1] Task b237d6f6-e106-4390-81dc-36742a3113a8 raised exception: None/None
None and is in 'PENDING' state
[2018-06-07 18:14:12,676: ERROR/ForkPoolWorker-1] Task tasks.mydiv[b237d6f6-e106-4390-81dc-36742a3113a8] raised unexpected: ZeroDivisionError('division by zero',)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/doka/PycharmProjects/pyLearn/salad/tasks.py", line 15, in mydiv
    return int(x/y)
ZeroDivisionError: division by zero
```
## Expected behavior

Since one of chain's components failed and successfully called "link_error", chain must signal somehow about this, for example:

    >>> res.ready()
    False
    >>> res.failed()
    True

## Actual behavior

Actually, no ways to find that chain failed, since both ready and failed return False, while res.get() crashes with task's Exception:

```
>>> res.ready()
False
>>> res.failed()
False
>>> res.get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/result.py", line 174, in get
    self._maybe_reraise_parent_error()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/result.py", line 197, in _maybe_reraise_parent_error
    node.maybe_throw()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/result.py", line 296, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/result.py", line 289, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vine/promises.py", line 217, in throw
    reraise(type(exc), exc, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vine/five.py", line 179, in reraise
    raise value
celery.backends.base.ZeroDivisionError: division by zero
```

**Comment by auvipy** [comment]
could you try celery==4.2rc4 and let us know what happens?

**Comment by doka-ua** [comment]
The test built on OSX 10.12.6, Celery 4.2rc4, RabbitMQ 3.7.5. Config is
```
celery@Volodymyrs-MacBook-Air.local v4.2.0rc4 (windowlicker)

Darwin-16.7.0-x86_64-i386-64bit 2018-06-08 11:50:34

[config]
.> app:         tasks:0x103b22978
.> transport:   amqp://guest:**@localhost:5672//
.> results:     rpc://
.> concurrency: 4 (prefork)
.> task events: OFF (enable -E to monitor tasks in this worker)

[queues]
.> celery           exchange=celery(direct) key=celery
```

Result is exactly the same:

```
>>> from tasks import *
>>> res = (myadd.s(3,3) | mydiv.s(0).set(link_error = p0_fail.s()) | mysub.s(2)).apply_async()
>>> res.ready()
False
>>> res.failed()
False
>>> res.get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/result.py", line 207, in get
    self._maybe_reraise_parent_error()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/result.py", line 230, in _maybe_reraise_parent_error
    node.maybe_throw()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/result.py", line 329, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/celery/result.py", line 322, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vine/promises.py", line 217, in throw
    reraise(type(exc), exc, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vine/five.py", line 179, in reraise
    raise value
ZeroDivisionError: division by zero
```
One more observation:
```
>>> res.state
'PENDING'
>>> res.info
>>> res.traceback
>>> res.result
>>> res.get(propagate=False)
[ ... deadlock ... ]
```

so, Celery think that chain is in PENDING state. Don't know whether it really finished and Celery just didn't update it's internal state or task is still active, consuming worker and other resources.

Hope this will help.

**Comment by doka-ua** [comment]
Hi again, tested on Ubuntu 16.04 with Celery 4.1.1, RabbitMQ 3.5.7 with same result.
```
doka@devel2:~$ python3 console.py
2018-06-08 10:11:41.560706 : Object is 33a084c9-ca82-4c53-a04a-8e516eba7727 type <class 'celery.result.AsyncResult'>
2018-06-08 10:11:41.560824 : Sleeping for 5 seconds
[2018-06-08 10:11:41,593: INFO/MainProcess] Received task: tasks.mydiv[32f3de8a-5400-4bb9-ab30-2805ca920331]
[2018-06-08 10:11:41,642: ERROR/ForkPoolWorker-4] Task tasks.mydiv[32f3de8a-5400-4bb9-ab30-2805ca920331] raised unexpected: Exception('Ooopps!',)
2018-06-08 10:11:46.565942 Ready: False
2018-06-08 10:11:46.569296 Failed: False
2018-06-08 10:11:46.570861 Status: PENDING
2018-06-08 10:11:46.571970 : Trying to .get()
Traceback (most recent call last):
  File "console.py", line 22, in <module>
    result = res.get()
  File "/usr/local/lib/python3.5/dist-packages/celery/result.py", line 174, in get
    self._maybe_reraise_parent_error()
  File "/usr/local/lib/python3.5/dist-packages/celery/result.py", line 197, in _maybe_reraise_parent_error
    node.maybe_throw()
  File "/usr/local/lib/python3.5/dist-packages/celery/result.py", line 296, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/usr/local/lib/python3.5/dist-packages/celery/result.py", line 289, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/vine/promises.py", line 217, in throw
    reraise(type(exc), exc, tb)
  File "/usr/local/lib/python3.5/dist-packages/vine/five.py", line 179, in reraise
    raise value
celery.backends.base.Exception: Ooopps!
```

**Comment by doka-ua** [comment]
Hi friends, upgraded to 4.2.0 and got the same result. There are links to modules and outputs:

- tasks.py: https://pastebin.com/V4KBP9pf
- console.py: https://pastebin.com/xqXBX20D
- celery debug: https://pastebin.com/4Q1XDH3m
- console output: https://pastebin.com/11TCvynh

Any ideas on where I'm wrong? Thank you!

**Comment by auvipy** [comment]
new celery and vine versions?
