### ISSUE TITLE
celery multi restart error on 4.X: Connection reset by peer / 

### ISSUE THREAD

**Issue by cp2587** [celery/celery#4818]
celery -A report

```
software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:2.7.12
            billiard:3.5.0.3 py-amqp:2.3.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/0

task_serializer: u'pickle'
result_serializer: u'pickle'
python_modules: set([u'cayzn_yield.business_rules',
     u'cayzn_yield.etl',
     u'cayzn_yield.extractors',
     u'wiremind_python'])
task_time_limit: 3600
worker_max_tasks_per_child: 50
task_create_missing_queues: True
imports: ()
worker_redirect_stdouts: False
worker_prefetch_multiplier: 2
task_queues: 
    (<unbound Queue wiremind -> <unbound Exchange wiremind(direct)> -> wiremind>,)
task_soft_time_limit: 1800
task_routes: 
    (<function wiremind_route_for_task at 0x7fbc96e138c0>,)
accept_content: set([u'pickle'])
worker_disable_rate_limits: True
worker_hijack_root_logger: False
task_default_queue_priority: u''
redis_socket_connect_timeout: 5.0
broker_url: u'amqp://guest:********@localhost:5672//'
task_default_queue: u'wiremind'
result_backend: u'redis://localhost:6379/0'
```

## Steps to reproduce
run the command `celery multi start cayzn_worker_default cayzn_worker_low_priority cayzn_worker_high_priority  --pidfile="/home/cpierre/celery-%N.pid" -A cayzn_yield.etl.settings:celery_app -l INFO -Ofair -Q:cayzn_worker_default  cayzn_yield.etl,wiremind_python -c:cayzn_worker_default  4 -Q:cayzn_worker_low_priority  cayzn_yield.etl,cayzn_yield.etl.low-priority -c:cayzn_worker_low_priority  2 -Q:cayzn_worker_high_priority  cayzn_yield.etl.high-priority -c:cayzn_worker_high_priority  1`

## Expected behavior
The 3 workers should stop cleanly and restart. 

## Actual behavior
In practice, when under high load, two type of errors may happen:
 ```
Traceback (most recent call last):
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 46, in on_message
    self.node.handle_message(body, message)
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/amqp/channel.py", line 1732, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/amqp/method_framing.py", line 123, in write_frame
    type_, channel, framelen, frame, 0xce))
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/amqp/transport.py", line 275, in write
    self._write(s)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer
```

```
Traceback (most recent call last):
  File "/home/wirebot/.virtualenvs/cayzn_yield.etl/local/lib/python2.7/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: exitcode 0.
```

These errors are not always thrown but due to the nature of the bugs, it is very hard to reproduce with 100% certainty. I have just spent 3 hours trying to isolate the source but i failed - i could however reproduce the bugs by either sending the restart command almost immediatly after starting the workers or by waiting for long running task to get launched and then issuing a restart command... So i think the bugs are linked to the fact the worker is alrady in a shutdown state when the process returns the result of a task ? 

Does anyone encountered the same issues ?

**Comment by liuguichao** [comment]
Yes,  I saw the these two errors too. 
The first one, "error: [Errno 104] Connection reset by peer",  i downgrade the celery from 4.2 to 4.1.1, it looks good by now, not easy to reproduce it again.
The seconde one, it occurs many times in my log,  with a certain randomness, it seem like the worker subprocess crashed,  and the mainprocess respawn a new one.

```
2018-07-26 15:54:05,026: ERROR/MainProcess] Process 'ForkPoolWorker-1' 
pid:2270 exited with 'signal 6 (SIGABRT)' 
[2018-07-26 15:54:06,233: ERROR/MainProcess] Task handler raised error: 
WorkerLostError('Worker exited prematurely: signal 6 (SIGABRT).',) 
Traceback (most recent call last): 
File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 1223, in 
mark_as_worker_lost 
human_status(exitcode)), 
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 6 
(SIGABRT). 
```

```
[2018-08-01 15:51:58,978: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 0.',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 316, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 592, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/dist-packages/kombu/asynchronous/hub.py", line 298, in create_loop
    events = poll(poll_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/eventio.py", line 84, in poll
    return self._epoll.poll(timeout if timeout is not None else -1)
  File "/usr/local/lib/python3.5/dist-packages/celery/apps/worker.py", line 284, in _handle_request
    raise exc(exitcode)
celery.exceptions.WorkerShutdown: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 0.
```

**Comment by auvipy** [comment]
curious to know if this issue still persist in latest releases?

**Comment by cp2587** [comment]
I am afraid i cannot answer, we moved on to another librairy for our distributed task system (https://github.com/wiremind/remoulade). 

I think you can close this issue

**Comment by auvipy** [comment]
closing as per feedback but will re open when more report confirming this
