### ISSUE TITLE
Registering of serializers not working as expected.

### ISSUE THREAD

**Issue by janfreyberg** [celery/celery#4822]
Hello,

I'm trying to write a celery application that passes data in the form of numpy arrays and pandas objects to the workers. For this to work, I'd like to either use pickle formatting or a custom serialiser that implements special json en- and de-coders for the above objects. However, neither is working - when I try and execute a task, I receive the exception `kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type myjson (application/x-myjson)`. This is even though I believe I followed all the necessary steps.

## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.

```
$ celery -A tasks report

software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:3.6.5
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

broker_url: 'redis://localhost:8888//'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

My project structure is as follows:

```
celery-test
    |-tasks.py
    |-celeryconfig.py
    |-decoders.py
```

```python
# decoders.py
import json
import numpy as np
import pandas as pd


class DataEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return {
                '__type__': '__np.ndarray__',
                'content': obj.tolist()
            }
        elif isinstance(obj, pd.DataFrame):
            return {
                '__type__': '__pd.DataFrame__',
                'content': obj.to_json()
            }
        elif isinstance(obj, pd.Series):
            return {
                '__type__': '__pd.Series__',
                'content': obj.to_json()
            }
        else:
            return json.JSONEncoder.default(self, obj)


def data_decoder(obj):
    if '__type__' in obj:
        if obj['__type__'] == '__np.ndarray__':
            return np.array(obj['content'])
        elif obj['__type__'] == '__pd.DataFrame__':
            return pd.read_json(obj['content'], typ='frame')
        elif obj['__type__'] == '__pd.DataFrame__':
            return pd.read_json(obj['content'], typ='series')
    return obj


def data_dumps(obj):
    return json.dumps(obj, cls=DataEncoder)


def data_loads(obj):
    return json.loads(obj, object_hook=data_decoder)
```

```python
# tasks.py
from celery import Celery
from celery import security

from kombu.serialization import register
from decoders import data_dumps, data_loads

register('myjson', data_dumps, data_loads,
    content_type='application/x-myjson',
    content_encoding='utf-8')

app = Celery(
    'tasks',
    broker='redis://localhost:8888',
    accept_content=['myjson'],
    task_serializer='myjson'
)

app.setup_security(
    allowed_serializers=['myjson'],
    serializer='myjson'
)

@app.task
def adding(x, y):
    return x + y

if __name__ == '__main__':
    import numpy as np
    adding.apply_async((np.array([1]), np.array([1])), serializer='myjson')
```

```python
# celeryconfig.py
print('configuring...')

from kombu.serialization import register
from decoders import data_dumps, data_loads

register('myjson', data_dumps, data_loads,
    content_type='application/x-myjson',
    content_encoding='utf-8')

# Tell celery to use your new serializer:
accept_content = ['myjson']
task_serializer = 'myjson'
result_serializer = 'myjson'
```

Then run:
`$ celery -A tasks worker --loglevel=info &; python tasks.py`

## Expected behavior

Content is serialized with my custom serializer and the task is performed.

## Actual behavior

The following exception is thrown:
```python
[2018-06-16 13:42:14,978: CRITICAL/MainProcess] Unrecoverable error: ContentDisallowed('Refusing to deserialize untrusted content of type myjson (application/x-myjson)',)
Traceback (most recent call last):
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 598, in start
    c.loop(*c.loop_args())
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 633, in _callback
    return callback(message)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 572, in on_task_received
    callbacks,
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/celery/worker/strategy.py", line 136, in task_message_handler
    if body is None and 'args' not in message.payload:
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/message.py", line 207, in payload
    return self._decoded_cache if self._decoded_cache else self.decode()
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/message.py", line 192, in decode
    self._decoded_cache = self._decode()
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/message.py", line 197, in _decode
    self.content_encoding, accept=self.accept)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/kombu/serialization.py", line 253, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type myjson (application/x-myjson)
[2018-06-16 13:42:16,525: WARNING/MainProcess] Restoring 1 unacknowledged message(s)
```

The same occurs when trying to use pickle. I have tried many different ways of enabling pickle or this json drop-in, but none of them work.

I realise I'm specifying the configurations in several places here, but it also doesn't work if I delete celeryconfig.py or don't specify the serializers in tasks.py.

Am I correct in thinking if this is a bug?

**Comment by janfreyberg** [comment]
Hm - using the following in tasks.py worked:

```
import celeryconfig
...
app.config_from_object(celeryconfig)
```

Maybe the configuration steps could be documented better?
