### ISSUE TITLE
Consecutive groups in chain fails

### ISSUE THREAD

**Issue by miklagard** [celery/celery#4848]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
     CELERY 4.2.0
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
     chain(
         group(task1.s(), task2().s()),
         group(task3.s(), task4().s()),
         task5.s(),
    )
## Expected behavior
It works when I put task5.s() task between two groups but when I add consecutive groups in the chain, it fails with "AttributeError: 'GroupResult' object has no attribute 'task_id'" error.

## Actual behavior
    No messages purged from 1 queue
    Traceback (most recent call last):
      File "///home/cyildiz/projects/infrastructures/run-scripts/../src//start.py", line 139, in <module>
        start(validate_args)
      File "///home/cyildiz/projects/infrastructures/run-scripts/../src//start.py", line 85, in start
        wf.delay()
      File "/home/cyildiz/Projects/env/infra/local/lib/python2.7/site-packages/celery/canvas.py", line 179, in delay
        return self.apply_async(partial_args, partial_kwargs)
      File "/home/cyildiz/Projects/env/infra/local/lib/python2.7/site-packages/celery/canvas.py", line 557, in apply_async
        dict(self.options, **options) if options else self.options))
      File "/home/cyildiz/Projects/env/infra/local/lib/python2.7/site-packages/celery/canvas.py", line 573, in run
        task_id, group_id, chord,
      File "/home/cyildiz/Projects/env/infra/local/lib/python2.7/site-packages/celery/canvas.py", line 655, in prepare_steps
        task_id=prev_res.task_id, root_id=root_id, app=app,
    AttributeError: 'GroupResult' object has no attribute 'task_id'

**Comment by auvipy** [comment]
It seems you are providing the wrong parameter.

**Comment by illagrenan** [comment]
I had the same problem with:

```
software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.6.6
            billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

chaining groups produces:

```
AttributeError: 'GroupResult' object has no attribute 'task_id'
  File "celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "celery/app/base.py", line 476, in run
    raise task.retry(exc=exc, **retry_kwargs)
  File "celery/app/task.py", line 667, in retry
    raise_with_context(exc)
  File "celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "**REDACTED**.py", line 471, in **REDACTED**
    **REDACTED**.subtask(kwargs={**REDACTED**}, immutable=True),
  File "celery/canvas.py", line 557, in apply_async
    dict(self.options, **options) if options else self.options))
  File "celery/canvas.py", line 573, in run
    task_id, group_id, chord,
  File "celery/canvas.py", line 655, in prepare_steps
    task_id=prev_res.task_id, root_id=root_id, app=app,
```

This workaround worked for me: https://github.com/celery/celery/issues/3585#issuecomment-406658604
