### ISSUE TITLE
broadcast tasks can't send to workers 

### ISSUE THREAD

**Issue by ray1888** [celery/celery#4890]
## Checklist
```
software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:2.7.12
            billiard:3.5.0.3 py-amqp:2.3.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/

CELERY_QUEUES: 
    (<unbound Queue bcast.78a70966-db25-4256-aee2-e5e9e44ed2c7 -> <unbound Exchange broadcast_tasks(fanout)> -> >,)
Queue: <class 'kombu.entity.Queue'>
CELERY_DEFAULT_EXCHANGE_TYPE: 'direct'
CELERY_ALWAYS_EAGER: False
CELERY_DISABLE_RATE_LIMITS: True
CELERY_ENABLE_UTC: True
Exchange: <class 'kombu.entity.Exchange'>
CELERY_ACCEPT_CONTENT: ['pickle', 'json', 'msgpack', 'yaml']
Celery: <class 'celery.app.base.Celery'>
platforms: <module 'celery.platforms' from '/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/celery/platforms.pyc'>
CELERY_ROUTES: {
    'celery_task.method.get_new_method': {   'exchange': <unbound Exchange broadcast_tasks(fanout)>,
                                             'queue': 'broadcast_tasks'}}
C_FORCE_ROOT: True
Broadcast: <class 'kombu.common.Broadcast'>
CELERY_TIMEZONE: 'Asia/Shanghai'
CELERY_TASK_SERIALIZER: 'pickle'
BROKER_URL: u'amqp://guest:********@localhost:5672//'
CELERY_RESULT_BACKEND: u'redis://localhost:6379/'
CELERY_RESULT_SERIALIZER: 'pickle'
```

## Steps to reproduce

celery workers  -A celery_tasks 

## Expected behavior
workers should receive the broadcast task to run it 

## Actual behavior
```
[2018-07-07 16:45:19,401: CRITICAL/MainProcess] Unrecoverable error: PreconditionFailed(406, u"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'broadcast_tasks' in vhost '/': received 'fanout' but current is 'direct'", (40, 10), u'Exchange.declare')
Traceback (most recent call last):
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/celery/worker/consumer/tasks.py", line 41, in start
    c.connection, on_decode_error=c.on_decode_error,
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/celery/app/amqp.py", line 297, in TaskConsumer
    **kw
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/kombu/messaging.py", line 408, in revive
    self.declare()
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/kombu/messaging.py", line 421, in declare
    queue.declare()
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/kombu/entity.py", line 604, in declare
    self._create_exchange(nowait=nowait, channel=channel)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/kombu/entity.py", line 611, in _create_exchange
    self.exchange.declare(nowait=nowait, channel=channel)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/kombu/entity.py", line 185, in declare
    nowait=nowait, passive=passive,
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/amqp/channel.py", line 614, in exchange_declare
    wait=None if nowait else spec.Exchange.DeclareOk,
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/home/ray/.virtualenvs/general_algorithm_system/local/lib/python2.7/site-packages/amqp/channel.py", line 277, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
PreconditionFailed: Exchange.declare: (406) PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'broadcast_tasks' in vhost '/': received 'fanout' but current is 'direct'
```
ENV
python2.7
celery == 3.1.24  or celery==4.2.0
rabbitmq == 3(docker version)

**Comment by ray1888** [comment]
more update: 
i find that the broadcast Object create exchange in rabbitmq is default direct in my use case , is that my config error leading to this ?

**Comment by ray1888** [comment]
problem solve, but in a strage case .  i have to create multi channel to subscribe on a fanout exchange to get the data.   so what is the problem? looking forward the core team can find why this bug exist ?

now env variable 
python3.6
celery 4.2.0
