### ISSUE TITLE
Upgrade to Celery 4.2.0 causes "TypeError: 'NoneType' object is not iterable" when starting Celery worker

### ISSUE THREAD

**Issue by jeffj** [celery/celery#4907]
Hey Guys, I just noticed an upgrade to 4.2.0 from 4.1.1 causes breaking changes. Any ideas where this was intoduced?

System:
OSX 10.13.5
Anaconda Python 3.7

## Steps to reproduce

Install:

```
$ pip install Celery=4.2.0
```
Code:

```
celery_amqp_url=os.getenv("CELERY_AMQP_URL")

app = Celery('magic_worker',broker=celery_amqp_url)

@task
def parse(uid):
    print('parsing: %s' % uid)
```
Run:

```
$ celery -A magic_worker worker
```

## Expected behavior
Celery task is consumed.

## Actual behavior
Error throw:

```bash
[2018-07-16 21:04:52,098: CRITICAL/MainProcess] Unrecoverable error: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "python3.5/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "python3.5/site-packages/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "python3.5/site-packages/celery/worker/consumer/consumer.py", line 598, in start
    c.loop(*c.loop_args())
  File "python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "python3.5/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "python3.5/site-packages/kombu/transport/base.py", line 236, in on_readable
    reader(loop)
  File "python3.5/site-packages/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "python3.5/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "python3.5/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "python3.5/site-packages/amqp/method_framing.py", line 77, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "python3.5/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "python3.5/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "python3.5/site-packages/amqp/channel.py", line 1597, in _on_basic_deliver
    fun(msg)
  File "python3.5/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "python3.5/site-packages/celery/worker/consumer/consumer.py", line 572, in on_task_received
    callbacks,
  File "python3.5/site-packages/celery/worker/strategy.py", line 200, in task_message_handler
    handle(req)
  File "python3.5/site-packages/celery/worker/worker.py", line 223, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
  File "python3.5/site-packages/kombu/asynchronous/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
  File "python3.5/site-packages/celery/worker/worker.py", line 228, in _process_task
    req.execute_using_pool(self.pool)
  File "python3.5/site-packages/celery/worker/request.py", line 520, in execute_using_pool
    time_limit, soft_time_limit = self.time_limits
TypeError: 'NoneType' object is not iterable
```
## Work Around
Downgrade to celery 4.1.1

```
pip uninstall Celery
pip install Celery=4.1.1
```

**Comment by thedrow** [comment]
This is a bug that was probably caused by our recent feature addition that allows customizing the Request object.
Should be an easy fix.
