### ISSUE TITLE
`AsyncResult.ready` raises `TaskRevokedError` on Celery 4.2

### ISSUE THREAD

**Issue by tilgovi** [celery/celery#4910]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Might be tricky. I haven't been able to reproduce this in a test environment with the in-memory broker, but I experience it in production with Redis since upgrading from 4.1 to 4.2.

## Expected behavior

Checking `AsyncResult.ready()` should return `True` for a revoked task, since `REVOKED` is part of `READY_STATES`.

## Actual behavior

Checking `AsyncResult.ready()` raised `TaskRevokedError`.

I will add that the these tasks are part of a `Group` and the error is raised when checking the individual group children for readiness. I do not know whether checking the group for readiness triggers the error as well.

Here is a partial traceback, starting from where my application calls `.ready()`:

```
  File "celery/result.py", line 311, in ready
    return self.state in self.backend.READY_STATES
  File "celery/result.py", line 471, in state
    return self._get_task_meta()['status']
  File "celery/result.py", line 410, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "celery/result.py", line 404, in _maybe_set_cache
    self.on_ready(self)
  File "vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "vine/synchronization.py", line 67, in __call__
    self.p(*self.args, **self.kwargs)
  File "vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "vine/promises.py", line 143, in __call__
    return self.throw()
  File "vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "celery/result.py", line 877, in _on_ready
    ResultSet._on_ready(self)
  File "celery/result.py", line 519, in _on_ready
    self._cache = [r.get() for r in self.results]
  File "celery/result.py", line 519, in <listcomp>
    self._cache = [r.get() for r in self.results]
  File "celery/result.py", line 213, in get
    self.maybe_throw(callback=callback)
  File "celery/result.py", line 329, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "celery/result.py", line 322, in throw
    self.on_ready.throw(*args, **kwargs)
  File "vine/promises.py", line 217, in throw
    reraise(type(exc), exc, tb)
  File "vine/five.py", line 179, in reraise
    raise value
```

Please let me know if I can provide more information.

**Comment by auvipy** [comment]
could you check commits on master?

**Comment by auvipy** [comment]
lets hope for the best. ping here again if you still face it with 4.2.1

**Comment by worksewell** [comment]
It looks like this is still on `4.2.1`.

```
$ redis-server
$ python3 --version
Python 3.6.6
$ cat requirements.txt
celery[redis]==4.2.1
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install -r requirements.txt
$ cat test.py
import time

from celery import Celery, group


redis_url = 'redis://127.0.0.1:6379/0'

app = Celery('test', broker=redis_url, backend=redis_url)


@app.task
def hello():
    time.sleep(1)
    return 'hello world'


if __name__ == '__main__':
    r = group([hello.si() for _ in range(5)]).apply_async()
    r.revoke()
    while True:
        time.sleep(1)
        print(r.ready())
$ celery --app=test worker --concurrency=1
$ python test.py
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    print(r.ready())
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 591, in ready
    return all(result.ready() for result in self.results)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 591, in <genexpr>
    return all(result.ready() for result in self.results)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 311, in ready
    return self.state in self.backend.READY_STATES
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 471, in state
    return self._get_task_meta()['status']
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 410, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 404, in _maybe_set_cache
    self.on_ready(self)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/vine/synchronization.py", line 67, in __call__
    self.p(*self.args, **self.kwargs)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 877, in _on_ready
    ResultSet._on_ready(self)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 519, in _on_ready
    self._cache = [r.get() for r in self.results]
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 519, in <listcomp>
    self._cache = [r.get() for r in self.results]
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 213, in get
    self.maybe_throw(callback=callback)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 329, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/celery/result.py", line 322, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/vine/promises.py", line 217, in throw
    reraise(type(exc), exc, tb)
  File "/Users/ssewell/Desktop/celery/venv/lib/python3.6/site-packages/vine/five.py", line 179, in reraise
    raise value
celery.exceptions.TaskRevokedError: revoked
```

**Comment by tilgovi** [comment]
Thanks for the repro! I think we can catch the error and return the right value. I can try to make a PR and use this repro as the basis for a test case, if that sounds right, @auvipy.
