### ISSUE TITLE
i am getting celery 3.1 error if i add delay or apply_sync to function and cor-tab working fine in django

### ISSUE THREAD

**Issue by hemanth-sp** [celery/celery#4914]
```
[2018-07-19 06:49:41,781: WARNING/Worker-3] /home/xx/venv/xx/local/lib/python2.7/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: MultipleObjectsReturned('get() returned more than one Client -- it returned 2!',):
Traceback (most recent call last):
  File "/home/hemanth/venv/sd/local/lib/python2.7/site-packages/celery/app/trace.py", line 230, in trace_task
    args=args, kwargs=kwargs)
  File "/home/hemanth/venv/ww/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/hemanth/venv/ww/local/lib/python2.7/site-packages/tenant_schemas_celery/app.py", line 34, in switch_schema
    tenant = get_tenant_model().objects.get(schema_name=schema)
  File "/home/hemanth/venv/ww/local/lib/python2.7/site-packages/cacheops/query.py", line 444, in get
    return self.get_queryset().inplace().get(*args, **kwargs)
  File "/home/hemanth/venv/ww/local/lib/python2.7/site-packages/cacheops/query.py", line 316, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/home/hemanth/venv/ww/local/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one Client -- it returned 2!

  exc, exc_info.traceback)))

```

**Comment by auvipy** [comment]
use celery 4.2+
