### ISSUE TITLE
Celery failed to start as daemon with supervisor

### ISSUE THREAD

**Issue by brightgems** [celery/celery#4924]
## Checklist

- [ -] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ -] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

1. rewrite supervisord.conf
```

[program:celery-beat]
command=/usr/bin/celery -A adopt beat
environment=PYTHONPATH=/home/sharpdev/.local/lib/python3.6/site-packages/,APPSETTING_ENV_CONFIG=1
autostart=true
redirect_stderr=false
directory=/var/www/adopt-api/
stdout_logfile=/var/log/celery-beat.stdout.log
stderr_logfile=/var/log/celery-beat.stderr.log
priority=999

[program:celery-worker]
command=/usr/bin/celery -A adopt worker
environment=PYTHONPATH=/home/sharpdev/.local/lib/python3.6/site-packages/,APPSETTING_ENV_CONFIG=1
autostart=true
redirect_stderr=false
directory=/var/www/adopt-api/
stdout_logfile=/var/log/celery-worker.stdout.log
stderr_logfile=/var/log/celery-worker.stderr.log
numprocs=1
startsecs=10
priority=1000
```

2. run `service supervisor start`

## Expected behavior
Start celery as daemon task

## Actual behavior
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/sharpdev/.local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/sharpdev/.local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/sharpdev/.local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/sharpdev/.local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/sharpdev/.local/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/home/sharpdev/.local/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/home/sharpdev/.local/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/home/sharpdev/.local/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/home/sharpdev/.local/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/home/sharpdev/.local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/sharpdev/.local/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/adopt-api/adopt/__init__.py", line 1, in <module>
    from adopt.settings.celery import app as celery_app
  File "/var/www/adopt-api/adopt/settings/__init__.py", line 13, in <module>
    from .general import * 
  File "/var/www/adopt-api/adopt/settings/general.py", line 18, in <module>
    from djoser.conf import ObjDict
  File "/home/sharpdev/.local/lib/python3.6/site-packages/djoser/conf.py", line 5, in <module>
    from django.test.signals import setting_changed
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/test/__init__.py", line 3, in <module>
    from django.test.client import Client, RequestFactory
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/test/client.py", line 13, in <module>
    from django.core.handlers.base import BaseHandler
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 7, in <module>
    from django.urls import get_resolver, set_urlconf
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/urls/base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/http/__init__.py", line 5, in <module>
    from django.http.response import (
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/http/response.py", line 13, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/core/serializers/base.py", line 6, in <module>
    from django.db import models
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/db/models/__init__.py", line 3, in <module>
    from django.db.models.aggregates import *  # NOQA
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/db/models/aggregates.py", line 5, in <module>
    from django.db.models.expressions import Case, Func, Star, When
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/db/models/expressions.py", line 7, in <module>
    from django.db.models import fields
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 11, in <module>
    from django import forms
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/forms/__init__.py", line 6, in <module>
    from django.forms.boundfield import *  # NOQA
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/forms/boundfield.py", line 5, in <module>
    from django.forms.widgets import Textarea, TextInput
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/forms/widgets.py", line 21, in <module>
    from .renderers import get_default_renderer
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/forms/renderers.py", line 11, in <module>
    from django.template.backends.jinja2 import Jinja2
  File "/home/sharpdev/.local/lib/python3.6/site-packages/django/template/backends/jinja2.py", line 1, in <module>
    import jinja2
  File "/home/sharpdev/.local/lib/python3.6/site-packages/jinja2/__init__.py", line 82, in <module>
    _patch_async()
  File "/home/sharpdev/.local/lib/python3.6/site-packages/jinja2/__init__.py", line 78, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/home/sharpdev/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/usr/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/home/sharpdev/.local/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/sharpdev/.local/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback

**Comment by brightgems** [comment]
the issue had disappeared after reinstall twisted and futures.

Looks like twisted require async support version when looking at log.
