### ISSUE TITLE
Worker can't pickle body to pass it to a forked process if librabbitmq transport is used.

### ISSUE THREAD

**Issue by zaquest** [celery/celery#4931]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

1. Install celery (master or 4.2.1) with librabbitmq (2.0.0) transport;
2. Use any celery tasks file, [this](https://pastebin.com/DakEa7L6) for example;
3. Start celery worker with prefork (with any strategy for which `body_can_be_buffer == False` actually): `celery -A tasks worker`.

```
$ celery -A tasks report
software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:3.6.6
            billiard:3.5.0.4 librabbitmq:2.0.0
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:librabbitmq results:rpc:///

broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'rpc:///'
```

4. In python REPL:

```
>>> from tasks import *
>>> add.delay(1, 2)
```

5. Get stacktrace from the worker:

```
[2018-07-27 05:13:26,496: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fb2e9ec8e18> (args:('tasks.add', 'cdce855d-1b5d-42e0-9693-d438cb2ee678', {'lang': 'py', 'task': 'tasks.add', 'id': 'cdce855d-1b5d-42e0-9693-d438cb2ee678', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'cdce855d-1b5d-42e0-9693-d438cb2ee678', 'parent_id': None, 'argsrepr': '(1, 2)', 'kwargsrepr': '{}', 'origin': 'gen13691@zaquest-desktop', 'reply_to': '8fe6c6a2-e5c9-319a-ad7b-3de75e293ff4', 'correlation_id': 'cdce855d-1b5d-42e0-9693-d438cb2ee678', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': False}}, <memory at 0x7fb2e8c2fb88>, 'application/json', 'utf-8') kwargs:{})
[2018-07-27 05:13:26,497: CRITICAL/MainProcess] Unrecoverable error: SystemError('<built-in method _basic_recv of Connection object at 0x7fb2edd31d38> returned a result with an error set',)
Traceback (most recent call last):
  File "/home/zaquest/.virtualenvs/celery/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/zaquest/projects/mycelery/celery/celery/worker/consumer/consumer.py", line 567, in on_task_received
    callbacks,
  File "/home/zaquest/projects/mycelery/celery/celery/worker/strategy.py", line 200, in task_message_handler
    handle(req)
  File "/home/zaquest/projects/mycelery/celery/celery/worker/worker.py", line 223, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
  File "/home/zaquest/.virtualenvs/celery/lib/python3.6/site-packages/kombu/asynchronous/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
  File "/home/zaquest/projects/mycelery/celery/celery/worker/worker.py", line 228, in _process_task
    req.execute_using_pool(self.pool)
  File "/home/zaquest/projects/mycelery/celery/celery/worker/request.py", line 532, in execute_using_pool
    correlation_id=task_id,
  File "/home/zaquest/projects/mycelery/celery/celery/concurrency/base.py", line 155, in apply_async
    **options)
  File "/home/zaquest/.virtualenvs/celery/lib/python3.6/site-packages/billiard/pool.py", line 1486, in apply_async
    self._quick_put((TASK, (result._job, None, func, args, kwds)))
  File "/home/zaquest/projects/mycelery/celery/celery/concurrency/asynpool.py", line 821, in send_job
    body = dumps(tup, protocol=protocol)
TypeError: can't pickle memoryview objects

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zaquest/projects/mycelery/celery/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/zaquest/projects/mycelery/celery/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/zaquest/projects/mycelery/celery/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/zaquest/projects/mycelery/celery/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/home/zaquest/projects/mycelery/celery/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/zaquest/projects/mycelery/celery/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/home/zaquest/projects/mycelery/celery/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/home/zaquest/.virtualenvs/celery/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/home/zaquest/.virtualenvs/celery/lib/python3.6/site-packages/kombu/transport/base.py", line 236, in on_readable
    reader(loop)
  File "/home/zaquest/.virtualenvs/celery/lib/python3.6/site-packages/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "/home/zaquest/.virtualenvs/celery/lib/python3.6/site-packages/librabbitmq/__init__.py", line 227, in drain_events
    self._basic_recv(timeout)
SystemError: <built-in method _basic_recv of Connection object at 0x7fb2edd31d38> returned a result with an error set
```

After that worker shuts down.

## Expected behavior
No errors, execution of a task, worker continues to run.

## Actual behavior
Stack trace, task is not executed, worker shuts down.

I've figured the problem is that arguments passed to worker processes (process forked from worker's main process) contain `body` which is a `memoryview` object and is not picklable. I guess at some point `librabbitmq` returned either a `buffer` or `bytes` object, but it seems that now it returns `memoryview` and the check [here](https://github.com/celery/celery/blob/master/celery/worker/strategy.py#L141) doesn't work.

CC @xirdneh

**Comment by auvipy** [comment]
it's recommended to use py=amqp instead of librabbitmq. could you try py-amqp and report again?

**Comment by zaquest** [comment]
This is librabbitmq specific as the original post says.

**Comment by cyzanfar** [comment]
same error here using `librabbitmq`

**Comment by rajat-np** [comment]
same error using `librabbitmq`. using [amqp](https://github.com/celery/py-amqp) fixed the issue
