### ISSUE TITLE
In celery >=4.2, group_result.waiting() produces RuntimeError when launched within a task

### ISSUE THREAD

**Issue by ewjoachim** [celery/celery#4938]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```console
$ celery -A tasks report   
software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:3.6.5
            billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:redis:///

broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'redis:///'
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

```console
git --no-pager log -1                            
commit bff690df23f9d8bdb76911f0ed53d30639cfb6f1 (HEAD -> master, origin/master, origin/HEAD)
Author: Dash Winterson <dashdanw@gmail.com>
Date:   Sat Jul 28 00:26:52 2018 -0400

    Changed wording in docs for Task.retry() to mention the fact that it requeues (#4933)
    
    * changed wording for autodocs
    
    * Updated wording to be more descriptive
```

## Steps to reproduce

In an empty dir & new venv:
```console
$ git clone https://github.com/celery/celery.git
(...)
$ pip install -e ./celery[redis]
$ docker run -it --rm -p 127.0.0.1:5672:5672 rabbitmq &
$ docker run -it --rm -p 127.0.0.1:6379:6379 redis &
```

```python
# tasks.py
from celery import Celery
from celery import group

app = Celery('tasks',
             backend='redis://',
             broker='pyamqp://guest@localhost//')


@app.task()
def A():
    result = group(pow2.s(i) for i in range(3)).apply_async()
    result.save()
    restore.apply_async(kwargs={"result_id": result.id})


@app.task(bind=True)
def restore(self, result_id):
    group_result = app.GroupResult.restore(result_id)
    if group_result.waiting():
        self.retry()


@app.task()
def pow2(i):
    return i ** 2


if __name__ == '__main__':
    A.apply_async()

```

Launch a task:
```console
$ python tasks.py
$ celery -A tasks worker --loglevel=info
 
 -------------- celery@pidgin v4.2.0 (windowlicker)
---- **** ----- 
--- * ***  * -- Linux-4.15.0-24-generic-x86_64-with-Ubuntu-18.04-bionic 2018-07-30 19:08:58
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7f734f0f9748
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     redis://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . tasks.A
  . tasks.pow2
  . tasks.restore

[2018-07-30 19:08:58,142: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2018-07-30 19:08:58,150: INFO/MainProcess] mingle: searching for neighbors
[2018-07-30 19:08:59,184: INFO/MainProcess] mingle: all alone
[2018-07-30 19:08:59,207: INFO/MainProcess] celery@pidgin ready.
[2018-07-30 19:08:59,208: INFO/MainProcess] Received task: tasks.restore[7fc02326-6ede-4b79-b7c1-417647608f43]  ETA:[2018-07-30 17:10:16.138043+00:00] 
[2018-07-30 19:08:59,960: INFO/MainProcess] Received task: tasks.A[67c552ba-b6c3-4e96-ad27-96c6fa1c1ee2]  
[2018-07-30 19:08:59,986: INFO/MainProcess] Received task: tasks.pow2[10eb7370-f509-409a-be7d-4be201e3b7ef]  
[2018-07-30 19:08:59,993: INFO/MainProcess] Received task: tasks.pow2[ab1673dc-134e-4a8b-894d-f5e0dfebda1d]  
[2018-07-30 19:08:59,995: INFO/MainProcess] Received task: tasks.pow2[b36a7913-244f-4261-af19-c55f576062dc]  
[2018-07-30 19:08:59,997: INFO/ForkPoolWorker-2] Task tasks.A[67c552ba-b6c3-4e96-ad27-96c6fa1c1ee2] succeeded in 0.03580729899840662s: None
[2018-07-30 19:09:00,002: INFO/ForkPoolWorker-3] Task tasks.pow2[ab1673dc-134e-4a8b-894d-f5e0dfebda1d] succeeded in 0.006111745002272073s: 1
[2018-07-30 19:09:00,007: INFO/MainProcess] Received task: tasks.restore[f06959ff-e2da-4f98-936f-634b0aa163ca]  
[2018-07-30 19:09:00,008: INFO/ForkPoolWorker-1] Task tasks.pow2[10eb7370-f509-409a-be7d-4be201e3b7ef] succeeded in 0.02113196800200967s: 0
[2018-07-30 19:09:00,009: INFO/ForkPoolWorker-4] Task tasks.pow2[b36a7913-244f-4261-af19-c55f576062dc] succeeded in 0.009347234001324978s: 4
[2018-07-30 19:09:00,019: ERROR/ForkPoolWorker-2] Task tasks.restore[f06959ff-e2da-4f98-936f-634b0aa163ca] raised unexpected: RuntimeError('Never call result.get() within a task!\nSee http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks\n',)
Traceback (most recent call last):
  File "/home/joachim/src/celerytest/celery/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/joachim/src/celerytest/celery/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/joachim/src/celerytest/tasks.py", line 19, in restore
    if group_result.waiting():
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 583, in waiting
    return any(not result.ready() for result in self.results)
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 583, in <genexpr>
    return any(not result.ready() for result in self.results)
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 311, in ready
    return self.state in self.backend.READY_STATES
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 471, in state
    return self._get_task_meta()['status']
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 410, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 404, in _maybe_set_cache
    self.on_ready(self)
  File "/home/joachim/.virtualenvs/celerytest/lib/python3.6/site-packages/vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "/home/joachim/.virtualenvs/celerytest/lib/python3.6/site-packages/vine/synchronization.py", line 67, in __call__
    self.p(*self.args, **self.kwargs)
  File "/home/joachim/.virtualenvs/celerytest/lib/python3.6/site-packages/vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "/home/joachim/.virtualenvs/celerytest/lib/python3.6/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/home/joachim/.virtualenvs/celerytest/lib/python3.6/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 877, in _on_ready
    ResultSet._on_ready(self)
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 519, in _on_ready
    self._cache = [r.get() for r in self.results]
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 519, in <listcomp>
    self._cache = [r.get() for r in self.results]
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 203, in get
    assert_will_not_block()
  File "/home/joachim/src/celerytest/celery/celery/result.py", line 41, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

## Expected behavior

No failure, no traceback, like previous versions of Celery (`<=4.1`)

## Actual behavior

With Celery>=4.2, failure, with the traceback above.

## Additional information

Problem only happens (as far as I can tell) when calling `.waiting` or `.failed` or equivalent on the result of a Group (or anything inheriting `ResultSet`) when the result backend is async (thus my minimal example using redis) and the result is known (thus the `retry`).

I'm fairly certain that the problem lies in this commit https://github.com/celery/celery/pull/4131/files that replaced `on_ready` with `_on_ready`. Actually, if I undo the change:

```diff
diff --git a/celery/result.py b/celery/result.py
index e961d327d..cdfb1da58 100644
--- a/celery/result.py
+++ b/celery/result.py
@@ -502,7 +502,7 @@ class ResultSet(ResultBase):
         self.on_ready = promise(args=(self,))
         self._on_full = ready_barrier or barrier(results)
         if self._on_full:
-            self._on_full.then(promise(self._on_ready))
+            self._on_full.then(promise(self.on_ready))
 
     def add(self, result):
         """Add :class:`AsyncResult` as a new member of the set.

```

It works:
```console
$ celery -A tasks worker --loglevel=info
 (...)
[2018-07-30 19:13:21,809: INFO/ForkPoolWorker-1] Task tasks.restore[d97e04f2-a1ed-4211-966d-2a42b42fad7e] succeeded in 0.005780382001830731s: None
```

So shall I do a PR ? I'm not sure I understand the reasons behind the change.

Ping @thedrow: Any opinion on this, given it's your change ?

**Comment by georgepsarakis** [comment]
@ewjoachim thanks for the detailed description, but can you please describe your use case?

**Comment by ewjoachim** [comment]
I think it could have been written as a chord **except** for the fact that if any of the tasks of the group fail, we would quickly revoke the other tasks and avoid a lot on unnecessary work. So the idea is to have a task that starts running at the same time as the group, and that will so some checks on the current results of the group while the group is running. 

Of course, it's not really visible in the code above, which is a minimal example, made to highlight the exception, not to show my use case :)

I may be missing existing primitives that would allow to have a fail-fast behaviour on a chord.

**Comment by dolfim** [comment]
Is there any update on this?

We seem to have a similar failure, but for us it comes from calling `result.ready()` inside a task. The stacktrace shows that the `.ready()` function is calling the `.get()` for some caching. This triggers the `assert_will_not_block()` exception.

With celery 4.2.1:
```
    ready_task = parent.ready()
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 311, in ready
    return self.state in self.backend.READY_STATES
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 471, in state
    return self._get_task_meta()['status']
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 410, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 404, in _maybe_set_cache
    self.on_ready(self)
  File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "/usr/local/lib/python3.6/site-packages/vine/synchronization.py", line 67, in __call__
    self.p(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 150, in __call__
    svpending(*ca, **ck)
  File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 143, in __call__
    return self.throw()
  File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 877, in _on_ready
    ResultSet._on_ready(self)
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 519, in _on_ready
    self._cache = [r.get() for r in self.results]
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 519, in <listcomp>
    self._cache = [r.get() for r in self.results]
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 203, in get
    assert_will_not_block()
  File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 41, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
```

**Comment by lstolcman** [comment]
BUMP
Any update?

I have the same error, I am using `.join()` on group


log from `celery==4.3.0`
```
[2019-06-19 03:04:27,712: ERROR/ForkPoolWorker-8] Task process_run_task[fe246ffd-3a55-4bbd-88d8-c17862a80de8] raised unexpected: RuntimeError('Never call result.get() within a task!\nSee http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/myapp/apps/core/tasks.py", line 65, in process_run_task
    result.join()
  File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 748, in join
    assert_will_not_block()
  File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 41, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

log from last commit (2c029c4):
```
Traceback (most recent call last):
  File "/code/celery/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/code/celery/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/myapp/apps/core/tasks.py", line 65, in process_run_task
    result.join()
  File "/code/celery/celery/result.py", line 748, in join
    assert_will_not_block()
  File "/code/celery/celery/result.py", line 41, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks

```

My usecase is that I want to have several tasks finished before doing a cleanup in main task. Some pseudocode:
```python
@app.task()
def main_task():

    # some setups here...

    jobs = []
    for i in range(2):
        jobs.append(subtask1.s(i))
    result = group(jobs)
    result.apply_async()
    result.join()

    # some cleanups here...


@app.task()
def subtask1(arg_i):
    time.sleep(arg_i)
    print(f'subtask {arg_i} waiting for {arg_i}s')
```

**Comment by adriancarayol** [comment]
@lstolcman you must use 

`from celery.result import allow_join_result
with allow_join_result():
    result.join()
`

**Comment by auvipy** [comment]
what is the latest resultion

**Comment by ewjoachim** [comment]
Oh, sorry I missed the post above. Let me check with the project that bumped into the problem, I'll get back to you and reopen if needed.
