### ISSUE TITLE
Django: custom user module not recognized

### ISSUE THREAD

**Issue by asterion2nd** [celery/celery#4939]
Python: 3.5.2
Django: 1.11.2
Celery: 4.2.1

My Django project has a custom user model called (CustomUser) declared inside an app/folder called "profile":
settings/base.py:
```
INSTALLED_APPS += ('profile',)
AUTH_USER_MODEL = 'profile.CustomUser'
```

proj/proj/celery.py
```
from __future__ import absolute_import, unicode_literals
from celery import Celery

app = Celery('proj')
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks()

@app.task(bind=True)
def debug_task(self):
	print('Request: {0!r}'.format(self.request))
```

proj/proj/__init__.py
```
from __future__ import absolute_import, unicode_literals
from .celery import app as celery_app


__all__ = ('celery_app',)
```

All Django's manage.py options such as "runserver" and "shell" work fine.
e.g.: 
`$ python manage.py runserver --settings=proj.settings.local`

But when trying to run a worker by executing:
`$ DJANGO_SETTINGS_MODULE=proj.settings.local celery worker  -A proj -l info`
I get the following Exception:
```
Traceback (most recent call last):
  File "/home/.virtualenvs/celery4/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/fixups/django.py", line 82, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/fixups/django.py", line 120, in validate_models
    self.django_setup()
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/celery/fixups/django.py", line 116, in django_setup
    django.setup()
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/.virtualenvs/celery4/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/.virtualenvs/celery4/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/repo/repo/proj/test_module/models.py", line 5, in <module>
    from test_module2.models import TestClass
  File "/home/repo/repo/proj/test_module2/models.py", line 31, in <module>
    from profile.helper import test_func
ImportError: No module named 'profile.helper'; 'profile' is not a package
```

The module which defines my custom user model is not recognized as a python module and cannot be imported by other project modules.

After checking:
[https://github.com/django/django/blob/master/django/core/management/__init__.py#L325](https://github.com/django/django/blob/master/django/core/management/__init__.py#L325)

I decided to add the following to proj/proj/celery.py
```
from django.conf import settings
settings.INSTALLED_APPS
```
right after 
`app = Celery('proj')`

And it worked, both celery worker and beat.

Maybe this happens when a project is using a custom user model rather than the one provided by Django. In that case, a workaround should be added to Celery's documentation.

**Comment by inoks** [comment]
@asterion2nd Looks like your does not relate to Celery itself.
Couple of suggestion:
- Do you have `__init__.py` inside your `profile` dir?
 - Can you execute code `from profile.helper import test_func` inside Django shell?
`python manage.py shell --settings=proj.settings.local`

**Comment by asterion2nd** [comment]
@inoks 
1. Yes, `__init__.py` is there. Remember that I've set `AUTH_USER_MODEL = 'profile.CustomUser'`, which wouldn't work if that was missing.
2. The project works perfectly, including the custom user model, when running `runserver` and `shell`. What is happening is that when upgrading from Celery 3 to 4 and removing `django-celery` (djcelery), I start getting the behavior described unless I do the mentioned workaround.

**Comment by inoks** [comment]
@asterion2nd I think there can be issue with the way how your `settings/local.py` evaluated from `settings/base.py`, can you test if everything works with having one settings file first?

**Comment by asterion2nd** [comment]
@inoks
The first line of `settings/local.py` is `from .base import *`.
As far as I know, using multiple files for development, staging and production and importing common settings using the syntax above is a common pattern in Django.
 
Besides that, I followed your suggestion and unified the settings files into `settings/local.py` and the exception still shows up.

Just to make it clear, both celery worker and celery beat works if use on `proj/proj/celery.py`:
```
from django.conf import settings
settings.INSTALLED_APPS
app = Celery('proj')
```

Have you tried to reproduce this bug?

**Comment by inoks** [comment]
@asterion2nd It would be nice if you can create sample project on Github, which displays that issue.
Thanks!
