### ISSUE TITLE
Warm shutdown does not work correctly with solo taskpool

### ISSUE THREAD

**Issue by entwanne** [celery/celery#4942]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.6.5
            billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Run a Celery worker with `--pool=solo` option and send it a SIGTERM while executing a task. By running [this script](https://gist.github.com/entwanne/819db854ea3e01f6e54968bab9ecc723) for example.

## Expected behavior

The task should complete before the process stops, like when running without `--pool=solo`.

## Actual behavior

The worker prints "worker: Warm shutdown (MainProcess)" and immediatly stops.

Maybe related to #3430

**Comment by auvipy** [comment]
closing as a duplicate for now. will reopen again if thats not the case

**Comment by ohyang326** [comment]
I have same problem

**Comment by auvipy** [comment]
celery==4.4.0?

**Comment by ohyang326** [comment]
celery==4.3.0

log is :
[2019-12-18 11:44:47,447: DEBUG/MainProcess] | Worker: Closing Hub...
[2019-12-18 11:44:47,469: DEBUG/MainProcess] | Worker: Closing Pool...
[2019-12-18 11:44:47,471: DEBUG/MainProcess] | Worker: Closing Consumer...
[2019-12-18 11:44:47,472: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2019-12-18 11:44:47,473: DEBUG/MainProcess] | Consumer: Closing Connection...
[2019-12-18 11:44:47,475: DEBUG/MainProcess] | Consumer: Closing Events...
[2019-12-18 11:44:47,476: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2019-12-18 11:44:47,478: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2019-12-18 11:44:47,484: DEBUG/MainProcess] | Consumer: Closing Control...
[2019-12-18 11:44:47,488: DEBUG/MainProcess] | Consumer: Closing Heart...
[2019-12-18 11:44:47,491: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2019-12-18 11:44:47,497: DEBUG/MainProcess] | Consumer: Closing event loop...
[2019-12-18 11:44:47,504: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2019-12-18 11:44:47,505: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2019-12-18 11:44:47,511: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2019-12-18 11:44:47,516: DEBUG/MainProcess] | Consumer: Stopping Control...
[2019-12-18 11:44:47,523: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2019-12-18 11:44:47,524: DEBUG/MainProcess] Canceling task consumer...
[2019-12-18 11:44:47,526: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2019-12-18 11:44:47,527: DEBUG/MainProcess] | Consumer: Stopping Events...
[2019-12-18 11:44:47,527: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2019-12-18 11:44:47,529: DEBUG/MainProcess] | Worker: Stopping Pool...
[2019-12-18 11:44:47,531: DEBUG/MainProcess] | Worker: Stopping Hub...
[2019-12-18 11:44:47,532: ERROR/MainProcess] Error on stopping Hub: MessageStateError('Message already acknowledged with state: ACK',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.5/site-packages/kombu/transport/redis.py", line 1052, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.5/site-packages/kombu/transport/redis.py", line 348, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.5/site-packages/kombu/transport/redis.py", line 736, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/usr/local/lib/python3.5/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
  File "/usr/local/lib/python3.5/site-packages/kombu/transport/virtual/base.py", line 633, in _callback
    return callback(message)
  File "/usr/local/lib/python3.5/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 568, in on_task_received
    callbacks,
  File "/usr/local/lib/python3.5/site-packages/celery/worker/strategy.py", line 203, in task_message_handler
    handle(req)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 228, in _process_task
    req.execute_using_pool(self.pool)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/request.py", line 551, in execute_using_pool
    correlation_id=task_id,
  File "/usr/local/lib/python3.5/site-packages/celery/concurrency/base.py", line 155, in apply_async
    **options)
  File "/usr/local/lib/python3.5/site-packages/celery/concurrency/base.py", line 31, in apply_target
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 556, in _fast_trace_task
    uuid, args, kwargs, request,
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/myapp/hhgj/app/celeryTask/tasks.py", line 75, in task_status
    data = func(*args, **kwargs)
  File "/usr/src/myapp/hhgj/app/celeryTask/tasks.py", line 92, in migrate_task
    ret = migrate(arr_post)
  File "/usr/src/myapp/hhgj/app/celeryTask/migrate.py", line 335, in migrate
    upload_one_product(data, tp_product, migration)
  File "/usr/src/myapp/hhgj/app/celeryTask/migrate.py", line 245, in upload_one_product
    data = build_basic_data(user, template, tp_product, tp_property, pre_sale_date)
  File "/usr/src/myapp/hhgj/app/celeryTask/migrate.py", line 66, in build_basic_data
    tp_property['desc_json'] = update_img_urls(user['access_token'], tp_property['desc_json'], 2)
  File "/usr/src/myapp/hhgj/pddpy/goods.py", line 235, in update_img_urls
    image_url = update_img_file(access_token, file_path, type)
  File "/usr/src/myapp/hhgj/pddpy/goods.py", line 254, in update_img_file
    im.save(file_path,'jpeg')
  File "/usr/local/lib/python3.5/site-packages/PIL/Image.py", line 2084, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.5/site-packages/PIL/JpegImagePlugin.py", line 770, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "/usr/local/lib/python3.5/site-packages/PIL/ImageFile.py", line 530, in _save
    s = e.encode_to_file(fh, bufsize)
  File "/usr/local/lib/python3.5/site-packages/celery/apps/worker.py", line 284, in _handle_request
    raise exc(exitcode)
celery.exceptions.WorkerShutdown: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/components.py", line 85, in stop
    w.hub.close()
  File "/usr/local/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 263, in close
    item()
  File "/usr/local/lib/python3.5/site-packages/vine/promises.py", line 170, in __call__
    return self.throw()
  File "/usr/local/lib/python3.5/site-packages/vine/promises.py", line 167, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/local/lib/python3.5/site-packages/kombu/message.py", line 131, in ack_log_error
    self.ack(multiple=multiple)
  File "/usr/local/lib/python3.5/site-packages/kombu/message.py", line 125, in ack
    self))
kombu.exceptions.MessageStateError: Message already acknowledged with state: ACK
[2019-12-18 11:44:47,565: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2019-12-18 11:44:47,570: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2019-12-18 11:44:47,570: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2019-12-18 11:44:47,571: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2019-12-18 11:44:47,572: DEBUG/MainProcess] Canceling task consumer...
[2019-12-18 11:44:47,573: DEBUG/MainProcess] Closing consumer channel...
[2019-12-18 11:44:47,573: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2019-12-18 11:44:47,575: DEBUG/MainProcess] | Consumer: Shutdown Connection...

**Comment by auvipy** [comment]
use the latest version dude

**Comment by ohyang326** [comment]
I have try celery=4.4.0

has no error log, but my task not finish , interrupt.

**Comment by auvipy** [comment]
> I have try celery=4.4.0 kombu==4.6.7
> 
> has no error log, but my task not finish , interrupt.
> 
> start command:
> celery -A tasks worker --loglevel=debug -n worker-test -Q worker_test_queue -c 1 -P solo --logfile /data/logs/celery/worker_test.log

can you please check this issue? https://github.com/celery/celery/issues/3430
