### ISSUE TITLE
`task_name.delay()` behaving differently than normal `task_name()` call

### ISSUE THREAD

**Issue by bsolomon1124** [celery/celery#4943]
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Unable to give exact function call, but full traceback & related function calls given here.

Appreciate any thoughts on where this could be coming from, and let us know what other info we can provide here.

## Actual behavior

Calling `task_name.delay()` versus just `task_name()` produces different behavior.  (An exception for the former, smooth execution for the latter.)

By default, the tasks (on a 2x per day basis) is called with the async `.delay()` call, which throws the error given here.  When we run the same task manually from `./manage.py shell`, without `.delay()`, the update occurs without a hitch. 

## Issue Detail

We use Celery for daily task scheduling within a Django project.

**Issue**: when we call a task with `task_name.delay()`, we received a strange AttributeError.  When we call the same task without `.delay()`, i.e. `task_name()`, the task runs smoothly and we have no issue.

----

**Versions in use**:

- Python 2.7.5
- Django 1.11
- Celery 3.1.18
- dateutil 2.5.3

----

**Problem background**: this particular tasks is related to updating a database after retrieving API calls that return JSON.

The field in question comes in as a `unicode` representation of a Unix timestamp, i.e. u'1524820319'.

This is the Python value that we get from the JSON response.  It is then converted to a `datetime.datetime` with a `.tzinfo` attribute:

```python
post['created_at'] = int(post['created_at'])
try:
    post['created_at'] = get_tz_aware_datetime(post['created_at'])
except AttributeError:
    logger.exception(
        'Dateutil parser error; we tried passing %s (type=%s) from post_url=%s (username=%s)',
        post['created_at'],
        type(post['created_at']),
        POST_URL(post['post_id']),
        self.username)
    raise
```

What throws the exception is `get_tz_aware_datetime()`, which is shown in full below:

```python
import datetime
import logging

from dateutil.parser import parse
import pytz

logger = logging.getLogger('app')


def get_tz_aware_datetime(dt):
    """
    Convert a datetime-like object to a `datetime.datetime` with .tzinfo.

    Parameters
    ----------
    dt
        Acceptable types/values:
        - 'today'
        - datetime.date
        - datetime.datetime
        - basestring (parsed by dateutil.parser.parse)
        - float/int (Unix ts)

    Returns
    -------
    timezone-aware `datetime.datetime` object
    """
                              # <-- This is line 27, as referenced in the traceback below
    if not dt:
        msg = 'Invalid; `dt` is empty (%s).'
        logger.warn(msg, dt)
        raise ValueError(msg % dt)

    elif isinstance(dt, basestring):
        if dt.lower() == 'today':  # Special feature!
            return utcnow()
        try:
            dt = parse(dt)
        except AttributeError:
            logger.exception('Dateutil parser error: received %s (%s)',
                             dt, type(dt))
            raise

    elif isinstance(dt, datetime.datetime):
        # Catch this first:
        # datetime.datetime is subclass of datetime.date
        pass

    elif isinstance(dt, datetime.date):
        y, m, d = (getattr(dt, attr) for attr in ('year', 'month', 'day'))
        dt = datetime.datetime(y, m, d)

    elif isinstance(dt, (float, int)):
        dt = datetime.datetime.utcfromtimestamp(dt)

    else:
        # We're out of accepted types
        raise ValueError('Type of `dt` (%s) is not recognized.' % type(dt))

    if not dt.tzinfo:
        # Give the datetime object a `.tzinfo` attribute, now that
        # we either have `datetime.datetime` or already raised
        dt = dt.replace(tzinfo=pytz.UTC)
    return dt
```

Example:

```python
>>> get_tz_aware_datetime(1524820319)
datetime.datetime(2018, 4, 27, 9, 11, 59, tzinfo=<UTC>)
```

The oddity is that we are presumably passing an `int()` to `get_tz_aware_datetime()`, but still having `dateutil.parser.parse()` get called even though that `elif` block shouldn't be reached.

The full traceback is below, with some information redacted to generic terms.  As mentioned above, it indicates we are passing an int (1524820319 here), but receiving some exception from dateutil, the call for which should not have been reached in the first place.

```
[31/Jul/2018 06:34:32] ERROR [api_interface.py get_user_posts:211] Dateutil parser error; we tried passing 1524820319 (type=<type 'int'>) from post_url=XXXXX (username=XXXXX)
Traceback (most recent call last):
  File "/www/XXXXX/apps/XXXXX/api_interface.py", line 204, in get_user_posts
    post['created_at'] = get_tz_aware_datetime(post['created_at'])
  File "/www/XXXXX/apps/lib/date_helpers.py", line 27, in get_tz_aware_datetime
    
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 552, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 671, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 188, in split
    return list(cls(s))
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 184, in next
    return self.__next__()  # Python 2.x support
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 177, in __next__
    token = self.get_token()
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 93, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'int' object has no attribute 'read'
[31/Jul/2018 06:34:32] ERROR [tasks.py update_owner:108] ERR001 could not update XXXXX from the XXXXX API 'int' object has no attribute 'read' Traceback (most recent call last):
  File "/www/XXXXX/apps/master/tasks.py", line 94, in update_owner
    # Only update selected `content_type` (str)
  File "/www/XXXXX/apps/master/architecture.py", line 856, in update_from_api
    def update_from_api(self, since, until, limit=None, greedy=False):
  File "/www/XXXXX/apps/master/architecture.py", line 993, in download_posts
    print post_check.content
  File "/www/XXXXX/apps/master/architecture.py", line 1015, in _download_posts
    else:
  File "/www/XXXXX/apps/XXXXX/api_interface.py", line 76, in get_posts
    limit=limit, greedy=greedy)
  File "/www/XXXXX/apps/XXXXX/api_interface.py", line 204, in get_user_posts
    post['created_at'] = get_tz_aware_datetime(post['created_at'])
  File "/www/XXXXX/apps/lib/date_helpers.py", line 27, in get_tz_aware_datetime
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 552, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 671, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 188, in split
    return list(cls(s))
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 184, in next
    return self.__next__()  # Python 2.x support
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 177, in __next__
    token = self.get_token()
  File "/www/XXXXX/venv/lib/python2.7/site-packages/dateutil/parser.py", line 93, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'int' object has no attribute 'read'
```

A summarized version of the task itself that calls `api_interface.py`:

```python
import logging

from lib.date_helpers import ago, utcnow
from project.celery_app import app
from master.architecture import OwnerManager

logger = logging.getLogger('app')

@app.task(name='master.update')
def update_all_accounts(since=None, until=None, debugging=False,
                        skip_if_updated_today=False, content_type=None,
                        note_skipped=True):

    since = since or ago(weeks=8)
    until = until or utcnow()

    accounts = OwnerManager.all()
    for a in accounts:
        if debugging:
            update = update_owner
        else:
            update = update_owner.delay
        update(
            owner_name=a.name,
            since=since,
            until=until,
            skip_if_updated_today=skip_if_updated_today,
            content_type=content_type,
            note_skipped=note_skipped
        )

@app.task(name='master.update_acct')
def update_owner(owner_name, since, until, skip_if_updated_today=False,
                 content_type=None, note_skipped=True):
     for acct in owner.accounts:
        # Update the individual account row in DB
```

## Result of `celery -A proj report`

```
$ celery -A proj report
Traceback (most recent call last):
  File "/www/XXXXX/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/www/XXXXX/venv/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/www/XXXXX/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/www/XXXXX/venv/lib/python2.7/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/www/AXXXXX/venv/lib/python2.7/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/celery/app/utils.py", line 229, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/celery/bin/base.py", line 492, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/www/XXXXX/venv/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named proj
```

**Comment by auvipy** [comment]
I would also suggest you try a newer version of celery.
