### ISSUE TITLE
Celery (4.2.1) times out often with AWS ElastiCache (Redis, 4.0.10) with high loads

### ISSUE THREAD

**Issue by dejlek** [celery/celery#5004]
There was already a bug report about this. It got closed as the author of the ticket did not provide any feedback. (Issue: #4039)

Basically what is happening is that whenever we have a larger cluster (of say over 40 c5d.9xlarge nodes) we experience frequent Redis connection timeouts.

````
Traceback (most recent call last):
File "/opt/celery/venv/lib64/python3.6/site-packages/redis/client.py", line 667, in execute_command
connection.send_command(*args)
File "/opt/celery/venv/lib64/python3.6/site-packages/redis/connection.py", line 610, in send_command
self.send_packed_command(self.pack_command(*args))
File "/opt/celery/venv/lib64/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
self.connect()
File "/opt/celery/venv/lib64/python3.6/site-packages/redis/connection.py", line 486, in connect
raise TimeoutError("Timeout connecting to server")
````

## Checklist

- [ x ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ x ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

It is really hard to reproduce this problem as it happens only when there are many Celery nodes...

## Expected behavior

No TimeoutError exceptions thrown.

## Actual behavior

Redis TimeoutError frequently thrown...

**Comment by thedrow** [comment]
Does the same thing happen when connecting to Redis without ElasticCache?
According to #4039 it seems it does not matter if it's ElasticCache or not.
Since these are extreme conditions I'd like to inspect the Redis logs which is not possible using ElasticCache.

@antirez Any chance you can help us debug this from Redis' side? Could this be a cluster issue?

**Comment by dejlek** [comment]
I forgot to mention - it is a single node ElastiCache setup...

At the moment I have no time to investigate whether the same happens with a dedicated Redis server (an EC2 instance), but I definitely will try to find time to do this test. I will need to modify the infrastructure scripts as this problem only happens in production when we have 40+ Celery nodes...

**Comment by thedrow** [comment]
Can you paste the output of the INFO command when timeouts occur?

**Comment by georgepsarakis** [comment]
Also, could you please share the hardware specifications (or simply the instance type) of the Redis instance? 

Generally it would be helpful if you had available metrics of (at least) the connection count, CPU usage, RAM usage for the ElastiCache node, over time.

**Comment by dejlek** [comment]
Thing is - I find timeout errors in the logs... I will try to capture the INFO output next time the timeout happens.

**Comment by dejlek** [comment]
@thedrow - I've updated my Celery monitor to capture the timeout error, and run INFO when that happens. I've updated the issue with the INFO output.

**Comment by crabhi** [comment]
I've submitted some info into https://github.com/celery/celery/issues/4039#issuecomment-441003405

The packet loss in simulation is extreme to be able to reproduce it quickly but it happens also with lower amount of lost packets.

**Comment by dejlek** [comment]
I am not sure this is Celery problem. py-redis should retry to connect and execute command with some backoff strategy...

**Comment by crabhi** [comment]
It might be a problem in py-redis or some race condition in Redis usage. But I don't know Celery internals to further narrow the problem down.

**Comment by machineslearnoliver** [comment]
Any updates on this issue? When using ElastiCache calling result.get() gridlocks the requests. Works perfectly fine when i spin up a standalone Redis server
redis==3.2.1
celery==4.4.0rc3 
kombu==4.6.3
(Same results for latest stable celery/kombu)

**Comment by auvipy** [comment]
same result with celery==4.4.0rc4?

**Comment by romange** [comment]
@oliverhowden  which ElastiCache version did you use ? ElastiCache 5.0 provide much better throughput

**Comment by oliverhowden** [comment]
Can't remember @romange. Moved as far away from celery + ElastiCache as possible and into an AWS Lambda + Step Function + SQS environment. Have 300x'd our throughput for the same server costs

**Comment by romange** [comment]
Great improvement!

**Comment by thedrow** [comment]
@oliverhowden We're hoping to improve :)

**Comment by dejlek** [comment]
FYI, this is happening with 5.0.7 too.
