### ISSUE TITLE
MAX_TASKS_PER_CHILD causes connection errors

### ISSUE THREAD

**Issue by MattBlack85** [celery/celery#5010]
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
one wants to recycle workers after X tasks so the setting is added to workers configuration
## Expected behavior
children workers are happily killed by the main process with no problem
## Actual behavior
when killing the child worker, I get a ConnectionResetError

Traceback:
```Python
ConnectionResetError: [Errno 104] Connection reset by peer
  File "celery/worker/pidbox.py", line 46, in on_message
    self.node.handle_message(body, message)
  File "kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "amqp/channel.py", line 1732, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "amqp/transport.py", line 275, in write
    self._write(s)
```

using `BROKER_POOL_LIMIT = None` makes this errors go away

**Comment by auvipy** [comment]
can you provide a failing testcase?

**Comment by adampl** [comment]
The same error occurs in my case. However, I've also discovered that the following code _quite often_ fails, which seems unrelated to the MAX_TASKS_PER_CHILD setting:
```python
inspector = app.control.inspect()
active_queues = inspector.active_queues()
# the same happens with other methods like .stats() or .active()
```

Traceback:
```
    active_queues = inspector.active_queues()
  File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 130, in active_queues
    return self._request('active_queues')
  File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 95, in _request
    timeout=self.timeout, reply=True,
  File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 454, in broadcast
    limit, callback, channel=channel,
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 315, in _broadcast
    serializer=serializer)
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 280, in _publish
    maybe_declare(self.reply_queue(channel))
  File "/usr/local/lib/python3.6/site-packages/kombu/common.py", line 129, in maybe_declare
    return _maybe_declare(entity, declared, ident, channel, orig)
  File "/usr/local/lib/python3.6/site-packages/kombu/common.py", line 135, in _maybe_declare
    entity.declare(channel=channel)
  File "/usr/local/lib/python3.6/site-packages/kombu/entity.py", line 604, in declare
    self._create_exchange(nowait=nowait, channel=channel)
  File "/usr/local/lib/python3.6/site-packages/kombu/entity.py", line 611, in _create_exchange
    self.exchange.declare(nowait=nowait, channel=channel)
  File "/usr/local/lib/python3.6/site-packages/kombu/entity.py", line 185, in declare
    nowait=nowait, passive=passive,
  File "/usr/local/lib/python3.6/site-packages/amqp/channel.py", line 614, in exchange_declare
    wait=None if nowait else spec.Exchange.DeclareOk,
  File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 275, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by adampl** [comment]
@auvipy Does my case above satisfy your needs?

**Comment by th0th** [comment]
I am also having this issue. I am running celery worker on container via kubernetes. I am running [liveness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) `celery inspect ping`.

Worker logs this error:

```
[ERROR] celery.worker.pidbox: Control command error: ConnectionResetError(104, 'Connection reset by peer') 
Traceback (most recent call last): 
  File "/usr/lib/python3.6/site-packages/celery/worker/pidbox.py", line 46, in on_message 
    self.node.handle_message(body, message) 
  File "/usr/lib/python3.6/site-packages/kombu/pidbox.py", line 129, in handle_message 
    return self.dispatch(**body) 
  File "/usr/lib/python3.6/site-packages/kombu/pidbox.py", line 112, in dispatch 
    ticket=ticket) 
  File "/usr/lib/python3.6/site-packages/kombu/pidbox.py", line 135, in reply 
    serializer=self.mailbox.serializer) 
  File "/usr/lib/python3.6/site-packages/kombu/pidbox.py", line 265, in _publish_reply 
    **opts 
  File "/usr/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish 
    exchange_name, declare, 
  File "/usr/lib/python3.6/site-packages/kombu/messaging.py", line 203, in _publish 
    mandatory=mandatory, immediate=immediate, 
  File "/usr/lib/python3.6/site-packages/amqp/channel.py", line 1732, in _basic_publish 
    (0, exchange, routing_key, mandatory, immediate), msg 
  File "/usr/lib/python3.6/site-packages/amqp/abstract_channel.py", line 50, in send_method 
    conn.frame_writer(1, self.channel_id, sig, args, content) 
  File "/usr/lib/python3.6/site-packages/amqp/method_framing.py", line 166, in write_frame 
    write(view[:offset]) 
  File "/usr/lib/python3.6/site-packages/amqp/transport.py", line 275, in write 
    self._write(s) 
ConnectionResetError: [Errno 104] Connection reset by peer 
```

No such thing occurs when I disable liveness probe.
