### ISSUE TITLE
Python3: RDB giving error as "AttributeError: 'dict_keys' object has no attribute 'sort'"

### ISSUE THREAD

**Issue by anandtripathi5** [celery/celery#5019]
## Checklist

Issue is in celery version 4.2.0. Error is raised when we use rdb in celery inside the pyrepl python library

## Steps to reproduce
```
from celery.contrib import rdb
rdb.set_trace()
```

## Expected behavior
will connect to debugger

## Actual behavior
```
Traceback (most recent call last):
  File "/Users/anandtripathi/venv/smartcook3/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/anandtripathi/venv/smartcook3/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/anandtripathi/workspace/smartcook/workers/celery_app.py", line 42, in wrapper
    logger = logging.getLogger(__name__)
  File "/Users/anandtripathi/workspace/smartcook/workers/celery_app.py", line 42, in wrapper
    logger = logging.getLogger(__name__)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 112, in dispatch_line
    self.user_line(frame)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 261, in user_line
    self.interaction(frame, None)
  File "/Users/anandtripathi/venv/smartcook3/lib/python3.7/site-packages/pdb.py", line 245, in interaction
    completer = fancycompleter.setup()
  File "/Users/anandtripathi/venv/smartcook3/lib/python3.7/site-packages/fancycompleter.py", line 355, in setup
    completer = Completer()
  File "/Users/anandtripathi/venv/smartcook3/lib/python3.7/site-packages/fancycompleter.py", line 231, in __init__
    delims = readline.get_completer_delims()
  File "/Users/anandtripathi/venv/smartcook3/lib/python3.7/site-packages/pyrepl/readline.py", line 230, in get_completer_delims
    chars.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```

**Comment by auvipy** [comment]
celery 4.2.1 supports python 3.6 only

**Comment by thedrow** [comment]
Our next minor version will do so.

**Comment by georgepsarakis** [comment]
This does not seem like an issue with Celery: https://bitbucket.org/pypy/pyrepl/src/62630c596d7c47ec9c42abc9c16814dcb2813f9c/pyrepl/readline.py?at=default&fileviewer=file-view-default#readline.py-72

I would suggest that you open an issue to `pyrepl` instead.

**Comment by thedrow** [comment]
Maybe we should switch dependencies?
It seems like pyrepl isn't maintained very well.
What do you think?

**Comment by georgepsarakis** [comment]
@thedrow `pyrepl` is not a Celery dependency.
