### ISSUE TITLE
celery beat stop working

### ISSUE THREAD

**Issue by franchuk82** [celery/celery#5039]
**My Problem**
I'm using latest stable Celery (4.2.1) with redis backend on my project.
Redis running on local machine (custom instance with port 6384, just another one copy of origin instance), Beat after start wotk perfectly, but periodically after a while, it may be 30 minutes, 1 or more hours, or even several days he stop send task to worker, without any error.
But after restart (beat and worker) all this procedure become repeat.
I noticed it with celery of version 4.1.0, after i upgraded to 4.2.1 - no result, than i did downgrade to 4.0.2 - nothing changed
 
(celery) root@server:~# pip freeze|grep celery
celery==4.2.1
celery-once==2.0.0
(celery) root@server:~# pip freeze|grep redis
redis==2.10.6
redis-simple-cache==0.0.8

root@server~# dpkg -l|grep redis-server
ii  redis-server                      3:3.2.6-3+deb9u2               amd64        Persistent key-value database with network interface

**Configs**

> 1.  worker service

# cat /etc/systemd/system/celery-worker.service
```
[Unit]
Description=Celery Worker
After=network.target

[Service]
Type=forking
User=nobody
Group=nogroup
EnvironmentFile=-/etc/default/celery
Environment="config_type=production"
Environment="log_path=/var/log/celery/default.log"

WorkingDirectory=/opt/app/celery
ExecStart=/bin/bash -c 'cd ${CELERYD_CHDIR}; source ${ACTIVATE_BIN}; ${CELERY_BIN} multi start ${CELERYD_NODES} default \
  -A ${CELERY_APP} --loglevel=DEBUG --logfile=%n \
  --pidfile=${CELERYD_PID_FILE} ${CELERYD_OPTS}'
ExecStop=/bin/bash -c 'cd ${CELERYD_CHDIR}; source ${ACTIVATE_BIN}; ${CELERY_BIN} multi stopwait ${CELERYD_NODES} default \
  --pidfile=${CELERYD_PID_FILE} --loglevel=DEBUG --logfile=${CELERYD_LOG_FILE}'
ExecReload=/bin/bash -c 'cd ${CELERYD_CHDIR}; source ${ACTIVATE_BIN}; ${CELERY_BIN} multi restart ${CELERYD_NODES} default \
  -A {$CELERY_APP} --pidfile=${CELERYD_PID_FILE} --loglevel=DEBUG --logfile=${CELERYD_LOG_FILE} \
  ${CELERYD_OPTS} ' 


[Install]
WantedBy=multi-user.target
```

# cat /etc/default/celery
```
CELERYD_NODES="Q1 Q2 Q3 Q4 Q5 Q6"
CELERY_BIN="/opt/venv/celery/bin/celery"
ACTIVATE_BIN="/opt/venv/celery/bin/activate"
CELERY_APP="run_celery.celery"
CELERYD_CHDIR="/opt/app/celery"

CELERYD_OPTS="-Q:1 Q1 -Q:2 Q2 -Q:3 Q3 -Q:4 Q4 -Q:5 Q5 -Q:6 Q6 -c:1 1 -c:2 90 -c:3 90 -c:4 16 -c:5 2 -c:6 1 -c:7 1"

CELERYD_LOG_FILE="/var/log/celery/%N.log"
CELERYD_PID_FILE="/tmp/%N.pid"

CELERYD_USER="nobody"
CELERYD_GROUP="nogroup"

```
> 2. Beat service
# cat /etc/systemd/system/celery-beat.service 
```
[Unit]
Description=Celery Cron Beat
After=network.target
After=syslog.target

[Service]
Type=simple
User=nobody
Group=nogroup
Environment="VENVDIR=/opt/venv/celery_test"
Environment="BINDIR=/opt/app/celery"
Environment="config_type=production"
Environment="log_path=/var/log/celery/default_beat.log"
Environment="APP=beat"
ExecStart=/bin/bash -c "cd $BINDIR; source $VENVDIR/bin/activate; $VENVDIR/bin/celery beat -A run_celery.celery --loglevel=DEBUG --logfile=$log_path --pidfile=/tmp/celery-$APP.pid"
ExecStop=/bin/bash -c "cd $BINDIR; source $VENVDIR/bin/activate; $VENVDIR/bin/celery multi stopwait worker --pidfile=/tmp/celery-$APP.pid"

[Install]
WantedBy=multi-user.target
```

> 3. run app script
# cat /opt/app/celery/run_celery.py
```
import logging
import os

from celery import Celery, current_app
from celery.signals import setup_logging
from flask import Flask

import celery_log
import config as Config
from modules.cache import cache

from config import SimpleCacheRedisConfig

app = Flask(__name__)
from flask_mongoengine import MongoEngine

app.config.from_object(Config.Config)
MongoEngine(app)
cache.init_app(app=app)


@setup_logging.connect
def setup_logging(**kwargs):

    config_type = os.environ.get('config_type', 'development')
    if config_type == 'production':
        default_log_path = '/var/log/celery/default.log'
        log_path = os.environ.get('log_path', default_log_path)
    else:
        log_path = '/tmp/celery.log'

    celery_log.init_log(log_path=log_path, log_level=logging.DEBUG)

celery = Celery()
celery.config_from_object('celeryconfig')
```

> 4. Celery Config
# cat /opt/app/celery/celeryconfig.py
```
import os
from datetime import timedelta
from logging import getLogger

from celery.schedules import crontab
from kombu.serialization import register

from modules.celery.serializers import my_dumps
from modules.celery.serializers import my_loads

REDIS_PORT = '6379'
REDIS_DB_INDEX = '1'
config_type = os.environ.get('config_type', None)
if config_type == 'production':
    REDIS_DB_INDEX = '0'
    REDIS_PORT = '6384'
    timezone = 'UTC'
    broker_pool_limit = 0

register('customjson', my_dumps, my_loads, content_type='application/x-myjson', content_encoding='utf-8')

task_serializer = 'customjson'
result_serializer = 'customjson'
accept_content = ['customjson']

broker_url = 'redis://localhost:%s/%s' % (REDIS_PORT, REDIS_DB_INDEX)

result_backend = 'redis://localhost:%s/%s' % (REDIS_PORT, REDIS_DB_INDEX)

ONCE_REDIS_URL = 'redis://localhost:%s/%s' % (REDIS_PORT, REDIS_DB_INDEX)

redis_max_connections = 5000
REDIS_MAX_CONNECTIONS = 5000

broker_transport_options = {
   'max_connections': 5000
}
BROKER_TRANSPORT_OPTIONS = {
   'max_connections': 30
}

worker_state_db = '/tmp/celery_state.db'

task_ignore_result = True

ONCE_DEFAULT_TIMEOUT = 60 * 60
ONCE = {
    'backend': 'celery_once.backends.Redis',
    'settings': {
        'url': ONCE_REDIS_URL,
        'default_timeout': ONCE_DEFAULT_TIMEOUT
    }
}

imports = [
    "modules.module1.tasks",
    "modules.module2.tasks",
    "modules.module3.tasks",
    "modules.module4.tasks",
]


ENABLE_UTC = True
enable_utc = True
worker_redirect_stdouts = True
task_create_missing_queues = True
worker_hijack_root_logger = False
beat_scheduler = "modules.celery.scheduler.CustomScheduler"

beat_schedule = dict(
    task1=dict(
        task='modules.module1.tasks.task1',
        schedule=crontab(minute='0', hour="0")
    ),
    task2=dict(
        task='modules.module3.tasks.task2',
        schedule=crontab(minute='5', hour="0")
    ),
    task3=dict(
        task='modules.module2.tasks.task3',
        schedule=crontab(minute='57', hour="23")
    ),
    task4=dict(
        task='modules.module4.tasks.task4',
        schedule=timedelta(minutes=1)
    ),
    task5=dict(
        task='modules.module3.tasks.task5',
        schedule=timedelta(seconds=15)
    ),
    task6=dict(
        task='modules.module2.tasks.task6',
        schedule=timedelta(seconds=5)
    ),
    task7=dict(
        task='modules.module4.tasks.task7',
        schedule=timedelta(minutes=10)
    ),
)

```
Is it possible to fix this problem or to indicate where I have an error in the configuration?

**Comment by razerraz** [comment]
Seems I got the same issue : tasks stops working after 3 days, even non beat ones, with this log :
```
Exception ignored in: <function BaseEventLoop.__del__ at 0x72a08e40>
Traceback (most recent call last):
File "/usr/lib/python3.7/asyncio/base_events.py", line 609, in __del__
self.close()
File "/usr/lib/python3.7/asyncio/unix_events.py", line 55, in close
super().close()
File "/usr/lib/python3.7/asyncio/selector_events.py", line 97, in close
self._close_self_pipe()
File "/usr/lib/python3.7/asyncio/selector_events.py", line 104, in _close_self_pipe
self._remove_reader(self._ssock.fileno())
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
```

**Comment by auvipy** [comment]
python 3.7 is not supported with celery 4.2, try 3.6 and see

**Comment by franchuk82** [comment]
@auvipy can you suggest something on my question, there may be some ideas?

**Comment by tipfei** [comment]
i have the same problem as you. but it will recovery after about 10 minutes

**Comment by auvipy** [comment]
update with latest release or master?

**Comment by tedivm** [comment]
I'm also having this issue using the latest pypi release of celery. I'm seeing this in two applications (one that I've been using for years, another that I rewrote over the weekend).

All of my celery workers are dockerized. The container running yesterday was doing fine for about a day before it stopped scheduling beat tasks. 

Restarting the container was enough to get the scheduled task running again, but then the beat worker would *only* run beat tasks. Emptying rabbitmq, restarting the container, and deleting the beat schedule file did resolve the issue.

**Comment by tedivm** [comment]
This issue has also been seen in other packages-

https://github.com/celery/django-celery-beat/issues/27

**Comment by auvipy** [comment]
@tedivm could you try celery 4.4rc2 and post your problem in mailing list as well?
