### ISSUE TITLE
You can't execute queries until the end of the 'atomic' block.

### ISSUE THREAD

**Issue by oortega** [celery/celery#5048]
## Checklist

- [ x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I think it's when they update or add tasks from django admin
I get this error via sentry
## Expected behavior
Update the scheduler without this error.

## Actual behavior

```
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
  File "django_celery_beat/schedulers.py", line 216, in schedule_changed
    last, ts = self._last_timestamp, self.Changes.last_change()
  File "django_celery_beat/models.py", line 226, in last_change
    return cls.objects.get(ident=1).last_update
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 379, in get
    num = len(clone)
  File "django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "django/db/backends/base/base.py", line 428, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "

```
## Setup
amqp==2.3.2
billiard==3.5.0.4
celery==4.2.1
Django==1.10.4
django-celery-beat==1.1.1
django-celery-results==1.0.1
kombu==4.2.1
vine==1.1.4
redis==2.10.5

Thank you very much, I remain for your comments.

**Comment by rthille** [comment]
I don't think this: https://github.com/celery/django-celery-beat/pull/166/files change fixes this error. We're running django-celery-beat==1.2.0 which has the Pull-166 change and we're still seeing these errors.

**Comment by oortega** [comment]
@rthille can you please try this ? https://github.com/celery/django-celery-beat/issues/190#issuecomment-434069315

I have not updated my version of celery :/

**Comment by rthille** [comment]
@oortega Try what exactly?  Is there a patch/diff I'm missing?

**Comment by oortega** [comment]
there is a patch in comment @picturedots 

https://github.com/celery/django-celery-beat/issues/190#issuecomment-434069315

**Comment by rthille** [comment]
This: 
```
do all queries...
with transaction.atomic():
    do all writes
```
is pseudocode, not a patch.

**Comment by picturedots** [comment]
Yeah, I haven't fixed anything, just came up with a workaround method to prevent the error.

**Comment by fergyfresh** [comment]
@rthille that doesn't work for me.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 3, in wrapper
  File "/home/ferg/hoarder/app/historian/tests.py", line 240, in test_records_with_celery_brute_force
    electric_reading()
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/celery/local.py", line 193, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/celery/app/task.py", line 379, in __call__
    return self.run(*args, **kwargs)
  File "/home/ferg/hoarder/app/historian/tasks.py", line 95, in electric_reading
    r.save()
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "/home/ferg/hoarder/app/.venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 437, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```
Is what I get with your suggestion.

**Comment by rthille** [comment]
@fergyfresh I don't understand. I haven't made a suggestion anywhere here that I see, just a comment that I don't think this issue should be closed because we were still seeing the issue running code which supposedly fixed it.  We've since reverted to an older celery-beat and are waiting to upgrade until the issue seems actually resolved.

**Comment by fergyfresh** [comment]
@rthille I'm so sorry. I tagged the wrong person. What version of celery-beat are you on that you don't get this issue?

**Comment by rthille** [comment]
@fergyfresh No problem. Just didn't want someone thinking I had a solution I was hiding from everyone :-)
We've got requirements.txt pinning django-celery-beat at 1.1.1 and haven't seen the issue with that version.

**Comment by fergyfresh** [comment]
@rthille can you look under the hood to see what version of celery is being used `celery==???`

**Comment by rthille** [comment]
@fergyfresh `celery==4.2.1`.
