### ISSUE TITLE
Redis result backend KeyError: 'backend'  Unrecoverable error: SyntaxError('invalid syntax', ...)

### ISSUE THREAD

**Issue by yzinets** [celery/celery#5049]
## Checklist

software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.7.0
            billiard:3.5.0.4 redis:2.10.6
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/

broker_url: 'redis://localhost:6379//'
result_backend: 'redis://localhost:6379/'

## Steps to reproduce

app.py
```
...
celery_app = Celery('tasks', backend='redis://localhost:6379', broker='redis://localhost:6379')
...
```

`$ celery -A app.celery_app worker --loglevel=info`

## Actual behavior

```
[2018-09-13 09:30:26,584: CRITICAL/MainProcess] Unrecoverable error: SyntaxError('invalid syntax', ('/Users/yzinets/Desktop/RealEstate/realestate-bac
kend/venv/lib/python3.7/site-packages/celery/backends/redis.py', 22, 19, 'from . import async, base\n'))
Traceback (most recent call last):
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/bootsteps.py", line 115, in start    self.on_start()
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/apps/worker.py", line 139, in on_start
    self.emit_banner()
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/apps/worker.py", line 154, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/apps/worker.py", line 217, in startup_info
    results=self.app.backend.as_uri(),
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/app/base.py", line 1196, in backend
    return self._get_backend()
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/app/base.py", line 914, in _get_backend
    self.loader)
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/app/backends.py", line 70, in by_url
    return by_name(backend, loader), url
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/app/backends.py", line 50, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yzinets/Desktop/RealEstate/realestate-backend/venv/lib/python3.7/site-packages/celery/backends/redis.py", line 22
    from . import async, base
                      ^
SyntaxError: invalid syntax
```

## Possible solution
https://stackoverflow.com/questions/51273659/trouble-in-setting-celery-tasks-backend-in-python/51308631

**Comment by auvipy** [comment]
if you want to use python 3.7 with celery then install celery from the master branch. celery 4.2.x supports 3.6 only

**Comment by deepio** [comment]
I ran into this issue as well, it is probably because of the "async" keyword as we can see. 
```
  File "/usr/local/lib/python3.7/site-packages/celery/backends/redis.py", line 22
    from . import async, base
                      ^
```

Anyone else falling on this error, just do as @auvipy said. I can confirm it works

`pip install git+https://github.com/celery/celery.git`

**Comment by Jmosesee** [comment]
I'm getting the same error with python 3.6.7

**Comment by garyjh126** [comment]
Make sure you have both redis and channels-redis installed. I had this error raised due to only having channels-redis.
