### ISSUE TITLE
Socket error. Connection closed by server.

### ISSUE THREAD

**Issue by toti1212** [celery/celery#5069]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

```
software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.6.6
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:rpc://xx.xxx.xx.xx:xxxx//

BROKER_URL: 'redis://:********@xx.xxx.xx.xx:xxxx/0'
CELERY_RESULT_BACKEND: 'rpc://xx.xxx.xx.xx:xxxx//'
```
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
- We have a HAProxy in front of Django, therefore, it makes the load balancer of redis db (master / slave). The ip is from HAProxy. We try to change the final result but without success.

## Expected behavior
- 
## Actual behavior
We have this errors:

```

| [2018-09-24 17:08:03,223: INFO/MainProcess] Connected to redis://:**@xx.xxx.xx.xx:xxxx/0
| [2018-09-24 17:08:03,233: INFO/MainProcess] mingle: searching for neighbors
| [2018-09-24 17:08:04,244: INFO/MainProcess] mingle: all alone
| [2018-09-24 17:08:25,266: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
| Traceback (most recent call last):
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 177, in _read_from_socket
| raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
| OSError: Connection closed by server.
| During handling of the above exception, another exception occurred:
| Traceback (most recent call last):
| File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2408, in _execute
| return command(*args)
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
| response = self._parser.read_response()
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
| response = self._buffer.readline()
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
| self._read_from_socket()
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 191, in _read_from_socket
| (e.args,))
| redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
| During handling of the above exception, another exception occurred:
| Traceback (most recent call last):
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 177, in _read_from_socket
| raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
| OSError: Connection closed by server.
| During handling of the above exception, another exception occurred:
| Traceback (most recent call last):
| File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
| blueprint.start(self)
| File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
| step.start(parent)
| File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
| c.loop(*c.loop_args())
| File "/usr/local/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
| next(loop)
| File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
| cb(*cbargs)
| File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 1040, in on_readable
| self.cycle.on_readable(fileno)
| File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
| chan.handlers[type]()
| File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 667, in _receive
| ret.append(self._receive_one(c))
| File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 678, in _receive_one
| response = c.parse_response()
| File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2430, in parse_response
| return self._execute(connection, connection.read_response)
| File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2419, in _execute
| return command(*args)
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
| response = self._parser.read_response()
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
| response = self._buffer.readline()
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
| self._read_from_socket()
| File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 191, in _read_from_socket
| (e.args,))
| redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
```

**Comment by TopcoderWuxie** [comment]
If you have solved this problem, can you tell me how to solve this problem?

**Comment by toti1212** [comment]
> If you have solved this problem, can you tell me how to solve this problem?

Sorry but we decide wait to new release. It is possible will be solved.

**Comment by auvipy** [comment]
is it fixed in celery 4.3 or even in master?

**Comment by toti1212** [comment]
We had to rollback the solution. Sorry but can't prove it

**Comment by auvipy** [comment]
could you try rabbitmq as broaker and redis or anything else as result backend and et us know?
