### ISSUE TITLE
TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by aaronluoq** [celery/celery#5071]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I have a scheduled task that will query the database，But occasionally you will receive errors like this
```
OperationalError: (2003, "Can't connect to MySQL server on 'xxxx.database.azure.com' (110)")

```

I created another task as follows
 ```
@app.task(bind=True, ignore_result=True)
def telnet(self):
    database_conf = settings.DATABASES['default']
    host = database_conf['HOST']
    port = int(database_conf['PORT'])
    logger.info('telnet %s %s begin' % (host, port))

    tn = None
    try:
        tn = telnetlib.Telnet(host, port)
        logger.info(tn.read_until(b'native_password'))
    finally:
        if tn:
            tn.close()
```
But occasionally you will receive errors like this
```
Traceback (most recent call last):
  File ".pyenv/versions/3.6.3/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File ".pyenv/versions/3.6.3/lib/python3.6/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "project/exchange/tasks.py", line 612, in telnet
    tn = telnetlib.Telnet(host, port)
  File "pyenv/versions/3.6.3/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File ".pyenv/versions/3.6.3/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File ".pyenv/versions/3.6.3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File ".pyenv/versions/3.6.3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```

But the network request is not received on the corresponding machine

The execution frequency of each task is once per second

celery report
```
software -> celery:4.1.1 (latentcall) kombu:4.2.1 py:3.6.3
            billiard:3.5.0.4 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

```

**Comment by auvipy** [comment]
you can try django celery results

**Comment by MultiSuperK** [comment]
dear brother; we have same problem with celery worker;
we have 1 slow worker  to process the bigdata task(the data size perhaps 3-4GBytes)
After 2-3 task runs，we found the new task is cannot connect to redis with error 110 in ths new task runtime.
maybe the oom problem trigger a socket(io-source?) resource init error?
