### ISSUE TITLE
Task state can not be updated from within a thread when using RPC

### ISSUE THREAD

**Issue by MS-AvivG** [celery/celery#5100]
The following task:

    @task(bind=True, name='tasks.test')
    def test(self):
        # Update the task state
        def x():
            self.update_state(
                state='PROGRESS',
                ...
            )
        # Making the future synchronous to ensure that function x is called
        # before the task was finished
        threadpool_executor.submit(x).result()

raises the following exception when executed:

    Traceback (most recent call last):
      File "...\lib\site-packages\celery\app\trace.py", line 382, in trace_task
        R = retval = fun(*args, **kwargs)
      File "...\lib\site-packages\celery\app\trace.py", line 641, in __protected_call__
        return self.run(*args, **kwargs)
      File "...server.py", line 357, in test
        state.threadpool.submit(x).result()
      File "C:\Python37\Lib\concurrent\futures\_base.py", line 425, in result
        return self.__get_result()
      File "C:\Python37\Lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "C:\Python37\Lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "...server.py", line 354, in x
        self.update_state(
      File "...\lib\site-packages\celery\app\task.py", line 914, in update_state
        self.backend.store_result(task_id, meta, state, **kwargs)
      File "...\lib\site-packages\celery\backends\rpc.py", line 202, in store_result
        routing_key, correlation_id = self.destination_for(task_id, request)
      File "...\lib\site-packages\celery\backends\rpc.py", line 182, in destination_for
        'RPC backend missing task request for {0!r}'.format(task_id))
    RuntimeError: RPC backend missing task request for None

after diving into celery's code, I managed to create a simple workaround by passing the "request" (although it is not a signature parameter and not documented):

changing

    self.update_state(
        state='PROGRESS',
        ...
    )

to 

    self.update_state(
        request=self.request
        state='PROGRESS',
        ...
    )

Any explanation (or fix) will be useful

**Comment by MS-AvivG** [comment]
> Dear Aviv,
> 
> so what I think happened here is as follows:
> 
> You are sending the function for updating the task state to the concurrent.futures (https://docs.python.org/3/library/concurrent.futures.html#module-concurrent.futures)
> 
> which gets executed after the task has actually finished it's execution.
> When the task is actually executed, it doesn't have a request object anymore.
> 
> What you are doing in fact is monkeypatching the `@property` method of a Task, with the request object you have in memory at the moment.
> 
> So your updating of the state really doesn't make much sense, and it can actually create other problems in future.
> 
> It looks like you are trying to manage states of tasks from an alternate thread, and I would advise to not do this and possibly take a different approach to your problem.
> 
> Try to explain in a comment what it is that you are trying to exactly do with the threadpool_executor and maybe we can suggest a different approach.

`.result()` actually blocks inside the class, so the state change doesn't happen after execution.
