### ISSUE TITLE
Multiple redis sentinels on backend URI causes banner format exception

### ISSUE THREAD

**Issue by FloatingGhost** [celery/celery#5117]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

Running from commit 21baef53c39bc190. Report cannot be run since nothing is able to start.

## Steps to reproduce

Create a minimal worker, but use a backend URI that specifies a failover set [as specified by the documentation](http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#configuration)

Hostnames do not matter since no connection attempt will be made

```python
from celery import Celery

c = Celery(
    __name__,
    broker="sentinel://host1:8080;sentinel://host2:8080;sentinel://host3:8080",
    backend="sentinel://host1:8080;sentinel://host2:8080;sentinel://host3:8080"
)


@c.task
def add(x, y):
    return x + y
```

Run as normal with `celery -A minimal_celery worker`

## Expected behavior

Worker loads and starts as normal

## Actual behavior

Celery banner formatter attempts to parse the string as a single URI and cannot extract the port number

```
[2018-10-16 17:47:25,407: CRITICAL/MainProcess] Unrecoverable error: ValueError("invalid literal for int() with base 10: '8080;sentinel:'",)
Traceback (most recent call last):
  File "ENV/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "ENV/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "ENV/celery/apps/worker.py", line 139, in on_start
    self.emit_banner()
  File "ENV/celery/apps/worker.py", line 154, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "ENV/celery/apps/worker.py", line 217, in startup_info
    results=self.app.backend.as_uri(),
  File "ENV/celery/backends/base.py", line 135, in as_uri
    url = maybe_sanitize_url(self.url or '')
  File "ENV/kombu/utils/url.py", line 92, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "ENV/kombu/utils/url.py", line 85, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "ENV/kombu/utils/url.py", line 52, in url_to_parts
    parts.port,
  File "/usr/lib64/python3.6/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '8080;sentinel:'
```

**Comment by yoncan** [comment]
@FloatingGhost  like this #5146   #5142

**Comment by auvipy** [comment]
closing as duplicate
