### ISSUE TITLE
Celery periodic task not running occasionally

### ISSUE THREAD

**Issue by csabakeszegh** [celery/celery#5128]
Hi,
I've just started to play with celery, and running periodic tasks confuses me. Modified the [sample code](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#entries) to run a task every 1s.

    from celery import Celery
    from celery.schedules import crontab
    app = Celery()
    app.conf.broker_url = 'redis://localhost:6379/0'

    @app.on_after_configure.connect
    def setup_periodic_tasks(sender, **kwargs):
        sender.add_periodic_task(1.0, test.s('hello'), name='add every 1')

    @app.task
    def test(arg):
        print(arg)

Starting with ``celery -A celery_example worker -B`` the task runs usually every second, but sometime there are gaps. Example output:

```
[2018-10-20 09:05:19,321: WARNING/ForkPoolWorker-2] hello
[2018-10-20 09:05:20,321: WARNING/ForkPoolWorker-6] hello
[2018-10-20 09:05:24,321: WARNING/ForkPoolWorker-5] hello
[2018-10-20 09:05:25,320: WARNING/ForkPoolWorker-3] hello
```

With DEBUG logging it seems the scheduler has sent the task, but nobody accepted:

```
[2018-10-20 09:07:45,456: INFO/Beat] Scheduler: Sending due task add every 1 (celery_example.test)
[2018-10-20 09:07:45,457: DEBUG/Beat] celery_example.test sent. id->ef78f385-8e2b-4b99-9abc-01eec72c3824
[2018-10-20 09:07:45,458: DEBUG/Beat] beat: Waking up now.
[2018-10-20 09:07:46,456: INFO/Beat] Scheduler: Sending due task add every 1 (celery_example.test)
[2018-10-20 09:07:46,458: DEBUG/Beat] celery_example.test sent. id->442e9c20-53d1-4337-a8a2-65979cedd826
[2018-10-20 09:07:46,458: INFO/MainProcess] Received task: celery_example.test[442e9c20-53d1-4337-a8a2-65979cedd826]  
[2018-10-20 09:07:46,458: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x101764c80> (args:(u'celery_example.test', u'442e9c20-53d1-4337-a8a2-65979cedd826', {u'origin': u'gen89912@kcs-mbp.local', u'lang': u'py', u'task': u'celery_example.test', u'group': None, u'root_id': u'442e9c20-53d1-4337-a8a2-65979cedd826', u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u''}, u'expires': None, u'correlation_id': u'442e9c20-53d1-4337-a8a2-65979cedd826', u'retries': 0, u'timelimit': [None, None], u'argsrepr': u"('hello',)", u'eta': None, u'parent_id': None, u'reply_to': u'1ce10e14-0b34-3523-8e0b-fe14322ed61a', u'shadow': None, u'id': u'442e9c20-53d1-4337-a8a2-65979cedd826', u'kwargsrepr': u'{}'}, '[["hello"], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]', u'application/json', u'utf-8') kwargs:{})
[2018-10-20 09:07:46,458: DEBUG/Beat] beat: Waking up now.
[2018-10-20 09:07:46,459: DEBUG/MainProcess] Task accepted: celery_example.test[442e9c20-53d1-4337-a8a2-65979cedd826] pid:89907
[2018-10-20 09:07:46,459: WARNING/ForkPoolWorker-5] hello
[2018-10-20 09:07:46,460: INFO/ForkPoolWorker-5] Task celery_example.test[442e9c20-53d1-4337-a8a2-65979cedd826] succeeded in 0.000647652952466s: None
```

OS: macOS 10.13.6 (17G65)
celery version: 4.2.1 (windowlicker)
redis: Redis server v=4.0.11 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=548a63e6520c3bce

Any explanation is really appreciated. Thanks,
csaba

**Comment by Skeen** [comment]
I can't seem to reproduce this. Can you include more information about the state of the machine when jobs miss out? - Is there excessive load on the system, cpu, io, etc?

**Comment by csabakeszegh** [comment]
Thanks for the reply. On Ubuntu 16.04 (celery: 4.2.1 (windowlicker), redis: Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42) it works as expected.

Btw on macOS I can't see any suspicious CPU usage. Python: ~1.5%, redis-server: ~0.1%. The most CPU intensive app is Activity Monitor: ~10%. I/O usage seems also fine. In a 10s time frame there are usually 2-3 gaps. Could you guide me, how to collect more debug info?

**Comment by csabakeszegh** [comment]
Okay, it was my fault. There was another celery [app](https://blog.miguelgrinberg.com/post/using-celery-with-flask) running. The request was handled in that task:

```
[2018-10-22 11:49:11,811: ERROR/MainProcess] Received unregistered task of type u'celery_example.test'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
'[["hello"], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]' (84b)
Traceback (most recent call last):
  File "/Users/csaba.keszegh/work/flask_app/venv/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: u'celery_example.test'
```

**Comment by csabakeszegh** [comment]
Okay, it was my fault. There was another celery [app](https://blog.miguelgrinberg.com/post/using-celery-with-flask) running. The request was handled in that task:

```
[2018-10-22 11:49:11,811: ERROR/MainProcess] Received unregistered task of type u'celery_example.test'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
'[["hello"], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]' (84b)
Traceback (most recent call last):
  File "/Users/csaba.keszegh/work/flask_app/venv/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
KeyError: u'celery_example.test'
```
