### ISSUE TITLE
AsyncResult: TypeError in failed method

### ISSUE THREAD

**Issue by sp1thas** [celery/celery#5150]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Project Report
```bash
software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:2.7.15rc1
            billiard:3.5.0.4 redis:2.10.6
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://127.0.0.1:6379/0

broker_url: u'redis://127.0.0.1:6379/0'
result_backend: u'redis://127.0.0.1:6379/0'
task_routes: {
    u'celery.crawler.fbk.download_alt_text': {   u'queue': u'fbk_alt_text'}}
```
## Steps to reproduce
I created a list of `celery.result.AsyncResult` objects. During the iteration over the list, I'm checking for failed tasks but sometimes I'm getting the following error.

## Expected behavior
return `True` or `False`
## Actual behavior
```bash
Traceback (most recent call last):
  File "downloader.py", line 289, in <module>
    alt_text_only(args)
  File "downloader.py", line 264, in alt_text_only
    if result.failed():
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/result.py", line 319, in failed
    return self.state == states.FAILURE
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/result.py", line 471, in state
    return self._get_task_meta()['status']
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/result.py", line 410, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 365, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 680, in _get_task_meta_for
    return self.decode_result(meta)
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 284, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 280, in meta_from_decoded
    meta['result'] = self.exception_to_python(meta['result'])
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 260, in exception_to_python
    exc = cls(*exc_msg if isinstance(exc_msg, tuple) else exc_msg)
TypeError: __init__() takes at least 3 arguments (2 given)
```

**Comment by georgepsarakis** [comment]
Can you debug and investigate what class is used as `cls` in this case?

**Comment by sp1thas** [comment]
I got the same error using the `ready()` method:

```bash
Traceback (most recent call last):
  File "downloader.py", line 292, in <module>
    alt_text_only(args)
  File "downloader.py", line 267, in alt_text_only
    if result.ready():
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/result.py", line 311, in ready
    return self.state in self.backend.READY_STATES
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/result.py", line 471, in state
    return self._get_task_meta()['status']
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/result.py", line 410, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 367, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 682, in _get_task_meta_for
    return self.decode_result(meta)
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 286, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 282, in meta_from_decoded
    meta['result'] = self.exception_to_python(meta['result'])
  File "/home/simakis/.p2env/local/lib/python2.7/site-packages/celery/backends/base.py", line 262, in exception_to_python
    exc = cls(*exc_msg if isinstance(exc_msg, tuple) else exc_msg)
TypeError: __init__() takes at least 3 arguments (2 given)
```
I used some prints  to find out which class is used and the given patameters:
`cls`: `<class 'urllib3.exceptions.MaxRetryError'>`
`exc_msg`: `[u"HTTPConnectionPool(host='127.0.0.1', port=45859): Max retries exceeded with url: /session/22c0a25233507721dc8c1f08303a49f8/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f32700ef790>: Failed to establish a new connection: [Errno 111] Connection refused',))"]`

**Comment by georgepsarakis** [comment]
@sp1thas this exception class seems to have a specialized constructor signature which can not be handled correctly:

```python
class MaxRetryError(RequestError):
    "Raised when the maximum number of retries is exceeded."

    def __init__(self, pool, url, reason=None):
```

I would advise you to catch this specific exception in your task and reraise using a different exception class that accepts a single argument during instantiation (`message`).
