### ISSUE TITLE
Unable to add arguments when cloning chain

### ISSUE THREAD

**Issue by Simage** [celery/celery#5193]
## Checklist

Python 3.6.6
Celery 4.2.1

## Steps to reproduce
in a file named tasks.py

```
@app.task
def add(x,y):
    return x+y
```
and then from the python shell

```
>>> from tasks import add
>>> chain=add.s()|add.s(1)
>>> chain
magic_carpet.celery.add() | add(1)
>>> chain.args
()
>>> chain.delay(2,2)
<AsyncResult: fcc97c30-4700-47a6-aeb6-ffca19a1446f>
>>> cloned_chain=chain.clone(args=(2,))
>>> cloned_chain.args
()
>>> cloned_chain.delay(2)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/bjorn/.local/share/virtualenvs/magic_carpet-PeFVEcL-/lib/python3.6/site-packages/celery/canvas.py", line 179, in delay
    return self.apply_async(partial_args, partial_kwargs)
  File "/home/bjorn/.local/share/virtualenvs/magic_carpet-PeFVEcL-/lib/python3.6/site-packages/celery/canvas.py", line 557, in apply_async
    dict(self.options, **options) if options else self.options))
  File "/home/bjorn/.local/share/virtualenvs/magic_carpet-PeFVEcL-/lib/python3.6/site-packages/celery/canvas.py", line 584, in run
    first_task.apply_async(**options)
  File "/home/bjorn/.local/share/virtualenvs/magic_carpet-PeFVEcL-/lib/python3.6/site-packages/celery/canvas.py", line 218, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/bjorn/.local/share/virtualenvs/magic_carpet-PeFVEcL-/lib/python3.6/site-packages/celery/app/task.py", line 513, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: add() missing 1 required positional argument: 'y'
>>> 
```
## Expected behavior

The arguments and keyword arguments passed into the clone method should be prepended to those in the source chain

## Actual behavior
An unmodified copy of the source chain is returned

this is due to the args to the chain being explicitly set to an empty tuple in the `__init__` of `_chain`. as I see it two options exist to correct this issue
- Update the `__init__` to accept an args and kwargs keyword and handle them as needed 
- Update the `clone` method of the `_chain` class to modify the first task to reflect the updated arguments

It appears that groups have the same issue, with the same options for correcting it.

**Comment by Simage** [comment]
For the time being, I am working around this issue by creating my own clone function that implements the second approach to solving this issue

```python
def clone_signature(sig, args=(), kwargs=(), **opts):
    if sig.subtask_type and sig.subtask_type != "chain":
        raise NotImplementedError(
            "Cloning only supported for Tasks and chains, not %s" % sig.subtask_type
        )
    clone = sig.clone()
    if hasattr(clone, "tasks"):
        t = clone.tasks[0]
    else:
        t = clone
    args, kwargs, opts = t._merge(args=args, kwargs=kwargs, options=opts)
    t.update(args=args, kwargs=kwargs, options=deepcopy(opts))
    return clone
```

**Comment by auvipy** [comment]
could you come with a PR with an appropriate test case?

**Comment by auvipy** [comment]
I am willing to know the current status of the issue. can anyone verify on master?

**Comment by thedrow** [comment]
@auvipy You have a test case, include it in the test suite instead of asking.
That way we'll know for sure.
