### ISSUE TITLE
CRITICAL/MainProcess] Unrecoverable error: TypeError("unhashable type: 'list'",)

### ISSUE THREAD

**Issue by dejlek** [celery/celery#5204]
Amazon Linux 2, Python 3.6, Celery 4.2.1, Redis/prefork concurrency

Worker sometimes exits with the following in the log:

[2018-11-28 17:38:44,214: CRITICAL/MainProcess] Unrecoverable error: TypeError("unhashable type: 'list'",)

    Traceback (most recent call last): File "/opt/celery/venv/lib64/python3.6/site-packages/celery/worker/worker.py", line 205, in start self.blueprint.start(self) File "/opt/celery/venv/lib64/python3.6/site-packages/celery/bootsteps.py", line 119, in start step.start(parent) File "/opt/celery/venv/lib64/python3.6/site-packages/celery/bootsteps.py", line 369, in start return se
    Traceback (most recent call last):
    File "/opt/celery/venv/lib64/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
    File "/opt/celery/venv/lib64/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
    File "/opt/celery/venv/lib64/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
    File "/opt/celery/venv/lib64/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
    File "/opt/celery/venv/lib64/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
    File "/opt/celery/venv/lib64/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
    File "/opt/celery/venv/lib64/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
    File "/opt/celery/venv/lib64/python3.6/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
    File "/opt/celery/venv/lib64/python3.6/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
    File "/opt/celery/venv/lib64/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
    File "/opt/celery/venv/lib64/python3.6/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
    File "/opt/celery/venv/lib64/python3.6/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
    File "/opt/celery/venv/lib64/python3.6/site-packages/kombu/transport/virtual/base.py", line 633, in _callback
    return callback(message)
    File "/opt/celery/venv/lib64/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
    File "/opt/celery/venv/lib64/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]

**To reproduce**:

    res = app.send_task(("one", "two"), (arg1, arg2))
    print(res.get())

Yes, I know I am giving it a tuple as task name, but this happened because a busy developer deleted the old task name and forgot to write a new one. That is not a problem. The _real_ problem is that this causes the worker that picks and tries to execute the task to _crash_!

**Comment by kcolton** [comment]
@dejlek Any hints/leads on if it's something about Python 3.6 specifically or pre-fork Redis or Amazon Linux.

Having a test case that can reproducibly fail would make it a lot easier for anyone to spin on it and maybe come up with PR.

**Comment by dejlek** [comment]
There are other related issues - it seems that people got the same exception in few different cases. I really can't reproduce it - it just happens randomly and I see it in the logs...

**Comment by cronywalls** [comment]
The hash() is a built-in python method, used to return a unique number . This can be applied to any user-defined object which won’t get changed once initialized. This property is used mainly in dictionary keys .


TypeError: [unhashable type](http://net-informations.com/python/iq/unhashable.htm): 'list' usually means that you are trying to use a list as an hash argument. This means that when you try to hash an unhashable object it will result an error. For ex. when you use a list as a key in the dictionary , this cannot be done because lists can't be hashed. The standard way to solve this issue is to cast a list to a tuple .

**Comment by dejlek** [comment]
I am still getting this error and nowhere in a task that triggers this behaviour I use lists!

**Comment by dejlek** [comment]
Here is another one (also crashes the worker):
````
[2019-07-29 16:38:33,667: CRITICAL/MainProcess] Unrecoverable error: TypeError("unhashable type: 'list'",)
Traceback (most recent call last):
  File "/opt/celery/lib64/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/opt/celery/lib64/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/celery/lib64/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/opt/celery/lib64/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/opt/celery/lib64/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/celery/lib64/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/opt/celery/lib64/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/opt/celery/lib64/python3.6/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/opt/celery/lib64/python3.6/site-packages/kombu/transport/redis.py", line 1052, in on_readable
    self.cycle.on_readable(fileno)
  File "/opt/celery/lib64/python3.6/site-packages/kombu/transport/redis.py", line 348, in on_readable
    chan.handlers[type]()
  File "/opt/celery/lib64/python3.6/site-packages/kombu/transport/redis.py", line 736, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/opt/celery/lib64/python3.6/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
  File "/opt/celery/lib64/python3.6/site-packages/kombu/transport/virtual/base.py", line 633, in _callback
    return callback(message)
  File "/opt/celery/lib64/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/opt/celery/lib64/python3.6/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    strategy = strategies[type_]
TypeError: unhashable type: 'list'
````

**Comment by xirdneh** [comment]
Reopening this issue since it's being reported as a bug again.
@dejlek Please post a way to reproduce and your Celery config.

**Comment by dejlek** [comment]
I've updated the document with explanation how to reproduce the problem.

**Comment by koslibpro** [comment]
Hello all,

@dejlek I stumbled upon the same issue. What is your redis version? (the python package, not the server itself). In my case, it was 4.x.x and I resolved the issue by downgrading to `redis==3.2.0`. RedisTransport seems to be causing this issue, however, not celery.

**Comment by iamareebjamal** [comment]
@koslibpro @auvipy OK, then redis should be capped in celery 

https://github.com/celery/celery/blob/f2ddd894c32f642a20f03b805b97e460f4fb3b4f/requirements/extras/redis.txt#L1

**Comment by thedrow** [comment]
@auvipy Why did you close the issue?
Downgrading is a workaround, not a solution.

**Comment by ThanKarab** [comment]
I stumbled upon the same issue and the problem was that instead of sending a signature, for example:
```
task_signature = "package.package.package.task"

celery_app.signature(task_signature)
```

I was sending:
```
task_signature = "package.package.package.task",

celery_app.signature(task_signature)
```

The difference is just a typo, a comma at the end of the string...
