### ISSUE TITLE
Config cassandra backend port config not work

### ISSUE THREAD

**Issue by tam04101993** [celery/celery#5226]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.12
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:cassandra

broker_url: u'amqp://guest:********@localhost:32781//'
cassandra_entry_ttl: 86400
cassandra_table: 'tasks_result'
cassandra_port: '61003'
cassandra_write_consistency: 'ONE'
cassandra_read_consistency: 'ONE'
include: [u'celery_for_medium.tasks']
result_backend: 'cassandra'
cassandra_keyspace: u'********'
cassandra_servers: ['localhost']
```
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Expected behavior
Result data should write correctly to cassandra database at: **localhost:61003**
## Actual behavior
```
[2018-12-07 14:28:17,815: ERROR/ForkPoolWorker-1] Control connection failed to connect, shutting down Cluster:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1301, in cassandra.cluster.Cluster.connect
    self.control_connection.connect()
  File "cassandra/cluster.py", line 2802, in cassandra.cluster.ControlConnection.connect
    self._set_new_connection(self._reconnect_internal())
  File "cassandra/cluster.py", line 2845, in cassandra.cluster.ControlConnection._reconnect_internal
    raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {'localhost': error(111, "Tried connecting to [('localhost', 9042)]. Last error: Connection refused")})
```

**Comment by thedrow** [comment]
@auvipy Why is this closed?

**Comment by thedrow** [comment]
@auvipy ?
