### ISSUE TITLE
chord callback method can not execute when result_expires =0 or None

### ISSUE THREAD

**Issue by lvscup** [celery/celery#5237]
## Checklist
os: ubuntu 16.04
celery version: 4.2.1
python version: 3.6
broker: redis
backend: redis

## Steps to reproduce
* chord(group_tasks)(success_callback.s().on_error(on_error_callback.s()))
* celery.conf.update(result_expires=0) or celery.conf.update(result_expires=None)

## Expected behavior
* success_callback method will execute
* task results' ttl is -1(never expire)

### current
* success_callback method has not executed
* task results' ttl is -1

### another case
* when set result_expires=3600(neithor 0 or None)，success_callback can execute, task results' ttl is correct

can anybody help me?

**Comment by thedrow** [comment]
Can you please provide a test case I can use to reproduce the problem?
Preferably one that we can execute.

**Comment by lou-viannay** [comment]
software -> celery:4.2.1 (windowlicker) kombu:4.2.2-post1 py:2.7.15rc1
            billiard:3.5.0.5 redis:3.0.1
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:django-db


Hi, I am having a similar problem.  I've set (in Django settings):` CELERY_RESULT_EXPIRES = None`.
According to the documentation, this will prevent the deletion of the results.  However, celery beat worker fails with:
`[2019-03-04 04:08:05,065: INFO/MainProcess] Received task: celery.backend_cleanup[e8cd236f-76a2-4664-aa6d-3efe2385e84e]  

[2019-03-04 04:08:06,115: ERROR/ForkPoolWorker-3] Task celery.backend_cleanup[e8cd236f-76a2-4664-aa6d-3efe2385e84e] raised unexpected: TypeError("unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'",)

Traceback (most recent call last):
  File "/home/lou/.virtualenvs/webroute/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)

  File "/home/lou/.virtualenvs/webroute/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)

  File "/home/lou/.virtualenvs/webroute/local/lib/python2.7/site-packages/celery/app/builtins.py", line 25, in backend_cleanup
    app.backend.cleanup()

  File "/home/lou/.virtualenvs/webroute/local/lib/python2.7/site-packages/django_celery_results/backends/database.py", line 68, in cleanup
    self.TaskModel._default_manager.delete_expired(self.expires)

  File "/home/lou/.virtualenvs/webroute/local/lib/python2.7/site-packages/django_celery_results/managers.py", line 161, in delete_expired
    self.get_all_expired(expires).update(hidden=True)

  File "/home/lou/.virtualenvs/webroute/local/lib/python2.7/site-packages/django_celery_results/managers.py", line 155, in get_all_expired
    return self.filter(date_done__lt=now() - maybe_timedelta(expires))

TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'`


If I set `CELERY_RESULT_EXPIRES = 0`, task results still gets deleted as soon as cleanup task is run.

**Comment by auvipy** [comment]
can anyone provide a test case for this?

**Comment by laixintao** [comment]
Hi @auvipy it looks like a bug.

reproduce by:

```
# filename is main.py

from celery import Celery


app = Celery(
    "demo",
    broker="redis://127.0.0.1:6379/1",
    backend="redis://127.0.0.1:6379/1",
)

app.conf.update(
    result_expires=0,  # never expired, bug
)


@app.task
def add(x, y):
    return x + y


@app.task
def xsum(l):
    return sum(l)
```

start celery by:
```
celery -A main worker -l INFO
```

run this script:

```
# filename is put_job.py
# run: python put_job.py
from main import add, xsum
from celery import group, chord
g = group(add.s(i, i) for i in range(2))
c = chord(g, xsum.s())
print(c)
r = c()
print("job is : ", r)
result = r.get()  # will block here
print(result)
```

You will get(hang forever):
```
python add_job.py
%main.xsum([add(0, 0), add(1, 1)])
job is :  31b81bc6-1699-4ccc-bde7-87a1c15bb2b4
```

And when press `Ctrl + C`, you will get traceback like:
```
python add_job.py
%main.xsum([add(0, 0), add(1, 1)])
job is :  ddcf3f95-6e8c-4973-b1f1-4ea106910735
^CTraceback (most recent call last):
  File "add_job.py", line 8, in <module>
    result = r.get()  # will block here
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/celery/result.py", line 223, in get
    return self.backend.wait_for_pending(
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/celery/backends/asynchronous.py", line 199, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/celery/backends/asynchronous.py", line 265, in _wait_for_pending
    for _ in self.drain_events_until(
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/celery/backends/asynchronous.py", line 54, in drain_events_until
    yield self.wait_for(p, wait, timeout=interval)
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/celery/backends/asynchronous.py", line 63, in wait_for
    wait(timeout=timeout)
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/celery/backends/redis.py", line 150, in drain_events
    message = self._pubsub.get_message(timeout=timeout)
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/local/var/pyenv/versions/t2/lib/python3.8/site-packages/redis/_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
KeyboardInterrupt
```
