### ISSUE TITLE
Connection reset by peer during on_error() callback calling a task

### ISSUE THREAD

**Issue by AbdealiJK** [celery/celery#5247]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.

```
versions: celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.6.5 billiard:3.5.0.4 py-amqp:2.3.2
system: Linux arch:64bit imp:CPython (Anaconda)
transport:   redis://:**@REDIS_URL:6379/1
results:     redis://:**@REDIS_URL:6379/2
```
This issue seems very similar to https://github.com/celery/celery/issues/4226 but seems to be happening in the error handling part.

## Steps to reproduce

I have 2 workers with 2 different queues: bulkymachines, dbconn
The `bulkymachines` queue is on a good computer meant for heavy math (high ram, cpu, etc). It does not have DB connectivity.
The `dbconn` queue is on the same machine as my Flask API server (and has DB connectivity).

We are trying to do some heavy computation and save it into our MySQL DB so it can be shown to users via the API. The queue-allocation is done using CELERY_ROUTES config variable.

I use the args: `--loglevel info --pool solo --without-gossip --concurrency 1`
        
This is mostly pseudo-ish code I've written based on my overall much more complex structure.

```python
@celery.task
def start_job(job_id):
    # This runs on a queue="dbconn"
    return {"job_id": job_id}

@celery.task
def heavy_computation(data):
    # This runs on a queue="bulkymachines"
    print("Running heavy_computation ...")
    import time
    time.sleep(3 * 60 * 60)  # Long running computation ...
    raise ValueError("Some error occured in computation")
    data['computation_result'] = 4
    return data

@celery.task
def local_error_handler(request, exc, traceback, job_id):
    # The on_error() callback for the computation task. It runs on local worker only.
    print("Job complete ERROR -> job_id={} task_id={}".format(job_id, request.id))
    msg = "job_id = {} got error: {}".format(job_id, str(exc))
    save_error_to_database.delay(job_id, msg)

@celery.task
def save_error_to_database(job_id, msg):
    # Code to connect to Database and save the message. This runs on a queue="dbconn"
    job_logs =  # Get job_logs handler
    job_logs.write(job_id, msg)

@celery.task
def save_result_to_db(data)
    # Code to connect to Database and save the computation result. This runs on a queue="dbconn"
    job_result =  # Get job_result handler
    job_result.write(job_id, data['computation_result'])
```

Running the task:
```python
job_id = 129
err_handler = local_error_handler.s(job_id=job_id)
async_task = celery.chain(
    start_job.s(),
    heavy_computation.s().on_error(err_handler)
    save_result_to_db.s()
async_result = async_task(job_id)
async_result.ignored = True
```

I've tried setting `broker_pool_limit = None` and also used the master branch - neither fixed the issue.
I also tried to use the kombu patch for `retry=True` in https://github.com/celery/kombu/pull/920 - did not fix the issue

## Expected behavior
Should have worked fine - in fact it works fine for some smaller tasks, but fails for a long running tasks.

## Actual behavior

Error:
```
[2018-12-24 00:54:25,212: INFO/MainProcess] Received task: myapp.tasks.heavy_computation[088a6454-11af-4152-a9a3-72d81b348d11]
[2018-12-24 00:54:25,360: WARNING/MainProcess] Running heavy_computation ...
# ... 3 hrs later

[2018-12-24 03:54:25,227: INFO/MainProcess] Traceback for ValueError ....
...
ValueError: Some error occured in computation

[2018-12-24 03:54:28,419: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 174, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/_compat.py", line 79, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/opt/miniconda3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/miniconda3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/opt/miniconda3/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/opt/miniconda3/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/opt/miniconda3/lib/python3.6/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/opt/miniconda3/lib/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/opt/miniconda3/lib/python3.6/site-packages/kombu/transport/redis.py", line 714, in _brpop_read
    **options)
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 191, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
[2018-12-24 03:54:29,075: INFO/MainProcess] Connected to redis://:**@REDIS_SERVER:6379/1
[2018-12-24 03:54:29,255: INFO/MainProcess] mingle: searching for neighbors
[2018-12-24 03:54:30,876: INFO/MainProcess] mingle: sync with 1 nodes
[2018-12-24 03:54:30,876: INFO/MainProcess] mingle: sync complete
[2018-12-24 03:54:31,872: INFO/MainProcess] Received task: myapp.tasks.heavy_computation[088a6454-11af-4152-a9a3-72d81b348d11]
... Infinite loop: Start at line 1
```

**Comment by AbdealiJK** [comment]
A quick note that on a successful task, I get the following:
```
[2018-12-24 22:18:54,564: INFO/MainProcess] Received task: myapp.tasks.heavy_computation[1210198b-9ff5-4e22-a1f1-5bdfc0933cc6]
[2018-12-24 22:18:54,570: WARNING/MainProcess] Running heavy_computation ...
# ... ~20mins later
[2018-12-24 22:38:38,679: INFO/MainProcess]
[2018-12-24 22:38:38,679: INFO/MainProcess] Task myapp.tasks.heavy_computation[1210198b-9ff5-4e22-a1f1-5bdfc0933cc6] succeeded in 1184.1089600194246s: ...
[2018-12-24 22:38:41,186: WARNING/MainProcess]consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 174, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/_compat.py", line 79, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/opt/miniconda3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/miniconda3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/opt/miniconda3/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/opt/miniconda3/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/opt/miniconda3/lib/python3.6/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/opt/miniconda3/lib/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/opt/miniconda3/lib/python3.6/site-packages/kombu/transport/redis.py", line 714, in _brpop_read
    **options)
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/opt/miniconda3/lib/python3.6/site-packages/redis/connection.py", line 191, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
[2018-12-24 03:54:29,075: INFO/MainProcess] Connected to redis://:**@REDIS_SERVER:6379/1
[2018-12-24 03:54:29,255: INFO/MainProcess] mingle: searching for neighbors
[2018-12-24 03:54:30,876: INFO/MainProcess] mingle: sync with 1 nodes
[2018-12-24 03:54:30,876: INFO/MainProcess] mingle: sync complete
# And now it takes in the next task in the queue ...
```

So, it seems like in a successful case also I get this disconnect error. And in that case the result gets sent back to redis and the next task continues on. In the example above `save_result_to_db` does run in the dbconn queue
During error case - it does an infinite loop.

**Comment by auvipy** [comment]
did you find any solution for this?

**Comment by AbdealiJK** [comment]
I'm not sure to be honest. 
But I did the following and it generally got fixed :
 - Upgraded to the rc version of celery at the time
 - Set Broker pool limit to None
 - Increased redis visibility_timeout 

So closing as I don't face it anymore.
