### ISSUE TITLE
Celery stop with 1 task

### ISSUE THREAD

**Issue by Nilad** [celery/celery#5280]
## Environment & Settings
**Celery version**: 4.2.1 (windowlicker)

**Report**:
<details>

```
software -> celery:4.2.1 (windowlicker) kombu:4.2.2-post1 py:3.6.7
            billiard:3.5.0.5 py-amqp:2.3.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost/
ABSOLUTE_URL_OVERRIDES: {
 }
ADMINS: 
    ()
ALLOWED_HOSTS: []
APPEND_SLASH: True
AUTHENTICATION_BACKENDS: ['django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS: '********'
AUTH_USER_MODEL: 'auth.User'
BASE_DIR: '/home/ab/my_site'
BROKER_POOL_LIMIT: None
BROKER_URL: 'amqp://guest:********@localhost:5672//'
CACHES: {
 'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS: 'default'
CACHE_MIDDLEWARE_KEY_PREFIX: '********'
CACHE_MIDDLEWARE_SECONDS: 600
CELERY_DEFAULT_QUEUE: 'default'
CELERY_QUEUES: 
    (<unbound Queue default -> <unbound Exchange ''(direct)> -> >,
 <unbound Queue priority_high -> <unbound Exchange ''(direct)> -> >)
CELERY_RESULT_BACKEND: 'redis://localhost/'
CSRF_COOKIE_AGE: 31449600
CSRF_COOKIE_DOMAIN: None
CSRF_COOKIE_HTTPONLY: False
CSRF_COOKIE_NAME: 'csrftoken'
CSRF_COOKIE_PATH: '/'
CSRF_COOKIE_SAMESITE: 'Lax'
CSRF_COOKIE_SECURE: False
CSRF_FAILURE_VIEW: 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME: 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS: []
CSRF_USE_SESSIONS: False
DATABASES: {
    'default': {   'ATOMIC_REQUESTS': False,
                   'AUTOCOMMIT': True,
                   'CONN_MAX_AGE': 0,
                   'ENGINE': 'django.db.backends.mysql',
                   'HOST': 'localhost',
                   'NAME': 'my_db',
                   'OPTIONS': {'sql_mode': 'STRICT_ALL_TABLES,'},
                   'PASSWORD': '********',
                   'PORT': '',
                   'TEST': {   'CHARSET': None,
                               'COLLATION': None,
                               'MIRROR': None,
                               'NAME': None},
                   'TIME_ZONE': None,
                   'USER': 'root'}}
DATABASES_CNR_ROOT: '********'
DATABASE_ROUTERS: '********'
DATA_UPLOAD_MAX_MEMORY_SIZE: 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS: 1000
DATETIME_FORMAT: 'N j, Y, P'
DATETIME_INPUT_FORMATS: ['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y']
DATE_FORMAT: 'N j, Y'
DATE_INPUT_FORMATS: ['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']
DEBUG: True
DEBUG_PROPAGATE_EXCEPTIONS: False
DECIMAL_SEPARATOR: '.'
DEFAULT_CHARSET: 'utf-8'
DEFAULT_CONTENT_TYPE: 'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER: 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE: 'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL: 'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE: ''
DEFAULT_TABLESPACE: ''
DISALLOWED_USER_AGENTS: []
EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend
EMAIL_SUBJECT_PREFIX: '[Django] '
EMAIL_TIMEOUT: None
EMAIL_USE_LOCALTIME: False
EMAIL_USE_SSL: False
EMAIL_USE_TLS: True
EXCEL_SUPPORT: 'openpyxl'
FILE_CHARSET: 'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS: None
FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
FILE_UPLOAD_PERMISSIONS: 493
FIRST_DAY_OF_WEEK: 0
FIXTURE_DIRS: []
FORCE_SCRIPT_NAME: None
FORMAT_MODULE_PATH: None
FORM_RENDERER: 'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS: []
INSTALLED_APPS: ['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_tables2',
 'django_tables2_column_shifter',
 'django_filters',
 'import_export',
 'accueil',
 'contact']
INTERNAL_IPS: []
LANGUAGES: [('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kab', 'Kabyle'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI: ['he', 'ar', 'fa', 'ur']
LANGUAGE_CODE: 'fr-FR'
LANGUAGE_COOKIE_AGE: None
LANGUAGE_COOKIE_DOMAIN: None
LANGUAGE_COOKIE_NAME: 'django_language'
LANGUAGE_COOKIE_PATH: '/'
LOCALE_PATHS: []
LOGGING: {
    'disable_existing_loggers': False,
    'filters': {   'require_debug_false': {   '()': 'django.utils.log.RequireDebugFalse'}},
    'handlers': {   'mail_admins': {   'class': 'django.utils.log.AdminEmailHandler',
                                       'filters': ['require_debug_false'],
                                       'level': 'ERROR'}},
    'loggers': {   'django.request': {   'handlers': ['mail_admins'],
                                         'level': 'ERROR',
                                         'propagate': True}},
    'version': 1}
LOGGING_CONFIG: 'logging.config.dictConfig'
LOGIN_REDIRECT_URL: '/accounts/profile/'
LOGIN_URL: '/users/connexion'
LOGOUT_REDIRECT_URL: None
MANAGERS: 
    ()
MEDIA_ROOT: '/home/ab/my_site/media/'
MEDIA_URL: 'media/'
MESSAGE_STORAGE: 'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE: ['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
MIGRATION_MODULES: {
 }
MONTH_DAY_FORMAT: 'F j'
NUMBER_GROUPING: 0
PASSWORD_HASHERS: '********'
PASSWORD_RESET_TIMEOUT_DAYS: '********'
PREPEND_WWW: False
PYTHON_INTERPRETER: 'python3'
ROOT_URLCONF: 'Site_CNR.urls'
SECRET_KEY: '********'
SECURE_BROWSER_XSS_FILTER: False
SECURE_CONTENT_TYPE_NOSNIFF: False
SECURE_HSTS_INCLUDE_SUBDOMAINS: False
SECURE_HSTS_PRELOAD: False
SECURE_HSTS_SECONDS: 0
SECURE_PROXY_SSL_HEADER: None
SECURE_REDIRECT_EXEMPT: []
SECURE_SSL_HOST: None
SECURE_SSL_REDIRECT: False
SERVER_EMAIL: 'root@localhost'
SESSION_CACHE_ALIAS: 'default'
SESSION_COOKIE_AGE: 1209600
SESSION_COOKIE_DOMAIN: None
SESSION_COOKIE_HTTPONLY: True
SESSION_COOKIE_NAME: 'sessionid'
SESSION_COOKIE_PATH: '/'
SESSION_COOKIE_SAMESITE: 'Lax'
SESSION_COOKIE_SECURE: False
SESSION_ENGINE: 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE: False
SESSION_FILE_PATH: None
SESSION_SAVE_EVERY_REQUEST: False
SESSION_SERIALIZER: 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE: 'Site_CNR.settings'
SHORT_DATETIME_FORMAT: 'm/d/Y P'
SHORT_DATE_FORMAT: 'm/d/Y'
SIGNING_BACKEND: 'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS: []
STATICFILES_FINDERS: ['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE: 'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT: '/static/'
STATIC_URL: '/static/'
TEMPLATES: [{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/home/bacteriologie/Bureau/Site_CNR/templates'],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages',
                                     'django.template.context_processors.static',
                                     'django.template.context_processors.csrf',
                                     'Site_CNR.context_processors.context']}}]
TEST_NON_SERIALIZED_APPS: []
TEST_RUNNER: 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR: ','
TIME_FORMAT: 'P'
TIME_INPUT_FORMATS: ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE: 'Europe/Paris'
USE_I18N: True
USE_L10N: True
USE_THOUSAND_SEPARATOR: False
USE_TZ: True
USE_X_FORWARDED_HOST: False
USE_X_FORWARDED_PORT: False
WSGI_APPLICATION: 'Site_CNR.wsgi.application'
X_FRAME_OPTIONS: 'SAMEORIGIN'
YEAR_MONTH_FORMAT: 'F Y'
is_overridden: <bound method Settings.is_overridden of <Settings "my_site.settings">>
timezone: 'Europe/Paris'
 ```
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: Python 3.6.7 (default, Oct 22 2018, 11:32:17)
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: : N/A or Unknown

### Python Packages

<details>

```amqp==2.3.2
anyjson==0.3.3
apturl==0.5.2
asn1crypto==0.24.0
billiard==3.5.0.5
biopython==1.73
Brlapi==0.6.6
celery==4.2.1
certifi==2018.1.18
chardet==3.0.4
command-not-found==0.3
configparser==3.5.0
cryptography==2.1.4
cupshelpers==1.0
defer==1.0.6
defusedxml==0.5.0
diff-match-patch==20121119
distro-info==0.18
Django==2.1.5
django-bootstrap-datepicker-plus==3.0.5
django-filter==2.0.0
django-filters==0.2.1
django-import-export==1.2.0
django-tables2==2.0.3
django-tables2-column-shifter==0.5.2
ephem==3.7.6.0
et-xmlfile==1.0.1
httplib2==0.9.2
idna==2.6
jdcal==1.4
keyring==10.6.0
keyrings.alt==3.0
kombu==4.2.2.post1
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
leaflet==0.0.3
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.0
mysql==0.0.2
mysql-connector-python-rf==2.2.2
mysqlclient==1.3.14
netifaces==0.10.4
numpy==1.14.5
oauth==1.0.1
odfpy==1.3.6
olefile==0.45.1
openpyxl==2.5.4
pexpect==4.2.1
Pillow==5.1.0
protobuf==3.0.0
psutil==5.4.8
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pygobject==3.26.1
pymacaroons==0.13.0
PyMySQL==0.9.3
PyNaCl==1.1.2
pyparsing==2.2.0
pyRFC3339==1.0
python-apt==1.6.3
python-dateutil==2.6.1
python-debian==0.1.32
python-memcached==1.53
pytz==2018.9
pyxdg==0.25
PyYAML==3.12
redis==2.10.6
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
simplejson==3.13.2
six==1.11.0
ssh-import-id==5.7
system-service==0.3
systemd-python==234
tablib==0.12.1
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
unicodecsv==0.14.1
urllib3==1.22
usb-creator==0.3.3
vine==1.2.0
wadllib==1.3.2
xkit==0.0.0
xlrd==1.1.0
xlwt==1.3.0
zope.interface==4.3.2
```
</details>

## Minimally Reproducible Test Case

<details>

```celery -A Site_CNR worker -l info --autoscale 11 -Q default -n worker1.%h
 
 -------------- celery@worker1.my_pc v4.2.1 (windowlicker)
---- **** ----- 
--- * ***  * -- Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic 2019-01-10 17:02:10
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         my_site:0x7ff109be3a20
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     redis://localhost/
- *** --- * --- .> concurrency: {min=0, max=11} (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> default          exchange=default(direct) key=default
                

[tasks]
  . task_a

[2019-01-10 17:02:10,404: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2019-01-10 17:02:10,419: INFO/MainProcess] mingle: searching for neighbors
[2019-01-10 17:02:11,448: INFO/MainProcess] mingle: sync with 1 nodes
[2019-01-10 17:02:11,449: INFO/MainProcess] mingle: sync complete
[2019-01-10 17:02:11,472: WARNING/MainProcess] /home/bacteriologie/.local/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2019-01-10 17:02:11,472: INFO/MainProcess] celery@worker1.MPPR-M2ISH-153 ready.
```

Send a task_a task

```
[2019-01-10 17:02:11,496: INFO/MainProcess] Received task: task_a[f16e60a5-2a61-4077-9b2b-aa2a47ec66c6]  
[2019-01-10 17:02:11,497: INFO/MainProcess] Scaling up 1 processes.
[2019-01-10 17:02:11,672: WARNING/ForkPoolWorker-1] I am wait a minimum of 15.0Go Free RAM for A!
[2019-01-10 17:02:11,673: WARNING/ForkPoolWorker-1] The RAM is FREE for A!
[2019-01-10 17:02:11,673: WARNING/ForkPoolWorker-1] ***Run task_a task for A ***

```

Send a another task_a task
```
[2019-01-10 17:02:19,757: INFO/MainProcess] Received task: task_a[c332cc5c-065b-4c6e-b012-034677f1cd75]  
[2019-01-10 17:02:19,757: INFO/MainProcess] Scaling up 1 processes.
[2019-01-10 17:02:19,852: ERROR/MainProcess] Control command error: ConnectionResetError(104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/home/ab/.local/lib/python3.6/site-packages/celery/worker/pidbox.py", line 46, in on_message
    self.node.handle_message(body, message)
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/messaging.py", line 194, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/messaging.py", line 194, in <listcomp>
    [maybe_declare(entity) for entity in declare]
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/messaging.py", line 102, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/common.py", line 129, in maybe_declare
    return _maybe_declare(entity, declared, ident, channel, orig)
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/common.py", line 135, in _maybe_declare
    entity.declare(channel=channel)
  File "/home/ab/.local/lib/python3.6/site-packages/kombu/entity.py", line 185, in declare
    nowait=nowait, passive=passive,
  File "/home/ab/.local/lib/python3.6/site-packages/amqp/channel.py", line 614, in exchange_declare
    wait=None if nowait else spec.Exchange.DeclareOk,
  File "/home/ab/.local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/ab/.local/lib/python3.6/site-packages/amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "/home/ab/.local/lib/python3.6/site-packages/amqp/transport.py", line 275, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
[2019-01-10 17:02:19,866: WARNING/ForkPoolWorker-2] I am wait a minimum of 15.0Go Free RAM for B!
[2019-01-10 17:02:19,866: WARNING/ForkPoolWorker-2] The RAM is FREE for B!
[2019-01-10 17:02:19,867: WARNING/ForkPoolWorker-2] ***Run task_a task for B ***

```
And just millisecond after this last promt of celery

```

`[5]+  Arrêté                celery -A Site_CNR worker -l info --autoscale 11 -Q default -n worker1.%h
````

</details>

# Expected Behavior

I expected that celery done 1 task.

# Actual Behavior

I changed my OS of Ubuntu 16 LTS to Ubuntu 18 LTS but with this change i try to rework my devloppement environnement (i had done a freeze of pip3) but i stuck with this problem. I dont see what can be the problem. I followed the official installation guide on the celery website and i didnt have a problem on the installation...

I reproduce the steps and at each time that i have  1 or more task running in same time, celery stop.

Tell me in you want more informations.
Thank in advance for any help.

### Edit 1

Report of redis-cli monitor for 1 task

``` OK
1547139053.613337 [0 127.0.0.1:57898] "SUBSCRIBE" "celery-task-meta-7321bf9f-52d1-47b3-a0a8-dda1bcb89738"
1547139053.652452 [0 127.0.0.1:57898] "UNSUBSCRIBE" "celery-task-meta-7321bf9f-52d1-47b3-a0a8-dda1bcb89738"
```

#### Edit 2

After many operations to try to have special chemical recipe of celery and kombu. I fix it to celery (4.1.1) and kombu (4.2.2.post1).

And  it was a problem with the shell in ubuntu 18 LTS... For a reason that i don't explain celery "crash" like a memory crash but if the celery command is launch with nohup like 'nohup celery -A my_site worker **args'. It's functional oO.

Anyone have an explain for me or a way to call celery without `nohup` ?

**Comment by alwaysused** [comment]
Hi.I think the problem will be in the message backend.Try to restart rabbitmq .

**Comment by Nilad** [comment]
@alwaysused Thank for your reply. I make this `sudo systemctl restart rabbitmq-server.service` and it is not change the problem. I continue to use celery with `nohup` :hushed:

**Comment by auvipy** [comment]
update of this issue?

**Comment by Nilad** [comment]
@auvipy Still use nohup by default. I tested it and the problem is still here...

**Comment by auvipy** [comment]
any suggested fix?
