### ISSUE TITLE
Problem with factory pattern and init_app() workaround

### ISSUE THREAD

**Issue by okomarov** [celery/celery#5282]
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Environment & Settings
**Celery version**: 4.2.1 (windowlicker)

**Report**:
<details>

```
software -> celery:4.2.1 (windowlicker) kombu:4.2.2-post1 py:3.7.2
            billiard:3.5.0.5 redis:3.0.1
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

include: 'logic.locked_door_logic'
```
</details>

# Steps to Reproduce

## Required Dependencies
* **Minimal Python Version**: 3.7.2
* **Minimal Broker Version**: N/A
* **Minimal Result Backend Version**: N/A
* **Minimal OS and/or Kernel Version**: : N/A

### Python Packages
<details>

```
alembic==1.0.5
amqp==2.3.2
aniso8601==3.0.2
asn1crypto==0.24.0
astroid==2.1.0
Babel==2.6.0
billiard==3.5.0.5
Bootstrap-Flask==1.0.9
CacheControl==0.12.5
cachetools==3.0.0
celery==4.2.1
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
cryptography==2.4.2
decorator==4.3.0
dominate==2.3.5
flake8==3.6.0
Flask==1.0.2
Flask-Admin==1.5.3
Flask-Bootstrap==3.3.7.1
Flask-GraphQL==2.0.0
Flask-JWT-Extended==3.14.0
Flask-Login==0.4.1
Flask-Migrate==2.3.1
Flask-Script==2.0.6
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
flower==0.9.2
graphene==2.1.3
graphql-core==2.1
graphql-relay==0.4.5
graphql-server-core==1.1.1
gunicorn==19.9.0
idna==2.8
isort==4.3.4
itsdangerous==1.1.0
Jinja2==2.10
kombu==4.2.2.post1
lazy-object-proxy==1.3.1
Mako==1.0.7
MarkupSafe==1.1.0
mccabe==0.6.1
msgpack==0.6.0
oauthlib==2.1.0
pip-autoremove==0.9.1
promise==2.2.1
protobuf==3.6.1
psycopg2==2.7.6.1
pyasn1==0.4.5
pyasn1-modules==0.2.3
pycodestyle==2.4.0
pycparser==2.19
pyflakes==2.0.0
PyJWT==1.4.2
pylint==2.2.2
pylint-flask==0.5
pylint-plugin-utils==0.4
PySocks==1.6.8
python-dateutil==2.7.5
python-editor==1.0.3
pytz==2018.7
redis==3.0.1
requests==2.21.0
requests-oauthlib==1.0.0
rope==0.11.0
rsa==4.0
Rx==1.6.1
singledispatch==3.4.0.3
six==1.11.0
SQLAlchemy==1.2.14
tornado==5.1.1
tweepy==3.7.0
urllib3==1.24.1
vine==1.1.4
visitor==0.1.3
Werkzeug==0.14.1
wrapt==1.10.11
WTForms==2.2.1
```

</details>

## Minimally Reproducible Test Case
I am using the factory pattern to instantiate celery in `extensions.py` and then I initialize it in `app.py`. I am using the exact solution (copy-paste and same order of instantiation) in: https://stackoverflow.com/questions/12044776/how-to-use-flask-sqlalchemy-in-a-celery-task

Unfortunately, it seems the `app` reference is lost.

<details>
The simplified example below shows that the `init_app()` method from the link above, in principle, should work. However, the reference to the `flask_app` is not set or lost?

```python
class FlaskApp(object):
    def __init__(self):
        self.some_property = 'property'

# Celery without an init_app() method
class Celery(object):
    app = "Not set"

    class Task(object):
        def __call__(self):
            return "original task call"

    
class CeleryWrapper(Celery):

    def __init__(self):
        super(CeleryWrapper, self).__init__()

    def init_app(self, flask_app):
        TaskBase = self.Task
        _celery = self
        
        class ContextTask(TaskBase):
            abstract = True

            def __call__(self):
                return _celery.app.some_property
        
        self.app = flask_app
        self.Task = ContextTask

flask_app = FlaskApp()
print("Flask app has:", flask_app.some_property)
print("Unwrapped celery:", Celery().Task()())
celery = CeleryWrapper()
print("Wrapped but NOT initialized celery:", celery.Task()())
celery.init_app(flask_app)
print("Wrapped AND initialized celery:", celery.Task()())
```
and the results:
```
Flask app has: property
Unwrapped celery: original task call
Wrapped but NOT initialized celery: original task call
Wrapped AND initialized celery: property
```
So, while the wrapped but NOT `app_init`iated `celery` still returns the original `Task` call, once initiated it should be pointing to the `property` from the `flask_app`. This does not happen:

```
[2019-01-12 12:21:33,497: ERROR/ForkPoolWorker-6] Task logic.locked_door_logic._my_method[52515065-373e-471a-b184-0230b50bbd4a] raised unexpected: AttributeError("'FlaskCelery' object has no attribute 'app'")
Traceback (most recent call last):
  File "/Users/okomarov/.virtualenvs/my_project/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/okomarov/Documents/repos/my_project/app/extensions.py", line 40, in __call__
    with _celery.app.app_context():
AttributeError: 'FlaskCelery' object has no attribute 'app'
```
</details>

# Expected Behavior
The celery wrapper described in https://stackoverflow.com/questions/12044776/how-to-use-flask-sqlalchemy-in-a-celery-task should provide an easy way for tasks to run with app context.

# Actual Behavior
Unfortunately, the `flask_app` reference for the `FlaskCelery` wrapper is lost, and hence it cannot access the context. 

Any pointer on how to solve this issue and a have a `celery.init_app()` is appreciated.

**Comment by okomarov** [comment]
Figured the problem. Was related to our imports.

The [solution](https://stackoverflow.com/a/14146403/2180721) suggests:

app.py

```python
from flask import Flask
from extensions import celery, db

def create_app():
    app = Flask()

    #configure/initialize all your extensions
    db.init_app(app)
    celery.init_app(app)

    return app
```

It is paramount you do NOT do this:

```python
from flask import Flask

def create_app():
    app = Flask()

    initiliaze_extensions(app)

    return app

def initiliaze_extensions(app):
    from extensions import celery, db    # DOOMED!  Keep celery import at the FILE level
    
    db.init_app(app)
    celery.init_app(app)
```

Start celery workers with `celery worker -A app:celery -l info -f celery.log`. Note the `app:celery_app`.

In other files you can still import from extension: `from extensions import celery`.

**Comment by Kenan7** [comment]
thank you so much for updating the issue after you found the solution <3
