### ISSUE TITLE
Recursion error on complex chains of chords

### ISSUE THREAD

**Issue by van4oza** [celery/celery#5327]
Issue on 4.2.1, any workaround besides `sys.setrecursionlimit`?

```
tasks_set1 = [task.si() * 358]  # ~400 tasks
tasks_set2 = [task.si() * 250]  # ~300 tasks whatever

tasks = []
for report in [tasks_set1, tasks_set2]:
    chords = []
    chunks = array_split(report, 5)
    for chunk in chunks:
        chords.append(
            chord(
                group(chunk),
                chordfinisher.si()
            )
        )

    tasks.append(
        chain(chords)
    )

chord(
    group(tasks),
    chordfinisher.si()
).apply_async()
```

Now we have recursion
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
RecursionError: maximum recursion depth exceeded while encoding a JSON object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/ETL/tasks.py", line 154, in spare_yandex_stats
    spare_chordfinisher.si(start_time=start_time)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1232, in apply_async
    return self.run(tasks, body, args, task_id=task_id, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1277, in run
    header_result = header(*partial_args, task_id=group_id, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 953, in __call__
    return self.apply_async(partial_args, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 978, in apply_async
    args=args, kwargs=kwargs, **options))
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1054, in _apply_tasks
    **options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1232, in apply_async
    return self.run(tasks, body, args, task_id=task_id, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1277, in run
    header_result = header(*partial_args, task_id=group_id, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 953, in __call__
    return self.apply_async(partial_args, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 978, in apply_async
    args=args, kwargs=kwargs, **options))
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 1054, in _apply_tasks
    **options)
  File "/usr/local/lib/python3.6/site-packages/celery/canvas.py", line 218, in apply_async
    return _apply(args, kwargs, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 745, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
kombu.exceptions.EncodeError: maximum recursion depth exceeded while encoding a JSON object
```

**Comment by ikthecatt** [comment]
такая же история.

**Comment by auvipy** [comment]
could you try celery master with kombu 4.3?

**Comment by van4oza** [comment]
> could you try celery master with kombu 4.3?

celery==git+https://github.com/celery/celery.git
kombu==4.3.0

same behaviour(

**Comment by van4oza** [comment]
@auvipy 
it fails even here

```
tasks_set1 = [task.si() * 358]  # ~400 tasks
tasks_set2 = [task.si() * 250]  # ~300 tasks whatever

tasks = []
for report in [tasks_set1, tasks_set2]:
    chords = []
    chunks = [report[i:i+ 5] for i in range(0, len(report), 5)]
    for chunk in chunks:
        chords.append(
            chord(
                group(chunk),
                chordfinisher.si()
            )
        )
    chain(chords).apply_async()  # FAIL kombu.exceptions.EncodeError: maximum recursion depth exceeded while encoding a JSON object

    # tasks.append(
    #    chain(chords)
    # )

# chord(
#     group(tasks),
#     chordfinisher.si()
# ).apply_async()
```

**Comment by brabiega** [comment]
#5000 Might be related

**Comment by auvipy** [comment]
could you try celery 4.3 kindly and lets us know the logs?

**Comment by brabiega** [comment]
You might want to try my workaround-ish solution
https://github.com/ovh/celery-dyrygent

**Comment by tim-schilling** [comment]
This definitely seems related to #5000. I'm running into the max recursion error and it's due to the nested `kwargs` of the options of a task in a signature with a large chords chained together.
