### ISSUE TITLE
'TaskPool' object has no attribute 'grow' - linux, Python 3.6

### ISSUE THREAD

**Issue by mygitnote** [celery/celery#5333]
> python manage.py celery worker --autoscale=100,8 -l info -P threads

> requirements.txt:

amqp==1.4.9
anyjson==0.3.3
celery==3.1.26.post2
cryptography==2.4.2
Django==2.0.8
django-celery==3.2.2
idna==2.8
kombu==3.0.37
paramiko==2.4.2
pyasn1==0.4.5
pycparser==2.19
PyMySQL==0.9.3
PyNaCl==1.3.0
pytz==2018.9
redis==3.1.0
threadpool==1.3.2

> Error:

[2019-02-12 15:52:24,946: INFO/MainProcess] Received task: schedule.tasks.SyncTaskDispatcher[0141c066-e14f-49e8-91d8-509fd56b21e6]
[2019-02-12 15:52:24,946: INFO/MainProcess] Scaling up 1 processes.
[2019-02-12 15:52:24,947: ERROR/MainProcess] Unrecoverable error: AttributeError("'TaskPool' object has no attribute 'grow'",)
Traceback (most recent call last):
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/consumer.py", line 280, in start
    blueprint.start(self)
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/consumer.py", line 884, in start
    c.loop(*c.loop_args())
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/opt/yxh/env/lib/python3.6/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/opt/yxh/env/lib/python3.6/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/opt/yxh/env/lib/python3.6/site-packages/kombu/transport/base.py", line 146, in _read
    drain_events(timeout=0)
  File "/opt/yxh/env/lib/python3.6/site-packages/amqp/connection.py", line 326, in drain_events
    return amqp_method(channel, args, content)
  File "/opt/yxh/env/lib/python3.6/site-packages/amqp/channel.py", line 1909, in _basic_deliver
    fun(msg)
  File "/opt/yxh/env/lib/python3.6/site-packages/kombu/messaging.py", line 598, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/opt/yxh/env/lib/python3.6/site-packages/kombu/messaging.py", line 564, in receive
    [callback(body, message) for callback in callbacks]
  File "/opt/yxh/env/lib/python3.6/site-packages/kombu/messaging.py", line 564, in <listcomp>
    [callback(body, message) for callback in callbacks]
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/consumer.py", line 468, in on_task_received
    callbacks)
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/strategy.py", line 92, in task_message_handler
    [callback() for callback in callbacks]
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/strategy.py", line 92, in <listcomp>
    [callback() for callback in callbacks]
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/autoscale.py", line 95, in maybe_scale
    if self._maybe_scale(req):
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/autoscale.py", line 88, in _maybe_scale
    self.scale_up(cur - procs)
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/autoscale.py", line 127, in scale_up
    return self._grow(n)
  File "/opt/yxh/env/lib/python3.6/site-packages/celery/worker/autoscale.py", line 137, in _grow
    self.pool.grow(n)
AttributeError: 'TaskPool' object has no attribute 'grow'

`How I can do ?`

**Comment by auvipy** [comment]
try the latest release of celery.

**Comment by danielWagnerr** [comment]
I'm facing the same issue with celery 4.4.6

**Comment by auvipy** [comment]
can you share a test case you are using?

**Comment by ygdlx521** [comment]
`threads` mode doesn't support `--autoscale` option

**Comment by yuekui** [comment]
`threads` mode doesn't support `--autoscale` option
