### ISSUE TITLE
E_UNSUPPORTED_PYTHON isn't printed due to a syntax error

### ISSUE THREAD

**Issue by RadekBiba** [celery/celery#5336]
# Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have tried reproducing the issue on more than one message broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

## Environment & Settings
**Celery version**: 4.0.2

**Report**:
<details>
N/A
</details>

# Steps to Reproduce
If `setup.py` is executed on a system running Python 2.6, the error message with instructions on what to do isn't printed. That's because `setup.py` itself won't run on Python 2.6.

## Required Dependencies

* **Minimal Python Version**: 2.6 (this one specifically)
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: : N/A or Unknown

### Python Packages

<details>
```
N/A
```
</details>

### Other Dependencies

<details>
N/A
</details>

## Minimally Reproducible Test Case

<details>
```python
```
</details>

# Expected Behavior

The Python interpreter is able to parse the file, detects the incompatible version, and the intended error message is printed.

# Actual Behavior

```
  File "setup.py", line 53
    'auth',
          ^
SyntaxError: invalid syntax
```

**Comment by thedrow** [comment]
Version 4.0 does not support Python 2.6. Please refer to the [4.0 version documentation](http://docs.celeryproject.org/en/4.0/whatsnew-4.0.html#dropped-support-for-python-2-6) for the list of supported Python versions.
Please upgrade your Python runtime. Python 2.6 is ancient and does not receive security updates.

**Comment by RadekBiba** [comment]
I know, but that's not the point. The point is the code in `setup.py` tries hard to advise what to do if you're running Python 6:

```
E_UNSUPPORTED_PYTHON = <a very informative error message>
...
PY26_OR_LESS = sys.version_info < (2, 7)
...
if PY26_OR_LESS:
    raise Exception(E_UNSUPPORTED_PYTHON % (PYIMP, '2.7'))
```

But in fact the exception is never raised, and the error message is never printed, as the code fails to compile on Python 2.6 (or less) in the first place. It's kind of like unreachable code.

If `setup.py` is made compatible with Python 2.6, then the error message will be printed and it'll be clear what to do.

Note: this comes from RHEL 6, where Python 2.6 is available by default. I can use Software Collections to get a modern version, but that's another story.

**Comment by thedrow** [comment]
So you're suggesting we'll release a new 4.0.x version that fixes this?
Will it be even picked up by REHL?
BTW 4.0 is pretty old. We have plenty of bug fixes in 4.2 and the upcoming 4.3.
Would you consider to upgrade?

PRs are of course welcome if you think this is worth your while.

**Comment by thedrow** [comment]
I see that you work for RedHat so scratch my suggestion to upgrade.
Is this a formal request from RedHat? Does it hurt their customers?

**Comment by RadekBiba** [comment]
I don't have any suggestions or preferences regarding the version that might fix this. We've decided not to use Celery 4 on RHEL 6.

This isn't a formal request. Besides, even if the syntax in `setup.py` is changed, the main Celery 4 code won't run on Python 2.6 / RHEL 6, and I respect that. To give more information about the origin of this issue:

The issue occurred while trying to make a newer version of Pulp available on RHEL 6 for one of our products. The new Pulp (-server) needs Celery 4, though. I hadn't checked the min. requirements; just tried building Celery 4.0 (taken from a source RPM previously built on RHEL 7) and got the syntax error. Then I noticed the error message and the check for the min. version in the code.

Though we won't be upgrading Pulp after all, I thought it would be fair to report the issue so that the effort invested in the version check & the error message in `setup.py` isn't wasted. I might put in a pull request with a patch in the future, unless someone is faster.

**Comment by RadekBiba** [comment]
Would you consider the following patch?

```
    diff --git a/setup.py b/setup.py
    index 123a1392f..bcf898891 100644
    --- a/setup.py
    +++ b/setup.py
    @@ -49,7 +49,7 @@ elif PY33_OR_LESS and not PYPY24_ATLEAST:
     
     # -*- Extras -*-
     
    -EXTENSIONS = {
    +EXTENSIONS = set([
         'auth',
         'cassandra',
         'django',
    @@ -78,7 +78,7 @@ EXTENSIONS = {
         'mongodb',
         'cosmosdbsql',
         's3',
    -}
    +])
     
     # -*- Classifiers -*-
     
    @@ -176,7 +176,7 @@ def install_requires():
     
     def extras_require():
         """Get map of all extra requirements."""
    -    return {x: extras(x + '.txt') for x in EXTENSIONS}
    +    return dict((x, extras(x + '.txt')) for x in EXTENSIONS)
     
     # -*- Long Description -*-

```

With it, I get the expected error message on RHEL 6 (as opposed to that syntax error):

```
# python setup.py build
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    raise Exception(E_UNSUPPORTED_PYTHON % (PYIMP, '2.7'))
Exception: 
----------------------------------------
 Celery 4.0 requires CPython 2.7 or later
----------------------------------------

- For CPython 2.6, PyPy 1.x, Jython 2.6, CPython 3.2->3.3; use Celery 3.1:

    $ pip install 'celery<4'

- For CPython 2.5, Jython 2.5; use Celery 3.0:

    $ pip install 'celery<3.1'

- For CPython 2.4; use Celery 2.2:

    $ pip install 'celery<2.3'

```

**Comment by auvipy** [comment]
> Would you consider the following patch?
> 
> ```
>     diff --git a/setup.py b/setup.py
>     index 123a1392f..bcf898891 100644
>     --- a/setup.py
>     +++ b/setup.py
>     @@ -49,7 +49,7 @@ elif PY33_OR_LESS and not PYPY24_ATLEAST:
>      
>      # -*- Extras -*-
>      
>     -EXTENSIONS = {
>     +EXTENSIONS = set([
>          'auth',
>          'cassandra',
>          'django',
>     @@ -78,7 +78,7 @@ EXTENSIONS = {
>          'mongodb',
>          'cosmosdbsql',
>          's3',
>     -}
>     +])
>      
>      # -*- Classifiers -*-
>      
>     @@ -176,7 +176,7 @@ def install_requires():
>      
>      def extras_require():
>          """Get map of all extra requirements."""
>     -    return {x: extras(x + '.txt') for x in EXTENSIONS}
>     +    return dict((x, extras(x + '.txt')) for x in EXTENSIONS)
>      
>      # -*- Long Description -*-
> ```
> 
> With it, I get the expected error message on RHEL 6 (as opposed to that syntax error):
> 
> ```
> # python setup.py build
> Traceback (most recent call last):
>   File "setup.py", line 46, in <module>
>     raise Exception(E_UNSUPPORTED_PYTHON % (PYIMP, '2.7'))
> Exception: 
> ----------------------------------------
>  Celery 4.0 requires CPython 2.7 or later
> ----------------------------------------
> 
> - For CPython 2.6, PyPy 1.x, Jython 2.6, CPython 3.2->3.3; use Celery 3.1:
> 
>     $ pip install 'celery<4'
> 
> - For CPython 2.5, Jython 2.5; use Celery 3.0:
> 
>     $ pip install 'celery<3.1'
> 
> - For CPython 2.4; use Celery 2.2:
> 
>     $ pip install 'celery<2.3'
> ```

sure please
