### ISSUE TITLE
Celery worker hangs when exception and worker_max_tasks_per_child=1

### ISSUE THREAD

**Issue by okomarov** [celery/celery#5388]
# Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
<details><summary> details </summary>

```
software -> celery:4.2.1 (windowlicker) kombu:4.4.0 py:3.7.2
            billiard:3.5.0.5 redis:3.2.0
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

ENV: 'production'
DEBUG: False
TESTING: False
PROPAGATE_EXCEPTIONS: None
PRESERVE_CONTEXT_ON_EXCEPTION: None
SECRET_KEY: '********'
PERMANENT_SESSION_LIFETIME: datetime.timedelta(days=31)
USE_X_SENDFILE: False
SERVER_NAME: None
APPLICATION_ROOT: '/'
SESSION_COOKIE_NAME: 'session'
SESSION_COOKIE_DOMAIN: None
SESSION_COOKIE_PATH: None
SESSION_COOKIE_HTTPONLY: True
SESSION_COOKIE_SECURE: False
SESSION_COOKIE_SAMESITE: None
SESSION_REFRESH_EACH_REQUEST: True
MAX_CONTENT_LENGTH: None
SEND_FILE_MAX_AGE_DEFAULT: datetime.timedelta(seconds=43200)
TRAP_BAD_REQUEST_ERRORS: None
TRAP_HTTP_EXCEPTIONS: False
EXPLAIN_TEMPLATE_LOADING: False
PREFERRED_URL_SCHEME: 'http'
JSON_AS_ASCII: True
JSON_SORT_KEYS: '********'
JSONIFY_PRETTYPRINT_REGULAR: False
JSONIFY_MIMETYPE: 'application/json'
TEMPLATES_AUTO_RELOAD: None
MAX_COOKIE_SIZE: 4093
broker_url: 'redis://localhost:6379/0'
worker_max_tasks_per_child: 1
```
</details>

- [x] I have included the contents of ``pip freeze`` in the issue.
<details><summary> details </summary>

```
amqp==2.4.2
billiard==3.5.0.5
blinker==1.4
celery==4.2.1
certifi==2019.3.9
Click==7.0
Flask==1.0.2
itsdangerous==1.1.0
Jinja2==2.10
kombu==4.4.0
MarkupSafe==1.1.1
pytz==2018.9
redis==3.2.0
sentry-sdk==0.7.6
urllib3==1.24.1
vine==1.2.0
Werkzeug==0.14.1
```
</details>

#### Related Issues

Far-fetched but maybe related to the memory leaks: https://github.com/celery/celery/issues/4843 and https://github.com/celery/celery/issues/5249

# Steps to Reproduce

I was investigating why I did not receive sentry.io errors when the task raised an exception. I find that the worker is stuck when `worker_max_tasks_per_child = 1` and there is an exception is raised in the task. 
The sentry dependency is useful to highlight where the worker is stuck.

### Consider this single file flask app, `web/app.py`:
```python
from celery import Celery
import flask
import sentry_sdk
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init(
  dsn='https://******@sentry.io/******',
  integrations=[FlaskIntegration(), CeleryIntegration()], debug=True)
app = flask.Flask(__name__)


class FlaskCelery(Celery):

    def __init__(self, *args, **kwargs):
        super(FlaskCelery, self).__init__(*args, **kwargs)
        self.patch_task()

        if 'app' in kwargs:
            self.init_app(kwargs['app'])

    def patch_task(self):
        TaskBase = self.Task
        _celery = self

        class ContextTask(TaskBase):
            abstract = True

            def __call__(self, *args, **kwargs):
                if flask.has_app_context():
                    return TaskBase.__call__(self, *args, **kwargs)
                else:
                    with _celery.app.app_context():
                        return TaskBase.__call__(self, *args, **kwargs)

        self.Task = ContextTask

    def init_app(self, app):
        self.app = app
        self.config_from_object(app.config)


celery_app = FlaskCelery()
celery_app.conf.broker_url = "redis://localhost:6379/0"
celery_app.conf.worker_max_tasks_per_child = 1
celery_app.init_app(app)


@celery_app.task
def simple_task():
    raise Exception("Testing Celery exception")


@app.route("/")
def index():
    simple_task.delay()
    return "OK"

```

### Launch the app and celery
With `flask run` and celery with `celery worker -A app:celery_app -l debug -E`:

```
 [sentry] DEBUG: Setting up integrations (with default = True)
 [sentry] DEBUG: Setting up previously not enabled integration flask
 [sentry] DEBUG: Setting up previously not enabled integration celery
 [sentry] DEBUG: Setting up previously not enabled integration logging
 [sentry] DEBUG: Setting up previously not enabled integration stdlib
 [sentry] DEBUG: Setting up previously not enabled integration excepthook
 [sentry] DEBUG: Setting up previously not enabled integration dedupe
 [sentry] DEBUG: Setting up previously not enabled integration atexit
 [sentry] DEBUG: Setting up previously not enabled integration modules
 [sentry] DEBUG: Setting up previously not enabled integration argv
 [sentry] DEBUG: Setting up previously not enabled integration threading
 [sentry] DEBUG: Enabling integration flask
 [sentry] DEBUG: Enabling integration celery
 [sentry] DEBUG: Enabling integration logging
 [sentry] DEBUG: Enabling integration stdlib
 [sentry] DEBUG: Enabling integration excepthook
 [sentry] DEBUG: Enabling integration dedupe
 [sentry] DEBUG: Enabling integration atexit
 [sentry] DEBUG: Enabling integration modules
 [sentry] DEBUG: Enabling integration argv
 [sentry] DEBUG: Enabling integration threading
[2019-03-13 18:42:04,943: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2019-03-13 18:42:04,945: DEBUG/MainProcess] | Worker: Building graph...
[2019-03-13 18:42:04,945: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Timer, Hub, Pool, Autoscaler, Beat, Consumer}
[2019-03-13 18:42:04,959: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2019-03-13 18:42:04,960: DEBUG/MainProcess] | Consumer: Building graph...
[2019-03-13 18:42:04,982: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Agent, Mingle, Gossip, Tasks, Control, event loop}
 
 -------------- celery@Olegs-MBP.local v4.2.1 (windowlicker)
---- **** ----- 
--- * ***  * -- Darwin-18.2.0-x86_64-i386-64bit 2019-03-13 18:42:04
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x101d33470
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . app.simple_task
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap

[2019-03-13 18:42:05,002: DEBUG/MainProcess] | Worker: Starting Hub
[2019-03-13 18:42:05,002: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:42:05,002: DEBUG/MainProcess] | Worker: Starting Pool
[2019-03-13 18:42:05,223: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:42:05,224: DEBUG/MainProcess] | Worker: Starting Consumer
[2019-03-13 18:42:05,225: DEBUG/MainProcess] | Consumer: Starting Connection
[2019-03-13 18:42:05,244: INFO/MainProcess] Connected to redis://localhost:6379/0
[2019-03-13 18:42:05,244: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:42:05,244: DEBUG/MainProcess] | Consumer: Starting Events
[2019-03-13 18:42:05,255: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:42:05,255: DEBUG/MainProcess] | Consumer: Starting Heart
[2019-03-13 18:42:05,257: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:42:05,258: DEBUG/MainProcess] | Consumer: Starting Mingle
[2019-03-13 18:42:05,258: INFO/MainProcess] mingle: searching for neighbors
[2019-03-13 18:42:06,284: INFO/MainProcess] mingle: all alone
[2019-03-13 18:42:06,285: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:42:06,285: DEBUG/MainProcess] | Consumer: Starting Gossip
[2019-03-13 18:42:06,288: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:42:06,289: DEBUG/MainProcess] | Consumer: Starting Tasks
[2019-03-13 18:42:06,292: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:42:06,292: DEBUG/MainProcess] | Consumer: Starting Control
[2019-03-13 18:42:06,296: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:42:06,296: DEBUG/MainProcess] | Consumer: Starting event loop
[2019-03-13 18:42:06,296: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2019-03-13 18:42:06,297: INFO/MainProcess] celery@Olegs-MBP.local ready.
[2019-03-13 18:42:06,297: DEBUG/MainProcess] basic.qos: prefetch_count->32
```

### Navigate to http://127.0.0.1:5000/
Then check the logging in the celery window:
```
[tasks]
  . app.simple_task
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap

[2019-03-13 18:28:45,682: DEBUG/MainProcess] | Worker: Starting Hub
[2019-03-13 18:28:45,683: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:28:45,683: DEBUG/MainProcess] | Worker: Starting Pool
[2019-03-13 18:28:45,902: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:28:45,903: DEBUG/MainProcess] | Worker: Starting Consumer
[2019-03-13 18:28:45,903: DEBUG/MainProcess] | Consumer: Starting Connection
[2019-03-13 18:28:45,924: INFO/MainProcess] Connected to redis://localhost:6379/0
[2019-03-13 18:28:45,924: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:28:45,924: DEBUG/MainProcess] | Consumer: Starting Events
[2019-03-13 18:28:45,934: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:28:45,934: DEBUG/MainProcess] | Consumer: Starting Mingle
[2019-03-13 18:28:45,934: INFO/MainProcess] mingle: searching for neighbors
[2019-03-13 18:28:46,959: INFO/MainProcess] mingle: all alone
[2019-03-13 18:28:46,959: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:28:46,959: DEBUG/MainProcess] | Consumer: Starting Tasks
[2019-03-13 18:28:46,963: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:28:46,964: DEBUG/MainProcess] | Consumer: Starting Control
[2019-03-13 18:28:46,967: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:28:46,967: DEBUG/MainProcess] | Consumer: Starting Heart
[2019-03-13 18:28:46,969: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:28:46,969: DEBUG/MainProcess] | Consumer: Starting Gossip
[2019-03-13 18:28:46,973: DEBUG/MainProcess] ^-- substep ok
[2019-03-13 18:28:46,973: DEBUG/MainProcess] | Consumer: Starting event loop
[2019-03-13 18:28:46,973: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2019-03-13 18:28:46,975: INFO/MainProcess] celery@Olegs-MBP.local ready.
[2019-03-13 18:28:46,975: DEBUG/MainProcess] basic.qos: prefetch_count->32
[2019-03-13 18:28:52,154: INFO/MainProcess] Received task: app.simple_task[79474113-867f-42ac-b712-a656ff5b845b]  
[2019-03-13 18:28:52,155: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x1096312f0> (args:('app.simple_task', '79474113-867f-42ac-b712-a656ff5b845b', {'lang': 'py', 'task': 'app.simple_task', 'id': '79474113-867f-42ac-b712-a656ff5b845b', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '79474113-867f-42ac-b712-a656ff5b845b', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen5197@Olegs-MBP.local', 'reply_to': '99554197-925c-3633-a69a-88d7c7f89233', 'correlation_id': '79474113-867f-42ac-b712-a656ff5b845b', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}}, b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2019-03-13 18:28:52,158: DEBUG/MainProcess] Task accepted: app.simple_task[79474113-867f-42ac-b712-a656ff5b845b] pid:5262
 [sentry] DEBUG: Sending error event [b1302c1a97fe44379284b58198d59aec] to sentry.io project:1408785
[2019-03-13 18:28:52,169: DEBUG/ForkPoolWorker-5] Sending error event [b1302c1a97fe44379284b58198d59aec] to sentry.io project:1408785
[2019-03-13 18:28:52,171: DEBUG/ForkPoolWorker-5] Starting new HTTPS connection (1): sentry.io:443
[2019-03-13 18:28:52,176: ERROR/ForkPoolWorker-5] Task app.simple_task[79474113-867f-42ac-b712-a656ff5b845b] raised unexpected: Exception('Testing Celery exception')
Traceback (most recent call last):
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/okomarov/Documents/repos/myproject/web/app.py", line 32, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 66, in _inner
    reraise(*_capture_exception())
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 52, in reraise
    raise value
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 64, in _inner
    return f(*args, **kwargs)
  File "/Users/okomarov/Documents/repos/myproject/web/app.py", line 49, in simple_task
    raise Exception("Testing Celery exception")
Exception: Testing Celery exception
 [sentry] INFO: event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x1096317b8>) dropped event ({'level': 'error', 'exception': {'values': [{'module': None, 'type': 'Exception', 'value': 'Testing Celery exception', 'mechanism': {'type': 'logging', 'handled': True}, 'stacktrace': {'frames': [{'filename': 'celery/app/trace.py', 'abs_path': '/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/celery/app/trace.py', 'function': 'trace_task', 'module': 'celery.app.trace', 'lineno': 382, 'pre_context': ['                        request=task_request,', '                    )', '', '                # -*- TRACE -*-',
...
```

# Expected Behavior
On error in the task, the http response is posted to sentry.io:

```
[2019-03-13 18:42:55,260: INFO/MainProcess] Received task: app.simple_task[ec0f05ec-c575-43d1-a879-d264f229cff9]  
[2019-03-13 18:42:55,262: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x101d38378> (args:('app.simple_task', 'ec0f05ec-c575-43d1-a879-d264f229cff9', {'lang': 'py', 'task': 'app.simple_task', 'id': 'ec0f05ec-c575-43d1-a879-d264f229cff9', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'ec0f05ec-c575-43d1-a879-d264f229cff9', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen6070@Olegs-MBP.local', 'reply_to': '27e5deff-3570-3f35-b2fe-b17e5c46fa35', 'correlation_id': 'ec0f05ec-c575-43d1-a879-d264f229cff9', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}}, b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2019-03-13 18:42:55,267: DEBUG/MainProcess] Task accepted: app.simple_task[ec0f05ec-c575-43d1-a879-d264f229cff9] pid:6113
 [sentry] DEBUG: Sending error event [06df5ccdbe1248db9c61c264c3b55995] to sentry.io project:1408785
[2019-03-13 18:42:55,286: DEBUG/ForkPoolWorker-5] Sending error event [06df5ccdbe1248db9c61c264c3b55995] to sentry.io project:1408785
[2019-03-13 18:42:55,291: DEBUG/ForkPoolWorker-5] Starting new HTTPS connection (1): sentry.io:443
[2019-03-13 18:42:55,301: ERROR/ForkPoolWorker-5] Task app.simple_task[ec0f05ec-c575-43d1-a879-d264f229cff9] raised unexpected: Exception('Testing Celery exception')
Traceback (most recent call last):
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/okomarov/Documents/repos/myproject/web/app.py", line 32, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 66, in _inner
    reraise(*_capture_exception())
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 52, in reraise
    raise value
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 64, in _inner
    return f(*args, **kwargs)
  File "/Users/okomarov/Documents/repos/myproject/web/app.py", line 49, in simple_task
    raise Exception("Testing Celery exception")
Exception: Testing Celery exception
 [sentry] INFO: event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x101d38840>) dropped event ({'level': 'error', 'exception': {'values': [{'module': None, 'type': 'Exception', 'value': 'Testing Celery exception', 'mechanism': {'type': 'logging', 'handled': True}, 'stacktrace': {'frames': [{'filename': 'celery/app/trace.py', 'abs_path': '/Users/okomarov/.virtualenvs
...truncated [sentry] INFO.

[2019-03-13 18:42:55,812: DEBUG/ForkPoolWorker-5] https://sentry.io:443 "POST /api/1408785/store/ HTTP/1.1" 200 41
 [sentry] DEBUG: Request status: 200
[2019-03-13 18:42:55,813: DEBUG/ForkPoolWorker-5] Request status: 200
```

# Actual Behavior
With `worker_max_tasks_per_child=1`, http request is not posted:

```
[2019-03-13 18:45:01,999: INFO/MainProcess] Received task: app.simple_task[1bda2b95-e04c-408a-9bb6-bc3de9e35739]  
[2019-03-13 18:45:02,000: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x111789378> (args:('app.simple_task', '1bda2b95-e04c-408a-9bb6-bc3de9e35739', {'lang': 'py', 'task': 'app.simple_task', 'id': '1bda2b95-e04c-408a-9bb6-bc3de9e35739', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '1bda2b95-e04c-408a-9bb6-bc3de9e35739', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen6159@Olegs-MBP.local', 'reply_to': '12e761ab-80ab-3b18-983a-4f2e3e081306', 'correlation_id': '1bda2b95-e04c-408a-9bb6-bc3de9e35739', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}}, b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2019-03-13 18:45:02,002: DEBUG/MainProcess] Task accepted: app.simple_task[1bda2b95-e04c-408a-9bb6-bc3de9e35739] pid:6174
 [sentry] DEBUG: Sending error event [7c77b209fa1543eaa290cdca73775120] to sentry.io project:1408785
[2019-03-13 18:45:02,019: DEBUG/ForkPoolWorker-5] Sending error event [7c77b209fa1543eaa290cdca73775120] to sentry.io project:1408785
[2019-03-13 18:45:02,022: DEBUG/ForkPoolWorker-5] Starting new HTTPS connection (1): sentry.io:443
[2019-03-13 18:45:02,033: ERROR/ForkPoolWorker-5] Task app.simple_task[1bda2b95-e04c-408a-9bb6-bc3de9e35739] raised unexpected: Exception('Testing Celery exception')
Traceback (most recent call last):
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/okomarov/Documents/repos/myproject/web/app.py", line 32, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 66, in _inner
    reraise(*_capture_exception())
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 52, in reraise
    raise value
  File "/Users/okomarov/.virtualenvs/myenv/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 64, in _inner
    return f(*args, **kwargs)
  File "/Users/okomarov/Documents/repos/myproject/web/app.py", line 49, in simple_task
    raise Exception("Testing Celery exception")
Exception: Testing Celery exception
 [sentry] INFO: event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x111789840>) dropped event ({'level': 'error', 'exception': {'values': [{'module': None, 'type': 
...truncated [sentry] INFO.
```

It never produces the:
```
[2019-03-13 18:42:55,812: DEBUG/ForkPoolWorker-5] https://sentry.io:443 "POST /api/1408785/store/ HTTP/1.1" 200 41
 [sentry] DEBUG: Request status: 200
[2019-03-13 18:42:55,813: DEBUG/ForkPoolWorker-5] Request status: 200
```

where  `[sentry] DEBUG: Request status: 200` is a debug print inserted manually in `sentry_sdk/transport.py`.

**Comment by okomarov** [comment]
Closing as the issue is with sdk_sentry (python).
