### ISSUE TITLE
celery beat bug with python 3.7 re pattern_type change

### ISSUE THREAD

**Issue by ssharma80** [celery/celery#5416]
# Steps to Reproduce
celery.beat  INFO     Scheduler: Sending due task update_job_status_task (validate.tasks.update_job_status_task)
celery.beat  ERROR    Message Error: Couldn't apply scheduled task update_job_status_task: module 're' has no attribute '_pattern_type'
['  File "/home/ubuntu/anaconda3/envs/ev_celery/bin/celery", line 10, in <module>\n    sys.exit(main())\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/__main__.py", line 16, in main\n    _main()\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main\n    cmd.execute_from_commandline(argv)\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/bin/base.py", line 275, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/bin/celery.py", line 488, in handle_argv\n    return self.execute(command, argv)\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/bin/celery.py", line 420, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/bin/base.py", line 279, in run_from_argv\n    sys.argv if argv is None else argv, command)\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/bin/base.py", line 363, in handle_argv\n    return self(*args, **options)\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/bin/base.py", line 238, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/bin/beat.py", line 109, in run\n    return beat().run()\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/apps/beat.py", line 81, in run\n    self.start_scheduler()\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/apps/beat.py", line 109, in start_scheduler\n    service.start()\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/beat.py", line 588, in start\n    interval = self.scheduler.tick()\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/beat.py", line 307, in tick\n    self.apply_entry(entry, producer=self.producer)\n', '  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/beat.py", line 244, in apply_entry\n    exc, traceback.format_stack(), exc_info=True)\n']
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'router'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/beat.py", line 350, in apply_async
    **entry.options)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/base.py", line 708, in send_task
    router = router or amqp.router
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/amqp.py", line 606, in router
    return self.Router()
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/amqp.py", line 284, in Router
    return _routes.Router(self.routes, queues or self.queues,
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/amqp.py", line 601, in routes
    self.flush_routes()
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/amqp.py", line 289, in flush_routes
    self._rtable = _routes.prepare(self.app.conf.task_routes)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/routes.py", line 136, in prepare
    return [expand_route(route) for route in routes]
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/routes.py", line 136, in <listcomp>
    return [expand_route(route) for route in routes]
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/routes.py", line 127, in expand_route
    return MapRoute(route)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/routes.py", line 36, in __init__
    if isinstance(k, re._pattern_type):
AttributeError: module 're' has no attribute '_pattern_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/beat.py", line 241, in apply_entry
    result = self.apply_async(entry, producer=producer, advance=False)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/beat.py", line 358, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/beat.py", line 350, in apply_async
    **entry.options)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/base.py", line 708, in send_task
    router = router or amqp.router
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/amqp.py", line 606, in router
    return self.Router()
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/amqp.py", line 284, in Router
    return _routes.Router(self.routes, queues or self.queues,
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/amqp.py", line 601, in routes
    self.flush_routes()
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/amqp.py", line 289, in flush_routes
    self._rtable = _routes.prepare(self.app.conf.task_routes)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/routes.py", line 136, in prepare
    return [expand_route(route) for route in routes]
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/routes.py", line 136, in <listcomp>
    return [expand_route(route) for route in routes]
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/routes.py", line 127, in expand_route
    return MapRoute(route)
  File "/home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/app/routes.py", line 36, in __init__
    if isinstance(k, re._pattern_type):
**celery.beat.SchedulingError: Couldn't apply scheduled task update_job_status_task: module 're' has no attribute '_pattern_type'**

## Required Dependencies

* **Minimal Python Version**: Python3.7
* **Minimal Broker Version**: Rabbitmq 3.7
* **Minimal Result Backend Version**: Yes
* **Minimal OS and/or Kernel Version**: Ubuntu 18.04 Server
* **Minimal Result Backend Client Version**: Celery 4.2.2

# Expected Behavior
Celery should be able to parse the routes from CELERY_ROUTES in django config.

# Actual Behavior
Throws an error
 celery.beat.SchedulingError: Couldn't apply scheduled task update_job_status_task: module 're' has no attribute '_pattern_type'

# Steps to Reproduce
Install python 3.7
install anaconda any latest version as of March 2019.
install celery 4.2.2

run celery beat as :+1: 
celery -A emailverifiery beat -l info

**Comment by ssharma80** [comment]
Please refer to issue https://github.com/beetbox/beets/issues/2978 on another thread about another app, but same short of issue.

**Comment by ssharma80** [comment]
Found the fix as well.
For the time being you can edit 
 sudo nano /home/ubuntu/anaconda3/envs/ev_celery/lib/python3.7/site-packages/celery/a/routes.py

Add code in bold:

# -*- coding: utf-8 -*-
"""Task Routing.

Contains utilities for working with task routers, (:setting:`task_routes`).
"""
from __future__ import absolute_import, unicode_literals

import re
import string

to

# -*- coding: utf-8 -*-
"""Task Routing.

Contains utilities for working with task routers, (:setting:`task_routes`).
"""
from __future__ import absolute_import, unicode_literals

import re
**re._pattern_type = re.Pattern**
import string

**Comment by auvipy** [comment]
celery 4.2.x doesn't support python 3.7, please try celery 4.3rc3 to get rid of the bug and report if you found any other bug in celery 4.3rc3 :)
