### ISSUE TITLE
Update fails across Python versions.

### ISSUE THREAD

**Issue by jenstroeger** [celery/celery#5444]
```
software -> celery:4.3.0 (rhubarb) kombu:4.4.0 py:3.7.3
            billiard:3.6.0.0 py-amqp:2.4.1
platform -> system:Linux arch:64bit, ELF
            kernel version:4.4.0-1079-aws imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/0

broker_url: 'amqp://foo:********@localhost:5672//'
result_backend: 'redis://localhost:6379/0'
result_expires: 0
task_serializer: 'json'
result_serializer: 'json'
accept_content: ['json']
enable_utc: True
timezone: 'UTC'
imports: 
    (…)
task_routes: {…}
```
I think the problem is related to issue https://github.com/BobBuildTool/bob/issues/183: Using files generated by `--statedb` and `--schedule` when updating from Python 3.6 to 3.7 gives me the following error:
```
Traceback (most recent call last):
  File "/…/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/celery", line 10, in <module>
    sys.exit(main())
  File "/…/lib/python3.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/…/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/…/lib/python3.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/…/lib/python3.7/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/…/lib/python3.7/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/…/lib/python3.7/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/…/lib/python3.7/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/…/lib/python3.7/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/…/lib/python3.7/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/…/lib/python3.7/site-packages/celery/worker/worker.py", line 101, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/…/lib/python3.7/site-packages/celery/worker/worker.py", line 141, in setup_instance
    self.blueprint.apply(self, **kwargs)
  File "/…/lib/python3.7/site-packages/celery/bootsteps.py", line 214, in apply
    step.include(parent)
  File "/…/lib/python3.7/site-packages/celery/bootsteps.py", line 343, in include
    return self._should_include(parent)[0]
  File "/…/lib/python3.7/site-packages/celery/bootsteps.py", line 339, in _should_include
    return True, self.create(parent)
  File "/…/lib/python3.7/site-packages/celery/worker/components.py", line 215, in create
    w._persistence = w.state.Persistent(w.state, w.statedb, w.app.clock)
  File "/…/lib/python3.7/site-packages/celery/worker/state.py", line 189, in __init__
    self.merge()
  File "/…/lib/python3.7/site-packages/celery/worker/state.py", line 197, in merge
    self._merge_with(self.db)
  File "/…/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/…/lib/python3.7/site-packages/celery/worker/state.py", line 266, in db
    return self.open()
  File "/…/lib/python3.7/site-packages/celery/worker/state.py", line 193, in open
    self.filename, protocol=self.protocol, writeback=True,
  File "/usr/lib/python3.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.7/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
```
After deleting the two state files, celery booted; but all state is lost.

I suspect that this is caused by the same fragility of the [dbm](https://docs.python.org/3/library/dbm.html) module. Possible fix is linked in the related issue.

**Comment by thedrow** [comment]
This is how you compiled your Python.
You need to compile it with that module...

**Comment by jenstroeger** [comment]
I did not compile Python myself, I used the packages from

However, it seems that…
```
>>> import dbm
>>> dbm
<module 'dbm' from '/usr/lib/python3.7/dbm/__init__.py'>
>>> import dbm.gnu
Traceback (most recent call last):
  File "/usr/lib/python3.7/dbm/gnu.py", line 4, in <module>
    from _gdbm import *
ModuleNotFoundError: No module named '_gdbm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/dbm/gnu.py", line 6, in <module>
    raise ImportError(str(msg) + ', please install the python3-gdbm package')
ImportError: No module named '_gdbm', please install the python3-gdbm package
>>> 
```

**Comment by thedrow** [comment]
PRs welcome :)
