### ISSUE TITLE
_dbm.error: cannot add item to database (celery 4.3.0, python 3.7)

### ISSUE THREAD

**Issue by Meisterschueler** [celery/celery#5447]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

#4777 (but the work around "delete celerybeat-schedule file" does not work)

## Environment & Settings

**Celery version**:
4.3.0 (rhubarb)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.3.0 (rhubarb) kombu:4.4.0 py:3.7.2+
            billiard:3.6.0.0 redis:3.2.1
platform -> system:Linux arch:64bit, ELF
            kernel version:4.19.0-4-amd64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0

BROKER_URL: 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND: 'redis://localhost:6379/0'
ENV: 'production'
DEBUG: False
TESTING: False
PROPAGATE_EXCEPTIONS: None
PRESERVE_CONTEXT_ON_EXCEPTION: None
SECRET_KEY: '********'
PERMANENT_SESSION_LIFETIME: datetime.timedelta(days=31)
USE_X_SENDFILE: False
SERVER_NAME: None
APPLICATION_ROOT: '/'
SESSION_COOKIE_NAME: 'session'
SESSION_COOKIE_DOMAIN: None
SESSION_COOKIE_PATH: None
SESSION_COOKIE_HTTPONLY: True
SESSION_COOKIE_SECURE: False
SESSION_COOKIE_SAMESITE: None
SESSION_REFRESH_EACH_REQUEST: True
MAX_CONTENT_LENGTH: None
SEND_FILE_MAX_AGE_DEFAULT: datetime.timedelta(seconds=43200)
TRAP_BAD_REQUEST_ERRORS: None
TRAP_HTTP_EXCEPTIONS: False
EXPLAIN_TEMPLATE_LOADING: False
PREFERRED_URL_SCHEME: 'http'
JSON_AS_ASCII: True
JSON_SORT_KEYS: '********'
JSONIFY_PRETTYPRINT_REGULAR: False
JSONIFY_MIMETYPE: 'application/json'
TEMPLATES_AUTO_RELOAD: None
MAX_COOKIE_SIZE: 4093
CACHE_DEFAULT_TIMEOUT: 300
CACHE_TYPE: 'redis'
CELERYBEAT_SCHEDULE: {
    'purge_old_data': {   'kwargs': {'max_hours': 48},
                          'schedule': datetime.timedelta(seconds=600),
                          'task': 'purge_old_data'},
    'update-country-codes': {   'schedule': datetime.timedelta(seconds=60),
                                'task': 'update_receivers_country_code'},
    'update-ddb': {   'schedule': datetime.timedelta(seconds=3600),
                      'task': 'import_ddb'},
    'update-logbook': {   'schedule': datetime.timedelta(seconds=60),
                          'task': 'update_logbook_entries'},
    'update-max-altitudes': {   'schedule': <crontab: 30 0 * * * (m/h/d/dM/MY)>,
                                'task': 'update_logbook_max_altitude'},
    'update-stats-daily': {   'kwargs': {'day_offset': -1},
                              'schedule': <crontab: 5 0 * * * (m/h/d/dM/MY)>,
                              'task': 'update_stats'},
    'update-takeoff-and-landing': {   'kwargs': {'last_minutes': 10},
                                      'schedule': datetime.timedelta(seconds=60),
                                      'task': 'update_takeoff_landings'}}
CELERY_BROKER_URL: 'redis://localhost:6379/0'
SQLALCHEMY_DATABASE_URI: '********'
SQLALCHEMY_TRACK_MODIFICATIONS: False
BOOTSTRAP_USE_MINIFIED: True
BOOTSTRAP_CDN_FORCE_SSL: False
BOOTSTRAP_QUERYSTRING_REVVING: True
BOOTSTRAP_SERVE_LOCAL: False
BOOTSTRAP_LOCAL_SUBDOMAIN: None
SQLALCHEMY_BINDS: None
SQLALCHEMY_NATIVE_UNICODE: None
SQLALCHEMY_ECHO: False
SQLALCHEMY_RECORD_QUERIES: None
SQLALCHEMY_POOL_SIZE: None
SQLALCHEMY_POOL_TIMEOUT: None
SQLALCHEMY_POOL_RECYCLE: None
SQLALCHEMY_MAX_OVERFLOW: None
SQLALCHEMY_COMMIT_ON_TEARDOWN: False
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
aerofiles==0.4.1
alembic==1.0.8
amqp==2.4.2
Babel==2.6.0
billiard==3.6.0.0
celery==4.3.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
coverage==4.5.3
coveralls==1.2.0
docopt==0.6.2
dominate==2.3.5
flake8==3.5.0
Flask==1.0.2
Flask-Bootstrap==3.3.7.1
Flask-Caching==1.7.0
Flask-Migrate==2.3.1
flask-nav==0.6
Flask-SQLAlchemy==2.3.2
flower==0.9.2
GeoAlchemy2==0.5.0
geographiclib==1.49
geopy==1.17.0
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
kombu==4.4.0
lxml==4.3.2
Mako==1.0.7
MarkupSafe==1.1.1
mccabe==0.6.1
mgrs==1.3.5
nose==1.3.7
ogn-client==0.9.1
-e git+http://github.com/Meisterschueler/ogn-python@a177049d6e6d02e288b6ed141bab04efd878e53f#egg=ogn_python
pkg-resources==0.0.0
psycopg2-binary==2.7.6.1
pycodestyle==2.3.1
pyflakes==1.6.0
python-dateutil==2.8.0
python-editor==1.0.4
pytz==2018.9
redis==3.2.1
requests==2.21.0
Shapely==1.5.17
six==1.12.0
SQLAlchemy==1.3.1
tornado==5.1.1
tqdm==4.28.1
urllib3==1.24.1
vine==1.3.0
visitor==0.1.3
Werkzeug==0.14.1
xmlunittest==0.5.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

1. start the redis server ```redis-server```
2. start the worker ```celery -A ogn_python.collect worker -l info```
3. start the beat ```celery -A ogn_python.collect beat -l info```
<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Beat is running

# Actual Behavior

Beat is crashing
```
$ celery -A ogn_python.collect beat -l info
celery beat v4.3.0 (rhubarb) is starting.
__    -    ... __   -        _
LocalTime -> 2019-04-08 20:59:02
Configuration ->
    . broker -> redis://localhost:6379/0
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
[2019-04-08 20:59:02,200: INFO/MainProcess] beat: Starting...
[2019-04-08 20:59:02,216: CRITICAL/MainProcess] beat raised exception <class '_dbm.error'>: error('cannot add item to database')
Traceback (most recent call last):
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/celery/beat.py", line 524, in _create_schedule
    self._store[str('entries')]
  File "/usr/lib/python3.7/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
KeyError: b'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/celery/apps/beat.py", line 109, in start_scheduler
    service.start()
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/celery/beat.py", line 588, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/celery/beat.py", line 632, in scheduler
    return self.get_scheduler()
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/celery/beat.py", line 627, in get_scheduler
    lazy=lazy,
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/celery/beat.py", line 467, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/celery/beat.py", line 226, in __init__
    self.setup_schedule()
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/celery/beat.py", line 495, in setup_schedule
    self._create_schedule()
  File "/var/www/html/ogn-python/venv/lib/python3.7/site-packages/celery/beat.py", line 528, in _create_schedule
    self._store[str('entries')] = {}
  File "/usr/lib/python3.7/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database
```

**Comment by thedrow** [comment]
I'll check it but I wonder if it's related to your Python runtime.
Can you reproduce this on a pyenv built Python?

**Comment by esh-b** [comment]
I think the issue is with the user's Python runtime as mentioned. I tried to start the beat in Python3.7 and using celery 4.3.0. Beat starts with no issues.
Maybe try to start the beat after removing the `celerybeat-schedule` file.

**Comment by Meisterschueler** [comment]
Deleted the virtualenv and created it new. The bug is not reproducable anymore.

**Comment by shuklaabhi** [comment]
Pretty sure, you need to install python3-gdbm

**Comment by Kaju-Bubanja** [comment]
Any idea what is causing this issue? Because it's a problem that causes manual intervention.

**Comment by richlanc** [comment]
I'm able to recreate this issue and it's seemingly because of a corrupted DBM DB file. Would a fix PR be welcome?

**Comment by supreme-core** [comment]
this is fixed?
