### ISSUE TITLE
consumer: Connection to broker lost... ConnectionError: Bad frame read

### ISSUE THREAD

**Issue by Penguin7z** [celery/celery#5502]
Hi guys. I got something strange. I am using **Celery** with **rabbitmq** and **redis**. I found **every 390 seconds**, it will shows **consumer: Connection to broker lost. Trying to re-establish the connection...**, then it will reconnected successfully.
each error message fully displayed as below.

```
[2019-05-05 21:07:21,113: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/base.py", line 238, in on_readable
    reader(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/base.py", line 220, in _read
    drain_events(timeout=0)
  File "/usr/local/lib/python2.7/dist-packages/librabbitmq/__init__.py", line 227, in drain_events
    self._basic_recv(timeout)
ConnectionError: Bad frame read

then shows: reconnected successfully...
[2019-05-05 21:07:21,135: INFO/MainProcess] Connected to amqp://mq:**@11.0.0.18:5672/nc_to_wehome

```

**I have got some time snapshot. all is 390 seconds.**

```
[2019-05-05 21:07:21,113: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
same error shows: **ConnectionError: Bad frame read...**
then shows: reconnected successfully...

[2019-05-05 21:13:51,197: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
same error shows: **ConnectionError: Bad frame read...**
then shows: reconnected successfully...

[2019-05-05 21:20:21,286: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
same error shows: **ConnectionError: Bad frame read...**
then shows: reconnected successfully...

```

I am using 
```
ubuntu 16.04 with docker
python 2.7.12
celery==4.3.0
amqp==2.4.2
hiredis==1.0.0
redis==2.10.5
kombu==4.5.0
librabbitmq==2.0.0
```

why it lost connection every 390 seconds? and then why it could reconnect successfully immediately.

-------------------------------------------------------------------------------------
edit:
if some calls the job in this 390 seconds, it will not lost connection and always work correctly.

**Comment by vardhmanrp** [comment]
I was trying sample example of celery on Windows 7 with Celery 4.3.0.
Rabbitmq server 3.6.5
Python 3.7.2

I do observe this issue but didn't count the time at which it gets disconnected. Also it gets reconnect.

**Comment by auvipy** [comment]
could you check by dropping hiredis==1.0.0 from the setup?

**Comment by Penguin7z** [comment]
I got some more logs.
one is from rabbitmq-server. It shows **client unexpectedly closed TCP connection**
Have a look at time **2019-05-06 15:21:06.265**

```
client unexpectedly closed TCP connection
2019-05-06 15:08:06.110 [info] <0.12645.0> accepting AMQP connection <0.12645.0> (172.17.0.1:52106 -> 172.17.0.2:5672)
2019-05-06 15:08:06.113 [info] <0.12648.0> accepting AMQP connection <0.12648.0> (172.17.0.1:52110 -> 172.17.0.2:5672)
2019-05-06 15:08:06.117 [info] <0.12645.0> connection <0.12645.0> (172.17.0.1:52106 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:08:06.118 [info] <0.12648.0> connection <0.12648.0> (172.17.0.1:52110 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:08:06.128 [info] <0.12657.0> accepting AMQP connection <0.12657.0> (172.17.0.1:52114 -> 172.17.0.2:5672)
2019-05-06 15:08:06.153 [info] <0.12661.0> accepting AMQP connection <0.12661.0> (172.17.0.1:52118 -> 172.17.0.2:5672)
2019-05-06 15:08:06.153 [info] <0.12657.0> connection <0.12657.0> (172.17.0.1:52114 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:08:06.157 [info] <0.12661.0> connection <0.12661.0> (172.17.0.1:52118 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:14:36.167 [warning] <0.12645.0> closing AMQP connection <0.12645.0> (172.17.0.1:52106 -> 172.17.0.2:5672, vhost: 'nc_to_wehome', user: 'mq'):
client unexpectedly closed TCP connection
2019-05-06 15:14:36.167 [warning] <0.12657.0> closing AMQP connection <0.12657.0> (172.17.0.1:52114 -> 172.17.0.2:5672, vhost: 'nc_to_wehome', user: 'mq'):
client unexpectedly closed TCP connection
2019-05-06 15:14:36.168 [warning] <0.12648.0> closing AMQP connection <0.12648.0> (172.17.0.1:52110 -> 172.17.0.2:5672, vhost: 'nc_to_wehome', user: 'mq'):
client unexpectedly closed TCP connection
2019-05-06 15:14:36.169 [warning] <0.12661.0> closing AMQP connection <0.12661.0> (172.17.0.1:52118 -> 172.17.0.2:5672, vhost: 'nc_to_wehome', user: 'mq'):
client unexpectedly closed TCP connection
2019-05-06 15:14:36.175 [info] <0.12731.0> accepting AMQP connection <0.12731.0> (172.17.0.1:52178 -> 172.17.0.2:5672)
2019-05-06 15:14:36.176 [info] <0.12722.0> accepting AMQP connection <0.12722.0> (172.17.0.1:52174 -> 172.17.0.2:5672)
2019-05-06 15:14:36.181 [info] <0.12722.0> connection <0.12722.0> (172.17.0.1:52174 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:14:36.181 [info] <0.12731.0> connection <0.12731.0> (172.17.0.1:52178 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:14:36.194 [info] <0.12740.0> accepting AMQP connection <0.12740.0> (172.17.0.1:52182 -> 172.17.0.2:5672)
2019-05-06 15:14:36.197 [info] <0.12743.0> accepting AMQP connection <0.12743.0> (172.17.0.1:52186 -> 172.17.0.2:5672)
2019-05-06 15:14:36.198 [info] <0.12740.0> connection <0.12740.0> (172.17.0.1:52182 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:14:36.202 [info] <0.12743.0> connection <0.12743.0> (172.17.0.1:52186 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:21:06.265 [warning] <0.12722.0> closing AMQP connection <0.12722.0> (172.17.0.1:52174 -> 172.17.0.2:5672, vhost: 'nc_to_wehome', user: 'mq'):
client unexpectedly closed TCP connection
2019-05-06 15:21:06.265 [warning] <0.12743.0> closing AMQP connection <0.12743.0> (172.17.0.1:52186 -> 172.17.0.2:5672, vhost: 'nc_to_wehome', user: 'mq'):
client unexpectedly closed TCP connection
2019-05-06 15:21:06.266 [warning] <0.12731.0> closing AMQP connection <0.12731.0> (172.17.0.1:52178 -> 172.17.0.2:5672, vhost: 'nc_to_wehome', user: 'mq'):
client unexpectedly closed TCP connection
2019-05-06 15:21:06.266 [warning] <0.12740.0> closing AMQP connection <0.12740.0> (172.17.0.1:52182 -> 172.17.0.2:5672, vhost: 'nc_to_wehome', user: 'mq'):
client unexpectedly closed TCP connection
2019-05-06 15:21:06.274 [info] <0.12814.0> accepting AMQP connection <0.12814.0> (172.17.0.1:52240 -> 172.17.0.2:5672)
2019-05-06 15:21:06.278 [info] <0.12814.0> connection <0.12814.0> (172.17.0.1:52240 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:21:06.280 [info] <0.12820.0> accepting AMQP connection <0.12820.0> (172.17.0.1:52244 -> 172.17.0.2:5672)
2019-05-06 15:21:06.289 [info] <0.12823.0> accepting AMQP connection <0.12823.0> (172.17.0.1:52248 -> 172.17.0.2:5672)
2019-05-06 15:21:06.300 [info] <0.12820.0> connection <0.12820.0> (172.17.0.1:52244 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:21:06.302 [info] <0.12823.0> connection <0.12823.0> (172.17.0.1:52248 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome'
2019-05-06 15:21:06.313 [info] <0.12837.0> accepting AMQP connection <0.12837.0> (172.17.0.1:52252 -> 172.17.0.2:5672)
2019-05-06 15:21:06.318 [info] <0.12837.0> connection <0.12837.0> (172.17.0.1:52252 -> 172.17.0.2:5672): user 'mq' authenticated and granted access to vhost 'nc_to_wehome

```

I also trace the code, it's in file **/celery/worker/consumer/consumer.py** line 319
```
    def start(self):
        blueprint = self.blueprint
        while blueprint.state not in STOP_CONDITIONS:
            maybe_shutdown()
            if self.restart_count:
                try:
                    self._restart_state.step()
                except RestartFreqExceeded as exc:
                    crit('Frequent restarts detected: %r', exc, exc_info=1)
                    sleep(1)
            self.restart_count += 1
            try:
                blueprint.start(self)
            except self.connection_errors as exc:
                # If we're not retrying connections, no need to catch
                # connection errors
                if not self.app.conf.broker_connection_retry:
                    raise
                if isinstance(exc, OSError) and exc.errno == errno.EMFILE:
                    raise  # Too many open files
                maybe_shutdown()
                if blueprint.state not in STOP_CONDITIONS:
                    if self.connection:
                        self.on_connection_error_after_connected(exc)
                    else:
                        self.on_connection_error_before_connected(exc)
                    self.on_close()
                    blueprint.restart(self)
```

every 390 seconds, will step in code **except self.connection_errors as exc:** I am still try to figure it out.

**Comment by Penguin7z** [comment]
> could you check by dropping hiredis==1.0.0 from the setup?

@auvipy I have tried it by dropping hiredis, same problem.

**Comment by auvipy** [comment]
i suggest posting on IRC or mailing list as well.

**Comment by Penguin7z** [comment]
> i suggest posting on IRC or mailing list as well.

@auvipy if I add --beat in start script, it's all ok.
update  start script 

```
celery -A app worker -l info...
```

 to be 

```
celery -A app worker --beat -l info...
```

no connection broken anymore, no the problem **390 seconds** above.
