### ISSUE TITLE
TypeError when waiting for results using join_native in a group

### ISSUE THREAD

**Issue by ikalyvas** [celery/celery#5511]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:
        4.3.0 (rhubarb)                                                                                                                                                                              

<details>
<summary><b><code>celery report</code> Output:<br>software -> celery:4.3.0 (rhubarb)<br><> kombu:4.5.0 py:3.6.4<br>                                                                                                                              
            billiard:3.6.0.0 py-amqp:2.4.2 <br>                                                                                                                                           
platform -> system:Linux arch:64bit, ELF<br>                                                                                                                                                     
            kernel version:3.10.0-693.11.1.el7.x86_64 imp:CPython<br>
loader   -> celery.loaders.default.Loader<br>
settings -> transport:amqp results:disabled
</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: Python 3.6.4
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: CentOS Linux release 7.4.1708 (Core) <br>
Linux  3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:
amqp==2.4.2
asn1crypto==0.24.0
Babel==2.6.0
backcall==0.1.0
bcrypt==3.1.6
billiard==3.6.0.0
celery==4.3.0
cffi==1.12.3
cryptography==2.6.1
decorator==4.4.0
flower==0.9.3
ipython==7.5.0
ipython-genutils==0.2.0
jedi==0.13.3
kombu==4.5.0
lxml==4.3.3
paramiko==2.4.2
parso==0.4.0
pexpect==4.7.0
pickleshare==0.7.5
prompt-toolkit==2.0.9
ptyprocess==0.6.0
pyaml==19.4.1
pyasn1==0.4.5
pycparser==2.19
Pygments==2.4.0
PyNaCl==1.3.0
pytz==2019.1
PyYAML==5.1
redis==3.2.1
scp==0.13.2
six==1.12.0
tornado==5.1.1
traitlets==4.3.2
vine==1.3.0
wcwidth==0.1.7

</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

in a code like the following:
```python
    subtasks = []
    states = yaml.safe_load(open(STATES))

    for _, batch in states.items():
        for sub_batch in batch:
            subtasks.append(create_multipolygons.s(sub_batch, " "))
    job = group(subtasks)
    results = job.apply_async()
    for result in results.join_native(interval=300):
        logger.info(f"Processed {result}")
```

should wait for the results to be completed and print the log as many times as the results

# Actual Behavior

Instead, 

i am getting (not always) the following exception:

```
(celery_orch) [tts@uthttn13 celery_orch]$ python orch.py       
Traceback (most recent call last):
  File "orch.py", line 55, in <module>
    start_execution()
  File "orch.py", line 41, in start_execution
    for result in results.join_native(interval=300):
  File "/home/tts/.local/share/virtualenvs/celery_orch-oKbCb8co/lib/python3.6/site-packages/celery/result.py", line 815, in join_native
    on_message, on_interval):
  File "/home/tts/.local/share/virtualenvs/celery_orch-oKbCb8co/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 142, in iter_native
    for _ in self._wait_for_pending(result, no_ack=no_ack, **kwargs):
  File "/home/tts/.local/share/virtualenvs/celery_orch-oKbCb8co/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 255, in _wait_for_pending
    on_interval=on_interval):
  File "/home/tts/.local/share/virtualenvs/celery_orch-oKbCb8co/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 56, in drain_events_until
    yield self.wait_for(p, wait, timeout=1)
  File "/home/tts/.local/share/virtualenvs/celery_orch-oKbCb8co/lib/python3.6/site-packages/celery/backends/asynchronous.py", line 65, in wait_for
    wait(timeout=timeout)
  File "/home/tts/.local/share/virtualenvs/celery_orch-oKbCb8co/lib/python3.6/site-packages/celery/backends/redis.py", line 129, in drain_events
    self.on_state_change(self._decode_result(message['data']), message)
  File "/home/tts/.local/share/virtualenvs/celery_orch-oKbCb8co/lib/python3.6/site-packages/celery/backends/base.py", line 305, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/home/tts/.local/share/virtualenvs/celery_orch-oKbCb8co/lib/python3.6/site-packages/celery/backends/base.py", line 301, in meta_from_decoded
    meta['result'] = self.exception_to_python(meta['result'])
  File "/home/tts/.local/share/virtualenvs/celery_orch-oKbCb8co/lib/python3.6/site-packages/celery/backends/base.py", line 281, in exception_to_python
    exc = cls(*exc_msg if isinstance(exc_msg, tuple) else exc_msg)
TypeError: __init__() missing 5 required positional arguments: 'url', 'code', 'msg', 'hdrs', and 'fp'
```
-->

**Comment by thedrow** [comment]
@ikalyvas Why did you close this issue?

**Comment by ikalyvas** [comment]
Because I found the solution.I do not know if this is expected behaviour but I saw that my task was throwing urllib.error.HTTPError , an exception with 5 arguments.Passing this to join_native seems to cause the type error since the arguments are missing.So I catch the http error in my task and raise oserror .this seem to keep join happy.Should this behave like that?

**Comment by thedrow** [comment]
I'm fairly certain this is a bug.
However, the code you provided does not constitute as a test case.

Please provide us with the most minimal test case possible to reproduce this problem.

**Comment by ikalyvas** [comment]
I would gladly write a testcase,is there any guideline to follow so as to provide what you asked?

**Comment by auvipy** [comment]
https://github.com/celery/celery/issues/5057 are they related?

**Comment by thedrow** [comment]
A test case is something you can run as a script or as part of our integration test suite.
You can open a PR with the relevant tests or include a script here which I'll use to convert into a test for our integration suite.

**Comment by thedrow** [comment]
@auvipy #5057 is related to #5290. Not to this issue.

**Comment by auvipy** [comment]
ok

**Comment by ikalyvas** [comment]
@drow  i have created a PR.Please check it if you have some time and let me know if its OK.

**Comment by auvipy** [comment]
If the test fails fix will be needed

**Comment by ikalyvas** [comment]
As you can see the test passes because I made it to pass.The custom error task raises a full flavoured exception with all's necessary arguments.However the join call will receive a typeerror instead of the http error. I can make the test fail by expecting to raise the same exception (is http error) as it should be the correct behaviour.

**Comment by ikalyvas** [comment]
just added another test case where you can see the failure

**Comment by tothegump** [comment]
In the `celery.backends.base.Backend.prepare_exception`, `exc_message` field comes from `exc.args`.
Looks like, it assume exception parameters would store in `exception.args`. But `urllib.error.HTTPError` does not save parameters in args.
So, when the exception deserialize from json, `HTTPError.__init__` will not receive any args, while it expect 5 positional arguments, that's why it raise a `TypeError`.

 I'm sorry, I have no idea for how to get the parameters of the `HTTPError.__init__`, and I even don't know, am i on the right way of thinking?

**Comment by georgepsarakis** [comment]
@tothegump I think that https://github.com/celery/celery/commit/b54da11598fc6a7e360ca9bc09e1bcdfafa3cd1f adds a temporary patch for the exception deserialization issue that you are describing.

**Comment by tothegump** [comment]
@georgepsarakis Yes, you are right. As described by @ikalyvas , Celery 4.3.0 raise a `TypeError`, and after commit b54da11, raise a Exception with args `("<class 'urllib.error.HTTPError'>([])",)`.
According to the unit test, raise a `urllib.error.HTTPError` is expected behavior.
So, what is expected behavior indeed? Is a Exception with string args `("<class 'urllib.error.HTTPError'>([])",)` enough?

**Comment by auvipy** [comment]
@ikalyvas PR?

**Comment by ikalyvas** [comment]
@auvipy you mean #5524 ?

**Comment by auvipy** [comment]
yeah!!

**Comment by auvipy** [comment]
anyone got a fix for this?
