### ISSUE TITLE
Having / in password gives an int base 10 error

### ISSUE THREAD

**Issue by akshaybabloo** [celery/celery#5532]
I am trying to setup AMQP with username and password in Django if the password contains `/` I am getting an error as `ValueError: invalid literal for int() with base 10`.

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.3.0 (rhubarb) kombu:4.5.0 py:3.7.3
            billiard:3.6.0.0 py-amqp:2.4.2
platform -> system:Windows arch:64bit, WindowsPE
            kernel version:10 imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

</p>
</details>

# Steps to Reproduce

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery

app = Celery('tasks', broker='amqps://user:pass/word@localhost', broker_use_ssl=True)

@app.task
def add(x, y):
    return x + y

add.delay(1,2)
```

</p>
</details>

# Expected Behavior
I get a traceback as

```
Traceback (most recent call last):
  File ".\temp.py", line 283, in <module>
    add.delay(1,2)
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\celery\app\task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\celery\app\task.py", line 570, in apply_async
    **options
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\celery\app\base.py", line 752, in send_task
    with self.producer_or_acquire(producer) as P:
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\celery\app\base.py", line 887, in producer_or_acquire
    producer, self.producer_pool.acquire, block=True,
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\celery\app\base.py", line 1257, in producer_pool
    return self.amqp.producer_pool
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\celery\app\amqp.py", line 612, in producer_pool
    self.app.connection_for_write()]
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\celery\app\base.py", line 784, in connection_for_write
    return self._connection(url or self.conf.broker_write_url, **kwargs)
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\celery\app\base.py", line 852, in _connection
    'broker_connection_timeout', connect_timeout
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\kombu\connection.py", line 189, in __init__
    url_params = parse_url(hostname)
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\kombu\utils\url.py", line 47, in parse_url
    scheme, host, port, user, password, path, query = _parse_url(url)
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\site-packages\kombu\utils\url.py", line 81, in url_to_parts
    parts.port,
  File "C:\Users\aksha\Miniconda3\envs\neucube\lib\urllib\parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'pass'
```

# Actual Behavior

should add both numbers

**Comment by esh-b** [comment]
From the info on the rabbitmq [website](https://www.rabbitmq.com/uri-spec.html) (section 2), the username and password must follow the pattern `*( unreserved / pct-encoded / sub-delims )` and this stackoverflow [question](https://stackoverflow.com/questions/32662166/can-username-or-password-have-a-hash-in-it-according-to-w3c-spec) talks about the characters that can be used for the pattern.

I hope that answers your question.

**Comment by akshaybabloo** [comment]
True, but if this library is going to next version, amqp 1.0 then azure provides amqp 1.0 and they use / in their random keys. This is just compatibility with other providers

**Comment by esh-b** [comment]
The general URI syntax says that we must uri-encode the `: / ? # [ ] @` set before we use it in the URI  (since these chars are used as delimiters in URI parsing). So, the passwords with those charset if uri-encoded, can be used in the URI syntax. 

One solution is to first find the `username` and `password` in the given `url` (using regex), uri-encode them, put them back in the URI and then send them to `urlparse` method as in: 
https://github.com/celery/kombu/blob/e83f1c537166b018e3ada0241c4471798edf79b0/kombu/utils/url.py#L71-L86

Just to add, the above problem is not related with any protocol. Its just an issue with the reserved charset in URI.
@auvipy need your suggestions on this.
