### ISSUE TITLE
MySQL connection error causes celery worker to keep running but execute no tasks

### ISSUE THREAD

**Issue by salty-horse** [celery/celery#5563]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.3.0 (rhubarb) kombu:4.6.0 py:3.6.8
            billiard:3.6.0.0 redis:3.2.0
platform -> system:Linux arch:64bit
            kernel version:4.15.0-50-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:django-db
```

</p>
</details>

# Steps to Reproduce

Run a celery worker with a MySQL backend (possibly through Django).
After the worker is up, shut down the MySQL service.
Try running a task.

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: 4.2.0
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
celery==4.3.0
Django==2.2.1
mysqlclient==1.4.2
```
(only relevant packages)

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

This is a non-recoverable error. The worker process should terminate, which would be treated as an error by a monitoring tool that will restart it.

# Actual Behavior
An exception is printed to stderr. The worker itself keeps running, receiving tasks, but never running them.
An exception is printed after each "Task accepted" log message.
<details>
<p>

```
[ERROR/MainProcess] Pool callback raised exception: OperationalError(2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Traceback (most recent call last):
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[REDACTED]/lib/python3.6/site-packages/billiard/pool.py", line 1750, in safe_apply_callback
    fun(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/request.py", line 371, in on_failure
    store_result=self.store_errors,
  File "[REDACTED]/lib/python3.6/site-packages/celery/backends/base.py", line 160, in mark_as_failure
    traceback=traceback, request=request)
  File "[REDACTED]/lib/python3.6/site-packages/celery/backends/base.py", line 342, in store_result
    request=request, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 35, in _store_result
    task_kwargs=task_kwargs,
  File "[REDACTED]/lib/python3.6/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/django_celery_results/managers.py", line 126, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```

</p>
</details>

This is unhelpful. Without looking at the logs you wouldn't know anything was wrong.

In the production setting, the exception is only printed as many times as there are concurrent workers, which makes it even harder to identify. I was not able to reproduce this particular behavior locally, and get an exception each time.

**Comment by auvipy** [comment]
can you try new django celery integrations releases? or celery 4.4.0rc1?

**Comment by matteius** [comment]
FWIW I found it better to run Cerlery and Django without django-celery -- since I don't see django-celery listed in the pip freeze I would not recommend adding it.

@salty-horse  I suspect this could be an application configuration error or a task implementation error possibly.   From the report, it sounds as though once the database is lost, that the tasks must all continue to error in the same way due to the socket being closed.  I did a quick search and think this might be helpful:  https://stackoverflow.com/questions/18150858/operationalerror-2002-cant-connect-to-local-mysql-server-through-socket-v

**Comment by salty-horse** [comment]
I'm terribly sorry, the test-case I wrote above is completely wrong. I was trying to replicate the production environment, tested the wrong thing, and failed to even describe the problem correctly.

The issue is in fact related to mysql errors **while revoking tasks**, and is very similar to an issue I reported as celery/django-celery-results#88.
While that bug was fixed at the time I reported it, this bug is still present in 4.4.0rc2.

If you wish I can close this bug and open a new one, maybe in that other project(?), but for now I will describe it here.

While the celery worker is running, and while using mysql as a results backend, perform these steps:
1) Shut down mysql (simulating a connection issue)
2) Attempt to run a task and revoke it as many times as there are workers:
```
from APPNAME.tasks import delayed_print
result = delayed_print.apply_async(args=['this is a test'], countdown=5)
AsyncResult(result.id).revoke()
```
This will cause an error in `kombu` and will crash the process.

<details>
<summary>Error message</summary>
<p>

```
[TIMESTAMP: ERROR/MainProcess] Error in timer: OperationalError(2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Traceback (most recent call last):
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[REDACTED]/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 145, in fire_timers
    entry()
  File "[REDACTED]/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 478, in apply_eta_task
    self.on_task_request(task)
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/worker.py", line 223, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
  File "[REDACTED]/lib/python3.6/site-packages/kombu/asynchronous/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/worker.py", line 228, in _process_task
    req.execute_using_pool(self.pool)
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/request.py", line 631, in execute_using_pool
    if (self.expires or task_id in revoked_tasks) and self.revoked():
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/request.py", line 419, in revoked
    'expired' if expired else 'revoked', False, None, expired,
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/request.py", line 402, in _announce_revoked
    store_result=self.store_errors,
  File "[REDACTED]/lib/python3.6/site-packages/celery/backends/base.py", line 212, in mark_as_revoked
    traceback=None, request=request)
  File "[REDACTED]/lib/python3.6/site-packages/celery/backends/base.py", line 348, in store_result
    request=request, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 35, in _store_result
    task_kwargs=task_kwargs,
  File "[REDACTED]/lib/python3.6/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/django_celery_results/managers.py", line 126, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
[2019-06-17 11:59:48,245: INFO/MainProcess] Discarding revoked task: tasks.delayed_print[b90dfb64-42e0-4db9-97e2-3e12406eb238]
[2019-06-17 11:59:48,255: ERROR/MainProcess] Error in timer: OperationalError(2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Traceback (most recent call last):
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[REDACTED]/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 145, in fire_timers
    entry()
  File "[REDACTED]/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 478, in apply_eta_task
    self.on_task_request(task)
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/worker.py", line 223, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
  File "[REDACTED]/lib/python3.6/site-packages/kombu/asynchronous/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/worker.py", line 228, in _process_task
    req.execute_using_pool(self.pool)
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/request.py", line 631, in execute_using_pool
    if (self.expires or task_id in revoked_tasks) and self.revoked():
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/request.py", line 419, in revoked
    'expired' if expired else 'revoked', False, None, expired,
  File "[REDACTED]/lib/python3.6/site-packages/celery/worker/request.py", line 402, in _announce_revoked
    store_result=self.store_errors,
  File "[REDACTED]/lib/python3.6/site-packages/celery/backends/base.py", line 212, in mark_as_revoked
    traceback=None, request=request)
  File "[REDACTED]/lib/python3.6/site-packages/celery/backends/base.py", line 348, in store_result
    request=request, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 35, in _store_result
    task_kwargs=task_kwargs,
  File "[REDACTED]/lib/python3.6/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/django_celery_results/managers.py", line 126, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "[REDACTED]/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```

</p>
</details>


### Result:

If you then restart mysql, it will have no effect, as all the workers have already crashed. The main process will keep running, and print "Received task" messages, but no task will run.

The example I posted at the top isn't really an issue, as I unfortunately neglected to mention the real test: After restarting mysql, I can keep running tasks, and celery doesn't complain - it reconnects to mysql.

But when the connection is lost, and **an attempt to revoke a task is made**, that's when the worker crashes and the process keeps going as if nothing bad happens.

**Comment by salty-horse** [comment]
Has this been fixed? Do you need me to test again?

**Comment by auvipy** [comment]
yes please test and report again
