### ISSUE TITLE
TypeError: autodiscover_tasks() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by shiyiwenv** [celery/celery#5596]
celery version 4.3.0
django 1.11

Usage this page deployment : http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#where-to-go-from-here

![image](https://user-images.githubusercontent.com/41094243/59489669-69fe2980-8eb5-11e9-934c-12cf6896ca5d.png)

![image](https://user-images.githubusercontent.com/41094243/59489681-72eefb00-8eb5-11e9-88a8-9d17773cd7e8.png)

![image](https://user-images.githubusercontent.com/41094243/59489686-784c4580-8eb5-11e9-8958-4c2151f7ab25.png)

Run command : celery -A proj worker -l info

Error :
E:\sfsm\proj>celery -A proj worker -l info
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\PYTHON27\SCRIPTS\celery.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\celery\__main__.py", line 30, in main
    main()
  File "c:\python27\lib\site-packages\celery\bin\celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "c:\python27\lib\site-packages\celery\bin\celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "c:\python27\lib\site-packages\celery\bin\base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "c:\python27\lib\site-packages\celery\bin\base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "c:\python27\lib\site-packages\celery\bin\base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "c:\python27\lib\site-packages\celery\app\utils.py", line 235, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "c:\python27\lib\site-packages\celery\bin\base.py", line 492, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "c:\python27\lib\site-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "c:\python27\lib\site-packages\celery\utils\imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "c:\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\sfsm\proj\proj\__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "E:\sfsm\proj\proj\celery.py", line 17, in <module>
    app.autodiscover_tasks()
TypeError: autodiscover_tasks() takes at least 2 arguments (1 given)

Why did it go wrong? I did it exactly according to the tutorial.

**Comment by auvipy** [comment]
post on the mailing list. GitHub is for bug reports mainly
