### ISSUE TITLE
Serialization of RetryError from tenacity library fails

### ISSUE THREAD

**Issue by OskarPersson** [celery/celery#5626]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- #3586

#### Possible Duplicates

- #3586

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.0rc2 (cliffs) kombu:4.6.3 py:3.6.7
            billiard:3.6.0.0 py-amqp:2.5.0
platform -> system:Linux arch:64bit
            kernel version:4.9.125-linuxkit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:redis://redis/

broker_url: 'amqp://guest:********@rabbit:5672//'
result_backend: 'redis://redis/'
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
alabaster==0.7.12
amqp==2.5.0
asn1crypto==0.24.0
aspy.yaml==1.3.0
atomicwrites==1.3.0
attrs==19.1.0
aws-xray-sdk==0.95
azure-common==1.1.5
azure-nspkg==3.0.2
azure-storage==0.36.0
azure-storage-common==1.1.0
azure-storage-nspkg==3.1.0
Babel==2.7.0
basho-erlastic==2.1.1
billiard==3.6.0.0
boto==2.49.0
boto3==1.9.180
botocore==1.12.180
bumpversion==0.5.3
case==1.5.3
cassandra-driver==3.18.0
celery==4.4.0rc2
certifi==2019.6.16
cffi==1.12.3
cfgv==2.0.0
chardet==3.0.4
codecov==2.0.15
couchbase==2.5.5
coverage==4.5.3
cryptography==2.7
DateTime==4.3
dnspython==1.16.0
docker==4.0.2
docutils==0.14
ecdsa==0.13.2
elasticsearch==7.0.2
entrypoints==0.3
ephem==3.7.6.0
eventlet==0.25.0
filelock==3.0.12
flake8==3.7.7
flakeplus==1.1.0
future==0.17.1
gevent==1.4.0
greenlet==0.4.15
identify==1.4.5
idna==2.8
imagesize==1.1.0
importlib-metadata==0.18
importlib-resources==1.0.2
Jinja2==2.10.1
jmespath==0.9.4
jsondiff==1.1.1
jsonpickle==1.2
kombu==4.6.3
linecache2==1.0.0
MarkupSafe==1.1.1
mccabe==0.6.1
mock==3.0.5
monotonic==1.5
more-itertools==7.1.0
moto==1.3.7
msgpack==0.6.1
nodeenv==1.3.3
nose==1.3.7
packaging==19.0
pluggy==0.12.0
pre-commit==1.17.0
py==1.8.0
pyaml==19.4.1
pyArango==1.3.2
pycodestyle==2.5.0
pycouchdb==1.14
pycparser==2.19
pycryptodome==3.8.2
pycurl==7.43.0.3
pydocstyle==1.1.1
pydocumentdb==2.3.2
pyflakes==2.1.1
Pygments==2.4.2
pylibmc==1.6.0
pymongo==3.8.0
pyparsing==2.4.0
pytest==4.6.4
pytest-cov==2.7.1
pytest-sugar==0.9.2
pytest-travis-fold==1.3.0
python-consul==1.1.0
python-dateutil==2.8.0
python-jose==2.0.2
python-memcached==1.59
python3-protobuf==2.5.0
pytz==2019.1
PyYAML==5.1.1
redis==3.2.1
requests==2.22.0
responses==0.10.6
riak==2.7.0
s3transfer==0.2.1
simplejson==3.16.0
six==1.12.0
snowballstemmer==1.9.0
softlayer-messaging==1.0.3
Sphinx==1.8.5
sphinx-celery==1.4.6
sphinx-testing==0.7.2
sphinx2rst==1.1.0
sphinxcontrib-websupport==1.1.2
SQLAlchemy==1.3.5
tblib==1.4.0
tenacity==5.0.4
termcolor==1.1.0
toml==0.10.0
tox==3.13.1
traceback2==1.4.0
typing==3.7.4
Unipath==1.1
unittest2==1.1.0
urllib3==1.25.3
vine==1.3.0
virtualenv==16.6.1
wcwidth==0.1.7
websocket-client==0.56.0
Werkzeug==0.15.4
wrapt==1.11.2
xmltodict==0.12.0
zipp==0.5.1
zope.interface==4.6.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery
from tenacity import retry, stop_after_attempt, wait_fixed

app = Celery('tasks', broker='pyamqp://rabbit:5672', backend='redis://redis/')

@retry(reraise=False, stop=stop_after_attempt(2), wait=wait_fixed(1))
def foo(x):
    print('attempt foo')
    raise ValueError('this is value error')

@app.task
def add(x, y):
    foo(x)
    return x + y
```

</p>
</details>

# Expected Behavior

Running the `add` task should result in the following output

``` python
attempt foo
attempt foo
Traceback (most recent call last):
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/home/developer/celery/tasks.py", line 15, in foo
    foo(x)
ValueError: this is value error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/developer/celery/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/developer/celery/celery/app/task.py", line 400, in __call__
    return self.run(*args, **kwargs)
  File "/home/developer/celery/tasks.py", line 21, in add
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/tenacity/__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/tenacity/__init__.py", line 332, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7fe83b4c4240 state=finished raised ValueError>]
```

# Actual Behavior

Instead, it fails to serialize the exception

``` python
[2019-07-01 17:47:12,837: WARNING/ForkPoolWorker-1] attempt foo
[2019-07-01 17:47:13,846: WARNING/ForkPoolWorker-1] attempt foo
[2019-07-01 17:47:13,866: ERROR/ForkPoolWorker-1] Task tasks.add[f303fe29-11fe-4da6-aed4-97648b0c27d1] raised unexpected: RetryError('<Future at 0x7fdf2212b710 state=finished raised ValueError>',)
Traceback (most recent call last):
  File "/home/developer/celery/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/developer/celery/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/developer/celery/tasks.py", line 21, in add
    foo(x)
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/tenacity/__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/tenacity/__init__.py", line 332, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: <Future at 0x7fdf2212b710 state=finished raised ValueError>
[2019-07-01 17:47:13,880: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: RetryError('<Future at 0x7fdf2212b710 state=finished raised ValueError>',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'tenacity.RetryError\'>: it\'s not the same object as tenacity.RetryError",)''.>
Traceback (most recent call last):
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/billiard/pool.py", line 362, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: RetryError('<Future at 0x7fdf2212b710 state=finished raised ValueError>',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'tenacity.RetryError\'>: it\'s not the same object as tenacity.RetryError",)''.
```

**Comment by mezgerj** [comment]
This isn't an issue with the celery library, but there is an issue with the tenacity library in that its exceptions cannot be pickled. I have raised a [PR](https://github.com/jd/tenacity/pull/183) according to the [celery guidelines](https://docs.celeryproject.org/en/latest/userguide/tasks.html#creating-pickleable-exceptions) for creating pickleable exceptions
