### ISSUE TITLE
TypeError: wrap_socket() got an unexpected keyword argument '_contex t'

### ISSUE THREAD

**Issue by zyyoo** [celery/celery#5647]
python 3.7 + celery4.3 +django2.2  on windows

>celery -A kdTools worker -l info -P eventlet  start celery
use requests model,find a problem

[2019-07-18 19:30:51,338: ERROR/MainProcess] Task domain.tasks.build
html_celery[bda2062e-eb5d-4bdf-afc6-c43e0ebf228a] raised unexpected:
 TypeError("wrap_socket() got an unexpected keyword argument '_conte
xt'")
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\celery\app\trace.py", line 385
, in trace_task
    R = retval = fun(*args, **kwargs)
  File "c:\python37\lib\site-packages\celery\app\trace.py", line 648
, in __protected_call__
    return self.run(*args, **kwargs)
  File "D:\domain_v1\domain\tasks.py", line 10, in buildhtml_celery
    result = build_ins.main()
  File "D:\domain_v1\domain\api_reslove.py", line 385, in main
    self.build_website(res_dic, check_ip_axist)
  File "D:\domain_v1\domain\api_reslove.py", line 354, in build_webs
ite
    res_dic['cdn_code'],res_dic['cdn_cname'],res_dic['cdn_info'] = s
elf.cdn_open()
  File "D:\domain_v1\domain\api_reslove.py", line 194, in cdn_open
    cdn_cname = create_cdn.get_cname(self.ip, cdn_301_name, cdn_writ
e)
  File "D:\domain_v1\domain\tools\wangsu_v1.py", line 117, in get_cn
ame
    return self.get_domain(domain)
  File "D:\domain_v1\domain\tools\wangsu_v1.py", line 56, in get_dom
ain
    result = self.sendRequest(httpUrl, method)
  File "D:\domain_v1\domain\tools\wangsu_v1.py", line 44, in sendReq
uest
    resp = requests.get(httpUrl, headers=self.header,timeout=(5.0,30
.0))
  File "c:\python37\lib\site-packages\requests\api.py", line 75, in
get
    return request('get', url, params=params, **kwargs)
  File "c:\python37\lib\site-packages\requests\api.py", line 60, in
request
    return session.request(method=method, url=url, **kwargs)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 53
3, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 64
6, in send
    r = adapter.send(request, **kwargs)
  File "c:\python37\lib\site-packages\requests\adapters.py", line 44
9, in send
    timeout=timeout
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", li
ne 600, in urlopen
    chunked=chunked)
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", li
ne 343, in _make_request
    self._validate_conn(conn)
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", li
ne 839, in _validate_conn
    conn.connect()
  File "c:\python37\lib\site-packages\urllib3\connection.py", line 3
44, in connect
    ssl_context=context)
  File "c:\python37\lib\site-packages\urllib3\util\ssl_.py", line 34
5, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname
)
  File "c:\python37\lib\site-packages\eventlet\green\ssl.py", line 4
38, in wrap_socket
    return GreenSSLSocket(sock, *a, _context=self, **kw)
  File "c:\python37\lib\site-packages\eventlet\green\ssl.py", line 7
6, in __new__
    *args, **kw
TypeError: wrap_socket() got an unexpected keyword argument '_contex
t'
[2019-07-18 19:30:57,379: INFO/MainProcess] Received task: domain.ta
sks.buildhtml_celery[330d3e52-c085-46bb-8adc-0315e6043054]

[2019-07-18 19:30:57,477: ERROR/MainProcess] Task domain.tasks.build
html_celery[330d3e52-c085-46bb-8adc-0315e6043054] raised unexpected:
 TypeError("wrap_socket() got an unexpected keyword argument '_conte
xt'")
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\celery\app\trace.py", line 385
, in trace_task
    R = retval = fun(*args, **kwargs)
  File "c:\python37\lib\site-packages\celery\app\trace.py", line 648
, in __protected_call__
    return self.run(*args, **kwargs)
  File "D:\domain_v1\domain\tasks.py", line 10, in buildhtml_celery
    result = build_ins.main()
  File "D:\domain_v1\domain\api_reslove.py", line 385, in main
    self.build_website(res_dic, check_ip_axist)
  File "D:\domain_v1\domain\api_reslove.py", line 354, in build_webs
ite
    res_dic['cdn_code'],res_dic['cdn_cname'],res_dic['cdn_info'] = s
elf.cdn_open()
  File "D:\domain_v1\domain\api_reslove.py", line 194, in cdn_open
    cdn_cname = create_cdn.get_cname(self.ip, cdn_301_name, cdn_writ
e)
  File "D:\domain_v1\domain\tools\wangsu_v1.py", line 117, in get_cn
ame
    return self.get_domain(domain)
  File "D:\domain_v1\domain\tools\wangsu_v1.py", line 56, in get_dom
ain
    result = self.sendRequest(httpUrl, method)
  File "D:\domain_v1\domain\tools\wangsu_v1.py", line 44, in sendReq
uest
    resp = requests.get(httpUrl, headers=self.header,timeout=(5.0,30
.0))
  File "c:\python37\lib\site-packages\requests\api.py", line 75, in
get
    return request('get', url, params=params, **kwargs)
  File "c:\python37\lib\site-packages\requests\api.py", line 60, in
request
    return session.request(method=method, url=url, **kwargs)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 53
3, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 64
6, in send
    r = adapter.send(request, **kwargs)
  File "c:\python37\lib\site-packages\requests\adapters.py", line 44
9, in send
    timeout=timeout
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", li
ne 600, in urlopen
    chunked=chunked)
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", li
ne 343, in _make_request
    self._validate_conn(conn)
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", li
ne 839, in _validate_conn
    conn.connect()
  File "c:\python37\lib\site-packages\urllib3\connection.py", line 3
44, in connect
    ssl_context=context)
  File "c:\python37\lib\site-packages\urllib3\util\ssl_.py", line 34
5, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname
)
  File "c:\python37\lib\site-packages\eventlet\green\ssl.py", line 4
38, in wrap_socket
    return GreenSSLSocket(sock, *a, _context=self, **kw)
  File "c:\python37\lib\site-packages\eventlet\green\ssl.py", line 7
6, in __new__
    *args, **kw
TypeError: wrap_socket() got an unexpected keyword argument '_contex
t'

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)

**Comment by zyyoo** [comment]
I found a way:
in django project.settings
Add the following code
##################
import os
os.environ.setdefault('FORKED_BY_MULTIPROCESSING', '1')
###################
This error will not occur.

**Comment by njho** [comment]
Any thoughts on why this happens in celery? Having the same issue trying to use Firebase inside of a Flask/Celery project

**Comment by rygelouv** [comment]
@njho maybe you should try adding pyOpenSSL in your dependencies. Check this thread. https://github.com/eventlet/eventlet/issues/526
Hope it helps
