### ISSUE TITLE
Sending Flask Request's file object through celery and getting maximum recursion depth Runtime Error

### ISSUE THREAD

**Issue by achavhantexada** [celery/celery#5650]
# Checklist

- [X] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [X] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:software -> celery:4.3.0 (rhubarb) kombu:4.6.3 py:3.6.5
            billiard:3.6.0.0 py-amqp:2.5.0
platform -> system:Linux arch:64bit
            kernel version:4.15.0-54-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:rpc:///

accept_content: ['pickle']
broker_url: 'amqp://amitc005:********@localhost:5672/rest'
include: ['srm_rest_email.email.views']
result_backend: 'rpc:///'
result_expires: 3000
result_extended: True
task_default_queue: 'email'
task_serializer: 'pickle'
task_track_started: True</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Problem Description

When I was passing files immutiable dict object by calling a .delay() method, celery is throwing exception, 

```
[2019-07-19 10:58:48,420: CRITICAL/MainProcess] Can't decode message body: DecodeError(RecursionError('maximum recursion depth exceeded while calling a Python object',),) [type:'application/x-python-serialize' encoding:'binary' headers:{'lang': 'py', 'task': 'srm_rest_email.email.views.send_async_email', 'id': 'a6891a6e-e428-460b-bb98-940df5f430b2', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'a6891a6e-e428-460b-bb98-940df5f430b2', 'parent_id': None, 'argsrepr': "({'file': <FileStorage: '2019-05-07.png' ('image/png')>}, {'exp': 1563589252, 'iat': 1563546052, 'sub': 'HTTPie/0.9.9', 'jti': '06df3341-c1cc-49ce-a7a8-d4a4983469ad', 'client_id': 'test_client', 'company_id': 1, 'operator_id': 'SC'})", 'kwargsrepr': '{}', 'origin': 'gen4932@achavhan-ThinkPad-X1-Carbon-6th'}]

body: b'\x80\x02cwerkzeug.datastructures\nImmutableMultiDict\nq\x00]q\x01X\x04\x00\x00\x00fileq\x02cwerkzeug.datastructures\nFileStorage\nq\x03)\x81q\x04c_codecs\nencode\nq\x05XH\x9f\x00\x00\xc2\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03h\x00\x00\x01\x05\x08\x02\x00\x00\x00\x19\xc2\x81S\xc3\x87\x00\x00\x00\x03sBIT\x08\x08\x08\xc3\x9b\xc3\xa1O\xc3\xa0\x00\x00\x00_zTXtRaw profile type APP1\x00\x00\x08\xc2\x99\xc3\xa3JO\xc3\x8dK-\xc3\x8aLV((\xc3\x8aO\xc3\x8b\xc3\x8cI\xc3\xa5R\x00\x03c\x13.\x13K\x13K\xc2\xa3D\x03\x03\x03\x0b\x03\x0804006\x04\xc2\x92F@\xc2\xb69T(\xc3\x91\x00\x05\xc2\x98\xc2\x98\xc2\x9b\xc2\xa5\x01\xc2\xa1\xc2\xb9Y\xc2\xb2\xc2\x99)\xc2\x88\xc3\x8f\x05\x00O\xc2\xba\x15h\x1b-\xc3\x98\xc2\x8c\x00\x00... (41213b)
Traceback (most recent call last):
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 337, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 59, in pickle_loads
    return load(BytesIO(s))
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2821, in __getattr__
    return getattr(self.stream, name)
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2821, in __getattr__
    return getattr(self.stream, name)
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2821, in __getattr__
    return getattr(self.stream, name)
  [Previous line repeated 314 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 568, in on_task_received
    callbacks,
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/celery/worker/strategy.py", line 137, in task_message_handler
    if body is None and 'args' not in message.payload:
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/message.py", line 208, in payload
    return self._decoded_cache if self._decoded_cache else self.decode()
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/message.py", line 193, in decode
    self._decoded_cache = self._decode()
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/message.py", line 198, in _decode
    self.content_encoding, accept=self.accept)
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 337, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/kombu/serialization.py", line 59, in pickle_loads
    return load(BytesIO(s))
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2821, in __getattr__
    return getattr(self.stream, name)
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2821, in __getattr__
    return getattr(self.stream, name)
  File "/home/achavhan/srm_rest_email/env/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2821, in __getattr__
    return getattr(self.stream, name)
  [Previous line repeated 314 more times]
kombu.exceptions.DecodeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by auvipy** [comment]
is it your code or flask or celery issue?  could you provide a test case to reproduce?
