### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by wsf1990** [celery/celery#5655]
Hello,
I'm using celery 4.3.0,And use it to generate a image which maybe 10M+,Then I got an error like below:
```
Pool callback raised exception: MemoryError('Process got: ')
Traceback (most recent call last):
  File "*/lib/python3.7/site-packages/billiard/pool.py", line 1750, in safe_apply_callback
    fun(*args, **kwargs)
  File "*/lib/python3.7/site-packages/celery/worker/request.py", line 564, in on_success
    return self.on_failure(retval, return_ok=True)
  File "*/lib/python3.7/site-packages/celery/worker/request.py", line 351, in on_failure
    raise MemoryError('Process got: %s' % (exc_info.exception,))
```
My server has more than 20G memory.And I had test some small images which work well.Do I need set some config to prevent this?

**Comment by auvipy** [comment]
please follow the proper guideline to open an issue. could you post your problem to the mailing list or irc?

**Comment by wsf1990** [comment]
Sure,Thanks!
