### ISSUE TITLE
'Rdb' object has no attribute 'ident'

### ISSUE THREAD

**Issue by lovezeropython** [celery/celery#5667]
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/django4celery/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/anaconda3/envs/django4celery/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/root/spider_projects/django4celery/taskproj/app01/utils/tasks.py", line 354, in down_single_json
    rdb.set_trace()
  File "/root/anaconda3/envs/django4celery/lib/python3.7/site-packages/celery/contrib/rdb.py", line 193, in set_trace
    return debugger().set_trace(frame)
  File "/root/anaconda3/envs/django4celery/lib/python3.7/site-packages/celery/contrib/rdb.py", line 185, in debugger
    rdb = _current[0] = Rdb()
  File "/root/anaconda3/envs/django4celery/lib/python3.7/site-packages/celery/contrib/rdb.py", line 104, in __init__
    host, port, port_search_limit, port_skew,
  File "/root/anaconda3/envs/django4celery/lib/python3.7/site-packages/celery/contrib/rdb.py", line 141, in get_avail_port
    raise Exception(NO_AVAILABLE_PORT.format(self=self))
AttributeError: 'Rdb' object has no attribute 'ident'
```

**Comment by thedrow** [comment]
@auvipy Is this closed because it skipped the template?

**Comment by auvipy** [comment]
yes you are right

**Comment by thedrow** [comment]
@auvipy Please leave a comment next time and mark the issue as invalid.

**Comment by thedrow** [comment]
@lovezeropython Please open a new issue with all the details we required.

**Comment by auvipy** [comment]
noted. i will
