### ISSUE TITLE
Killing Celery Worker and Redis from Python Script

### ISSUE THREAD

**Issue by RudyVenguswamy** [celery/celery#5675]
Hi, I'm having an issue with shutting down my celery and redis instance from within a python script. I'm running v4.3.0 with the following code in Python:

       print("Starting setup ...")
        # ==== START REDIS SERVER ==== #
        cmd = "nohup redis-server&"
        returned_value = subprocess.call(cmd, shell=True)
        print("\nRedis server started with status =", returned_value)

        cmd = "celery worker -A parallelised_pandas_apply -E -n abc -l INFO&"
        returned_value = subprocess.call(cmd, shell=True)
        print("Celery worker threads started with status =", returned_value)

Later, after the process is done, I call:
        cmd = "pkill -f CeleryStalk"
        returned_value = subprocess.call(cmd, shell=True)
        print("Celery workers shutdown with status =", returned_value)
        
        cmd = "pkill -f redis-server"
        returned_value = subprocess.call(cmd, shell=True)
        print("\nRedis Server shutdown with status =", returned_value)

This causes the following error. What command should I call to kill my redis server and celery workers without resulting in the error? 

[2019-08-13 07:22:56,065: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 185, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/kombu/transport/redis.py", line 1052, in on_readable
    self.cycle.on_readable(fileno)
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/kombu/transport/redis.py", line 348, in on_readable
    chan.handlers[type]()
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/kombu/transport/redis.py", line 679, in _receive
    ret.append(self._receive_one(c))
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/kombu/transport/redis.py", line 690, in _receive_one
    response = c.parse_response()
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/redis/client.py", line 3036, in parse_response
    return self._execute(connection, connection.read_response)
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/Users/rudyvenguswamy/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 199, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

**Comment by georgepsarakis** [comment]
`pkill` sends a SIGTERM signal to Celery workers, which if are still processing tasks, will wait for them to finish. You can see how the worker processes signals in the [documentation](https://docs.celeryproject.org/en/latest/userguide/workers.html?highlight=warm%20shutdown#process-signals).

Github issues are used for bug reports, so please ask this type of questions to the [mailing list](https://docs.celeryproject.org/en/latest/getting-started/resources.html?highlight=mailing%20list#getting-help).
