### ISSUE TITLE
Weird death / worker not restarting

### ISSUE THREAD

**Issue by brianwawok** [celery/celery#5690]
Hi,

Two different weird issues started happening. The first one is:

I have workers dying with this stacktrace
```

[2019-08-22 21:03:58,650: ERROR/MainProcess] Process 'ForkPoolWorker-89' pid:101 exited with 'signal 9 (SIGKILL)'
ERROR 2019-08-22 21:03:58,666 [celery.worker.request] <140652482161544> Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).')
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/venv/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/venv/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/venv/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/venv/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/venv/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/venv/lib/python3.7/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/venv/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/venv/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 298, in on_result_readable
    next(it)
  File "/venv/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 279, in _recv_message
    message = load(bufv)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 46-47: invalid continuation byte


```

Second weird thing:

These workers never get restarted. So one by one my workers die, until it is just the "master" left on the node. A PS gives me something like
```

PID   USER     TIME  COMMAND
    1 root      3:53 {celery} /venv/bin/python3.7 /venv/bin/celery -A app_name worker -l INFO -n worker-%n-standard -c 20 -Q slow --without-heartbeat --without-mingle --without-gossip
   86 root      0:40 [celery]
   87 root      0:28 [celery]
   88 root      0:37 [celery]
   89 root      0:34 [celery]
   90 root      0:38 [celery]
   91 root      0:37 [celery]
   92 root      0:26 [celery]
   93 root      0:12 [celery]
   94 root      0:09 [celery]
   98 root      0:06 [celery]
   99 root      0:05 [celery]
  100 root      0:06 [celery]
  102 root      0:04 [celery]
  103 root      0:02 [celery]
  104 root      0:02 [celery]
  105 root      0:01 [celery]
  106 root      0:01 [celery]
  107 root      0:01 [celery]
  108 root      0:00 [celery]
  109 root      0:00 sh

```

As you can see, the 0 process is the master. The rest are just zombies doing nothing.

A weird byte seems like it should not kill a worker, and killing a worker should not make a zombie. Unsure what to tackle first?

Setup:

celery==4.3.0
billiard==3.6.1.0
kombu==4.5.0

RabbitMQ
Prefork

Running in docker on `python:3.7.3-alpine3.8`

**Comment by auvipy** [comment]
you shouldn't use multiprocessing at all

**Comment by auvipy** [comment]
could you give celery 4.4.orc3 a try? for Unicode error, could you check this https://stackoverflow.com/questions/19699367/unicodedecodeerror-utf-8-codec-cant-decode-byte?

**Comment by brianwawok** [comment]
@auvipy  i THINK unicode error is a False error, it happens after the OOM killer has sent a kill -9 to the process. So I think not worth looking at.  But A and B bugs from above maybe???

**Comment by auvipy** [comment]
will need a verifiable testcase for checking this further
