### ISSUE TITLE
Celery not reading CELERY_RESULT_BACKEND and CELERY_BROKER_URL Django

### ISSUE THREAD

**Issue by lucasmellos** [celery/celery#5710]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [X] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [X] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [X] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [X] I have tried reproducing the issue on more than one workers pool.
- [X] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [X] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.3.0 and 4.4.0rc3

<details>
<summary><b><code>celery report</code> Output: </b>
</summary>
<p>

```
/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 309, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 393, in handle_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 371, in run
    self.out(self.app.bugreport())
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 413, in out
    print(s, file=fh or self.stdout)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe5' in position 6271: ordinal not in range(128)
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.6.7
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.5.1
asn1crypto==0.24.0
billiard==3.6.1.0
celery==4.4.0rc3
certifi==2019.6.16
chardet==3.0.4
cryptography==2.1.4
Django==2.1.12
django-celery-beat==1.5.0
django-celery-results==1.1.2
django-pyodbc-azure==2.1.0.0
django-redis==4.8.0
django-rest-auth==0.9.5
django-timezone-field==3.0
djangorestframework==3.9.4
environs==4.2.0
flower==1.0.0
humanize==0.5.1
idna==2.6
importlib-metadata==0.20
keyring==10.6.0
keyrings.alt==3.0
kombu==4.6.4
marshmallow==3.0.1
more-itertools==7.2.0
psycopg2==2.7.5
pycrypto==2.6.1
pygobject==3.26.1
pyodbc==4.0.23
python-crontab==2.3.8
python-dateutil==2.8.0
python-dotenv==0.10.3
pytz==2019.2
pyxdg==0.25
redis==3.3.0
requests==2.22.0
SecretStorage==2.3.1
six==1.11.0
sqlparse==0.3.0
tornado==6.0.3
urllib3==1.25.3
vine==1.3.0
zipp==0.6.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
The settings.py: 

```
CELERY_BROKER_URL = 'amqp://crunchy:waffles@192.168.0.38//'

CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

# celery setting.
CELERY_CACHE_BACKEND = 'default'

# django setting.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}

CELERY_BEAT_SCHEDULE = {
    'mountPackages': { 
        'task': 'sge.tasks.mountPackages',
        'schedule': crontab(),#crontab(minute='0', hour='7-22/1',day_of_week='mon-sat'),  # execute every hour on day weeks from 7AM to 22PM
        'options': {'queue': 'sender'}
    },
    'notProcessedPackages': { 
        'task': 'sge.tasks.notProcessedPackages',
        'schedule': crontab(),#crontab(minute='30', hour='7-22/3' ,day_of_week='mon-sat'), # execute every three hours on day weeks from 7AM to 10PM
        'options': {'queue': 'unused'}
    },
    'getNotas': { 
        'task': 'sge.tasks.getNotas',
        'schedule': crontab(minute='50', hour='19' ,day_of_week='mon-sat'),  # execute every 8PM from monday to saturdar
        'options': {'queue': 'grades'}
    }
}
```

celery.py
```
from __future__ import absolute_import
import os
from celery import Celery
from django.conf import settings


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'iis.settings')

app = Celery('iis',)
app.config_from_object('django.conf:settings', namespace='CELERY',)
app.autodiscover_tasks()
```

</p>
</details>

# Expected Behavior

The URLs on celery should be replaced by the parameters defined in the settings.py 

# Actual Behavior

The result URL and transport URL in the config aren't update to the URLs placed in the Django settings.py.
shell>> celery -A iis worker -Q unused -l info
 -------------- celery@celery-worker-unused-6bb747fcc5-ql4w5 v4.4.0rc3 (cliffs)
---- **** ----- 
--- * ***  * -- Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-Ubuntu-18.04-bionic 2019-09-02 15:07:10
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         iis:0x7fc6a4802f98
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> unused           exchange=unused(direct) key=unused
                

[tasks]
  . sge.tasks.getNotas
  . sge.tasks.mountPackages
  . sge.tasks.notNeededPackage
  . sge.tasks.notProcessedPackages
  . sge.tasks.requestNotasAlunos
  . sge.tasks.sendPackages

[2019-09-02 15:07:11,202: INFO/MainProcess] Connected to redis://redis:6379//
[2019-09-02 15:07:11,215: INFO/MainProcess] mingle: searching for neighbors
^C

**Comment by sp1rs** [comment]
@lucasmellos  Where & when are you loading `celery` app?

**Comment by lucasmellos** [comment]
@sp1rs  Kubernetes cluster v1.15 Running on Ubuntu LTS latest

**Comment by sp1rs** [comment]
Make sure you import your project setting and then initialize the celery app.

**Comment by lucasmellos** [comment]
I'm importing on my celery.py
```
from __future__ import absolute_import
import os
from celery import Celery
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'iis.settings')

app = Celery('iis',)
app.config_from_object('django.conf:settings', namespace='CELERY',)
app.autodiscover_tasks()
```

and on my _init_.py
```
from __future__ import absolute_import, unicode_literals

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app

__all__ = ('celery_app',)
```

**Comment by sp1rs** [comment]
Is `settings` your package or file? Paste the setting code.

**Comment by lucasmellos** [comment]
File.

"""
Django settings for iis project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from celery.schedules import crontab
# from celery import Queue 
from environs import Env

env = Env()
# Read .env into os.environ
env.read_env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0skvy-gk+_z(x1t)3o3%bnf+&@1+clxtn9rxttxb7xh5$avp87'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'rest_framework_docs', # used for document purpouses 
    'rest_framework',  # DRF core
    'sge', # sge app
    'django_celery_results',
    'django_celery_beat',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# Database has been optmized to use on Kubernetes with the following enviroment variables:
# **DATABASE_ENGINE**: Select the database engine. The default value is 'sql_server.pyodbc'
# **DATABASE_NAME**: Defines the database name. The default value is 'iis'
# **DATABASE_HOST**: Define the target database host. The default value is 'db-service'
# **DATABASE_USER**: Define the specific database user for this schema. The default value is 'sa'
# **DATABASE_PASSWORD**: Define the database user password. The default value is 'default'

DATABASES = {
    'default': {
        'ENGINE': "{engine}".format(
    engine=os.getenv('DATABASE_ENGINE', 'sql_server.pyodbc')),
        'NAME': "{name}".format(
    name=os.getenv('DATABASE_NAME', 'iis')),
        'HOST': "{host}".format(
    host=os.getenv('DATABASE_HOST', 'db-service')),
        'USER': "{user}".format(
    user=os.getenv('DATABASE_USER', 'sa')),
        'PASSWORD': "{password}".format(
    password=os.getenv('DATABASE_PASSWORD', 'default')),

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/
# The TIME_ZONE parameter has been optimized for Kubernetes. The default value is 'America/Sao_Paulo'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'America/Sao_Paulo')

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Append slash
APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = '/static/'

RABBIT_URL = os.getenv('RABBIT_HOST', 'rabbit-service')
CELERY_BROKER_URL = 'amqp://guest:guest@{RABBIT_URL}:5672/iis'


# **CELERY_RESULT_BACKEND** Back-end used to store the information
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

# celery setting.
CELERY_CACHE_BACKEND = 'default'

# django setting.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}


CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULE = {
    'mountPackages': { 
        'task': 'sge.tasks.mountPackages',
        'schedule': crontab(),#crontab(minute='0', hour='7-22/1',day_of_week='mon-sat'),  # execute every hour on day weeks from 7AM to 22PM
        'options': {'queue': 'sender'}
    },
    'notProcessedPackages': { 
        'task': 'sge.tasks.notProcessedPackages',
        'schedule': crontab(),#crontab(minute='30', hour='7-22/3' ,day_of_week='mon-sat'), # execute every three hours on day weeks from 7AM to 10PM
        'options': {'queue': 'unused'}
    },
    'getNotas': { 
        'task': 'sge.tasks.getNotas',
        'schedule': crontab(minute='50', hour='19' ,day_of_week='mon-sat'),  # execute every 8PM from monday to saturdar
        'options': {'queue': 'grades'}
    }
}


CELERY_TASK_ROUTES = {
    'sge.tasks.mountPackages': {
        'queue': 'sender',
        'routing_key': 'sender_tasks',
    },
   'sge.tasks.notProcessedPackage': {
        'queue': 'unused',
        'routing_key': 'unused_taks'
    },
   'sge.tasks.getNotas': {
        'queue': 'grades',
        'routing_key': 'grades_taks'
   }
}

**Comment by sp1rs** [comment]
The issue is celery app is initializing before django setting is loaded.

Put
```
from  __future__ import absolute_import, unicode_literals

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app

__all__ = ('celery_app',)
```
in apps.py created on startproject command.

**Comment by lucasmellos** [comment]
I'm sorry, but it doesn't seem to be my problem. I'm still getting the same error.

<code>startproject/apps.py</code>
```
from  __future__ import absolute_import, unicode_literals
from .celery import app as celery_app
__all__ = ('celery_app',)
```

<code>startproject/__init__.py</code>
```
from __future__ import absolute_import, unicode_literals
from .celery import app as celery_app
__all__ = ('celery_app',)
```

<code>startproject/celery.py</code>
```
from __future__ import absolute_import, unicode_literals
import os
from celery import Celery

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'iis.settings')

app = Celery('iis')

app.config_from_object('django.conf:settings')

app.autodiscover_tasks()
@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```

<code>startproject/settings.py</code>
```
import os
from celery.schedules import crontab
# from celery import Queue 
from environs import Env

env = Env()
# Read .env into os.environ
env.read_env()

RABBIT_URL = os.getenv('RABBIT_HOST', 'rabbit-service')
CELERY_BROKER_URL = 'amqp://guest:guest@{RABBIT_URL}:5672/iis'

CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

# celery setting.
CELERY_CACHE_BACKEND = 'default'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0skvy-gk+_z(x1t)3o3%bnf+&@1+clxtn9rxttxb7xh5$avp87'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # DRF core
    'sge', # sge app
    'django_celery_results',
    'django_celery_beat',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iis.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': "{engine}".format(
    engine=os.getenv('DATABASE_ENGINE', 'sql_server.pyodbc')),
        'NAME': "{name}".format(
    name=os.getenv('DATABASE_NAME', 'iis')),
        'HOST': "{host}".format(
    host=os.getenv('DATABASE_HOST', 'db-service')),
        'USER': "{user}".format(
    user=os.getenv('DATABASE_USER', 'sa')),
        'PASSWORD': "{password}".format(
    password=os.getenv('DATABASE_PASSWORD', 'default')),

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'America/Sao_Paulo')

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Append slash
APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = '/static/'

# django setting.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}

CELERY_BEAT_SCHEDULE = {
    'mountPackages': { 
        'task': 'sge.tasks.mountPackages',
        'schedule': crontab(),#crontab(minute='0', hour='7-22/1',day_of_week='mon-sat'),  # execute every hour on day weeks from 7AM to 22PM
        'options': {'queue': 'sender'}
    },
    'notProcessedPackages': { 
        'task': 'sge.tasks.notProcessedPackages',
        'schedule': crontab(),#crontab(minute='30', hour='7-22/3' ,day_of_week='mon-sat'), # execute every three hours on day weeks from 7AM to 10PM
        'options': {'queue': 'unused'}
    },
    'getNotas': { 
        'task': 'sge.tasks.getNotas',
        'schedule': crontab(minute='50', hour='19' ,day_of_week='mon-sat'),  # execute every 8PM from monday to saturdar
        'options': {'queue': 'grades'}
    }
}


CELERY_TASK_ROUTES = {
    'sge.tasks.mountPackages': {
        'queue': 'sender',
        'routing_key': 'sender_tasks',
    },
   'sge.tasks.notProcessedPackage': {
        'queue': 'unused',
        'routing_key': 'unused_taks'
    },
   'sge.tasks.getNotas': {
        'queue': 'grades',
        'routing_key': 'grades_taks'
   }
}
```

<code>app/apps.py</code>
```
from django.apps import AppConfig

class SgeConfig(AppConfig):
    name = 'sge'
```

<code>apps/tasks.py</code>
```
from __future__ import absolute_import, unicode_literals
import os
import json
import requests
from environs import Env
from django.core.serializers import serialize
from celery import shared_task, Task, group
from .requests import getNotasAlunos
from .models import *
from .serializer import PacotesSerializer
from .retrieve_packages import *
from .filter import *
from .requests import getNotasAlunos

@shared_task(serializer="json")
def requestNotasAlunos(*args):
    notasAlunos = getNotasAlunos(object)
    # msg = str(len(notasAlunos)) + ' idPacote: ' + notasAlunos[0]['idPacote']
    return notasAlunos


@shared_task(name="sge.tasks.notProcessedPackages", queue='unused')
def notProcessedPackages():
    queryset = Pacotes.objects.filter(statusProc=0)
    serializer = PacotesSerializer(queryset, many=True)
    ids = []

    for package in serializer.data:
        if package["tipo"] in (2, 4, 7, 8, 9, 10, 13):
            ids.append(notNeededPackage.s(package["idPacote"], package["tipo"]))

    job = group(ids)
    result = job.apply_async()

    while result.ready != True:
        if result.successful():
            return result.completed_count()
        elif result.failed():
            return result.successful()


@shared_task(name="sge.tasks.notNeededPackage", queue='unused')
def notNeededPackage(idPacote, typePackage):
    try:
        Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
        return {"idPacote": idPacote, "type": typePackage}
    except Exception as e:
        return str(e)


@shared_task(name="sge.tasks.mountPackages", queue='sender')
def mountPackages():
    queryset = Pacotes.objects.filter(statusProc=0)
    serializer = PacotesSerializer(queryset, many=True)
    packagesSend = []
    idsNotNeeded = []  # packages that are not necessary

    for package in serializer.data:
        if package["tipo"] == 1:
            # TODO: FIX
            cursoMatriz = packageCursoMatriz(package["idPacote"], None)
            upperCursoMatriz, destiny = filterCursoMatriz(cursoMatriz, None)

            if upperCursoMatriz is not None:
                idsNotNeeded.append(notNeededPackage.s(package["idPacote"], 1))
            else:
                packagesSend.append(
                    sendPackages.s(cursoMatriz, 1, destiny, package["idPacote"])
                )

        elif package["tipo"] == 3:
            # TODO: FIX
            turmasDisciplinas = packageTurmaDisciplina(package["idPacote"], None, None)

            destiny, upperTurmasDisciplinas = filterTurmasDisciplinas(turmasDisciplinas)

            if upperTurmasDisciplinas is not None or destiny is None:
                idsNotNeeded.append(notNeededPackage.s(package["idPacote"], 3))
            else:
                packagesSend.append(
                    sendPackages.s(turmasDisciplinas, 3, destiny, package["idPacote"])
                )

        elif package["tipo"] == 5:
            alunos = packageAlunos(package["idPacote"], None)

            upperAluno, destiny = filterAlunos(alunos)

            # TODO fix filtering
            if upperAluno is not None:
                idsNotNeeded.append(notNeededPackage.s(package["idPacote"], 5))
            else:
                if len(list(destiny)) > 1:
                    packagesSend.append(
                        sendPackages.s(alunos, 5, "P", package["idPacote"])
                    )
                    packagesSend.append(
                        sendPackages.s(alunos, 5, "D", package["idPacote"])
                    )
                else:
                    packagesSend.append(
                        sendPackages.s(alunos, 5, destiny, package["idPacote"])
                    )

        elif package["tipo"] == 6:
            # TODO: FIX
            matricula = packageMatriculas(package["idPacote"])

            destiny, upperMatricula = filterMatricula(matricula)
            
            if upperMatricula is not None:
                idsNotNeeded.append(notNeededPackage.s(package["idPacote"], 6))
            else:
                if len(list(destiny)) > 1:
                    packagesSend.append(
                        sendPackages.s(matricula, 6, "P", package["idPacote"])
                    )
                    packagesSend.append(
                        sendPackages.s(matricula, 6, "D", package["idPacote"])
                    )
                else:
                    packagesSend.append(
                        sendPackages.s(matricula, 6, destiny, package["idPacote"])
                    )

        elif package["tipo"] == 12:
            # TODO: FIX
            professor = packageProfessores(package["idPacote"], None)

            pProfessor, dProfessor = filterProfessor(professor)

            if pProfessor is not None:
                packagesSend.append(
                    sendPackages.s(pProfessor, 12, "P", package["idPacote"])
                )
            if dProfessor is not None:
                packagesSend.append(
                    sendPackages.s(dProfessor, 12, "D", package["idPacote"])
                )
            if pProfessor is None and dProfessor is None:
                idsNotNeeded.append(notNeededPackage.s(package["idPacote"], 12))

    if len(list(idsNotNeeded)) > 0:
        job = group(idsNotNeeded)
        result = job.apply_async()

    if len(list(packagesSend)) > 0:
        job = group(packagesSend)
        result = job.apply_async()
    else:
        return packagesSend

    while result.ready != True:
        if result.successful():
            return result.completed_count()
        elif result.failed():
            return result.successful()


@shared_task(name="sge.tasks.sendPackages", queue='sender')
def sendPackages(payload, packageType, destiny, idPacote):

    headers = {"Content-type": "application/json", "encoding": "utf-8"}
    authentication = (
        "{username}".format(
    username=os.getenv('DESTINY_USERNAME', 'username')),
        "{password}".format(
    password=os.getenv('DESTINY_PASSWORD', 'password')),
    )

    URL_EAD = "{url_ead}".format(
        url_ead=os.getenv('URL_EAD','https://localhost/desenv/sge')
    )

    URL_UNIDADES = "{url_unidades}".format(
        url_unidades=os.getenv('URL_UNIDADES', 'https://localhost/unidades/sge')
    )

    if packageType == 1:
        if destiny == "D":
            r = requests.post(
                URL_EAD + "/cursoMatriz",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text             
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text
        else:
            r = requests.post(
                URL_UNIDADES + "/cursoMatriz",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text

    if packageType == 3:
        if destiny == "D":
            r = requests.post(
                URL_EAD + "/turmaDisciplina",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text
        else:
            r = requests.post(
                URL_UNIDADES + "/turmaDisciplina",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text
            


    if packageType == 5:
        if destiny == "D":
            r = requests.post(
                URL_EAD + "/alunos",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text
        else:
            r = requests.post(
                URL_UNIDADES + "/alunos",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text

    elif packageType == 6:
        if destiny == "D":
            r = requests.post(
                URL_EAD + "/matriculas",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text
        else:
            r = requests.post(
                URL_UNIDADES + "/matriculas",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text

    elif packageType == 12:
        if destiny == "D":
            r = requests.post(
                URL_EAD + "/professores",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text
        else:
            r = requests.post(
                URL_UNIDADES + "/professores",
                auth=(authentication),
                headers=headers,
                data=json.dumps(payload),
                verify=False,
            )
            if r.status_code == 201:
                Pacotes.objects.filter(idPacote=idPacote).update(statusProc=2)
                return r.text
            else:
                Pacotes.objects.filter(idPacote=idPacote).update(numProc=1)
                return r.text


@shared_task(name='sge.tasks.getNotas', queue='grades')
def getNotas():
    grades = getNotasAlunos(object)
    return grades

```
