### ISSUE TITLE
celery/backends/base.py:281;TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

### ISSUE THREAD

**Issue by YouZhengChuan** [celery/celery#5712]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

error when get task state or other attribute value.

```python
>>> taskid="d7b78dfa-5602-4a4e-bf4e-dff1c9a8e46e"
>>> task = TAA.AsyncResult(taskid)
>>>
>>> task.state
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 473, in state
    return self._get_task_meta()['status']
  File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 412, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 386, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 730, in _get_task_meta_for
    return self.decode_result(meta)
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 305, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 301, in meta_from_decoded
    meta['result'] = self.exception_to_python(meta['result'])
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 281, in exception_to_python
    exc = cls(*exc_msg if isinstance(exc_msg, tuple) else exc_msg)
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'
```

The content of the taskid task in redis:

```json
{
  "status": "FAILURE",
  "result": {
    "exc_type": "JSONDecodeError",
    "exc_message": [
      "Expecting ',' delimiter: line 1 column 528408 (char 528407)"
    ],
    "exc_module": "json.decoder"
  },
  "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/celery/app/trace.py\", line 385, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/celery/app/trace.py\", line 648, in __protected_call__\n    return self.run(*args, **kwargs)\n  File \"/Users/youzhengchuan/PycharmProjects/collector/pcdn/analysis/__init__.py\", line 14, in telegraf_abnormal_analysis\n    ret = taa.analysis(sts, ets, lot)\n  File \"/Users/youzhengchuan/PycharmProjects/collector/pcdn/analysis/telegraf_abnormal_analysis.py\", line 42, in analysis\n    online = self._query.groupby(**params)\n  File \"/Users/youzhengchuan/PycharmProjects/collector/pcdn/analysis/query.py\", line 35, in groupby\n    ret = self._query.groupby(**params)\n  File \"/usr/local/lib/python3.7/site-packages/pydruid/client.py\", line 306, in groupby\n    return self._post(query)\n  File \"/usr/local/lib/python3.7/site-packages/pydruid/client.py\", line 571, in _post\n    query.parse(data)\n  File \"/usr/local/lib/python3.7/site-packages/pydruid/query.py\", line 53, in parse\n    res = json.loads(self.result_json)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py\", line 348, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 528408 (char 528407)\n",
  "children": [],
  "task_id": "d7b78dfa-5602-4a4e-bf4e-dff1c9a8e46e",
  "date_done": "2019-09-04T08:11:17.388695"
}
```

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

**Comment by thecrackofdawn** [comment]
I met this issue too. To avoid this I use pickle as the serializer.

**Comment by auvipy** [comment]
Does the issue still persist in master?

**Comment by robin-blanchard** [comment]
I met this exact issue with celery 4.3.0. The error in task also was a `JSONDecodeError`.

**Comment by benedikt-bartscher** [comment]
i just got the same issue with the latest version of celery:
`TypeError: JSONDecodeError.__init__() missing 2 required positional arguments: 'doc' and 'pos'`

**Comment by Tirzono** [comment]
I get the same error:

```
[2022-11-09 10:41:07,769: CRITICAL/MainProcess] Unrecoverable error: TypeError("JSONDecodeError.__init__() missing 2 required positional arguments: 'doc' and 'pos'")
Traceback (most recent call last):
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
    next(it)
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 306, in _recv_message
    message = load(bufv)
  File "/workspace/XXX/.venv/lib/python3.10/site-packages/requests/exceptions.py", line 41, in __init__
    CompatJSONDecodeError.__init__(self, *args)
TypeError: JSONDecodeError.__init__() missing 2 required positional arguments: 'doc' and 'pos'
```

Running `celery` 5.2.7and `requests` 2.28.1.

I managed to reproduce the issue. The following would cause the issue above:

```
import requests
from celery import shared_task
from requests.exceptions import InvalidJSONError

@shared_task(autoretry_for=(InvalidJSONError,), default_retry_delay=60, ignore_result=True)
def test_task():
    requests.get('https://www.whaleportal.com').json()
```

The following won't throw the error above (but obviously will fail the task, but won't crash the worker at least):

```
import requests
from celery import shared_task

@shared_task(ignore_result=True)
def test_task():
    requests.get('https://www.whaleportal.com').json()
```

Note that doing this `InvalidJSONError` inherits `RequestException`:

```
import requests
from celery import shared_task
from requests.exceptions import RequestException

@shared_task(autoretry_for=(RequestException,), default_retry_delay=60, ignore_result=True)
def test_task():
    requests.get('https://www.whaleportal.com').json()
```

Will also crash the worker. The following won't crash the worker though (`ConnectionError` inherits `RequestException`):

```
import requests
from celery import shared_task
from requests.exceptions import RequestException, ConnectionError

@shared_task(autoretry_for=(RequestException,), default_retry_delay=60, ignore_result=True)
def test_task():
    raise ConnectionError('foo')
```

Please let me know if you need any more information to debug this issue. So far I haven't found a workaround, but will post one if I find one.

**Comment by Tirzono** [comment]
For anyone looking for a workaround for this issue: it's an issue related to using celery in combination with requests. I recently changed to httpx instead of requests (not because of this bug) and I noticed I have had no issues so far.

**Comment by benedikt-bartscher** [comment]
I think @Tirzono found the issue. It still persists on master, i have the same problem with `autoretry_for=(RequestException,)` killing celery workers. Please reopen

**Comment by DashKenny** [comment]
Also seeing this with Celery 5.2.7, requests 2.28.1.

**Comment by alternativshik** [comment]
Also seeing this with Celery 5.2.7, requests 2.28.1.

**Comment by gmassman** [comment]
Also seeing this with Celery 5.2.7, requests 2.28.1.

**Comment by Tirzono** [comment]
@auvipy, would you be able to open this issue again please?

**Comment by senbax** [comment]
Yes please, the issue still persists!

**Comment by Wats0ns** [comment]
Same here, can confirm this persists on master

**Comment by jeremyallencpa** [comment]
I am also still having this issue. It doesn't appear to happen when I am running my program locally but it does happen in production.

**Comment by auvipy** [comment]
can any one contribute a failing test to the CI?

**Comment by gmassman** [comment]
FWIW I spent some time yesterday swapping out celery for dramatiq in one of my flask apps where this error occurs frequently. Lo and behold, a real stacktrace appeared (here's the relevant snippet):
```
  File "/Users/garrett/bodyport/repos/bodyport_device/animal/tasks/subscriber_tasks.py", line 25, in _notify_subscribers
    logger.error(f"POST to subscriber ID {subscriber.id} failed: {res.json()}")
                                                                  ^^^^^^^^^^
  File "/Users/garrett/bodyport/repos/bodyport_device/.venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Two things of interest here:
1. Clearly the response was not valid JSON, which is why requests raises an error as one would expect.
2. Most alarmingly, Celery _hides the raised error's stack trace_ from the source exception. Instead, the worker simply crashes with a useless `TypeError: JSONDecodeError.__init__() missing 2 required positional arguments: 'doc' and 'pos'`.

I'm done with this package. I've made a case to my team to prioritize removing celery from our stack. I can't trust a tool that hides information from developers and makes simple issues impossible to debug.

**Comment by ported-pw** [comment]
Seems like this is somehow caused by the serializer logic thinking that the `JSONDecodeError` from within a task was internal somehow...
Yes, an error in a task can crash the Celery worker.

**Comment by auvipy** [comment]
> FWIW I spent some time yesterday swapping out celery for dramatiq in one of my flask apps where this error occurs frequently. Lo and behold, a real stacktrace appeared (here's the relevant snippet):
> 
> ```
>   File "/Users/garrett/bodyport/repos/bodyport_device/animal/tasks/subscriber_tasks.py", line 25, in _notify_subscribers
>     logger.error(f"POST to subscriber ID {subscriber.id} failed: {res.json()}")
>                                                                   ^^^^^^^^^^
>   File "/Users/garrett/bodyport/repos/bodyport_device/.venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> Two things of interest here:
> 
>     1. Clearly the response was not valid JSON, which is why requests raises an error as one would expect.
> 
>     2. Most alarmingly, Celery _hides the raised error's stack trace_ from the source exception. Instead, the worker simply crashes with a useless `TypeError: JSONDecodeError.__init__() missing 2 required positional arguments: 'doc' and 'pos'`.
> 
> 
> I'm done with this package. I've made a case to my team to prioritize removing celery from our stack. I can't trust a tool that hides information from developers and makes simple issues impossible to debug.

I can see this issue in other projects as well https://github.com/psf/requests/issues/6628. I guess you should stop trusting them too.
