### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by ra-coder** [celery/celery#5713]
Celery worker crashes with next trace 

```
2019-09-04 10:59:34,519: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1266602, 303031, '2KFVX25DYNZ6PJAV5JP4LBZWCY_63703028717210.mp3', '2019-09-02T16:46:50.061594+03:00', 84.715125s)>
[2019-09-04 10:59:34,529: CRITICAL/MainProcess] [celery.worker] Unrecoverable error: AssertionError('Cannot switch to MAINLOOP from MAINLOOP',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kombu/utils/eventio.py", line 283, in poll
    self._rfd, self._wfd, self._efd, timeout,
  File "/usr/local/lib/python3.6/dist-packages/eventlet/green/select.py", line 76, in select
    listeners.append(hub.add(hub.READ, k, on_read, current.throw, lambda: None))
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/epolls.py", line 24, in add
    self.register(fileno, new=not oldlisteners)
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/poll.py", line 40, in register
    self.poll.register(fileno, mask)
OSError: [Errno 9] Bad file descriptor
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python3.6/dist-packages/eventlet/green/select.py", line 57, in on_write
    current.switch(([], [original], []))
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/pidbox.py", line 120, in loop
    connection.drain_events(timeout=1.0)
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 315, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/virtual/base.py", line 963, in drain_events
    get(self._deliver, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/redis.py", line 367, in get
    events = self.poller.poll(timeout)
  File "/usr/local/lib/python3.6/dist-packages/kombu/utils/eventio.py", line 289, in poll
    return self._remove_bad()
  File "/usr/local/lib/python3.6/dist-packages/kombu/utils/eventio.py", line 262, in _remove_bad
    _selectf([fd], [], [], 0)
  File "/usr/local/lib/python3.6/dist-packages/eventlet/green/select.py", line 76, in select
    listeners.append(hub.add(hub.READ, k, on_read, current.throw, lambda: None))
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/epolls.py", line 22, in add
    listener = hub.BaseHub.add(self, evtype, fileno, cb, tb, mac)
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/hub.py", line 181, in add
    evtype, fileno, evtype, cb, bucket[fileno]))
RuntimeError: Second simultaneous read on fileno 8 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<function select.<locals>.on_read at 0x7f50d8df6598>; THAT THREAD=FdListener('read', 8, <function select.<locals>.on_read at 0x7f50cc849f28>, <built-in method throw of greenlet.greenlet object at 0x7f50cdd1a930>)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/loops.py", line 121, in synloop
    connection.drain_events(timeout=2.0)
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 315, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/virtual/base.py", line 963, in drain_events
    get(self._deliver, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/redis.py", line 367, in get
    events = self.poller.poll(timeout)
  File "/usr/local/lib/python3.6/dist-packages/kombu/utils/eventio.py", line 283, in poll
    self._rfd, self._wfd, self._efd, timeout,
  File "/usr/local/lib/python3.6/dist-packages/eventlet/green/select.py", line 80, in select
    return hub.switch()
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/hub.py", line 298, in switch
    return self.greenlet.switch()
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/hub.py", line 352, in run
    self.wait(0)
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/poll.py", line 115, in wait
    self.squelch_exception(fileno, sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/hub.py", line 301, in squelch_exception
    traceback.print_exception(*exc_info)
  File "/usr/lib/python3.6/traceback.py", line 105, in print_exception
    print(line, file=file, end="")
  File "/usr/local/lib/python3.6/dist-packages/celery/utils/log.py", line 235, in write
    self.logger.log(self.loglevel, safe_str(data))
  File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/integrations/logging.py", line 70, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 863, in handle
    self.acquire()
  File "/usr/lib/python3.6/logging/__init__.py", line 814, in acquire
    self.lock.acquire()
  File "/usr/lib/python3.6/threading.py", line 147, in acquire
    rc = self._block.acquire(blocking, timeout)
  File "/usr/local/lib/python3.6/dist-packages/eventlet/semaphore.py", line 115, in acquire
    hubs.get_hub().switch()
  File "/usr/local/lib/python3.6/dist-packages/eventlet/hubs/hub.py", line 284, in switch
    assert cur is not self.greenlet, 'Cannot switch to MAINLOOP from MAINLOOP'
AssertionError: Cannot switch to MAINLOOP from MAINLOOP
[2019-09-04 10:59:34,544: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1269888, 303031, '8QBR3J8SWN7FJ2HAS9QRTQKHB3_63703015160546.mp3', '2019-09-02T12:59:57.903236+03:00', 31.84325s)>
[2019-09-04 10:59:34,933: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[74e58ca9-c3cc-4f3f-b137-392ebf8f2870] succeeded in 5.735226388002047s: {}
[2019-09-04 10:59:34,993: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1267870, 303031, '7CQXU4WJ73GN72KWBFVQPDGRSU_63703097828483.mp3', '2019-09-03T12:07:06.927592+03:00', 575.216375s)>
[2019-09-04 10:59:35,224: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1270028, 303031, '9FMDVJGEXRDPH27UGBPMCAC6QC_63703016886817.mp3', '2019-09-02T13:31:51.042248+03:00', 214.831s)>
[2019-09-04 10:59:35,463: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1266868, 303031, '8B9VFC9DMRQMT266247ZKLBMJJ_63703031850954.mp3', '2019-09-02T17:38:22.781357+03:00', 48.561625s)>
[2019-09-04 10:59:35,665: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1269541, 303031, '6QM5MAS997V9P24F9M64QFYN76_63703010248328.mp3', '2019-09-02T11:38:58.097190+03:00', 84.349375s)>
[2019-09-04 10:59:35,684: INFO/MainProcess] [glue.fulltext] Put to Elastic <Call(1268768, 303031, '7V9MK62SDB2282F8B4SVSEQ49C_63703108676295.mp3', '2019-09-03T14:58:23.088030+03:00', 21.0025s)>: {'_index': 'speechanalytics-transcript-index', '_type': 'speechanalytics-transcript', '_id': '1268768', '_version': 1, 'result': 'created', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 4046, '_primary_term': 2}
[2019-09-04 10:59:35,688: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[145ff1ee-5369-49f1-ac7c-10991350d648] succeeded in 6.42055144799815s: {}
[2019-09-04 10:59:35,693: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1268524, 303031, '3AYUD2HMRFLAE22RQGEFDJGRHE_63703106532930.mp3', '2019-09-03T14:22:23.466223+03:00', 6.896375s)>
[2019-09-04 10:59:35,698: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1272299, 303031, '2Y9JUM7WEUUDQ276MFFKGRDT97_63703122232076.mp3', '2019-09-03T18:43:55.098832+03:00', 1.698s)>
[2019-09-04 10:59:35,912: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1267769, 303031, '362LQPQ98KUBX247CAPK7BP7PW_63703097029218.mp3', '2019-09-03T11:44:07.666197+03:00', 14.8375s)>
[2019-09-04 10:59:35,990: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1272343, 303031, '8WTNDY69ZGXA7JEB4LDGF3G7KY_63703122909726.mp3', '2019-09-03T18:55:16.107893+03:00', 2.533875s)>
[2019-09-04 10:59:36,011: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1272361, 303031, '4FUBPMVKLH27H2DASQHVLPV6H9_63703123136399.mp3', '2019-09-03T18:59:01.442279+03:00', 2.769s)>
[2019-09-04 10:59:36,011: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[e20d310a-bf49-4b16-8baf-ab91fdb4f057] succeeded in 6.960011729010148s: {}
[2019-09-04 10:59:36,254: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1268324, 303031, '46Z5A57VZ94P82ZYPRTGPK9TNJ_63703103784679.mp3', '2019-09-03T13:36:54.769181+03:00', 28.369s)>
[2019-09-04 10:59:36,495: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1267723, 303031, '495NS2MRHCTXP2KW4RBBE329ZA_63703096540338.mp3', '2019-09-03T11:36:07.237450+03:00', 24.555125s)>
[2019-09-04 10:59:36,540: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1268344, 303031, '3E4VMY22GBMSAJVEVDMLY8226W_63703104160192.mp3', '2019-09-03T13:43:20.768682+03:00', 37.747s)>
[2019-09-04 10:59:36,756: INFO/MainProcess] [glue.fulltext] Put to Elastic <Call(1270699, 303031, '2DS7NFHYN75GE2S7VW2RQKL959_63702928774240.mp3', '2019-09-01T12:59:43.796476+03:00', 6.269375s)>: {'_index': 'speechanalytics-transcript-index', '_type': 'speechanalytics-transcript', '_id': '1270699', '_version': 1, 'result': 'created', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 4165, '_primary_term': 2}
[2019-09-04 10:59:36,776: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1271628, 303031, '8T8THYBDL75Z32AJLM9HUS7Z8F_63703114527911.mp3', '2019-09-03T16:35:44.786694+03:00', 11.78125s)>
[2019-09-04 10:59:36,803: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1271860, 303031, '9RKEPHGQHQ7QK29X9RJK73KUS4_63703116267217.mp3', '2019-09-03T17:12:26.608637+03:00', 462.863625s)>
[2019-09-04 10:59:37,207: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1266718, 303031, '2V2Y62TB4UV4L2NKYRBQ3GWBBK_63703030016672.mp3', '2019-09-02T17:07:44.801904+03:00', 41.7175s)>
[2019-09-04 10:59:37,285: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[c300c550-c841-4995-b3cd-a42ff6d26a06] succeeded in 5.3194135509984335s: {}
[2019-09-04 10:59:37,319: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1271174, 303031, '4MF6HSFSNX2ZJ2KTPA9NLV5UB7_63702944408982.mp3', '2019-09-01T17:20:39.083042+03:00', 25.939625s)>
[2019-09-04 10:59:37,335: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1269395, 303031, '8B45V5WSSLJ2P2UXQGYMJYBX42_63703008409454.mp3', '2019-09-02T11:07:02.945167+03:00', 12.617125s)>
[2019-09-04 10:59:37,338: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1267007, 303031, '49Z7Y8YDA9CAU2Q2T435J6D7W2_63703034230567.mp3', '2019-09-02T18:18:16.639977+03:00', 60.499625s)>
[2019-09-04 10:59:37,339: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[69cc2d6f-10e3-45b0-a668-04665d408245] succeeded in 8.396969287001411s: {}
[2019-09-04 10:59:37,347: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[1b9f4f88-13de-4f3d-9878-c1da0538e77d] succeeded in 8.41690219200973s: {}
[2019-09-04 10:59:37,356: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[a2275ef0-707f-41f7-92c4-f3226867bd01] succeeded in 7.955177594005363s: {}
[2019-09-04 10:59:37,370: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1268768, 303031, '7V9MK62SDB2282F8B4SVSEQ49C_63703108676295.mp3', '2019-09-03T14:58:23.088030+03:00', 21.0025s)>
[2019-09-04 10:59:37,596: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1267858, 303031, '3YMPCC22UNYD3JH5ZJ57XCDVSJ_63703097992252.mp3', '2019-09-03T12:00:55.439755+03:00', 59.559125s)>
[2019-09-04 10:59:37,617: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1270699, 303031, '2DS7NFHYN75GE2S7VW2RQKL959_63702928774240.mp3', '2019-09-01T12:59:43.796476+03:00', 6.269375s)>
[2019-09-04 10:59:37,837: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1267369, 303031, '46MAUW79Z9Q26JQZ4CCKQ74X6R_63703089906540.mp3', '2019-09-03T09:46:02.685725+03:00', 52.349375s)>
[2019-09-04 10:59:38,070: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1270876, 303031, '3CHS4Z95QKL4LJUDEGDURTCF9R_63702934970918.mp3', '2019-09-01T14:43:25.623914+03:00', 30.432625s)>
[2019-09-04 10:59:38,237: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1268546, 303031, '6Q7LZSCWUCUG8JN75AW3VKM5UZ_63703106680486.mp3', '2019-09-03T14:25:55.848462+03:00', 71.862875s)>
[2019-09-04 10:59:38,409: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1269374, 303031, '9QG9D3H8D6ADF2LNDYSSBDT6FH_63703008179510.mp3', '2019-09-02T11:03:12.435594+03:00', 11.911875s)>
[2019-09-04 10:59:38,421: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[fa6600cc-d900-4a6a-a8e4-65f1183f6912] succeeded in 7.232695500002592s: {}
[2019-09-04 10:59:38,516: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1267696, 303031, '57ZGX7L3AKN8S2DAY5CDG9LT6C_63703096110388.mp3', '2019-09-03T11:28:46.107230+03:00', 10.161625s)>
[2019-09-04 10:59:38,522: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[eb51bc86-f3f3-4e61-8434-46f8b5da8b47] succeeded in 8.978083163005067s: {}
[2019-09-04 10:59:40,056: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1267401, 303031, '7GNR7QYH35ZPA2DUL42JYXC2TD_63703090932080.mp3', '2019-09-03T10:10:01.317584+03:00', 454.55675s)>
[2019-09-04 10:59:40,447: INFO/MainProcess] [glue.business.analyzer] Successfully analyzed <Call(1270354, 303031, '98TZ72C8STR7KJR5RML7PSE5PT_63703022051281.mp3', '2019-09-02T14:55:04.524778+03:00', 50.6775s)>
[2019-09-04 10:59:40,456: INFO/MainProcess] [celery.app.trace] Task glue.tasks.analyzer.start_analyzing_some_calls_for_account[66e1a954-44da-4d73-9bd2-3d685517c443] succeeded in 9.183803658001125s: {}
[2019-09-04 10:59:40,459: WARNING/MainProcess] [celery.redirected] Restoring 10 unacknowledged message(s)
[2019-09-04 10:59:40,469: WARNING/MainProcess] [celery.redirected] Error in atexit._run_exitfuncs:
[2019-09-04 10:59:40,469: WARNING/MainProcess] [celery.redirected] Traceback (most recent call last):
[2019-09-04 10:59:40,470: WARNING/MainProcess] [celery.redirected] File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/worker.py", line 81, in flush
[2019-09-04 10:59:40,470: WARNING/MainProcess] [celery.redirected] self._wait_flush(timeout, callback)
[2019-09-04 10:59:40,470: WARNING/MainProcess] [celery.redirected] File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/worker.py", line 87, in _wait_flush
[2019-09-04 10:59:40,470: WARNING/MainProcess] [celery.redirected] if not self._timed_queue_join(initial_timeout):
[2019-09-04 10:59:40,471: WARNING/MainProcess] [celery.redirected] File "/usr/local/lib/python3.6/dist-packages/sentry_sdk/worker.py", line 45, in _timed_queue_join
[2019-09-04 10:59:40,471: WARNING/MainProcess] [celery.redirected] queue.all_tasks_done.acquire()  # type: ignore
[2019-09-04 10:59:40,471: WARNING/MainProcess] [celery.redirected] AttributeError
[2019-09-04 10:59:40,471: WARNING/MainProcess] [celery.redirected] :
[2019-09-04 10:59:40,472: WARNING/MainProcess] [celery.redirected] 'Queue' object has no attribute 'all_tasks_done'
```

**Comment by auvipy** [comment]
could you try celery==4.4.0rc3?
