### ISSUE TITLE
the version of kombu error 

### ISSUE THREAD

**Issue by a372661369** [celery/celery#5733]
env: `python:2.7.15, celery:4.1.1, kombu:4.6.4`

when i run `celery`, it report error:

`Traceback (most recent call last):
  File "/usr/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 15, in main
    from celery.bin.celery import main as _main
  File "/usr/lib/python2.7/site-packages/celery/bin/__init__.py", line 2, in <module>
    from .base import Option
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 16, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency, signals
  File "/usr/lib/python2.7/site-packages/celery/signals.py", line 16, in <module>
    from .utils.dispatch import Signal
  File "/usr/lib/python2.7/site-packages/celery/utils/__init__.py", line 9, in <module>
    from .functional import memoize  # noqa
  File "/usr/lib/python2.7/site-packages/celery/utils/functional.py", line 10, in <module>
    from kombu.utils.functional import (LRUCache, dictfilter, is_list, lazy,
  File "/usr/lib/python2.7/site-packages/kombu/utils/__init__.py", line 5, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/usr/lib/python2.7/site-packages/kombu/utils/compat.py", line 10, in <module>
    import importlib_metadata
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/usr/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from more_itertools.more import *  # noqa
  File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 340
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax
`

and then i find the requirements file, it shows: 
`pytz>dev
billiard>=3.5.0.2,<3.6.0
kombu>=4.2.0,<5.0
`.
but kombu==4.6.4 requires python3

**Comment by sp1rs** [comment]
Just install the kombu version `4.2.0`

**Comment by auvipy** [comment]
this is not a celery or kombu issue
