### ISSUE TITLE
 ERROR/MainProcess] Unrecoverable error: InterfaceError("(0, '')",)

### ISSUE THREAD

**Issue by Baloneo** [celery/celery#5774]
```
[2019-10-11 11:06:32,967: ERROR/MainProcess] Unrecoverable error: InterfaceError("(0, '')",)
Traceback (most recent call last):
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/pymysql/connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/pymysql/connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/worker/consumer.py", line 280, in start
    blueprint.start(self)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/worker/consumer.py", line 884, in start
    c.loop(*c.loop_args())
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/kombu/transport/base.py", line 146, in _read
    drain_events(timeout=0)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/amqp/connection.py", line 326, in drain_events
    return amqp_method(channel, args, content)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/amqp/channel.py", line 1909, in _basic_deliver
    fun(msg)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/kombu/messaging.py", line 598, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/kombu/messaging.py", line 564, in receive
    [callback(body, message) for callback in callbacks]
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/kombu/messaging.py", line 564, in <listcomp>
    [callback(body, message) for callback in callbacks]
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/worker/consumer.py", line 468, in on_task_received
    callbacks)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/worker/strategy.py", line 56, in task_message_handler
    if req.revoked():
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/worker/job.py", line 338, in revoked
    'expired' if expired else 'revoked', False, None, expired,
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/worker/job.py", line 322, in _announce_revoked
    self.task.backend.mark_as_revoked(self.id, reason, request=self)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/backends/base.py", line 169, in mark_as_revoked
    request=request)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/celery/backends/base.py", line 271, in store_result
    request=request, **kwargs)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/djcelery/backends/database.py", line 29, in _store_result
    traceback=traceback, children=self.current_task_children(request),
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/djcelery/managers.py", line 42, in _inner
    return fun(*args, **kwargs)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/djcelery/managers.py", line 181, in store_result
    'meta': {'children': children}})
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/djcelery/managers.py", line 87, in update_or_create
    return get_queryset(self).update_or_create(**kwargs)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/djcelery/managers.py", line 70, in update_or_create
    obj, created = self.get_or_create(**kwargs)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/pymysql/connections.py", line 515, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/guoji/Documents/jk_venv/lib/python3.6/site-packages/pymysql/connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
django.db.utils.InterfaceError: (0, '')
[2019-10-11 11:06:32,979: WARNING/Worker-12] --Fri Oct 11 11:06:32 2019-----本次周期查询结束----------
[2019-10-11 11:06:33,596: WARNING/Worker-10] {'wind_speed': 1.1754522323608398, 'wind_direction': 134.5, 'temperature': 33.65625, 'moisture': 55.129215240478516, 'pressure': 1012.2000122070312, 'rainfall_min': 0.0, 'rainfall_hour': 0.0, 'rainfall_day': 0.0, 'rainfall_acc': 0.0}
[2019-10-11 11:06:34,655: WARNING/Worker-11] {'wind_speed': 1.1317801475524902, 'wind_direction': 133.71875, 'temperature': 33.66015625, 'moisture': 55.129215240478516, 'pressure': 1012.2000122070312, 'rainfall_min': 0.0, 'rainfall_hour': 0.0, 'rainfall_day': 0.0, 'rainfall_acc': 0.0}
guoji@guojiComputer:~$ 
```

**Comment by thedrow** [comment]
Please use and fill our bug report issue template.
As of right now, we cannot aid in debugging this issue with the information you provided.
