### ISSUE TITLE
Using -c 2  to start celery then revoke task twice, waiting for new worker create then start the same new task will happen "ValueError: invalid file descriptor 12"

### ISSUE THREAD

**Issue by zhenjiazheng** [celery/celery#5782]
# Checklist

- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:
software -> celery:4.3.0 (rhubarb) kombu:4.6.3 py:3.7.4
            billiard:3.6.0.0 py-amqp:2.5.0
platform -> system:Darwin arch:64bit
            kernel version:19.0.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp://guest:**@172.20.25.197:5672/vhost

BROKER_URL: 'amqp://guest:********@ip:5672/vhost'
CELERY_RESULT_BACKEND: 'amqp://guest:********@ip:5672/vhost'

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
aiofiles==0.4.0
aiohttp==3.5.4
aiokafka==0.5.2
alembic==1.0.11
amqp==2.5.0
aniso8601==8.0.0
appnope==0.1.0
APScheduler==3.6.1
asn1crypto==0.24.0
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.1.0
autopep8==1.3.4
Babel==2.7.0
backcall==0.1.0
bandit==1.6.2
bcrypt==3.1.7
beautifulsoup4==4.8.0
billiard==3.6.0.0
blinker==1.4
cassandra-driver==3.18.0
celery==4.3.0
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
ConcurrentLogHandler==0.9.1
crypto==1.4.1
cryptography==2.7
cycler==0.10.0
Cython==0.29.13
decorator==4.4.0
defusedxml==0.6.0
Django==2.2.4
docopt==0.6.2
elasticsearch==7.0.2
enum34==1.1.6
et-xmlfile==1.0.1
filetype==1.0.5
fire==0.2.1
Flask==1.1.1
flask-apidoc==1.2.0
Flask-APScheduler==1.11.0
Flask-BabelEx==0.9.3
Flask-Cors==3.0.8
Flask-Elasticsearch==0.2.5
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Migrate==2.5.2
Flask-Principal==0.4.0
Flask-PyMongo==2.3.0
flask-redis==0.4.0
Flask-RESTful==0.3.7
flask-restplus==0.13.0
Flask-Script==2.0.6
Flask-Security==3.0.0
Flask-SocketIO==4.2.0
Flask-SQLAlchemy==2.4.0
Flask-Uploads==0.2.1
Flask-WTF==0.14.2
flower==0.9.3
future==0.17.1
gevent==1.4.0
gitdb2==2.0.5
GitPython==2.1.13
google==2.0.2
greenlet==0.4.15
gunicorn==19.9.0
hdfs==2.5.8
hdfs3==0.3.1
idna==2.8
importlib-metadata==0.18
ipdb==0.12.2
ipython==7.7.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.14.1
jieba==0.39
Jinja2==2.10.1
jira==2.0.0
JPype1==0.6.3
jsonpath-rw==1.4.0
jsonpickle==1.2
jsonschema==3.0.2
kafka-python==1.4.6
kazoo==2.5.0
kiwisolver==1.1.0
kombu==4.6.3
macaca==0.1.0
Mako==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.1
more-itertools==7.1.0
msgpack==0.6.1
multidict==4.5.2
Naked==0.1.31
nodejs==0.1.1
npm==0.1.1
numpy==1.16.4
oauthlib==3.1.0
opencv-python==4.1.0.25
opencv-python-headless==4.1.0.25
openpyxl==2.6.2
optional-django==0.3.0
packaging==19.0
pandas==0.25.0
paramiko==2.6.0
ParamUnittest==0.2
parso==0.5.1
passlib==1.7.1
pbr==5.4.2
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
pipreqs==0.4.9
pluggy==0.12.0
ply==3.11
prettytable==0.7.2
prompt-toolkit==2.0.9
protobuf==3.9.0
ptyprocess==0.6.0
py==1.8.0
py4j==0.10.8.1
pyasn1==0.4.5
pyasn1-modules==0.2.6
pycodestyle==2.3.1
pycparser==2.19
pycrypto==2.6.1
pyecharts==1.3.1
PyExcelerate==0.8.0
PyExecJS==1.5.1
pyflakes==2.1.1
Pygments==2.4.2
PyJWT==1.7.1
pykafka==2.8.0
pymongo==3.8.0
PyMySQL==0.9.3
PyNaCl==1.3.0
pyparsing==2.4.0
pyRFC3339==1.1
pyrsistent==0.15.4
pyspark==2.4.3
pytesseract==0.2.7
pytest==5.0.1
python-dateutil==2.8.0
python-editor==1.0.4
python-engineio==3.9.2
python-ldap==3.2.0
python-socketio==4.3.0
pytz==2019.2
PyYAML==5.1.2
pyzmq==18.0.2
redis==3.3.5
reportlab==3.5.23
requests==2.22.0
requests-mock==1.6.0
requests-oauthlib==1.2.0
requests-toolbelt==0.9.1
retrying==1.3.3
rsa==4.0
rstr==2.2.6
ruamel.yaml==0.16.0
ruamel.yaml.clib==0.1.0
selenium==3.141.0
shellescape==3.4.1
simplejson==3.16.0
six==1.12.0
smmap2==2.0.5
soupsieve==1.9.2
speaklater==1.3
SQLAlchemy==1.3.6
sqlparse==0.3.0
stevedore==1.30.1
StringGenerator==0.3.3
tabulate==0.8.3
termcolor==1.1.0
TestLink-API-Python-client==0.8.0
threadpool==1.3.2
tornado==5.1.1
traitlets==4.3.2
tzlocal==2.0.0
urllib3==1.25.3
vine==1.3.0
wcwidth==0.1.7
wd==1.0.1
websocket==0.2.1
websocket-client==0.56.0
Werkzeug==0.15.5
wsaccel==0.6.2
WTForms==2.2.1
xeger==0.3.5
xlrd==1.2.0
XlsxWriter==1.1.8
xlutils==2.0.0
xlwt==1.3.0
yarg==0.1.9
yarl==1.3.0
zerorpc==0.6.3
zipp==0.5.2

```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

**Comment by zhenjiazheng** [comment]
[2019-10-21 15:07:21,714: DEBUG/MainProcess] Timer wake-up! Next ETA 0.99959993199991 secs.
[2019-10-21 15:07:22,715: DEBUG/MainProcess] Timer wake-up! Next ETA 1.0 secs.
[2019-10-21 15:07:23,715: DEBUG/MainProcess] Timer wake-up! Next ETA 0.8660087639996163 secs.
[2019-10-21 15:07:23,739: INFO/MainProcess] Received task: app.controllers.automation.testset.print_platform[22c634eb-320b-479d-acba-65c7c96831a3]  
[2019-10-21 15:07:23,740: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x11efb9680> (args:('app.controllers.automation.testset.print_platform', '22c634eb-320b-479d-acba-65c7c96831a3', {'lang': 'py', 'task': 'app.controllers.automation.testset.print_platform', 'id': '22c634eb-320b-479d-acba-65c7c96831a3', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '22c634eb-320b-479d-acba-65c7c96831a3', 'parent_id': None, 'argsrepr': '(1, 10)', 'kwargsrepr': '{}', 'origin': 'gen40221@cn0014005695.local', 'reply_to': 'a7e6c528-c148-35fd-963c-a224a1e52e0b', 'correlation_id': '22c634eb-320b-479d-acba-65c7c96831a3', 'delivery_info': {'exchange': '', 'routing_key': 'query_platform_1_api', 'priority': None, 'redelivered': False}}, '[[1, 10], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2019-10-21 15:07:23,741: DEBUG/MainProcess] Task accepted: app.controllers.automation.testset.print_platform[22c634eb-320b-479d-acba-65c7c96831a3] pid:40544
[2019-10-21 15:07:23,742: WARNING/ForkPoolWorker-10] Platform_id: 1
[2019-10-21 15:07:23,752: ERROR/ForkPoolWorker-10] Thread 'ResultHandler' crashed: ValueError('invalid file descriptor 12')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 478, in run
    return self.body()
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 864, in body
    for _ in self._process_result(1.0):  # blocking
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 829, in _process_result
    ready, task = poll(timeout)
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 1329, in _poll_result
    if self._outqueue._reader.poll(timeout):
  File "/usr/local/lib/python3.7/site-packages/billiard/connection.py", line 287, in poll
    return self._poll(timeout)
  File "/usr/local/lib/python3.7/site-packages/billiard/connection.py", line 465, in _poll
    r = wait([self], timeout)
  File "/usr/local/lib/python3.7/site-packages/billiard/connection.py", line 998, in wait
    return _poll(object_list, timeout)
  File "/usr/local/lib/python3.7/site-packages/billiard/connection.py", line 978, in _poll
    raise ValueError('invalid file descriptor %i' % fd)
ValueError: invalid file descriptor 12
[2019-10-21 15:07:24,171: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2019-10-21 15:07:24,540: ERROR/MainProcess] Process 'ForkPoolWorker-10' pid:40544 exited with 'exitcode 1'
[2019-10-21 15:07:24,553: DEBUG/ForkPoolWorker-12] Closed channel #1
[2019-10-21 15:07:24,587: DEBUG/MainProcess] Timer wake-up! Next ETA 0.1279656229999091 secs.

**Comment by auvipy** [comment]
can you post your problem in celery-users mailing list?

**Comment by RonRothman** [comment]
Quick question: Is the celery-users mailing list the Source of Truth for technical problems and their solutions? Or is it here on Github?

We're seeing this issue as well, and would like to follow the conversation. Thanks.

**Comment by auvipy** [comment]
> Quick question: Is the celery-users mailing list the Source of Truth for Celery bug reports and their solutions? Or is it here on Github?
> 
> We're seeing this issue as well, and would like to follow the conversation. Thanks.

For bug report, GitHub is here, but many users mistakenly ask their questions here instead of the mailing list. the suggestion is for making sure the issue is really issue and not a question at all. and since more then on of you can verify this as a celery bug, we can continue discussin here.

**Comment by wjkaola123** [comment]
I have got the same problem like "ValueError: invalid file descriptor 16" when the celery task running a few days.

**Comment by auvipy** [comment]
update on the latest master?

**Comment by jayaskren** [comment]
We are also seeing this issue
