### ISSUE TITLE
First Steps SyntaxError: invalid syntax add troubleshooting guidlines

### ISSUE THREAD

**Issue by ChuckIT** [celery/celery#5821]
# Checklist

- [ x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x ] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

Following the First Steps tutorial all goes well
Until I execute the command

$ celery -A tasks worker --loglevel=info
I get the following traceback I go to the trouble shooting section and no mention of how to deal with this error is mentioned. Could the documentation please be updated to include such information,  Note that a cursory attempt at debugging revealed that executing the command
$ celery resulted in the same traceback error.
 
Traceback (most recent call last):
  File "/home/chuck/.local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/chuck/.local/lib/python2.7/site-packages/celery/__main__.py", line 15, in main
    from celery.bin.celery import main as _main
  File "/home/chuck/.local/lib/python2.7/site-packages/celery/bin/__init__.py", line 2, in <module>
    from .base import Option
  File "/home/chuck/.local/lib/python2.7/site-packages/celery/bin/base.py", line 16, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency, signals
  File "/home/chuck/.local/lib/python2.7/site-packages/celery/signals.py", line 16, in <module>
    from .utils.dispatch import Signal
  File "/home/chuck/.local/lib/python2.7/site-packages/celery/utils/__init__.py", line 8, in <module>
    from .functional import memoize  # noqa
  File "/home/chuck/.local/lib/python2.7/site-packages/celery/utils/functional.py", line 10, in <module>
    from kombu.utils.functional import (LRUCache, dictfilter, is_list, lazy,
  File "/home/chuck/.local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 5, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/home/chuck/.local/lib/python2.7/site-packages/kombu/utils/compat.py", line 10, in <module>
    import importlib_metadata
  File "/home/chuck/.local/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/home/chuck/.local/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/home/chuck/.local/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from more_itertools.more import *  # noqa
  File "/home/chuck/.local/lib/python2.7/site-packages/more_itertools/more.py", line 340
    def _collate(*iterables, key=lambda a: a, reverse=False):
                                            ^
SyntaxError: invalid syntax
)

# Suggestions

Please include the appropriate troubleshooting guidelines.

**Comment by auvipy** [comment]
6.0.0

    Major changes:
            Python 2.7 is no longer supported. The 5.0.0 release will be the last version targeting Python 2.7.
            All future releases will target the active versions of Python 3. As of 2019, those are Python 3.4 and above.
            The six library is no longer a dependency.
            The accumulate function is no longer part of this library. You may import a better version from the standard itertools module.

**Comment by auvipy** [comment]
use a python 2.7 supported version of itertool
