### ISSUE TITLE
Using link_error with remote worker lead to "kombu.exceptions.EncodeError: Object of type 'Context' is not JSON serializable error"

### ISSUE THREAD

**Issue by nicolaspanel** [celery/celery#5922]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
celery==4.4.0
django-redis==4.10.0
redis==3.3.11
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.6
* **Minimal Celery Version**: 4.4.0
* **Minimal Kombu Version**: 4.6.7
* **Minimal Broker Version**: rabbitmq
* **Minimal Result Backend Version**: redis
* **Minimal OS and/or Kernel Version**: ubuntu 18.04
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
celery==4.4.0
kombu==4.6.7
redis==3.3.11
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

</p>
</details>

# Actual Behavior

I have the following code that run as expected on a single worker / code base :
```python
@task()
def fail(*args, **kwargs):
    raise NotImplementedError

@task()
def set_error(*args, **kwargs):
    print('im in')

fail.s().on_error(set_error.s()).delay('foo', foo='bar').get()
```
As expected, behavior is:
1. `fail` task is called and raise a error
2. `set_error` is called
3. client gets a `NotImplementedError` exception

Now let say `fail` is on another worker. code becomes:
```python
signature('proj.fail', queue='some-queue').on_error(set_error.s()).delay('foo', foo='bar').get()
```
Behavior:
1. `fail` task is called and raise an error.  kombu tries to serialize the error leading to another exception (see Traceback below)
```
Traceback (most recent call last):
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/billiard/pool.py", line 1791, in safe_apply_callback
    fun(*args, **kwargs)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/celery/worker/request.py", line 528, in on_failure
    store_result=self.store_errors,
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/celery/backends/base.py", line 165, in mark_as_failure
    self._call_task_errbacks(request, exc, traceback)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/celery/backends/base.py", line 188, in _call_task_errbacks
    errback(request, exc, traceback)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/celery/canvas.py", line 613, in __call__
    return self.apply_async(args, kwargs)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/celery/canvas.py", line 642, in apply_async
    dict(self.options, **options) if options else self.options))
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/celery/canvas.py", line 669, in run
    first_task.apply_async(**options)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/celery/canvas.py", line 235, in apply_async
    return _apply(args, kwargs, **options)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/celery/app/base.py", line 771, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/celery/app/amqp.py", line 559, in send_task_message
    **properties
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/.pyenv/versions/3.6.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/.pyenv/versions/3.6.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/.pyenv/versions/3.6.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/.pyenv/versions/3.6.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/.pyenv/versions/3.6.6/envs/my-env/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/.pyenv/versions/3.6.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
kombu.exceptions.EncodeError: Object of type 'Context' is not JSON serializable
```
2. `set_error` is never called
3. client wait forever

**NOTE**: I also tried with `serializer='pickle'` (see below) but I still have the exact same error (`kombu.exceptions.EncodeError: Object of type 'Context' is not JSON serializable`)
```python
signature('proj.fail', serializer='pickle', queue='some-queue').on_error(set_error.s()).delay('foo', foo='bar').get()
```

# Expected Behavior

`Context` object should be serialized and error propagated.

Best regards
Nicolas

**Comment by OleksiiKoshulian** [comment]
CELERY_TASK_SERIALIZER = 'pickle' does not help if pthreads are used

**Comment by auvipy** [comment]
can you please provide a script / code to reproduce it on top of current main branch?
