### ISSUE TITLE
issue when calling apply_async with a complex pipeline

### ISSUE THREAD

**Issue by ericman93** [celery/celery#5944]
# Checklist

- [X] I have verified that the issue exists against the `master` branch of Celery.
- [] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [X] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [X] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.
- [X] I have included the contents of ``pip freeze`` in the issue.
- [X] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [X] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [X] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [X] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [X] I have tried reproducing the issue on more than one operating system.
- [X] I have tried reproducing the issue on more than one workers pool.
- [X] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [X] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.0

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

keep having `celery: error: unrecognized arguments: report`
but the error is in when calling to celery and not from celery it self
</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.6.1
* **Minimal Celery Version**: 4.4.0
* **Minimal Kombu Version**: 4.6.7
* **Minimal Broker Version**: 3.8.3
* **Minimal Result Backend Version**: 5.0.3
* **Minimal OS and/or Kernel Version**: Mac 10.14.6
* **Minimal Broker Client Version**: 3.3.11
* **Minimal Result Backend Client Version**: 3.3.11

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
kombu==4.6.7
amqp==2.5.2
celery==4.4.0
redis==3.3.11
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

Its not a test case but please run the python file here
https://gist.github.com/ericman93/2ec31270ea68b3cfd56338039c766e9c

</p>
</details>

# Expected Behavior
Taks to run

# Actual Behavior

Trying to run this pipeline
```
eric.celery.core.print_message('START!') | %(dummy([print_message('Starting subtask A'), eric.celery.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Subtask A')]) | %(dummy([print_message('Starting Subtask B'), eric.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Subtask B'), eric.tasks.subtask_b('ad56c520f9a74173ad3e6446f19712b8', '458db63427bd48e98f9b3d27204589a9', 2, '946f464babca43de8bc03e5c1202f813')]) | %(dummy([print_message('Starting Subtask C'), eric.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Subtask C'), eric.tasks.subtask_c('ad56c520f9a74173ad3e6446f19712b8', 'C')]) | print_message('Starting next session') | %(dummy([%(dummy([print_message('Starting subtask D-I'), eric.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Subtask D'), eric.tasks.subtask_d('974fb9cb12e04a3a856c4438b5bb33b7')]) | %dummy([print_message('Starting Subtask D-I'), eric.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Subtask E'), eric.tasks.subtask_e('aa107a89e6d84aa1999269725f5a6b11', 2), eric.tasks.subtask_e('ce2d6f8dc6494222979b00582f75a0eb', 2), eric.tasks.subtask_e('35d2c5f0d04a4c7cb48751ddec3e469d', 2), eric.tasks.subtask_e('410318c5579046cdbf009be243e4596c', 2)])), %(dummy([print_message('Starting subtask D-II'), eric.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Subtask D'), eric.tasks.subtask_d('0cd1a4cd01774644aa9ee8cc1fbac834')]) | %dummy([print_message('Starting Subtask E-II'), eric.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Subtask E'), eric.tasks.subtask_e('c6d0947ac9214d68a1b3ef889a2fe2b2', 2), eric.tasks.subtask_e('81a7e39833e54fdcba9dbe0590354954', 2), eric.tasks.subtask_e('38f80253760c4f8d8747e667dfc90914', 2), eric.tasks.subtask_e('5249d50e4c0342e8abe3d343f9998361', 2)]))]) | %(dummy([print_message('Staring subtask F'), eric.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Subtask F'), eric.tasks.subtask_f('ad56c520f9a74173ad3e6446f19712b8')]) | %(dummy([print_message('Starting subtask G'), eric.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Subtask G'), eric.tasks.subtask_g_1('ad56c520f9a74173ad3e6446f19712b8'), eric.tasks.subtask_g_2('ad56c520f9a74173ad3e6446f19712b8')]) | %dummy([print_message('Final sub task'), eric.tasks.change_project_status_task('ad56c520f9a74173ad3e6446f19712b8', 'Complete'), eric.tasks.finish_1('ad56c520f9a74173ad3e6446f19712b8'), eric.tasks.finish_2('ad56c520f9a74173ad3e6446f19712b8')])))))))
```
When using Rabbit as a broker it tasks 20 seconds to run `applay_async` and then the tasks are not starting in celery.
When using Redis as a broker this exception raising
```
Traceback (most recent call last):
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/redis/connection.py", line 666, in send_packed_command
    sendall(self._sock, item)
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/redis/_compat.py", line 8, in sendall
    return sock.sendall(*args, **kwargs)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
    yield
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/kombu/connection.py", line 518, in _ensured
    return fun(*args, **kwargs)
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 608, in basic_publish
    return self._put(routing_key, message, **kwargs)
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/kombu/transport/redis.py", line 789, in _put
    client.lpush(self._q_for_pri(queue, pri), dumps(message))
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/redis/client.py", line 1679, in lpush
    return self.execute_command('LPUSH', name, *values)
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/redis/client.py", line 838, in execute_command
    conn.send_command(*args)
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/redis/connection.py", line 687, in send_command
    check_health=kwargs.get('check_health', True))
  File "/Users/eric/.local/share/virtualenvs/romee-vHL_yubm/lib/python3.6/site-packages/redis/connection.py", line 679, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.
```
This is really gets stuck at `producer.publish` in `amqp.py`
If I make the pipeline smaller, everthing works fine

**Comment by ericman93** [comment]
While this is still an issue, it isn't anymore for me
In older versions of celery when chaining groups, it would concatenate them so I needed to have a dummy task between each group
This task translated to chord task, and when having chrod tasks all pipeline is inserted as one message to the broker
In celery 4.4.0 the groups are not concatenating any more, no need to have a dummy task, no chord, and the tasks are not inserting as one to the broker
