### ISSUE TITLE
Updating to redis 3.4.0 package causing startup error in Mingle

### ISSUE THREAD

**Issue by calumrussell** [celery/celery#5948]
Had redis - https://pypi.org/project/redis/ - as a non-versioned dependency. Package was updated to v3.4 yesterday, rebuilt my application today using the new package and received this error on startup:
```
[2020-01-31 22:52:56,558: DEBUG/MainProcess] | Consumer: Starting Mingle
[2020-01-31 22:52:56,558: INFO/MainProcess] mingle: searching for neighbors
[2020-01-31 22:52:56,576: CRITICAL/MainProcess] Unrecoverable error: TypeError("unhashable type: 'Redis'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/mingle.py", line 40, in start
    self.sync(c)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/mingle.py", line 44, in sync
    replies = self.send_hello(c)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/mingle.py", line 57, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/usr/local/lib/python3.6/dist-packages/celery/app/control.py", line 154, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/control.py", line 106, in _request
    pattern=self.pattern, matcher=self.matcher,
  File "/usr/local/lib/python3.6/dist-packages/celery/app/control.py", line 477, in broadcast
    limit, callback, channel=channel,
  File "/usr/local/lib/python3.6/dist-packages/kombu/pidbox.py", line 352, in _broadcast
    channel=chan)
  File "/usr/local/lib/python3.6/dist-packages/kombu/pidbox.py", line 391, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 323, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/virtual/base.py", line 963, in drain_events
    get(self._deliver, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/redis.py", line 374, in get
    self._register_BRPOP(channel)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/redis.py", line 311, in _register_BRPOP
    if not self._client_registered(channel, channel.client, 'BRPOP'):
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/redis.py", line 306, in _client_registered
    (channel, client, cmd) in self._chan_to_sock)
TypeError: unhashable type: 'Redis'
```
My application was not starting up after this error. Reverted redis to 3.3.11 and everything is working normally again.

EDIT: just adding more info about what I am seeing...

The `_client_registered` method (on the `MultiChannelPoller` object) in redis.py takes three params: channel, client, cmd. 

channel - `kombu.transport.redis.Channel` object 
client - Redis object (which has the Connection Pool object wrapped around a Connection object), my assumption here is that this is an object in the redis package mentioned above
cmd - string representing a Redis command (I am seeing BRPOP, I have no real clue about Redis so may be missing something here).

The line that is causing the error (for the avoidance of doubt) does appear to be 306, `self._chan_to_sock` is a hash whose key is the first three parameters of `_client_registered` (and value is the socket). 

Using redis 3.3.11 the client param/Redis object passed to `_client_registered` has `__hash__` property that returns a Truthy value. Using redis 3.4 calling `__hash__ ` returns None.

Fixed with - https://github.com/andymccurdy/redis-py/issues/1275

Related - https://github.com/celery/kombu/issues/1152

**Comment by calumrussell** [comment]
Closed with - https://github.com/andymccurdy/redis-py/commit/1b050753d6ec6a6630c2cfd83c2cfbd741a3ced3

**Comment by thedrow** [comment]
So what do we need to do with celery/kombu#1152?
