### ISSUE TITLE
Django + Celery + Kombu + Redis - hangs connecting to broker

### ISSUE THREAD

**Issue by petersanchez** [celery/celery#5969]
Python 3.8, Django 2.2.8, Celery 4.3.0, Kombu 4.6.7 (also same thing with 4.4.0), Redis 4.0.9

This is very strange and I really have no explanation. I believe the connection is hanging when attempting to connect to the broker (Redis) to queue a job. I'm not sure if this is a kombu or amqp issue but I figured I'd post here first. It will just hang forever unless I manually stop the process (ie, Ctrl+C).

The weirder thing is, if I run the celery default `debug_task`, it's immediately successful and then all tasks afterwards will be queued and processed normally.

This is my local dev environment. Redis is running and I can immediately connect to it via redis-cli or via Python shell using redis-py using the BROKER_URL setting.

Here are my Settings (again, this is in a Django settings file):

```
# Celery
BROKER_URL = 'redis://localhost:6379/3'
BROKER_POOL_LIMIT = 0  # Disable connection pooling
BROKER_TRANSPORT_OPTIONS = {'socket_timeout': 5}
CELERY_BROKER_TRANSPORT_OPTIONS = {'socket_timeout': 5}
CELERY_ACCEPT_CONTENT = ['json', ]
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_SEND_TASK_ERROR_EMAILS = True
CELERY_TASK_RESULT_EXPIRES = 1
CELERY_MAX_CACHED_RESULTS = -1
```

I added the `BROKER_TRANSPORT_OPTIONS` to test based on some results from searching. No luck.

Here's a shell session showing the behavior and tracebacks when I kill the hung connection process. When I killed the process it was hung for probably 30 seconds or so...

```
>>> from hyfm.notifications import engine
>>> u = A.UserShare.objects.order_by('-id')[0]
>>> engine.user_share_added(u)  # XXX Hanging here, eventually Ctrl+C ...
^CTraceback (most recent call last):
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/utils/functional.py", line 43, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/amqp/transport.py", line 136, in _connect
    entries = socket.getaddrinfo(
  File "/usr/lib/python3.8/socket.py", line 914, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -9] Address family for hostname not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/amqp/connection.py", line 311, in connect
    self.transport.connect()
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/amqp/transport.py", line 77, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/amqp/transport.py", line 145, in _connect
    raise (e
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pjs/development/hyfm/hyfm/notifications/base.py", line 26, in gen_func
    res = func(*args, **kwargs)
  File "/home/pjs/development/hyfm/hyfm/notifications/email.py", line 18, in user_share_added
    em.send(user_share.shared_user.email)
  File "/home/pjs/development/hyfm/hyfm/helpers.py", line 54, in send
    send_simple_email.delay(
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/celery/app/task.py", line 564, in apply_async
    return app.send_task(
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/celery/app/base.py", line 758, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/celery/app/amqp.py", line 550, in send_task_message
    ret = producer.publish(
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/messaging.py", line 178, in publish
    return _publish(
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/connection.py", line 518, in _ensured
    return fun(*args, **kwargs)
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/utils/functional.py", line 45, in __call__
    value = self.__value__ = self.__contract__()
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/messaging.py", line 224, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/connection.py", line 868, in default_channel
    self.ensure_connection(**conn_opts)
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/connection.py", line 427, in ensure_connection
    retry_over_time(self.connect, self.recoverable_connection_errors,
  File "/home/pjs/development/hyfm/env/lib/python3.8/site-packages/kombu/utils/functional.py", line 358, in retry_over_time
    sleep(1.0)
KeyboardInterrupt
>>> from hyfm.celery import debug_task
>>> debug_task.delay()
<AsyncResult: 01cbcf08-3849-4095-bf35-848b32e888e9>
>>> engine.user_share_added(u)
{'classes': [('hyfm.notifications.email.EmailNotification', None)],
 'notification_function': 'user_share_added'}
>>>
```

**Note:** the `engine.user_share_added` method is a simple wrapper that formats and email and calls a task that actually delivers the email. I didn't include the code here because I didn't think it necessary as you can see it clearly processes in the output above. The retuned result is expected.

Here are all modules (`pip freeze`):

```
amqp==2.5.2
argon2-cffi==19.2.0
billiard==3.6.1.0
boto==2.49.0
boto3==1.10.38
botocore==1.13.39
celery==4.4.0rc5
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
coverage==4.3.4
cryptography==2.8
Django==2.2.8
django-appconf==1.0.3
django-countries==5.5
django-crispy-forms==1.8.1
django-debug-toolbar==1.7
django-extensions==2.2.5
django-impersonate==1.4.1
django-localflavor==2.2
django-pipeline==1.6.14
django-select2==7.1.2
django-ses==0.8.13
django-storages==1.8
docutils==0.15.2
easy-thumbnails==2.6
future==0.18.2
gnureadline==8.0.0
idna==2.8
jmespath==0.9.4
jsmin==2.2.2
kombu==4.6.7
Pillow==6.2.1
pkg-resources==0.0.0
psycopg2-binary==2.8.4
pycparser==2.19
python-dateutil==2.8.1
python-memcached==1.59
python-stdnum==1.12
pytz==2019.3
redis==3.3.11
requests==2.22.0
s3transfer==0.2.1
sendypy==0.2
six==1.13.0
sqlparse==0.3.0
stripe==2.41.0
syncfiles==0.1b0
urllib3==1.25.7
vine==1.3.0
```

Celery will start just fine and process all tasks that are queued. It's just that I can't seem to queue the tasks without calling `debug_task` first. I feel like I'm overlooking something so simple but I've run into various issues in the past related to kombu and usually a downgrade fixes it. However now, it continues to happen.

I'm wondering if it's not a supporting lib that's a requirement for kombu or amqp?

Any ideas?

**Comment by auvipy** [comment]
This is probably not a celery issue. rather a problem with your settings

**Comment by yomguy** [comment]
I had the same behavior because my main project was not in its own subdirectory (with settings.py, urls, etc) but at the root of the app together with `manage.py`. Fixed setting up exactly the same structure than in the example of the celery module.

**Comment by Krogsager** [comment]
I have the same issue as OP, but the suggestion of adding code to __init__.py has no effect. I'm not using Django.
I started a post on SO https://stackoverflow.com/questions/66462079/celery-task-does-not-get-send-to-broker
TO me It seems that Kombu is stuck in an infinite loop.
I've tried downgrading celery from 5.0.5 to 4.7.7 with the same result. Any help is much appreciated.
