### ISSUE TITLE
keyerror: 'USER' when use supervisord but working in command line

### ISSUE THREAD

**Issue by pcleon** [celery/celery#5995]
celery: 4.4.1
python: 2.7.5
os: centos-7.2

i use celery with django prj.  and it works under shell when i run 
`celery worker -A mysite -l info
`
but not works when use supervisord, the ini like this 
```
[program:celery]
command=/usr/bin/celery  worker -A nemopy -l info
directory=/home/mysite
user=web 
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/celery.log

```

then i get these error log 

```
Traceback (most recent call last):
  File "/usr/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 419, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 258, in run
    **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/usr/lib/python2.7/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/usr/lib/python2.7/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
KeyError: 'USER'
```

**Comment by georgepsarakis** [comment]
Can you please provide more details about the modules that you are loading?

**Comment by pcleon** [comment]
i found it's not celery's bug , my coding not write.
i use os.environ['USER'] to get current login user.  but when celery running under supervisor env, it not works , so i  replace  getpass.getuser()  then working
