### ISSUE TITLE
Allow celery to spawn rather than fork

### ISSUE THREAD

**Issue by ibrewster** [celery/celery#6036]
# Checklist

* [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same feature was already implemented in the
  master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues
* None

#### Possible Duplicates
Similar to issue #5005 and issue #5021

# Brief Summary
When launching child processes, celery uses the fork method. Sometimes it is preferable to be able to spawn rather than fork, for instance:  https://bugs.python.org/issue33725. Celery 3.x had this ability with the `CELERYD_FORCE_EXECV` option, however it was apparently removed in version 4.0 for some reason ( https://docs.celeryproject.org/en/stable/history/whatsnew-4.0.html). Please re-introduce this feature.

# Design
## Architectural Considerations

None

## Proposed Behavior

This feature would behave exactly as it (presumably) did in version 3.x: using spawn to launch child workers rather than fork. It is likely this is already the behavior when run on windows anyway, since at least in the python multiprocessing module fork is not available on windows.

## Proposed UI/UX

Same as in version 3.x: provide a CELERYD_FORCE_EXECV option (although I guess it would be lowercase now)

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment]
will revisit and reconsider it for celery 4.5

**Comment by georgexsh** [comment]
copied from the mailing list thread: https://groups.google.com/d/msgid/celery-users/468ff21a-afd1-4887-ab9a-b7e548501e65%40googlegroups.com?utm_medium=email&utm_source=footer

> currently, on platform supports `fork()`, and `prefork` pool is used, `app.loader.init_worker`(from `AppLoader`) is called in the master process, which is very annoying.
as app task modules are imported inside the master process, user application code is executed before `fork`, but not all the application code or library is prepared for the fork, generally, they are multithreading safe, but not fork safe.
for example, the Queue stdlib, if the application created Queue instance, but process forked, deadlock happened as the mutex Queue used is not fork-safe.
https://groups.google.com/forum/#!topic/sqlalchemy/YX9NuBD75oY is a serious problem we have met also.
https://github.com/celery/celery/issues/496 is another example.
I think having the master process polluted with user application code before `fork()` is a bad design, take gunicorn as a good example, it will not touch the user WSGI app code before the worker forked by default, but give the user the option to do so.

**Comment by auvipy** [comment]
> I think celery should defer `init_worker` call inside the worker process with the prefork pool, which will resolve this and many other issues together.
> 
> (following message is copied from a celery-users mailing list thread: https://groups.google.com/d/msgid/celery-users/468ff21a-afd1-4887-ab9a-b7e548501e65%40googlegroups.com?utm_medium=email&utm_source=footer)
> 
> currently, on platform supports `fork()`, and `prefork` pool is used, `app.loader.init_worker`(from `AppLoader`) is called in the master process, which is very annoying.
> as app task modules are imported inside the master process, user application code is executed before `fork`, but not all the application code or library is prepared for the fork, generally, they are multithreading safe, but not fork safe.
> for example, the Queue stdlib, if the application created Queue instance, but process forked, deadlock happened as the mutex Queue used is not fork-safe.
> https://groups.google.com/forum/#!topic/sqlalchemy/YX9NuBD75oY is a serious problem we have met also.
> #496 is another example.
> I think having the master process polluted with user application code before `fork()` is a bad design, take gunicorn as a good example, it will not touch the user WSGI app code before the worker forked by default, but give the user the option to do so.

thanks for chiming in. would you mind handling this?

**Comment by georgexsh** [comment]
@auvipy I am trying to find a workaround by forking `AppLoader`, let `init_worker` do nothing in the master process because `process_initializer` would trigger `init_worker` again in the worker process anyway.
the problem is, so far I can't find a sound way to tell the difference between master and worker. environ variable like `_MP_FORK_LOGFILE_ ` is not a reliable source I think.

**Comment by auvipy** [comment]
please dig deeper. i will need some time to revisit this

**Comment by georgexsh** [comment]
a quick and dirty demo
```python
from celery.loaders.app import AppLoader

class ForkLazyAppLoader(AppLoader):

    def _is_in_child_process(self):
        from billiard.process import current_process
        p = current_process()
        if p._parent_pid is not None:
            return True
        return False

    def init_worker(self):
        if not self._is_in_child_process():
            return
        super(ForkSafeAppLoader, self).init_worker()

app = Celery(..., loader=ForkLazyAppLoader)
```

**Comment by xirdneh** [comment]
@georgexsh I think this looks like a good solution to explore.
Have you been able to test this locally?
I'm curious to see if the master process brakes in some way.

**Comment by georgexsh** [comment]
> Have you been able to test this locally?

of course, it is workable.

**Comment by auvipy** [comment]
would you mind come with a PR?

**Comment by georgexsh** [comment]
@auvipy not yet, it misses worker pool class checking which I have no clue, and, it is unclear to me where should the patch goes, do you think it should be the default behavior of `AppLoader`, or as an option?

**Comment by georgexsh** [comment]
besides, dependent on a non-std API `p._parent_pid` is not a good idea to me, billiard should expose an API to indicate the current process is a worker.

**Comment by xirdneh** [comment]
@georgexsh I think it would be a good idea to open up a PR and work on those things. I can lend a hand if you want.
Also, that is if you have time to keep an eye of this PR.
Having said that let me ask a few questions:
- what do you mean by
> it misses worker pool class checking which I have no clue
- I think the best option is to expose this as an option and not the default behavior. Maybe in the future we can move this to be the default.
- I agree that this should not use a non-standard API from billiard. We can also open up a PR on Billiard to standardize this if we don't find a better way to see if it's the master thread or not. Although, given the fact that this is a Unix specific problem it shouldn't be too difficult to come up with a solution.

**Comment by georgexsh** [comment]
> it misses worker pool class checking which I have no clue

above code should only work while prefork pool is used.

**Comment by xirdneh** [comment]
@georgexsh I see what you mean.
so, to be clear the main issues are:
- [ ] Figure which standard API from billiard to use to check if the current thread is a parent or not.
    - [ ] If it doesn't exists then how can we standardize `_is_in_child_process`
- [ ] How can we check which worker pool class is being used?
- [ ] How to check of master process when no tuse prefork?

**Comment by ShaheedHaque** [comment]
Fwiw, such a change might also fix the cause of jpype-project/jpype#720 which was tracked to the use of fork.

**Comment by exislow** [comment]
What is the status here? We need `spawn` really bad for macOS. Especially in combination of JayDeBeAPI and Jpype1.

**Comment by thedrow** [comment]
We haven't got around to it since this is not a priority for any of us.
We'd welcome any help :)

**Comment by jessehui** [comment]
What is the status of this issue? Will it be released with 5.1.0?

**Comment by thedrow** [comment]
Unfortunately, no one contributed this feature as of yet.

**Comment by skanti** [comment]
`Push`

I have an app hanging that doesn't support `fork`. Would totally **APPRECIATE** this feature

**Comment by hadim** [comment]
Very naive question: would that allow using `joblib` and `loky` with `-P processes`? I am currently relying on `-P threads` but I have some concerns about performance. See https://groups.google.com/g/celery-users/c/IGOBnp4n0gU for details.

**Comment by itamarst** [comment]
It seems like setting two environment variables with current PID and expected worker type in the parent process would then allow both checking whether this is child or parent, and checking if this a prefork or spawn worker type.

**Comment by drShivashankar** [comment]
celery worker --app=worker.app --pool=solo

tried this from https://www.distributedpython.com/2018/10/26/celery-execution-pool/

Works for me macOS Catalina 10.15.7
opencv-python-headless==4.4.0.46

**Comment by fredley** [comment]
I am using pymongo which is [not fork-safe](https://pymongo.readthedocs.io/en/stable/faq.html), so this feature would be greatly appreciated.

**Comment by EricAtORS** [comment]
We're deploying celery on both windows and linux nodes and our code turned out to be not fork-safe.
On windows, multiprocessing in python only supports spawn, so it worked on windows, but not on linux.
So I dug around the multiprocessing mechanism and I now have this snippet of code in my `if __name__ != "__main__"` block:

```
    # this forces the application to use spawn instead of fork
    os.environ["FORKED_BY_MULTIPROCESSING"] = "1"
    if os.name != "nt":
        from billiard import context
        context._force_start_method("spawn")
```
This block of code needs to be run before instantiating your `Celery` app.
Now our linux nodes spawn workers instead of forking

**Comment by ShaheedHaque** [comment]
As earlier, this definitely caused problems for me with using JPype (FYI, @exislow), but I also suspected it as the cause of difficulty running Celery under PyCharm (their tracker has MANY issues which I suspect are rooted in this issue, including https://youtrack.jetbrains.com/issue/PY-48388/Celery-debug-mode-stuck-on-step-into). Today, I have proof of the latter...

@georgexsh, @xirdneh I tried a variation on your fix, but ran into problems which I suspect (but am not sure) are related to my use of Djanog, and the fixups that Celery applies in my case to resolve the issues around configuration and model loading. This is what I tried to use:
```
from celery.loaders.app import AppLoader

class ForkLazyAppLoader(AppLoader):

    def _is_in_child_process(self):
        #
        # **CHECK FOR POOL TYPE**
        #
        if self.app.conf.worker_pool != 'prefork':
            return False
        # FIXME assert prefork pool
        from billiard.process import current_process
        p = current_process()
        if p._parent_pid is not None:
            return True
        return False

    def init_worker(self):
        if not self._is_in_child_process():
            return
        super().init_worker()

#
# **NEED TO PASS FQN INSTEAD OF CLASS OBJECT**
#
celery_app = Celery(..., loader=ForkLazyAppLoader.__module__ + '.' + ForkLazyAppLoader.__name__)
```
I think the first change might give a clue to one of the open question you noted? The second change is probably either because of some flaw in the Celery class-or-symbol-lookup logic, or again possibly related to the Django fixups. Ultimately, I stopped pursuing this because this broke the auto-registration of my tasks (again, I suspect related to the Django fixups).

I then tried the workaround from @EricAtORS, to force "spawn", and all my issues to do with mysterious hangs with or without PyCharm seem resolved.

@auvipy , @thedrow Is it worth considering a setting to have the prefork pool use spawn over fork? I bet it would solve a LOT of people's issues at a stroke even if it was not the default.

**Comment by sebtrack** [comment]
We use google big query and the worker hangs as well when running a simple query in a celery task.

MIght be related: https://github.com/googleapis/google-cloud-python/issues/4736

**Comment by sabetAI** [comment]
> We're deploying celery on both windows and linux nodes and our code turned out to be not fork-safe. On windows, multiprocessing in python only supports spawn, so it worked on windows, but not on linux. So I dug around the multiprocessing mechanism and I now have this snippet of code in my `if __name__ != "__main__"` block:
> 
> ```
>     # this forces the application to use spawn instead of fork
>     os.environ["FORKED_BY_MULTIPROCESSING"] = "1"
>     if os.name != "nt":
>         from billiard import context
>         context._force_start_method("spawn")
> ```
> 
> This block of code needs to be run before instantiating your `Celery` app. Now our linux nodes spawn workers instead of forking
> 
> Edit: I did try the `ForkLazyAppLoader` but it didn't work in my case because the tasks were not being registered

@EricAtORS I get a weird crash, and the following error when trying to run that snippet:

/home/<usr>/miniconda3/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

Any ideas why?

**Comment by drShivashankar** [comment]
Why are there 2 forward slash after /home ?

**Comment by drShivashankar** [comment]
> > We're deploying celery on both windows and linux nodes and our code turned out to be not fork-safe. On windows, multiprocessing in python only supports spawn, so it worked on windows, but not on linux. So I dug around the multiprocessing mechanism and I now have this snippet of code in my `if __name__ != "__main__"` block:
> > ```
> >     # this forces the application to use spawn instead of fork
> >     os.environ["FORKED_BY_MULTIPROCESSING"] = "1"
> >     if os.name != "nt":
> >         from billiard import context
> >         context._force_start_method("spawn")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This block of code needs to be run before instantiating your `Celery` app. Now our linux nodes spawn workers instead of forking
> > Edit: I did try the `ForkLazyAppLoader` but it didn't work in my case because the tasks were not being registered
> 
> @EricAtORS I get a weird crash, and the following error when trying to run that snippet:
> 
> /home//miniconda3/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
> 
> Any ideas why?

Why are there 2 forward slash after /home ?

**Comment by sabetAI** [comment]
> Why are there 2 forward slash after /home ?
No idea @drShivashankar, doesn't affect execution. Any ideas on how to fix the crash?

**Comment by EricAtORS** [comment]
@sabetAI 
I had only tested with python 3.8, though this could be related:
https://github.com/conda/conda/issues/9589
You probably just need to update to the latest build of python 3.9. If they haven't back ported, just update to the latest patch release.

**Comment by atreyasha** [comment]
Thanks @EricAtORS for the suggestion! I needed to spawn child processes in `celery` to load/run CUDA models on a GPU, because CUDA does not support forking (see: https://pytorch.org/docs/stable/notes/multiprocessing.html). Your suggestion works great, will report back if any errors come up.

Would be great to have this feature directly supported in `celery` :+1:

**Comment by yigit-konuksever** [comment]
@EricAtORS Thanks to you for this awesome solution. It's working with open3d's point cloud instance methods on celery while normal prefork pool doesn't.

**Comment by EricAtORS** [comment]
> I tried changing billiard context to spawn as suggested by @EricAtORS. It gave me following error.
> 
> ```shell
> [2024-02-09 10:35:37,636: ERROR/MainProcess] Task handler raised error: ValueError('not enough values to unpack (expected 3, got 0)')
> billiard.einfo.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/ubuntu/demucs_deploy/venv/lib/python3.9/site-packages/billiard/pool.py", line 361, in workloop
>     result = (True, prepare_result(fun(*args, **kwargs)))
>   File "/home/ubuntu/demucs_deploy/venv/lib/python3.9/site-packages/celery/app/trace.py", line 664, in fast_trace_task
>     tasks, accept, hostname = _loc
> ValueError: not enough values to unpack (expected 3, got 0)
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/demucs_deploy/venv/lib/python3.9/site-packages/billiard/pool.py", line 361, in workloop
>     result = (True, prepare_result(fun(*args, **kwargs)))
>   File "/home/ubuntu/demucs_deploy/venv/lib/python3.9/site-packages/celery/app/trace.py", line 664, in fast_trace_task
>     tasks, accept, hostname = _loc
> ValueError: not enough values to unpack (expected 3, got 0)
> ```
> 
> Celery should have spawn method also along with fork.

You need to set the  `FORKED_BY_MULTIPROCESSING` environment varaible to `1` or else you get the issue above.
I made my suggestions to do it in python code, but you are free to set it however you want

**Comment by raghavprabhakar1** [comment]
@EricAtORS Thanks for the suggestion. It worked.

**Comment by rkuo-danswer** [comment]
We consider this a near showstopper ... is anyone else in this situation?  Fork-ing makes using any sort of third party SDK or library in a task unstable as we simply don't control what those SDK's do in terms of threading, memory, handles, etc.  

Removing the workarounds over time seems even more unbelievable.

Our recent solution is to simply run a worker in threaded mode and using multiprocessing.set_start_method to "spawn", then self managing the process creation and monitoring via Process in each thread.  This is far from ideal, but gives us the task queueing benefits of Celery while sidestepping the instability of forking in the prefork mode.

**Comment by MajorDallas** [comment]
I want to bump this issue and highlight something I haven't seen mentioned yet: as of Python 3.12, calling `fork()` in a multithreaded process is deprecated. I'm testing with 3.13 now and I get the following warning every time a worker starts:

```
DeprecationWarning: This process (pid=1) is multi-threaded, use of fork() may lead to deadlocks in the child.
```

Adapting EricAtORS' workaround in https://github.com/celery/celery/issues/6036#issuecomment-1151224775 for my needs silenced the warning and the app seems to be running with no differences so far, so I'll +1 that as a workaround in the meantime. But:

It sounds like Celery will _have_ to either replace `fork()` with `spawn()` even on Unix platforms sometime in the near future, or else take a hard-against stance on allowing workers to be multithreaded.

[This thread](https://discuss.python.org/t/concerns-regarding-deprecation-of-fork-with-alive-threads/33555) discusses why `fork()` has been deprecated and why CPython will probably never do anything to fix it.

**Comment by heilaw** [comment]
> Thanks [@EricAtORS](https://github.com/EricAtORS) for the suggestion! I needed to spawn child processes in `celery` to load/run CUDA models on a GPU, because CUDA does not support forking (see: https://pytorch.org/docs/stable/notes/multiprocessing.html). Your suggestion works great, will report back if any errors come up.
> 
> Would be great to have this feature directly supported in `celery` 👍

I recently came across this issue too. We need spawn to support scripts that use CUDA. It will be great to see this is supported directly in celery.

**Comment by auvipy** [comment]
I will look into it soon and see if it can be done in v5.7

**Comment by stuaxo** [comment]
It's interesting, as the crash seems to happen in different third party libraries - I was using Postgres and disabling kerberos seemed to make it more stable...  until it didn't.

This seems to pretty reliably trigger when calling my task that underneath is using django with postgres + mssql, using MacOS.

For the the individual tasks, I can call them as functions but one of the tasks I have is a workflow with subtasks, and that's not usable when this triggers.

**Comment by stuaxo** [comment]
When it comes to PsycoPg (as used in the Celery+Django+Postgres) combination, it was kerberos auth that was triggering this (most of the time), and a fix is being added there to disable that when it's not being used.

This should help somewhat until sparn is available here.
https://github.com/psycopg/psycopg/issues/1136

**Comment by IngmarStein** [comment]
I've started seeing paperless-ngx's Celery worker crash after updating to macOS 26.0 (still the same in 26.1 beta 1) which may trigger another fork-unsafe call. A workaround is to use any other pool type than the default `prefork`.

Here's a stacktrace:

```
Application Specific Information:
*** multi-threaded process forked ***
crashed on child side of fork pre-exec


Thread 0 Crashed:
0   libsystem_trace.dylib         	       0x180a690b4 _os_log_find + 64
1   libsystem_trace.dylib         	       0x180a68dd4 os_log_create + 304
2   libswiftos.dylib              	       0x19de85a7c Logger.init(subsystem:category:) + 92
3   Network                       	       0x1892b7ed4 0x18903b000 + 2608852
4   libdispatch.dylib             	       0x180b9aac4 _dispatch_client_callout + 16
5   libdispatch.dylib             	       0x180b83a60 _dispatch_once_callout + 32
6   Network                       	       0x18925a1b4 0x18903b000 + 2224564
7   Network                       	       0x189119dd4 0x18903b000 + 912852
8   Network                       	       0x18911d6ac 0x18903b000 + 927404
9   Network                       	       0x18911d5e4 0x18903b000 + 927204
10  Network                       	       0x189117018 0x18903b000 + 901144
11  Network                       	       0x189e77318 nw_path_access_agent_cache + 188
12  Network                       	       0x189113e44 0x18903b000 + 888388
13  Network                       	       0x189113580 0x18903b000 + 886144
14  Network                       	       0x1893d9a58 _nw_path_update_is_viableTm + 84
15  Network                       	       0x189e50f20 nw_path_snapshot_path(NWConcrete_nw_path*) + 64
16  Network                       	       0x189e50698 nw_path_evaluator_evaluate(NWConcrete_nw_path_evaluator*, int*) + 2308
17  Network                       	       0x189e4f578 nw_path_create_evaluator_for_endpoint + 68
18  Network                       	       0x189ca88a0 nw_nat64_v4_address_requires_synthesis + 240
19  libsystem_info.dylib          	       0x180d6554c _gai_nat64_second_pass + 280
20  libsystem_info.dylib          	       0x180d51900 si_addrinfo + 1388
21  libsystem_info.dylib          	       0x180d512ec getaddrinfo + 168
22  _socket.cpython-313-darwin.so 	       0x109ee9bc4 socket_getaddrinfo + 484
23  Python                        	       0x104f5d51c cfunction_call + 76
24  Python                        	       0x104effb3c _PyObject_MakeTpCall + 120
25  Python                        	       0x1050295a4 _PyEval_EvalFrameDefault + 6876
26  Python                        	       0x104eff9b4 _PyObject_VectorcallDictTstate + 200
27  Python                        	       0x104f92e28 slot_tp_init + 196
28  Python                        	       0x104f88de0 type_call + 148
29  Python                        	       0x104effb3c _PyObject_MakeTpCall + 120
30  Python                        	       0x10502f0e4 _PyEval_EvalFrameDefault + 30236
31  Python                        	       0x104eff9b4 _PyObject_VectorcallDictTstate + 200
32  Python                        	       0x104f92e28 slot_tp_init + 196
33  Python                        	       0x104f88de0 type_call + 148
34  Python                        	       0x104effb3c _PyObject_MakeTpCall + 120
35  Python                        	       0x10502f0e4 _PyEval_EvalFrameDefault + 30236
36  Python                        	       0x104eff948 _PyObject_VectorcallDictTstate + 92
37  Python                        	       0x104f00f18 _PyObject_Call_Prepend + 136
38  Python                        	       0x104f91d40 slot_tp_call + 128
39  Python                        	       0x104f0081c _PyObject_Call + 128
40  Python                        	       0x10502d1c0 _PyEval_EvalFrameDefault + 22264
41  Python                        	       0x104eff948 _PyObject_VectorcallDictTstate + 92
42  Python                        	       0x104f00f18 _PyObject_Call_Prepend + 136
43  Python                        	       0x104f91d40 slot_tp_call + 128
44  Python                        	       0x104f0081c _PyObject_Call + 128
45  Python                        	       0x10502d1c0 _PyEval_EvalFrameDefault + 22264
46  Python                        	       0x104f03124 method_vectorcall + 392
47  Python                        	       0x10502d1c0 _PyEval_EvalFrameDefault + 22264
48  Python                        	       0x104eff948 _PyObject_VectorcallDictTstate + 92
49  Python                        	       0x104f00f18 _PyObject_Call_Prepend + 136
50  Python                        	       0x104f91d40 slot_tp_call + 128
51  Python                        	       0x104effb3c _PyObject_MakeTpCall + 120
52  Python                        	       0x105029cc0 _PyEval_EvalFrameDefault + 8696
53  Python                        	       0x104f1c428 gen_send_ex2 + 196
54  Python                        	       0x104f1afe4 gen_iternext + 36
55  Python                        	       0x105024328 builtin_next + 72
56  Python                        	       0x10502c144 _PyEval_EvalFrameDefault + 18044
57  Python                        	       0x104f030e0 method_vectorcall + 324
58  Python                        	       0x104f00534 _PyVectorcall_Call + 152
59  Python                        	       0x10502d1c0 _PyEval_EvalFrameDefault + 22264
60  Python                        	       0x104f030e0 method_vectorcall + 324
61  Python                        	       0x104f00534 _PyVectorcall_Call + 152
62  Python                        	       0x10502d1c0 _PyEval_EvalFrameDefault + 22264
63  Python                        	       0x104eff9b4 _PyObject_VectorcallDictTstate + 200
64  Python                        	       0x104f00f18 _PyObject_Call_Prepend + 136
65  Python                        	       0x104f91d40 slot_tp_call + 128
66  Python                        	       0x104effb3c _PyObject_MakeTpCall + 120
67  Python                        	       0x10502f0e4 _PyEval_EvalFrameDefault + 30236
68  Python                        	       0x10502784c PyEval_EvalCode + 200
69  Python                        	       0x1050981bc run_eval_code_obj + 104
70  Python                        	       0x105097c04 run_mod + 168
71  Python                        	       0x1050962ac pyrun_file + 164
72  Python                        	       0x1050955e8 _PyRun_SimpleFileObject + 256
73  Python                        	       0x105095220 _PyRun_AnyFileObject + 80
74  Python                        	       0x1050bceb8 pymain_run_file_obj + 164
75  Python                        	       0x1050bcb64 pymain_run_file + 76
76  Python                        	       0x1050bbdd4 Py_RunMain + 968
77  Python                        	       0x1050bc3d0 pymain_main + 304
78  Python                        	       0x1050bc470 Py_BytesMain + 40
79  dyld                          	       0x180975d54 start + 7184
```

**Comment by Nusnus** [comment]
Potential fix:
- https://github.com/celery/billiard/pull/443

Released in [billiard v4.3.0rc1](https://github.com/celery/billiard/releases/tag/v4.3.0rc1)

**Comment by auvipy** [comment]
This pr https://github.com/celery/celery/pull/10339 might be a potential fix for this, need people to check and try this

**Comment by auvipy** [comment]
another relevant pr https://github.com/celery/celery/pull/10584

**Comment by ShaheedHaque** [comment]
@auvipy Could you kindly summarise here, or with a pointer to the docs, how to enable this? (with or without async?)

**Comment by auvipy** [comment]
please wait until the pre release of v5.7
