### ISSUE TITLE
Calling get() on a synchronous chain result triggers E_WOULDBLOCK

### ISSUE THREAD

**Issue by neuroid** [celery/celery#6072]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- https://github.com/celery/celery/issues/5330

#### Possible Duplicates

- https://github.com/celery/celery/issues/5330

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.2 (cliffs) kombu:4.6.8 py:2.7.17
            billiard:3.6.3.0 py-amqp:2.5.2
platform -> system:Darwin arch:64bit
            kernel version:19.4.0 imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.5.2
billiard==3.6.3.0
celery==4.4.2
configparser==4.0.2
contextlib2==0.6.0.post1
importlib-metadata==1.6.0
kombu==4.6.8
pathlib2==2.3.5
pytz==2020.1
scandir==1.10.0
six==1.14.0
vine==1.3.0
zipp==1.2.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
@app.task
def task(s):
    signature(s).apply().get(disable_sync_subtasks=False)


@app.task
def task2():
    pass


@app.task
def task3():
    pass

# works
task.delay(task2.s())

# results in RuntimeError(E_WOULDBLOCK)
task.delay(task2.s() | task3.s())
```

</p>
</details>

# Expected Behavior
Both scheduled tasks should succeed.

# Actual Behavior
The second task raises in the following error:

```
[2020-05-04 16:42:29,038: ERROR/ForkPoolWorker-7] [-] Task foo.task[44640f0b-c9cc-45ba-b082-f100eec77ee0] raised unexpected: RuntimeError(u'Never call result.get() within a task!\nSee http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks\n',)
Traceback (most recent call last):
  File "/env/lib/python2.7/site-packages/celery/app/trace.py", line 411, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/env/lib/python2.7/site-packages/celery/app/trace.py", line 680, in __protected_call__
    return self.run(*args, **kwargs)
  File "/foo/tasks/__init__.py", line 18, in task
    signature(s).apply().get(disable_sync_subtasks=False)
  File "/env/lib/python2.7/site-packages/celery/canvas.py", line 808, in apply
    last and (last.get(),), **dict(self.options, **options))
  File "/env/lib/python2.7/site-packages/celery/result.py", line 1027, in get
    assert_will_not_block()
  File "/env/lib/python2.7/site-packages/celery/result.py", line 43, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

As a side note, I'm not entirely sure why is it necessary to pass `disable_sync_subtasks` to `EagerResult.get()`. Since the code is executed in the same process there doesn't seem to be much potential for anything to block.

**Comment by neuroid** [comment]
As a workaround I'm using `with allow_join_result():` instead of `disable_sync_subtasks`.

**Comment by auvipy** [comment]
can you propose a PR with fix a and test case?

**Comment by auvipy** [comment]
> As a workaround I'm using `with allow_join_result():` instead of `disable_sync_subtasks`.

did you check https://stackoverflow.com/questions/33280456/calling-async-result-get-from-within-a-celery-task/39975099 ?

**Comment by auvipy** [comment]
> > As a workaround I'm using `with allow_join_result():` instead of `disable_sync_subtasks`.
> 
> did you check https://stackoverflow.com/questions/33280456/calling-async-result-get-from-within-a-celery-task/39975099 ?

https://github.com/celery/celery/issues/3498#issuecomment-252705043

**Comment by YPCrumble** [comment]
@auvipy I'm coming up against this when calling `get()` on an `EagerResult`. 

In particular, I'm doing something like this which throws the error:

```
eager_result = some_task.apply()
result = eager_result.get()
```

It seems odd to get the warning `RuntimeError: Never call result.get() within a task!`, because clearly here `get()` is being called after a task has been called using the synchronous `apply()` syntax. In particular, the docs state that an `EagerResult` is a ["Result that we know has already been executed."](https://docs.celeryq.dev/en/stable/reference/celery.result.html#celery.result.EagerResult)

I'm also wondering, wouldn't it make sense to remove the two WARNING boxes that seem only to apply to `AsyncResult` about waiting for tasks within a task, if we know that an `EagerResult` is performed synchronously?

I'm adding this comment because I believe it's possible I'm completely mis-understanding how Celery is working, especially with respect to `EagerResult` if that's the case I would love to help update the docs to clarify.

Thank you for maintaining Celery!

**Comment by auvipy** [comment]
if you can come with a PR, it would be easier for me to check and verify. can you do please?
