### ISSUE TITLE
task retry does not manage argsrepr and kwargsrepr

### ISSUE THREAD

**Issue by llicour** [celery/celery#6086]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.2 (cliffs) kombu:4.6.8 py:3.6.10
            billiard:3.6.3.0 redis:3.4.1
platform -> system:Darwin arch:64bit
            kernel version:19.4.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/1

broker_url: 'redis://localhost:6379/1'
result_backend: 'redis://localhost:6379/1'

```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

retry does not handle argsrepr and kwargsrepr, so sensitive datas are not hidden.
This occurs when task retry after a failure (*repr variables seems not be part of the retry message). Exception MaxRetriesExceededError also disclose args and kwargs insteed of argsrepr and kwargsrepr, even if max_retries=0 (when no retry occurs)
<p>
See following code :
<details>

```python
from celery import Celery
from tasks import demo

app = Celery('tasks', broker='redis://localhost:6379/1', backend='redis://localhost:6379/1')

r = demo.apply_async(("user", "password"), argsrepr="user:****", kwargs={"password":"secretvalue"}, kwargsrepr="password:****")
```

```python
from celery import Celery

app = Celery('tasks', broker='redis://localhost:6379/1', backend='redis://localhost:6379/1')

@app.task(bind=True, default_retry_delay=1)
def demo(self, *args, **kwargs):
    print("Enter task")
    print(self.request.args)
    print(self.request.argsrepr)
    print(self.request.kwargs)
    print(self.request.kwargsrepr)
    raise self.retry(max_retries=1)
```

</p>
</details>

# Expected Behavior

All retries context should contain argsrepr and kwargsrepr values. Exception should report repr values also
```
[2020-05-12 23:10:18,349: WARNING/ForkPoolWorker-2] Enter task
[2020-05-12 23:10:18,352: WARNING/ForkPoolWorker-2] ['user', 'password']
[2020-05-12 23:10:18,353: WARNING/ForkPoolWorker-2] user:****
[2020-05-12 23:10:18,354: WARNING/ForkPoolWorker-2] {'password': 'secretvalue'}
[2020-05-12 23:10:18,355: WARNING/ForkPoolWorker-2] password:****
[2020-05-12 23:10:19,704: WARNING/ForkPoolWorker-2] Enter task
[2020-05-12 23:10:19,705: WARNING/ForkPoolWorker-2] ['user', 'password']
[2020-05-12 23:10:19,706: WARNING/ForkPoolWorker-2] user:****
[2020-05-12 23:10:19,710: WARNING/ForkPoolWorker-2] {'password': 'secretvalue'}
[2020-05-12 23:10:19,712: WARNING/ForkPoolWorker-2] password:****
[2020-05-12 23:10:19,721: ERROR/ForkPoolWorker-2] Task tasks.demo[97f47a98-f12a-4745-864e-deb99b9d5ab5] raised unexpected: MaxRetriesExceededError("Can't retry tasks.demo[97f47a98-f12a-4745-864e-deb99b9d5ab5] args:'user:****' kwargs:'password:****'
Traceback (most recent call last):
  File "/Users/20010116/.pyenv/versions/3.6.10/envs/venv-test-flaskit-new/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/20010116/.pyenv/versions/3.6.10/envs/venv-test-flaskit-new/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/20010116/Documents/Workspace/beapi--flaskit-snow-demo/tasks.py", line 12, in demo
    raise self.retry(max_retries=1)
  File "/Users/20010116/.pyenv/versions/3.6.10/envs/venv-test-flaskit-new/lib/python3.6/site-packages/celery/app/task.py", line 708, in retry
    ), task_args=S.args, task_kwargs=S.kwargs
celery.exceptions.MaxRetriesExceededError: Can't retry tasks.demo[97f47a98-f12a-4745-864e-deb99b9d5ab5] args:'user:****' kwargs:'password:****'
```

# Actual Behavior

Only first task execution contain repr value. context of retry execution does not contain repr values any more. Exception dump full args and kwargs, so sensitive values are disclosed
```
[2020-05-12 23:10:18,349: WARNING/ForkPoolWorker-2] Enter task
[2020-05-12 23:10:18,352: WARNING/ForkPoolWorker-2] ['user', 'password']
[2020-05-12 23:10:18,353: WARNING/ForkPoolWorker-2] user:****
[2020-05-12 23:10:18,354: WARNING/ForkPoolWorker-2] {'password': 'secretvalue'}
[2020-05-12 23:10:18,355: WARNING/ForkPoolWorker-2] password:****
[2020-05-12 23:10:19,704: WARNING/ForkPoolWorker-2] Enter task
[2020-05-12 23:10:19,705: WARNING/ForkPoolWorker-2] ['user', 'password']
[2020-05-12 23:10:19,706: WARNING/ForkPoolWorker-2] ('user', 'password')
[2020-05-12 23:10:19,710: WARNING/ForkPoolWorker-2] {'password': 'secretvalue'}
[2020-05-12 23:10:19,712: WARNING/ForkPoolWorker-2] {'password': 'secretvalue'}
[2020-05-12 23:10:19,721: ERROR/ForkPoolWorker-2] Task tasks.demo[97f47a98-f12a-4745-864e-deb99b9d5ab5] raised unexpected: MaxRetriesExceededError("Can't retry tasks.demo[97f47a98-f12a-4745-864e-deb99b9d5ab5] args:('user', 'password') kwargs:{'password': 'secretvalue'}",)
Traceback (most recent call last):
  File "/Users/20010116/.pyenv/versions/3.6.10/envs/venv-test-flaskit-new/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/20010116/.pyenv/versions/3.6.10/envs/venv-test-flaskit-new/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/20010116/Documents/Workspace/beapi--flaskit-snow-demo/tasks.py", line 12, in demo
    raise self.retry(max_retries=1)
  File "/Users/20010116/.pyenv/versions/3.6.10/envs/venv-test-flaskit-new/lib/python3.6/site-packages/celery/app/task.py", line 708, in retry
    ), task_args=S.args, task_kwargs=S.kwargs
celery.exceptions.MaxRetriesExceededError: Can't retry tasks.demo[97f47a98-f12a-4745-864e-deb99b9d5ab5] args:('user', 'password') kwargs:{'password': 'secretvalue'}
```

**Comment by auvipy** [comment]
celery.exceptions.MaxRetriesExceededError: Can't retry tasks.demo[97f47a98-f12a-4745-864e-deb99b9d5ab5] args:('user', 'password') kwargs:{'password': 'secretvalue'}

you should check your could and celery doc

**Comment by llicour** [comment]
Hello. I don't understand why you closed this issue. Your comment is a bit confuse for me. You consider there is no problem ?

**Comment by ondrejkolafa** [comment]
Hi,
I'm here with the same problem as llicour. Is it solved? Or are we doing something wrong?
