### ISSUE TITLE
[Backend RabbitMQ] AsyncResult is never resolved for task links

### ISSUE THREAD

**Issue by Abam** [celery/celery#6107]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

4.4.2 (cliffs)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.2 (cliffs) kombu:4.6.8 py:3.8.2
            billiard:3.6.3.0 py-amqp:2.5.2
platform -> system:Linux arch:64bit
            kernel version:4.4.0-174-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:rpc:///

broker_url: 'amqp://test-celery:********@rabbitmq:5672//'
enable_utc: True
result_backend: 'rpc:///'
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.5.2
billiard==3.6.3.0
celery==4.4.2
kombu==4.6.8
pytz==2019.3
vine==1.3.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
Docker image python:3.8-slim,   id: a6d5c14af13b
</p>
<p>
Docker image rabbitmq:3.8.3,  id: cf7986a5b16f
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery

app = Celery('tasks')

app.config_from_object('celeryconfig')

@app.task
def add(x, y):
    return x + y

@app.task
def mul(x, y):
    return x * y
```

```python
broker_url = 'pyamqp://test-celery:test-celery@rabbitmq/'
result_backend = 'rpc://'
enable_utc = True
```

```python
broker_url = 'pyamqp://test-celery:test-celery@rabbitmq/'
result_backend = 'rpc://'
enable_utc = True
```

Tests in an interactive shell
```bash
Python 3.8.2 (default, Apr 16 2020, 18:36:10) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tasks import add
>>> result = add.apply_async((4,16), link=add.s(80))
>>> result.get()
20
>>> result.children[0]
<AsyncResult: 34c1fb0b-6145-4d05-b0c1-6fcd575cb1f8>
>>> result.children[0].get()
--> Hang here forever <--
```
</p>
</details>

# Expected Behavior

result.children[0].get() should return 100.

# Actual Behavior

result.children[0].get() never return value. Linked task is treated  by the worker but the result cannot be fetched. 

<details>
<summary><b><code>When Ctrl+C is hit:</code> Output:</b></summary>
<p>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/celery/result.py", line 221, in get
    return self.backend.wait_for_pending(
  File "/usr/local/lib/python3.8/site-packages/celery/backends/asynchronous.py", line 200, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/celery/backends/asynchronous.py", line 266, in _wait_for_pending
    for _ in self.drain_events_until(
  File "/usr/local/lib/python3.8/site-packages/celery/backends/asynchronous.py", line 55, in drain_events_until
    yield self.wait_for(p, wait, timeout=interval)
  File "/usr/local/lib/python3.8/site-packages/celery/backends/asynchronous.py", line 64, in wait_for
    wait(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/celery/backends/rpc.py", line 63, in drain_events
    return self._connection.drain_events(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 323, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
    return connection.drain_events(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 505, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 510, in blocking_read
    frame = self.transport.read_frame()
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 252, in read_frame
    frame_header = read(7, True)
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 438, in _read
    s = recv(n - len(rbuf))
KeyboardInterrupt
```
</p>
</details>

With the same configuration, when chain is used, all results can be fetched.

```bash
>>> from tasks import add
>>> from celery import chain
>>> result = chain(add.s(6,14), add.s(80))()
>>> result.get()
100
>>> result.parent.get()
20
```

**Comment by auvipy** [comment]
thanks for the report. can you come with PR?

**Comment by Abam** [comment]
No. Sorry, I did not manage to identify where the code is biggy.

**Comment by Abam** [comment]
No update ?

**Comment by auvipy** [comment]
avoid rpc backend

**Comment by Abam** [comment]
Is rpc backend deprecated ?
