### ISSUE TITLE
consumer: Connection to broker lost. Trying to re-establish the connection...

### ISSUE THREAD

**Issue by girijesh97** [celery/celery#6110]
Hi,
I am using celery with my Django Application and I am facing connection error while executing a task for a longer time (approximately 10-15 mins). Though the connection is not getting broken for a shorter process.  Error log 

```
[2020-05-19 08:33:35,254: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 494, in channel
    return self.channels[channel_id]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 40, in start
    self.sync(c)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 44, in sync
    replies = self.send_hello(c)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 57, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/app/control.py", line 154, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/app/control.py", line 106, in _request
    pattern=self.pattern, matcher=self.matcher,
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/app/control.py", line 480, in broadcast
    limit, callback, channel=channel,
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/pidbox.py", line 333, in _broadcast
    chan = channel or self.connection.default_channel
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/connection.py", line 870, in default_channel
    self._default_channel = self.channel()
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/connection.py", line 288, in channel
    chan = self.transport.create_channel(self.connection)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 100, in create_channel
    return connection.channel()
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 497, in channel
    channel.open()
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/channel.py", line 435, in open
    spec.Channel.Open, 's', ('',), wait=spec.Channel.OpenOk,
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/abstract_channel.py", line 68, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 505, in drain_events
    while not self.blocking_read(timeout):
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 511, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/method_framing.py", line 79, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 518, in on_inbound_method
    method_sig, payload, content,
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/channel.py", line 1615, in _on_basic_deliver
    fun(msg)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/messaging.py", line 590, in receive
    [callback(body, message) for callback in callbacks]
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/messaging.py", line 590, in <listcomp>
    [callback(body, message) for callback in callbacks]
  File "/mnt/z/womble_backend/ml_app/TextAnalysis/tasks.py", line 85, in handle_message
    message.ack()
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/message.py", line 126, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/channel.py", line 1394, in basic_ack
    spec.Basic.Ack, argsig, (delivery_tag, multiple),
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/method_framing.py", line 172, in write_frame
    write(view[:offset])
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/transport.py", line 284, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
```
Although connection is getting restablished. I tried various methods to resolve the issue as it has been mentioned in other issue on this repo like setting `broker_hearbeat = None`, `amqp_task_result_expires = 30000` and running celery by using 
`celery -A MyApp worker -l info --without-heartbeat` but nothing work out for me.

I am stuck at this error for quite some time. Any help would be highly appreciated.

The version of the libraries I am using are as follows:

```
amqp==2.5.2
celery==4.4.2
Django==1.11.26
kombu==4.6.8
```

And, my complete setting is like this

```
class Config:
    broker_url = 'amqp://user:aaaaaaaa@11.111.111.111:1111/'
    broker_pool_limit = None
    result_backend = "amqp"
    accept_content = ['json']
    task_serializer = 'json'
    result_serializer = 'json'
    amqp_task_result_expires = 30000
    # CELERY_TASK_TIME_LIMIT = 86400 #24 hours
    # CELERY_TASK_SOFT_TIME_LIMIT = 86400
    broker_connection_timeout=86400
    broker_hearbeat = None
    #CELERY_BROKER_CONNECTION_RETRY = False
```

**Comment by davidmir** [comment]
Why did you close this issue? This is still happening...

**Comment by girijesh97** [comment]
@davidmir It was resolved in my case.

**Comment by jardinetsouffleton** [comment]
I'm a little late at the party, but how did you manage to solve this issue @girijesh97? This is happening to me too....

**Comment by thedrow** [comment]
This is probably because the broker_heartbeat is set to `None`.
Try setting it and see what happens.

**Comment by AndreLobato** [comment]
@thedrow Thanks that fixed my problem too.

**Comment by thedrow** [comment]
I'm closing this issue. If you need more assistance, I'm here to help.

**Comment by DAAworld** [comment]
> This is probably because the broker_heartbeat is set to `None`. Try setting it and see what happens.

Hi,I also has same error.I close internet about 1 minutes and then reconnected. After that celery beat reconnected successfully，but celery worker raise this error。

redis==5.0.0
celery==5.3.4
kombu==5.3.2

Config:
    CELERYD_CONCURRENCY = 3  
    CELERYD_MAX_TASKS_PER_CHILD = 200
    CELERYD_FORCE_EXECV = True
    CELERYD_PREFETCH_MULTIPLIER = 1 
    
    BROKER_CONNECTION_MAX_RETRIES = 0
    CELERY_REDIS_RETRY_ON_TIMEOUT = True
    CELERY_REDIS_SOCKET_CONNECT_TIMEOUT = 5
    REDIS_BACKEND_HEALTH_CHECK_INTERVAL = 5
    
    BROKER_HEARTBEAT = 15
    BROKER_HEARTBEAT_CHECKRATE = 3

    CELERY_ACKS_LATE = False

Error:
[2023-10-25 17:22:12,954: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/connection.py", line 435, in send_packed_command
self._sock.sendall(item)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 340, in start
blueprint.start(self)
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
step.start(parent)
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 742, in start
c.loop(*c.loop_args())
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
next(loop)
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
cb(*cbargs)
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/transport/redis.py", line 1341, in on_readable
self.cycle.on_readable(fileno)
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/transport/redis.py", line 566, in on_readable
chan.handlers[type](https://github.com/celery/celery/issues/3932)
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/transport/redis.py", line 910, in _receive
ret.append(self._receive_one(c))
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/kombu/transport/redis.py", line 920, in _receive_one
response = c.parse_response()
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/client.py", line 786, in parse_response
self.check_health()
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/client.py", line 824, in check_health
conn.send_command("PING", self.HEALTH_CHECK_MESSAGE, check_health=False)
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/connection.py", line 457, in send_command
self.send_packed_command(
File "/home/ww/miniconda3/envs/sss/lib/python3.10/site-packages/redis/connection.py", line 446, in send_packed_command
raise ConnectionError(f"Error {errno} while writing to socket. {errmsg}.")
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.

**Comment by fcarucci** [comment]
Did you find the solution?

**Comment by GusarevKirill** [comment]
> Did you find the solution?

@fcarucci Just use RabbitMQ v3, not v4
