### ISSUE TITLE
celery worker with gevent cannot be Warm shutdown

### ISSUE THREAD

**Issue by ercJuL** [celery/celery#6111]
use gevnet, when SIGTERM shutdown will raise error

## mini demo
```bash
celery worker -P gevent
kill -15 xxx
```

## error output
```
 -------------- celery@DESKTOP-7R24JEG v4.4.2 (cliffs)
--- ***** -----
-- ******* ---- Linux-4.4.0-18362-Microsoft-x86_64-with-debian-bullseye-sid 2020-05-20 15:17:23
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         timburr:0x7f8c51059da0
- ** ---------- .> transport:   amqp://xxx:**@xxx/timburr_dev
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (gevent)
-- ******* ---- .> task events: ON
--- ***** -----
 -------------- [queues]
                .> timburr_medium   exchange=timburr_medium(direct) key=timburr_medium



worker: Warm shutdown (MainProcess)
[2020-05-20 15:17:32,150: WARNING/MainProcess] Received method (60, 31) during closing channel 2. This method will be ignored
[2020-05-20 15:17:32,832: ERROR/MainProcess] Error on stopping Control: AttributeError("'NoneType' object has no attribute 'drain_events'",)
Traceback (most recent call last):
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/worker/loops.py", line 113, in synloop
    connection.drain_events(timeout=2.0)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/kombu/connection.py", line 323, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
    return connection.drain_events(**kwargs)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/amqp/connection.py", line 505, in drain_events
    while not self.blocking_read(timeout):
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/amqp/connection.py", line 510, in blocking_read
    frame = self.transport.read_frame()
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/amqp/transport.py", line 252, in read_frame
    frame_header = read(7, True)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/amqp/transport.py", line 438, in _read
    s = recv(n - len(rbuf))
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/gevent/_socket3.py", line 382, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 284, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 289, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 280, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 281, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
celery.exceptions.WorkerShutdown: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/worker/pidbox.py", line 63, in stop
    self.consumer = self._close_channel(c)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/celery/worker/pidbox.py", line 71, in _close_channel
    ignore_errors(c, self.node.channel.close)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/kombu/common.py", line 323, in ignore_errors
    return fun(*args, **kwargs)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/amqp/channel.py", line 224, in close
    wait=spec.Channel.CloseOk,
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/amqp/abstract_channel.py", line 68, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/ercjul/.pyenv/versions/3.6.10/lib/python3.6/site-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'drain_events'
[2020-05-20 15:17:32,946: WARNING/MainProcess] Received method (60, 31) during closing channel 1. This method will be ignored
```

## env
python: 3.6.10 & 3.7.7
celery: 4.4.2
amqp: 2.5.2
kombu: 4.6.8
gevent:1.4.0 & 20.5.0

**Comment by auvipy** [comment]
gevent has some caveats, can you try eventlet?

**Comment by ercJuL** [comment]
yes, i try, it's same
```
 -------------- celery@python-timburrhigh-59bddf5b5d-wn4nx v4.4.2 (cliffs)
--- ***** -----
-- ******* ---- Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-debian-10.3 2020-05-20 09:06:18
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         timburr:0x7f5f07533310
- ** ---------- .> transport:   amqp://xxx:**@xxx/timburr_test
- ** ---------- .> results:     redis://:**@172.18.121.176:6379/9
- *** --- * --- .> concurrency: 1 (eventlet)
-- ******* ---- .> task events: ON
--- ***** -----
 -------------- [queues]
                .> timburr_medium   exchange=timburr_medium(direct) key=timburr_medium


[2020-05-20 09:06:20,102: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/kombu/pidbox.py:74: UserWarning: A node named celery@python-timburrhigh-59bddf5b5d-wn4nx is already using this process mailbox!

Maybe you forgot to shutdown the other node or did not do so properly?
Or if you meant to start multiple nodes on the same host please make sure
you give each node a unique node name!

  warnings.warn(W_PIDBOX_IN_USE.format(node=self))

worker: Warm shutdown (MainProcess)
[2020-05-20 09:06:55,154: ERROR/MainProcess] Error on stopping Control: AttributeError("'NoneType' object has no attribute 'drain_events'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 113, in synloop
    connection.drain_events(timeout=2.0)
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 323, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
    return connection.drain_events(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 505, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 510, in blocking_read
    frame = self.transport.read_frame()
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 252, in read_frame
    frame_header = read(7, True)
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 438, in _read
    s = recv(n - len(rbuf))
  File "/usr/local/lib/python3.7/site-packages/eventlet/greenio/base.py", line 366, in recv
    return self._recv_loop(self.fd.recv, b'', bufsize, flags)
  File "/usr/local/lib/python3.7/site-packages/eventlet/greenio/base.py", line 360, in _recv_loop
    self._read_trampoline()
  File "/usr/local/lib/python3.7/site-packages/eventlet/greenio/base.py", line 331, in _read_trampoline
    timeout_exc=socket_timeout('timed out'))
  File "/usr/local/lib/python3.7/site-packages/eventlet/greenio/base.py", line 210, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/usr/local/lib/python3.7/site-packages/eventlet/hubs/__init__.py", line 159, in trampoline
    return hub.switch()
  File "/usr/local/lib/python3.7/site-packages/eventlet/hubs/hub.py", line 298, in switch
    return self.greenlet.switch()
  File "/usr/local/lib/python3.7/site-packages/eventlet/hubs/hub.py", line 350, in run
    self.wait(sleep_time)
  File "/usr/local/lib/python3.7/site-packages/eventlet/hubs/poll.py", line 80, in wait
    presult = self.do_poll(seconds)
  File "/usr/local/lib/python3.7/site-packages/eventlet/hubs/epolls.py", line 31, in do_poll
    return self.poll.poll(seconds)
  File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 284, in _handle_request
    raise exc(exitcode)
celery.exceptions.WorkerShutdown: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/pidbox.py", line 63, in stop
    self.consumer = self._close_channel(c)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/pidbox.py", line 71, in _close_channel
    ignore_errors(c, self.node.channel.close)
  File "/usr/local/lib/python3.7/site-packages/kombu/common.py", line 323, in ignore_errors
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/amqp/channel.py", line 224, in close
    wait=spec.Channel.CloseOk,
  File "/usr/local/lib/python3.7/site-packages/amqp/abstract_channel.py", line 68, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/usr/local/lib/python3.7/site-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'drain_events'
[2020-05-20 09:06:55,163: WARNING/MainProcess] Received method (60, 31) during closing channel 2. This method will be ignored
```

**Comment by jheld** [comment]
Possibility that this happened from the threadpool executor code getting merged? Never used anything other than prefork pool (yet), but curious.

**Comment by silviuum** [comment]
Hello. Any updates for this bug? 

I'm using the gevent pool and everytime I terminate the queue from the terminal, neither Warm nor Cold shutdown finishes, so I have to restart the Redis server I use for it and then it finally closes with ConnectionError exception. It's a bit troublesome to do that every single time I change a task in my Flask application. Is there another workaround for this problem?
