### ISSUE TITLE
Warm shutdown kills task when using custom consumer and prefork pool

### ISSUE THREAD

**Issue by davidshepherd7** [celery/celery#6126]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.   -- I posted but my post doesn't seem to have appeared, maybe it needs to be approved by an admin or something?
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

Full reproduction here: https://github.com/davidshepherd7/celery-bug-repro

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.2 (cliffs)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
docker run -it david/celery-experiment celery -A tasks report
INFO:root:hello

software -> celery:4.4.2 (cliffs) kombu:4.6.8 py:3.7.7
            billiard:3.6.3.0 py-amqp:2.5.2
platform -> system:Linux arch:64bit
            kernel version:5.3.0-53-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:disabled

broker_url: 'amqp://guest:********@rabbit:5672//'
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
docker run -it david/celery-experiment pip freeze
amqp==2.5.2
billiard==3.6.3.0
celery @ git+https://github.com/celery/celery.git@8448eecd2b6009cb5cfaa95f7125f1a544b717c2
gevent==20.5.1
greenlet==0.4.15
importlib-metadata==1.6.0
kombu==4.6.8
pytz==2020.1
vine==1.3.0
zipp==3.1.0
zope.event==4.4
zope.interface==5.1.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

https://github.com/davidshepherd7/celery-bug-repro

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

The task in progress to be allowed to finish.

# Actual Behavior
The WorkerShutdown exception kills the task in progress.

```
celery    | [2020-05-28 17:21:50,909: INFO/MainProcess] mingle: all alone
celery    | [2020-05-28 17:21:50,948: INFO/MainProcess] celery@a9aa1fdd4ce9 ready.
celery    | [2020-05-28 17:21:54,138: INFO/MainProcess] got message: 2
celery    | 
celery    | worker: Warm shutdown (MainProcess)
celery    | [2020-05-28 17:21:55,257: ERROR/MainProcess] aborted
celery    | Traceback (most recent call last):
celery    |   File "/tasks.py", line 19, in on_message
celery    |     time.sleep(5)
celery    |   File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 284, in _handle_request
celery    |     raise exc(exitcode)
celery    | celery.exceptions.WorkerShutdown: 0
```

**Comment by auvipy** [comment]
can you send PR for this?

**Comment by davidshepherd7** [comment]
I don't think I understand the intended shutdown behaviour well enough to fix it without causig bugs in other areas.

I could remove the 'if multithreaded' statement so that it always shutsdown by setting a flag, but presumably the shutdown exception is needed sometimes? I don't know when those times are.
