### ISSUE TITLE
No module named 'future' after upgrading to 4.4.4

### ISSUE THREAD

**Issue by menecio** [celery/celery#6148]
This one is simple to reproduce, I just upgraded to `celery==4.4.4` and now my builds are broken.

```
[2020-06-03 09:48:39,517: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2020-06-03 09:48:39,518: DEBUG/MainProcess] | Worker: Building graph...
[2020-06-03 09:48:39,518: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Beat, Timer, Hub, Pool, Autoscaler, Consumer}
[2020-06-03 09:48:39,522: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2020-06-03 09:48:39,522: DEBUG/MainProcess] | Consumer: Building graph...
[2020-06-03 09:48:39,538: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Mingle, Gossip, Agent, Tasks, Control, event loop}
[2020-06-03 09:48:39,540: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'future'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 139, in on_start
    self.emit_banner()
  File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 154, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 217, in startup_info
    results=self.app.backend.as_uri(),
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 1232, in backend
    return self._get_backend()
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 949, in _get_backend
    self.loader)
  File "/usr/local/lib/python3.7/site-packages/celery/app/backends.py", line 74, in by_url
    return by_name(backend, loader), url
  File "/usr/local/lib/python3.7/site-packages/celery/app/backends.py", line 54, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 10, in <module>
    from future.utils import raise_with_traceback
ModuleNotFoundError: No module named 'future'
```

Running in a docker container using `python:3.7-alpine` as base image.

**Comment by solarissmoke** [comment]
Looks like this was fixed in https://github.com/celery/celery/pull/6146.

**Comment by menecio** [comment]
@solarissmoke I saw that commit and if you check v4.4.4's [commits](https://github.com/celery/celery/compare/v4.4.4...master) it's included, but still if you install `celery==4.4.4` from pypi it will crash with this error.

**Comment by solarissmoke** [comment]
You are reading the diff wrong - this commit is _not_ part of the 4.4.4 release, hence why it's appearing in the diff. See the commit history here: https://github.com/celery/celery/commits/master

**Comment by menecio** [comment]
@solarissmoke how am I reading it wrong when it's github pointing out that the release has 2 commits and when you compare the release vs. master branch it clearly shows those 2 commits?

Maybe is it that github release is not matching pypi release? What a effing mess

**Comment by auvipy** [comment]
fixed on master expect another minor release ver very soon.
