### ISSUE TITLE
ModuleNotFoundError: No module named 'future' in 4.4.4

### ISSUE THREAD

**Issue by rmk135** [celery/celery#6153]
Guys, version `4.4.4` doesn't work on Python 3.8:

```
celery_1         | Traceback (most recent call last):
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 208, in start
celery_1         |     self.blueprint.start(self)
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 115, in start
celery_1         |     self.on_start()
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/apps/worker.py", line 139, in on_start
celery_1         |     self.emit_banner()
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/apps/worker.py", line 154, in emit_banner
celery_1         |     ' \n', self.startup_info(artlines=not use_image))),
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/apps/worker.py", line 217, in startup_info
celery_1         |     results=self.app.backend.as_uri(),
celery_1         |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/objects.py", line 44, in __get__
celery_1         |     value = obj.__dict__[self.__name__] = self.__get(obj)
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 1232, in backend
celery_1         |     return self._get_backend()
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 947, in _get_backend
celery_1         |     backend, url = backends.by_url(
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/app/backends.py", line 74, in by_url
celery_1         |     return by_name(backend, loader), url
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/app/backends.py", line 54, in by_name
celery_1         |     cls = symbol_by_name(backend, aliases)
celery_1         |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
celery_1         |     module = imp(module_name, package=package, **kwargs)
celery_1         |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
celery_1         |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1         |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
celery_1         |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
celery_1         |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
celery_1         |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
celery_1         |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
celery_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celery_1         |   File "/usr/local/lib/python3.8/site-packages/django_celery_results/backends/__init__.py", line 3, in <module>
celery_1         |     from .cache import CacheBackend
celery_1         |   File "/usr/local/lib/python3.8/site-packages/django_celery_results/backends/cache.py", line 6, in <module>
celery_1         |     from celery.backends.base import KeyValueStoreBackend
celery_1         |   File "/usr/local/lib/python3.8/site-packages/celery/backends/base.py", line 10, in <module>
celery_1         |     from future.utils import raise_with_traceback
celery_1         | ModuleNotFoundError: No module named 'future'
```

PS: Apologies for not following your bug report pattern.

**Comment by nemesisdesign** [comment]
Happens to us as well in @openwisp.

Moreover, even if future is installed, we started getting build failures related to celery since 4.4.3, I tested 4.4.4 as well. More on this shortly.

**Comment by ErikKalkoken** [comment]
We are getting this issue too. Looks like a missing dependency for pip. 
Manually pip installing future seams to fix the issue for us.

**Comment by austinbutler** [comment]
Seems it's fixed in master but no release yet.

https://github.com/celery/celery/issues/6145
https://github.com/celery/celery/issues/6148

**Comment by auvipy** [comment]
please manually install future before the next point release.

**Comment by robvdl** [comment]
hang on why should we manually install future, this should be a dependency of celery, we shouldn't need to add it to our projects

**Comment by nedbat** [comment]
Is there something we can do to help get out 4.4.5? This is going to continue to cause trouble for people.

**Comment by auvipy** [comment]
> Is there something we can do to help get out 4.4.5? This is going to continue to cause trouble for people.

I'm releasing a point today for sure sir

**Comment by gentleKun** [comment]
Manully install 'future' package fixs.

**Comment by adampl** [comment]
> I'm releasing a point today for sure sir

@auvipy are you sure? ;)

**Comment by auvipy** [comment]
> > I'm releasing a point today for sure sir
> 
> @auvipy are you sure? ;)

https://github.com/celery/celery/releases/tag/v4.4.5 and please feel free to donate for celery on opencollective or convince your employer to buy tidelift subscription for celery.
