### ISSUE TITLE
Celery 4.4.4 raises => ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by pjulian** [celery/celery#6159]
This doesn't happen on 4.4.3, only on 4.4.4.

Here is a traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 569, in apply_async
    **options
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 779, in send_task
    self.backend.on_task_call(P, task_id)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 1232, in backend
    return self._get_backend()
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 949, in _get_backend
    self.loader)
  File "/usr/local/lib/python3.7/site-packages/celery/app/backends.py", line 74, in by_url
    return by_name(backend, loader), url
  File "/usr/local/lib/python3.7/site-packages/celery/app/backends.py", line 54, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 10, in <module>
    from future.utils import raise_with_traceback
ModuleNotFoundError: No module named 'future'
```

I'm running Python 3.7.4 on Debian v9.
```
root@6b09806573e5:/app# cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

root@6b09806573e5:/app# python --version
Python 3.7.4

```

# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
root@6b09806573e5:/app# pip freeze
amqp==2.6.0
bcrypt==3.1.7
beautifulsoup4==4.7.1
billiard==3.6.3.0
bleach==3.1.0
blinker==1.4
celery==4.4.4
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
Click==7.0
cryptography==2.9.2
CvLib==3.3.7
decorator==4.4.2
docker==4.1.0
Flask==1.1.1
Flask-APIBlueprint==1.0.0
Flask-Limiter==1.0.1
Flask-SQLAlchemy==2.3.2
flask-swagger==0.2.13
html5lib==1.0.1
idna==2.8
importlib-metadata==1.6.0
itsdangerous==1.1.0
Jinja2==2.10.1
kombu==4.6.10
limits==1.5.1
MarkupSafe==1.1.1
marshmallow==3.0.0b2
mysqlclient==1.4.6
paramiko==2.4.1
pbr==5.4.5
py==1.8.1
pyasn1==0.4.8
pycparser==2.20
pymssql==2.1.4
PyNaCl==1.4.0
python-dateutil==2.8.0
pytz==2017.2
PyYAML==5.3.1
requests==2.21.0
retry==0.9.2
six==1.15.0
soupsieve==2.0.1
SQLAlchemy==1.2.18
sshtunnel==0.1.5
urllib3==1.24.3
uWSGI==2.0.18
vine==1.3.0
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==0.16.0
zipp==3.1.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

**Comment by pjulian** [comment]
I guess I missed this earlier (I looked, really ;-) ).  This was already reported and being addressed in https://github.com/celery/celery/issues/6153.
