### ISSUE TITLE
chord_unlock on_error tries to write in DB

### ISSUE THREAD

**Issue by Ixiodor** [celery/celery#6160]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.4

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>
Nothing to report in that example, but in my real case i get :
```
[2020-06-05 10:29:15,418: ERROR/ForkPoolWorker-1] Task celery.chord_unlock[7af39ada-5e89-4150-a6d8-64311eb7ed02] raised unexpected: IntegrityError('null value in column "task_id" violates not-null constraint\nDETAIL: Failing row contains (217, null, FAILURE, application/x-python-serialize, binary, gAJjY2VsZXJ5LmV4Y2VwdGlvbnMKQ2hvcmRFcnJvcgpxAFgRAAAARXhjZXB0aW9u..., 2020-06-05 10:29:15.265746+00, Traceback (most recent call last):\n File "/home/ubuntu/.local/l..., gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJYJAAAAGI4YTk2YjM1LWYxMjAtNGE2MS1i..., null, null, null, null, 2020-06-05 10:29:15.265709+00).\n')

Traceback (most recent call last):
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/app/builtins.py", line 83, in unlock_chord
propagate=True,
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/result.py", line 772, in join
disable_sync_subtasks=disable_sync_subtasks,
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/result.py", line 217, in get
self.maybe_throw(callback=callback)
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/result.py", line 333, in maybe_throw
self.throw(value, self._to_remote_traceback(tb))
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/result.py", line 326, in throw
self.on_ready.throw(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.7/site-packages/vine/promises.py", line 244, in throw
reraise(type(exc), exc, tb)
File "/home/ubuntu/.local/lib/python3.7/site-packages/vine/five.py", line 195, in reraise
raise value
Exception: GONE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/query.py", line 559, in get_or_create
return self.get(**kwargs), False
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/query.py", line 417, in get
self.model._meta.object_name
django_celery_results.models.TaskResult.DoesNotExist: TaskResult matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "task_id" violates not-null constraint
DETAIL: Failing row contains (217, null, FAILURE, application/x-python-serialize, binary, gAJjY2VsZXJ5LmV4Y2VwdGlvbnMKQ2hvcmRFcnJvcgpxAFgRAAAARXhjZXB0aW9u..., 2020-06-05 10:29:15.265746+00, Traceback (most recent call last):
File "/home/ubuntu/.local/l..., gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJYJAAAAGI4YTk2YjM1LWYxMjAtNGE2MS1i..., null, null, null, null, 2020-06-05 10:29:15.265709+00).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
R = retval = fun(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in protected_call
return self.run(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/app/builtins.py", line 92, in unlock_chord
app.backend.chord_error_from_stack(callback, ChordError(reason))
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/backends/base.py", line 258, in chord_error_from_stack
return backend.fail_from_current_stack(callback.id, exc=exc)
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/backends/base.py", line 265, in fail_from_current_stack
self.mark_as_failure(task_id, exc, exception_info.traceback)
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/backends/base.py", line 169, in mark_as_failure
traceback=traceback, request=request)
File "/home/ubuntu/.local/lib/python3.7/site-packages/celery/backends/base.py", line 443, in store_result
request=request, **kwargs)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 40, in _store_result
using=using,
File "/home/ubuntu/.local/lib/python3.7/site-packages/django_celery_results/managers.py", line 52, in _inner
return fun(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django_celery_results/managers.py", line 138, in store_result
defaults=fields)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/query.py", line 562, in get_or_create
return self._create_object_from_params(kwargs, params)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/query.py", line 604, in _create_object_from_params
raise e
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/query.py", line 596, in _create_object_from_params
obj = self.create(**params)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/query.py", line 433, in create
obj.save(force_insert=True, using=self.db)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/base.py", line 746, in save
force_update=force_update, update_fields=update_fields)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/base.py", line 784, in save_base
force_update, using, update_fields,
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/base.py", line 887, in _save_table
results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/base.py", line 926, in _do_insert
using=using, raw=raw,
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
return query.get_compiler(using=using).execute_sql(returning_fields)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
cursor.execute(sql, params)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
return super().execute(sql, params)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
return self.cursor.execute(sql, params)
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/utils.py", line 90, in exit
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/home/ubuntu/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "task_id" violates not-null constraint
DETAIL: Failing row contains (217, null, FAILURE, application/x-python-serialize, binary, gAJjY2VsZXJ5LmV4Y2VwdGlvbnMKQ2hvcmRFcnJvcgpxAFgRAAAARXhjZXB0aW9u..., 2020-06-05 10:29:15.265746+00, Traceback (most recent call last):
File "/home/ubuntu/.local/l..., gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJYJAAAAGI4YTk2YjM1LWYxMjAtNGE2MS1i..., null, null, null, null, 2020-06-05 10:29:15.265709+00).
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
@app_cluster.task(bind=True)
def execute1(self):
    print("started")
    raise Exception("An error")
    print("ended")

@app_cluster.task(bind=True)
def error_handle(self):
    print("started error")
    print("ended error")

@app_cluster.task(bind=True, ignore_result=True)
def bridge(self):
    pass

class DummyTest(TestCase):

    def test_celery(self):
        sig = execute1.si()
        err = error_handle.si()

        chords = []
        chords.append(chord(sig, body=bridge.si(), immutable=True))
        item = chain(*chords).on_error(err)
        t = item.delay()
```

</p>
</details>

# Expected Behavior

In this schelton code, you will get the "father of all task" id written in DB and i think it shouldn't and in my real case code(too long and complex to share) i get the same thing but with a "null" task_id.

# Actual Behavior

Only "real tasks" written on DB.

**Comment by Ixiodor** [comment]
This is still an issue.
My example DB result:
```
8,5006ec5e-ee15-41af-9236-8e0335401c48,FAILURE,application/x-python-serialize,binary,gAJjY2VsZXJ5LmV4Y2VwdGlvbnMKQ2hvcmRFcnJvcgpxAFgzAAAARXhjZXB0aW9uKCdOb3RpZnkgZXhjZXB0aW9uOiBCYWQgc3RhdHVzIGNvZGU6IDQwNCcpcQGFcQJScQMu,2020-09-21 12:07:59.457132,"Traceback (most recent call last):
  File ""/usr/local/lib/python3.8/dist-packages/celery/app/builtins.py"", line 81, in unlock_chord
    ret = j(
  File ""/usr/local/lib/python3.8/dist-packages/celery/result.py"", line 778, in join
    value = result.get(
  File ""/usr/local/lib/python3.8/dist-packages/celery/result.py"", line 226, in get
    self.maybe_throw(callback=callback)
  File ""/usr/local/lib/python3.8/dist-packages/celery/result.py"", line 342, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File ""/usr/local/lib/python3.8/dist-packages/celery/result.py"", line 335, in throw
    self.on_ready.throw(*args, **kwargs)
  File ""/home/ubuntu/.local/lib/python3.8/site-packages/vine/promises.py"", line 244, in throw
    reraise(type(exc), exc, tb)
  File ""/home/ubuntu/.local/lib/python3.8/site-packages/vine/five.py"", line 195, in reraise
    raise value
celery.exceptions.ChordError: Exception('Notify exception: Bad status code: 404')
",gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJYJAAAAGM2YjkxZGY5LThlMDctNDhmNi1iOGM0LTNkNjQ4NmFhMjJhZXEDToZxBF1xBVgkAAAAOGMxY2Y0ODktMWYyZC00NTA3LWI5ZGMtNTg2ZmI1MzIwZTg0cQZOhnEHToZxCGGGcQlhcy4=,,,,,2020-09-21 12:07:59.457111
```
Reported Exception is from a 'real task' that correctly failed but chord re raise that exception and write it in DB.
