### ISSUE TITLE
File "/home/emailv-completed/env/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 64, in wait_for

### ISSUE THREAD

**Issue by Hamza-Lachi** [celery/celery#6167]
I'm Using celery in my Django project

but I get these issues when I deploy

```
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]: Traceback (most recent call last):
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:     self.run()
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:   File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:     self._target(*self._args, **self._kwargs)
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:   File "/home/emailv-completed/validator/views.py", line 1372, in ch
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:     for r in res1.collect():
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:   File "/home/emailv-completed/env/lib/python3.7/site-packages/celery/result.py", line 289, in collect
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:     yield R, R.get(**kwargs)
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:   File "/home/emailv-completed/env/lib/python3.7/site-packages/celery/result.py", line 228, in get
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:     on_message=on_message,
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:   File "/home/emailv-completed/env/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 200, in wait_for_pending
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:     for _ in self._wait_for_pending(result, **kwargs):
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:   File "/home/emailv-completed/env/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 268, in _wait_for_pending
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:     on_interval=on_interval):
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:   File "/home/emailv-completed/env/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 55, in drain_events_until
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:     yield self.wait_for(p, wait, timeout=interval)
Jun 14 04:17:01 hamza2.pawnhost.com gunicorn[24450]:   File "/home/emailv-completed/env/lib/python3.7/site-packages/celery/backends/asynchronous.py", line 64, in wait_for

```

I don't know why it's showing in gunicorn but it's celery issue

Version: celery==4.4.2,redis==3.2.1

Os: Ubuntu 16.0.4

Python Version: 3.7

I'm running celery as a daemon

**Comment by auvipy** [comment]
use a template and update your report.

**Comment by Hamza-Lachi** [comment]
what? please explain me
