### ISSUE TITLE
Possible backward incompatible changes in celery 4.4.3

### ISSUE THREAD

**Issue by shivamv300** [celery/celery#6176]
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [x] I have verified that the issue exists against the `master` branch of Celery.
* [x] I have included the contents of ``pip freeze`` in the issue.
* [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* None

#### Possible Duplicates
* None

## Environment & Settings

**Celery version**: 4.4.3 (cliffs) (seen in 4.4.4, 4.4.5 also)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
Traceback (most recent call last):
  File "venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "venv/lib/python3.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "venv/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "venv/lib/python3.7/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "venv/lib/python3.7/site-packages/celery/bin/base.py", line 289, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "venv/lib/python3.7/site-packages/celery/bin/base.py", line 509, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "venv/lib/python3.7/site-packages/celery/bin/base.py", line 531, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "venv/lib/python3.7/site-packages/celery/app/utils.py", line 373, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "venv/lib/python3.7/site-packages/celery/bin/base.py", line 534, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "venv/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "venv/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "Desktop/test/celery_test.py", line 46, in <module>
    print('OUTPUT = ', task.apply(args=(5, )).get())
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 808, in apply
    last and (last.get(),), **dict(self.options, **options))
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 1366, in apply
    args=(tasks.apply(args, kwargs).get(propagate=propagate),),
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 1113, in apply
    sig.apply(args=args, kwargs=kwargs, **options) for sig, _ in tasks
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 1113, in <listcomp>
    sig.apply(args=args, kwargs=kwargs, **options) for sig, _ in tasks
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 808, in apply
    last and (last.get(),), **dict(self.options, **options))
  File "venv/lib/python3.7/site-packages/celery/result.py", line 1034, in get
    self.result, Exception) else Exception(self.result)
  File "venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
TypeError: pass_args() missing 1 required positional argument: 'n'
```

</p>
</details>

# Steps to Reproduce
* upgrade to 4.4.3 from 4.4.2
* `celery -A proj`

## Required Dependencies

* **Minimal Python Version**: 3.7
* **Minimal Celery Version**: 4.4.3
* **Minimal Kombu Version**: 4.6.10
* **Minimal Broker Version**: redis 3.5.3
* **Minimal Result Backend Version**: redis 3.5.3
* **Minimal OS and/or Kernel Version**: 5.3.0-59-generic #53~18.04.1-Ubuntu
* **Minimal Broker Client Version**: redis-cli 4.0.9
* **Minimal Result Backend Client Version**: 

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

alembic==1.4.2
amqp==2.6.0
apispec==3.3.1
appdirs==1.4.4
attrs==19.3.0
autograd==1.3
autograd-gamma==0.4.2
Babel==2.8.0
backcall==0.1.0
bandit==1.6.2
billiard==3.6.3.0
celery==4.4.3
celery-redis-sentinel==0.3.0
certifi==2020.4.5.2
chardet==3.0.4
click==7.1.2
coverage==5.0.4
cycler==0.10.0
Cython==0.29.20
debtcollector==2.0.1
decorator==4.4.2
distlib==0.3.0
dlint==0.10.3
dogpile.cache==0.9.2
dparse==0.5.0
dulwich==0.20.2
dynaconf==2.2.3
entrypoints==0.3
filelock==3.0.12
findspark==1.3.0
flake8==3.7.9
flake8-bandit==2.1.2
flake8-broken-line==0.2.0
flake8-bugbear==20.1.4
flake8-builtins==1.5.2
flake8-comprehensions==3.2.2
flake8-import-order==0.18.1
flake8-mutable==1.2.0
flake8-polyfill==1.0.2
flake8-pytest==1.3
flake8-quotes==2.1.1
Flask==1.1.2
flask-apispec==0.9.0
Flask-Cors==3.0.8
flask-marshmallow==0.10.1
Flask-Migrate==2.5.3
flask-shell-ipython==0.4.1
Flask-SQLAlchemy==2.4.3
flask-talisman==0.7.0
flower==0.9.3
frozendict==1.2
fs==2.4.11
future==0.18.2
futurist==2.1.1
gitdb==4.0.2
GitPython==3.1.0
idna==2.9
importlib-metadata==1.6.1
ipdb==0.13.2
ipython==7.13.0
ipython-genutils==0.2.0
iso8601==0.1.12
itsdangerous==1.1.0
jedi==0.16.0
Jinja2==2.11.2
joblib==0.14.1
jsonschema==3.2.0
jupyter-core==4.6.3
kiwisolver==1.1.0
kombu==4.6.10
lifelines==0.24.2
Mako==1.1.3
MarkupSafe==1.1.1
marshmallow==3.6.1
marshmallow-sqlalchemy==0.23.1
matplotlib==3.2.0
mccabe==0.6.1
more-itertools==8.2.0
mysqlclient==1.4.6
nbformat==5.0.6
netaddr==0.7.19
netifaces==0.10.9
networkx==2.4
notifier==1.0.3
notifiers==1.2.1
numpy==1.17.4
oslo.i18n==4.0.1
oslo.utils==4.1.1
packaging==20.3
pandas==0.25.3
pandas-vet==0.2.2
parso==0.6.2
passlib==1.7.2
pbr==5.4.4
pep8-naming==0.9.1
pexpect==4.8.0
pickleshare==0.7.5
pip-tools==4.5.1
pipenv==2018.11.26
plotly==4.8.1
pluggy==0.13.1
prompt-toolkit==3.0.4
ptyprocess==0.6.0
py==1.8.1
pyasn1==0.4.8
pycodestyle==2.5.0
pyflakes==2.2.0
Pygments==2.6.1
pyjnius==1.3.0
pyparsing==2.4.6
pyrsistent==0.16.0
pytest==5.4.1
pytest-cov==2.8.1
pytest-env==0.6.2
pytest-flask==1.0.0
pytest-mock==2.0.0
python-box==3.4.6
python-dateutil==2.8.1
python-dotenv==0.13.0
python-editor==1.0.4
pytz==2020.1
PyYAML==5.3
redis==3.5.3
requests==2.23.0
retrying==1.3.3
rfc3987==1.3.8
rsa==4.2
safety==1.8.7
scikit-learn==0.22.2.post1
scipy==1.4.1
setuptools-scm==3.5.0
six==1.15.0
smmap==3.0.1
SQLAlchemy==1.3.17
stevedore==1.32.0
stringcase==1.2.0
swagger-parser==1.0.1
swagger-spec-validator==2.5.0
testfixtures==6.14.1
toml==0.10.1
tornado==5.1.1
traitlets==4.3.3
urllib3==1.25.9
vine==1.3.0
virtualenv==20.0.10
virtualenv-clone==0.5.3
wcwidth==0.1.8
webargs==5.5.3
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery, chain, chord, shared_task

CELERY_RESULT_BACKEND = 'redis://localhost'
CELERY_BROKER_URL = 'redis://localhost'

def create_celery_app():
    celery_app = Celery(
        'my-celery-app',
        backend=CELERY_RESULT_BACKEND, broker=CELERY_BROKER_URL)
    celery_app.finalize()
    celery_app.set_current()
    celery_app.set_default()
    return celery_app


celery = create_celery_app()


@shared_task
def selection_task(res_list):
	return res_list[0]


@shared_task
def print_res(result):
	return result


@shared_task
def pass_args(n):
	return n + 1


@shared_task
def add(x, y):
	return x + y


def create_add_task():
	execs = chord([chain(pass_args.s(), add.s(10)), chain(pass_args.s(), add.s(10)), ], selection_task.s())
	execs = chain(*[execs, print_res.s()])
	return execs


task = create_add_task()
print('OUTPUT = ', task.apply(args=(5, )).get())

```

</p>
</details>

# Expected Behavior

I expected the output `OUTPUT =  16`

# Actual Behavior

```
Traceback (most recent call last):
  File "venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "venv/lib/python3.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "venv/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "venv/lib/python3.7/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "venv/lib/python3.7/site-packages/celery/bin/base.py", line 289, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "venv/lib/python3.7/site-packages/celery/bin/base.py", line 509, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "venv/lib/python3.7/site-packages/celery/bin/base.py", line 531, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "venv/lib/python3.7/site-packages/celery/app/utils.py", line 373, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "venv/lib/python3.7/site-packages/celery/bin/base.py", line 534, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "venv/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "venv/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "Desktop/test/celery_test.py", line 46, in <module>
    print('OUTPUT = ', task.apply(args=(5, )).get())
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 808, in apply
    last and (last.get(),), **dict(self.options, **options))
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 1366, in apply
    args=(tasks.apply(args, kwargs).get(propagate=propagate),),
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 1113, in apply
    sig.apply(args=args, kwargs=kwargs, **options) for sig, _ in tasks
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 1113, in <listcomp>
    sig.apply(args=args, kwargs=kwargs, **options) for sig, _ in tasks
  File "venv/lib/python3.7/site-packages/celery/canvas.py", line 808, in apply
    last and (last.get(),), **dict(self.options, **options))
  File "venv/lib/python3.7/site-packages/celery/result.py", line 1034, in get
    self.result, Exception) else Exception(self.result)
  File "venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
TypeError: pass_args() missing 1 required positional argument: 'n'

```

**Comment by AbdealiJK** [comment]
A quick addition - I am having the same issue.

And I also get the same error for 4.4.3, 4.4.4, and 4.4.5.
I also tried it with the 4.4.6 released yesterday, and the error is still reproducible

**Comment by AbdealiJK** [comment]
Spent some time here, but I did not have enough expertise in celery to actually go through the issue and fix it :(

But I was able to create a small reproducible test case in the integration tests.
I thought having a xfail test case would be good, so that when someone is looking into the ticket, they have a easy to test example.

Added the test case in: https://github.com/celery/celery/pull/6187

**Comment by auvipy** [comment]
should be now fixed in main branch, as the integration test related to this issue is passing now
