### ISSUE TITLE
RabbitMQ failover not working in Celery > 4.2.2

### ISSUE THREAD

**Issue by rafalwytrykus** [celery/celery#6183]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

- Stop RabbitMQ node 

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.6.0
appdirs==1.4.4
attrs==19.3.0
billiard==3.6.3.0
black==19.10b0
CacheControl==0.12.6
cachy==0.3.0
celery==4.3.0
celery-stubs==0.1.1
certifi==2020.4.5.2
cffi==1.14.0
chardet==3.0.4
cleo==0.7.6
click==7.1.2
clikit==0.4.3
coverage==5.1
cryptography==2.9.2
fastapi==0.58.0
flake8==3.8.3
flake8-comprehensions==3.2.3
flake8-isort==2.9.1
flake8-polyfill==1.0.2
flake8-print==3.1.4
flake8-use-fstring==1.1
gunicorn==20.0.4
h11==0.9.0
html5lib==1.0.1
httptools==0.1.1
idna==2.9
isort==4.3.21
jeepney==0.4.3
jsonschema==3.2.0
keyring==20.0.1
kombu==4.6.10
lockfile==0.12.2
mccabe==0.6.1
more-itertools==8.4.0
msgpack==1.0.0
mypy==0.780
mypy-extensions==0.4.3
packaging==20.4
pastel==0.2.0
pathspec==0.8.0
pep8-naming==0.10.0
pexpect==4.8.0
pika==0.13.0
pkginfo==1.5.0.1
pluggy==0.13.1
poetry==1.0.9
ptyprocess==0.6.0
py==1.8.2
PyAMQP==0.1.0.7
pycodestyle==2.6.0
pycparser==2.20
pydantic==1.5.1
pyflakes==2.2.0
pylev==1.3.0
pyparsing==2.4.7
pyrsistent==0.14.11
pytest==5.4.3
pytest-cov==2.10.0
pytest-cover==3.0.0
pytest-coverage==0.0
pytz==2020.1
regex==2020.6.8
requests==2.24.0
requests-toolbelt==0.8.0
SecretStorage==3.1.2
shellingham==1.3.2
six==1.15.0
starlette==0.13.4
testfixtures==6.14.1
toml==0.10.1
tomlkit==0.5.11
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.9
uvicorn==0.11.5
uvloop==0.14.0
vine==1.3.0
wcwidth==0.2.4
webencodings==0.5.1
websockets==8.1
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Celery worker should failover to replica, this is what happens in 4.2.2:
```
ConnectionResetError: [Errno 104] Connection reset by peer
[2020-06-22 09:49:30,443: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@notifications-rabbitmq-rabbitmq-ha-1.notifications-rabbitmq-rabbitmq-ha-discovery.default.svc.cluster.local:5672//: [Errno 111] Connection refused.
Will retry using next failover.

[2020-06-22 09:49:30,456: INFO/MainProcess] Connected to amqp://guest:**@notifications-rabbitmq-rabbitmq-ha-0.notifications-rabbitmq-rabbitmq-ha-discovery.default.svc.cluster.local:5672//
```

# Actual Behavior

Celery worker is crashing:
```
[2020-06-22 09:57:28,652: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.8/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/usr/local/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/base.py", line 238, in on_readable
    reader(loop)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/base.py", line 220, in _read
    drain_events(timeout=0)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.8/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 520, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 649, in _on_close
    self._x_close_ok()
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 664, in _x_close_ok
    self.send_method(spec.Connection.CloseOk, callback=self._on_close_ok)
  File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 59, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.8/site-packages/amqp/method_framing.py", line 172, in write_frame
    write(view[:offset])
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 305, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
[2020-06-22 09:57:28,697: CRITICAL/MainProcess] Unrecoverable error: OperationalError('[Errno 111] Connection refused')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 137, in _connect
    entries = socket.getaddrinfo(
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 451, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 437, in _ensure_connection
    self._connection = self._connection or retry_over_time(
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 870, in _connection_factory
    connection = self._establish_connection()
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 806, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 314, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 78, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 146, in _connect
    raise (e
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 162, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/connection.py", line 23, in start
    c.connection = c.connect()
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 405, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 411, in connection_for_read
    return self.ensure_connected(
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 434, in ensure_connected
    conn = conn.ensure_connection(
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 388, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 443, in _ensure_connection
    return self._connection
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 455, in _reraise_as_library_errors
    reraise(ConnectionError, ConnectionError(text_t(exc)),
  File "/usr/local/lib/python3.8/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 451, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 437, in _ensure_connection
    self._connection = self._connection or retry_over_time(
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 870, in _connection_factory
    connection = self._establish_connection()
  File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 806, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 314, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 78, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 146, in _connect
    raise (e
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 162, in _connect
    self.sock.connect(sa)
kombu.exceptions.OperationalError: [Errno 111] Connection refused
```

**Comment by auvipy** [comment]
this should be fixed in kombu master.

**Comment by asfaltboy** [comment]
I just had the same issue while trying out multi-node connection string in celery. I tried the latest kombu and while I see a connection established to a "live node", celery worker still retries the first connections couple of times until it crashes.

So far, the only way I was able to overcome this was by using an HA Proxy before the rabbitmq nodes. Not sure if this got broken in a recent version, someone would have to do some (git) bisecting to find out

**Comment by thedrow** [comment]
We always welcome help.

**Comment by econeale** [comment]
Confirming that this issue is still present in 5.3.0b1.

**Comment by auvipy** [comment]
feel free to dig it deeper
