### ISSUE TITLE
定时任务无法启动

### ISSUE THREAD

**Issue by YXinAndy** [celery/celery#6194]
Traceback (most recent call last):
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/kombu/utils/__init__.py", line 323, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/billiard/process.py", line 292, in _bootstrap
    self.run()
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/celery/beat.py", line 553, in run
    self.service.start(embedded_process=True)
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/celery/beat.py", line 470, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/kombu/utils/__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/celery/beat.py", line 512, in scheduler
    return self.get_scheduler()
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/celery/beat.py", line 507, in get_scheduler
    lazy=lazy)
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/celery/utils/imports.py", line 53, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/celery/beat.py", line 358, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/celery/beat.py", line 185, in __init__
    self.setup_schedule()
  File "/data/mobi-admin-panel/venv/lib/python3.6/site-packages/celery/beat.py", line 388, in setup_schedule
    self._store['entries']
  File "/usr/local/lib/python3.6/shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
EOFError: Ran out of input

以上为错误日志，之前一直正常，今天忽然报这个错误，期间无更改

**Comment by thedrow** [comment]
We're sorry. We don't speak Chinese.

In any case, there's not enough information for us to help you resolve this bug.
Please fill the template we provided.
