### ISSUE TITLE
Have issue using celery with SQS when connection is being lost and recovered messages are not being served by celery.

### ISSUE THREAD

**Issue by aram2726** [celery/celery#6209]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have checked the 
[celery issues 3932](https://github.com/celery/celery/issues/3932/)
[kombu issue 931](https://github.com/celery/kombu/issues/931)
  for similar or identical bug reports.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

#### Related Issues

- https://github.com/celery/celery/issues/3932/
- https://github.com/celery/kombu/issues/931

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.2 (cliffs) kombu:4.6.11 py:3.7.6
            billiard:3.6.3.0 py-amqp:2.6.0
platform -> system:Linux arch:64bit
            kernel version:4.15.0-1065-aws imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7.6 imp: CPython
* **Minimal Celery Version**: 4.4.2
* **Minimal Kombu Version**: 4.6.11
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: GNU Linux Ubuntu x86_64 18.04 
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
aiohttp==3.6.2
amqp==2.6.0
argh==0.26.2
asgiref==3.2.10
async-timeout==3.0.1
attrs==19.3.0
billiard==3.6.3.0
boto3==1.12.39
botocore==1.15.49
celery==4.4.2
certifi==2020.6.20
chardet==3.0.4
ddtrace==0.37.0
Django==3.0.4
docutils==0.15.2
future==0.18.2
gunicorn==20.0.4
idna==2.10
jmespath==0.10.0
kombu==4.6.11
msgpack==1.0.0
multidict==4.7.6
pathtools==0.1.2
psycopg2-binary==2.8.4
python-dateutil==2.8.1
python-dotenv==0.12.0
pytz==2020.1
PyYAML==5.3.1
requests==2.23.0
s3transfer==0.3.3
setproctitle==1.1.10
six==1.15.0
slackclient==2.5.0
sqlparse==0.3.1
urllib3==1.25.9
vine==1.3.0
yarl==1.4.2
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
It depends. The issue is occurring when we will get a connection lost error.
```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

Got this in logs.
```
[2020-06-03 01:36:35,499: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/pyenv/versions/3.7.6/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/httpsession.py", line 263, in send
    chunked=self._chunked(request.headers),
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f910d7373d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 301, in create_loop
    item()
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/vine/promises.py", line 170, in __call__
    return self.throw()
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/vine/promises.py", line 167, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/kombu/transport/SQS.py", line 390, in _schedule_queue
    queue, callback=promise(self._loop1, (queue,)),
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/kombu/transport/SQS.py", line 406, in _get_bulk_async
    return self._get_async(queue, maxcount, callback=callback)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/kombu/transport/SQS.py", line 417, in _get_async
    callback=transform(self._on_messages_ready, callback, q, queue),
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/kombu/transport/SQS.py", line 442, in _get_from_sqs
    queue_url = connection.get_queue_url(queue)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/kombu/asynchronous/aws/sqs/connection.py", line 45, in get_queue_url
    res = self.sqs_connection.get_queue_url(QueueName=queue)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/ddtrace/contrib/botocore/patch.py", line 70, in patched_api_call
    result = original_func(*args, **kwargs)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/client.py", line 613, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/client.py", line 632, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/home/$USER/.local/share/virtualenvs/$PROJECT_NAME-zlr2NI-5/lib/python3.7/site-packages/botocore/httpsession.py", line 283, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://queue.amazonaws.com/"
[2020-06-03 01:36:47,080: ERROR/MainProcess] consumer: Cannot connect to sqs://localhost//: Could not connect to the endpoint URL: "https://queue.amazonaws.com/".
Trying again in 2.00 seconds... (1/100)

[2020-06-03 01:36:57,674: INFO/MainProcess] Connected to sqs://localhost//

```
And after the last line logs are empty because celery stops handling any message.

**Comment by thedrow** [comment]
@aram2726 Why did you close this bug report?

**Comment by aram2726** [comment]
@thedrow 
I've opened two issues by mistake instead of one after I've closed this one.
And this is the open issue.
https://github.com/celery/celery/issues/6210
