### ISSUE TITLE
Installing couchbase on celery's ubuntu:focal based Docker image no longer works

### ISSUE THREAD

**Issue by maybe-sybr** [celery/celery#6227]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce
```
~/celery $ docker build -f docker/Dockerfile .
```

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
Not applicable
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

The docker image should build without error.

# Actual Behavior

The image fails to build due to a dependency versioning issue with couchbase.

```
$ podman build -t celery -f docker/Dockerfile .
STEP 1: FROM ubuntu:focal
STEP 2: ENV PYTHONIOENCODING UTF-8
--> Using cache acaba7be84835036fb85e90b837986d94871823c68921aca8b9bc6858f7eede6
STEP 3: ARG DEBIAN_FRONTEND=noninteractive
--> Using cache f53b7bd5d6f45cd40239c7d083c268db8b62e826a8018a47c32d96c8e439952f
STEP 4: RUN apt-get update && apt-get install -y build-essential     libcurl4-openssl-dev     libffi-dev     tk-dev     xz-utils     curl     lsb-release     git     libmemcached-dev     make     liblzma-dev     libreadline-dev     libbz2-dev     llvm     libncurses5-dev     libsqlite3-dev     wget     pypy     python-openssl     libncursesw5-dev     zlib1g-dev     pkg-config     libssl-dev     sudo
--> Using cache 3528dd3a7bde42f48e3f792b717ce95ad3bcc1d169b2d676abf20faaa2eaaacc
STEP 5: ENV PROVISIONING /provisioning
--> Using cache 5cd403e630187ed510ed7aa5c1a7279b2e169e77a35a17dacaf82a49bbc8ce7c
STEP 6: ARG CELERY_USER=developer
--> Using cache faa9faee390dded0bab0e78ebca4b9075b19f05a50bc055bb77f88efbd64682f
STEP 7: RUN : "${CELERY_USER:?CELERY_USER build argument needs to be set and non-empty.}"
--> Using cache 43389d0aac47abf3b16a5af3689c5371180a6b3950841c179a2569affffed4eb
STEP 8: ENV HOME /home/$CELERY_USER
--> Using cache ec0be7e288094b41313bd80d5ea9df3fbb44b99cd8a7299f5a4b21a4d7932b39
STEP 9: ENV PATH="$HOME/.pyenv/bin:$PATH"
--> Using cache e7239a2d2c12e00bfabaec790d0c1937690095b55c3473b80a13c3afbd9a0333
STEP 10: WORKDIR $PROVISIONING
--> Using cache f0f43f30b813e023ba7a9edb2fdef8761187b529deb69f4e131d207665a8016b
STEP 11: COPY docker/scripts/install-couchbase.sh .
--> Using cache 86faecc53eba42812d4ac16e7498707e855e93030de83e14230f5da13391ca4f
STEP 12: RUN sh install-couchbase.sh
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
--2020-07-14 01:15:18--  http://packages.couchbase.com/ubuntu/couchbase.key
Resolving packages.couchbase.com (packages.couchbase.com)... 143.204.83.79, 143.204.83.24, 143.204.83.78, ...
Connecting to packages.couchbase.com (packages.couchbase.com)|143.204.83.79|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4815 (4.7K) [application/pgp-keys]
Saving to: 'STDOUT'

-                                 100%[=============================================================>]   4.70K  --.-KB/s    in 0s

2020-07-14 01:15:19 (57.3 MB/s) - written to stdout [4815/4815]

OK
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
deb http://packages.couchbase.com/ubuntu bionic bionic/main
Get:1 http://packages.couchbase.com/ubuntu bionic InRelease [2992 B]
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Get:4 http://packages.couchbase.com/ubuntu bionic/bionic/main amd64 Packages [1419 B]
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 4411 B in 2s (2570 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.8ubuntu1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcouchbase2-bin : Depends: libcouchbase2-libevent (= 2.10.6-1) but it is not going to be installed
                     Depends: libevent-core-2.1-6 (>= 2.1.8-stable) but it is not installable
E: Unable to correct problems, you have held broken packages.
Error: error building at STEP "RUN sh install-couchbase.sh": error while running runtime: exit status 100
```

The dockerfile was originally changed to be based on focal in 8246f3a91, but it's likely that a more recent change in the Couchbase bionic package repo or the Ubuntu focal repos is what causes the breakage. Changing the docker image to be based on bionic again allows the image to build again.

**Comment by maybe-sybr** [comment]
I should point out that I'm using podman (per the output I copied under actual behaviour) but that shouldn't make a different AFAIK

**Comment by maybe-sybr** [comment]
Actually, changing the base image back to `bionic` failed when trying to install the `couchbase` Python package:

```
...
Collecting couchbase<3.0.0
  Using cached couchbase-2.5.12.tar.gz (665 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/developer/.pyenv/versions/python3.6/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-attw80li/couchbase/setup.py'"'"'; __file__='"'"'/tmp/pip-install-attw80li/couchbase/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gwqx89jd
         cwd: /tmp/pip-install-attw80li/couchbase/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /home/developer/.pyenv/versions/python3.6/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-_tz3wd9p/typing/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-_tz3wd9p/typing/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gbnmjqhh
           cwd: /tmp/pip-wheel-_tz3wd9p/typing/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for typing
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/developer/.pyenv/versions/python3.6/bin/python3.6', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpvavyptki', '--quiet', 'typing']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-attw80li/couchbase/setup.py", line 245, in <module>
        **setup_kw
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/setuptools/dist.py", line 702, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
        replace_conflicting=replace_conflicting
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/developer/.pyenv/versions/python3.6/lib/python3.6/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/developer/.pyenv/versions/python3.6/bin/python3.6', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpvavyptki', '--quiet', 'typing']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: error building at STEP "RUN pyenv exec python3.8 -m pip install   -r requirements/dev.txt   -r requirements/test.txt   -r requirements/test-ci-default.txt   -r requirements/docs.txt   -r requirements/test-integration.txt   -r requirements/pkgutils.txt &&   pyenv exec python3.7 -m pip install   -r requirements/dev.txt   -r requirements/test.txt   -r requirements/test-ci-default.txt   -r requirements/docs.txt   -r requirements/test-integration.txt   -r requirements/pkgutils.txt &&   pyenv exec python3.6 -m pip install   -r requirements/dev.txt   -r requirements/test.txt   -r requirements/test-ci-default.txt   -r requirements/docs.txt   -r requirements/test-integration.txt   -r requirements/pkgutils.txt &&   pyenv exec python3.5 -m pip install   -r requirements/dev.txt   -r requirements/test.txt   -r requirements/test-ci-default.txt   -r requirements/docs.txt   -r requirements/test-integration.txt   -r requirements/pkgutils.txt &&   pyenv exec python2.7 -m pip install   -r requirements/dev.txt   -r requirements/test.txt   -r requirements/test-ci-default.txt   -r requirements/docs.txt   -r requirements/test-integration.txt   -r requirements/pkgutils.txt": error while running runtime: exit status 1
```

In lines above, it does look like `wheel` got installed in the Python3.8 environment, but perhaps the 3.6 environment didn't get it and that's why the couchbase install died?

**Comment by auvipy** [comment]
I would expect a PR for fixing it.

**Comment by maybe-sybr** [comment]
My main question prior to sending a PR would be how this hasn't broken in a CI or release process yet. That might shed some light on what needs to change if anything.

The change to base the image on focal happened in 8246f3a91 which is included in:
```
$ PAGER= sh -c 'git branch --contains=8246f3a91; git tag --contains=8246f3a91'
* (HEAD detached at origin/master)
  master
4.4.3
v4.4.4
v4.4.5
v4.4.6
```

Do you think we would have done any re-builds of the container image with this change, @auvipy ?

**Comment by auvipy** [comment]
thats for development docker for celery!

**Comment by maybe-sybr** [comment]
Okay, great. Definitely something I can look into fixing then. I'll spin up a PR when I have time over the next few days.

**Comment by thedrow** [comment]
> Okay, great. Definitely something I can look into fixing then. I'll spin up a PR when I have time over the next few days.

We don't build our Docker container on every build.
Maybe we should.
