### ISSUE TITLE
Workers crash when storing results of expired task in MongoDB result backend

### ISSUE THREAD

**Issue by jobi** [celery/celery#6238]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.6

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.6.0
celery==4.4.6
kombu==4.6.11
pymongo==3.6.1
redis==3.2.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
Python 3.7
MongoDB 3.6.12 (for result backend)
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>\

Using the Redis broker, MongoDB result backend, pickle serializers.

We don't yet have an exact test case but are seeing this on production. It appears that backup_cleanup tasks are expiring before they get a chance to run. When processing those, the celery workers exit having failed to serialize the result.

</p>
</details>

# Expected Behavior

Result for expired task is correctly reported in MongoDB result backend

# Actual Behavior

Celery worker exits with the following exception:

```
celery.worker worker:212 Unrecoverable error: EncodeError(InvalidDocument("Cannot encode object: TaskRevokedError('expired')"))
Traceback (most recent call last):
  File "/home/scout/.local/lib/python3.7/site-packages/celery/backends/mongodb.py", line 196, in _store_result
    self.collection.replace_one({'_id': task_id}, meta, upsert=True)
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/collection.py", line 908, in replace_one
    collation=collation, session=session),
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/collection.py", line 836, in _update_retryable
    _update, session)
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1102, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1079, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/collection.py", line 832, in _update
    retryable_write=retryable_write)
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/collection.py", line 797, in _update
    retryable_write=retryable_write).copy()
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/pool.py", line 522, in command
    self._raise_connection_failure(error)
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/pool.py", line 677, in _raise_connection_failure
    raise error
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/pool.py", line 517, in command
    collation=collation)
  File "/home/scout/.local/lib/python3.7/site-packages/pymongo/network.py", line 102, in command
    None, codec_options, check_keys)
bson.errors.InvalidDocument: Cannot encode object: TaskRevokedError('expired')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scout/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/home/scout/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/scout/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/scout/.local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/scout/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/scout/.local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/home/scout/.local/lib/python3.7/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/home/scout/.local/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/home/scout/.local/lib/python3.7/site-packages/kombu/transport/redis.py", line 1083, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/scout/.local/lib/python3.7/site-packages/kombu/transport/redis.py", line 354, in on_readable
    chan.handlers[type]()
  File "/home/scout/.local/lib/python3.7/site-packages/kombu/transport/redis.py", line 744, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/home/scout/.local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
  File "/home/scout/.local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 633, in _callback
    return callback(message)
  File "/home/scout/.local/lib/python3.7/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/scout/.local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 571, in on_task_received
    callbacks,
  File "/home/scout/.local/lib/python3.7/site-packages/celery/worker/strategy.py", line 158, in task_message_handler
    if (req.expires or req.id in revoked_tasks) and req.revoked():
  File "/home/scout/.local/lib/python3.7/site-packages/celery/worker/request.py", line 419, in revoked
    'expired' if expired else 'revoked', False, None, expired,
  File "/home/scout/.local/lib/python3.7/site-packages/celery/worker/request.py", line 402, in _announce_revoked
    store_result=self.store_errors,
  File "/home/scout/.local/lib/python3.7/site-packages/celery/backends/base.py", line 227, in mark_as_revoked
    traceback=None, request=request)
  File "/home/scout/.local/lib/python3.7/site-packages/celery/backends/base.py", line 443, in store_result
    request=request, **kwargs)
  File "/home/scout/.local/lib/python3.7/site-packages/celery/backends/mongodb.py", line 198, in _store_result
    raise EncodeError(exc)
kombu.exceptions.EncodeError: Cannot encode object: TaskRevokedError('expired')
```

**Comment by auvipy** [comment]
, in command
    None, codec_options, check_keys)
bson.errors.InvalidDocument: Cannot encode object: TaskRevokedError('expired')

During handling of the above exception, another exception occurred:

may be kombu can't encode bson?

**Comment by auvipy** [comment]
which version of pymongo you are using?

**Comment by jobi** [comment]
> which version of pymongo you are using?

pymongo==3.6.1

**Comment by jobi** [comment]
If I compare the mongo backend _store_result with the one in the base class, or the ones in some of the other backends, it looks like the mongo backend never calls encode() on either the result or the result metadata. Perhaps this is fine for regular results but fails for something that isn't directly handled by pymongo, such as a Python object.

For example:
https://github.com/celery/celery/blob/master/celery/backends/cassandra.py#L204
https://github.com/celery/celery/blob/master/celery/backends/base.py#L861

vs

https://github.com/celery/celery/blob/master/celery/backends/mongodb.py#L187-L200

(no call to encode())

**Comment by jobi** [comment]
The following attempts to reproduce the issue:

```python
# pip3 install celery==4.4.6 pytest==5.4.3 pymongo==3.6.1
# docker run -it -p 27017:27017 --rm mongo:3.6.12
# pytest -v
import time

from celery import shared_task
from celery.exceptions import TaskRevokedError
import pytest


@shared_task(bind=True)
def sleep_task(self, sleep_time=0):
    with open('/tmp/x.log', 'a') as fp:
        print(sleep_time, file=fp)
    time.sleep(sleep_time)
    return "I have wait %s sec." % sleep_time


@pytest.mark.celery(
    # result_backend="cache+memory:///",
    result_backend="mongodb",
    mongodb_backend_settings=dict(
        host='localhost',
        port='27017',
        database='pytest',
    ),
    broker_url="memory://",
    accept_content=['json', 'pickle'],
    # task_serializer="pickle",
    result_serializer="pickle",  # json works
)
def test_celery(celery_worker):
    from pathlib import Path
    Path('/tmp/x.log').unlink()

    sleep_task.apply_async(  # keep the worker busy so the next task expires
        kwargs={"sleep_time": 0.2},
    )
    r = sleep_task.apply_async(
        kwargs={"sleep_time": 0.1},
        expires=0.1,
    )
    with pytest.raises(TaskRevokedError):
        assert r.get(propagate=True) == "I have wait 0.1 sec."

```

Running with the `result_serializer` set to `pickle` hangs. Running with `json` succeeds

**Comment by thedrow** [comment]
How does the result look like in MongoDB when using JSON as a serializer?
