### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by wangguanfu** [celery/celery#6247]
File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\util\ssl_.py", line 276, in create_urllib3_context
    context.options |= options
  File "d:\work\anaconda3\envs\django3\lib\ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "d:\work\anaconda3\envs\django3\lib\ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "d:\work\anaconda3\envs\django3\lib\ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 110 more times]
  File "...", line -1, in [rest of traceback truncated]
RecursionError: maximum recursion depth exceeded while calling a Python object

when i start a  beat
celery                 4.4.6
Django                 2.0.4
requests

**Comment by wangguanfu** [comment]
Traceback (most recent call last):
  File "d:\work\anaconda3\envs\django3\lib\site-packages\celery\app\trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\celery\app\trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "D:\work\kangaroo_monitor\kangaroo_monitor_django\eciTask\notifyTask.py", line 47, in ncStatistics
    _baseSendMsg(content, 18510234326)
  File "D:\work\kangaroo_monitor\kangaroo_monitor_django\notifyHardler\DingDingHardler.py", line 47, in _baseSendMsg
    r = requests.post(uri, headers=headers, data=json.dumps(data))
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\connection.py", line 344, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\util\ssl_.py", line 276, in create_urllib3_context
    context.options |= options
  File "d:\work\anaconda3\envs\django3\lib\ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "d:\work\anaconda3\envs\django3\lib\ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "d:\work\anaconda3\envs\django3\lib\ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 110 more times]
  File "...", line -1, in [rest of traceback truncated]
RecursionError: maximum recursion depth exceeded while calling a Python object
[2020-07-28 12:28:13,895: ERROR/MainProcess] Task eciTask.notifyTask.ncStatistics[09fd3c3f-b52a-4225-bfc5-81d1c70c33c0] raised unexpected: RecursionError('maximum recursion depth excee
ded while calling a Python object')
Traceback (most recent call last):
  File "d:\work\anaconda3\envs\django3\lib\site-packages\celery\app\trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\celery\app\trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "D:\work\kangaroo_monitor\kangaroo_monitor_django\eciTask\notifyTask.py", line 47, in ncStatistics
    _baseSendMsg(content, 18510234326)
  File "D:\work\kangaroo_monitor\kangaroo_monitor_django\notifyHardler\DingDingHardler.py", line 47, in _baseSendMsg
    r = requests.post(uri, headers=headers, data=json.dumps(data))
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\connection.py", line 344, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "d:\work\anaconda3\envs\django3\lib\site-packages\urllib3\util\ssl_.py", line 276, in create_urllib3_context
    context.options |= options
  File "d:\work\anaconda3\envs\django3\lib\ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "d:\work\anaconda3\envs\django3\lib\ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "d:\work\anaconda3\envs\django3\lib\ssl.py", line 518, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 110 more times]
  File "...", line -1, in [rest of traceback truncated]
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by auvipy** [comment]
it is not sure it's your code or celery error. please edit the issue template with more detail and check your code thoroughly

**Comment by wangguanfu** [comment]
> it is not sure it's your code or celery error. please edit the issue template with more detail and check your code thoro


The code has been posted and the problem is still not well solved

**Comment by wangguanfu** [comment]
> it is not sure it's your code or celery error. please edit the issue template with more detail and check your code thoroughly

The code has been posted and the problem is still not well solved

**Comment by thedrow** [comment]
Please adhere to the guidelines when you create a new issue.
