### ISSUE TITLE
flask celery request   django celery request 

### ISSUE THREAD

**Issue by wangguanfu** [celery/celery#6248]
###What's the same code? Why do I use Django celery==4.4.0 request to make a false report 。on flask， and I can't report it wrong

[tasks]
  . eciTask.notifyTask.ncStatistics

[2020-07-28 16:09:09,350: INFO/MainProcess] Connected to redis://127.0.0.1:6379/5
[2020-07-28 16:09:09,356: INFO/MainProcess] mingle: searching for neighbors
[2020-07-28 16:09:10,402: INFO/MainProcess] mingle: all alone
[2020-07-28 16:09:10,415: WARNING/MainProcess] d:\work\anaconda3\envs\django3\lib\site-packages\celery\fixups\django.py:206: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  leak, never use this setting in production environments!''')
[2020-07-28 16:09:10,416: INFO/MainProcess] celery@D-C02200BD-1453 ready.
[2020-07-28 16:09:10,424: INFO/MainProcess] pidbox: Connected to redis://127.0.0.1:6379/5.
[2020-07-28 16:09:16,608: INFO/MainProcess] Received task: eciTask.notifyTask.ncStatistics[f2941166-747d-47e6-b13f-57d02f74977f]
[2020-07-28 16:09:16,951: WARNING/MainProcess] {'报警': ['192.168.1.196', '192.168.1.196', '192.168.1.196', '192.168.1.196', '192.168.1.196']}
[2020-07-28 16:09:26,443: INFO/MainProcess] Received task: eciTask.notifyTask.ncStatistics[d1cfad3c-0a00-4521-a791-8f2ae23caaa9]
[2020-07-28 16:09:26,647: WARNING/MainProcess] {'报警': ['192.168.1.196', '192.168.1.196', '192.168.1.196', '192.168.1.196', '192.168.1.196']}
[2020-07-28 16:09:27,275: ERROR/MainProcess] Task eciTask.notifyTask.ncStatistics[f2941166-747d-47e6-b13f-57d02f74977f] raised unexpected: gaierror(11002, 'Lookup timed out')
Traceback (most recent call last):
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 425, in resolve
    use_network=use_network)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 380, in query
    return end()
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 359, in end
    raise result[1]
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 340, in step
    a = fun(*args, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\dns\resolver.py", line 1091, in query
    True)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\dns\resolver.py", line 1043, in resolve
    timeout = self._compute_timeout(start, lifetime)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\dns\resolver.py", line 950, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 5.135733604431152 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\work\anaconda3\envs\django3\lib\site-packages\celery\app\trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\celery\app\trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "D:\work\kangaroo_monitor\kangaroo_monitor_django\eciTask\notifyTask.py", line 55, in ncStatistics
    _baseSendMsg(content, 18510234326)
  File "D:\work\kangaroo_monitor\kangaroo_monitor_django\notifyHardler\DingDingHardler.py", line 49, in _baseSendMsg
    conn.request("POST", uri, json.dumps(dingMsg), headers)
  File "d:\work\anaconda3\envs\django3\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\work\anaconda3\envs\django3\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\work\anaconda3\envs\django3\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\work\anaconda3\envs\django3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "d:\work\anaconda3\envs\django3\lib\http\client.py", line 966, in send
    self.connect()
  File "d:\work\anaconda3\envs\django3\lib\http\client.py", line 1414, in connect
    super().connect()
  File "d:\work\anaconda3\envs\django3\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "d:\work\anaconda3\envs\django3\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 517, in getaddrinfo
    qname, addrs = _getaddrinfo_lookup(host, family, flags)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 490, in _getaddrinfo_lookup
    raise err
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 479, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 432, in resolve
    raise EAI_EAGAIN_ERROR
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 479, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "d:\work\anaconda3\envs\django3\lib\site-packages\eventlet\support\greendns.py", line 432, in resolve
    raise EAI_EAGAIN_ERROR
socket.gaierror: [Errno 11002] Lookup timed out

**Comment by auvipy** [comment]
raise EAI_EAGAIN_ERROR
socket.gaierror: [Errno 11002] Lookup timed out

says it's probably not a celery issue but your codes. use flask support forum or celery-users mailing list and provide follow proper issue reporting template.
