### ISSUE TITLE
celery  async send email   (Lookup timed out) ERROR

### ISSUE THREAD

**Issue by binbinjianjian** [celery/celery#6275]
celery start param:

celery -A ceshi worker -l info -P eventlet

os:
window10

[2020-08-02 15:09:00,218: ERROR/MainProcess] Task ceshi.email[709cf57b-6a67-46c7-9d8e-56e6ce60a4a8] raised unexpected: gaierror(11002, 'Lookup timed out')
Traceback (most recent call last):
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 425, in resolve
    use_network=use_network)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 380, in query
    return end()
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 359, in end
    raise result[1]
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 340, in step
    a = fun(*args, **kwargs)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\dns\resolver.py", line 1091, in query
    True)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\dns\resolver.py", line 1043, in resolve
    timeout = self._compute_timeout(start, lifetime)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\dns\resolver.py", line 950, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 5.134687900543213 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\celery\app\trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\celery\app\trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "D:\MyProgram\code\opsm-be-old\app\test_demo\celery_test\ceshi.py", line 51, in email
    yag.send(email_name, subject, contents=[body, html, img])
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\yagmail\sender.py", line 147, in send
    self.login()
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\yagmail\sender.py", line 246, in login
    self._login(self.credentials)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\yagmail\sender.py", line 192, in _login
    self.smtp = self.connection(self.host, self.port, **self.kwargs)
  File "d:\myprogram\python36\Lib\smtplib.py", line 1031, in __init__
    source_address)
  File "d:\myprogram\python36\Lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "d:\myprogram\python36\Lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "d:\myprogram\python36\Lib\smtplib.py", line 1037, in _get_socket
    self.source_address)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\green\socket.py", line 44, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 517, in getaddrinfo
    qname, addrs = _getaddrinfo_lookup(host, family, flags)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 490, in _getaddrinfo_lookup
    raise err
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 479, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 432, in resolve
    raise EAI_EAGAIN_ERROR
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 479, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "d:\myprogram\code\project\opsm-be\.venv\lib\site-packages\eventlet\support\greendns.py", line 432, in resolve
    raise EAI_EAGAIN_ERROR
socket.gaierror: [Errno 11002] Lookup timed out

**Comment by thedrow** [comment]
This is not related to us. This is a DNS issue.
In addition, this issue does not meet the project's standards for reporting bugs.
Please use the appropriate template going forwards.

**Comment by binbinjianjian** [comment]
Sorry, I probably know that the problem is caused by the abnormal function of the eventlet module in the window environment. It can be used normally in the linux environment. Note that the template will be used later
