### ISSUE TITLE
celery multi - preload options unrecognized

### ISSUE THREAD

**Issue by maconfr** [celery/celery#6307]
Preload options are not unrecognized anymore since celery v4.4.4

The example at [Preload options](https://docs.celeryproject.org/en/stable/userguide/extending.html#preload-options) works with celery v4.4.3 but not with >=4.4.4.

```python3
# app.py
from celery import Celery
from celery import signals
from celery.bin import Option

app = Celery()


def add_preload_options(parser):
    parser.add_argument(
        "-Z", "--template", default="default", help="Configuration template to use.",
    )


app.user_options["preload"].add(add_preload_options)


@signals.user_preload_options.connect
def on_preload_parsed(options, **kwargs):
    print(options["template"])
```

Here is the output with v4.4.3:

```bash
$ venv/bin/celery \
> multi start worker1 \
> -A app \
> --template=foo \
> --concurrency=1
celery multi v4.4.3 (cliffs)
> Starting nodes...
foo
	> worker1@d113: OK
$ venv/bin/celery -A app report
default

software -> celery:4.4.3 (cliffs) kombu:4.6.11 py:3.7.3
            billiard:3.6.3.0 py-amqp:2.6.1
platform -> system:Linux arch:64bit, ELF
            kernel version:4.19.0-10-amd64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

This is the output with v4.4.7:

```bash
$ venv/bin/celery \
> multi start worker1 \
> -A app \
> --template=foo \
> --concurrency=1
celery multi v4.4.7 (cliffs)
> Starting nodes...
usage: /tmp/celery_preload/venv/lib/python3.7/site-packages/celery/bin/celery.py worker [options] 
/tmp/celery_preload/venv/lib/python3.7/site-packages/celery/bin/celery.py: error: unrecognized arguments: --template=foo
	> worker1@d113: * Child terminated with exit code 2
FAILED
$ venv/bin/celery -A app report
default

software -> celery:4.4.7 (cliffs) kombu:4.6.11 py:3.7.3
            billiard:3.6.3.0 py-amqp:2.6.1
platform -> system:Linux arch:64bit, ELF
            kernel version:4.19.0-10-amd64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

**Comment by auvipy** [comment]
can you help to find out the commit that could cause the potential regression?

**Comment by maconfr** [comment]
Seems to be introduced with v4.4.7

Last working commit:
d537be48e Remove mutable arguments in assert_routes_to_queue.
Starts to fail with:
e3ac73b6f FIX: -A and --args should behave the same. (#6223)

**Comment by maconfr** [comment]
Accidentally closed. Sorry!

**Comment by auvipy** [comment]
> Seems to be introduced with v4.4.7
> 
> Last working commit:
> [d537be4](https://github.com/celery/celery/commit/d537be48e41cec1336e8e35f6db271b5f635adb7) Remove mutable arguments in assert_routes_to_queue.
> Starts to fail with:
> [e3ac73b](https://github.com/celery/celery/commit/e3ac73b6fbe2d996070b90833c23a3b336cd4ac6) FIX: -A and --args should behave the same. (#6223)

@JulienPalard if you could spent some time please!

**Comment by JulienPalard** [comment]
(@auvipy just revert my commit, see my comments in other issues, I'm mostly offline those days).

**Comment by thedrow** [comment]
Hi, could you please try the Celery 5.0 release candidate?
We **rewrote** our CLI using click.

I'm glad to know that someone is using Preload Options.
I considered removing them entirely.

Could you please (even privately by mail) describe what you are doing with it?

**Comment by maconfr** [comment]
I just tested it again with this commit:
* 51fe1f320 (HEAD -> master, tag: v5.0.0rc1, origin/master, origin/HEAD) Bump version: 5.0.0b1 → 5.0.0rc1

I put the general/preload options befor the sub-command `multi` wich is (usually) crucial for click.

```bash
$ venv/bin/celery \
> -A app \
> --template=foo \
> multi start worker1 \
> --concurrency=1
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: no such option: --template


$ venv/bin/celery -A app report
Traceback (most recent call last):
  File "venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 150, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 1965, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 1589, in full_process_value
    value = self.process_value(ctx, value)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 1579, in process_value
    return self.type_cast_value(ctx, value)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 1568, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/core.py", line 1565, in _convert
    return self.type(value, self, ctx)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 35, in convert
    return find_app(value)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/celery/app/utils.py", line 364, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/tmp/celery_preload/venv/lib/python3.7/site-packages/celery/utils/imports.py", line 107, in import_from_cwd
    return imp(module, package=package)
  File "/tmp/celery_preload/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/celery_preload/app.py", line 3, in <module>
    from celery.bin import Option
ImportError: cannot import name 'Option' from 'celery.bin' (/tmp/celery_preload/venv/lib/python3.7/site-packages/celery/bin/__init__.py)
```

We use the [pyramid_celery](https://github.com/sontek/pyramid_celery) plugin in our application, but it is unmaintained so we might have to move away from it when we also upgrade to celery 5.0 because it will be incompatible with click.

**Comment by thedrow** [comment]
Oh yes, that's a breaking change.
You should use `click.Option` instead.

This will soon be documented in the What's New document :)

**Comment by rcjsuen** [comment]
```
$ venv/bin/celery -A bug worker --template x
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.

Error: no such option: --template
```
```Python
from celery import Celery
from celery import signals

app = Celery()


def add_preload_options(parser):
    parser.add_argument(
        "-Z", "--template", default="default", help="Configuration template to use.",
    )


app.user_options["preload"].add(add_preload_options)


@signals.user_preload_options.connect
def on_preload_parsed(options, **kwargs):
    print(options["template"])
```
@thedrow What is the right way to do this in 5.0.0? I see #6379 has been opened in any case.

**Comment by thedrow** [comment]
I'll get to this issue very soon.
I have a few very urgent fixes to make.
I'll try to take a look on this for 5.0.1.

**Comment by sontek** [comment]
@thedrow Can you please let us know how to do this?   Its breaking our preload options

**Comment by thedrow** [comment]
Hi,
This issue is the top priority for 5.0.3.

I had other very urgent bugs to fix.

**Comment by ergo** [comment]
Yup, looks like this also affected our application. Will downgrade to 4.x for the time being.

**Comment by thedrow** [comment]
I was ill and now I'm back on track. I handled #6501 today.
I need to take care of this before 5.0.3 is released so this is still on my radar.

**Comment by ergo** [comment]
@thedrow Hey, I hope you are getting better. Thank you for your hard work!

**Comment by ergo** [comment]
@thedrow 
```
I'm glad to know that someone is using Preload Options.
I considered removing them entirely.

Could you please (even privately by mail) describe what you are doing with it?
```
That makes me wonder - how do people initialize their applications/configs early using other means than preload options? This is exactly what we were using this feature for.

**Comment by thedrow** [comment]
5.0.3 is released. 🎉

**Comment by olemoign** [comment]
@ergo @thedrow
Same here. We use the preload options to specify the location of our app config file. I expect this to be a pretty common use case and don't really see how to do that differently.

**Comment by sontek** [comment]
Yeah, I would love to see how people are configuring celery with their application config without using preload_options.  Is there a feature I'm not aware of since I've been doing it with preload for so long?

```
@celery.signals.user_preload_options.connect
def on_preload_parsed(options, **kwargs):
    from eventray.configuration import read_config
    config = read_config(
        options['eventray_config'],
        options['eventray_app_env'],
        setup_one_time=True,
    )

    configure_celery(config, initialize_context=True)
```

and:

```
app = celery.Celery('eventray')
app.conf.update(
    CELERY_ACCEPT_CONTENT=['json'],
    CELERY_IMPORTS=[
        'eventray.attendees.services',
        'eventray.attendees.models.transactions.payflow_pro',
        'eventray.celery_.tasks',
        'eventray.email_templates.actions',
        'eventray.emails',
        'eventray.event_feed.services',
        'eventray.exports.services',
        'eventray.forms.models.form_addons.eventmobi',
        'eventray.gateways.slack',
        'eventray.web.api.v1.attendees',
        'eventray.web.hooks.teamcity',
    ],
    CELERY_TASK_SERIALIZER='json',
    CELERYD_HIJACK_ROOT_LOGGER=False,
)

app.user_options['preload'].add(add_preload_options)
```
and for another project:

```
def add_preload_arguments(parser):
    parser.add_argument(
        '-i', '--ini', default=None,
        help='Paste ini configuration file.'
    )
    parser.add_argument(
        '--ini-var', default=None,
        help='Comma separated list of key=value to pass to ini.'
    )


celery_app = Celery()


@signals.user_preload_options.connect
def on_preload_parsed(options, **kwargs):
    ini_location = options['ini']
    ini_vars = options['ini_var']

    if ini_location is None:
        print('You must provide the paste --ini argument')
        exit(-1)

    options = {}
    if ini_vars is not None:
        for pairs in ini_vars.split(','):
            key, value = pairs.split('=')
            options[key] = value

        env = bootstrap(ini_location, options=options)
    else:
        env = bootstrap(ini_location)

    registry = env['registry']
    app = env['app']
    root = env['root']
    request = env['request']
    closer = env['closer']
    setup_app(app, root, request, registry, closer, ini_location)
```
