### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'float' and 'str'

### ISSUE THREAD

**Issue by Hamza-Lachi** [celery/celery#6339]
i have a django porject and i want to use celery

so i configure celery in my django project

but when i run celery via this command `celery -A marla5 worker -l info` i get this issue `TypeError: unsupported operand type(s) for +: 'float' and 'str'
`

and the file it's telling it's not mine

how can i fix?

full error:
```

[2020-09-07 13:44:39,446: CRITICAL/MainProcess] Unrecoverable error: TypeError("unsupported operand type(s) for +: 'float' and 'str'")
Traceback (most recent call last):
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 351, in on_result_readable
    next(it)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 334, in _recv_message
    callback(message)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/billiard/pool.py", line 853, in on_state_change
    state_handlers[state](*args)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/billiard/pool.py", line 811, in on_ack
    cache[job]._ack(i, time_accepted, pid, synqW_fd)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/billiard/pool.py", line 1845, in _ack
    self._on_timeout_set(self, self._soft_timeout, self._timeout)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 566, in on_timeout_set
    hard, self._on_hard_timeout, R._job,
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 207, in call_later
    return self.timer.call_after(delay, callback, args)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/kombu/asynchronous/timer.py", line 117, in call_after
    return self.enter_after(secs, self.Entry(fun, args, kwargs), priority)
  File "/var/www/html/5marla/env/lib/python3.7/site-packages/kombu/asynchronous/timer.py", line 161, in enter_after
    return self.enter_at(entry, time() + secs, priority)
TypeError: unsupported operand type(s) for +: 'float' and 'str'

```

**Comment by thedrow** [comment]
This issue does not contain the minimum information required to resolve it.
Therefore, I'm going to close it.

Please file a new issue and fill our template.
