### ISSUE TITLE
Celery Migrate Broken

### ISSUE THREAD

**Issue by Nishant23** [celery/celery#6347]
I am migrating from redis to rabbitmq as a task broker for celery. I tried to migrate tasks from redis to rabbitmq using this command `celery migrate redis://localhost:6379 amqp://testuser:testpass@localhost:5672/testhost` but it is throwing error

```
Traceback (most recent call last):
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/celery.py", line 419, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/base.py", line 309, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/base.py", line 393, in handle_argv
    return self(*args, **options)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/migrate.py", line 66, in run
    **kwargs)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/contrib/migrate.py", line 118, in migrate_tasks
    on_declare_queue=on_declare_queue, **kwargs)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/contrib/migrate.py", line 355, in start_filter
    **kwargs).start()
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/contrib/migrate.py", line 278, in start
    ignore_timeouts=self.forever):
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/common.py", line 237, in eventloop
    yield conn.drain_events(timeout=timeout)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/connection.py", line 324, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 963, in drain_events
    get(self._deliver, timeout=timeout)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 376, in get
    ret = self.handle_event(fileno, event)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 358, in handle_event
    return self.on_readable(fileno), self
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 354, in on_readable
    chan.handlers[type]()
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 744, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 633, in _callback
    return callback(message)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/messaging.py", line 590, in receive
    [callback(body, message) for callback in callbacks]
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/kombu/messaging.py", line 590, in <listcomp>
    [callback(body, message) for callback in callbacks]
  File "/Users/nishantsuman/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/celery/bin/migrate.py", line 57, in on_migrate_task
    self.out(self.progress_fmt.format(state=state, body=body))
TypeError: list indices must be integers or slices, not str
Restoring 1 unacknowledged message(s)
```

**Comment by pgcd** [comment]
I'm not even getting there - I run the command (in the other direction) and it simply remains there with no error, no message and absolutely no change whatsoever in the messages on either broker.

**Comment by kcharwood** [comment]
I think I'm seeing the same behavior. Appears to just sit there with no progress?

**Comment by kcharwood** [comment]
> I think I'm seeing the same behavior. Appears to just sit there with no progress?

Looks like it wasn't progressing because I wasn't explicitly passing `-Q` with the queues I wanted to migrate. I assumed it would migrate all if I didn't pass anything.
