### ISSUE TITLE
celery multi celery.exceptions.TimeoutError: The operation timed out

### ISSUE THREAD

**Issue by redstoneleo** [celery/celery#6351]
I followed the official [Celery guide][1] to learn , everything works well when using `celery -A proj worker -l info` to  start the worker, however , if I run the worker in the background using `celery multi start w1 -A proj -l info`, then I got 

    >>> from proj.tasks import add
    >>> add.delay().get(timeout=19)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.8/dist-packages/celery/result.py", line 230, in get
        return self.backend.wait_for_pending(
      File "/usr/local/lib/python3.8/dist-packages/celery/backends/base.py", line 660, in wait_for_pending
        meta = self.wait_for(
      File "/usr/local/lib/python3.8/dist-packages/celery/backends/base.py", line 696, in wait_for
        raise TimeoutError('The operation timed out.')
    celery.exceptions.TimeoutError: The operation timed out.
    >>>
So what's wrong ?

Test environment :

 - Python 3.8.2 
 - celery multi v4.4.7
 - rabbitmqctl version --->    3.8.2

and 

    app = Celery('proj',
                 broker='amqp://localhost',
                 # backend='db+sqlite:///results.sqlite',  # The backend argument， If you don’t need results, it’s better to disable them.  Results can also be disabled for individual tasks by setting the @task(ignore_result=True) option.
                 include=['proj.tasks'])  # The include argument is a list of modules to import when the worker starts. You need to add our tasks module here so that the worker is able to find our tasks.
    app.conf.CELERY_RESULT_BACKEND = 'db+sqlite:///results.sqlite'

  [1]: https://docs.celeryproject.org/en/stable/getting-started/next-steps.html#in-the-background

**Comment by thedrow** [comment]
Have you tried checking if the task is still in the queue?
Does Celery run? Have you checked the logs?

**Comment by redstoneleo** [comment]
```
>>> res.state
'PENDING'
```
and the log info, I googled , but didn't find a working solutions 
```
[2020-09-15 22:10:03,229: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2020-09-15 22:10:03,238: INFO/MainProcess] mingle: searching for neighbors
[2020-09-15 22:10:04,260: INFO/MainProcess] mingle: all alone
[2020-09-15 22:10:04,273: INFO/MainProcess] w1@iZwz962a07bhoio77q4ewxZ ready.
[2020-09-15 22:10:10,625: ERROR/MainProcess] Received unregistered task of type 'proj.tasks.add'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/consumer/consumer.py", line 562, in on_task_received
    strategy = strategies[type_]
KeyError: 'proj.tasks.add'

```

**Comment by thedrow** [comment]
Celery can't find your task. This is why you're not getting a result and the operation times out.

I can't help you any further without seeing the code.
In addition, I think that this is a usage question and you should refer it to our mailing list or StackOverflow.

Unless there's an actual problem with Celery, I'm going to close this issue.

**Comment by redstoneleo** [comment]
I uploaded my code, would you mind give further help ? Thanks !
[proj.zip](https://github.com/celery/celery/files/5231502/proj.zip)
