### ISSUE TITLE
Celery 5.0.0: Error: Invalid value for '-A' / '--app': No module named 'celery.five'

### ISSUE THREAD

**Issue by oprog** [celery/celery#6369]
I'm inside the official dockerhub python image for 3.8.6 (but same issue with 3.8.5).

**My environment**

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ python --version
Python 3.8.6

$ celery --version
5.0.0 (singularity)

$ pip freeze
amqp==5.0.1
attrs==20.2.0
Automat==20.2.0
billiard==3.6.3.0
cachetools==4.1.1
celery==5.0.0
celery-redbeat==1.0.0
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
click-didyoumean==0.0.3
click-repl==0.1.6
constantly==15.1.0
cryptography==3.1.1
cssselect==1.1.0
google-api-core==1.22.2
google-api-python-client==1.12.2
google-auth==1.21.3
google-auth-httplib2==0.0.4
google-auth-oauthlib==0.4.1
googleapis-common-protos==1.52.0
httplib2==0.18.1
hyperlink==20.0.1
idna==2.10
incremental==17.5.0
itemadapter==0.1.0
itemloaders==1.0.3
jmespath==0.10.0
kombu==5.0.2
lxml==4.5.2
numpy==1.19.2
oauthlib==3.1.0
pandas==1.1.2
parsel==1.6.0
prompt-toolkit==3.0.7
Protego==0.1.16
protobuf==3.13.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyDispatcher==2.0.5
PyHamcrest==2.0.2
pymongo==3.11.0
pyOpenSSL==19.1.0
python-dateutil==2.8.1
pytz==2020.1
queuelib==1.5.0
redis==3.5.3
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
Scrapy==2.3.0
service-identity==18.1.0
six==1.15.0
tenacity==6.2.0
Twisted==20.3.0
uritemplate==3.0.1
urllib3==1.25.10
vine==5.0.0
w3lib==1.22.0
wcwidth==0.2.5
zope.interface==5.1.0

```
**The issue**

In the shell:
```
$ celery -A tasks worker
Usage: celery [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for '-A' / '--app': No module named 'celery.five'
```

The issue was not present for previous celery version (i.e. 4.4.7)

**Comment by thedrow** [comment]
Do you happen to have a traceback?
Are you sure you're not using an outdated RC? According to your `pip freeze` output it seems like you aren't.
Are you sure you haven't imported it yourself?

Could there be any reminder `*.pyc` files that may cause this issue?

**Comment by oprog** [comment]
HI @thedrow. I'm not using celery docker image. What I meant is that the bug is happening inside my docker container that is based on python 3.8.6 image. I've installed celery using RUN pip install celery, so no outdated RC or direct import.
I removed all the .pyc files from the app folder but without success.

I'll try to do some other test and collect more info.

**Comment by thedrow** [comment]
If you can, replace [this line](https://github.com/celery/celery/blob/master/celery/bin/celery.py#L38) with `traceback.print_exc()`.
This will show you where the error is coming from.

I'm going to add a UX enhancement which will print the traceback in case the error came from another module other than the settings module.

**Comment by oprog** [comment]
I guess we can close this and we can say that I had to dig a little more. 
Anyway the #6383 was really helpful.
Have a look at last lines:
```
root@2d8b5ac434ca:/app# celery -A tasks worker
Usage: celery [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module tasks the following error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 50, in convert
    return find_app(value)
  File "/usr/local/lib/python3.8/site-packages/celery/app/utils.py", line 384, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/utils/imports.py", line 107, in import_from_cwd
    return imp(module, package=package)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/tasks.py", line 5, in <module>
    from crawler import *
  File "/app/crawler/__init__.py", line 2, in <module>
    from .crawler import *
  File "/app/crawler/crawler.py", line 9, in <module>
    from redbeat import RedBeatSchedulerEntry as Entry
  File "/usr/local/lib/python3.8/site-packages/redbeat/__init__.py", line 3, in <module>
    from .schedulers import RedBeatScheduler, RedBeatSchedulerEntry  # noqa
  File "/usr/local/lib/python3.8/site-packages/redbeat/schedulers.py", line 30, in <module>
    from celery.five import values
ModuleNotFoundError: No module named 'celery.five'
```

I removed from my code the dependencies from redbeat and everything worked.
I guess I will move on redbeat issues tab now :)
Thanks for your assistance
