### ISSUE TITLE
Document breaking changes in user options

### ISSUE THREAD

**Issue by thedrow** [celery/celery#6380]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- #6266 

#### Possible Duplicates

- None

# Description

Since we migrated to Click, user options are now using Click's API.
Previously, the used argparse's API.

This breaking change was not properly documented.

# Suggestions

We should update our [extending](https://github.com/celery/celery/blob/master/docs/userguide/extending.rst#command-line-programs) user guide and use the correct APIs.

**Comment by sylencecc** [comment]
Yep, after upgrading to celery 5.0 I'm currently stuck with
```
Traceback (most recent call last):
  File "/usr/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/usr/lib/python3.8/site-packages/celery/bin/celery.py", line 150, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1044, in parse_args
    parser = self.make_parser(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 965, in make_parser
    for param in self.get_params(ctx):
  File "/usr/lib/python3.8/site-packages/click/core.py", line 912, in get_params
    help_option = self.get_help_option(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 944, in get_help_option
    help_options = self.get_help_option_names(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 938, in get_help_option_names
    all_names.difference_update(param.opts)
AttributeError: 'function' object has no attribute 'opts'
```
This is just based on the getting started task extended with a command line option from the [documentation](https://docs.celeryproject.org/en/stable/userguide/extending.html#extending-commandoptions):
```
from celery import Celery

app = Celery('tasks', broker='redis://broker:6379')
def add_worker_arguments(parser):
    parser.add_argument(
        '--enable-my-option', action='store_true', default=False,
        help='Enable custom option.',
    )
app.user_options['worker'].add(add_worker_arguments)

@app.task
def add(x, y):
    return x + y
```
Any hint on how that code should look like with celery 5.0 and click?

**Comment by thedrow** [comment]
I'm working on this.

**Comment by rrueth** [comment]
@thedrow Is there any update on this? I'm also running into this issue on celery 5.0.2.

**Comment by thedrow** [comment]
Apologies. I was ill and now I'm back on track.
I'm on this.
