### ISSUE TITLE
Celery 5.0.0 ModuleNotFoundError: No module named 'celery.task'

### ISSUE THREAD

**Issue by cryptobench** [celery/celery#6406]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
https://groups.google.com/g/celery-users/c/VIyUHo0UHCM

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.0.0

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7
* **Minimal Celery Version**: 5.0.0
* **Minimal Kombu Version**: 5.0.2
* **Minimal Broker Version**: Redis 3.5.3
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: Ubuntu 20.04
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

```
from celery.decorators import periodic_task

@periodic_task(run_every=crontab(minute='*/10'))
def my-task():
    doSomething()

```

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior
Import `from celery.decorators import periodic_task` and use the `periodic_task `decorator on a task

# Actual Behavior
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.7/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
  File "/usr/local/lib/python3.7/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 640, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 653, in _autodiscover_tasks_from_fixups
    ], related_name=related_name)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 645, in _autodiscover_tasks_from_names
    packages() if callable(packages) else packages, related_name,
  File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 220, in autodiscover_tasks
    related_name) if mod)
  File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 245, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 245, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 270, in find_related_module
    raise e
  File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 266, in find_related_module
    return importlib.import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/scraper/tasks.py", line 25, in <module>
    @periodic_task(run_every=crontab(minute='*/10'))
  File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 403, in _compat_periodic_task_decorator
    from celery.task import periodic_task
ModuleNotFoundError: No module named 'celery.task'
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/usr/local/lib/python3.7/site-packages/celery/bin/celery.py", line 150, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/bin/worker.py", line 329, in worker
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.7/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 82, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/local/lib/python3.7/site-packages/celery/fixups/django.py", line 121, in validate_models
    run_checks()
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/mydjango/urls.py", line 22, in <module>
    path('api/', include('scraper.urls', namespace="scraper")),
  File "/usr/local/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/scraper/urls.py", line 3, in <module>
    from . import views
  File "/src/scraper/views.py", line 2, in <module>
    from .tasks import save_fuzzed_domains
  File "/src/scraper/tasks.py", line 25, in <module>
    @periodic_task(run_every=crontab(minute='*/10'))
  File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 403, in _compat_periodic_task_decorator
    from celery.task import periodic_task
ModuleNotFoundError: No module named 'celery.task'
```

**Comment by lewisemm** [comment]
Please include the command you are using to start the celery worker.

**Comment by thedrow** [comment]
The deprecated task module was removed in Celery 5 in #6315.
If this is not documented in the release notes, this is a documentation bug.

**Comment by sandeepbalagopal09** [comment]
what is the fix for this ? not able to use `@periodic_task` decorator anymore.

**Comment by thedrow** [comment]
The module was deprecated.
If there is missing functionality, it is because it was intentionally removed by @ask.
If you require a new implementation, please file a feature request and we'll discuss the matter.

**Comment by sandeepbalagopal09** [comment]
okay. Seems the way in which periodic tasks are created is change. Is there any link for finding the new way to do it ?

**Comment by thedrow** [comment]
Please refer to the [documentation](https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html).

**Comment by kousthubasqi** [comment]
Woah! Thanks for making it hard.

**Comment by thedrow** [comment]
> Woah! Thanks for making it hard.

This functionality was deprecated a long while ago.
If you have any criticism, please express it constructively.

**Comment by macdonjo** [comment]
What was with replaced with? Doing a migration from Python 2 to Python 3.

**Comment by thedrow** [comment]
`from celery import shared_task`.
Please refer to the documentation.

**Comment by rameshdevprajapati** [comment]
ModuleNotFoundError: No module named 'celery.task'
I HAVE THIS PROBLEM , PLEASE HELP ME

**Comment by thedrow** [comment]
The module doesn't exist anymore in Celery 5 as I explained.
You need to use either the `@app.task` or the `@shared_task` decorator.
Please refer to the documentation for help.

**Comment by bblanchon** [comment]
From [the documentation](https://docs.celeryproject.org/en/stable/userguide/tasks.html):

> ### How do I import the task decorator? And what’s “app”?
> The task decorator is available on your [`Celery`](https://docs.celeryproject.org/en/stable/reference/celery.html#celery.Celery) application instance, if you don’t know what this is then please read [First Steps with Celery](https://docs.celeryproject.org/en/stable/getting-started/first-steps-with-celery.html#first-steps).
>
> If you’re using Django (see [First steps with Django](https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html#django-first-steps)), or you’re the author of a library then you probably want to use the `shared_task()` decorator:
>
> ```python
> from celery import shared_task
> @shared_task
> def add(x, y):
>     return x + y
> ```

**Comment by hvoid-build-block** [comment]
FYI: the celery.task module does not exist in 4.4.7 either.
