### ISSUE TITLE
`multi start` workers do not expand `~` in workdir CLI option

### ISSUE THREAD

**Issue by maybe-sybr** [celery/celery#6458]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```shell
$ celery multi start worker1 --workdir=~/tmp --app=app --pidfile=./%n.pid --logfile=./%n%I.log
```
App file never gets loaded so not relevant
</p>
</details>

# Expected Behavior
Multi worker starts as expected

# Actual Behavior
```
$ celery multi start worker1 --workdir=~/tmp --app=app --pidfile=./%n.pid --logfile=./%n%I.log
celery multi v5.0.2 (singularity)
> Starting nodes...
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/maybe/dev/celery/celery/__main__.py", line 19, in <module>
    main()
  File "/home/maybe/dev/celery/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/home/maybe/dev/celery/celery/bin/celery.py", line 207, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/home/maybe/dev/celery/venv/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/maybe/dev/celery/venv/lib64/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/maybe/dev/celery/venv/lib64/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/home/maybe/dev/celery/venv/lib64/python3.8/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/home/maybe/dev/celery/venv/lib64/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/maybe/dev/celery/venv/lib64/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/home/maybe/dev/celery/venv/lib64/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/maybe/dev/celery/celery/bin/celery.py", line 99, in <lambda>
    callback=lambda _, __, wd: os.chdir(wd) if wd else None,
FileNotFoundError: [Errno 2] No such file or directory: '~/tmp'
        > worker1@zen: * Child terminated with exit code 1
FAILED
```

**Comment by thedrow** [comment]
Was it supported before?
We can easily fix that.

**Comment by maybe-sybr** [comment]
Looks like it doesn't work in v4.4.7 or v4.3.0, failing with the same `FileNotFoundError` on the unexpanded path. I suspect it's probably never been implemented. If we don't  need to backport it then `pathlib` will make our life a bit easier. I think it'd be fine to just `Path.expanduser()` the workdir, and assume that any variables should be expanded by the executing shell rather than us having to substitute env vars.

**Comment by thedrow** [comment]
I don't think that we need to backport this as this is a new feature.

**Comment by thedrow** [comment]
I've marked this as a lower priority for us.
If you have the time to come up with a PR (with tests) for this and our other tasks, go ahead.

**Comment by maybe-sybr** [comment]
This was a minor issue and since we haven't had much interest on the issue, I assume it's not really affecting people. I'm going to put it in 5.2 as a fairly minor piece of work and will retain assignment in the hope that I can get time to fix it up.
