### ISSUE TITLE
Maximum recursion depth

### ISSUE THREAD

**Issue by amerpersonal** [celery/celery#6473]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.1.0

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 2.7.5
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior
When I run Celery worker with this command

`celery -A sx_workers worker -c1 -l info`

it shows me the next error stack trace:

`Traceback (most recent call last):
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/bin/worker.py", line 219, in run_from_argv
    *self.parse_options(prog_name, argv, command))
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/bin/base.py", line 403, in parse_options
    self.parser = self.create_parser(prog_name, command)
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/bin/base.py", line 419, in create_parser
    self.add_arguments(parser)
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/bin/worker.py", line 275, in add_arguments
    default=conf.worker_state_db,
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 431, in __getitem__
    return getitem(k)
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 280, in __getitem__
    return mapping[_key]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
...
/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/app/base.py", line 148, in data
    return self.callback()
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/app/base.py", line 911, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/app/base.py", line 921, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/loaders/base.py", line 146, in _smart_import
    return imp(path)
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/loaders/base.py", line 106, in import_from_cwd
    package=package,
  File "/Users/amerzildzic/swipestox/sx_distributed_processing/sxdpenv/lib/python2.7/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
    with cwd_in_path():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(*args, **kwds))
RuntimeError: maximum recursion depth exceeded
`

I dig through the code a bit and as I see there is recutsion between 

collections.py : self[k] 
and
UserDyct.py: __getitem__ (which should be same as indexing??)

since both are used on the stack trace.

I'm not so familiar with Python nor project, pretty new to this.
Thanks in advance,

Amer

**Comment by amerpersonal** [comment]
Fixed, there was issue in my celery config, but the error message was very strange indeed.

**Comment by james-mchugh** [comment]
Is there anyway of improving the error handling of config loading? I like the lazy loading that Celery does, but if there is an error with the config file (or even if the config file doesn't exist), it reports a RecursionError which is very misleading and hard to work with.
