### ISSUE TITLE
Are MongoDB replica sets supported as a result backend?

### ISSUE THREAD

**Issue by rbarrette** [celery/celery#6477]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- [3611](https://github.com/celery/celery/issues/3611) - I tried the config example here and could not get it to work.

#### Possible Duplicates

- None

# Description

Just wondering if this is actually something that is supported. I have seen posts on stackoverflow and other sites while googling around and looking for examples. [This](https://stackoverflow.com/a/53055412) example was not specific to a replica set, but I did find that updating the config after the initial Celery instantiation would show a URL/DB connection string. It does not appear to be parsing correctly tho. 

_.> results: mongodb://celery:**@host.com:27017/,host.com:27017,host.com:27017/?replicaSet=replicants(omitting rest of URL)_

Trying other examples just lead to no result backend configuration showing when loaded. 

_.> results: disabled_

# Suggestions

If this is supported, if would be nice to add some configuration examples for replica sets.

**Comment by thedrow** [comment]
It should be supported. If it isn't this is not a documentation bug but a functionality bug.

**Comment by rbarrette** [comment]
I should have taken more time to document the issues I was seeing, I ended up writing my own signals to document tasks to mongo instead of really diving into the issue. If I recall correctly, results were writing to mongo, but kombu was raising deserialization errors when I would attempt to check the status of via the task object. It would be nice to see official documentation on how we are should actually configure celery for a replica set. I do agree with you tho, there might be a couple functionality bugs that need to come out of this. One with replica set config not being parsed correctly (i.e. needing to update the config after celery app instantiation), and another with deserialization.

**Comment by thedrow** [comment]
Do you still need our help with this issue?

**Comment by rbarrette** [comment]
Not at the moment as I have worked around the issue by using signals and kept redis as both a broker and results backend. It might help others in the future if there were official documentation on how to configure celery to use a mongodb replicaset for either a broker, results backend or both.

**Comment by snachx** [comment]
I also encountered this problem. 

Although celery creates and updates celery_taskmeta correctly when setting result_backend to a mongodb uri with multiple hosts replicaset , it fails when I try to use some celery commands, for example 'celery report'.

It seems that celery uses kombu to parse mongodb uri which is not support to parse replicaset

I used celery v4.2.2, but I checked the latest code, the problem should still exist.

Traceback (most recent call last):
  File "/usr/local/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 279, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 363, in handle_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 371, in run
    self.out(self.app.bugreport())
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 909, in bugreport
    return bugreport(self)
  File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 348, in bugreport
    results=maybe_sanitize_url(app.conf.result_backend or 'disabled'),
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/url.py", line 98, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/url.py", line 91, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/url.py", line 58, in url_to_parts
    parts.port,
  File "/usr/local/lib/python3.6/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '3717,test.example.com:3717'
