### ISSUE TITLE
Decode error with ```disable_sync_subtasks=False``` in a subtask.

### ISSUE THREAD

**Issue by zhongluwang** [celery/celery#6493]
I am experimenting an error  with ```disable_sync_subtasks=False``` in a subtask. 
It might be caused by the type of ```children``` in backend data. It is a list rather a string.
Here is my code.

## Python Packages
celery==5.0.2
kombu==5.0.2

## Minimally Reproducible Test Case

<p>

```python
# task.py
import celery
backend='mongodb://localhost:27017/celery_test'
broker='mongodb://localhost:27017/celery_test'
cel=celery.Celery('test',backend=backend,broker=broker)

@cel.task
def task1(x,y):
    sum=x+y
    return sum
@cel.task
def task2(x,y):
    sum = task1.delay(x,y)
    sum = sum.get(disable_sync_subtasks=False)
    return x*y+sum

```

</p>
<p>

```python
# call_task.py
import celery
from task import task2
r=task2.delay(3,4)
print(r.get())

```

</p>

# Backend Data
```
{
    "_id" : "d39c6b7b-357a-4648-925b-10476845f15f",
    "status" : "SUCCESS",
    "result" : "19",
    "traceback" : null,
    "children" : [ 
        [ 
            [ 
                "38507c2b-88fd-4a62-9da6-2cd6a11c4c26", 
                null
            ], 
            null
        ]
    ],
    "date_done" : "2020-11-23T08:45:48.176082"
}
```

# Actual Behavior
```
Traceback (most recent call last):
  File "/home/wangzhonglu/anaconda3/lib/python3.7/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/home/wangzhonglu/anaconda3/lib/python3.7/site-packages/kombu/serialization.py", line 262, in loads
    return decode(data)
  File "/home/wangzhonglu/anaconda3/lib/python3.7/site-packages/kombu/utils/json.py", line 85, in loads
    return _loads(s)
  File "/home/wangzhonglu/anaconda3/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/wangzhonglu/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/wangzhonglu/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 392, in raw_decode
    raise TypeError("Input string must be text, not bytes")
TypeError: Input string must be text, not bytes
```

**Comment by thedrow** [comment]
Why are you using simplejson instead of the JSON module?

**Comment by auvipy** [comment]
I am  closing this for now. if you can reproduce this with celery 5.2betas and json we will reopen this. thanks for using celery.
