### ISSUE TITLE
Arguments specification when retrying task has to match the form used for calling the task

### ISSUE THREAD

**Issue by tlinhart** [celery/celery#6494]
# Checklist

- [X] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [X] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [X] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.
- [X] I have included the contents of ``pip freeze`` in the issue.
- [X] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Environment & Settings

**Celery version**: `5.0.2 (singularity)`

<details>
<summary><b><code>celery report</code> Output: </b></summary>
<p>

```
software -> celery:5.0.2 (singularity) kombu:5.0.2 py:3.6.9
            billiard:3.6.3.0 py-amqp:5.0.2
platform -> system:Linux arch:64bit, ELF
            kernel version:5.3.0-59-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

deprecated_settings: None
broker_url: 'amqp://test:********@192.168.84.224:5672/test_vhost'
```

</p>
</details>

# Steps to Reproduce

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.2
billiard==3.6.3.0
celery==5.0.2
click==7.1.2
click-didyoumean==0.0.3
click-repl==0.1.6
importlib-metadata==3.0.0
kombu==5.0.2
pkg-resources==0.0.0
prompt-toolkit==3.0.8
pytz==2020.4
six==1.15.0
vine==5.0.0
wcwidth==0.2.5
zipp==3.4.0
```

</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

Task definition:
```python
from celery import Celery

app = Celery('tasks')
app.conf.update({
    'broker_url': 'amqp://test:secret@192.168.84.224:5672/test_vhost'
})

@app.task(bind=True)
def retry(self, foo, bar=None):
    self.retry(args=(foo, bar), countdown=5)
```

Run worker:
```
celery -A tasks worker --loglevel=INFO
```

Submit task:
```python
from tasks import retry

retry.apply_async(kwargs={'foo': 1, 'bar': 'baz'})
```

</p>
</details>

# Expected Behavior
When retrying the task using `self.retry`, I can provide the task arguments either using `args` or `kwargs` (or mix both).

# Actual Behavior
When retrying the task using `self.retry`, I have to supply the task arguments in the same form as was used to call the task originally, otherwise an exception is raised:

```
 -------------- celery@jinx v5.0.2 (singularity)
--- ***** ----- 
-- ******* ---- Linux-5.3.0-59-generic-x86_64-with-Ubuntu-18.04-bionic 2020-11-23 12:32:02
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7fed5c609ba8
- ** ---------- .> transport:   amqp://test:**@192.168.84.224:5672/test_vhost
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . tasks.retry

[2020-11-23 12:32:02,653: INFO/MainProcess] Connected to amqp://test:**@192.168.84.224:5672/test_vhost
[2020-11-23 12:32:02,664: INFO/MainProcess] mingle: searching for neighbors
[2020-11-23 12:32:03,731: INFO/MainProcess] mingle: all alone
[2020-11-23 12:32:03,765: INFO/MainProcess] celery@jinx ready.
[2020-11-23 12:32:06,515: INFO/MainProcess] Received task: tasks.retry[1346d9aa-22da-4de2-a0f4-e42bd8cab57d]  
[2020-11-23 12:32:06,520: WARNING/ForkPoolWorker-2] Task tasks.retry[1346d9aa-22da-4de2-a0f4-e42bd8cab57d] reject requeue=False: retry() got multiple values for argument 'foo'
Traceback (most recent call last):
  File "/home/pasmen/tmp/x-celery-retry-bug/venv/lib/python3.6/site-packages/celery/app/task.py", line 720, in retry
    S.apply_async()
  File "/home/pasmen/tmp/x-celery-retry-bug/venv/lib/python3.6/site-packages/celery/canvas.py", line 225, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/pasmen/tmp/x-celery-retry-bug/venv/lib/python3.6/site-packages/celery/app/task.py", line 526, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: retry() got multiple values for argument 'foo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pasmen/tmp/x-celery-retry-bug/venv/lib/python3.6/site-packages/celery/app/trace.py", line 409, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/pasmen/tmp/x-celery-retry-bug/venv/lib/python3.6/site-packages/celery/app/trace.py", line 701, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/pasmen/tmp/x-celery-retry-bug/tasks.py", line 10, in retry
    self.retry(args=(foo, bar), countdown=5)
  File "/home/pasmen/tmp/x-celery-retry-bug/venv/lib/python3.6/site-packages/celery/app/task.py", line 722, in retry
    raise Reject(exc, requeue=False)
celery.exceptions.Reject: (TypeError("retry() got multiple values for argument 'foo'",), False)
```

The exception is raised in both cases, i.e. when calling the task providing arguments using `args` and then using `kwargs` in `self.retry`, and the other way around, when calling the task with `kwargs` and using `args` in `self.retry`. When I use the same form in `self.retry` as was used when calling the task, everything works without an error.

This seems to come from [`signature_from_request`](https://github.com/celery/celery/blob/e2031688284484d5b5a57ba29cd9cae2d9a81e39/celery/app/task.py#L592) method or `Task` class. Both `args` and `kwargs` are take from the request if they are `None` in `self.retry` call which leads to the described behavior. There is nothing about it in the documentation and I believe the task itself shouldn't assume anything about how it was called originally in orded to successfully call `self.retry`.

**Comment by thedrow** [comment]
Thanks for the bug report.
I agree you should be allowed to call retry with other arguments.
It seems like you have a basic analysis of the problem. Can you come up with a fix?
