### ISSUE TITLE
filedescriptor out of range in select()

### ISSUE THREAD

**Issue by hardikbansal** [celery/celery#6504]
I am using Django, Celery and Channels(with redis backend) to handle tasks in Dajngo based backend. Recently, as the things have scaled, I am facing the issue of :

**ValueError('filedescriptor out of range in select()',)**

```
Traceback (most recent call last):
  File "/home/cbt/backend/venv/lib/python3.6/site-packages/asgiref/sync.py", line 46, in __call__
    loop.run_until_complete(self.main_wrap(args, kwargs, call_result))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "/home/cbt/backend/venv/lib/python3.6/site-packages/gevent/monkey.py", line 831, in _select
    return select.select(*args, **kwargs)
  File "/home/cbt/backend/venv/lib/python3.6/site-packages/gevent/select.py", line 145, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cbt/backend/venv/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/cbt/backend/venv/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/cbt/backend/cbproj/tasks/tasks.py", line 1095, in start_new_subgame_timer
    add_users_to_subgame(game, game_type)
  File "/home/cbt/backend/cbproj/tasks/tasks.py", line 1405, in add_users_to_subgame
    async_to_sync(group_send_empty_subgame_audio_game_response)(game, game_type)
  File "/home/cbt/backend/venv/lib/python3.6/site-packages/asgiref/sync.py", line 50, in __call__
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "/home/cbt/backend/venv/lib/python3.6/site-packages/gevent/monkey.py", line 831, in _select
    return select.select(*args, **kwargs)
  File "/home/cbt/backend/venv/lib/python3.6/site-packages/gevent/select.py", line 145, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()
```

I am using following packages and `python 3.6`

* celery==4.3.0
* channels==3.0.2
* channels-redis==3.2.0

Also, this is happening when I am using `async_to_sync` function provided by django channels library(not everytime though). Is there a work around for this?

My limit for open files is 20000 and I am definitely not touching that limit.

**Edit 1:**

I am using following command from supervisor to start the process

`/home/cbt/backend/venv/bin/celery -A cbproj.celery worker -l info -P gevent -c 50 -Q game,default,celery -n worker1@%%h`

**Comment by thedrow** [comment]
Please use our template for reporting bugs.
We cannot reproduce this and therefore cannot help you.
