### ISSUE TITLE
PRECONDITION_FAILED - inequivalent arg 'durable', `auto_delete', 'message_ttl' + workaround

### ISSUE THREAD

**Issue by tomaszhlawiczka** [celery/celery#6509]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- https://github.com/celery/celery/issues/2269

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.0.2

<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.0.2 (singularity) kombu:5.0.2 py:3.8.6
            billiard:3.6.3.0 py-amqp:5.0.2
platform -> system:Linux arch:64bit, ELF
            kernel version:5.4.0-48-generic imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.2
argh==0.26.2
billiard==3.6.3.0
celery==5.0.2
click==7.1.2
click-didyoumean==0.0.3
click-repl==0.1.6
kombu==5.0.2
pathtools==0.1.2
prompt-toolkit==3.0.8
pytz==2020.4
PyYAML==5.3.1
six==1.15.0
vine==5.0.0
wcwidth==0.2.5
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

Start 2 workers `python a.py` and `python b.py`. The second worker `b.py` sends a message `do_stuff` to the `a.py` and wants to get a result to a callback (`link` parameter) to a dedicated queue that is unknown for `a.py`.
The dedicated queue has non-standard options (`durable`, `auto_delete`, `message_ttl`).

<details>
<p>

<b>a.py</b>
```python
import celery

app = celery.Celery(
    task_ignore_result=True,
    broker='amqp://127.0.0.1',
)

@app.task(name='do_stuff', queue="stuff_queue")
def do_stuff():
    print("got task")
    return {'response': 1234}

worker = app.Worker(
    concurrency=1,
    hostname="worker-a@%h",
    use_eventloop=True,
    queues=["stuff_queue"]
)
worker.start()
```

</p>

<p>

<b>b.py</b>
```python
import uuid
import celery
from celery.signals import worker_ready
from kombu.common import Queue

client_id = celery.utils.uuid()

app = celery.Celery(
    task_ignore_result=True,
    broker='amqp://127.0.0.1',
)

dedicated_queue = Queue(
    f"dedicated_queue_{client_id}",

    # Non-default queue options:
    durable=False,
    auto_delete=True,
    message_ttl=10 * 60
)

app.conf.task_queues = (dedicated_queue, )

@app.task(name='get_response', queue=dedicated_queue.name)
def get_response(response):
    print(f"got response {response}")

@worker_ready.connect
def on_worker_ready(**kwargs):
    app.send_task('do_stuff', queue="stuff_queue", link=get_response.s().set(queue=dedicated_queue.name))

worker = app.Worker(
    concurrency=1,
    hostname=f"worker-b-{client_id}@%h",
    use_eventloop=True,
    queues=[dedicated_queue.name]
)
worker.start()
```
</p>

</details>

# Expected Behavior

Sending a message to another worker via `send_task(..., link=get_response.s().set(queue=dedicated_queue.name))` with a non standard declaration of the queue results and an exception `amqp.exceptions.PreconditionFailed` - it is quite clear: the another worker has no idea how to declare a queue so it uses a default options and default options are incompatible with custom settings.
The problem here is a random name of the dedicated queue (done by purpose - each worker creates own queue), so such a queue cannot be added to the list of known queues to the other side.
How to get a task result to the unknown and non-standard queue?
There is one logic thing worth to mention - in a such scenario **a result queue is always declared before a task is executed**. If a result queue does not exist when a task is finished it does not make any sens to create a queue and put a result there - no one would ever retrieve it.

**Here is a workaround, how to stop declaration of the queue on the other side:**
```python
app.send_task('do_stuff', queue="stuff_queue", link=get_response.s().set(queue=dedicated_queue.name, declare=[]))
```

The crucial part here is to add `declare=[]` to the options of the callback (`link`). It prevents a declaration of the queue, also no exception is risen when a queue looks different then expected.

But.. shouldn't be there a dedicated and well described option on `send_task()` to prevent queue declaration on the other side?
Something like this:
```python
app.send_task(.., link=get_response.s().set(queue=dedicated_queue.name, declare_queue=False))
```

# Actual Behavior

Exception is risen:
```py3bt
[2020-11-30 15:44:35,937: ERROR/ForkPoolWorker-1] Task do_stuff[0b3a82d0-b4b8-492f-b34d-16f0d14861b8] raised unexpected: PreconditionFailed(406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'dedicated_queue_0510b87b-1afb-4999-a25e-25caf955743d' in vhost '/': received 'true' but current is 'false'", (50, 10), 'Queue.declare')
Traceback (most recent call last):
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/celery/app/trace.py", line 462, in trace_task
    signature(callbacks[0], app=app).apply_async(
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/celery/canvas.py", line 225, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/celery/app/base.py", line 718, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/celery/app/amqp.py", line 523, in send_task_message
    ret = producer.publish(
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/messaging.py", line 175, in publish
    return _publish(
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/connection.py", line 525, in _ensured
    return fun(*args, **kwargs)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/messaging.py", line 191, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/messaging.py", line 191, in <listcomp>
    [maybe_declare(entity) for entity in declare]
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/messaging.py", line 99, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/common.py", line 119, in maybe_declare
    return _maybe_declare(entity, channel)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/common.py", line 159, in _maybe_declare
    entity.declare(channel=channel)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/entity.py", line 606, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/entity.py", line 615, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/kombu/entity.py", line 643, in queue_declare
    ret = channel.queue_declare(
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/amqp/channel.py", line 1146, in queue_declare
    return queue_declare_ok_t(*self.wait(
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/amqp/abstract_channel.py", line 86, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/amqp/connection.py", line 522, in drain_events
    while not self.blocking_read(timeout):
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/amqp/connection.py", line 528, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/amqp/method_framing.py", line 53, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/amqp/connection.py", line 534, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/amqp/abstract_channel.py", line 143, in dispatch_method
    listener(*args)
  File "/home/users/me/celery-test/.venv/lib/python3.8/site-packages/amqp/channel.py", line 277, in _on_close
    raise error_for_code(
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'dedicated_queue_0510b87b-1afb-4999-a25e-25caf955743d' in vhost '/': received 'true' but current is 'false'
```

**Comment by auvipy** [comment]
did you try the latest release?

**Comment by auvipy** [comment]
did   you check the comment here https://github.com/celery/celery/issues/2269#issuecomment-57339073 ?

**Comment by tomaszhlawiczka** [comment]
> did you check the comment here [#2269 (comment)](https://github.com/celery/celery/issues/2269#issuecomment-57339073) ?

Yes. Basically it makes a perfect sens to have things in that way... however there are some cases (like this one here) where you would like to have just an option so Celery could act differently. Right now I'm using `declare=[]` but it sounds more like a workaround then expected and documented behavior - I'm just afraid that this option/workaround might be get lost in the future.

**Comment by auvipy** [comment]
> > did you check the comment here [#2269 (comment)](https://github.com/celery/celery/issues/2269#issuecomment-57339073) ?
> 
> Yes. Basically it makes a perfect sens to have things in that way... however there are some cases (like this one here) where you would like to have just an option so Celery could act differently. Right now I'm using `declare=[]` but it sounds more like a workaround then expected and documented behavior - I'm just afraid that this option/workaround might be get lost in the future.

you could come with a PR with your suggested improvement, the @celery/core-developers will share their insight on that :D

**Comment by tomaszhlawiczka** [comment]
It took me some time to figure it out after having searched the "whole internet" for this particular error and I realized that people are struggling with that but there was no straight answer (or at least I didn't find one) for that (why it is happening and what can I do to overcome this). That is why I created this issue. If you can do this, like even mention this in docs, it would just make world a bit better place.

**Comment by auvipy** [comment]
> It took me some time to figure it out after having searched the "whole internet" for this particular error and I realized that people are struggling with that but there was no straight answer (or at least I didn't find one) for that (why it is happening and what can I do to overcome this). That is why I created this issue. If you can do this, like even mention this in docs, it would just make world a bit better place.

you can send a PR for doc improvement so that other members can chime in
