### ISSUE TITLE
ModuleNotFoundError: No module named 'click._bashcomplete'

### ISSUE THREAD

**Issue by paladin0** [celery/celery#6511]
Setting up a new server today and got this

Traceback (most recent call last):

File "/usr/local/bin/celery", line 8, in <module>

sys.exit(main())

File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 14, in main

from celery.bin.celery import main as _main

File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 12, in <module>

from celery.bin.amqp import amqp

File "/usr/local/lib/python3.8/site-packages/celery/bin/amqp.py", line 7, in <module>

from click_repl import register_repl

File "/usr/local/lib/python3.8/site-packages/click_repl/__init__.py", line 6, in <module>

import click._bashcomplete

ModuleNotFoundError: No module named 'click._bashcomplete'

Traceback (most recent call last):

File "/usr/local/bin/celery", line 8, in <module>

sys.exit(main())

File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 14, in main

from celery.bin.celery import main as _main

File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 12, in <module>

from celery.bin.amqp import amqp

File "/usr/local/lib/python3.8/site-packages/celery/bin/amqp.py", line 7, in <module>

from click_repl import register_repl

File "/usr/local/lib/python3.8/site-packages/click_repl/__init__.py", line 6, in <module>

import click._bashcomplete

ModuleNotFoundError: No module named 'click._bashcomplete'

I even added it to my requirements.txt and it gets installed

**Comment by auvipy** [comment]
did you try importing click first?

**Comment by paladin0** [comment]
we dont use it in our project (directly)

However yes i added it to the top of the requirements.txt and still get the same result

**Comment by thedrow** [comment]
See upstream issue: https://github.com/click-contrib/click-repl/issues/72

Which click version do you have installed?

**Comment by thedrow** [comment]
The next bugfix release is going to ensure we don't install click 8.0 for now.

**Comment by paladin0** [comment]
Is there an ETA on this next release? right now we cant build our project as it uses docker and the latest versions of all packages

**Comment by thedrow** [comment]
I really hope to release it today.

**Comment by AdamWill** [comment]
click-repl seems to have fixed the problem in 0.2.0 released a couple of weeks ago:
https://github.com/click-contrib/click-repl/pull/76
https://github.com/click-contrib/click-repl/releases/tag/0.2.0
could you bump celery's click-repl requirement and drop the constraint on click max version, perhaps? thanks!

**Comment by thedrow** [comment]
We're on it. Expect 5.1.1 soon :)
