### ISSUE TITLE
celery sqs fails

### ISSUE THREAD

**Issue by MuslimBeibytuly** [celery/celery#6530]
celery with sqs, python 3.6 and celery 5.0.3
```
celery_consumer     | [2020-12-08 19:33:34,637: DEBUG/MainProcess] StringToSign:
celery_consumer     | AWS4-HMAC-SHA256
celery_consumer     | 20201208T113334Z
celery_consumer     | 20201208/ap-southeast-1/sqs/aws4_request
celery_consumer     | f2e73eca72c4a605b5fd4adcee76df4d7b6b602fc4c5fc86d89586efb675accd
celery_consumer     | [2020-12-08 19:33:34,637: DEBUG/MainProcess] Signature:
celery_consumer     | fe209cd2e49f3a1c12c2019fc98b61955309eac9cdfb6138d82986da070ff05a
celery_consumer     | [2020-12-08 19:33:37,689: DEBUG/MainProcess] Response headers: {}
celery_consumer     | [2020-12-08 19:33:37,689: DEBUG/MainProcess] Response body:
celery_consumer     | b'<?xml version="1.0"?><ReceiveMessageResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><ReceiveMessageResult><Message><MessageId>dd74c482-8581-4d33-a719-9cd02103223d</MessageId><ReceiptHandle>AQEBTMmwTunc8G+NxGoA1+hT++gNIa0BixIaviz/XoYYwrzDQfWmJdVRhTmbyhjNiF4FFbCQCc15SeY1nEiBGr5zRYMuP+bXdS6Ts9nwYeDhSPh7PoiZaAiOi+wb6eqCeFl3866rmzlqkB7Fbh2Wy+XiyDTU2egw1YQ08v1ypzcJIa3r33ATJieyYX0FJNm+gcQebTLEGVpIuRFxp/Da8SxlJI2MFxG74GghuNVMVG9vLpMlhkuaZLVVL8GrnGtCTcmwrgqd3Sczuz9btR7pDIPxqHvWeCo25kmPnpNzFKgv7r+VQZ578R5IYFxjxU5jDK8BnnZBUULID/JVZuKXxO+tKWiTvgs7ZkmZkYkjTkCjaTwIJOaKdy/UKaLLlJxA1QTdmICwKnpd+FADX2r7ZpaSggNVvKoxt2buU/G3s2MxOl8=</ReceiptHandle><MD5OfBody>0cbc6611f5540bd0809a388dc95a615b</MD5OfBody><Body>Test</Body></Message></ReceiveMessageResult><ResponseMetadata><RequestId>cb8b2a88-05e5-51dc-9230-72c16334b2ea</RequestId></ResponseMetadata></ReceiveMessageResponse>'
celery_consumer     | [2020-12-08 19:33:37,689: CRITICAL/MainProcess] Unrecoverable error: JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)
celery_consumer     | Traceback (most recent call last):
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
celery_consumer     |     self.blueprint.start(self)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 116, in start
celery_consumer     |     step.start(parent)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 365, in start
celery_consumer     |     return self.obj.start()
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 311, in start
celery_consumer     |     blueprint.start(self)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 116, in start
celery_consumer     |     step.start(parent)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 592, in start
celery_consumer     |     c.loop(*c.loop_args())
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/celery/worker/loops.py", line 81, in asynloop
celery_consumer     |     next(loop)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 361, in create_loop
celery_consumer     |     cb(*cbargs)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/http/curl.py", line 120, in on_readable
celery_consumer     |     return self._on_event(fd, _pycurl.CSELECT_IN)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/http/curl.py", line 137, in _on_event
celery_consumer     |     self._process_pending_requests()
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/http/curl.py", line 143, in _process_pending_requests
celery_consumer     |     self._process(curl)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/http/curl.py", line 191, in _process
celery_consumer     |     buffer=buffer, effective_url=effective_url, error=error,
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 167, in __call__
celery_consumer     |     svpending(*ca, **ck)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 160, in __call__
celery_consumer     |     return self.throw()
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 157, in __call__
celery_consumer     |     retval = fun(*final_args, **final_kwargs)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/funtools.py", line 98, in _transback
celery_consumer     |     return callback(ret)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 160, in __call__
celery_consumer     |     return self.throw()
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 157, in __call__
celery_consumer     |     retval = fun(*final_args, **final_kwargs)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/funtools.py", line 98, in _transback
celery_consumer     |     return callback(ret)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 160, in __call__
celery_consumer     |     return self.throw()
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/promises.py", line 157, in __call__
celery_consumer     |     retval = fun(*final_args, **final_kwargs)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/funtools.py", line 96, in _transback
celery_consumer     |     callback.throw()
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/vine/funtools.py", line 94, in _transback
celery_consumer     |     ret = filter_(*args + (ret,), **kwargs)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/kombu/transport/SQS.py", line 438, in _on_messages_ready
celery_consumer     |     msg_parsed = self._message_to_python(msg, qname, queue)
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/kombu/transport/SQS.py", line 301, in _message_to_python
celery_consumer     |     payload = loads(bytes_to_str(body))
celery_consumer     |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 85, in loads
celery_consumer     |     return _loads(s)
celery_consumer     |   File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
celery_consumer     |     return _default_decoder.decode(s)
celery_consumer     |   File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
celery_consumer     |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
celery_consumer     |   File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
celery_consumer     |     raise JSONDecodeError("Expecting value", s, err.value) from None
celery_consumer     | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by thedrow** [comment]
This is not enough information for us to debug this problem.
Please use our issue template.
