### ISSUE TITLE
Can't start Celery with gevent pool mode

### ISSUE THREAD

**Issue by alterEgo123** [celery/celery#6534]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.0.2

# Steps to Reproduce
`celery -A proj worker --pool=gevent`
## Required Dependencies

* **Minimal Python Version**: 3.6.9
* **Minimal Celery Version**: 5.0.2
* **Minimal Kombu Version**: 5.0.2
* **Minimal Broker Version**: rabbitmq_server-3.6.10
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: Ubuntu 18.04
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
tornado~=6.0.2
mongoengine~=0.17.0
passlib==1.7.3
PyJWT==1.7.1
celery==5.0.2
twilio==6.0.0
pytest~=5.3.2
python-gitlab~=2.4.0
bcrypt==3.1.7
pandas~=1.1.2
boto3==1.15.1
botocore==1.18.1
validate_email==1.3
py3DNS==3.2.1
pillow~=7.2.0
requests
pyfcm==1.3.1
gevent==20.9.0
setuptools~=39.1.0
```
</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Run Celery with gevent pool

# Actual Behavior

```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/celery/__main__.py", line 14, in main
    from celery.bin.celery import main as _main
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 15, in <module>
    from celery.bin.amqp import amqp
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/amqp.py", line 7, in <module>
    from click_repl import register_repl
  File "/usr/local/lib/python3.6/dist-packages/click_repl/__init__.py", line 2, in <module>
    from prompt_toolkit.completion import Completer, Completion
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 41, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/buffer.py", line 28, in <module>
    from .application.current import get_app
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/current.py", line 75, in <module>
    "_current_app_session", default=AppSession()
TypeError: 'type' object is not subscriptable
```

**Comment by thedrow** [comment]
I don't understand what you were trying to do.

It seems like you were trying to start `celery shell repl` and not the worker according to the traceback.
I can't reproduce this on Celery 5.0.2 & master.

**Comment by alterEgo123** [comment]
@thedrow I'm trying to start a celery worker with gevent pool. The command to do so is: `celery -A proj worker --pool=gevent`. Celery version I'm using is 5.0.2 and gevent is 20.9.0. Doing so raises the error above.

**Comment by thedrow** [comment]
Please upgrade to the latest 5.0.5.
I think that it should resolve the issue.

**Comment by devaljain1998** [comment]
@thedrow the issue is still opened, is it a bug that is currently being fixed or opened by mistake?

**Comment by alterEgo123** [comment]
@devaljain1998 “Mistakes are a fact of life. It is the response to error that counts.” - Nikki Giovanni

**Comment by thedrow** [comment]
I can't reproduce this. I'll need more details or a reproducible test case.

**Comment by skalecki-imblox** [comment]
This happens when you're using `contextvars` [package ](https://pypi.org/project/contextvars/) aiming to provide contextvars to older versions of python. Typing annotation `_current_app_session: ContextVar["AppSession"]` raises an exception, since their implementation doesn't inherit from `Generic[_T]`.

**Comment by thedrow** [comment]
So is this an upstream bug?

**Comment by skalecki-imblox** [comment]
Probably requires confirmation of the original issue author, but I think so. I've had exactly the same error.

**Comment by thedrow** [comment]
Could you please report this bug?

**Comment by issaccv** [comment]
I have this issue, it' funny. When I use loguru to log, this is what happened:
```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    from celery.bin.celery import main as _main
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/lib/python3.6/site-packages/celery/bin/celery.py", line 15, in <module>
    from celery.bin.amqp import amqp
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/lib/python3.6/site-packages/celery/bin/amqp.py", line 7, in <module>
    from click_repl import register_repl
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/lib/python3.6/site-packages/click_repl/__init__.py", line 2, in <module>
    from prompt_toolkit.completion import Completer, Completion
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/lib/python3.6/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/lib/python3.6/site-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 41, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 31, in <module>
    from .application.current import get_app
  File "/root/.local/share/virtualenvs/iharbor-ONSs7AGF/lib/python3.6/site-packages/prompt_toolkit/application/current.py", line 75, in <module>
    "_current_app_session", default=AppSession()
TypeError: 'type' object is not subscriptable
```
To reproduce the issue, only install loguru.
I am not sure it is the bug of celery or loguru.

**Comment by auvipy** [comment]
lets us check this for 5.2 bug fix release

**Comment by felix-last** [comment]
Can confirm that uninstalling `contextvars` resolves the same issue for me.
