### ISSUE TITLE
Celery gevent bug with Python3.9

### ISSUE THREAD

**Issue by yshaban-godaddy** [celery/celery#6627]
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [x] I have verified that the issue exists against the `master` branch of Celery.
* [x] I have included the contents of ``pip freeze`` in the issue.
* [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [  ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* None

#### Possible Duplicates
* None

## Environment & Settings

5.0.5 (singularity)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```

software -> celery:5.0.5 (singularity) kombu:5.0.2 py:3.9.0
            billiard:3.6.3.0 py-amqp:5.0.5
platform -> system:Linux arch:64bit, ELF
            kernel version:3.10.0-1127.19.1.el7.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:rpc:///

broker_host: 'localhost'
broker_password: '********'
broker_port: 5672
broker_url: 'amqp://********:********@localhost:5672//'
broker_user: '********'
broker_vhost: '/'
cache_lock_expire: 1
celery_backend_url: 'redis://:********@192.168.176.22:6379/0'
celery_max_mem_kilobytes: 49316430.0
event_queue_expires: 60
log_file_name: './jobs.log'
log_level: 20
max_overflow: '0'
max_pool_size: '250'
redbeat_redis_url: 'redis://192.168.176.22:6379/0&password=********'
redis_db: '0'
redis_host: '192.168.176.22'
redis_pass: '********'
redis_port: '6379'
result_backend: 'rpc:///'
result_expires: 3600
singleton_backend_url: 'redis://:********@192.168.176.22:6379/0'
singleton_lock_expiry: 300
task_acks_late: True
task_default_exchange_type: 'direct'
task_default_queue: 'default'
task_default_routing_key: '********'
task_send_sent_event: True
testing: False
worker_concurrency: '50'
worker_max_memory_per_child: 986328.6
worker_max_tasks_per_child: 10
worker_pool_restarts: True
worker_prefetch_multiplier: 1
worker_send_task_events: True
deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce
celery -A jobs worker E -l info -n server_validator_test  -Q registration_validation_queue --pool=gevent --concurrency=10 -O fair --max-memory-per-child=20000

## Required Dependencies

* **Minimal Python Version**: 3.9
* **Minimal Celery Version**: 5.0.5 (singularity)
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: RabbitMQ 3.8.11
* **Minimal OS and/or Kernel Version**: CentOS Linux release 8.3.2011
* **Minimal Redis**: 6.0.10

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
aiohttp==3.7.3
amqp==5.0.5
aniso8601==8.1.1
async-timeout==3.0.1
attrs==20.3.0
bcrypt==3.2.0
billiard==3.6.3.0
celery==5.0.5
celery-redbeat==2.0.0
celery-singleton==0.3.1
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.1.6
dnspython==2.1.0
docker==4.4.1
Flask==1.1.2
Flask-Limiter==1.4
Flask-RESTful==0.3.8
gevent==21.1.2
greenlet==1.0.0
idna==2.10
jobs==4.0.0
itsdangerous==1.1.0
Jinja2==2.11.3
kombu==5.0.2
ldap3==2.9
limits==1.5.1
MarkupSafe==1.1.1
multidict==5.1.0
mysql-connector-python==8.0.23
mysqlclient==2.0.3
pbr==5.5.1
pokinator==1.2.0
prompt-toolkit==3.0.14
protobuf==3.14.0
psutil==5.8.0
pyasn1==0.4.8
pycparser==2.20
python-dateutil==2.8.1
python-json-logger==2.0.1
pytz==2021.1
redis==3.5.3
requests==2.25.1
six==1.15.0
slackclient==2.9.3
SQLAlchemy==1.3.23
SQLAlchemy-Utils==0.36.8
stevedore==3.3.0
superlance==1.0.0
supervisor==4.2.1
sushy==3.6.1
tenacity==6.3.1
typing-extensions==3.7.4.3
urllib3==1.26.3
vine==5.0.0
wcwidth==0.2.5
websocket-client==0.57.0
Werkzeug==1.0.1
yarl==1.6.3
zope.event==4.5.0
zope.interface==5.2.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
Have any job and run it using gevent

```
celery -A jobs worker E -l info -n server_validator_test  -Q registration_validation_queue --pool=gevent --concurrency=10 -O fair --max-memory-per-child=20000
```

Job eventually fails during processing with the following exception:

```
[2021-02-05 20:07:35,910: WARNING/MainProcess] thread._reset_internal_locks(True)
[2021-02-05 20:07:35,910: WARNING/MainProcess] File "/usr/local/lib/python3.9/threading.py", line 829, in _reset_internal_locks
[2021-02-05 20:07:35,911: WARNING/MainProcess] self._tstate_lock._at_fork_reinit()
[2021-02-05 20:07:35,911: WARNING/MainProcess] AttributeError
[2021-02-05 20:07:35,911: WARNING/MainProcess] :
[2021-02-05 20:07:35,911: WARNING/MainProcess] 'NoneType' object has no attribute '_at_fork_reinit'
[2021-02-05 20:07:36,262: WARNING/MainProcess] Exception ignored in:
[2021-02-05 20:07:36,263: WARNING/MainProcess] <function _after_fork at 0x7f70c10a3ee0>
[2021-02-05 20:07:36,263: WARNING/MainProcess] Traceback (most recent call last):
[2021-02-05 20:07:36,263: WARNING/MainProcess] File "/usr/local/lib/python3.9/threading.py", line 1486, in _after_fork
[2021-02-05 20:07:36,265: WARNING/MainProcess] thread._reset_internal_locks(True)
[2021-02-05 20:07:36,265: WARNING/MainProcess] File "/usr/local/lib/python3.9/threading.py", line 829, in _reset_internal_locks
```

</p>
</details>

# Expected Behavior

Celery task actually completes, instead of failing. 

# Actual Behavior

Expect it to actually work. 

Downgrading to 3.8.1 python version resolves the issue. I suspect it is an issue with celery monkeypatching?

**Comment by auvipy** [comment]
officially we don't support py3.9 yet so if you could dig further to find out a fix tha would be really helpful

**Comment by frost-nzcr4** [comment]
Try to use this to apply monkeypatches before the Celery will start: 
`python -m gevent.monkey --module celery -A jobs worker E -l info -n server_validator_test -Q registration_validation_queue --pool=gevent --concurrency=10 -O fair --max-memory-per-child=20000`

**Comment by thedrow** [comment]
@jamadden Would you mind taking a look?

**Comment by auvipy** [comment]
what about python 3.10 as well?

**Comment by jrespeto** [comment]
I was running into this issue last night with python:3.10.2-bullseye downgrading the version to 3.8.12 fixed the issue.

Here is my test setup.


`docker-compose.yml`
```
version: '3'
services:
  tools2:
    image: sirt-test
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    tty: true
    environment:
    - FLASK_ENV=development
    - FLASK_APP=app
```

`dockerfile`
```
FROM python:3.8.12-bullseye
WORKDIR /opt/
COPY requirements.txt ./
RUN pip3 install -r requirements.txt
COPY *.py ./
CMD flask run -h 0.0.0.0 -p 5000
```

`requirements.txt`
```
celery
pika
flask
```

`app.py`
```python
from flask import Flask
from celery import Celery, shared_task
import ssl

app = Flask(__name__)

# update with your creds 
url = 'amqps://user:pass@host:5671'

app.config.update(
    CELERY_BROKER_URL=url,
    CELERY_RESULT_BACKEND='rpc://',
    BROKER_USE_SSL={'cert_reqs': ssl.CERT_NONE},
    CELERY_TIMEZONE='UTC',
    CELERY_DEFAULT_QUEUE='TEST'
)


def make_celery(app):
    celery = Celery(
        app.import_name,
        backend=app.config['CELERY_RESULT_BACKEND'],
        broker=app.config['CELERY_BROKER_URL']
    )
    celery.conf.update(app.config)

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    return celery


celery = make_celery(app)


@shared_task()
def addCall(a, b):
    return


def my_ext_caller(a, b):
    from kombu import Connection
    with Connection(hostname=url,
                    ssl={'cert_reqs': ssl.CERT_NONE}, default_channel='test_ext') as conn1:

        result = addCall.apply_async((a, b), queue='TEST', connection=conn1)
        # result.wait()
        conn1.close()
        return result


@app.route('/works', methods=["GET"])
def test1():
    my_ext_caller(1, 1)
    return 'test'


@app.route('/not_working', methods=["GET"])
def test2():
    addCall.delay(1, 1)
    return 'test'


if __name__ == "__main__":
    app.run()
```

**Comment by hateyou218** [comment]
Hi is there any plan on py3.9+ support?

**Comment by auvipy** [comment]
python 3,9 n 10 is supported long time ago. this is an upstream bug
