### ISSUE TITLE
Explicit queues not working with CELERY_CREATE_MISSING_QUEUES set to False

### ISSUE THREAD

**Issue by brmzkw** [celery/celery#6692]
If `CELERY_CREATE_MISSING_QUEUES` is `False`, the default queue `celery` is not created (unless of course it is created explicitly).

```python
from celery import Celery
from celery.canvas import Signature
from kombu import Exchange, Queue


app = Celery(
    'example',
    broker='amqp://guest:guest@rabbitmq//',
    backend='db+postgresql://celery:celery@postgres/celery',
)


app.conf['CELERY_QUEUES'] = (
    Queue('my_queue',
          exchange=Exchange('my_exchange', type='headers'),
          binding_arguments={'my_header': 'my_value'}),
)

app.conf['CELERY_CREATE_MISSING_QUEUES'] = False


@app.task
def add(x, y):
    print('add %s and %s' % (x, y))
    return x + y


def main():
    sig = Signature(
        'example.add',
        args=[1, 1],
        headers={
            'my_header': 'my_value',
        }
    )
    sig.apply_async(queue='my_queue')


if __name__ == '__main__':
    main()
```

Here, `queue='my_queue'` is specified in `apply_async` so the message should not access the default queue. However, [_create_task_sender from celery/amqp.py](https://github.com/celery/celery/blob/master/celery/app/amqp.py#L448) raises if the default queue is not specified.

Run with `python example.py`:

```
$ python example.py
Traceback (most recent call last):
  File "example.py", line 41, in <module>
    main()
  File "example.py", line 37, in main
    sig.apply_async(queue='my_queue')
  File "/usr/local/lib/python2.7/site-packages/celery/canvas.py", line 235, in apply_async
    return _apply(args, kwargs, **options)
  File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 741, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 264, in send_task_message
    return self._create_task_sender()
  File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 477, in _create_task_sender
    default_queue = self.default_queue
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 596, in default_queue
    return self.queues[self.app.conf.task_default_queue]
  File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 90, in __getitem__
    return dict.__getitem__(self, name)
  File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 102, in __missing__
    raise KeyError(name)
KeyError: None
```

If the line

```python
default_queue = self.default_queue
```

is replaced with

```python
try:
    default_queue = self.default_queue
except KeyError:
    default_queue = None
```

The message is routed successfully.

It is also impossible to route the message to an exchange. If I now send the message with `sig.apply_async(exchange='my_exchange')`:

```
$ python example.py
Traceback (most recent call last):
  File "example.py", line 41, in <module>
    main()
  File "example.py", line 37, in main
    sig.apply_async(exchange='my_exchange')
  File "/usr/local/lib/python2.7/site-packages/celery/canvas.py", line 235, in apply_async
    return _apply(args, kwargs, **options)
  File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 709, in send_task
    options, route_name or name, args, kwargs, task_type)
  File "/usr/local/lib/python2.7/site-packages/celery/app/routes.py", line 90, in route
    self.app.conf.task_default_queue), options)
  File "/usr/local/lib/python2.7/site-packages/celery/app/routes.py", line 100, in expand_destination
    queue = route.pop('queue', None)
AttributeError: 'NoneType' object has no attribute 'pop'
```

For information, the behavior is the same when `app.conf['CELERY_DEFAULT_QUEUE'] = None`.

**Comment by thedrow** [comment]
These are two separate bugs but we can fix them in one PR if you'd wish.
Care to issue a PR? This only requires the fix and tests to be merged.

**Comment by brmzkw** [comment]
To be honest, I don't know celery internals enough to fix these bugs. I assume the try/except (for the first bug) is not how it should be fixed.

**Comment by thedrow** [comment]
> 
> 
> To be honest, I don't know celery internals enough to fix these bugs. I assume the try/except (for the first bug) is not how it should be fixed.

The actual fix would be to use a [monad](https://returns.readthedocs.io/en/latest/pages/maybe.html) but that requires a redesign.
If your fix routes the task successfully, why isn't it the right fix?

**Comment by brmzkw** [comment]
> If your fix routes the task successfully, why isn't it the right fix?

Because I have no idea what else usage it would break.

**Comment by auvipy** [comment]
> > If your fix routes the task successfully, why isn't it the right fix?
> 
> Because I have no idea what else usage it would break.

just start with the thing you found working. we will get to know what that is going to break. don't afraid to make a PR. the maintainers will guide you as much as possible.

**Comment by VMAtm** [comment]
Thank you for raising this. I spent a lot of time to understand the bug

**Comment by Nisk33** [comment]
Is there a fix on the way, @auvipy or @Nusnus ? I have a task that consumes from a rabbitmq fanout exchange, bound to my queue with no routing key, but it was receiving duplicate messages. Celery was auto-adding bindings with routing keys “#.celery” and “celery” to the same queue. To avoid that, I set task_default_queue=None and task_create_missing_queues=False, and explicitly defined my queue bindings:

Queue
With this setup, I can no longer use send_task() or apply_async() because there’s no default queue. The only workaround I see is introducing a dummy default queue:
task_default_queue = "default" Queue

 Queue(
            name="default",
            durable=True,
        ),

Is there a better solution planned to prevent auto-bindings without requiring a dummy default queue? Obvious that the above solution with try/except will not work in my case due to large repo/project and can cause issues during packaging.

**Comment by auvipy** [comment]
we got a potential new fix for this, it would be great if anyone of you can try this

**Comment by Nisk33** [comment]
@auvipy - Thank you, will get to it by end of week at the earliest
