### ISSUE TITLE
Revoked tasks cause `RecursionError('maximum recursion depth exceeded while calling a Python object')`

### ISSUE THREAD

**Issue by nicolaerosia** [celery/celery#6736]
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] I have included the contents of ``pip freeze`` in the issue.
* [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* None

#### Possible Duplicates
* None

## Environment & Settings

**Celery version**: master, https://github.com/celery/celery/commit/8ebcce1523d79039f23da748f00bec465951de2a

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.1.0b1 (singularity) kombu:5.1.0b1 py:3.8.8
            billiard:3.6.4.0 redis:3.5.3
platform -> system:Linux arch:64bit
            kernel version:5.11.1-1.el7.elrepo.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis:6379/

broker_url: 'redis://redis:6379//'
result_backend: 'redis://redis:6379/'
include: ['myapp.service.celery.tasks']
deprecated_settings: None
accept_content: ['json', 'pickle']
result_accept_content: ['json', 'pickle']
task_serializer: 'pickle'
result_serializer: 'pickle'
task_track_started: False
task_store_errors_even_if_ignored: False
result_expires: datetime.timedelta(seconds=600)
result_extended: False
result_persistent: False
broker_connection_timeout: 30
beat_max_loop_interval: 60
```

</p>
</details>

# Steps to Reproduce
## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: redis 6.2.1
* **Minimal Result Backend Version**: redis 6.2.1
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```

```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python

```

</p>
</details>

# Expected Behavior

The worker is started with

```sh
celery -A <app>
--loglevel WARNING
--pool prefork
-- concurrency 32
--prefetch-multiplier 256
--queues ...
--uid=nobody
--gid=nogroup
```

I'm adding pushing tasks with the `expires` flag and there are periods in which the processing cannot keep up and I expect it to not process tasks which are no longer relevant (`expired` passed).
E.g.

```python
expires = 600 # 10 minutes
mytask_sig = celery_my_task.signature(
    kwargs=dict(myarg="abc"),
    queue=CELERY_TASK_QUEUE,
    expires=expires,
    ignore_result=True,
    immutable=True,
)

my_task.apply_async()
```

# Actual Behavior

Seems like the worker crashes when ALL tasks it gets to process are expired.
Full backtrace attached. Below you can see snippets:
[crashlog.txt](https://github.com/celery/celery/files/6347950/crashlog.txt)

```
[2021-04-21 03:39:44,629: CRITICAL/MainProcess] Unrecoverable error: RecursionError('maximum recursion depth exceeded while calling a Python object')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/request.py", line 652, in execute_using_pool
    raise TaskRevokedError(task_id)
celery.exceptions.TaskRevokedError: 5ccb493c-7a23-468f-9016-2a6d21d84d0c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/request.py", line 652, in execute_using_pool
    raise TaskRevokedError(task_id)
celery.exceptions.TaskRevokedError: 0a0d96d6-11fb-4b35-b8c4-ce9c6c72ecbc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/request.py", line 652, in execute_using_pool
    raise TaskRevokedError(task_id)
celery.exceptions.TaskRevokedError: af6d95d1-8c16-4ebb-8115-c73ee84d20ae

During handling of the above exception, another exception occurred:
```

and it keeps going like this until...

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/opt/conda/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/opt/conda/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 311, in start
    blueprint.start(self)
  File "/opt/conda/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 592, in start
    c.loop(*c.loop_args())
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "/opt/conda/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 361, in create_loop
    cb(*cbargs)
  File "/opt/conda/lib/python3.8/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
    next(it)
  File "/opt/conda/lib/python3.8/site-packages/celery/concurrency/asynpool.py", line 308, in _recv_message
    callback(message)
  File "/opt/conda/lib/python3.8/site-packages/billiard/pool.py", line 853, in on_state_change
    state_handlers[state](*args)
  File "/opt/conda/lib/python3.8/site-packages/billiard/pool.py", line 833, in on_ready
    putlock.release()
  File "/opt/conda/lib/python3.8/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/opt/conda/lib/python3.8/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/opt/conda/lib/python3.8/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/opt/conda/lib/python3.8/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/opt/conda/lib/python3.8/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/opt/conda/lib/python3.8/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/opt/conda/lib/python3.8/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
```

and again keeps going ...

```
  File "/opt/conda/lib/python3.8/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/request.py", line 651, in execute_using_pool
    if (self.expires or task_id in revoked_tasks) and self.revoked():
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/request.py", line 424, in revoked
    self._announce_revoked(
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/request.py", line 406, in _announce_revoked
    self.task.backend.mark_as_revoked(
  File "/opt/conda/lib/python3.8/site-packages/celery/backends/base.py", line 228, in mark_as_revoked
    self.store_result(task_id, exc, state,
  File "/opt/conda/lib/python3.8/site-packages/celery/backends/base.py", line 440, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/opt/conda/lib/python3.8/site-packages/celery/backends/base.py", line 867, in _store_result
    self._set_with_state(self.get_key_for_task(task_id), self.encode(meta), state)
  File "/opt/conda/lib/python3.8/site-packages/celery/backends/base.py", line 744, in _set_with_state
    return self.set(key, value)
  File "/opt/conda/lib/python3.8/site-packages/celery/backends/redis.py", line 380, in set
    return self.ensure(self._set, (key, value), **retry_policy)
  File "/opt/conda/lib/python3.8/site-packages/celery/backends/redis.py", line 364, in ensure
    return retry_over_time(
  File "/opt/conda/lib/python3.8/site-packages/kombu/utils/functional.py", line 313, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/celery/backends/redis.py", line 389, in _set
    pipe.execute()
  File "/opt/conda/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/opt/conda/lib/python3.8/site-packages/redis/client.py", line 3894, in _execute_transaction
    self.parse_response(connection, '_')
  File "/opt/conda/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/opt/conda/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/opt/conda/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/opt/conda/lib/python3.8/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/opt/conda/lib/python3.8/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/opt/conda/lib/python3.8/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/opt/conda/lib/python3.8/site-packages/redis/_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
RecursionError: maximum recursion depth exceeded while calling a Python object
[2021-04-21 03:39:46,533: ERROR/MainProcess] Error on stopping Pool: RecursionError('maximum recursion depth exceeded')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "/opt/conda/lib/python3.8/site-packages/celery/worker/request.py", line 652, in execute_using_pool
    raise TaskRevokedError(task_id)
celery.exceptions.TaskRevokedError: 5ccb493c-7a23-468f-9016-2a6d21d84d0c
```

and here we see the source

**Comment by thedrow** [comment]
Could you please try reproducing the error with #6654?

Don't enable the feature flag. It is not necessary.
I fixed a bug where `Request._announce_revoked` is called twice.

**Comment by nicolaerosia** [comment]
@thedrow I could try. Basically I need to make an environment where I push lots of tasks that are expired and then start the worker.

I am seeing this only with redis because it's not able to drop expired tasks from the queue. With RabbitMQ this never happened because I believe expired tasks never get to the workers because the broker drops them on his behalf.

**Comment by thedrow** [comment]
> 
> 
> @thedrow I could try. Basically I need to make an environment where I push lots of tasks that are expired and then start the worker.

That would be most helpful.

**Comment by nicolaerosia** [comment]
> Could you please try reproducing the error with #6654?
> 
> Don't enable the feature flag. It is not necessary.
> I fixed a bug where `Request._announce_revoked` is called twice in [32ed54d](https://github.com/celery/celery/commit/32ed54d061d8ad6b54bc4dc41ab0805a8d06716a).

@thedrow 
Actually I see this also with RabbitMQ as well and I'm running celery==5.1.0b2.
The commit you've referenced is not longer part of a branch, did you drop it?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/request.py", line 688, in execute_using_pool
    raise TaskRevokedError(task_id)
celery.exceptions.TaskRevokedError: 0cd4c7c3-a16c-4304-9568-984cb6a1cddc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/request.py", line 688, in execute_using_pool
    raise TaskRevokedError(task_id)
celery.exceptions.TaskRevokedError: ceed5e24-fb1c-45f7-b5fd-bc7794573f30

During handling of the above exception, another exception occurred:
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.9/site-packages/celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 361, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
    next(it)
  File "/usr/local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 308, in _recv_message
    callback(message)
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 853, in on_state_change
    state_handlers[state](*args)
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 833, in on_ready
    putlock.release()
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 229, in _process_task
[...]
  File "/usr/local/lib/python3.9/site-packages/kombu/abstract.py", line 45, in <dictcomp>
    attr: f(getattr(self, attr), type) for attr, type in self.attrs
  File "/usr/local/lib/python3.9/site-packages/kombu/abstract.py", line 43, in f
    return type(obj) if type and obj is not None else obj
RecursionError: maximum recursion depth exceeded while calling a Python object

[...]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 0 Job: 51869.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1796, in safe_apply_callback
    fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/request.py", line 580, in on_failure
    error('Task handler raised error: %r', exc,
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/site-packages/celery/utils/log.py", line 145, in format
    msg = logging.Formatter.format(self, record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 671, in format
    record.exc_text = self.formatException(record.exc_info)
  File "/usr/local/lib/python3.9/site-packages/celery/utils/log.py", line 141, in formatException
    r = logging.Formatter.formatException(self, ei)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 621, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/usr/local/lib/python3.9/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/usr/local/lib/python3.9/traceback.py", line 493, in __init__
    context = TracebackException(
  File "/usr/local/lib/python3.9/traceback.py", line 493, in __init__
    context = TracebackException(
  File "/usr/local/lib/python3.9/traceback.py", line 493, in __init__
    context = TracebackException(
  [Previous line repeated 475 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by nicolaerosia** [comment]
Actually I see it is included in https://github.com/celery/celery/commit/934a2271c1636364486eb737a598d224e5184cf8 which is part of 5.1.0b2, do you have another idea ? :) I would be happy to test

**Comment by thedrow** [comment]
None currently.

**Comment by thedrow** [comment]
We released Celery 5.1.1.
I think it should fix your issue but I'm not 100% sure.

If it doesn't, we'll take care of it in our next release.

**Comment by nicolaerosia** [comment]
@thedrow i'll give it a try, thanks for the headsup!

**Comment by nicolaerosia** [comment]
@thedrow it's still in 5.1.2, I would like to help you debug this.

The log contains this hundreds of times:
```
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/semaphore.py", line 72, in release
    waiter(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 229, in _process_task
    self._quick_release()   # Issue 877
```
I can't understand how can this happen here:
https://github.com/celery/celery/blob/master/celery/worker/worker.py#L223

How do we end up calling from `self._quick_release()` when we have `TaskRevokedError` the function `_process_task` again so we end up again in calling `self._quick_release()`?

**Comment by nicolaerosia** [comment]
@thedrow for all tasks I send I set an expiry time, however I "feel" that this expiry time is not translated to `x-message-ttl` when the event is sent to RabbitMQ.
I don't have an `x-message-ttl` set at the queue level.

The documentation is not very clear on how "expires" is translated to the backend.
I understand that if a task is received and it is expired, it will trigger a RevokedTask. However, in my case with RabbitMQ, I should not receive expired tasks because they should be dropped by the broker. If I do get expired tasks, it would be because until I get to take a look at the task, it expired (they were close to expiry).

I did a grep on `expires` in the source code and read the changelog/whatsnew however I can't say I understand if `expires` is translated to per task `expiration` field, https://www.rabbitmq.com/ttl.html#per-message-ttl-in-publishers

In kombu I see there is a parameter for expiration at message level, https://github.com/celery/kombu/blob/master/kombu/messaging.py#L114
Any ideas?

**Comment by nicolaerosia** [comment]
@thedrow I was wrong - I see the `expiration` is being set.

I think I understand what is happening now.
I have a celery app with `concurrency` set to `16` and `prefetch` to `64`.
Now, I haven't digged into how the master process checks for expired tasks, but I assume the parent process does it, and because my tasks sometime take a lot of time, and because it prefetches 16 * 64 = 1024 tasks, most/if not all of them will be expired, and somehow it gets stuck in that recursion.

Does this help?

**Comment by thedrow** [comment]
It's a nudge in the right direction.
Can you reproduce this issue when you set the prefetch count to 16?

**Comment by nicolaerosia** [comment]
@thedrow I was wrong - celery never transmits the expiration to AMQP.

Celery uses kombu to transmit messages, this function, https://github.com/celery/kombu/blob/master/kombu/messaging.py#L118
If you setup a breakpoint here, you will see that `expiration` is always None.

The problem comes from the fact that `expires`, which is the task argument, does not get passed to the function mentioned up, see here: https://github.com/celery/celery/blob/master/celery/app/base.py#L767

I believe the right fix is to add something like
```
if expires is not None:
  options["expiration"] = expires
```
what do you think?

**Comment by thedrow** [comment]
> I believe the right fix is to add something like
> 
> ```
> if expires is not None:
>   options["expiration"] = expires
> ```
> 
> what do you think?

Isn't your suggestion contradicting what you did in #6957?

**Comment by nicolaerosia** [comment]
@thedrow what do you mean? this is what I ended up implementing - it's just that expires can also be a `datetime`, hence it ended up like this:
```
        if expires is not None:
            if isinstance(expires, datetime):
                expires_s = (expires - self.now()).total_seconds()
            else:
                expires_s = expires

            if expires_s < 0:
                expires_s = 0

            options["expiration"] = expires_s
```

**Comment by thedrow** [comment]
So the problem should be fixed, right?
What am I missing here?

**Comment by nicolaerosia** [comment]
@thedrow basically now that I added the expiration I will never get enough expired tasks to trigger the maximum recursion

**Comment by auvipy** [comment]
so we can close this issue

**Comment by nicolaerosia** [comment]
the issue is still there, but I don't have bandwidth to provide a reproducer since I have this workaround

**Comment by thedrow** [comment]
I'd like to fix this issue for everyone so could you please explain what you did and why?

**Comment by gabor-boros** [comment]
@thedrow @auvipy Could you please help me with how should the above issue handled?

In case that's the normal behavior from now on, I'd need to update the integrations on my side using Celery before upgrading to 5.2.x, otherwise the PR that causes (as I can see multiple) issues should be reverted (?).

**Comment by nicolaerosia** [comment]
@gabor-boros  can you please provide a reproducer?

Which multiple issues? Please provide the github issue ids

**Comment by nicolaerosia** [comment]
> I'd like to fix this issue for everyone so could you please explain what you did and why?

With RabbitMQ, if you have in a queue 100k tasks that are all expired (remember, we were not setting the expiration at RabbitMQ level, so the tasks are still in the queue), the worker will go into a RecursionError.

My workaround here is to leverage the expiration at MQ level, so I will never receive an expired task in the first place (well, actually you can get some expired tasks if they expire after you get them from MQ and until you actually do the check)

**Comment by nicolaerosia** [comment]
@thedrow @auvipy what @gabor-boros is reporting is the following:
`now()` returns a tz aware datetime, see https://github.com/celery/celery/blob/master/celery/app/base.py#L927

I believe he passes in a non-tz aware datetime, and that's why we end up with the error here:
https://github.com/celery/celery/blob/master/celery/app/base.py#L737
`(expires - self.now())`, expires has no tz, self.now() has tz.

In another place in celery I see that you're taking the now to have the tz of expires, https://github.com/celery/celery/blob/master/celery/worker/request.py#L392
Would this be ok as a fix?

**Comment by auvipy** [comment]
can you please come with a draft PR?

**Comment by thedrow** [comment]
Yes, that would be the right fix.

**Comment by gabor-boros** [comment]
> what @gabor-boros is reporting is the following [...]

Yes, that's what I meant in my previous comment.

**Comment by nicolaerosia** [comment]
OK, I'll make a PR then

**Comment by gabor-boros** [comment]
@nicolaerosia @thedrow @auvipy The fix for the issue I mentioned above: https://github.com/celery/celery/pull/7065

Please note that this issue affects v5.2.0rc1, so the fix should be cherry-picked there.

**Comment by auvipy** [comment]
this is a bug fix so we will include the fix in celery 5.2.1 release soon. we have couple more fixes as  well.

**Comment by Elias-SLH** [comment]
It seems that the bug is still present, any update ?

**Comment by auvipy** [comment]
> It seems that the bug is still present, any update ?

so https://github.com/celery/celery/pull/7065 didn't fix the problem, right?

**Comment by gabor-boros** [comment]
@auvipy @Elias-SLH we are using the fix in production for almost a year and never seen the issue again. If it still exists (and it is the same bug), could you please help with exact steps how to reproduce the issue?

**Comment by auvipy** [comment]
> @auvipy @Elias-SLH we are using the fix in production for almost a year and never seen the issue again. If it still exists (and it is the same bug), could you please help with exact steps how to reproduce the issue?

closing it now then!
