### ISSUE TITLE
Retry not working properly when using `chunks`

### ISSUE THREAD

**Issue by magnusja** [celery/celery#6755]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [X] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

#### Related Issues

- https://stackoverflow.com/questions/30653216/retry-behavior-for-celery-tasks-within-a-chunk
- https://stackoverflow.com/questions/62735109/celery-chunks-tasks-never-retry

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.8.3
* **Minimal Celery Version**: 5.0.5
* **Minimal Broker Version**: docker.io/bitnami/rabbitmq:3.8.15-debian-10-r0

## Minimally Reproducible Test Case

I have a task implemented in a worker like this

<details>
<p>

```python
class RateLimitedTask(Task):
    autoretry_for = [NoTokenAvailableError]
    throws = [NoTokenAvailableError]
    retry_kwargs = {"max_retries": 300, "countdown": 1}  # delay until task is retried

    def __init__(self, external_api_name: str, token_queue_suffix: str):
        # A task is not instantiated for every request,
        # but is registered in the task registry as a global instance.
        self._token_queue_name = external_api_name.upper() + token_queue_suffix.upper()
        self._connection = self.app.connection_for_read(connect_timeout=5)

    def _is_token_available(self) -> bool:
        # TODO reuse channels
        # TODO set connection timeout for getting channel
        with self._connection.channel() as channel:
            try:
                msg = channel.basic_get(self._token_queue_name)
                if msg is not None:
                    channel.basic_ack(msg.delivery_tag)
                    celery_logger.debug(
                        f"Consumed 1 token from {self._token_queue_name}"
                    )
                    return True
            except (BrokenPipeError, NotFound, KeyError) as e:
                celery_logger.error(
                    f"Could not get token from token queue {self._token_queue_name}: {e}"
                )
            except Exception as e:
                celery_logger.error(
                    f"Unexpected error: Could not get token from token queue {self._token_queue_name}: {e}"
                )
        return False

    def _run(self, *args, **kwargs):
        raise NotImplementedError

    def run(self, *args, **kwargs):
        if self._is_token_available():
            celery_logger.debug(
                f"Token is available for {EXTERNAL_API_NAME}, performing task."
            )
            return self._run(*args, **kwargs)
        else:
            celery_logger.debug(
                f"No token available for {EXTERNAL_API_NAME}, retrying task."
            )
            raise NoTokenAvailableError


class OutsourcingTask(RateLimitedTask):
    def __init__(self, external_api_name: str, token_queue_suffix: str):
        super().__init__(
            external_api_name=external_api_name, token_queue_suffix=token_queue_suffix
        )
        self.ignore_result = True

    @property
    def name(self) -> str:
        # This is the name to use when calling it from celery.send_task() elsewhere
        return str(self.__class__.__name__)

    def _run(self, payload_json: str, *args, **kwargs):
        task_data = SourcingTaskData(**json.loads(payload_json))
        address = settings.handler_settings.address
        celery_logger.info(f"Posting task data {task_data} to {address}.")
        requests.post(
            address,
            json={
               ...
            },
        )
```

We are querying different API providers and would like to adhere to the rate limiting. Hence, if there is no token available task shall be retried after a second to adhere to rate limit.

In the producer we just called `send_task` hundreds of times.
```python
async_result: AsyncResult = celery.send_task(
                self._task_name,
                task_payload,
                queue=queue_name,
                expires=REQUEST_TASK_TTL_SECONDS,
            )
```

Unfortunately this takes like a minute or so to queue a couple of hundred of tasks. Googling I found out that `send_task` comes with lots of communication overhead with each call and that using `chunks` is a solid option. We are queuing now like this:

```python
tasks = ((task_data.json(),) for task_data in tasks)
chunked_task = chunks(
    task=self._task_name, it=iter(tasks), n=10, app=celery
)

return chunked_task.apply_async(queue=queue_name.upper())
```

Unfortunately this seems to break our retry mechanism:

```
[2021-05-04 14:58:57,169: ERROR/ForkPoolWorker-5] Task celery.starmap[c05be451-6feb-426f-b5d6-9728c4edbc8b] raised unexpected: NoTokenAvailableError()
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 405, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 697, in __protected_call__
return self.run(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/celery/app/builtins.py", line 120, in xstarmap
return [task(*item) for item in it]
File "/usr/local/lib/python3.8/site-packages/celery/app/builtins.py", line 120, in <listcomp>
return [task(*item) for item in it]
File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 698, in __protected_call__
return orig(self, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 388, in __call__
return self.run(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
ret = task.retry(exc=exc, **retry_kwargs)
File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 687, in retry
raise_with_context(exc or Retry('Task can be retried', None))
File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 34, in run
return task._orig_run(*args, **kwargs)
File "/receiver/src/receiver/celery.py", line 78, in run
raise NoTokenAvailableError
receiver.celery.NoTokenAvailableError
```

The corresponding part of the code (https://github.com/celery/celery/blob/master/celery/app/task.py#L695):

```python
# Not in worker or emulated by (apply/always_eager),
# so just raise the original exception.
if request.called_directly:
    # raises orig stack if PyErr_Occurred,
    # and augments with exc' if that argument is defined.
    raise_with_context(exc or Retry('Task can be retried', None))
```

</p>
</details>

# Expected Behavior

Would be great if retry would just work just like if tasks are not chunked!

# Actual Behavior

See above

**Comment by thedrow** [comment]
Is there a more minimal reproducible test case?
I'd like to verify that the problem is with Celery before continuing to triage this bug report.
Is retry always broken with chunks?

**Comment by magnusja** [comment]
Hey there, and thanks for getting back to me.

tbh I think it is generally broken. That is also why I posted this, because I am not sure how it should work. Is it supposed to retry (ie. getting re-queued) the whole chunk or a particular task? 


From the code:
```
# Not in worker or emulated by (apply/always_eager),
# so just raise the original exception.
if request.called_directly:
    # raises orig stack if PyErr_Occurred,
    # and augments with exc' if that argument is defined.
    raise_with_context(exc or Retry('Task can be retried', None))
```

(https://github.com/celery/celery/blob/master/celery/app/task.py#L695)

I think due to a task being chunked and therefore wrapped by another Task (ie. the `chunk` task), this part does not retry the failed task. I suspect that the chunked task runs all tasks locally, and therefore this `called_directly` property is `true`. But if a task was called directly there is no backend like rabbitmq available (or might not be in certain occasions), that is why it is not retried. This this particular situation this is obviously untrue, it just looks like that, so the backend could definitely be used to retry the task I just dont know how to tell that to celery.
Anyways, I was hoping someone with some more in depth knowledge on the inner workings could shed some light on this..

**Comment by AIexanderDicke** [comment]
Is there any progress on this issue?

**Comment by auvipy** [comment]
no, so contributions are welcome.
