### ISSUE TITLE
`group.link_error()` makes the errback signature immutable

### ISSUE THREAD

**Issue by maybe-sybr** [celery/celery#6766]
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] I have included the contents of ``pip freeze`` in the issue.
* [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* behaviour was introduced in ff72f55c4 as part of work for #1120

#### Possible Duplicates
* None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```

```

</p>
</details>

# Steps to Reproduce
## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```

```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case
Roughly:

1. Make an errback which expects to receive the request ID or the `(request, exc, traceback)` tuple
1. `group_sig = celery.group(die.s())`
1. `group_sig.link_error(errback_sig)`
1. `group_sig()` and watch it break in the worker

<details>
<p>

```python

```

</p>
</details>

# Expected Behavior
* errback is called with the expected arguments

# Actual Behavior
* errback signature to be run is immutable and therefore is not passed the normal errback args
* errback invocation blows up due to missing arguments like:

```
[2021-05-11 13:21:27,653: ERROR/MainProcess] Pool callback raised exception: TypeError("notify_exc() missing 3 required positional arguments: '_', 'exc', and 'tb'")
Traceback (most recent call last):
  File "/path/to/proj/.venv/lib64/python3.8/site-packages/billiard/pool.py", line 1796, in safe_apply_callback
    fun(*args, **kwargs)
  File "/path/to/proj/.venv/lib64/python3.8/site-packages/celery/worker/request.py", line 567, in on_failure
    self.task.backend.mark_as_failure(
  File "/path/to/proj/.venv/lib64/python3.8/site-packages/celery/backends/base.py", line 213, in mark_as_failure
    self._call_task_errbacks(request, exc, traceback)
  File "/path/to/proj/.venv/lib64/python3.8/site-packages/celery/backends/base.py", line 236, in _call_task_errbacks
    errback(request, exc, traceback)
  File "/path/to/proj/.venv/lib64/python3.8/site-packages/celery/canvas.py", line 169, in __call__
    return self.type(*args, **kwargs)
  File "/path/to/proj/.venv/lib64/python3.8/site-packages/celery/app/trace.py", line 727, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/path/to/proj/.venv/lib64/python3.8/site-packages/celery/app/task.py", line 389, in __call__
    return self.run(*args, **kwargs)
TypeError: notify_exc() missing 3 required positional arguments: '_', 'exc', and 'tb'
```

**Comment by maybe-sybr** [comment]
IMO this is not a good choice for celery to be making, for either errbacks or callbacks since it breaks the general assumption that they will receive the result of the thing they are linked to or some information about the failure respectively. That said, it might be the case that for callbacks this is done to paper over the fact that only the 0th task actually needs to be completed and the callback won't receive the aggregate result of the entire group.

There is a hack in `group.link_error()` which is apparently there to deal with some mocking issues so presumably there are some tests for this stuff which might clarify what the expectation of behaviour was (and maybe still should be).
