### ISSUE TITLE
Errors in task in chord in chain not handled correctly

### ISSUE THREAD

**Issue by aditya051293** [celery/celery#6792]
**Checklist**

* version 5.1.0 of celery

**Steps to reproduce**

```
import celery
from celery.app.task import Task
from celery import shared_task

@shared_task(base=Task)
def echo_task(taskdata):
    return taskdata

@shared_task(base=Task)
def error_task(taskdata):
	1/0
	return taskdata

exec_list = [error_task.s(), echo_task.s()]
x = celery.chord(exec_list, echo_task.s())

y = celery.chain([x, echo_task.s()])

result = y(None).get()
```

**Expectation**

`celery.exceptions.ChordError: Dependency a812ae61-a99c-45c8-9d8f-119b36fcbeb3 raised ZeroDivisionError('division by zero',)`

**Actual Behaviour**

Raising error while handling.

```
Exception raised outside body: TypeError('sequence item 1: expected a bytes-like object, NoneType found',):
Traceback (most recent call last):
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 519, in on_chord_part_return
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 519, in <listcomp>
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 425, in _unpack_chord_result
    raise ChordError(f'Dependency {tid} raised {retval!r}')
celery.exceptions.ChordError: Dependency b07a3b72-89c8-4c6b-9d7b-be24cda9af61 raised TaskException('ZeroDivisionError: division by zero',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/app/trace.py", line 518, in trace_task
    uuid, retval, task_request, publish_result,
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 163, in mark_as_done
    self.on_chord_part_return(request, state, result)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 538, in on_chord_part_return
    return self.chord_error_from_stack(callback, exc)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 297, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 304, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, exception_info.traceback)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 172, in mark_as_failure
    traceback=traceback, request=request)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 478, in store_result
    request=request, **kwargs)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 898, in _store_result
    current_meta = self._get_task_meta_for(task_id)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 920, in _get_task_meta_for
    meta = self.get(self.get_key_for_task(task_id))
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 799, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found
[E 2021-05-31 21:17:32,921 celery.app.trace] Task echo_task[0635a7ab-08c5-4872-ae57-785b35c5f4e4] raised unexpected: TypeError('sequence item 1: expected a bytes-like object, NoneType found',)
Traceback (most recent call last):
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 519, in on_chord_part_return
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 519, in <listcomp>
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 425, in _unpack_chord_result
    raise ChordError(f'Dependency {tid} raised {retval!r}')
celery.exceptions.ChordError: Dependency b07a3b72-89c8-4c6b-9d7b-be24cda9af61 raised TaskException('ZeroDivisionError: division by zero',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/app/trace.py", line 518, in trace_task
    uuid, retval, task_request, publish_result,
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 163, in mark_as_done
    self.on_chord_part_return(request, state, result)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/redis.py", line 538, in on_chord_part_return
    return self.chord_error_from_stack(callback, exc)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 297, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 304, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, exception_info.traceback)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 172, in mark_as_failure
    traceback=traceback, request=request)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 478, in store_result
    request=request, **kwargs)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 898, in _store_result
    current_meta = self._get_task_meta_for(task_id)
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 920, in _get_task_meta_for
    meta = self.get(self.get_key_for_task(task_id))
  File "/home/aditya/local/venv/lib/python3.6/site-packages/celery/backends/base.py", line 799, in get_key_for_task
    self.task_keyprefix, key_t(task_id), key_t(key),
TypeError: sequence item 1: expected a bytes-like object, NoneType found
```

**Addition to get it working**

Every time I create a celery.chord 'x'
Add below line after
`x = celery.chain(echo_task.s(), celery.chord(x, echo_task.s()))`

**Comment by XuCcc** [comment]
same problem,my code like 

```python
        flow = chain(
            group(good.si(),bad.si()),
            upload_job_data.si(),
            upload_asset_data.si()
        ).on_error(
            upload_error_job_data.s(info=self.info)
        )
```

log output


```bash
[2022-02-11 10:44:23,017: ERROR/ForkPoolWorker-10] Task core.engine.tasks.rule.run_rule[a2123704-bbc4-47f1-8ca4-9d0734d57c80] raised unexpected: TypeError('sequence item 1: expected a bytes-like object, NoneType found')             Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/sourcecode/miniscanner/core/engine/tasks/rule.py", line 54, in run_rule                                   scanner.verify()
  File "<string>", line 51, in verify
KeyError: 'sad'

During handling of the above exception, another exception occurred:
                                                                                                                    Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/redis.py", line 520, in on_chord_part_return                                                                               resl = [unpack(tup, decode) for tup in resl]
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/redis.py", line 520, in <listcomp>                                                                                         resl = [unpack(tup, decode) for tup in resl]
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/redis.py", line 426, in _unpack_chord_result                                                                               raise ChordError(f'Dependency {tid} raised {retval!r}')
celery.exceptions.ChordError: Dependency a2123704-bbc4-47f1-8ca4-9d0734d57c80 raised KeyError('sad')
                                                                                                                    During handling of the above exception, another exception occurred:


Traceback (most recent call last):                                                                                    File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 468, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)                                                           File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 379, in on_error
    R = I.handle_error_state(                                                                                         File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 178, in handle_error_state
    return {                                                                                                          File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 225, in handle_failure
    task.backend.mark_as_failure(                                                                                     File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/base.py", line 177, in mark_as_failure
    self.on_chord_part_return(request, state, exc)                                                                    File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/redis.py", line 539, in on_chord_part_return
    return self.chord_error_from_stack(callback, exc)
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/base.py", line 309, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/base.py", line 316, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, exception_info.traceback)
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/base.py", line 172, in mark_as_failure
    self.store_result(task_id, exc, state,
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/base.py", line 956, in _store_result
    current_meta = self._get_task_meta_for(task_id)
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/base.py", line 978, in _get_task_meta_for
    meta = self.get(self.get_key_for_task(task_id))
  File "/root/.cache/pypoetry/virtualenvs/miniscanner--a4Dn15j-py3.8/lib/python3.8/site-packages/celery/backends/base.py", line 856, in get_key_for_task
    return key_t('').join([
TypeError: sequence item 1: expected a bytes-like object, NoneType found
```

**Comment by mlembke** [comment]
It seems it's still an issue in 5.4.0. When I create a chord consisting of header tasks and a callback task that is a chain, then I get `ValueError: task_id must not be empty. Got None instead.` when one of the header tasks fails.

Any chances to have it fixed soon?
I'm using celery 5.4.0 as mentioned and redis 4.6.0

**Comment by DavraYoung** [comment]
same error. In my case the .get() is gone in infinite loop because of this.
`chord(tasks, chain(result_effect, post_effect))`
```log
[2024-05-28 08:06:08,744: ERROR/MainProcess] Chord '728c02da-f8e1-4080-890c-3e02d1c4fcd5' raised: ChordError('Dependency f8c21096-da06-4ff5-bbc8-0c56444d26d6 raised WorkerException("Exception(\'Random exception\')", {\'id\': \'f8c21096-da06-4ff5-bbc8-0c56444d26d6\', \'logs\': [], \'progress\': 0.0, \'result\': None, \'is_reporter_output\': True})')
transcription_worker  | Traceback (most recent call last):
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/redis.py", line 520, in on_chord_part_return
transcription_worker  |     resl = [unpack(tup, decode) for tup in resl]
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/redis.py", line 520, in <listcomp>
transcription_worker  |     resl = [unpack(tup, decode) for tup in resl]
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/redis.py", line 426, in _unpack_chord_result
transcription_worker  |     raise ChordError(f'Dependency {tid} raised {retval!r}')
transcription_worker  | celery.exceptions.ChordError: Dependency f8c21096-da06-4ff5-bbc8-0c56444d26d6 raised WorkerException("Exception('Random exception')", {'id': 'f8c21096-da06-4ff5-bbc8-0c56444d26d6', 'logs': [], 'progress': 0.0, 'result': None, 'is_reporter_output': True})
transcription_worker  | [2024-05-28 08:06:08,747: ERROR/MainProcess] Task transcription[e2124809-75db-4795-bf00-fd686b6ef9ac] raised unexpected: TypeError('sequence item 1: expected a bytes-like object, NoneType found')
transcription_worker  | Traceback (most recent call last):
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/redis.py", line 520, in on_chord_part_return
transcription_worker  |     resl = [unpack(tup, decode) for tup in resl]
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/redis.py", line 520, in <listcomp>
transcription_worker  |     resl = [unpack(tup, decode) for tup in resl]
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/redis.py", line 426, in _unpack_chord_result
transcription_worker  |     raise ChordError(f'Dependency {tid} raised {retval!r}')
transcription_worker  | celery.exceptions.ChordError: Dependency f8c21096-da06-4ff5-bbc8-0c56444d26d6 raised WorkerException("Exception('Random exception')", {'id': 'f8c21096-da06-4ff5-bbc8-0c56444d26d6', 'logs': [], 'progress': 0.0, 'result': None, 'is_reporter_output': True})
transcription_worker  |
transcription_worker  | During handling of the above exception, another exception occurred:
transcription_worker  |
transcription_worker  | Traceback (most recent call last):
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 518, in trace_task
transcription_worker  |     task.backend.mark_as_done(
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/base.py", line 164, in mark_as_done
transcription_worker  |     self.on_chord_part_return(request, state, result)
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/redis.py", line 539, in on_chord_part_return
transcription_worker  |     return self.chord_error_from_stack(callback, exc)
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/base.py", line 309, in chord_error_from_stack
transcription_worker  |     return backend.fail_from_current_stack(callback.id, exc=exc)
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/base.py", line 316, in fail_from_current_stack
transcription_worker  |     self.mark_as_failure(task_id, exc, exception_info.traceback)
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/base.py", line 172, in mark_as_failure
transcription_worker  |     self.store_result(task_id, exc, state,
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/base.py", line 528, in store_result
transcription_worker  |     self._store_result(task_id, result, state, traceback,
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/base.py", line 956, in _store_result
transcription_worker  |     current_meta = self._get_task_meta_for(task_id)
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/base.py", line 978, in _get_task_meta_for
transcription_worker  |     meta = self.get(self.get_key_for_task(task_id))
transcription_worker  |   File "/usr/local/lib/python3.9/dist-packages/celery/backends/base.py", line 856, in get_key_for_task
transcription_worker  |     return key_t('').join([
transcription_worker  | TypeError: sequence item 1: expected a bytes-like object, NoneType found```

**Comment by Nusnus** [comment]
The `ValueError: task_id must not be empty. Got None instead.` error was fixed here: https://github.com/celery/celery/pull/8798

Are you saying it still reproduces?

@DavraYoung can you check if it reproduces with the current `main` please?

**Comment by artemijan** [comment]
any updates? version 5.4.0 is still problematic

**Comment by thedrow** [comment]
@artemijan Can you check if this still reproduces with main? Thanks.

**Comment by NazarDudiak** [comment]
> @artemijan Can you check if this still reproduces with main? Thanks.
```shell
 [2024-08-19 09:20:22,043: ERROR/ForkPoolWorker-5] Task assistant.tasks.channels_generation[e5b492ec-ca00-40ec-911f-b5917205d009] raised unexpected: ValueError('task_id must not be empty. Got None instead.')
 Traceback (most recent call last):
   File "/usr/local/lib/python3.12/site-packages/celery/backends/redis.py", line 528, in on_chord_part_return
     resl = [unpack(tup, decode) for tup in resl]
             ^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/redis.py", line 434, in _unpack_chord_result
     raise ChordError(f'Dependency {tid} raised {retval!r}')
 celery.exceptions.ChordError: Dependency 0163a4bc-da03-48f3-99eb-acabc9e0a0a8 raised AttributeError("'NoneType' object has no attribute 'group'")

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 520, in trace_task
     task.backend.mark_as_done(
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 159, in mark_as_done
     self.on_chord_part_return(request, state, result)
   File "/usr/local/lib/python3.12/site-packages/celery/backends/redis.py", line 547, in on_chord_part_return
     return self.chord_error_from_stack(callback, exc)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 304, in chord_error_from_stack
     return backend.fail_from_current_stack(callback.id, exc=exc)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 311, in fail_from_current_stack
     self.mark_as_failure(task_id, exc, exception_info.traceback)
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 167, in mark_as_failure
     self.store_result(task_id, exc, state,
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 526, in store_result
     self._store_result(task_id, result, state, traceback,
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 973, in _store_result
     current_meta = self._get_task_meta_for(task_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 995, in _get_task_meta_for
     meta = self.get(self.get_key_for_task(task_id))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 869, in get_key_for_task
     raise ValueError(f'task_id must not be empty. Got {task_id} instead.')
 ValueError: task_id must not be empty. Got None instead.
```

Unfortunately, I still have this problem :(
Celery version `5.4.0`
Radis version `5.0.4`

Does anyone know when we can expect a fix?

**Comment by NazarDudiak** [comment]
> @artemijan Can you check if this still reproduces with main? Thanks.
```shell
 [2024-08-19 09:20:22,043: ERROR/ForkPoolWorker-5] Task assistant.tasks.channels_generation[e5b492ec-ca00-40ec-911f-b5917205d009] raised unexpected: ValueError('task_id must not be empty. Got None instead.')
 Traceback (most recent call last):
   File "/usr/local/lib/python3.12/site-packages/celery/backends/redis.py", line 528, in on_chord_part_return
     resl = [unpack(tup, decode) for tup in resl]
             ^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/redis.py", line 434, in _unpack_chord_result
     raise ChordError(f'Dependency {tid} raised {retval!r}')
 celery.exceptions.ChordError: Dependency 0163a4bc-da03-48f3-99eb-acabc9e0a0a8 raised AttributeError("'NoneType' object has no attribute 'group'")

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 520, in trace_task
     task.backend.mark_as_done(
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 159, in mark_as_done
     self.on_chord_part_return(request, state, result)
   File "/usr/local/lib/python3.12/site-packages/celery/backends/redis.py", line 547, in on_chord_part_return
     return self.chord_error_from_stack(callback, exc)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 304, in chord_error_from_stack
     return backend.fail_from_current_stack(callback.id, exc=exc)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 311, in fail_from_current_stack
     self.mark_as_failure(task_id, exc, exception_info.traceback)
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 167, in mark_as_failure
     self.store_result(task_id, exc, state,
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 526, in store_result
     self._store_result(task_id, result, state, traceback,
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 973, in _store_result
     current_meta = self._get_task_meta_for(task_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 995, in _get_task_meta_for
     meta = self.get(self.get_key_for_task(task_id))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/site-packages/celery/backends/base.py", line 869, in get_key_for_task
     raise ValueError(f'task_id must not be empty. Got {task_id} instead.')
 ValueError: task_id must not be empty. Got None instead.
```

Unfortunately, I still have this problem :(
Celery version `5.4.0`
Redis version `5.0.4`

Does anyone know when we can expect a fix?

**Comment by stuton** [comment]
> Are you saying it still reproduces?
@DavraYoung can you check if it reproduces with the current main please?

@Nusnus yes, it still reproduces with the current main

**Comment by dfm88** [comment]
This should have solved by https://github.com/celery/celery/pull/9774

**Comment by auvipy** [comment]
thanks diego!
