### ISSUE TITLE
Exception when using SQS backend

### ISSUE THREAD

**Issue by make-ing** [celery/celery#6809]
# Checklist
* [ ] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [ ] I have verified that the issue exists against the `master` branch of Celery.
* [ ] I have included the contents of ``pip freeze`` in the issue.
* [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information
* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* https://github.com/celery/celery/issues/3932
* https://github.com/boto/boto3/issues/1777

#### Possible Duplicates
* None

## Environment & Settings
**Celery version**: 5.0.5
<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```

```

</p>
</details>

# Steps to Reproduce
## Required Dependencies
* **Minimal Python Version**: 3.9
* **Minimal Celery Version**: 5.0.5
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages
<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```

```

</p>
</details>

### Other Dependencies
<details>
<p>
Running celery with the AWS SQS backend.
</p>
</details>

## Minimally Reproducible Test Case
<details>
<p>

I can not reproduce this error at the moment, but i assume it has something to do with the SQS service from AWS not being available. They had a big issue this night ([news article](https://www.theregister.com/2021/06/11/aws_eu_central_1_incident/)). I found an old open issue from boto3 which i linked above.
I also want to add that we had the same error on two completly separated systems at almost the same time (5 seconds difference).

</p>
</details>

# Expected Behavior
Celery worker should continou running even when the SQS service is temporarily not available.

# Actual Behavior
The celery worker threw and execption and stoppen running.

```
[2021-06-10 23:26:37,315: CRITICAL/MainProcess] Unrecoverable error: ClientError('An error occurred (Unknown) when calling the GetQueueUrl operation (reached max retries: 4): Unknown')
Traceback (most recent call last):
File "/app/venv/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
self.blueprint.start(self)
File "/app/venv/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
step.start(parent)
File "/app/venv/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
return self.obj.start()
File "/app/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 311, in start
blueprint.start(self)
File "/app/venv/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
step.start(parent)
File "/app/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 592, in start
c.loop(*c.loop_args())
File "/app/venv/lib/python3.8/site-packages/celery/worker/loops.py", line 81, in asynloop
next(loop)
File "/app/venv/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 298, in create_loop
item()
File "/app/venv/lib/python3.8/site-packages/vine/promises.py", line 160, in __call__
return self.throw()
File "/app/venv/lib/python3.8/site-packages/vine/promises.py", line 157, in __call__
retval = fun(*final_args, **final_kwargs)
File "/app/venv/lib/python3.8/site-packages/kombu/transport/SQS.py", line 513, in _schedule_queue
self._get_bulk_async(
File "/app/venv/lib/python3.8/site-packages/kombu/transport/SQS.py", line 530, in _get_bulk_async
return self._get_async(queue, maxcount, callback=callback)
File "/app/venv/lib/python3.8/site-packages/kombu/transport/SQS.py", line 539, in _get_async
return self._get_from_sqs(
File "/app/venv/lib/python3.8/site-packages/kombu/transport/SQS.py", line 566, in _get_from_sqs
queue_url = connection.get_queue_url(queue)
File "/app/venv/lib/python3.8/site-packages/kombu/asynchronous/aws/sqs/connection.py", line 43, in get_queue_url
res = self.sqs_connection.get_queue_url(QueueName=queue)
File "/app/venv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/app/venv/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Unknown) when calling the GetQueueUrl operation (reached max retries: 4): Unknown
```

**Comment by make-ing** [comment]
Hello to you all 👋...  Are there any news on this bug report? Is this something you would takle in the near future or what are you plans?

**Comment by auvipy** [comment]
you are welcome  to help diagnosis the issue

**Comment by galCohen88** [comment]
@make-ing This is probably a problem with queue definitions, have you tried using `predefined-queues`? https://docs.celeryproject.org/en/stable/getting-started/backends-and-brokers/sqs.html#predefined-queues

**Comment by auvipy** [comment]
Yeah indeed
