### ISSUE TITLE
python3.8.10 SyntaxError: invalid syntax  async keyword problem for celery

### ISSUE THREAD

**Issue by hltfaith** [celery/celery#6858]
## Problem description

<details>
<p>
Using environment Python 3.8, async keyword problem, does the celery version support it?
The following is the project error output
</p>
</details>

```python
(dynamic-authorization) changhao@kylinos-v10:~/data/gitlab/dynamic-authorization-server/server$ python manage.py celery worker -l info 
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/djcelery/management/commands/celery.py", line 22, in run_from_argv
    base.execute_from_commandline(
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/bin/celery.py", line 713, in execute
    return cls(
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/bin/worker.py", line 194, in run
    pool_cls = (concurrency.get_implementation(pool_cls) or
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/concurrency/__init__.py", line 29, in get_implementation
    return symbol_by_name(cls, ALIASES)
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/concurrency/prefork.py", line 20, in <module>
    from celery.concurrency.base import BasePool
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/concurrency/base.py", line 21, in <module>
    from celery.utils import timer2
  File "/home/changhao/.conda/envs/dynamic-authorization/lib/python3.8/site-packages/celery/utils/timer2.py", line 19
    from kombu.async.timer import Entry, Timer as Schedule, to_timestamp, logger
               ^
SyntaxError: invalid syntax
```

**Comment by auvipy** [comment]
you are using a very old unsupported version. use 4.4 or 5.1

**Comment by wuyuzhe** [comment]
my environtment show the same question
python  3.7.16
celery   3.1.26
django-celery 3.3.1
kombu 3.0.37

how to fix this problem

**Comment by wuyuzhe** [comment]
pip install django-celery==3.3.1 default will install celery 3.1.26。 and django-celery do not support celery version > 4.0

**Comment by wuyuzhe** [comment]
@auvipy

**Comment by auvipy** [comment]
answer is upgrade to celery 4.4 and use new django celery integrations

**Comment by wuyuzhe** [comment]
thank you for your answer.
