### ISSUE TITLE
Celery crashes with invalid file descriptor 11 and WorkerLostError

### ISSUE THREAD

**Issue by qlands** [celery/celery#6864]
All of a sudden our celery service is getting stuck (it does not process any tasks). In the log files we encountered:

```
[2021-07-19 11:50:10,500: INFO/MainProcess] Received task: climmob.products.packages.celerytasks.createPackages[a44428bd-2837-4aac-8fd9-9d95d832045a]  
[2021-07-19 11:50:11,126: ERROR/ForkPoolWorker-14] Thread 'ResultHandler' crashed: ValueError('invalid file descriptor 11')
Traceback (most recent call last):
  File "/opt/climmob_env/lib/python3.8/site-packages/billiard/pool.py", line 504, in run
    return self.body()
  File "/opt/climmob_env/lib/python3.8/site-packages/billiard/pool.py", line 899, in body
    for _ in self._process_result(1.0):  # blocking
  File "/opt/climmob_env/lib/python3.8/site-packages/billiard/pool.py", line 864, in _process_result
    ready, task = poll(timeout)
  File "/opt/climmob_env/lib/python3.8/site-packages/billiard/pool.py", line 1370, in _poll_result
    if self._outqueue._reader.poll(timeout):
  File "/opt/climmob_env/lib/python3.8/site-packages/billiard/connection.py", line 285, in poll
    return self._poll(timeout)
  File "/opt/climmob_env/lib/python3.8/site-packages/billiard/connection.py", line 463, in _poll
    r = wait([self], timeout)
  File "/opt/climmob_env/lib/python3.8/site-packages/billiard/connection.py", line 996, in wait
    return _poll(object_list, timeout)
  File "/opt/climmob_env/lib/python3.8/site-packages/billiard/connection.py", line 976, in _poll
    raise ValueError('invalid file descriptor %i' % fd)
ValueError: invalid file descriptor 11
[2021-07-19 11:50:11,205: ERROR/MainProcess] Process 'ForkPoolWorker-14' pid:26866 exited with 'exitcode 1'
[2021-07-19 11:50:21,534: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 1.')
Traceback (most recent call last):
  File "/opt/climmob_env/lib/python3.8/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 1.
[2021-07-19 11:51:31,613: INFO/MainProcess] Received task: climmob.products.qrpackages.celerytasks.createQR[2919e441-23b0-4d7b-a96d-1aa2e46bd3c2]  
```
Our configuration is:
```
# Names of nodes to start
#   most people will only start one node:
CELERYD_NODES="worker1"
#   but you can also start multiple and configure settings
#   for each in CELERYD_OPTS
#CELERYD_NODES="worker1 worker2 worker3"
#   alternatively, you can specify the number of nodes to start:
#CELERYD_NODES=10

# Absolute or relative path to the 'celery' command:
CELERY_BIN="/opt/climmob_env/bin/celery"
#CELERY_BIN="/virtualenvs/def/bin/celery"

# App instance to use
# comment out this line if you don't use an app
#CELERY_APP="proj"
# or fully qualified:
CELERY_APP="climmob.config.celery_app"

# Where to chdir at start.
CELERYD_CHDIR="/opt/climmob/"

# Extra command-line arguments to the worker
CELERYD_OPTS="--time-limit=900 --concurrency=8 -Q ClimMob"
# Configure node-specific settings by appending node name to arguments:
#CELERYD_OPTS="--time-limit=300 -c 8 -c:worker2 4 -c:worker3 2 -Ofair:worker1"

# Set logging level to DEBUG
#CELERYD_LOG_LEVEL="DEBUG"

# %n will be replaced with the first part of the nodename.
CELERYD_LOG_FILE="/opt/climmob_celery/log/%n%I.log"
CELERYD_PID_FILE="/opt/climmob_celery/run/%n.pid"

# Workers should run as an unprivileged user.
#   You need to create this user manually (or you can choose
#   a user/group combination that already exists (e.g., nobody).
CELERYD_USER="root"
CELERYD_GROUP="root"

# If enabled pid and log directories will be created if missing,
# and owned by the userid/group configured.
CELERY_CREATE_DIRS=1
```
With BROKER_POOL_LIMIT = None

The only way to recover our server is after a shutdown.

Celery: celery==4.4.2   (Installed from PyPi)
billiard==3.6.3.0 (Installed from PyPi)
Ubuntu 20.04 docker

**Comment by thedrow** [comment]
There is not enough information to reproduce this problem.
Please open a new issue using our bug report template and fill out all the necessary details.

In this case, we'd must have a reproducible test case we can use to debug this issue.
