### ISSUE TITLE
Celery producer witch rpc backend cannot fetch results when rabbitmq is restarted

### ISSUE THREAD

**Issue by Abam** [celery/celery#6912]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.1.2 (sun-harmonics) kombu:5.1.0 py:3.9.6
            billiard:3.6.4.0 py-amqp:5.0.6
platform -> system:Linux arch:64bit, ELF
            kernel version:5.4.0-81-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:rpc:///

broker_url: 'amqp://guest:********@rabbitmq:5672//'
result_backend: 'rpc:///'
deprecated_settings: None

```

</p>
</details>

# Steps to Reproduce

1. Start the worker and import the tasks add.
2. Reboot the broker.
3. Call the task add and try to get the result.

Example:
```
# Start python and rabbitmq containers

docker-compose up -d

# In one shell, start the worker

docker-compose exec python  celery -A tasks worker --loglevel=DEBUG

# In another shell, run pyton interpreter

 docker-compose exec python python

```

## Required Dependencies

* **Minimal Python Version**:  3.8.11 and 3.9.6
* **Minimal Celery Version**: 4.4.7 and 5.1.2
* **Minimal Kombu Version**:  5.1.0
* **Minimal Broker Version**:  RabbitMQ 3.9.3
* **Minimal Result Backend Version**: RabbitMQ 3.9.3
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.6
attrs==21.2.0
billiard==3.6.4.0
celery==5.1.2
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.2.0
iniconfig==1.1.1
kombu==5.1.0
librabbitmq==2.0.0
packaging==21.0
pika==0.13.0
pluggy==0.13.1
prompt-toolkit==3.0.19
py==1.10.0
pyparsing==2.4.7
pytest==6.2.4
pytz==2021.1
six==1.16.0
toml==0.10.2
vine==5.0.0
wcwidth==0.2.5
```

</p>
</details>

### Other Dependencies

<details>
<p>
docker-compose file:

```
version: '3.1'

services:

  python:
    image: python:3.9.6-buster
    working_dir: /data
    entrypoint: "/bin/bash"
    tty: true
    networks:
        learn_celery:
          ipv4_address: 172.20.2.3
    volumes:
      - ./src:/data

  rabbitmq:
    image: rabbitmq:3.9.3-management-alpine

    networks:
        learn_celery:
          ipv4_address: 172.20.2.2
networks:
  learn_celery:
    ipam:
      driver: default
      config:
      - subnet: 172.20.2.0/24

```

</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery

app = Celery('tasks', broker='pyamqp://guest:guest@rabbitmq/', backend='rpc://')

@app.task
def add(x, y):
    return x + y

```

</p>
</details>

# Expected Behavior

When the broker is rebooted, the worker and the producer should reconnect automatically and keep producing and consuming message.

# Actual Behavior

In one hand, when the broker is rebooted, the worker reconnects automatically and keep consuming message as expected.

But on the other hand, for the producer, when the broker is rebooted, tasks are sent and the worker can consume them. But results are never pulled out.
An `ConnectionResetError` exception is raised by the producer when the `task.get`method is called.

**Comment by promasu** [comment]
Hi there,

can confirm the exact behavior with RabbitMQ 3.9.13, Celery 3.1.25 / Celery 4.4.7 and Python 3.7.3.

Kind regards
Adrian

**Comment by promasu** [comment]
We have further investigated this issue and the ResultConsumer does not connect back to RabbitMQ.
After the broker restarts and the first message is published to the broker a new queue with the same name as before the restart is created but this time with no consumer subscribed to it.

If you need further information to investigate the issue, please reach out so we can provide more information.

**Comment by apmariglis** [comment]
Confirming same behavior with RabbitMQ 3.9.15, Celery 5.2.6 on Python 3.8. 

To reproduce:
#### RabbitMQ
```
$ docker run -d -p 5679:5672 --name rabbitmq-testnode rabbitmq:3.9.15
```
(takes about half a minute for the container to be ready) then configure rabbitmq
```
$ docker exec -it rabbitmq-testnode /bin/bash -c "rabbitmqctl add_user user password; rabbitmqctl set_user_tags user  user_tag administrator; rabbitmqctl add_vhost user_vhost; rabbitmqctl set_permissions -p user_vhost user '.*' '.*' '.*'"
```
#### Consumer
A consumer with only one shared task a_task
```
# consumer.py
from celery import Celery
celery = Celery(
    broker="pyamqp://user:password@127.0.0.1:5679/user_vhost",
    backend="rpc://",
    include=[
        "consumer_tasks",
    ],
)
```
```
# consumer_tasks.py
from celery import shared_task
import time
 
@shared_task()
def a_task():
    return "this is a_task's response"
```
consumer is started with
```
$ celery -A consumer worker -l info --purge
```
#### Producer
```
# producer.py
from celery import Celery
import time

TIMEOUT = 5

celery_app = Celery(
    broker="pyamqp://user:password@127.0.0.1:5679/user_vhost",
    backend="rpc://",
)
celery_app.conf.broker_pool_limit = None #otherwise when broker is down apply_async() hangs until broker is back up

while True:
    try:
        task_signature = celery_app.signature("consumer_tasks.a_task")
        async_result = task_signature.apply_async()
        print(f"-->{async_result.id=}")
        result = async_result.get(TIMEOUT)
        print(f"task result --> {result}")

    except Exception as exc:
        print(f"{exc=} ")
    finally:
        time.sleep(0.5)
        print("")
```
Start the producer
```
$ python producer.py
```
after a couple of seconds (timing is not important) kill the rabbitMQ container
```
$ docker rm -f rabbitmq-testnode
```
then (timing is not important) start rabbitMQ again 
```
$ docker run -d -p 5679:5672 --name rabbitmq-testnode rabbitmq:3.9.15
```
(takes about half a minute for the container to be ready) then configure rabbitmq
```
$ docker exec -it rabbitmq-testnode /bin/bash -c "rabbitmqctl add_user user password; rabbitmqctl set_user_tags user  user_tag administrator; rabbitmqctl add_vhost user_vhost; rabbitmqctl set_permissions -p user_vhost user '.*' '.*' '.*'"
```

the output of the **consumer** will be like this 
``` 
$ celery -A consumer worker -l info --purge

 -------------- celery@abcd-pc v5.2.5 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-4.15.0-175-generic-x86_64-with-glibc2.27 2022-04-23 04:13:28
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7f311948b2b0
- ** ---------- .> transport:   amqp://user:**@127.0.0.1:5679/user_vhost
- ** ---------- .> results:     rpc://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . consumer_tasks.a_task

[2022-04-23 04:13:28,991: INFO/MainProcess] Connected to amqp://user:**@127.0.0.1:5679/user_vhost
[2022-04-23 04:13:29,002: INFO/MainProcess] mingle: searching for neighbors
[2022-04-23 04:13:30,037: INFO/MainProcess] mingle: all alone
[2022-04-23 04:13:30,069: INFO/MainProcess] celery@abcd-pc ready.
[2022-04-23 04:21:54,930: INFO/MainProcess] Task consumer_tasks.a_task[99e22d91-e007-420e-af9d-29ce34ead458] received
[2022-04-23 04:21:54,953: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[99e22d91-e007-420e-af9d-29ce34ead458] succeeded in 0.021101941005326807s: 'this is a_task\'s response'
[2022-04-23 04:21:55,471: INFO/MainProcess] Task consumer_tasks.a_task[f65a9080-a646-4e6c-8857-6c2b98bbd46e] received
[2022-04-23 04:21:55,473: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[f65a9080-a646-4e6c-8857-6c2b98bbd46e] succeeded in 0.0010343230096623302s: 'this is a_task\'s response'
[2022-04-23 04:21:56,006: INFO/MainProcess] Task consumer_tasks.a_task[b9434648-b1a8-496d-90c8-02e95ac6a8c1] received
[2022-04-23 04:21:56,008: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[b9434648-b1a8-496d-90c8-02e95ac6a8c1] succeeded in 0.0009761779801920056s: 'this is a_task\'s response'
[2022-04-23 04:21:56,550: INFO/MainProcess] Task consumer_tasks.a_task[7764782f-624d-449c-9d36-cd7f545087b7] received
[2022-04-23 04:21:56,552: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[7764782f-624d-449c-9d36-cd7f545087b7] succeeded in 0.0009925600024871528s: 'this is a_task\'s response'
[2022-04-23 04:21:57,079: INFO/MainProcess] Task consumer_tasks.a_task[6a1cf47f-5681-4d05-968c-9d56f093fdec] received
[2022-04-23 04:21:57,082: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[6a1cf47f-5681-4d05-968c-9d56f093fdec] succeeded in 0.0011918439995497465s: 'this is a_task\'s response'
[2022-04-23 04:21:57,596: INFO/MainProcess] Task consumer_tasks.a_task[9cac8523-ce21-436e-b12f-604c50a71132] received
[2022-04-23 04:21:57,598: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[9cac8523-ce21-436e-b12f-604c50a71132] succeeded in 0.0008094499935396016s: 'this is a_task\'s response'
[2022-04-23 04:21:58,118: INFO/MainProcess] Task consumer_tasks.a_task[79ecac81-e038-4b64-a5f7-c270bb993779] received
[2022-04-23 04:21:58,120: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[79ecac81-e038-4b64-a5f7-c270bb993779] succeeded in 0.0009018040145747364s: 'this is a_task\'s response'
[2022-04-23 04:21:58,638: INFO/MainProcess] Task consumer_tasks.a_task[4a29fbb3-ed87-4dc8-812c-44aecf757db0] received
[2022-04-23 04:21:58,640: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[4a29fbb3-ed87-4dc8-812c-44aecf757db0] succeeded in 0.0016999630024656653s: 'this is a_task\'s response'
[2022-04-23 04:21:59,159: INFO/MainProcess] Task consumer_tasks.a_task[9e3fa84b-e66c-4abc-9a02-20438772f060] received
[2022-04-23 04:21:59,162: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[9e3fa84b-e66c-4abc-9a02-20438772f060] succeeded in 0.0024456570390611887s: 'this is a_task\'s response'
[2022-04-23 04:21:59,681: INFO/MainProcess] Task consumer_tasks.a_task[7407329a-a897-4bb9-9288-b8d8ce5f94f1] received
[2022-04-23 04:21:59,684: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[7407329a-a897-4bb9-9288-b8d8ce5f94f1] succeeded in 0.001073391002137214s: 'this is a_task\'s response'
[2022-04-23 04:22:00,198: INFO/MainProcess] Task consumer_tasks.a_task[be7d2788-6764-4be2-ad34-49168569220c] received
[2022-04-23 04:22:00,200: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[be7d2788-6764-4be2-ad34-49168569220c] succeeded in 0.0007704689633101225s: 'this is a_task\'s response'
[2022-04-23 04:22:00,720: INFO/MainProcess] Task consumer_tasks.a_task[8c1e255c-5af7-49ff-9b96-62c5d1129bed] received
[2022-04-23 04:22:00,722: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[8c1e255c-5af7-49ff-9b96-62c5d1129bed] succeeded in 0.0009923350298777223s: 'this is a_task\'s response'
[2022-04-23 04:22:01,240: INFO/MainProcess] Task consumer_tasks.a_task[6bc90c35-275b-4d4a-b6a0-5ccf5320f975] received
[2022-04-23 04:22:01,242: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[6bc90c35-275b-4d4a-b6a0-5ccf5320f975] succeeded in 0.0009339560056105256s: 'this is a_task\'s response'
[2022-04-23 04:22:01,639: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/celery-5.2.5-py3.8.egg/celery/worker/consumer/consumer.py", line 331, in start
    blueprint.start(self)
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/celery-5.2.5-py3.8.egg/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/celery-5.2.5-py3.8.egg/celery/worker/consumer/consumer.py", line 657, in start
    c.loop(*c.loop_args())
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/celery-5.2.5-py3.8.egg/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/kombu-5.2.4-py3.8.egg/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/kombu-5.2.4-py3.8.egg/kombu/transport/base.py", line 235, in on_readable
    reader(loop)
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/kombu-5.2.4-py3.8.egg/kombu/transport/base.py", line 217, in _read
    drain_events(timeout=0)
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/amqp-5.1.1-py3.8.egg/amqp/connection.py", line 525, in drain_events
    while not self.blocking_read(timeout):
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/amqp-5.1.1-py3.8.egg/amqp/connection.py", line 530, in blocking_read
    frame = self.transport.read_frame()
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/amqp-5.1.1-py3.8.egg/amqp/transport.py", line 294, in read_frame
    frame_header = read(7, True)
  File "/home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/amqp-5.1.1-py3.8.egg/amqp/transport.py", line 635, in _read
    raise OSError('Server unexpectedly closed connection')
OSError: Server unexpectedly closed connection
[2022-04-23 04:22:01,645: WARNING/MainProcess] /home/abcd/.cache/pypoetry/virtualenvs/mip-engine-cqWRDGMx-py3.8/lib/python3.8/site-packages/celery-5.2.5-py3.8.egg/celery/worker/consumer/consumer.py:381: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2022-04-23 04:22:01,648: ERROR/MainProcess] consumer: Cannot connect to amqp://user:**@127.0.0.1:5679/user_vhost: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds... (1/100)

[2022-04-23 04:22:03,651: ERROR/MainProcess] consumer: Cannot connect to amqp://user:**@127.0.0.1:5679/user_vhost: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2022-04-23 04:22:07,656: ERROR/MainProcess] consumer: Cannot connect to amqp://user:**@127.0.0.1:5679/user_vhost: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds... (3/100)

[2022-04-23 04:22:13,663: ERROR/MainProcess] consumer: Cannot connect to amqp://user:**@127.0.0.1:5679/user_vhost: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds... (4/100)

[2022-04-23 04:22:21,676: INFO/MainProcess] Connected to amqp://user:**@127.0.0.1:5679/user_vhost
[2022-04-23 04:22:21,692: INFO/MainProcess] mingle: searching for neighbors
[2022-04-23 04:22:22,729: INFO/MainProcess] mingle: all alone
[2022-04-23 04:22:22,757: INFO/MainProcess] Task consumer_tasks.a_task[7bf3c9e8-9fa9-4081-9080-51ff175a7a5b] received
[2022-04-23 04:22:22,758: INFO/MainProcess] Task consumer_tasks.a_task[4a186b22-ec09-4210-9239-4e9dbaf37891] received
[2022-04-23 04:22:22,870: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[7bf3c9e8-9fa9-4081-9080-51ff175a7a5b] succeeded in 0.010713921976275742s: 'this is a_task\'s response'
[2022-04-23 04:22:22,875: INFO/ForkPoolWorker-3] Task consumer_tasks.a_task[4a186b22-ec09-4210-9239-4e9dbaf37891] succeeded in 0.015249031013809144s: 'this is a_task\'s response'
[2022-04-23 04:22:26,897: INFO/MainProcess] Task consumer_tasks.a_task[86afda7c-0b23-4aaa-96dc-57ad4b116eda] received
[2022-04-23 04:22:26,903: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[86afda7c-0b23-4aaa-96dc-57ad4b116eda] succeeded in 0.001408679992891848s: 'this is a_task\'s response'
[2022-04-23 04:22:32,416: INFO/MainProcess] Task consumer_tasks.a_task[5a72ca88-29e7-4820-afcd-9e786331c02c] received
[2022-04-23 04:22:32,418: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[5a72ca88-29e7-4820-afcd-9e786331c02c] succeeded in 0.0007772039971314371s: 'this is a_task\'s response'
[2022-04-23 04:22:37,942: INFO/MainProcess] Task consumer_tasks.a_task[0194a9c4-0928-4971-8173-b972867e38cb] received
[2022-04-23 04:22:37,945: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[0194a9c4-0928-4971-8173-b972867e38cb] succeeded in 0.0006305860006250441s: 'this is a_task\'s response'
[2022-04-23 04:22:43,459: INFO/MainProcess] Task consumer_tasks.a_task[31c92db1-b534-4adf-9c81-618acbf3832a] received
[2022-04-23 04:22:43,461: INFO/ForkPoolWorker-2] Task consumer_tasks.a_task[31c92db1-b534-4adf-9c81-618acbf3832a] succeeded in 0.0008131660288199782s: 'this is a_task\'s response'
```

the output of the **producer** will be like this 
```
$ python producer.py

-->async_result.id='99e22d91-e007-420e-af9d-29ce34ead458'
task result --> this is a_task's response

-->async_result.id='f65a9080-a646-4e6c-8857-6c2b98bbd46e'
task result --> this is a_task's response

-->async_result.id='b9434648-b1a8-496d-90c8-02e95ac6a8c1'
task result --> this is a_task's response

-->async_result.id='7764782f-624d-449c-9d36-cd7f545087b7'
task result --> this is a_task's response

-->async_result.id='6a1cf47f-5681-4d05-968c-9d56f093fdec'
task result --> this is a_task's response

-->async_result.id='9cac8523-ce21-436e-b12f-604c50a71132'
task result --> this is a_task's response

-->async_result.id='79ecac81-e038-4b64-a5f7-c270bb993779'
task result --> this is a_task's response

-->async_result.id='4a29fbb3-ed87-4dc8-812c-44aecf757db0'
task result --> this is a_task's response

-->async_result.id='9e3fa84b-e66c-4abc-9a02-20438772f060'
task result --> this is a_task's response

-->async_result.id='7407329a-a897-4bb9-9288-b8d8ce5f94f1'
task result --> this is a_task's response

-->async_result.id='be7d2788-6764-4be2-ad34-49168569220c'
task result --> this is a_task's response

-->async_result.id='8c1e255c-5af7-49ff-9b96-62c5d1129bed'
task result --> this is a_task's response

-->async_result.id='6bc90c35-275b-4d4a-b6a0-5ccf5320f975'
task result --> this is a_task's response

exc=OperationalError('[Errno 104] Connection reset by peer') 

exc=OperationalError('[Errno 104] Connection reset by peer') 

exc=AccessRefused(403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.', (0, 0), '') 

exc=AccessRefused(403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.', (0, 0), '') 

exc=AccessRefused(403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.', (0, 0), '') 

exc=AccessRefused(403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.', (0, 0), '') 

exc=NotAllowed(530, "NOT_ALLOWED - access to vhost 'user_vhost' refused for user 'user'", (10, 40), 'Connection.open') 

exc=NotAllowed(530, "NOT_ALLOWED - access to vhost 'user_vhost' refused for user 'user'", (10, 40), 'Connection.open') 

exc=NotAllowed(530, "NOT_ALLOWED - access to vhost 'user_vhost' refused for user 'user'", (10, 40), 'Connection.open') 

exc=NotAllowed(530, "NOT_ALLOWED - access to vhost 'user_vhost' refused for user 'user'", (10, 40), 'Connection.open') 

-->async_result.id='7bf3c9e8-9fa9-4081-9080-51ff175a7a5b'
exc=OSError('Server unexpectedly closed connection')

-->async_result.id='4a186b22-ec09-4210-9239-4e9dbaf37891'
exc=TimeoutError('The operation timed out.') 

-->async_result.id='86afda7c-0b23-4aaa-96dc-57ad4b116eda'
exc=TimeoutError('The operation timed out.') 

-->async_result.id='5a72ca88-29e7-4820-afcd-9e786331c02c'
exc=TimeoutError('The operation timed out.') 

-->async_result.id='0194a9c4-0928-4971-8173-b972867e38cb'
exc=TimeoutError('The operation timed out.') 

-->async_result.id='31c92db1-b534-4adf-9c81-618acbf3832a'
exc=TimeoutError('The operation timed out.') 
```

Both processes are started when the broker is up and running, then at some point the rabbitMQ container is killed, then rabbitMQ is started and configured again, while the producer and the consumer processes keep running. What is of interest here are the ids of the tasks that get queued _**after**_ the broker is back up again
```
4a186b22-ec09-4210-9239-4e9dbaf37891
86afda7c-0b23-4aaa-96dc-57ad4b116eda
5a72ca88-29e7-4820-afcd-9e786331c02c
0194a9c4-0928-4971-8173-b972867e38cb
31c92db1-b534-4adf-9c81-618acbf3832a
```
These tasks' ids are logged in both processes (producer and consumer) but the consumer reports them as `succeeded`, when the producer reports them as timed out (`TimeoutError('The operation timed out.')`). So, task queuing and consuming is successfully resumed after restarting the broker but the results are not returned correctly to the client/producer.

**Comment by ThanKarab** [comment]
Any updates on this one?

**Comment by KFilippopolitis** [comment]
Is there a fix on this one or is it not ready yet?

**Comment by csrodi** [comment]
Hello! Any news about the fix, or a release date?

**Comment by auvipy** [comment]
@ChickenBenny if you have time, can you investigate?

**Comment by ChickenBenny** [comment]
No problem! I'll take a look at this on Friday.

**Comment by auvipy** [comment]
we got a new fix for this. please check and report if it works properly or not
