### ISSUE TITLE
run celery 5.1.2 in docker python3.8.2 failed

### ISSUE THREAD

**Issue by supercrow** [celery/celery#6921]
when I run  celery 5.1.2 in docker python3.8.2 has come error:
```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1666, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 2320, in process_value
    value = self.type_cast_value(ctx, value)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 2307, in type_cast_value
    return convert(value)
  File "/usr/local/lib/python3.8/site-packages/click/types.py", line 75, in __call__
    return self.convert(value, param, ctx)
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 245, in convert
    value = value.upper()
AttributeError: 'int' object has no attribute 'upper'
```
but when I rollback the python version use 3.7.10, the celery run success

the celery config:
```

from celery.schedules import crontab
from datetime import timedelta
from kombu import Queue

broker_url = config.celery_config.get("broker")
result_backend = config.mongo_url
mongodb_backend_settings = {
    'database': config.mongo_db_name,
}
worker_concurrency = 4
result_expires = 60 * 60 * 24 * 7
worker_max_tasks_per_child = 10
# 1G
worker_max_memory_per_child = 1024 * 1024 * 1024

task_acks_late = True
# task_ignore_result = True
# task_store_errors_even_if_ignored = True
task_acks_on_failure_or_timeout = False
task_reject_on_worker_lost = True

timezone = 'Asia/Shanghai'
enable_utc = False

# task_annotations

task_publish_retry_policy = {
    "max_retries": 10,
    "interval_start": 1,
    "interval_step": 10
}

imports = ["someone package"]


# celery beat
beat_schedule = {
    'backend_cleanup': {
        'task': 'celery.backend_cleanup',
        'schedule': timedelta(days=3)
    }
}
```

**Comment by supercrow** [comment]
feel some error happend in python-3.8.2 image,  the click cant't fetch the correct args,
i can run celery normal  both in python 3.9 and python 3.7 image, but in python3.8 is failed

**Comment by syrull** [comment]
@supercrow Can you please follow the contributing guide here: https://github.com/celery/celery/blob/master/CONTRIBUTING.rst#id3 

I would look into that but please do include the things from the guide.

**Comment by thedrow** [comment]
Yes, this is very interesting and it does sound like a bug but we have a procedure for reporting those.
Please use the full template to supply as much information as possible.
In the meanwhile, I'm closing this one as invalid.
