### ISSUE TITLE
chord & chain try to serialize Queue object from task signature, which always fails

### ISSUE THREAD

**Issue by radiantone** [celery/celery#6943]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [X] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.8.5
* **Minimal Celery Version**: 5.1.2
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**:  Pop!_OS 21.04
* **Minimal Broker Client Version**:  pyamqp
* **Minimal Result Backend Client Version**:  redis

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

When using .signature(..., queue=Queue(...),...) in a chord or chain, it tries to serialize the Queue() object, which fails. group execution does work.

Exception
```
Traceback (most recent call last):
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/serialization.py", line 42, in _reraise_errors
    yield
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/serialization.py", line 213, in dumps
    payload = encoder(data)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/home/darren/condas/miniconda3/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/darren/condas/miniconda3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/darren/condas/miniconda3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/home/darren/condas/miniconda3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Queue is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyfi/client/example/example2.py", line 8, in <module>
    result = chain([
  File "/home/darren/PycharmProjects/pyfi/celery/canvas.py", line 612, in __call__
    return self.apply_async(args, kwargs)
  File "/home/darren/PycharmProjects/pyfi/celery/canvas.py", line 640, in apply_async
    return self.run(args, kwargs, app=app, **(
  File "/home/darren/PycharmProjects/pyfi/celery/canvas.py", line 669, in run
    result_from_apply = first_task.apply_async(**options)
  File "/home/darren/PycharmProjects/pyfi/celery/canvas.py", line 219, in apply_async
    return _apply(args, kwargs, **options)
  File "/home/darren/PycharmProjects/pyfi/celery/app/base.py", line 767, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/darren/PycharmProjects/pyfi/celery/app/amqp.py", line 510, in send_task_message
    ret = producer.publish(
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/messaging.py", line 166, in publish
    body, content_type, content_encoding = self._prepare(
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/messaging.py", line 254, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/serialization.py", line 213, in dumps
    payload = encoder(data)
  File "/home/darren/condas/miniconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/serialization.py", line 46, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/serialization.py", line 42, in _reraise_errors
    yield
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/serialization.py", line 213, in dumps
    payload = encoder(data)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/home/darren/condas/miniconda3/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/darren/condas/miniconda3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/darren/condas/miniconda3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/darren/PycharmProjects/pyfi/venv/lib/python3.8/site-packages/kombu-5.1.0-py3.8.egg/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/home/darren/condas/miniconda3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type Queue is not JSON serializable
```

**Comment by radiantone** [comment]
Changing the serializer to 'pickle' fixes this.
