### ISSUE TITLE
Error when using multiple Redis (TLS) result backends

### ISSUE THREAD

**Issue by stevenfranks** [celery/celery#6950]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.7

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

Try to use more than one Redis result backend (TLS)

```
result_backend = 'rediss://:<password>@{{ host1 }}?ssl_cert_reqs=required&ssl_ca_certs=cert.pem;rediss://:<password>@{{ host2 }}?ssl_cert_reqs=required&ssl_ca_certs=cert.pem'
```

## Required Dependencies

* **Minimal Python Version**: Python 3.7
* **Minimal Celery Version**: Celery 4.4.7 (celery[redis]==4.4.7)

* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
celery==4.4.7
celery[redis]==4.4.7
redis==3.5.3
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Tasks and results succeed

# Actual Behavior
```
Traceback (most recent call last):
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/redis/connection.py", line 1185, in get_connection
connection = self._available_connections.pop()
IndexError: pop from empty list
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/celery/app/base.py", line 740, in send_task
self.backend.on_task_call(P, task_id)
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/celery/backends/redis.py", line 343, in on_task_call
self.result_consumer.consume_from(task_id)
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/celery/backends/redis.py", line 168, in consume_from
return self.start(task_id)
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/celery/backends/redis.py", line 146, in start
self._consume_from(initial_task_id)
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/celery/backends/redis.py", line 176, in _consume_from
self._pubsub.subscribe(key)
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/redis/client.py", line 3580, in subscribe
ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/redis/client.py", line 3468, in execute_command
self.shard_hint
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/redis/connection.py", line 1187, in get_connection
connection = self.make_connection()
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/redis/connection.py", line 1227, in make_connection
return self.connection_class(**self.connection_kwargs)
File "/user/.virtualenvs/venv/lib/python3.7/site-packages/redis/connection.py", line 828, in __init__
super(SSLConnection, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'rediss://:<password>@<host2>:6379?ssl_cert_reqs'
```

**Comment by auvipy** [comment]
@maybe-sybr you have more redis exp I guess

**Comment by anveshagarwal** [comment]
any updates on this? facing similar issue
