### ISSUE TITLE
Problems with deserializing Django objects inside inspect active command

### ISSUE THREAD

**Issue by ivanvumedi** [celery/celery#6977]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [X] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [X] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- #6672 

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:  5.1.2

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.1.2 (sun-harmonics) kombu:5.1.0 py:3.6.8
            billiard:3.6.4.0 py-amqp:5.0.6
platform -> system:Darwin arch:64bit
            kernel version:20.5.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:django-db

accept_content: ['pickle']
result_serializer: 'pickle'
task_serializer: 'pickle'
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
Prerequirements are to have the Django project and setup described in official celery docs.

<p>

```python
@app.task
def sleep_task(user_object):
    import time
    time.sleep(100000)

# in Django shell
sleep_task.delay(User.objects.first())
```

</p>
</details>

# Expected Behavior

We should have standard inspect active output with deserialized Django object like in 4.x.
```
->  celery@xyz: OK
    * {'id': '81f641db-8ba9-45c8-8d1e-e8cd52c50de1', 'name': 'proj.tasks.sleep_task', 'args': (<User: XYZ>,), 'kwargs': {}, 'type': 'proj.tasks.sleep_task'', 'hostname': 'celery@xyz', 'time_start': 1633008451.4256349, 'acknowledged': True, 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': False}, 'worker_pid': 36039}

1 node online.
```

# Actual Behavior

Instead of receiving the active task data, `celery -A proj inspect active` raises DecodeError
```
Traceback (most recent call last):
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 42, in _reraise_errors
    yield
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 255, in loads
    return decode(data)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 327, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 51, in pickle_loads
    return load(BytesIO(s))
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/django/db/models/base.py", line 1828, in model_unpickle
    model = apps.get_model(*model_id)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/django/apps/registry.py", line 198, in get_model
    self.check_models_ready()
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/django/apps/registry.py", line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xyz/.virtualenvs/proj/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/celery/bin/control.py", line 137, in inspect
    **arguments)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/celery/app/control.py", line 114, in _request
    pattern=self.pattern, matcher=self.matcher,
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/celery/app/control.py", line 743, in broadcast
    limit, callback, channel=channel,
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/pidbox.py", line 350, in _broadcast
    channel=chan)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/pidbox.py", line 389, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/connection.py", line 318, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 135, in drain_events
    return connection.drain_events(**kwargs)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/amqp/connection.py", line 523, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/amqp/connection.py", line 529, in blocking_read
    return self.on_inbound_frame(frame)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/amqp/method_framing.py", line 77, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/amqp/connection.py", line 536, in on_inbound_method
    method_sig, payload, content,
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/amqp/abstract_channel.py", line 143, in dispatch_method
    listener(*args)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/amqp/channel.py", line 1613, in _on_basic_deliver
    fun(msg)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/messaging.py", line 620, in _receive_callback
    decoded = None if on_m else message.decode()
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/message.py", line 190, in decode
    self._decoded_cache = self._decode()
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/message.py", line 195, in _decode
    self.content_encoding, accept=self.accept)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 255, in loads
    return decode(data)
  File "/Users/xyz/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 46, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 42, in _reraise_errors
    yield
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 255, in loads
    return decode(data)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 327, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/kombu/serialization.py", line 51, in pickle_loads
    return load(BytesIO(s))
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/django/db/models/base.py", line 1828, in model_unpickle
    model = apps.get_model(*model_id)
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/django/apps/registry.py", line 198, in get_model
    self.check_models_ready()
  File "/Users/xyz/.virtualenvs/proj/lib/python3.6/site-packages/django/apps/registry.py", line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
kombu.exceptions.DecodeError: Models aren't loaded yet.
```

**Comment by auvipy** [comment]
it  might be a kombu or django model loading issue

**Comment by thedrow** [comment]
It's definitely a Django model loading issue.
