### ISSUE TITLE
[Question] Could not pass test whether running locally or via docker-compose

### ISSUE THREAD

**Issue by PinchasLev** [celery/celery#7190]
# Checklist

- [X] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [X] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [X] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.2.1 (dawn-chorus)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

Output from celery report
```
software -> celery:5.2.1 (dawn-chorus) kombu:5.2.2 py:3.7.4
            billiard:3.6.4.0 py-amqp:5.0.9
platform -> system:Darwin arch:64bit
            kernel version:20.5.0 imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: I've been testing under multiple virtual environments of python: 3.7.4, 3.8.5, 3.9.6
* **Minimal Celery Version**: master
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: MacOS Big Sur 11.4
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
(3.7.4/envs/stellar_3_7) pinchas.lev@Pinchass-MacBook-Pro celery % pip3 freeze
amqp==5.0.9
appdirs==1.4.4
asgiref==3.4.1
astroid==2.6.6
attrs==21.2.0
autopep8==1.5.7
Babel==2.9.1
backports.entry-points-selectable==1.1.1
bcrypt==3.2.0
beautifulsoup4==4.10.0
before-after==1.0.1
billiard==3.6.4.0
black==21.7b0
bleach==4.1.0
boto3==1.20.26
botocore==1.23.26
cached-property==1.5.2
cachetools==4.2.4
cairocffi==1.1.0
CairoSVG==2.5.2
cchardet==2.1.7
celery==5.2.1
celery-once==3.0.1
certifi==2021.5.30
cffi==1.14.6
cfgv==3.3.1
chardet==3.0.4
charset-normalizer==2.0.7
click==8.0.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
colorama==0.4.3
cryptography==3.4.8
cssselect2==0.4.1
customerio==1.0
Cython==0.29.22
defusedxml==0.7.1
distlib==0.3.4
dj-database-url==0.5.0
Django==3.2.9
django-add-default-value==0.9.1
django-admin-autocomplete-filter==0.6.1
django-appconf==1.0.4
django-axes==5.2.2
django-better-admin-arrayfield==1.4.2
django-ckeditor==5.8.0
django-compressor==2.4.1
django-cryptography==1.0
django-csp==3.7
django-debug-toolbar==3.1.1
django-dirtyfields==1.7.0
django-guardian==2.4.0
django-ipware==2.1.0
django-js-asset==1.2.2
django-libsass==0.9
django-migration-linter==2.5.3
django-pglocks==1.0.4
django-polymorphic==3.0.0
django-redis==5.0.0
django-silk==4.1.0
django-storages==1.8
django-termsandconditions==2.0.9
django-user-sessions==1.7.1
django-webpack-loader==1.4.1
django-widget-tweaks==1.4.9
djangorestframework==3.11.0
djangorestframework-datatables==0.5.1
dnspython==1.16.0
docutils==0.15.2
dparse==0.5.1
elasticsearch==7.12.1
et-xmlfile==1.1.0
eventlet==0.30.2
expiringdict==1.2.1
filelock==3.4.0
flower==0.9.3
freezegun==0.3.13
future==0.18.2
fuzzywuzzy==0.18.0
geoip2==2.9.0
gevent==1.4.0
gprof2dot==2021.2.21
greenlet==1.1.0
gunicorn==20.1.0
html5lib==1.1
identify==2.4.0
idna==2.8
importlib-metadata==4.6.1
influxdb==5.2.3
iniconfig==1.1.1
isodate==0.6.0
isort==5.9.3
jdcal==1.4.1
Jinja2==3.0.1
jmespath==0.9.4
kombu==5.2.2
lazy-object-proxy==1.6.0
libsass==0.21.0
lxml==4.6.3
MarkupSafe==2.0.1
marshmallow==2.20.5
maxminddb==2.0.3
mccabe==0.6.1
mock==1.0.1
more-itertools==8.10.0
moto==2.2.19
msgpack==1.0.3
mypy-extensions==0.4.3
newrelic==7.2.4.171
nodeenv==1.6.0
numpy==1.19.5
openpyxl==3.0.3
packaging==21.0
pandas==0.25.3
paramiko==2.8.0
pathspec==0.9.0
pep8==1.7.1
phonenumbers==8.12.36
Pillow==8.3.1
platformdirs==2.4.0
pluggy==1.0.0
pre-commit==2.16.0
prompt-toolkit==3.0.24
psutil==5.8.0
psycopg2-binary==2.8.6
py==1.11.0
pycodestyle==2.5.0
pycparser==2.20
pyflakes==2.3.1
Pygments==2.9.0
pylint==2.9.6
pymongo==4.0.1
PyNaCl==1.4.0
pyparsing==2.4.7
pyphen==0.11.0
pysftp==0.2.9
pytest==6.2.5
pytest-celery==0.0.0
pytest-subtests==0.5.0
pytest-timeout==1.4.2
python-crontab==2.5.1
python-dateutil==2.8.2
python-Levenshtein==0.12.2
python3-saml==1.9.0
pytz==2021.3
pyx12==2.3.3
PyYAML==6.0
rcssmin==1.0.6
redis==3.5.3
regex==2021.8.3
requests==2.26.0
responses==0.16.0
rjsmin==1.1.0
s3transfer==0.5.0
safety==1.8.5
si-prefix==1.2.2
simplejson==3.17.5
six==1.16.0
sodapy==2.0.0
soupsieve==2.2.1
sqlparse==0.4.1
structlog==19.2.0
tblib==1.7.0
tenacity==6.2.0
tinycss2==1.0.2
toml==0.10.2
tomli==1.2.1
tornado==5.1.1
typed-ast==1.4.3
typing==3.7.4.3
typing-extensions==3.10.0.0
urllib3==1.25.7
vine==5.0.0
virtualenv==20.10.0
wcwidth==0.2.5
WeasyPrint==52.5
webencodings==0.5.1
Werkzeug==2.0.2
whitenoise==5.3.0
wrapt==1.12.1
xlrd==1.2.0
xmlsec==1.3.11
xmltodict==0.12.0
zipp==3.5.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```
pytest t/unit
```

</p>
</details>

# Expected Behavior

I expected all tests to pass

# Actual Behavior
<!--
When trying to test via docker-compose, initiating the call `docker-compose -f docker/docker-compose.yml run --rm celery:dev pyenv exec python3.7 -m pytest t/unit` I get the following error
```
(3.7.4/envs/stellar_3_7) pinchas.lev@Pinchass-MacBook-Pro celery % docker run celery:dev -- pyenv exec python3.7 -m pytest t/unit
rm: missing operand
Try 'rm --help' for more information.
rm: missing operand
Try 'rm --help' for more information.
============================= test session starts ==============================
platform linux -- Python 3.7.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/developer/celery, configfile: pyproject.toml
plugins: rerunfailures-10.2, timeout-1.4.2, subtests-0.5.0, celery-0.0.0, cov-3.0.0
collected 2627 items / 1 error / 2626 selected

==================================== ERRORS ====================================
_____________ ERROR collecting t/unit/concurrency/test_prefork.py ______________
ImportError while importing test module '/home/developer/celery/t/unit/concurrency/test_prefork.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.pyenv/versions/python3.7/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
t/unit/concurrency/test_prefork.py:11: in <module>
    from celery.concurrency.asynpool import iterate_file_descriptors_safely
celery/concurrency/asynpool.py:29: in <module>
    from billiard.compat import buf_t, isblocking, setblocking
E   ImportError: cannot import name 'buf_t' from 'billiard.compat' (/home/developer/.pyenv/versions/python3.7/lib/python3.7/site-packages/billiard/compat.py)
=============================== warnings summary ===============================
../.pyenv/versions/python3.7/lib/python3.7/site-packages/kombu/utils/compat.py:82
../.pyenv/versions/python3.7/lib/python3.7/site-packages/kombu/utils/compat.py:82
  /home/developer/.pyenv/versions/python3.7/lib/python3.7/site-packages/kombu/utils/compat.py:82: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
    for ep in importlib_metadata.entry_points().get(namespace, [])

../.pyenv/versions/python3.7/lib/python3.7/site-packages/_pytest/config/__init__.py:1233
  /home/developer/.pyenv/versions/python3.7/lib/python3.7/site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: xdfail_strict
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

../.pyenv/versions/python3.7/lib/python3.7/site-packages/sphinx/util/docutils.py:45
  /home/developer/.pyenv/versions/python3.7/lib/python3.7/site-packages/sphinx/util/docutils.py:45: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    __version_info__ = tuple(LooseVersion(docutils.__version__).version)

../.pyenv/versions/python3.7/lib/python3.7/site-packages/sphinx/util/rst.py:56
  /home/developer/.pyenv/versions/python3.7/lib/python3.7/site-packages/sphinx/util/rst.py:56: DeprecationWarning: 'environmentfilter' is renamed to 'pass_environment', the old name will be removed in Jinja 3.1.
    def heading(env: Environment, text: str, level: int = 1) -> str:

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
ERROR t/unit/concurrency/test_prefork.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 5 warnings, 1 error in 6.31s =========================
```

And alternatively when attempting to test locally calling `pytest t/unit` I get another set of errors, with 4 failing tests:
```
=================================================== FAILURES ====================================================
__________________________ test_BaseBackend_dict.test_not_an_exception_but_a_callable ___________________________

self = <t.unit.backends.test_base.test_BaseBackend_dict object at 0x111911990>

    def test_not_an_exception_but_a_callable(self):
        x = {
            'exc_message': ('echo 1',),
            'exc_type': 'system',
            'exc_module': 'os'
        }
    
        with pytest.raises(SecurityError,
                           match=re.escape(r"Expected an exception class, got os.system with payload ('echo 1',)")):
>           self.b.exception_to_python(x)
E           Failed: DID NOT RAISE <class 'celery.exceptions.SecurityError'>

t/unit/backends/test_base.py:597: Failed
--------------------------------------------- Captured stdout call ----------------------------------------------
1
________________________ test_BaseBackend_dict.test_not_an_exception_but_another_object _________________________

self = <t.unit.backends.test_base.test_BaseBackend_dict object at 0x11191db10>

    def test_not_an_exception_but_another_object(self):
        x = {
            'exc_message': (),
            'exc_type': 'object',
            'exc_module': 'builtins'
        }
    
        with pytest.raises(SecurityError,
                           match=re.escape(r"Expected an exception class, got builtins.object with payload ()")):
>           self.b.exception_to_python(x)
E           Failed: DID NOT RAISE <class 'celery.exceptions.SecurityError'>

t/unit/backends/test_base.py:608: Failed
_______________________ test_MongoBackend.test_init_mongodb_dnspython1_pymongo4_seedlist ________________________

self = <t.unit.backends.test_mongodb.test_MongoBackend object at 0x112028190>

    @pytest.mark.skipif(dns.version.MAJOR > 1,
                        reason="For dnspython version >= 2, pymongo's"
                               "srv_resolver calls resolver.resolve")
    @pytest.mark.skipif(pymongo.version_tuple[0] <= 3,
                        reason="For pymongo version > 3, options returns tls")
    def test_init_mongodb_dnspython1_pymongo4_seedlist(self):
        resolver = fake_resolver_dnspython()
        self.app.conf.mongodb_backend_settings = None
    
        with patch('dns.resolver.query', side_effect=resolver):
>           mb = self.perform_seedlist_assertions()

t/unit/backends/test_mongodb.py:200: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
t/unit/backends/test_mongodb.py:225: in perform_seedlist_assertions
    mb = MongoBackend(app=self.app, url=MONGODB_SEEDLIST_URI)
../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/backends/mongodb.py:76: in __init__
    uri_data = pymongo.uri_parser.parse_uri(self.url)
../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pymongo/uri_parser.py:532: in parse_uri
    nodes = dns_resolver.get_hosts()
../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pymongo/srv_resolver.py:119: in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pymongo/srv_resolver.py:104: in _get_srv_response_and_hosts
    for res in results]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

.0 = <list_iterator object at 0x1120446d0>

    (maybe_decode(res.target.to_text(omit_final_dot=True)), res.port)
>   for res in results]
E   AttributeError: 'str' object has no attribute 'to_text'

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pymongo/srv_resolver.py:104: AttributeError
_________________________ test_AsynPool.test_register_with_event_loop__no_on_tick_dupes _________________________

self = <t.unit.concurrency.test_prefork.test_AsynPool object at 0x1135b72d0>

    def test_register_with_event_loop__no_on_tick_dupes(self):
        """Ensure AsynPool's register_with_event_loop only registers
        on_poll_start in the event loop the first time it's called. This
        prevents a leak when the Consumer is restarted.
        """
        pool = asynpool.AsynPool(threads=False)
        hub = Mock(name='hub')
        pool.register_with_event_loop(hub)
        pool.register_with_event_loop(hub)
>       hub.on_tick.add.assert_called_once()

t/unit/concurrency/test_prefork.py:356: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

_mock_self = <Mock name='hub.on_tick.add' id='4661042192'>

    def assert_called_once(_mock_self):
        """assert that the mock was called only once.
        """
        self = _mock_self
        if not self.call_count == 1:
            msg = ("Expected '%s' to have been called once. Called %s times." %
                   (self._mock_name or 'mock', self.call_count))
>           raise AssertionError(msg)
E           AssertionError: Expected 'add' to have been called once. Called 2 times.

../../.pyenv/versions/3.7.4/lib/python3.7/unittest/mock.py:815: AssertionError
=============================================== warnings summary ================================================
../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/kombu/utils/compat.py:82
../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/kombu/utils/compat.py:82
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/kombu/utils/compat.py:82: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
    for ep in importlib_metadata.entry_points().get(namespace, [])

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/_pytest/config/__init__.py:1233
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: xdfail_strict
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:10
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _nlv = LooseVersion(_np_version)

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:11
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p14 = _nlv < LooseVersion("1.14")

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:12
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p15 = _nlv < LooseVersion("1.15")

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:13
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:13: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p16 = _nlv < LooseVersion("1.16")

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:14
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p17 = _nlv < LooseVersion("1.17")

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:15
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p18 = _nlv < LooseVersion("1.18")

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/setuptools/_distutils/version.py:351
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    other = LooseVersion(other)

../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/function.py:116
../../.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/function.py:116
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pandas/compat/numpy/function.py:116: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(_np_version) >= LooseVersion("1.17.0"):

t/unit/tasks/test_canvas.py: 14 warnings
t/unit/utils/test_functional.py: 6 warnings
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/pytest_subtests.py:143: PytestDeprecationWarning: A private pytest class or function was used.
    fixture = CaptureFixture(FDCapture, self.request)

t/unit/tasks/test_trace.py::test_trace::test_backend_error_should_report_failure
t/unit/worker/test_request.py::test_Request::test_execute_backend_error_acks_late
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py:662: RuntimeWarning: Exception raised outside body: Exception():
  Traceback (most recent call last):
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py", line 519, in trace_task
      uuid, retval, task_request, publish_result,
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/lib/python3.7/unittest/mock.py", line 965, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/lib/python3.7/unittest/mock.py", line 1025, in _mock_call
      raise effect
  Exception
  
    exc, exc_info.traceback)))

t/unit/tasks/test_trace.py::test_trace::test_backend_error_should_report_failure
t/unit/worker/test_request.py::test_Request::test_execute_backend_error_acks_late
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py:662: RuntimeWarning: Exception raised outside body: Exception():
  Traceback (most recent call last):
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py", line 519, in trace_task
      uuid, retval, task_request, publish_result,
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/lib/python3.7/unittest/mock.py", line 965, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/lib/python3.7/unittest/mock.py", line 1025, in _mock_call
      raise effect
  Exception
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py", line 584, in trace_task
      return task.__trace__(uuid, args, kwargs, request)
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py", line 572, in trace_task
      I, _, _, _ = on_error(task_request, exc, uuid)
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py", line 380, in on_error
      task, request, eager=eager, call_errbacks=call_errbacks,
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py", line 183, in handle_error_state
      call_errbacks=call_errbacks)
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py", line 228, in handle_failure
      call_errbacks=call_errbacks,
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/lib/python3.7/unittest/mock.py", line 965, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/lib/python3.7/unittest/mock.py", line 1025, in _mock_call
      raise effect
  Exception
  
    exc, exc_info.traceback)))

t/unit/worker/test_consumer.py::test_Consumer::test_collects_at_restart
t/unit/worker/test_worker.py::test_Consumer::test_start_connection_error
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
  In Celery 5.1 we introduced an optional breaking change which
  on connection loss cancels all currently executed tasks with late acknowledgement enabled.
  These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
  You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
  In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.
  
    warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

t/unit/worker/test_request.py::test_Request::test_from_message_invalid_kwargs
  /Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py:662: RuntimeWarning: Exception raised outside body: InvalidTaskError('Task keyword arguments is not a mapping'):
  Traceback (most recent call last):
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py", line 401, in trace_task
      kwargs.items
  AttributeError: 'str' object has no attribute 'items'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/Users/pinchas.lev/.pyenv/versions/3.7.4/envs/stellar_3_7/lib/python3.7/site-packages/celery/app/trace.py", line 404, in trace_task
      'Task keyword arguments is not a mapping')
  celery.exceptions.InvalidTaskError: Task keyword arguments is not a mapping
  
    exc, exc_info.traceback)))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================ short test summary info ============================================
FAILED t/unit/backends/test_base.py::test_BaseBackend_dict::test_not_an_exception_but_a_callable - Failed: DID...
FAILED t/unit/backends/test_base.py::test_BaseBackend_dict::test_not_an_exception_but_another_object - Failed:...
FAILED t/unit/backends/test_mongodb.py::test_MongoBackend::test_init_mongodb_dnspython1_pymongo4_seedlist - At...
FAILED t/unit/concurrency/test_prefork.py::test_AsynPool::test_register_with_event_loop__no_on_tick_dupes - As...
================= 4 failed, 2520 passed, 25 skipped, 3 xfailed, 39 warnings in 69.70s (0:01:09) =================
```

The purpose of this question is to figure out the best way forward.  My interest is in getting the codebase to work properly, before I attempt to make any contributions.

**Comment by pawl** [comment]
@PinchasLev I ran the tests locally recently with `tox -v -e 3.8-unit` and it was successful. Maybe the docs should be updated to suggest using tox?

**Comment by PinchasLev** [comment]
@pawl Thanks.  While I failed to run **tox** with the exact parameters you provided--probably owning to my setup, running it without flags runs it for several python versions in the range of 3.7, 3.8, 3.9 and 3.10.  The unit tests failed one of the tests for 3.7, but succeeded for the 3.9.  On it's try to test with python 3.8 it gave an error ```ERROR: InterpreterNotFound: python3.8```.  The same goes for python 3.10.  However--to my surprise--the python versions that are being run are independent of whatever **pyenv**s I have installed on my machine, so evidently I'm lacking in my understanding of python environments and tooling around **tox**.
Whether or not I must shore up that understanding before feeling comfortable working on the codebase is something I'm mulling over in my mind.
