### ISSUE TITLE
prefork error when start worker

### ISSUE THREAD

**Issue by dongchirua** [celery/celery#7208]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.2.3 (dawn-chorus) kombu:5.2.3 py:3.9.9
            billiard:3.6.4.0 py-amqp:5.0.9
platform -> system:Darwin arch:64bit
            kernel version:21.2.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/0

broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'redis://localhost:6379/0'
deprecated_settings: None
timezone: 'UTC'
task_serializer: 'json'
result_serializer: 'json'
result_expires: 3600
task_queue_ha_policy: 'all'
worker_prefetch_multiplier: 1
celery_acks_late: True
task_queues:
    (<unbound Queue test_parallel_queue -> <unbound Exchange test.exchange_name(direct)> -> D_Key>,
 <unbound Queue test_transaction_queue -> <unbound Exchange test.exchange_name(direct)> -> T_Key>)
task_default_queue: 'test_parallel_queue'
task_default_exchange: 'test.exchange_name'
task_default_routing_key: '********'
task_routes: {
    'FlushJobScoreToS3': {   'queue': 'test_transaction_queue',
                             'routing_key': '********'},
    'FlushWorkerScoreToDB': {   'queue': 'test_transaction_queue',
                                'routing_key': '********'},
    'JobClosed': {'queue': 'test_transaction_queue', 'routing_key': '********'},
    'JobInformationChanged': {   'queue': 'test_transaction_queue',
                                 'routing_key': '********'},
    'Notification': {   'queue': 'test_transaction_queue',
                        'routing_key': '********'},
    'WorkerChangePersonalInfo': {   'queue': 'test_transaction_queue',
                                    'routing_key': '********'}}
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.8
* **Minimal Celery Version**: 5.2.3
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: MacOS/Ubuntu
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
aiobotocore @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/5e/bf/3c/6783eb60c28cac1efe7b1c2659f3bce2d9ffd78812006043ca5462041c/aiobotocore-2.0.1.tar.gz
aiohttp @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/9b/46/14/b3421d6da32d3ef74cd2fbafd74b15f54b4755b3bf9d3826a73a219291/aiohttp-3.8.1-cp39-cp39-macosx_10_9_x86_64.whl
aioitertools @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/52/b5/48/a3fca6e3cb2d43ab4a772421b64375661bca9915cce2aa239fed0dbb1f/aioitertools-0.8.0-py3-none-any.whl
aiosignal @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/d3/d7/92/f7aa28b137b4b00e62270f58330cedde299917a71a3c00ee64913aa3c2/aiosignal-1.2.0-py3-none-any.whl
amqp @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/c8/53/a1/109ba91cb62b50e83bac8fd973e8fd02643dea2db190619b314f1fd0a8/amqp-5.0.9-py3-none-any.whl
app==2.3.0
async-timeout @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/62/ff/30/bd0ec891880d93bf40cf6e7c53ab08dd9eb6af45fa532c030731e6eed0/async_timeout-4.0.2-py3-none-any.whl
attrs @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/5b/25/94/5d165cd3190cb7dfdc98de86c28e8131fc6e19d83a504412664abffec0/attrs-21.4.0-py2.py3-none-any.whl
autoenv @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/c7/57/77/d45eb99c3dfe202ecbbed6b2c08850fa43c52bceb2292125cfcebc8c10/autoenv-1.0.0.tar.gz
billiard @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/cf/59/06/55d38419b5aa6e1fe731cb9d5dfdc4fa930000cc089eb421e3d039cfc2/billiard-3.6.4.0-py3-none-any.whl
botocore @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/84/59/50/ff814bc4aeab8f42b19c056c5eb427c4d6323753eb4e9c6dc032285075/botocore-1.22.8-py3-none-any.whl
celery @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/13/f0/12/3aacbfdf7fb55b35301ae6889ddac1e922c121a93c3ebb365b74806ad0/celery-5.2.3-py3-none-any.whl
certifi @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/71/9a/ba/a51b34ce9aacf9ac5dbb90d7c7335877522ee188189d9a521ee1a9c411/certifi-2021.10.8-py2.py3-none-any.whl
charset-normalizer @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/f6/3f/55/3942ccd83d837749333a1accbc46779cf465f7a099099d5eac9336caa5/charset_normalizer-2.0.10-py3-none-any.whl
click @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/34/4d/5b/2e936191a48c61e37319c157af7e3c0dbdde9b80ccdd04b7940f99c5db/click-8.0.3-py3-none-any.whl
click-didyoumean @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/fc/14/66/e0f912d7ee8b42454ca7c5b7b2a5b9cec16198ea38cb018c904fc95c87/click_didyoumean-0.3.0-py3-none-any.whl
click-plugins @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/87/75/c3/fb63a9b9f496004a8bf69eb791be6e419ca0cd59f1d7e250a1bd8322e3/click_plugins-1.1.1-py2.py3-none-any.whl
click-repl @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/36/62/78/c7266ac6c43eed045786703622efa441aeb52948537f4332c66609e511/click_repl-0.2.0-py3-none-any.whl
clickclick @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/c2/ba/a6/1d8ff79af045c11b8172abc2f9a581a7f11ba6aa7bbcdf3bca36eae1bd/clickclick-20.10.2-py2.py3-none-any.whl
colorama @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/9e/b3/11/7d87ac44fdb2d557301f1f4086a37c080d1482a98751abe7cdbabbad26/colorama-0.4.4-py2.py3-none-any.whl
connexion @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/1f/7c/42/b9090c675a1aaf0b81ac39bed39bb254f9dfde75893630e6f13e7b14a0/connexion-2.9.0-py2.py3-none-any.whl
coverage @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/0a/78/2b/c63163d1b75109e88d8501ae8f9894b11e8160a1f6d5684ac7e00c77d1/coverage-6.2-cp39-cp39-macosx_10_9_x86_64.whl
Deprecated @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/02/6c/d9/698c9c1be5d7e779bb2ff730bae7fb601b8d636233ca2ba1548761a514/Deprecated-1.2.13-py2.py3-none-any.whl
flake8 @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/99/5c/01/a49c075bc6dead5c60588c1cd1701f63d614740792c9a09fb133b41d58/flake8-4.0.1-py2.py3-none-any.whl
Flask @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/2f/65/9e/7fe305316b8f564a8577a93bfeb984493ce9eeb1e8926abb0ed9030910/Flask-1.1.2-py2.py3-none-any.whl
frozenlist @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/7e/94/50/9a9059696871d52d8933fa24931a2854b46367652bf7b6ee9622fbc94a/frozenlist-1.2.0-cp39-cp39-macosx_10_9_x86_64.whl
fsspec @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/21/c5/18/c49ba5010477a09fddd7a039e5d6496310652a5637ced473b5b1e7331d/fsspec-2021.11.1-py3-none-any.whl
idna @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/d5/04/80/9c17fd3240a37d12ff2ef042b0306aeb1abd2d8b95f150fd60be938352/idna-3.3-py3-none-any.whl
inflection @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/2f/ed/82/68adaa9865195edc03da6786b66cc708b169265e333e239c28b11e9a4d/inflection-0.5.1-py2.py3-none-any.whl
iniconfig @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/fa/b0/c6/10cfac68c9e6de9d2a1678366ca89fd9292b362c1760dbe758e41691cb/iniconfig-1.1.1-py2.py3-none-any.whl
isodate @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/27/72/73/797ff02d8a5aa44201f572e41bfe29a288347bae5e95f30d502cdb5528/isodate-0.6.1-py2.py3-none-any.whl
itsdangerous @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/56/85/a6/70db371e4b63cdd55bf95de92ac726d8cf622812e0d7383910edd55619/itsdangerous-2.0.1-py3-none-any.whl
Jinja2 @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/3b/12/80/ed05a8559d6ad1e85324dbcebfe790670d339c674fb15c419b29aae138/Jinja2-3.0.3-py3-none-any.whl
jmespath @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/2c/f0/52/b0ba93d941bd49c8719dee7ca27d2096bf96e17948667388c3ee2ac8f8/jmespath-0.10.0-py2.py3-none-any.whl
jsonschema @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/db/1d/66/ad84fa70cc987bd4aad68be808562321cdab3cb03f4d5d7714a0e0571c/jsonschema-3.2.0-py2.py3-none-any.whl
kombu @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/0a/e9/38/34c2684e703326460de5c15d7e83e7998817fdb377e5a2d10faf77496d/kombu-5.2.3-py3-none-any.whl
MarkupSafe @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/20/e4/29/5b1a93d4ee8437f01551437cffbb57ba6744c59796443ca99051473f75/MarkupSafe-2.0.1-cp39-cp39-macosx_10_9_x86_64.whl
mccabe @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/96/5e/5f/21ae5296697ca7f94de4da6e21d4936d74029c352a35202e4c339a4253/mccabe-0.6.1-py2.py3-none-any.whl
mmh3 @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/fa/5f/68/cc07b5988274892ad851f41176c79596b89dbc78df1f56f9e2daa29125/mmh3-3.0.0-cp39-cp39-macosx_10_9_x86_64.whl
multidict @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/ad/d3/80/34243b8870f7ed7b481e970b90a240314cc25f3b3cacf2ce3e5352c53d/multidict-5.2.0-cp39-cp39-macosx_10_9_x86_64.whl
newrelic @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/8e/fe/9d/15304e631e989ee06d93435346b2f9f71569d5df7235125843ddeeea27/newrelic-7.2.4.171.tar.gz
numpy @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/e0/b1/df/690d9fbfee2f04156babdedd7e21d2b91c305c85e56b7ff895602e3c27/numpy-1.22.0-cp39-cp39-macosx_10_9_x86_64.whl
openapi-schema-validator @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/0a/c5/18/0035a3f7c82070beba89539d074664461caf8d8a14f4cfea96748716c8/openapi_schema_validator-0.1.6-py3-none-any.whl
openapi-spec-validator @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/cb/0a/bd/dfefe8a8ae0520abc038913c33736627d7ffbf742936c56eec1bdb3319/openapi_spec_validator-0.3.1-py3-none-any.whl
orjson @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/94/d0/bc/1b89a0263d4b14a726e9b3fa0914ea11b6b4b5e98147e3645f1d4f6c09/orjson-3.6.5-cp39-cp39-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl
packaging @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/47/3f/ce/b240169f7d8bef1ff24a0269b709721ce86543c2ec25e0b6adb2c2d7ac/packaging-21.3-py3-none-any.whl
pandas @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/d9/b6/7f/7014f6ad29530dce41444ac8497a638f8cf1391912e4d71c2f71b31273/pandas-1.3.5-cp39-cp39-macosx_10_9_x86_64.whl
pluggy @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/81/78/ca/13f743a3628faf5a0b7f021efb45f2193acba3a13663d498f6b34bf02e/pluggy-1.0.0-py2.py3-none-any.whl
pottery @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/17/19/60/7e5f92bdd0b8c76fca61a4b9655e890867df870c51d22fa585cdc5aa89/pottery-2.3.5-py3-none-any.whl
prompt-toolkit @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/ec/2a/77/5024fe40d375fe25a5d638cb593ec62b68f66f18670ea6eb8be5e0d414/prompt_toolkit-3.0.24-py3-none-any.whl
psycopg2-binary @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/f0/06/db/bc90ca22d1c7266b52ac8ec7cb5b3abd9af75a70e6d01090b78941236c/psycopg2_binary-2.9.3-cp39-cp39-macosx_10_14_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
py @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/b3/5c/47/ba5a596e01a2b61fa2daa6a438252483ad8c04e6c99e5dc22eaf8a489a/py-1.11.0-py2.py3-none-any.whl
pycodestyle @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/80/25/e5/ced4effd2487693e96521aebb353ce58ad0d81417f71c480419ea8f44a/pycodestyle-2.8.0-py2.py3-none-any.whl
pyflakes @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/ad/8e/6d/e46117c96aa3e955c40ed2f0d35b29910b0e557e327fbbba17fd8c390c/pyflakes-2.4.0-py2.py3-none-any.whl
pyparsing @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/61/f1/da/6428e68d48dbbc9e9b942cf2dfb6b5a7faa052423078aae46465c3c8e0/pyparsing-3.0.6-py3-none-any.whl
pyrsistent @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/a3/50/5c/55747fd13209ee597a3e45d1ad70eef133559516e470c05a47c29365b0/pyrsistent-0.18.0-cp39-cp39-macosx_10_9_x86_64.whl
pytest @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/28/be/f1/ce8fa22c989106fc7c1ee7fa31d55d7f31aee1c58c63b2a43670601b79/pytest-6.2.5-py3-none-any.whl
python-dateutil @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/53/f8/2a/7d63ce15df7386e9536e83413453f8aa845b47fb425f05c4ca2fb231c3/python_dateutil-2.8.2-py2.py3-none-any.whl
pytz @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/3e/f3/dd/6629bf5ed0a970a128e0a015f2af3b67280e749a56fdaabdaa06d5fc6b/pytz-2021.3-py2.py3-none-any.whl
PyYAML @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/b6/55/22/537845ea953a4d8d5006f11bdd1b03824425d7f809d5a7ae8efbbeab95/PyYAML-5.4.1-cp39-cp39-macosx_10_9_x86_64.whl
redis @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/60/29/8c/e19b4c9eb6ae3aed8e83c8f884f3d461ad28b66e014369074b8dfc3a7e/redis-4.1.0-py3-none-any.whl
requests @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/5e/2d/78/049121be0a13da42ecf9b2e031d273c7b57436104bd6f525f86cb1c668/requests-2.27.0-py2.py3-none-any.whl
s3fs @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/77/f3/ee/c284c3b80b95fe2f803b79db3487134ef76451867f3fdeb41c69d25f45/s3fs-2021.11.1-py3-none-any.whl
six @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/08/9f/47/c16ae03035fc69eaf100ea39657a49baaeef714e25a52575710c34cd48/six-1.16.0-py2.py3-none-any.whl
structlog @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/d5/18/ec/dae176ee85c67dc20c576e0e6ff3570f7435bc9fcfd99d3642590ff256/structlog-21.5.0-py3-none-any.whl
swagger-ui-bundle @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/7e/1a/72/2de6ed0696ad1cf681732dbeb5edf6ecf902eea8176e8b754261ddb4e6/swagger_ui_bundle-0.0.9-py3-none-any.whl
toml @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/6b/6a/c9/53b19f7870a77d855e8b05ecdc98193944e5d246dafe11bbcad850ecba/toml-0.10.2-py2.py3-none-any.whl
typing-extensions @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/88/68/28/f1a10f89c5267ca2c8a3c0e79c45230a866cd7c52d295e556597219c54/typing_extensions-4.0.1-py3-none-any.whl
urllib3 @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/55/46/d1/1acba0600879bfaada54191116fbaea89a464f437b3f949bc9c2a220e7/urllib3-1.26.7-py2.py3-none-any.whl
vine @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/c1/80/fc/ccb677b19dd37eb7ad77b94745e563b67472b45dbcfb34e75a6110f12f/vine-5.0.0-py2.py3-none-any.whl
wcwidth @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/7d/f4/60/0737157bb9711fec72c70dff523aa54491eef317e0d586cf5388ff0908/wcwidth-0.2.5-py2.py3-none-any.whl
Werkzeug @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/5b/83/26/5e5a83cbe509bcc5d52ce4a8fba5d1ad0f8bd321d67002ec782bade539/Werkzeug-1.0.1-py2.py3-none-any.whl
wrapt @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/ba/1e/e4/5cf7d09568503d60c13636e83332a06ff289571ec166c18c6d8e229036/wrapt-1.13.3-cp39-cp39-macosx_10_9_x86_64.whl
yarl @ file:///Users/bryan/Library/Caches/pypoetry/artifacts/be/64/bc/6045b0ef5702217e72067b8b60f36f6c099f579426e06387bae4341940/yarl-1.7.2-cp39-cp39-macosx_10_9_x86_64.whl
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior
After run `celery -A run.celery worker -n D -c 1 -Q queues_DISTRIBUTED_QUEUE --loglevel info` celery works normally in version  `5.2.3`

Note: in `5.1.2` celery works normally 

# Actual Behavior
Celery throws exceptions and stop
```
[2022-01-06 02:42:13,186: ERROR/ForkPoolWorker-1] Process ForkPoolWorker-1
Traceback (most recent call last):
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/billiard/pool.py", line 289, in __call__
    self.after_fork()
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/billiard/pool.py", line 421, in after_fork
    self.initializer(*self.initargs)
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/concurrency/prefork.py", line 75, in process_initializer
    task.__trace__ = build_tracer(name, task, app.loader, hostname,
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 361, in build_tracer
    push_request = request_stack.push
AttributeError: 'NoneType' object has no attribute 'push'
[2022-01-06 02:42:13,189: WARNING/ForkPoolWorker-1] Process ForkPoolWorker-1:
[2022-01-06 02:42:13,189: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
[2022-01-06 02:42:13,190: WARNING/ForkPoolWorker-1]   File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2022-01-06 02:42:13,190: WARNING/ForkPoolWorker-1]   File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2022-01-06 02:42:13,190: WARNING/ForkPoolWorker-1]   File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/billiard/pool.py", line 289, in __call__
    self.after_fork()
[2022-01-06 02:42:13,191: WARNING/ForkPoolWorker-1]   File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/billiard/pool.py", line 421, in after_fork
    self.initializer(*self.initargs)
[2022-01-06 02:42:13,191: WARNING/ForkPoolWorker-1]   File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/concurrency/prefork.py", line 75, in process_initializer
    task.__trace__ = build_tracer(name, task, app.loader, hostname,
[2022-01-06 02:42:13,191: WARNING/ForkPoolWorker-1]   File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 361, in build_tracer
    push_request = request_stack.push
[2022-01-06 02:42:13,191: WARNING/ForkPoolWorker-1] AttributeError: 'NoneType' object has no attribute 'push'
[2022-01-06 02:42:13,207: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2022-01-06 02:42:13,229: INFO/MainProcess] mingle: searching for neighbors
[2022-01-06 02:42:14,267: INFO/MainProcess] mingle: all alone
[2022-01-06 02:42:14,272: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'push'")
Traceback (most recent call last):
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/worker/consumer/tasks.py", line 26, in start
    c.update_strategies()
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 552, in update_strategies
    task.__trace__ = build_tracer(name, task, loader, self.hostname,
  File "/Users/bryan/workplace/mylong/data-event-bus/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 361, in build_tracer
    push_request = request_stack.push
AttributeError: 'NoneType' object has no attribute 'push'
```

**Comment by istapletoncordascosfdc** [comment]
@dongchirua this seems answered here: https://github.com/celery/celery/discussions/7172 and works for me

**Comment by auvipy** [comment]
> @dongchirua this seems answered here: #7172 and works for me

let us know if this solves your problem

**Comment by kbehlers** [comment]
Related issue and comment: https://github.com/celery/celery/issues/7173#issuecomment-1206584450
