### ISSUE TITLE
Run 'Nest Steps' code example code error

### ISSUE THREAD

**Issue by xiaolitongxue666** [celery/celery#7323]
OS: Centos8 Stram
Python env:
```python
# Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
celery = "*"

[dev-packages]

[requires]
python_version = "3.10"
```
Project struct
```bash
.
├── dump.rdb
├── Pipfile
├── Pipfile.lock
├── proj
│   ├── celery.py
│   ├── dump.rdb
│   ├── __init__.py
│   └── tasks.py
└── README.md
```
```python
#tasks.py
#proj/tasks.py
from .celery import app


@app.task
def add(x, y):
    return x + y


@app.task
def mul(x, y):
    return x * y


@app.task
def xsum(numbers):
    return sum(numbers)

```

```python
#proj/celery.py¶
from celery import Celery

app = Celery('proj',
             broker='redis://localhost',
             backend='redis://localhost//',
             include=['proj.tasks'])

app.conf.broker_url = 'redis://localhost:6379/0'

#Optional configuration, see the application user guide.
app.conf.update(
    result_expires=3600,
)

if __name__ == '__main__':
    app.start()

```
Now I change to dir abrove 'proj' run this:
```bash
celery -A proj worker --loglevel=INFO 
```
Error log
```bash
+ celery -A proj worker --loglevel=INFO
/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
[2022-02-25 16:59:20,943: CRITICAL/MainProcess] Unrecoverable error: ValueError("invalid literal for int() with base 10: ''")
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/app/base.py", line 1250, in backend
    return self._local.backend
AttributeError: '_thread._local' object has no attribute 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/bootsteps.py", line 112, in start
    self.on_start()
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/apps/worker.py", line 136, in on_start
    self.emit_banner()
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/apps/worker.py", line 170, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/apps/worker.py", line 232, in startup_info
    results=self.app.backend.as_uri(),
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/app/base.py", line 1252, in backend
    self._local.backend = new_backend = self._get_backend()
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/app/base.py", line 958, in _get_backend
    return backend(app=self, url=url)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/backends/redis.py", line 264, in __init__
    self.connparams = self._params_from_url(url, self.connparams)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/celery/backends/redis.py", line 342, in _params_from_url
    connparams['db'] = int(db)
ValueError: invalid literal for int() with base 10: ''

```

By the way , I run first-steps-with-celery work well .

**Comment by xiaolitongxue666** [comment]
I make a edit mistake , sorry for that . Already solved .

**Comment by auvipy** [comment]
from the next time open a discussion or post in stackoverflw first before opening an issue please

**Comment by xiaolitongxue666** [comment]
> 

Yes , I'll thanks
