### ISSUE TITLE
Overflow error for periodic tasks after hour change

### ISSUE THREAD

**Issue by rvcadding** [celery/celery#7381]
### Discussed in https://github.com/celery/celery/discussions/7380

<div type='discussions-op-text'>

<sup>Originally posted by **rvcadding** March 28, 2022</sup>
Hi, I have the following problem: I run some periodic tasks using crontabs and the DatabaseScheduler from django_celery_beat, using 'Europe/Madrid' as timezone for the crontabs. After the hour change yesterday, trying to enable these tasks throws an overflow error.

I think there is a bug in the _when() method in the celery/beat.py file.
Before the hour change, I could enable any periodic task, but now I can't.

Celery version: 4.2.0rc2
django_celery_beat: 1.4.0
Django version: 2.1.7
Python: 3.6.15

Relevant project settings:

TIME_ZONE = 'UTC'
USE_TZ = True
...
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

Error:
DatabaseScheduler: Schedule changed.
Writing entries...
 DatabaseScheduler: Fetching database schedule
Current schedule:
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4
          * *
           * (m/h/d/dM/MY), UTC>
         >
 <ModelEntry: taskX taskX(*[], **{'par1': 'value1', 'par2': ['value2']}) <crontab: 30 11
          * *
           * (m/h/d/dM/MY), Europe/Madrid>
         >
 Writing entries...
 beat raised exception <class 'OverflowError'>: OverflowError('mktime argument out of range',)
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 109, in start_scheduler
     service.start()
   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 588, in start
     interval = self.scheduler.tick()
   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 293, in tick
     self.populate_heap()
   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 271, in populate_heap
     0 if is_due else next_call_delay
   File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 259, in _when
     return (mktime(entry.default_now().timetuple()) +
 OverflowError: mktime argument out of range
 Traceback (most recent call last):
 File "/usr/local/bin/celery", line 8, in <module>
 sys.exit(main())
 File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
 _main()
 File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
 cmd.execute_from_commandline(argv)
 File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 484, in execute_from_commandline
 super(CeleryCommand, self).execute_from_commandline(argv)))
 File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
 return self.handle_argv(self.prog_name, argv[1:])
 File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 476, in handle_argv
 return self.execute(command, argv)
 File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 408, in execute
 .run_from_argv(self.prog_name, argv[1:], command=argv[0])
 File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 279, in run_from_argv
 sys.argv if argv is None else argv, command)
 File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 363, in handle_argv
 return self(*args, **options)
 File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
 ret = self.run(*args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
 return beat().run()
 File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 81, in run
 self.start_scheduler()
 File "/usr/local/lib/python3.6/site-packages/celery/apps/beat.py", line 109, in start_scheduler
 service.start()
 File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 588, in start
 interval = self.scheduler.tick()
 File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 293, in tick
 self.populate_heap()
 File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 271, in populate_heap
 0 if is_due else next_call_delay
 File "/usr/local/lib/python3.6/site-packages/celery/beat.py", line 259, in _when
 return (mktime(entry.default_now().timetuple()) +
 OverflowError
 :
 mktime argument out of range
 Writing entries...
 Writing entries...

Steps to replicate:
1- Create a crontab periodic task, using some timezone different from 'UTC', like 'Europe/Madrid'
2- Try to enable it or import it using a Django loader command.</div>

**Comment by ljluestc** [comment]
1. Patched celery/beat.py (Workaround)
Since you’re using Celery 4.2.0rc2, you can patch the _when() method to avoid the overflow error. Replace the problematic logic in /usr/local/lib/```3.6/site-packages/celery/beat.py around line 259 with this:
```
from time import mktime
from datetime import datetime
import pytz

def _when(self, entry, now=None):
    """Calculate the next scheduled time for the entry."""
    if now is None:
        now = entry.default_now()
    try:
        # Original logic
        next_time = mktime(entry.default_now().timetuple()) + entry.schedule.remaining_estimate(now).total_seconds()
        # Clamp to avoid overflow
        if next_time > 2**31 - 1:  # Max 32-bit signed int (2038 problem)
            next_time = 2**31 - 1
        elif next_time < -2**31:  # Min 32-bit signed int
            next_time = -2**31
        return next_time
    except (OverflowError, ValueError):
        # Fallback: Use current time + minimum delay if calculation fails
        return mktime(now.timetuple()) + 60  # Add 1 minute as a safe fallback
```

However, editing library files directly isn’t ideal. Instead, upgrading Celery or using a custom scheduler is recommended. Below, I’ll proceed with a complete working setup assuming you upgrade to Celery 5.3.6 (latest stable as of Feb 20, 2025) where this bug is resolved.
2. Complete Django Project
Directory Structure
myproject/
├── myproject/
│   ├── __init__.py
│   ├── settings.py
│   ├── celery.py
│   ├── urls.py
│   └── wsgi.py
├── tasks/
│   ├── __init__.py
│   └── tasks.py
├── manage.py
└── requirements.txt
requirements.txt
celery==5.3.6
django==2.1.7  # Your version
django-celery-beat==1.4.0  # Your version
```-dateutil==2.8.2
pytz==2024.1
redis==5.0.1  # For Celery broker
```

Install with: pip install -r requirements.txt
myproject/settings.py
```
import os
from celery.schedules import crontab

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = 'your-secret-key'
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'
WSGI_APPLICATION = 'myproject.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

TIME_ZONE = 'UTC'
USE_TZ = True

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_TIMEZONE = 'UTC'  # Match Django's TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

STATIC_URL = '/static/'

```

myproject/celery.py
```
import os
from celery import Celery

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings')

app = Celery('myproject')
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks()

@app.task(bind=True, ignore_result=True)
def debug_task(self):
    print(f'Request: {self.request!r}')

```

myproject/__init__.py
```
from .celery import app as celery_app

__all__ = ('celery_app',)
```

tasks/tasks.py
```
from celery import shared_task

@shared_task
def example_task(par1, par2):
    print(f"Running task with par1={par1}, par2={par2}")
    return f"Task completed with {par1} and {par2}"
```

myproject/urls.py
```
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
3. Configure Periodic Task in Django Admin
Run migrations: ``` manage.py migrate
Create a superuser: ``` manage.py createsuperuser
Start the Django development server: ``` manage.py runserver
Start Redis (if not running): Install Redis and run redis-server.
Start Celery worker: celery -A myproject worker -l info
Start Celery Beat: celery -A myproject beat -l info
Go to http://localhost:8000/admin/ and log in.
Under "Django Celery Beat":
Add a Crontab Schedule:
Minute: 30
Hour: 11
Day of Week: *
Day of Month: *
Month of Year: *
Timezone: Europe/Madrid
Add a Periodic Task:
Name: taskX
Task: tasks.tasks.example_task
Arguments: []
Keyword Arguments: {"par1": "value1", "par2": ["value2"]}
Crontab: Select the crontab you created above.
Enabled: Check the box.
4. Running the Setup
Worker: celery -A myproject worker -l info
Beat: celery -A myproject beat -l info
Verify: The task should run at 11:30 AM Europe/Madrid time daily without the overflow error if using Celery 5.3.6. If you must stick to 4.2.0rc2, apply the patch above.
