### ISSUE TITLE
Redis BROKER_URL causes KeyError('No such transport https')

### ISSUE THREAD

**Issue by stuaxo** [celery/celery#7512]
I have my config setup to point to redis [1]

```python
 celery -A common.celery inspect conf
->  celery@orangered: ERROR
        KeyError('No such transport: https')

1 node online.
```

[1] The following is my local dev config, I have the same error on my actual server.

```python
In [5]: pprint({k:v for k, v in app.conf.items() if k.startswith('CELERY')})
{'CELERY_ACCEPT_CONTENT': ['json'],
 'CELERY_BEAT_SCHEDULE': {'check_any_unchecked_transactions': {'schedule': datetime.timedelta(seconds=15),
                                                               'task': 'checks.tasks.update_checks'},
                          'sqlite_export': {'schedule': datetime.timedelta(seconds=1800),
                                            'task': 'exporter.sqlite.tasks.export_and_upload_sqlite'}},
 'CELERY_BROKER_URL': 'redis://0.0.0.0:6379/1',
 'CELERY_RESULT_BACKEND': 'redis://0.0.0.0:6379/1',
 'CELERY_TASK_SERIALIZER': 'json',
 'CELERY_TIMEZONE': 'UTC',
 'CELERY_TRACK_STARTED': True}
```

**Comment by stuaxo** [comment]
Hi @thedrow how can I help verify this ?

**Comment by stuaxo** [comment]
I found celery --report, here is the output:

```python
celery -A common.celery report      
Traceback (most recent call last):
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/kombu/transport/__init__.py", line 57, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: 'https'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stu/.virtualenvs/dit-tamato/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/bin/celery.py", line 162, in report
    ctx.obj.echo(app.bugreport())
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/app/base.py", line 952, in bugreport
    return bugreport(self)
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/app/utils.py", line 374, in bugreport
    human_settings=app.conf.humanize(),
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/app/utils.py", line 196, in humanize
    for key, value in self.table(with_defaults, censored).items())
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/app/utils.py", line 187, in table
    return filt({
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/app/utils.py", line 344, in filter_hidden_settings
    return {k: maybe_censor(k, v) for k, v in conf.items()}
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/app/utils.py", line 344, in <dictcomp>
    return {k: maybe_censor(k, v) for k, v in conf.items()}
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/celery/app/utils.py", line 338, in maybe_censor
    return Connection(value).as_uri(mask=mask)
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/kombu/connection.py", line 181, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/kombu/transport/__init__.py", line 85, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/home/stu/.virtualenvs/dit-tamato/lib/python3.8/site-packages/kombu/transport/__init__.py", line 66, in resolve_transport
    raise KeyError(f'No such transport: {transport}')
KeyError: 'No such transport: https'

```
