### ISSUE TITLE
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type text/plain (text/plain)

### ISSUE THREAD

**Issue by zhenzi0322** [celery/celery#7635]
The output is as follows：
```cmd
[2022-07-18 13:57:14,839: CRITICAL/MainProcess] Can't decode message body: ContentDisallowed('Refusing to deserialize untrusted content of type text/plain (text/plain)') [type:'text/plain' encoding:'UTF-8' headers:{}]

body: '{"path":"dev/test/02c8578d2fa4d18bb44dfaec0ef721ea.jpg","execute_type":"vip","id":"20"}' (87b)
Traceback (most recent call last):
  File "D:\packages\python\Envs\celery-mq-iryfzYIF\lib\site-packages\celery\worker\consumer\consumer.py", line 578, in on_task_received
    type_ = message.headers['task']  # protocol v2
KeyError: 'task'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\packages\python\Envs\celery-mq-iryfzYIF\lib\site-packages\celery\worker\consumer\consumer.py", line 583, in on_task_received
    payload = message.decode()
  File "D:\packages\python\Envs\celery-mq-iryfzYIF\lib\site-packages\kombu\message.py", line 194, in decode
    self._decoded_cache = self._decode()
  File "D:\packages\python\Envs\celery-mq-iryfzYIF\lib\site-packages\kombu\message.py", line 198, in _decode
    return loads(self.body, self.content_type,
  File "D:\packages\python\Envs\celery-mq-iryfzYIF\lib\site-packages\kombu\serialization.py", line 242, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type text/plain (text/plain)
```

**Comment by auvipy** [comment]
is text serialization supported / allowed in kombu/celery?

**Comment by zhenzi0322** [comment]
> is text serialization supported / allowed in kombu/celery?

Not clear, the producer is the java server, the consumer is the python side of the program

**Comment by auvipy** [comment]
i think you should try supported serializer

**Comment by zhenzi0322** [comment]
> i think you should try supported serializer

What are the serializations supported by celery?

**Comment by auvipy** [comment]
json, msgpack, pickle
