### ISSUE TITLE
I have some problem when host my python server with celery

### ISSUE THREAD

**Issue by devlancer412** [celery/celery#7743]
I used celery for backend task and it runs correctly on local environment.
I use Windows for os and use Redis server.

After host server  to ubuntu server such error occured.

This is my error log
```error
[2022-09-05 00:04:52,275: ERROR/ForkPoolWorker-2] Task src.celery.dispatch_transaction[71b41e05-0fd1-4b5f-b6b8-35ee7297164d] raised unexpected: EncodeError(TypeError('Object of type coroutine is not JSON serializable'))
Traceback (most recent call last):
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/serialization.py", line 39, in _reraise_errors
    yield
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/celery/app/trace.py", line 518, in trace_task
    task.backend.mark_as_done(
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/celery/backends/base.py", line 162, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/celery/backends/base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/celery/backends/base.py", line 962, in _store_result
    self._set_with_state(self.get_key_for_task(task_id), self.encode(meta), state)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/celery/backends/base.py", line 418, in encode
    _, _, payload = self._encode(data)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/celery/backends/base.py", line 422, in _encode
    return dumps(data, serializer=self.serializer)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/serialization.py", line 209, in dumps
    with _reraise_errors(EncodeError):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/serialization.py", line 43, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/serialization.py", line 39, in _reraise_errors
    yield
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/serialization.py", line 210, in dumps
    payload = encoder(data)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/utils/json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/modern-game-backend/environment/lib/python3.10/site-packages/kombu/utils/json.py", line 58, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type coroutine is not JSON serializable
```

And this is my celery task code:
```python
from datetime import datetime, timedelta
from celery import Celery, shared_task
from celery.utils.log import get_task_logger
from src.database import database, Database
from src.models import Transaction
from src.changenow_api.client import api_wrapper as cnio_api
from config import cfg

celery = Celery(
    __name__, broker="redis://127.0.0.1:6379/0", backend="redis://127.0.0.1:6379/0"
)

database = Database()
engine = database.get_db_connection()
session = database.get_db_session()

celery_log = get_task_logger(__name__)

celery.conf.update(
    task_serializer="json", result_serializer="json", accept_content=["json"]
)


@celery.task
def divide(x, y):
    import time

    time.sleep(5)
    return x / y


@celery.task
async def dispatch_transaction(id: str):
    transaction: Transaction = (
        session.query(Transaction).filter(Transaction.transaction_id == id).one()
    )
    endTime = datetime.strptime(
        transaction.created_at, "%Y-%m-%d %H:%M:%S"
    ) + timedelta(days=1)
    while transaction.status != "finished":
        try:
            response = cnio_api(
                "TX_STATUS", id=transaction.transaction_id, api_key=cfg.CN_API_KEY
            )
            celery_log.info(transaction.transaction_id, response["status"])
            transaction.status = response["status"]

            if datetime.now() > endTime:
                break
        except Exception as ex:
            celery_log.error(ex)
```

And I added task with such code:
```python
            dispatch_transaction.delay(str(response["id"]))
```

Please help me.

**Comment by devlancer412** [comment]
> I also meet this problem with celery. Has someone solved this problem?

You can try with sync function.

**Comment by Domtry** [comment]
I also meet this problem with celery. Has someone solved this problem?

**Comment by Kalkulus1** [comment]
The problem is, celery works well with sync functions. You could use asyncio to run your async func within a sync func


```python
from datetime import datetime, timedelta
from celery import Celery
from src.database import database, Database
from src.models import Transaction
from src.changenow_api.client import api_wrapper as cnio_api
from config import cfg
import asyncio

celery = Celery(
    __name__, broker="redis://127.0.0.1:6379/0", backend="redis://127.0.0.1:6379/0"
)

database = Database()
engine = database.get_db_connection()
session = database.get_db_session()

@celery.task
def dispatch_transaction_sync(id: str):
    asyncio.run(dispatch_transaction_async(id))

async def dispatch_transaction_async(id: str):
    transaction: Transaction = (
        session.query(Transaction).filter(Transaction.transaction_id == id).one()
    )
    endTime = datetime.strptime(
        transaction.created_at, "%Y-%m-%d %H:%M:%S"
    ) + timedelta(days=1)
    while transaction.status != "finished":
        try:
            response = await asyncio.to_thread(
                cnio_api,
                "TX_STATUS",
                id=transaction.transaction_id,
                api_key=cfg.CN_API_KEY
            )
            celery_log.info(transaction.transaction_id, response["status"])
            transaction.status = response["status"]

            if datetime.now() > endTime:
                break
        except Exception as ex:
            celery_log.error(ex)
```

**Comment by liuweijie1234** [comment]
I also meet this problem with celery. Has someone solved this problem?
celery 5.4.0, windows

**Comment by Domtry** [comment]
Hi @liuweijie1234 Please open a new ticket and add the details of the problem.
