### ISSUE TITLE
In redis sharded cluster environment, raised redis.exceptions.ResponseError: 'BRPOP' command keys must in same slot

### ISSUE THREAD

**Issue by zyicy** [celery/celery#7751]
[2022-09-09 14:25:58,043: CRITICAL/MainProcess] Unrecoverable error: ResponseError("'BRPOP' command keys must in same slot",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/mingle.py", line 40, in start
    self.sync(c)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/mingle.py", line 44, in sync
    replies = self.send_hello(c)
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/consumer/mingle.py", line 57, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/usr/local/lib/python3.6/dist-packages/celery/app/control.py", line 143, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/control.py", line 95, in _request
    timeout=self.timeout, reply=True,
  File "/usr/local/lib/python3.6/dist-packages/celery/app/control.py", line 454, in broadcast
    limit, callback, channel=channel,
  File "/usr/local/lib/python3.6/dist-packages/kombu/pidbox.py", line 321, in _broadcast
    channel=chan)
  File "/usr/local/lib/python3.6/dist-packages/kombu/pidbox.py", line 360, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/virtual/base.py", line 963, in drain_events
    get(self._deliver, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/redis.py", line 359, in get
    ret = self.handle_event(fileno, event)
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/redis.py", line 341, in handle_event
    return self.on_readable(fileno), self
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.6/dist-packages/kombu/transport/redis.py", line 714, in _brpop_read
    **options)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: 'BRPOP' command keys must in same slot

**Comment by zyicy** [comment]
celery version is 4.2.1

**Comment by auvipy** [comment]
use celery latest stable version please. that celery version is very old and not maintained anymore

**Comment by nopipifish** [comment]
I also encountered the same problem and used the latest version of celery. Has this problem been solved?

**Comment by auvipy** [comment]
https://github.com/celery/kombu/pull/1733 can you check?

**Comment by ZLotusRain** [comment]
set priority_steps to [0] in transport_options or create a series of keys related to the priority in redis cluster when using redis will sovle the problem, because kombu will try to pop item from a series of keys constructed by the priority, if some key here can't be hashed to the same slot, the error will occur.
