### ISSUE TITLE
amqp.exceptions.ConnectionForced: Too many heartbeats missed

### ISSUE THREAD

**Issue by nikksbagul-ttl** [celery/celery#7820]
I am facing heartbeats missed issue on below config

celery==4.3.0
django-celery==3.3.1
amqp==2.5.2
python: 3.7

celery -A app_name worker -l info --pool=gevent --concurrency=10

Having 5 node cluster of celery in used all are facing same issue Please suggest any think I missed.

`[2022-10-15 02:33:56,331: WARNING/MainProcess] Traceback (most recent call last):
[2022-10-15 02:33:56,331: WARNING/MainProcess] File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
[2022-10-15 02:33:56,331: WARNING/MainProcess] File "/var/www/core_env/lib/python3.7/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
[2022-10-15 02:33:56,331: WARNING/MainProcess] File "/var/www/core_env/lib/python3.7/site-packages/kombu/asynchronous/timer.py", line 130, in _reschedules
    return fun(*args, **kwargs)
[2022-10-15 02:33:56,331: WARNING/MainProcess] File "/var/www/core_env/lib/python3.7/site-packages/kombu/connection.py", line 312, in heartbeat_check
    return self.transport.heartbeat_check(self.connection, rate=rate)
[2022-10-15 02:33:56,331: WARNING/MainProcess] File "/var/www/core_env/lib/python3.7/site-packages/kombu/transport/pyamqp.py", line 149, in heartbeat_check
    return connection.heartbeat_tick(rate=rate)
[2022-10-15 02:33:56,331: WARNING/MainProcess] File "/var/www/core_env/lib/python3.7/site-packages/amqp/connection.py", line 745, in heartbeat_tick
    raise ConnectionForced('Too many heartbeats missed')
[2022-10-15 02:33:56,331: WARNING/MainProcess] amqp.exceptions.ConnectionForced: Too many heartbeats missed
[2022-10-15 02:33:56,331: WARNING/MainProcess] 2022-10-15T02:33:56Z
[2022-10-15 02:33:56,332: WARNING/MainProcess] <_Greenlet at 0x7f08ef326cb0: <TimerEntry: heartbeat_check(*(3.0,), **{})> failed with ConnectionForced`

**Comment by auvipy** [comment]
closed for not following the guideline and using a very old version.
