### ISSUE TITLE
Celery worker connection with Rabittmq met broken pipe error in Gevent pool.

### ISSUE THREAD

**Issue by rmaleki** [celery/celery#7888]
This does not happen with our dev environment, tasks there run on a much smaller DB, so issuing much less DB queries and external requests, I imagine this issue might have something to do with task loads.

```
celery==5.2.7
gevent==22.10.1
amqp==5.1.1
kombu==5.2.4
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 246, in perform_pending_operations
    self._pending_operations.pop()()
  File "/usr/local/lib/python3.8/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
  File "/usr/local/lib/python3.8/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/message.py", line 128, in ack_log_error
    self.ack(multiple=multiple)
  File "/usr/local/lib/python3.8/site-packages/kombu/message.py", line 123, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 1407, in basic_ack
    return self.send_method(
  File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 70, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.8/site-packages/amqp/method_framing.py", line 186, in write_frame
    write(buffer_store.view[:offset])
  File "/usr/local/lib/python3.8/site-packages/amqp/transport.py", line 347, in write
    self._write(s)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe
```

This is my celery command:
`celery -A analytics worker -P gevent -c 500 -l info -E --without-gossip --without-mingle --without-heartbeat &`

and my Django configs:
```
CELERY_IGNORE_RESULT = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 100
CELERY_WORKER_MAX_TASKS_PER_CHILD = 400
CELERYD_TASK_SOFT_TIME_LIMIT = 60 * 60 * 12
CELERYD_TASK_TIME_LIMIT = 60 * 60 * 13
```

**Comment by auvipy** [comment]
I think there are more BrokenPipe errors like open issues

**Comment by rmaleki** [comment]
I did not find anything similar to this issue. just this issue https://github.com/celery/celery/issues/3377.
in this issue, you said 'you should upgrade to celery 5.2.0rc1 for that.' but I used the celery==5.2.7 version and after this, you closed the issue.

**Comment by auvipy** [comment]
this comment said that a kombu fix solved the issue https://github.com/celery/celery/issues/3377#issuecomment-938661446

**Comment by shardool-turing** [comment]
We are also facing the exact same issue. Config is same as @rmaleki

**Comment by ArtyomKozyrev8** [comment]
@rmaleki @auvipy we also face the same issue, I created the following question on [StackOverflow](https://stackoverflow.com/questions/76056447/brokenpipeerror-inside-gevent-library-when-it-is-used-with-celery-how-to-overco)

I see in [3377](https://github.com/celery/celery/issues/3377) the issue was solved in [pull-1231](https://github.com/celery/kombu/pull/1231) I see that the code adds "raise" to reraise BrokenPipeError, but how can I catch and handle the error in my code to create a new connection with RabbitMQ after connections was broken by BrokenPipeError ?

**Comment by GuillaumeCisco** [comment]
Getting same issue.
Should we simply increase ram?

**Comment by shardool-turing** [comment]
We changed the event pool from gevent to prefork (default) and we are not seeing the broken pipe issue. 
We experienced the issue when each task was taking more time (> 1min in our case) causing the issue.
