### ISSUE TITLE
Celery Django: Resource temporarily unavailable: 'celerybeat-schedule'

### ISSUE THREAD

**Issue by Zesshhi** [celery/celery#8037]
Have some problems with setting celery a schedule
Trying to create celerybeat-schedule with command: "celery -A my_app beat -l info"
It has infinity starting msg:
```
LocalTime -> 2023-01-30 14:36:49
Configuration ->
    . broker -> amqp://guest:**@192.168.101.36:5672//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
[2023-01-30 14:36:49,493: INFO/MainProcess] beat: Starting...
```
When im trying to call command: "celery -A my_app beat"

I got an error:
```
[2023-01-30 14:36:37,316: ERROR/MainProcess] Removing corrupted schedule file 'celerybeat-schedule': error(11, 'Resource temporarily unavailable')
Traceback (most recent call last):
  File "/home/knefedov/PycharmProjects/unica_b2b_1/venv/lib/python3.10/site-packages/celery/beat.py", line 533, in setup_schedule
    self._store = self._open_schedule()
  File "/home/knefedov/PycharmProjects/unica_b2b_1/venv/lib/python3.10/site-packages/celery/beat.py", line 523, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
  File "/usr/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.10/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable: 'celerybeat-schedule'

```

celery.py
```
import os
from celery import Celery
from django.conf import settings
from celery.schedules import crontab


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'my_app.settings')

app = Celery('unica_b2b', broker_url='some_ip')


app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

app.conf.beat_schedule = {
    'add-update-every-5-minutes': {
        'task': 'authentication.tasks.create_counter_party',
        'schedule': 300.0,
        'args': (16, 16)
    },
}
app.conf.timezone = 'UTC'

```
I have this file in my project:
[My_project_architecture ][1]

  [1]: https://i.stack.imgur.com/CaUjw.png

**Comment by yasinarabi** [comment]
I had same issue.
And finally found that I called command "celery -A my_app beat" in another terminal and doesn't closed it.

**Comment by auvipy** [comment]
So I an closing it as not a celery bug
