### ISSUE TITLE
Chord raises ChordError for tasks in header even when error handler is defined

### ISSUE THREAD

**Issue by jerkern** [celery/celery#8211]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.2.7 (dawn-chorus) kombu:5.2.4 py:3.10.6
            billiard:3.6.4.0 redis:4.5.4
platform -> system:Linux arch:64bit, ELF
            kernel version:5.19.0-38-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost/

broker_url: 'redis://localhost:6379//'
result_backend: 'redis://localhost/'
deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp @ file:///home/jerkern/.cache/pypoetry/artifacts/36/c1/19/63c22b8414a53a8d16c5c69b0c88a7793e36971687375caade634a1ad1/amqp-5.1.1-py3-none-any.whl
async-timeout @ file:///home/jerkern/.cache/pypoetry/artifacts/5e/15/15/173c5bae6f8d28fa399857d021326b2b05fc2debcbc7bcae7c5bf79891/async_timeout-4.0.2-py3-none-any.whl
billiard @ file:///home/jerkern/.cache/pypoetry/artifacts/87/e9/d2/d245a08624d3420b0b686825e03488047d78810f7e5a5b655494142f3b/billiard-3.6.4.0-py3-none-any.whl
celery @ file:///home/jerkern/.cache/pypoetry/artifacts/4f/e6/90/45fac679034ef8435327a15fd209fed878b0eedf9453c2fd55cef52ece/celery-5.2.7-py3-none-any.whl
click @ file:///home/jerkern/.cache/pypoetry/artifacts/63/f3/4c/2270b95f4d37b9ea73cd401abe68b6e9ede30380533cd4e7118a8e3aa3/click-8.1.3-py3-none-any.whl
click-didyoumean @ file:///home/jerkern/.cache/pypoetry/artifacts/68/39/8a/188f80a4cf867c2fd7e85d6c4167edf6e3c8ba120079a0a0fdd1e18b7f/click_didyoumean-0.3.0-py3-none-any.whl
click-plugins @ file:///home/jerkern/.cache/pypoetry/artifacts/68/3c/22/d1afce20118b67990c0362604c4c6b0dac94208c21e87dedf1145aecae/click_plugins-1.1.1-py2.py3-none-any.whl
click-repl @ file:///home/jerkern/.cache/pypoetry/artifacts/66/5b/b8/75c2c68512c4561089c8110d558eb1f3c4c33ae9d81c0f63ea5c622f74/click_repl-0.2.0-py3-none-any.whl
kombu @ file:///home/jerkern/.cache/pypoetry/artifacts/58/ae/7e/e93c63e3187121f2608d8a92aa59a459cd1590f1d850005138c3ff37be/kombu-5.2.4-py3-none-any.whl
prompt-toolkit @ file:///home/jerkern/.cache/pypoetry/artifacts/1a/96/f5/82495038495549955f328f07a110230c1819eb7ca938ce8da756be07a4/prompt_toolkit-3.0.38-py3-none-any.whl
pytz @ file:///home/jerkern/.cache/pypoetry/artifacts/ef/d7/70/a6e3cca05c00e2f0aa43699df7c28ca8f9b4a568bbe20bcf32a2583e4d/pytz-2023.3-py2.py3-none-any.whl
redis @ file:///home/jerkern/.cache/pypoetry/artifacts/7b/dd/e6/65520570ad31208c19809b41b452a0110086d510f517754b75f678bfcc/redis-4.5.4-py3-none-any.whl
six @ file:///home/jerkern/.cache/pypoetry/artifacts/89/b2/f8/fd92b6d5daa0f8889429b2fc67ec21eedc5cae5d531ee2853828ced6c7/six-1.16.0-py2.py3-none-any.whl
vine @ file:///home/jerkern/.cache/pypoetry/artifacts/e9/b0/9e/482aa7339f33371099d1a175dba4df81b20f814c0aeed882e8776af6be/vine-5.0.0-py2.py3-none-any.whl
wcwidth @ file:///home/jerkern/.cache/pypoetry/artifacts/c7/d4/a4/a3291f0c0a1c2a7c871b4e07c1474f6fa18d19e0ec019ada8bb4451b1a/wcwidth-0.2.6-py2.py3-none-any.whl

```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

There are two files below `canvastest.py`  and `main.py`, I run the example by first starting a local redis instance by running `docker run -p 6379:6379 redis` then I run the worker `celery -A canvastest worker` and the main application `python main.py`

```python
from celery import Celery

app = Celery('canvastest', backend='redis://localhost', broker='redis://localhost')

@app.task(throws=(Exception,),)
def t1(x):
    print("t1")
    return x


@app.task(throws=(Exception,),)
def t2(x):
    print("t2")
    raise Exception()
    return x


@app.task(throws=(Exception,),)
def t3(x):
    print("t3")
    return x

@app.task()
def error_handler(*args, **kwargs):
    print("Error handler")
```

```python
from canvastest import t1, t2, t3, error_handler
from celery import chord

if __name__ == '__main__':

    combined_task = chord((t1.s(1), t2.s(2)),t3.s()).on_error(error_handler.si())

    combined_task()
```

</p>
</details>

# Expected Behavior

The example consist of a chord with two tasks in the header, one in the callback, and with an attached error_handler.

`chord((t1.s(1), t2.s(2)),t3.s()).on_error(error_handler.si())`

When one of the tasks fail I expect that to trigger the error handler, and no further errors should be generated after that. (It's expected behavior that the tasks might fail due to external reasons occasionally, which is handled by the error_handler). 

I expect this behavior regardless of which of the three tasks fail.

# Actual Behavior

- If the callback task in the chord fails the error handler is called, and no other exceptions show up in the log. :heavy_check_mark: 
- If one of the tasks in the body fails, a ChordError exception is raised and corresponding stack traces is present in the worker log.

This is a problem because it's not an actual error in the context of the application, since it's expected to (occasionally) happen and any logging needed would be handled by the error handler method rather than dumping a stack trace into the logs. So having this extra noise in the logs is not desirable.

```log
[2023-04-20 14:01:31,667: WARNING/ForkPoolWorker-16] t1
[2023-04-20 14:01:31,668: WARNING/ForkPoolWorker-1] t2
[2023-04-20 14:01:31,675: ERROR/ForkPoolWorker-1] Chord '3336718d-57e3-41e0-b62d-4fad8ae9cc62' raised: ChordError('Dependency ffdd942e-cfe9-498f-a4b1-9d3a80a9ee45 raised Exception()')
Traceback (most recent call last):
  File "/home/jerkern/celery_mre/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/jerkern/celery_mre/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/jerkern/celery_mre/canvastest.py", line 15, in t2
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jerkern/celery_mre/.venv/lib/python3.10/site-packages/celery/backends/redis.py", line 520, in on_chord_part_return
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/jerkern/celery_mre/.venv/lib/python3.10/site-packages/celery/backends/redis.py", line 520, in <listcomp>
    resl = [unpack(tup, decode) for tup in resl]
  File "/home/jerkern/celery_mre/.venv/lib/python3.10/site-packages/celery/backends/redis.py", line 426, in _unpack_chord_result
    raise ChordError(f'Dependency {tid} raised {retval!r}')
celery.exceptions.ChordError: Dependency ffdd942e-cfe9-498f-a4b1-9d3a80a9ee45 raised Exception()
[2023-04-20 14:01:31,676: WARNING/ForkPoolWorker-1] Error handler
```

**Comment by jerkern** [comment]
I originally created a StackOverflow question about this, but opened this issue instead since I expect this is a bug
https://stackoverflow.com/questions/76063891/python-celery-chord-raises-chorderror-even-when-error-is-handled-by-callback

**Comment by mwodonnell** [comment]
were ever able to figure this out?

**Comment by Nusnus** [comment]
> were ever able to figure this out?

I'll give it a look on the weekend and see what I can do 👍

**Comment by mwodonnell** [comment]
@Nusnus @auvipy 

[Here is a S.O. question](https://stackoverflow.com/questions/76496801/celery-chorderror-propagation-from-deeply-nested-workflows-and-catching-them-in) I made about the topic if that helps give more context.

I also added a simpler Use Case to the comments of [this issue](https://github.com/celery/celery/issues/6220) as it appeared to be related.

**Comment by Nusnus** [comment]
> @Nusnus @auvipy 
> 
> [Here is a S.O. question](https://stackoverflow.com/questions/76496801/celery-chorderror-propagation-from-deeply-nested-workflows-and-catching-them-in) I made about the topic if that helps give more context.
> 
> I also added a simpler Use Case to the comments of [this issue](https://github.com/celery/celery/issues/6220) as it appeared to be related.

Thanks for the additional info!
I'll check it out

**Comment by Nusnus** [comment]
I gave it a quick look, I hope this satisfies the situation @jerkern @mwodonnell 

## Understanding the problem
Let's start by trying to first understand better what were the unmatched expectations.
@jerkern 
> The example consist of a chord with two tasks in the header, one in the callback, and with an attached error_handler.
>
>`chord((t1.s(1), t2.s(2)),t3.s()).on_error(error_handler.si())`
>
>When one of the tasks fail I expect that to trigger the error handler, and no further errors should be generated after that...
>
>I expect this behavior regardless of which of the three tasks fail.

If I understand correctly, the above expects:
1. `error_handler` should be applied on `t1`, `t2`, `t3`
2. `error_handler` should run once.

Additionally, the current behavior creates unwanted artifacts in the log, being two error messages:
1. `Exception` - Raised due to exception in _chord header_ task being `t1` or `t2`.
2. `celery.exceptions.ChordError: Dependency ffdd942e-cfe9-498f-a4b1-9d3a80a9ee45 raised Exception()` - Raised due to invalid chord structure.

## Explanation
When setting an error on a chord, the purpose of the error handler is to catch the errors from the chord's _body_, not the _header_.
From [Linking (callbacks/errbacks)](https://docs.celeryq.dev/en/stable/userguide/calling.html#linking-callbacks-errbacks) we can see chord's have a special treatment:
> In the case of a chord, we can handle errors using multiple handling strategies. See [chord error handling](https://docs.celeryq.dev/en/stable/userguide/canvas.html#chord-errors) for more information.
...
![CleanShot 2023-06-22 at 01 57 24](https://github.com/celery/celery/assets/4662342/f275eb30-645d-4207-b6c2-dbce0cf8fe48)

We can see this block
> Chords may have callback and errback signatures linked to them, which addresses some of the issues with linking signatures to groups. Doing so will link the provided signature to the chord’s body which can be expected to gracefully invoke callbacks just once upon completion of the body, or errbacks just once if any task in the chord header or body fails.

which might be mistakenly misleading, as it mixes the ideas of setting error handlers to the _header_ tasks **before** constructing the chord and then adding another handler, which might confuse as the error handler set from the chord will only be applied to the _body_ and only if the header tasks had errbacks before, they would also be relevant.

This means the expectation
> `error_handler` should be applied on `t1`, `t2`, `t3`

Might make sense but is not consistent with Celery < 5.3's defined behavior.

> Additionally, the current behavior creates unwanted artifacts in the log, being two error messages:
1. `Exception` - Raised due to exception in _chord header_ task being `t1` or `t2`.
2. `celery.exceptions.ChordError: Dependency ffdd942e-cfe9-498f-a4b1-9d3a80a9ee45 raised Exception()` - Raised due to invalid chord structure.

I **assume** the second error causes the first one to be logged but based on the docs above, this is a desired behavior at the moment.

## Proposed Solution
The last part of the given doc above has the following:
> This behavior can be manipulated to allow error handling of the chord header using the task_allow_error_cb_on_chord_header flag. Enabling this flag will cause the chord header to invoke the errback for the body (default behavior) and any task in the chord’s header that fails.

Which refers to this flag: [task_allow_error_cb_on_chord_header](https://docs.celeryq.dev/en/stable/userguide/configuration.html#task-allow-error-cb-on-chord-header)
<img width="739" alt="CleanShot 2023-06-22 at 02 22 01@2x" src="https://github.com/celery/celery/assets/4662342/cb9bc673-2ee3-4fee-877e-ace9ca867739">

This means that generally speaking, upgrading to Celery 5.3.x and enabling the flag should get you _closer_ to the desired solution. That being said, this causes a new issue of having the error handler called **more than once** (once for `t1`, once for `t2`, and lastly for `t3`).
A [discussion was opened about it recently](https://github.com/celery/celery/discussions/8318), so it might be worth checking as chord's error handling might be a bit tricky as we all can see.

**Comment by lucioladen** [comment]
I've been dealing with this behavior a lot as I heavily rely on Celery for a different set of complex workflows, mostly chords. 
My experience is that, the weird thing (if I may) is that the error thrown by the chord isn't the actual exception thrown by the failing header task, but a ChordError instead wrapping it. 
From docs, "The chord callback result will transition to the failure state, and the error is set to the ChordError exception"
This part is not only confusing, but also it often creates the need to capture the error in the client and rethrow the original exception.
