### ISSUE TITLE
python 3.11 support

### ISSUE THREAD

**Issue by cliftondhanee** [celery/celery#8227]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the same feature was already implemented in the
  main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

We have a requirement to run celery tasks in a python 3.11 environment (other dependencies require python 3.11). Could python 3.11 be supported?

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment]
it should work

**Comment by cliftondhanee** [comment]
Ok great I have tested it on python 3.11 and it works. I have submitted a pull request to add python 3.11 in the documentation as a supported version.

**Comment by jzmiller1** [comment]
@cliftondhanee you might encounter some issues running 3.11 see: https://github.com/celery/billiard/issues/377

**Comment by mardiros** [comment]
Celery 4.4.7 does not work with Python 3.11. But, event if it is an LTS version, it's an unsupported version.
since the 1st of August, 2021.

**Comment by auvipy** [comment]
current LTS is 5.3.x version which is upcoming

**Comment by lachaib** [comment]
Hi, Celery 5.3 should be supporting Python 3.11 but I can see that it's not in the metadata of the package, I guess it's only a bug of packaging?

**Comment by Mapiarz** [comment]
@lachaib 
> @Nusnus modified the milestones: 5.3, 5.4 last week

A pity, really.

**Comment by auvipy** [comment]
That should work. I will add that to 5.3.1 release very soon

**Comment by maciejstromich** [comment]
there is 1 issue with python 3.11  (2 issues if you're using sqs extra, both reported to kombu issues) that are blocking upgrade on python3.11 (at least for me it would be awesome is someone could confirm that)

https://github.com/celery/kombu/issues/1744
https://github.com/celery/kombu/issues/1743

**Comment by Mapiarz** [comment]
> added initial support for python 3.11 #8304
>
> let see what works and whats not

Now that's a reassuring git commit 🙌 😂

**Comment by auvipy** [comment]
I will release a point release of kombu and celery 5.3.x by 15th of june

**Comment by igorgue** [comment]
Anyway I can help testing? I tried to install it from git but the dependencies couldn't get fetched in my poetry configuration.

**Comment by Mapiarz** [comment]
I've been rocking Celery 5.2.7 on Python 3.11 for quite some time now (with rabbitmq). I don't have any obvious issues.

**Comment by akmi** [comment]
I am getting the below error on running the this command: celery -A celery_app worker -Q celery-generate-pdf-dev

Error: 
Traceback (most recent call last):
  File "/project-root/venv/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/celery/bin/celery.py", line 236, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/project-root/venv/lib/python3.11/site-packages/click/core.py", line 1404, in parse_args
    parser = self.make_parser(ctx)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/click/core.py", line 1315, in make_parser
    for param in self.get_params(ctx):
                 ^^^^^^^^^^^^^^^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/click/core.py", line 1257, in get_params
    help_option = self.get_help_option(ctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/click/core.py", line 1293, in get_help_option
    help_options = self.get_help_option_names(ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project-root/venv/lib/python3.11/site-packages/click/core.py", line 1287, in get_help_option_names
    all_names.difference_update(param.opts)
                                ^^^^^^^^^^
AttributeError: 'function' object has no attribute 'opts'

Environment:
Python - 3.11
Celery - 5.3.4
Vine -  5.0.0
Kombu - 5.3.2
Amqp - 5.1.1

How to resolve this?

**Comment by auvipy** [comment]
which version of click are you using, please?

**Comment by akmi** [comment]
I didn't add click version explicitly in the requirements.txt. 

However, I was able to solve it. I was using command line functions of celery to add some custom arguments. I removed it as it was not needed anymore and it started working.

However it was working before till celery version 4.4.7 but celery 4.4.7 worked till python 3.7
