### ISSUE TITLE
The last time the revoke interval exceeded the mysql wait_timeout, the revoke task will report the error MySQL server has gone away

### ISSUE THREAD

**Issue by yesemenglong** [celery/celery#8405]
celery==5.2.7
Django==4.0.8
django-celery-beat==2.3.0
django-celery-results==2.4.0

![image](https://github.com/celery/celery/assets/42922106/9bb3004c-0dd5-42f2-a218-57cae55ea38e)

However, tasks that do not perform revoke operations can write to MySQL normally
![1690883545091](https://github.com/celery/celery/assets/42922106/dd170549-7928-4271-916c-8d0cd163500c)

How did your solve this problem?

**Comment by yesemenglong** [comment]
```
[2023-08-01 16:07:20,246: INFO/MainProcess] Task 命令[5bc0f54a-354b-473e-bc99-8423b21bd045] received
[2023-08-01 16:07:20,363: WARNING/ForkPoolWorker-12] 第1次尝试SaltApi调用cmd_run_api请求失败：401 Client Error: Unauthorized for url: https://192.168.123.130:8080/
[2023-08-01 16:07:20,363: WARNING/ForkPoolWorker-12] saltapi
[2023-08-01 16:07:20,363: WARNING/ForkPoolWorker-12]  
[2023-08-01 16:07:20,364: WARNING/ForkPoolWorker-12] 123456
[2023-08-01 16:07:27,052: INFO/MainProcess] Terminating 5bc0f54a-354b-473e-bc99-8423b21bd045 (9)
[2023-08-01 16:11:59,199: INFO/MainProcess] Task 命令[2f571af0-4237-4b7a-8671-8e6fa1ee0fae] received
[2023-08-01 16:11:59,346: WARNING/ForkPoolWorker-13] 第1次尝试SaltApi调用cmd_run_api请求失败：401 Client Error: Unauthorized for url: https://192.168.123.130:8080/
[2023-08-01 16:11:59,347: WARNING/ForkPoolWorker-13] saltapi
[2023-08-01 16:11:59,347: WARNING/ForkPoolWorker-13]  
[2023-08-01 16:11:59,347: WARNING/ForkPoolWorker-13] 123456
[2023-08-01 16:12:06,282: INFO/MainProcess] Terminating 2f571af0-4237-4b7a-8671-8e6fa1ee0fae (9)
[2023-08-01 16:12:06,286: ERROR/MainProcess] pidbox command error: OperationalError(2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/kombu/pidbox.py", line 100, in dispatch
    reply = handle(method, arguments)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/kombu/pidbox.py", line 122, in handle_cast
    return self.handle(method, arguments)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/kombu/pidbox.py", line 116, in handle
    return self.handlers[method](self.state, **arguments)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/celery/worker/control.py", line 159, in revoke
    request.terminate(state.consumer.pool, signal=signum)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/celery/worker/request.py", line 402, in terminate
    self._announce_revoked('terminated', True, signal, False)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/celery/worker/request.py", line 438, in _announce_revoked
    self.task.backend.mark_as_revoked(
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/celery/backends/base.py", line 272, in mark_as_revoked
    self.store_result(task_id, exc, state,
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/celery/backends/base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django_celery_results/backends/database.py", line 132, in _store_result
    self.TaskModel._default_manager.store_result(**task_props)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django_celery_results/managers.py", line 43, in _inner
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django_celery_results/managers.py", line 168, in store_result
    obj, created = self.using(using).get_or_create(task_id=task_id,
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
[2023-08-01 16:12:06,316: ERROR/MainProcess] Pool callback raised exception: OperationalError(2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/billiard/pool.py", line 1774, in _set_terminated
    raise Terminated(-(signum or 0))
billiard.exceptions.Terminated: 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/billiard/pool.py", line 1796, in safe_apply_callback
    fun(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/celery/worker/request.py", line 541, in on_failure
    self._announce_revoked(
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/celery/worker/request.py", line 438, in _announce_revoked
    self.task.backend.mark_as_revoked(
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/celery/backends/base.py", line 272, in mark_as_revoked
    self.store_result(task_id, exc, state,
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/celery/backends/base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django_celery_results/backends/database.py", line 132, in _store_result
    self.TaskModel._default_manager.store_result(**task_props)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django_celery_results/managers.py", line 43, in _inner
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django_celery_results/managers.py", line 168, in store_result
    obj, created = self.using(using).get_or_create(task_id=task_id,
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/root/.pyenv/versions/3.9.16/envs/test_admin/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
[2023-08-01 16:18:52,450: INFO/MainProcess] Task 命令[28e08283-f1a1-44de-8fa7-e161139e4ec9] received
[2023-08-01 16:18:52,560: WARNING/ForkPoolWorker-14] 第1次尝试SaltApi调用cmd_run_api请求失败：401 Client Error: Unauthorized for url: https://192.168.123.130:8080/
[2023-08-01 16:18:52,560: WARNING/ForkPoolWorker-14] saltapi
[2023-08-01 16:18:52,560: WARNING/ForkPoolWorker-14]  
[2023-08-01 16:18:52,560: WARNING/ForkPoolWorker-14] 123456
[2023-08-01 16:19:27,208: INFO/ForkPoolWorker-14] Task 命令[28e08283-f1a1-44de-8fa7-e161139e4ec9] succeeded in 34.75658606365323s: {'game-1': '', 'game-5': ''}
[2023-08-01 16:19:41,132: INFO/MainProcess] Task 命令[75ae876b-f344-4854-a302-bca2ae00f0ef] received
[2023-08-01 16:20:11,717: INFO/ForkPoolWorker-14] Task 命令[75ae876b-f344-4854-a302-bca2ae00f0ef] succeeded in 30.584011064842343s: {'game-5': '', 'game-1': ''}

```

**Comment by auvipy** [comment]
you have to figure out if the mysqlserver gone away is an operational issue or caused by any code issues of celery

**Comment by yesemenglong** [comment]
`class TailfConsumer(WebsocketConsumer):
    def connect(self):
        self.result = tailf.delay(self.channel_name)
        print('connect:', "channel_name: ",self.channel_name, "result.id:", self.result.id)
        self.accept()

    def disconnect(self, close_code):
        self.result.revoke(terminate=True)
        print('disconnect:', self.channel_name)

    def send_message(self, event):
        self.send(text_data=json.dumps({"message": event["message"]}, ensure_ascii=False))
`

`@shared_task(ignore_result=True)
def tailf(channel_name):
    channel_layer = get_channel_layer()
    filename = '/data/dev/backend/logs/batch.log'

    try:
        with open(filename, 'r', encoding='utf-8') as f:
            f.seek(0, 2)
            while True:
                line = f.readline()
                if line:
                    async_to_sync(channel_layer.send)(
                        channel_name, {"type": "send.message", "message": line}
                    )
                else:
                    time.sleep(0.5)
    except Exception as e:
        print(e)
    finally:
        print("-----close_old_connections-----")
        close_old_connections()`

**Comment by yesemenglong** [comment]
> you have to figure out if the mysqlserver gone away is an operational issue or caused by any code issues of celery

The specific code is shown above

**Comment by woshiyanghai** [comment]
Did you solve your problem? I seem to have the same problem as you.
