### ISSUE TITLE
Running tests in Docker fails

### ISSUE THREAD

**Issue by adamckay** [celery/celery#8447]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce
Check out the `main` branch and follow the instructions to build and run the tests in Docker:

`docker-compose build celery` builds the image successfully. 

`docker-compose run --rm celery make test` fails:

```
Traceback (most recent call last):
  File "setup.py", line 136, in <module>
    setuptools.setup(
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/setuptools/command/test.py", line 223, in run
    self.run_tests()
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/setuptools/command/test.py", line 226, in run_tests
    test = unittest.main(
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/setuptools/command/test.py", line 49, in loadTestsFromModule
    for file in resource_listdir(module.__name__, ''):
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1231, in resource_listdir
    return get_provider(package_or_requirement).resource_listdir(resource_name)
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1538, in resource_listdir
    return self._listdir(self._fn(self.module_path, resource_name))
  File "/home/developer/.pyenv/versions/3.8.17/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1585, in _listdir
    raise NotImplementedError(
NotImplementedError: Can't perform this operation for unregistered loader type
```

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

**Comment by Nusnus** [comment]
@adamckay Hey there - we've just merged to `main` this PR #8531 which should relate to this issue.
The integration tests are not fully supported over docker but at least I fixed the basics.


Do you mind giving it a try?
1. Use latest `main` with cwd celery repo root dir.
2. run `make docker-build`
3. run `make docker-unit-tests`
4. Not fully but `make docker-integration-tests` should partially work.

Lastly, `make docker-bash` should give you a bash prompt into the container where you can run commands by yourself.

**Comment by Nusnus** [comment]
`make docker-build`
```bash
[+] Building 381.2s (42/42) FINISHED                                                                                                                              docker:desktop-linux
 => [docs internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 935B                                                                                                                                              0.0s
 => [docs internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 348B                                                                                                                                                 0.0s
 => [docs internal] load metadata for docker.io/library/python:3.9-slim-bullseye                                                                                                  2.5s
 => [celery internal] load .dockerignore                                                                                                                                          0.0s
 => => transferring context: 348B                                                                                                                                                 0.0s
 => [celery internal] load build definition from Dockerfile                                                                                                                       0.0s
 => => transferring dockerfile: 4.30kB                                                                                                                                            0.0s
 => [celery internal] load metadata for docker.io/library/debian:bookworm-slim                                                                                                    2.1s
 => [celery auth] library/debian:pull token for registry-1.docker.io                                                                                                              0.0s
 => [docs auth] library/python:pull token for registry-1.docker.io                                                                                                                0.0s
 => [celery  1/22] FROM docker.io/library/debian:bookworm-slim@sha256:24c92a69df28b21676d721fe18c0bf64138bfc69b486746ad935b49cc31b0b91                                            0.0s
 => [celery internal] load build context                                                                                                                                          0.2s
 => => transferring context: 16.03MB                                                                                                                                              0.2s
 => CACHED [celery  2/22] RUN apt-get update && apt-get install -y build-essential     libcurl4-openssl-dev     libffi-dev     tk-dev     xz-utils     curl     lsb-release       0.0s
 => CACHED [celery  3/22] RUN : "developer"                                                                                                                                       0.0s
 => CACHED [celery  4/22] WORKDIR /provisioning                                                                                                                                   0.0s
 => CACHED [celery  5/22] RUN useradd -m -s /bin/bash developer                                                                                                                   0.0s
 => CACHED [celery  6/22] RUN curl https://pyenv.run | bash                                                                                                                       0.0s
 => CACHED [celery  7/22] RUN pyenv install 3.8                                                                                                                                   0.0s
 => CACHED [celery  8/22] RUN pyenv install 3.9                                                                                                                                   0.0s
 => CACHED [celery  9/22] RUN pyenv install 3.10                                                                                                                                  0.0s
 => CACHED [celery 10/22] RUN pyenv install 3.11                                                                                                                                  0.0s
 => CACHED [celery 11/22] RUN pyenv global 3.8 3.9 3.10 3.11                                                                                                                      0.0s
 => CACHED [celery 12/22] WORKDIR /home/developer                                                                                                                                 0.0s
 => CACHED [celery 13/22] COPY --chown=1000:1000 requirements /home/developer/requirements                                                                                        0.0s
 => CACHED [celery 14/22] COPY --chown=1000:1000 docker/entrypoint /entrypoint                                                                                                    0.0s
 => CACHED [celery 15/22] RUN chmod gu+x /entrypoint                                                                                                                              0.0s
 => CACHED [celery 16/22] RUN pyenv local 3.11 3.10 3.9 3.8                                                                                                                       0.0s
 => CACHED [celery 17/22] RUN pyenv exec python3.8 -m pip install --upgrade pip setuptools wheel &&     pyenv exec python3.9 -m pip install --upgrade pip setuptools wheel &&     0.0s
 => [celery 18/22] COPY --chown=1000:1000 . /home/developer/celery                                                                                                                0.3s
 => [docs 1/8] FROM docker.io/library/python:3.9-slim-bullseye@sha256:5b66e8d3acc99cb3965636c25501c1483f8f97ece762bd623973ce88ba8406f7                                            0.0s
 => => resolve docker.io/library/python:3.9-slim-bullseye@sha256:5b66e8d3acc99cb3965636c25501c1483f8f97ece762bd623973ce88ba8406f7                                                 0.0s
 => [docs internal] load build context                                                                                                                                            0.0s
 => => transferring context: 2.46kB                                                                                                                                               0.0s
 => CACHED [docs 2/8] RUN apt-get update     && apt-get install -y build-essential     && apt-get install -y texlive     && apt-get install -y texlive-latex-extra     && apt-ge  0.0s
 => CACHED [docs 3/8] COPY /requirements /requirements                                                                                                                            0.0s
 => CACHED [docs 4/8] RUN pip install -r /requirements/docs.txt -r /requirements/default.txt                                                                                      0.0s
 => CACHED [docs 5/8] COPY docker/docs/start /start-docs                                                                                                                          0.0s
 => CACHED [docs 6/8] RUN sed -i 's/\r$//g' /start-docs                                                                                                                           0.0s
 => CACHED [docs 7/8] RUN chmod +x /start-docs                                                                                                                                    0.0s
 => CACHED [docs 8/8] WORKDIR /docs                                                                                                                                               0.0s
 => [docs] exporting to image                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                           0.0s
 => => writing image sha256:d4ce5c0d3607d2ff9e345d7a8bf80e0dfb1adba77e81fa5ae8f5387d54a5d09e                                                                                      0.0s
 => => naming to docker.io/celery/docs                                                                                                                                            0.0s
 => [celery 19/22] RUN pyenv exec python3.8 -m pip install -e /home/developer/celery &&     pyenv exec python3.9 -m pip install -e /home/developer/celery &&     pyenv exec pyt  21.9s
 => [celery 20/22] RUN pyenv exec python3.8 -m pip install   -r requirements/default.txt   -r requirements/dev.txt   -r requirements/docs.txt   -r requirements/pkgutils.txt    351.2s
 => [celery 21/22] WORKDIR /home/developer/celery                                                                                                                                 0.0s
 => [celery 22/22] RUN git config --global --add safe.directory /home/developer/celery                                                                                            0.1s
 => [celery] exporting to image                                                                                                                                                   5.3s
 => => exporting layers                                                                                                                                                           5.3s
 => => writing image sha256:bcd7f9936995fdc2be95918ed3f932f1ddf507b7765d91cac0162ba23091e6fa                                                                                      0.0s
 => => naming to docker.io/celery/celery:dev                                                                                                                                      0.0s
```

**Comment by Nusnus** [comment]
`make docker-unit-tests`
```bash
t/unit/worker/test_worker.py::test_WorkController::test_Hub_create PASSED
t/unit/worker/test_worker.py::test_WorkController::test_Pool_create_threaded PASSED
t/unit/worker/test_worker.py::test_WorkController::test_Pool_pool_no_sem PASSED
t/unit/worker/test_worker.py::test_WorkController::test_Pool_create PASSED
...
============================================= 3217 passed, 10 skipped, 3 xfailed, 55 warnings, 28901 subtests passed in 140.21s (0:02:20) =============================================
.pkg: _exit> python /home/developer/celery/.tox/.tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  3.11-unit: OK (150.04=setup[3.28]+cmd[146.77] seconds)
  congratulations :) (152.62 seconds)
```

**Comment by Nusnus** [comment]
`make docker-bash`
Then `tox -e lint`
```bash
[+] Creating 4/0
 ✔ Container docker-redis-1     Running                                                                                                                                           0.0s
 ✔ Container docker-dynamodb-1  Running                                                                                                                                           0.0s
 ✔ Container docker-rabbit-1    Running                                                                                                                                           0.0s
 ✔ Container docker-azurite-1   Running                                                                                                                                           0.0s
developer@108b5b1ec627:~/celery$ tox -e lint
ROOT: will run in automatically provisioned tox, host /home/developer/.pyenv/versions/3.11.5/bin/python3.11 is missing [requires (has)]: tox-gh-actions
ROOT: provision> .tox/.tox/bin/python -m tox -e lint
ROOT: tox-gh-actions won't override envlist because tox is not running in GitHub Actions
lint: recreate env because python changed executable='/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/bin/python3.11'->'/home/developer/.pyenv/versions/3.11.5/bin/python3.11'
lint: remove tox env folder /home/developer/celery/.tox/lint
lint: install_deps> python -I -m pip install pre-commit -r /home/developer/celery/requirements/test.txt -r /home/developer/celery/requirements/pkgutils.txt
.pkg: _optional_hooks> python /home/developer/celery/.tox/.tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_editable> python /home/developer/celery/.tox/.tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_editable> python /home/developer/celery/.tox/.tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
lint: install_package_deps> python -I -m pip install 'backports.zoneinfo>=0.2.1; python_version < "3.9"' 'billiard<5.0,>=4.1.0' 'click-didyoumean>=0.3.0' 'click-plugins>=1.1.1' 'click-repl>=0.2.0' 'click<9.0,>=8.1.2' 'importlib-metadata>=3.6; python_version < "3.8"' 'kombu<6.0,>=5.3.2' 'python-dateutil>=2.8.2' 'tzdata>=2022.7' 'vine<6.0,>=5.0.0'
lint: install_package> python -I -m pip install --force-reinstall --no-deps /home/developer/celery/.tox/.tmp/package/20/celery-5.3.4-0.editable-py3-none-any.whl
lint: commands[0]> pre-commit run --all-files --show-diff-on-failure
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/asottile/yesqa.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pycqa/isort.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/yesqa.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
pyupgrade................................................................Passed
flake8...................................................................Passed
Strip unnecessary `# noqa`s..............................................Passed
check for merge conflicts................................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
mixed line ending........................................................Passed
isort....................................................................Passed
mypy.....................................................................Passed
.pkg: _exit> python /home/developer/celery/.tox/.tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  lint: OK (77.39=setup[45.59]+cmd[31.80] seconds)
  congratulations :) (79.44 seconds)
developer@108b5b1ec627:~/celery$
```

**Comment by auvipy** [comment]
I think we can close this for now?
