### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by GustWind-byte** [celery/celery#8672]
celery start up appear command keys must be in same slot
redis uses a cluster，What should I do?

[2023-11-22 10:54:21,301: CRITICAL/MainProcess] Unrecoverable error: ResponseError("'BRPOP' command keys must in same slot")
Traceback (most recent call last):
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/worker/consumer/mingle.py", line 37, in start
    self.sync(c)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
    replies = self.send_hello(c)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/app/control.py", line 389, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/kombu/pidbox.py", line 346, in _broadcast
    return self._collect(reply_ticket, limit=limit,
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/kombu/pidbox.py", line 388, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/kombu/transport/redis.py", line 590, in get
    ret = self.handle_event(fileno, event)
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/kombu/transport/redis.py", line 572, in handle_event
    return self.on_readable(fileno), self
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/kombu/transport/redis.py", line 568, in on_readable
    chan.handlers[type]()
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/kombu/transport/redis.py", line 961, in _brpop_read
    dest__item = self.client.parse_response(self.client.connection,
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/redis/client.py", line 525, in parse_response
    response = connection.read_response()
  File "/root/.virtualenvs/barrage/lib/python3.8/site-packages/redis/connection.py", line 516, in read_response
    raise response
redis.exceptions.ResponseError: 'BRPOP' command keys must in same slot

**Comment by TracyRAN1** [comment]
me too, how to fix it?

**Comment by ZLotusRain** [comment]
set priority_steps to [0] in transport_options or create a series of keys related to the priority in redis cluster when using redis will sovle the problem, because kombu will try to pop item from a series of keys constructed by the priority, if some key here can't be hashed to the same slot, the error will occur.

**Comment by doorOfChoice** [comment]
https://github.com/celery/celery/issues/8276#issuecomment-1698602062

**Comment by thedrow** [comment]
There's not enough information to reproduce this issue.
Please re-file the issue using our template.
