### ISSUE TITLE
celery's control().inspect() breaks multiprocessing.Process (doesn't run target function) (Redis)

### ISSUE THREAD

**Issue by CharlesB2** [celery/celery#8874]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: `5.3.6 (emerald-rush)`

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.3.6 (emerald-rush) kombu:5.3.5 py:3.10.13
            billiard:4.2.0 redis:5.0.1
platform -> system:Linux arch:64bit
            kernel version:6.5.13-orbstack-00122-g57b8027e2387 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis:6379/1

deprecated_settings: None
broker_url: 'redis://redis:6379/0'
imports:
    ('celerytest.tasks',)
result_backend: 'redis://redis:6379/1'
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: 3.10
- **Minimal Celery Version**: 5.3.6
- **Minimal Kombu Version**: 5.3.5
- **Minimal Broker Version**: Redis 7
- **Minimal Result Backend Version**: N/A
- **Minimal OS and/or Kernel Version**: Alpine docker image python:3.10-alpine
- **Minimal Broker Client Version**: Redis 5.0.1
- **Minimal Result Backend Client Version**: N/A

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
async-timeout==4.0.3
billiard==4.2.0
celery==5.3.6
certifi==2024.2.2
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
distlib==0.3.8
filelock==3.13.1
kombu==5.3.5
pipenv==2023.12.1
platformdirs==4.2.0
prompt-toolkit==3.0.43
python-dateutil==2.8.2
redis==5.0.1
six==1.16.0
tzdata==2024.1
vine==5.1.0
virtualenv==20.25.1
wcwidth==0.2.13
```

</p>
</details>

### Other Dependencies

<details>
<p>
See repository https://github.com/CharlesB2/celery_broken_multiprocessing_repro
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
[Complete code with docker-compose](https://github.com/CharlesB2/celery_broken_multiprocessing_repro) 
</p>
</details>

# Expected Behavior

multiprocessing.Process should be launched correctly

# Actual Behavior

Given a task that uses `multiprocessing.Process`, the Process fails to start if it's run after having called celery's `app.control().inspect()`. 
Looking at debug output we can see that the Process and Pipe are alive, but the target function specified at Process creation isn't run.
This happens only with Redis broker, not RabbitMQ.

Tested also with billiard implementation, same result.

```
❯ docker compose exec celery python /app/celery_broken_multiprocessing_repro.py
calling function
child: conn.closed=False, conn.fileno()=4, conn.readable=True, conn.writable=True
child_conn.closed=False, child_conn.fileno()=4, child_conn.readable=True, child_conn.writable=True
Result: 42
calling function as task
child: conn.closed=False, conn.fileno()=4, conn.readable=True, conn.writable=True
child_conn.closed=False, child_conn.fileno()=4, child_conn.readable=True, child_conn.writable=True
Result: 42
getting active tasks
calling function
child: conn.closed=False, conn.fileno()=11, conn.readable=True, conn.writable=True
child_conn.closed=False, child_conn.fileno()=11, child_conn.readable=True, child_conn.writable=True
Result: 42
calling function as task
child_conn.closed=False, child_conn.fileno()=11, child_conn.readable=True, child_conn.writable=True
process killed
Traceback (most recent call last):
  File "/app/celery_broken_multiprocessing_repro.py", line 45, in <module>
    subprocess_fun_task()
  File "/usr/local/lib/python3.10/site-packages/celery/local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 411, in __call__
    return self.run(*args, **kwargs)
  File "/app/celery_broken_multiprocessing_repro.py", line 32, in subprocess_fun_task
    subprocess_fun()
  File "/app/celery_broken_multiprocessing_repro.py", line 25, in subprocess_fun
    print(f"Result: {parent_conn.recv()}")
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by thuibr** [comment]
Please try setting
```python
app.conf.broker_transport_options = {'socket_timeout': 5}
```

**Comment by davseitsev** [comment]
We got into the same issue after major upgrade `celery: 5.2.7 > 5.5.2`, `kombu: 5.3.1 > 5.5.3`, `Python: 3.9 > 3.12`. Our current env:
`Python 3.12.10`

Dependencies:
```
celery==5.5.2
kombu==5.5.3
redis==6.1.0
```

We run celery like this
`
celery -A tasks.all_tasks worker --pool=prefork -l debug -Ofair -n celery@%h -c 2 -E
`

If we call `celery.control.inspect().active()` it breaks **prefork** workers:
```python
@celeryd_init.connect
def configure_workers(sender=None, conf=None, **kwargs):
    ...
    i = celery.control.inspect()
    active_tasks = i.active() or {}
   ...
```
They hang and are killed by timeout:
```
[2025-05-20 09:54:47,656: ERROR/MainProcess] Timed out waiting for UP message from <ForkProcess(ForkPoolWorker-12, started daemon)>
[2025-05-20 09:54:47,661: ERROR/MainProcess] Process 'ForkPoolWorker-12' pid:21 exited with 'signal 9 (SIGKILL)'
```

Hanging worker stacktrace looks like this:
```
Process 30: /usr/local/bin/python3.12 /usr/local/bin/celery -A tasks.all_tasks worker -E --without-heartbeat --without-gossip --without-mingle -P prefork -c 1 -l debug -Ofair -n celery@%h
Python v3.12.10 (/mnt/lima-rosetta/rosetta)

Thread 30 (idle): "MainThread"
    _read_from_socket (redis/_parsers/socket.py:65)
    readline (redis/_parsers/socket.py:115)
    _read_response (redis/_parsers/resp2.py:25)
    read_response (redis/_parsers/resp2.py:15)
    read_response (redis/connection.py:644)
    parse_response (redis/client.py:652)
    _brpop_read (kombu/transport/redis.py:967)
    close (kombu/transport/redis.py:1092)
    maybe_close_channel (kombu/connection.py:346)
    _do_close_self (kombu/connection.py:354)
    collect (kombu/connection.py:384)
    collect_resource (kombu/connection.py:1082)
    force_close_all (kombu/resource.py:181)
    _after_fork_cleanup_resource (kombu/resource.py:21)
    _run_after_forkers (multiprocessing/util.py:170)
    _bootstrap (billiard/process.py:316)
    _launch (billiard/popen_fork.py:77)
    __init__ (billiard/popen_fork.py:22)
    _Popen (billiard/context.py:331)
    start (billiard/process.py:120)
    _create_worker_process (billiard/pool.py:1158)
    _create_worker_process (celery/concurrency/asynpool.py:491)
    _repopulate_pool (billiard/pool.py:1328)
    _maintain_pool (billiard/pool.py:1343)
    maintain_pool (billiard/pool.py:1351)
    _event_process_exit (celery/concurrency/asynpool.py:496)
    create_loop (kombu/asynchronous/hub.py:373)
    asynloop (celery/worker/loops.py:97)
    start (celery/worker/consumer/consumer.py:772)
    start (celery/bootsteps.py:116)
    start (celery/worker/consumer/consumer.py:341)
    start (celery/bootsteps.py:365)
    start (celery/bootsteps.py:116)
    start (celery/worker/worker.py:203)
    worker (celery/bin/worker.py:356)
    caller (celery/bin/base.py:135)
    new_func (click/decorators.py:34)
    invoke (click/core.py:794)
    invoke (click/core.py:1226)
    invoke (click/core.py:1830)
    main (click/core.py:1363)
    __call__ (click/core.py:1442)
    main (celery/bin/celery.py:231)
    main (celery/__main__.py:15)
    <module> (celery:8)
```
So when celery tries to restart a worker it calls `multiprocessing.util.calls _run_after_forkers()` to cleanup resources and gets stuck on reading socket from Redis. It may indirectly be related to the change of `kombu.transport.redis.close()` method. We get stuck on `self._brpop_read()` here https://github.com/celery/kombu/blob/353ba16b113560e78951768073dcb216a5802e8b/kombu/transport/redis.py#L1095-L1101
Method close() was significantly changed in kombu 5.3.2.
I don't understand how it's related yet but when I comment this block of code, the issue is not reproduced: https://github.com/celery/kombu/blob/353ba16b113560e78951768073dcb216a5802e8b/kombu/pidbox.py#L386-L390

If I don't call `celery.control.inspect().active()`, method `kombu.transport.redis.close()` returns immediately as `self._in_poll` is False.

When I set `app.conf.broker_transport_options = {'socket_timeout': 5}` method `kombu.transport.redis.close()` doesn't hang forever but it waits 5s and then proceeds. I'm still not sure it's right solution as we wait 5s before restarting a worker.

Let me know if I can provide more information. It's easily reproduced locally.

**Comment by davseitsev** [comment]
I'm not sure what I should try. We are using latest celery and billiard versions (billiard==4.2.1, celery==5.5.2). AFAIK there is no way to replace billiard with multiprocessing in celery. Could you please be more specific?

**Comment by auvipy** [comment]
I was confused by seeing this File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
