### ISSUE TITLE
AbortableTask raises `KeyError: 'name'` when get status after aborted with result extend enabled

### ISSUE THREAD

**Issue by waketzheng** [celery/celery#8877]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [x] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.3.6

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.3.6 (emerald-rush) kombu:5.3.5 py:3.10.13
            billiard:4.2.0 py-amqp:5.2.0
platform -> system:Darwin arch:64bit
            kernel version:20.6.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:mongodb://localhost:27017/celery_results

broker_url: 'amqp://myuser:********@localhost:5672/myvhost'
result_backend: 'mongodb://localhost:27017/celery_results'
deprecated_settings: None
result_extended: True
broker_connection_retry_on_startup: False
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: 5.4
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: RabbitMQ 3.12.13
- **Minimal Result Backend Version**: MongoDB 7.0.5
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
celery==5.3.6
pymongo==4.6.2
```

</p>
</details>

### Other Dependencies

<details>
<p>
<li>MongoDB</li>
```
docker pull mongo:latest
docker run -d -p 27017:27017 --name mongo_latest mongo:latest
```
<li>RabbitMQ</li>
https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/rabbitmq.html#setting-up-rabbitmq
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
<li>tasks.py</li>
```python
import os
import time

from celery import Celery
from celery.contrib.abortable import AbortableTask

DB_URL = "mongodb://localhost:27017/celery_results"
MQ_URL = f"amqp://myuser:mypassword@localhost:5672/myvhost"
app = Celery("tasks", broker=MQ_URL, backend=DB_URL)
app.conf.result_extended = True


@app.task(bind=True, base=AbortableTask)
def test(self) -> int:
    for _ in range(5):
        if self.is_aborted():
            time.sleep(3)
            return 0
        time.sleep(1)
    return 1
```
<li>main.py</li>
```python
from tasks import test

r = test.delay()
r.abort()
print(r.status)
```
<li>run</li>
```bash
celery -A tasks worker
python main.py
```
</p>
</details>

# Expected Behavior

Output: `ABORTED`
# Actual Behavior

Got:
```
Traceback (most recent call last):
  File "/Users/mac10.12/trying/directly/main.py", line 5, in <module>
    print(r.status)
  File "/Users/mac10.12/trying/directly/venv/lib/python3.10/site-packages/celery/result.py", line 503, in state
    return self._get_task_meta()['status']
  File "/Users/mac10.12/trying/directly/venv/lib/python3.10/site-packages/celery/result.py", line 442, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/Users/mac10.12/trying/directly/venv/lib/python3.10/site-packages/celery/backends/base.py", line 608, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/Users/mac10.12/trying/directly/venv/lib/python3.10/site-packages/celery/backends/mongodb.py", line 203, in _get_task_meta_for
    'name': obj['name'],
KeyError: 'name'
```
> Note: celery 5.2 does not raise this error

**Comment by lianyueh** [comment]
I met a similar issue like this one.
because you enable `app.conf.result_extended = True`
then you could see 
`/lib/python3.10/site-packages/celery/backends/mongodb.py`
```
    def _get_task_meta_for(self, task_id):
        """Get task meta-data for a task by id."""
        obj = self.collection.find_one({'_id': task_id})
        if obj:
            if self.app.conf.find_value_for_key('extended', 'result'):     # !!! Here it enables 'extended'
                return self.meta_from_decoded({
                    'name': obj['name'],                                               #  !!! Here is where raises error
                    'args': obj['args'],
                    'task_id': obj['_id'],
                    'queue': obj['queue'],
                    'kwargs': obj['kwargs'],
                    'status': obj['status'],
                    'worker': obj['worker'],
                    'retries': obj['retries'],
                    'children': obj['children'],
                    'date_done': obj['date_done'],
                    'traceback': obj['traceback'],
                    'result': self.decode(obj['result']),
                })

  #   if you check your mongoDB, it just stores data in this way
            return self.meta_from_decoded({     
                'task_id': obj['_id'],
                'status': obj['status'],
                'result': self.decode(obj['result']),
                'date_done': obj['date_done'],
                'traceback': obj['traceback'],
                'children': obj['children'],
            })
        return {'status': states.PENDING, 'result': None}
```
So in your database, it has no `name`, though even both of them have `status`
