### ISSUE TITLE
AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for' in docker container.

### ISSUE THREAD

**Issue by shehroz010** [celery/celery#9088]
# Checklist

- [X] I have verified that the issue exists against the `main` branch of Celery.
- [X] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [X] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [X] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [X] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [X] I have verified that the issue exists against the `main` branch of Celery.
- [X] I have included the contents of ``pip freeze`` in the issue.
- [X] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [X] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [X] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

software -> celery:5.4.0 (opalescent) kombu:5.3.7 py:3.10.14
            billiard:4.2.0 py-amqp:5.2.0
platform -> system:Linux arch:64bit
            kernel version:5.15.146.1-microsoft-standard-WSL2 imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None

</p>
</details>

# Steps to Reproduce
I am using the docker-compose where broker is redis.
file name = flask_app.py
code is mentioned below:
```from flask import Flask, jsonify, request
from celery import Celery
from celery.result import AsyncResult

app = Flask(__name__)
app.config['CELERY_BROKER_URL'] = 'redis://redis:6379/0'
app.config['CELERY_RESULT_BACKEND'] = 'redis://redis:6379/0'

celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'], backend=app.config['CELERY_RESULT_BACKEND'])
celery.conf.update(
    result_backend=app.config['CELERY_RESULT_BACKEND']
)

import redis

r = redis.Redis(host='redis', port=6379, db=0)
try:
    r.ping()
    print("Redis connection successful")
except redis.ConnectionError:
    print("Redis connection failed")

@celery.task(bind=True, name='crontest.flask_app.long_running_task')
def long_running_task(self):
    import time
    for i in range(10):
        time.sleep(10)
        print("running")
        self.update_state(state='PROGRESS', meta={'current': i, 'total': 10})
    return {'current': i+1, 'total': 10, 'status': 'Task completed!!!'}

@app.route('/start_task', methods=['POST'])
def start_task():
    task = long_running_task.delay()
    return jsonify({"task_id": task.id}), 202

@app.route('/status/<task_id>', methods=['GET'])
def task_status(task_id):
    task = AsyncResult(task_id)
    if task.state == 'PENDING':
        response = {
            'state': task.state,
            'current': 0,
            'total': 100,
            'status': 'Pending...'
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'current': task.info.get('current', 0),
            'total': task.info.get('total', 100),
            'status': task.info.get('status', '')
        }
        if 'result' in task.info:
            response['result'] = task.info['result']
    else:
        response = {
            'state': task.state,
            'current': 100,
            'total': 100,
            'status': str(task.info),
        }
    return jsonify(response)

@app.route('/', methods=['GET'])
def index():
    return jsonify({'status': 'ok'})

if __name__ == '__main__':
    app.run(debug=True)
```
all this code is running inside a docker container using docker-compose, broker is redis. Below is the docker-compose file content:
```version: '3.9'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/crontest
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - worker

  worker:
    build: .
    command: celery -A flask_app.celery worker --loglevel=info
    volumes:
      - .:/crontest
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
``` 

## Required Dependencies

- **Minimal Python Version**: 3.10.14
- **Minimal Celery Version**: 5.4.0
- **Minimal Kombu Version**: 5.3.7
- **Minimal Broker Version**: redis==5.0.6
- **Minimal Result Backend Version**: redis==5.0.6
- **Minimal OS and/or Kernel Version**: system:Linux arch:64bit
            kernel version:5.15.146.1-microsoft-standard-WSL2
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

amqp==5.2.0
annotated-types==0.7.0
anyio==4.4.0
async-timeout==4.0.3
billiard==4.2.0
blinker==1.8.2
boto3==1.34.5
botocore==1.34.131
celery==5.4.0
certifi==2024.6.2
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.1
click-plugins==1.1.1
click-repl==0.3.0
distro==1.9.0
dnspython==2.6.1
exceptiongroup==1.2.1
Flask==3.0.3
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
itsdangerous==2.2.0
Jinja2==3.1.4
jmespath==1.0.1
kombu==5.3.7
MarkupSafe==2.1.5
numpy==2.0.0
openai==1.34.0
pandas==2.2.2
pinecone==4.0.0
prompt_toolkit==3.0.47
pydantic==2.7.4
pydantic_core==2.18.4
pymongo==4.7.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.1
redis==5.0.6
regex==2024.5.15
requests==2.32.3
s3transfer==0.9.0
six==1.16.0
sniffio==1.3.1
tiktoken==0.6.0
tqdm==4.66.4
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
vine==5.1.0
wcwidth==0.2.13
Werkzeug==3.0.3

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```
```

</p>
</details>

# Expected Behavior

When I hit the "/status/<task_id>" endpoint, it should it should return the state of task whether pending, failure or success as per the code.

# Actual Behavior

Instead m getting this error. In the code above I tried to explicitly set the result backend in the Celery configuration:
`celery.conf.update(
    result_backend=app.config['CELERY_RESULT_BACKEND']
)`
but same error is persisting.

 Error:
```[2024-06-21 11:04:51,605] ERROR in app: Exception on /status/fdb22f08-bac1-49c0-a957-e0e351ca5a03 [GET]
web-1     | Traceback (most recent call last):
web-1     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
web-1     |     response = self.full_dispatch_request()
web-1     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
web-1     |     rv = self.handle_user_exception(e)
web-1     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
web-1     |     rv = self.dispatch_request()                                                                                      
web-1     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request                          
web-1     |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]           
web-1     |   File "/crontest/flask_app.py", line 115, in task_status
web-1     |     if task.state == 'PENDING':                                                                                       
web-1     |   File "/usr/local/lib/python3.10/site-packages/celery/result.py", line 503, in state                                 
web-1     |     return self._get_task_meta()['status']
web-1     |   File "/usr/local/lib/python3.10/site-packages/celery/result.py", line 442, in _get_task_meta                        
web-1     |     return self._maybe_set_cache(self.backend.get_task_meta(self.id))                                                 
web-1     |   File "/usr/local/lib/python3.10/site-packages/celery/backends/base.py", line 608, in get_task_meta                  
web-1     |     meta = self._get_task_meta_for(task_id)
web-1     | AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for' 
```

**Comment by shehroz010** [comment]
Got the issue fixed by adding `celery.AsyncResult(id)` instead of 
```@app.route('/status/<task_id>', methods=['GET'])
def task_status(task_id):
    task = AsyncResult(task_id)
    if task.state == 'PENDING':
        response = {
            'state': task.state,
            'current': 0,
            'total': 100,
            'status': 'Pending...'
        }
```
