### ISSUE TITLE
TypeError: _unpack_version() takes from 1 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by couzhei** [celery/celery#9161]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [ ] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `main` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: Python 3.10.14
- **Minimal Celery Version**: 5.4.0 (opalescent)
- **Minimal Kombu Version**: 5.3.7
- **Minimal Broker Version**: rabbitmq:4.0-rc
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output: <code>amqp                          5.2.0
asgiref                       3.8.1
billiard                      4.2.0
celery                        5.4.0
click                         8.1.7
click-didyoumean              0.3.1
click-plugins                 1.1.1
click-repl                    0.3.0
Django                        5.0.6
django-cors-headers           4.3.1
django-enumchoicefield        3.0.1
django-environ                0.11.2
djangorestframework           3.15.1
djangorestframework-simplejwt 5.3.1
exceptiongroup                1.2.2
iniconfig                     2.0.0
kombu                         5.3.7
logging                       0.4.9.6
olefile                       0.47
packaging                     24.1
pika                          0.13.0
pillow                        10.3.0
pip                           24.1.2
pluggy                        1.5.0
prompt_toolkit                3.0.47
psycopg2                      2.9.9
PyAMQP                        0.1.0.7
PyJWT                         2.8.0
pytest                        8.3.2
python-dateutil               2.9.0.post0
setuptools                    65.5.0
six                           1.16.0
sqlparse                      0.5.0
tomli                         2.0.1
typing_extensions             4.12.2
tzdata                        2024.1
vine                          5.1.0
wcwidth                       0.2.13</code></b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

I am just going through the tutorial on [this](https://docs.celeryq.dev/en/stable/getting-started/first-steps-with-celery.html#first-steps), where I have gone through the RabbitMQ option (which I got its image from dockerhub).
After I reached this [part](https://docs.celeryq.dev/en/stable/getting-started/first-steps-with-celery.html#running-the-celery-worker-server) where I ran `celery -A tasks worker --loglevel=INFO`
I got the following error:
# Actual Behavior

```bash
 -------------- celery@lappy v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-6.5.0-45-generic-x86_64-with-glibc2.35 2024-07-30 09:34:54
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x73f8888ed690
- ** ---------- .> transport:   amqp://ashkan:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . tasks.add

[2024-07-30 09:34:54,231: WARNING/MainProcess] /home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-30 09:34:54,254: INFO/MainProcess] Connected to amqp://ashkan:**@127.0.0.1:5672//
[2024-07-30 09:34:54,254: WARNING/MainProcess] /home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-07-30 09:34:54,265: INFO/MainProcess] mingle: searching for neighbors
[2024-07-30 09:34:55,318: INFO/MainProcess] mingle: all alone
[2024-07-30 09:34:55,330: CRITICAL/MainProcess] Unrecoverable error: TypeError('_unpack_version() takes from 1 to 5 positional arguments but 6 were given')
Traceback (most recent call last):
  File "/home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/celery/worker/consumer/tasks.py", line 31, in start
    qos_global = not c.connection.qos_semantics_matches_spec
  File "/home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/kombu/connection.py", line 889, in qos_semantics_matches_spec
    return self.transport.qos_semantics_matches_spec(self.connection)
  File "/home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/kombu/transport/pyamqp.py", line 227, in qos_semantics_matches_spec
    return version_string_as_tuple(props['version']) < (3, 3)
  File "/home/couzhei/code/Map-of-defect/backend/venv/lib/python3.10/site-packages/kombu/utils/text.py", line 47, in version_string_as_tuple
    v = _unpack_version(*s.split('.'))
TypeError: _unpack_version() takes from 1 to 5 positional arguments but 6 were given
```

**Comment by couzhei** [comment]
by the way, your template for committing issues is so complicated it took 8 minutes to report such a simple thing!

**Comment by ebautista-globant** [comment]
> by the way, your template for committing issues is so complicated it took 8 minutes to report such a simple thing!

Please share your broker version

**Comment by couzhei** [comment]
```Bash
Status of node rabbit@f6ad08760dc5 ...
Runtime

OS PID: 20
OS: Linux
Uptime (seconds): 5
Is under maintenance?: false
RabbitMQ version: 4.0.0+beta.2.6.g65c3daf
RabbitMQ release series support status: see https://www.rabbitmq.com/release-information
Node name: rabbit@f6ad08760dc5
Erlang configuration: Erlang/OTP 26 [erts-14.2.5.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
Crypto library: OpenSSL 3.3.1 4 Jun 2024
Erlang processes: 362 used, 1048576 limit
Scheduler run queue: 1
Cluster heartbeat timeout (net_ticktime): 60
```

**Comment by couzhei** [comment]
Whoa it's `rc`. Now I feel ashamed! Although I believe it's a good head start for your team to be informed about their rc release.

**Comment by auvipy** [comment]
can you please share code to reproduce this?

**Comment by couzhei** [comment]
```Python
from celery import Celery

app = Celery('tasks', broker='pyamqp://ashkan:123456@localhost:5672//')

@app.task
def add(x, y):
    return x+y
```

Where the RabbitMQ server is exposed from a docker container onto my localhost:5672

using the command `docker run -d -p 5672:5672 rabbitmq:4.0-rc`, excluding the `:4.0-rc` part, everything is according to the tutorial on [](this )[page](https://docs.celeryq.dev/en/stable/getting-started/first-steps-with-celery.html#running-the-celery-worker-server).
Cheers

**Comment by thedrow** [comment]
@ebautista-globant Would you mind creating a PR for this bug fix?

**Comment by auvipy** [comment]
we need a better fix

**Comment by couzhei** [comment]
What seems to be the problem? @auvipy

**Comment by auvipy** [comment]
this was the report for revert https://github.com/celery/kombu/pull/2098#issuecomment-2488319244 I also opened a new revert for better review and improved version. feel free to review that
