### ISSUE TITLE
Error getting task state: _pickle.UnpicklingError: invalid load key, '{'

### ISSUE THREAD

**Issue by Azteker** [celery/celery#9172]
celery version: 5.3.6
django-redis>=4.12.1

```
>>> from celery.result import AsyncResult
>>> task = AsyncResult('f3b46ac8-e6e3-4221-b785-9e3ccb24a3bc')
>>> task.state
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 265, in loads
    return decode(data)
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 337, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 50, in pickle_loads
    return load(BytesIO(s))
_pickle.UnpicklingError: invalid load key, '{'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/celery/result.py", line 503, in state
    return self._get_task_meta()['status']
  File "/usr/local/lib/python3.9/site-packages/celery/result.py", line 442, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/usr/local/lib/python3.9/site-packages/celery/backends/base.py", line 608, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/usr/local/lib/python3.9/site-packages/celery/backends/base.py", line 998, in _get_task_meta_for
    return self.decode_result(meta)
  File "/usr/local/lib/python3.9/site-packages/celery/backends/base.py", line 425, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/usr/local/lib/python3.9/site-packages/celery/backends/base.py", line 431, in decode
    return loads(payload,
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 265, in loads
    return decode(data)
  File "/usr/lib64/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 45, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/kombu/exceptions.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 265, in loads
    return decode(data)
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 337, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 50, in pickle_loads
    return load(BytesIO(s))
kombu.exceptions.DecodeError: invalid load key, '{'.
```
The task is triggered with send_task method to another pod for celery task executing, it is fine to get result with that pod though

**Comment by thedrow** [comment]
There's not enough here to reproduce this problem.
Could you come up with a test case that demonstrates it?
If you can, I'll reopen this issue.

**Comment by AvihaiSam** [comment]
I had the same issue. removing "json" from "accept_content" did the work.
