### ISSUE TITLE
getting celery.exceptions.Reject: (KeyError('headers'), False) when custom headers is set and the task is retried 

### ISSUE THREAD

**Issue by aashayamballi** [celery/celery#9174]
# Checklist

- [X] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [ ] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [X] I have verified that the issue exists against the `main` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

#### Related Issues

https://github.com/celery/celery/issues/4875
https://github.com/celery/celery/pull/7555
https://github.com/celery/celery/pull/6374

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b>
</summary>
<p>

software -> celery:5.4.0 (opalescent) kombu:5.3.7 py:3.9.19
            billiard:4.2.0 py-amqp:5.2.0
platform -> system:Linux arch:64bit
            kernel version:6.10.0-linuxkit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: 3.9
- **Minimal Celery Version**: 5.4.0

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>
django==4.2.10
celery==5.4.0
django-celery-beat==2.6.0
django-celery-results==2.5.1
sentry-sdk==1.42.0

</p>
</details>

### Other Dependencies

<details>
<p>
Redis server v=7.2.4 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=42763e0fcb7bd0b8
</p>
</details>

Hi everyone,

I have encountered an issue with my code and I would appreciate some advice on how to resolve it.

I have a Celery base class that retrieves a user instance using the `get_current_user` method (this is a utility method used in our app). Before publishing a task, I set the current user ID as a header. Once the task is received in the worker, I extract the user ID from the header and set the current user using a utility function.

```
class BaseTask(CELERY_APP.Task):
    """Abstract base class for all tasks in my app"""

    abstract = True

    def _log_exception(self, exc, task_id, args, kwargs, einfo):  # pylint: disable=too-many-arguments
        LOGGER.error(
            'Celery Exception: "%s" from Task "%s" with args/kwargs %s/%s and einfo "%s"',
            exc,
            task_id,
            args,
            kwargs,
            einfo,
        )  # pylint: disable=line-too-long
        LOGGER.exception(exc)

    def on_retry(self, exc, task_id, args, kwargs, einfo):  # pylint: disable=too-many-arguments
        """Log the exceptions at retry"""
        self._log_exception(exc, task_id, args, kwargs, einfo)
        super(BaseTask, self).on_retry(exc, task_id, args, kwargs, einfo)

    def on_failure(self, exc, task_id, args, kwargs, einfo):  # pylint: disable=too-many-arguments
        """Log the exceptions when we fail"""
        self._log_exception(exc, task_id, args, kwargs, einfo)
        super(BaseTask, self).on_failure(exc, task_id, args, kwargs, einfo)

class BaseCurrentUserTask(BaseTask):
    """Abstract base class for tasks that require the current user"""

    abstract = True

    def _is_eager_mode(self):
        """
        Check if the Celery task is running in eager mode.

        Returns:
            bool: True if the task is running in eager mode, False otherwise.
        """
        from celery import current_app

        return current_app.conf.task_always_eager

    def _set_current_user(self):
        """Set the current user to local thread of the worker"""
        from utility.current_user import set_current_user

        current_user = self.get_current_user()

        if current_user:
            set_current_user(current_user)

    def get_current_user_id(self):
        """
        Get the current user ID.

        If the task is running in eager mode, it retrieves the current user ID from the request headers.
        Otherwise, it retrieves the current user ID from the request.

        Returns:
            str: The current user ID.
        """
        if self._is_eager_mode():
            return self.request.headers.get("current_user_id")
        else:
            return self.request.get("current_user_id")

    def get_current_user(self):
        from authentication.models import User

        current_user = User.objects.filter(pk=self.get_current_user_id()).first()
        return current_user

    def before_start(self, task_id, args, kwargs):
        self._set_current_user()
        return super().before_start(task_id, args, kwargs)

    def on_success(self, retval, task_id, args, kwargs):
        super().on_success(retval, task_id, args, kwargs)

        from utility.current_user import set_current_user

        # on succss reset the current user to None if not in eager mode
        if not self._is_eager_mode():
            set_current_user(None)

    def on_failure(self, exc, task_id, args, kwargs, einfo):  # pylint: disable=too-many-arguments

        from utility.current_user import set_current_user

        # on failure reset the current user to None if not in eager mode
        if not self._is_eager_mode():
            set_current_user(None)

    def _get_current_user_id_header(self, task_kwargs: dict) -> dict:
        from utility.current_user import get_current_user

        if task_kwargs.get("custom_current_user_id"):
            user_id = task_kwargs.pop("custom_current_user_id")
            return {"current_user_id": user_id}

        current_user = get_current_user()
        user_id = str(current_user.id) if current_user else None
        return {"current_user_id": user_id}

    def _get_task_headers(self, task_kwargs: dict) -> dict:
        headers = {}
        headers.update(self._get_current_user_id_header(task_kwargs))
        return headers

    def apply_async(
        self, args=None, kwargs=None, task_id=None, producer=None, link=None, link_error=None, shadow=None, **options
    ):
        headers = self._get_task_headers(kwargs)
        super().apply_async(args, kwargs, task_id, producer, link, link_error, shadow, headers=headers, **options)
```

```
@CELERY_APP.task(base=BaseCurrentUserTask, bind=True, name="test_current_user", retry_kwargs={"max_retries": 2})
def test_current_user(self):
    from time import sleep

    try:
        if self.request.retries < self.max_retries:
            sleep(2)
            raise Exception()
        else:
            return "Last retry, no exception raised"
    except Exception as e:
        raise self.retry(exc=e)
```
The problem arises when I try to retry a task. In the console, I receive the following error message:

```
[2024-08-05 14:49:52,482: WARNING/ForkPoolWorker-7] Task test_current_user[606303f0-16fc-4eff-9dea-8355f503ed8f] reject requeue=False: 'headers'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
  File "/code/projects/tasks.py", line 71, in test_current_user
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 753, in retry
    S.apply_async()
  File "/usr/local/lib/python3.9/site-packages/celery/canvas.py", line 400, in apply_async
    return _apply(args, kwargs, **options)
  File "/code/core/celery.py", line 324, in apply_async
    super().apply_async(args, kwargs, task_id, producer, link, link_error, shadow, headers=headers, **options)
KeyError: 'headers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 306, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 127, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 301, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 755, in retry
    raise Reject(exc, requeue=False)
celery.exceptions.Reject: (KeyError('headers'), False)
```

Additionally, I have tried to search for a solution to this issue and came across two relevant PRs

https://github.com/celery/celery/issues/4875
https://github.com/celery/celery/pull/7555
https://github.com/celery/celery/pull/6374

I'm uncertain if this issue is internal to Celery or if there's something I need to fix in my code. If anyone has any insights or suggestions, your help would be greatly appreciated.

Thank you!

**Comment by aashayamballi** [comment]
I have observed some inconsistencies in the documentation for the [apply_async](https://docs.celeryq.dev/en/stable/reference/celery.app.task.html#celery.app.task.Task.apply_async) method of the Celery Task class. While the documented method signature shows parameters like `args, kwargs, task_id, producer, link, link_error, and shadow,` there is mention of the `headers` parameter at the end of the documentation. However, upon inspecting the source code, I couldn't find any headers=None parameter.

I'm uncertain whether this discrepancy is related to the issue I mentioned earlier or if it's a separate concern.

**Comment by aashayamballi** [comment]
well I made silly mistake forgot include the headers argument in the base class apply_async method, adding it sovled my issue.
