### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'fileno' on reconnection with worker_cancel_long_running_tasks_on_connection_loss

### ISSUE THREAD

**Issue by Osmoskour** [celery/celery#9250]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [ ] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.5.0b3 (immunity) kombu:5.4.0 py:3.12.5
            billiard:4.2.0 py-amqp:5.2.0
platform -> system:Linux arch:64bit, ELF
            kernel version:6.8.0-41-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

broker_channel_error_retry: True
broker_connection_max_retries: None
broker_connection_retry_on_startup: True
task_acks_late: True
worker_cancel_long_running_tasks_on_connection_loss: True
broker_url: 'amqp://guest:********@localhost:5672//'
include: ['src.tasks']
deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: 3.12.5
- **Minimal Celery Version**: 5.4.0
- **Minimal Kombu Version**: 5.4.0
- **Minimal Broker Version**: RabbitMQ 3.13.7
- **Minimal Result Backend Version**: N/A
- **Minimal OS and/or Kernel Version**: Ubuntu 24.04.1 / Kernel 6.8.0
- **Minimal Broker Client Version**: N/A
- **Minimal Result Backend Client Version**: N/A

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.2.0
autopep8==2.3.1
billiard==4.2.0
cached-property==1.5.2
celery==5.5.0b3
click==8.1.7
click-didyoumean==0.3.1
click-plugins==1.1.1
click-repl==0.3.0
coverage==7.6.1
flake8==7.1.1
flower==2.0.1
greenlet==3.0.3
humanize==4.10.0
inflection==0.5.1
iniconfig==2.0.0
kombu==5.4.0
mccabe==0.7.0
mock==5.1.0
mypy-extensions==1.0.0
packaging==24.1
pluggy==1.5.0
prometheus_client==0.20.0
prompt_toolkit==3.0.47
pycodestyle==2.12.1
pyflakes==3.2.0
pytest==8.3.2
python-dateutil==2.9.0.post0
pytz==2024.1
six==1.16.0
SQLAlchemy==2.0.34
sqlalchemy-orm==1.2.10
tornado==6.4.1
typing-inspect==0.9.0
typing_extensions==4.12.2
vine==5.1.0
wcwidth==0.2.13
```

</p>
</details>

### Other Dependencies

<details>
<p>
    
celery_config.py
```python
task_acks_late = True

broker_connection_retry_on_startup = True
broker_channel_error_retry = True
broker_connection_max_retries = None

worker_cancel_long_running_tasks_on_connection_loss = True
```

rabbitmq.conf
```
consumer_timeout = 61000
```

</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>
    
celery.py
```python
from celery import Celery
app = Celery('src',
             broker='amqp://guest@localhost//',
             include=['src.tasks'])
app.config_from_object('celery_config')
```

tasks.py
```python
from src.celery import app
import time
    
@app.task
def timeout_rabbitmq():
    print('RabbitMQ timeout task')
    time.sleep(70)
    return  
```
    
run.py
```python
from src.tasks import timeout_rabbitmq

if __name__ == '__main__':
    for i in range(20):
        r1 = timeout_rabbitmq.delay()
```

with a RabbitMQ instance in the background.
- Run run.py.
- Cut the connection between the worker and the broker (by Ctrl C/docker kill the docker container of the RabbitMQ or by having a PRECONDITION_FAILED cuased by a timeout on the RabbitMQ, for example).
- Restart the RabbitMQ.
- When the connection is established, cut a second time the connection between the worker and the broker.
- Restart the RabbitMQ.
- The worker crashed.

</p>
</details>

# Expected Behavior

The worker must stay up after the second reconnection and not crash.
# Actual Behavior

The worker crashed. I dug into the code and found that in the function iterate_file_descriptors_safely in concurrency/asynpool.py L.211, some of the fd transformed into NoneType, resulting in an AttributeError not captured by the except L.216 (https://github.com/celery/celery/blob/main/celery/concurrency/asynpool.py#L211). By adding the AttributeError to the except, the expected behavior is observed.

```python
    for fd in fds_iter:
        # Handle using the correct arguments to the hub method
        hub_args, hub_kwargs = _meta_fd_argument_maker(), kwargs
        try:  # Call the hub method
            hub_method(fd, *hub_args, **hub_kwargs)
        except (OSError, FileNotFoundError, AttributeError):
            logger.warning(
                "Encountered OSError when accessing fd %s ",
                fd, exc_info=True)
            stale_fds.append(fd)  # take note of stale fd
```

```
 -------------- celery@eloi-Latitude-5420 v5.5.0b3 (immunity)
--- ***** ----- 
-- ******* ---- Linux-6.8.0-41-generic-x86_64-with-glibc2.39 2024-09-10 09:56:05
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         src:0x7a777d56ae70
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . src.tasks.fail_on_purpose
  . src.tasks.looping
  . src.tasks.test
  . src.tasks.timeout_rabbitmq

[2024-09-10 09:56:05,971: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-09-10 09:56:05,979: INFO/MainProcess] mingle: searching for neighbors
[2024-09-10 09:56:07,004: INFO/MainProcess] mingle: all alone
[2024-09-10 09:56:07,021: INFO/MainProcess] celery@eloi-Latitude-5420 ready.
[2024-09-10 09:56:07,021: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[c2799351-eadb-4b43-8a4b-ed9aa699981d] received
[2024-09-10 09:56:07,022: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[f2d4788b-62c3-4a66-91e9-1d5500f733dc] received
[2024-09-10 09:56:07,022: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[2b4d32a8-f324-4602-b32c-d9de5ba1f7d5] received
[2024-09-10 09:56:07,022: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[843401d4-f20a-4b33-93d3-1b7871c18de1] received
[2024-09-10 09:56:07,022: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[95b8a62b-74ba-4a6b-bc15-022b3dc744cd] received
[2024-09-10 09:56:07,023: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[bd8096e0-f22e-4f71-af3c-47bfd5f43621] received
[2024-09-10 09:56:07,023: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[f0fb68a4-62df-4c84-9c3b-5e5143a80160] received
[2024-09-10 09:56:07,023: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[2df3b8b3-83a4-4085-9032-c1646b1f2c24] received
[2024-09-10 09:56:07,024: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[a7579fdb-5826-48bf-9e44-70baee108738] received
[2024-09-10 09:56:07,024: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[236b6e85-b16c-45ba-9b68-10dd6e60216e] received
[2024-09-10 09:56:07,024: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[b53d85ad-d8eb-45d2-acd9-708506a2a7aa] received
[2024-09-10 09:56:07,024: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[5aa6559d-6d7d-4b0e-97db-0a9d997929ea] received
[2024-09-10 09:56:07,024: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[4d851ce4-1d3d-4429-80f3-6a9339518588] received
[2024-09-10 09:56:07,025: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[28e6606f-283a-4873-8aa1-dad4c93ccb7f] received
[2024-09-10 09:56:07,025: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[43e253e9-ead0-4cc7-8e30-62c27a32868d] received
[2024-09-10 09:56:07,025: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[4800c117-cd9f-4eb3-8c9f-18e866b991a0] received
[2024-09-10 09:56:07,025: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[c4e2aa7e-3665-46c2-a66c-e74dc5bf0b0c] received
[2024-09-10 09:56:07,025: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[7bdf148a-8558-4adc-b030-a4a5b3ac8087] received
[2024-09-10 09:56:07,026: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[e7fce92e-831d-45b7-9554-9269de83baa4] received
[2024-09-10 09:56:07,026: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[fc85b837-d796-45ce-b403-b22264f30710] received
[2024-09-10 09:56:07,127: WARNING/ForkPoolWorker-7] RabbitMQ timeout task
[2024-09-10 09:56:07,127: WARNING/ForkPoolWorker-6] RabbitMQ timeout task
[2024-09-10 09:56:07,127: WARNING/ForkPoolWorker-1] RabbitMQ timeout task
[2024-09-10 09:56:07,128: WARNING/ForkPoolWorker-2] RabbitMQ timeout task
[2024-09-10 09:56:07,127: WARNING/ForkPoolWorker-5] RabbitMQ timeout task
[2024-09-10 09:56:07,127: WARNING/ForkPoolWorker-3] RabbitMQ timeout task
[2024-09-10 09:56:07,128: WARNING/ForkPoolWorker-4] RabbitMQ timeout task
[2024-09-10 09:56:07,128: WARNING/ForkPoolWorker-8] RabbitMQ timeout task
[2024-09-10 09:56:15,700: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 759, in start
    c.loop(*c.loop_args())
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/kombu/transport/base.py", line 248, in on_readable
    reader(loop)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/kombu/transport/base.py", line 230, in _read
    drain_events(timeout=0)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/connection.py", line 526, in drain_events
    while not self.blocking_read(timeout):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/connection.py", line 532, in blocking_read
    return self.on_inbound_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/method_framing.py", line 53, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/connection.py", line 538, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/abstract_channel.py", line 156, in dispatch_method
    listener(*args)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/connection.py", line 668, in _on_close
    raise error_for_code(reply_code, reply_text,
amqp.exceptions.ConnectionForced: (0, 0): (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
[2024-09-10 09:56:15,705: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[bd8096e0-f22e-4f71-af3c-47bfd5f43621] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:15,706: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[2df3b8b3-83a4-4085-9032-c1646b1f2c24] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:15,706: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[c2799351-eadb-4b43-8a4b-ed9aa699981d] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:15,706: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[843401d4-f20a-4b33-93d3-1b7871c18de1] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:15,706: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[2b4d32a8-f324-4602-b32c-d9de5ba1f7d5] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:15,706: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[95b8a62b-74ba-4a6b-bc15-022b3dc744cd] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:15,706: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[f0fb68a4-62df-4c84-9c3b-5e5143a80160] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:15,707: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[f2d4788b-62c3-4a66-91e9-1d5500f733dc] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:15,709: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds... (1/None)

[2024-09-10 09:56:17,710: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/None)

[2024-09-10 09:56:21,711: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds... (3/None)

[2024-09-10 09:56:27,715: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-09-10 09:56:27,727: INFO/MainProcess] mingle: searching for neighbors
[2024-09-10 09:56:28,752: INFO/MainProcess] mingle: all alone
[2024-09-10 09:56:28,769: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[c2799351-eadb-4b43-8a4b-ed9aa699981d] received
[2024-09-10 09:56:28,770: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[f2d4788b-62c3-4a66-91e9-1d5500f733dc] received
[2024-09-10 09:56:28,770: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[2b4d32a8-f324-4602-b32c-d9de5ba1f7d5] received
[2024-09-10 09:56:28,770: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[843401d4-f20a-4b33-93d3-1b7871c18de1] received
[2024-09-10 09:56:28,770: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[95b8a62b-74ba-4a6b-bc15-022b3dc744cd] received
[2024-09-10 09:56:28,770: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[bd8096e0-f22e-4f71-af3c-47bfd5f43621] received
[2024-09-10 09:56:28,771: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[f0fb68a4-62df-4c84-9c3b-5e5143a80160] received
[2024-09-10 09:56:28,771: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[2df3b8b3-83a4-4085-9032-c1646b1f2c24] received
[2024-09-10 09:56:28,771: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[a7579fdb-5826-48bf-9e44-70baee108738] received
[2024-09-10 09:56:28,771: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[236b6e85-b16c-45ba-9b68-10dd6e60216e] received
[2024-09-10 09:56:28,771: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[b53d85ad-d8eb-45d2-acd9-708506a2a7aa] received
[2024-09-10 09:56:28,771: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[5aa6559d-6d7d-4b0e-97db-0a9d997929ea] received
[2024-09-10 09:56:28,771: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[4d851ce4-1d3d-4429-80f3-6a9339518588] received
[2024-09-10 09:56:28,772: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[28e6606f-283a-4873-8aa1-dad4c93ccb7f] received
[2024-09-10 09:56:28,772: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[43e253e9-ead0-4cc7-8e30-62c27a32868d] received
[2024-09-10 09:56:28,772: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[4800c117-cd9f-4eb3-8c9f-18e866b991a0] received
[2024-09-10 09:56:28,772: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[c4e2aa7e-3665-46c2-a66c-e74dc5bf0b0c] received
[2024-09-10 09:56:28,772: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[7bdf148a-8558-4adc-b030-a4a5b3ac8087] received
[2024-09-10 09:56:28,772: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[e7fce92e-831d-45b7-9554-9269de83baa4] received
[2024-09-10 09:56:28,773: INFO/MainProcess] Task src.tasks.timeout_rabbitmq[fc85b837-d796-45ce-b403-b22264f30710] received
[2024-09-10 09:56:29,180: WARNING/ForkPoolWorker-10] RabbitMQ timeout task
[2024-09-10 09:56:29,180: WARNING/ForkPoolWorker-14] RabbitMQ timeout task
[2024-09-10 09:56:29,180: WARNING/ForkPoolWorker-13] RabbitMQ timeout task
[2024-09-10 09:56:29,180: WARNING/ForkPoolWorker-12] RabbitMQ timeout task
[2024-09-10 09:56:29,180: WARNING/ForkPoolWorker-9] RabbitMQ timeout task
[2024-09-10 09:56:29,180: WARNING/ForkPoolWorker-11] RabbitMQ timeout task
[2024-09-10 09:56:29,180: WARNING/ForkPoolWorker-15] RabbitMQ timeout task
[2024-09-10 09:56:29,183: WARNING/ForkPoolWorker-16] RabbitMQ timeout task
[2024-09-10 09:56:31,021: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 759, in start
    c.loop(*c.loop_args())
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/kombu/transport/base.py", line 248, in on_readable
    reader(loop)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/kombu/transport/base.py", line 230, in _read
    drain_events(timeout=0)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/connection.py", line 526, in drain_events
    while not self.blocking_read(timeout):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/connection.py", line 532, in blocking_read
    return self.on_inbound_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/method_framing.py", line 53, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/connection.py", line 538, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/abstract_channel.py", line 156, in dispatch_method
    listener(*args)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/amqp/connection.py", line 668, in _on_close
    raise error_for_code(reply_code, reply_text,
amqp.exceptions.ConnectionForced: (0, 0): (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
[2024-09-10 09:56:31,022: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[2df3b8b3-83a4-4085-9032-c1646b1f2c24] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:31,023: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[f2d4788b-62c3-4a66-91e9-1d5500f733dc] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:31,023: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[95b8a62b-74ba-4a6b-bc15-022b3dc744cd] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:31,023: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[f0fb68a4-62df-4c84-9c3b-5e5143a80160] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:31,023: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[c2799351-eadb-4b43-8a4b-ed9aa699981d] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:31,023: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[843401d4-f20a-4b33-93d3-1b7871c18de1] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:31,024: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[2b4d32a8-f324-4602-b32c-d9de5ba1f7d5] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:31,024: WARNING/MainProcess] Task src.tasks.timeout_rabbitmq[bd8096e0-f22e-4f71-af3c-47bfd5f43621] cannot be acknowledged after a connection loss since late acknowledgement is enabled for it.
Terminating it instead.

[2024-09-10 09:56:31,026: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds... (1/None)

[2024-09-10 09:56:33,027: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/None)

[2024-09-10 09:56:37,029: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds... (3/None)

[2024-09-10 09:56:43,032: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-09-10 09:56:43,036: INFO/MainProcess] mingle: searching for neighbors
[2024-09-10 09:56:44,094: INFO/MainProcess] mingle: all alone
[2024-09-10 09:56:44,107: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'fileno'")
Traceback (most recent call last):
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 759, in start
    c.loop(*c.loop_args())
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/loops.py", line 62, in asynloop
    obj.controller.register_with_event_loop(hub)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/worker.py", line 215, in register_with_event_loop
    self.blueprint.send_all(
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/bootsteps.py", line 148, in send_all
    fun(parent, *args)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/worker/components.py", line 175, in register_with_event_loop
    w.pool.register_with_event_loop(hub)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/concurrency/prefork.py", line 137, in register_with_event_loop
    return reg(loop)
           ^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 519, in register_with_event_loop
    [self._track_child_process(w, hub) for w in self._pool]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 500, in _track_child_process
    iterate_file_descriptors_safely(
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 215, in iterate_file_descriptors_safely
    hub_method(fd, *hub_args, **hub_kwargs)
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/kombu/asynchronous/hub.py", line 221, in add_reader
    return self.add(fds, callback, READ | ERR, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/kombu/asynchronous/hub.py", line 169, in add
    fd = fileno(fd)
         ^^^^^^^^^^
  File "/home/eloi/BOC/demo-celery/.venv/lib/python3.12/site-packages/kombu/utils/compat.py", line 95, in fileno
    return f.fileno()
           ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fileno'
```

**Comment by thedrow** [comment]
Contributions are welcome.

**Comment by Tazmaniac** [comment]
fds_iter could not be null : https://github.com/celery/celery/blob/82d7895e3a78fd7682870fb5084ebce582c9f2ba/celery/concurrency/asynpool.py#L489

So after the first re-connection the previous fd is replaced in the list by NoneType instead of being removed from the list.

The next question is: is this expected to have NoneType in fds_iter list ? Or is it the symptom of a bug in the fd management/cleanup ?

**Comment by anushds** [comment]
I did look into this a bit and here are my findings from the logs generated.

1. This is applicable in the prefork pool(I tried it out solo pool but didn't see this behavior).
2. The `task_acks_late` and `worker_cancel_long_running_tasks_on_connection_loss` should be set to True to reproduce this behavior.
3. This is applicable when the forked process count is greater than 1(I tried out with just 1 process by setting concurrency to 1 but didn't see this behavior).
[celery3.log](https://github.com/user-attachments/files/17054919/celery3.log) - I've set the concurrency to 2 to avoid a lot of logs. But from logs, it can be seen that the fork process(4) which is in the **started** state is untracked and when the second disconnection happens, the track child method is called on this process. But since the `_sentinel_poll` is already set(None value) on this process, it proceeds to iterate over the file descriptor which leads to this error.

Well, I'm not sure whether untracking a process that is in started state is correct as I'm not entirely familiar with the codebase. Just wanted to post the findings in case someone can point me in the right direction.

**Comment by auvipy** [comment]
we now got a potential fix for this
