### ISSUE TITLE
Breaking `pymongo[srv]` with `pymongo==4.8.0`

### ISSUE THREAD

**Issue by fmigneault** [celery/celery#9254]
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [ ] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- Corresponding issue on MongoDB tracker: https://jira.mongodb.org/browse/PYTHON-4756
- Workaround PR fix: https://github.com/crim-ca/weaver/pull/709

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.3.5 (emerald-rush) kombu:5.3.4 py:3.10.13
            billiard:4.2.0 py-amqp:5.2.0
platform -> system:Linux arch:64bit, ELF
            kernel version:5.15.0-119-generic imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: `pymongo==4.8.0`
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
alabaster==0.7.13
alembic==1.12.1
amqp==5.2.0
annotated-types==0.6.0
anyascii==0.3.2
argcomplete==3.1.6
asciitree==0.3.3
astor==0.8.1
astroid==2.15.8
attrs==23.1.0
Authlib==1.3.0
Babel @ file:///croot/babel_1671781930836/work
bandit==1.7.5
Beaker==1.12.1
beautifulsoup4==4.12.2
billiard==4.2.0
boto3==1.34.144
boto3-stubs==1.29.4
botocore==1.34.144
botocore-stubs==1.32.4
Brotli @ file:///croot/brotli-split_1714483155106/work
bump2version==1.0.1
CacheControl==0.13.1
celery==5.3.5
certifi @ file:///home/conda/feedstock_root/build_artifacts/certifi_1707022139797/work/certifi
cffconvert==2.0.0
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cligj==0.7.2
codacy-coverage==1.3.11
colander==1.8.3
colorama @ file:///croot/colorama_1672386526460/work
coloredlogs==15.0.1
contextlib2==21.6.0
cornice==6.1.0
cornice-swagger @ git+https://github.com/fmigneault/cornice.ext.swagger.git@b66bd4d85f5f5550f39d046742ae9799aee1f153
coverage==7.3.2
cryptography==41.0.5
cwl-upgrader==1.2.10
cwl-utils==0.33
cwltool @ git+https://github.com/fmigneault/cwltool.git@77254efa4dc053bc5c8713f1886a75ab7e130023
dateparser==1.2.0
decorator==5.1.1
deepmerge==1.1.1
defusedxml==0.7.1
dill==0.3.7
dnspython==2.4.2
doc8==0.11.2
docformatter==1.7.5
docker==7.1.0
docopt==0.6.2
docutils==0.18.1
dparse==0.6.4b0
duration==1.1.1
esgf-compute-api @ git+https://github.com/ESGF/esgf-compute-api.git@8faf829abb3ba0434715c4db44440cfb9c71b55f
execnet==2.0.2
fasteners==0.19
filelock==3.13.1
fiona==1.9.5
flake8==5.0.4
flynt==1.0.1
future==0.18.3
geotiff==0.2.10
gitdb==4.0.11
GitPython==3.1.40
greenlet==3.0.1
gunicorn==22.0.0
humanfriendly==10.0
humanize==4.8.0
hupper==1.12.1
idna @ file:///croot/idna_1714398848350/work
imagesize @ file:///opt/conda/conda-bld/imagesize_1657179498843/work
importlib-resources==6.1.1
iniconfig==2.0.0
iso8601==2.1.0
isodate==0.6.1
isort==5.12.0
Jinja2==3.1.2
jmespath==1.0.1
json2xml==4.1.0
jsonschema==4.23.0
jsonschema-specifications==2023.11.1
kombu==5.3.4
lark==0.12.0
lazy-object-proxy==1.9.0
lxml==4.9.3
Mako @ file:///croot/mako_1665472421453/work
markdown-it-py==3.0.0
MarkupSafe @ file:///croot/markupsafe_1704205993651/work
marshmallow==3.21.1
mccabe==0.7.0
mdurl==0.1.2
mistune==3.0.2
mock==3.0.5
moto==4.2.14
msgpack==1.0.7
mypy==1.7.0
mypy-boto3-s3==1.29.3
mypy-extensions==1.0.0
networkx==3.2.1
numcodecs==0.12.1
numpy==1.26.2
oauthlib==3.2.2
OWSLib==0.29.3
packaging @ file:///croot/packaging_1710807400464/work
parameterized==0.9.0
Paste==3.7.1
PasteDeploy==2.0.1
path==16.7.1
path.py==12.5.0
pbr==6.0.0
picobox==4.0.0
Pint==0.22
plaster==1.0
plaster-pastedeploy==0.7
platformdirs==4.0.0
pluggy==1.3.0
prompt-toolkit==3.0.41
prov==1.5.1
psutil==5.9.6
py==1.11.0
pycodestyle==2.9.1
pycparser==2.21
pydantic==2.7.0
pydantic_core==2.18.1
pydocstyle==6.3.0
pydot==1.4.2
pyflakes==2.5.0
pygeofilter==0.2.4
pygeoif==1.5.0
Pygments @ file:///croot/pygments_1684279966437/work
pygml==0.2.2
pykwalify==1.8.0
pylint==2.17.7
pylint-per-file-ignores==1.3.2
pylint-quotes==0.2.3
pymongo==4.8.0
pyparsing==3.1.1
pyproj==3.6.1
pyramid==2.0.2
pyramid-beaker==0.8
pyramid-celery @ git+https://github.com/crim-ca/pyramid_celery.git@3d4c5096661176b176cab4b7d31b282317c70301
pyramid-mako @ file:///home/builder/ci_310/pyramid_mako_1640793613736/work
pyramid-rewrite==0.2
pyramid-storage==1.3.0
pyrsistent==0.20.0
PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
pystac==1.10.1
pystac-client==0.8.3
pytest==6.2.5
pytest-fixture-config==1.7.0
pytest-httpserver==1.0.8
pytest-rerunfailures==12.0
pytest-server-fixtures==1.7.0
pytest-shutil==1.7.0
python-box==7.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
pywps==4.6.0
PyYAML==6.0.1
rdflib==7.0.0
referencing==0.31.0
regex==2024.5.15
requests==2.32.2
requests-file==1.5.1
requests-magpie @ git+https://github.com/Ouranosinc/requests-magpie@b26ed3c2cee4395c1bd745c7e102a442ba2199ae
responses==0.24.1
restructuredtext-lint==1.4.0
retry==0.9.2
rich==13.7.0
rpds-py==0.13.1
ruamel.yaml==0.17.40
ruamel.yaml.clib==0.2.8
s3transfer==0.10.2
safety==3.1.0
safety-schemas==0.0.2
schema-salad==8.7.20240820070935
shapely==2.0.2
shellescape==3.8.1
shellingham==1.5.4
simplejson==3.19.2
six==1.16.0
smmap==5.0.1
snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1637937080595/work
soupsieve==2.5
Sphinx==7.2.6
sphinx-argparse==0.4.0
sphinx-autoapi==3.0.0
sphinx-autodoc-typehints==1.25.2
sphinx-paramlinks==0.6.0
sphinx-rtd-theme==1.3.0
sphinx_mdinclude==0.6.1
sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work
sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work
sphinxcontrib-htmlhelp @ file:///tmp/build/80754af9/sphinxcontrib-htmlhelp_1623945626792/work
sphinxcontrib-httpdomain==1.8.1
sphinxcontrib-jquery @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-jquery_1678808969227/work
sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work
sphinxcontrib-openapi==0.8.4
sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work
sphinxcontrib-redoc==1.6.0
sphinxcontrib-serializinghtml==1.1.10
spython==0.3.13
SQLAlchemy==2.0.23
stevedore==5.1.0
stopit==1.1.2
termcolor==2.3.0
tifffile==2023.9.26
toml==0.10.2
tomli==2.0.1
tomlkit==0.12.3
translationstring==1.3
typer==0.12.3
types-awscrt==0.19.13
types-html5lib==1.1.11.20240228
types-requests==2.31.0.20240406
types-s3transfer==0.7.0
typing_extensions==4.8.0
tzdata==2023.3
tzlocal==5.2
untokenize==0.1.1
urllib3==2.2.2
urlmatch==1.0.1
venusian==1.2.0
vine==5.1.0
waitress==2.1.2
wcwidth==0.2.11
-e git+ssh://git@github-perso/crim-ca/weaver@15eb97d3769cd1245cc8416fe3119d33b29b27fd#egg=weaver
WebOb @ file:///tmp/build/80754af9/webob_1614626070523/work
websocket-client==1.6.4
WebTest==3.0.0
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1715000201436/work
wrapt==1.16.0
WSGIProxy==0.2.2
WSGIProxy2==0.5.1
xmltodict==0.13.0
zarr==2.12.0
zipp==3.19.2
zope.deprecation==4.4.0
zope.interface @ file:///home/builder/ci_310/zope.interface_1640811449297/work

```

</p>
</details>

### Other Dependencies

- `pymongo==4.8.0`
- `pyramid==2.0.2`

## Minimally Reproducible Test Case

Import the packages in Python, such that `pkg_resources` parsing of `celery` dependency metadata with `pymongo[srv]` gets triggered. 

```pytb
Traceback (most recent call last):
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3097, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'srv'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/francis/dev/conda/envs/weaver/bin/weaver", line 33, in <module>
    sys.exit(load_entry_point('weaver', 'console_scripts', 'weaver')())
  File "/home/francis/dev/conda/envs/weaver/bin/weaver", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/francis/dev/weaver/weaver/cli.py", line 17, in <module>
    from pyramid.httpexceptions import HTTPNotImplemented
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pyramid/httpexceptions.py", line 139, in <module>
    from pyramid.util import text_
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pyramid/util.py", line 8, in <module>
    from pyramid.path import DottedNameResolver as _DottedNameResolver
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pyramid/path.py", line 3, in <module>
    import pkg_resources
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3657, in <module>
    def _initialize_master_working_set():
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3640, in _call_aside
    f(*args, **kwargs)
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3669, in _initialize_master_working_set
    working_set = _declare_state('object', 'working_set', WorkingSet._build_master())
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    ws.require(__requires__)
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pkg_resources/__init__.py", line 895, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3099, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: pymongo 4.8.0 has no such extra feature 'srv'
```

# Expected Behavior

The `srv` extra requirement should not be employed.
As shown in this diff ([mongodb/mongo-python-driver@`master...v4.8`#diff-60f61ab7a8](https://github.com/mongodb/mongo-python-driver/compare/master...v4.8#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)L154-L156), the `srv` extra requirement (https://github.com/mongodb/mongo-python-driver/blob/c36bfbc3f9c94078372de8c552bd0c23f77b43f9/setup.py#L154-L156) has been removed since 4.3, and is only left to avoid errors as above when parsing package metadata. 

Either pin `pymongo<4.8.0` (less prefered solution), or preferably, pin `pymongo>4.3.0` without the `[srv]` extra requirement should be used.

# Actual Behavior

Because it was completely removed in `pymongo==4.8.0`, the celery-specific requirement (https://github.com/celery/celery/blob/main/requirements/extras/mongodb.txt) using `[srv]` now breaks the package compatibility.

**Comment by thedrow** [comment]
If dnspython is now a direct dependency of mongodb, we can bump the version up.
Contributions are welcome.
