### ISSUE TITLE
Asynchronous tasks are repeatedly executed by multiple workers?

### ISSUE THREAD

**Issue by woshiyanghai** [celery/celery#9262]
I added a task chain through , my code is:
execute_sql_sig = signature('sql.utils.execute_sql.execute', args=(workflow_id,),task_id=name)
# 创建回调任务的签名
callback_sig = signature('sql.utils.execute_sql.execute_callback', args=(workflow_id,))
task_chain = execute_sql_sig | callback_sig

# Schedule chain tasks
task_chain.apply_async(eta=run_date) At some point in time, I found that my celery worker was executing the first person task at the same time, which is very strange

[2024-09-13 14:00:00,161: ERROR/ForkPoolWorker-1] Task sql.utils.execute_sql.execute[sqlreview-timing-197-1726192780.7794344] raised unexpected: Exception('工单状态不正确，禁止执行！')
Traceback (most recent call last):
  File "/data/download/venv4archery_archery/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data/download/venv4archery_archery/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/download/Archery/sql/utils/execute_sql.py", line 34, in execute
    raise Exception("工单状态不正确，禁止执行！")
Exception: 工单状态不正确，禁止执行！
[2024-09-13 14:00:00,168: ERROR/ForkPoolWorker-2] Task sql.utils.execute_sql.execute[sqlreview-timing-197-1726192780.7794344] raised unexpected: Exception('工单状态不正确，禁止执行！')
Traceback (most recent call last):
  File "/data/download/venv4archery_archery/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data/download/venv4archery_archery/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/download/Archery/sql/utils/execute_sql.py", line 34, in execute
    raise Exception("工单状态不正确，禁止执行！")
Exception: 工单状态不正确，禁止执行！
[2024-09-13 14:00:00,167: ERROR/ForkPoolWorker-4] Task sql.utils.execute_sql.execute[sqlreview-timing-197-1726192780.7794344] raised unexpected: Exception('工单状态不正确，禁止执行！')
Traceback (most recent call last):
  File "/data/download/venv4archery_archery/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data/download/venv4archery_archery/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/download/Archery/sql/utils/execute_sql.py", line 34, in execute
    raise Exception("工单状态不正确，禁止执行！")
Exception: 工单状态不正确，禁止执行！
[2024-09-13 14:00:00,333: ERROR/ForkPoolWorker-1] Task sql.utils.execute_sql.execute[sqlreview-timing-197-1726192780.7794344] raised unexpected: Exception('工单状态不正确，禁止执行！')
Traceback (most recent call last):
  File "/data/download/venv4archery_archery/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data/download/venv4archery_archery/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/download/Archery/sql/utils/execute_sql.py", line 34, in execute
    raise Exception("工单状态不正确，禁止执行！")
Exception: 工单状态不正确，禁止执行！
[2024-09-13 14:00:00,455: INFO/MainProcess] Task sql.utils.execute_sql.execute_callback[34166ffb-b232-4d08-b685-a8f24bb2786d] received

**Comment by woshiyanghai** [comment]
https://github.com/celery/celery/issues/4400
