### ISSUE TITLE
celery multi start not working in a Docker container

### ISSUE THREAD

**Issue by nielsreijers** [celery/celery#9390]
# Checklist
- [ ] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).
- [ ] I have tried to reproduce the issue with [pytest-celery](https://docs.celeryq.dev/projects/pytest-celery/en/latest/userguide/celery-bug-report.html) and added the reproduction script below.

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
- [ ] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
```
root@a5af371f7cac:/app# pip freeze
amqp==5.2.0
billiard==4.2.1
celery==5.4.0
click==8.1.7
click-didyoumean==0.3.1
click-plugins==1.1.1
click-repl==0.3.0
kombu==5.4.2
prompt_toolkit==3.0.48
python-dateutil==2.9.0.post0
redis==5.2.0
six==1.16.0
tzdata==2024.2
vine==5.1.0
wcwidth==0.2.13
```
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.
```
$ docker --version
Docker version 27.1.2, build d01f264

$ docker compose version
Docker Compose version v2.29.1

$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

## Optional Debugging Information
- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.4.0 (opalescent)

```
root@a5af371f7cac:/app# celery -A tasks report

software -> celery:5.4.0 (opalescent) kombu:5.4.2 py:3.11.10
            billiard:4.2.1 redis:5.2.0
platform -> system:Linux arch:64bit
            kernel version:6.10.4-200.fc40.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis/

broker_url: 'redis://redis:6379//'
result_backend: 'redis://redis/'
deprecated_settings: None
```

# Steps to Reproduce
I've setup a minimal docker-compose project with clear steps to reproduce here: https://github.com/nielsreijers/celery-docker-multi-bug

Output of `docker compose up multi` (which does a `celery -A tasks multi start worker_a`):
```
celery-docker-multi-bug-python-multi  | celery multi v5.4.0 (opalescent)
celery-docker-multi-bug-python-multi  | > Starting nodes...
celery-docker-multi-bug-python-multi  |         > worker_a@a5af371f7cac: OK
```

Output of `docker compose run client`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py", line 287, in _wait_for_pending
    for _ in self.drain_events_until(
  File "/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py", line 52, in drain_events_until
    raise socket.timeout()
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/client.py", line 4, in <module>
    print(add.delay(2,40).get(timeout=1))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 251, in get
    return self.backend.wait_for_pending(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py", line 221, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py", line 293, in _wait_for_pending
    raise TimeoutError('The operation timed out.')
celery.exceptions.TimeoutError: The operation timed out.
```

# Expected Behavior
`celery multi start` should start a worker, which should start serving tasks.

# Actual Behavior
The behaviour depends on the OS.
- Mac and Ubuntu: works as expected
- Fedora and Arch: the worker starts but doesn't respond (tested on 2 Fedora machines and a single Arch machine)

The output says it's starting nodes, and a `ps | grep celery` shows it's running:
```
1732651 ?        R      0:29      \_ /usr/local/bin/python3.11 -m celery -A tasks worker --detach -n worker_a@a5af371f7cac --pidfile=/var/run/celery/worker_a.pid --logfile=/var/log/celery/worker_a%I.log --executable=/usr/local/bin/python3.11
```

But it seems to be stuck in a loop, taking 100% cpu on one core, and it doesn't respond. Doing another `docker compose run client` in the second terminal now gives an error: `celery.exceptions.TimeoutError: The operation timed out.`

The problem is in forking the `--detach` worker, because when I start it with `C_FAKEFORK=1` it works (see `docker compose up multi-fakefork`).

**Comment by corrosive4354** [comment]
As you mentioned, using C_FAKEFORK=1 can solve the problem. This is because C_FAKEFORK will make Celery use a fake fork mechanism to avoid the real fork operation in Docker. You can set the environment variable in docker-compose.yml to use this option:

services:
celery:
environment:
- C_FAKEFORK=1

If it still doesn't work, it may be a compatibility issue between docker and mac. You can use [servbay](servbay.com) instead of docker, which is more professional on mac and has fewer bugs.

**Comment by nielsreijers** [comment]
The comment about FAKEFORK was meant as a hint as to where the problem might be, not as a solution since it behaves differently.
