### ISSUE TITLE
Connect Celery to Redis cluster

### ISSUE THREAD

**Issue by radeklos** [celery/celery#9436]
Hey, I'm facing an issue with connecting to Redis Cluster (using SSL) using Celery '5.4.0'. I have this configuration:

```python
app = Celery(
    'tasks',
    broker=f'rediss://:{password}@{host}:{port}/0',
    backend=f'rediss://:{password}@{host}:{port}/0',
    broker_use_ssl = {
        'ssl_cert_reqs': ssl.CERT_NONE
    },
    redis_backend_use_ssl={
        'ssl_cert_reqs': ssl.CERT_NONE
    },
    cluster=True,
)
app.send_task("xxx", queue="xxx")
```

But I'm getting following exception:
```
Traceback (most recent call last):
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/connection.py", line 556, in _ensured
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/messaging.py", line 202, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/messaging.py", line 202, in <listcomp>
    [maybe_declare(entity) for entity in declare]
     ^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/messaging.py", line 107, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/common.py", line 113, in maybe_declare
    return _maybe_declare(entity, channel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/common.py", line 153, in _maybe_declare
    entity.declare(channel=channel)
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/entity.py", line 617, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/entity.py", line 626, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/entity.py", line 655, in queue_declare
    ret = channel.queue_declare(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 538, in queue_declare
    return queue_declare_ok_t(queue, self._size(queue), 0)
                                     ^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/transport/redis.py", line 1000, in _size
    sizes = pipe.execute()
            ^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1500, in execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1501, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1364, in _execute_transaction
    response = self.parse_response(connection, "_")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1432, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: CROSSSLOT Keys in request don't hash to the same slot

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/service-name/.venv/lib/python3.11/site-packages/celery/app/base.py", line 801, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/service-name/.venv/lib/python3.11/site-packages/celery/app/amqp.py", line 518, in send_task_message
    ret = producer.publish(
          ^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/messaging.py", line 186, in publish
    return _publish(
           ^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/connection.py", line 553, in _ensured
    with self._reraise_as_library_errors():
  File "/root/.local/share/pdm/python/cpython@3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: CROSSSLOT Keys in request don't hash to the same slot
```

I tried to change configuration of cluster to False and I get:
```
Traceback (most recent call last):
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1364, in _execute_transaction
    response = self.parse_response(connection, "_")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1432, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/connection.py", line 536, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/connection.py", line 556, in _ensured
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/messaging.py", line 202, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/messaging.py", line 202, in <listcomp>
    [maybe_declare(entity) for entity in declare]
     ^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/messaging.py", line 107, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/common.py", line 113, in maybe_declare
    return _maybe_declare(entity, channel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/common.py", line 153, in _maybe_declare
    entity.declare(channel=channel)
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/entity.py", line 617, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/entity.py", line 626, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/entity.py", line 655, in queue_declare
    ret = channel.queue_declare(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 538, in queue_declare
    return queue_declare_ok_t(queue, self._size(queue), 0)
                                     ^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/transport/redis.py", line 1000, in _size
    sizes = pipe.execute()
            ^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1500, in execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1501, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1367, in _execute_transaction
    raise errors[0][1]
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1357, in _execute_transaction
    self.parse_response(connection, "_")
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 1432, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/redis/connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (LLEN xxx) of pipeline caused error: MOVED 4038 redis-cluster-url

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/service-name/.venv/lib/python3.11/site-packages/celery/app/base.py", line 801, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/service-name/.venv/lib/python3.11/site-packages/celery/app/amqp.py", line 518, in send_task_message
    ret = producer.publish(
          ^^^^^^^^^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/messaging.py", line 186, in publish
    return _publish(
           ^^^^^^^^^
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/connection.py", line 553, in _ensured
    with self._reraise_as_library_errors():
  File "/root/.local/share/pdm/python/cpython@3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/service-name/.venv/lib/python3.11/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Command # 1 (LLEN xxx) of pipeline caused error: MOVED 4038 redis-cluster-url
```

Don't you know how can I configure Celery app to send message to queue?

**Comment by grahamlyons** [comment]
It looks like Celery doesn't support clustered Redis out of the box. There are some discussions, solutions and workarounds linked from #8968

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this looks like a duplicate of the long-standing Redis-Cluster-as-broker feature request, not a new bug.

Evidence:
- The traceback shows `redis.exceptions.ResponseError: CROSSSLOT Keys in request don't hash to the same slot`, raised from `kombu/transport/redis.py` `Channel._size` (around L1015–1022 in kombu 5.6.2), where the transport issues a single `pipe.execute()` that runs `llen` against one `_q_for_pri()` key per priority step. Since each priority key gets a distinct `{queue}{sep}{pri}` suffix, they hash to different cluster slots, and Redis Cluster rejects the pipeline with CROSSSLOT. There is no `cluster=True` knob on the `Celery()` constructor — passing it silently does nothing.
- The canonical tracker for this is [#2852 — FR: Integrate Redis Cluster as broker](https://github.com/celery/celery/issues/2852) (open since 2015, labeled Feature Request). [@grahamlyons' comment above](https://github.com/celery/celery/issues/9436#issuecomment-2503826225) also points to [#8968](https://github.com/celery/celery/issues/8968) ("how to use redis cluster as backend"), both still open.
- The upstream blocker is on the transport layer: [celery/kombu#526](https://github.com/celery/kombu/issues/526) ("FR: Integrate Redis Cluster as transporter"). Celery's Redis broker is implemented in kombu, so the cluster-aware slot routing has to land there first.
- Celery's own Redis broker docs ([`docs/getting-started/backends-and-brokers/redis.rst`](https://github.com/celery/celery/blob/main/docs/getting-started/backends-and-brokers/redis.rst)) document Sentinel mode via `master_name` / `sentinel_kwargs` but never mention Redis Cluster — consistent with cluster mode not being supported.

If I'm wrong and you're hitting CROSSSLOT against a non-cluster Redis (e.g. just a Sentinel/HA setup), point me at the deployment shape and I'll dig further. Otherwise this is the same ask as #2852 and would benefit from being consolidated there.

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the cross-references and the kombu code path above were verified manually against the linked source.*

**Comment by auvipy** [comment]
closing as duplicate
