### ISSUE TITLE
pydantic=true is not effective

### ISSUE THREAD

**Issue by yuanjie-ai** [celery/celery#9442]
TypeError: Object of type Request is not JSON serializable

During handling of the above exception, another exception occurred:

**Comment by yuanjie-ai** [comment]
```
class Request(BaseModel):
    method: str = "GET"
    url: str = "https://api.chatfire.cn/"

    class Config:
        frozen = True
@shared_task(pydantic=True)
def do_pydantic_task(request: Request) -> Request:
    logger.debug(request)
    return request
```
![Uploading image.png…]()

**Comment by yuanjie-ai** [comment]
![image](https://github.com/user-attachments/assets/e1eea3e1-fbe0-447f-9c23-c327c129a10d)

**Comment by yuanjie-ai** [comment]
It should be a Basemodel, but it's still a dictionary inside

**Comment by Nusnus** [comment]
@mathiasertl

**Comment by tobiasge** [comment]
I'm seeing a similar error with version `5.5.0rc5`.

```python
class NotificationTypeEnum(str, Enum):
    DANGER = "danger"
    SUCCESS = "success"
    WARNING = "warning"


class NotificationData(BaseModel):
    message: str
    title: str
    type: NotificationTypeEnum = NotificationTypeEnum.SUCCESS
```

```python
@shared_task(pydantic=True)
def send_notification(notification_data: NotificationData, user_id: int):
   ...
```

```´
>>> from ... import NotificationData
>>> from ... import send_notification
>>> nd = NotificationData(message="Testnachricht", title="Testtitel")
>>> send_notification.delay(nd, 1)
Traceback (most recent call last):
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/utils/json.py", line 63, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
  File "/pythonpath/lib/python3.13/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "/pythonpath/lib/python3.13/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/pythonpath/lib/python3.13/json/encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/utils/json.py", line 47, in default
    return super().default(o)
           ~~~~~~~~~~~~~~~^^^
  File "/pythonpath/lib/python3.13/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type NotificationData is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/projectpath/.venv/lib/python3.13/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/projectpath/.venv/lib/python3.13/site-packages/celery/app/task.py", line 601, in apply_async
    return app.send_task(
           ~~~~~~~~~~~~~^
        self.name, args, kwargs, task_id=task_id, producer=producer,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        **options
        ^^^^^^^^^
    )
    ^
  File "/projectpath/.venv/lib/python3.13/site-packages/celery/app/base.py", line 922, in send_task
    amqp.send_task_message(P, name, message, **options)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectpath/.venv/lib/python3.13/site-packages/celery/app/amqp.py", line 523, in send_task_message
    ret = producer.publish(
        body,
    ...<8 lines>...
        **properties
    )
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/messaging.py", line 178, in publish
    body, content_type, content_encoding = self._prepare(
                                           ~~~~~~~~~~~~~^
        body, serializer, content_type, content_encoding,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        compression, headers)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/messaging.py", line 280, in _prepare
    body) = dumps(body, serializer=serializer)
            ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/serialization.py", line 219, in dumps
    with _reraise_errors(EncodeError):
         ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/pythonpath/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/serialization.py", line 45, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/exceptions.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/utils/json.py", line 63, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
  File "/pythonpath/lib/python3.13/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "/pythonpath/lib/python3.13/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/pythonpath/lib/python3.13/json/encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "/projectpath/.venv/lib/python3.13/site-packages/kombu/utils/json.py", line 47, in default
    return super().default(o)
           ~~~~~~~~~~~~~~~^^^
  File "/pythonpath/lib/python3.13/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
kombu.exceptions.EncodeError: Object of type NotificationData is not JSON serializable
```

**Comment by mathiasertl** [comment]
Hi,

As noted in the docs, the current implementation only covers the task side. The task function will receive a model, but the caller itself still has to dump it.

Kr, mat

**Comment by tobiasge** [comment]
I think it would be a nice improvement if the caller side was also handled automatically.

**Comment by mathiasertl** [comment]
Yes, absolutely! I unfortunately do not have time to implement it on my own. I'm happy to help review a pull request!

Kr, Mat

**Comment by auvipy** [comment]
we have this documented, right?

**Comment by mathiasertl** [comment]
Yes: https://github.com/celery/celery/blob/main/docs%2Fuserguide%2Ftasks.rst#L808-L811

**Comment by johannesloibl** [comment]
Same problem here:

![Image](https://github.com/user-attachments/assets/b1a2cac0-97cb-48d0-90a8-98553b1deffb)

```
AssertionError: Argument must be of type ArgModel, but got {'source_project': 'A
```
Using celery v5.5.0

**Comment by mathiasertl** [comment]
This is not the same problem as above, this really looks like an actual issue. 

Can you post a snippet that allows me to reproduce the issue?

**Comment by auvipy** [comment]
checking the codes in the issue, it seems to me that the users are not serializing all of their objects properly so the issues. but may be I could be wrong. do we have this documented that the users have to json dump / serialize the objects by themselves?

**Comment by mathiasertl** [comment]
Yes, there even is a big warning!

**Comment by sk-** [comment]
@auvipy Note that this is a big problem for users of [celery-types](https://github.com/sbdchd/celery-types), because the decorator is currently typed to return a Task with the same parameters as the decorated function (arguably a celery-types issue). However, IMO this breaks the expectation that a celery task can be called without changes as a regular python function (see [Calling Tasks / Basics](https://docs.celeryq.dev/en/main/userguide/calling.html#basics))

Unfortunately, In python there is no machinery in place to selectively modify function parameters in type stubs. However, the stubs could special case the case when the decorated function receives just one single argument which is a subclass of `BaseModel`.

<img width="566" height="187" alt="Image" src="https://github.com/user-attachments/assets/884b71fe-b395-4256-90e7-3632288d209f" />

**Comment by auvipy** [comment]
what we need to do to fix the remaining part?

**Comment by sk-** [comment]
We could modify `apply_async`  as follows:

```python
def apply_async(self, args=None, kwargs=None, ...):
    ...
    # After serializer resolution, before send_task
    if getattr(self, 'pydantic', False):
        serializer = options.get('serializer') or app.conf.task_serializer
        # Not sure about this
        # We may want to always serialize as json, as on the receiving side we are going
        # to decode it anyways so it should roundtrip, regardless of the mode
        mode = "json" if serializer == "json" else "python"
        args = _dump_pydantic_args(args, mode)
        kwargs = _dump_pydantic_kwargs(kwargs, mode)
    
    return app.send_task(self.name, args, kwargs, ...)

def _dump_pydantic_value(value, mode="json"):
    if isinstance(value, pydantic.BaseModel):
        return value.model_dump(mode=mode)
    return value

def _dump_pydantic_args(args, mode="json"):
    if not args:
        return args
    return tuple(_dump_pydantic_value(a, mode) for a in args)

def _dump_pydantic_kwargs(kwargs, mode="json"):
    if not kwargs:
        return kwargs
    return {k: _dump_pydantic_value(v, mode) for k, v in kwargs.items()}
```

**Comment by sk-** [comment]
For anyone wanting to use this in the meantime, you can define a custom task as following

```python
from typing import Any

from celery import Task
from pydantic import BaseModel


def _dump_pydantic_args(args: tuple[Any, ...]) -> tuple[Any, ...]:
    return tuple(
        arg.model_dump(mode="json") if isinstance(arg, BaseModel) else arg
        for arg in args
    )


def _dump_pydantic_kwargs(kwargs: dict[str, Any]) -> dict[str, Any]:
    return {
        key: value.model_dump(mode="json") if isinstance(value, BaseModel) else value
        for key, value in kwargs.items()
    }


class PydanticTask(Task):
    def apply_async(self, args=None, kwargs=None, **options):
        if args:
            args = _dump_pydantic_args(tuple(args))
        if kwargs:
            kwargs = _dump_pydantic_kwargs(kwargs)

        return super().apply_async(args, kwargs, **options)
```

**Comment by false200** [comment]
Same issue here. `pydantic=True` validates on the worker but `.delay(Model(...))` still fails at serialize time unless you `model_dump()` first, and `.get()` gives you a dict back.

I put together a small workaround for our stack: [queuebridge](https://github.com/false200/queuebridge). Registers a Kombu serializer so you can pass Pydantic models on enqueue, and `typed_result()` so `.get()` returns a model again.

```python
from queuebridge.celery import register_queuebridge, typed_result

register_queuebridge(app)

@app.task(pydantic=True)
def process(order: OrderCreate) -> OrderResult:
    return OrderResult(id=order.id, status="ok")

ar = process.delay(OrderCreate(id=1, sku="ABC"))
result = typed_result(ar, OrderResult).get()
```

Docs: https://queuebridge.readthedocs.io

I built this to work around the same problem. Sharing here in case it helps anyone else.
