### ISSUE TITLE
Retry failing immediately.

### ISSUE THREAD

**Issue by erikcw** [celery/celery#947]
I'm using a distributed lock (redis) to prevent race conditions when calling a 3rd party API from my celery tasks.  If the lock cannot be required, I want my task to retry later so that I don't keep workers busy blocking for the lock.

However, Celery (3.0.7) is failing the tasks immediately if the lock cannot be acquired instead of retrying.  The traceback indicates that "called_directly" is set to True -- even though I'm executing the task using the delay() method in ipython.

```
#Ipython
In [1]: from portal import tasks

In [2]: lock, have_lock = tasks.acquire_lock("divider_lock", timeout=120)

In [3]: tasks.divider2.delay(10, 2)                                                                                                                                                                         
Out[3]: <AsyncResult: 72a890aa-0ae1-46cf-8075-0a74143b0514
```

```
# tasks.py

def get_redis():
    """
    Helper function to get a Redis instance.
    """
    redis_url = urlparse.urlsplit(settings.REDIS_URL)
    r = redis.StrictRedis(host=redis_url.hostname, port=redis_url.port, password=redis_url.password)
    return r


class MutexException(Exception):
    pass

def acquire_lock(key, timeout):
    lock = get_redis().lock("divider_lock", timeout=120)
    have_lock = lock.acquire(blocking=False)
    if not have_lock:
        raise MutexException("Lock could not be aquired.")
    return lock, have_lock


@task(rate_limit="1/s")
def divider2(a, b):
    """
    Useful for debugging.  Can create an exception by diving 1/0.
    """
    have_lock = False
    try:
        lock, have_lock = acquire_lock("divider_lock", timeout=120)
        # task logic
        time.sleep(round(a/b))
        return a/b
    except MutexException, exc:
        divider2.retry(exc=exc, countdown=121)
        #divider2.retry(args=divider2.request.args, countdown=121)
    finally:
         if have_lock:
             lock.release()
```

Traceback

```
Traceback (most recent call last): File "/app/lib/python2.7/site-packages/celery/task/trace.py", line 212, in trace_task R = retval = fun(*args, **kwargs) File "/app/lib/python2.7/site-packages/newrelic-1.4.0.137/newrelic/api/object_wrapper.py", line 166, in __call__ self._nr_instance, args, kwargs) File "/app/lib/python2.7/site-packages/newrelic-1.4.0.137/newrelic/api/background_task.py", line 88, in wrapper return wrapped(*args, **kwargs) File "/app/lib/python2.7/site-packages/newrelic-1.4.0.137/newrelic/api/object_wrapper.py", line 166, in __call__ self._nr_instance, args, kwargs) File "/app/lib/python2.7/site-packages/newrelic-1.4.0.137/newrelic/api/background_task.py", line 74, in wrapper return wrapped(*args, **kwargs) File "/app/lib/python2.7/site-packages/celery/app/task.py", line 315, in __call__ return self.run(*args, **kwargs) File "/app/portal/tasks.py", line 55, in divider2 divider2.retry(args=divider2.request.args, countdown=121) File "/app/lib/python2.7/site-packages/celery/app/task.py", line 531, in retry maybe_reraise() File "/app/portal/tasks.py", line 49, in divider2 lock, have_lock = acquire_lock("divider_lock", timeout=120) File "/app/portal/tasks.py", line 32, in acquire_lock raise MutexException("Lock could not be aquired.") MutexException: Lock could not be aquired.
```

**Comment by rajendrakrp** [comment]
Is this resolved? Having exact issue in 3.0.21. Thanks..

**Comment by residentsummer** [comment]
Sorry for reviving this old thread, but I hope this will be useful for the people who'll find it like me today.

Had the same problem on celery 3.1.6. The key is setting `bind=True` for the task you're going to retry. Otherwise it doesn't know neither `args`/`kwargs` (which means that you can't simply `retry()`), nor actual `retries` count. And `called_directly` is always `True`, as mentioned by the others.

I guess the problem arises when we were calling retry by task (== func) name, which means dealing with some kind of a task 'singleton' instead of currently executing one => default/uninitialized request context and broken retry.

**Comment by PMickael** [comment]
Try to update to 3.1.8 and let us know if there is always a problem

**Comment by residentsummer** [comment]
Just checked with 3.1.18 (from pip) - it's all the same :(

**Comment by thedrow** [comment]
@PMickael Can we reopen the issue please?
