### ISSUE TITLE
gevent: AMQP backend and large chords causes rabbitmq to drop AMQP connection due to bad payload

### ISSUE THREAD

**Issue by cyounkins** [celery/celery#960]
Celery version 3.0.8 using rabbitmq v2.8.5, kombu 2.4.4 and mongodb for tombstones.

This was the first attempt at the chord_unlock for a group of 24,012 tasks.

It's unclear to me if this is a bug in kombu or celery. Let me know if I need to transfer it the kombu issues.

```
=ERROR REPORT==== 1-Sep-2012::19:06:34 ===
closing AMQP connection <0.213.0> (127.0.0.1:54731 -> 127.0.0.1:5672):
{bad_payload,3,1,131064,
             <<45,52,48,56,57,45,98,57,55,52,45,52,48,102,50,48,57,52,57,101,
               99,101,50,39,44,32,39,55,100,52,55,97,100,100,51,45,55,56,100,
               48,45,52,48,55,55,45,57,57,48,51,45,50,99,102,97,98,100,100,49,
               56,99,57,54,39,44,32,39,100,100,50,97,97,57,49,54,45,53,53,100,
               50,45,52,52,52,50,45,57,50,55,97,45,53,57,102,100,102,48,102,
.... (many many many similar lines)

               100,56,50,50,54,57,100,98,49,101,39,44,32,39,55,98,101,102,98,
               55,55,99,45,49,99,54,99,45,52,56,55,57,45,56,50,52,54,45,99,51,
               99,55,57,56,97,100,100,50,56,100,39,44,32,39,51,53,49,53,101,
               49,50,99,45,56,56,102,102,45,52,55,57>>}

=INFO REPORT==== 1-Sep-2012::19:06:35 ===
closing AMQP connection <0.222.0> (127.0.0.1:54732 -> 127.0.0.1:5672)
(END) 
```

```
[2012-09-01 19:06:34,714: INFO/MainProcess] Task download_image[34f43be8-366e-409b-be71-dc93e9461b10] succeeded in 8.24139285088s: [u'2ba4
7506fe9dc3dcfc0f7eca8bcceb17/2000-Cadil...
[2012-09-01 19:06:34,726: DEBUG/MainProcess] Start from server, version: 8.0, properties: {u'information': u'Licensed under the MPL.  See 
http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2012 VMware, Inc.', u'capabilities': {}, u'platform
': u'Erlang/OTP', u'version': u'2.8.5'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2012-09-01 19:06:34,727: DEBUG/MainProcess] Open OK! known_hosts []
[2012-09-01 19:06:34,729: DEBUG/MainProcess] using channel_id: 1
[2012-09-01 19:06:34,731: DEBUG/MainProcess] Channel open
[2012-09-01 19:06:34,758: DEBUG/MainProcess] Closed channel #1
[2012-09-01 19:06:34,771: INFO/MainProcess] Got task from broker: celery.chord_unlock[20d02f0c-72be-434d-9d77-ee491c12c65f] eta:[2012-09-0
1 19:07:04.731612-04:00]
[2012-09-01 19:06:34,790: ERROR/MainProcess] Consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/celery/worker/consumer.py", line 369, in start
    self.consume_messages()
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/celery/worker/consumer.py", line 842, in consume_messages
    self.connection.drain_events(timeout=10.0)
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/connection.py", line 197, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/transport/amqplib.py", line 327, in drain_events
    return connection.drain_events(**kwargs)
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/transport/amqplib.py", line 161, in drain_events
    chanmap, None, timeout=timeout)
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/transport/amqplib.py", line 219, in _wait_multiple
    channel, method_sig, args, content = read_timeout(timeout)
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/transport/amqplib.py", line 193, in read_timeout
    return self.method_reader.read_method()
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/amqplib/client_0_8/method_framing.py", line 221, in read_method
    raise m
IOError: Socket closed
[2012-09-01 19:06:34,876: DEBUG/MainProcess] Consumer: Re-establishing connection to the broker...
[2012-09-01 19:06:34,877: DEBUG/MainProcess] Consumer: Heart: Going into cardiac arrest...
[2012-09-01 19:06:34,877: DEBUG/MainProcess] Consumer: Cancelling task consumer...
[2012-09-01 19:06:34,878: DEBUG/MainProcess] Consumer: Shutting down event dispatcher...
[2012-09-01 19:06:34,878: DEBUG/MainProcess] Consumer: Cancelling broadcast consumer...
[2012-09-01 19:06:34,878: ERROR/MainProcess] Unrecoverable error: AssertionError("This event is already used by another greenlet: (<greenlet.greenlet object at 0x2f6f370>, timeout('timed out',))",)
Traceback (most recent call last):
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/celery/worker/__init__.py", line 353, in start
    component.start()
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/celery/worker/consumer.py", line 368, in start
    self.reset_connection()
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/celery/worker/consumer.py", line 694, in reset_connection
    self.stop_consumers()
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/celery/worker/consumer.py", line 621, in stop_consumers
    self.maybe_conn_error(self.broadcast_consumer.cancel)
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/celery/worker/consumer.py", line 570, in maybe_conn_error
    fun()
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/messaging.py", line 356, in cancel
    cancel(tag)
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/transport/amqplib.py", line 297, in basic_cancel
    return super(Channel, self).basic_cancel(consumer_tag, **kwargs)
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/amqplib/client_0_8/channel.py", line 1791, in basic_cancel
    (60, 31),    # Channel.basic_cancel_ok
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/amqplib/client_0_8/abstract_channel.py", line 95, in wait
    self.channel_id, allowed_methods)
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/amqplib/client_0_8/connection.py", line 202, in _wait_method
    self.method_reader.read_method()
  File "/srv/autoref/virtual_env/lib/python2.6/site-packages/amqplib/client_0_8/method_framing.py", line 221, in read_method
    raise m
AssertionError: This event is already used by another greenlet: (<greenlet.greenlet object at 0x2f6f370>, timeout('timed out',))
[2012-09-01 19:06:34,919: DEBUG/MainProcess] Stopping celery.worker.consumer.BlockingConsumer...
[2012-09-01 19:06:34,919: DEBUG/MainProcess] Consumer: Stopping consumers...
[2012-09-01 19:06:34,919: DEBUG/MainProcess] Stopping celery.concurrency.gevent.TaskPool...
[2012-09-01 19:06:34,919: INFO/MainProcess] Task celery.chord_unlock[20d02f0c-72be-434d-9d77-ee491c12c65f] retry: Retry in 30s
[2012-09-01 19:06:34,920: DEBUG/MainProcess] Consumer: Closing consumer channel...
[2012-09-01 19:06:34,920: DEBUG/MainProcess] Consumer: Waiting for broadcast thread to shutdown...
[2012-09-01 19:06:35,028: DEBUG/MainProcess] Closed channel #1
[2012-09-01 19:06:35,079: WARNING/MainProcess] Traceback (most recent call last):
[2012-09-01 19:06:35,080: WARNING/MainProcess] File "core.pyx", line 132, in gevent.core.__event_handler (gevent/core.c:1404)
[2012-09-01 19:06:35,168: WARNING/MainProcess] File "/srv/autoref/virtual_env/lib/python2.6/site-packages/gevent/socket.py", line 150, in _wait_helper
[2012-09-01 19:06:35,180: WARNING/MainProcess] current.switch(ev)
[2012-09-01 19:06:35,180: WARNING/MainProcess] File "/srv/autoref/virtual_env/lib/python2.6/site-packages/celery/worker/consumer.py", line 686, in _green_pidbox_node
[2012-09-01 19:06:35,181: WARNING/MainProcess] pass
[2012-09-01 19:06:35,181: WARNING/MainProcess] File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/messaging.py", line 326, in __exit__
[2012-09-01 19:06:35,181: WARNING/MainProcess] self.cancel()
[2012-09-01 19:06:35,182: WARNING/MainProcess] File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/messaging.py", line 356, in cancel
[2012-09-01 19:06:35,182: WARNING/MainProcess] cancel(tag)
[2012-09-01 19:06:35,182: WARNING/MainProcess] File "/srv/autoref/virtual_env/lib/python2.6/site-packages/kombu/transport/amqplib.py", line 297, in basic_cancel
[2012-09-01 19:06:35,183: WARNING/MainProcess] return super(Channel, self).basic_cancel(consumer_tag, **kwargs)
[2012-09-01 19:06:35,183: WARNING/MainProcess] File "/srv/autoref/virtual_env/lib/python2.6/site-packages/amqplib/client_0_8/channel.py", line 1791, in basic_cancel
[2012-09-01 19:06:35,183: WARNING/MainProcess] (60, 31),    # Channel.basic_cancel_ok
[2012-09-01 19:06:35,184: WARNING/MainProcess] File "/srv/autoref/virtual_env/lib/python2.6/site-packages/amqplib/client_0_8/abstract_channel.py", line 97, in wait
[2012-09-01 19:06:35,184: WARNING/MainProcess] return self.dispatch_method(method_sig, args, content)
[2012-09-01 19:06:35,184: WARNING/MainProcess] File "/srv/autoref/virtual_env/lib/python2.6/site-packages/amqplib/client_0_8/abstract_channel.py", line 115, in dispatch_method
[2012-09-01 19:06:35,184: WARNING/MainProcess] return amqp_method(self, args)
[2012-09-01 19:06:35,185: WARNING/MainProcess] File "/srv/autoref/virtual_env/lib/python2.6/site-packages/amqplib/client_0_8/channel.py", line 1818, in _basic_cancel_ok
[2012-09-01 19:06:35,185: WARNING/MainProcess] del self.callbacks[consumer_tag]
[2012-09-01 19:06:35,185: WARNING/MainProcess] KeyError: u'2'
[2012-09-01 19:06:35,186: WARNING/MainProcess] Failed to execute callback for event fd=13 READ flags=INIT
  cb  = <function _wait_helper at 0x2797aa0>
  arg = None
[2012-09-01 19:06:35,186: DEBUG/MainProcess] Consumer: Closing broker connection...
```

**Comment by ask** [comment]
Closing this, please use the redis result backend if you have lots of chord members.  We are unlikely to have the resources to complete this task for AMQP.
