### ISSUE TITLE
Memory leak on sending result error

### ISSUE THREAD

**Issue by maciej-gol** [celery/celery#966]
Hey,

I've recently noticed that if a task fails to send task results, the associated worker's RAM usage skyrockets (about 10x) until it's killed.
Corresponding traceback:

```
[2012-09-07 10:42:59,814: ERROR/MainProcess] Task test[f30e8c98-26a8-45c8-8092-ebab28388c26] raised exception: <MaybeEncodingError: Error sending result: '"<ExceptionInfo: ObjectDoesNotExist('TestClass matching query does not exist.',)>"'. Reason: ''PicklingError("Can\'t pickle <class \'models.DoesNotExist\'>: attribute lookup models.DoesNotExist failed",)''.>
Traceback (most recent call last):
  File "/virtualenv/local/lib/python2.7/site-packages/billiard/pool.py", line 286, in worker
    put((READY, (job, i, result)))
  File "/virtualenv/local/lib/python2.7/site-packages/billiard/queues.py", line 377, in put
    return send(obj)
MaybeEncodingError: Error sending result: '"<ExceptionInfo: ObjectDoesNotExist('TestClass matching query does not exist.',)>"'. Reason: ''PicklingError("Can\'t pickle <class \'models.DoesNotExist\'>: attribute lookup models.DoesNotExist failed",)''.
```

**Comment by jayapal** [comment]
Did you solved this issue?

**Comment by maciej-gol** [comment]
Actually, I don't remember now what the cause was. If it doesn't occur nowadays then I think it's been fixed.

**Comment by jayapal** [comment]
thanks for your response. But I am facing the same issue now. Can you please have a look @ #2539 
Let me know if you can help me?

**Comment by maciej-gol** [comment]
What's your celery version?

**Comment by jayapal** [comment]
Celery 3.0.22 
I mentioned there?

**Comment by jayapal** [comment]
Did you check? Any possible to help me out?

**Comment by maciej-gol** [comment]
Your issue has little to do with this one. The point in this one is that
the RAM usage was rising, the point in yours is the `MySQL has gone away`
exception.

2015-03-18 9:38 GMT+01:00 jayapal <notifications@github.com>:

**Comment by jayapal** [comment]
How you are saying that RAM usage was high? is there any way to look in to that?
