### ISSUE TITLE
Error in timer: ValueError('Not naive datetime (tzinfo is already set)',) 

### ISSUE THREAD

**Issue by ju-popov** [celery/celery#983]
After upgrade to `celery==3.0.7` and `django-celery==3.0.6` (from 2.x.x) I get this error in log. I think it's related to celerycam and Django setting USE_TZ = True.

`[2012-09-17 17:20:16,001: ERROR/MainProcess] Error in timer: ValueError('Not naive datetime (tzinfo is already set)',) Traceback (most recent call last):
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/celery/utils/timer2.py", line 92, in apply_entry entry()
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/celery/utils/timer2.py", line 48, in _call_ return self.fun(*self.args, **self.kwargs)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/celery/utils/timer2.py", line 149, in _reschedules return fun(*args, **kwargs)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/celery/events/snapshot.py", line 71, in capture self.state.freeze_while(self.shutter, clear_after=self.clear_after)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/celery/events/state.py", line 225, in freeze_while return fun(*args, **kwargs)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/celery/events/snapshot.py", line 68, in shutter self.on_shutter(self.state)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/django/db/transaction.py", line 209, in inner return func(*args, **kwargs)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/djcelery/snapshot.py", line 139, in on_shutter self._autocommit(_handle_tasks)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/djcelery/snapshot.py", line 115, in _autocommit fun()
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/djcelery/snapshot.py", line 133, in _handle_tasks self.handle_task(task)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/djcelery/snapshot.py", line 74, in handle_task "eta": maybe_make_aware(maybe_iso8601(task.eta)),
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/djcelery/utils.py", line 74, in maybe_make_aware return make_aware(value)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/djcelery/utils.py", line 52, in make_aware value = timezone.make_aware(value, timezone.utc) 
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/django/utils/timezone.py", line 269, in make_aware return timezone.localize(value, is_dst=None)
File "/opt/tixgate/tg_virtenv/lib/python2.7/site-packages/pytz/__init__.py", line 231, in localize raise ValueError('Not naive datetime (tzinfo is already set)') ValueError: Not naive datetime (tzinfo is already set)`

**Comment by SubrahmanyaG** [comment]
This is not a celery issue. You are trying to set the timezone for date_time which already has a timezone. 
Use `replace` and `astimezone` functions.
```
local_tz = pytz.timezone(zone)
    local_dt = d_time.replace(tzinfo=pytz.utc).astimezone(local_tz)
```

**Comment by mohabamroo** [comment]
> This is not a celery issue. You are trying to set the timezone for date_time which already has a timezone. Use `replace` and `astimezone` functions.
> 
> ```
> local_tz = pytz.timezone(zone)
>     local_dt = d_time.replace(tzinfo=pytz.utc).astimezone(local_tz)
> ```

thank you!
this works properly
using `.replace` alone without `.astimezone` yields random results
